(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.bgImg = function() {
	this.initialize(img.bgImg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.dev1 = function() {
	this.initialize(img.dev1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,66,300);


(lib.shadow = function() {
	this.initialize(img.shadow);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,258,554);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.urText = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Al1DpIAAhQIAKAAIAAAIQADgEAFgDQAGgDAEAAQAHAAAHAEQAGAEADAGQADAGAAAJQAAAIgDAGQgEAHgFADQgGAEgIAAQgFAAgFgDQgEgCgEgFIAAAjgAljCjQgEADgCAEQgCAGAAAEQAAAEACAFQACAEAEADQAEACAFAAQAEAAAEgCQAEgDACgEQACgEABgFQgBgFgCgFQgCgEgEgDQgEgCgEAAQgFAAgEACgAsSDcIAAgOIgsAAIAAAOIgJAAIAAgXIAGAAQADgCAAgFQACgFAAgJIABgXIAqAAIAAAsIAIAAIAAAXgAsxCwIgCANIgDAIIAbAAIAAgjIgWAAgAM9DPIgDgDIgBgDIABgEIADgDIAEgBIADABIADADIABAEIgBADIgDADIgDABgAHADPIABgJIADAAQABAAAAAAQABAAABAAQAAAAABgBQAAAAAAAAIACgGIACgmIArAAIAAA1IgKAAIAAgsIgWAAIgDAiQgBAHgEACQgDADgHAAgAGRDMQgFgDgFgHQgDgGAAgIQAAgIADgHQAFgHAFgDQAGgEAJAAQAHAAAGAEQAHADADAHQAEAHAAAIQAAAIgEAGQgDAHgHADQgGAEgHAAQgIAAgHgEgAGXCkQgFACgCAEQgCAEAAAGQAAAFACAEQACAEAFADQADACAGAAQAFAAADgCQAEgDACgEQADgEAAgFQAAgGgDgEQgCgEgEgCQgEgDgEAAQgGAAgDADgADXDMQgGgEgEgGQgDgGAAgIQAAgIADgHQAEgGAGgEQAHgEAHAAQAJAAAGAEQAGAEAEAGQADAIAAAHQAAAGgDAIQgEAGgGAEQgHAEgIAAQgHAAgHgEgADdCkQgFADgCADQgCAEAAAGQAAAGACADQACAEAFADQAEACAEAAQAFAAAFgCQAEgDACgEQACgEAAgFQAAgGgCgEQgCgEgEgCQgFgDgFAAQgEAAgEADgAh7DMQgGgDgEgHQgDgGAAgIQAAgJADgGQADgGAHgEQAGgEAGAAQAFAAAFADQAGADACAEIAAgIIALAAIAAA1IgLAAIAAgIQgDAFgFACQgDADgHAAQgHAAgFgEgAh2CjQgDADgCAEQgCAGgBAEQABAEACAFQACAEADADQAEACAFAAQAFAAAEgCQAEgDACgEQACgEAAgFQAAgFgCgFQgCgDgEgEQgDgCgGAAQgFAAgEACgAjqDMQgFgDgFgHQgDgGAAgIQAAgIADgHQAEgGAGgEQAHgEAIAAQAHAAAGADQAGADAEAFIgHAHQgDgEgEgCQgEgCgFAAQgFAAgEADQgEACgCAEQgCAEgBAGQABAEACAFQABAEAFADQAEACAFAAQAEAAAFgCQAEgCADgDIAHAGQgEAFgFADQgHADgHAAQgJAAgGgEgAmrDMQgHgEgDgGQgEgGAAgIQAAgIAEgHQADgGAHgEQAGgEAIAAQAIAAAGAEQAHAEADAGQAEAIAAAHQAAAGgEAIQgDAGgHAEQgHAEgHAAQgHAAgHgEgAmlCkQgFADgCADQgCAEAAAGQAAAGACADQACAEAFADQADACAFAAQAFAAAEgCQAEgDACgEQACgEAAgFQAAgGgCgEQgCgEgEgCQgFgDgEAAQgEAAgEADgAsBDPIABgJIADAAQABAAAAAAQABAAABAAQAAAAABgBQAAAAABAAIABgGIACgmIArAAIAAA1IgKAAIAAgsIgXAAIgCAiQgCAHgDACQgEADgGAAgAMjDOIAAgnIgcAnIgKAAIAAg1IAKAAIAAAnIAcgnIAKAAIAAA1gALkDOIAAgmIgSAYIgHAAIgRgYIAAAmIgKAAIAAg1IAKAAIAVAcIAVgcIAKAAIAAA1gAKWDOIAAg1IAKAAIAAA1gAJ7DOIAAgXIgaAAIAAAXIgLAAIAAg1IALAAIAAAVIAaAAIAAgVIALAAIAAA1gAIvDOIAAgsIgTAAIAAgJIAwAAIAAAJIgSAAIAAAsgAIHDOIAAg1IAKAAIAAA1gAFtDOIAAgXIgbAAIAAAXIgKAAIAAg1IAKAAIAAAVIAbAAIAAgVIAKAAIAAA1gAENDOIAAg1IAYAAQAKAAAFAEQAFADAAAHQAAAEgCADQgBADgFACQAGABACAEQADACAAAGQgBAEgCADQgCADgEADQgEABgHAAgAEYDHIAOAAQAFAAADgCQADgCAAgEQABgIgMAAIgOAAgAEYCwIAMAAQAGAAACgCQADgCAAgEQAAgHgLAAIgMAAgACzDOIAAgsIgbAAIAAAsIgKAAIAAg1IAwAAIAAA1gABcDOIAAgUIgNAAIgMAUIgMAAIAOgVQgHgCgDgDQgDgEAAgGQAAgIAGgFQAFgEAKAAIAZAAIAAA1gABFCjQgCADAAAEQAAAEACACQAEACAFAAIAOAAIAAgRIgOAAQgFAAgEACgAAgDOIAAgXIgaAAIAAAXIgKAAIAAg1IAKAAIAAAVIAaAAIAAgVIALAAIAAA1gAgeDOIAAgXIgaAAIAAAXIgLAAIAAg1IALAAIAAAVIAaAAIAAgVIALAAIAAA1gAirDOIAAgsIgTAAIAAgJIAxAAIAAAJIgTAAIAAAsgAkNDOIAAgnIgcAnIgKAAIAAg1IAKAAIAAAnIAdgnIAJAAIAAA1gAnIDOIgPgVIgBgBIgCgBIgIAAIAAAXIgLAAIAAg1IALAAIAAAVIAKAAIABgCIAPgTIALAAIgSAZIATAcgAoGDOIAAgnIgcAnIgKAAIAAg1IAKAAIAAAnIAcgnIAKAAIAAA1gApnDOIAAg1IAZAAQAJAAAFAEQAFAEAAAGQAAADgBAEQgDADgEACQAFABADAEQADADAAAFQAAADgDAEQgCADgEADQgFABgGAAgApcDHIAOAAQAGAAADgCQACgCAAgEQAAgIgLAAIgOAAgApcCwIAMAAQAGAAACgCQADgCAAgEQAAgHgLAAIgMAAgAqZDOIAAgUIgNAAIgMAUIgMAAIAOgVQgGgCgDgDQgDgEAAgGQgBgIAGgFQAGgEAKAAIAZAAIAAA1gAqvCjQgDADAAAEQAAAEADACQAEACAEAAIAOAAIAAgRIgOAAQgEAAgEACgAKXCMIgCgDIgBgDIABgDIACgDIAEgBIADABIADADIABADIgBADIgDADIgDABIgEgBgAIICMIgCgDIAAgDIAAgDIACgDIAEgBIADABIADADIABADIgBADIgDADIgDABIgEgBgAGPBXIABgJIADAAQABAAAAAAQABAAABAAQAAAAABgBQAAAAABAAIACgGIABgmIAsAAIAAA1IgLAAIAAgsIgXAAIgCAiQgCAHgDACQgEADgGAAgAEHBXIgDgDIgBgDIABgEIADgDIADgBIADABIAEADIABAEIgBADIgEADIgDABgABnBUQgGgEgDgGQgEgGAAgIQAAgIAEgHQADgGAGgEQAHgEAIAAQAHAAAGADQAHAEACAEIgGAHQgDgEgEgCQgEgCgFAAQgFAAgEADQgFADgBADQgCAEAAAGIACAJQACAFAEACQAEACAFAAIAJgCIAHgFIAGAGQgCAFgHADQgGADgHAAQgJAAgGgEgAh9BUQgGgEgEgGQgDgIgBgGQABgJADgGQAEgHAGgDQAGgEAHAAQAHAAAHAEQAGADAEAGQADAGAAAIIAAAFIgrAAQAAAFAEADQACAEADABQAEACAFAAQAFAAAFgBIAHgFIAGAHQgEAEgGACQgGADgHAAQgJAAgGgEgAhfA3QgCgHgEgEQgEgDgHAAQgGAAgEADQgFAEgBAHIAhAAIAAAAgAjOBXIACgJIACAAQABAAABAAQABAAAAAAQABAAAAgBQAAAAAAAAQADgDAAgDIACgmIArAAIAAA1IgLAAIAAgsIgXAAIAAATQAAAHgCAIQgCAHgDACQgEADgGAAgAkBBUQgGgDgEgHQgDgGAAgIQAAgJADgGQADgGAHgEQAGgEAGAAQAGAAAEADQAGADACAEIAAgIIALAAIAAA1IgLAAIAAgIQgDAFgFACQgDADgHAAQgHAAgFgEgAj8ArQgEADgBAEQgCAGAAAEQAAAEACAFQABAEAEADQAFACAEAAQAFAAAEgCQAEgDABgEQADgEAAgFQAAgFgDgFQgBgDgEgEQgEgCgFAAQgFAAgEACgAk8BVQgGgDgDgDIAGgHQADAEAFABQADACAGAAQAGAAAEgCQADgCAAgEQAAgIgLAAIgLAAIAAgHIAJAAQAGAAACgCQADgCAAgEQAAgEgCgCQgDgCgFAAQgKAAgHAHIgFgHQAEgEAFgCQAGgDAHAAQAKAAAFAFQAGAEgBAHQAAADgCAEQgBADgFACQAGABACADQACADAAAFQAAAFgCAEQgDADgGADQgEACgIAAQgIAAgGgDgAmJBUQgGgEgEgGQgDgIgBgGQABgHADgIQAEgGAGgEQAHgEAIAAQAHAAAHADQAFADAEAEIgHAHQgCgEgFgCIgJgCQgDAAgFACQgFADgBADQgCADgCAFIAbAAIAAAHIgbAAQABAHAFAFQAGAEAGAAIAJgCIAHgFIAHAGQgEAFgFACQgHADgHAAQgIAAgHgEgAnMBUQgGgEgDgGQgDgGAAgIQAAgJADgGQACgFAHgFQAGgEAHAAQAGAAAFADQAEADADAEIAAgIIALAAIAAA1IgLAAIAAgIQgDAFgEACQgEADgHAAQgHAAgGgEgAnGArQgEADgCAEQgCAEAAAGQAAAGACADQACAEAEADQAEACAFAAQAFAAAEgCQADgDADgEQACgDAAgGQAAgGgCgEQgDgEgDgDQgEgCgFAAQgFAAgEACgAqTBXIABgJIAEAAQAAAAABAAQABAAAAAAQABAAAAgBQAAAAAAAAIADgGIACgmIAqAAIAAA1IgKAAIAAgsIgWAAIgBATQAAAHgCAIQgBAHgEACQgDADgHAAgAJuBWIAAgnIgbAnIgLAAIAAg1IALAAIAAAnIAcgnIAKAAIAAA1gAIzBWIgPgVIgCgBIgBgBIgJAAIAAAXIgKAAIAAg1IAKAAIAAAVIAKAAIACgCIAPgTIALAAIgTAZIATAcgAHWBWIAAg1IALAAIAAATIALAAQAKAAAGAEQAGAFAAAIQAAAJgGAEQgGAEgKAAgAHhBOIAKAAQAMAAAAgJQAAgEgDgDQgEgCgFAAIgKAAgAF6BWIAAg1IALAAIAAA1gAFLBWIAAhEIgYAAIAAgKIA8AAIAAAKIgZAAIAABEgADOBWIAAg1IALAAIAAATIALAAQALAAAGAEQAFAEAAAJQAAAJgFAEQgHAEgKAAgADZBOIALAAQAMAAgBgJQAAgEgCgDQgFgCgEAAIgLAAgACmBWIAAgsIgSAAIAAgJIAvAAIAAAJIgTAAIAAAsgABDBWIAAg1IALAAIAAA1gAApBWIAAgXIgbAAIAAAXIgKAAIAAg1IAKAAIAAAVIAbAAIAAgVIAKAAIAAA1gAgRBWIgOgVIgBgBIgCgBIgEAAIAAAXIgLAAIAAgXIgDAAIgDABIgBABIgNAVIgNAAIASgcIgRgZIAMAAIAOAVIAGAAIAAgVIALAAIAAAVIAHAAIAOgVIAMAAIgSAZIASAcgAnoBWIgOgVIgCgBIgCgBIgJAAIAAAXIgKAAIAAg1IAKAAIAAAVIALAAIACgCIAOgTIALAAIgSAZIATAcgAonBWIAAgnIgcAnIgJAAIAAg1IAKAAIAAAnIAcgnIAJAAIAAA1gAqkBWIgOgVIgBgBIgDgBIgJAAIAAAXIgKAAIAAg1IAKAAIAAAVIAMAAIAPgVIAMAAIgTAZIAUAcgArjBWIAAgnIgbAnIgKAAIAAg1IAKAAIAAAnIAcgnIAKAAIAAA1gAtCBWIAAg1IAYAAQAJAAAFAEQAFADABAHQgBAFgCACQgBADgEACQAFABADAEQACACAAAGQAAAEgCADQgCADgEADQgFABgGAAgAs4BPIAOAAQAFAAAEgCQADgCAAgEQAAgIgMAAIgOAAgAs4A4IAMAAQAGAAACgCQADgCAAgEQABgHgMAAIgMAAgAF8AUIgDgDIgBgDIABgDIADgDIADgBIAEABIADADIABADIgBADIgDADIgEABIgDgBgABFAUIgCgDIgBgDIABgDIACgDIAEgBIADABIACADIABADIgBADIgCADIgDABIgEgBgAq7gGIAAhQIALAAIAAAIQABgDAHgEQAEgDAGAAQAHAAAFAEQAHAEADAGQADAGAAAJQAAAIgDAGQgEAHgGADQgEAEgIAAQgGAAgEgDQgGgCgCgFIAAAjgAqohMQgFADgCAEQgCAFAAAFQAAAFACAEQACAEAFADQAEACAEAAQAFAAAEgCQADgDACgEQACgFABgEQgBgEgCgGQgCgEgDgDQgEgCgFAAQgFAAgDACgAHmgRIAGgHIAEgIIgGgCQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAgBAAgBQAAgDACgCQACgCADAAQADAAACADQACACAAAFQAAAHgDAGQgEAGgGAFgAJngTIAAgOIhKAAIAAg1IALAAIAAAsIAVAAIAAgsIAKAAIAAAsIAXAAIAAgsIAKAAIAAAsIAIAAIAAAXgAKEgjQgHgEgDgGQgEgHAAgHQAAgIAEgHQADgGAHgEQAHgEAHAAQAIAAAGAEQAHAEADAGQAEAIAAAHQAAAGgEAIQgDAGgHAEQgHAEgHAAQgHAAgHgEgAKKhLQgFACgCAEQgCAEAAAGQAAAGACADQACAFAFACQADACAFAAQAFAAAEgCQAEgDACgEQACgDAAgGQAAgGgCgEQgCgEgEgCQgFgDgEAAQgEAAgEADgAEDgjQgFgEgFgGQgDgIAAgGQAAgHADgIQAFgGAFgEQAIgEAHAAQAHAAAIAEQAGAEADAGQAEAHAAAIQAAAHgEAHQgDAGgGAEQgIAEgHAAQgGAAgJgEgAEJhLQgEACgCAEQgCAEAAAGQAAAGACADQACAEAEADQAEACAFAAQAFAAAEgCQAEgCACgFQACgDAAgGQAAgGgCgEQgCgEgEgCQgEgDgFAAQgEAAgFADgAjCgjQgHgEgDgGQgEgGAAgIQAAgIAEgHQADgGAHgEQAGgEAIAAQAHAAAHADQAGAEADAEIgHAHQgCgEgFgCQgDgCgGAAQgEAAgFADQgEADgCADQgCAFAAAFIACAJQACAFAEACQAFACAEAAIAJgCIAHgFIAHAGQgDAFgGADQgHADgHAAQgIAAgGgEgAnMggIACgJIADAAQABAAAAAAQABAAABAAQAAAAABgBQAAAAAAAAIADgGIABgmIArAAIAAA1IgLAAIAAgsIgWAAIAAATQgBAJgBAGQgBAGgEADQgEADgGAAgAn6gjQgGgDgEgHQgEgGABgIQgBgIAEgHQAEgHAGgDQAHgEAHAAQAIAAAGAEQAHAEADAGQAEAHAAAIQAAAIgEAGQgDAGgHAEQgGAEgIAAQgHAAgHgEgAn0hLQgFADgCADQgCAEAAAGQAAAGACADQACAEAFADQADACAFAAQAGAAADgCQAEgDACgEQADgEAAgFQAAgGgDgEQgCgEgEgCQgEgDgFAAQgEAAgEADgAo0giQgHgCgDgEIAGgHQACAEAFABQAEACAFAAQAHAAADgCQAEgDAAgDQAAgIgMAAIgLAAIAAgHIAJAAQAGAAADgCQADgCAAgEQAAgEgDgCQgDgCgFAAQgJAAgHAHIgFgHQADgEAGgCQAGgDAGAAQALAAAFAFQAFADAAAIQAAAEgCADQgCADgEACQAGABABADQAEAEAAAEQAAAFgEAEQgDAEgEACQgGACgIAAQgIAAgEgDgApvgjQgGgEgEgGQgDgIAAgGQAAgHADgIQAEgGAGgEQAIgEAHAAQAIAAAGAEQAHAEADAGQAEAHAAAIQAAAHgEAHQgDAGgHAEQgHAEgHAAQgGAAgJgEgApphLQgEACgCAEQgCAEAAAGQAAAGACADQACAEAEADQAEACAFAAQAFAAAEgCQAEgCACgFQACgDAAgGQAAgGgCgEQgCgEgEgCQgFgDgEAAQgEAAgFADgArvgjQgFgDgFgHQgEgGAAgIQAAgJAEgGQAEgHAGgDQAGgEAHAAQAHAAAHAEQAGADADAGQAEAHAAAHIgBAFIgqAAQABAFACADQADAEAEABQADACAGAAQAFAAAEgBQAEgBADgEIAGAHQgEAEgGACQgGADgHAAQgJAAgGgEgArShAQgBgHgEgEQgEgDgHAAQgGAAgFADQgEAFAAAGIAfAAIAAAAgAHRghIAAgXIgaAAIAAAXIgLAAIAAg1IALAAIAAAVIAaAAIAAgVIALAAIAAA1gAGTghIAAgnIgcAnIgKAAIAAg1IAKAAIAAAnIAcgnIAKAAIAAA1gAFGghIAAgsIgTAAIAAgJIAwAAIAAAJIgTAAIAAAsgADmghIgNgVIgCgBIgDgBIgIAAIAAAXIgKAAIAAg1IAKAAIAAAVIALAAIAPgVIAMAAIgTAZIAUAcgACnghIAAg1IALAAIAAA1gACNghIAAgXIgaAAIAAAXIgLAAIAAg1IALAAIAAAVIAaAAIAAgVIALAAIAAA1gAAYghIAAg1IAKAAIAAATIAMAAQALAAAFAEQAGAEAAAJQAAAJgGAEQgFAEgLAAgAAigpIAMAAQALAAABgJQAAgEgDgDQgFgCgEAAIgMAAgAgPghIAAgsIgSAAIAAgJIAvAAIAAAJIgSAAIAAAsgAg2ghIAAgnIgcAnIgKAAIAAg1IAKAAIAAAnIAcgnIAKAAIAAA1gAiDghIAAgsIgTAAIAAgJIAvAAIAAAJIgSAAIAAAsgAjmghIAAg1IAKAAIAAA1gAkAghIAAgmIgSAYIgHAAIgRgYIAAAmIgKAAIAAg1IAKAAIAVAcIAVgcIAKAAIAAA1gAmFghIAAg1IALAAIAAATIAMAAQAKAAAGAEQAGAFAAAIQAAAJgGAEQgGAEgKAAgAl6gpIALAAQAMAAAAgJQAAgEgCgDQgEgCgGAAIgLAAgAsNghIgGgPIgkAAIgFAPIgLAAIAehOIAJAAIAeBOgAsWg5IgPgmIgOAmIAdAAgACphjIgCgDIgBgDIABgDIACgDIAEgBIADABIADADIABADIgBADIgDADIgDABIgEgBgAjlhjIgCgDIgBgDIABgDIACgDIAEgBIAEABIACADIABADIgBADIgCADIgEABIgEgBgAiIh+IADgJIAGABIAFgBQACgBACgDQADgDABgEIACgGIgXg2IAMAAIARAqIAQgqIALAAIgYA8QgCAGgFAGQgDAFgEACQgDACgHAAgABfh+IAAhQIAKAAIAAAIQADgEAFgDQAFgDAFAAQAHAAAHAEQAGAFADAFQADAHAAAIQAAAGgDAIQgEAGgFAEQgGAEgIAAQgGAAgEgDQgEgCgEgFIAAAjgABxjEQgEADgCAEQgCAEAAAGQAAAGACADQACAEAEADQAEACAEAAQAFAAAEgCQAEgDACgEQACgDAAgGQAAgGgCgEQgCgEgEgDQgEgCgFAAQgEAAgEACgAHliYIgCgDIgBgDIABgEIACgDIAEgBIADABIAEADIABAEIgBADIgEADIgDABgADliaQgGgCgDgEIAGgHQACAEAEABQAEACAGAAQAGAAAEgCQADgDABgDQAAgIgMAAIgLAAIAAgHIAIAAQAHAAACgCQAEgCAAgEQAAgEgEgCQgBgCgHAAQgJAAgGAHIgGgHQAEgEAFgCQAHgDAGAAQALAAAEAFQAGADAAAIQAAAEgCADQgDADgDACQAFABACADQADAEAAAEQAAAFgDAEQgDAEgFACQgGACgHAAQgIAAgFgDgAg/ibQgGgEgDgGQgDgGgBgIQABgIADgHQADgGAGgEQAHgEAIAAQAIAAAGADQAGAEADAEIgGAHQgEgEgEgCQgEgCgFAAQgFAAgEADQgEADgCADQgCAFAAAFIACAJQACAFAEACQAEACAFAAIAJgCIAIgFIAGAGQgDAFgGADQgHADgHAAQgIAAgHgEgAjJibQgFgDgFgHQgDgGAAgIQAAgIADgHQAFgHAFgDQAHgEAJAAQAGAAAGADQAGACAEAFIgGAHQgDgEgEgCQgGgCgDAAQgEAAgFACQgEADgCADQgDACAAAGIAaAAIAAAHIgaAAQAAAHAFAFQAFAEAIAAQAFAAAEgCQAEgCADgDIAGAGQgEAFgGACQgGADgGAAQgJAAgHgEgAkLibQgGgDgEgHQgDgGAAgIQAAgJADgGQADgGAHgEQAGgEAGAAQAFAAAFADQAGADACAEIAAgIIALAAIAAA1IgLAAIAAgIQgDAFgFACQgDADgHAAQgHAAgFgEgAkGjEQgDADgCAEQgCAGgBAEQABAEACAFQACAEADADQAEACAFAAQAFAAAEgCQAEgDACgEQACgEAAgFQAAgFgCgFQgCgDgEgEQgDgCgGAAQgFAAgEACgAmDibQgFgDgEgFQgEgGAAgHIgJAAIAAAXIgKAAIAAg1IAKAAIAAAVIAJAAQACgGADgGQADgFAHgDQAFgDAHAAQAIAAAGAEQAGAEAEAGQADAGAAAJQAAAIgDAGQgFAHgFADQgGAEgIAAQgIAAgGgEgAl+jDQgDACgCAEQgCAEAAAGQAAAGACADQACAEADADQAEACAFAAQAFAAAEgCQADgCACgFQACgEAAgFQAAgGgCgEQgCgEgDgCQgEgDgFAAQgFAAgEADgAnqiYIABgJIADAAQABAAABAAQABAAAAAAQABAAAAgBQABAAAAAAIACgGIABgmIArAAIAAA1IgKAAIAAgsIgXAAIAAATQAAAKgCAFQgCAHgDACQgDADgGAAgArmibQgFgDgFgHQgEgGAAgIQAAgJAEgGQADgGAHgEQAGgEAHAAQAGAAAIAEQAGADADAGQAEAHAAAHIgBAFIgqAAQABAFACADQADAEAEABQADACAGAAIAJgBIAHgFIAFAHQgDAEgGACQgHADgGAAQgJAAgGgEgArJi4QgBgHgEgEQgEgDgHAAQgGAAgFADQgEAEgBAHIAgAAIAAAAgAGqiZIAAg1IAYAAQAJAAAGAEQAFADAAAHQAAAFgCACQgCAEgDABQAFACACADQACADABAFIgCAHQgCADgFADQgFABgFAAgAG0igIAPAAQAEAAAFgCQACgDAAgDQAAgIgLAAIgPAAgAG0i3IAMAAQAHAAACgCQADgBAAgFQAAgHgMAAIgMAAgAGQiZIAAg1IALAAIAAA1gAF5iZIgNgVIgCgBIgDgBIgHAAIAAAXIgLAAIAAg1IALAAIAAAVIAKAAIACgCIAOgTIAMAAIgTAZIATAcgAE8iZIAAgnIgdAnIgJAAIAAg1IAKAAIAAAnIAcgnIAKAAIAAA1gADHiZIAAgnIgcAnIgKAAIAAg1IALAAIAAAnIAcgnIAJAAIAAA1gAAviZIgPgTIgOATIgNAAIAVgbIgVgaIANAAIAPATIAPgTIAMAAIgUAbIAUAagAgOiZIAAg1IAKAAIAAA1gAkviZIAAgWQgGAEgJAAQgFAAgFgDQgFgBgDgFQgCgEAAgHIAAgPIAKAAIAAAOQAAAGADADQAEACAFAAQAIAAAFgDIAAgWIALAAIAAA1gAn7iZIgOgVIgCgBIgCgBIgIAAIAAAXIgLAAIAAg1IALAAIAAAVIAKAAIACgCIAOgTIAMAAIgTAZIATAcgAo5iZIAAgnIgcAnIgKAAIAAg1IAKAAIAAAnIAcgnIAKAAIAAA1gAqZiZIAAg1IAYAAQAJAAAGAEQAEADAAAHQAAAFgCACQgBADgEACQAFABACAEQADACAAAGQAAAEgCADQgCADgEADQgFABgGAAgAqPigIAOAAQAGAAADgCQACgCAAgEQAAgIgLAAIgOAAgAqPi3IAMAAQAHAAACgCQACgCAAgEQAAgHgLAAIgMAAgAsMiZIAAgjIgpAAIAAAjIgLAAIAAhOIALAAIAAAhIApAAIAAghIAKAAIAABOgAGSjbIgCgDIgBgDIABgDIACgDIAEgBIADABIACADIABADIgBADIgCADIgDABIgEgBgAgNjbIgCgDIgBgDIABgDIACgDIAEgBIAEABIACADIABADIgBADIgCADIgEABIgEgBg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.urText, new cjs.Rectangle(-84,-23.3,168,46.6), null);


(lib.t2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AOpHQIAHgiQAJACAIAAQAHAAAGgCQAFgDAEgFQADgEAFgNIAEgIIg5iLIAqAAIAjBdIAihdIAqAAIg8CUQgIAUgKAQQgIANgNAHQgLAGgRAAQgQAAgLgEgADHHQIAAjOIAnAAIAAAPQAIgKAKgEQAKgFANAAQATAAAOAJQAPAJAIARQAJARAAAVQAAAUgJARQgHAQgQAKQgOAKgTAAQgNAAgKgFQgKgEgIgKIAABTgAD9EmQgIAFgEAIQgEAIAAAMQAAALAEAIQAEAJAIAEQAHAFAKAAQALAAAHgFQAHgEAFgJQAEgJAAgKQAAgLgEgJQgFgJgHgEQgHgFgLAAQgKAAgHAFgAI5GuIAAgiIhkAAIAAAiIgiAAIAAhDIAQAAQAGgHADgMQADgOABgTIACg1IB0AAIAABpIAVAAIAABDgAH2E5QgBAUgCALQgCALgFAIIAzAAIAAhJIgoAAgARLGMQgFgCgEgHQgDgFAAgHQAAgGADgGQAFgGAEgDQAFgDAIAAQAHAAAFADQAGADADAGQADAGAAAGQAAAHgDAFQgDAGgGADQgFAEgHAAQgIAAgFgEgAgJGGQgOgJgJgRQgIgQAAgVQAAgWAIgQQAJgRAOgJQAOgJASAAQANAAAKAFQAKAEAIAKIAAgPIAnAAIAACKIgnAAIAAgPQgIAJgKAFQgKAFgNAAQgSAAgOgKgAAOEmQgHAEgFAJQgDAJAAALQAAAKADAJQAFAJAHAEQAHAFALAAQAKAAAHgFQAHgEAFgJQAEgJAAgKQAAgLgEgJQgFgJgHgEQgHgFgKAAQgLAAgHAFgAoOGIQgQgIgJgNQgJgNgDgRIgSAAIAAA3IgnAAIAAiKIAnAAIAAAyIATAAQAEgQAJgMQAJgMAPgHQAPgHARAAQAWAAAQAKQAQAJAJARQAIAQAAAVQAAAVgIAQQgJAQgQAKQgRAJgVAAQgSAAgPgHgAn+EnQgHAFgEAIQgDAHAAAMQAAAMADAHQAEAIAHAFQAHAEAKAAQALAAAGgEQAIgFADgIQAEgHAAgMQAAgMgEgHQgFgJgGgEQgHgFgKAAQgJAAgIAFgAt6GIQgOgHgKgOQgKgPgCgPIgTAAIAAA3IgnAAIAAiKIAnAAIAAAyIATAAQAEgQAKgMQAJgMAPgHQAPgHARAAQAVAAAQAKQARAKAIAQQAJAQAAAVQAAAVgJAQQgIAPgQALQgSAJgUAAQgTAAgPgHgAtpEnQgHAEgEAJQgEAHAAAMQAAAMAEAHQAEAIAHAFQAGAEALAAQAKAAAHgEQAHgEAEgJQAEgIAAgLQAAgKgEgJQgFgJgGgEQgIgFgJAAQgKAAgHAFgANvGMIAAg3IgxAAIAAA3IgoAAIAAiKIAoAAIAAAyIAxAAIAAgyIAoAAIAACKgALOGMIAAhVIg3BVIgkAAIAAiKIAlAAIAABUIA3hUIAkAAIAACKgAF0GMIAAiKIAnAAIAACKgAiJGMIAAhqIgrAAIAAggIB+AAIAAAgIgsAAIAABqgAkyGMIAAg3IgxAAIAAA3IgoAAIAAiKIAoAAIAAAyIAxAAIAAgyIAoAAIAACKgArYGMIAAhqIgsAAIAAggIB+AAIAAAgIgrAAIAABqgAxEGMIAAhqIgrAAIAAggIB+AAIAAAgIgrAAIAABqgAF7DoQgEgDgEgGQgDgFAAgGQAAgGADgGQADgFAFgDQAFgEAHAAQAHAAAFAEQAGADACAFQADAGAAAGQAAAGgDAFQgDAGgFADQgFADgHAAQgGAAgGgDgAqVCGIAAjNIAoAAIAAAPQAIgKAJgEQAKgFANAAQATAAAOAJQAPAJAIARQAJAQAAAWQAAAUgJAQQgIARgPAJQgOAKgTAAQgNAAgKgFQgJgFgIgJIAABTgApfgjQgHAFgFAIQgEAJAAALQAAAJAEAJQAFAJAHAEQAHAFALAAQAKAAAHgFQAIgEAEgJQAEgJAAgJQAAgLgEgJQgEgIgIgFQgHgFgKAAQgLAAgHAFgAg/A8QgSgKgJgRQgJgRAAgSQAAgTAJgSQAJgRASgJQARgKAXAAQAUAAAOAGQAQAGAJAKIgVAZQgGgGgKgFQgKgEgKAAQgPAAgKAHQgKAHgEANIA6AAIAAAZIg6AAQADAOAKAHQALAHAPAAQAKAAAKgEQAJgDAHgIIAVAaQgLAKgOAGQgOAGgUAAQgXAAgRgKgAjvA8QgPgJgIgRQgIgQAAgUQAAgWAIgQQAJgRAOgJQAPgJASAAQANAAAKAFQAKAEAIAKIAAgPIAnAAIAACJIgnAAIAAgPQgIAJgKAFQgKAFgNAAQgSAAgPgKgAjXgjQgHAFgFAIQgEAJAAALQAAAJAEAJQAFAJAHAEQAHAFALAAQAKAAAHgFQAIgEAEgJQAEgJAAgJQAAgLgEgJQgEgIgIgFQgHgFgKAAQgLAAgHAFgAuqA8QgPgKgIgQQgJgRAAgTQAAgVAJgRQAIgRAPgJQAPgJASAAQANAAAKAFQAKAEAIAKIAAgPIAnAAIAACJIgnAAIAAgPQgIAKgKAEQgKAFgNAAQgSAAgPgKgAuSgjQgHAEgFAJQgEAJAAALQAAAJAEAJQAFAJAHAEQAHAFALAAQAKAAAHgFQAIgEAEgJQAEgJAAgJQAAgLgEgJQgEgIgIgFQgHgFgKAAQgLAAgHAFgAmdBCIAAiJIBCAAQAbAAAMAKQANAKAAARQAAAKgEAIQgFAIgJAEQAYAGAAAYQAAALgGAJQgGAKgLAFQgLAFgRAAgAl3AmIAZAAQAXAAAAgPQAAgHgGgEQgGgDgLAAIgZAAgAl3gPIAVAAQALAAAFgEQAGgEAAgHQAAgHgGgDQgFgEgLAAIgVAAgAnoBCIAAiJIAnAAIAACJgAsWBCIAAiJIBoAAIAAAgIhBAAIAABpgAwMBCIAAg3IgyAAIAAA3IgnAAIAAiJIAnAAIAAAyIAyAAIAAgyIAnAAIAACJgAnghhQgGgDgDgGQgDgFAAgGQAAgGADgGQADgFAGgDQAFgEAGAAQAHAAAFAEQAGADADAFQADAGAAAGQAAAGgDAFQgDAGgGADQgFADgHAAQgGAAgFgDgAsNjlIAAgiIhlAAIAAAiIgiAAIAAhDIAQAAQAGgHADgMQADgNABgUIADg1IBzAAIAABpIAVAAIAABDgAtRlaQgBAWgCAJQgDAMgEAHIAzAAIAAhJIgoAAgAgrkNQgSgKgIgRQgJgQAAgUQAAgUAJgRQAIgQARgKQASgKAWAAQASAAAQAHQAQAGAJAMIgWAbQgGgGgLgGQgKgEgJAAQgLAAgIAFQgHAEgFAJQgFAIAAALQAAALAFAIQAEAIAIAFQAIAEALAAQAJAAAKgEQAKgEAHgHIAWAaQgKANgPAGQgQAHgSAAQgWAAgRgKgAjakNQgQgKgHgQQgJgRAAgUQAAgVAJgRQAIgRAPgJQAOgJATAAQANAAAKAFQAKAEAIAKIAAgPIAnAAIAACKIgnAAIAAgPQgIAKgKAEQgKAFgNAAQgTAAgOgKgAjCltQgIAFgEAIQgEAIAAAMQAAALAEAIQAEAJAIAEQAHAFAKAAQALAAAHgFQAIgEAEgJQAEgJAAgKQAAgLgEgJQgEgIgIgFQgHgFgLAAQgKAAgHAFgAw5kRQgYgNgNgYQgNgYAAgdQAAgcANgZQAOgYAXgNQAYgOAdAAQAcAAAZAOQAYAOANAXQANAYAAAdQAAAegNAXQgNAXgYAOQgYAOgdAAQgeAAgXgOgAwlmkQgOAJgIAPQgHAPAAASQAAATAHAPQAHAOAPAJQAOAJATAAQASAAAPgJQAOgJAHgOQAIgPAAgTQAAgSgIgPQgIgQgNgIQgOgIgTAAQgUAAgNAIgAENkNQgRgLgJgPQgJgQAAgVQAAgVAJgQQAJgQARgKQASgKAVAAQAVAAARAKQARAKAJAQQAJASAAATQAAATgJASQgJAQgRAKQgQAJgWAAQgWAAgRgJgAEilsQgHAEgFAJQgEAIAAALQAAAMAEAHQAFAJAHAEQAHAEALAAQALAAAGgEQAIgFAEgIQAFgIAAgLQAAgKgFgJQgEgJgIgEQgHgFgKAAQgKAAgIAFgAoVkNQgSgLgIgPQgKgQAAgVQAAgVAKgQQAIgQASgKQARgKAVAAQAVAAARAKQASAKAIAQQAJARAAAUQAAAUgJARQgIAPgSALQgQAJgWAAQgWAAgQgJgAoBlsQgHAEgFAJQgEAJAAAKQAAALAEAIQAFAIAHAFQAIAEAKAAQAKAAAIgEQAHgFAFgIQAEgHAAgMQAAgLgEgIQgFgJgHgEQgIgFgKAAQgJAAgJAFgACokHIAAg3IgyAAIAAA3IgnAAIAAiKIAnAAIAAAyIAyAAIAAgyIAnAAIAACKgAk8kHIAAg0QgQAHgRAAQgQAAgMgGQgMgGgHgNQgHgLAAgSIAAgoIAnAAIAAAlQAAAMAGAEQAGAFANAAQANAAAKgEIAAg1IAnAAIAACKgAp7kHIAAg3IgyAAIAAA3IgnAAIAAiKIAnAAIAAAyIAyAAIAAgyIAnAAIAACKg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t2, new cjs.Rectangle(-113.5,-46.7,227.2,93.6), null);


(lib.t1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AFgGOQgGgEgDgFQgDgGAAgHQAAgGADgGQADgGAGgDQAFgDAHAAQAHAAAGADQAFADADAGQAEAHAAAFQAAAGgEAHQgDAFgFAEQgGADgHAAQgHAAgFgDgACWGNIAAjIIBHAAQAfAAAYANQAYALANAYQANAXAAAeQAAAdgNAXQgNAXgYALQgXANggAAgAC+FpIAdAAQAeAAASgQQARgQAAgfQAAgWgIgOQgIgOgPgIQgPgGgTgBIgdAAgABAGNIAAjIIAoAAIAADIgAgMGNIguhPIgaAAIAABPIgoAAIAAjIIBNAAQAUAAASAHQAPAGAJANQAJAOAAAUQAAAYgLANQgKANgUAHIAxBTgAhUEcIAmAAQAOAAAIgIQAIgFAAgOQAAgLgIgHQgIgHgOAAIgmAAgAk5GNIAAjIIBUAAQASAAAPAHQAOAHAHALQAHAMAAAQQAAAPgGALQgFAMgLAFQAPAHAHAMQAIAMAAARQAAARgHAMQgIANgNAHQgNAHgTAAgAkRFrIAsAAQAOAAAHgHQAHgFAAgNQAAgLgHgHQgHgHgOAAIgsAAgAkREYIAlAAQAOAAAGgHQAIgGAAgLQAAgMgIgGQgGgGgOAAIglAAgAnBGNIAAhBIhHiHIAsAAIAvBfIAwhfIAsAAIhICHIAABBgApJGNIAAhUIhVAAIAABUIgoAAIAAjIIAoAAIAABPIBVAAIAAhPIAoAAIAADIgAAzBFIAEgjIAHABQAHAAADgEQADgDABgHIACgYIADhDIB1AAIAACJIgnAAIAAhpIgoAAIgCAlQgBAbgFAOQgGARgKAHQgLAHgSAAIgPgCgAomA9QgRgJgJgSQgJgQAAgTQAAgVAJgQQAJgRAQgKQASgJATAAQAVAAAQAJQAPAKAJAPQAJAQAAASIgBAQIhjAAQADALAJAJQAKAGAQABQALAAAKgEQALgEAHgFIARAdQgKAIgQAFQgRAFgRAAQgWAAgSgKgAnjgPQgDgNgHgGQgJgIgMABQgMgBgIAIQgIAGgDANIA+AAIAAAAgAEFA9QgSgLgIgPQgKgQAAgUQAAgVAKgQQAIgPASgLQARgKAVAAQAVAAARAKQASAKAIAQQAKAQAAAVQAAAUgKAQQgJAQgRAKQgQAJgWAAQgVAAgRgJgAEaghQgIAEgFAJQgEAKAAAJQAAAKAEAIQAFAJAIAEQAGAEALAAQALAAAHgEQAHgEAFgJQAEgIAAgKQAAgKgEgJQgFgIgHgFQgIgEgKgBQgKABgHAEgAhJA9QgRgLgJgPQgJgQAAgUQAAgVAJgQQAJgPARgLQARgKAWAAQAVAAAQAKQARALAJAPQAJARAAAUQAAAUgJAQQgJAPgRALQgPAJgWAAQgXAAgQgJgAg0ghQgIAFgEAIQgFAJAAAKQAAAKAFAIQAEAJAIAEQAHAEALAAQAKAAAHgEQAIgEAEgJQAFgIAAgKQAAgKgFgJQgEgIgIgFQgIgEgJgBQgKABgIAEgAKtBDIAAgwIgTAAIgbAwIgrAAIAgg1QgdgKAAgcQAAgQAHgKQAIgKANgFQANgFASAAIBDAAIAACJgAKEglQgGAEAAAJQAAAIAGAEQAGAEAKAAIAZAAIAAghIgZAAQgLAAgFAEgAIRBDIAAiJIAoAAIAACJgAGQBDIAAiJIBnAAIAAAgIhAAAIAABpgAiuBDIAAg2IgyAAIAAA2IgnAAIAAiJIAnAAIAAAyIAyAAIAAgyIAnAAIAACJgAlNBDIgegrIgcArIguAAIAyhGIgyhDIAuAAIAeAqIAdgqIAuAAIgzBFIAzBEgAqpBDIAAhpIgrAAIAAggIB+AAIAAAgIgrAAIAABpgAIZhgQgFgDgDgFQgDgGAAgGQAAgGADgGQACgEAGgEQAFgDAHAAQAHAAAFADQAGAEACAEQADAGAAAGQAAAGgDAGQgDAFgFADQgFADgHAAQgGAAgGgDgAiljOQgPgLgIgPQgIgSAAgUQAAgUAIgRQAJgRAOgJQAPgKASAAQANABAKAFQAKAEAIAJIAAgOIAnAAIAACJIgnAAIAAgPQgIALgKADQgKAFgNABQgSAAgPgKgAiNkuQgHAFgEAIQgEAIAAALQAAAMAEAIQAEAIAHAFQAHAFALAAQALAAAHgFQAHgFAEgIQAEgIAAgMQAAgLgEgIQgEgIgHgFQgHgFgLAAQgLAAgHAFgAnejPQgQgJgKgQQgJgRAAgUQAAgVAJgQQAJgRARgKQARgJAVgBQAWABARAJQAQALAKAQQAJAQAAAVQAAAUgJARQgKAQgQAJQgQAKgXAAQgWAAgQgKgAnJktQgIAEgEAIQgFAJAAALQAAALAFAIQAEAIAIAEQAHAEAKAAQALAAAHgEQAHgEAFgIQAEgIAAgLQAAgKgEgKQgFgIgHgEQgIgFgKAAQgJAAgIAFgAlTjJIAAiJIBCAAQAagBANALQANAJAAASQAAAKgEAIQgGAIgIADQAYAIAAAYQAAALgGAJQgFAJgMAGQgLAEgQAAgAktjkIAaAAQAWAAAAgPQAAgHgGgEQgGgEgKABIgaAAgAktkbIAVAAQAMAAAFgDQAFgEAAgHQAAgIgFgDQgFgDgMAAIgVAAgApJjJIAAhTIhVAAIAABTIgoAAIAAjHIAoAAIAABPIBVAAIAAhPIAoAAIAADHg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1, new cjs.Rectangle(-72.4,-40.1,145,80.2), null);


(lib.r_part = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#35303E").s().p("AhijHQBSAAA5A7QA6A6AABSQAABTg6A6Qg5A7hSAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.r_part, new cjs.Rectangle(-9.9,-20,19.9,40), null);


(lib.lil_logo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("EgGJAwCIhihiQgFgFgGgCQgHgDgGAAIm9AAQiKAAhPhDQglgfgTgpQgTgqAAgwIAAl5QAAgQAMgNQAMgLAQAAIH+AAQCJAABQBDQAlAeATAqQATAqAAAvIAACyQAAARgMAMQgMALgQAAIgPAAQgQAAgMgLQgMgNAAgQIAAiyQAAgbgLgWQgKgXgUgRQgagVgogMQgpgLgxAAIm5AAQgGAAgEAEQgEAEAAAFIAAE1QAAAbAKAXQAKAVAVASQAbAXAnALQAoALAyAAIHZAAQANAAALAFQALAEAJAJIB1B1QAMAMAAARQAAARgMAMIgKAKQgMALgRAAQgRAAgLgLgEAOgAuWQgsAAgsgRQgpgRgigfIgWgUQgLgMgBgRQgBgQAMgNIAJgKQALgMASgBQARAAAMAMIAVAUQAVATAZAKQAZAKAbAAIE/AAQAsAAAigIQAigIAUgPQALgJAGgNQAGgPAAgWQAAgWgGgPQgFgNgMgJQgTgPgjgIQgigIgsAAIkNAAQh9AAhBg0Qg8guABhNIAAgVQgBhNA8guQBBg0B9AAIElAAQAtAAAoAPQAqARAgAcIAbAZQAMALABARQABARgLAMIgJAKQgLANgRABQgRABgNgLIgbgZQgTgRgZgKQgYgJgbAAIklAAQgrAAgjAIQgjAJgSAPQgMAIgGAOQgGAPAAAVQAAAWAGAPQAGAOAMAIQASAPAjAJQAjAIArAAIENAAQB9AABCAzQA7AvAABNIAAAUQAABNg7AvQhBAzh+AAgEAArAuWQiJAAhQhDQhLg/AAhjIAAi9QAAgvATgqQATgqAlgeQBQhDCJAAIEAAAQCLAABPBDQAlAeATAqQATAqAAAvIAAC9QAAAwgTAqQgTApglAfQhPBDiLAAgEgAvAl6QgoAMgaAVQgUARgKAXQgLAWAAAbIAAC9QAAAcALAWQAKAWAUARQAbAWAnAMQAoALAyAAIEAAAQAzAAAogLQAngLAbgXQAVgSAKgVQAKgWAAgcIAAi9QAAgbgKgWQgLgWgUgSQgagVgogMQgogLgzAAIkAAAQgyAAgoALgEgXLAuWQgQAAgMgMQgMgMAAgRIAAo1QAAgRAMgLQAMgMAQAAIAOAAQARAAAMAMQAMALAAARIAAI1QAAARgMAMQgMAMgRAAgADZdGQgighAAgvQAAgvAiggQAiggAxAAQAgAAAaAPQAZAOAOAZIgiAXQgWgkgpAAQgeAAgUAUQgUAUAAAfQAAAfAUATQAUAUAeAAQApAAAWgkIAiAXQgOAZgZAOQgaAPggAAQgwAAgjgggAgxdNQgagaAAgqIAAh+IAtAAIAACBQAAAXAOAOQANAMAVAAQAVAAANgMQANgNAAgYIAAiBIAtAAIAAB+QABAqgbAaQgaAZgoAAQgoAAgbgZgApmdGQgighAAgvQAAgvAiggQAiggAxAAQAwAAAjAgQAiAgAAAvQAAAvgiAhQgjAggwAAQgxAAgigggApGbEQgTAUAAAeQAAAgATATQAUAUAfAAQAeAAAUgUQAVgTAAggQAAgegVgUQgUgUgeAAQgeAAgVAUgAy4dmIiAiFIAACBIgsAAIAAjbIAPAAIB/CEIAAiAIAtAAIAADbgAV7diIAAhVIhMiCIAzAAIAwBVIAwhVIAyAAIhMCCIAABVgARhdiIAAjXIBOAAQAfAAATARQAUARAAAaQAAAXgRAQQAnAOAAAnQAAAcgUARQgUASggAAgASMc8IA0AAQAOAAAJgHQAIgHAAgNQAAgNgIgHQgJgHgOAAIg0AAgASMbiIAgAAQANAAAIgHQAHgHAAgLQAAgLgHgHQgIgGgNAAIggAAgAK7diIAAjXIBHAAQA2AAAhAdQAhAeABAwQgBAvghAfQgiAeg1AAgALoc6IAaAAQAiAAAUgTQAUgSABgfQgBgfgUgSQgUgSgiAAIgaAAgAHWdiIAAjXICUAAIAAAoIhnAAIAAArIBLAAIAAAmIhLAAIAAA2IBrAAIAAAogAlTdiIAAjXIBIAAQA1AAAiAdQAhAeAAAwQAAAvghAfQgiAeg1AAgAkmc6IAbAAQAhAAAUgTQAVgSAAgfQAAgfgVgSQgUgSghAAIgbAAgArpdiIg5hMIghAAIAABMIgtAAIAAjXIBTAAQAjAAAWATQAWATAAAfQAAAVgKAQQgLAQgRAIIA+BVgAtDbvIAmAAQAPAAAKgIQAIgJAAgOQAAgNgIgJQgKgIgPAAIgmAAgAwjdiIAAivIhHAAIAAgoIC7AAIAAAoIhHAAIAACvgA3odiIAAjXIAsAAIAADXgALZN0QgNgMAAgSIAAnwQAAgSANgMQAMgNARAAQASAAANANQAMAMAAASIAAHwQAAASgMAMQgNANgSAAQgRAAgMgNgAINNpIhsjbIimAAIAADIQAAASgNAMQgMANgSAAQgSAAgMgNQgNgMAAgSIAAnqQAAgRANgNQAMgMASAAIDlAAQBTAAAxAtQAyAtAABMQAAA5geApQgdApg1ARIBeC/QAEAKAAAKQAAARgMAMQgMANgSAAQgZAAgNgYgAD7I+IDDAAQAoAAAYgYQAYgXAAgnQAAgngYgXQgYgYgoAAIjDAAgAqRN0QgNgMAAgSIAAjSIi4kIQgIgMAAgNQAAgRALgLQAMgMARAAQAXAAANATICfDjICfjjQANgTAXAAQARAAALAMQALALAAARQABANgJALIi3EJIAADSQAAASgNAMQgNANgRAAQgSAAgMgNgAvSN0QgMgMAAgSIAAjVIkdAAIAADVQAAASgNAMQgNANgRAAQgSAAgMgNQgNgMAAgSIAAnwQAAgSANgMQAMgNASAAQARAAANANQANAMAAASIAADKIEdAAIAAjKQAAgSAMgMQANgNARAAQATAAAMANQAMAMAAASIAAHwQAAASgMAMQgMANgTAAQgRAAgNgNgAO2OAQgSAAgNgMQgMgNAAgRIAAnyQAAgRAMgNQANgMASAAIB4AAQB5AABVBVQBVBVAAB5QAAB4hVBWQhVBVh5AAgAPgMrIBOAAQBVAAA9g8QA8g9AAhVQAAhVg8g9Qg9g8hVAAIhOAAgAkzN6QgSAAgNgMQgMgNAAgRIAAnkQAAgSAMgMQAMgMATAAIC1AAQBPAAAvApQAxApgBBDQAABHgzAnQAsATAZAmQAZAmAAAyQAABBgwAvQg3A0hfAAgAkJMrIChAAQAzAAAegYQAcgYAAgqQAAgrgcgYQgegXg1AAIifAAgAkJIoICPAAQAqAAAXgYQAWgWAAgeQgBgqgdgTQgXgPglAAIiMAAgALyh8QhAg/ABhaMAAAgofQgBhZBAhAQBAg/BZAAQBZAABAA/QA+A/ABBaMAAAAofQgBBag+A/QhAA/hZAAQhZAAhAg/gAiYh8Qg/g/AAhaIAA6/QAAhaA/g/QBAg/BYAAQBZAABAA/QA+A/ABBaIAAa/QgBBag+A/QhAA/hZAAQhYAAhAg/gAwjh8Qg/g/AAhaMAAAgofQAAhaA/g/QA/g/BaAAQBZAAA/A/QBABAAABZMAAAAofQAABZhABAQg/A/hZAAQhaAAg/g/gEgCngm0QhFhGgBhiQABhjBFhFQBGhGBhAAQBjAABFBGQBFBGAABiQAABihFBGQhFBFhjAAQhhAAhGhFg");
	this.shape.setTransform(372.5,-198.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.lil_logo, new cjs.Rectangle(220.1,-506.8,304.8,617.1), null);


(lib.l_part = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#35303E").s().p("AgoCNQg7g6AAhTQAAhSA7g6QA5g7BTAAIAAGPQhTAAg5g7g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.l_part, new cjs.Rectangle(-9.9,-20,19.9,40), null);


(lib.kv2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(3).p("AoLNMImXyxQgRgyAXgwQAYgwAzgRIS5mUQAzgRAwAYQAwAXARAzIGXSxQASAygYAwQgYAwgzARIy5GUQgzARgwgYQgwgYgRgyg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.kv2, new cjs.Rectangle(-99.6,-94.7,199,194.4), null);


(lib.kv1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(3).p("AoMNMImXywQgRgzAYgwQAYgwAzgRIS5mUQAzgRAwAYQAxAYARAyIGXSxQARAzgYAvQgYAwgzARIy6GUQgzARgvgYQgxgXgRgzg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.kv1, new cjs.Rectangle(-95.3,-94.7,190.7,189.7), null);


(lib.dev = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_3
	this.instance = new lib.dev1();
	this.instance.parent = this;
	this.instance.setTransform(-62,-169.6,1,1,-18);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой_2
	this.instance_1 = new lib.shadow();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-93,-143,0.9,0.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.dev, new cjs.Rectangle(-93,-190,232.2,545.6), null);


(lib.btn_txt = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AkIBDIAAgYIhVAAIAAhsIAOAAIAABeIA3AAIAAheIAQAAIAABeIAPAAIAAAmgAglA+IAAgTIhBAAIAAhJIAOAAIAAA9IAlAAIAAg9IAPAAIAAA9IAMAAIAAAfgAEiAoQgIgFgGgJQgEgIAAgMQAAgJAEgKQAHgJAHgFQAKgFALAAQALAAAIAFQAKAFAFAJQAFAIAAALQAAAMgFAIQgFAJgKAFQgIAFgLABQgKgBgLgFgAErgOQgGADgDAFQgEAGAAAGQAAAHAEAHQACADAHAGQAFACAHAAQAGAAAGgCQAGgEACgFQAEgGAAgIQAAgHgEgFQgDgGgFgCQgFgEgHAAQgHAAgFAEgAB4AoQgIgEgFgKQgFgJAAgLQAAgKAFgJQAEgJAJgFQAIgFAKAAQAIAAAGADQAFACAGAIIAAgLIAPAAIAABJIgPAAIAAgLQgFAHgGADQgIADgGABQgKgBgIgFgACBgPQgGAEgDAFQgCAFAAAHQAAAJACAFQAEAGAFADQAFADAHAAQAFAAAGgDQAFgDADgGQAEgGAAgIQAAgGgEgGQgCgFgGgEQgGgDgFAAQgHAAgFADgAjaAoQgLgGgDgIQgFgIgBgMQABgKAFgJQAEgIAJgGQALgFAIAAQALAAAIAFQAJAFAFAIQAEAHAAALIAAAHIg7AAQABAHADAEQADAEAGAEQAFACAIAAQAHAAAGgCQAGgCAEgFIAHAJQgEAHgIACQgKAEgKABQgKgBgKgFgAiwAAQgCgJgGgFQgGgFgKAAQgIAAgGAFQgGAFgCAJIAuAAIAAAAgADEArIAAhJIAiAAQAOAAAGAGQAIAFgBAIQABAGgDAEQgDAEgEABQAFADAEAFQAEAFABAGQAAAGgEAEQgDAFgGADQgIACgGAAgADTAgIAUAAQAIABAFgDQAEgDAAgFQgBgLgQAAIgUAAgADTABIARAAQAHAAAEgCQAEgDABgFQAAgKgQAAIgRAAgABNArIgTgdIgCgCIgEgBIgLAAIAAAgIgPAAIAAhJIAPAAIAAAdIAPAAIAVgdIASAAIgaAiIAaAngAgMArIAAhJIAOAAIAABJgAgKgwIgDgDIgCgFIACgFIADgEIAGgBIAEABIADAEIABAFIgBAFIgDADIgEACg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.btn_txt, new cjs.Rectangle(-35,-6.6,70,13.3), null);


(lib.btn_round = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#35303E").s().p("AiMCNQg7g6AAhTQAAhSA7g6QA6g7BSAAQBTAAA6A7QA7A6AABSQAABTg7A6Qg6A7hTAAQhSAAg6g7g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.btn_round, new cjs.Rectangle(-20,-20,40,40), null);


(lib.btn_bg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#35303E").s().p("Al7DIQhTAAg5g6Qg7g5AAhTIAAgCQAAhSA7g6QA5g7BTAAIL3AAQBTAAA6A7QA6A6AABSIAAACQAABSg6A6Qg6A6hTAAg");
	this.shape.setTransform(-0.2,0);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.btn_bg, new cjs.Rectangle(-58.1,-20,115.8,40), null);


(lib.btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_4
	this.instance = new lib.btn_txt();
	this.instance.parent = this;
	this.instance.setTransform(0,8.9);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(12).to({_off:false},0).to({y:0.7,alpha:1},8).wait(1));

	// r_part
	this.instance_1 = new lib.r_part();
	this.instance_1.parent = this;
	this.instance_1.setTransform(10.1,0);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(9).to({_off:false},0).to({x:47.8},8,cjs.Ease.get(1)).to({_off:true},1).wait(3));

	// l_part
	this.instance_2 = new lib.l_part();
	this.instance_2.parent = this;
	this.instance_2.setTransform(-10,0);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(9).to({_off:false},0).to({x:-48.3},8,cjs.Ease.get(1)).to({_off:true},1).wait(3));

	// Слой_5
	this.instance_3 = new lib.btn_bg();
	this.instance_3.parent = this;
	this.instance_3.setTransform(0,0,0.01,1);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(9).to({_off:false},0).to({scaleX:1},8,cjs.Ease.get(1)).wait(4));

	// Слой_1
	this.instance_4 = new lib.btn_round();
	this.instance_4.parent = this;
	this.instance_4.setTransform(0,0,0.012,0.012);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({scaleX:1.2,scaleY:1.2},5,cjs.Ease.get(1)).to({scaleX:1,scaleY:1},4,cjs.Ease.quadInOut).to({_off:true},9).wait(3));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-0.2,-0.2,0.5,0.5);


(lib.banner = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{loop:65});

	// timeline functions:
	this.frame_165 = function() {
		this.gotoAndPlay('loop');
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(165).call(this.frame_165).wait(1));

	// btn
	this.instance = new lib.btn("synched",0,false);
	this.instance.parent = this;
	this.instance.setTransform(-65.3,-140.5,0.94,0.94,0,0,0,-0.8,-0.7);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(25).to({_off:false},0).wait(141));

	// t2
	this.instance_1 = new lib.t2();
	this.instance_1.parent = this;
	this.instance_1.setTransform(17,-219.1,1.019,1.019,0,0,0,0.2,-0.4);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(65).to({_off:false},0).to({regX:-0.2,x:-3.4,alpha:1},10).wait(30).to({alpha:0},10).to({_off:true},1).wait(50));

	// t1
	this.instance_2 = new lib.t1();
	this.instance_2.parent = this;
	this.instance_2.setTransform(-25.2,-222.6,1.019,1.019,0,0,0,-0.2,-0.5);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(15).to({_off:false},0).to({regX:-0.4,x:-45.6,alpha:1},10).wait(30).to({alpha:0},10).to({_off:true},1).wait(49).to({_off:false,regX:-0.2,x:-25.2},0).to({regX:-0.4,x:-45.6,alpha:1},10).wait(30).to({alpha:0},10).wait(1));

	// dev
	this.instance_3 = new lib.dev();
	this.instance_3.parent = this;
	this.instance_3.setTransform(109,473);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({x:-25,y:77},15,cjs.Ease.cubicOut).wait(151));

	// kv2
	this.instance_4 = new lib.kv2();
	this.instance_4.parent = this;
	this.instance_4.setTransform(262.7,-96.8,1,1,55.2,0,0,-0.2,2.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({rotation:0,x:13.7,y:37.9},15,cjs.Ease.cubicOut).wait(151));

	// kv1
	this.instance_5 = new lib.kv1();
	this.instance_5.parent = this;
	this.instance_5.setTransform(-318.8,257.2,1,1,-75,0,0,0,0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).to({rotation:0,x:-20.9,y:95.2},15,cjs.Ease.cubicOut).wait(151));

	// urText
	this.instance_6 = new lib.urText();
	this.instance_6.parent = this;
	this.instance_6.setTransform(-35.9,252.4);
	this.instance_6.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).to({alpha:1},15).wait(151));

	// logo
	this.instance_7 = new lib.lil_logo();
	this.instance_7.parent = this;
	this.instance_7.setTransform(51.2,259.5,0.135,0.136,0,0,0,1.1,0);
	this.instance_7.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).to({alpha:1},15).wait(151));

	// bg
	this.instance_8 = new lib.bgImg();
	this.instance_8.parent = this;
	this.instance_8.setTransform(-150,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(166));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-435.1,-300,834.3,1128.6);


// stage content:
(lib._300x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// cover
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#666666").ss(2,2,0,3).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// banner
	this.instance = new lib.banner();
	this.instance.parent = this;
	this.instance.setTransform(150.1,300.1,1,1,0,0,0,0.1,0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-135.1,299,834.3,1129.6);
// library properties:
lib.properties = {
	id: '0A6E3F5DF6B342F4AF907DBE848CDF8D',
	width: 300,
	height: 600,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/bgImg.jpg", id:"bgImg"},
		{src:"images/dev1.png", id:"dev1"},
		{src:"images/shadow.png", id:"shadow"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['0A6E3F5DF6B342F4AF907DBE848CDF8D'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;