(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.bgImg1 = function() {
	this.initialize(img.bgImg1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,300);


(lib.bgImg2 = function() {
	this.initialize(img.bgImg2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,300);


(lib.devs = function() {
	this.initialize(img.devs);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,150,316);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.urText = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AEsCkIAAhEIAIAAIAAAKQAIgLAMAAQAKAAAHAHQAHAIAAAMQAAALgHAIQgHAIgKAAQgNAAgHgLIAAAagAE5BrQgFAGAAAJQAAAJAFAFQAFAGAIAAQAIAAAFgGQAGgFAAgJQAAgIgGgHQgFgFgIAAQgHAAgGAFgAAPCkIAAhEIAIAAIAAAKQAIgLAMAAQAKAAAHAHQAHAIAAAMQAAALgHAIQgHAIgKAAQgNAAgHgLIAAAagAAcBrQgFAGAAAJQAAAJAFAFQAFAGAIAAQAIAAAFgGQAGgFAAgJQAAgIgGgHQgFgFgIAAQgHAAgGAFgAiHCkIAAhEIAIAAIAAAKQAIgLAMAAQAKAAAHAHQAHAIAAAMQAAALgHAIQgHAIgKAAQgNAAgHgLIAAAagAh6BrQgFAGAAAJQAAAJAFAFQAFAGAIAAQAIAAAFgGQAGgFAAgJQAAgIgGgHQgFgFgIAAQgHAAgGAFgAoqChIADgGQADACAFAAQADAAADgCQACgCACgFIgXg0IAIAAIATArIARgrIAIAAIgWA1QgCAHgFAFQgEADgGAAQgGAAgFgDgAuCCjIAAgPIg5AAIAAhGIAHAAIAAA/IAoAAIAAg/IAIAAIAAA/IAJAAIgBAWgAHVChIAAgNIgtAAIAAg0IAIAAIAAAtIAdAAIAAgtIAIAAIAAAtIAHAAIgBAUgAL6CRQgGgFAAgHQAAgJAGgEQAGgEAKAAQAKAAAGACIAAgCQAAgGgEgEQgDgEgIAAQgIAAgIAEIgCgGQAKgFAJAAQALAAAFAGQAGAFAAAKIAAAgIgIAAIAAgIQgHAJgLAAQgIAAgGgEgAMAB9QgEACAAAFQAAAFAEADQAEADAFAAQAHAAAFgEQAFgEAAgGIAAgFQgGgCgJAAQgHAAgEADgALECNQgIgIAAgLQAAgKAIgJQAIgIALAAQALAAAJAJIgFAFQgHgHgJAAQgHAAgGAGQgFAFAAAJQAAAIAFAGQAGAGAIAAQAIAAAHgIIAGAFQgJAKgMAAQgMAAgHgIgAJtCRQgGgFAAgHQAAgJAGgEQAGgEAKAAQAJAAAHACIAAgCQAAgGgEgEQgDgEgIAAQgIAAgIAEIgCgGQAKgFAJAAQALAAAFAGQAGAFAAAKIAAAgIgIAAIAAgIQgHAJgLAAQgIAAgGgEgAJzB9QgEACAAAFQAAAFAEADQAEADAFAAQAHAAAFgEQAFgEAAgGIAAgFQgGgCgJAAQgHAAgEADgAFxCRQgGgFAAgHQAAgJAGgEQAGgEAKAAQAJAAAHACIAAgCQAAgGgEgEQgDgEgIAAQgIAAgIAEIgCgGQAKgFAJAAQALAAAFAGQAGAFAAAKIAAAgIgIAAIAAgIQgHAJgLAAQgIAAgGgEgAF3B9QgEACAAAFQAAAFAEADQAEADAFAAQAHAAAFgEQAFgEAAgGIAAgFQgGgCgJAAQgHAAgEADgADJCNQgIgIAAgLQAAgKAIgJQAIgIALAAQALAAAJAJIgFAFQgHgHgJAAQgHAAgGAGQgFAFAAAJQAAAIAFAGQAGAGAIAAQAIAAAHgIIAGAFQgJAKgMAAQgMAAgHgIgACQCNQgIgIAAgLQAAgLAHgIQAIgIALAAQAMAAAJAJIgFAFQgGgHgJAAQgIAAgFAFQgFAEgBAHIAYAAIAAAHIgYAAQAAAGAGAGQAFAFAIAAQAJAAAGgIIAGAFQgFAFgFACQgDADgJAAQgLAAgHgIgABWCNQgHgHAAgMQAAgMAHgHQAHgIALAAQALAAAGAIQAHAHAAAMIAAADIgpAAQAAAHAGAGQAFAEAHAAQAKAAAGgHIAFAEQgJAKgMAAQgLAAgIgIgAB4B3QAAgHgFgGQgFgFgGAAQgHAAgFAFQgFAGAAAHIAhAAIAAAAgAkSCRQgGgFAAgHQAAgJAGgEQAGgEAKAAQAJAAAHACIAAgCQAAgGgEgEQgDgEgIAAQgIAAgIAEIgCgGQAKgFAJAAQALAAAFAGQAGAGAAAJIAAAgIgIAAIAAgIQgHAJgLAAQgIAAgGgEgAkMB9QgEACAAAFQAAAFAEADQAEADAFAAQAHAAAFgEQAFgEAAgGIAAgFQgGgCgJAAQgHAAgEADgAnsCRQgGgFAAgHQAAgJAGgEQAGgEAKAAQAKAAAGACIAAgCQAAgGgEgEQgDgEgIAAQgIAAgIAEIgCgGQAKgFAJAAQALAAAFAGQAGAFAAAKIAAAgIgIAAIAAgIQgHAJgLAAQgIAAgGgEgAnmB9QgEACAAAFQAAAFAEADQAEADAFAAQAHAAAFgEQAFgEAAgGIAAgFQgGgCgJAAQgHAAgEADgArGCRQgGgFAAgHQAAgJAGgEQAGgEAKAAQAJAAAHACIAAgCQAAgGgEgEQgDgEgIAAQgIAAgIAEIgCgGQAKgFAJAAQALAAAFAGQAGAGAAAJIAAAgIgIAAIAAgIQgHAJgLAAQgIAAgGgEgArAB9QgEACAAAFQAAAFAEADQAEADAFAAQAHAAAFgEQAFgEAAgGIAAgFQgGgCgJAAQgHAAgEADgAsaCRQgGgFAAgHQAAgJAGgEQAGgEAKAAQAJAAAHACIAAgCQAAgGgEgEQgDgEgIAAQgIAAgIAEIgCgGQAKgFAJAAQALAAAFAGQAGAGAAAJIAAAgIgIAAIAAgIQgHAJgLAAQgIAAgGgEgAsUB9QgEACAAAFQAAAFAEADQAEADAFAAQAHAAAFgEQAFgEAAgGIAAgFQgGgCgJAAQgHAAgEADgAm+CUIABgHIAEABIAEgBIADgDQACgDAAgDIACgMIAAgYIAlAAIAAA0IgIAAIAAgtIgVAAIgBAVIgCANQgCAFgCACIgFAEIgFAAgAOzCUIAAgLIAKAAIAAALgAOaCUIAAg0IAIAAIAAA0gAN3CUIAAgtIgTAAIAAgHIAtAAIAAAHIgSAAIAAAtgANXCUIAAgpIgeApIgIAAIAAg0IAIAAIAAApIAfgpIAHAAIAAA0gAJYCUIAAgXIgeAAIAAAXIgIAAIAAg0IAIAAIAAAWIAeAAIAAgWIAHAAIAAA0gAH9CUIAAg0IAIAAIAAA0gAHiCUIAAg0IAIAAIAAA0gAEKCUIAAgtIgTAAIAAgHIAtAAIAAAHIgTAAIAAAtgAgeCUIAAgpIgeApIgIAAIAAg0IAIAAIAAApIAfgpIAHAAIAAA0gAibCUIAAgtIgdAAIAAAtIgIAAIAAg0IAtAAIAAA0gAknCUIAAgXIgeAAIAAAXIgIAAIAAg0IAIAAIAAAWIAeAAIAAgWIAHAAIAAA0gAl8CUIAAg0IAIAAIAAATIAOAAQAJAAAFAEQAGAEAAAIQAAAIgFAEQgFAFgJAAgAl0CNIAOAAQAGAAADgDQADgCAAgFQAAgFgDgCQgDgCgGAAIgOAAgApJCUIAAgtIgTAAIAAgHIAtAAIAAAHIgTAAIAAAtgApqCUIgSgYIgLALIAAANIgIAAIAAg0IAIAAIAAAeIAcgeIAKAAIgWAWIAWAegAsvCUIAAgXIgeAAIAAAXIgIAAIAAg0IAIAAIAAAWIAeAAIAAgWIAHAAIAAA0gAtvCUIAAg0IAIAAIAAA0gAM/BVQgEgDgBgGIAFgBQACAHAHAAQAGAAADgHIAFABQgBAGgEADQgEAEgFAAQgFAAgEgEgAIFBYIAAgJIAJAAIAAAJgAH0BYIAAgJIAJAAIAAAJgAOZBVIAAgJIAJAAIAAAJgAHhBVIAAgJIAJAAIAAAJgAtwBVIAAgJIAJAAIAAAJgAuRAsIAAhDIAHAAIAAAKQAJgLALAAQAKAAAIAHQAHAIAAALQAAALgHAIQgIAIgKAAQgMAAgIgLIAAAagAuEgMQgGAGAAAIQAAAJAGAFQAFAGAIAAQAIAAAFgGQAFgFAAgJQAAgHgFgHQgGgFgHAAQgIAAgFAFgAAsApIAAgNIgqAAIgCANIgFAAIAAgUIAFAAQAHgNAAgWIAAgJIAkAAIAAAsIAIAAIAAAAIAEABIADgBIADgDQACgDABgDIABgMIABgXIAlAAIAAAzIgIAAIAAgsIgWAAIgBAUIgCANQgBAFgDACIgEAEIgGAAIgFAAIgBANgAAOgJQAAATgGALIAcAAIAAglIgWAAgAOiAVQgHgIAAgNIAAgIIABgHIACgHIADgGIAFgFQAEgDAEAAIAdgHIABAGIgcAHQgIADgDAEQgDAFgBAHQAHgLAPAAQAKAAAHAHQAHAHAAAKQAAALgHAIQgIAIgLAAQgMAAgHgIgAOogKQgFAFAAAHQAAAJAFAFQAFAGAIAAQAIAAAFgGQAGgFAAgJQAAgHgGgFQgFgGgIAAQgIAAgFAGgANNAVQgIgIAAgLQAAgJAIgJQAIgIALAAQAMAAAJAJIgFAFQgIgHgIAAQgIAAgFAGQgGAFAAAIQAAAIAGAGQAFAGAIAAQAJAAAHgIIAFAFQgIAKgNAAQgLAAgIgIgAMUAVQgIgIAAgLQAAgJAIgJQAIgIALAAQAMAAAIAIQAHAIAAAKQAAALgHAIQgIAIgMAAQgLAAgIgIgAMagLQgGAFAAAIQAAAIAGAGQAGAGAHAAQAJAAAFgGQAFgFAAgJQAAgIgFgFQgFgGgJAAQgIAAgFAGgAGwAVQgIgIAAgLQAAgJAIgJQAIgIALAAQAMAAAIAIQAHAIAAAKQAAALgHAIQgIAIgMAAQgLAAgIgIgAG2gLQgGAFAAAIQAAAIAGAGQAGAGAHAAQAJAAAFgGQAFgFAAgJQAAgIgFgFQgFgGgJAAQgIAAgFAGgAEFAVQgIgIAAgLQAAgJAIgJQAIgIALAAQAMAAAIAIQAHAIAAAKQAAALgHAIQgIAIgMAAQgLAAgIgIgAELgLQgGAFAAAIQAAAIAGAGQAGAGAHAAQAJAAAFgGQAGgGAAgIQAAgHgGgGQgFgGgJAAQgIAAgFAGgAo3AVQgIgHAAgMQAAgLAIgHQAHgIAKAAQAMAAAGAIQAGAHAAALIAAADIgpAAQABAHAFAGQAGAEAGAAQAKAAAHgHIAFAEQgJAKgNAAQgLAAgHgIgAoVAAQgBgHgEgGQgFgFgHAAQgGAAgFAFQgFAGgBAHIAiAAIAAAAgAqsAZQgFgFAAgHQAAgJAGgEQAGgDAKAAQAIAAAIACIAAgCQAAgGgEgEQgEgEgIAAQgIAAgHAEIgDgGQAKgFAJAAQALAAAGAGQAFAGAAAJIAAAfIgHAAIAAgIQgHAJgMAAQgHAAgHgEgAqlAFQgEACAAAFQAAAFADADQAEADAGAAQAGAAAGgEQAFgEAAgGIAAgFQgHgCgIAAQgHAAgEADgAsaAVIAEgGQAIAHAJAAQAFAAAEgCQAEgDAAgEQAAgEgEgCQgCgCgHAAIgHAAIAAgGIAHAAQAEAAAEgCQADgCAAgFQAAgDgDgCQgCgCgGAAQgJAAgHAFIgDgGQAJgGALAAQAIAAAFAEQAFADAAAHQAAAIgIADQAKADAAAJQAAAHgGAEQgGAFgJAAQgLAAgKgIgAHcAcIABgHIAEABIADgBIADgDQACgDABgDIACgjIAlAAIAAAzIgIAAIAAgsIgWAAIgBAUIgCANQgBAFgDACIgEAEIgGAAgAj7AcIABgHIAEABIADgBIADgDQACgDABgDIACgjIAlAAIAAAzIgIAAIAAgsIgWAAIAAABIgBATIgCANQgCAGgCABIgEAEIgGAAgAPVAcIAAgLIAJAAIAAALgAOCAcIAAgzIAIAAIAAAzgALgAcIgQgVIgQAVIgJAAIAUgbIgTgYIAJAAIAPAUIAPgUIAJAAIgUAYIAVAbgAKhAcIAAgzIAIAAIAAAzgAKNAcIAAgXIgeAAIAAAXIgHAAIAAgzIAHAAIAAAWIAeAAIAAgWIAIAAIAAAzgAJFAcIAAgsIgSAAIAAgHIAtAAIAAAHIgTAAIAAAsgAIeAcIAAgzIAIAAIAAAzgAGYAcIAAgXIgeAAIAAAXIgHAAIAAgzIAHAAIAAAWIAeAAIAAgWIAIAAIAAAzgAE6AcIAAgzIAZAAQAHAAAFADQAFAEAAAGQAAAIgJADQALADAAAKQAAAGgFAEQgFAEgIAAgAFBAVIASAAQAFAAADgCQADgCAAgFQAAgEgDgBQgEgDgFAAIgRAAgAFBgBIAQAAQAFAAADgCQADgCAAgEQAAgEgDgBQgCgCgGAAIgQAAgADtAcIAAgsIgeAAIAAAsIgHAAIAAgzIAtAAIAAAzgACVAcIAAgTIgOAAIgOATIgKAAIAQgUQgFgBgFgFQgEgDAAgGQAAgHAFgFQAGgEAJAAIAYAAIAAAzgAB8gOQgDADAAAEQAAAFADACQADACAGAAIAQAAIAAgSIgQAAQgFAAgEACgAgrAcIAAgoIgfAoIgHAAIAAgzIAHAAIAAAoIAfgoIAIAAIAAAzgAhlAcIgTgYIgLALIAAANIgHAAIAAgzIAHAAIAAAdIAdgdIAJAAIgVAWIAWAdgAi5AcIAAgzIAHAAIAAATIAOAAQAJAAAGAEQAGADAAAIQAAAIgGAEQgFAFgJAAgAiyAVIAOAAQAHAAADgDQADgCAAgFQAAgFgEgCQgCgCgHAAIgOAAgAkNAcIAAgzIAIAAIAAAzgAkwAcIAAgsIgSAAIAAgHIAsAAIAAAHIgSAAIAAAsgAlqAcIAAgoIgfAoIgHAAIAAgzIAHAAIAAAoIAfgoIAIAAIAAAzgAmjAcIAAgoIgfAoIgHAAIAAgzIAHAAIAAAoIAfgoIAIAAIAAAzgAndAcIAAgXIgeAAIAAAXIgHAAIAAgzIAHAAIAAAWIAeAAIAAgWIAIAAIAAAzgApTAcIAAgWIgJAEIgJABQgHAAgFgEQgFgEAAgGIAAgUIAIAAIAAATQAAAEADACQACACAFAAQAJAAAIgEIAAgXIAHAAIAAAzgArBAcIAAgXIgeAAIAAAXIgHAAIAAgzIAHAAIAAAWIAeAAIAAgWIAIAAIAAAzgAsoAcIAAgoIgfAoIgHAAIAAgzIAHAAIAAAoIAfgoIAIAAIAAAzgAuuAcIAAg+IgnAAIAAA+IgIAAIAAhFIA3AAIAABFgAmDgiQgEgDgBgGIAGgBQABAHAHAAQAHAAACgHIAFABQAAAGgEADQgFAEgFAAQgEAAgFgEgAOCgiIAAgJIAJAAIAAAJgAKhgiIAAgJIAJAAIAAAJgAIegiIAAgJIAJAAIAAAJgAkNgiIAAgJIAJAAIAAAJgADjhOIACgGQAEACAEAAQADAAADgCQADgCACgFIgYg0IAJAAIATArIAQgrIAJAAIgWA1QgDAHgEAFQgFADgFAAQgGAAgFgDgARmhLIAAhEIAHAAIAAAKQAJgLALAAQAKAAAIAHQAHAIAAAMQAAALgHAIQgIAIgKAAQgMAAgIgLIAAAagARziEQgGAGAAAJQAAAJAGAFQAFAGAIAAQAIAAAFgGQAFgFAAgJQAAgIgFgHQgGgFgHAAQgIAAgFAFgAGOhLIAAhEIAHAAIAAAKQAJgLALAAQAKAAAIAHQAHAIAAAMQAAALgHAIQgIAIgKAAQgMAAgIgLIAAAagAGbiEQgGAGAAAJQAAAJAGAFQAFAGAIAAQAIAAAFgGQAFgFAAgJQAAgIgFgHQgGgFgHAAQgIAAgFAFgAyJhLIAAhEIAHAAIAAAKQAJgLALAAQALAAAGAHQAIAIAAAMQAAAMgIAHQgGAIgLAAQgMAAgIgLIAAAagAx8iEQgGAGAAAJQAAAJAGAFQAFAGAIAAQAIAAAFgGQAFgFAAgJQAAgJgFgGQgGgFgHAAQgIAAgFAFgAQehOIAAgNIgqAAIgCANIgGAAIAAgUIAGAAQAHgNAAgXIAAgJIAkAAIAAAtIAIAAIgBAUgAQAiBQAAATgGAMIAcAAIAAgmIgWAAgAMphOIAAgNIgqAAIgCANIgGAAIAAgUIAGAAQAHgNAAgXIAAgJIAkAAIAAAtIAIAAIAAAAIAEABIADgBIADgDQACgDABgDIABgMIABgYIAlAAIAAA0IgIAAIAAgtIgWAAIAAABIgDAhQgBAFgDACQgCADgCABIgGAAIgFAAIgBANgAMLiBQAAATgGAMIAcAAIAAgmIgWAAgApThiQgKAIgNAAQgPAAgKgLQgKgLAAgOQAAgPAKgLQAKgKAQAAQAQAAAJAKQAKALAAAPQAAANgIAKIAJAIIgFAGgAp9iTQgIAJAAAMQAAAMAIAIQAIAJAMAAQAJAAAHgGIgNgLIAFgGIANAMQAGgHAAgLQAAgMgIgJQgHgIgNAAQgLAAgIAIgASthiQgIgIAAgLQAAgKAIgJQAIgIALAAQAMAAAIAIQAHAIAAALQAAALgHAIQgIAIgMAAQgLAAgIgIgASziDQgGAFAAAJQAAAIAGAGQAGAGAHAAQAJAAAFgGQAFgFAAgJQAAgJgFgFQgFgGgJAAQgIAAgFAGgAQxhiQgIgIAAgLQAAgKAIgJQAIgIALAAQAMAAAIAIQAHAIAAALQAAALgHAIQgIAIgMAAQgLAAgIgIgAQ3iDQgGAFAAAJQAAAIAGAGQAGAGAHAAQAJAAAFgGQAGgGAAgIQAAgIgGgGQgFgGgJAAQgIAAgFAGgAPAhiIAEgGQAIAHAJAAQAFAAAEgCQAEgDAAgEQAAgEgEgCQgCgCgHAAIgHAAIAAgHIAHAAQAEAAAEgCQADgCAAgFQAAgDgDgCQgCgCgGAAQgJAAgHAFIgDgGQAJgGALAAQAIAAAFAEQAFADAAAHQAAAIgIAEQAKADAAAJQAAAHgGAEQgFAFgKAAQgLAAgKgIgAIFhiIAEgGQAIAHAJAAQAFAAAEgCQAEgDAAgEQAAgEgEgCQgCgCgHAAIgHAAIAAgHIAHAAQAEAAAEgCQADgCAAgFQAAgDgDgCQgCgCgGAAQgJAAgHAFIgDgGQAJgGALAAQAIAAAFAEQAFADAAAHQAAAIgIAEQAKADAAAJQAAAHgGAEQgFAFgKAAQgLAAgKgIgAEjhiQgIgIAAgLQAAgKAIgJQAIgIALAAQAMAAAJAJIgFAFQgIgHgIAAQgIAAgFAGQgGAFAAAJQAAAIAGAGQAFAGAIAAQAJAAAHgIIAFAFQgIAKgNAAQgLAAgIgIgACWhiQgIgIAAgLQAAgLAIgIQAIgIAKAAQANAAAIAJIgEAFQgHgHgJAAQgHAAgFAFQgFAEgCAHIAYAAIAAAHIgYAAQABAHAGAFQAFAFAHAAQAJAAAHgIIAFAFQgEAFgFACQgEADgIAAQgLAAgIgIgABaheQgFgFAAgHQAAgJAGgEQAGgEAKAAQAIAAAIACIAAgCQAAgGgEgEQgEgEgIAAQgIAAgHAEIgDgGQAKgFAJAAQALAAAGAGQAFAGAAAJIAAAgIgHAAIAAgIQgHAJgMAAQgHAAgHgEgABhhyQgEACAAAFQAAAFADADQAEADAGAAQAGAAAGgEQAFgEAAgGIAAgFQgHgCgIAAQgHAAgEADgAgRhhQgHgGgBgLIgMAAIAAAXIgHAAIAAg0IAHAAIAAAWIAMAAQABgKAHgGQAIgHAJAAQALAAAHAIQAHAIAAALQAAALgHAIQgIAIgKAAQgLAAgGgHgAgNiDQgEAFAAAJQAAAJAFAFQAEAGAIAAQAHAAAFgGQAFgGAAgIQAAgJgFgFQgFgGgHAAQgHAAgGAGgAlghiQgIgHAAgMQAAgMAIgHQAHgIAKAAQAMAAAGAIQAGAHAAAMIAAADIgpAAQABAHAFAGQAGAEAGAAQAKAAAHgHIAFAEQgJAKgNAAQgLAAgHgIgAk+h4QgBgHgEgGQgFgFgHAAQgGAAgFAFQgFAGgBAHIAiAAIAAAAgAn1hlIAFgGQAHAFAFACQAGADAGAAQAHAAAFgEQAEgDAAgFQAAgGgEgDQgDgCgLgDQgNgDgFgEQgGgFAAgIQAAgJAHgFQAGgFAKAAQAOAAALAIIgFAGQgJgHgLAAQgHAAgEADQgEADAAAFQAAAGAEACQADADAMADQAMADAFAEQAGAEAAAJQAAAJgHAFQgHAGgKAAQgPAAgOgLgAo2hlQgKgLAAgOQAAgPAKgLQAKgKAQAAQAQAAAJAKQAKALAAAPQAAAOgKALQgKALgQAAQgPAAgKgLgAowiTQgIAJAAAMQAAAMAIAIQAIAJAMAAQAMAAAHgJQAIgIAAgMQAAgMgIgJQgHgIgNAAQgLAAgIAIgAukheQgFgFAAgHQAAgJAGgEQAGgEAKAAQAIAAAIACIAAgCQAAgGgEgEQgEgEgIAAQgIAAgHAEIgDgGQAKgFAJAAQALAAAGAGQAFAGAAAJIAAAgIgHAAIAAgIQgHAJgMAAQgHAAgHgEgAudhyQgEACAAAFQAAAFADADQAEADAGAAQAGAAAGgEQAFgEAAgGIAAgFQgHgCgIAAQgHAAgEADgAwJhiQgIgIAAgLQAAgKAIgJQAIgIALAAQAMAAAJAJIgFAFQgIgHgIAAQgIAAgFAGQgGAFAAAJQAAAIAGAGQAFAGAIAAQAJAAAHgIIAFAFQgIAKgNAAQgLAAgIgIgAy+hiQgIgIAAgLQAAgKAIgJQAIgIALAAQAMAAAIAIQAHAIAAALQAAALgHAIQgIAIgMAAQgLAAgIgIgAy4iDQgGAFAAAJQAAAIAGAGQAGAGAHAAQAJAAAFgGQAFgFAAgJQAAgJgFgFQgFgGgJAAQgIAAgFAGgAhuhbIABgHIAEABIADgBIADgDQACgDABgDIACgkIAlAAIAAA0IgIAAIAAgtIgWAAIAAABIgBAUIgCANQgCAGgCABQgCADgCABIgGAAgAVkhbIAAgLIAJAAIAAALgAVNhbIAAgTIgOAAIgOATIgKAAIAQgUQgFgBgFgFQgEgEAAgGQAAgHAFgFQAGgEAJAAIAYAAIAAA0gAU0iGQgDADAAAEQAAAFADADQADACAGAAIAQAAIAAgTIgQAAQgFAAgEACgATihbIAAg0IAZAAQAGAAAGADQAFAEAAAGQAAAIgJAEQALADAAAKQAAAGgFAEQgFAEgIAAgATphiIASAAQAFAAADgCQAEgDAAgEQAAgDgEgCQgEgDgFAAIgRAAgATph5IAQAAQAFAAADgCQADgCAAgEQAAgEgDgBQgCgCgGAAIgQAAgAOShbIAAgTIgOAAIgOATIgKAAIAQgUQgFgBgFgFQgEgEAAgGQAAgHAFgFQAGgEAJAAIAYAAIAAA0gAN5iGQgDADAAAEQAAAFADADQADACAGAAIAQAAIAAgTIgQAAQgFAAgEACgALRhbIAAgpIgfApIgHAAIAAg0IAHAAIAAApIAfgpIAIAAIAAA0gAKXhbIgTgYIgLALIAAANIgHAAIAAg0IAHAAIAAAeIAdgeIAJAAIgVAWIAWAegAJfhbIAAgpIgfApIgHAAIAAg0IAHAAIAAApIAfgpIAIAAIAAA0gAH3hbIAAgpIgfApIgHAAIAAg0IAHAAIAAApIAfgpIAIAAIAAA0gAFYhbIAAg0IAIAAIAAA0gABAhbIAAgWQgCACgGACIgJABQgHAAgFgEQgFgEAAgHIAAgUIAIAAIAAATQAAAEADADQACACAFAAQAKAAAGgEIAAgYIAIAAIAAA0gAh5hbIgTgYIgLALIAAANIgHAAIAAg0IAHAAIAAAeIAdgeIAJAAIgVAWIAWAegAixhbIAAgpIgfApIgHAAIAAg0IAHAAIAAApIAfgpIAIAAIAAA0gAkQhbIAAg0IAZAAQAHAAAFADQAFAEAAAGQAAAIgJAEQALADAAAKQAAAGgFAEQgFAEgIAAgAkJhiIASAAQAFAAADgCQADgCAAgFQAAgEgDgBQgEgDgFAAIgRAAgAkJh5IAQAAQAFAAADgCQADgCAAgEQAAgEgDgBQgCgCgGAAIgQAAgAl4hbIAAgXIgeAAIAAAXIgHAAIAAg0IAHAAIAAAWIAeAAIAAgWIAIAAIAAA0gAqkhbIAAhGIAIAAIAABGgArZhbIAAgTIgOAAIgOATIgKAAIAQgUQgFgBgFgFQgEgEAAgGQAAgHAFgFQAGgEAJAAIAYAAIAAA0gAryiGQgDADAAAEQAAAFADADQADACAGAAIAQAAIAAgTIgQAAQgFAAgEACgAsOhbIAAgXIgeAAIAAAXIgHAAIAAg0IAHAAIAAAWIAeAAIAAgWIAIAAIAAA0gAtHhbIAAgXIgeAAIAAAXIgHAAIAAg0IAHAAIAAAWIAeAAIAAgWIAIAAIAAA0gAvIhbIAAgtIgSAAIAAgHIAsAAIAAAHIgSAAIAAAtgAwghbIAAgpIgfApIgHAAIAAg0IAHAAIAAApIAfgpIAIAAIAAA0gAzMhbIgTgYIgLALIAAANIgHAAIAAg0IAHAAIAAAeIAdgeIAJAAIgVAWIAWAegA0EhbIAAgpIgfApIgHAAIAAg0IAHAAIAAApIAfgpIAIAAIAAA0gA1shbIAAhGIAeAAQAMAAAGAGQAFAFAAAGQAAALgMAGQAPAEAAANQAAAJgGAFQgJAFgKAAgA1khiIAXAAQAIAAAFgEQAEgDAAgGQAAgGgEgDQgEgDgKAAIgWAAgA1kiCIAUAAQAIAAAEgDQAFgEAAgGQAAgFgEgDQgFgDgHAAIgVAAgAUZiGIADgbIAJAAIAAAAIgIAbgAFYiaIAAgJIAJAAIAAAJg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.urText, new cjs.Rectangle(-138.8,-16.4,277.8,32.8), null);


(lib.t2_2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACRCfIAfggQArAvA5AAQA5AAAtgtQAagYAQglQATglADgjQgSAZggATQggATgoAAQg7AAglgjQglgiAAg1QABg/AwgtQAvgtBFAAQA/AAAnAmQAqArAABMQgBBAgWA4QgXA5gnAnQg8A8hNAAQhNAAg0g6gAENiPQggAfAAAtQgBAkAZAZQAZAYAtgBQAxAAAhgeQAggfAAgrQABgmgZgXQgagbgsAAQgxAAghAggAjqCfIAgggQArAvA4AAQA5AAAtgtQAZgYAQglQATglADgjQgRAZggATQggATgnAAQg9AAgkgjQglgiAAg1QACg/AugtQAwgtBFAAQA+AAAnAmQApArAABMQAABAgWA4QgXA5gnAnQg8A8hMAAQhNAAg0g6gAhuiPQggAfAAAtQgBAkAZAZQAZAYAtgBQAwAAAhgeQAggfABgrQAAgmgZgXQgagbgrAAQgxAAghAggApmCfIAgggQArAvA5AAQA4AAAtgtQAZgYASglQARglAEgjQgTAageASQghATgnAAQg9AAgkgjQgkgiAAg1QABg/AugtQAwgtBFAAQA/AAAnAmQApAqAABNQAABAgWA4QgWA4gnAoQg+A8hMAAQhNAAg0g6gAnqiPQggAfAAAtQAAAkAYAZQAZAYAtgBQAyAAAggeQAhgfAAgrQAAglgYgYQgcgbgrAAQgxAAghAggAsaDSIBjlyIhVAZIgBgpIBwgkIAjAAIhxGmgAJnhpIAZhfIARAAIgDAJQALgLANAAQAMABAIAIQAIAIAAAOQAAAUgMAMQgMANgRAAQgQAAgIgOIgJAjgAKNiyQgIAJAAALQAAAHAFAGQAFAFAIAAQALAAAHgIQAHgJAAgMQAAgJgEgEQgFgFgIAAQgKAAgIAJgAL3h/IAIgeIggAAIgIAeIgRAAIAUhJIAQAAIgHAdIAgAAIAHgdIARAAIgTBJgAIwh/IAUhJIAzAAIgEAOIgjAAIgPA7g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t2_2, new cjs.Rectangle(-79.5,-21.7,159,43.4), null);


(lib.t2_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAGC1QgpgqAAhKQAAhBAXg6QAVg4AngoQA9g8BOAAQBMAAAwA2IgfAgQgogrg5AAQg4AAgtAsQgaAbgRAkQgSAmgEAkQATgZAggSQAfgSAnABQA8AAAlAiQAkAiAAAzQAAA9gvAtQgwAthEAAQhAAAgmgngAAuAUQggAdAAApQAAAnAYAWQAZAbAuAAQAwAAAhgfQAggfAAgrQAAgjgYgYQgZgYgsAAQgyAAghAegAl1C1QgqgqAAhKQAAhBAXg6QAWg4AngoQA9g8BOAAQBMAAAwA2IgfAgQgogrg5AAQg4AAgtAsQgaAbgRAkQgSAmgEAkQATgZAggSQAfgSAnABQA8AAAlAiQAkAiAAAzQAAA9gvAtQgwAthEAAQhAAAgmgngAlNAUQggAdAAApQAAAnAYAWQAZAbAuAAQAwAAAhgfQAggfAAgrQAAgjgYgYQgZgYgsAAQgyAAghAegApwDUIBjlxIhWAZIgBgqIBxgkIAjAAIhxGmgAIIAgQgKgJAAgOQAAgRANgNQANgMARAAQAVAAAJAQIgNAJQgEgGgEgCQgDgDgHAAQgKAAgIAIQgHAKAAAKQAAAIAFAFQAFAFAHAAQAKAAAJgIIAJALQgNALgPAAQgOABgKgKgAHSAoIAThIIARAAIgUBIgAGmAoIANgwIggAfIgOgeIgNAvIgQAAIAThIIAPAAIAOAhIAgghIASAAIgTBIgAHogrIAEgQIASAAIgEAQgAFZhYIAAgGIEYAAIAAAGgAGzh6IAZhfIARAAIgDAJQALgKAMgBQANAAAIAJQAIAIAAAPQAAASgNANQgLANgRAAQgRAAgHgOIgKAjgAHZjDQgIAIAAAMQAAAHAFAGQAFAFAIAAQAKAAAIgJQAHgJAAgLQAAgIgEgGQgGgEgHAAQgKAAgIAJgAJDiRIAIgeIggAAIgIAeIgRAAIAThIIARAAIgIAdIAhAAIAHgdIARAAIgTBIgAF8iRIAThIIAzAAIgDAOIgjAAIgQA6g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t2_1, new cjs.Rectangle(-62.5,-21.9,125.1,43.9), null);


(lib.t2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACjAnQgPgQAAgXQAAgVAPgQQAQgQAYAAQAXAAAQAQQAPAPAAAWQAAAXgPAPQgQAQgYAAQgXAAgQgPgACxgZQgKALAAAOQAAAQAKALQAKALAQAAQAPAAAKgLQAKgLAAgQQAAgOgKgLQgKgLgQAAQgPAAgKALgAqRAnQgPgPAAgYQAAgVAPgQQAQgQAXAAQAXAAASAOIgMAOQgNgLgQAAQgPAAgKALQgKALAAAOQAAARAKAKQAKALAQAAQAPAAALgIIAAgUIgbAAIAAgPIAsAAIAAArQgSAQgZAAQgZAAgPgPgAsPAnQgQgQAAgXQAAgVAQgQQAQgQAYAAQAXAAAQAQQAPAPAAAWQAAAXgPAPQgQAQgYAAQgYAAgPgPgAsBgZQgKALAAAOQAAAQAKALQAKALAQAAQAPAAAKgLQAKgLAAgQQAAgOgKgLQgKgLgQAAQgPAAgKALgAHgA1IgahKIgaBKIgQAAIglhoIAUAAIAZBNIAahOIAQAAIAaBOIAZhNIATAAIglBogANsA1IAAgVIAUAAIAAAVgAMBA1IAAhoIAnAAQAZAAAQAPQAPAPAAAVQAAAXgPAPQgQAPgZAAgAMUAkIAUAAQARAAAKgKQAKgKAAgQQAAgOgKgKQgKgKgRAAIgUAAgALWA1IgaglIgXAAIAAAlIgSAAIAAhoIAvAAQASAAAKAJQALAJAAAPQAAAYgZAHIAcAogAKlAAIAbAAQAWAAAAgRQAAgRgWAAIgbAAgAJrA1IgLgaIgyAAIgKAaIgTAAIAuhpIARAAIAuBpgAJZALIgSgpIgSApIAkAAgAFaA1IgaglIgXAAIAAAlIgSAAIAAhoIAvAAQASAAAKAJQALAJAAAPQAAAYgZAHIAcAogAEpAAIAbAAQAWAAAAgRQAAgRgWAAIgbAAgAA1A1IAAhoIBOAAIAAARIg7AAIAAAcIA1AAIAAAQIg1AAIAAArgAggA1IAAgVIAUAAIAAAVgAhHA1IgaglIgXAAIAAAlIgTAAIAAhoIAvAAQATAAAKAJQAKAJAAAPQAAAYgZAHIAdAogAh4AAIAbAAQAKAAAGgEQAFgFAAgIQAAgRgVAAIgbAAgAjuA1IAAhoIBOAAIAAAQIg7AAIAAAcIA0AAIAAAPIg0AAIAAAcIA8AAIAAARgAkdA1IAAgtIgyAAIAAAtIgSAAIAAhoIASAAIAAArIAyAAIAAgrIATAAIAABogAmrA1IAAhXIghAAIAAgRIBVAAIAAARIghAAIAABXgAooA1IAAhoIBOAAIAAAQIg7AAIAAAcIA1AAIAAAPIg1AAIAAAcIA8AAIAAARgAteA1IAAhXIghAAIAAgRIBVAAIAAARIghAAIAABXg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t2, new cjs.Rectangle(-89.5,-5.4,179.1,10.9), null);


(lib.t1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AqNBXQgdATgiAAQgpAAgagaQgZgaAAgnQAAgfAPgdQARgeAbgRQAdgSAhAAQAoAAAbAaQAaAaAAAnQAAAYgMAaQgKAYgUATIAVAXIgTAOgArhhJQgXAPgLAYQgNAZAAAYQAAAeATAUQATAUAfAAQAaAAAWgQIgggmIATgOIAeAmQAfgfAAgqQAAgegTgUQgSgUggAAQgbAAgWAPgALWBQQgagaAAgnQAAgfAQgdQASgeAagRQAdgSAiAAQAoAAAaAaQAaAaAAAnQAAAfgQAdQgPAdgeASQgcASghAAQgpAAgagagAMEhJQgXAPgMAYQgMAZAAAYQAAAeATAUQATAUAfAAQAaAAAXgPQAWgPANgYQAMgYAAgZQAAgegTgUQgSgUggAAQgbAAgWAPgAgaBfQgTgKgJgUIASgMQASAgAmAAQAZAAAQgOQAQgMAAgVQAAgSgOgJQgOgJgaAAIgJAAIgDgMIBUhLIhmAAIAGgVICHAAIgEARIhWBLQAaACAQAMQAQANAAAXQAAAegZAUQgYAUgiAAQgbAAgSgLgAoVBQQgagaAAgnQAAgfAQgdQARgeAbgRQAdgSAiAAQAoAAAaAaQAaAaAAAnQAAAfgQAdQgPAdgeASQgcASghAAQgpAAgagagAnnhJQgXAPgMAYQgMAZAAAYQAAAeATAUQATAUAfAAQAaAAAXgPQAWgPAMgYQANgYAAgZQAAgegTgUQgSgUggAAQgbAAgWAPgAHrBXQgTgSAAgeQAAgRAEgQIAehwIAYAAIggB2QgDALAAANQAAAVAOAOQAOANAbAAQAcAAATgTQATgTAIghIAgh3IAYAAIgiB8QgKAngWAXQgaAagoAAQglAAgUgTgAlLBCIASgOQAbAgAqAAQAXAAAOgLQAQgLAAgRQAAgLgKgKQgKgJgYgIQgfgMgNgMQgNgMAAgUQAAgZAWgSQAVgRAjAAQAuAAAcAfIgRAQQgZgagjAAQgXAAgNALQgOALAAAPQAAAMAKAIQAKAJAbAJQAdAMALALQAOANAAATQAAAbgXATQgWASgjAAQg5AAgcgogADfBnIA5jRIAyAAQA2AAAcAbQAWAYABAlQAAAvgiAiQgnAohEAAgAD9BRIAsAAQA2AAAgghQAbgaAAgnQAAgdgSgRQgWgWgqAAIgeAAgAuSBnIA4jRIAYAAIg5DRg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1, new cjs.Rectangle(-91.5,-11.1,183,22.3), null);


(lib.logo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhwByIglgkIh3AAQgcAAgTgFQgYgGgOgNQgTgTAAgjIAAhlQgBgHAGgFQAEgEAIAAICDAAQAdAAASAGQAZAEAOAOQASARABAlIAABkIAdAeQAEAEABAGQgBAGgFAFQgFAFgGAAQgGAAgEgDgAlTAAQABAZANAMIABABQANAKAaACICEAAIAAhZQgBgZgLgMIgDgCQgMgKgbgBIiEAAgAEoBNQglgBgRgLQgMgIgDgPIAAgEQABgGAEgEQAFgDAFAAQAHAAAFADQADADACAEIABADQAFAGAHADQAIADAPAAIBHAAQAnAAAMgGQAFgCACgHQACgFABgJIAAgCQgBgOgFgFQgKgHgZAAIhgAAQghABgOgMQgNgNAAgaIAAgMQAAgXARgMQAVgMA1gBIA0AAQAqAAASALQAPAJACAQIAAADQAAAGgDADQgGAFgGAAQgGAAgFgEQgEgCgBgEIgBgDQgFgIgMgCQgJgCgYgBIg1AAQghAAgKAGQgKAEAAAQIAAAHQAAAMAGAGQAIAFAWAAIBSAAQAoAAARAJQAWAMAAAiQAAAlgeAMQgRAHgmAAgAAgBNQguAAgYgOQghgRAAguIAAgnQAAgvAhgSQAYgNAuAAIAtAAQAvAAAYANQAgASAAAvIAAAnQAAAuggARQgYAOgvAAgAgVhQQgRANAAAdIAAAmQAAAcARAMQAOAKAdAAIBAAAQAeAAAPgKQARgMAAgcIAAgmQAAgdgRgNQgPgKgeAAIhAAAQgdAAgOAKgAnFBJQgFgFAAgHIAAihQAAgIAFgDQAEgGAHAAQAIAAAEAGQAEADABAIIAAChQgBAHgEAFQgEAEgIAAQgHAAgEgEg");
	this.shape.setTransform(2.6,0.5,1,1,0,0,0,0.6,0);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.logo, new cjs.Rectangle(-43.9,-11.2,91.8,23.5), null);


(lib.dev_3duo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(126,114,104,0.6)").s().p("AgpAiQgMgBgCgJQgCgHAGgIQAFgIAKgDQAJgDAJABQAJACAFAEQAFAHgBAIQgBAEgGAEQgEAEgLADQgJACgGAAIgEAAgAAKADQgJgFADgKQACgIAJgEIAQgGQAGgDAEAAQAIgBAFAHQAEAFgCAJQgBAHgHAGQgFADgEACQgEACgJAAQgKAAgGgEg");
	this.shape.setTransform(-40.9,12.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(126,114,104,0.6)").s().p("AgTAQQgJgGADgKQACgGAJgFIAPgGQAGgDAEAAQAIgBAFAHQAEAGgCAIQgBAGgHAGQgFAFgEACQgEACgIAAQgKAAgGgFg");
	this.shape_1.setTransform(-37.9,11.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},1).to({state:[]},10).wait(1));

	// Слой_1
	this.instance = new lib.devs();
	this.instance.parent = this;
	this.instance.setTransform(-75,-158);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(12));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-75,-158,150,316);


(lib.bgImg2_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.bgImg2();
	this.instance.parent = this;
	this.instance.setTransform(-150,-150);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bgImg2_1, new cjs.Rectangle(-150,-150,300,300), null);


(lib.bgImg1_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.bgImg1();
	this.instance.parent = this;
	this.instance.setTransform(-150,-150);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bgImg1_1, new cjs.Rectangle(-150,-150,300,300), null);


(lib.bg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#ECD087","#A27B3A","#000000","#000000"],[0,1,1,1],0,-299,0,299).s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.bg, new cjs.Rectangle(-150,-300,300,600), null);


(lib.arrow = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#E3B47D").ss(2,2,0,3).p("Agbg2IA3A2Ig3A3");
	this.shape.setTransform(7.5,0.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#E3B47D").s().p("AhmAJIAAgRIDNAAIAAARg");
	this.shape_1.setTransform(-1.6,0.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.arrow, new cjs.Rectangle(-11.9,-6.1,23.6,13.8), null);


(lib.btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// arrow
	this.instance = new lib.arrow();
	this.instance.parent = this;
	this.instance.setTransform(59.6,-0.7,1,1,0,0,0,0.3,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({x:62},3,cjs.Ease.get(1)).to({x:59.6},2).wait(3).to({x:62},3,cjs.Ease.get(1)).to({x:59.6},2).wait(1));

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhgAnQgPgQAAgXQAAgVAPgQQAQgQAYAAQAYAAAPAQQAQAPAAAWQAAAXgQAPQgQAQgXAAQgYAAgQgPgAhSgZQgKAKAAAPQAAAQAKALQALALAPAAQAPAAAKgLQAKgLAAgQQAAgOgKgLQgKgLgPAAQgQAAgKALgAn0AlIAKgNQAPAOAUAAQAIAAAGgEQAGgEAAgHQAAgQgYAAIgLAAIAAgOIALAAQAWAAAAgPQAAgHgGgEQgFgEgJAAQgRAAgMAMIgKgMQARgQAXAAQARAAAKAIQAKAIAAAMQAAARgSAIQAVAFAAATQAAANgLAJQgKAIgSAAQgbAAgSgRgAHjA1IAAhMIg1BMIgRAAIAAhoIASAAIAABLIA1hLIARAAIAABogAFDA1IAAhXIghAAIAAgRIBVAAIAAARIghAAIAABXgADpA1IAAhMIg1BMIgRAAIAAhoIASAAIAABLIA1hLIARAAIAABogAAmA1IAAhoIAvAAQASAAAJAJQAHAIAAAKQAAAPgPAIQAVAGAAATQAAAOgKAHQgLAIgSAAgAA4AkIAeAAQAVAAAAgOQAAgOgWAAIgdAAgAA4gHIAZAAQAUAAAAgPQAAgNgTAAIgaAAgAinA1IAAhLIghAxIAAAAIghgwIAABKIgSAAIAAhoIATAAIAgAxIAggxIAUAAIAABogAkxA1IgLgaIgyAAIgLAaIgSAAIAuhpIARAAIAuBpgAlDALIgSgpIgSApIAkAAg");
	this.shape.setTransform(-18.5,0.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(15));

	// Слой_7
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AuDDSIAAmjIcHAAIAAGjg");
	this.shape_1.setTransform(-1.2,0);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(15));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-91.2,-21,180,42);


(lib.banner = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// urText
	this.instance = new lib.urText();
	this.instance.parent = this;
	this.instance.setTransform(0,274.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(209));

	// logo
	this.instance_1 = new lib.logo();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-0.1,-254.4,1.16,1.16,0,0,0,1.8,0.4);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({alpha:1},10).wait(99).to({x:-238.1},10,cjs.Ease.get(-1)).to({_off:true},1).wait(29).to({_off:false,x:-0.1,y:150.6,alpha:0},0).to({alpha:1},10).wait(39).to({x:-243.1},10,cjs.Ease.get(-1)).wait(1));

	// dev_3duo
	this.instance_2 = new lib.dev_3duo("single",0);
	this.instance_2.parent = this;
	this.instance_2.setTransform(226,-50);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(149).to({_off:false},0).to({x:-2},10).wait(5).to({mode:"synched",loop:false},0).wait(34).to({startPosition:11},0).to({x:-245},10,cjs.Ease.get(-1)).wait(1));

	// t3
	this.instance_3 = new lib.t2();
	this.instance_3.parent = this;
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(119).to({_off:false},0).to({alpha:1},10).wait(10).to({y:-263},10,cjs.Ease.quadInOut).wait(49).to({x:-243},10,cjs.Ease.get(-1)).wait(1));

	// t2_2
	this.instance_4 = new lib.t2_2();
	this.instance_4.parent = this;
	this.instance_4.setTransform(230,114.5);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(74).to({_off:false},0).to({x:0},10,cjs.Ease.quadInOut).wait(25).to({x:-243},10,cjs.Ease.get(-1)).to({_off:true},1).wait(89));

	// t2_1
	this.instance_5 = new lib.t2_1();
	this.instance_5.parent = this;
	this.instance_5.setTransform(253.9,114);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(39).to({_off:false},0).to({x:9.9},10,cjs.Ease.get(1)).wait(25).to({x:-215.1},10,cjs.Ease.quadInOut).to({_off:true},1).wait(124));

	// t1
	this.instance_6 = new lib.t1();
	this.instance_6.parent = this;
	this.instance_6.setTransform(243.8,160.9);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(39).to({_off:false},0).to({x:-0.2},10,cjs.Ease.get(1)).wait(60).to({x:-243.2},10,cjs.Ease.get(-1)).to({_off:true},1).wait(89));

	// dev_3duo
	this.instance_7 = new lib.dev_3duo("single",0);
	this.instance_7.parent = this;
	this.instance_7.setTransform(246.8,-71,0.854,0.854);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(39).to({_off:false},0).to({x:-1},10,cjs.Ease.get(1)).wait(5).to({mode:"synched",loop:false},0).wait(55).to({startPosition:11},0).to({x:-244},10,cjs.Ease.get(-1)).to({_off:true},1).wait(89));

	// btn
	this.instance_8 = new lib.btn("single",0);
	this.instance_8.parent = this;
	this.instance_8.setTransform(-0.5,214.5,0.02,0.02,0,0,0,0,2.5);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(39).to({_off:false},0).to({regX:-0.5,regY:0.5,scaleX:1,scaleY:1},10,cjs.Ease.get(1)).wait(130).to({mode:"synched",loop:false},0).wait(19).to({startPosition:14},0).to({x:-243.5},10,cjs.Ease.get(-1)).wait(1));

	// bgImg1
	this.instance_9 = new lib.bgImg1_1();
	this.instance_9.parent = this;
	this.instance_9.setTransform(-300,-150);

	this.timeline.addTween(cjs.Tween.get(this.instance_9).to({x:0},10,cjs.Ease.get(1)).wait(19).to({x:300},10,cjs.Ease.get(-1)).to({_off:true},1).wait(169));

	// bgImg2
	this.instance_10 = new lib.bgImg2_1();
	this.instance_10.parent = this;
	this.instance_10.setTransform(300,150);

	this.timeline.addTween(cjs.Tween.get(this.instance_10).to({x:0},10,cjs.Ease.get(1)).wait(19).to({x:-300},10,cjs.Ease.get(-1)).to({_off:true},1).wait(169));

	// bg
	this.instance_11 = new lib.bg();
	this.instance_11.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(209));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-450,-300,900,600);


// stage content:
(lib._300x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// cover
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#666666").ss(2,1,1).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// banner
	this.instance = new lib.banner();
	this.instance.parent = this;
	this.instance.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,299,900,602);
// library properties:
lib.properties = {
	id: 'D78E0080C82B4A91A29A8C60B712AE41',
	width: 300,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/bgImg1.jpg", id:"bgImg1"},
		{src:"images/bgImg2.jpg", id:"bgImg2"},
		{src:"images/devs.png", id:"devs"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['D78E0080C82B4A91A29A8C60B712AE41'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;