(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.bgImg1 = function() {
	this.initialize(img.bgImg1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.bgImg2 = function() {
	this.initialize(img.bgImg2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.bgImg3 = function() {
	this.initialize(img.bgImg3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.bgImg4 = function() {
	this.initialize(img.bgImg4);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.box1 = function() {
	this.initialize(img.box1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,250,322);


(lib.box2 = function() {
	this.initialize(img.box2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,250,322);


(lib.p1 = function() {
	this.initialize(img.p1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,54,40);


(lib.p2 = function() {
	this.initialize(img.p2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,58,58);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.t4_3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AKGA6IgFgCIgEgGIgBgJIABgIIAEgFIAFgDIAHgBIAHABIAFADIAEAFQABADAAAFQAAAGgBADIgEAGIgFACIgHAAgAIfA3QgLgDgHgHQgHgIgDgLQgFgLAAgPQAAgPAFgKQADgLAHgIQAHgHALgDQAIgDAPgBQAOABAKADQAKADAHAHQAIAJACAKQAEAKABAPQgBAPgEALQgCAKgIAJQgHAHgKADQgKADgOAAQgPAAgIgDgAItgWQgEABgCACQgCACgCAFIgBAMQAAAKABADQACAEACADQADADADAAIARAAQAEAAADgDQACgCACgFQACgFAAgIQAAgHgCgFQgCgGgCgBQgDgDgEAAIgIAAIgJAAgACyA6IgLgFIALgbIAEACIADABIACgBIACgBIABgDIAFhJIAEgBQAGgEAGgBIAMgBIA0AAIAABxIgjAAIAAhPIgLAAIgDAqQgBAKgEAJQgBAGgGAFQgFAGgGABQgGABgIAAIgLAAgAnmA3QgKgDgHgHQgHgHgEgMQgDgNAAgNQAAgNADgMQAEgLAHgIQAHgHAKgDQAKgDAOgBQAPABAJADQAJACAIAIQAHAIAEALQADAJAAAQQAAAQgDAKQgEALgHAIQgIAIgJACQgJADgPAAQgOAAgKgDgAnXgWIgGADQgCABgCAGQgCAFABAHQgBAIACAFQACAFACACQADADADAAIARAAQAEAAADgDQACgDACgEQABgFAAgIQAAgHgBgFQgCgFgCgCQgCgCgFgBIgIAAIgJAAgAHNA5IAAgoIgeAAIAAAoIgjAAIAAhxIAjAAIAAApIAeAAIAAgpIAkAAIAABxgAEkg4IAjAAIAAAiIAeABQAGABAHAFQAFAEADAHQADAGABAPQgBAQgDAHQgCAIgGADQgFAFgIAAIhBABgAFHAZIAOAAIADgBIACgCIAAgFIAAgEIgCgCIgDgBIgDAAIgLAAgACJA5IgGgQIgeAAIgFAQIgdAAIABgXIAghaIAgAAIAbBLQADAIACAHQABAHAAAJIAAAHgAB6AHQgDgHAAgHIgDgUIgGAiIAMAAIAAAAgAgGA5IAAhPIgZAAIAAgiIBUAAIAAAiIgZAAIAABPgAhPA5IAAgoIgfAAIAAAoIgjAAIAAhxIAjAAIAAApIAfAAIAAgpIAiAAIAABxgAjuA5IAAhxIBNAAIAAAhIgpAAIAAAIIAmAAIAAAfIgmAAIAAAIIApAAIAAAhgAkjA5IAAgRIAGgqIgBAAIgZA7IgaAAIgZg7IAAAAIAEAZIABAiIgjAAIAAhxIAlAAIAbA4IADAPIABAJIAFgYIAbg4IAlAAIAABxgAo3A5IAAgiIAFgZIgBAAIgZA7IgaAAIgYg7IgBAAIAFAZIAAAiIgjAAIAAhxIAlAAIAaA4IAGAYIAEgYIAbg4IAlAAIAABxgAKBAPIgGhHIAjAAIgFBHg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t4_3, new cjs.Rectangle(-67,-5.8,134,11.7), null);


(lib.t4_2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AkwA6IgYgGIgHgDIANgeIAHADIASADIAGAAIAGgBIABgDIgBgDIgDgCIgPAAIAAggIALAAIAHgBQAAAAAAgBQAAAAABAAQAAgBAAAAQAAgBAAAAIgBgCQAAgBAAAAQgBAAAAgBQgBAAAAAAQgBAAgBAAIgHAAIgIAAIgJACIgIADIgKgeIAGgDIAJgDIANgCIAOgBQALAAAHACQAIACAFAEQAFAFACAGQACAHABAJIgBAJQgBADgCADIgFAFQgFACgFABIAAAAQAHAAADACQAEACADADQACADABAFIAAAJQAAALgCAFQgCAHgGAEQgFAEgIACQgKACgIAAIgQgBgAETA3QgKgDgHgHQgHgHgEgMQgDgNAAgNQAAgNADgNQAEgLAHgHQAHgHAKgDQAKgEAOAAIAMABIALADIAIAEIAGADIgMAeIgOgFIgHgBIgFAAIgLABQgEACgCAFIAbAAIAAAfIgbAAQACAFAFABIAKABIAFAAIAHgBIAOgEIAMAeIgGADIgTAGIgMABQgOAAgKgDgAh/A5IgLgEIALgbIAEACIACAAIADAAQAAAAABAAQAAAAAAgBQAAAAAAAAQAAAAAAAAIACgDIAFhKIADgBQAIgDAEgBIANgBIA0AAIAABxIgjAAIAAhPIgLAAIgEApQgBANgDAGQgDAIgEAEQgEAEgHADQgHABgIAAIgKgBgADNA5IgEgQIgfAAIgFAQIgdAAIABgXIAghaIAgAAIAcBLQACAIABAHQACAHAAAJIAAAHgAC/AHQgCgHgBgIIgDgTIgDATQgBAIgCAHIAMAAIAAAAgAA+A5IAAhPIgZAAIAAgiIBVAAIAAAiIgZAAIAABPgAgMA5IAAhxIAjAAIAABxgAipA5IgFgQIgeAAIgFAQIgeAAIAAgHQAAgJABgHIAEgPIAdhLIAgAAIAbBLIAFAPIABAQIAAAHgAi4AHIgGgiIgFAiIALAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t4_2, new cjs.Rectangle(-33.6,-5.8,67.2,11.8), null);


(lib.t4_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AASBFIAAgWIguAAIAAAWIgdAAIgGg3IAEAAIAGgBQADgBABgCIADgGIABgIIAEg4IADgBQAIgDAFgBIAMgBIA0AAIAABQIAOAAIgGA3gAgJgEQgBAMgDAGIARAAIAAguIgLAAgAEHAvIgMgFIALgaIADABIAEABIADgBIABgBIABgCIAFhKIAEgBQAGgDAFgBIANgBIA1AAIAABxIgjAAIAAhPIgMAAIgDApQgBAJgDAKQgDAIgEAEQgFAEgHADQgGABgIAAIgKgBgApjAsQgLgCgGgIQgIgHgDgLQgDgKgBgQQABgQADgKQADgLAIgIQAGgHALgDQAKgDANAAQAOAAALADQAKADAHAHQAHAIAEALQADAMAAAOQAAANgDANQgEAMgHAGQgHAIgKACQgLAEgOAAQgNAAgKgEgApUggQgEAAgDACQgCADgCAFIAAAMIAAAMQACAFACACIAHAEIARAAQAEgBADgDQABgBACgGQACgDAAgJQAAgHgCgFQgCgGgBgCQgDgBgEgBIgJgBIgIABgAKUAvIgFgQIgeAAIgGAQIgdAAIABgXIAhhaIAfAAIAcBKIAFAPIAAAYgAKFgCQgCgJAAgHIgDgTIgEATQAAAHgCAJIALAAIAAAAgAIhAvIAAgpIgeAAIAAApIgjAAIAAhxIAjAAIAAAoIAeAAIAAgoIAjAAIAABxgAF4hCIAjAAIAAAiIAfABQAFAAAHAFQAFAEADAIQAEAHgBAOQABAPgEAIQgDAHgFAEQgFAEgHABIhCABgAGbAPIAPAAIACgBIABgCIABgFIgBgEIgBgCIgCgBIgEAAIgLAAgADcAvIgFgQIgeAAIgFAQIgeAAIABgXIAhhaIAgAAIAcBKIAEAPIABAYgADOgCQgCgJgBgHIgDgTIgDATQAAAHgDAJIAMAAIAAAAgABAAvIAAhxIBNAAIAAAhIgpAAIAAAIIAmAAIAAAeIgmAAIAAAJIApAAIAAAhgAhtAvIAAhxIAjAAIAABxgAjFAvIgFgQIgeAAIgFAQIgdAAIAAgHIABgQIAfhaIAhAAIAbBKIAFAPQABAIAAAJIAAAHgAjTgCIgGgjIgGAjIAMAAgAk3AvIAAgSIAEgpIgBAAIgYA7IgaAAIgYg7IgBAAIAEAZIAAAiIgjAAIAAhxIAmAAIAaA4IAFAYIAFgYIAbg4IAlAAIAABxgAoFAvIAAhxIBBAAQAHACAFADQAFAEADAIQAEAHAAAPQAAAPgEAIQgDAGgFAEQgFAFgHAAIgeABIAAAjgAnigTIAOAAIADgBIABgCIABgFIgBgEIgBgDIgDgBIgOAAgArjAvIAAgTIgXgBQgHgBgGgDQgFgFgEgHQgDgJAAgNQAAgOADgIQAEgIAFgEQAGgEAHAAIAXgBIAAgQIAjAAIAAAQIAZABQAGABAFADQAGAEADAIQAEAHAAAPQAAAOgEAIQgDAHgGAFQgFADgGABIgZABIAAATgArAgDIAIAAIADgBIACgCIABgFIgBgEIgCgDIgDgBIgIAAgArtgSIgCADIAAAEIAAAFIACACIACABIAIAAIAAgQIgIAAgALqADIAAgZIAqAAIAAAZg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t4_1, new cjs.Rectangle(-78.7,-6.9,157.5,13.8), null);


(lib.t3_2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AHZA6QgDgBgCgCQgDgCgBgDQgBgEAAgFQAAgFABgEQABgCADgCQABgCAEgBIAHgBIAGABQAEABACACQACACABACQACAEAAAFQAAAFgCAEQgBADgCACQgDACgDABIgGAAgAGnA6QgDgBgCgCQgDgCgBgDQgBgEAAgFQAAgFABgEQABgCADgCQABgCAEgBIAHgBIAGABQAEABACACIADAEQACAEAAAFQAAAFgCAEIgDAFQgCACgEABIgGAAgAF1A6QgDgBgCgCIgEgFIgBgJIABgJIAEgEIAFgDIAHgBIAGABQAEABACACIADAEQACAEAAAFQAAAFgCAEIgDAFQgCACgEABIgGAAgAnRA6IgYgGIgHgDIAMgdIAIACIAZADIAFgBIABgCIAAgCIgBgDIgDgBIgEAAIgLAAIAAggIALAAIAGgBIACgDIgBgCIgEgCIgHAAIgSACIgHADIgLgeIAHgDIAJgDIANgCIAOgBIASACQAHACAGAEQAEAFADAGQACAGAAALIAAAIIgDAHIgGAEQgFACgFAAIAAABQAHAAAEACQAEACACADQADAEAAAEIABAJQAAAKgDAGQgCAHgFAEQgGAEgHACQgIABgKAAgAE3A5IACgtIACgNIgpA6IgbAAIAAhxIAjAAIgDA6IAog6IAcAAIAABxgACnA5IAAhPIgZAAIAAgiIBWAAIAAAiIgaAAIAABPgABrA5IgFgQIgfAAIgEAQIgeAAIAAgHQAAgJABgHQABgGADgJIAchLIAhAAIAfBaIABAXgABcAHIgDgPIgDgTIgDATIgDAPIAMAAIAAAAgAg/A5IAAhxIA6AAIAHABIAJADQAEABADADIAGAJQACAIAAAHQAAAHgEAHQgDAHgFADIAAAAQAIADADAHQAEAGAAAJQAAAJgCAGQgDAFgDAEQgCADgFACIgIACIgIABgAgcAZIARAAQABAAAAAAQABAAAAgBQAAAAAAgBQAAgBAAgBQAAgBAAgBQAAgBAAAAQAAgBgBAAQAAAAgBgBIgRAAgAgcgPIARAAQABAAAAgBQABAAAAAAQAAgBAAgBQAAAAAAgCQAAgBAAAAQAAgBAAgBQAAAAgBgBQAAAAgBAAIgRAAgAhyA5IADg6IgoA6IgcAAIAAhxIAkAAIgCAtIgCANIApg6IAbAAIAABxgAjmA5IAAhPIgbAAIAABPIgjAAIAAhxIBhAAIAABxgAlKA5IgFgQIgfAAIgEAQIgeAAIAAgHIABgQIAghaIAhAAIAbBLIAEAPQACAHAAAJIAAAHgAlZAHIgFgiIgGAiIALAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Слой_1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AHZA6QgDgBgCgCQgDgCgBgDQgBgEAAgFQAAgEABgFQABgCADgCQABgCAEgBIAHgBIAGABIAGADQACACABACQACAFAAAEQAAAFgCAEQgBADgCACQgDACgDABIgGAAgAGnA6QgDgBgCgCQgDgCgBgDQgBgEAAgFQAAgEABgFQABgCADgCIAFgDIAHgBIAGABIAGADIADAEQACAFAAAEQAAAFgCAEIgDAFQgCACgEABIgGAAgAF1A6QgDgBgCgCIgEgFIgBgJIABgJIAEgEIAFgDIAHgBIAGABIAGADIADAEQACAFAAAEQAAAFgCAEIgDAFQgCACgEABIgGAAgAnRA6IgYgGIgHgDIAMgdIAIACIAZADIAFgBIABgDIAAgBIgBgCIgDgCIgEAAIgLAAIAAggIALAAIAGgBIACgDIgBgDIgEgBIgHAAIgSACIgHADIgLgeIAHgDIAJgDIANgCIAOgBIASACQAHACAGAEQAEAFADAGQACAGAAAKIAAAJIgDAHIgGAEQgFACgFAAIAAABQAHAAAEACQAEACACADQADADAAAFIABAJQAAAKgDAGQgCAIgFADQgGAEgHACQgIACgKgBgAE3A5IACgtIACgNIgpA6IgbAAIAAhxIAjAAIgDA6IAog6IAcAAIAABxgACnA5IAAhPIgZAAIAAgiIBWAAIAAAiIgaAAIAABPgABrA5IgFgQIgfAAIgEAQIgeAAIAAgHQAAgJABgHQABgGADgJIAchLIAhAAIAfBaIABAXgABcAHIgDgPIgDgSIgDASIgDAPIAMAAIAAAAgAg/A5IAAhxIA6AAIAHABIAJADQAEABADADIAGAJQACAIAAAHQAAAHgEAHQgDAGgFAEIAAAAQAIADADAHQAEAGAAAJQAAAJgCAFQgDAGgDADQgCADgFADIgIACIgIABgAgcAZIARAAQABAAAAAAQABAAAAgBQAAAAAAgBQAAgBAAgBQAAgBAAgBQAAgBAAAAQAAgBgBAAQAAAAgBgBIgRAAgAgcgPIARAAQABAAAAgBQABAAAAAAQAAgBAAgBQAAgBAAgBQAAgBAAAAQAAgBAAgBQAAAAgBgBQAAAAgBAAIgRAAgAhyA5IADg6IgoA6IgcAAIAAhxIAkAAIgCAtIgCANIApg6IAbAAIAABxgAjmA5IAAhPIgbAAIAABPIgjAAIAAhxIBhAAIAABxgAlKA5IgFgQIgfAAIgEAQIgeAAIAAgHIABgQIAghaIAhAAIAbBLIAEAPQACAHAAAJIAAAHgAlZAHIgFghIgGAhIALAAg");
	this.shape_1.setTransform(1,1);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.t3_2, new cjs.Rectangle(-49.7,-5.8,100.4,12.7), null);


(lib.t3_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AJAA3QgLgDgGgIQgIgHgDgLQgEgLAAgPQAAgOAEgMQADgJAIgJQAGgGALgFQAKgDAOAAQANAAALADQAKAFAHAGQAIAJACAJQAEAMAAAOQAAAPgEALQgCALgIAHQgHAIgKADQgKADgOAAQgPAAgJgDgAJPgWQgDAAgDADQgDACgBAFIgBAMQAAAKABADQABAEADADQADACADABIAJAAIAIAAQAEgBADgCQACgCACgFQABgFAAgIQAAgHgBgFQgCgGgCgBQgDgDgEAAIgIAAIgJAAgAgIA3QgLgDgHgIQgGgGgEgMQgEgKAAgQQAAgPAEgLQAEgKAGgIQAHgGALgFQAJgDANAAIANABIATAHIAFADIgMAeIgOgFIgMgBIgIABIgFADQgCABgCAGIgBAMQAAAKABADQACAFACACQABACAEABIAIAAIAGAAIANgCIAHgDIAMAeIgFADIgTAHIgNAAQgNAAgJgDgAixA5QgIgDgFgEIALgdQAFACAEAAIAKACIADgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQgBgBAAAAIgYgqQgDgFgDgJQgCgJAAgGIAAgGIAcAAIAJAQIAHANQACAHABAJIACAMIAEgcIAMgdIAdAAIAAAFIgCAPIgVA6QgEAKgFAIQgDAHgGAEQgGAFgEABIgMABQgKABgIgCgAHvA5IAAgoIgeAAIAAAoIgjAAIAAhxIAjAAIAAAoIAeAAIAAgoIAjAAIAABxgAF6A5IAAgmIgFACIgNACIgTgBQgHgBgFgFQgEgCgEgKQgDgGAAgOIAAgoIAjAAIAAAoIAAAEIACACIACABIANAAIAIgCIAAgtIAkAAIAABxgAEbA5IgFgQIgfAAIgFAQIgdAAIABgXIAEgPIAchLIAgAAIAcBLQADAJABAGQABAHAAAJIAAAHgAEMAHIgGgiIgGAiIAMAAgACoA5IABgiIAEgZIgBAAIgZA7IgZAAIgZg7IgBAAIAEAZIABAiIgjAAIAAhxIAlAAIAVAqIAFAOIAEAPIABAJIAFgYIAbg4IAlAAIAABxgAjnA5IgTgoIgIAAIAAAoIgjAAIAAhxIAjAAIAAAoIAIAAIATgoIAmAAIgbA4IAbA5gAlYA5IAAgoIgfAAIAAAoIgjAAIAAhxIAjAAIAAAoIAfAAIAAgoIAjAAIAABxgAnOA5IAAhxIAjAAIAABxgAo4A5IAAhxIBCABQAHABAFAEQAFADADAIQAEAHAAAQQAAAPgEAGQgDAIgFAEQgGAEgHABIgeABIAAAigAoVgJIAPAAIACgBIACgCIAAgEIAAgFIgCgCIgCgBIgPAAgAqOA5IAAhxIBMAAIAAAhIgpAAIAABQg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Слой_1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AJAA3QgLgDgGgHQgIgJgDgJQgEgMAAgPQAAgOAEgMQADgKAIgIQAGgGALgFQAKgDAOAAQANAAALADQAKAFAHAGQAIAIACAKQAEAMAAAOQAAAPgEAMQgCAJgIAJQgHAHgKADQgKADgOAAQgPAAgJgDgAJPgWQgDABgDACQgDACgBAFIgBAMQAAAKABADQABAEADADQADACADAAIAJABIAIgBQAEAAADgCQACgCACgFQABgFAAgIQAAgGgBgGQgCgGgCgBQgDgCgEgBIgIgBIgJABgAgIA3QgLgDgHgHQgGgHgEgLQgEgLAAgQQAAgPAEgLQAEgKAGgIQAHgGALgFQAJgDANAAIANABIATAHIAFADIgMAeIgOgFIgMgBIgIABIgFADQgCABgCAGIgBAMQAAAKABADQACAFACACQABACAEABIAIAAIAGAAIANgCIAHgDIAMAeIgFADIgTAHIgNAAQgNAAgJgDgAixA5QgIgDgFgEIALgdQAFACAEAAIAKACIADgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQgBgBAAAAIgYgqQgDgGgDgIQgCgJAAgGIAAgGIAcAAIAJAPIAHAPQACAFABAKIACAMIAEgcIAMgdIAdAAIAAAFIgCAPIgVA6QgEAJgFAJQgDAGgGAFQgGAFgEABQgGACgGgBQgKAAgIgBgAHvA5IAAgoIgeAAIAAAoIgjAAIAAhxIAjAAIAAAoIAeAAIAAgoIAjAAIAABxgAF6A5IAAgmIgFACIgNABIgTgBQgHAAgFgFQgEgCgEgKQgDgGAAgOIAAgoIAjAAIAAAoIAAAEIACACIACACIANgBIAIgCIAAgtIAkAAIAABxgAEbA5IgFgQIgfAAIgFAQIgdAAIABgXIAEgPIAchLIAgAAIAcBLQADAJABAGQABAHAAAJIAAAHgAEMAHIgGghIgGAhIAMAAgACoA5IABgiIAEgZIgBAAIgZA7IgZAAIgZg7IgBAAIAEAZIABAiIgjAAIAAhxIAlAAIAVAqIAFAOIAEAPIABAJIAFgYIAbg4IAlAAIAABxgAjnA5IgTgoIgIAAIAAAoIgjAAIAAhxIAjAAIAAAoIAIAAIATgoIAmAAIgbA4IAbA5gAlYA5IAAgoIgfAAIAAAoIgjAAIAAhxIAjAAIAAAoIAfAAIAAgoIAjAAIAABxgAnOA5IAAhxIAjAAIAABxgAo4A5IAAhxIBCABQAHABAFAEQAFADADAIQAEAHAAAQQAAAOgEAHQgDAIgFAEQgGAEgHAAIgeABIAAAjgAoVgIIAPAAIACgCIACgCIAAgEIAAgFIgCgCIgCgBIgPAAgAqOA5IAAhxIBMAAIAAAhIgpAAIAABQg");
	this.shape_1.setTransform(1,1);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.t3_1, new cjs.Rectangle(-65.5,-5.8,132.1,12.7), null);


(lib.t2_3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AlcBEIAAgWIgvAAIAAAWIgcAAIgHg3IADAAIAHgBIAEgDIADgGIABgIIAEg4IADgBIANgEQAFgBAHAAIA1AAIAABQIAOAAIgHA3gAl4gFQgBAJgDAJIASAAIAAguIgMAAgAIyAuQgDAAgCgCIgEgFIgBgJIABgJIAEgFIAFgCIAHgBIAGABIAGACIADAFQACAEAAAFQAAAFgCAEIgDAFQgDACgDAAIgGABgAIAAuQgDAAgCgCQgCgBgCgEQgCgEAAgFQAAgFACgEQACgEACgBIAFgCIAHgBIAGABIAGACIADAFQACAEAAAFQAAAFgCAEIgDAFQgDACgDAAIgGABgAHOAuQgDAAgDgCIgDgFQgCgEAAgFQAAgFACgEIADgFIAGgCIAHgBIAGABIAGACIADAFIABAJIgBAJIgDAFQgDACgDAAIgGABgAGQAuIADg6IgoA6IgbAAIAAhxIAjAAIgDA7IAog7IAbAAIAABxgAEAAuIAAhPIgZAAIAAgiIBWAAIAAAiIgaAAIAABPgADDAuIgEgRIgfAAIgFARIgdAAIAAgHIABgQIAEgPIAchLIAgAAIAcBKIAEAQQABAHAAAIIAAAIgAC1gDIgGgjIgGAjIAMAAgAAZAuIAAhxIA6AAIAIABIAIACQAFACADADQADADACAGQACAGAAAIQAAAKgDAFQgDAGgFAEIAAABQAIADADAGQAEAGAAAJQAAAIgDAGQgBAFgEAEQgDAEgEABIgJADIgIABgAA8AOIARAAQACgBAAgEQAAAAAAgBQAAgBAAAAQgBgBAAAAQgBgBAAAAIgRAAgAA8gaIARgBQAAAAABAAQAAAAABgBQAAAAAAgBQAAgBAAgBQAAgDgCgBIgRgBgAgaAuIAEg6IgoA6IgcAAIAAhxIAjAAIgDA7IAog7IAbAAIAABxgAjCAuIAAhxIBCABQAHABAFADQAGAEACAIQAEAHAAAPQAAAPgEAIQgDAGgFAFQgFAEgHAAIgfABIAAAjgAifgUIAMAAIADAAIACgBIACgCIABgFIgBgEIgCgDIgCgBIgPAAgAjxAuIgTgoIgIAAIAAAoIgkAAIAAhxIAkAAIAAAoIAIAAIATgoIAmAAIgbA5IAbA4gApJAuIAAhxIA6AAIAIABQAEAAAFACQAFACACADIAGAJQACAGAAAIQAAAKgEAFQgDAGgFAEIAAABQAJADACAGQAEAGAAAJQAAAJgCAFQgDAGgDADQgCAEgFABIgIADIgJABgAomAOIARAAQADgBAAgEQAAAAAAgBQgBgBAAAAQAAgBgBAAQAAgBgBAAIgRAAgAomgaIARgBQABAAAAAAQABAAAAgBQAAAAABgBQAAgBAAgBQAAgDgDgBIgRgBgAncAtIAAhwIAjAAIAABwg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t2_3, new cjs.Rectangle(-58.5,-6.8,117.2,13.7), null);


(lib.t2_2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ADwA3QgLgDgGgHQgHgHgEgLQgEgNAAgOQAAgNAEgNQAEgLAHgHQAGgGALgEQAMgEAMAAQAMAAALAEQALAEAHAGQAHAHADALQAEALAAAPQAAAQgEALQgDALgHAHQgHAHgLADQgLAEgMAAQgMAAgMgEgAD/gWQgEABgCACQgCACgCAFQgCAFAAAHQAAAIACAFQACAFACACQACACAEABIAJABIAIgBQAFgBACgCQACgDACgEQABgFAAgIQAAgHgBgFQgCgEgCgDQgCgCgFgBIgIAAIgJAAgAhpA5QgIgDgFgDIALgeQAFACAEABIAKABIADgBQAAAAAAAAQAAAAAAgBQAAAAAAgBQgBAAAAgBIgYgqIgGgOIgCgPIAAgGIAcAAIAJAQIAHAOQADAJAAAGIACAMIAEgcIAMgdIAdAAIAAAFIgCAPIgVA6QgDAKgGAIQgFAIgEADQgFAFgFABQgGACgHAAQgJAAgIgCgAkfA6IgOgCIgLgEIgGgDIAMgdIAIACIAYADQAEAAACgBIABgDIgBgDIgDgBIgEgBIgLAAIAAggIALAAIAGgBIACgDIgBgCIgEgCIgHAAIgSADIgHACIgLgeIAHgDIAJgDIAbgDQAIAAAKACQAIADAFADQAEAEADAHQACAIAAAJIAAAIIgDAHIgGAFQgFACgFAAIAAAAQAHAAAEACQAFADABADQADADAAAEIABAJQAAALgDAFQgCAHgFAEQgFAEgIACQgIACgKAAIgQgBgACfA5IAAgoIgeAAIAAAoIgkAAIAAhxIAkAAIAAAoIAeAAIAAgoIAjAAIAABxgAAqA5IAAgmIgFACIgNACIgTgBQgGgBgFgEQgFgEgDgIQgEgIAAgNIAAgoIAjAAIAAAoIAAAEIACACIACABIADABIASgCIAAguIAjAAIAABxgAjYA5IAAhxIBCABQAHABAFAEQAFADAEAIQADAJAAAOQAAAOgDAHQgEAJgFADQgFAEgHABIgfABIAAAigAi1gIIAMAAIADgBIACgBIACgCIABgEIgBgFIgCgCIgCgBIgPAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t2_2, new cjs.Rectangle(-31.9,-5.9,63.8,11.8), null);


(lib.t2_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AE+A5QgIgCgGgEIALgeIAKADIAJABIADgBQAAAAABAAQAAAAgBgBQAAAAAAgBQAAAAgBgBIgXgqIgHgOQgCgGAAgJIAAgGIAcAAIAJAQIAHAOQADAJABAGIABAMIAEgcIAGgPIAGgOIAdAAIAAAFQAAAJgCAGIgVA6QgFANgDAFQgGAIgEADQgEAFgGABQgFACgHAAQgKAAgHgCgAkHA3QgLgDgHgHQgGgHgEgLQgEgLAAgQQAAgPAEgLQAEgLAGgHQAHgGALgEQAMgEALAAQAMAAAMAEQALAEAGAGQAHAHAEALQAEANAAANQAAAOgEANQgEALgHAHQgGAHgLADQgMAEgMAAQgLAAgMgEgAj4gWQgEABgDACQgCADgCAEIgBAMIABANQACAEACADQADACAEABIAIABIAJgBQAEgBACgCQACgCACgFQACgFAAgIQAAgHgCgFQgCgFgCgCQgCgCgEgBIgJAAIgIAAgAEIA5IgTgoIgJAAIAAAoIgjAAIAAhxIAjAAIAAAoIAJAAIATgoIAlAAIgbA4IAbA5gACWA5IAAgmIgGACIgNACIgSgBQgHgBgFgEQgGgEgDgIQgDgIAAgNIAAgoIAjAAIAAAoIABAEIABACIADABIADABIASgCIAAguIAjAAIAABxgAA2A5IgFgQIgfAAIgEAQIgdAAIAAgHQAAgIABgIIAFgPIAahLIAhAAIAbBLIAEAPQACAIAAAIIAAAHgAAnAHIgFghIgGAhIALAAgAg8A5IAAhPIgbAAIAABPIgjAAIAAhxIBhAAIAABxgAmNg4IBTAAIAAAhIgwAAIAAAIIAeABQAJACADACQAGAEADAGQADAHAAAOQAAAOgDAGQgDAHgGAEQgEADgIABIhBABgAlqAaIARgBQACgBAAgDQAAgBAAgBQAAgBAAAAQgBgBAAAAQgBAAAAAAIgRgBg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t2_1, new cjs.Rectangle(-39.8,-5.9,79.7,11.8), null);


(lib.t1_3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ABHBVIAAgWIguAAIAAAWIgcAAIgGg3IADAAIAGgBIAEgDIADgGIAFhAIADgBIANgEIAMgBIA1AAIAABQIANAAIgFA3gAArALQAAAKgDAJIASAAIAAguIgMAAgAIJA9QgLgDgHgIQgHgIgDgKQgEgMAAgOQAAgPAEgLQADgJAHgJQAHgHALgEQAKgDAOAAIAMABIALADIAIAEIAFADIgLAeIgPgFIgLgBIgJABIgGADQgCABgBAGIgBAMQAAAJABADQABAGACABQACADAEABIAJAAIAFAAIAOgDIAHgCIALAeIgFADIgTAGIgMABQgPAAgJgDgAEdA+QgHgCgGgEIALgeQAFADAEAAQAFACAEAAIADgBQABAAAAAAQAAgBAAAAQAAgBgBAAQAAgBgBgBIgXgpQgDgGgDgIQgCgGAAgKIAAgFIAcAAIAJAPQAFAJACAFIADAQIABALIAFgbIAFgPIAGgOIAdAAIAAAEQABAJgCAHIgVA6IgJASQgDAGgGAFQgGAEgFACQgGABgGAAQgKAAgHgCgAhgA9QgKgDgHgIQgHgGgEgMQgDgKgBgQQABgQADgKQADgLAIgHQAIgHAJgEQALgDANAAQANAAAKADQAKAEAIAHQAHAHADALQAEAKAAAQQAAAQgEAKQgDAMgHAGQgHAIgLADQgKADgNAAQgOAAgKgDgAhRgQIgGADQgCABgCAGQgBAFgBAHQABAIABAEQACAGACABQACADAEAAIAJABIAIgBQAEAAADgDQADgCABgFIABgMIgBgMQgBgFgDgCQgDgDgEAAIgIgBIgJABgAjvA/QgDAAgIgFIALgaIADACIAGAAQAAAAAAAAQAAAAABAAQAAgBAAAAQAAAAAAAAIABgDIAGhKIACgBIANgEIANgBIA0AAIAABxIgjAAIAAhPIgMAAIgDApQgCAOgCAFQgDAIgEAEQgFAFgGACQgGABgJAAgAlRA9QgKgDgHgIQgHgGgDgMQgEgKAAgQQAAgQAEgKQADgLAHgHQAIgHAJgEQALgDAOAAQANAAAKADQAKAEAHAHQAHAHAEALQADAKABAQQgBAQgDAKQgEAMgHAGQgHAIgKADQgKADgNAAQgOAAgLgDgAlBgQQgEAAgDADQgDADAAAEQgCAFAAAHQAAAIACAEQAAAEADADQADADAEAAIAJABIAIgBQADAAADgDQAEgDAAgEQABgEABgIQgBgHgBgFQAAgEgEgDQgDgDgDAAIgIgBIgJABgAm6A9QgKgDgHgIQgIgIgDgKQgDgMAAgOQAAgPADgLQADgJAIgJQAHgHAKgEQAKgDAOAAIANABIALADIAHAEIAGADIgMAeIgOgFIgMgBIgIABIgGADQgCABgCAGIgBAMQAAAJABADQACAGACABQACADAEABIAIAAIAFAAIAOgDIAHgCIAMAeIgGADIgTAGIgMABQgPAAgJgDgAKQA/IAAgkIgJAAIgNAkIgmAAIAQgqQgFgDgFgJQgDgHgBgNQAAgOADgIQAFgJAEgDQAGgDAHgBIBEgBIAABxgAJ8gSIgCADIAAAEIAAAFIACACIACABIASAAIAAgQIgSAAgAG3A/IAEg7IgpA7IgbAAIAAhxIAjAAIgCA6IAng6IAcAAIAABxgADnA/IgTgoIgGAAIAAAoIgiAAIAAgoIgGAAIgSAoIgmAAIAbg5Igbg4IAmAAIASAoIAGAAIAAgoIAiAAIAAAoIAGAAIATgoIAlAAIgbA4IAbA5gAn+A/IgFgQIgeAAIgFAQIgeAAIAAgHQAAgJABgHIAFgPIAchLIAgAAIAbBLIAFAPIABAQIAAAHgAoNANIgFgiIgGAiIALAAgApxA/IAAgoIgdAAIAAAoIgkAAIAAhxIAkAAIAAAoIAdAAIAAgoIAkAAIAABxgAGfg5IgJgDIgKgFIAIgTIAJAEQAGACAGAAQAGAAAGgCIAJgEIAIATIgKAFIgIADIgLABg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1_3, new cjs.Rectangle(-69.1,-8.5,138.2,17.1), null);


(lib.t1_2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AnKA3QgKgDgIgIQgGgGgEgMQgEgKAAgQQAAgQAEgJQADgLAHgIQAIgHAKgEQAKgDAOAAQANAAAKADQAKAEAIAHQAHAIADALQAEAJAAAQQAAAQgEAKQgDAMgHAGQgIAIgKADQgKADgNAAQgOAAgKgDgAm7gWIgGADQgCABgCAGQgCAFAAAHQAAAIACAFQACAFACACQACACAEABIAJAAIAIAAQAEgBADgCQACgDACgEIABgNIgBgMQgCgFgCgCQgDgDgEAAIgIAAIgJAAgAI6A5IAAhxIAkAAIAABxgAHWA5IADg6IgoA6IgcAAIAAhxIAkAAIgEA6IAog6IAcAAIAABxgAFFA5IAAhPIgZAAIAAgiIBWAAIAAAiIgZAAIAABPgADOA5IAAgSIgYgBQgHgBgGgEQgEgDgEgJQgDgIAAgOQAAgOADgIQAEgIAEgDQAGgFAHAAIAYgBIAAgQIAjAAIAAAQIAYABQAHABAFAEQAFADAEAIQADAIAAAOQAAAOgDAIQgEAIgFAEQgFAEgHABIgYABIAAASgADxAGIAIAAIACgBIACgCIABgEIgBgEIgCgCIgCgCIgIAAgADDgHIgCACIAAAEIAAAEIACACIADABIAIAAIAAgPIgIAAgAB5A5IgFgQIgfAAIgEAQIgeAAIAAgHQAAgJABgHIAghaIAhAAIAbBLIAEAPQACAHAAAJIAAAHgABqAHIgFgiIgGAiIALAAgAguA5IAAhxIBBABQAGAAAGAFQAFACAEAJQADAIAAAPQAAAOgDAHQgEAJgFADQgGAEgGABIgdABIAAAigAgKgJIANAAIACgBIACgCIABgEIgBgFIgCgCIgCgBIgNAAgAhdA5IgTgoIgIAAIAAAoIgjAAIAAhxIAjAAIAAApIAIAAIATgpIAmAAIgbA4IAbA5gAkAA5IAAhxIAjAAIAABxgAltA5IAAhxIA6AAIAJABQAGABACACQAFABACADQADAEADAFQACAGAAAJQAAAJgEAFQgDAGgFAEIAAAAQAIADAEAHQADAIAAAHQAAAIgCAHQgBAEgEAFIgIAFIgIACIgIABgAlKAZIARAAQABAAAAAAQABAAAAgBQAAAAABgBQAAgBAAgBQAAgEgDgBIgRAAgAlKgPIARAAQABAAAAgBQABAAAAAAQAAgBABgBQAAAAAAgCQAAgDgDgBIgRAAgAobA5IAAgoIgeAAIAAAoIgkAAIAAhxIAkAAIAAApIAeAAIAAgpIAjAAIAABxg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1_2, new cjs.Rectangle(-60.6,-5.8,121.2,11.7), null);


(lib.t1_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AHuBKIAEg7IgpA7IgbAAIAAhxIAjAAIgCA6IAng6IAcAAIAABxgAGIBKIgEgQIggAAIgEAQIgeAAIAAgHQAAgIABgIIAFgPIAbhLIAhAAIAcBLIADAPIABAQIAAAHgAF5AYIgFgiIgGAiIALAAgADdBKIAAhxIA7AAIAHABIAJACQAFACACADIAGAJQACAJAAAGQAAAIgDAFQgEAHgFADIAAABQAJADACAGQAEAHAAAJQAAAJgCAGQgDAGgCADQgDADgFACIgIACIgIABgAEAAqIASAAQAAAAAAAAQABAAAAgBQAAAAAAgBQAAgBAAgBQAAgBAAgBQAAgBAAAAQAAgBgBAAQAAAAAAgBIgSAAgAEAABIASAAQAAAAAAgBQABAAAAAAQAAAAAAgBQAAgBAAgBQAAgBAAAAQAAgBAAgBQAAAAgBgBQAAAAAAAAIgSAAgACqBKIAEg7IgpA7IgcAAIAAhxIAkAAIgDA6IAog6IAbAAIAABxgAACBKIAAhxIBCABQAHABAEAEQAGAEADAHQAEAJAAANQAAANgEAJQgDAIgGAEQgFAEgHABIgeABIAAAigAAlAHIAOAAIADgBIACgCIAAgEIAAgEIgCgCIgDgBIgOAAgAgtBKIgSgoIgJAAIAAAoIgjAAIAAhxIAjAAIAAAoIAJAAIASgoIAmAAIgbA4IAbA5gAixBKIAAhPIgZAAIAAgiIBVAAIAAAiIgZAAIAABPgAjvBKIgpg7IAEA7IgkAAIAAhxIAcAAIAoA6IgCgOIgBgsIAjAAIAABxgAlrBKIAAhxIAjAAIAABxgAm7BKIAAhxIAjAAIAABPIAjAAIAAAigAoRBKIAAhxIBMAAIAAAhIgpAAIAAAHIAnAAIAAAgIgnAAIAAApgAHWguIgJgDIgKgFIAIgTIAJAEQAGACAGAAQAHAAAFgCIAJgEIAIATIgKAFIgJADIgKABg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1_1, new cjs.Rectangle(-53,-7.4,106,14.8), null);


(lib.p2_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.p2();
	this.instance.parent = this;
	this.instance.setTransform(-29,-29);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.p2_1, new cjs.Rectangle(-29,-29,58,58), null);


(lib.p1_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.p1();
	this.instance.parent = this;
	this.instance.setTransform(-27,-20);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.p1_1, new cjs.Rectangle(-27,-20,54,40), null);


(lib.logo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#221F20").s().p("AhjCzQgugbgbgtIASgCQAZAoApAWQAqAXAwABQA6gBAwggQAughAVg0IAHgDIAEgBIAJgEQgUA/g1AmQg1AohDAAQg2AAgvgbgAgFCeIgBgDIgIgBIgCAEIgGgBIALgUIAFABIAGAVgAgMCWIAEAAIgBgFgAAHCLIAIgBQAEgBADACQACACAAADQABADgCADQgDACgEAAIgDAAIABAGIgGAAgAANCOIAAAGIADAAQABAAAAgBQABAAAAAAQABgBAAAAQAAgBAAAAQAAgBgBgBQAAAAAAAAQgBgBAAAAQgBAAgBAAgAAdCIIAFgCIADAMIAFgOIAFgBIAFAUIgFABIgDgLIgFAOIgFABgAgkCaIgCgHIgGAFIgGgCIAKgIIgEgLIAGABIACAHIAFgFIAHACIgKAHIAEANgAA1CBIAFgDIAEAIIADgLIAGgCIgDAKIAMAIIgGACIgIgEIgBADIACAFIgFADgAhHCNIgEgDIAEgDIACACIACAAIAAgRIAFACIAAALIAIgHIAGADIgOAKQgDADgDAAIgDgBgABLB2IAFgEIAGAJIAAgNIAEgEIAMARIgEAEIgHgKIAAAOIgEADgAhaCCQgDgEgBgEQgBgEADgEQADgDAEgBQAEgBAEADQAEAEAAAFIgFAAQAAgDgCgCQgBAAAAAAQAAAAgBgBQAAAAgBAAQAAAAgBAAQAAABgBAAQAAAAgBAAQAAABgBAAQAAAAAAABQgBAAAAABQAAAAAAABQAAAAAAABQAAABAAAAQAAABAAAAQAAAAAAABQAAAAABABQAAAAAAAAQACACAEgBIABAFIgEABQgDAAgDgCgABmBuIgBgEQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAAAQABgBAAAAQAAAAABgBQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAABAAAAQABAAAAABQABAAAAAAQAAABAAAAQABABAAAAQAAABAAAAIgCAEQAAAAgBAAQAAAAAAABQgBAAAAAAQgBAAAAAAIgEgBgAhoBuQgBgBAAAAQAAgBAAAAQgBgBAAAAQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAgBQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABABAAAAQAAAAABABQAAAAAAAAQABABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAAAAAABQAAAAgBABQAAAAAAABQgBAAAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAgBgBAAQAAAAAAAAgAieAKIgKABIADgOIAKgBIAGgeQADgMAHgJQAIgJALgCIASgBIgBABQgHACgCAJIgJAvIAcgDIgDAOIgdADIgQBSIghAEgAhVBSQgLgIAEgTIAShZQACgNgHABIABgCIAUgCQAFgBAEADQAJAHgFAWIgOBFQgCAJAFADQAEAEAHgEQAHgCAGgJIABgDIALg1QACgNgHABIABgCIAUgDQAEAAAEADQAJAHgFAWIgHAhQgBAJAEADQAEADAHgCQAHgEAGgHIAMg5QACgGgCgEIgBgBIgCgBIgBAAIAAgCIAVgDQAEAAAFADQAEAEABAIIADgFQALgOARgDQAGgBAGACQAKADADAKQACAHgBAHIgIAmQgCAIAEADQAFAEAHgDQAGgDAFgFIABgHIAKg0IgKABIADgPIAKgBIACgIQACgLAIgIQAIgLALgBIARgCIAAACQgHACgCAJIgFAYIAPgCIgDAPIgPACIgLA0QgBAGACAEQACAEAFAAIABAAQAIgBAFgFQgBAHgGAIQgGAGgHADIgDABQgQAFgJgHQgFgEgCgGQgNAOgOAEQgQAFgJgGQgLgIAEgTIAIgpQABgGgDgDQgDgDgGADQgEABgEAFQgFAFgBAFIgNBCIgiADIACgJQgMANgNADQgPAFgJgGQgGgFgBgIQgNARgQAEQgHACgFAAQgIAAgFgDgAgOggQgFgEAAgFQABgHAGgEQAFgEAHgBQAHgBAFAEQAFADAAAGQgBAGgFAFQgGAEgHABIgCAAQgFAAgFgDgAiwgiQgMgEgIgIQgIgHgCgKQgCgKADgLQAEgMAJgJQAJgKANgFQANgGAPAAQAfgBBXAVQBWAVAngBQAXgCAQgIQAQgLACgOQACgJgDgJQAOASgDATQgDAQgPALQgUAPgjACQgnAChNgTQhNgTggABQgLABgJAEQgLAEgHAHQgHAIAAAJQgBAHAEAGQAEAHAIAGIgIABIgIgBgABSiuQgmgQgqAAQgkAAgiANQghAMgbAYIgXABQAeggAngQQAogRAsAAQAfgBAeAJQAdAJAZAQQARALAIAMQAHAMgCAJQgcgdglgRgAAZiJIABgDIAJgFQAAAAABAAQABgBAAAAQABAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAAAAAgBQgBAAAAAAQgCAAgDACIgDgFQAEgDAFABIAFADQACACgBADQAAABAAAAQAAABgBAAQAAABAAAAQgBABAAAAIgEACIgEACIAIACIgBAFgAgniJIAGgHQABgBAAAAQAAgBABAAQAAgBAAAAQAAgBAAAAQAAgBgBAAQAAAAAAAAQAAgBgBAAQAAAAgBABQAAAAgBAAQAAAAgBABQAAAAgBABQAAAAAAABIgFgCQADgFAEgCQAEAAACABQABAAAAABQABAAAAABQABAAAAABQAAAAAAABQAAABABAAQAAABAAAAQAAABAAAAQgBABAAAAIgDAEIgCADIAIgBIABAEIgQAEgAAGiNQgCgDAAgEQAAgFADgDQADgDAEABQAEgBADAEQACADAAAFQAAAEgDADQgDADgFAAQgEgBgCgDgAALiYIgBAEQgBAGAEAAQAEAAAAgGIgBgEQAAAAAAgBQgBAAAAAAQAAAAgBAAQAAgBAAAAIgDACgAgQiLQgDgDAAgFQgBgFADgDQACgDAEAAQAFgBACADQADADABAFQAAAEgCADQgDADgEABQgEAAgDgCgAgOiUIACAEIADACIACgCQAAAAABgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAgBgBAAQAAAAAAgBQgBAAAAAAQAAAAgBAAQAAgBAAAAQgEABAAAFg");
	this.shape.setTransform(-0.2,0);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Слой_3
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhdDdQgrgSgggiQgigggSgrQgTgtAAgxQAAgwATgtQASgrAiggQAggiArgSQAtgTAwAAQAxAAAtATQArASAgAiQAiAgASArQATAtAAAwQAAAxgTAtQgSArgiAgQggAigrASQgtATgxAAQgwAAgtgTg");

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.logo, new cjs.Rectangle(-24,-24,48,48), null);


(lib.btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_5
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("ABCAyQgHgHAAgOIAAg5QAAgNAHgIQAHgHANAAQANAAAGAHQAIAIAAANIAAA5QAAAOgIAHQgGAHgNAAQgNAAgHgHgABPgmQgDADABAGIAAA7QgBAGADADQADACAEAAQAEAAADgCQACgDAAgGIAAg7QAAgGgCgDQgCgCgFAAQgEAAgDACgAlpAyQgGgHAAgOIAAg5QAAgOAGgHQAIgHAMAAQANAAAHAHQAGAIAAANIAAALIgRAAIAAgMQAAgHgCgCQgCgCgFAAQgEAAgCACQgDADAAAGIAAAVIAYAAIAAAPIgYAAIAAAXQAAAGADADQACACAEAAQAEAAADgCQACgCAAgHIAAgQIARAAIAAAPQAAAOgGAHQgHAHgNAAQgMAAgIgHgAmoAyQgGgHAAgOIAAg5QAAgOAGgHQAJgHALAAQANAAAIAHQAGAIAAANIAAA5QAAAOgGAHQgHAHgOAAQgMAAgIgHgAmagmQgDADAAAGIAAA7QAAAGADADQACACAEAAQAEAAADgCQACgCAAgHIAAg7QAAgHgCgCQgCgCgFAAQgEAAgCACgAonAyQgGgHAAgOIAAg5QAAgOAGgHQAIgHAMAAQANAAAHAHQAGAIAAANIAAALIgQAAIAAgMQAAgGgDgDQgCgCgFAAQgEAAgCACQgDADAAAGIAAA7QAAAGADADQACACAEAAQAFAAACgCQADgDAAgGIAAgQIAQAAIAAAPQAAANgGAIQgGAHgOAAQgMAAgIgHgAsBAyQgHgHAAgOIAAg5QAAgOAHgHQAHgHAMAAQAOAAAGAHQAIAIgBANIAAA5QABAOgIAHQgGAHgOAAQgMAAgHgHgAr0gmQgCADgBAGIAAA7QABAGACADQADACADAAQAEAAAEgCQACgDAAgGIAAg7QAAgGgCgDQgDgCgFAAQgEAAgCACgAt8AyQgGgHgBgOIAAgOIARAAIAAAPQAAAHADACQACACAEAAQAEAAADgCQACgEAAgGIAAgJQAAgIgCgDQgEgEgFAAIgCAAIAAgPIADAAQAFAAADgCQACgDAAgGIAAgHQAAgHgCgDQgCgCgFAAQgEAAgCACQgDACAAAHIAAAMIgRAAIAAgLQABgNAGgIQAIgHAMAAQAMAAAIAHQAGAHAAAOIAAADQAAASgMAFQAHACACAGQADAGAAAIIAAAJQAAAOgGAHQgHAHgNAAQgMAAgIgHgANyA4IAAguIgGAAQgHAAgCADQgDAEAAAIIAAAaIgBADIgBACIgSAAIACgGIAAgZQAAgIADgHQACgGAIgDQgMgEAAgSIAAgIQAAgNAGgHQAGgGAOAAIAaAAIAABvgANjgkQgCACgBAGIAAALQAAAHADADQADACAFAAIAHAAIAAgiIgJAAQgEAAgCADgAMkA4IAAhfIgSAAIAAgQIA2AAIAAAQIgSAAIAABfgALqA4IAAhfIgSAAIAAgQIA2AAIAAAQIgSAAIAABfgALAA4IAAhQIgWBQIgSAAIAAhvIAQAAIAABCIAShCIAWAAIAABvgAJcA4IAAhvIAaAAQANAAAHAHQAGAHAAAOIAAAOQAAANgGAHQgHAHgNAAIgJAAIAAAqgAJtgBIAJAAQAEAAACgCQACgDAAgGIAAgRQAAgFgCgDQgDgCgDAAIgJAAgAJCA4IgRgtIgGAKIAAAjIgSAAIAAhvIASAAIAAAxIAYgxIARAAIgYAyIAYA9gAHtA4IAAhfIgSAAIAAgQIA2AAIAAAQIgSAAIAABfgAHBA4IgVhQIAABQIgRAAIAAhvIAXAAIASBCIAAhCIAPAAIAABvgAF+A4IAAhvIARAAIAABvgAFHA4IAAhvIASAAIAABfIAdAAIAAAQgAEQA4IAAhvIAvAAIAAAQIgdAAIAAAiIAWAAIAAAPIgWAAIAAAugAC8A4IAAhvIAxAAIAAAQIgfAAIAAAfIAYAAIAAAPIgYAAIAAAhIAfAAIAAAQgAB7A4IAAhvIAbAAQANAAAHAGQAGAHAAANIAAAEQAAAJgCAFQgCAFgHADQAIADACAFQADAGAAAJIAAAJQAAAOgHAGQgGAHgOAAgACNAoIAKAAQAFAAACgDQADgCgBgGIAAgKQABgHgDgEQgDgDgGAAIgIAAgACNgKIAHAAQAGAAACgCQADgCAAgHIAAgHQAAgGgCgCQgCgDgFAAIgJAAgAAQA4IAAhfIgRAAIAAgQIA1AAIAAAQIgSAAIAABfgAg5A4IAAgUIgIAAQgNAAgHgHQgGgHgBgNIAAgeQABgOAGgHQAHgHANAAIAIAAIAAgGIASAAIAAAGIAIAAQANAAAHAHQAGAIABANIAAAeQgBAMgGAIQgHAHgNAAIgIAAIAAAUgAgnAUIAIAAQAEAAADgCQACgCAAgGIAAggQAAgGgCgCQgDgDgEAAIgIAAgAhIgeQgCACAAAGIAAAgQAAAFACADQADACAEAAIAIAAIAAg1IgIAAQgEAAgDADgAhxA4IgDgUIgWAAIgDAUIgQAAIAShvIAaAAIASBvgAh3AUIgIg3IgJA3IARAAgAjUA4IAAhvIAaAAQAMAAAIAHQAGAIAAANIAAAOQAAANgGAHQgIAHgMAAIgJAAIAAAqgAjDgBIAJAAQAEAAACgCQACgCAAgHIAAgRQAAgGgCgCQgCgCgEAAIgJAAgAjuA4IgRgtIgGAKIAAAjIgSAAIAAhvIASAAIAAAxIAYgxIARAAIgZAyIAZA9gAnuA4IAAhvIAbAAQAOAAAGAGQAHAIgBAMIAAAEQAAAJgDAFQgCAFgGADQAHADADAFQADAGAAAJIAAAJQAAAOgGAGQgHAHgNAAgAncAoIALAAQAEAAACgDQADgCAAgGIAAgKQAAgHgDgEQgDgDgGAAIgIAAgAncgKIAHAAQAFAAADgCQACgCAAgHIAAgHQAAgGgCgCQgBgDgGAAIgIAAgAphA4IAAhQIgWBQIgSAAIAAhvIAQAAIAABCIAShCIAWAAIAABvgArIA4IAAhvIAvAAIAAAQIgdAAIAAAaIAIAAQAOAAAGAHQAHAGgBAOIAAAOQABAOgHAHQgGAHgOAAgAq2AoIAIAAQAFAAACgCQACgCAAgHIAAgQQAAgHgCgCQgDgCgEAAIgIAAgAtCA4IAAhvIAZAAQANAAAHAHQAHAHgBAOIAAAOQABANgHAHQgHAHgNAAIgIAAIAAAqgAsxgBIAIAAQAFAAABgCQADgDAAgGIAAgRQAAgFgDgDQgCgCgEAAIgIAAg");
	this.shape.setTransform(-0.1,-1.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(2));

	// Слой_6
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#F8E300").s().p("AwcCFIAAkJMAg5AAAIAAEJg");
	this.shape_1.setTransform(0,-1.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#BFAF01").s().p("AwcCFIAAkJMAg5AAAIAAEJg");
	this.shape_2.setTransform(0,-1.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1}]}).to({state:[{t:this.shape_2}]},1).wait(1));

	// Слой_7
	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#BFAF00").s().p("AwcCFIAAkJMAg5AAAIAAEJg");
	this.shape_3.setTransform(0,1.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#F8E202").s().p("AwcCFIAAkJMAg5AAAIAAEJg");
	this.shape_4.setTransform(0,1.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3}]}).to({state:[{t:this.shape_4}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-105.3,-14.8,210.6,29.6);


(lib.box2_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.box2();
	this.instance.parent = this;
	this.instance.setTransform(-58,-75,0.466,0.466);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.box2_1, new cjs.Rectangle(-58,-75,116.5,150), null);


(lib.box1_mc = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.box1();
	this.instance.parent = this;
	this.instance.setTransform(-58,-75,0.466,0.466);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.box1_mc, new cjs.Rectangle(-58,-75,116.5,150), null);


(lib.bgImg4_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.bgImg4();
	this.instance.parent = this;
	this.instance.setTransform(-150,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bgImg4_1, new cjs.Rectangle(-150,-300,300,600), null);


(lib.bgImg3_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.bgImg3();
	this.instance.parent = this;
	this.instance.setTransform(-150,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bgImg3_1, new cjs.Rectangle(-150,-300,300,600), null);


(lib.bgImg2_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.bgImg2();
	this.instance.parent = this;
	this.instance.setTransform(-150,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bgImg2_1, new cjs.Rectangle(-150,-300,300,600), null);


(lib.bgImg1_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.bgImg1();
	this.instance.parent = this;
	this.instance.setTransform(-150,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bgImg1_1, new cjs.Rectangle(-150,-300,300,600), null);


(lib.t4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AzMA+IAAh8MAmZAAAIAAB8g");
	mask.setTransform(3.2,19.3);

	// t4_3
	this.instance = new lib.t4_3();
	this.instance.parent = this;
	this.instance.setTransform(-11.5,31.9);
	this.instance._off = true;

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(10).to({_off:false},0).to({y:19.2},10,cjs.Ease.quadInOut).wait(1));

	// mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	mask_1.graphics.p("AzMA+IAAh8MAmZAAAIAAB8g");
	mask_1.setTransform(3.2,0.1);

	// t4_2
	this.instance_1 = new lib.t4_2();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-45.1,12.7);
	this.instance_1._off = true;

	var maskedShapeInstanceList = [this.instance_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(5).to({_off:false},0).to({y:0},10,cjs.Ease.quadInOut).wait(6));

	// mask (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	mask_2.graphics.p("AzMBLIAAiVMAmZAAAIAACVg");
	mask_2.setTransform(3.2,-18.1);

	// t4_1
	this.instance_2 = new lib.t4_1();
	this.instance_2.parent = this;
	this.instance_2.setTransform(0.1,-3.8);

	var maskedShapeInstanceList = [this.instance_2];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({y:-18.1},10,cjs.Ease.quadInOut).wait(11));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-78.7,-10.7,157.5,0.2);


(lib.t3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AzMBYIAAivMAmZAAAIAACvg");
	mask.setTransform(3.2,8.1);

	// t3_2
	this.instance = new lib.t3_2();
	this.instance.parent = this;
	this.instance.setTransform(-15.9,22.9);
	this.instance._off = true;

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(5).to({_off:false},0).to({y:9.6},10,cjs.Ease.quadInOut).wait(1));

	// mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	mask_1.graphics.p("AzMBXIAAitMAmZAAAIAACtg");
	mask_1.setTransform(3.2,-11.2);

	// t3_1
	this.instance_1 = new lib.t3_1();
	this.instance_1.parent = this;
	this.instance_1.setTransform(0.1,3.7);

	var maskedShapeInstanceList = [this.instance_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({y:-9.6},10,cjs.Ease.quadInOut).wait(6));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.t2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AzMBLIAAiVMAmZAAAIAACVg");
	mask.setTransform(3.2,19.1);

	// t2_3
	this.instance = new lib.t2_3();
	this.instance.parent = this;
	this.instance.setTransform(0.1,33.8);
	this.instance._off = true;

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(10).to({_off:false},0).to({y:19.3},10,cjs.Ease.quadInOut).wait(1));

	// mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	mask_1.graphics.p("AzMBAIAAh/MAmZAAAIAAB/g");
	mask_1.setTransform(3.2,-1.1);

	// t2_2
	this.instance_1 = new lib.t2_2();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-26.7,11.6);
	this.instance_1._off = true;

	var maskedShapeInstanceList = [this.instance_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(5).to({_off:false},0).to({y:-1},10,cjs.Ease.quadInOut).wait(6));

	// mask (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	mask_2.graphics.p("AzMBYIAAivMAmZAAAIAACvg");
	mask_2.setTransform(3.2,-22.6);

	// t2_1
	this.instance_2 = new lib.t2_1();
	this.instance_2.parent = this;
	this.instance_2.setTransform(-18.6,-7.6);

	var maskedShapeInstanceList = [this.instance_2];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({y:-20.2},10,cjs.Ease.quadInOut).wait(11));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.t1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AzMBaIAAizMAmZAAAIAACzg");
	mask.setTransform(3.2,19.5);

	// t1_3
	this.instance = new lib.t1_3();
	this.instance.parent = this;
	this.instance.setTransform(0,37.3);
	this.instance._off = true;

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(10).to({_off:false},0).to({y:19.2},10,cjs.Ease.quadInOut).wait(1));

	// mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	mask_1.graphics.p("AzMA+IAAh8MAmZAAAIAAB8g");
	mask_1.setTransform(3.2,0.6);

	// t1_2
	this.instance_1 = new lib.t1_2();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-8.5,13.3);
	this.instance_1._off = true;

	var maskedShapeInstanceList = [this.instance_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(5).to({_off:false},0).to({y:0.6},10,cjs.Ease.quadInOut).wait(6));

	// mask (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	mask_2.graphics.p("AzMBOIAAibMAmZAAAIAACbg");
	mask_2.setTransform(3.2,-20.2);

	// t1_1
	this.instance_2 = new lib.t1_1();
	this.instance_2.parent = this;
	this.instance_2.setTransform(-16.1,-4.5);

	var maskedShapeInstanceList = [this.instance_2];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({y:-20.3},10,cjs.Ease.quadInOut).wait(11));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.box1_mc_p2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("ApSBsIAAjXISlAAIAADXg");
	mask.setTransform(-0.4,-71.1);

	// Слой_1
	this.instance = new lib.box1_mc();
	this.instance.parent = this;

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.box1_mc_p2, new cjs.Rectangle(-58,-75,116.5,14.7), null);


(lib.box1_mc_p1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("ApsLBIAA2BITZAAIAAWBg");
	mask.setTransform(1.4,10.2);

	// Слой_1
	this.instance = new lib.box1_mc();
	this.instance.parent = this;

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.box1_mc_p1, new cjs.Rectangle(-58,-60.3,116.5,135.4), null);


(lib.box1_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_3
	this.instance = new lib.box1_mc_p2();
	this.instance.parent = this;
	this.instance.setTransform(58,-60.4,1,1,0,0,0,58,-60.4);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({_off:false},0).to({rotation:18.2,x:58.1,y:-60.3},10,cjs.Ease.quadInOut).wait(1));

	// Слой_2
	this.instance_1 = new lib.box1_mc_p1();
	this.instance_1.parent = this;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1).to({_off:false},0).wait(11));

	// Слой_1
	this.instance_2 = new lib.box1_mc();
	this.instance_2.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({_off:true},1).wait(11));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-58,-75,116.5,150);


(lib.banner = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// logo
	this.instance = new lib.logo();
	this.instance.parent = this;
	this.instance.setTransform(114.3,-261.8,1.035,1.035,-90,0,0,0.1,-0.1);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(20).to({_off:false},0).to({regX:0.2,regY:-0.2,scaleX:1.03,scaleY:1.03,rotation:-44.9,x:114.4,alpha:1},5).to({regX:0.1,regY:-0.1,scaleX:1.03,scaleY:1.03,rotation:0,x:114.3},5).wait(300).to({alpha:0},15).wait(1));

	// p2
	this.instance_1 = new lib.p2_1();
	this.instance_1.parent = this;
	this.instance_1.setTransform(114.3,-261.8,1.08,1.08,0,0,0,0.1,-0.1);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(10).to({_off:false},0).to({regX:-0.1,rotation:90,x:114.2,y:-261.9,alpha:1},5).to({rotation:180,x:114.3,y:-261.8},5).to({regX:0,regY:0,rotation:270},5).to({rotation:360,alpha:0},5).to({_off:true},1).wait(315));

	// p1
	this.instance_2 = new lib.p1_1();
	this.instance_2.parent = this;
	this.instance_2.setTransform(114.9,-262.4,1.08,1.08,0,0,0,0.1,-0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(5).to({rotation:360},10,cjs.Ease.cubicIn).to({alpha:0},5).to({_off:true},1).wait(309).to({_off:false},0).to({alpha:1},15).wait(1));

	// bgImg1
	this.instance_3 = new lib.bgImg1_1();
	this.instance_3.parent = this;
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(330).to({_off:false},0).to({alpha:1},15).wait(1));

	// btn
	this.instance_4 = new lib.btn("single",0);
	this.instance_4.parent = this;
	this.instance_4.setTransform(0,-156.3,0.01,0.01,0,0,0,-4.9,19.4);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(280).to({_off:false},0).to({regX:-0.1,regY:0.1,scaleX:1.24,scaleY:1.24,x:-0.1,y:-156.4},10,cjs.Ease.backOut).wait(15).to({regY:0.2,scaleX:1.19,scaleY:1.19,y:-156.3,startPosition:1},0).wait(3).to({regY:0.1,scaleX:1.24,scaleY:1.24,y:-156.4,startPosition:0},0).wait(4).to({regY:0.2,scaleX:1.19,scaleY:1.19,y:-156.3,startPosition:1},0).wait(3).to({regY:0.1,scaleX:1.24,scaleY:1.24,y:-156.4,startPosition:0},0).wait(31));

	// box1
	this.instance_5 = new lib.box1_1("single",0);
	this.instance_5.parent = this;
	this.instance_5.setTransform(-239.5,75.1,1.409,1.41,0,0,0,-0.1,0.1);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(265).to({_off:false},0).to({x:-58},15,cjs.Ease.cubicOut).wait(66));

	// box2
	this.instance_6 = new lib.box2_1();
	this.instance_6.parent = this;
	this.instance_6.setTransform(230.9,71.3,1.298,1.299,0,0,0,0.1,0.1);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(265).to({_off:false},0).to({x:68.6},15,cjs.Ease.cubicOut).wait(66));

	// bgImg4
	this.instance_7 = new lib.bgImg4_1();
	this.instance_7.parent = this;
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(250).to({_off:false},0).to({alpha:1},15).wait(81));

	// t4
	this.instance_8 = new lib.t4("synched",0,false);
	this.instance_8.parent = this;
	this.instance_8.setTransform(-0.2,-159.4,1.65,1.631,0,0,0,-0.1,-0.1);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(205).to({_off:false},0).to({_off:true},60).wait(81));

	// box1
	this.instance_9 = new lib.box1_1("single",0);
	this.instance_9.parent = this;
	this.instance_9.setTransform(-234.1,182.3,0.849,0.849,0,0,0,-0.2,0.1);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(205).to({_off:false},0).to({regX:-0.1,x:-0.2},15,cjs.Ease.cubicOut).to({_off:true},45).wait(81));

	// bgImg3
	this.instance_10 = new lib.bgImg3_1();
	this.instance_10.parent = this;
	this.instance_10.alpha = 0;
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(190).to({_off:false},0).to({alpha:1},15).to({_off:true},60).wait(81));

	// t3
	this.instance_11 = new lib.t3("synched",0,false);
	this.instance_11.parent = this;
	this.instance_11.setTransform(-21.7,-175,1.65,1.631);
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(145).to({_off:false},0).to({_off:true},60).wait(141));

	// box2
	this.instance_12 = new lib.box2_1();
	this.instance_12.parent = this;
	this.instance_12.setTransform(-251.3,168.8,1.109,1.109,0,0,0,-0.1,0.1);
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(145).to({_off:false},0).to({x:-64.9},15,cjs.Ease.cubicOut).to({_off:true},45).wait(141));

	// bgImg2
	this.instance_13 = new lib.bgImg2_1();
	this.instance_13.parent = this;
	this.instance_13.alpha = 0;
	this.instance_13._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(130).to({_off:false},0).to({alpha:1},15).to({_off:true},60).wait(141));

	// t2
	this.instance_14 = new lib.t2("synched",0,false);
	this.instance_14.parent = this;
	this.instance_14.setTransform(-33.3,-157.9,1.65,1.631,0,0,0,-0.1,-0.2);
	this.instance_14._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(80).to({_off:false},0).to({_off:true},65).wait(201));

	// t1
	this.instance_15 = new lib.t1("synched",0,false);
	this.instance_15.parent = this;
	this.instance_15.setTransform(-16.1,-160.4,1.65,1.631,0,0,0,-0.1,-0.1);
	this.instance_15._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_15).wait(5).to({_off:false},0).wait(60).to({startPosition:20},0).to({alpha:0},15).to({_off:true},1).wait(265));

	// box2
	this.instance_16 = new lib.box2_1();
	this.instance_16.parent = this;
	this.instance_16.setTransform(218.1,172,1.109,1.109);
	this.instance_16._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_16).wait(20).to({_off:false},0).to({x:64.7},15,cjs.Ease.cubicOut).wait(30).to({x:240.2},15,cjs.Ease.cubicInOut).to({_off:true},65).wait(201));

	// box1
	this.instance_17 = new lib.box1_1("single",0);
	this.instance_17.parent = this;
	this.instance_17.setTransform(-248.4,172.1,1.109,1.109,0,0,0,-0.1,0.1);
	this.instance_17._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_17).wait(20).to({_off:false},0).to({regX:-0.2,x:-66.4},15,cjs.Ease.cubicOut).wait(30).to({startPosition:0},0).to({x:-0.4},15,cjs.Ease.quadInOut).wait(5).to({mode:"synched",loop:false},0).to({_off:true},60).wait(201));

	// bgImg1
	this.instance_18 = new lib.bgImg1_1();
	this.instance_18.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_18).wait(346));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,-300,300,600);


// stage content:
(lib._300x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// banner
	this.instance = new lib.banner();
	this.instance.parent = this;
	this.instance.setTransform(150.1,300.1,1,1,0,0,0,0.1,0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(150,300,300,600);
// library properties:
lib.properties = {
	id: '0A6E3F5DF6B342F4AF907DBE848CDF8D',
	width: 300,
	height: 600,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/bgImg1.jpg", id:"bgImg1"},
		{src:"images/bgImg2.jpg", id:"bgImg2"},
		{src:"images/bgImg3.jpg", id:"bgImg3"},
		{src:"images/bgImg4.jpg", id:"bgImg4"},
		{src:"images/box1.png", id:"box1"},
		{src:"images/box2.png", id:"box2"},
		{src:"images/p1.png", id:"p1"},
		{src:"images/p2.png", id:"p2"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['0A6E3F5DF6B342F4AF907DBE848CDF8D'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;