(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.bgImg = function() {
	this.initialize(img.bgImg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,330,660);


(lib.dev1 = function() {
	this.initialize(img.dev1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,276,218);


(lib.dev2 = function() {
	this.initialize(img.dev2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,204,236);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.urText = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1,2,0,3).p("AzrjHMAnXAAAIAAGPMgnXAAAg");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AmBCTIABgHIAGAAIAEAAQABAAAAgBQAAAAABAAQAAgBABAAQAAgBABAAIAEgLIgSgsIAJAAIAOAiIANgiIAJAAIgZA7QgDAEgDABQgDACgEAAgACXCTIAAhBIAJAAIAAAGQADgEADgCQAFgCADAAQAGAAAEADQAEADAEAGQACAEAAAHQAAAIgCAEQgEAHgEACQgEADgGAAQgDAAgFgCQgDgCgDgEIAAAcgACmBaQgDACgCAEQgBADAAAEQAAAFABADQACAEADACQADACADAAQAFAAADgCQACgBACgFQACgDAAgFQAAgEgCgDIgEgGQgDgCgFAAQgDAAgDACgAheCTIAAhBIAIAAIAAAGQADgEAEgCQAFgCAEAAQAFAAAFADQAEADADAGQADAFAAAGQAAAHgDAFQgDAGgEADQgFADgFAAQgEAAgFgCQgEgCgDgEIAAAcgAhPBaIgFAGQgBADgBAEQABAFABADQACAFADABQADACAEAAQAEAAACgCQAEgCABgEQACgDAAgFQAAgEgCgDQAAgDgFgDQgCgCgEAAQgEAAgDACgAqZCLIAAgOIgxAAIAAhAIAIAAIAAA4IAgAAIAAg4IAJAAIAAA4IAJAAIAAAWgAEqCJIAAgMIgmAAIAAgrIAJAAIAAAkIAVAAIAAgkIAIAAIAAAkIAHAAIAAATgALaB+IgCgCIgBgDIABgDIACgCIACgBIAEABIACACIABADIgBADIgCACIgEABgAIzB8QgEgDgCgGQgEgFAAgHQAAgGAEgFQACgGAEgDQAGgDAFAAQADAAAGACQADACADAEIAAgGIAIAAIAAArIgIAAIAAgGQgDAEgDACQgGACgDAAQgFAAgGgDgAI5BaQgEADgBADQgCAEAAADQAAAEACAEQACAEADACQACACAFAAQAEAAADgCQADgCABgEQACgDAAgFQAAgEgCgDQgBgDgDgDQgDgCgEAAQgFAAgCACgAIFB7QgFgDgDgFQgDgFAAgHQAAgGADgFQADgFAFgDQAFgEAHAAQAFAAAGADQAEACAEAEIgGAFIgGgEIgGgBQgFAAgDABQgEADgBADQgCACAAAFQAAAGACACQACAEADACQAEACAEAAIAGgCIAGgEIAGAFQgDAEgFACQgGADgFAAQgHAAgFgEgAG5B8QgEgDgDgGQgDgFAAgHQAAgGADgFQADgGAEgDQAGgDAEAAQAEAAAFACQADACAEAEIAAgGIAIAAIAAArIgIAAIAAgGQgEAEgDACQgFACgEAAQgEAAgGgDgAG+BaQgDADgBADQgCAEAAADQAAAEACAEQABAEADACQACACAFAAQAEAAADgCQAEgCABgEQACgDAAgFQAAgEgCgDQgBgDgEgDQgDgCgEAAQgFAAgCACgADWB8QgGgDgCgGQgDgFAAgHQAAgGADgFQACgGAGgDQAEgDAGAAQADAAAFACQADACADAEIAAgGIAJAAIAAArIgJAAIAAgGQgDAEgDACQgFACgDAAQgGAAgEgDgADaBaQgDACgBAEQgCADAAAEQAAAFACADQABAEADACQADACAEAAQAFAAACgCQAEgCABgEQABgDAAgFQAAgEgBgDQgBgDgEgDQgCgCgFAAQgEAAgDACgABCB7QgGgDgCgFQgDgFAAgHQAAgGADgFQACgFAGgDQAFgEAHAAQAFAAAGADQAFACADAEIgGAFIgGgEIgGgBQgFAAgDABQgEADgBADQgCACAAAFQAAAGACACQACAEADACQAEACAEAAIAGgCIAGgEIAGAFQgDAEgFACQgGADgFAAQgHAAgFgEgAAUB8QgHgFgCgEQgCgFAAgHQgBgFADgGQADgFAFgDQAFgEAHAAQAGAAAFADQAEABADAEIgEAGQgCgDgEgCIgIgBQgDAAgDABIgFAFIgDAGIAVAAIAAAGIgVAAQAAAGAEAEQAFADAFAAIAIgBQAEgCACgDIAEAGQgDAEgEABQgFADgGAAQgGAAgFgDgAgfB7QgFgDgDgFQgDgFAAgGQAAgHADgFQADgGAFgDQAFgDAGAAQAGAAAFADQAEADAEAFQACAFAAAGIgBAEIghAAQAAADACAEQADADADABQACACAFAAIAHgCIAGgDIAFAFQgFAEgDABQgFADgGAAQgHAAgFgEgAgdBbQgDADgBAGIAaAAQgBgGgEgDQgDgDgFAAQgFAAgEADgAm/B8QgEgDgDgGQgCgGgBgGQABgFACgGQADgGAEgDQAFgDAGAAQAEAAAEACQAFADACADIAAgGIAIAAIAAArIgIAAIAAgGQgCAEgFACQgEACgEAAQgGAAgFgDgAm5BaQgEADgBADQgCACAAAFQAAAGACACQABAEAEACQACACAEAAQAFAAACgCQADgCACgEQACgCAAgGQAAgFgCgCQgBgDgEgDQgCgCgFAAQgEAAgCACgAnuB9QgFgDgDgDIAFgFIAGAEIAHABQAFAAAEgBQACgCAAgEQAAgGgJAAIgJAAIAAgGIAHAAQAFAAADgBQABgCAAgDQAAgBAAgBQAAAAAAgBQAAAAgBgBQAAAAAAgBQgCgBgFAAQgIAAgEAFIgGgGIAIgFQAGgCAEAAQAIAAAEAEQAFADAAAGQAAAEgBACIgGAEQAGACABACQACACAAAEQAAADgCAEQgDADgEACQgGACgFAAQgEAAgGgCgAo2B8QgEgDgDgGQgDgFAAgHQAAgGADgFQADgGAEgDQAGgDAEAAQAEAAAFACQADACAEAEIAAgGIAIAAIAAArIgIAAIAAgGQgEAEgDACQgFACgEAAQgEAAgGgDgAoxBaQgDADgBADQgCAEAAADQAAAEACAEQABAEADACQACACAFAAQAEAAADgCQAEgCABgEQACgDAAgFQAAgEgCgDQgBgDgEgDQgDgCgEAAQgFAAgCACgAkDB7QgFgDgEgFQgCgFAAgGQAAgHACgFQAEgGAFgDQAFgDAGAAQAHAAAEADQAHAEABAFQAEAFAAAHQAAAGgEAFQgBAFgHADQgEADgHAAQgGAAgFgDgAj/BaIgFAGIgCAIQAAADACAEIAFAGQADABAEAAQAEAAADgBQAEgCABgEQACgCAAgFQAAgFgCgDQgBgEgEgCQgDgBgEAAQgEAAgDABgALDB9IAAgrIAIAAIAAArgAKiB9IAAgkIgPAAIAAgHIAmAAIAAAHIgPAAIAAAkgAKBB9IAAggIgWAgIgIAAIAAgrIAIAAIAAAgIAWggIAIAAIAAArgAGcB9IAAgTIgWAAIAAATIgJAAIAAgrIAJAAIAAARIAWAAIAAgRIAJAAIAAArgAFSB9IAAgrIAJAAIAAArgAE7B9IAAgrIAJAAIAAArgAB2B9IAAgkIgPAAIAAgHIAnAAIAAAHIgPAAIAAAkgAiIB9IAAggIgXAgIgIAAIAAgrIAIAAIAAAgIAXggIAIAAIAAArgAjXB9IAAgrIATAAQAJAAADADQAFADAAAFIgCAGQgBACgEACQAFABACADQABACAAAEQAAAEgBACQgDAEgDABQgDABgFAAgAjOB3IALAAQAEAAADgCQAAAAABgBQAAAAAAgBQABAAAAgBQAAgBAAAAQAAgHgJAAIgLAAgAjOBkIAJAAQAFAAACgBQACgCABgDQAAgGgKAAIgJAAgAkhB9IAAgfIgPATIgFAAIgOgTIAAAfIgIAAIAAgrIAIAAIARAWIARgWIAIAAIAAArgApTB9IAAgTIgWAAIAAATIgJAAIAAgrIAJAAIAAARIAWAAIAAgRIAJAAIAAArgAqHB9IAAgrIAJAAIAAArgAJvBIQgEgCgBgCQgCgEgBgEIAHAAIACAGQADACADAAQAEAAABgCQADgDABgDIAGAAQgBAGgCACIgEAEQgEACgEAAQgEAAgDgCgALFBHIgDgCIgBgDIABgDIADgCIACAAIADAAIACACIAAADIAAADIgCACIgDABgAE8BHIgCgCIAAgDIAAgDIACgCIADAAIADAAIACACIABADIgBADIgCACIgDABgAqGBHIgCgCIAAgDIAAgDIACgCIADAAIADAAIACACIABADIgBADIgCACIgDABgAFaBGQAAgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAAAQAAgBAAAAQABgBAAAAQABAAAAAAQABgBAAAAQAAAAABAAQAAAAABAAQAAAAABABQAAAAABAAQAAAAAAABQABAAAAABQAAAAABAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQgBABAAAAQAAAAgBABQAAAAAAAAQgBABAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAAAgBAAQAAAAgBgBQAAAAgBAAgAFMBGIgBgEIABgDQAAgBABAAQAAAAABAAQAAgBABAAQAAAAABAAQABAAAAAAQAAAAABABQAAAAABAAQAAAAABABIABADIgBAEQgBAAAAAAQgBABAAAAQgBAAAAAAQAAAAgBAAQgBAAAAAAQgBAAAAAAQgBAAAAgBQgBAAAAAAgAlwArIAAhBIAIAAIAAAHQACgDAEgDQADgCAFAAQAGAAAFADQAFAEACAEQADAGAAAGQAAAGgDAFQgCAFgFADQgFADgGAAQgFAAgDgCQgEgBgCgEIAAAcgAligNIgFAFIgBAIQAAAEABADIAFAGQADABAEAAQAEAAADgBQAEgDAAgDIADgHIgDgIQgBgDgDgCQgDgCgEAAQgFAAgCACgAq2ArIAAhBIAIAAIAAAHQACgDAEgDQAEgCAEAAQAGAAAFADQAEADADAFQADAGAAAGQAAAFgDAGQgDAFgEADQgFADgGAAQgEAAgEgCQgEgBgCgEIAAAcgAqogNQgDACgBADQgCAEgBAEQABAEACADQAAADAEADQADABAEAAQAEAAADgBQADgDABgDQACgDAAgEQAAgEgCgEQgCgDgCgCQgCgCgFAAQgEAAgDACgADLAgIAAgLIgkAAIAAALIgHAAIAAgSIAFAAIACgGIACgLIABgTIAiAAIAAAkIAGAAIAAASgACygDIgCAKIgCAHIAWAAIAAgcIgSAAgAr7AgIAAgLIgkAAIAAALIgHAAIAAgSIAFAAIACgGIACgLIAAgTIAjAAIAAAkIAHAAIAAASgAsWAHIgCAHIAVAAIAAgcIgSAAgAvcAgIAAgLIgkAAIAAALIgIAAIAAgSIAFAAQACgCABgEIACgeIAiAAIAAAkIAHAAIAAASgAv3AHIgCAHIAUAAIAAgcIgRAAgAQSAWIgDgDIgBgDIABgCIADgDIADAAIACAAIACADIABACIgBADIgCADIgCAAgAPlATQgFgDgDgGQgDgGAAgIQAAgMADgJQADgIAHgFIAFgCIAXgFIABAIIgZAFQgDACgCAEQgCAEgCAIQADgEAEgCQAEgCAFAAQAGAAAFADQAEADADAFQADAFAAAGQAAAGgDAFQgCAFgGADQgEADgHAAQgGAAgGgDgAPpgMIgEAFQgCADAAAEQAAAEACADQABADADACQADACAFAAQADAAAEgBQADgCABgEQACgCAAgFQAAgEgCgDQgCgEgCgBQgDgCgEAAQgEAAgEACgAOfATQgGgDgCgFQgDgFAAgGQAAgGADgFQABgFAHgEQAEgDAHAAQAFAAAGADQAFADACADIgFAFQgCgDgDgBQgEgCgEAAQgEAAgDACQgDACgCADIgBAIQAAAEABADQACAEADABQADACAEAAQAEAAAEgBQADgBACgEIAFAGQgCAEgFACQgEACgHAAQgGAAgFgDgANqATQgFgDgEgFQgCgFAAgGQAAgGACgFQAEgGAFgDQAFgDAGAAQAHAAAFADQAFAEADAFQADAGAAAFQAAAFgDAGQgDAFgFADQgFADgHAAQgGAAgFgDgANugNQgCABgDAFQgBADAAAEQAAAEABADIAFAFQACACAFAAQAEAAADgCQADgBACgEQACgDAAgEQAAgFgCgCQgBgEgEgCQgDgCgEAAQgFAAgCACgAJVAWIABgIIADAAIADgBQAAAAABgBQAAAAAAgBQAAAAAAgBQAAgBAAAAIABgJIABgWIAjAAIAAArIgJAAIAAgjIgSAAIAAAOIgBANQgCAEgDADQgCACgGAAgAIuATQgFgDgDgFQgCgEAAgHQAAgHACgEQAEgGAEgDQAGgDAFAAQAIAAAEADQAGAEACAFQADAGAAAFQAAAFgDAGQgCAFgGADQgEADgIAAQgFAAgGgDgAIygNQgCABgCAFQgCADAAAEQAAAEACADIAEAFQAEACADAAQAEAAAEgCIAFgFQACgDAAgEQAAgEgCgDQgCgFgDgBQgEgCgEAAQgDAAgEACgAGWATQgHgDgCgFQgCgFAAgGQAAgGACgFQACgFAHgEQAEgDAHAAQAGAAAFADQAFADADAGQAEAFAAAGQAAAGgEAFQgCAFgGADQgFADgGAAQgHAAgEgDgAGagNQgEACgBAEQgCACAAAFQAAAEACADQACAEADABQACACAFAAQAEAAADgCIAFgFQACgDAAgEQAAgEgCgDQgCgFgDgBQgDgCgEAAQgFAAgCACgADZAWIABgIIADAAIAEgBIABgEIABgJIAAgWIAjAAIAAArIgIAAIAAgjIgTAAIAAAOQAAAIgBAFQgBAEgEADQgCACgGAAgAg3ATQgFgDgDgFQgDgFAAgGQAAgGADgGQADgFAFgDQAEgDAHAAQAGAAAFADQAEACAEAGQACAFAAAGIAAADIgiAAQAAADACAEIAFAEQADACAEAAIAIgCQAFgBABgDIAEAGQgBACgGADQgFACgGAAQgGAAgGgDgAg0gMQgEADgBAFIAaAAQgCgGgCgCQgEgDgFAAQgFAAgDADgAifATQgEgDgDgFQgCgGgBgFQABgGACgGQADgFAEgDQAFgDAGAAQAFAAADACQAFADACADIAAgHIAIAAIAAArIgIAAIAAgGQgDAEgEABQgDACgFAAQgGAAgFgDgAiZgNIgGAFIgBAIQAAAEABADIAGAGQACABAEAAQAFAAACgBQAEgDABgDQACgDAAgEQAAgEgCgEQgCgDgDgCQgCgCgFAAQgEAAgCACgAkDAUQgDgBgEgEIAFgFIAFAEQAEABAEAAQAGAAACgCQADgBAAgEQAAgGgKAAIgIAAIAAgFIAHAAQAEAAADgCQADgBgBgDQABgDgDgCQgCgCgFAAQgHAAgFAGIgFgGIAHgFQAFgCAGAAQAIAAAFAEQADADAAAGIgBAGIgFAEQAEAAACACQACAEAAADQAAADgCAEQgCADgFACQgEABgGAAQgHAAgEgCgAncAWIgCgDIgBgDIABgCIACgDIADAAIADAAIACADIABACIgBADIgCADIgDAAgAp4ATQgFgDgDgFQgDgEAAgHQAAgHADgEQADgGAFgDQAFgDAHAAQAGAAAFADQAFAEADAFQADAGAAAFQAAAFgDAGQgCAFgGADQgFADgGAAQgHAAgFgDgAp0gNQgCABgDAFQgBADAAAEQAAAEABADIAFAFQAEACAEAAQAEAAADgCIAFgFQABgDAAgEQAAgEgBgDQgDgFgCgBQgDgCgEAAQgEAAgEACgArjATQgGgDgCgFQgDgEAAgHQAAgHADgEQACgFAGgEQAFgDAGAAQAHAAAFADQAFAEADAFQACAEAAAHQAAAHgCAEQgDAFgFADQgFADgHAAQgGAAgFgDgArfgNQgDABgCAFQgCADAAAEQAAAEACADIAFAFQAEACADAAQAEAAAEgCIAEgFQACgDAAgEQAAgEgCgDQgCgFgCgBQgEgCgEAAQgDAAgEACgAtLAUQgDgBgFgEIAGgFQABACAEACQADABAFAAQAFAAADgCQACgBAAgEQAAgGgJAAIgJAAIAAgFIAHAAQAFAAACgCQADgBAAgDQAAgDgCgCQgCgCgFAAQgHAAgFAGIgFgGIAHgFQAFgCAFAAQAKAAADAEQAFADgBAGQAAADgCADQgBACgDACQADAAADACQACADAAAEQAAAEgCADIgHAFIgKABQgHAAgEgCgAvOAWIABgIIADAAIADgBIABgEIACgfIAiAAIAAArIgIAAIAAgjIgSAAIgBAOQAAAIgBAFQgBAFgDACQgCACgGAAgAPGAVIAAgrIAJAAIAAArgAM5AVIgMgQIgMAQIgJAAIAQgVIgQgWIAKAAIALAQIAMgQIAKAAIgQAWIAQAVgAMGAVIAAgrIAIAAIAAArgALvAVIAAgTIgVAAIAAATIgJAAIAAgrIAJAAIAAASIAVAAIAAgSIAJAAIAAArgAKwAVIAAgjIgOAAIAAgIIAmAAIAAAIIgPAAIAAAjgAKQAVIAAgrIAIAAIAAArgAIQAVIAAgTIgWAAIAAATIgIAAIAAgrIAIAAIAAASIAWAAIAAgSIAIAAIAAArgAHCAVIAAgrIATAAQAIAAAEADQAFAEAAAFQgBAEgBACQgBACgEACQAEAAADACQABAEAAADQAAAEgBACQgCADgEACQgDABgFAAgAHLAPIALAAQAFAAACgCQACgCAAgDQAAgGgJAAIgLAAgAHLgDIAJAAQAFAAACgBQACgCAAgDQAAgGgJAAIgJAAgAF3AVIAAgjIgWAAIAAAjIgIAAIAAgrIAmAAIAAArgAEuAVIAAgRIgKAAIgKARIgJAAIALgRQgEgCgDgCQgEgDAAgFQAAgGAGgEQAFgEAHAAIAUAAIAAArgAEcgNQgCACAAADQAAAEACABQADACAEAAIALAAIAAgOIgLAAQgCAAgFACgAB5AVIAAgfIgWAfIgIAAIAAgrIAIAAIAAAfIAWgfIAIAAIAAArgABGAVIAAgfIgXAfIgIAAIAAgrIAIAAIAAAfIAXgfIAHAAIAAArgAARAVIAAgTIgVAAIAAATIgIAAIAAgrIAIAAIAAASIAVAAIAAgSIAJAAIAAArgAhVAVIAAgSQgHADgFAAQgFAAgEgCQgEgCgCgCQgCgEAAgFIAAgNIAJAAIAAAMQAAAFACACQACACAGAAQAGAAAEgCIAAgTIAIAAIAAArgAi8AVIAAgTIgWAAIAAATIgIAAIAAgrIAIAAIAAASIAWAAIAAgSIAJAAIAAArgAkcAVIAAgfIgWAfIgIAAIAAgrIAIAAIAAAfIAWgfIAIAAIAAArgAmJAVIAAg3IgfAAIAAA3IgJAAIAAg/IAxAAIAAA/gAnzAVIAAgRIgJAAIgLARIgJAAIALgRQgEgCgEgCQgCgDAAgFQAAgGAFgEQAFgEAHAAIAUAAIAAArgAoEgNQgCACgBADQABAEACABQACACAFAAIAKAAIAAgOIgKAAQgEAAgDACgApLAVIAAgrIATAAQAJAAADADQAEAEAAAFQAAAEgCACQgBACgDACQAEAAACACQADAEAAADIgDAGQgBADgDACQgEABgFAAgApDAPIAMAAQAFAAABgCQADgBAAgEQAAgGgJAAIgMAAgApDgDIAKAAQAEAAACgBQADgDAAgCQAAgGgJAAIgKAAgAt5AVIAAgRIgKAAIgKARIgJAAIALgRQgFgCgDgCQgDgDAAgFQAAgHAFgDQAFgEAIAAIATAAIAAArgAuLgNQgCACAAADQAAAEACABQACACAFAAIALAAIAAgOIgLAAQgEAAgDACgAohgTIAGgGQACgEAAgDIgEgCQAAAAgBgBQAAAAAAAAQAAgBAAgBQgBAAAAgBIADgEQAAAAAAAAQABgBAAAAQABAAAAAAQABAAAAAAIAFACQABACABAEQAAAFgEAFQgDAGgEADgABngfQgDgBgCgDQgBgCgCgGIAHAAQABAEACABQACACADAAQAEAAACgCQACgBAAgEIAIAAIgDAIQgCADgDABQgEACgEAAQgDAAgEgCgAPHggIgCgCIAAgDIAAgDIACgCIAEgBIADABIABACIABADIgBADIgBACIgDABgAMHggIgCgCIAAgDIAAgDIACgCIADgBIADABIACACIABADIgBADIgCACIgDABgAKRggIgCgCIgBgDIABgDIACgCIACgBIADABIADACIAAADIAAADIgDACIgDABgALTg7IgDgBIABgIIAGABIAEgBIADgDIAFgLIgSgsIAJAAIANAiIAOgiIAJAAIgUAxQgCAFgEAGIgFAFQgEACgEAAgANfg8IAAhCIAIAAIAAAHQADgEADgCQAEgCAFAAQAGAAAEADQAFADACAFQADAGABAGQgBAHgDAFQgCAFgFADQgEADgGAAQgDAAgGgCQgDgCgDgEIAAAdgANth1IgEAFQgCADAAAFQAAAFACADIAEAFQADACAEAAQAEAAADgCQADgBACgEQACgDAAgFQAAgFgCgDQgBgDgEgCIgHgCQgCAAgFACgAoCg8IAAhCIAIAAIAAAHQACgEAEgCQAEgCAEAAQAGAAAFADQAFAEACAEQADAGAAAGQAAAHgDAFQgDAFgEADQgFADgGAAQgDAAgFgCQgEgCgCgEIAAAdgAn0h1IgFAFQgCADAAAFQAAAFACADIAFAFQADACAEAAQAFAAACgCQACgBACgEIACgIQAAgEgCgEQgBgDgDgCQgEgCgDAAQgDAAgEACgAPNhTQgGgCgCgDIAFgFIAGAEQADABAEAAQAEAAAEgCQADgCAAgDQAAgGgJAAIgJAAIAAgGIAHAAQAEAAAEgCQABgBAAgEQAAgBAAAAQAAgBAAAAQAAgBgBAAQAAgBAAAAQgCgCgFAAQgIAAgEAFIgGgFQADgDAFgCQAEgCAGAAQAJAAAEADQAEAEAAAFQAAAEgBACQgDAEgDAAQAFACABACQACACAAAFQAAAEgCADQgCACgEACQgEACgHAAQgEAAgGgCgAMMhUQgFgCgDgGQgDgFAAgHQAAgGADgGQACgEAFgEQAGgDAHAAQAGAAAFACQAEADADAEIgGAFQgCgDgDgBIgHgCQgFAAgDACQgDACgCADIgCAIQAAAEACAEQACADADACQADACAFAAQAEAAADgBQADgCACgDIAGAGQgDAEgEACQgGACgFAAQgHAAgFgDgAKahUQgGgDgDgFQgCgGAAgGQAAgGACgGQAEgFAEgDQAGgDAGAAQAHAAAEACQAEACADAEIgEAFQgDgDgDgBIgIgCQgDAAgEACIgEAEIgDAHIAWAAIAAAGIgWAAQABAGAEADQAEAEAFAAIAIgCIAGgEIAEAFQgDAEgEACQgGACgFAAQgGAAgFgDgAJihUQgEgDgDgFQgDgGAAgGQAAgGADgGQADgFAEgDQAGgDAFAAQAEAAAEACQADACADAEIAAgHIAIAAIAAAsIgIAAIAAgHQgCAEgEACQgFACgDAAQgFAAgGgDgAJnh1QgEACAAADQgCADgBAFQABAFACADQABAEADABQADACAEAAQAFAAACgCIAFgFQABgDAAgFQAAgFgBgDIgFgFQgEgCgDAAQgDAAgEACgAGrhRIACgIIACAAQABAAAAAAQABAAAAAAQABAAAAgBQAAAAAAAAIACgEIABggIAjAAIAAAsIgIAAIAAgkIgSAAIgBAPQAAAIgBAFQgCAFgCACQgDACgFAAgADbhUQgFgCgDgGQgDgFAAgHQAAgGADgGQADgGAFgCQAFgDAGAAQAGAAAFADQAEADADAFQAEAEAAAHIgBADIgiAAQAAADACAEQADAEADABQACABAFAAIAHgBIAGgEIAFAGQgCACgGADIgLACQgGAAgGgDgADdh0QgDADgBAFIAaAAQgCgGgDgCQgDgEgFAAQgGAAgDAEgABbhTQgGgCgDgEIAEgHQADADAFACQAEACAGAAQAEAAADgBQADgBACgDQACgCAAgEQAAgCgCgDIgGgEIgIgDIgKgEIgHgFQgDgEABgFQgBgGADgEQAEgEAEgBQAFgCAGAAQAIAAAFACQAFABAEAEIgFAHQgDgDgEgCQgEgBgFAAQgGAAgEACQgDACAAAFQAAABAAAAQAAABAAAAQAAABABAAQAAABAAAAIAFAEIATAGQADACAEAEQADAEAAAGQgBAGgCAFQgDAEgFACQgGACgGAAQgHAAgGgCgAAZhVQgHgEgFgIQgFgIABgJQgBgKAFgHQAFgIAHgEQAHgEAJAAQAJAAAHAEQAHAEAFAIQAEAHAAAKQAAAJgEAIQgFAIgHAEQgHAEgJAAQgJAAgHgEgAAdiIQgGADgDAGQgCAGAAAHQAAAIACAFQADAGAGADQAFADAHAAQAHAAAFgDQAFgDAEgGQADgFgBgIQABgHgDgGQgEgGgFgDQgFgDgHAAQgHAAgFADgAgxhVQgHgEgFgIQgEgIAAgJQAAgKAEgHQAFgIAHgEQAIgEAIAAQAJAAAIAEQAIAEADAIQAFAHAAAKIgCAMQgCAGgEAEIAIAKIgJAAIgFgFQgDADgFACIgLABQgJAAgHgEgAgsiIQgGADgDAGQgDAGAAAHQAAAIADAFQADAGAGADQAFADAGAAQAJAAAFgEIgNgPIAGgFIAMAOIAEgHIABgIQAAgHgDgGQgDgGgGgDQgEgDgIAAQgGAAgFADgAk2hUQgEgDgDgFQgCgGgBgGQABgGACgGQADgFAEgDQAGgDAFAAQAFAAADACQAEACACAEIAAgHIAJAAIAAAsIgJAAIAAgHQgBAEgFACQgFACgDAAQgFAAgGgDgAkwh1QgEACgBADQgCADAAAFQAAAFACADQACAEADABQACACAFAAQAEAAACgCIAFgFQACgDAAgFQAAgFgCgDIgFgFQgEgCgCAAQgEAAgDACgAmQhUQgGgDgCgFQgDgFAAgHQAAgGADgGQADgFAEgDQAGgDAHAAQAGAAAFACQAEADADAEIgGAFQgCgDgDgBIgHgCQgFAAgCACQgEACgCADQgCAEAAAEQAAAFACADQACADAEACQACACAFAAIAHgBQADgCACgDIAGAGQgDAEgEACQgHACgEAAQgIAAgEgDgAovhUQgFgCgDgGQgEgFAAgHQAAgGAEgGQACgFAGgDQAFgDAGAAQAHAAAEADQAHAEABAEQADAGAAAGQAAAHgDAFQgBAFgHADQgEADgHAAQgGAAgFgDgAorh1IgFAFIgCAIQAAAFACADIAFAFQAEACADAAQADAAAEgCQADgCACgDQACgDAAgFQAAgEgCgEQgCgDgDgCQgCgCgFAAQgEAAgDACgAr+hSIgCgCIgBgDIABgDIACgCIADgBIADABIACACIABADIgBADIgCACIgDABgAsrhUQgFgCgDgGQgEgFAAgHQAAgGAEgGQACgFAGgDQAFgDAGAAQAHAAAFADQAFAEADAEQACAGAAAGQAAAGgCAGQgDAFgFADQgFADgHAAQgGAAgFgDgAsnh1IgFAFIgCAIQAAAFACADIAFAFQAEACADAAIAIgCQADgCABgDQACgDAAgFQAAgEgCgEQgCgDgCgCQgEgCgEAAQgEAAgDACgAvRhRIABgIIADAAQAAAAAAAAQABAAAAAAQABAAAAgBQABAAAAAAIABgEIABggIAjAAIAAAsIgIAAIAAgkIgSAAIgBAPQABAIgCAFQgCAFgCACQgEACgEAAgAw/hUQgEgDgDgFQgDgGABgGQgBgGADgGQADgFAEgDQAGgDAFAAQAFAAADACQAEACADAEIAAgHIAIAAIAAAsIgIAAIAAgHQgDAEgEACQgEACgEAAQgFAAgGgDgAw5h1QgEACgBADQgCADAAAFQAAAFACADQACAEADABQACACAEAAQAFAAACgCIAGgFQABgDAAgFQAAgFgBgDIgGgFQgDgCgEAAQgDAAgDACgAIBhUQgFgCgDgFQgCgEgBgGIgHAAIAAATIgJAAIAAgsIAJAAIAAASIAHAAQABgHADgDQADgFAEgCQAEgCAGAAQAHAAAEADQAFADADAFQACAGAAAGQAAAGgCAGQgDAGgFACQgEADgHAAQgGAAgEgDgAIEh1QgDACgBADQgCADAAAFQAAAFACADQAAADAEACQADACAEAAQAEAAADgCIAEgFQACgDAAgFQAAgFgCgDQgCgDgCgCQgCgCgFAAQgEAAgDACgAR4hSIAAggIgWAgIgIAAIAAgsIAIAAIAAAgIAXggIAIAAIAAAsgARHhSIgNgTIgBAAIgHAAIAAATIgJAAIAAgsIAJAAIAAARIAIAAIANgRIAKAAIgPAVIAPAXgAQUhSIAAggIgXAgIgIAAIAAgsIAIAAIAAAgIAXggIAIAAIAAAsgAOzhSIAAggIgWAgIgHAAIAAgsIAIAAIAAAgIAWggIAIAAIAAAsgAM0hSIAAgsIAJAAIAAAsgAJEhSIAAgSQgFADgGAAQgGAAgDgCQgEgCgCgEQgCgDAAgFIAAgNIAJAAIAAAMQAAAFACACQADACAEAAQAHAAADgCIAAgTIAJAAIAAAsgAGdhSIgNgTIgCAAIgHAAIAAATIgIAAIAAgsIAIAAIAAARIAJAAIANgRIAKAAIgQAVIAQAXgAFphSIAAggIgWAgIgHAAIAAgsIAIAAIAAAgIAWggIAIAAIAAAsgAEbhSIAAgsIATAAQAJAAAEADQADADAAAGIgBAGQgCADgCAAQAEACABACQACADAAAEQAAADgBADIgFAEQgEACgFAAgAEjhYIAMAAQAFAAACgCQABgBAAAAQAAgBABAAQAAgBAAAAQAAgBAAgBQAAgGgJAAIgMAAgAEjhrIAKAAQAFAAACgCQACgBAAgDQAAgGgJAAIgKAAgAC9hSIAAgTIgWAAIAAATIgIAAIAAgsIAIAAIAAASIAWAAIAAgSIAJAAIAAAsgAhXhSIAAhAIAIAAIAABAgAiEhSIAAgRIgKAAIgKARIgJAAIALgSQgFAAgDgEQgDgDABgFQAAgGAEgEQAEgEAJAAIATAAIAAAsgAiWh1QgCABAAAEQAAADACACQADACAEAAIALAAIAAgOIgLAAQgFAAgCACgAi0hSIAAgTIgWAAIAAATIgJAAIAAgsIAJAAIAAASIAWAAIAAgSIAIAAIAAAsgAjohSIAAgTIgWAAIAAATIgIAAIAAgsIAIAAIAAASIAWAAIAAgSIAIAAIAAAsgAldhSIAAgkIgPAAIAAgIIAnAAIAAAIIgPAAIAAAkgAmuhSIAAggIgXAgIgHAAIAAgsIAIAAIAAAgIAWggIAJAAIAAAsgApIhSIgNgTIgCAAIgGAAIAAATIgIAAIAAgsIAIAAIAAARIAIAAIANgRIAKAAIgQAVIAQAXgAp7hSIAAggIgXAgIgHAAIAAgsIAIAAIAAAgIAWggIAIAAIAAAsgArThSIAAhAIAYAAQAFAAAFACQAEACADAEQABADAAAFQAAAFgBAEQgCAEgEABQAFADACADQADAFAAAGQAAAFgCAEQgCADgEADQgEACgGAAgArLhaIARAAQAFAAADgCQADgDAAgFQAAgFgDgDQgDgDgFAAIgRAAgArLh2IAPAAQAFAAADgDQADgCAAgGQAAgEgDgDQgDgCgFAAIgPAAgAtjhSIAAgsIATAAQAJAAADADQAEADAAAGIgCAGQgCADgCAAQAFACABACQADAEAAADIgDAGQgBADgEABQgDACgFAAgAtbhYIAMAAQAEAAACgCQADgCAAgDQAAgGgJAAIgMAAgAtbhrIAKAAQAEAAACgCQADgBAAgDQAAgGgJAAIgKAAgAt5hSIAAggIgWAgIgIAAIAAgsIAIAAIAAAgIAWggIAJAAIAAAsgAvghSIgMgTIgCAAIgCAAIAAATIgJAAIAAgTIgDAAIgCAAIgBACIgLARIgJAAIAOgXIgOgVIAJAAIAMARIAFAAIAAgRIAJAAIAAARIAEAAIAMgRIAKAAIgPAVIAPAXgAx/hSIAAhAIAXAAQAFAAAGACQAEACACAEQACADAAAFQAAAFgCAEQgBAEgEABQAEACAEAEQACAFAAAGQAAAFgCAEQgCADgEADQgEACgGAAgAx3haIARAAQAFAAADgCQADgDAAgFQAAgFgDgDQgDgDgFAAIgRAAgAx3h2IAOAAQAFAAADgDQADgCABgGQgBgEgDgDQgCgCgGAAIgOAAgAr+hxIgCgCIgBgDIABgDIACgCIADgBIADABIACACIABADIgBADIgCACIgDABgAM1iIIgCgCIAAgDIAAgDIACgCIADgBIADABIACACIAAADIAAADIgCACIgDAAg");
	this.shape_1.setTransform(-0.6,-0.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.urText, new cjs.Rectangle(-127,-20.9,254,42), null);


(lib.t1_2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AtuCPIAAjZIAdAAIAAAVQAJgMAMgHQAMgGAQAAQATAAAQAKQAQAKAJARQAJASAAAWQAAAVgJARQgJARgQAKQgPAKgUAAQgQAAgMgGQgNgHgIgMIAABegAs8guQgKAHgGALQgGAMAAAPQAAANAGAMQAGAMAKAGQAJAGAOAAQAOAAAJgGQALgGAGgMQAFgMAAgNQAAgPgFgMQgGgLgLgHQgJgGgOAAQgNAAgKAGgAQoBIQgFgDgCgFQgCgFAAgEQAAgFACgFQACgEAFgDQAEgDAGAAQAHAAADADIAHAHQADAEAAAGQAAAIgGAGQgGAFgIAAQgFAAgFgCgAOeBAQgRgJgKgSQgKgTAAgTQAAgWAKgRQAJgSARgKQASgKAXAAQATAAARAHQAQAIAKANIgTASQgHgKgMgEQgKgFgOAAQgOAAgLAGQgLAGgGALQgGAMAAAPQAAAOAGALQAGALALAGQALAHAOAAQAMAAAMgFQAMgGAHgJIASASQgJANgQAIQgQAHgUAAQgXAAgRgKgALuBAQgRgJgKgSQgJgRAAgVQAAgWAJgSQAKgSARgJQATgKAUAAQAWAAASAKQARAJAKATQAJARAAAWQAAAVgJARQgKASgRAJQgSAKgWAAQgUAAgTgKgAL+gtQgLAHgGALQgGALAAAPQAAAOAGALQAGALALAGQAKAGANAAQAOAAAKgGQALgGAGgLQAGgLAAgOQAAgPgGgLQgGgLgLgHQgKgGgOAAQgNAAgKAGgAF8BAQgRgJgKgSQgJgSAAgUQAAgWAJgRQAKgSARgKQARgKAXAAQAUAAAQAHQARAIAJANIgSASQgJgKgLgEQgKgFgOAAQgOAAgKAGQgLAFgGAMQgGAMAAAPQAAAOAGALQAGALAKAGQAKAHAPAAQAMAAANgFQAKgFAJgKIASASQgJANgRAIQgQAHgUAAQgWAAgSgKgADNBAQgRgJgKgSQgKgSAAgUQAAgVAKgTQAKgSARgJQARgKAWAAQAVAAASAKQARAJAKATQAKARAAAWQAAAUgKASQgKASgRAJQgSAKgVAAQgWAAgRgKgADcgtQgLAGgGAMQgGAMAAAOQAAANAGAMQAGALALAGQALAGANAAQANAAALgGQAKgGAGgLQAHgLAAgOQAAgPgHgLQgGgMgKgGQgKgGgOAAQgNAAgLAGgAi/BAQgRgJgKgSQgJgRAAgVQAAgWAJgSQAKgSARgJQATgKAUAAQAWAAASAKQARAJAKATQAJARAAAWQAAAVgJARQgKASgRAJQgSAKgWAAQgUAAgTgKgAivgtQgLAHgGALQgGALAAAPQAAAOAGALQAGALALAGQAKAGANAAQAOAAAKgGQALgGAGgLQAGgLAAgOQAAgPgGgLQgGgLgLgHQgKgGgOAAQgNAAgKAGgAnuBAQgRgJgJgSQgKgSAAgUQAAgWAJgRQAKgSARgKQASgKAWAAQAUAAARAHQAQAIAJANIgSASQgJgKgKgEQgLgFgNAAQgOAAgLAGQgKAFgHAMQgGAMAAAPQAAAOAGALQAGALALAGQAKAHAPAAQAMAAAMgFQALgFAIgKIASASQgJANgQAIQgRAHgTAAQgWAAgTgKgAqdBAQgRgJgKgSQgKgSAAgUQAAgVAKgTQAKgSARgJQASgKAVAAQAWAAARAKQARAJAKATQAKARAAAWQAAAUgKASQgKASgRAJQgRAKgWAAQgVAAgSgKgAqOgtQgKAGgGAMQgHAMAAAOQAAANAHAMQAGALAKAGQAMAGAMAAQAOAAAKgGQALgGAGgLQAGgLAAgOQAAgPgGgLQgGgMgLgGQgKgGgOAAQgNAAgLAGgAKNBGIAAhnIgwBAIgTAAIgvhAIAABnIgcAAIAAiQIAcAAIA5BKIA5hKIAcAAIAACQgAB9BGIgng5QgCgEgCgBIgGgBIgXAAIAAA/IgdAAIAAiQIAdAAIAAA5IAZAAIAFgBQAAAAABgBQAAAAAAgBQABAAAAgBQAAAAABgBIAng0IAhAAIg0BEIA1BMgAlCBGIAAh4IgyAAIAAgYICCAAIAAAYIgzAAIAAB4gAu7BGIAAi5IhsAAIAAC5IgeAAIAAjUICnAAIAADUgAQlAIIgBiWIAdAAIgCCWg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1_2, new cjs.Rectangle(-109.4,-14.3,218.8,28.7), null);


(lib.t1_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AMFCSIgMgDIAFgYIASACQAJAAAFgDQAFgCAFgHQAGgJAEgMIAHgRIg9iRIAfAAIAtBxIAthxIAeAAIhDChQgJAWgIANQgJAMgKAHQgLAGgPAAgACIBBQgQgLgJgQQgJgSAAgVQAAgWAJgSQAJgRAQgKQAQgKATAAQAQAAANAGQAMAHAIANIAAgWIAdAAIAACQIgdAAIAAgVQgHAMgNAHQgNAGgQABQgUgBgPgJgACZguQgLAIgFAKQgGAMAAAPQAAANAGAMQAGAMAKAGQAKAGANABQAOgBAKgGQAKgGAGgMQAGgMAAgNQAAgPgGgMQgGgKgKgIQgLgFgNAAQgNAAgKAFgAhTBKIAFgaIAIAAQAIAAAEgEQADgFACgJQACgOAAgQIAChKIB1AAIAACQIgcAAIAAh3Ig9AAIgBAyQgBAbgFAPQgDAPgKAJQgJAIgSAAgAoABDQgUgHgNgOIAQgVQAKALARAFQAQAHASAAQANAAALgEQALgEAGgJQAFgHABgMQgBgMgGgGQgHgHgKgGIgdgKQgTgGgPgGQgOgHgJgLQgJgMAAgSQAAgSAJgNQAKgNAQgGQASgHAVAAQATAAAVAHQATAFANANIgPAVQgKgIgPgGQgPgFgQgBQgWABgMAHQgLAIAAAOQAAALAFAFQAIAIAIADIAaAJQAZAIAMAGQAPAGAJANQAKANAAAUQAAAUgJAOQgKAPgRAGQgRAIgXAAQgXAAgVgIgArdA8QgagOgOgZQgOgZAAgfQAAggAOgZQAOgYAagPQAYgPAfAAQAeAAAZAPQAaAOAOAZQAOAYAAAhQAAAhgOAXQgPAZgZAOQgYAOgfABQgfgBgYgOgArOhsQgTALgKATQgLATAAAYQAAAYALASQAKATATALQASAJAWABQAWgBATgJQARgLALgTQAKgSAAgYQAAgYgKgTQgLgTgRgLQgTgKgWAAQgXAAgRAKgAvWA8QgYgNgPgaQgPgYAAggQAAghAPgYQAOgZAZgOQAZgPAeAAQAfAAAZAPQAZAOAOAZQAPAYAAAhQAAAXgHAQQgHATgMAPIAcAgIghAAIgNgPQgOAJgRAFQgPAGgUAAQgegBgZgOgAvHhsQgSALgKATQgKATAAAYQAAAYAKASQAKATASALQATAJAVABQAcAAASgOIgsgxIATgQIArAwQAIgLAEgLQADgNAAgQQABgZgLgSQgKgTgSgLQgSgKgXAAQgWAAgSAKgAQ5BGIAAhnIgwBAIgTAAIgvg/IAABmIgcAAIAAiQIAcAAIA4BLIA6hLIAcAAIAACQgALIBGIAAg/IhJAAIAAA/IgdAAIAAiQIAdAAIAAA6IBJAAIAAg6IAcAAIAACQgAIdBGIAAhoIhNBoIgaAAIAAiQIAbAAIAABpIBNhpIAaAAIAACQgAFJBGIAAh3IgzAAIAAgZICDAAIAAAZIgzAAIAAB3gAiSBGIAAi4IhsAAIAAC4IgdAAIAAjUICnAAIAADUgAxUBGIAAjUIAeAAIAADUg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1_1, new cjs.Rectangle(-110.8,-14.7,221.7,29.4), null);


(lib.t1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AjLBnQgVgIgLgMIAPgUQAMALAOAFQAPAFAOAAQANAAALgFQAKgEAGgKQAGgKAAgMQAAgTgNgKQgMgLgZAAIg2AAIAAhsIB6AAIAAAaIhfAAIAAA7IAbAAQAnAAAUARQAUAPAAAfQAAAUgJAQQgJAPgRAIQgQAIgWAAQgVAAgTgHgACdBqIAxhKQgKADgMAAQgUAAgQgJQgRgJgJgQQgKgPAAgVQAAgWAKgQQAKgRARgJQASgKAVAAQAUAAATAJQARAJAKARQAKARAAAVQAAAPgFAOQgEAMgNAUIg2BRgACkhNQgKAGgHALQgGALAAAOQAAAOAGALQAHAKAKAFQALAGANAAQANAAALgGQALgFAGgLQAGgKAAgPQAAgOgGgKQgGgKgLgHQgLgGgNAAQgNAAgLAGgAgUBqIAxhKQgKADgNAAQgTAAgQgJQgQgJgKgQQgKgPAAgVQAAgVAKgRQAKgRARgJQASgKAUAAQAVAAASAJQARAJAKARQAKAQAAAWQAAAPgFAOQgFANgMATIg2BRgAgNhNQgLAGgGALQgGALAAAOQAAAOAGALQAGAKALAFQALAGAMAAQANAAALgGQALgFAGgLQAGgKAAgPQAAgOgGgKQgGgLgLgGQgLgGgNAAQgMAAgLAGgAkpBqIAAi2Ig5AbIAAgbIA/gdIAXAAIAADTgAE3gDQgFgBgEgEQgDgCgDgGQgCgEAAgHQAAgGACgEIgGAAIAAgLIAPAAIAKgIIgZAAIAAgLIApAAIAEgFQACgCAAgEQAAgGgEgDQgFgDgHAAIgFABIgGABIgGADIgGAFIAAgQQALgHALAAQAHAAAFACQAGACADADQAEACADAGQACAGAAAEIgBAGIgCAFIAIAAIAAALIgUAAIgMAIIAgAAIAAALIgsAAIgDAFIgBAFIABAFIADAEIAFADIAHABIAHgBIAGgDIAHgEIAGgFIAAAQQgGAFgHACQgHADgHAAQgHAAgEgCg");
	this.shape.setTransform(-0.5,-39);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#041A2C").s().p("AgRFOIhjhjIjMAAQhOAAg4g4Qg4g3AAhQIAAjAQAAhPA4g4QA4g4BOAAIKAAAQBQAAA3A4QA4A4AABPIAADAQAABQg4A3Qg4A4hPAAIjRAAIhjBjQgGAGgIAAQgJAAgGgGg");
	this.shape_1.setTransform(0,-34);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1, new cjs.Rectangle(-51.1,-68,102.3,68.1), null);


(lib.iqos_logo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AiBCBIgpgpIiGAAQggAAgVgEQgbgGgQgQQgWgUAAgpIAAhzQAAgIAFgFQAFgEAJAAICVAAQAgAAAVAEQAcAHAPAPQAXAVAAApIAABxIAhAiQAEAFAAAGQAAAHgGAGQgGAGgHAAQgGABgGgGgAl/ACQAAAbAOANIACADQAOALAeABICVAAIAAhlQAAgbgOgOIgCgDQgOgLgfgBIiUAAgAoCBSQgFgFAAgJIAAi2QAAgKAFgEQAFgGAJABQAIgBAFAGQAFAEAAAKIAAC2QAAAIgFAGQgFAEgIAAQgJAAgFgEgAFQBWQgqgCgTgLQgPgKgDgSIAAgDQABgHAFgEQAEgDAIAAQAGAAAGADQAEADACAFIABACQAFAIAJADQAJADAQAAIBRAAQAtgBAMgFQAMgHAAgTIAAgCQAAgRgHgEQgKgJgeAAIhsAAQglAAgQgNQgQgNAAgeIAAgMQAAgcAUgMQAYgPA+ABIA2AAQAxAAAWAMQARAJACATIAAADQAAAHgEAEQgGAEgHAAQgHAAgFgDQgFgDgCgFIgBgCQgFgKgOgDQgKgCgaAAIg8AAQgmAAgMAGQgLAEAAASIAAAIQAAAOAHAFQAKAHAYAAIBdAAQAuAAASAJQAaAOAAAnIAAABQAAApgiANQgUAHgsABgAAjBWQg0AAgbgPQglgUAAgzIAAguQAAg0AlgVQAbgOA0AAIAzAAQA2AAAbAOQAlAVAAA0IAAAuQAAAzgmAUQgaAPg2AAgAgYhcQgUANAAAjIAAAqQAAAhAUANQAPALAiAAIBIAAQAiAAAQgLQATgNAAghIAAgqQAAgjgTgNQgQgLgiAAIhIAAQgiAAgPALg");
	this.shape.setTransform(-0.4,0);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.iqos_logo, new cjs.Rectangle(-52.4,-13.4,104,42.5), null);


(lib.dev2_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.dev2();
	this.instance.parent = this;
	this.instance.setTransform(-102,-118);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.dev2_1, new cjs.Rectangle(-102,-118,204,236), null);


(lib.dev1_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(153,152,145,0.6)").s().p("AAxA/IgYgOQgEgDgEgIQgIgNACgIQACgLALgCQAJgDAKACQAJACAHAEQAKAHAIAOQAFAIAAAHQABAMgMAFQgFADgGAAQgFAAgGgCgAhDgQIgFgLIgGgIQgHgKAHgKQAGgKAMABQAHAAANAHQATAMAFAIQAEAHABAIQAAAIgGAGQgGAGgMAAIgDABQgUAAgJgPg");
	this.shape.setTransform(121.6,-66.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(153,152,145,0.6)").s().p("AgTARIgFgLIgHgHQgGgKAHgKQAGgKAMABQAGAAAMAHQATAMAFAIQAFAGAAAIQAAAIgFAGQgHAGgLAAIgDAAQgUAAgIgOg");
	this.shape_1.setTransform(116.9,-69.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},1).to({state:[]},9).wait(1));

	// Слой_1
	this.instance = new lib.dev1();
	this.instance.parent = this;
	this.instance.setTransform(-138,-109);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(11));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-138,-109,276,218);


(lib.bgImg_mc = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.bgImg();
	this.instance.parent = this;
	this.instance.setTransform(-165,-330);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bgImg_mc, new cjs.Rectangle(-165,-330,330,660), null);


(lib.bg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0E1114").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.bg, new cjs.Rectangle(-150,-300,300,600), null);


(lib.bgImg_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_8
	this.instance = new lib.bgImg_mc();
	this.instance.parent = this;
	this.instance.setTransform(0,0,0.909,0.909,0,0,180);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:0.96,scaleY:0.96,alpha:1},60).to({scaleX:1,scaleY:1,alpha:0.016},59).wait(1));

	// Слой_7
	this.instance_1 = new lib.bgImg_mc();
	this.instance_1.parent = this;
	this.instance_1.setTransform(0,0,0.955,0.955);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({scaleX:1,scaleY:1},60).wait(1).to({scaleX:0.91,scaleY:0.91},0).to({scaleX:0.95,scaleY:0.95},58).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-157.5,-315,315,630);


(lib.banner = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{loop:35});

	// timeline functions:
	this.frame_144 = function() {
		this.gotoAndPlay('loop');
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(144).call(this.frame_144).wait(1));

	// bg
	this.instance = new lib.bg();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:0},10).to({_off:true},1).wait(134));

	// urText
	this.instance_1 = new lib.urText();
	this.instance_1.parent = this;
	this.instance_1.setTransform(0,262.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(145));

	// t1_2
	this.instance_2 = new lib.t1_2();
	this.instance_2.parent = this;
	this.instance_2.setTransform(-1.4,-202.5);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(25).to({_off:false},0).to({alpha:1},10).wait(110));

	// t1_1
	this.instance_3 = new lib.t1_1();
	this.instance_3.parent = this;
	this.instance_3.setTransform(0.2,-242.6);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(15).to({_off:false},0).to({alpha:1},10).wait(120));

	// t2
	this.instance_4 = new lib.t1();
	this.instance_4.parent = this;
	this.instance_4.setTransform(-17.1,-12.6,0.02,0.02,0,0,0,0,2.5);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(15).to({_off:false},0).to({regY:0,scaleX:1.2,scaleY:1.2,y:-12.7},10,cjs.Ease.quadInOut).to({scaleX:1,scaleY:1},5).wait(115));

	// logo
	this.instance_5 = new lib.iqos_logo();
	this.instance_5.parent = this;
	this.instance_5.setTransform(66.3,212,1,1,0,0,0,-0.9,8.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(145));

	// dev2
	this.instance_6 = new lib.dev2_1();
	this.instance_6.parent = this;
	this.instance_6.setTransform(-253.9,97);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(10).to({_off:false},0).to({x:-48,y:-16},15,cjs.Ease.quartOut).wait(120));

	// dev1
	this.instance_7 = new lib.dev1_1("single",0);
	this.instance_7.parent = this;
	this.instance_7.setTransform(289,-59);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(10).to({_off:false},0).to({x:12,y:93},15,cjs.Ease.quartOut).wait(25).to({mode:"synched",loop:false},0).wait(95));

	// bgImg1
	this.instance_8 = new lib.bgImg_1();
	this.instance_8.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(145));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-157.5,-315,315,630);


// stage content:
(lib._300x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// cover
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#666666").ss(2,2,0,3).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// banner
	this.instance = new lib.banner();
	this.instance.parent = this;
	this.instance.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(142.5,285,315,630);
// library properties:
lib.properties = {
	id: '0A6E3F5DF6B342F4AF907DBE848CDF8D',
	width: 300,
	height: 600,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/bgImg.jpg", id:"bgImg"},
		{src:"images/dev1.png", id:"dev1"},
		{src:"images/dev2.png", id:"dev2"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['0A6E3F5DF6B342F4AF907DBE848CDF8D'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;