(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.dev1 = function() {
	this.initialize(img.dev1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,570,390);


(lib.dev2 = function() {
	this.initialize(img.dev2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,700,790);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.urText_w = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1,2,0,3).p("A2JjNMAsTAAAIAAGbMgsTAAAg");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("ArnBuIAAhHIAFAAIAAAMQAJgOANAAQALABAHAHQAJAIAAANQAAAMgJAJQgHAIgLgBQgNAAgJgMIAAAcgArbAxQgHAHAAAKQAAAKAHAHQAGAGAJABQAJAAAGgHQAGgGAAgLQAAgKgGgHQgGgHgJABQgJgBgGAHgAyQBuIAAhHIAFAAIAAAMQAJgOANAAQALABAHAHQAJAIAAANQAAAMgJAJQgHAIgLgBQgNAAgJgMIAAAcgAyEAxQgHAHAAAKQAAAKAHAHQAGAGAJABQAJAAAGgHQAGgGAAgLQAAgKgGgHQgGgHgJABQgJgBgGAHgAFCBtIAAgQIgxAAIgBAQIgFAAIAAgUIAIAAQAIgOAAgZIAAgLIAkAAIAAAyIAJAAIgBAUgAEgA2QAAAWgIANIAiAAIAAgtIgaAAgAzhBtIAAgQIgyAAIgBAQIgEAAIAAgUIAHAAQAIgOAAgZIAAgLIAkAAIAAAyIAJAAIgBAUgA0EA2QAAAWgHANIAhAAIAAgtIgaAAgAUKBWQgHgIAAgOQAAgRADgHQAEgMAMgDIAfgHIABAEIgdAIQgQAEgBASQAIgNAPgBQALAAAIAJQAHAIAAALQAAAMgHAIQgIAJgMgBQgMAAgIgIgAUOAyQgGAHAAAJQAAAKAHAHQAGAGAJABQAKAAAGgHQAGgHAAgKQAAgJgHgHQgGgGgJAAQgJAAgHAGgAS1BWQgIgIAAgMQAAgLAIgJQAIgIALgBQAMAAAKALIgEAEQgJgJgJAAQgJAAgGAGQgHAIAAAJQAAAJAHAIQAGAHAJAAQAKAAAIgKIAEADQgJALgNAAQgMABgHgJgAR1BWQgIgIAAgMQAAgLAIgJQAIgIAMgBQAMABAIAIQAHAIAAAMQAAAMgIAIQgIAJgMgBQgMABgHgJgAR5AxQgHAIAAAJQAAAKAHAHQAGAHAKAAQAJAAAGgHQAHgIAAgJQAAgJgHgIQgGgGgKAAQgJAAgGAGgAL2BWQgIgIAAgMQAAgLAIgJQAIgIAMgBQAMABAIAIQAIAIAAAMQAAAMgIAIQgIAJgMgBQgMABgIgJgAL6AxQgGAIAAAJQAAAKAGAHQAHAHAJAAQAJAAAHgHQAGgIAAgJQAAgJgGgIQgHgGgJAAQgJAAgHAGgAI3BWQgIgIAAgMQAAgLAIgJQAIgIAMgBQAMABAIAIQAIAJAAALQAAAMgIAIQgIAJgMgBQgMABgIgJgAI7AxQgGAIAAAJQAAAKAGAHQAGAHAKAAQAJAAAHgHQAGgIAAgJQAAgJgGgIQgHgGgJAAQgJAAgHAGgAlkBWQgIgHAAgNQAAgMAHgIQAHgIALgBQAMABAHAIQAGAIAAAMIAAACIgtAAQABAKAGAGQAGAFAIABQAMAAAHgJIAEADQgKAKgNAAQgLAAgHgIgAlgAwQgGAHgBAJIAoAAQgCgWgSABQgIAAgFAFgAnmBaQgHgFAAgIQAAgIAHgFQAHgFAKAAQAJAAAJADIAAgDQAAgQgSAAQgIAAgJAEIgCgEQAKgFAKAAQALAAAGAGQAFAGAAAJIAAAiIgFAAIAAgJQgHAKgOAAQgJABgFgFgAnnBNQAAANAQAAQAIgBAGgEQAGgFAAgHIAAgHQgLgCgHAAQgSAAAAANgAxBBWQgIgIAAgMQAAgLAIgJQAIgIALgBQAMABAIAIQAIAIAAAMQAAAMgIAIQgIAJgMgBQgMABgHgJgAw9AxQgHAIAAAJQAAAKAHAHQAGAHAJAAQAJAAAHgHQAHgIAAgJQAAgJgHgIQgHgGgJAAQgJAAgGAGgAzMBWQgIgIAAgMQAAgLAIgJQAIgIAMgBQAMABAIAIQAIAJAAALQAAAMgIAIQgIAJgMgBQgMABgIgJgAzHAxQgHAHAAAKQAAAKAHAHQAGAHAJAAQAJAAAHgHQAGgIAAgJQAAgJgGgIQgHgGgJAAQgJAAgGAGgAMoBdIABgEIAEAAQAHAAACgHQAEgKAAgeIAAgDIAlAAIAAA2IgFAAIAAgxIgbAAIAAABQAAAfgFAKQgDAIgJAAgAFKBdIABgEIAEAAQAHAAACgHQAEgKAAgeIAAgDIAlAAIAAA2IgGAAIAAgxIgaAAIAAABQAAAfgFAKQgDAIgJAAgAgJBdIABgEIAEAAQAGAAACgHQAEgKAAgeIAAgDIAlAAIAAA2IgGAAIAAgxIgaAAIAAABQAAAfgFAKQgDAIgIAAgApiBWIADgEQAJAIAKAAQAGgBAEgDQAFgDAAgFQAAgEgEgDQgFgEgHAAIgHAAIAAgEIAIAAQANAAAAgKQAAgKgNAAQgKAAgHAFIgDgDQAIgHAMAAQAIAAAGAEQAFAEAAAHQAAAIgJAEQAKADAAAKQAAAGgFAFQgGAFgJAAQgNAAgJgIgA1KBWIADgEQAKAIAJAAQAGgBAEgDQAFgEAAgEQAAgLgPAAIgIAAIAAgEIAIAAQANAAAAgKQAAgKgNAAQgKAAgHAFIgDgDQAIgHAMAAQAJAAAFAEQAFAEAAAHQAAAIgJAEQAKADAAAKQAAAGgFAFQgGAFgJAAQgMAAgKgIgAVEBdIAAgJIAHAAIAAAJgATxBdIAAg2IAFAAIAAA2gAQ4BdIgTgYIgTAYIgGAAIAWgcIgVgaIAGAAIASAXIATgXIAGAAIgVAaIAWAcgAP8BdIAAg2IAGAAIAAA2gAPlBdIAAgaIgkAAIAAAaIgFAAIAAg2IAFAAIAAAYIAkAAIAAgYIAFAAIAAA2gAOUBdIAAgxIgUAAIAAgFIAuAAIAAAFIgUAAIAAAxgANyBdIAAg2IAFAAIAAA2gALbBdIAAgaIgkAAIAAAaIgFAAIAAg2IAFAAIAAAYIAkAAIAAgYIAGAAIAAA2gAJyBdIAAg2IAZAAQASAAAAAOQAAAHgJAFQAMADAAALQAAAOgUAAgAJ4BZIAUAAQAOAAAAgMQAAgJgQgBIgSAAgAJ4A/IASAAQANAAAAgKQAAgJgMAAIgTAAgAIbBdIAAgxIgjAAIAAAxIgFAAIAAg2IAtAAIAAA2gAG3BdIAAgUIgRAAIgRAUIgGAAIARgVQgQgDAAgOQAAgHAGgEQAFgFAJAAIAZAAIAAA2gAGWA3QAAAGAFADQAEADAGAAIASAAIAAgXIgSAAQgPAAAAALgADeBdIAAgvIglAvIgFAAIAAg2IAFAAIAAAvIAlgvIAFAAIAAA2gACcBdIgVgbIgNAOIAAANIgFAAIAAg2IAFAAIAAAjIAhgjIAHAAIgYAYIAZAegAA/BdIAAg2IAGAAIAAAVIAQAAQAUAAAAAPQAAAJgFAEQgFAFgJAAgABFBZIAQAAQAPAAAAgNQAAgMgQAAIgPAAgAgUBdIAAg2IAFAAIAAA2gAg8BdIAAgxIgUAAIAAgFIAtAAIAAAFIgUAAIAAAxgAh/BdIAAgvIglAvIgFAAIAAg2IAFAAIAAAvIAlgvIAFAAIAAA2gAi/BdIAAgvIglAvIgFAAIAAg2IAFAAIAAAvIAlgvIAFAAIAAA2gAkABdIAAgaIgkAAIAAAaIgFAAIAAg2IAFAAIAAAYIAkAAIAAgYIAGAAIAAA2gAmGBdIAAgXQgJAFgKAAQgSAAAAgQIAAgUIAFAAIAAAUQAAALAMAAQAMAAAIgGIAAgZIAFAAIAAA2gAn/BdIAAgaIgkAAIAAAaIgFAAIAAg2IAFAAIAAAYIAkAAIAAgYIAGAAIAAA2gApzBdIAAgvIglAvIgFAAIAAg2IAFAAIAAAvIAlgvIAFAAIAAA2gAsHBdIAAhFIguAAIAABFIgGAAIAAhKIA6AAIAABKgAtyBdIAAgJIAHAAIAAAJgAuNBdIAAgUIgSAAIgQAUIgGAAIARgVQgQgDAAgOQAAgHAGgEQAFgFAJAAIAYAAIAAA2gAuuA3QAAAMAPAAIASAAIAAgXIgSAAQgPAAAAALgAwGBdIAAg2IAZAAQARAAAAAOQAAAIgJAEQAMADAAALQAAAOgTAAgAwBBZIAUAAQAPAAAAgMQAAgJgQgBIgTAAgAwBA/IATAAQANAAAAgKQAAgJgNAAIgTAAgAvKAlQAGgDAAgGIAAAAIgDAAIAAgJIAHAAIAAAIQAAAIgJAEgAigASIAEgBQACAIAIAAQAIAAACgIIAFABQgDAMgMAAQgMAAgCgMgATwAZIAAgHIAHAAIAAAHgAP8AZIAAgHIAGAAIAAAHgANyAZIAAgHIAGAAIAAAHgAgVAZIAAgHIAHAAIAAAHgAIJgSIACgFQAEACAFAAQAIAAAGgNIgag2IAGAAIAWAxIAUgxIAGAAIgYA4QgGAQgMAAQgEAAgHgCgALCgQIAAhIIAFAAIAAAMQAKgNANAAQAKAAAIAIQAIAHAAANQAAANgIAIQgIAIgKAAQgOAAgJgNIAAAdgALOhOQgHAIAAAJQAAAKAHAIQAGAGAJAAQAJAAAGgGQAGgGAAgMQAAgKgGgHQgGgGgJAAQgJAAgGAGgAwLgQIAAhIIAFAAIAAAMQAJgNANAAQALAAAHAIQAJAHAAANQAAANgJAIQgHAIgLAAQgNAAgJgNIAAAdgAwAhOQgGAIAAAJQAAAKAGAIQAHAGAJAAQAJAAAGgGQAGgGAAgMQAAgKgGgHQgGgGgJAAQgJAAgHAGgASPgSIAAgQIgxAAIgCAQIgEAAIAAgUIAHAAQAIgNAAgZIAAgMIAlAAIAAAyIAIAAIgBAUgARshJQAAAXgHAMIAhAAIAAgtIgaAAgAmSgpQgLAJgNAAQgRAAgKgLQgLgMAAgPQAAgQALgLQAKgMARAAQAQAAALAMQAKALAAAQQAAAOgKAMIALAJIgEAEgAnBheQgJAJAAAPQAAANAJAKQAJAKAOAAQAKAAAKgHIgPgNIAEgEIAOANQAIgKAAgMQAAgPgJgJQgJgKgNAAQgOAAgJAKgAJSgpQgIgIAAgMQAAgLAIgIQAIgJALAAQAMAAAKAKIgEAEQgJgJgJAAQgJAAgGAHQgHAHAAAJQAAALAHAGQAGAHAKAAQAJAAAIgJIAEADQgJALgNAAQgLAAgIgJgAGygpQgIgIAAgMQAAgLAIgIQAIgJAMAAQAMAAAJAKIgDAEQgIgJgKAAQgIAAgHAGQgGAGgBAJIAcAAIAAAEIgcAAQABAJAGAHQAGAGAJAAQAKAAAIgJIAEADQgJALgNAAQgMAAgIgJgAFwgkQgGgFAAgJQAAgHAGgFQAHgFAKAAQAKAAAIADIAAgDQAAgQgRgBQgIAAgJAFIgCgFQAKgEAJAAQALgBAGAHQAFAEAAALIAAAhIgFAAIAAgJQgGALgOAAQgJAAgGgEgAFvgyQAAANAQAAQAIAAAGgFQAGgFAAgGIAAgHQgLgDgHABQgSgBAAANgAD0goQgHgHgBgLIgNAAIAAAYIgGAAIAAg2IAGAAIAAAZIANAAQABgLAHgHQAHgIALAAQAMAAAHAJQAHAHAAAMQAAAMgHAIQgHAJgMAAQgLAAgHgIgAD3hNQgFAGAAAKQAAALAFAGQAGAHAJAAQAKAAAFgHQAGgGAAgLQAAgKgGgGQgGgHgJAAQgJAAgGAHgAiAgoQgIgIAAgNQAAgMAIgHQAHgJALAAQALAAAHAJQAHAHAAAMIAAACIgtAAQAAALAHAFQAGAGAIAAQALAAAHgIIAEACQgJALgNAAQgLAAgIgIgAh8hOQgFAGgBAJIAnAAQgCgVgRAAQgIAAgGAGgAlwgrQgLgMAAgPQAAgQALgLQAKgMARAAQAQAAALAMQAKALAAAQQAAAPgKAMQgLALgQAAQgRAAgKgLgAlsheQgJAJAAAPQAAANAJAKQAJAKAOAAQANAAAJgKQAJgKAAgNQAAgPgJgJQgJgKgNAAQgOAAgJAKgAsKgkQgHgGAAgIQAAgHAHgFQAGgFALAAQAJAAAJADIAAgDQAAgQgSgBQgIAAgJAFIgCgFQAKgEAJAAQAMgBAFAHQAGAEAAALIAAAhIgFAAIAAgJQgHALgOAAQgJAAgFgEgAsLgyQAAANAPAAQAJAAAGgFQAGgFAAgGIAAgHQgLgDgHABQgSgBAAANgAt9gpQgIgIAAgMQAAgLAIgIQAIgJAMAAQANAAAIAKIgDAEQgJgJgJAAQgJAAgHAHQgGAHAAAJQAAALAGAGQAHAHAJAAQAKAAAIgJIAEADQgKALgMAAQgMAAgIgJgAxHgpQgIgHAAgNQAAgLAIgIQAIgJAMAAQAMAAAIAJQAIAHAAAMQAAAMgIAIQgIAJgMAAQgMAAgIgJgAxDhNQgGAHAAAJQAAALAGAGQAHAHAJAAQAJAAAHgHQAGgHAAgKQAAgJgGgHQgHgHgJAAQgJAAgHAHgASXgiIABgEIAEABQAGgBADgGQADgKAAgfIAAgDIAlAAIAAA2IgFAAIAAgxIgbAAIAAACQAAAegEALQgEAHgIAAgANHgpIADgDQAKAHAJAAQAGAAAEgEQAFgCAAgGQAAgKgPAAIgIAAIAAgEIAIAAQANAAAAgLQAAgKgNAAQgKAAgHAGIgDgEQAIgGAMAAQAJAAAFADQAFAFAAAGQAAAJgJAEQAKADAAAJQAAAHgFAFQgGAEgJAAQgMABgKgJgACQgiIABgEIAEABQAHgBACgGQAEgKAAgfIAAgDIAlAAIAAA2IgFAAIAAgxIgbAAIAAACQAAAegFALQgDAHgJAAgAkngsIADgFQANAMAOAAQAJgBAFgEQAFgEAAgGQAAgHgEgCQgFgEgMgDQgZgFAAgQQAAgIAHgHQAGgFALAAQAOAAALAJIgDAEQgKgIgNAAQgIAAgFAFQgFADAAAHQAAAGAEADQAFAEANADQAYAFAAAQQAAAJgHAFQgGAFgLAAQgQAAgOgLgAUEgiIAAgUIgSAAIgQAUIgGAAIARgVQgQgCAAgOQAAgIAGgEQAFgEAJgBIAYAAIAAA2gATjhHQAAAGAEADQAEADAHAAIASAAIAAgYIgSAAQgPAAAAAMgAQrgiIAAguIglAuIgFAAIAAg2IAFAAIAAAvIAlgvIAFAAIAAA2gAPpgiIgVgaIgOAOIAAAMIgFAAIAAg2IAFAAIAAAjIAigjIAHAAIgYAZIAZAdgAOrgiIAAguIgkAuIgGAAIAAg2IAGAAIAAAvIAkgvIAGAAIAAA2gAM2giIAAguIgkAuIgFAAIAAg2IAFAAIAAAvIAkgvIAGAAIAAA2gAKOgiIAAg2IAFAAIAAA2gAFRgiIAAgXQgJAFgKAAQgSAAAAgQIAAgUIAFAAIAAAVQAAALAMgBQALAAAJgFIAAgaIAFAAIAAA2gACCgiIgWgaIgNAOIAAAMIgFAAIAAg2IAFAAIAAAjIAigjIAHAAIgYAZIAYAdgABEgiIAAguIglAuIgFAAIAAg2IAFAAIAAAvIAlgvIAFAAIAAA2gAglgiIAAg2IAZAAQARAAAAAOQAAAIgIAFQALACAAALQAAAOgTAAgAgfgmIAUAAQANAAAAgLQAAgKgPAAIgSAAgAgfg/IASAAQANAAAAgLQAAgJgMAAIgTAAgAibgiIAAgZIgkAAIAAAZIgFAAIAAg2IAFAAIAAAZIAkAAIAAgZIAFAAIAAA2gAnsgiIAAhJIAGAAIAABJgAopgiIAAgUIgSAAIgQAUIgGAAIARgVQgQgCAAgOQAAgIAGgEQAFgEAJgBIAYAAIAAA2gApKhHQAAAGAEADQAEADAHAAIASAAIAAgYIgSAAQgPAAAAAMgApkgiIAAgZIgkAAIAAAZIgFAAIAAg2IAFAAIAAAZIAkAAIAAgZIAGAAIAAA2gAqjgiIAAgZIgkAAIAAAZIgGAAIAAg2IAGAAIAAAZIAkAAIAAgZIAFAAIAAA2gAs0giIAAgxIgUAAIAAgFIAuAAIAAAFIgVAAIAAAxgAuXgiIAAguIglAuIgFAAIAAg2IAFAAIAAAvIAlgvIAFAAIAAA2gAxYgiIgWgaIgNAOIAAAMIgFAAIAAg2IAFAAIAAAjIAigjIAGAAIgXAZIAYAdgAyWgiIAAguIglAuIgFAAIAAg2IAFAAIAAAvIAlgvIAFAAIAAA2gA0JgiIAAhJIAfAAQALAAAGAEQAHAGAAAIQAAAMgNAGQARAEAAAOQAAAJgHAFQgIAFgMAAgA0EgnIAbAAQAVAAAAgPQAAgPgWAAIgaAAgA0EhJIAZAAQATgBAAgPQAAgOgTAAIgZAAgAKNhmIAAgHIAHAAIAAAHg");
	this.shape_1.setTransform(-0.6,-0.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.urText_w, new cjs.Rectangle(-142.8,-21.6,285.7,43.3), null);


(lib.urText_b = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#404041").ss(1,2,0,3).p("A2JjNMAsTAAAIAAGbMgsTAAAg");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#404041").s().p("ArnBuIAAhHIAFAAIAAAMQAJgOANAAQALABAHAHQAJAIAAANQAAAMgJAJQgHAIgLgBQgNAAgJgMIAAAcgArbAxQgHAHAAAKQAAAKAHAHQAGAGAJABQAJAAAGgHQAGgGAAgLQAAgKgGgHQgGgHgJABQgJgBgGAHgAyQBuIAAhHIAFAAIAAAMQAJgOANAAQALABAHAHQAJAIAAANQAAAMgJAJQgHAIgLgBQgNAAgJgMIAAAcgAyEAxQgHAHAAAKQAAAKAHAHQAGAGAJABQAJAAAGgHQAGgGAAgLQAAgKgGgHQgGgHgJABQgJgBgGAHgAFCBtIAAgQIgxAAIgBAQIgFAAIAAgUIAIAAQAIgOAAgZIAAgLIAkAAIAAAyIAJAAIgBAUgAEgA2QAAAWgIANIAiAAIAAgtIgaAAgAzhBtIAAgQIgyAAIgBAQIgEAAIAAgUIAHAAQAIgOAAgZIAAgLIAkAAIAAAyIAJAAIgBAUgA0EA2QAAAWgHANIAhAAIAAgtIgaAAgAUKBWQgHgIAAgOQAAgRADgHQAEgMAMgDIAfgHIABAEIgdAIQgQAEgBASQAIgNAPgBQALAAAIAJQAHAIAAALQAAAMgHAIQgIAJgMgBQgMAAgIgIgAUOAyQgGAHAAAJQAAAKAHAHQAGAGAJABQAKAAAGgHQAGgHAAgKQAAgJgHgHQgGgGgJAAQgJAAgHAGgAS1BWQgIgIAAgMQAAgLAIgJQAIgIALgBQAMAAAKALIgEAEQgJgJgJAAQgJAAgGAGQgHAIAAAJQAAAJAHAIQAGAHAJAAQAKAAAIgKIAEADQgJALgNAAQgMABgHgJgAR1BWQgIgIAAgMQAAgLAIgJQAIgIAMgBQAMABAIAIQAHAIAAAMQAAAMgIAIQgIAJgMgBQgMABgHgJgAR5AxQgHAIAAAJQAAAKAHAHQAGAHAKAAQAJAAAGgHQAHgIAAgJQAAgJgHgIQgGgGgKAAQgJAAgGAGgAL2BWQgIgIAAgMQAAgLAIgJQAIgIAMgBQAMABAIAIQAIAIAAAMQAAAMgIAIQgIAJgMgBQgMABgIgJgAL6AxQgGAIAAAJQAAAKAGAHQAHAHAJAAQAJAAAHgHQAGgIAAgJQAAgJgGgIQgHgGgJAAQgJAAgHAGgAI3BWQgIgIAAgMQAAgLAIgJQAIgIAMgBQAMABAIAIQAIAJAAALQAAAMgIAIQgIAJgMgBQgMABgIgJgAI7AxQgGAIAAAJQAAAKAGAHQAGAHAKAAQAJAAAHgHQAGgIAAgJQAAgJgGgIQgHgGgJAAQgJAAgHAGgAlkBWQgIgHAAgNQAAgMAHgIQAHgIALgBQAMABAHAIQAGAIAAAMIAAACIgtAAQABAKAGAGQAGAFAIABQAMAAAHgJIAEADQgKAKgNAAQgLAAgHgIgAlgAwQgGAHgBAJIAoAAQgCgWgSABQgIAAgFAFgAnmBaQgHgFAAgIQAAgIAHgFQAHgFAKAAQAJAAAJADIAAgDQAAgQgSAAQgIAAgJAEIgCgEQAKgFAKAAQALAAAGAGQAFAGAAAJIAAAiIgFAAIAAgJQgHAKgOAAQgJABgFgFgAnnBNQAAANAQAAQAIgBAGgEQAGgFAAgHIAAgHQgLgCgHAAQgSAAAAANgAxBBWQgIgIAAgMQAAgLAIgJQAIgIALgBQAMABAIAIQAIAIAAAMQAAAMgIAIQgIAJgMgBQgMABgHgJgAw9AxQgHAIAAAJQAAAKAHAHQAGAHAJAAQAJAAAHgHQAHgIAAgJQAAgJgHgIQgHgGgJAAQgJAAgGAGgAzMBWQgIgIAAgMQAAgLAIgJQAIgIAMgBQAMABAIAIQAIAJAAALQAAAMgIAIQgIAJgMgBQgMABgIgJgAzHAxQgHAHAAAKQAAAKAHAHQAGAHAJAAQAJAAAHgHQAGgIAAgJQAAgJgGgIQgHgGgJAAQgJAAgGAGgAMoBdIABgEIAEAAQAHAAACgHQAEgKAAgeIAAgDIAlAAIAAA2IgFAAIAAgxIgbAAIAAABQAAAfgFAKQgDAIgJAAgAFKBdIABgEIAEAAQAHAAACgHQAEgKAAgeIAAgDIAlAAIAAA2IgGAAIAAgxIgaAAIAAABQAAAfgFAKQgDAIgJAAgAgJBdIABgEIAEAAQAGAAACgHQAEgKAAgeIAAgDIAlAAIAAA2IgGAAIAAgxIgaAAIAAABQAAAfgFAKQgDAIgIAAgApiBWIADgEQAJAIAKAAQAGgBAEgDQAFgDAAgFQAAgEgEgDQgFgEgHAAIgHAAIAAgEIAIAAQANAAAAgKQAAgKgNAAQgKAAgHAFIgDgDQAIgHAMAAQAIAAAGAEQAFAEAAAHQAAAIgJAEQAKADAAAKQAAAGgFAFQgGAFgJAAQgNAAgJgIgA1KBWIADgEQAKAIAJAAQAGgBAEgDQAFgEAAgEQAAgLgPAAIgIAAIAAgEIAIAAQANAAAAgKQAAgKgNAAQgKAAgHAFIgDgDQAIgHAMAAQAJAAAFAEQAFAEAAAHQAAAIgJAEQAKADAAAKQAAAGgFAFQgGAFgJAAQgMAAgKgIgAVEBdIAAgJIAHAAIAAAJgATxBdIAAg2IAFAAIAAA2gAQ4BdIgTgYIgTAYIgGAAIAWgcIgVgaIAGAAIASAXIATgXIAGAAIgVAaIAWAcgAP8BdIAAg2IAGAAIAAA2gAPlBdIAAgaIgkAAIAAAaIgFAAIAAg2IAFAAIAAAYIAkAAIAAgYIAFAAIAAA2gAOUBdIAAgxIgUAAIAAgFIAuAAIAAAFIgUAAIAAAxgANyBdIAAg2IAFAAIAAA2gALbBdIAAgaIgkAAIAAAaIgFAAIAAg2IAFAAIAAAYIAkAAIAAgYIAGAAIAAA2gAJyBdIAAg2IAZAAQASAAAAAOQAAAHgJAFQAMADAAALQAAAOgUAAgAJ4BZIAUAAQAOAAAAgMQAAgJgQgBIgSAAgAJ4A/IASAAQANAAAAgKQAAgJgMAAIgTAAgAIbBdIAAgxIgjAAIAAAxIgFAAIAAg2IAtAAIAAA2gAG3BdIAAgUIgRAAIgRAUIgGAAIARgVQgQgDAAgOQAAgHAGgEQAFgFAJAAIAZAAIAAA2gAGWA3QAAAGAFADQAEADAGAAIASAAIAAgXIgSAAQgPAAAAALgADeBdIAAgvIglAvIgFAAIAAg2IAFAAIAAAvIAlgvIAFAAIAAA2gACcBdIgVgbIgNAOIAAANIgFAAIAAg2IAFAAIAAAjIAhgjIAHAAIgYAYIAZAegAA/BdIAAg2IAGAAIAAAVIAQAAQAUAAAAAPQAAAJgFAEQgFAFgJAAgABFBZIAQAAQAPAAAAgNQAAgMgQAAIgPAAgAgUBdIAAg2IAFAAIAAA2gAg8BdIAAgxIgUAAIAAgFIAtAAIAAAFIgUAAIAAAxgAh/BdIAAgvIglAvIgFAAIAAg2IAFAAIAAAvIAlgvIAFAAIAAA2gAi/BdIAAgvIglAvIgFAAIAAg2IAFAAIAAAvIAlgvIAFAAIAAA2gAkABdIAAgaIgkAAIAAAaIgFAAIAAg2IAFAAIAAAYIAkAAIAAgYIAGAAIAAA2gAmGBdIAAgXQgJAFgKAAQgSAAAAgQIAAgUIAFAAIAAAUQAAALAMAAQAMAAAIgGIAAgZIAFAAIAAA2gAn/BdIAAgaIgkAAIAAAaIgFAAIAAg2IAFAAIAAAYIAkAAIAAgYIAGAAIAAA2gApzBdIAAgvIglAvIgFAAIAAg2IAFAAIAAAvIAlgvIAFAAIAAA2gAsHBdIAAhFIguAAIAABFIgGAAIAAhKIA6AAIAABKgAtyBdIAAgJIAHAAIAAAJgAuNBdIAAgUIgSAAIgQAUIgGAAIARgVQgQgDAAgOQAAgHAGgEQAFgFAJAAIAYAAIAAA2gAuuA3QAAAMAPAAIASAAIAAgXIgSAAQgPAAAAALgAwGBdIAAg2IAZAAQARAAAAAOQAAAIgJAEQAMADAAALQAAAOgTAAgAwBBZIAUAAQAPAAAAgMQAAgJgQgBIgTAAgAwBA/IATAAQANAAAAgKQAAgJgNAAIgTAAgAvKAlQAGgDAAgGIAAAAIgDAAIAAgJIAHAAIAAAIQAAAIgJAEgAigASIAEgBQACAIAIAAQAIAAACgIIAFABQgDAMgMAAQgMAAgCgMgATwAZIAAgHIAHAAIAAAHgAP8AZIAAgHIAGAAIAAAHgANyAZIAAgHIAGAAIAAAHgAgVAZIAAgHIAHAAIAAAHgAIJgSIACgFQAEACAFAAQAIAAAGgNIgag2IAGAAIAWAxIAUgxIAGAAIgYA4QgGAQgMAAQgEAAgHgCgALCgQIAAhIIAFAAIAAAMQAKgNANAAQAKAAAIAIQAIAHAAANQAAANgIAIQgIAIgKAAQgOAAgJgNIAAAdgALOhOQgHAIAAAJQAAAKAHAIQAGAGAJAAQAJAAAGgGQAGgGAAgMQAAgKgGgHQgGgGgJAAQgJAAgGAGgAwLgQIAAhIIAFAAIAAAMQAJgNANAAQALAAAHAIQAJAHAAANQAAANgJAIQgHAIgLAAQgNAAgJgNIAAAdgAwAhOQgGAIAAAJQAAAKAGAIQAHAGAJAAQAJAAAGgGQAGgGAAgMQAAgKgGgHQgGgGgJAAQgJAAgHAGgASPgSIAAgQIgxAAIgCAQIgEAAIAAgUIAHAAQAIgNAAgZIAAgMIAlAAIAAAyIAIAAIgBAUgARshJQAAAXgHAMIAhAAIAAgtIgaAAgAmSgpQgLAJgNAAQgRAAgKgLQgLgMAAgPQAAgQALgLQAKgMARAAQAQAAALAMQAKALAAAQQAAAOgKAMIALAJIgEAEgAnBheQgJAJAAAPQAAANAJAKQAJAKAOAAQAKAAAKgHIgPgNIAEgEIAOANQAIgKAAgMQAAgPgJgJQgJgKgNAAQgOAAgJAKgAJSgpQgIgIAAgMQAAgLAIgIQAIgJALAAQAMAAAKAKIgEAEQgJgJgJAAQgJAAgGAHQgHAHAAAJQAAALAHAGQAGAHAKAAQAJAAAIgJIAEADQgJALgNAAQgLAAgIgJgAGygpQgIgIAAgMQAAgLAIgIQAIgJAMAAQAMAAAJAKIgDAEQgIgJgKAAQgIAAgHAGQgGAGgBAJIAcAAIAAAEIgcAAQABAJAGAHQAGAGAJAAQAKAAAIgJIAEADQgJALgNAAQgMAAgIgJgAFwgkQgGgFAAgJQAAgHAGgFQAHgFAKAAQAKAAAIADIAAgDQAAgQgRgBQgIAAgJAFIgCgFQAKgEAJAAQALgBAGAHQAFAEAAALIAAAhIgFAAIAAgJQgGALgOAAQgJAAgGgEgAFvgyQAAANAQAAQAIAAAGgFQAGgFAAgGIAAgHQgLgDgHABQgSgBAAANgAD0goQgHgHgBgLIgNAAIAAAYIgGAAIAAg2IAGAAIAAAZIANAAQABgLAHgHQAHgIALAAQAMAAAHAJQAHAHAAAMQAAAMgHAIQgHAJgMAAQgLAAgHgIgAD3hNQgFAGAAAKQAAALAFAGQAGAHAJAAQAKAAAFgHQAGgGAAgLQAAgKgGgGQgGgHgJAAQgJAAgGAHgAiAgoQgIgIAAgNQAAgMAIgHQAHgJALAAQALAAAHAJQAHAHAAAMIAAACIgtAAQAAALAHAFQAGAGAIAAQALAAAHgIIAEACQgJALgNAAQgLAAgIgIgAh8hOQgFAGgBAJIAnAAQgCgVgRAAQgIAAgGAGgAlwgrQgLgMAAgPQAAgQALgLQAKgMARAAQAQAAALAMQAKALAAAQQAAAPgKAMQgLALgQAAQgRAAgKgLgAlsheQgJAJAAAPQAAANAJAKQAJAKAOAAQANAAAJgKQAJgKAAgNQAAgPgJgJQgJgKgNAAQgOAAgJAKgAsKgkQgHgGAAgIQAAgHAHgFQAGgFALAAQAJAAAJADIAAgDQAAgQgSgBQgIAAgJAFIgCgFQAKgEAJAAQAMgBAFAHQAGAEAAALIAAAhIgFAAIAAgJQgHALgOAAQgJAAgFgEgAsLgyQAAANAPAAQAJAAAGgFQAGgFAAgGIAAgHQgLgDgHABQgSgBAAANgAt9gpQgIgIAAgMQAAgLAIgIQAIgJAMAAQANAAAIAKIgDAEQgJgJgJAAQgJAAgHAHQgGAHAAAJQAAALAGAGQAHAHAJAAQAKAAAIgJIAEADQgKALgMAAQgMAAgIgJgAxHgpQgIgHAAgNQAAgLAIgIQAIgJAMAAQAMAAAIAJQAIAHAAAMQAAAMgIAIQgIAJgMAAQgMAAgIgJgAxDhNQgGAHAAAJQAAALAGAGQAHAHAJAAQAJAAAHgHQAGgHAAgKQAAgJgGgHQgHgHgJAAQgJAAgHAHgASXgiIABgEIAEABQAGgBADgGQADgKAAgfIAAgDIAlAAIAAA2IgFAAIAAgxIgbAAIAAACQAAAegEALQgEAHgIAAgANHgpIADgDQAKAHAJAAQAGAAAEgEQAFgCAAgGQAAgKgPAAIgIAAIAAgEIAIAAQANAAAAgLQAAgKgNAAQgKAAgHAGIgDgEQAIgGAMAAQAJAAAFADQAFAFAAAGQAAAJgJAEQAKADAAAJQAAAHgFAFQgGAEgJAAQgMABgKgJgACQgiIABgEIAEABQAHgBACgGQAEgKAAgfIAAgDIAlAAIAAA2IgFAAIAAgxIgbAAIAAACQAAAegFALQgDAHgJAAgAkngsIADgFQANAMAOAAQAJgBAFgEQAFgEAAgGQAAgHgEgCQgFgEgMgDQgZgFAAgQQAAgIAHgHQAGgFALAAQAOAAALAJIgDAEQgKgIgNAAQgIAAgFAFQgFADAAAHQAAAGAEADQAFAEANADQAYAFAAAQQAAAJgHAFQgGAFgLAAQgQAAgOgLgAUEgiIAAgUIgSAAIgQAUIgGAAIARgVQgQgCAAgOQAAgIAGgEQAFgEAJgBIAYAAIAAA2gATjhHQAAAGAEADQAEADAHAAIASAAIAAgYIgSAAQgPAAAAAMgAQrgiIAAguIglAuIgFAAIAAg2IAFAAIAAAvIAlgvIAFAAIAAA2gAPpgiIgVgaIgOAOIAAAMIgFAAIAAg2IAFAAIAAAjIAigjIAHAAIgYAZIAZAdgAOrgiIAAguIgkAuIgGAAIAAg2IAGAAIAAAvIAkgvIAGAAIAAA2gAM2giIAAguIgkAuIgFAAIAAg2IAFAAIAAAvIAkgvIAGAAIAAA2gAKOgiIAAg2IAFAAIAAA2gAFRgiIAAgXQgJAFgKAAQgSAAAAgQIAAgUIAFAAIAAAVQAAALAMgBQALAAAJgFIAAgaIAFAAIAAA2gACCgiIgWgaIgNAOIAAAMIgFAAIAAg2IAFAAIAAAjIAigjIAHAAIgYAZIAYAdgABEgiIAAguIglAuIgFAAIAAg2IAFAAIAAAvIAlgvIAFAAIAAA2gAglgiIAAg2IAZAAQARAAAAAOQAAAIgIAFQALACAAALQAAAOgTAAgAgfgmIAUAAQANAAAAgLQAAgKgPAAIgSAAgAgfg/IASAAQANAAAAgLQAAgJgMAAIgTAAgAibgiIAAgZIgkAAIAAAZIgFAAIAAg2IAFAAIAAAZIAkAAIAAgZIAFAAIAAA2gAnsgiIAAhJIAGAAIAABJgAopgiIAAgUIgSAAIgQAUIgGAAIARgVQgQgCAAgOQAAgIAGgEQAFgEAJgBIAYAAIAAA2gApKhHQAAAGAEADQAEADAHAAIASAAIAAgYIgSAAQgPAAAAAMgApkgiIAAgZIgkAAIAAAZIgFAAIAAg2IAFAAIAAAZIAkAAIAAgZIAGAAIAAA2gAqjgiIAAgZIgkAAIAAAZIgGAAIAAg2IAGAAIAAAZIAkAAIAAgZIAFAAIAAA2gAs0giIAAgxIgUAAIAAgFIAuAAIAAAFIgVAAIAAAxgAuXgiIAAguIglAuIgFAAIAAg2IAFAAIAAAvIAlgvIAFAAIAAA2gAxYgiIgWgaIgNAOIAAAMIgFAAIAAg2IAFAAIAAAjIAigjIAGAAIgXAZIAYAdgAyWgiIAAguIglAuIgFAAIAAg2IAFAAIAAAvIAlgvIAFAAIAAA2gA0JgiIAAhJIAfAAQALAAAGAEQAHAGAAAIQAAAMgNAGQARAEAAAOQAAAJgHAFQgIAFgMAAgA0EgnIAbAAQAVAAAAgPQAAgPgWAAIgaAAgA0EhJIAZAAQATgBAAgPQAAgOgTAAIgZAAgAKNhmIAAgHIAHAAIAAAHg");
	this.shape_1.setTransform(-0.6,-0.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.urText_b, new cjs.Rectangle(-142.8,-21.6,285.7,43.3), null);


(lib.t2_3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#404040").s().p("AMxBWQgWgYAAgiQAAghAWgYQAZgZAiAAQAjAAAXAYQAXAZAAAhQAAAigXAYQgYAYgiAAQgkAAgXgYgAM+gUQgTAUAAAcQAAAcATAUQATAUAbAAQAaAAAUgUQASgUAAgcQAAgcgSgUQgUgUgaAAQgbAAgTAUgAERBWQgYgYAAgiQAAghAYgYQAYgZAiAAQAiAAAYAYQAXAYAAAiQAAAigXAYQgYAYgjAAQgjAAgWgYgAEdgUQgTAUAAAcQAAAcATAUQATAUAbAAQAbAAASgUQAUgUgBgcQABgcgUgUQgTgUgbAAQgaAAgTAUgAk4BWQgYgYAAgiQAAghAYgYQAXgZAjAAQAiAAAYAYQAXAYAAAiQAAAigXAYQgYAYgjAAQgiAAgXgYgAksgUQgTAUAAAcQAAAcATAUQATAUAbAAQAbAAASgUQAUgUgBgcQABgcgUgUQgTgUgbAAQgaAAgTAUgAsUBYQgYgYAAglQABghAVgYQAWgYAgAAQAhAAATAYQAUAXAAAjIAAAGIiEAAQACAcATASQARAQAZAAQAfAAAXgZIAKAKQgbAdgmAAQggAAgWgWgAqoAUQgCgZgOgQQgPgTgaAAQgYAAgQARQgQASgDAZIB0AAIAAAAgAqDBWIAJgMQAZAWAeAAQAQAAANgKQAOgJAAgOQAAgOgLgIQgMgIgVAAIgWAAIAAgOIAWAAQASAAAKgIQALgIAAgOQAAgNgLgHQgKgIgRAAQgdAAgUAQIgJgMQAZgSAiAAQAYAAAQAMQAPALgBATQABAZgaALQAeAKAAAcQAAAUgQANQgRAOgbAAQgjAAgdgYgAPgBrIAAgbIAUAAIAAAbgALkBrIAAhKIhqAAIAABKIgPAAIAAidIAPAAIAABFIBqAAIAAhFIAOAAIAACdgAG+BrIAAidIBJAAQAXAAAOAKQAOALAAASQAAAZgaAKQAjAKAAAeQAAAUgQALQgPAMgZAAgAHOBdIA6AAQAVAAALgIQALgJAAgOQAAgeguAAIg3AAgAHOATIA3AAQARAAAKgHQAKgJAAgNQAAgMgJgHQgKgIgRAAIg4AAgACpBrIAAiQIg7AAIAAgNICGAAIAAANIg8AAIAACQgAiLBrIAAidIAQAAIAACPIBXAAIAAiPIAPAAIAACPIBXAAIAAiPIAPAAIAACdgAlvBrIg+hNIgnAmIAAAnIgPAAIAAidIAPAAIAABkIBihkIAUAAIhFBFIBIBYgAvzBrIAAjYICYAAIAAAPIiHAAIAABNIBIAAQAkAAAVAOQAWAOAAAfQAAAfgUARQgUARgkAAgAviBcIBIAAQA+AAAAgyQAAgWgRgMQgQgLgeAAIhHAAgAPlAyIgEifIASAAIgFCfg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t2_3, new cjs.Rectangle(-101.2,-11,202.4,22.1), null);


(lib.t2_2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#404040").s().p("AiqCEIAAgsIiRAAIgDAsIgMAAIAAg6IAUAAQAYgmAAhIIAAghIBqAAIAACPIAZAAIgDA6gAkQgbQAAAegGAcQgFAbgKAQIBiAAIAAiCIhNAAgAE3BYIAAgbIAUAAIAAAbgACOBYIAAidIBIAAQAXAAAOAKQAOALAAASQAAAagbAJQAkAKAAAeQAAATgPAMQgQAMgaAAgACdBKIA7AAQATAAAMgIQALgJAAgOQAAgeguAAIg3AAgACdAAIA3AAQARAAAKgGQALgJAAgOQAAgMgKgHQgKgIgRAAIg4AAgABEBYIAAidIAPAAIAACdgAAABYIAAhKIhoAAIAABKIgQAAIAAidIAQAAIAABFIBoAAIAAhFIAPAAIAACdgABChvIAAgUIATAAIAAAUg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t2_2, new cjs.Rectangle(-33.1,-13.2,66.3,26.5), null);


(lib.t2_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#404040").s().p("ABbBtIAAg1Ih1AAIgFgMIB7iYIAOAAIAACWIAjAAIAAAOIgjAAIAAA1gAgMAqIBnAAIAAh/gAheBtIAAjJIgrAPIgDgNIAxgSIANAAIAADZg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t2_1, new cjs.Rectangle(-14.1,-10.9,28.3,21.9), null);


(lib.t1_2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ah7BTQgdAYgnAAQgvAAgeggQgcgfAAgsQAAgtAdgfQAeghAuAAQAvAAAeAhQAdAfAAAtQAAApgcAgIAeAZIgLAMgAj/hDQgZAbAAAoQAAAmAZAcQAaAbAmAAQAhAAAXgUIgpgiIAMgNIAoAlQAXgaAAglQAAgogagbQgagcgmAAQgnAAgZAcgAgNBLQgcgfAAgsQAAgtAdgfQAdghAuAAQAvAAAeAhQAdAfAAAtQAAArgdAfQgfAhguAAQgvAAgdgggAAAhDQgZAbAAAoQAAAmAZAcQAZAbAmAAQAnAAAagbQAZgbAAgnQAAgogagbQgagcgmAAQgnAAgYAcgADQBJIALgMQARARARAHQASAIAXAAQAXAAAPgMQAPgMAAgTQAAgRgMgKQgNgKgigHQgmgHgRgOQgQgOAAgYQAAgYATgPQATgQAdAAQApAAAfAZIgKAMQgbgXgjAAQgXAAgPALQgOAMAAARQAAASAMAJQAOAMAkAHQAkAHAQANQARAOAAAXQAAAagUAQQgTAQgfAAQgvAAgmgigAlqBoIAAjRIAQAAIAADRg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1_2, new cjs.Rectangle(-36.2,-11,72.6,22), null);


(lib.t1_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AB9CDIAAjHIAPAAIAAAiQAYgmAnAAQAeAAAVAVQAXAXAAAjQAAAjgXAYQgVAVgeAAQgnAAgYglIAABRgACegoQgTAUAAAbQAAAdATATQASASAaAAQAZAAARgRQARgTABgeQAAgcgSgTQgSgSgYAAQgaAAgSASgABUB/IAAgrIiLAAIgDArIgMAAIAAg5IAUAAQAWglAAhFIAAggIBmAAIAACKIAYAAIgDA5gAgNgcQgBAdgFAcQgGAagJAPIBdAAIAAh+IhIAAgAE9BLQgSgNAAgXQAAgYATgNQARgMAfgBQAXABAcAGIAAgHQAAgWgOgNQgNgLgYAAQgYAAgYAMIgGgNQAegNAZAAQAfAAASARQAPAQAAAbIAABfIgOAAIAAgaQgVAdgmAAQgZAAgQgMgAFIAMQgNAKAAAQQAAAQAMAKQAMAJAUAAQAYAAARgNQARgOAAgUIAAgSQgcgGgYAAQgYAAgNAKgAm7BAQgWgYAAghQAAggAWgYQAXgXAhAAQAkAAAZAdIgKAKQgZgagaABQgagBgRAUQgTAUAAAaQAAAcATATQARATAbAAQAcAAAWgaIALAKQgaAegkAAQghAAgXgXgApnBBQgWgXAAgkQAAggAUgXQAVgXAfAAQAgAAATAXQAUAWgBAiIAAAGIh/AAQACAcASARQARAPAXAAQAfAAAWgYIAKAJQgOAOgNAHQgQAIgUAAQgfAAgWgWgAn+AAQgCgYgOgQQgPgSgYAAQgXAAgQARQgPAQgDAZIBwAAIAAAAgAKeBUIAAiYIBHAAQAWgBAOALQANAKAAARQAAAZgaAKQAiAJAAAcQABAUgPALQgQAMgZAAgAKtBGIA5AAQATAAALgIQAMgJAAgNQAAgOgMgHQgMgIgVAAIg2AAgAKtAAIA2AAQAQAAAJgHQALgJAAgOQAAgLgJgIQgKgHgRAAIg2AAgAJaBUIAAiFIhnCFIgPAAIAAiYIAPAAIAACEIBniEIAPAAIAACYgAkBBUIAAiMIg6AAIAAgMICCAAIAAAMIg6AAIAACMgArUBUIAAjDIhJAAIAAgPICiAAIAAAPIhKAAIAADDgAirADIAAgQIBQAAIAAAQgAIMhnQgLgKgDgPIANgCQAFAVAXAAQAXAAAFgVIAMACQgDAPgKAKQgMAKgPgBQgPABgMgKg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1_1, new cjs.Rectangle(-79.8,-13.1,159.7,26.3), null);


(lib.logo_w = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhgBhIgfgfIhmAAQgXAAgQgDQgWgFgLgMQgRgQAAgdIAAhZQABgGADgCQAEgEAHAAIBwAAQAYAAARAEQATAEAMALQARARAAAfIAABUIAaAcQADADAAAFQAAAFgFAFQgEADgFAAIgCABQgEAAgDgEgAkiABQABAVAKAJIADACQALAJAVAAIByAAIAAhMQAAgUgLgMIgCgCQgLgIgXAAIhxAAgAD9BBIAAABQgfgBgOgKQgMgHgCgMIAAgDQAAgGAEgDQADgCAHAAQAFAAADABQADADABAEIACADQADAEAIADIATADIA9AAQAhAAAJgGQAJgEAAgQIAAgBQAAgMgGgEQgHgGgXAAIhQAAQgdAAgLgKQgMgKgBgXIAAgKQAAgVAPgJQATgLAtAAIAsAAQAlAAAPAJQALAHADAOIAAACQAAAHgDACQgEAFgGAAQgGAAgDgEQgDgCgBgEIgCgCQgFgIgJgBQgIgCgUAAIguAAQgcAAgIAEQgJAEAAAPIAAAFQAAAKAGAFQAHAFATAAIBEAAQAjAAAOAHQAUAKAAAeQAAAggbAKQgOAGghAAgAmDA/QgEgFAAgHIAAiKQAAgGAEgDQAEgEAGAAQAGAAAFAEQADADAAAGIAACKQAAAHgDAFQgFADgGAAQgGAAgEgDgAAcBBQgpAAgTgLQgcgPAAgnIAAgiQAAgoAcgPQATgLApAAIAlAAQApAAATALQAdAPAAAoIAAAiQAAAngdAPQgTALgpAAgAgThFQgOAKABAaIAAAgQgBAYAOALQAMAJAZAAIA3AAQAaAAANgJQANgLAAgYIAAggQAAgagNgKQgNgIgaAAIg3AAQgZAAgMAIg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.logo_w, new cjs.Rectangle(-39.2,-10,78.4,20.1), null);


(lib.logo_b = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#404041").s().p("AhgBhIgfgfIhmAAQgXAAgQgDQgWgFgLgMQgRgQAAgdIAAhZQABgGADgCQAEgEAHAAIBwAAQAYAAARAEQATAEAMALQARARAAAfIAABUIAaAcQADADAAAFQAAAFgFAFQgEADgFAAIgCABQgEAAgDgEgAkiABQABAVAKAJIADACQALAJAVAAIByAAIAAhMQAAgUgLgMIgCgCQgLgIgXAAIhxAAgAD9BBIAAABQgfgBgOgKQgMgHgCgMIAAgDQAAgGAEgDQADgCAHAAQAFAAADABQADADABAEIACADQADAEAIADIATADIA9AAQAhAAAJgGQAJgEAAgQIAAgBQAAgMgGgEQgHgGgXAAIhQAAQgdAAgLgKQgMgKgBgXIAAgKQAAgVAPgJQATgLAtAAIAsAAQAlAAAPAJQALAHADAOIAAACQAAAHgDACQgEAFgGAAQgGAAgDgEQgDgCgBgEIgCgCQgFgIgJgBQgIgCgUAAIguAAQgcAAgIAEQgJAEAAAPIAAAFQAAAKAGAFQAHAFATAAIBEAAQAjAAAOAHQAUAKAAAeQAAAggbAKQgOAGghAAgAmDA/QgEgFAAgHIAAiKQAAgGAEgDQAEgEAGAAQAGAAAFAEQADADAAAGIAACKQAAAHgDAFQgFADgGAAQgGAAgEgDgAAcBBQgpAAgTgLQgcgPAAgnIAAgiQAAgoAcgPQATgLApAAIAlAAQApAAATALQAdAPAAAoIAAAiQAAAngdAPQgTALgpAAgAgThFQgOAKABAaIAAAgQgBAYAOALQAMAJAZAAIA3AAQAaAAANgJQANgLAAgYIAAggQAAgagNgKQgNgIgaAAIg3AAQgZAAgMAIg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.logo_b, new cjs.Rectangle(-39.2,-10,78.4,20.1), null);


(lib.dev2_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.dev2();
	this.instance.parent = this;
	this.instance.setTransform(-350,-395);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.dev2_1, new cjs.Rectangle(-350,-395,700,790), null);


(lib.dev1_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(104,97,93,0.749)").s().p("AgOBNQgEgHgCgIQgDgNAAgPQgBgNAGgHQAHgIALABQANAAAEAJQABADAAAHIAAAZQAAAOgCAHQgGANgKAAQgIAAgGgIgAgFgKQgLgFgEgVIgEgQQgDgOACgGQACgFAEgEQAEgDAFAAQAEABAHAGIAKAGQAIAFADAGQACAFABAIQAEASgIAJQgCAFgJAEQgFACgFAAIgFgBg");
	this.shape.setTransform(-35.1,7.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(104,97,93,0.749)").s().p("AgFAkQgLgEgEgVIgEgPQgDgOACgHQACgFAEgDQAEgEAFABQAEAAAHAGIAKAHQAIAFADAGQACAEABAIQAEARgIAKQgCAEgJAEQgFACgFAAIgFgBg");
	this.shape_1.setTransform(-35.1,2.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},1).to({state:[]},10).wait(1));

	// Слой_1
	this.instance = new lib.dev1();
	this.instance.parent = this;
	this.instance.setTransform(-285,-195);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(12));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-285,-195,570,390);


(lib.btn_w = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_4
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhgAqQgRgRAAgZQAAgXARgSQARgRAZAAQAaAAAQARQAQASAAAXQAAAZgQARQgQARgaAAQgZAAgRgRgAhWghQgNAPAAASQAAAUANANQAMAOAUABQAUAAANgOQAMgPAAgTQAAgSgNgOQgMgOgUgBQgTAAgNAOgAnxApIAIgJQARARAXAAQAMgBAHgGQAIgGAAgKQAAgKgJgGQgIgFgOAAIgNAAIAAgKIANAAQANAAAHgGQAIgFAAgLQAAgIgHgGQgIgGgLAAQgTAAgPANIgIgJQAKgIAJgEQALgDAMAAQARgBALAKQALAIAAANQAAAUgVAHQALADAHAHQAGAIAAAKQAAAOgLAJQgLAJgSAAQgcAAgUgSgAHmA6IAAhfIhFBfIgNAAIAAhzIANAAIAABfIBFhfIAMAAIAABzgAFBA6IAAhnIgmAAIAAgMIBaAAIAAAMIgnAAIAABngADvA6IAAhfIhFBfIgMAAIAAhzIANAAIAABfIBEhfIANAAIAABzgAAiA6IAAhzIAxAAQAUAAALAKQAHAJAAAKQAAATgSAIQAYAGAAAVQAAAPgLAIQgMAJgSAAgAAvAuIAnAAQANAAAIgGQAHgGAAgJQAAgKgIgEQgIgGgOAAIglAAgAAvgFIAiAAQANAAAHgGQAHgFAAgKQAAgJgHgFQgHgFgMAAIgjAAgAiZA6IAAhcIgqA8IgBAAIgqg8IAABcIgNAAIAAhzIAOAAIApA+IAqg+IAOAAIAABzgAkjA6IgNgfIg/AAIgNAfIgOAAIA1h0IAMAAIA0B0gAk1APIgag5IgbA5IA1AAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Слой_5
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(255,255,255,0.22)").s().p("AqjCtIAAlZIVHAAIAAFZg");

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.btn_w, new cjs.Rectangle(-67.6,-17.2,135.2,34.5), null);


(lib.btn_b = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_4
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#404040").s().p("AhgAqQgRgRAAgZQAAgXARgSQARgRAZAAQAaAAAQARQAQASAAAXQAAAZgQARQgQARgaAAQgZAAgRgRgAhWghQgNAPAAASQAAAUANANQAMAOAUABQAUAAANgOQAMgPAAgTQAAgSgNgOQgMgOgUgBQgTAAgNAOgAnxApIAIgJQARARAXAAQAMgBAHgGQAIgGAAgKQAAgKgJgGQgIgFgOAAIgNAAIAAgKIANAAQANAAAHgGQAIgFAAgLQAAgIgHgGQgIgGgLAAQgTAAgPANIgIgJQAKgIAJgEQALgDAMAAQARgBALAKQALAIAAANQAAAUgVAHQALADAHAHQAGAIAAAKQAAAOgLAJQgLAJgSAAQgcAAgUgSgAHmA6IAAhfIhFBfIgNAAIAAhzIANAAIAABfIBFhfIAMAAIAABzgAFBA6IAAhnIgmAAIAAgMIBaAAIAAAMIgnAAIAABngADvA6IAAhfIhFBfIgMAAIAAhzIANAAIAABfIBEhfIANAAIAABzgAAiA6IAAhzIAxAAQAUAAALAKQAHAJAAAKQAAATgSAIQAYAGAAAVQAAAPgLAIQgMAJgSAAgAAvAuIAnAAQANAAAIgGQAHgGAAgJQAAgKgIgEQgIgGgOAAIglAAgAAvgFIAiAAQANAAAHgGQAHgFAAgKQAAgJgHgFQgHgFgMAAIgjAAgAiZA6IAAhcIgqA8IgBAAIgqg8IAABcIgNAAIAAhzIAOAAIApA+IAqg+IAOAAIAABzgAkjA6IgNgfIg/AAIgNAfIgOAAIA1h0IAMAAIA0B0gAk1APIgag5IgbA5IA1AAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Слой_5
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(64,64,64,0.22)").s().p("AqjCtIAAlZIVHAAIAAFZg");

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.btn_b, new cjs.Rectangle(-67.6,-17.2,135.2,34.5), null);


(lib.bg2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#D0D0D0","#FFFFFF"],[0,1],0,297,0,-296.9).s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.bg2, new cjs.Rectangle(-150,-300,300,600), null);


(lib.bg1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#18171C","#2E2B34"],[0,1],0,297,0,-296.9).s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.bg1, new cjs.Rectangle(-150,-300,300,600), null);


(lib.banner = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// t2_3
	this.instance = new lib.t2_3();
	this.instance.parent = this;
	this.instance.setTransform(-24.6,-166.6);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(135).to({_off:false},0).to({alpha:1},5).wait(40).to({x:-464.6},15,cjs.Ease.get(-1)).wait(1));

	// t2_2
	this.instance_1 = new lib.t2_2();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-56,-200.7);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(125).to({_off:false},0).to({alpha:1},5).wait(50).to({x:-496},15,cjs.Ease.get(-1)).wait(1));

	// t2_1
	this.instance_2 = new lib.t2_1();
	this.instance_2.parent = this;
	this.instance_2.setTransform(-113.9,-202.8);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(115).to({_off:false},0).to({alpha:1},5).wait(60).to({x:-553.9},15,cjs.Ease.get(-1)).wait(1));

	// btn_b
	this.instance_3 = new lib.btn_b();
	this.instance_3.parent = this;
	this.instance_3.setTransform(-57.9,-119.4);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(145).to({_off:false},0).to({alpha:1},5).wait(10).to({regX:-0.1,scaleX:0.96,scaleY:0.96,x:-58},2).to({regX:0,scaleX:1,scaleY:1,x:-57.9},2).wait(3).to({regX:-0.1,scaleX:0.96,scaleY:0.96,x:-58},2).to({regX:0,scaleX:1,scaleY:1,x:-57.9},2).wait(9).to({x:-497.9},15,cjs.Ease.get(-1)).wait(1));

	// logo_b
	this.instance_4 = new lib.logo_b();
	this.instance_4.parent = this;
	this.instance_4.setTransform(-81.5,-256.9,1.122,1.122);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(85).to({_off:false},0).to({alpha:1},15).wait(80).to({alpha:0},15).wait(1));

	// logo_w
	this.instance_5 = new lib.logo_w();
	this.instance_5.parent = this;
	this.instance_5.setTransform(-81.5,-256.9,1.122,1.122);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).to({_off:true},100).wait(80).to({_off:false},0).wait(16));

	// urText_b
	this.instance_6 = new lib.urText_b();
	this.instance_6.parent = this;
	this.instance_6.setTransform(0.5,269.5);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(85).to({_off:false},0).to({alpha:1},15).wait(80).to({alpha:0},15).wait(1));

	// urText_w
	this.instance_7 = new lib.urText_w();
	this.instance_7.parent = this;
	this.instance_7.setTransform(0.5,269.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).to({_off:true},100).wait(80).to({_off:false},0).wait(16));

	// t1_2
	this.instance_8 = new lib.t1_2();
	this.instance_8.parent = this;
	this.instance_8.setTransform(82.4,-202.9);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(25).to({_off:false},0).to({alpha:1},5).wait(55).to({x:-189.6},15,cjs.Ease.get(-1)).to({_off:true},1).wait(95));

	// t1_1
	this.instance_9 = new lib.t1_1();
	this.instance_9.parent = this;
	this.instance_9.setTransform(-47.7,-200.9);
	this.instance_9.alpha = 0;
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(15).to({_off:false},0).to({alpha:1},5).wait(65).to({x:-319.7},15,cjs.Ease.get(-1)).to({_off:true},1).wait(95));

	// btn_w
	this.instance_10 = new lib.btn_w();
	this.instance_10.parent = this;
	this.instance_10.setTransform(-57.9,-119.4);
	this.instance_10.alpha = 0;
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(35).to({_off:false},0).to({alpha:1},5).wait(24).to({regX:-0.1,scaleX:0.96,scaleY:0.96,x:-58},2).to({regX:0,scaleX:1,scaleY:1,x:-57.9},2).wait(3).to({regX:-0.1,scaleX:0.96,scaleY:0.96,x:-58},2).to({regX:0,scaleX:1,scaleY:1,x:-57.9},2).wait(10).to({x:-329.9},15,cjs.Ease.get(-1)).to({_off:true},1).wait(95));

	// dev2
	this.instance_11 = new lib.dev2_1();
	this.instance_11.parent = this;
	this.instance_11.setTransform(-139.1,369.1,0.2,0.2,0,0,0,0,-0.2);
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(100).to({_off:false},0).to({regY:0,scaleX:1,scaleY:1,x:-37.1,y:-87},15,cjs.Ease.get(1)).wait(65).to({x:-477.1},15,cjs.Ease.get(-1)).wait(1));

	// dev1
	this.instance_12 = new lib.dev1_1("single",0);
	this.instance_12.parent = this;
	this.instance_12.setTransform(435,105);

	this.timeline.addTween(cjs.Tween.get(this.instance_12).to({x:165},15,cjs.Ease.get(1)).to({x:109.3,mode:"synched",loop:false},30).to({x:35,mode:"single",startPosition:11},40).to({x:-435},15,cjs.Ease.get(-1)).to({_off:true},1).wait(95));

	// bg2
	this.instance_13 = new lib.bg2();
	this.instance_13.parent = this;
	this.instance_13.alpha = 0;
	this.instance_13._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(85).to({_off:false},0).to({alpha:1},15).wait(80).to({alpha:0},15).wait(1));

	// bg1
	this.instance_14 = new lib.bg1();
	this.instance_14.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(196));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,-300,870,600);


// stage content:
(lib._300x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// cover
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#666666").ss(2,1,1).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// banner
	this.instance = new lib.banner();
	this.instance.parent = this;
	this.instance.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(149,299,871,602);
// library properties:
lib.properties = {
	id: 'BC42C47B6414420FAD25D220DE088B52',
	width: 300,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/dev1.png", id:"dev1"},
		{src:"images/dev2.png", id:"dev2"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['BC42C47B6414420FAD25D220DE088B52'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;