(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 300,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	manifest: [
		{src:"images/bgImg1.jpg", id:"bgImg1"},
		{src:"images/bgImg2.jpg", id:"bgImg2"},
		{src:"images/bgImg3.jpg", id:"bgImg3"},
		{src:"images/car1.png", id:"car1"},
		{src:"images/car2.png", id:"car2"},
		{src:"images/elf.png", id:"elf"},
		{src:"images/logo.png", id:"logo"},
		{src:"images/wheel.png", id:"wheel"}
	]
};



// symbols:



(lib.bgImg1 = function() {
	this.initialize(img.bgImg1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,418,322);


(lib.bgImg2 = function() {
	this.initialize(img.bgImg2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,360,320);


(lib.bgImg3 = function() {
	this.initialize(img.bgImg3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.car1 = function() {
	this.initialize(img.car1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,336);


(lib.car2 = function() {
	this.initialize(img.car2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,338);


(lib.elf = function() {
	this.initialize(img.elf);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,37,20);


(lib.logo = function() {
	this.initialize(img.logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,42,52);


(lib.wheel = function() {
	this.initialize(img.wheel);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,35,35);


(lib.wheelMc = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.wheel();
	this.instance.setTransform(-17.5,-17.5);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-17.5,-17.5,35,35);


(lib.t4_3 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("AgrBRIAAhuIgBgDIgGgCIACgIIASAAQAAAAABABQAAAAAAAAQABAAAAABQAAAAAAAAIAAAHQAIgLAUAAQATAAAJALQAJALAAAWQAAAYgJALQgJALgTAAQgSAAgKgKIAAAtgAgWgaQgGAGAAANIAAAiQAKAIAPAAQAMAAAHgIQAGgJAAgSQAAgQgGgIQgHgIgMAAQgOAAgFAGgAkKBRQgBAAAAAAQAAAAAAAAQgBAAAAgBQAAAAAAAAIAAgiQgagBgMgLQgMgLAAgXQAAgVAMgLQAMgKAagCIAAgZQAAAAAAAAQAAgBAAAAQAAAAgBAAQAAgBAAAAIgGgCIACgHIAQAAQABAAAAAAQABAAAAAAQAAAAAAAAQAAABAAAAIAAAjQAaACAMAKQAMALAAAVQAAAXgMALQgMALgaABIAAAXQAAAAAAABQAAAAABABQAAAAAAAAQAAAAABAAIAFADIgBAHgAj/AjQATgBAIgIQAJgJAAgRQAAgPgJgIQgIgIgTgBgAkngXQgJAHAAAQQAAARAJAJQAIAIATABIAAhDQgTABgIAIgACFBGIAAgaIhLAAIAAAaIgOAAIAAglIAJAAQAHgFAEgKQADgKAAgTIAAgSIgCgDIgFgCIABgIIBHAAIAABLIAOAAIAAAlgABQgKQAAAggKALIAwAAIAAg/IgmAAgAiLAjQgLgLAAgYQAAgWALgLQAKgLAWAAQAXAAAKALQAKALAAAWQAAAYgKALQgKALgXAAQgWAAgKgLgAiAgYQgHAIAAAQQAAASAHAJQAGAIAPAAQAPAAAHgIQAHgJAAgSQAAgQgHgIQgHgIgPAAQgPAAgGAIgAErAkQAAgKAKABQAKgBAAAKQAAAJgKAAQgKAAAAgJgADOAsIAAhJQAAgBAAAAQAAgBgBAAQAAAAAAAAQAAgBgBAAIgFgCIABgIIAxAAQAbAAAAAZQAAAOgMADQAPACAAARQAAAOgHAFQgHAGgOAAgADbAiIAcAAQASAAAAgPQAAgOgSAAIgcAAgADbgEIAbAAQAQAAAAgNQAAgOgQAAIgbAAgAClAsIAAhJQAAgBAAAAQAAgBAAAAQAAAAgBAAQAAgBAAAAIgFgCIABgIIASAAQABAAAAABQAAAAAAAAQABAAAAABQAAAAAAAAIAABUgAi5AsIAAhJQAAgBAAAAQAAgBAAAAQAAAAgBAAQAAgBAAAAIgGgCIACgIIASAAQABAAAAABQAAAAAAAAQABAAAAABQAAAAAAAAIAABUgAEvAIIgBhTIAOAAIAABTgACjhEQAAgKAJAAQAKAAAAAKQAAAJgKAAQgJAAAAgJgAi7hEQAAgKAJAAQAKAAAAAKQAAAJgKAAQgJAAAAgJg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-31.9,-8.2,63.9,16.4);


(lib.t4_2 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("AiuBQIAAhvIgBgDIgGgBIACgIIASAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIAAAHQAJgLAUAAQAUAAAJALQAJAKAAAYQAAAXgJALQgJALgUAAQgSgBgLgJIAAAtgAiagbQgGAFAAAOIAAAhQALAIAPAAQAOAAAGgIQAHgIAAgRQAAgRgHgJQgGgIgOAAQgOAAgGAHgAIRAiQgKgLAAgXQAAgYAKgKQAKgLAXAAQAXAAAKALQAKAKAAAYQAAAXgKALQgKALgXAAQgXAAgKgLgAIcgaQgGAJAAARQAAARAGAIQAHAIAPAAQAPAAAHgIQAGgIAAgRQAAgRgGgJQgHgIgPAAQgPAAgHAIgAENAiQgKgLAAgXQAAgYAKgKQAKgLAXAAQAQAAAKADIgCAMQgIgDgOgBQgQAAgHAIQgHAJAAARQAAARAHAIQAHAIAQAAQANAAALgEIAAAMQgLADgPABQgXAAgKgLgAhDAiQgLgLAAgXQAAgYALgKQAKgLAXAAQAWAAALALQAIAKAAAYQAAAXgIALQgLALgWAAQgXAAgKgLgAg4gaQgHAJAAARQAAARAHAIQAGAIAQAAQAPAAAGgIQAHgIAAgRQAAgRgHgJQgGgIgPAAQgQAAgGAIgAkPAiQgKgLAAgXQAAgYAKgKQAKgLAXAAQAXAAAKALQAKAKAAAYQAAAXgKALQgKALgXAAQgXAAgKgLgAkEgaQgGAJAAARQAAARAGAIQAHAIAPAAQAPAAAHgIQAGgIAAgRQAAgRgGgJQgHgIgPAAQgPAAgHAIgAnzATQAAgYAjAAQAPAAAKAEIAAgMQAAgLgGgFQgGgFgOAAQgNAAgOAFIAAgMQAPgEAOAAQAUAAAJAIQAJAHAAASIAAAqQAAABAAAAQAAAAABABQAAAAAAAAQAAABABAAIAFACIgBAIIgPAAQgBAAAAgBQAAAAAAAAQgBAAAAAAQAAgBAAAAIgBgHQgIALgVAAQghAAAAgagAnlASQAAAQAWAAQAYAAAAgTIAAgIQgKgEgNAAQgXAAAAAPgAAOAsIAAgMIADAAQALAAAEgLQAFgLAAgXIAAgSQAAAAAAgBQAAAAgBAAQAAgBAAAAQAAAAgBgBIgFgBIABgIIBIAAIAABWIgOAAIAAhLIgmAAIAAAVQAAAcgIANQgIAOgRAAgAGuArIAAhKQAAAAAAgBQAAAAAAAAQAAgBgBAAQAAAAAAgBIgGgBIACgIIAwAAQAbAAAAAYQAAAOgLAEQAOACAAARQAAANgHAGQgGAFgPABgAG8AgIAcAAQARAAAAgPQAAgOgRAAIgcAAgAG8gFIAaAAQAQAAAAgOQAAgHgDgDQgEgEgJAAIgaAAgAFxArIAAhLIgeAAIAAgLIBKAAIAAALIgeAAIAABLgACqArIAAhKQAAAAAAgBQAAAAAAAAQAAgBgBAAQAAAAAAgBIgGgBIACgIIAwAAQAbAAAAAYQAAAOgLAEQAOACAAARQAAANgHAGQgGAFgPABgAC4AgIAcAAQAJAAAEgEQAEgCAAgJQAAgIgEgCQgEgEgJAAIgcAAgAC4gFIAaAAQAQAAAAgOQAAgHgDgDQgEgEgJAAIgaAAgACCArIAAhKQAAAAAAgBQAAAAgBAAQAAgBAAAAQAAAAgBgBIgFgBIABgIIATAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIAABUgAkwArIgggmIgJAIIAAAeIgNAAIAAhKIgCgDIgFgBIABgIIASAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIAAAnIAogpIARAAIgnApIAoAtgAoWArIAAgoIgwAAIAAAoIgPAAIAAhKQAAAAAAgBQAAAAAAAAQAAgBgBAAQAAAAAAgBIgGgBIACgIIASAAQAAAAABAAQAAAAAAABQAAAAABAAQAAABAAAAIAAAjIAwAAIAAglIAOAAIAABWgAB/hGQAAgJAKAAQAJAAAAAJQAAAKgJgBQgKABAAgKg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-60.5,-8,121.1,16.1);


(lib.t4_1 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("ACPBPIAAgLIAEAAQAJAAAFgDQAEgEAEgLIADgJIglhWIAPAAIAdBEIAZhEIAPAAIglBhQgGAQgHAGQgHAGgNAAgADsBOIAAhvIgCgDIgFgCIACgHIASAAQAAAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAHQAIgLAVAAQAUAAAJALQAJAKAAAYQAAAXgJAKQgJALgUAAQgSAAgLgJIAAAtgAEAgeQgGAGAAANIAAAiQAKAIAQAAQAOAAAGgIQAGgIABgRQgBgSgGgIQgGgIgOAAQgOAAgGAGgAi6BOIAAhvQAAgBAAAAQAAAAAAgBQgBAAAAAAQAAgBgBAAIgFgCIACgHIASAAQAAAAAAAAQABAAAAAAQAAABAAAAQABAAAAABIAAAHQAHgLAVAAQAVAAAIALQAKAKgBAYQABAXgKAKQgIALgVAAQgSAAgKgJIAAAtgAimgeQgFAGAAANIAAAiQAKAIAPAAQAOAAAHgIQAFgIABgRQgBgSgFgIQgHgIgOAAQgOAAgGAGgAFXAfQgKgKgBgXQABgYAKgKQAKgLAXAAQAOAAAMADIgDAMQgIgEgOAAQgQAAgHAIQgHAIAAASQAAARAHAIQAHAIAQAAQANAAALgEIAAAMQgLADgOAAQgXAAgKgLgAkTAfQgLgKAAgXQAAgYAKgKQAJgLAXAAQATAAAKAKQAJALAAAXIgBAEIhAAAQAAAQAIAHQAIAHARAAQAOAAAOgEIAAALQgMAEgRAAQgZAAgLgLgAjdgHQAAgQgFgHQgGgHgMAAQgOAAgHAHQgGAHAAAQIAyAAIAAAAgABwAoIgggmIgJAJIAAAdIgOAAIAAhJQAAgBAAAAQAAAAAAgBQgBAAAAAAQAAgBgBAAIgEgCIABgHIASAAQAAAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAnIAngpIARAAIgmAoIAoAtgAgUAoIAAhCIgyBCIgOAAIAAhJQAAgBAAAAQAAAAAAgBQgBAAAAAAQAAgBgBAAIgEgCIABgHIARAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAABIAABAIAxhCIAPAAIAABVgAmKAoIAAhrQAAgBAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIgGgCIABgHIBZAAIAAAMIhEAAIAAAoIAlAAQAVAAAJAIQAKAIgBAQQABATgKAIQgJAIgVAAgAl7AdIAkAAQANAAAHgFQAGgGAAgNQAAgKgGgFQgHgGgNAAIgkAAg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-40.2,-8,80.5,16.1);


(lib.t3_3 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("AASBQIAAhvIgBgDIgGgBIACgIIASAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIAAAHQAJgLAUAAQAUAAAJALQAJAKAAAYQAAAXgJALQgJALgUAAQgSgBgLgJIAAAtgAAmgbQgGAFAAAOIAAAhQALAIAPAAQAOAAAHgIQAGgIAAgRQAAgRgGgJQgHgIgOAAQgOAAgGAHgAmABFIAAgaIhLAAIAAAaIgNAAIAAglIAIAAQAIgFADgKQADgLAAgTIAAgSIgBgDIgGgBIACgIIBGAAIAABLIAOAAIAAAlgAm0gLQAAAggKALIAvAAIAAhAIglAAgADcAiQgLgLAAgXQAAgYAKgKQAJgLAWAAQAUAAAJAKQAJALAAAYIAAADIhBAAQABAQAHAIQAIAHASAAQAOgBAOgEIAAAMQgMADgRABQgZAAgLgLgAESgFQAAgQgFgHQgGgGgNgBQgOAAgGAIQgGAGgBAQIAzAAIAAAAgAhNAiQgKgLAAgXQAAgYAKgKQAKgLAXAAQAXAAAKALQAKAKAAAYQAAAXgKALQgKALgXAAQgXAAgKgLgAhBgaQgHAJAAARQAAARAHAIQAGAIAPAAQAPAAAHgIQAGgIAAgRQAAgRgGgJQgHgIgPAAQgPAAgGAIgAlfAiQgLgLAAgXQAAgYALgKQAKgLAWAAQAXAAAKALQALAKAAAYQAAAXgLALQgKALgXAAQgWAAgKgLgAlUgaQgHAJAAARQAAARAHAIQAGAIAPAAQAPAAAHgIQAHgIAAgRQAAgRgHgJQgHgIgPAAQgPAAgGAIgAG5ArIAAhKQAAAAAAgBQAAAAgBAAQAAgBAAAAQAAAAgBgBIgFgBIABgIIASAAQABAAAAAAQAAAAABABQAAAAAAAAQAAABAAAAIAABUgAGBArIAAhKQAAAAAAgBQAAAAgBAAQAAgBAAAAQAAAAgBgBIgFgBIACgIIASAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIAABUgAE1ArIAAhKQAAAAAAgBQAAAAgBAAQAAgBAAAAQAAAAgBgBIgFgBIABgIIBAAAIAAALIgsAAIAABLgAB4ArIAAhKQAAAAAAgBQAAAAAAAAQAAgBgBAAQAAAAAAgBIgGgBIACgIIAxAAQAaAAAAAYQAAAOgLAEQAOACAAARQAAANgGAGQgHAFgPABgACGAgIAcAAQAJAAAEgEQAEgCAAgJQAAgIgEgCQgEgEgJAAIgcAAgACGgFIAaAAQAQAAAAgOQAAgOgQAAIgaAAgAh8ArIAAg2IhJAAIAAA2IgPAAIAAhsQAAAAAAgBQAAAAgBAAQAAgBAAAAQAAAAgBgBIgFgCIABgHIATAAQABAAAAABQAAAAAAAAQABAAAAABQAAAAAAABIAAAzIBJAAIAAg2IAOAAIAAB4gAF+hGQAAgJAKAAQAJAAAAAJQAAAKgJgBQgKABAAgKgAHHhGQAAgJAJAAQAJAAAAAJQAAAJgJAAQgJAAAAgJgAGjhGQAAgJAJAAQAJAAAAAJQAAAJgJAAQgJAAAAgJg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-47.4,-8,94.8,16.1);


(lib.t3_2 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("AAyA/IAAhvQAAAAAAgBQAAAAgBAAQAAgBAAAAQAAAAgBgBIgFgCIABgHIATAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIAAAHQAJgLAUAAQAUAAAJALQAJAKAAAYQAAAXgJALQgJALgUgBQgSAAgLgJIAAAtgABGgsQgGAFAAANIAAAiQAKAIAQAAQAOAAAGgIQAGgIAAgRQAAgRgGgJQgGgHgOgBQgOAAgGAHgAhOA0IAAgaIhLAAIAAAaIgNAAIAAglIAJAAQAHgFADgKQADgJAAgUIAAgTQAAAAAAgBQAAAAAAAAQAAgBgBAAQAAAAAAgBIgFgCIABgHIBHAAIAABLIAOAAIAAAlgAiCgcQAAAggKALIAwAAIAAhAIgmAAgACdARQgLgLAAgXQAAgYALgKQAKgLAWAAQAXAAAKALQAKAKAAAYQAAAXgKALQgKALgXgBQgWABgKgLgACogrQgHAJAAARQAAARAHAIQAGAIAPAAQAPAAAHgIQAHgIAAgRQAAgRgHgJQgHgHgPgBQgPABgGAHgAgtARQgKgLAAgXQAAgYAKgKQAKgLAXAAQAVAAAKALQAKAKAAAYQAAAXgKALQgKALgVgBQgXABgKgLgAgigrQgHAJAAARQAAARAHAIQAHAIAPAAQANAAAHgIQAGgIAAgRQAAgRgGgJQgHgHgNgBQgPABgHAHgAj5ARQgLgLAAgXQAAgYALgKQAKgLAWAAQAXAAAKALQAKAKAAAYQAAAXgKALQgKALgXgBQgWABgKgLgAjugrQgHAJAAARQAAARAHAIQAGAIAPAAQAPAAAHgIQAHgIAAgRQAAgRgHgJQgHgHgPgBQgPABgGAHgAFcAaIggglIgIAJIAAAcIgNAAIAAgcIgHgJIghAlIgQAAIAngtIgmgpIAQAAIAnApIAAgpIANAAIAAApIAngpIARAAIgnApIAoAtgAkmAaIAAhLIgwAAIAABLIgPAAIAAhKQAAAAAAgBQAAAAAAAAQAAgBgBAAQAAAAAAgBIgGgCIACgHIBSAAIAABWg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-36.5,-6.3,73.1,12.7);


(lib.t3_1 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("AAOBRIAAhuIgCgDIgFgCIABgIIATAAQAAAAAAABQABAAAAAAQAAAAAAABQAAAAAAAAIAAAHQAIgLAVAAQAUAAAJALQAJALAAAWQAAAYgJALQgJALgUAAQgSAAgLgKIAAAtgAAjgaQgHAGAAANIAAAiQAKAIAQAAQAOAAAGgIQAHgJgBgSQABgQgHgIQgGgIgOAAQgOAAgFAGgAEsAUQABgXAiAAQAQAAAKADIAAgLQAAgMgGgEQgGgGgOAAQgNABgOAEIAAgMQAPgEAOAAQAVABAIAHQAJAIAAASIAAAqIACADIAFABIgCAIIgOAAQgBAAAAAAQAAAAgBAAQAAgBAAAAQAAAAAAAAIgBgIQgIALgWAAQggAAgBgagAE7AUQAAAPAVAAQAZAAAAgSIAAgJQgLgDgMAAQgYAAABAPgABuAUQAAgXAkAAQAPAAAKADIAAgLQABgMgHgEQgGgGgOAAQgNABgOAEIAAgMQAPgEAOAAQAUABAKAHQAIAIABASIAAAqQAAAAAAAAQAAABAAAAQAAABAAAAQABAAAAABIAFABIgBAIIgPAAQAAAAgBAAQAAAAAAAAQAAgBgBAAQAAAAAAAAIgBgIQgHALgWAAQgiAAAAgagAB9AUQAAAPAVAAQAZAAAAgSIAAgJQgLgDgMAAQgXAAAAAPgAmNAUQgBgXAkAAQAPAAAKADIAAgLQAAgMgFgEQgHgGgNAAQgOABgNAEIAAgMQAOgEAOAAQAUABAJAHQAKAIgBASIAAAqIABADIAGABIgBAIIgPAAIgCgBIAAgIQgJALgVAAQgiAAABgagAl/AUQAAAPAWAAQAZAAgBgSIAAgJQgKgDgNAAQgXAAAAAPgAHRAsIAAhCIgyBCIgOAAIAAhJIgBgDIgFgCIABgIIARAAQAAAAABABQAAAAAAAAQAAAAAAABQAAAAAAAAIAABBIAyhDIAOAAIAABWgADUAsIAAhJQAAgBgBAAQAAgBAAAAQAAAAAAAAQgBgBAAAAIgFgCIABgIIAwAAQAbAAAAAZQAAAOgLADQAOACAAARQAAAOgGAFQgHAGgPAAgADhAiIAcAAQAJgBAEgDQAEgDAAgIQAAgIgEgDQgEgDgJAAIgcAAgADhgEIAaAAQAQAAABgNQgBgIgDgDQgEgDgJAAIgaAAgAg8AsIAAhJQAAgBAAAAQAAgBAAAAQAAAAAAAAQgBgBAAAAIgFgCIABgIIBAAAIAAAMIgsAAIAABKgAhiAsIAAhCIgyBCIgOAAIAAhJQAAgBAAAAQAAgBAAAAQgBAAAAAAQAAgBAAAAIgGgCIABgIIARAAQABAAAAABQABAAAAAAQAAAAAAABQAAAAAAAAIAABBIAyhDIANAAIAABWgAkBAsIAAhJIgBgDIgFgCIACgIIAwAAQAbAAgBAZQAAAOgLADQAOACAAARQABAOgHAFQgHAGgPAAgAjzAiIAcAAQARAAABgPQgBgOgRAAIgcAAgAjzgEIAbAAQAPAAABgNQgBgOgPAAIgbAAgAm/AsIAAhKIgeAAIAAgMIBKAAIAAAMIgdAAIAABKgAGchQIAKAAQABAQARAAQAQAAABgQIAKAAQAAAagbAAQgcAAAAgag");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-47.8,-8.2,95.7,16.4);


(lib.t2_3 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("AD+AjIAAgtQAAgBAAAAQgBgBAAAAQAAAAAAAAQgBgBAAAAIgLgDIACgIIALAAIAAgaIAOAAIAAAaIAeAAIAAAMIgeAAIAAAvQAAARARAAQAHAAAGgBIAAALQgHACgIAAQgdAAAAgdgAB2A3QgJgIAAgTIAAgoQAAAAAAAAQAAgBAAAAQAAAAgBAAQAAAAAAAAIgGgDIACgIIASAAQAAAAABAAQAAABAAAAQABAAAAAAQAAABAAAAIAAAxQAAAOAFAGQAGAFAMAAQANAAAGgFQAFgGAAgOIAAgzIAPAAIAAA0QAAATgJAIQgJAJgVAAQgUAAgJgJgAAJAmQAAgZAjAAQAPAAALADIAAgMQAAgJgHgFQgGgFgOAAQgNAAgOAFIAAgMQAPgEAOAAQAVAAAIAIQAJAIAAAPIAAAsIACADIAFACIgBAIIgPAAQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAgHQgIALgWAAQghAAAAgagAAXAmQAAAPAWAAQAZAAAAgTIAAgIQgLgEgNAAQgXAAAAAQgAivA1QgLgLAAgYQAAgWAKgLQAJgLAWAAQAUAAAJALQAJAKAAAWIAAAFIhBAAQABAQAHAIQAIAHASAAQAOAAAOgFIAAAMQgMAEgRAAQgZAAgLgLgAh5AMQAAgOgGgHQgFgGgNAAQgOAAgGAHQgHAHAAANIAzAAIAAAAgADUA+QgBAAAAAAQAAAAAAgBQgBAAAAAAQAAgBAAAAIAAhvQAAAAAAgBQAAAAAAAAQAAgBgBAAQAAAAAAAAIgGgDIACgHIASAAQABAAAAAAQAAAAAAABQABAAAAAAQAAAAAAABIAABuQAAABAAAAQAAABAAAAQAAAAABABQAAAAAAAAIAGACIgCAIgAgXA+QAAAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAIAAg1QAAgKgFgGQgGgFgLAAQgQAAgKAGIAABGIgOAAIAAhKIgCgCIgFgCIABgIIASAAQABAAAAAAQAAABAAAAQABAAAAAAQAAABAAAAIAAAGQALgKARAAQASAAAIAIQAIAIAAARIAAAqQAAABAAAAQAAABABAAQAAAAAAABQAAAAABAAIAFACIgBAIgAjVA+IgfgyIgfAAIAAAyIgPAAIAAhsQAAAAAAAAQAAgBAAAAQAAAAgBgBQAAAAAAAAIgGgDIACgGIA2AAQAWAAAKAIQAJAJAAATQAAAcgdAEIAgAzgAkTABIAhAAQAPAAAGgEQAHgFAAgNQAAgNgHgGQgGgGgPAAIghAAg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-29.8,-6.4,59.7,12.9);


(lib.t2_2 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("AAcBQIAAhvIgBgDIgGgBIACgIIASAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIAAAHQAJgLAUAAQAUAAAJALQAJAKAAAYQAAAXgJALQgJALgUAAQgSgBgLgJIAAAtgAAwgbQgGAFAAAOIAAAhQALAIAPAAQAOAAAGgIQAHgIAAgRQAAgRgHgJQgGgIgOAAQgOAAgGAHgAFYATQAAgYAjAAQAPAAALAEIAAgMQAAgLgGgFQgGgFgOAAQgOAAgNAFIAAgMQAOgEAOAAQAVAAAJAIQAJAHAAASIAAAqIABADIAFACIgBAIIgPAAQAAAAAAgBQgBAAAAAAQAAAAAAAAQgBgBAAAAIAAgHQgIALgWAAQghAAAAgagAFmASQAAAQAWAAQAZAAAAgTIAAgIQgLgEgNAAQgXAAAAAPgAEPAiQgLgLAAgXQAAgYALgKQAKgLAWAAQAPAAAMADIgDAMQgIgDgOgBQgQAAgHAIQgHAJAAARQAAARAHAIQAHAIAQAAQAOAAAKgEIAAAMQgLADgPABQgWAAgKgLgAg7AiQgLgLAAgXQAAgYAKgKQAKgLAWAAQAUAAAIAKQAHALAAAYIAAADIg/AAQABAQAIAIQAIAHARAAQAOgBAMgEIAAAMQgKADgRABQgZAAgLgLgAgEgFQgBgQgFgHQgGgGgMgBQgOAAgHAIQgGAGgBAQIA0AAIAAAAgAiKAiQgLgLAAgXQAAgYALgKQAKgLAXAAQAPAAALADIgCAMQgJgDgNgBQgRAAgHAIQgHAJAAARQAAARAHAIQAHAIARAAQANAAAKgEIAAAMQgKADgPABQgXAAgKgLgAjvAiQgLgLAAgXQAAgYALgKQAKgLAWAAQAXAAAKALQAKAKAAAYQAAAXgKALQgKALgXAAQgWAAgKgLgAjkgaQgHAJAAARQAAARAHAIQAGAIAPAAQAPAAAHgIQAHgIAAgRQAAgRgHgJQgHgIgPAAQgPAAgGAIgAoDATQAAgYAjAAQAPAAALAEIAAgMQAAgLgGgFQgGgFgOAAQgOAAgNAFIAAgMQAOgEAOAAQAVAAAJAIQAJAHAAASIAAAqQAAABAAAAQAAAAAAABQAAAAABAAQAAABAAAAIAFACIgBAIIgPAAQAAAAAAgBQgBAAAAAAQAAAAAAAAQgBgBAAAAIAAgHQgIALgWAAQghAAAAgagAn1ASQAAAQAWAAQAZAAAAgTIAAgIQgLgEgNAAQgXAAAAAPgAH1ArIgZgkIgZAkIgPAAIAggrIgfgrIAQAAIAXAiIAYgiIAPAAIgeArIAfArgADhArIAAhKQAAAAAAgBQAAAAAAAAQAAgBgBAAQAAAAAAgBIgFgBIABgIIASAAQABAAAAAAQAAAAAAABQABAAAAAAQAAABAAAAIAABUgACCArIAAhKQAAAAAAgBQAAAAAAAAQAAgBgBAAQAAAAAAgBIgGgBIACgIIAwAAQAbAAAAAYQAAAOgLAEQAOACAAARQAAANgHAGQgGAFgPABgACQAgIAcAAQAJAAAEgEQAEgCAAgJQAAgIgEgCQgEgEgJAAIgcAAgACQgFIAaAAQAQAAAAgOQAAgOgQAAIgaAAgAkuArIAAhLIgeAAIAAgLIBLAAIAAALIgeAAIAABLgAmeArIAAhKQAAAAAAgBQAAAAgBAAQAAgBAAAAQAAAAgBgBIgFgBIABgIIAxAAQAbAAAAAYQAAAOgMAEQAOACAAARQAAANgGAGQgHAFgPABgAmRAgIAcAAQAKAAADgEQAEgCAAgJQAAgIgEgCQgDgEgKAAIgcAAgAmRgFIAbAAQAQAAAAgOQAAgHgEgDQgEgEgIAAIgbAAgADfhGQAAgJAJAAQAKAAAAAJQAAAKgKgBQgJABAAgKg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-51.7,-8,103.4,16.1);


(lib.t2_1 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("Ai1BRQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAgiQgagBgMgLQgMgLAAgXQAAgVAMgLQAMgKAagCIAAgZQAAAAAAAAQAAgBgBAAQAAAAAAAAQAAgBgBAAIgFgCIABgHIARAAQAAAAABAAQAAAAAAAAQABAAAAAAQAAABAAAAIAAAjQAaACALAKQAMALAAAVQAAAXgMALQgLALgaABIAAAXQAAAAAAABQAAAAAAABQAAAAABAAQAAAAAAAAIAFADIgBAHgAipAjQATgBAIgIQAIgJAAgRQAAgPgIgIQgIgIgTgBgAjSgXQgIAHAAAQQAAARAIAJQAJAIATABIAAhDQgTABgJAIgAAQBGIAAgaIhLAAIAAhJQAAgBAAAAQAAgBgBAAQAAAAAAAAQAAgBgBAAIgFgCIABgIIASAAQABAAAAABQAAAAAAAAQABAAAAABQAAAAAAAAIAABJIAuAAIAAhLIAOAAIAABLIAPAAIAAAlgAlCAjQgKgLAAgYQAAgWAKgLQAKgLAXAAQAXAAAKALQAKALAAAWQAAAYgKALQgKALgXAAQgXAAgKgLgAk3gYQgHAIAAAQQAAASAHAJQAHAIAPAAQAPAAAHgIQAGgJAAgSQAAgQgGgIQgHgIgPAAQgPAAgHAIgAHFAsIgYgkIgZAkIgPAAIAfgsIgegqIAPAAIAYAiIAYgiIAPAAIgeAqIAfAsgAFmAsIAAhCIgxBCIgOAAIAAhJQAAgBAAAAQAAgBgBAAQAAAAAAAAQAAgBgBAAIgFgCIABgIIARAAQABAAAAABQABAAAAAAQAAAAAAABQAAAAAAAAIAABBIAxhDIAOAAIAABWgAD+AsIAAgnIgwAAIAAAnIgOAAIAAhJQAAgBAAAAQAAgBAAAAQAAAAgBAAQAAgBAAAAIgGgCIACgIIASAAQAAAAAAABQABAAAAAAQAAAAAAABQAAAAAAAAIAAAkIAwAAIAAgmIAPAAIAABWgACZAsIAAhCIgxBCIgOAAIAAhJIgCgDIgFgCIABgIIARAAQABAAAAABQAAAAAAAAQABAAAAABQAAAAAAAAIAABBIAxhDIAOAAIAABWgAAxAsIAAhJIgBgDIgGgCIACgIIASAAQAAAAAAABQABAAAAAAQAAAAAAABQAAAAAAAAIAABUgAhjAsIAAhJQAAgBAAAAQAAgBgBAAQAAAAAAAAQAAgBgBAAIgFgCIABgIIATAAQAAAAAAABQABAAAAAAQAAAAAAABQAAAAAAAAIAABUgAnNAsIAAhJQAAgBAAAAQAAgBgBAAQAAAAAAAAQAAgBgBAAIgFgCIABgIIAxAAQAbAAAAAZQAAAOgMADQAPACAAARQAAAOgHAFQgHAGgPAAgAnAAiIAcAAQAKgBADgDQAEgDAAgIQAAgIgEgDQgDgDgKAAIgcAAgAnAgEIAbAAQAQAAAAgNQAAgOgQAAIgbAAgABrg9QgGgFAAgOIAKAAQAAAJAEADQAEAEAJAAQARAAAAgQIAKAAQAAAOgGAFQgHAHgOAAQgOAAgHgHgAAvhEQAAgKAJAAQAJAAAAAKQAAAJgJAAQgJAAAAgJgAhmhEQAAgKAKAAQAJAAAAAKQAAAJgJAAQgKAAAAgJg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-47,-8.2,94,16.4);


(lib.t1 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("AmrBSIAAgLIAFAAQAIAAAFgEQAEgDAEgLIADgKIglhVIAPAAIAdBDIAZhDIAQAAIgmBhQgGAQgHAFQgHAHgNAAgAA/BFIAAgaIhJAAIAAAaIgOAAIAAglIAJAAQAHgFAEgKQADgLAAgSIAAgTIgCgCIgFgCIABgHIBFAAIAABKIAOAAIAAAlgAAKgLQAAAggKALIAwAAIAAg/IgmAAgAGpAiQgKgKAAgYQAAgXAKgKQAKgMAXAAQAQAAAKAEIgCALQgIgDgOAAQgQAAgHAIQgHAIAAARQAAARAHAIQAHAIAQAAQANABALgEIAAALQgLAEgPAAQgXAAgKgLgAFMAiQgLgKAAgYQAAgXAKgKQAJgMAWAAQAUAAAJALQAJAKAAAYIAAADIhBAAQABARAHAHQAIAHASAAQAOAAAOgEIAAALQgMAEgRAAQgZAAgLgLgAGCgEQAAgQgGgIQgFgGgNAAQgOAAgGAHQgHAHAAAQIAzAAIAAAAgABfAiQgKgKAAgYQAAgXAKgKQAKgMAXAAQAXAAAKAMQAKAKAAAXQAAAYgKAKQgKALgXAAQgXAAgKgLgABqgZQgHAIAAARQAAARAHAIQAHAIAPAAQAPAAAHgIQAGgIAAgRQAAgRgGgIQgHgIgPAAQgPAAgHAIgAjjAiQgKgKAAgYQAAgXAKgKQAKgMAXAAQAPAAAMAEIgDALQgIgDgOAAQgQAAgHAIQgHAIAAARQAAARAHAIQAHAIAQAAQANABALgEIAAALQgLAEgPAAQgXAAgKgLgApaAiQgKgKAAgYQAAgXAKgKQAKgMAXAAQAXAAAKAMQAKAKAAAXQAAAYgKAKQgKALgXAAQgXAAgKgLgApPgZQgGAIAAARQAAARAGAIQAHAIAPAAQAPAAAHgIQAGgIAAgRQAAgRgGgIQgHgIgPAAQgPAAgHAIgAKeArIAAhCIgxBCIgOAAIAAhKIgCgCIgFgCIABgHIARAAQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAABIAAA/IAxhBIAOAAIAABVgAI2ArIAAgnIgwAAIAAAnIgOAAIAAhKIgBgCIgGgCIACgHIASAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAABIAAAjIAwAAIAAglIAPAAIAABVgADoArIAAhKIgBgCIgGgCIACgHIAwAAQAOAAAHAFQAGAGAAAMQAAAPgLADQAOACAAASQAAAMgHAHQgGAFgPAAgAD2AgIAcAAQARAAAAgOQAAgPgRAAIgcAAgAD2gEIAaAAQAQgBAAgOQAAgNgQAAIgaAAgAheArIAAgiIgYAAIgVAiIgPAAIAWgkQgUgDAAgUQAAgOAIgGQAHgHAQABIApAAIAABVgAiKgQQAAAQATAAIAZAAIAAgfIgZAAQgTAAAAAPgAkPArIAAhCIgxBCIgOAAIAAhKIgBgCIgGgCIACgHIARAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAABIAAA/IAyhBIAOAAIAABVgAnnArIAAhKIgfAAIAAgLIBLAAIAAALIgeAAIAABKgAqjArIAAhsQAAAAAAAAQAAgBgBAAQAAAAAAAAQAAgBgBAAIgFgCIABgHIBPAAIAAALIg6AAIAABsgAlDhSIAKAAQAAARARAAQARAAAAgRIALAAQAAAbgcAAQgbAAAAgbg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-68.4,-8.3,136.8,16.6);


(lib.logoSmall = function() {
	this.initialize();

	// Layer 3
	this.instance = new lib.logo();
	this.instance.setTransform(-55,-16,0.635,0.635);

	// LOGO
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AhdB0QglgkAAhQQAAhOAhgkQAggkBHAAQBCAAAdAjQAeAiAABOIgBAQIjVAAQACA2AaAYQAaAXA4AAQAvAAAtgOIAAAmQgpANg3AAQhPAAglgjgAg8hcQgWAXgBA0ICoAAQgBg1gSgXQgTgXgpAAQgtAAgVAYg");
	this.shape.setTransform(21.6,10.5,0.118,0.118);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("Ag4DVIAAjzIgBgGQgBgCgEgBIgigKIAEgaIAkAAIAAgmQAAg0AYgXQAYgYAzAAQAiAAAUAIIgHAlQgUgHgVABQggAAgOANQgMAOAAAfIAAAoIBVAAIAAAmIhVAAIAAD6g");
	this.shape_1.setTransform(18.9,9.7,0.118,0.118);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgODLIAAj3QAAgGgFgCIgSgIIAFgYIA7AAQAEAAAAAGIAAEZgAgPiVQgHgHAAgQQAAgQAHgHQAHgHAOAAQARAAAHAHQAHAHABAQQgBAPgHAIQgHAHgRAAQgOAAgHgHg");
	this.shape_2.setTransform(16.5,9.8,0.118,0.118);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgRDRQgFAAAAgGIAAlzQAAgFgFgDIgSgIIAFgYIA6AAQAFAAAAAGIAAFzQABAGAEACIASAHIgFAZg");
	this.shape_3.setTransform(14.7,9.8,0.118,0.118);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AhICUIAAj3QAAgHgEgBIgTgIIAFgZIA8AAQAGAAAAAGIAAAeQAfgrA8AAQAMAAAQADIgIApQgRgDgKAAQgcAAgWAJQgQAHgSAPIAADfg");
	this.shape_4.setTransform(11.3,10.5,0.118,0.118);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AhrB0QgigkAAhQQAAhOAigkQAigkBJAAQBLAAAhAkQAiAkAABOQAABQgiAkQghAjhLAAQhKAAghgjgAhHhWQgWAbABA7QgBA8AWAbQAXAaAwAAQAyAAAVgaQAWgbAAg8QAAg7gWgbQgVgagyAAQgwAAgXAag");
	this.shape_5.setTransform(8,10.5,0.118,0.118);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("Ag5DVIAAjzIAAgGQgBgCgEgBIgigKIAEgaIAjAAIAAgmQAAg0AYgXQAZgYAzAAQAiAAAUAIIgHAlQgUgHgVABQggAAgOANQgMAOAAAfIAAAoIBVAAIAAAmIhVAAIAAD6g");
	this.shape_6.setTransform(5.1,9.7,0.118,0.118);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("ABUCUQgFAAgBgGIAAitQAAgqgQgRQgRgRgnAAQgYAAgaAHQgXAGgKAIIAADqIgxAAIAAj3QABgHgFgBIgSgIIAFgZIA8AAQAGAAAAAGIAAAVQAjgiA4AAQA8AAAaAbQAaAbAAA9IAACLQAAAGAFADIASAHIgFAZg");
	this.shape_7.setTransform(0,10.5,0.118,0.118);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AhrB0QgigkAAhQQAAhOAigkQAhgkBKAAQBKAAAjAkQAhAkAABOQAABQghAkQgjAjhKAAQhKAAghgjgAhGhWQgXAbAAA7QAAA8AXAbQAVAaAxAAQAxAAAWgaQAWgbAAg8QAAg7gWgbQgWgagxAAQgxAAgVAag");
	this.shape_8.setTransform(-4,10.5,0.118,0.118);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AgODLIAAj3QAAgGgFgCIgSgIIAFgYIA6AAQAGAAAAAGIAAEZgAgPiVQgHgHAAgQQAAgQAHgHQAHgHAPAAQAQAAAHAHQAIAHAAAQQAAAPgIAIQgHAHgQAAQgPAAgHgHg");
	this.shape_9.setTransform(-6.9,9.8,0.118,0.118);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AhqCJIAAgnQAvAQAzAAQBIAAAAgyQAAgZgbgMQgMgFgvgLQgpgJgTgLQgbgTAAgnQAAgpAfgVQAdgVA1AAQAuAAAwANIgIAlQgngNgtAAQhFAAAAAuQAAAXAcALQAHADAyAMQBYASAABAQgBArgeAWQgdAWg2AAQg5AAgtgOg");
	this.shape_10.setTransform(-9.3,10.5,0.118,0.118);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AhpCJIAAgnQAtAQA0AAQBHAAABgyQAAgZgbgMQgMgFgugLQgqgJgTgLQgbgTAAgnQABgpAegVQAdgVA1AAQAvAAAuANIgHAlQgogNgsAAQhFAAAAAuQAAAXAbALQAJADAxAMQBXASABBAQAAArgfAWQgdAWg2AAQg5AAgsgOg");
	this.shape_11.setTransform(-12.5,10.5,0.118,0.118);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AhqCDQgbgVAAgsQAAgsAcgUQAcgSA9AAQAuAAAkAMIAAgoQAAglgUgQQgUgQgsAAQgsAAgtAPIAAgmQAugOAwAAQBBAAAeAaQAeAaAAA6IAACQQAAAGAFACIARAIIgEAYIgyAAIgDAAQgBgBAAAAQAAAAgBgBQAAAAAAgBQAAgBAAgBIgCgZQgbAlhFAAQg5AAgagUgAhEAaQgSAMAAAcQAAAaARAMQARANAmAAQApAAAUgPQATgQAAggIAAgaQgigOgpAAQgpAAgSAMg");
	this.shape_12.setTransform(-15.9,10.5,0.118,0.118);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AiHDIIAAlpQgBgGgGgBIgRgIIAEgXICuAAQBLABAhAdQAhAdAABBQAABAghAbQghAdhLABIhrAAIAACagAhYAGIBoAAQAzAAAXgRQAWgUAAgsQAAgtgWgTQgXgUgzAAIhoAAg");
	this.shape_13.setTransform(-19.8,9.9,0.118,0.118);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFCB55").s().p("AihWJMAAAgsRIFDAAMAAAAsRg");
	this.shape_14.setTransform(53.1,0.3,0.118,0.118,0,0,0,0,-0.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("ADQE5IgphsIlNAAIgpBsIikAAQBFizBRi4QBAiRA5h1IDKAAQCPEmB/FLgAB4BWQg6iOg+iOQg6CFg9CXIDvAAIAAAAg");
	this.shape_15.setTransform(10.2,0.3,0.118,0.118);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AANE+QifAAhSg+QhSg/gBh6IAAkoQAAgMgKgRIgPgZIAHgmIC1AAIAAF9QAAAhAHAUQAHAVAQAPQAnAkBeAAQBeAAAngkQAQgPAHgVQAGgUABghIAAl9ICfAAIAAGEQAAB8hQA+QhOA9ihAAg");
	this.shape_16.setTransform(19.3,0.3,0.118,0.118);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("ADJE5Ij+kXQhHhMgtg7IAAGeIiTAAIAAoVQgBgNgKgRIgNgZIAGglICeAAIDiD3QBgBoAxA/IAAmeICTAAIAAJxg");
	this.shape_17.setTransform(0.3,0.3,0.118,0.118);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("ACgE5IhtjJIjJAAIAADJIikAAIAAoLIgBgSQgBgIgIgOIgPgZIAHglIF1AAQBQAAAzANQAzAMAjAdQA7AxAABkQAAA7geAyQgfA0g0AcICHDpgAiWgCIDdAAQAgAAATgSQAcgcAAg1QAAgwgbgXQgOgLgWgFQgYgFgnAAIiuAAg");
	this.shape_18.setTransform(-17.7,0.3,0.118,0.118);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AkPE5IAApxIIUAAIAAB0IlxAAIAACKIFSAAIAABuIlSAAIAACRIF8AAIAAB0g");
	this.shape_19.setTransform(-8.6,0.3,0.118,0.118);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AkCE5IAApxICjAAIAAH9IFiAAIAAB0g");
	this.shape_20.setTransform(28.5,0.3,0.118,0.118);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AhQE5IAAn9IjyAAIAAh0IKFAAIAAB0IjyAAIAAH9g");
	this.shape_21.setTransform(34.5,0.3,0.118,0.118);

	this.addChild(this.shape_21,this.shape_20,this.shape_19,this.shape_18,this.shape_17,this.shape_16,this.shape_15,this.shape_14,this.shape_13,this.shape_12,this.shape_11,this.shape_10,this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-55,-16.3,110,33.4);


(lib.icons = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgTBxQgQgQAAggIAAhoIAAgFIgDgBIgXgGIADgRIAXAAIAAg7IAhAAIAAA7IBAAAIAAAYIhAAAIAABsQgBAUAIAJQAIAJAUAAQAMAAARgEIAAAaQgSAEgPAAQggAAgQgPg");
	this.shape.setTransform(-25.1,10.4,0.219,0.219);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgLCLQgDAAgBgDIAAj3QAAgFgCgBIgNgFIAEgRIAmAAQAEAAAAAEIAAD3QAAAFACABIAMAFIgCAQg");
	this.shape_1.setTransform(-27.6,10.1,0.219,0.219);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("Ag4BQQgTgTAAgpIAAhbQAAgBgBAAQAAgBAAAAQgBgBAAAAQgBAAgBAAIgMgHIADgRIApAAQADAAAAAFIAABvQAAAeANANQAMAMAaAAQAcAAANgMQAMgNAAgeIAAh0IAgAAIAAB2QAAAqgUASQgUASgtAAQgrAAgUgSg");
	this.shape_2.setTransform(-31.2,11.1,0.219,0.219);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AhHBXQgSgOAAgdQAAgdATgOQATgLAoAAQAeAAAZAIIAAgbQAAgYgOgLQgNgLgdAAQgfAAgcAKIAAgaQAdgJAiAAQArAAAUASQAUARAAAnIAABfQAAAFADABIAMAFIgDAQIgiAAQAAAAgBAAQgBAAAAgBQgBAAAAAAQAAgBAAgBIgCgRQgRAZguAAQgmAAgSgOgAgtARQgMAIAAATQAAARALAJQAMAIAZAAQAbAAANgKQANgKAAgWIAAgSQgXgJgbAAQgbAAgMAIg");
	this.shape_3.setTransform(-35.8,11,0.219,0.219);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AA4BiQgDAAgBgDIAAhzQAAgcgLgMQgLgLgaAAQgPgBgSAGQgPAEgIAFIAACbIgfAAIAAikQAAgDgEgCIgMgGIAEgQIAoAAQAEAAgBAEIAAAOQAYgXAlAAQApABARARQARASAAApIAABcQAAAFAEABIALAFIgDAQg");
	this.shape_4.setTransform(-40.6,11,0.219,0.219);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("Ag+BNQgYgYAAg1QAAg0AWgYQAVgYAvAAQAsAAATAXQAUAYAAAzIAAALIiOAAQABAkASAPQARAQAlAAQAfAAAfgKIAAAaQgbAJglAAQg1AAgZgYgAgog9QgOAPgBAjIBvAAQAAgjgMgQQgMgPgcAAQgdAAgPAQg");
	this.shape_5.setTransform(-45.4,11,0.219,0.219);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("ABJCFIhEhtIhCAAIAABtIggAAIAAjwQAAgDgEgCIgMgFIADgPIB3AAQAwAAAWATQAVASAAAqQAAAjgQASQgQARgiADIBIBxgAg9AAIBHAAQAhAAAOgMQAPgMAAgdQAAgdgPgMQgOgNghAAIhHAAg");
	this.shape_6.setTransform(-50.2,10.2,0.219,0.219);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("Ag1BNQgXgZAAg0QAAgzAXgZQAXgZAwAAQAjAAAYAIIgFAZQgXgIgaAAQggAAgQAPQgQAPgCAjIBjAAIAAAUIhjAAQABAlAQAQQARAQAgAAQAaAAAagIIAAAYQgYAIghAAQgwAAgXgZg");
	this.shape_7.setTransform(24.1,11,0.219,0.219);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AhLCMIAAgYIAKAAQATAAALgIQAKgKAIgXIAIgVIhUjCIAjAAIA+CaIA4iaIAiAAIhTDdQgMAigPANQgRAOgdAAIgNgCg");
	this.shape_8.setTransform(20,12,0.219,0.219);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("ABTB+IAAg6IilAAIAAA6IgeAAIAAhTIATAAQARgJAHgYQAHgVAAguIAAgpQAAgEgDgBIgNgGIAEgQICbAAIAACoIAgAAIAABTgAggg2QAAAqgFAUQgEAXgNAMIBoAAIAAiPIhSAAg");
	this.shape_9.setTransform(15.1,11.7,0.219,0.219);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AA9BhIAAhXIhqAAIAABXIgfAAIAAimQAAgEgEgBIgMgGIAEgQIAoAAQADAAAAAEIAABQIBqAAIAAhUIAgAAIAADBg");
	this.shape_10.setTransform(9.8,11,0.219,0.219);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("Ag+BOQgZgYAAg2QAAg0AWgZQAWgYAvAAQAsAAAUAXQAUAYAAA0IAAALIiPAAQABAkARAQQASAQAlAAQAgAAAfgKIAAAaQgdAJgkAAQg1AAgZgYgAgog+QgOAQgBAjIBwAAQAAgkgNgPQgMgQgcAAQgdAAgPAQg");
	this.shape_11.setTransform(5.1,11,0.219,0.219);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("ABMBhIAAiTIg7BYIgHAAQgJAAgBgBQgCgCgFgGIg1hPIAACTIgeAAIAAimQAAgEgCgBIgNgGIAEgQIAkAAQAEAAACABQADACAEAHIA7BcIBDhmIAgAAIAADBg");
	this.shape_12.setTransform(-0.2,11,0.219,0.219);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AhIBOQgXgYAAg2QAAg0AXgZQAXgYAxAAQAyAAAXAYQAXAZAAA0QAAA2gXAYQgXAYgyAAQgxAAgXgYgAgvg5QgPASAAAnQAAApAPARQAPASAgAAQAhAAAPgSQAPgRAAgpQAAgngPgSQgPgSghAAQggAAgPASg");
	this.shape_13.setTransform(-5.3,11,0.219,0.219);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AAyBhIhHhVIgTATIAABCIgfAAIAAimQAAgEgDgBIgMgGIADgQIAnAAQAEAAAAAEIAABYIBXhcIAmAAIhWBaIBYBng");
	this.shape_14.setTransform(-9.6,11,0.219,0.219);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("Ag+BOQgZgYAAg2QAAg0AWgZQAWgYAvAAQAtAAATAXQAUAYAAA0IAAALIiQAAQACAkARAQQASAQAlAAQAgAAAegKIAAAaQgcAJgkAAQg1AAgZgYgAgog+QgPAQgBAjIByAAQgBgkgNgPQgMgQgcAAQgeAAgOAQg");
	this.shape_15.setTransform(-14.1,11,0.219,0.219);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AhRCOIAAj6QAAgEgEgCIgMgFIADgQIApAAQADAAAAADIAAARQATgaAsAAQAtAAAUAZQAUAYAAA3QAAAzgUAZQgUAYgtAAQgmAAgZgVIAABkgAgkhlQgOAMAAAfIAABMQAZATAeAAQAhAAAOgSQANgRAAgnQAAgqgNgSQgOgSghAAQgcAAgNAOg");
	this.shape_16.setTransform(-19,11.9,0.219,0.219);

	this.instance = new lib.elf();
	this.instance.setTransform(28.9,4.6,0.64,0.64);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AlIF/QgWAAgQgQQgQgQAAgWIAAqQQAAgXAQgQQAQgQAWAAIKRAAQAWAAAQAQQAQAQAAAXIAAKQQAAAWgQAQQgQAQgWAAgAhUDgQCJAABXhiQBOhZAAhyIAAgNQAggYAVggQgcANghAEQAjgVAMgmQgeARgmAJQgggiguAAQgsAAgfAgQggAfAAArQAAAOADALQg/gDg6geQg5gdgogyQgOAZAAAdQAAAcANAXQAMAXAWAPQgaAAgWgNIAAABQAAAnAYAbQAYAdAlAHQgOAFgOAAIgUgCQAKAfAcAVQAbAVAjABQg6AthLAAIgZgBQBLAwBYgBg");
	this.shape_17.setTransform(177.9,11,0.112,0.112);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AlIF/QgWAAgQgQQgQgQAAgWIAAqQQAAgXAQgQQAQgQAWAAIKQAAQAXAAAQAQQAQAQAAAXIAAKQQAAAWgQAQQgQAQgXAAgAhFAQIAAD7QAAAGACADQACACAGAAQAugCAsACQAHgBACgBQACgDAAgGIAAj4QAAgKABgBIALAAIA1AAQAIAAABgHIAIhOQAAgEgCgCQgBgCgGAAIhEABQgHAAAAgGQAAgfABgQQACgfAfAAIAtAAQAGAAAAgFIAAhQQAAgGgGAAQhIAAgVABQgvACgaAkQgUAdgBAmIAAA8QAAAGgCABQgCADgFAAIgpAAQgHgBABAHIAABNQgBAHAIAAIAnAAIABgBQAIAAAAAKg");
	this.shape_18.setTransform(166.4,11,0.112,0.112);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AiMCrQgigbgBg6QAAg5AlgaQAlgZBOAAQA9AAAwAQIAAg0QAAgwgagVQgbgVg6AAQg7AAg5ATIAAgyQA6gSBCAAQBVAAAnAiQAnAiAABMIAAC8QAAAIAGADIAXAKIgFAgIhBAAQgEAAgBgBQgCgBAAgEIgEghQgiAxhbAAQhKAAgjgbgAhZAiQgYAQAAAkQAAAiAXAQQAWAQAxAAQA1AAAbgUQAZgTAAgrIAAgiQgrgRg4AAQg1AAgXAPg");
	this.shape_19.setTransform(222.2,11.6,0.112,0.112);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AhuCdQgngkAAhRIAAi1QgBgEgFgDIgYgLIAFghIBQAAQAEAAABABQACACAAAFIAADbQAAA6AYAZQAYAZA1AAQA3AAAZgZQAYgZAAg6IAAjjIA+AAIAADoQAABRgnAkQgnAkhYAAQhVAAgngkg");
	this.shape_20.setTransform(217.3,11.7,0.112,0.112);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AgfAfQgKgJAAgWQAAgUAKgKQAKgKAVAAQAXAAAKAKQAJAKAAAUQAAAWgJAJQgKAKgXAAQgVAAgKgKg");
	this.shape_21.setTransform(214.1,13.3,0.112,0.112);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("AgmDdQgfgeAAhAIAAjMQAAgHgBgBQgBgCgFgCIgsgMIAFgjIAuAAIAAhwIA/AAIAABwICAAAIAAAxIiAAAIAADTQAAApAQARQARASAoAAQAYgBAfgGIAAAxQgeAIgjgBQhAAAgfgcg");
	this.shape_22.setTransform(211.4,11,0.112,0.112);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AgXERQgEAAgBgBQgBgCAAgFIAAnkQAAgIgHgDIgXgKIAGggIBNAAQAEAAABABQACACAAAFIAAHkIABAHQABACAEACIAXAKIgGAgg");
	this.shape_23.setTransform(208.9,10.7,0.112,0.112);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("AhuCdQgngkAAhRIAAi1QAAgEgGgDIgYgLIAFghIBQAAQAEAAABABQACACAAAFIAADbQAAA6AYAZQAYAZA1AAQA3AAAYgZQAZgZAAg6IAAjjIA+AAIAADoQAABRgnAkQgnAkhYAAQhVAAgngkg");
	this.shape_24.setTransform(205.3,11.7,0.112,0.112);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("AiMCrQgjgbAAg6QAAg5AlgaQAlgZBPAAQA8AAAwAQIAAg0QAAgwgagVQgagVg7AAQg7AAg5ATIAAgyQA7gSBAAAQBWAAAnAiQAnAiAABMIAAC8IABAHQABACAEACIAYAKIgHAgIhAAAIgFgBQgCgBAAgEIgDghQgjAxhbAAQhKAAgjgbgAhaAiQgXAQAAAkQAAAiAWAQQAXAQAxAAQA2AAAagUQAZgTAAgrIAAgiQgrgRg4AAQg1AAgYAPg");
	this.shape_25.setTransform(200.8,11.6,0.112,0.112);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("ABuDBQgEAAgCgCQgBgBAAgFIAAjiQAAg2gWgXQgWgXgzAAQggAAgiAKQgeAIgOAKIAAEyIg+AAIAAlDQAAgIgGgDIgYgKIAGggIBPAAQAEAAABABQACACAAAFIAAAbQAugsBLAAQBOAAAiAjQAiAjAABQIAAC2IABAHQABACAEACIAYAKIgHAgg");
	this.shape_26.setTransform(195.9,11.6,0.112,0.112);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("Ah6CXQgwgvAAhoQAAhnArgvQAqgvBdAAQBWAAAnAuQAmAtAABlIAAAWIkXAAQACBHAiAeQAhAfBLAAQA7AAA9gTIAAAyQg3AShGAAQhoAAgxgvgAhPh5QgcAegBBDIDbAAQgBhEgYgeQgYgeg2AAQg6AAgdAfg");
	this.shape_27.setTransform(191.2,11.6,0.112,0.112);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AhfDBIAAlDQABgIgHgDIgXgKIAGggIBOAAQAEAAACABQACACgBAFIAAAmQAqg3BQAAQATAAARADIgLA3QgSgGgRAAQglABgeAMQgUAJgZAUIAAEjg");
	this.shape_28.setTransform(187.8,11.6,0.112,0.112);

	this.addChild(this.shape_28,this.shape_27,this.shape_26,this.shape_25,this.shape_24,this.shape_23,this.shape_22,this.shape_21,this.shape_20,this.shape_19,this.shape_18,this.shape_17,this.instance,this.shape_16,this.shape_15,this.shape_14,this.shape_13,this.shape_12,this.shape_11,this.shape_10,this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-52.6,-5.6,276.8,23);


(lib.btnTxt = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("ALmAvQgNgMgCgcIgSAAIAAAzIgWAAIAAhjQAAAAgBgBQAAgBAAAAQAAgBgBAAQAAAAgBAAIgGgDIABgKIAeAAIAAAxIATAAQACgbANgMQAOgMAcAAQAeAAANAOQANAOAAAfQAAAggNAOQgNAOgeAAQgdAAgOgNgAL2gfQgIAKAAAVQAAAWAIAKQAIAKATAAQARAAAJgKQAHgKABgWQgBgVgHgKQgJgKgRAAQgTAAgIAKgABMAuQgNgPAAgfQAAgfANgOQAOgOAfAAQAfAAAOAOQAOAOAAAfQAAAfgOAPQgOAOgfAAQgfAAgOgOgABegfQgHAKgBAVQABAWAHAKQAIAKATAAQASAAAJgKQAIgKAAgWQAAgVgIgKQgJgKgSAAQgTAAgIAKgAnmAuQgOgPABgfQgBgfAOgOQAOgOAfAAQAYAAAMAFIgDARQgOgEgPAAQgVAAgJAKQgJAKAAAVQAAAWAJAKQAJAKAVAAQAQAAAPgFIAAATQgSAEgRAAQgfAAgOgOgArSA6IAAgSQAGACAHAAQAPAAAIgOIACgEIgthRIAZAAIAfA8IAcg8IAYAAIgqBXQgIAQgJAHQgKAHgRAAQgIAAgHgCgAJ8A6IAAhjQAAAAAAgBQAAgBgBAAQAAgBAAAAQgBAAgBAAIgGgDIACgKIAdAAQAAAAAAAAQAAAAABABQAAAAAAAAQAAAAAAABIAABxgAIdA6IAAhjQAAAAAAgBQAAgBgBAAQAAgBAAAAQgBAAgBAAIgGgDIACgKIBTAAIAAASIg1AAIAABhgAGyA6IAAhjQAAAAAAgBQAAgBgBAAQAAgBgBAAQAAAAgBAAIgGgDIACgKIBbAAIAAASIg9AAIAAAfIAxAAIAAAPIgxAAIAAAhIA+AAIAAASgAE9A6IAAhjQAAAAgBgBQAAgBAAAAQAAgBgBAAQAAAAgBAAIgGgDIABgKIA/AAQASAAAJAIQAIAHAAARQAAASgOAGQATAEgBAWQAAARgJAIQgIAIgUAAgAFSApIAgAAQASAAABgRQAAgJgFgEQgEgEgKAAIggAAgAFSgIIAdAAQASAAAAgQQAAgQgSAAIgdAAgADKA6IAAhjQAAAAAAgBQAAgBgBAAQAAgBAAAAQgBAAAAAAIgHgDIACgKIA5AAQAXAAAKAJQALAJgBAUQABATgLAIQgKAJgXAAIgbAAIAAApgADhAAIAZAAQAMAAAFgEQAGgEAAgLQAAgUgXAAIgZAAgAAXA6IAAgzIg6AAIAAAzIgXAAIAAhjQAAAAAAgBQAAgBgBAAQAAgBAAAAQgBAAAAAAIgHgDIACgKIAcAAQABAAAAAAQAAAAABABQAAAAAAAAQAAAAAAABIAAAvIA6AAIAAgxIAYAAIAABzgAiKA6IgIgbIgyAAIgIAbIgYAAQAIgaAMghQAOgmAKgSIAaAAQAKASAOAmQAOAhAGAagAiXAOQgJgagLgYQgLAYgJAaIAoAAIAAAAgAkGA6IAAgzIg7AAIAAAzIgYAAIAAhjQAAAAAAgBQAAgBAAAAQgBgBAAAAQgBAAAAAAIgHgDIACgKIAdAAQAAAAABAAQAAAAAAABQAAAAAAAAQABAAAAABIAAAvIA7AAIAAgxIAYAAIAABzgApeA6IAAhjQAAAAAAgBQAAgBgBAAQAAgBAAAAQgBAAAAAAIgHgDIACgKIA5AAQAXAAAKAJQALAJgBAUQABATgLAIQgKAJgXAAIgbAAIAAApgApHAAIAZAAQAMAAAGgEQAFgEAAgLQAAgUgXAAIgZAAgAr5A6IgmgxIgJAKIAAAnIgYAAIAAhjQAAAAAAgBQAAgBAAAAQAAgBgBAAQAAAAgBAAIgHgDIACgKIAdAAQAAAAABAAQAAAAAAABQAAAAAAAAQABAAAAABIAAAwIAtgyIAaAAIgwA2IAyA9g");
	this.shape.setTransform(0,0,0.56,0.56);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-47.2,-3.3,94.3,6.8);


(lib.btnBg = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCC33").s().p("AqzCMIAAkXIVnAAIAAEXg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-69.2,-14,138.5,28.1);


(lib.bgImg3_1 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.bgImg3();
	this.instance.setTransform(-150,-300);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-150,-300,300,600);


(lib.bgImg2_1 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.bgImg2();
	this.instance.setTransform(-180,-256);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-180,-256,360,320);


(lib.bgImg1_1 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.bgImg1();
	this.instance.setTransform(-209,-251);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-209,-251,418,322);


(lib.bg = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("A3bTiMAAAgnDMAu3AAAMAAAAnDg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-150,-125,300,250);


(lib.Symbol = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#1D1D1B").s().p("AgaAgIAjggIgigfIAIgJIAsAoIgtApg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-2.7,-4.1,5.5,8.4);


(lib.wheel_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.wheelMc();

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:1,scaleY:1,rotation:-694.4},13).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-17.5,-17.5,35,35);


(lib.car2_1 = function() {
	this.initialize();

	// Layer 2
	this.instance = new lib.wheel_1();
	this.instance.setTransform(-101.6,0.7,0.42,0.729);
	this.instance.alpha = 0.281;

	this.instance_1 = new lib.wheel_1();
	this.instance_1.setTransform(4,36,0.714,1);
	this.instance_1.alpha = 0.281;

	// Layer 1
	this.instance_2 = new lib.car2();
	this.instance_2.setTransform(-150,-82);

	this.addChild(this.instance_2,this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-150,-82,300,338);


(lib.car1_1 = function() {
	this.initialize();

	// Layer 2
	this.instance = new lib.wheel_1();
	this.instance.setTransform(-101.6,0.7,0.42,0.729);
	this.instance.alpha = 0.281;

	this.instance_1 = new lib.wheel_1();
	this.instance_1.setTransform(4,36,0.714,1);
	this.instance_1.alpha = 0.281;

	// Layer 1
	this.instance_2 = new lib.car1();
	this.instance_2.setTransform(-150,-80);

	this.addChild(this.instance_2,this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-150,-80,300,336);


(lib.btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_99 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(99).call(this.frame_99).wait(1));

	// >
	this.instance = new lib.Symbol();
	this.instance.setTransform(40,-0.1,0.092,0.06);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(20).to({_off:false},0).to({scaleX:1,scaleY:1,x:57},9,cjs.Ease.get(1)).wait(5).to({x:61},3,cjs.Ease.get(1)).to({x:57},2).wait(3).to({x:61},3,cjs.Ease.get(1)).to({x:57},2).wait(53));

	// btnTxt
	this.instance_1 = new lib.btnTxt();
	this.instance_1.setTransform(-8.7,10);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(10).to({_off:false},0).to({y:0,alpha:1},10).wait(80));

	// btnBg
	this.instance_2 = new lib.btnBg();
	this.instance_2.setTransform(0,0,0.01,0.018);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({scaleX:1,scaleY:1},10,cjs.Ease.get(1)).wait(90));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-0.7,-0.2,1.4,0.5);


(lib.banner = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// icons
	this.instance = new lib.icons();
	this.instance.setTransform(-90,273.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(245));

	// btn
	this.instance_1 = new lib.btn();
	this.instance_1.setTransform(49.7,217.6,1.22,1.22);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(184).to({_off:false},0).wait(50).to({alpha:0},10).wait(1));

	// t4_3
	this.instance_2 = new lib.t4_3();
	this.instance_2.setTransform(-291.8,-144.3,1.3,1.3);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(164).to({_off:false},0).to({x:-91.6,alpha:1},10).wait(60).to({alpha:0},10).wait(1));

	// t4_2
	this.instance_3 = new lib.t4_2();
	this.instance_3.setTransform(-254.6,-168.8,1.3,1.3);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(159).to({_off:false},0).to({x:-54.4,alpha:1},10).wait(65).to({alpha:0},10).wait(1));

	// t4_1
	this.instance_4 = new lib.t4_1();
	this.instance_4.setTransform(-280.8,-193.2,1.3,1.3);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(154).to({_off:false},0).to({x:-80.6,alpha:1},10).wait(70).to({alpha:0},10).wait(1));

	// t3_3
	this.instance_5 = new lib.t3_3();
	this.instance_5.setTransform(-271.7,-143.4,1.3,1.3);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(109).to({_off:false},0).to({x:-71.5,alpha:1},10).wait(25).to({alpha:0},10).to({_off:true},1).wait(90));

	// t3_2
	this.instance_6 = new lib.t3_2();
	this.instance_6.setTransform(-285.5,-165.9,1.3,1.3);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(104).to({_off:false},0).to({x:-85.3,alpha:1},10).wait(30).to({alpha:0},10).to({_off:true},1).wait(90));

	// t3_1
	this.instance_7 = new lib.t3_1();
	this.instance_7.setTransform(-271.1,-193,1.3,1.3);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(99).to({_off:false},0).to({x:-70.9,alpha:1},10).wait(35).to({alpha:0},10).to({_off:true},1).wait(90));

	// t2_3
	this.instance_8 = new lib.t2_3();
	this.instance_8.setTransform(-294.3,-145.9,1.3,1.3);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(54).to({_off:false},0).to({x:-94.1,alpha:1},10).wait(25).to({alpha:0},10).to({_off:true},1).wait(145));

	// t2_2
	this.instance_9 = new lib.t2_2();
	this.instance_9.setTransform(-266.1,-168.1,1.3,1.3,0,0,0,-0.1,0);
	this.instance_9.alpha = 0;
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(49).to({_off:false},0).to({x:-65.9,alpha:1},10).wait(30).to({alpha:0},10).to({_off:true},1).wait(145));

	// t2_1
	this.instance_10 = new lib.t2_1();
	this.instance_10.setTransform(-272.4,-193,1.3,1.3,0,0,0,-0.1,0);
	this.instance_10.alpha = 0;
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(44).to({_off:false},0).to({x:-72.2,alpha:1},10).wait(35).to({alpha:0},10).to({_off:true},1).wait(145));

	// t1
	this.instance_11 = new lib.t1();
	this.instance_11.setTransform(-244.4,-192.9,1.3,1.3);
	this.instance_11.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).to({x:-44.2,alpha:1},10).wait(24).to({alpha:0},10).to({_off:true},1).wait(200));

	// logoSmall
	this.instance_12 = new lib.logoSmall();
	this.instance_12.setTransform(62.7,-255,1.3,1.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(245));

	// bgImg3
	this.instance_13 = new lib.bgImg3_1();
	this.instance_13.alpha = 0;
	this.instance_13._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(144).to({_off:false},0).to({alpha:1},10).wait(80).to({alpha:0},10).wait(1));

	// car
	this.instance_14 = new lib.car2_1();
	this.instance_14.setTransform(0,43);
	this.instance_14.alpha = 0;
	this.instance_14._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(44).to({_off:false},0).to({alpha:1},15).wait(40).to({alpha:0},10).to({_off:true},1).wait(135));

	// car
	this.instance_15 = new lib.car1_1();
	this.instance_15.setTransform(0,43);

	this.timeline.addTween(cjs.Tween.get(this.instance_15).wait(245));

	// bgImg2
	this.instance_16 = new lib.bgImg2_1();
	this.instance_16.setTransform(-30,-44);
	this.instance_16.alpha = 0;
	this.instance_16._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_16).wait(99).to({_off:false},0).to({x:-8.2,alpha:1},20).to({x:30},35).to({_off:true},1).wait(90));

	// bgImg1
	this.instance_17 = new lib.bgImg1_1();
	this.instance_17.setTransform(-59,-48);

	this.timeline.addTween(cjs.Tween.get(this.instance_17).to({x:59},119).to({_off:true},1).wait(114).to({_off:false,x:-59},0).wait(11));

	// bg
	this.instance_18 = new lib.bg();

	this.timeline.addTween(cjs.Tween.get(this.instance_18).wait(245));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-333.3,-299,483.4,598);


// stage content:
(lib._300x600 = function() {
	this.initialize();

	// cover
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#666666").ss(2,1,1).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape.setTransform(150,300);

	// banner
	this.instance = new lib.banner();
	this.instance.setTransform(150,300);

	this.addChild(this.instance,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-33.3,299,484.4,602);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;