(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 300,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	manifest: [
		{src:"images/img1.jpg", id:"img1"},
		{src:"images/img2.jpg", id:"img2"},
		{src:"images/img3.jpg", id:"img3"},
		{src:"images/img4.jpg", id:"img4"},
		{src:"images/light.png", id:"light"}
	]
};



// symbols:



(lib.img1 = function() {
	this.initialize(img.img1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,487,600);


(lib.img2 = function() {
	this.initialize(img.img2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,292,414);


(lib.img3 = function() {
	this.initialize(img.img3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.img4 = function() {
	this.initialize(img.img4);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.light = function() {
	this.initialize(img.light);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,640,583);


(lib.t6_3 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AkpCSIg+AAIAAjxIAwAAQBLAAAAA6QAAASgKAPQgKAMgOAGIAAABQAWABAPARQAQARAAAbQAAAlgbATQgTAOgbAAIgHgBgAlQB/IAnAAQAeAAAPgRQAMgNgBgUQABghgbgMQgNgGgSAAIgmAAgAlQAHIAeAAQAOAAALgGQAWgJAAgcQAAgRgKgKQgMgNgZAAIgeAAgAw1CSIg9AAIAAjxIAwAAQBKAAAAA6QABASgKAPQgKAMgPAGIAAABQAXABAPARQAPARAAAbQAAAlgaATQgTAOgcAAIgHgBgAxbB/IAmAAQAeAAAPgRQAMgNAAgUQAAghgagMQgNgGgTAAIglAAgAxbAHIAdAAQAOAAALgGQAXgJgBgcQAAgRgKgKQgMgNgZAAIgdAAgARcCSIAAjxIAXAAIAADxgAP7CSIAAh8IiEAAIAAB8IgXAAIAAjxIAXAAIAABiICEAAIAAhiIAXAAIAADxgAL/CSIAAjxIAXAAIAADxgAK3CSIgghPIhhAAIggBPIgXAAIBnj4IBoD4gAKPAwIgphiIgoBiIBRAAgAFWCSIAAjxIBAAAQBGAAAABAQAAA/hGAAIgpAAIAABygAFtAMIAoAAQAvAAAAgrQAAgtgvAAIgoAAgAEHCSIhnh2IAAB2IgXAAIAAjxIAXAAIAABvIBnhvIAbAAIhtB0IBwB9gAgjCSIAhhJIhVioIAZAAIBFCPIA+iPIAWAAIhnDxgAp/CSIAAjxIB7AAIAAATIhlAAIAABMIBhAAIAAAUIhhAAIAABrIBlAAIAAATgArPCSIhfh3IAAB3IgWAAIAAh3IhfB3IgeAAIBoh8Ihih1IAcAAIBbBwIAAhwIAWAAIAABwIBchwIAbAAIhhB1IBnB8gAMUh2QgEgFgBgHQABgGAEgFQAEgFAHAAQAGAAAEAFQAFAFgBAGQABAHgFAFQgEAEgGAAQgHAAgEgEgALrh2QgEgFAAgHQAAgGAEgFQAEgFAHAAQAGAAAFAFQAEAEABAHQgBAHgEAFQgFAEgGAAQgHAAgEgEg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-113.9,-14.7,227.9,29.4);


(lib.t6_2 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AI9BJIAVgLQAGATAMAMQAQAPAVAAQAWAAAOgPQANgPAAgXQAAgVgOgOQgKgIgcgMQgcgOgMgMQgUgTAAgZQAAgWAMgPQARgUAiAAQAtAAAQAlIgSAKQgMgbgeAAQgVgBgLANQgJALAAANQAAATARANQAIAHAcAOQAcANALAJQAVATAAAfQAAAfgVAWQgVAVggAAQg1AAgWg3gAFKBdQghgkAAg5QAAg4AggjQAggkAzAAQBCAAAkA4IgSANQgggyg1ABQgoAAgaAfQgZAgAAAsQAAAxAbAeQAaAdAsAAQAoAAAZgbQAXgZAAghIhTAAIAAgUIBrAAQgBA0gZAhQgeAog4AAQg2AAghgjgAAdBsQgPgNgIgWIAVgLQAGATAMAMQAQAPAVAAQAWAAANgPQAOgPAAgXQAAgVgPgOQgJgIgcgMQgcgOgNgMQgTgTAAgZQAAgWAMgPQARgUAiAAQAtAAAQAlIgSAKQgMgbgeAAQgWgBgLANQgIALAAANQAAASAQAOQAJAGAbAPQAcANAMAJQAUATAAAfQAAAfgUAWQgVAVghAAQgeAAgVgUgAjEBXQgLgXAAgiIAAiXIAWAAIAACbQAAAWAIASQAOAjAmgBQAlABAOgjQAIgSAAgWIAAibIAXAAIAACXQAAAigLAXQgUApgzAAQgzAAgUgpgAkUB5Ig5hpIg4BpIgZAAIBGh6IhAh4IAZAAIAyBkIAzhkIAZAAIhAB4IBGB6gAo/B5IAAjyIB8AAIAAAUIhlAAIAABOIBhAAIAAATIhhAAIAABpIBlAAIAAAUgArRB5IAAjyIAWAAIAADeIBLAAIAAAUg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-72.2,-12.8,144.5,25.7);


(lib.t6_1 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AOLhjIAWAAIAAC+ICejHIAAD7IgXAAIAAi/IidDIgAKMhjIAWAAIAAC+ICejHIAAD7IgWAAIAAi/IieDIgAnuByQgkgkAAg5QAAg3AkgkQAkgkA0AAQA1AAAjAkQAlAkAAA3QAAA5glAkQgjAkg1AAQg0AAgkgkgAndg3QgeAeAAAuQAAAvAeAfQAcAfArAAQArAAAdgfQAdgfAAgvQAAgugdgeQgdgfgrAAQgrAAgcAfgAwZByQglgkAAg5QAAg3AlgkQAjgkA1AAQA1AAAjAkQAlAkAAA3QAAA5glAkQgkAkg0AAQg1AAgjgkgAwJg3QgdAeAAAuQAAAvAdAfQAdAfArAAQArAAAcgfQAegfAAgvQAAgugegeQgcgfgrAAQgrAAgdAfgAgpCPIAAgUQAGACAHAAQAXAAAHgWQAHgQAAgkIAAiWICAAAIAADyIgWAAIAAjfIhUAAIAACCQAAAsgJAVQgNAegggBQgJAAgJgBgAicCPIg9AAIAAjyIAwAAQBKAAAAA6QAAASgJAPQgKAMgPAGIAAABQAXACAPAQQAPARAAAbQAAAlgaATQgUAOgbAAIgHAAgAjCB7IAmAAQAeAAAPgQQAMgOAAgUQAAghgagMQgOgFgSAAIglAAgAjCADIAdAAQAOAAALgDQAWgMAAgcQAAgQgJgLQgMgNgaAAIgdAAgAIrCPIAAh9IiFAAIAAB9IgXAAIAAjyIAXAAIAABjICFAAIAAhjIAWAAIAADygADUCPIAAjyIB7AAIAAATIhlAAIAABPIBiAAIAAARIhiAAIAABrIBlAAIAAAUgAppCPIAAh9IiFAAIAAB9IgWAAIAAjyIAWAAIAABjICFAAIAAhjIAXAAIAADygAO1iPIASgIQAGAUAYAAQAXAAAGgUIASAIQgMAegjAAQgkAAgMgeg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-108.7,-15.2,217.5,30.5);


(lib.t5_2 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("ANkh4IAbAAIAADnIC/jzIAAExIgbAAIAAjoIi/D0gAIuh4IAcAAIAADnIC/jzIAAExIgbAAIAAjoIjAD0gAgTCIQgogsAAhDQAAhCArgsQAngsA9AAQA5AAAtAkIAAAhQgsgtg6AAQgvAAgiAlQghAnAAA2QAAA3AfAmQAhAoAyAAQA5AAAtgsIAAAhQgsAig6AAQhAAAgngtgAwmCVQgUgYgDgiIAqgJQABAWALAPQANASAXAAQAXAAANgQQALgNAAgVQAAgTgNgOQgJgJgSgIIgbgMQgagMgNgNQgSgTAAgdQAAgiAYgXQAYgVAiAAQAiAAAWAUQAOANAHARIgiAVQgEgKgJgIQgMgLgRAAQgSAAgLAJQgLAKAAAQQAAAYAeAMIAcAMQBCAYAAA9QAAAqgZAaQgaAbgoAAQgoAAgagegAG5CtIAAiXIiiAAIAACXIgbAAIAAklIAbAAIAAB4ICiAAIAAh4IAbAAIAAElgAiGCtIgnhgIh1AAIgnBgIgcAAIB+kuIB9EugAi2A1Igxh3IgyB3IBjAAgAm8CtIAAiFQgkADgbAAQg4AAgTgZQgLgOAAgiIAAhaIAbAAIAABTQAAAhALAJQANAOAoAAQAWAAAkgDIAAiIIAbAAIAAElgAsdCtIAnhaIhmjLIAfAAIBVCuIBMiuIAbAAIiAElgAOXivIAWgJQAIAZAcAAQAcAAAHgZIAWAJQgOAmgrAAQgrAAgPgmg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-108.6,-18.5,217.4,37.1);


(lib.t5_1 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AiDDQIAAg7IjDAAIAAA7IgZAAIAAhSQAbACAOggQAOgeAAg5IAAiZICdAAIAAEOIAhAAIAABSgAkMAJQAAAugGAYQgIAdgTASICHAAIAAj2IhmAAgAI5iQIAbAAIAADoIC/jzIAAEwIgbAAIAAjnIi/DzgAEEiQIAbAAIAADoIC/jzIAAEwIgbAAIAAjnIi/DzgAroBwQgqgtAAhBQAAg/AogrQAogtBCAAQAwAAAlAcQATAOAMASIgfAeQgegwg3AAQgtAAgcAgQgcAfAAAuQAAAwAdAgQAdAfApAAQAhAAAXgVQAXgVAFghIhGAAIAAgoIB0AAIAAAHQAAA5gZAmQgmA3hEAAQg8AAgpgrgACOCVIAAiVIifAAIAACVIgcAAIAAklIAcAAIAAB5ICfAAIAAh5IAbAAIAAElgAm2CVIAAklIAbAAIAAElgAJsjGIAWgJQAHAZAdAAQAcAAAIgZIAWAJQgPAmgrAAQgrAAgPgmg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-78.8,-20.9,157.6,41.8);


(lib.t4_2 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AyNDyQgxguAAhHQAAgwAZglQAagmArgNQghgRgTgdQgXghAAgsQAAhAApgrQAtgvBPAAQBOAAAtAvQAqArAABAQAAAsgXAhQgUAdghARQArANAaAmQAZAlAAAwQAABHgxAuQgzAvhTAAQhUAAgzgvgAxAA4QgXAYAAAmQAAAmAXAYQAXAYAjAAQAiAAAXgYQAXgYAAgmQAAgmgXgYQgXgZgiAAQgjAAgXAZgAw7i9QgVAWAAAiQAAAiAVAWQAUAVAhAAQAgAAAVgVQAUgWAAgiQAAgigUgWQgVgVggAAQghAAgUAVgAqwEBQgagaAAgmQAAgpAagZQAWgXAlAAQAVAAASALIAAAmQgQgTgXAAQgXAAgPASQgPARAAAYQAAAbARAQQAQAPAWAAQAWAAAPgTIAAAnQgUAKgUAAQgiAAgYgYgASgEVIAAiMIhBAAIAACMIgfAAIAAipIB/AAIAACpgAP9EVIAAiMIhBAAIAACMIgfAAIAAipIB/AAIAACpgANgEVIg5hMIgDAEIAABIIggAAIAAipIAgAAIAABHIA6hHIAoAAIhEBOIBHBbgALQEVIgOgkIhBAAIgOAkIgiAAIBGisIAXAAIBECsgAK5DXIgXg9IgXA9IAuAAgAH3EVIgOgkIhBAAIgOAkIgiAAIBGisIAXAAIBDCsgAHgDXIgXg9IgXA9IAuAAgAEBEVIAAipIAoAAQAaAAANALQAPAMAAAXQAAAXgSAKQANACAIAIQALAMAAAUQAAAVgOANQgOAOgaAAgAEgD6IAOAAQAOAAAHgFQAKgFAAgOQAAgNgMgGQgHgEgOAAIgMAAgAEgCyIAJAAQAYAAAAgWQAAgVgYAAIgJAAgACKEVIAAipIBZAAIAAAdIg6AAIAAAlIA3AAIAAAcIg3AAIAAAuIA6AAIAAAdgABGEVIAAhLIhDAAIAABLIgdAAIAAipIAdAAIAABBIBDAAIAAhBIAgAAIAACpgAiSEVIAAipIBZAAIAAAdIg5AAIAAAlIA3AAIAAAcIg3AAIAAAuIA5AAIAAAdgAjVEVIAAiMIhBAAIAACMIgfAAIAAipIB/AAIAACpgAm0EVIAXgvIg8h6IAlAAIAoBVIAihVIAjAAIhLCpgAoeEVIAAiMIgkAAIAAgdIBnAAIAAAdIgkAAIAACMgAscDpIAAgdIA+AAIAAAdg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-121.5,-28.9,243.1,58);


(lib.t4_1 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgjDbIAjheQATAdAdASQAnAYAsAAQAvAAAdgeQAdgeAAgvQAAgvgdgfQghggg5AAQg4AAgsAiIgHAAIA+khIDzAAIAABdIiuAAIgTBYQARgEARAAQBQAAAzAxQA1AyAABXQgBBWgwA2Qg3A+hnAAQhkAAhEhGgAOCESQgIgIAAgLQAAgKAIgIQAHgHAKAAQAKAAAIAHQAGAIAAAKQAAALgGAIQgIAHgKAAQgKAAgHgHgAL+EBQgZgaAAgmQAAgpAZgZQAXgXAlAAQAUAAATALIAAAmQgQgTgXAAQgXAAgPASQgPARAAAYQAAAbARAQQAQAPAVAAQAXAAAPgTIAAAnQgUAKgUAAQgiAAgZgYgAKvESQgGgFABgJQgBgIAGgGQAFgFAIAAQAIAAAFAFQAGAGAAAIQAAAJgGAFQgFAGgIAAQgIAAgFgGgAJzEVIg5hMIgDAEIAABIIgfAAIAAipIAfAAIAABHIA7hHIAnAAIhEBOIBHBbgAjlEVIAAhiIkBAAIAAgxIEFmgIBcAAIAAF6IA+AAIAABXIg+AAIAABigAltBcICIAAIAAjagAuqEVICbi6QBHhXATgaQAegyAAgnQABglgXgYQgWgXgiAAQgmAAgXAcQgVAagCAmIhqAAQAEhUA0gzQAygyBPAAQBXAAA0A3QAvAxAABIQAAA4ghA4QgSAdgtAzIhaBoIC+AAIAABdg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-94,-28.9,188,58);


(lib.t3_2 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AyPCMIAAgvIiXAAIAAAvIgWAAIAAhGQALAAAJgJQAJgIAFgOQAIgUAAglIAAhwICCAAIAADIIAYAAIAABGgAz7gSQAAAogHAVQgGAPgLAMIBrAAIAAiwIhTAAgAuviCIAYAAIAACrICVi0IAADoIgYAAIAAiqIiVC0gAR5BBQggghAAgxQAAgzAgghQAggiAyABQAygBAgAiQAgAhAAAzQAAAxggAhQggAhgyAAQgyAAggghgASYhJQgUAWAAAiQAAAgAUAWQAUAVAfABQAfgBAUgVQAUgWAAggQAAgigUgWQgUgWgfAAQgfAAgUAWgAJHBaQgTgJgLgQQgQgUAAgnIAAiIIAqAAIAACLQAAAVAKANQAMAPAWABQAVgBANgPQAKgMAAgWIAAiLIAqAAIAACIQAAAmgQAVQgMAQgTAJQgSAIgVAAQgWAAgSgIgACVBFQgaghAAg1QAAg4AaggQAXgeAiABQAigBAXAeQAZAgAAA4QAAA1gZAhQgXAdgiAAQgiAAgXgdgACzhPQgOAVAAApQAAAlAOAXQALARAQABQAQgBALgRQAOgWAAgmQAAgpgOgVQgLgSgQAAQgQAAgLASgAA5BaQgHgIAAgLQAAgLAHgHQAHgIALAAQAKAAAIAIQAHAHAAALQAAALgHAIQgIAHgKABQgLgBgHgHgAOtBdIAAjfIA1AAQAjAAARAOQAUAQAAAfQAAAcgYAQQAPADANALQAPANAAAbQAAAdgSARQgUASgiAAgAPWA5IASAAQATABAKgHQANgHAAgSQAAgTgQgHQgJgCgTAAIgQAAgAPWgkIAMAAQAhAAAAgdQAAgPgKgIQgIgGgOAAIgNAAgANdBdIg5hbIgFAAIAABbIgqAAIAAjfIA+AAQAjABATAQQAVATAAAgQAAAkgYARQgKAHgOACIBDBdgAMfgaIAMAAQApAAAAgjQAAghgpAAIgMAAgAGlBdIAAi5IgwAAIAAgmICKAAIAAAmIgwAAIAAC5gAiMBdIA/hLIAlgtQAMgVAAgPQAAgPgJgKQgJgJgOAAQgPAAgJALQgJALgBAPIgqAAQABghAVgVQAUgVAgABQAkAAAVAVQARAVAAAdQAAAWgMAXQgHAOgSARIglAqIBLAAIAAAmgAkPBdIAAhsIhuAAIAABsIgXAAIAAjfIAXAAIAABcIBuAAIAAhcIAXAAIAADfgAosBdIAbg/IhSigIAdAAIBCCCIA4iCIAaAAIhhDfgArLBdIAAjfIBhAAIAAAYIhKAAIAADHgAxYBdIAAjfIAmAAQAhAAAQAOQATAQAAAfQAAAdgVAPQAVAGALARQAJANAAASQAAAggWARQgRAPgiAAgAxABGIAbAAQAaAAALgKQAOgLAAgUQAAgXgSgIQgMgHgYAAIgYAAgAxAgfIARAAQAqAAAAgmQAAgXgSgJQgJgFgOAAIgSAAg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-134.1,-14,268.3,28.1);


(lib.t3_1 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AtEClIAAgvIiXAAIAAAvIgWAAIAAhHQAWABAMgfQAIgVgBgmIAAhuICDAAIAADHIAYAAIAABHgAuwAFQABAqgJAVQgEAOgMAMIBrAAIAAivIhTAAgANFhpIAZAAIAACqICUizIAADoIgYAAIAAiqIiVC0gAJjhpIAXAAIAACqICUizIAADoIgXAAIAAiqIiUC0gAsNhpIAYAAIAACqICUizIAADoIgXAAIAAiqIiVC0gAhpglIgVCbIgZAAIAkjrIBSC7IBRi8IAiDsIgZAAIgUibIhGCkgAIUB2IAAhuIhuAAIAABuIgYAAIAAjfIAYAAIAABbIBuAAIAAhbIAYAAIAADfgAFAB2IAAhhIgsADQgnAAgOgMQgTgOAAglIAAhCIAXAAIAAA/QAAAbANAKQAJAFAcAAQARAAAaAAIAAhpIAXAAIAADfgACDB2IAAjfIAYAAIAADfgAjHB2IgZhAIhbAAIgaBAIgaAAIBijqIBgDqgAjpAfIgkhYIglBYIBJAAgAmlB2IAAhuIhtAAIAABuIgYAAIAAjfIAYAAIAABbIBtAAIAAhbIAYAAIAADfgAN2iJQgJgIgDgLIAXgIQAFATAWAAQAWAAAFgTIAWAIQgEALgHAIQgOAOgYAAQgYAAgOgOg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-101,-16.5,202.1,33.1);


(lib.t2_2 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AKPBdIAigiQAJATARAKQAOAIAQAAQASAAALgKQAMgLAAgRQAAgQgKgKQgKgJgggLQgcgKgQgNQgVgUAAggQAAgiAUgXQAYgZApAAQAuAAAeAgIgbAmQgRgYgbAAQgTAAgKALQgIAJAAANQAAALAJAIQAHAGAZAKQAnAOAPAOQAXAUAAAlQAAApgaAaQgaAZgpAAQg5AAgjg1gAGIBqQgngpAAhBQAAhAAogpQAogoA+AAQBOAAAkBCIgtAZQgIgOgNgLQgUgRgdAAQgmAAgZAdQgYAcAAAnQAAAmAUAbQAYAfArAAQAeAAAUgNQAWgQAEgeIhFAAIAAguIB7AAIAAAIQAAA3gZAlQgkA3hGAAQg+AAgngogAAqBdIAigiQAJATARAKQAPAIAPAAQASAAAMgKQAMgLAAgRQAAgPgLgLQgJgJgggLQgdgKgPgNQgWgTAAghQAAgiAVgXQAXgZAqAAQAtAAAfAgIgcAmQgRgYgaAAQgTAAgKALQgIAJAAANQAAALAIAIQAHAGAZAKQAoAOAOAOQAXAUAAAlQAAApgZAaQgaAZgqAAQg5AAgjg1gAicCIQgYgLgOgTQgUgbAAgwIAAiqIA0AAIAACuQAAAbANAPQAOATAcAAQAbAAAQgTQAMgPAAgbIAAiuIA0AAIAACqQAAAwgUAbQgOATgXALQgXAKgbAAQgaAAgXgKgAk7CMIg6hnIg+BnIg+AAIBeiTIhPiEIA+AAIAvBXIAxhXIA+AAIhSCEIBcCTgAqcCMIAAkXICUAAIAAAvIhgAAIAAA/IBcAAIAAAtIhcAAIAABNIBgAAIAAAvgAtHCMIAAkXIA0AAIAADoIBTAAIAAAvg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-84,-14.7,168.1,29.4);


(lib.t2_1 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AO7htIAeAAIAADWIC5jhIAAEiIgdAAIAAjUIi6DhgAKfhtIAeAAIAADWIC5jhIAAEiIgdAAIAAjUIi6DhgAoiCGQgpgqAAg+QAAg8ApgqQAogpA6AAQA6AAAoApQApAqAAA8QAAA+gpAqQgoApg6AAQg6AAgogpgAoNgyQgfAiAAAuQAAAwAfAiQAgAiAtAAQAtAAAggiQAfgiAAgwQAAgugfgiQgggigtAAQgtAAggAigAxpCGQgogqAAg+QAAg8AogqQAogpA7AAQA6AAAoApQAoAqAAA8QAAA+goAqQgoApg6AAQg7AAgogpgAxTgyQggAiAAAuQAAAwAgAiQAgAiAtAAQAtAAAfgiQAggiAAgwQAAgugggiQgfgigtAAQgtAAggAigAhICqIAAgdQAHACAIAAQAPAAALgLQALgLADgWQABgMAAgeIAAimIChAAIAAEXIgeAAIAAj5IhnAAIAACVQAAAegDANQgFAbgOAQQgSARgcAAQgGAAgKgDgAI9CqIAAiJIiJAAIAACJIgeAAIAAkXIAeAAIAABwICJAAIAAhwIAdAAIAAEXgADWCqIAAkXICKAAIAAAeIhtAAIAABRIBqAAIAAAeIhqAAIAABtIBtAAIAAAdgAj/CqIAAkXIAwAAQAoAAAVASQAYATAAAnQAAAigaATQAaAHANAWQAMATAAAXQAAAmgbAXQgXASgpAAgAjhCNIAiAAQAgAAAPgMQARgOAAgZQAAgcgXgNQgOgIgfAAIgeAAgAjhANIAWAAQA1AAAAgtQAAgegXgLQgMgGgRAAIgXAAgAqfCqIAAiJIiJAAIAACJIgdAAIAAkXIAdAAIAABwICJAAIAAhwIAeAAIAAEXgAP4iVQgLgKgEgNIAcgKQAEAPAOAGQAIADAIAAQAIAAAHgDQAPgGAEgPIAcAKQgFANgKAKQgSASgdAAQgdAAgSgSg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-117,-18.3,234.2,36.7);


(lib.t1_3 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AhKggIgQB5IgTAAIAbi4IBACTIA/iTIAaC4IgSAAIgRh5Ig2CAgAnuggIgQB5IgTAAIAci4IBACTIBBiTIAaC4IgTAAIgPh5Ig6CAgAKTBCQgYgaAAgnQAAglAZgaQAZgaAlAAQAcABAWAQIAAAZQgLgLgMgFQgOgIgOAAQgcAAgUAWQgTAWAAAcQAAAhAWAUQATATAagBQAQABAPgJQAKgFAKgJIAAAYQgYARgbAAQglAAgZgagAE1BZIAAgSIAJABQAKAAAGgHQAHgHACgNIABgbIAAhnIBmAAIAACuIgTAAIAAicIhBAAIAABdQAAASgBAJQgEARgJAKQgNAKgQAAgAM8BZIAWgxIhAh9IAXAAIA0BmIArhmIAUAAIhMCugAJYBZIgTgyIhHAAIgVAyIgUAAIBNi2IBKC2gAI9AVIgchEIgdBEIA5AAgAEVBZIhFhRIgEAFIAABMIgTAAIAAiuIATAAIAABMIBHhMIAYAAIhNBSIBQBcgAjfBZIAVgxIhAh9IAXAAIA0BmIArhmIAVAAIhMCugAkzBZIAAiuIASAAIAACugAqEBZIAAiuIBXAAIAAASIhEAAIAAA0IBCAAIAAARIhCAAIAABFIBEAAIAAASgAr1BZIAAiuIAeAAQAcAAAOANQAPANAAAYQAAAVgMANQgOANgaAAIgRAAIAABNgArjgEIAPAAQARAAAJgJQAJgIAAgPQAAgfgkAAIgOAAgAszBZIAAicIhWAAIAACcIgSAAIAAiuIB7AAIAACugABiArIAAgUIA3AAIAAAUg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-92.4,-9.6,184.9,19.3);


(lib.t1_2 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("ANUCXIAAglIh2AAIAAAlIgSAAIAAg3QASABAJgZQAGgRAAgdIAAhVIBlAAIAACbIATAAIAAA3gAL/AaQAAAhgGAQQgEALgJAKIBUAAIAAiJIhBAAgAo5g7IATAAIAACEIB0iLIAAC0IgTAAIAAiDIh0CLgAHUBcQgZgaAAgnQAAglAZgaQAZgaAlAAQAdAAAVARIAAAZQgLgLgLgGQgPgHgOAAQgcAAgUAWQgTAVAAAdQAAAhAWAUQAUASAZAAQAQAAAPgIQAKgFAKgKIAAAZQgYARgbAAQglAAgYgagADUBcQgagaAAgnQAAglAagaQAZgaAkAAQAlAAAZAaQAZAaAAAlQAAAngZAaQgZAaglAAQgkAAgZgagADhgWQgUAVAAAcQAAAeAUAVQAUAVAcAAQAcAAAUgVQAUgVAAgeQAAgcgUgVQgUgWgcAAQgcAAgUAWgAhNBcQgZgaAAgnQAAglAZgaQAZgaAkAAQAjAAAZAaQAZAaAAAlQAAAngZAaQgZAagjAAQgkAAgZgagAhAgWQgTAVAAAcQAAAeATAVQAUAVAcAAQAaAAAUgVQAUgVAAgeQAAgcgUgVQgUgWgaAAQgcAAgUAWgAvLBcQgagaAAgnQAAglAagaQAZgaAkAAQAkAAAZAaQAaAaAAAlQAAAngaAaQgZAagkAAQgkAAgZgagAu+gWQgUAVAAAcQAAAeAUAVQAUAVAcAAQAcAAAUgVQAUgVAAgeQAAgcgUgVQgUgWgcAAQgcAAgUAWgA0TBcQgZgaAAgnQAAglAZgaQAZgaAmAAQAcAAAVARIAAAZQgLgLgLgGQgPgHgOAAQgcAAgUAWQgTAVAAAdQAAAhAXAUQATASAaAAQAPAAAPgIQAKgFAKgKIAAAZQgYARgaAAQglAAgZgagATWByIAWgwIhAh9IAWAAIA0BlIAshlIAUAAIhMCtgASCByIAAhVIhWAAIAABVIgSAAIAAitIASAAIAABFIBWAAIAAhFIASAAIAACtgAPuByIgUgxIhHAAIgUAxIgUAAIBMi1IBLC1gAPTAvIgchFIgdBFIA5AAgAJmByIAAitIBWAAIAAASIhEAAIAAAyIBCAAIAAATIhCAAIAABEIBEAAIAAASgABnByIAAitIBMAAIAAASIg5AAIAACbgAibByIAAhVIhVAAIAABVIgTAAIAAitIATAAIAABFIBVAAIAAhFIATAAIAACtgAmHByIAAitIAeAAQAZAAANALQAPAMAAAYQAAAVgRAMQAQAEAJAOQAHALAAAPQAAAZgRANQgOALgaAAgAl1BgIAVAAQAVAAAJgHQALgJAAgQQAAgRgPgIQgIgGgUAAIgTAAgAl1AQIAOAAQAhAAAAgbQAAgTgOgHQgIgEgKAAIgPAAgAqNByIAAibIgoAAIAAgSIBjAAIAAASIgoAAIAACbgAsVByIAAitIAeAAQAcAAAOAMQAPAOAAAYQAAATgMANQgOAPgbAAIgQAAIAABMgAsDAUIAPAAQARAAAJgJQAKgIAAgNQAAgfglAAIgOAAgAwZByIAAibIhWAAIAACbIgSAAIAAitIB6AAIAACtgAytiTIAAgDIARAAIAAADgA01iTIAAgDIASAAIAAADg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-133.4,-15.2,266.9,30.4);


(lib.t1_1 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("ApnB/IAAgiIh2AAIAAAiIgSAAIAAg0QASABAJgZQAGgOAAggIAAhVIBlAAIAACbIATAAIAAA0gAq8AFQAAAhgGAQQgEAMgIAJIBTAAIAAiJIhBAAgAk7hQIASAAIAACEIB0iLIAAC0IgSAAIAAiDIh0CLgAGRBHQgZgaAAgnQAAglAZgaQAZgaAlAAQAdAAAVARIAAAZQgLgLgLgGQgPgHgOAAQgcAAgUAWQgTAVAAAdQAAAhAWAUQAUASAZAAQAQAAAPgIQAKgFAKgKIAAAZQgYARgbAAQglAAgYgagAAJBHQgXgaAAgnQAAglAXgaQAZgaAkAAQAlAAAZAaQAZAaAAAlQAAAngZAaQgZAaglAAQgkAAgZgagAAXgrQgUAVAAAcQAAAeAUAVQATAVAcAAQAcAAAUgVQAUgVAAgeQAAgcgUgVQgUgWgcAAQgcAAgTAWgAKNBdIAAitIATAAIAABJIAWAAQA6AAAAAvQAAAZgPAOQgPAOgYAAgAKgBLIAVAAQAVAAAKgKQAJgJAAgQQAAgTgOgHQgIgFgUAAIgTAAgAI5BdIAAibIgoAAIAAgSIBjAAIAAASIgoAAIAACbgAFEBdIAAitIASAAIAACtgAC/BdIAAitIAeAAQAZAAANALQAPAMAAAYQAAAXgQAKQAQAEAJAOQAHALAAAPQAAAZgRANQgOALgaAAgADSBLIAVAAQAUAAAJgHQALgJAAgQQAAgRgOgIQgIgGgUAAIgTAAgADSgDIAOAAQAgAAAAgdQAAgTgOgHQgHgEgLAAIgOAAgAiKBdIAAitIAeAAQAZAAANALQAPAMAAAYQAAAXgQAKQAQAEAJAOQAHALAAAPQAAAZgRANQgOALgaAAgAh3BLIAVAAQAUAAAJgHQALgJAAgQQAAgRgOgIQgIgGgUAAIgTAAgAh3gDIAOAAQAgAAAAgdQAAgeggAAIgOAAgAlnBdIgUgxIhHAAIgUAxIgUAAIBNi1IBKC1gAmCAaIgchFIgcBFIA4AAgAo9BdIAAitIAfAAQAbAAAPAMQAPAOAAAYQAAAVgMALQgOAPgbAAIgQAAIAABMgAoqAAIAPAAQARAAAJgIQAJgIAAgPQAAgfgkAAIgOAAgAkVhpQgHgHgDgIIASgGQAEAPARAAQARAAAEgPIASAGQgDAIgHAHQgLALgSAAQgSAAgLgLg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-75.2,-12.7,150.5,25.5);


(lib.logo = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AkPDJQhwhOAAh7QAAh5BwhOQBthMCiAAQBGAAA+APQASAGgFAPQgBAFgMARQgWAYhDBcQhBBcgRAbQgPAVgBATQgCAXAcAAIFBAAQAWAAAIgcQAHgaAAgbQAAhNgtg5Qgsg3hNgcIATgcQBdAhA1A+QA4BCAABUQAABFgoA2QgIALgEAEQgIAFgOAAImSAAQhEgDgMgwQgLgqAhgzQAPgZA+hUQA+hVAaghQAFgIgFgEQgEgEgKAAQiNAAhaBAQhfBEAABwQAABmBfBHQBfBICIAAQBJAABBgWQA+gVAugnIA/AAQg2A1hQAdQhTAfhdAAQiiAAhthLg");
	this.shape.setTransform(-116,0);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AEVCKQgkAAghgUQgygfAAg9IAAiRIikBvIDICSIiXAAIiBhfIiPBfIsAAAQgnABgegYQgpghAAhGIAAiWIBgAAIAACfQAAA+A+AAIDaAAQATguAtggIhNAAQAIg1AwgqQA2gwBOAAIF3AAICBBfICMhfICvAAIAACfQAAA+A+AAIC3AAIAAjdIBgAAIAADdIFGAAQAhgBALgDQAQgHAAgRQAAgcgkAAIk5AAQAAhCAlguQAqg1BPAAIEYAAIAAA3IkMAAQgaAAgQASQgPAPgCAYIDjAAQA4AAAfAOQAqATAAAzQAAAxg0AUQgfALgvAAgApIAtQgUAQgCAWIFpAAIByhKIiph8IAAAgIj0AAQgaAAgWASQgUARgCAWIEjAAIAAA1IjVAAQgagBgWATg");
	this.shape_1.setTransform(43.6,0.5);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-154.4,-27.6,308.9,55.3);


(lib.lightMc1 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.light();
	this.instance.setTransform(-320,-291.5);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-320,-291.5,640,583);


(lib.img4_1 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.img4();
	this.instance.setTransform(-150,-300);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-150,-300,300,600);


(lib.img3_1 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.img3();
	this.instance.setTransform(-150,-300);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-150,-300,300,600);


(lib.img2_1 = function() {
	this.initialize();

	// img2.jpg
	this.instance = new lib.img2();
	this.instance.setTransform(-146,-207);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-146,-207,292,414);


(lib.img1_1 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.img1();
	this.instance.setTransform(-243.5,-300);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-243.5,-300,487,600);


(lib.gradient1 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["rgba(0,0,0,0)","rgba(0,0,0,0.702)"],[0.227,0.51],-64.2,-135,0,-64.2,-135,148.8).s().p("EgWyAgWMAAAhArMAtlAAAMAAABArg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-146,-207,292,414);


(lib.finalText = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AvsCVIAAhbIAKAAIAAAIQAHgKANAAQANAAAHAKQAIAJgBANQABAMgIAJQgHAJgNAAQgNAAgHgKIAAApgAvdBHQgGAHAAAKQAAAJAFAGQAGAGAJAAQAIAAAFgGQAFgGAAgJQAAgLgGgGQgGgGgHAAQgHABgGAFgALpCJIAHgVQAEgRAAgVQAAgXgEgRIgHgVIAJgDIAHAUQAGARAAAbQAAAagGARIgHAVgAHtB5QgGgRABgaQgBgbAGgRQADgMAEgIIAJADIgHAVQgEARAAAXQAAAVAEARIAHAVIgJAFQgEgJgDgMgAh9CHIAMggIAJADIgOAfgAxtCHIAMggIAJADIgOAfgAi3A6IAKAAIAAAnIAogsIAAA/IgKAAIAAgmIgoArgAj3A6IAKAAIAAAnIAogsIAAA/IgKAAIAAgmIgoArgAz3A6IALAAIAAAnIAogsIAAA/IgLAAIAAgmIgoArgAsoAzIgKBBIgKAAIAQhjIAkBQIAkhQIAPBjIgLAAIgJhBIggBFgAQjBxIA1hQIgzAAIAAgKIBFAAIg/BfgAOEBxIAVgeIgIABQgNAAgJgJQgJgJAAgNQABgNAIgKQAKgJAOAAQAPAAAKALQAHAIAAANQAAALgHAKIghAsgAODAlQgGAHAAAJQAAAJAGAHQAHAFAJAAQAJAAAHgFQAGgHAAgJQAAgJgGgHQgHgGgJAAQgKAAgGAGgATBBoQgJgOAAgUQAAgWAJgNQALgOANAAQAOAAAKAOQAJAOAAAVQAAAUgJAOQgKAOgOAAQgNAAgLgOgATJApQgHALAAASQAAARAHALQAGAKAKAAQAKAAAGgKQAHgKAAgSQAAgTgHgKQgGgKgKAAQgKAAgGAKgAR2BoQgJgOAAgUQAAgVAJgOQALgOAOAAQANAAALAOQAJAOAAAVQAAAUgJAOQgLAOgNAAQgOAAgLgOgAR+ApQgGALgBASQABARAGALQAHAKAKAAQAJAAAHgKQAGgLABgRQgBgSgGgLQgHgKgJAAQgKAAgHAKgAIQBoQgJgOAAgUQAAgVAJgOQALgOAOAAQAOAAAJAOQAKAOAAAVQAAAUgKAOQgJAOgOAAQgOAAgLgOgAIYApQgHALAAASQAAARAHALQAGAKALAAQAJAAAHgKQAGgLAAgRQAAgSgGgLQgHgKgJAAQgLAAgGAKgAEhBvQgJgJAAgOQAAgOAHgJQAIgIANgBQAOAAAIAMQAGAHAAAOIgtAAQgBAJAGAGQAGAFAHAAQAHAAAFgEQAEgDACgFIAIAEQgCAGgFADQgIAIgLAAQgMAAgIgHgAFFBRQgBgHgFgEQgEgEgHgBQgGAAgFAFQgFAEgBAHIAiAAIAAAAgAmTBtQgJgIAAgNQAAgOAJgJQAJgIANgBQAJABAJAFIAAAMQgHgIgLgBQgJAAgGAGQgGAGAAALQAAAKAGAGQAGAFAJAAQALAAAIgJIAAAMQgJAGgKAAQgNAAgJgJgAoPBtQgJgIAAgNQAAgOAJgJQAJgIANgBQANABAJAIQAJAJgBAOQABANgJAIQgJAJgNAAQgNAAgJgJgAoIBHQgFAGAAALQAAAKAGAGQAFAFAJAAQAJAAAFgFQAHgGgBgKQABgLgHgGQgFgGgJAAQgIAAgHAGgAp+BtQgIgIgBgNQABgOAIgJQAJgIAOgBQAKABAIAFIAAAMQgIgIgKgBQgJAAgGAGQgGAGAAALQAAAKAGAGQAGAFAIAAQAMAAAHgJIAAAMQgIAGgKAAQgOAAgJgJgArCBtQgJgIAAgNQAAgOAJgJQAJgIANgBQANABAJAIQAJAJAAAOQAAANgJAIQgJAJgNAAQgNAAgJgJgAq6BHQgHAGABALQAAAKAGAGQAGAFAIAAQAIAAAGgFQAGgGAAgKQAAgLgGgGQgGgGgIAAQgJAAgFAGgAGuBuQAAgCACgCQADgCACAAQAIAAAAAGQAAAIgIgBQgHABAAgIgAGTBuQAAgCACgCQADgCACAAQAIAAAAAGQAAAIgIgBQgHABAAgIgAC6BuQAAgCACgCQACgCADAAQADAAACACQACACAAACQAAAIgHgBQgHABAAgIgAFSB0IAAgJIACAAQAFAAACgDQACgEAAgGIAAgkIApAAIAAA6IgKAAIAAgwIgVAAIAAAaQABALgFAFQgGAHgIgBgAUDB0IAtg1QAFgHAAgHQAAgIgFgFQgFgFgJAAQgKAAgFAIQgDAEAAAHIgLAAQABgLAGgIQAJgKANAAQANAAAIAIQAJAIAAAMQAAAJgIALIggAlIAoAAIAAAKgAO9B0IAtg1QAFgHAAgHQAAgIgFgFQgFgFgJAAQgLAAgFAIQgCAEgBAHIgKAAQAAgMAIgHQAHgKAOAAQANAAAIAIQAJAIgBAMQABAJgIALQgGAJgHAHIgUAVIAoAAIAAAKgANTB0IAAgPIgvAAIA5hUIAABKIAMAAIAAAKIgMAAIAAAPgAM2BbIAdAAIAAgqgALJB0IAAgPIgxAAIA7hUIAABKIALAAIAAAKIgLAAIAAAPgAKrBbIAeAAIAAgqgAJ+B0IAAgPIgwAAIA6hUIAABKIAMAAIAAAKIgMAAIAAAPgAJhBbIAdAAIAAgqgAEBB0IAAhTIgYAAIAAgKIA5AAIAAAKIgYAAIAABTgAB4B0IAAhdIAuAAIAAAKIgkAAIAAAcIAMAAQAhAAAAAbQAAANgIAHQgJAIgOAAgACCBqIAMAAQAMAAAFgFQAFgEABgJQgBgJgHgFQgFgCgLgBIgLAAgAA4B0IAAgPIgwAAIA7hUIAABKIALAAIAAAKIgLAAIAAAPgAAaBbIAeAAIAAgqgAg9B0IAtg1QAGgHAAgHQAAgIgFgFQgFgFgJAAQgKAAgGAIQgCAGAAAFIgLAAQABgLAGgIQAJgKANAAQANAAAIAIQAIAIAAAMQAAAKgHAKQgHAJgGAHIgTAVIAnAAIAAAKgAkJB0IgXgaIgDAEIAAAWIgKAAIAAg6IAKAAIAAAYIAXgYIANAAIgaAaIAdAggAlgB0IAAg6IAKAAIAAAWIAKAAQAMABAGAFQAEAGABAGQgBAIgFAGQgFAEgMAAgAlWBrIAJAAQAHAAACgBQAEgCAAgGQAAgEgEgDQgCgBgHgBIgJAAgAnQB0IAAg6IAWAAQAIAAAEADQAGAFgBAGQAAAIgGAEQAFACACACQAFAFAAAGQAAAIgGAGQgFADgJAAgAnGBrIAMAAQAHAAADgBQADgDAAgEQAAgEgDgDQgDgCgGAAIgNAAgAnGBRIALAAQAEABADgCQACgDAAgDQAAgEgCgBQgDgCgGAAIgJAAgAonB0IgXgaIgDAEIAAAWIgKAAIAAg6IAKAAIAAAYIAYgYIAMAAIgZAaIAcAggAt5B0IAAgwIgTAAIAAgKIAvAAIAAAKIgSAAIAAAwgAwFB0IAAgwIgaAAIAAAwIgKAAIAAg6IAuAAIAAA6gAyeB0IAAg6IAWAAQAIAAAEADQAFAFAAAGQAAAIgGAEQAFABACADQAEAEABAHQAAAJgHAFQgEADgJAAgAyUBrIAMAAQAHAAACgBQAEgDAAgEQAAgEgDgDQgDgCgGAAIgNAAgAyUBRIAKAAQAFABACgCQADgDAAgDQAAgDgDgCQgCgCgGAAIgJAAgAy3B0IAAg6IALAAIAAA6gA0LB0IgngrIgCADIAAAoIgLAAIAAhdIALAAIAAAoIAogoIAOAAIgsAsIAtAxgAusBbIAAgKIAfAAIAAAKgAGuA/QAAgCACgCQADgCACgBQAIABAAAGQAAAIgIgBQgHABAAgIgAiyAhIAIgDQADAIAKAAQAJAAACgIIAJADQgEANgQAAQgQAAgFgNgAyvAnQAAgHAHAAQADAAACACQACADAAACQAAAHgHAAQgHAAAAgHgAzBAnQgBgHAIAAQAGAAAAAHQAAAHgGAAQgIAAABgHgAO2gRIAAhbIAKAAIAAAIQAIgJAMAAQANAAAIAJQAIAJgBAMQABANgIAJQgIAJgNAAQgMAAgIgKIAAApgAPGhfQgHAGAAAKQABAKAFAGQAGAGAIAAQAIAAAGgGQAFgHAAgJQAAgKgGgGQgGgGgHABQgIAAgFAFgAAqgRIAAhbIAKAAIAAAIQAIgJAMAAQANAAAIAJQAHAJAAAMQAAANgHAJQgIAJgNAAQgMAAgIgKIAAApgAA6hfQgHAGAAAKQABAKAFAGQAFAGAJAAQAIAAAGgGQAFgHAAgJQAAgKgGgGQgFgGgJABQgHAAgFAFgAmhgRIAAhbIAKAAIAAAIQAIgJAMAAQANAAAIAJQAIAJgBAMQABANgIAJQgIAJgNAAQgMAAgIgKIAAApgAmRhfQgHAGABAKQAAAKAFAGQAFAGAJAAQAIAAAGgGQAFgHAAgJQAAgKgGgGQgFgGgIABQgIAAgFAFgAx/gRIAAggQgQAAgIgHQgLgJAAgOQAAgPALgHQAIgIAQAAIAAgiIAKAAIAAAiQAPAAAKAIQAKAHAAAPQAAAOgKAJQgJAHgQAAIAAAggAx1g6QAKABAGgFQAJgGgBgLQAAgLgIgHQgGgDgKAAgAyOhhQgJAHAAALQAAALAIAGQAHAFAJgBIAAgqQgKAAgFADgApogjIAAgPIgsAAIAAAPIgJAAIAAgYQAHAAAEgHQACgGAAgKIAAgaIApAAIAAAxIAJAAIAAAYgAqGhNQAAALgHAHIAcAAIAAgoIgVAAgAv3gjIAAgPIgvAAIAAg6IAKAAIAAAxIAaAAIAAgxIAKAAIAAAxIAKAAIAAAYgAIBhsIAKAAIAAAmIAogrIAAA/IgKAAIAAgnIgoAsgAlXhsIAJAAIAAAmIApgrIAAA/IgLAAIAAgnIgnAsgApUhsIAKAAIAAAmIAogrIAAA/IgKAAIAAgnIgoAsgAr6hsIALAAIAAAmIAngrIAAA/IgKAAIAAgnIgoAsgAs+hsIAKAAIAAAmIAngrIAAA/IgKAAIAAgnIgnAsgAvGhsIAKAAIAAAmIAngrIAAA/IgKAAIAAgnIgnAsgASug4QgJgIABgPQgBgPAJgHQAIgJAMABQAMgBAIALIAAgJIAKAAIAAA6IgKAAIAAgIQgHAKgNAAQgMAAgIgIgAS2hfQgGAGAAAKQAAAJAFAHQAFAGAJAAQAJAAAFgGQAGgHgBgJQAAgKgGgHQgGgEgHAAQgIgBgFAGgAQFg4QgJgIAAgPQAAgPAJgHQAHgJANABQALgBAIALIAAgJIAKAAIAAA6IgKAAIAAgIQgHAKgMAAQgNAAgHgIgAQNhfQgHAGABAKQAAAJAEAHQAFAGAJAAQAKAAAFgGQAFgHAAgJQAAgKgHgHQgFgEgIAAQgIgBgEAGgALEg4QgIgIAAgPQAAgPAIgHQAJgJALABQAMgBAJALIAAgJIAKAAIAAA6IgKAAIAAgIQgJAKgMAAQgLAAgJgIgALMhfQgFAGgBAKQABAJAFAHQAFAGAIAAQAJAAAGgGQAFgHAAgJQAAgKgGgHQgGgEgIAAQgIgBgFAGgAJLg4QgJgKAAgNQAAgNAJgIQAJgKANABQANgBAJAKQAJAIgBANQABANgJAKQgJAIgNAAQgNAAgJgIgAJShfQgFAGAAAKQAAALAGAGQAFAFAJAAQAIAAAGgFQAHgGgBgLQABgKgHgGQgGgGgIABQgIgBgHAGgAG9g4QgJgKAAgNQAAgNAJgIQAIgKANABQAOgBAJAKQAJAIAAANQAAANgJAKQgJAIgOAAQgNAAgIgIgAHFhfQgHAGAAAKQAAALAHAGQAGAFAHAAQAJAAAGgFQAGgGAAgLQAAgKgGgGQgGgGgJABQgIgBgFAGgAgZg4QgIgKAAgNQAAgNAIgIQAKgKANABQALgBAJAKQAJAIgBANQABANgJAKQgJAIgLAAQgNAAgKgIgAgRhfQgGAGAAAKQAAALAGAGQAHAFAIAAQAGAAAFgFQAHgGAAgLQAAgKgGgGQgGgGgGABQgJgBgGAGgAiUg7QgGgIgBgIIgJAAIAAAZIgLAAIAAg6IALAAIAAAYIAKAAQABgLAHgFQAHgKAOABQAOgBAJAKQAJAIAAANQAAANgJAKQgJAIgOAAQgPAAgIgLgAiKhfQgHAGAAAKQABALAGAGQAGAFAHAAQAJAAAGgFQAGgGAAgLQAAgKgGgGQgGgGgJABQgIAAgFAFgAkNg3QgJgKAAgVQAAgjAQgNQAGgDAOgEQAKgCADgFIALAAQgEAMgPAEQgQAEgDACQgMAKAAARQAHgLAPABQANgBAIAKQAIAIAAANQAAANgIAJQgJAJgOAAQgMAAgJgHgAkGhfQgGAGAAAKQAAALAGAGQAHAFAIAAQAIAAAFgFQAHgGAAgLQAAgKgGgGQgGgGgIABQgJgBgGAGgAoKg4QgIgKgBgNQABgNAIgIQAJgKAOABQAIAAAKAFIAAANQgIgKgKABQgKgBgFAGQgHAGAAAKQAAALAHAGQAGAFAIAAQAMAAAHgJIAAAMQgJAGgJAAQgOAAgJgIgA0Bg+QgOgNgBgWQABgUAOgOQAOgOAUAAQAVAAANAOQAOAOAAAUQAAAWgOANQgNAOgVAAQgUAAgOgOgAz6h8QgLAMAAAPQAAAQALAMQALALAQAAQAQAAALgLQALgMAAgQQAAgPgLgMQgLgLgQAAQgQAAgLALgASMgyIAAgZIgbAAIAAAZIgKAAIAAg6IAKAAIAAAYIAbAAIAAgYIAKAAIAAA6gARJgyIAAg6IAKAAIAAA6gAOfgyIgWgZIgEADIAAAWIgKAAIAAg6IAKAAIAAAYIAXgYIANAAIgZAaIAcAggANDgyIAMgaIgkhDIANAAIAcA3IAZg3IALAAIgqBdgAKZgyIAAgxIgTAAIAAgJIAvAAIAAAJIgSAAIAAAxgAGTgyIAAhUIgWAAIAAgJIA4AAIAAAJIgXAAIAABUgAEWgyIAAhdIAKAAIAABdgADzgyIAAhdIALAAIAABdgADRgyIAAhUIgwAAIAABUIgLAAIAAhdIBGAAIAABdgAhEgyIAAgxIgSAAIAAgJIAuAAIAAAJIgSAAIAAAxgAnIgyIAAgxIgSAAIAAgJIAvAAIAAAJIgTAAIAAAxgAtcgyIAAgZIgbAAIAAAZIgLAAIAAg6IALAAIAAAYIAbAAIAAgYIALAAIAAA6gAvjgyIAAg6IAKAAIAAA6gAxDgyIAAg6IAKAAIAAA6gAMFhKIAAgLIAgAAIAAALgAUGhqIgBglIALAAIgCAlgATyhqIgBglIALAAIgCAlgAFqhqIgCglIAMAAIgDAlgAFWhqIgCglIALAAIgCAlgAjJhqIgCglIALAAIgBAlgAIGiFIAJgDQABAIAKAAQAJAAADgIIAIADQgEAOgQAAQgPAAgFgOgAr1iFIAIgDQADAIAJAAQAKAAADgIIAIADQgEAOgRAAQgPAAgFgOgAvBiFIAIgDQACAIAKAAQAKAAACgIIAJADQgFAOgQAAQgPAAgFgOgARQh/QAAgDACgCQADgCADAAQAGAAABAHQgBAHgGAAQgIAAAAgHgAQ+h/QAAgDACgCQACgCADAAQAHAAAAAHQAAAHgHAAQgHAAAAgHgAvmiCQAAgDADgCQACgCACAAQAIAAAAAHQAAAHgIAAQgGAAgBgHgAxFiCQAAgHAHAAQAIAAgBAHQABAHgIAAQgHAAAAgHg");
	this.shape.setTransform(0,157.1,1.004,1.005);

	// Слой 2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ag6g5IAQAAIAABwIBlh2IAACZIgQAAIAAhwIhlB3gAghhbIAPgFQAEANAOAAQAOAAAFgNIAPAFQgIAWgaAAQgZAAgIgWg");
	this.shape_1.setTransform(131.4,-68);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ag6hJIAQAAIAABwIBlh3IAACaIgQAAIAAhwIhlB3g");
	this.shape_2.setTransform(115.5,-66.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAmBKIAAhJIhLAAIAABJIgQAAIAAiTIAQAAIAAA8IBLAAIAAg8IAQAAIAACTg");
	this.shape_3.setTransform(100.2,-66.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("Ag6g5IAQAAIAABwIBlh2IAACZIgQAAIAAhwIhlB3gAgZhPQgGgFgCgHIAPgFQAEANAOAAQAPgBAEgMIAPAFQgIAWgaAAQgPAAgKgKg");
	this.shape_4.setTransform(84.9,-68);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgHBKIAAiTIAPAAIAACTg");
	this.shape_5.setTransform(74.2,-66.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAuBaIAAggIhrAAIAAiTIAQAAIAACEIBKAAIAAiEIAQAAIAACEIARAAIAAAvg");
	this.shape_6.setTransform(64.9,-64.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgHBKIAAiTIAPAAIAACTg");
	this.shape_7.setTransform(54,-66.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgHBNIAAgVIgDAAQgmAAgRgUQgOgPAAgVQAAgXAOgQQARgTAmAAIADAAIAAgSIAPAAIAAASIAEAAQAmAAARATQANAPAAAYQAAAVgNAPQgRAUgmAAIgEAAIAAAVgAAIAoIAFAAQAbABANgOQALgMgBgPQABgRgLgMQgNgNgbAAIgFAAgAg0gdQgKAMAAARQAAAPAKAMQANAOAcgBIAEAAIAAhSIgEAAQgcAAgNANg");
	this.shape_8.setTransform(42.1,-66.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("Ag2A3QgWgXAAggQAAggAWgWQAXgWAfAAQAgAAAWAWQAXAWAAAgQAAAggXAXQgWAWggAAQgfAAgXgWgAgpgqQgSASAAAYQAAAZASASQARASAYAAQAZAAARgSQASgSAAgZQAAgYgSgSQgRgSgZAAQgYAAgRASg");
	this.shape_9.setTransform(24.1,-66.4);

	this.addChild(this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-135,-77.8,272.4,249.9);


(lib.dillers = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AEINIIAAk7IAUAAIAAAiQAdgnAxABQAsgBAbAeQAaAdgBAsQAAAtgaAeQgbAfgsAAQgzABgagpIAACXgAEzIwQgYAXAAAnQAAAnAUAYQAVAaAkAAQAlAAAVgaQAUgYAAgmQAAgngXgYQgWgVggAAQggAAgWAVgAnTMJIAAg1IioAAIAAA1IgTAAIAAhIQAZgBAMgZQAIgRAAgkIAAhlICDAAIAAC0IAdAAIAABIgApNJ3QAAA1gZAVIB1AAIAAiiIhcAAgAmYINIAUAAIAACfICMirIAADTIgTAAIAAieIiNCqgAArK8QgagdAAgtQAAgyAegdQAbgbAoABQApgBAaAeQAcAegCAvIiqAAQgCAkAaAZQAWAXAhAAQAYAAASgNQARgLALgWIAQAKQgLAVgTAOQgYATghAAQgtAAgbgdgAC7JhQgEgfgUgTQgVgUgcAAQgeAAgVAUQgUATgEAfICUAAIAAAAgAjQLUIAAgTIAGACQARAAAJgOQAHgLAAgYIAAiFICDAAIAADHIgUAAIAAi1IhcAAIAABzQAAAigLAPQgOASgYAAgAJdLUIAAjHIBBAAQAbAAAPAMQASAOAAAYQAAAcgWANQANACALAKQASAOgBAZQABAcgVAPQgRAOgfAAgAJwLBIA5AAQAWAAAMgJQAOgKAAgTQAAgSgNgKQgMgJgXAAIg5AAgAJwJkIAuAAQASAAAKgJQAMgKAAgQQAAgRgMgJQgKgHgSgBIguAAgAIELUIAAjHIATAAIAADHgAIBHXQgFgEAAgJQAAgHAFgFQAGgGAGAAQAIAAAFAGQAFAFAAAHQAAAJgFAEQgFAGgIAAQgHAAgFgGgAw2GsIAxhyIhejLIAWAAIBUCyIBIiyIAWAAIiEE9gAmaGpIAAhvQg1AAgggaQgjgdAAgyQAAgxAjgdQAfgaA2AAIAAh2IAjAAIAAB2QA3AAAfAaQAjAdAAAxQgBAygiAdQgiAag0AAIAABvgAl3CIIAACTQAhABAXgPQAdgVAAgnQAAgqgfgSQgUgNgcAAIgGAAgAnQCVQgeASAAAqQAAAnAcAVQAXAPAhgBIAAiTIgGAAQgcAAgUANgAA8FtIAAg2IigAAIAAjLIAjAAIAACqIBZAAIAAiqIAjAAIAACqIAgAAIAABXgAK9BsIAjAAIAACGICKiWIAADbIgjAAIAAiHIiKCVgADmBsIAjAAIAACGICKiWIAADbIgjAAIAAiHIiKCVgArzEfQgegfAAguQAAguAegeQAfgeAuAAQAuAAAfAeQAeAeAAAuQAAAugfAfQgeAdguAAQguAAgfgdgArYCaQgVAVAAAjQAAAkAWAVQAUASAdABQAdgBAUgSQAWgVAAgkQAAgjgWgWQgTgSgeAAQgegBgUAUgAQ5E3IhAhTIg/BTIgrAAIBWhsIhJhfIAqAAIA0BFIA1hFIAsAAIhKBfIBTBsgAJYE3IAAhXIhgAAIAABXIgjAAIAAjLIAjAAIAABTIBgAAIAAhTIAjAAIAADLgACAE3IAAjLIAjAAIAADLgAjJE3IAAjLIAjAAIAADLgAESA3QgTgNgHgVIAdgMQAIAeAhAAQAhAAAJgeIAcAMQgHAVgTANQgTAOgZAAQgZAAgTgOgACAAyQgGgIAAgKQAAgKAGgIQAIgHAKAAQALAAAHAHQAHAIAAAKQAAAKgHAIQgHAGgLAAQgKAAgIgGgAjJAyQgIgIABgKQgBgKAIgIQAHgHAKAAQAKAAAIAHQAHAIAAAKQAAAKgHAIQgIAGgKAAQgKAAgHgGgAHHh9QgagdABgtQAAgxAdgeQAcgaAmAAQApAAAbAdQAcAfgBAvIiqAAQgCAkAZAZQAXAWAhAAQAXABASgNQASgNAKgUIAQAJQgdA3g6AAQgtAAgbgegAJXjYQgEgegUgUQgUgTgegBQgdAAgUAVQgUATgFAeICUAAIAAAAgApIh4QgjggAAhKQAAh5A+goQAQgKAXgGIAngJQAUgEAKgGQAKgGADgJIAYAAQgJAWgWAMQgOAHgbAFQgwAKgVARQgXATgLAhQgKAcgCAgIABAAQALgaAagOQAXgMAbAAQAtAAAcAdQAcAdgBAuQABAwgfAdQgdAcgtAAQgqAAgbgZgAo/kCQgVAYAAAiQAAAhATAYQAVAdApAAQAqABAXgdQATgYAAgiQAAgigUgZQgWgbgmAAQgnABgZAbgAknhkIAAgTIAIABQAQAAAKgOQAGgKABgYIAAiFICBAAIAADHIgSAAIAAi1IhcAAIAABzQAAAggMARQgMARgaABgACAhkIAAjHIAUAAIAAC0IBdAAIAAi0IATAAIAAC0IBcAAIAAi0IAUAAIAADHgAg2hkIAAjHIATAAIAABTIAtAAQAjAAAQASQAOAOAAAZQAAAcgSAPQgQAQgfAAgAgjh3IAtAAQAUAAALgJQANgKAAgVQABgUgOgKQgMgJgUAAIgsAAgAlhhkIAAjHIAUAAIAADHgAlklhQgEgFAAgIQAAgIAEgFQAGgFAHAAQAIAAAEAFQAFAGABAHQgBAIgFAFQgEAFgIAAQgHAAgGgFgAsFnBIAAhBIjyAAIAABBIgUAAIAAhUQARAAANgNQANgMAJgTQALgdAAg5IAAiwIC3AAIAAEyIAlAAIAABUgAu3qXQAAA7gLAgQgJAXgQAQICxAAIAAkfIiNAAgAAsrJIATAAIAACfICOiqIAADSIgUAAIAAifIiNCrgAKzoaQgcgeAAgsQAAguAbgdQAdgeAugBQAnABAeAZIAAAaQgdghgoAAQgkAAgXAZQgXAYAAAmQAAAoAbAYQAXAVAgAAQAnAAAggkIAAAaQgeAcgqAAQgtAAgcgdgAHFobQgZgdAAgsQAAgyAegdQAbgaAngBQApABAbAdQAbAegBAvIiqAAQgCAlAZAYQAXAXAhAAQAXAAASgNQASgMAKgVIAQAKQgcA2g7AAQgtAAgbgegAJVp1QgEgfgTgTQgVgUgdAAQgdAAgVAUQgVAUgDAeICTAAIAAAAgAi8oZQgdgdAAgvQAAgvAagdQAbgdArAAQAyABAbAmIAAgiIAUAAIAADHIgUAAIAAgjQgaAogzAAQgoAAgbgcgAitqlQgYAYAAAmQAAAkAUAZQAWAbAkAAQAjAAAWgbQATgZAAgkQAAgogagYQgVgUgeAAQggAAgVAWgAphoLQgQgNgIgRIARgLQAHAPAOALQAQALAWAAQAZAAAMgLQAQgMAAgXQAAgTgOgKQgLgJgZAAIgVAAIAAgSIAQAAQASAAALgJQAMgJAAgQQAAgPgKgLQgLgKgTAAQgeAAgQAcIgQgLQATgkArAAQAdAAAPAPQAQANAAAZQAAAegXAMQANADALAKQAOAOgBAYQAAAfgWASQgVAOgeAAQgeAAgWgOgAPdoCIAAhWIgjAAIg+BWIgXAAIA/hXQgXgBgQgOQgQgOgBgZQAAgdASgPQARgOAfAAIBCAAIAADHgAOOqtQgNAMAAARQAAASAMALQALAIAWAAIAvAAIAAhLIgvAAQgUAAgMAJgAE5oCIAAi0IhGAAIAAgTICeAAIAAATIhFAAIAAC0gAknoCIAAhdIhvAAIAABdIgUAAIAAjHIAUAAIAABYIBvAAIAAhYIAUAAIAADHgArGoCIAAjHIATAAIAADHgABCsZIARgIQAEAPAMAKQAMAKASAAQATAAANgKQALgKAFgPIAQAIQgPAtgxABQgvgBgQgtgArJr+QgFgFAAgJQAAgHAFgFQAGgGAGAAQAIAAAFAGQAFAFAAAHQAAAJgFAFQgFAFgIAAQgHAAgFgFg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-112.4,-84.1,224.9,168.2);


(lib.bg = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("EgXbAu3MAAAhdtMAu3AAAMAAABdtg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-150,-300,300,600);


(lib.lightMc = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 3
	this.instance = new lib.lightMc1();
	this.instance.setTransform(36.1,-1.4);
	this.instance.compositeOperation = "lighter";

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:0.012},20).to({alpha:1},20).wait(1));

	// Слой 1
	this.instance_1 = new lib.lightMc1();
	this.instance_1.setTransform(36.1,-1.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(41));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-283.9,-292.9,640,583);


(lib.light_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.lightMc();

	this.timeline.addTween(cjs.Tween.get(this.instance).to({rotation:360},179).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-283.9,-292.9,640,583);


(lib.banner = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// finText
	this.instance = new lib.finalText();
	this.instance.setTransform(2,104);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(404).to({_off:false},0).to({alpha:1},10).wait(35).to({alpha:0},10).to({_off:true},1).wait(10));

	// logo
	this.instance_1 = new lib.logo();
	this.instance_1.setTransform(66,277.2,0.474,0.474);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(394).to({scaleX:0.91,scaleY:0.91,x:0,y:-2.3},10).wait(55).to({scaleX:0.47,scaleY:0.47,x:66,y:277.2},10).wait(1));

	// dillers
	this.instance_2 = new lib.dillers();
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(354).to({_off:false},0).wait(1).to({alpha:0.021},0).wait(1).to({alpha:0.087},0).wait(1).to({alpha:0.196},0).wait(1).to({alpha:0.34},0).wait(1).to({alpha:0.505},0).wait(1).to({alpha:0.669},0).wait(1).to({alpha:0.81},0).wait(1).to({alpha:0.916},0).wait(1).to({alpha:0.979},0).wait(1).to({alpha:1},0).wait(25).to({alpha:0},10).to({_off:true},1).wait(70));

	// bg
	this.instance_3 = new lib.bg();
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(344).to({_off:false},0).to({alpha:0.801},15).wait(100).to({alpha:0},10).wait(1));

	// t6_3
	this.instance_4 = new lib.t6_3();
	this.instance_4.setTransform(-286,-108.2);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(304).to({_off:false},0).to({x:0},10,cjs.Ease.get(1)).wait(30).to({x:264},10,cjs.Ease.get(-1)).to({_off:true},1).wait(115));

	// t6_2
	this.instance_5 = new lib.t6_2();
	this.instance_5.setTransform(-285.3,-145.3);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(299).to({_off:false},0).to({x:0.8},10,cjs.Ease.get(1)).wait(35).to({x:264.7},10,cjs.Ease.get(-1)).to({_off:true},1).wait(115));

	// t6_1
	this.instance_6 = new lib.t6_1();
	this.instance_6.setTransform(-286.5,-187);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(294).to({_off:false},0).to({x:-0.5},10,cjs.Ease.get(1)).wait(40).to({x:263.5},10,cjs.Ease.get(-1)).to({_off:true},1).wait(115));

	// img4
	this.instance_7 = new lib.img4_1();
	this.instance_7.alpha = 0.012;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(279).to({_off:false},0).to({alpha:1},15).wait(165).to({alpha:0},10).wait(1));

	// t5_2
	this.instance_8 = new lib.t5_2();
	this.instance_8.setTransform(-286.8,-137.4);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(239).to({_off:false},0).to({x:2.2},10,cjs.Ease.get(1)).to({_off:true},45).wait(176));

	// t5_1
	this.instance_9 = new lib.t5_1();
	this.instance_9.setTransform(-321.2,-183.1);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(234).to({_off:false},0).to({x:-32.1},10,cjs.Ease.get(1)).to({_off:true},50).wait(176));

	// img3
	this.instance_10 = new lib.img3_1();
	this.instance_10.alpha = 0.012;
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(219).to({_off:false},0).to({alpha:1},15).to({_off:true},60).wait(176));

	// t3_2
	this.instance_11 = new lib.t3_2();
	this.instance_11.setTransform(-315.9,-119.8);
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(120).to({_off:false},0).to({x:0},10,cjs.Ease.get(1)).to({_off:true},104).wait(236));

	// t3_1
	this.instance_12 = new lib.t3_1();
	this.instance_12.setTransform(-315.9,-160.7);
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(115).to({_off:false},0).to({x:0},10,cjs.Ease.get(1)).to({_off:true},109).wait(236));

	// t2_2
	this.instance_13 = new lib.t2_2();
	this.instance_13.setTransform(-361.9,-109.1);
	this.instance_13._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(65).to({_off:false},0).to({x:-46},10,cjs.Ease.get(1)).wait(30).to({x:238.1},10,cjs.Ease.get(1)).to({_off:true},1).wait(354));

	// t2_1
	this.instance_14 = new lib.t2_1();
	this.instance_14.setTransform(-329.9,-160.2);
	this.instance_14._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(60).to({_off:false},0).to({x:-14},10,cjs.Ease.get(1)).wait(35).to({x:270.1},10,cjs.Ease.get(1)).to({_off:true},1).wait(354));

	// t1_3
	this.instance_15 = new lib.t1_3();
	this.instance_15.setTransform(-352.5,-112.7);
	this.instance_15._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_15).wait(10).to({_off:false},0).to({x:-36.6},10,cjs.Ease.get(1)).wait(30).to({x:247.5},10,cjs.Ease.get(1)).to({_off:true},1).wait(409));

	// t1_2
	this.instance_16 = new lib.t1_2();
	this.instance_16.setTransform(-313.4,-145.3);
	this.instance_16._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_16).wait(5).to({_off:false},0).to({x:2.5},10,cjs.Ease.get(1)).wait(35).to({x:286.6},10,cjs.Ease.get(1)).to({_off:true},1).wait(409));

	// t1_1
	this.instance_17 = new lib.t1_1();
	this.instance_17.setTransform(-371.6,-173.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_17).to({x:-55.7},10,cjs.Ease.get(1)).wait(40).to({x:228.4},10,cjs.Ease.get(1)).to({_off:true},1).wait(409));

	// light
	this.instance_18 = new lib.light_1();
	this.instance_18.setTransform(-149.9,179.4,0.01,0.01);
	this.instance_18._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_18).wait(130).to({_off:false},0).to({scaleX:1,scaleY:1,x:-140,y:179},29).to({_off:true},75).wait(236));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_130 = new cjs.Graphics().p("AgRARQgIgHABgKQgBgJAIgIQAIgIAJAAQAKAAAIAIQAIAIgBAJQABAKgIAHQgIAJgKgBQgJABgIgJg");
	var mask_graphics_131 = new cjs.Graphics().p("AhQBQQghgiAAguQAAguAhgiQAjghAtAAQAvAAAhAhQAiAiAAAuQAAAugiAiQghAigvAAQgtAAgjgig");
	var mask_graphics_132 = new cjs.Graphics().p("AiOCPQg7g8AAhTQAAhTA7g7QA8g7BSAAQBTAAA8A7QA7A7AABTQAABTg7A8Qg8A7hTAAQhSAAg8g7g");
	var mask_graphics_133 = new cjs.Graphics().p("AjNDNQhVhVAAh4QAAh4BVhVQBWhVB3AAQB4AABWBVQBVBVAAB4QAAB4hVBVQhWBWh4AAQh3AAhWhWg");
	var mask_graphics_134 = new cjs.Graphics().p("AkLEMQhvhwAAicQAAicBvhvQBvhvCcAAQCcAABwBvQBvBvAACcQAACchvBwQhwBvicAAQicAAhvhvg");
	var mask_graphics_135 = new cjs.Graphics().p("AlJFKQiKiJAAjBQAAjBCKiJQCJiJDAABQDCgBCICJQCJCJAADBQAADBiJCJQiICJjCABQjAgBiJiJg");
	var mask_graphics_136 = new cjs.Graphics().p("AmIGJQijijAAjmQAAjlCjijQCjijDlAAQDmAACjCjQCjCjAADlQAADmijCjQijCjjmAAQjlAAijijg");
	var mask_graphics_137 = new cjs.Graphics().p("AnHHIQi9i9AAkLQAAkKC9i8QC9i9EKAAQELAAC9C9QC9C8AAEKQAAELi9C9Qi9C9kLAAQkKAAi9i9g");
	var mask_graphics_138 = new cjs.Graphics().p("AoFIGQjXjXAAkvQAAkuDXjXQDXjXEuAAQEvAADXDXQDXDXAAEuQAAEvjXDXQjXDXkvAAQkuAAjXjXg");
	var mask_graphics_139 = new cjs.Graphics().p("ApEJEQjwjwAAlUQAAlTDwjxQDxjwFTAAQFUAADxDwQDwDxAAFTQAAFUjwDwQjxDxlUAAQlTAAjxjxg");
	var mask_graphics_140 = new cjs.Graphics().p("AqCKDQkLkLAAl4QAAl4ELkKQELkLF3AAQF4AAELELQELEKAAF4QAAF4kLELQkLELl4AAQl3AAkLkLg");
	var mask_graphics_141 = new cjs.Graphics().p("ArALBQklkkAAmdQAAmcElklQEkkkGcAAQGdAAElEkQEkElAAGcQAAGdkkEkQklElmdAAQmcAAkkklg");
	var mask_graphics_142 = new cjs.Graphics().p("Ar/L/Qk+k+gBnBQABnBE+k/QE/k9HAAAQHBAAE/E9QE+E/ABHBQgBHBk+E+Qk/FAnBgBQnAABk/lAg");
	var mask_graphics_143 = new cjs.Graphics().p("As+M+QlYlYAAnmQAAnmFYlYQFZlYHlAAQHmAAFYFYQFZFYAAHmQAAHmlZFYQlYFZnmAAQnlAAlZlZg");
	var mask_graphics_144 = new cjs.Graphics().p("At8N9QlylyAAoLQAAoKFylyQFylyIKAAQILAAFyFyQFyFyAAIKQAAILlyFyQlyFyoLAAQoKAAlylyg");
	var mask_graphics_145 = new cjs.Graphics().p("Au7O8QmMmMAAowQAAovGMmMQGMmMIvAAQIwAAGMGMQGMGMAAIvQAAIwmMGMQmMGMowAAQovAAmMmMg");
	var mask_graphics_146 = new cjs.Graphics().p("Av5P6QmmmmAApUQAApTGmmmQGmmmJTAAQJUAAGmGmQGmGmAAJTQAAJUmmGmQmmGmpUAAQpTAAmmmmg");
	var mask_graphics_147 = new cjs.Graphics().p("Aw4Q5QnAnAAAp5QAAp4HAnAQHAm/J4AAQJ5AAHAG/QHAHAAAJ4QAAJ5nAHAQnAG/p5AAQp4AAnAm/g");
	var mask_graphics_148 = new cjs.Graphics().p("Ax2R3QnanaAAqdQAAqcHanbQHZnZKdAAQKdAAHbHZQHZHbAAKcQAAKdnZHaQnbHaqdAAQqdAAnZnag");
	var mask_graphics_149 = new cjs.Graphics().p("Ay1S2Qnzn0AArCQAArBHzn0QH0nzLBAAQLCAAH0HzQHzH0AALBQAALCnzH0Qn0HzrCAAQrBAAn0nzg");
	var mask_graphics_150 = new cjs.Graphics().p("AzzT0QoOoNAArnQAArmIOoNQINoOLmAAQLnAAINIOQIOINAALmQAALnoOINQoNIOrnAAQrmAAoNoOg");
	var mask_graphics_151 = new cjs.Graphics().p("A0yUzQonooAAsLQAAsLInonQIoonMKAAQMLAAIoInQInInAAMLQAAMLonIoQooInsLAAQsKAAooong");
	var mask_graphics_152 = new cjs.Graphics().p("A1wVxQpCpBABswQgBsvJCpCQJBpBMvAAQMwAAJCJBQJAJCABMvQgBMwpAJBQpCJBswAAQsvAApBpBg");
	var mask_graphics_153 = new cjs.Graphics().p("A2vWwQpbpcAAtUQAAtUJbpbQJbpbNUAAQNUAAJcJbQJbJbAANUQAANUpbJcQpcJbtUAAQtUAApbpbg");
	var mask_graphics_154 = new cjs.Graphics().p("A3tXuQp2p0ABt6QgBt4J2p1QJ0p1N5AAQN5AAJ1J1QJ2J1gBN4QABN6p2J0Qp1J2t5gBQt5ABp0p2g");
	var mask_graphics_155 = new cjs.Graphics().p("A4sYtQqPqPAAueQAAudKPqPQKPqPOdAAQOeAAKPKPQKPKPAAOdQAAOeqPKPQqPKPueAAQudAAqPqPg");
	var mask_graphics_156 = new cjs.Graphics().p("A5qZsQqpqpAAvDQAAvBKpqpQKoqpPCAAQPDAAKoKpQKpKpAAPBQAAPDqpKpQqoKovDAAQvCAAqoqog");
	var mask_graphics_157 = new cjs.Graphics().p("A6paqQrDrDAAvnQAAvmLDrDQLDrDPmAAQPnAALDLDQLDLDAAPmQAAPnrDLDQrDLDvnAAQvmAArDrDg");
	var mask_graphics_158 = new cjs.Graphics().p("A7oboQrcrcAAwMQAAwKLcreQLdrcQLAAQQMAALcLcQLdLeAAQKQAAQMrdLcQrcLdwMAAQwLAArdrdg");
	var mask_graphics_159 = new cjs.Graphics().p("A8mcnQr2r3AAwwQAAwwL2r2QL3r2QvgBQQxABL2L2QL3L2gBQwQABQwr3L3Qr2L3wxAAQwvAAr3r3g");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(130).to({graphics:mask_graphics_130,x:-149.9,y:179.4}).wait(1).to({graphics:mask_graphics_131,x:-149.5,y:179.4}).wait(1).to({graphics:mask_graphics_132,x:-149.2,y:179.4}).wait(1).to({graphics:mask_graphics_133,x:-148.9,y:179.4}).wait(1).to({graphics:mask_graphics_134,x:-148.5,y:179.4}).wait(1).to({graphics:mask_graphics_135,x:-148.2,y:179.4}).wait(1).to({graphics:mask_graphics_136,x:-147.8,y:179.3}).wait(1).to({graphics:mask_graphics_137,x:-147.5,y:179.3}).wait(1).to({graphics:mask_graphics_138,x:-147.2,y:179.3}).wait(1).to({graphics:mask_graphics_139,x:-146.8,y:179.3}).wait(1).to({graphics:mask_graphics_140,x:-146.5,y:179.3}).wait(1).to({graphics:mask_graphics_141,x:-146.1,y:179.3}).wait(1).to({graphics:mask_graphics_142,x:-145.8,y:179.3}).wait(1).to({graphics:mask_graphics_143,x:-145.4,y:179.2}).wait(1).to({graphics:mask_graphics_144,x:-145.1,y:179.2}).wait(1).to({graphics:mask_graphics_145,x:-144.8,y:179.2}).wait(1).to({graphics:mask_graphics_146,x:-144.4,y:179.2}).wait(1).to({graphics:mask_graphics_147,x:-144.1,y:179.2}).wait(1).to({graphics:mask_graphics_148,x:-143.7,y:179.2}).wait(1).to({graphics:mask_graphics_149,x:-143.4,y:179.1}).wait(1).to({graphics:mask_graphics_150,x:-143.1,y:179.1}).wait(1).to({graphics:mask_graphics_151,x:-142.7,y:179.1}).wait(1).to({graphics:mask_graphics_152,x:-142.4,y:179.1}).wait(1).to({graphics:mask_graphics_153,x:-142,y:179.1}).wait(1).to({graphics:mask_graphics_154,x:-141.7,y:179.1}).wait(1).to({graphics:mask_graphics_155,x:-141.4,y:179.1}).wait(1).to({graphics:mask_graphics_156,x:-141,y:179}).wait(1).to({graphics:mask_graphics_157,x:-140.7,y:179}).wait(1).to({graphics:mask_graphics_158,x:-140.3,y:179}).wait(1).to({graphics:mask_graphics_159,x:-140,y:179}).wait(75).to({graphics:null,x:0,y:0}).wait(236));

	// t4_1
	this.instance_19 = new lib.t4_1();
	this.instance_19.setTransform(-248,52.9);
	this.instance_19._off = true;

	this.instance_19.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_19).wait(179).to({_off:false},0).to({x:-43.1},10,cjs.Ease.get(1)).to({_off:true},45).wait(236));

	// t4_2
	this.instance_20 = new lib.t4_2();
	this.instance_20.setTransform(246,147.9);
	this.instance_20._off = true;

	this.instance_20.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_20).wait(179).to({_off:false},0).to({x:-14.9},10,cjs.Ease.get(1)).to({_off:true},45).wait(236));

	// gradient
	this.instance_21 = new lib.gradient1();
	this.instance_21.setTransform(-6.7,93.1);
	this.instance_21.alpha = 0.012;
	this.instance_21._off = true;

	this.instance_21.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_21).wait(169).to({_off:false},0).to({alpha:1},10).to({_off:true},55).wait(236));

	// img2
	this.instance_22 = new lib.img2_1();
	this.instance_22.setTransform(-4,93);
	this.instance_22._off = true;

	this.instance_22.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_22).wait(130).to({_off:false},0).to({_off:true},104).wait(236));

	// img1
	this.instance_23 = new lib.img1_1();
	this.instance_23.setTransform(-93.5,0);

	this.timeline.addTween(cjs.Tween.get(this.instance_23).to({x:93.5},130).to({_off:true},104).wait(225).to({_off:false,x:-93.5},0).wait(11));

	// bg
	this.instance_24 = new lib.bg();

	this.timeline.addTween(cjs.Tween.get(this.instance_24).wait(470));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-446.8,-300,596.8,600);


// stage content:
(lib._300x600 = function() {
	this.initialize();

	// cover
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#999999").ss(2,1,1).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape.setTransform(150,300);

	// banner
	this.instance = new lib.banner();
	this.instance.setTransform(150,300);

	this.addChild(this.instance,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-146.8,299,597.8,602);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;