(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.bgImg = function() {
	this.initialize(img.bgImg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.dev = function() {
	this.initialize(img.dev);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,168,338);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.urText_v = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AE4CWIgCgDIgBgDIABgDIACgCIAEgBQAAAAABAAQAAAAABAAQAAAAAAAAQAAABABAAIACACIABADIgBADIgCADIgDAAgAgZCWIACgIIACAAQABAAAAAAQABAAAAgBQABAAAAAAQABAAAAgBQAAAAABgBQAAAAAAgBQAAAAAAgBQABAAAAgBIABgiIAlAAIAAAvIgJAAIAAgnIgTAAIAAAQQgBAJgBAFQgCAGgDACQgCACgHAAgAhGCTQgFgDgDgGQgEgHAAgFQAAgHAEgGQADgGAFgDQAGgEAHAAQAHAAAFAEQAHADACAGQAEAGAAAHQAAAGgEAGQgCAGgHADQgFADgHAAQgHAAgGgDgAhBBvQgEADgBADQgDAFAAAEQAAADADAFIAFAGQADACAFAAQAFAAADgCQADgDACgDQACgDAAgFQAAgFgCgEQgCgDgDgDQgDgCgFAAQgFAAgDACgAjsCTQgGgDgDgGQgDgGAAgGQAAgIADgFQADgGAGgDQAFgEAIAAQAHAAAFAEQAGADADAGQAEAFgBAIQABAHgEAFQgDAGgGADQgFADgHAAQgIAAgFgDgAjnBvQgEADgCADQgBAEAAAFQAAAFABADQACADAEADQACACAGAAQAEAAADgCIAGgGQACgFAAgDQAAgEgCgFQgCgDgEgDQgDgCgEAAQgGAAgCACgAEeCVIAAgiIgYAiIgJAAIAAgvIAJAAIAAAiIAYgiIAJAAIAAAvgADmCVIAAgiIgPAVIgGAAIgPgVIAAAiIgKAAIAAgvIAKAAIASAYIASgYIAJAAIAAAvgAClCVIAAgvIAKAAIAAAvgACLCVIAAgVIgYAAIAAAVIgJAAIAAgvIAJAAIAAASIAYAAIAAgSIAJAAIAAAvgABFCVIAAgnIgQAAIAAgIIAqAAIAAAIIgQAAIAAAngAAmCVIAAgvIAJAAIAAAvgAhoCVIAAgVIgYAAIAAAVIgKAAIAAgvIAKAAIAAASIAYAAIAAgSIAJAAIAAAvgAi6CVIAAgvIAVAAQAJAAAEADQAEADAAAGQAAAEgBADIgGAEQAGACABACQACACAAAFQAAAEgCADQgBACgEADQgDABgHAAgAixCOIAMAAQAGAAACgBQADgDgBgDQABgHgLAAIgMAAgAixB6IALAAQADAAAEgCQACgBAAgEQABgGgKAAIgLAAgAkPCVIAAgnIgXAAIAAAnIgKAAIAAgvIAqAAIAAAvgACmBaIgBgCIgBgDIABgDIABgCIADgBIAEABIACACIAAADIAAADIgCACIgEABgAAoBaIgDgCIAAgDIAAgDIADgCIACgBIAEABIACACIABADIgBADIgCACIgEABgALEA6IAAhGIAJAAIAAAHIAHgGQAFgCAEAAQAIAAADADQAGADADAGQADAFAAAHQAAAIgDAFQgDAGgGADQgFADgGAAQgEAAgFgCIgHgGIAAAegALUgCQgDABgDADQgBAEAAAFQAAAFABAEQADAEADABQADADAFAAQAEAAADgDQADgBACgEQACgFAAgEQAAgEgCgFQgCgDgDgBQgDgCgEAAQgFAAgDACgAFeAvIAAgMIgoAAIAAAMIgIAAIAAgUIAGAAQABgCACgFIACggIAlAAIAAAnIAIAAIAAAUgAFAAUIgCAHIAXAAIAAgfIgTAAgAwzAvIAAgMIhBAAIAAgvIAJAAIAAAnIATAAIAAgnIAKAAIAAAnIASAAIAAgnIAKAAIAAAnIAIAAIAAAUgAOkAhQgFgDgEgGQgCgFAAgIQAAgHACgFQAEgGAFgDQAEgDAHAAQAFAAAEACQADACAEAEIAAgHIAJAAIAAAvIgJAAIAAgHQgEAEgDACQgEACgFAAQgGAAgFgDgAOpgCQgDABgCADQgCAEAAAFQAAAFACAEQACAEADABQADADAEAAQAFAAADgDQAEgBACgEQABgEAAgFQAAgFgBgEQgCgCgEgCQgDgCgFAAQgFAAgCACgANCAhQgGgDgDgGQgCgGAAgHQAAgHACgFQAEgFAFgEQAGgDAHAAQAGAAAGACQAGAEADADIgHAFIgGgEIgHgBQgGAAgDACIgGAEQgBAEAAAFQAAAFABADQADAEADACQADACAGAAIAHgBIAGgFIAHAGQgDADgGAEQgGACgGAAQgGAAgHgDgAFpAkIABgJIADAAQAAAAABAAQAAAAABAAQAAAAABgBQAAAAAAAAQABgBAAAAQAAgBABAAQAAgBAAAAQAAgBAAgBIACghIAmAAIAAAvIgKAAIAAgnIgTAAIgBAQQAAAJgBAFQgCAFgDACQgDADgGAAgADuAhQgHgDgCgGQgDgFAAgIQAAgHADgFQADgGAFgDQAGgDAGAAQAHAAAGADQAGAEACAEQADAFAAAGIAAAFIgmAAIADAHQACADADACQAEACAEAAQAFAAADgCIAHgEIAFAGQgDAEgFACQgHACgGAAQgGAAgGgDgAEIAHQgBgGgEgDQgFgDgFAAQgEAAgFADQgFAEAAAFIAdAAIAAAAgAAJAkIABgJIAEAAQACAAADgCQABgCABgFIACg0IAwAAIAABFIgKAAIAAg8IgdAAIgBAbQAAAOgBAGQgCAIgEADQgEADgGAAgAgYAjIgDgCIgBgDIABgEIADgCIADgBIADABIADACIABAEIgBADIgDACIgDABgAijAhQgFgDgEgGQgDgHAAgGQAAgGADgGQAEgFAFgEQAGgDAHAAQAGAAAGACQAGAEACADIgGAFIgGgEIgHgBQgFAAgEACIgGAEQgCAFAAAEQAAAEACAEQADAEADACQAEACAFAAIAHgBIAGgFIAGAGQgCADgGAEQgGACgGAAQgGAAgHgDgAlmAhQgGgDgDgGQgEgFAAgIQAAgHAEgFQADgGAGgDQAEgDAIAAQAGAAAFADQAGAEADAEQADAFAAAGIgBAFIglAAIADAHQACADADACQADACAFAAQAFAAADgCIAIgEIAEAGQgDAEgGACQgFACgGAAQgHAAgGgDgAlNAHQAAgGgEgDQgFgDgEAAQgFAAgFADQgDADgCAGIAcAAIAAAAgAmvAkIACgJIACAAQABAAAAAAQABAAAAAAQABAAAAgBQABAAAAAAQAAgBABAAQAAgBAAAAQAAgBAAAAQABgBAAgBIABghIAmAAIAAAvIgJAAIAAgnIgUAAIAAAQQAAAJgCAFQgCAFgDACQgDADgGAAgAndAhQgEgDgDgGQgEgFAAgIQAAgHAEgFQADgGAEgDQAGgDAGAAQAFAAAEACQAFADACADIAAgHIAKAAIAAAvIgKAAIAAgHQgCADgFADQgEACgFAAQgFAAgHgDgAnXgCQgDABgDADQgBAEAAAFQAAAFABAEQADAEADABQAEADAEAAQADAAAFgDQADgBABgEQACgEABgFQgBgFgCgEQgBgCgDgCQgEgCgEAAQgFAAgDACgAoRAiQgGgCgDgEIAFgGQADADAEACQADABAFAAQAHAAACgCQADgCAAgDQAAgHgKAAIgKAAIAAgHIAIAAQAEAAAEgBQACgDAAgCQAAgDgCgCQgCgBgFAAQgJAAgGAFIgEgFQACgEAGgCQAGgCAFAAQAJAAAEAEQAFADAAAGQAAAEgBACQgDADgDABQAFACACACQACADAAAEQAAAFgCADQgCADgGACQgGACgFAAQgGAAgFgCgApRAhQgGgDgDgGQgDgHgBgGQABgGADgGQADgFAFgEQAIgDAGAAQAHAAAEACQAGADADAEIgFAEIgHgEQgDgBgFAAQgEAAgEACQgDABgCACIgDAHIAYAAIAAAHIgYAAQABAGAFAEQADAEAHAAQAEAAAEgCQAEgCADgCIAFAGQgDADgFADQgGACgGAAQgHAAgGgDgAqMAhQgGgDgDgGQgDgFAAgIQAAgHADgFQADgGAGgDQAEgDAHAAQAFAAAEACQADACAEAEIAAgHIAJAAIAAAvIgJAAIAAgHQgEAEgDACQgEACgFAAQgGAAgFgDgAqHgCQgDABgCADQgCAFAAAEQAAAEACAFQACAEADABQADADAEAAQAEAAAEgDQADgBADgEQABgFAAgEQAAgEgBgFQgDgDgDgBQgDgCgFAAQgFAAgCACgAtAAkIABgJIACAAQABAAABAAQABAAAAAAQABAAAAgBQAAAAABAAIABgFIACghIAmAAIAAAvIgJAAIAAgnIgUAAIgBAQIgBAOQgBAFgEACQgDADgGAAgAKSAhQgFgDgDgGQgEgFAAgIQAAgHAEgFQADgGAFgDQAHgDAGAAQAGAAAGADQAHADACAGQAEAFAAAHQAAAIgEAFQgCAGgHADQgFADgHAAQgHAAgGgDgAKXgCQgEACgBADQgDAFAAADQAAAEADAFIAFAFQADACAFAAQAFAAADgCQADgCACgDQACgEAAgFQAAgFgCgDQgCgDgDgCQgDgCgFAAQgFAAgDACgAwdAhQgGgDgDgGQgDgFAAgIQAAgHADgFQADgGAGgDQAGgDAHAAQAGAAAGADQAGADADAGQAEAFAAAHQAAAIgEAFQgDAGgGADQgGADgGAAQgIAAgFgDgAwYgCQgEACgCADQgCADAAAFQAAAFACAEQACADAEACQADACAFAAQAEAAAEgCIAFgFQACgFAAgEQAAgDgCgFQgCgDgDgCQgEgCgEAAQgFAAgDACgARpAjIAAgTIgLAAIgMATIgKAAIANgTQgGgCgDgDQgDgDAAgGQAAgGAFgEQAFgEAJAAIAWAAIAAAvgARVgDQgDADAAACQAAADADADQACACAGAAIAMAAIAAgPIgMAAQgEAAgEACgAQyAjIAAgVIgYAAIAAAVIgKAAIAAgvIAKAAIAAASIAYAAIAAgSIAJAAIAAAvgAP3AjIAAgVIgYAAIAAAVIgJAAIAAgvIAJAAIAAASIAYAAIAAgSIAJAAIAAAvgAN3AjIAAgnIgRAAIAAgIIArAAIAAAIIgRAAIAAAngAMgAjIAAgjIgZAjIgIAAIAAgvIAJAAIAAAiIAYgiIAJAAIAAAvgAJ5AjIgNgTIgBgCIgKAAIAAAVIgJAAIAAgvIAJAAIAAASIAKAAIAOgSIAKAAIgQAWIARAZgAI/AjIAAgjIgZAjIgIAAIAAgvIAJAAIAAAiIAYgiIAJAAIAAAvgAHsAjIAAgvIAWAAQAJAAAEAEQAFADAAAFQAAADgCADIgFAEQAFACACACQACADAAAFQgBADgBADIgGAFQgEACgFAAgAH1AcIAOAAQAFAAACgCQACgCABgDQgBgHgJAAIgOAAgAH1AIIALAAQAEAAAEgCQADgCAAgDQAAgGgLAAIgLAAgAHGAjIAAgTIgLAAIgMATIgKAAIANgTQgGgCgDgDQgDgDAAgGQAAgGAFgEQAFgEAJAAIAWAAIAAAvgAGygDQgDACAAADQAAADADADQACACAGAAIAMAAIAAgPIgMAAQgEAAgEACgACWAjIAAgvIAJAAIAAAnIATAAIAAgnIAKAAIAAAnIATAAIAAgnIAKAAIAAAvgAB9AjIAAgjIgZAjIgIAAIAAgvIAJAAIAAAiIAYgiIAJAAIAAAvgAhKAjIAAgvIAJAAIAAAQIALAAQAJAAAFAEQAFAEABAHQgBAIgFAEQgFAEgJAAgAhBAcIAKAAQALAAAAgJQAAgDgDgDQgCgBgGAAIgKAAgAhvAjIAAgnIgQAAIAAgIIAqAAIAAAIIgQAAIAAAngAi/AjIAAgvIAJAAIAAAvgAjZAjIAAgVIgXAAIAAAVIgKAAIAAgvIAKAAIAAASIAXAAIAAgSIAJAAIAAAvgAkKAjIgNgVIgFAAIAAAVIgKAAIAAgVIgGAAIgMAVIgMAAIARgZIgQgWIALAAIAMASIAGAAIAAgSIAKAAIAAASIAFAAIANgSIAKAAIgQAWIAQAZgAqlAjIgOgVIgJAAIAAAVIgKAAIAAgvIAKAAIAAASIAJAAIAOgSIAKAAIgRAWIASAZgArfAjIAAgjIgZAjIgJAAIAAgvIAJAAIAAAiIAZgiIAJAAIAAAvgAtLAjIgNgTIgCgCIgJAAIAAAVIgKAAIAAgvIAKAAIAAASIAJAAIACgCIANgQIAKAAIgRAWIASAZgAuGAjIAAgjIgZAjIgIAAIAAgvIAJAAIAAAiIAZgiIAIAAIAAAvgAvYAjIAAgvIAVAAQAKAAAEAEQAEADAAAFQAAADgCADIgEAEQAEACACACQADAEAAAEIgDAGIgFAFQgEACgGAAgAvPAcIANAAQAFAAACgCQADgCAAgDQAAgHgKAAIgNAAgAvPAIIALAAQAEAAADgCQADgCAAgDQAAgGgKAAIgLAAgAi+gXIgCgDIgBgDIABgDIACgCIAEgBIACABIACACIABADIgBADIgCADIgCAAgApJg3IACgIIAFABIAGgBIACgDIAEgHIACgFIgUgwIAKAAIAPAlIAPglIAJAAIgbBAQgDAEgEACQgEACgEAAgAB0g3IAAhHIAJAAIAAAHIAHgGQAFgDAEAAQAGAAAGAEQAFADADAGQADAFAAAHQAAAIgDAFQgDAGgFADQgGAEgGAAQgEAAgFgDIgHgGIAAAfgACEh1QgDACgCAEQgCAEAAAEQAAAGACADQACAEADACQAEACADAAQAEAAAEgCQADgBACgFQADgFAAgEQAAgDgDgFQgCgFgDgBQgDgCgFAAQgEAAgDACgAmIg3IAAhHIAKAAIAAAHQABgEAGgCQADgDAGAAQAFAAAGAEQAFADADAGQADAFAAAHQAAAIgDAFQgDAGgFADQgGAEgFAAQgGAAgDgDQgGgCgBgEIAAAfgAl4h1QgDACgCAEQgCADAAAFQAAAGACADQACAEADACQAEACAEAAQADAAAEgCQAEgCACgEQABgDAAgGQAAgFgBgDQgCgEgEgCQgDgCgEAAQgFAAgDACgASZhAIAGgHIADgHIgEgCQgBgBAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAQAAgBAAgBQAAAAAAgBQABAAAAgBQAAAAABgBQAAAAABAAQAAgBABAAQAAAAABAAQAAAAABAAQADAAACACQADACgBAFQAAAEgDAHQgEAGgFADgAI1hRQgFgCgEgHQgDgFAAgIQAAgGADgGQADgFAGgEQAGgEAHAAQAGAAAGADQAGADACAEIgGAGIgGgFQgDgCgFAAQgEAAgEACIgGAGQgBAFAAADQAAAEABAFIAGAGQAEACAEAAQAFAAADgCIAGgFIAGAGQgDAEgFADQgGADgGAAQgGAAgHgEgAFQhOIACgIIACAAIAEgBIACgFIABgiIAmAAIAAAvIgJAAIAAgnIgUAAIgBAQQAAAJgBAFQgBAFgEADQgDADgFAAgADuhQQgGgBgDgEIAGgGQACADADABQAFACAEAAQAGAAADgCQADgCAAgEQAAgGgKAAIgKAAIAAgHIAIAAQAFAAACgCQADgCAAgDQAAgDgDgCQgBgCgGAAQgIAAgFAGIgGgGQAEgEAFgBQAFgDAGAAQAIAAAGAEQAEAEAAAGQAAADgCADQgCAEgDABQAFACACACQACACAAAFQAAAFgDADQgBACgGADQgGACgFAAQgGAAgFgDgABDhRQgHgDgCgGQgEgFAAgHQAAgIAEgFQADgGAFgDQAGgEAGAAQAHAAAFAEQAFADADAFQAEAGAAAGIAAAEIgmAAQAAAEADAEQACADADABQAEACAEAAIAIgBIAHgEIAFAGQgCADgHACQgGADgGAAQgHAAgFgEgABdhrQgCgGgEgDQgEgEgFAAQgFAAgFAEQgDAEgBAFIAdAAIAAAAgAgxhOIgCgDIgBgDIABgDIACgCIADgBIAEABIACACIABADIgBADIgCADIgEABgAkPhQQgEgBgEgEIAFgGQADADAEABIAIACQAHAAACgCQADgCAAgEQAAgGgKAAIgKAAIAAgHIAIAAQAGAAABgCQAEgCAAgDQgBgDgCgCQgCgCgFAAQgJAAgFAGIgFgGQAEgEAEgBQAGgDAFAAQAIAAAGAEQAEADABAHQAAAEgCACQgCADgEACQAFABACADQACADAAAEQAAAEgCAEQgCACgFADQgHACgEAAQgHAAgGgDgAoIhRQgFgCgEgHQgDgGAAgHQAAgGADgGQADgFAGgEQAGgEAHAAQAFAAAHADQAFADADAEIgFAGIgHgFQgEgCgEAAQgFAAgDACIgFAGQgDAFAAADQAAAGADADIAFAGQADACAFAAQAEAAAEgCIAHgFIAFAGQgDAEgFADQgGADgGAAQgHAAgGgEgAp9hRQgGgDgDgGQgDgFgBgIQABgHADgFQADgFAGgEQAGgEAHAAQAGAAAFADQAHACACAEIgFAGIgHgFQgEgCgEAAQgEAAgEACQgDACgCADIgDAHIAYAAIAAAHIgYAAQABAGAFAEQADAEAHAAQAEAAAEgCIAHgFIAFAGQgDAEgGACQgFADgGAAQgHAAgGgEgAq5hRQgFgDgDgGQgDgFAAgIQAAgHADgFQADgGAFgDQAGgEAGAAQAFAAAEADIAHAGIAAgHIAJAAIAAAvIgJAAIAAgHQgEAEgDACQgEADgFAAQgGAAgGgEgAqzh1QgDABgDAFQgBAFAAADQAAAEABAFQADAFADABQADACAEAAQAFAAADgCQADgBADgFQABgFAAgEQAAgDgBgFQgDgFgDgBQgCgCgGAAQgFAAgCACgAt/hOIAAgIIADAAIAEgBQABgBABgEIABgiIAmAAIAAAvIgJAAIAAgnIgUAAIAAAQIgCAOQAAAFgFADQgDADgFAAgAxdhRQgFgDgEgGQgDgFAAgHQAAgIADgFQAEgGAFgDQAGgEAGAAQAHAAAFAEQAGADADAFQADAFAAAHIgBAEIglAAQAAAEACAEQADADADABQAEACAEAAIAJgBIAGgEIAFAGQgCADgHACQgGADgFAAQgIAAgGgEgAxDhrQAAgFgEgEQgFgEgFAAQgEAAgFAEQgFAEAAAFIAcAAIAAAAgAPHhRQgHgDgCgGQgDgFAAgHQAAgHADgGQACgGAHgDQAFgEAHAAQAGAAAHAEQAFADAEAGQADAFAAAIQAAAHgDAFQgEAGgFADQgGADgHAAQgHAAgFgDgAPLh1QgEADgBADQgCAEAAAFQAAAFACADQABADAEADQADACAFAAQAEAAAEgCIAGgGQABgFAAgDQAAgEgBgFQgCgDgEgDQgEgCgEAAQgFAAgDACgAEkhRQgHgDgCgGQgEgGAAgGQAAgGAEgHQACgGAHgDQAFgEAHAAQAGAAAHAEQAFADAEAGQACAGAAAHQAAAHgCAFQgEAGgFADQgGADgHAAQgHAAgFgDgAEoh1QgDADgCADQgCAFAAAEQAAADACAFIAFAGQADACAFAAQAEAAAEgCQAEgDABgDQACgDAAgFQAAgFgCgEQgCgDgDgDQgEgCgEAAQgFAAgDACgAC4hRQgGgDgDgGQgDgFAAgHQAAgIADgFQADgGAGgDQAGgEAGAAQAHAAAGAEQAGADADAGQADAGAAAHQAAAHgDAFQgDAGgGADQgFADgIAAQgHAAgFgDgAC8h1QgCACgDAEQgCAFAAAEQAAADACAFQACAEADACQAEACAEAAQAFAAADgCQAFgDABgDQABgDAAgFQAAgFgBgEQgCgDgEgDQgDgCgFAAQgEAAgEACgAsjhQQgGgEgDgEQgCgFgBgHIgIAAIAAAVIgJAAIAAgvIAJAAIAAATIAIAAQACgIACgDQAEgEAEgDQAHgDAEAAQAHAAAGAEQAGADADAGQACAFAAAHQAAAIgCAFQgDAFgGAEQgFADgIAAQgFAAgGgCgAsfh1IgFAGQgCAFAAADQAAAEACAFIAFAGIAHACQAEAAAEgCQADgDACgDQACgDAAgGQAAgFgCgDQgBgDgEgDQgCgCgGAAQgEAAgDACgASFhPIAAgVIgYAAIAAAVIgKAAIAAgvIAKAAIAAATIAYAAIAAgTIAJAAIAAAvgARLhPIAAgiIgZAiIgJAAIAAgvIAJAAIAAAiIAZgiIAJAAIAAAvgAQFhPIAAgnIgRAAIAAgIIAqAAIAAAIIgQAAIAAAngAOthPIgMgTIgCgBIgJAAIAAAUIgKAAIAAgvIAKAAIAAASIAKAAIANgSIALAAIgRAWIARAZgAN5hPIAAgvIAJAAIAAAvgANfhPIAAgVIgXAAIAAAVIgKAAIAAgvIAKAAIAAATIAXAAIAAgTIAJAAIAAAvgAL5hPIAAgvIAKAAIAAARIAKAAQAKAAAFAEQAFADAAAIQAAAIgFADQgEAEgLAAgAMDhWIAKAAQALAAgBgIQAAgEgCgCQgDgCgFAAIgKAAgALVhPIAAgnIgRAAIAAgIIArAAIAAAIIgRAAIAAAngAKwhPIAAgiIgaAiIgIAAIAAgvIAJAAIAAAiIAZgiIAJAAIAAAvgAJphPIAAgnIgQAAIAAgIIAqAAIAAAIIgQAAIAAAngAIZhPIAAgvIAJAAIAAAvgAIDhPIAAgiIgQAVIgHAAIgPgVIAAAiIgJAAIAAgvIAJAAIATAYIATgYIAJAAIAAAvgAGQhPIAAgvIAJAAIAAARIAKAAQAKAAAFAEQAFADAAAIQAAAIgFADQgEAEgLAAgAGZhWIAKAAQAKAAAAgIQABgEgDgCQgDgCgFAAIgKAAgAAjhPIgEgNIgfAAIgFANIgKAAIAahFIAIAAIAbBFgAAchlIgNghIgMAhIAZAAgAhjhPIAAgvIAWAAQAJAAAEADQAEADABAGQgBAEgBADIgFAEQAFABACADQACADAAAEIgCAHIgGAFQgEABgGAAgAhZhWIANAAQAFAAACgBQACgDAAgDQABgGgKAAIgNAAgAhZhqIALAAQADAAAEgCQACgBABgEQgBgGgJAAIgLAAgAh2hPIAAgvIAJAAIAAAvgAiGhPIgOgUIgJAAIAAAUIgKAAIAAgvIAKAAIAAASIAJAAIAOgSIALAAIgRAWIARAZgAjAhPIAAgiIgZAiIgJAAIAAgvIAJAAIAAAiIAZgiIAJAAIAAAvgAkshPIAAgiIgZAiIgJAAIAAgvIAJAAIAAAiIAZgiIAJAAIAAAvgAmshPIgNgRIgNARIgLAAIASgYIgSgXIALAAIANARIANgRIALAAIgSAXIASAYgAnghPIAAgvIAJAAIAAAvgArUhPIAAgTQgHADgHAAIgKgCQgEgDgCgDQgCgEAAgGIAAgNIAJAAIAAANQAAAFADACQACACAGAAQAGAAAGgCIAAgUIAJAAIAAAvgAuLhPIgNgTIgBgBIgKAAIAAAUIgJAAIAAgvIAJAAIAAASIAKAAIAOgSIALAAIgRAWIARAZgAvFhPIAAgiIgZAiIgJAAIAAgvIAJAAIAAAiIAZgiIAJAAIAAAvgAwYhPIAAgvIAWAAQAJAAAEADQAFADgBAGQAAAEgCADQgBACgDACQAFACABACQACACABAFQgBAEgCADQAAACgFADQgEABgFAAgAwPhWIANAAQAGAAACgBQADgDAAgDQAAgGgLAAIgNAAgAwPhqIALAAQAEAAAEgCQACgBAAgEQAAgGgKAAIgLAAgAx7hPIAAgfIgkAAIAAAfIgJAAIAAhFIAJAAIAAAdIAkAAIAAgdIAKAAIAABFgAN6iKIgCgCIgBgDIABgDIACgCIAEgBIACABIADACIABADIgBADIgDACIgCABgAIaiKIgCgCIgBgDIABgDIACgCIAEgBIADABIABACIABADIgBADIgBACIgDABgAh0iKIgDgCIgBgDIABgDIADgCIADgBIADABIACACIABADIgBADIgCACIgDABgAnfiKIgCgCIAAgDIAAgDIACgCIAEgBIADABIACACIABADIgBADIgCACIgDABg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.urText_v, new cjs.Rectangle(-119.3,-15,238.7,30.1), null);


(lib.t2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#22BACC").s().p("AHDBaQgRgKgIgPQgJgPAAgTQAAgSAJgPQAIgQARgJQAQgJAUAAQAUAAAQAJQAQAJAIAQQAIAOAAATQAAATgIAPQgIAPgQAKQgQAJgUAAQgUAAgQgJgAHWABQgIAFgDAHQgEAIAAAKQAAALAEAHQADAHAIAFQAHAEAKAAQAIAAAIgEQAIgFADgHQAEgHAAgLQAAgKgEgIQgDgHgIgFQgIgDgIAAQgKAAgHADgADxBdQgLgGgGgMQgGgMAAgPIAAgyIgdAAIAAgaIAJgCQAHAAAFgDQAEgEACgEQACgHAAgFIAAgYIAkAAIAAAsIAwAAIAAAfIgwAAIAAAvQAAAJAFAGQAGAFAJAAQAGAAAHgCQAGgCAFgFIARAaQgKAJgMAEQgKAEgQAAQgPAAgLgGgAgVBaQgNgIgJgQQgIgRAAgSQAAgSAIgQQAJgQANgJQANgIARAAQAMAAAKAEQAJAFAHAIIAAhOIAlAAIAADAIglAAIAAgOQgGAJgKAEQgKAFgMAAQgRAAgNgJgAABAAQgHAFgDAIQgEAIAAAKQAAAKAEAIQADAIAHAEQAHAFAJAAQAJAAAIgFQAHgEAEgIQAEgIAAgKQAAgKgEgIQgEgIgHgFQgIgDgJAAQgJAAgHADgAmKBaQgPgJgJgQQgJgQAAgSQAAgTAJgPQAJgQAPgIQAPgJATAAQAUAAAOAIQAOAIAJAPQAJAPAAAQIgBAQIhdAAQADAMAIAGQAJAHAPAAQALAAAJgEQAKgCAHgGIAQAbQgIAHgQAFQgPAFgRAAQgVAAgRgJgAl7AAQgHAGgDALIA6AAQgCgLgIgGQgIgGgLAAQgLAAgIAGgAKeBfIAAhLQAAgLgHgGQgGgFgKAAQgHAAgGACQgGACgFAGIAABXIglAAIAAiAIAiAAIABANQAGgHAKgFQAKgEALAAQANAAAMAFQAKAGAHAMQAGAMAAAOIAABSgAFZBfIAAiAIAlAAIAACAgAB8BfIAAiAIAlAAIAACAgAjIBfIAAi5IB6AAIAAAhIhUAAIAAAqIBNAAIAAAhIhNAAIAAAsIBXAAIAAAhgAoQBfIgph6IgoB6IgjAAIg9i5IAnAAIAoB+IAqh+IAgAAIApB9IAoh9IAnAAIg+C5gAFhg5QgFgDgDgFQgDgFAAgGQAAgFADgGQADgFAFgDQAEgDAHAAQAGAAAFADQAFAEADAEQACAGAAAFQAAAFgCAGQgDAEgFAEQgFADgGAAQgHAAgEgDgACDg5QgFgEgDgEQgCgGAAgFQAAgFACgGQADgEAFgEQAGgDAFAAQAHAAAEADQAFADADAFQADAGAAAFQAAAGgDAFQgDAFgFADQgEADgHAAQgFAAgGgDg");
	this.shape.setTransform(0,15.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AHxBUQgVgMgOgWQgMgXAAgbQAAgaAMgWQANgXAWgMQAWgNAcAAQAbAAAXANQAWANANAWQAMAWAAAaQAAAbgMAXQgNAWgWAMQgWANgcAAQgcAAgWgNgAIEg0QgMAHgIAPQgHAOAAAQQAAAQAHAQQAHANANAIQAOAJARAAQARAAAOgJQAOgJAGgMQAHgQAAgQQAAgQgHgOQgGgOgOgIQgNgIgSAAQgSAAgNAIgAEvBZQgSgJgKgQQgKgQAAgWIAAh2IAmAAIAABxQAAAMAFAKQAFAIAJAFQAIAGANAAQANAAAIgGQAJgEAFgJQAFgJAAgNIAAhxIAlAAIAAB2QAAAWgKAQQgKAQgRAJQgSAIgWAAQgWAAgSgIgAk6BUQgWgMgNgWQgMgWAAgcQAAgaAMgWQAMgWAXgNQAXgNAbAAQAcAAAWANQAVAMANAXQANAXAAAZQAAAagNAYQgNAXgVALQgWANgcAAQgcAAgWgNgAkng0QgOAIgGAOQgIANAAARQAAASAIAOQAGAMAOAJQAOAJARAAQAQAAAPgJQANgIAHgNQAHgOAAgSQAAgSgHgMQgHgPgNgHQgNgIgSAAQgSAAgNAIgAoQBUQgWgNgMgVQgNgYAAgaQAAgZANgXQALgVAXgOQAXgNAbAAQAcAAAWANQAXANAMAWQAMAWAAAaQAAARgFARQgGAQgKAMIAcAfIgpAAIgKgLQgKAIgOADQgNAEgQAAQgcAAgWgNgAn9g0QgNAIgHAOQgHAMAAASQAAASAHAOQAGAMAOAJQAPAJAQAAQAPgBAOgGIgngsIAXgUIAmAqQAHgOAAgTQAAgRgGgNQgIgPgNgHQgNgIgSAAQgSAAgNAIgAh4BaQgSgFgNgMIARgcQAKAIAPAFQANAFAQAAQAPAAAJgGQAJgHAAgKQAAgIgFgFQgHgGgGgDIgWgHQgUgFgLgFQgNgFgHgKQgJgKAAgSQAAgSAJgMQAJgMAQgGQAQgGAUAAQARAAATAFQARAFAMAJIgQAdQgLgHgMgEQgLgDgOAAQgPAAgJAFQgJAFAAAJQAAAHAFADQAEAFAHACIAUAHQARAFAQAGQANAGAJAKQAJAMAAAUQAAASgIANQgKANgPAGQgPAGgWABQgVAAgUgHgABJBdIAAi5IBEAAQAeAAAVALQAXAMAMAVQAMAVAAAbQAAAcgMAVQgMAVgXAMQgWAMgdgBgABvA8IAbAAQAdAAAQgPQARgPAAgeQAAgTgIgNQgIgOgNgGQgOgHgTAAIgbAAgAqDBdIAAi5IAmAAIAAC5g");
	this.shape_1.setTransform(1.6,-15.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.t2, new cjs.Rectangle(-70.6,-25.4,141.3,50.8), null);


(lib.t1_v = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AJ0GaQgFgDgEgGQgDgEAAgHQAAgFADgGQAEgFAFgDQAFgEAHAAQAGAAAFAEQAGADADAFQACAGAAAFQAAAHgCAEQgDAGgGADQgFADgGAAQgHAAgFgDgAHjGXQgUgHgLgKIARgdQALAJANAEQAOAFAQAAQAPAAAJgGQAJgGAAgLQAAgHgFgGQgGgFgIgDIgVgHQgUgGgMgFQgMgFgIgLQgJgKAAgSQAAgRAKgNQAJgMAQgGQAQgFAUAAQASAAARAEQASAFALAJIgQAcQgLgGgLgEQgOgDgMAAQgPAAgJAFQgIAFgBAJQAAAHAFAEQAGAFAFACIAVAGQARAFAQAGQANAHAIALQAKAMAAATQAAASgJANQgIANgQAHQgSAGgTAAQgUAAgVgGgAEfGQQgWgMgMgXQgNgWAAgbQAAgbANgWQAMgWAWgNQAWgMAcAAQAdAAAVAMQAWANAMAWQANAVAAAcQAAAcgNAVQgMAXgWAMQgVANgdAAQgcAAgWgNgAEyEHQgOAIgGAOQgHAOAAARQAAASAHANQAGANAOAKQANAHASAAQASAAANgHQANgJAIgOQAGgPAAgQQAAgQgGgPQgJgPgMgHQgNgIgSAAQgSAAgNAIgABJGQQgXgMgMgXQgNgVAAgcQAAgbANgWQAMgWAXgNQAVgMAcAAQAcAAAXAMQAVANANAWQAMAWAAAbQAAATgGAOQgFAQgJAOIAbAfIgpAAIgKgLQgLAGgOAFQgMADgQAAQgcAAgVgNgABcEHQgNAHgIAPQgHAPAAAQQAAAQAHAPQAHAOAOAJQAMAHASAAQAQABANgHIgngsIAXgUIAmAqQAHgNABgUQgBgQgGgPQgHgOgNgIQgOgIgSAAQgSAAgMAIgAjaGYQgNgFgKgKIATgWQANANAXAAQALAAAIgEQAGgDAAgIQAAgGgFgEQgFgDgLAAIgZAAIAAgYIAVAAQAVAAAAgNQAAgHgGgDQgEgDgKAAQgVAAgOAOIgSgYQAKgJAOgFQAPgFAPgBQAaABAOAJQAOAMAAAQQABALgGAGQgEAIgJAEQAYAHAAAWQAAAMgIAJQgIAKgNAFQgNAFgUAAQgSAAgOgFgAgrGaIAAi7IAmAAIAAC7gAlgGaIAAhQIgzBQIgiAAIAAiBIAjAAIAABOIAzhOIAhAAIAACBgAn+GaIAAh8IgtBIIgZAAIguhIIAAB8IgjAAIAAi7IAjAAIA6BaIA7haIAjAAIAAC7gAF1B/IAAggIhfAAIAAAgIgfAAIAAg+IAOAAQAFgHADgLQAEgNABgSIACgxIBsAAIAABiIAUAAIAAA+gAE2ASQgCAUgCAJQgCAKgEAIIAvAAIAAhEIglAAgATiBfQgGgDgCgFQgDgEAAgHQAAgGADgFQACgEAGgFQAGgDAGAAQAHAAAEADQAGAFADAEQADAFAAAGQAAAHgDAEQgDAFgGADQgEAEgHAAQgGAAgGgEgAJWBaQgOgKgIgOQgIgQABgTQgBgUAIgPQAIgPAOgJQAPgJAQAAQAMAAAKAFQAJAFAHAIIAAgOIAlAAIAACAIglAAIAAgNQgGAHgKAFQgKAFgMAAQgQAAgPgJgAJsAAQgHAEgEAJQgDAHAAALQAAAKADAIQAEAHAHAFQAIAEAJABQAKgBAGgEQAIgFADgHQAFgIAAgKQAAgLgFgHQgDgJgIgEQgGgDgKgBQgJABgIADgAk0BaQgNgJgIgPQgJgRABgSQgBgSAJgRQAIgQANgIQAOgJASAAQAMAAAJAFQAKAFAHAIIAAgOIAkAAIAACAIgkAAIAAgNQgGAGgLAGQgJAFgMAAQgSAAgOgJgAkdAAQgIAEgDAJQgEAHAAALQAAAKAEAIQADAHAIAFQAHAEAKABQAIgBAIgEQAHgFAEgHQAEgIAAgKQAAgLgEgHQgEgJgHgEQgIgDgIgBQgKABgHADgAq2BZQgQgIgIgQQgJgQABgSQgBgTAJgPQAJgPAPgKQAQgIAVgBQATAAAOAHQAPAGAJALIgWAYQgFgGgKgEQgKgEgJAAQgKABgHADQgJAEgDAIQgEAHAAALQAAAMAEAGQAEAIAIADQAHAFAKAAQAJAAAKgEQAJgDAGgIIAWAZQgIAKgQAIQgPAGgSAAQgVAAgQgKgAOKBZQgQgJgJgPQgIgPAAgTQAAgTAIgPQAKgPAPgKQARgIATgBQAVABAPAIQAPAJAKAQQAIAOAAAUQAAAUgIAOQgKAQgPAIQgPAJgVAAQgTAAgRgJgAOdABQgHAEgEAIQgEAJAAAJQAAAKAEAIQAEAGAHAFQAJAFAIAAQAJAAAHgFQAJgEADgHQAEgJAAgJQAAgJgEgJQgEgIgIgEQgGgDgKgBQgJABgIADgACCBZQgPgIgKgQQgIgOAAgUQAAgUAIgOQAKgQAPgJQAQgIAUgBQAVABAPAIQAPAJAKAQQAIAPAAATQAAATgIAPQgJAQgQAIQgPAJgVAAQgUAAgQgJgACVABQgFADgGAJQgEAJAAAJQAAAJAEAJQAFAHAGAEQAJAFAIAAQAJAAAIgFQAGgEAFgHQAEgJAAgJQAAgJgEgJQgGgJgFgDQgHgDgKgBQgJABgIADgASVBfIAAiAIAlAAIAACAgAQJBfIAAiAIA+AAQAZAAAMAKQANAIAAAQQAAAKgFAGQgFAIgHAEQAWAHAAAWQAAAKgFAJQgGAIgLAGQgKAEgPAAgAQtBFIAYAAQAVABgBgOQABgIgFgCQgFgEgLAAIgYAAgAQtATIAUAAQALAAAEgEQAGgEAAgGQAAgFgGgEQgEgDgLAAIgUAAgAM3BfIgagtIgDgFIgHgBIgQAAIAAAzIgkAAIAAiAIAkAAIAAAtIARAAQAEAAABgBQACgBACgEIAagnIAqAAIgpA7IAqBFgAH7BfIAAgzIgvAAIAAAzIglAAIAAiAIAlAAIAAAvIAvAAIAAgvIAlAAIAACAgAgSBfIAAiAIAkAAIAACAgAhSBfIgbgtIgDgFIgHgBIgPAAIAAAzIglAAIAAiAIAlAAIAAAtIAQAAQAEAAACgBQACgCABgDIAbgnIApAAIgpA7IAqBFgAmoBfIAAhiIgpAAIAAgeIB2AAIAAAeIgpAAIAABigApDBfIAAiAIAlAAIAACAgAtaBfIAAiAIA+AAQAZAAAMAKQAMAIAAAQQABAKgFAGQgFAIgHAEQAWAHAAAWQAAAKgGAJQgEAIgMAGQgLAEgOAAgAs2BFIAYAAQAVABgBgOQABgIgGgCQgEgEgLAAIgYAAgAs2ATIAUAAQALAAAEgEQAFgEABgGQgBgFgFgEQgEgDgLAAIgUAAgAvQBfIAAhPIg0BPIgiAAIAAiAIAjAAIAABOIAzhOIAjAAIAACAgAxsBfIAAh6IguBHIgZAAIgthHIAAB6IgkAAIAAi6IAjAAIA6BbIA7hbIAjAAIAAC6gASdg6QgFgCgDgFQgDgFgBgGQABgFADgGQADgFAFgDQAEgDAHAAQAFAAAFADQAFADADAFQADAGAAAFQAAAFgDAGQgDAFgFACQgFADgFAAQgHAAgEgDgAgLg6QgDgCgEgFQgDgFAAgGQAAgFADgGQADgFAEgDQAGgDAFAAQAGAAAFADQAEADAEAFQADAGAAAFQAAAGgDAFQgEAFgEACQgFADgGAAQgFAAgGgDgAo7g6QgEgCgFgFQgCgFAAgGQAAgFACgGQAEgFAFgDQAEgDAGAAQAHAAAEADQAFADADAFQADAGABAFQgBAGgDAFQgDAFgFACQgEADgHAAQgGAAgEgDgABpiaIAAjBIAlAAIAAANQAGgHAKgFQAKgFAMAAQARAAAOAJQANAJAJAPQAHAQAAATQAAAUgHAPQgJARgNAIQgOAIgRABQgLAAgLgFQgJgFgHgIIAABOgACck5QgIAEgDAIQgEAHAAALQAAALAEAHQADAJAIAEQAGAEAKABQAKgBAGgEQAIgEAEgJQADgJAAgJQAAgJgDgJQgFgIgHgEQgGgEgKgBQgKABgGAEgAK9jaQgEgCgDgGQgEgFAAgHQAAgFAEgFQADgGAEgDQAGgDAHAAQAGAAAFADQAEADAEAGQADAFAAAFQAAAHgDAFQgEAGgEACQgFADgGABQgHgBgGgDgAFgjcQgOgEgKgKIATgXQAOANAWAAQAMAAAHgDQAGgEABgHQAAgHgGgDQgEgDgLAAIgZAAIAAgYIAUAAQAWAAgBgOQABgGgGgEQgFgCgKAAQgVAAgNANIgTgXQAKgKAOgFQAQgFAPAAQAaAAAOAKQAOALAAARQAAAKgFAHQgEAIgJADQAXAIAAAVQAAAMgIAKQgHAKgNAEQgOAFgUABQgSgBgNgFgAiKjfQgQgKgIgPQgJgQAAgTQAAgSAJgQQAIgPAQgKQAQgJAVAAQARAAARAGQAPAIAIAJIgVAaQgGgGgKgFQgKgEgJAAQgKAAgIAFQgGADgFAIQgEAJAAAKQAAAJAEAIQAFAJAGADQAJAFAJAAQALAAAIgFQAIgDAIgHIAVAZQgIAKgPAHQgPAHgTAAQgUgBgRgIgAJvjaIAAiBIAkAAIAACBgAInjaIAAgzIguAAIAAAzIgmAAIAAiBIAmAAIAAAvIAuAAIAAgvIAlAAIAACBgAEKjaIAAiBIAlAAIAACBgAgVjaIAAiBIAkAAIAACBgAkvjaIAAiBIA+AAQAYAAANAJQAMAJAAARQAAAJgEAIQgFAGgJAFQAYAHAAAWQAAAKgGAJQgGAIgLAFQgJAFgRAAgAkLj0IAXAAQAVAAAAgOQAAgHgFgDQgFgDgLAAIgXAAgAkLknIATAAQAKAAAGgDQAEgDAAgIQAAgGgEgEQgGgCgKAAIgTAAgAmqjaIAAhPIg0BPIghAAIAAiBIAiAAIAABPIA0hPIAiAAIAACBgApIjaIAAh7IguBIIgYAAIgthIIAAB7IgkAAIAAi7IAjAAIA6BbIA7hbIAjAAIAAC7gAJ1l0QgFgDgCgFQgDgEAAgHQAAgFADgFQACgEAFgEQAGgDAGAAQAGAAAFADQAFADADAFQACAFAAAFQAAAHgCAEQgDAGgFACQgFADgGAAQgGAAgGgDgAESl0QgFgCgDgGQgDgEAAgHQAAgFADgFQADgFAFgDQAFgDAGAAQAGAAAFADQAFADADAFQADAFAAAFQAAAHgDAEQgDAGgFACQgFADgGAAQgGAAgFgDgAgNl0QgFgCgEgGQgCgEAAgHQAAgFACgFQAEgFAFgDQAEgDAGAAQAGAAAEADQAGADACAFQADAEAAAGQAAAIgDADQgCAGgGACQgEADgGAAQgGAAgEgDg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1_v, new cjs.Rectangle(-128.5,-41.3,257,82.6), null);


(lib.r_part = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhijHQBSAAA5A7QA6A6AABSQAABTg6A6Qg5A7hSAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.r_part, new cjs.Rectangle(-9.9,-20,19.9,40), null);


(lib.logo_iqos = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AuzFoQg9AAgygfQgwgdgcgxQgcgwgBg4QgCg7Afg1IClkeQAeg0A0gcQAxgcA4AAQA5AAAwAcQA0AcAeA0IClEeQAfA1gBA7QgBA4gdAwQgbAxgwAdQgzAfg9AAgAt8jUQgyAWgoAnQgmAngWAzQgWA0AAA5QAAA6AWA0QAWAyAmApQAoAnAyAUQA1AXA5AAQA6AAA1gXQAygUAognQAngpAUgyQAXg0AAg6QAAg5gXg0QgUgzgngnQgogngygWQg1gVg6gBQg5ABg1AVgAE1C7IgsgtIgFgDQgCgBgEAAIjJAAQg+AAgkgfQgigcAAgtIAAiqQAAgHAGgFQAGgGAHAAIDmAAQA9AAAkAeQAjAcAAAuIAABPQAAAIgGAFQgGAFgGAAIgHAAQgIAAgGgFQgEgFAAgIIAAhPQAAgLgFgLQgFgLgJgHQgLgKgUgGQgQgEgXgBIjIAAIgEABIgBAGIAACKQAAAMAEALQAFAKAJAIQALAKASAFQASAFAXAAIDVAAQAGAAAGABIAJAHIA1A2QAFAEAAAIQAAAIgFAFIgFAFQgFAFgHAAQgJAAgFgFgAOMCKQgVAAgTgHQgUgJgPgOIgJgIQgFgHgBgHQAAgHAFgGIAFgFQAFgEAHgCQAIAAAGAGIAKAJQAJAJALAEQALAFANAAICQAAQAVAAAPgDQAPgFAJgHQAFgFACgEQADgHAAgLQAAgKgDgFQgCgGgFgEQgJgIgPgDQgPgEgVAAIh6AAQg3AAgfgWQgagWAAgiIAAgKQAAgiAagVQAfgYA3AAICFAAQAUAAASAHQASAIAPAMIAMAMQAGAEABAIQAAAIgEAFIgFAFQgFAGgIAAQgHABgGgGIgMgKQgIgIgMgEQgMgFgLAAIiFAAQgTAAgQAFQgPADgKAHQgEADgDAHQgDAFAAALQAAALADAFQADAIAEADQAJAHAQAEQAQADATAAIB6AAQA5ABAdAWQAaAUAAAjIAAAKQAAAjgaAUQgdAYg5AAgAH7CKQg/AAgkgfQghgcAAgtIAAhUQAAguAhgcQAkgeA/AAIB1AAQA9AAAkAeQAiAcAAAuIAABUQAAAtgiAcQgkAfg9AAgAHShqQgSAGgNAKQgIAHgEALQgGALAAALIAABUQAAAMAGALQAEAKAIAIQANAKASAFQASAFAXAAIB1AAQAWAAASgFQASgFAMgKQAJgIAFgKQAFgLAAgMIAAhUQAAgNgFgJQgFgLgJgHQgMgKgSgGQgSgEgWgBIh1AAQgXABgSAEgAi2CKQgIAAgGgGQgFgEAAgIIAAj/QAAgJAFgEQAGgGAIAAIAFAAQAIAAAFAGQAGAFAAAIIAAD/QAAAIgGAEQgFAGgIAAg");
	this.shape.setTransform(-1.6,0);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.logo_iqos, new cjs.Rectangle(-118,-36,232.9,72), null);


(lib.l_part = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgoCNQg7g6AAhTQAAhSA7g6QA5g7BTAAIAAGPQhTAAg5g7g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.l_part, new cjs.Rectangle(-9.9,-20,19.9,40), null);


(lib.dev_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(10,134,142,0.6)").s().p("AghAcQgLgBgEgGQgDgDAAgHQAAgEACgEQACgFAHgCIANgCQAMAAAFAEQAIAFgEAJQgCAIgJAFQgGADgHAAIgDAAgAANANQgJgCgDgMQgBgHABgFQADgFAHgEQALgGAKACQAMABAFAJQAHAKgHAIQgEAFgPAEQgIACgFAAIgEAAg");
	this.shape.setTransform(-27.5,-0.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(10,134,142,0.6)").s().p("AgMAUQgJgCgDgNQgCgGACgFQADgFAHgEQAKgGAKACQAMABAFAJQAHAJgHAJQgEAFgPAEQgHACgFAAIgEAAg");
	this.shape_1.setTransform(-24.9,-1.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},1).to({state:[]},10).wait(1));

	// Слой_1
	this.instance = new lib.dev();
	this.instance.parent = this;
	this.instance.setTransform(-72,-146,0.857,0.857);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(12));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-72,-146,144,289.7);


(lib.btn_txt = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#35303E").s().p("AhPBDIAAgUIhDAAIAAhLIAQAAIAAA+IAlAAIAAg+IAPAAIAAA+IAMAAIAAAhgAFJAwIgEgEIgBgFIABgFIAEgEIAFgCQADABACABIAEAEIABAFQAAAEgCADQgDADgFAAIgFgBgAjkAsQgJgFgEgJQgFgJAAgMQAAgLAFgJQAEgJAJgFQAJgGAJAAQAJAAAGAEQAHAEAEAGIAAgLIAPAAIAABLIgPAAIAAgLQgEAGgHAEQgIADgHAAQgJABgJgGgAjbgOQgGAEgDAGQgDAGAAAHQAAAHADAGQADAHAGADQAEADAIABQAHgBAFgDQAFgDADgHQADgFAAgIQAAgIgDgFQgDgGgFgEQgHgDgFAAQgHAAgFADgAlFAtQgLgEgHgFIAIgMQAGAFAJADQAIACAJABQAMgBAGgEQAHgFAAgKQAAgJgFgFQgFgDgLAAIgTAAIAAgOIAQAAQAKAAAFgEQAFgFAAgJQAAgIgGgFQgGgFgKAAQgQAAgOAKIgHgLQAHgGAKgDQAJgEAMAAQALAAAIAEQAJAEAEAGQAFAHAAAKQAAAIgEAHQgDAGgHAEQAHADAGAHQAFAHAAAKQAAAKgFAHQgFAIgKADQgJAEgMAAQgLAAgLgEgAEkAvIAAg3IgoA3IgNAAIAAhLIAOAAIAAA3IAog3IANAAIAABLgAC1AvIAAg+IgaAAIAAgNIBEAAIAAANIgbAAIAAA+gACAAvIAAg3IgoA3IgNAAIAAhLIAOAAIAAA3IAog3IAOAAIAABLgAApAvIAAgiIgmAAIAAAiIgOAAIAAhLIAOAAIAAAdIAmAAIAAgdIAPAAIAABLgAgxAvIAAhLIAPAAIAABLgAFHAPIAAhPIAPAAIgBBPgAgugvIgEgEIgBgEIABgGQABAAAAAAQAAgBABAAQAAgBABAAQAAAAABAAQAAgBABAAQAAAAABgBQAAAAABAAQABAAAAAAIAGACIADACIABAGIgBAEIgDAEIgGACQAAAAgBgBQgBAAAAAAQgBAAAAAAQgBgBAAAAg");
	this.shape.setTransform(0.2,-0.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.btn_txt, new cjs.Rectangle(-34.2,-7.2,68.9,13.4), null);


(lib.btn_round = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AiMCNQg7g6AAhTQAAhSA7g6QA6g7BSAAQBTAAA6A7QA7A6AABSQAABTg7A6Qg6A7hTAAQhSAAg6g7g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.btn_round, new cjs.Rectangle(-20,-20,40,40), null);


(lib.btn_bg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AmGDIQhSAAg6g6Qg6g5gBhTIAAgCQABhSA6g6QA6g7BSAAIMMAAQBTAAA7A7QA5A6AABSIAAACQAABSg5A6Qg7A6hTAAg");
	this.shape.setTransform(0.2,0);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.btn_bg, new cjs.Rectangle(-58.7,-20,117.9,40), null);


(lib.bgImg_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.bgImg();
	this.instance.parent = this;
	this.instance.setTransform(-150,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bgImg_1, new cjs.Rectangle(-150,-300,300,600), null);


(lib.bg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#35303E").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.bg, new cjs.Rectangle(-150,-300,300,600), null);


(lib.btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_4
	this.instance = new lib.btn_txt();
	this.instance.parent = this;
	this.instance.setTransform(0,8.9);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(12).to({_off:false},0).to({y:0.7,alpha:1},8).wait(1));

	// r_part
	this.instance_1 = new lib.r_part();
	this.instance_1.parent = this;
	this.instance_1.setTransform(10.1,0);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(9).to({_off:false},0).to({x:49.6},8,cjs.Ease.get(1)).to({_off:true},1).wait(3));

	// l_part
	this.instance_2 = new lib.l_part();
	this.instance_2.parent = this;
	this.instance_2.setTransform(-10,0);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(9).to({_off:false},0).to({x:-48.8},8,cjs.Ease.get(1)).to({_off:true},1).wait(3));

	// Слой_5
	this.instance_3 = new lib.btn_bg();
	this.instance_3.parent = this;
	this.instance_3.setTransform(0,0,0.01,1);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(9).to({_off:false},0).to({scaleX:1},8,cjs.Ease.get(1)).wait(4));

	// Слой_1
	this.instance_4 = new lib.btn_round();
	this.instance_4.parent = this;
	this.instance_4.setTransform(0,0,0.012,0.012);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({scaleX:1.2,scaleY:1.2},5,cjs.Ease.get(1)).to({scaleX:1,scaleY:1},4,cjs.Ease.quadInOut).to({_off:true},9).wait(3));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-0.2,-0.2,0.5,0.5);


(lib.banner = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{loop:75});

	// timeline functions:
	this.frame_205 = function() {
		this.gotoAndPlay('loop');
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(205).call(this.frame_205).wait(1));

	// logo
	this.instance = new lib.logo_iqos();
	this.instance.parent = this;
	this.instance.setTransform(1,-261.4,0.54,0.54,0,0,0,0.2,-0.7);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:1},15).wait(191));

	// urText
	this.instance_1 = new lib.urText_v();
	this.instance_1.parent = this;
	this.instance_1.setTransform(0.1,267.1,1,1,0,0,0,0.1,0.3);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({regY:0.2,scaleX:1,alpha:1},15).wait(191));

	// dev
	this.instance_2 = new lib.dev_1("single",0);
	this.instance_2.parent = this;
	this.instance_2.setTransform(226,-53);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(75).to({_off:false},0).to({x:-4},10,cjs.Ease.quartOut).wait(5).to({mode:"synched",loop:false},0).wait(35).to({startPosition:11},0).to({x:-225},10,cjs.Ease.quartIn).to({_off:true},1).wait(70));

	// t2
	this.instance_3 = new lib.t2();
	this.instance_3.parent = this;
	this.instance_3.setTransform(0,142.5);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(75).to({_off:false},0).to({alpha:1},10).wait(40).to({alpha:0},10).to({_off:true},1).wait(70));

	// btn
	this.instance_4 = new lib.btn("synched",0,false);
	this.instance_4.parent = this;
	this.instance_4.setTransform(-0.1,211.6,1.06,1.06,0,0,0,-0.1,0.4);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(25).to({_off:false},0).wait(82).to({startPosition:20},0).wait(2).to({scaleX:1,scaleY:1},0).wait(2).to({scaleX:1.06,scaleY:1.06},0).wait(3).to({startPosition:20},0).wait(2).to({scaleX:1,scaleY:1},0).wait(2).to({scaleX:1.06,scaleY:1.06},0).wait(88));

	// t1
	this.instance_5 = new lib.t1_v();
	this.instance_5.parent = this;
	this.instance_5.setTransform(0,125.5);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(15).to({_off:false},0).to({alpha:1},10,cjs.Ease.cubicOut).wait(40).to({alpha:0},10).to({_off:true},1).wait(69).to({_off:false},0).to({alpha:1},10,cjs.Ease.cubicOut).wait(40).to({alpha:0},10).wait(1));

	// bgImg
	this.instance_6 = new lib.bgImg_1();
	this.instance_6.parent = this;
	this.instance_6.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).to({alpha:1},15).wait(50).to({alpha:0},10).to({_off:true},1).wait(59).to({_off:false},0).to({alpha:1},10).wait(50).to({alpha:0},10).wait(1));

	// bg
	this.instance_7 = new lib.bg();
	this.instance_7.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(206));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,-300,300,600);


// stage content:
(lib._300x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// cover
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#666666").ss(2,2,0,3).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// banner
	this.instance = new lib.banner();
	this.instance.parent = this;
	this.instance.setTransform(150.1,300.1,1,1,0,0,0,0.1,0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(149,299,302,602);
// library properties:
lib.properties = {
	id: '0A6E3F5DF6B342F4AF907DBE848CDF8D',
	width: 300,
	height: 600,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/bgImg.jpg", id:"bgImg"},
		{src:"images/dev.png", id:"dev"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['0A6E3F5DF6B342F4AF907DBE848CDF8D'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;