(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.dev_24 = function() {
	this.initialize(img.dev_24);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,206,232);


(lib.dev_24_open = function() {
	this.initialize(img.dev_24_open);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,92,132);


(lib.dev_3duo = function() {
	this.initialize(img.dev_3duo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,336,636);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.urText = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1,2,0,3).p("A1djBMAq7AAAIAAGDMgq7AAAg");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AFaCNIAAhGIAIAAIAAALQAIgNAMAAQALABAHAHQAIAIAAANQAAANgIAHQgHAIgLAAQgMAAgIgMIAAAbgAFnBTQgFAGAAAJQAAAJAFAGQAHAFAHABQAHgBAHgFQAFgGAAgKQAAgJgGgFQgFgGgIAAQgIAAgGAGgAA4CNIAAhGIAIAAIAAALQAJgNAMAAQAKABAIAHQAIAIAAANQAAANgIAHQgIAIgKAAQgMAAgJgMIAAAbgABGBTQgGAGAAAJQAAAJAGAGQAGAFAHABQAIgBAGgFQAFgGAAgKQAAgJgFgFQgGgGgIAAQgHAAgGAGgAklCLIACgHQAEACAFABQAEgBACgCQACgBADgHIgZg1IAJAAIAUAsIARgsIAJAAIgXA4QgDAIgFADQgDAEgHgBQgHAAgEgCgAvICNIAAgRIg8AAIAAhIIAJAAIAABBIApAAIAAhBIAIAAIAABBIAKAAIgBAYgAIGCKIAAgOIguAAIAAg1IAIAAIAAAvIAeAAIAAgvIAIAAIAAAvIAIAAIgBAUgArgCKIAAgOIgrAAIgCAOIgGAAIAAgUIAFAAQAIgNAAgZIAAgJIAmAAIAAAvIAIAAIgBAUgAr/BVQAAAVgGAMIAdAAIAAgoIgXAAgAM7B5QgGgEAAgIQAAgIAGgFQAHgFAKAAQAHAAAJACIAAgBQAAgIgEgDQgEgDgIgBQgIABgIADIgCgGQAKgFAJAAQAMAAAGAGQAFAGAAAKIAAAgIgIAAIAAgHQgGAJgNAAQgIAAgGgFgANBBlQgEACAAAGQAAAEAEAEQAEADAGAAQAHAAAFgFQAGgEAAgGIAAgFQgJgDgHAAQgIABgEADgAMEB2QgIgJAAgLQAAgMAIgIQAIgJALAAQANABAJAJIgFAGQgIgIgJAAQgIAAgFAGQgGAGAAAJQAAAJAGAFQAFAHAJAAQAIgBAIgHIAFAEQgJALgNAAQgLAAgIgIgAKrB5QgGgEAAgIQAAgIAGgFQAIgFAJAAQAIAAAJACIAAgBQAAgHgFgEQgDgDgIgBQgJABgIADIgCgGQAKgFAKAAQALAAAGAGQAGAGAAAKIAAAgIgIAAIAAgHQgIAJgMAAQgIAAgGgFgAKxBlQgEACAAAGQAAAEAEAEQAEADAGAAQAHAAAGgFQAFgEAAgGIAAgFQgJgDgHAAQgHABgFADgAGgB5QgGgEAAgIQAAgIAGgFQAHgFAKAAQAHAAAJACIAAgBQAAgHgEgEQgEgDgIgBQgJABgHADIgDgGQALgFAJAAQALAAAGAGQAGAGAAAKIAAAgIgIAAIAAgHQgHAJgMAAQgIAAgGgFgAGmBlQgEACAAAGQAAAEAEAEQAEADAFAAQAIAAAFgFQAFgEAAgGIAAgFQgJgDgGAAQgIABgEADgAD1B2QgIgJAAgLQAAgMAIgIQAHgJAMAAQANABAJAJIgFAGQgIgIgJAAQgIAAgGAGQgFAGAAAJQAAAJAGAFQAFAHAJAAQAIgBAIgHIAFAEQgJALgNAAQgMAAgHgIgAC7B2QgIgJAAgLQAAgMAHgIQAJgJALAAQANABAJAJIgFAGQgIgJgJAAQgGABgHAFQgFAFgBAHIAZAAIAAAHIgZAAQABAJAFADQAHAGAHAAQAIAAAIgIIAFAEQgEAGgFACQgGADgHAAQgMAAgHgIgACBB2QgIgHAAgNQAAgMAHgIQAIgJALAAQALAAAHAJQAHAIAAAMIAAADIgrAAQAAAIAGAFQAFAFAIAAQAKAAAHgHIAFAEQgJAKgNAAQgMAAgHgIgACHBSQgFAFgBAHIAjAAQgBgHgFgFQgDgGgJAAQgHAAgEAGgAigB2QgIgJAAgLQAAgMAIgIQAJgJALAAQANAAAHAJQAIAIAAAMQAAALgIAJQgIAIgMAAQgLAAgJgIgAiaBTQgGAGAAAJQAAAJAGAFQAGAHAIAAQAJAAAGgHQAFgGAAgIQAAgJgGgGQgFgGgJAAQgIAAgGAGgAl2B5QgGgEAAgIQAAgIAGgFQAHgFAKAAQAHAAAJACIAAgBQAAgHgEgEQgEgDgIgBQgIABgIADIgCgGQAKgFAJAAQAMAAAGAGQAFAGAAAKIAAAgIgIAAIAAgHQgGAJgNAAQgIAAgGgFgAlwBlQgEACAAAGQAAAEAEAEQAEADAGAAQAHAAAFgFQAFgEAAgGIAAgFQgIgDgHAAQgIABgEADgAmtB2IAEgGQAIAHAKAAQAFAAAEgCQAEgEAAgDQAAgFgDgCQgEgDgGABIgIAAIAAgHIAIAAQAFAAADgCQAEgDAAgEQAAgEgEgCQgDgCgFgBQgJABgHAFIgEgGQAJgGAMgBQAIAAAGAFQAFAEAAAGQAAAJgJADQAKAEAAAKQAAAGgFAFQgGAFgKAAQgNAAgJgIgAn8B5QgGgEAAgIQAAgIAGgFQAIgFAJAAQAIAAAJACIAAgBQAAgHgFgEQgDgDgIgBQgJABgIADIgCgGQAKgFAJAAQAMAAAGAGQAFAFAAALIAAAgIgHAAIAAgHQgIAJgMAAQgIAAgGgFgAn2BlQgEACAAAGQAAAEAEAEQAEADAGAAQAHAAAFgFQAGgEAAgGIAAgFQgJgDgHAAQgHABgFADgAptB2QgIgJAAgLQAAgLAIgJQAIgJAMAAQAMABAJAJIgFAGQgHgIgKAAQgIAAgFAGQgGAGAAAJQAAAIAGAGQAGAHAIAAQAJgBAHgHIAGAEQgKALgMAAQgMAAgIgIgAtfB5QgGgEAAgIQAAgIAGgFQAHgFAKAAQAHAAAJACIAAgBQAAgHgEgEQgEgDgIgBQgJABgHADIgDgGQALgFAJAAQALAAAGAGQAGAGAAAKIAAAgIgIAAIAAgHQgHAJgMAAQgIAAgGgFgAtZBlQgEACAAAGQAAAEAEAEQAEADAFAAQAIAAAFgFQAFgEAAgGIAAgFQgJgDgGAAQgIABgEADgAQCB8IAAgLIAJAAIAAALgAPnB8IAAg1IAIAAIAAA1gAPEB8IAAguIgTAAIAAgHIAuAAIAAAHIgTAAIAAAugAObB8IAAgqIggAqIgIAAIAAg1IAIAAIAAAqIAggqIAIAAIAAA1gAKWB8IAAgXIgfAAIAAAXIgIAAIAAg1IAIAAIAAAXIAfAAIAAgXIAIAAIAAA1gAI4B8IAAg1IAIAAIAAA1gAIcB8IAAg1IAIAAIAAA1gAE3B8IAAguIgTAAIAAgHIAuAAIAAAHIgTAAIAAAugAAAB8IAAgqIgfAqIgIAAIAAg1IAIAAIAAAqIAfgqIAIAAIAAA1gAhhB8IAAg1IAbAAQAIAAAEAEQAFADAAAHQAAAIgJADQAMAFAAAJQAAAHgFADQgFAEgKAAgAhYB2IARAAQAGAAADgDQAEgCAAgEQAAgFgEgCQgDgBgHAAIgQAAgAhYBeIAQAAQAFAAADgCQADgDAAgEQAAgDgDgCQgDgCgFgBIgQAAgAi5B8IAAgoIgUAbIgUgbIAAAoIgHAAIAAg1IAHAAIAUAcIAUgcIAIAAIAAA1gAoRB8IAAgXIgfAAIAAAXIgIAAIAAg1IAIAAIAAAXIAfAAIAAgXIAIAAIAAA1gAqOB8IAAgqIggAqIgIAAIAAg1IAIAAIAAAqIAggqIAIAAIAAA1gArRB8IAAg1IAIAAIAAA1gAt0B8IAAgXIgfAAIAAAXIgIAAIAAg1IAIAAIAAAXIAfAAIAAgXIAIAAIAAA1gAu2B8IAAg1IAIAAIAAA1gAOBA7QgFgEAAgFIAFgBQADAIAHAAQAGAAADgIIAFABQAAAFgFAEQgDAEgGAAQgHAAgDgEgAqoA7QgEgEgBgFIAGgBQACAIAHAAQAHAAACgIIAGABQgBAFgEAEQgEAEgGAAQgGAAgEgEgAJBA/IAAgKIAJAAIAAAKgAIuA/IAAgKIAKAAIAAAKgAPnA7IAAgJIAJAAIAAAJgAIcA7IAAgJIAJAAIAAAJgArRA7IAAgJIAJAAIAAAJgAu3A7IAAgJIAJAAIAAAJgArOAuIAAhGIAIAAIAAALQAJgMAMAAQAKAAAIAIQAIAHAAAMQAAANgIAHQgIAIgKAAQgMAAgJgLIAAAbgArAgMQgGAHAAAHQAAAJAGAGQAGAGAIAAQAIAAAFgGQAGgFAAgKQAAgIgGgGQgGgGgHAAQgIAAgGAGgAxrAuIAAhGIAIAAIAAALQAJgMAMAAQAKAAAIAIQAHAHAAAMQAAANgHAHQgIAIgKAAQgNAAgIgLIAAAbgAxdgMQgGAGAAAIQAAAJAGAGQAGAGAHAAQAJAAAFgGQAFgFAAgKQAAgIgFgGQgFgGgJAAQgHAAgGAGgAE0AqIAAgNIgsAAIgBANIgHAAIAAgUIAGAAQAHgNAAgXIAAgKIAmAAIAAAuIAJAAIAAAAIACAAIADAAIAEgDQACgCAAgFIACgMIAAgYIAnAAIAAA1IgIAAIAAguIgXAAIgBAVQAAAIgCAGQgCAGgCABIgFAEIgKABIgBAMgAEVgKQAAAVgHALIAdAAIAAgnIgWAAgAy9AqIAAgNIgsAAIgBANIgHAAIAAgUIAGAAQAHgOAAgWIAAgKIAnAAIAAAuIAIAAIgBAUgAzcgKQAAATgGANIAdAAIAAgnIgXAAgATYAWQgIgIAAgOIABgQIACgHIAEgHIAFgEIAIgEIAegHIACAHIgdAHQgIACgEAFQgDAEgBAIQAHgMAPABQALgBAIAJQAHAHAAALQAAALgIAIQgHAIgMAAQgNAAgHgIgATegLQgFAFAAAJQAAAJAFAFQAGAGAIAAQAIAAAGgGQAFgFAAgJQAAgJgGgFQgFgGgIABQgIgBgGAGgASBAWQgIgIAAgMQAAgLAIgIQAIgIAMAAQAMAAAJAKIgFAFQgHgIgJAAQgIAAgGAGQgGAHAAAHQAAAJAGAGQAGAGAIAAQAIAAAIgIIAGAFQgJAKgNAAQgMAAgIgIgAQ9AWQgIgIAAgMQAAgLAIgIQAIgIAMAAQANAAAHAIQAIAIAAALQAAAMgIAIQgIAIgMAAQgMAAgIgIgARDgMQgFAGAAAIQAAAKAFAFQAGAGAIAAQAJAAAGgGQAFgGAAgJQAAgIgGgGQgFgGgJAAQgIAAgGAGgALIAWQgIgJAAgLQAAgLAIgIQAIgIAMAAQAMAAAIAIQAIAJAAAKQAAALgIAJQgIAIgMAAQgMAAgIgIgALOgMQgGAHAAAHQAAAJAGAGQAGAGAIAAQAJAAAFgGQAGgGAAgJQAAgHgGgHQgGgGgIAAQgJAAgFAGgAIQAWQgIgIAAgMQAAgLAIgIQAIgIAMAAQAMAAAIAIQAIAIAAALQAAAMgIAIQgIAIgMAAQgMAAgIgIgAIWgMQgGAHAAAHQAAAJAGAGQAGAGAIAAQAJAAAGgGQAFgGAAgJQAAgIgGgGQgGgGgIAAQgIAAgGAGgAlkAWQgHgIAAgMQAAgLAHgIQAHgIALAAQAMAAAHAIQAHAJAAALIgBACIgqAAQABAIAFAGQAFAEAIAAQAJAAAIgIIAFAFQgJAKgOAAQgLAAgIgIgAlegOQgEAGgBAHIAiAAQgBgIgEgEQgEgGgIAAQgGABgGAEgAnaAZQgGgEAAgIQAAgJAGgEQAGgDALgBQAJAAAIACIAAgBQAAgHgFgEQgDgDgIAAQgJAAgIADIgCgHQAKgEAJAAQAMAAAGAGQAFAFAAALIAAAgIgHAAIAAgIQgIAJgMAAQgIAAgGgFgAnUAEQgEADAAAGQAAAFAEADQAEACAGAAQAHAAAFgDQAGgFAAgGIAAgFQgIgCgIAAQgHAAgFACgApLAWIAEgGQAIAHAKAAQAGAAAEgCQADgDAAgFQAAgEgDgCQgEgCgGgBIgHAAIAAgFIAHAAQAGAAADgDQADgCAAgEQAAgEgDgCQgDgCgGAAQgJAAgHAFIgEgGQAIgGANAAQAKAAAEAEQAFADAAAHQAAAJgIADQAKADAAAKQAAAGgGAFQgGAFgKAAQgMAAgKgIgAwiAWQgIgIAAgMQAAgLAIgIQAIgIAMAAQAMAAAIAIQAIAIAAALQAAAMgIAIQgIAIgMAAQgNAAgHgIgAwdgMQgFAHAAAHQAAAJAGAGQAFAGAJAAQAIAAAGgGQAGgGAAgJQAAgIgGgGQgGgGgIAAQgJAAgGAGgAyqAWQgIgJAAgLQAAgKAIgJQAIgIAMAAQAMAAAIAIQAIAIAAALQAAALgIAJQgIAIgMAAQgMAAgIgIgAykgMQgGAGAAAIQAAAKAGAFQAGAGAIAAQAIAAAGgGQAGgGAAgJQAAgIgGgGQgFgGgJAAQgJAAgFAGgA0eAWIAEgGQAIAHAKAAQAHAAADgCQAEgDAAgFQAAgDgEgDQgEgCgGgBIgHAAIAAgFIAHAAQAGAAADgDQADgCAAgEQAAgEgDgCQgDgCgGAAQgJAAgHAFIgEgGQAIgGANAAQAKAAAEAEQAFADAAAHQAAAJgIADQAKADAAAKQAAAGgGAFQgFAFgLAAQgMAAgKgIgAL+AdIABgHIAEAAIAEAAIADgDIADgHIACgkIAmAAIAAA1IgIAAIAAguIgXAAIAAACIgBATIgCAOIgEAHIgFAEIgFABgAgOAdIABgHIAEAAIAEAAIADgDQACgCAAgFIABgMIABgYIAmAAIAAA1IgIAAIAAguIgWAAIgBAVQgBAIgCAGQgBAGgDABIgDAEIgGABgAUVAdIAAgLIAKAAIAAALgAS3AdIAAg1IAIAAIAAA1gAQIAdIgQgWIgRAWIgJAAIAVgbIgUgaIAJAAIAQAVIAQgVIAJAAIgVAZIAWAcgAPIAdIAAg1IAIAAIAAA1gAO0AdIAAgYIgfAAIAAAYIgIAAIAAg1IAIAAIAAAXIAfAAIAAgXIAIAAIAAA1gANqAdIAAguIgTAAIAAgHIAuAAIAAAHIgTAAIAAAugANCAdIAAg1IAIAAIAAA1gAKwAdIAAgYIgfAAIAAAYIgIAAIAAg1IAIAAIAAAXIAfAAIAAgXIAIAAIAAA1gAJPAdIAAg1IAaAAQAJAAAEADQAFAFAAAFQAAAKgJACQAMADAAAKQAAAHgFAEQgGAEgJAAgAJXAWIASAAQAGAAADgCQAEgCAAgFQAAgFgEgBQgEgCgGgBIgRAAgAJXgBIARAAQAGAAACgCQADgCAAgFQAAgDgDgCQgCgCgGAAIgRAAgAH4AdIAAguIgeAAIAAAuIgIAAIAAg1IAuAAIAAA1gAGfAdIAAgTIgPAAIgPATIgKAAIAQgVQgGgCgEgDQgEgDAAgHQAAgIAFgFQAGgEAJAAIAaAAIAAA1gAGEgOQgDADAAAEQAAAFAEACQAEADAFAAIARAAIAAgUIgRAAQgGAAgEADgADQAdIAAgqIggAqIgIAAIAAg1IAIAAIAAAqIAggqIAIAAIAAA1gACVAdIgTgZIgMAMIAAANIgIAAIAAg1IAIAAIAAAeIAegeIAKAAIgXAXIAXAegAA0AdIAAg1IAIAAIAAAUIAPAAQAJAAAGAEQAGADAAAJQAAAIgGAEQgFAFgJAAgAA8AWIAPAAQAGAAADgDQAEgCAAgFQAAgFgEgDQgEgCgFAAIgPAAgAggAdIAAg1IAIAAIAAA1gAhDAdIAAguIgUAAIAAgHIAvAAIAAAHIgTAAIAAAugAiJAdIAAgqIggAqIgHAAIAAg1IAIAAIAAAqIAggqIAIAAIAAA1gAjMAdIAAgqIghAqIgHAAIAAg1IAIAAIAAAqIAggqIAIAAIAAA1gAkHAdIAAgYIgfAAIAAAYIgIAAIAAg1IAIAAIAAAXIAfAAIAAgXIAIAAIAAA1gAmAAdIAAgXIgIAEIgKACQgIAAgFgFQgFgEAAgHIAAgUIAIAAIAAATQAAAFADACQAEADAEgBQAKAAAHgEIAAgYIAIAAIAAA1gAnvAdIAAgYIgfAAIAAAYIgIAAIAAg1IAIAAIAAAXIAfAAIAAgXIAIAAIAAA1gApiAdIAAgqIggAqIgIAAIAAg1IAIAAIAAAqIAggqIAIAAIAAA1gArpAdIAAhAIgpAAIAABAIgIAAIAAhIIA5AAIAABIgAtUAdIAAgLIAJAAIAAALgAtqAdIAAgTIgPAAIgPATIgKAAIAQgVQgGgCgEgDQgEgDAAgHQAAgIAFgFQAGgEAJAAIAaAAIAAA1gAuFgOQgDADAAAEQAAAFAEACQAEADAFAAIARAAIAAgUIgRAAQgGAAgEADgAvjAdIAAg1IAaAAQAJAAAEADQAFAFAAAFQAAAKgJACQALADAAAKQAAAHgFAEQgFAEgJAAgAvbAWIASAAQAFAAAEgCQADgCAAgFQAAgFgDgBQgEgCgGgBIgRAAgAvbgBIARAAQAFAAACgCQADgCAAgFQAAgDgCgCQgDgCgFAAIgRAAgAutgXQAHgDAAgFIAAgBIgEAAIAAgLIAKAAIAAAKQAAAFgDAEQgDADgGABgAiigjQgEgEgBgFIAFgCQACAIAHgBQAIABACgIIAFACQgBAGgEADQgFADgFAAQgFAAgEgDgAS3gkIAAgIIAJAAIAAAIgAPHgkIAAgIIAJAAIAAAIgANBgkIAAgIIAJAAIAAAIgAgggkIAAgIIAJAAIAAAIgAHugzIACgHQAFACAEAAQADAAADgDQADgCACgFIgZg2IAJAAIAUAtIARgtIAIAAIgWA4QgDAHgFAFQgDADgHAAQgFAAgGgCgAKcgyIAAhGIAIAAIAAALQAJgMAMAAQAKAAAIAIQAIAHAAANQAAANgIAHQgIAIgKAAQgNAAgIgMIAAAbgAKqhsQgGAFAAAKQAAAJAGAGQAGAGAIAAQAHAAAGgFQAFgGAAgKQAAgKgFgFQgFgGgIAAQgIAAgGAGgAvSgyIAAhGIAIAAIAAALQAIgMAMAAQALAAAHAIQAIAHAAANQAAANgIAHQgHAIgLAAQgMAAgIgMIAAAbgAvFhsQgFAFAAAKQAAAJAFAGQAGAGAIAAQAHAAAHgFQAFgGAAgKQAAgKgGgFQgFgGgIAAQgIAAgGAGgARdg0IAAgOIgrAAIgCAOIgGAAIAAgVIAGAAQAHgOAAgYIAAgJIAmAAIAAAvIAIAAIAAAAIACABIAEgBIADgDIADgHIACgMIAAgZIAmAAIAAA2IgIAAIAAgvIgWAAIAAABIgBAVIgCAOQgCAGgCACIgFADIgGABIgEgBIgBAOgAQ/hpQAAATgHANIAdAAIAAgoIgWAAgAmHhJQgKAIgNAAQgQAAgKgLQgLgLAAgQQAAgOALgMQAKgLAQAAQARAAAKALQAKAKAAAQQAAAPgIAKIAJAIIgFAGgAmyh8QgIAJAAAMQAAANAIAJQAIAJAMgBQAKABAHgGIgNgLIAFgGIAOALQAGgHAAgMQAAgMgIgJQgJgIgMAAQgMAAgIAIgAMfhJIAEgFQAIAGAKABQAGgBADgDQAEgBAAgGQAAgDgDgDQgEgCgGAAIgHAAIAAgGIAHAAQAFAAAEgEQADgBAAgFQAAgDgDgDQgEgCgFAAQgJAAgHAFIgEgFQAJgHAMAAQAIAAAGAEQAFAEAAAHQAAAIgIAEQAKADAAAKQAAAHgGAFQgHAEgJAAQgLABgLgJgAIvhJQgIgIAAgMQAAgLAIgJQAJgIALAAQAMAAAJAJIgFAGQgHgIgJAAQgIAAgGAGQgGAHAAAIQAAAJAGAGQAGAGAIAAQAJAAAIgIIAFAFQgJAKgNAAQgLABgJgJgAGfhJQgIgJAAgLQAAgLAIgJQAIgIAMAAQANAAAIAKIgEAFQgIgIgJAAQgIAAgFAFQgFAFgBAIIAYAAIAAAHIgYAAQABAHAFAFQAGAGAIAAQAIAAAIgJIAFAFQgEAFgFACQgFADgIAAQgLABgJgJgADrhIQgHgHgBgKIgMAAIAAAXIgIAAIAAg2IAIAAIAAAYIAMAAQABgKAHgIQAIgHALAAQALAAAIAIQAHAJAAALQAAAMgHAIQgIAJgMgBQgLABgHgIgADwhsQgFAFAAAKQAAAJAFAGQAGAGAIAAQAIAAAFgGQAFgGAAgJQAAgKgFgFQgFgGgJAAQgIAAgFAGgAhzhJQgIgHAAgNQAAgLAIgJQAHgIALAAQAMAAAGAIQAHAIAAAMIAAAEIgrAAQABAIAGAEQAGAFAGABQAJgBAIgHIAFAEQgJAKgNAAQgKAAgJgIgAhthtQgFAFgBAIIAjAAQAAgIgFgFQgFgFgHAAQgHAAgFAFgAlhhMQgKgKAAgRQAAgOALgMQAKgLAQAAQARAAAKALQAKAKAAAQQAAAQgKALQgLALgQAAQgQAAgLgLgAlah8QgIAJAAAMQAAANAIAJQAIAJAMgBQANABAIgJQAIgJAAgNQAAgMgIgJQgJgIgMAAQgMAAgIAIgAtGhJQgIgIAAgMQAAgLAIgJQAJgIALAAQAMAAAJAJIgFAGQgHgIgJAAQgIAAgGAGQgFAGAAAJQAAAJAFAGQAGAGAIAAQAJAAAIgIIAFAFQgJAKgNAAQgLABgJgJgAwRhJQgIgIAAgMQAAgLAIgJQAIgIAMAAQALAAAJAIQAIAIAAAMQAAAMgIAIQgJAJgMgBQgMABgHgJgAwMhsQgFAHAAAIQAAAJAGAGQAFAGAJAAQAJAAAFgGQAFgGAAgJQAAgJgFgGQgGgGgJAAQgIAAgGAGgAFjhFQgGgFAAgIQAAgIAGgFQAGgFALAAQAHAAAJADIAAgCQAAgGgEgFQgFgDgHAAQgHAAgJADIgCgGQAKgEAJgBQAMAAAGAHQAFAFAAAKIAAAhIgIAAIAAgIQgGAJgNAAQgIAAgGgEgAFphaQgEADAAAFQAAAFAEADQAEADAGAAQAIgBAEgEQAFgDAAgHIAAgFQgGgCgJAAQgIAAgEADgACMhCIABgHIAEABIAEgBIADgDIACgHIACgMIABgZIAmAAIAAA2IgIAAIAAgvIgXAAIAAABIgBAVIgCAOQgBAGgDACQgCADgDAAIgFABgAkVhNIAFgGQAGAGAGACQAFACAIAAQAIAAAEgDQAFgDAAgGQAAgGgEgDQgEgDgLgCQgOgCgFgFQgGgFAAgJQAAgJAHgFQAHgGAKAAQAPAAALAJIgFAHQgJgJgMABQgHgBgEAEQgEADAAAFQAAAGAEADQAEADALADQANADAFAEQAGAFAAAIQAAAJgHAHQgIAFgKAAQgQAAgOgMgArfhFQgGgFAAgIQAAgIAHgFQAGgFAKAAQAIAAAJADIAAgCQAAgHgEgEQgFgDgHAAQgHAAgJADIgDgGQAKgEAKgBQALAAAGAHQAGAFAAAKIAAAhIgIAAIAAgIQgHAJgMAAQgJAAgGgEgArYhaQgEACAAAGQAAAFADADQAFADAFAAQAIgBAFgEQAFgDAAgHIAAgFQgHgCgJAAQgHAAgEADgATIhCIAAgUIgOAAIgPAUIgKAAIAQgVQgGgBgEgFQgEgEAAgGQAAgHAFgFQAFgFAKAAIAZAAIAAA2gASuhuQgDACAAAFQAAAEADAEQAEADAGgBIAQAAIAAgUIgQAAQgGAAgEADgAP6hCIAAgrIggArIgIAAIAAg2IAIAAIAAArIAggrIAIAAIAAA2gAO/hCIgUgZIgLAMIAAANIgIAAIAAg2IAIAAIAAAfIAdgfIAKAAIgWAYIAXAegAN8hCIAAgrIggArIgIAAIAAg2IAIAAIAAArIAggrIAIAAIAAA2gAMIhCIAAgrIggArIgIAAIAAg2IAIAAIAAArIAggrIAIAAIAAA2gAJlhCIAAg2IAIAAIAAA2gAFJhCIAAgWIgIADIgKABQgJAAgEgDQgFgEAAgJIAAgUIAIAAIAAATQAAAFADADQADACAFAAQAKAAAHgEIAAgZIAIAAIAAA2gACChCIgTgZIgMAMIAAANIgIAAIAAg2IAIAAIAAAfIAegfIAKAAIgXAYIAXAegAA/hCIAAgrIggArIgIAAIAAg2IAIAAIAAArIAggrIAIAAIAAA2gAgihCIAAg2IAaAAQAIAAAEAEQAFADAAAHQAAAIgJAEQAMADAAALQAAAGgFAEQgGAEgIAAgAgahJIASAAQAHAAABgDQAEgCAAgEQAAgEgEgCQgDgDgGAAIgRAAgAgahgIARAAQAEgBAEgCQACgCAAgEQAAgDgCgDQgCgCgGAAIgRAAgAiKhCIAAgXIgfAAIAAAXIgIAAIAAg2IAIAAIAAAYIAfAAIAAgYIAIAAIAAA2gAnbhCIAAhJIAIAAIAABJgAoQhCIAAgUIgPAAIgPAUIgKAAIARgVQgHgBgDgFQgEgEAAgGQAAgHAFgFQAFgFAKAAIAZAAIAAA2gAoqhuQgDACAAAFQAAAFADADQAEADAFgBIARAAIAAgUIgRAAQgFAAgEADgApGhCIAAgXIgfAAIAAAXIgIAAIAAg2IAIAAIAAAYIAfAAIAAgYIAIAAIAAA2gAqAhCIAAgXIgfAAIAAAXIgIAAIAAg2IAIAAIAAAYIAfAAIAAgYIAIAAIAAA2gAsDhCIAAgvIgUAAIAAgHIAvAAIAAAHIgTAAIAAAvgAtmhCIAAgrIghArIgHAAIAAg2IAIAAIAAArIAggrIAIAAIAAA2gAwphCIgUgZIgLAMIAAANIgIAAIAAg2IAIAAIAAAfIAdgfIAKAAIgWAYIAXAegAxshCIAAgrIggArIgIAAIAAg2IAIAAIAAArIAggrIAIAAIAAA2gAzghCIAAhJIAfAAQALAAAIAHQAEAFAAAGQAAAMgLAFQAPAFAAANQAAAJgHAGQgIAFgLAAgAzYhKIAYAAQAJABAEgEQAFgEAAgFQAAgGgFgEQgFgDgJAAIgXAAgAzYhqIAVAAQAIAAAEgEQAFgDAAgHQAAgFgEgEQgFgCgHAAIgWAAgAJliDIAAgJIAJAAIAAAJg");
	this.shape_1.setTransform(0.1,0.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.urText, new cjs.Rectangle(-138.3,-20.4,276.8,40.8), null);


(lib.t1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AH1EiQgWgVAAgjQgBgrAfggQAfggApABQAbAAARALQASAMAJARIgVAOQgTgfgggBQgeAAgXAZQgWAaAAAgQAAAaAPAOQAQAPAVAAQAaAAAagXIAQARQgfAdgmAAQghAAgWgVgAnaEhQgXgXAAgiQAAgpAgggQAeggAqABQAkgBAWAWQAWAWAAAjQAAAqgfAgQgfAfgqAAQgiAAgXgWgAm/CvQgXAaAAAeQAAAbAQAPQAOAOAZAAQAeAAAWgYQAYgZAAgfQAAgbgQgOQgPgPgYgBQgeAAgXAZgAt7EhQgWgXAAgiQAAgpAfggQAfggApABQAkgBAXAWQAWAXAAAiQAAAqgfAgQgfAfgqAAQgjAAgXgWgAtgCvQgWAaAAAeQAAAaAPAQQAPAOAZAAQAeAAAWgYQAXgZAAgfQAAgbgPgOQgPgPgZgBQgeAAgXAZgAM5EzIAJgjIAgAAIgJAjgAKLEzIAviwIAaAAIgSBEIAtAAQAcAAAQAMQAPANABAVQgBAegWAQQgXAQgnAAgAKrEcIAqAAQAcABAQgLQAPgJAAgTQAAgNgLgGQgKgHgPAAIgwAAgAGJEzIAmiLIiNCLIgZAAIAuiwIAbAAIgmCKICOiKIAZAAIgwCwgACOEzIAqiZIhAAAIAGgXICYAAIgGAXIg+AAIgqCZgAAcEzIAliLIiNCLIgZAAIAviwIAaAAIglCKICNiKIAZAAIgwCwgAkmEzIAviwIBMAAQAaAAAPALQAPAMAAASQAAARgNANQgNALgTAFQAPADAHAKQAKAJAAAPQAAAXgUAPQgVAOghAAgAkGEdIA6AAQAWAAAOgIQANgJAAgPQAAgMgLgHQgLgGgQAAIg1AAgAjxDPIAyAAQAWAAANgIQANgJAAgPQAAgWghAAIgzAAgApHEzIAVhOIhlAAIgWBOIgaAAIAwiwIAaAAIgVBLIBlAAIAVhLIAaAAIgwCwgANTDvIAmiqIAfAAIg1CqgApWhaQgWgXABgiQAAgqAegfQAfggAqAAQAjAAAXAXQAWAXAAAhQAAAqgfAfQggAggpAAQgjAAgXgWgAo7jLQgWAZAAAeQAAAaAPAQQAPAPAZgBQAeABAWgZQAXgZAAgfQAAgagPgPQgPgPgZgBQgeAAgXAagABLhSQgQgMAAgXQAAgeAVgRQAWgRAjAAQAeAAAgAKIACgEQABgJABgIQgBgigugBQgZABgaAIIgEgVQAcgLAeAAQAhAAATAOQARAOABAaQgBAMgDAMIgaBkIgaAAIAHgcQgaAggoAAQgYgBgPgNgABliVQgPALAAASQgBAOAKAJQAMAIAPAAQAXAAAVgOQATgQAHgWIADgNQgdgHgcAAQgXAAgOAMgAgShIIAVhOIhkAAIgVBOIgaAAIAviwIAbAAIgVBLIBjAAIAVhLIAaAAIgvCwgAjKhIIglhSIgwApIgMApIgaAAIANgsIgZgnIhRBTIghAAIBlhnIguhJIAdAAIA+BmIAchmIAZAAIgbBmIB0hmIAhAAIhZBMIAsBkgArOhIIAzjBIh4B/IgCAAIg0h/Ig0DBIgaAAIA/juIAaAAIAzCCIB5iCIAfAAIhADug");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1, new cjs.Rectangle(-92,-31.1,184,62.2), null);


(lib.logo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhwByIglgkIh3AAQgcAAgTgFQgYgGgOgNQgTgTAAgjIAAhlQgBgHAGgFQAEgEAIAAICDAAQAdAAASAGQAZAEAOAOQASARABAlIAABkIAdAeQAEAEABAGQgBAGgFAFQgFAFgGAAQgGAAgEgDgAlTAAQABAZANAMIABABQANAKAaACICEAAIAAhZQgBgZgLgMIgDgCQgMgKgbgBIiEAAgAEoBNQglgBgRgLQgMgIgDgPIAAgEQABgGAEgEQAFgDAFAAQAHAAAFADQADADACAEIABADQAFAGAHADQAIADAPAAIBHAAQAnAAAMgGQAFgCACgHQACgFABgJIAAgCQgBgOgFgFQgKgHgZAAIhgAAQghABgOgMQgNgNAAgaIAAgMQAAgXARgMQAVgMA1gBIA0AAQAqAAASALQAPAJACAQIAAADQAAAGgDADQgGAFgGAAQgGAAgFgEQgEgCgBgEIgBgDQgFgIgMgCQgJgCgYgBIg1AAQghAAgKAGQgKAEAAAQIAAAHQAAAMAGAGQAIAFAWAAIBSAAQAoAAARAJQAWAMAAAiQAAAlgeAMQgRAHgmAAgAAgBNQguAAgYgOQghgRAAguIAAgnQAAgvAhgSQAYgNAuAAIAtAAQAvAAAYANQAgASAAAvIAAAnQAAAuggARQgYAOgvAAgAgVhQQgRANAAAdIAAAmQAAAcARAMQAOAKAdAAIBAAAQAeAAAPgKQARgMAAgcIAAgmQAAgdgRgNQgPgKgeAAIhAAAQgdAAgOAKgAnFBJQgFgFAAgHIAAihQAAgIAFgDQAEgGAHAAQAIAAAEAGQAEADABAIIAAChQgBAHgEAFQgEAEgIAAQgHAAgEgEg");
	this.shape.setTransform(2.6,0.5,1,1,0,0,0,0.6,0);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.logo, new cjs.Rectangle(-43.9,-11.2,91.8,23.5), null);


(lib.dev_24_open_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.dev_24_open();
	this.instance.parent = this;
	this.instance.setTransform(-46,-66);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.dev_24_open_1, new cjs.Rectangle(-46,-66,92,132), null);


(lib.dev_24_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.dev_24();
	this.instance.parent = this;
	this.instance.setTransform(-103,-116);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.dev_24_1, new cjs.Rectangle(-103,-116,206,232), null);


(lib.dev_3duo_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.dev_3duo();
	this.instance.parent = this;
	this.instance.setTransform(-168,-318);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.dev_3duo_1, new cjs.Rectangle(-168,-318,336,636), null);


(lib.btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AE3AmQgOgQAAgWQAAgVAOgPQAPgQAXAAQAXAAARAQIgLAOQgOgNgPAAQgOAAgKAKQgKALAAAOQAAAPAKALQAKALAOAAQAPAAAOgOIAMAMQgRASgZAAQgWAAgPgPgAjyAlQgPgPAAgWQAAgVAPgPQAPgQAXAAQAYAAAPAQQAPAPAAAVQAAAWgPAPQgQAQgXAAQgXAAgPgQgAjlgYQgJAKAAAOQAAAPAKALQAJALAPAAQAPAAAKgLQAKgKAAgQQAAgOgKgKQgKgLgPAAQgPAAgKALgAneAlQgPgPAAgWQAAgVAPgPQAQgQAXAAQAXAAAPAQQAPAPAAAVQAAAWgPAPQgQAQgXAAQgXAAgPgQgAnQgYQgKAKAAAOQAAAQAKAKQAKALAPAAQAPAAAKgLQAJgLAAgPQAAgOgKgKQgKgLgPAAQgPAAgJALgAGeAzIAAhlIASAAIAAAlIAXAAQASAAAKAIQALAIAAAPQAAAPgLAJQgKAJgSAAgAGwAjIAXAAQAVAAAAgRQAAgQgVAAIgXAAgAEBAzIAAhJIg0BJIgRAAIAAhlIASAAIAABKIAzhKIARAAIAABlgAB4AzIAAhUIggAAIAAgRIBTAAIAAARIghAAIAABUgAAzAzIAAhJIgzBJIgRAAIAAhlIARAAIAABKIA0hKIAQAAIAABlgAiCAzIAAhlIAuAAQATAAAIAJQAHAHAAAKQAAAQgPAHQAUAGAAASQAAAOgKAHQgKAHgRAAgAhwAjIAeAAQATAAAAgOQAAgOgVAAIgcAAgAhwgHIAZAAQATAAAAgOQAAgNgSAAIgaAAgAkrAzIAAgrIgxAAIAAArIgRAAIAAhlIARAAIAAArIAxAAIAAgrIASAAIAABlg");
	this.shape.setTransform(-0.3,0.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Слой_4
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AqsCbIAAk1IVZAAIAAE1g");

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.btn, new cjs.Rectangle(-68.4,-15.5,137,31), null);


(lib.bg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#A6CFD5").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.bg, new cjs.Rectangle(-150,-300,300,600), null);


(lib.arrow = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ah+B/Qg1g1AAhKQAAhJA1g1QA1g1BJAAQBLAAA1A1QA0A1AABJQAABKg0A1Qg1A1hLAAQhJAAg1g1gAh1B5QAyAwBDAAQBGAAAygxQAxgyAAhGQAAhFgxgyQgygxhGAAQhDAAgyAwQgwAwgCBEIC+AAIghghIAAgQIA1A1Ig1A2IAAgQIAhghIi+AAQABBFAxAvg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.arrow, new cjs.Rectangle(-18,-18,36,36), null);


(lib.t2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ag1AzIgBgDIAAgGIABgDQAAgBABAAQAAAAABgBQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAABQABAAAAAAQAAABABAAQAAABAAAAQAAABAAAAIAAAGQAAAAAAABQAAAAAAABQgBAAAAABQAAAAgBAAIgDABIgEgBgAATAyQAAAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAIAAgQIgkAAQgEAAgEgDQgDgEAAgEIABgFIAahAQAAAAAAgBQABAAAAAAQABgBAAAAQAAAAABAAIADABQAAAAABAAQAAABAAAAQABABAAAAQAAABAAAAIAAACIgZA/IAAADIAAAAIADAAIAiAAIAAgVQAAgFAFAAQAAAAABABQAAAAABAAQAAAAABAAQAAABAAAAIABADIAAAVIANAAQAAAAAAABQABAAAAAAQABAAAAAAQABABAAAAIABAEIgBADQAAAAgBAAQAAAAgBABQAAAAgBAAQAAAAAAAAIgNAAIAAAQQABAFgFgBIgEgBgAiCAzQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBgBgBAAIgBgEQAAgBAAAAQAAgBAAAAQABgBAAAAQABgBAAgBIAlgjQAIgGADgEQAEgHAAgJIAAgEQABgIgIgGQgGgEgJAAIgaAAIgEgBIgBgEQAAAAAAAAQAAgBAAAAQABgBAAAAQAAgBAAAAQABAAAAgBQABAAAAAAQABAAAAAAQAAAAABAAIAaAAQAOAAAIAHQAKAIgBAMIAAAEQABALgGAIQgDAFgJAIIggAeIAxAAQABAAAAABQABAAAAAAQABAAAAAAQABABAAAAIABADQAAAAAAABQAAAAAAABQgBAAAAABQAAAAgBAAIgDABgABfAxQAAAAgBgBQAAAAAAAAQAAgBAAAAQAAgBAAAAIAAgdIgdAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAAAgBIgCgDQAAAAAAAAQAAgBAAAAQABgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAQABAAAAAAQABgBAAAAIAdAAIAAgcQAAAAAAAAQAAgBAAAAQAAgBABAAQAAAAABAAIACgCQAFAAAAAEIAAAcIAeAAQAAAAAAABQABAAAAAAQABAAAAAAQAAABAAAAQABAAAAABQAAAAABABQAAAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAQgBABAAAAQAAAAgBAAQAAABAAAAQAAAAgBABQAAAAgBAAQAAAAAAAAIgeAAIAAAdQAAAFgFgBQAAAAAAAAQgBAAAAAAQgBAAAAAAQgBgBAAAAg");
	this.shape.setTransform(9.2,-35.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Слой_3
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("ACdA1QgRAAgJgLQgJgJAAgPIAAghQAAgkAjAAIAHAAQAkAAAAAkIAAAhQAAAPgKAJQgJALgRAAgACDgPIAAAhQABAKAFAIQAIAIAMAAIAHAAQAMAAAHgIQAHgIAAgKIAAghQAAgcgaAAIgHAAQgaAAAAAcgAA3A1QgLgBgJgHQgIgJAAgPIAAhFIABgCQAAAAABgBQAAAAABAAQAAAAABAAQAAAAAAAAQABAAAAAAQABAAAAAAQAAAAAAAAQABABAAAAIACACIAABFQgBALAIAGQAEAGAIAAIASAAQAJAAAEgGQAEgGAAgLIAAhEQAAAAAAgBQAAAAABAAQAAgBAAAAQABgBAAAAQABAAAAgBQAAAAABAAQAAAAAAAAQABAAAAAAQABAAAAAAQAAAAABAAQAAAAABAAQAAABABAAIABACIAABFQgBAOgGAJQgIAIgMABgAg7A1QgDgBgCgCQgCgDAAgCIAAhZQAAgEACgCQACgBADAAIAdAAQAiAAAAAkIAAAhQAAAPgIAJQgKALgQAAgAg5AsIAbAAQAMAAAHgIQAHgIAAgKIAAghQAAgcgaAAIgbAAgAjDA1IgCgCQgBAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAgBIACgCIACgBIAfAAQAIgBAFgFQADgEAAgIQAAgIgDgHQgGgGgHAAIgTAAQAAAAAAAAQgBAAAAAAQgBgBAAAAQgBAAAAgBIgBgCIABgCIADgBIAUAAQAHAAAFgFQADgEAAgIQAAgJgDgFQgGgFgHAAIgfAAQAAAAAAAAQgBAAAAAAQgBgBAAAAQAAAAAAgBIgCgCQAAgBAAAAQAAgBAAAAQABAAAAAAQAAgBABAAIACgBIAfAAQALAAAHAHQAIAJgBALQABAIgEAFQgDAGgGABQAGADADAHQAEAHgBAIQABALgIAIQgHAHgLABg");
	this.shape_1.setTransform(67.4,-36.2);

	this.instance = new lib.logo();
	this.instance.parent = this;
	this.instance.setTransform(-40.5,-35.9,0.54,0.54,0,0,0,-0.5,-1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance},{t:this.shape_1}]}).wait(1));

	// Слой_2
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgrAmIBKgmIAAAAIhKglIAAgNIBXAuIAAAKIhXAtg");
	this.shape_2.setTransform(35.3,-35.7);

	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(1));

	// Слой_1
	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("ACNCSIAmgsQAnAjAoAAQArgBAgggQAhggAKgwQgNAQgYAMQgZAMgcAAQgvAAgfgdQgegcgBgsQABg4AqgoIANgMQAZgTAggFQAPgEAQAAQA6ABAhAhQAjAjgBBEQABA6gZA1QgYA0gsAgQgsAhg3AAQhCAAgwgugAEHhhQgWAVgBAfQAAAaASAQQASAPAdAAQAkAAAWgVQAXgWAAgdQAAgbgTgQQgSgQgdgBQgiAAgXAXgAieCSIAlgsQAnAjAoAAQAqgBAfggQAiggALgwQgOAQgYAMQgZAMgaAAQgwAAgfgdQgfgbABgtQAAg4ApgoIAOgMQAmgbAxgBQA0ABAhAbIAHAGQAhAjAABEQAAA6gYA1QgZA1gsAfQgrAhg3AAQhBAAgvgugAglhhQgXAVABAfQAAAaARAQQASAPAcAAQAiAAAYgVQAXgWAAgdQAAgbgTgQQgSgQgcgBQgiAAgXAXgAmhCuQgkgSgRgbIAsgkQAmArAzAAQAkAAAYgUQAYgUAAgcQAAgZgTgPQgUgPghAAQgcAAgdAPIghgbIA3inIDQAAIgQA2IiXAAIgbBSQAWgIAYAAQAxAAAfAbQAfAbAAAtQAAA2grAnQgrAlhEABQgoAAgigSgAppC6IBNkhIhDASIgBg2IBogeIArAAIhfFjgAH3ASQgQgEgJgKQgMgLAAgPQAAgVAVgPIgZAAIADgWICTAAIgDAWIhSAAQgZANAAARQAAAVAoABQAdAAAWgMIgEAeQgYAKgdAAQgTgBgOgDgAHUhfIAEgXIBYAAQASgJAAgPQAAgUgnAAQgZAAgXAJIAFgeQAUgIAeAAQAdAAASALQAUALAAAWQAAARgPAMIAUAAIgDAXg");

	this.timeline.addTween(cjs.Tween.get(this.shape_3).wait(1));

}).prototype = getMCSymbolPrototype(lib.t2, new cjs.Rectangle(-63.9,-41.5,151.3,60.7), null);


(lib.banner = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// urText
	this.instance = new lib.urText();
	this.instance.parent = this;
	this.instance.setTransform(-0.5,269.7);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(120));

	// logo
	this.instance_1 = new lib.logo();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-75.4,-257.8,1.05,1.05,0,0,0,-0.1,-0.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(120));

	// dev_3duo
	this.instance_2 = new lib.dev_3duo_1();
	this.instance_2.parent = this;
	this.instance_2.setTransform(318,95);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(35).to({_off:false},0).to({x:168},16,cjs.Ease.get(1)).wait(44).to({x:-319},24,cjs.Ease.get(-1)).wait(1));

	// t2
	this.instance_3 = new lib.t2();
	this.instance_3.parent = this;
	this.instance_3.setTransform(181.9,156.3);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(45).to({_off:false},0).to({x:-58.1},10,cjs.Ease.get(1)).to({_off:true},57).wait(8));

	// dev_24_open
	this.instance_4 = new lib.dev_24_open_1();
	this.instance_4.parent = this;
	this.instance_4.setTransform(-76,-128);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(55).to({_off:false},0).to({_off:true},53).wait(12));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_55 = new cjs.Graphics().p("A+2eAMAAAg7/MA9tAAAMAAAA7/g");
	var mask_graphics_108 = new cjs.Graphics().p("A+2eAMAAAg7/IEaAAIemaGMAatAh5g");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(55).to({graphics:mask_graphics_55,x:47.5,y:108}).wait(53).to({graphics:mask_graphics_108,x:47.5,y:108}).wait(2).to({graphics:null,x:0,y:0}).wait(10));

	// dev_24
	this.instance_5 = new lib.dev_24_1();
	this.instance_5.parent = this;
	this.instance_5.setTransform(254,-32);
	this.instance_5._off = true;

	var maskedShapeInstanceList = [this.instance_5];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(10).to({_off:false},0).to({x:-16},15,cjs.Ease.get(1)).to({_off:true},85).wait(10));

	// arrow
	this.instance_6 = new lib.arrow();
	this.instance_6.parent = this;
	this.instance_6.setTransform(-53.9,-25.5);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(25).to({_off:false},0).to({x:-3.9},10,cjs.Ease.get(1)).to({_off:true},68).wait(17));

	// btn
	this.instance_7 = new lib.btn();
	this.instance_7.parent = this;
	this.instance_7.setTransform(-54.1,211.2,0.02,0.02,0,0,0,-2.5,0);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(10).to({_off:false},0).to({regX:-0.8,regY:0.7,scaleX:1,scaleY:1,x:-54.2},10,cjs.Ease.get(1)).wait(50).to({scaleX:0.96,scaleY:0.96,x:-54.1},2).to({scaleX:1,scaleY:1,x:-54.2},2).wait(3).to({scaleX:0.96,scaleY:0.96,x:-54.1},2).to({scaleX:1,scaleY:1,x:-54.2},2).to({_off:true},31).wait(8));

	// t1
	this.instance_8 = new lib.t1();
	this.instance_8.parent = this;
	this.instance_8.setTransform(-32.5,145.2);
	this.instance_8.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).to({alpha:1},10).wait(25).to({x:-242.5},10,cjs.Ease.get(-1)).to({_off:true},1).wait(74));

	// bg
	this.instance_9 = new lib.bg();
	this.instance_9.parent = this;

	this.instance_10 = new lib.bg();
	this.instance_10.parent = this;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_10},{t:this.instance_9}]}).wait(120));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,-300,300,600);


// stage content:
(lib._300x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// cover
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#666666").ss(2,1,1).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// banner
	this.instance = new lib.banner();
	this.instance.parent = this;
	this.instance.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(149,299,302,602);
// library properties:
lib.properties = {
	id: 'D78E0080C82B4A91A29A8C60B712AE41',
	width: 300,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/dev_24.png", id:"dev_24"},
		{src:"images/dev_24_open.png", id:"dev_24_open"},
		{src:"images/dev_3duo.png", id:"dev_3duo"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['D78E0080C82B4A91A29A8C60B712AE41'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;