(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.arrow = function() {
	this.initialize(img.arrow);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,124,12);


(lib.bgImg1 = function() {
	this.initialize(img.bgImg1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.bgImg2 = function() {
	this.initialize(img.bgImg2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.bgImg3 = function() {
	this.initialize(img.bgImg3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,340,600);


(lib.bgImg4 = function() {
	this.initialize(img.bgImg4);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.bgImg5 = function() {
	this.initialize(img.bgImg5);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,340,600);


(lib.bgImg6 = function() {
	this.initialize(img.bgImg6);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.bgImg7 = function() {
	this.initialize(img.bgImg7);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,340,600);


(lib.bgImg8 = function() {
	this.initialize(img.bgImg8);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.img2_1 = function() {
	this.initialize(img.img2_1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,155,43);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.urText = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AIXJOIAAgPIgsAAIAAAPIgKAAIAAgXIAGAAIAEgGIAFgRIAFgtIAoAAIAABEIAEAAIAAAXgAH6IYIAAAKIgFAPIgDAGIAgAAIAAg8IgUAAgADlJOIAAgPIgtAAIAAAPIgKAAIAAgXIAEAAIAFgGIADgIIAFgVIACghIAnAAIAABEIAHAAIAAAXgADHIYIgCAKIgGAVIAfAAIAAg8IgUAAgARMI/IAAhMIAuAAIAAAIIgjAAIAAAZIAbAAIAAAGIgbAAIAAAdIAlAAIAAAIgAQsI/IAAglIggAAIAAAlIgLAAIAAhMIALAAIAAAhIAgAAIAAghIALAAIAABMgAPRIcIgHAAIAAAjIgKAAIAAgjIgIAAIgZAjIgLgCIAbgnIgCAAIAAgCIgKgXIgCgCIgEgCIgCAAIgCgGIAMAAIAFAGIAKAVIAEADIAEADIAEAAIAAghIAKAAIAAAhIAFAAIAEgDIANgYIADgFQABgBAGAAIAGAAIgCAGIgCAAIgEACIgCACIgLAXIAAACIgCAAIAcAnIgLACgAN+I/IAAg2IgiAsIAAAKIgKAAIAAhMIAKAAIAAA2IAigsIAAgKIAKAAIAABMgAMPI/IAAhMIAhAAIAIADIAHAHIACAKIgEAIIgGAHIAKAIIACALIgCAKIgEAHIgIADIgLACgAMaI3IAOAAQAIAAAFgEIADgKIgBgHIgFgEIgEgCIgUAAgAMaIUIAOAAIAGgDIAEgCIADgDIAAgFIgDgKIgMgCIgMAAgALTI9IgLgIIgGgMIgCgRIACgPIAGgMIALgJIAMgDIAPADQAEAAAGAHIAHAMIACARIgCARIgHAMIgKAIIgPACgALWH7IgFAGIgFALIgCAMIACAMIAFALIAFAGIAJAFIAKgFIAHgGIAEgLIAAgYIgEgJIgHgIIgKgCgAJ/I/IAAhMIAhAAIAHADIAGAHIACAKIgCAIIgIAHIAKAIIAEALIgCAKIgGAHIgJADIgHACgAKKI3IAOAAIANgEIAEgKIgCgHIgFgEIgFgCIgTAAgAKKIUIAOAAIAIgFIAFgIQAAgGgFgEIgMgCIgKAAgAJgI/IAAg2IgkAsIAAAKIgKAAIAAhMIAKAAIAAA2IAkgsIAAgKIAKAAIAABMgAGzI/IAAg2IgiAsIAAAKIgKAAIAAhMIAKAAIAAA2IAigsIAAgKIAKAAIAABMgAFMI/IgCgCIAAgGIANAAIAEgEIACgEIAAgDIgGgCIgEgBIgCgCIgRgzIAKgBIANApIACAEIAAACIAEACIADAAIAQgxIAIABIgTA7IgDAIIgJAIgAEnI/IAAgfIgIACIgLAAIgOgCQgGgCAAgIIgCgHIAAgcIAKAAIAAAbIACADIAAAFIAIAEIAPAAIAEgCIACAAIAAglIAKAAIAABMgACXI/IAAhMIAKAAIAABMgABTI/IAAhMIAhAAIAIADIAFAHIACAKIgCAIIgJAHIALAIIADALIgCAKIgGAHIgIADIgIACgABdI3IAOAAIANgEIAEgKIgCgHIgEgEIgGgCIgTAAgABdIUIAOAAIAJgFIAEgDIAAgFQAAgGgEgEIgNgCIgKAAgAg/I/IgOgCIgKgIIgHgMIgCgRIACgPIAHgMIAKgJIARgDIAKACIAJADIgFAHIgOgEIgLACIgGAEIgFAKIgCAPQABATAEAGQAIAJAIAAIAPgFIAAgXIgPAAIAAgIIAZAAIAAAkIgFABIgHAEgAh9I/IgEgCIgCgCIgbg2IAAA6IgIAAIAAhMIAIAAIAhBAIACACIACAAIAAhCIAJAAIAABAIgFAKIgGACgAjII/IAAhMIAKAAIAABMgAkCI/IgHgCIgCgGIAAgEIAEgEIAig0IgkAAIAAgIIAzAAIAAAGIgqA6IAAACIABACIApAAIAAAIgAkdI/IgJgYIgdAAIgIAYIgJgCIAThAIAEgJIAIgDIAFACIAEAAIACADIAXBJgAkoIeIgLghIgCgCIAAgCIgDAEIgJAhIAZAAgAlrI/IgCg6IgPAdIgDAFIgJAAIgEgDIgCgCIAAgEIgMgZIgDA6IgKAAIAEhMIAKAAIATAnIAAACIAFAAIAAgCIASgnIALAAIADBMgAm8I/IgJgYIgcAAIgJAYIgJgCIAThAIAFgJIAIgDIAEACIAEAAIADADIAWBJgAnGIeIgLghIgCgCIAAgCIgEAEIgJAhIAaAAgApEI/IAAhMIAwAAIAAAIIglAAIAAAZIAbAAIAAAGIgbAAIAAAdIAlAAIAAAIgAp2I9IgKgIIgEgMIgCgRIACgPQAAgIAGgEIALgJIAOgDIAKACIAJADIgDAHIgQgEIgJACIgIAEIgEAKIgCAPQAAARAGAIQAFAJAMAAIAEgDIAEAAIAIgEIAFAHIgIADIgPACgAqmI/IgIgIIgZgyIAAA6IgJAAIAAhMIALAAIAhBAIAAACIADAAIAAhCIAIAAIAABAIgCAKIgGACgAsQI/IAAhMIAwAAIAAAIIgmAAIAAAZIAbAAIAAAGIgbAAIAAAdIAmAAIAAAIgAsvI/IAAhMIAKAAIAABMgAtXIkIgCgCIgEgCIgCgCIgIAAIAAAhIgLAAIAAhMIAgAAIAIADIAGAHIACAKIgCAIIgEAHIgEAEIgGACIAGAGIAQAbIgMACgAtnIWIAKAAQAJAAADgFQAEgEABgGIgDgGIgCgEIgGgCIgQAAgAuzI/IAAhMIAxAAIAAAIIgmAAIAAAZIAbAAIAAAGIgbAAIAAAdIAmAAIAAAIgAvxI/IAAhMIAfAAIAJADIAGAHIACAMIgCAIIgEAHIgJAGIgKACIgPAAIAAAfgAvpIYIANAAQAIAAAEgEIAEgLIgCgIIgCgEIgGgCIgTAAgAwdIgIAAgCIgCAAIgCACIgTAfIgIgCIAUglIgUgkIAKgDIARAeIACACIACAAIAAgCIATgeIAIADIgVAkIAYAlIgJACgAx0I/IAAhMIAuAAIAAAIIgkAAIAAAZIAbAAIAAAGIgbAAIAAAdIAlAAIAAAIgAgEIiIAAgIIAzAAIAAAIgAGeHsIgEgCIgEgEIgDgGIAHgCIACADIAIADIAHAAIADgGIAHACQAAAIgHAAIgKAEgAImiCIgNAGQgEAEgNAAQgMAAgKgGQgJgJAAgQIACgNIAJgKIAMgEIAhgDIAAgDQAAgNgEgEQgCgHgLAAIgcAHIgEgMIAOgFIAUgCIARACIALAIIAEANIAAA5IAJAKIgNAKgAIAimQgHAGABAJIAEAOIANAFIAOgFIAIgGIAAgbIgPAAgAHGiCIgPAIIgRACIgQgCIgLgIIgEgNIgCgNIAAg+IATAAIAAA+IAEARQAEAGALABIAMgDIAKgIIAAhLIARAAIAABOIAIAKIgMAKgAFZh8IgEgIIAEgLIAJgCIAIACIAEALIgEAIIgIAEgAEIh6IgNgGIAGgMIALAFIAQADIARgFQAGgCABgIIgDgGIgFgGIgHgDIgKgCIgTgIIgHgJIgBgKIABgMQABgDAGgFIAKgHIARgCIARACIAMAFIgEAMQgNgHgMAAIgPADQgGAEAAAGIACAGIAEAGIAkANIAIAIIACANQAAAOgIAHQgJAIgSAAgADaiCIgPAIIgRACIgQgCIgLgIIgDgNIgCgNIAAg+IASAAIAAA+QAAANAEAEQAEAGALABIAMgDIALgIIAAhLIAQAAIAABOIAJAKIgMAKgAA4h+IAdgsIgbgrIAOgFIAVAjIACACIACAAIAEgCIAVglIAMAEIgYAsIAdAuIgPAEIgXglIgCgDIgCAAIgEADIgZAngAgLh8QgKgEgEgHQgGgFAAgJIgCgVIACgTQAAgEAGgMIAOgLQAFgEANAAQANAAAEAEIANALIAGAQIACARIgGAGIg3AAQAAARAFAJQAMAHAJABIAOgDIAKgEIAHANIgNAEIgSACgAAaiyQAAgNgGgKQgCgHgNAAQgOAAgCAJQgFAGAAAPIAqAAIAAAAgAh9h8IgCgIIACgLIALgCIAIACIACALIgCAIIgIAEgAi4h4IgDgEIgFgGIgMg1IgKAsQAAACgHANQgEAEgJAAIgIAAIgGgEIgCgGIgThWIARgCIAQBRIACAFIADAAIACgFIAShRIAPAAIATBRIACAFIACAAIACgFIAThRIAOACIgTBNQABAJgHAGQgDAEgJAAgAlDh4IgFgEIgDgGIgNg1IgLAsQABAJgHAGQgEAEgIAAIgJAAIgDgEIgFgGIgThWIARgCIARBRIACAFIACAAIACgFIAThRIAOAAIATBRIACAFIADAAIACgFIAShRIAPACIgTBNQAAAJgGAGQgFAEgIAAgAnPh4IgEgEIgEgGIgMg1IgLAsQAAAJgGAGQgFAEgIAAIgIAAIgFgEIgDgGIgUhWIARgCIARBRIACAFIACAAIADgFIAShRIAPAAIATBRIADAFIACAAIAAgFIAThRIAPACIgTBNQAAAJgGAGQgEAEgIAAgAhNh8IAAh9IgNAAIAAgNIAeAAIAACKgAOylAIAAhQIgFgJIAJgFIAGAIIAGgGIALgCQAMAAAJAIQAGAHAAASIgCAPIgGALQgHAGgEAAIgNAEIgGgCIgGAAIAAAbgAPFmTIgJADIAAAtIAGAAIAGABQAJABAGgJIAEgTQABgOgFgFQgCgFgIgBgAAPlAIAAhQIgDgJIAKgFIAEAIIAIgGIALgCQAMAAAHAIQAGAHAAASIgCAPQAAAJgHACQgFAGgDAAIgOAEIgFgCIgGAAIAAAbgAAlmTIgJADIAAAtIAGAAIAHABQAKABACgJQAHgGgBgNIgDgTQgCgFgLgBgAnAlAIAAhQIgGgJIAKgFIAGAIIAGgGIALgCQAMAAAHAIQAIAHAAASIgCAPIgGALQgHAGgEAAIgNAEIgGgCIgGAAIAAAbgAmtmTIgJADIAAAtIAGAAIAGABQAJABAHgJIADgTIgDgTQgDgFgIgBgAyzlCIAAgZIgPgCQgIgEgCgEIgHgJIgCgPIACgMIAHgIIAKgIIAPgFIAAgZIAMAAIAAAZIAPAFIAJAIQAFAEAAAEIADAMIgDANIgDALIgLAIIgPACIAAAZgAynljQANAAACgHQAHgGgBgNQABgKgHgGQgCgHgNABgAzCmNQgGAGAAAKQAAANAGAGQAEAHALAAIAAgzQgNAEgCAFgAqTlNIAAgQIgnAAIAAAQIgLAAIAAgYIAGAAIAFgJIABgKIADgGIAAgJIACgKIAAgLIAmAAIAAA3IAIAAIAAAYgAqwlsIgEAHIAbAAIAAguIgQAAgAwllNIAAgQIgwAAIAAg/IAKAAIAAA3IAeAAIAAg3IAKAAIAAA3IAIAAIAAAYgASflgQgGgCAAgMIACgKIAGgGIATgFIAKAAIAAgEIgCgKQgEgFgGAAIgRAFIgEgIIAXgFIANACIAGAEIACAIIAAAoIAGAGIgIAHIgGgHIgTAJQgJAAgGgHgASol4IgCAKIACAJIAIACIAJgCIAFgFIAAgRIgKAAgAP4lgQgFgCAAgMIACgKIAGgGIATgFIAKAAIAAgEIgCgKQgFgFgFAAIgRAFIgFgIIAYgFIAMACIAGAEIACAIIAAAoIAHAGIgJAHIgGgHIgTAJQgIAAgHgHgAQBl4IgCAKIACAJIAIACIAIgCIAHgFIAAgRIgKAAgAK2lgQgHgCAAgMIACgKIAFgGIAUgFIAKAAIAAgEIgBgKIgLgFIgSAFIgDgIIAIgDIAPgCIAMACIAHAEIACAIIAAAoIAHAGIgJAHIgHgHIgSAJQgLAAgDgHgAK9l4QgDAEAAAGIADAJIAHACIAKgCIAGgFIAAgRIgKAAgAJDldQgDAAgFgGIgFgLIgCgPIACgMIAFgKIAKgJIAMgCIANACIAIAJIAEAKIACAMIgCAPIgEALIgIAGIgPAEgAJDmQIgCATIAAALIACAIIAGAHIAIABQAHABAGgJIACgTIgCgTIgNgGQgIABgGAFgAG1ldIgJgGIgDgLIgDgPIADgMQADgLACABIAJgJIANgCIAMACIAJAJIAGAKIAAAbIgGALQgHAGgCAAIgMAEgAG3mQIgEATIAAALIAEAIIAEAHIAJABQAKABACgJIAEgTIgEgTQgCgFgKgBQgJABgEAFgAgpldQgCAAgHgGIgEgLIgCgPIACgMIAEgKQACgFAIgEIANgCIANACIAIAJIAEAKIACAMIgCAPIgEALIgIAGIgPAEgAgpmQIgCATIAAALIACAIIAFAHIAJABQAGABAHgJIABgTIgBgTIgNgGQgJABgFAFgAimldQgFAAgEgGIgFgJIgCgMIgMAAIAAAbIgNAAIAAg/IANAAIAAAcIAMAAIACgNIAFgJIAJgGIAMgCIANACIAIAJIAGAKIAAAbIgGALQgHAGgBAAIgNAEQgJAAgDgEgAimmQIgFATIAFATIADAHIAJABQAKABADgJIADgTIgDgTIgFgDIgIgDQgJABgDAFgAkoldIgIgIQgFgFAAgIIgBgOIABgRIAFgNQgBgEAHgHQAAgCAKgDIAIgDIAFAAIAEgCIAEgGIAJACIgDAEIAAAFIgCACIgEABQAAACgGAAIgJADIgIAEIgEAEIgEAGIAAAIIAIgGIANgCIAKACIAJAGIADAJIAAAKIgBAPIgFALIgIAGIgOAEgAkimNIgEAEIgEACIAAATIACAIIAGAHIAIADQAHABAGgJIACgRIgCgQIgLgFIgFAAgAopldQgCAAgGgGIgEgLIgCgPIACgMIAEgKIAKgJIANgCIAMACIAHADIgCAIIgRgFQgIABgFAFQgDAFAAAOIAAALIADAIIAFAHIARAAIAIgCIAEAFIgJAFIgMACgA0ZldIgLgLQgGgGAAgIIgEgTIAEgTQAAgIAGgHQAFgHAIgDQAJgEAHAAIARAEIAKAKQAHAHAAAIIAEATIgEATQAAAIgHAGQgEAJgIACIgPAEgA0TmsIgIAIIgEAMIAAAdIAEANIAIAJIAMACIALgCIAJgJIADgNIAAgdIgDgMIgJgIIgLgCgAUeldIgBgGIABgHIAHgCIAGACIACAHIgCAGIgGACgAOIl4IgJAAIAAAbIgMAAIAAg/IAMAAIAAAcIAHAAIAEgFIANgXIAGgCIAEACIACAAIAAAGIgGAAIgLAWIgBACIAUAhIgKACgAM1lbIgFgCIACgIIADACIAIAAIAEgCIACgFIAFgEIAAgEIgHgCIgEgCIgFgFIgDgFIgRg1IAMgCIAPAyIACAFIACACIAFABIADAAIATg6IAKACIgbBQIgDAFIgPAFgAR+ldIAAgeIgbAAIAAAeIgMAAIAAg/IAMAAIAAAZIAbAAIAAgZIANAAIAAA/gAQ3ldIAAg2IgGAAIAAgJIATAAIAAA/gAKKldIAAg2IgWAAIAAgJIA3AAIAAAJIgVAAIAAA2gAIZldIAAgqIgdAiIAAAIIgMAAIAAg/IAMAAIAAAqIAdghIAAgJIAKAAIAAA/gAF2ldIAAhPIgZAAIAAgLIBBAAIAAALIgbAAIAABPgADoldIAAhaIANAAIAABagADFldIAAhaIANAAIAABagACkldIAAhPIgoAAIAABPIgMAAIAAhaIBAAAIAABagAhildIAAg2IgTAAIAAgJIA0AAIAAAJIgUAAIAAA2gAlRldIAAgqIgeAiIAAAIIgLAAIAAg/IALAAIAAAqIAeghIAAgJIAJAAIAAA/gAnsldIAAg2IgVAAIAAgJIA0AAIAAAJIgUAAIAAA2gApSldIAAgqIgeAiIAAAIIgMAAIAAg/IAMAAIAAAqIAeghIAAgJIALAAIAAA/gAryldIAAgqIgeAiIAAAIIgMAAIAAg/IAMAAIAAAqIAeghIAAgJIAKAAIAAA/gAs5ldIAAgqIgeAiIAAAIIgKAAIAAg/IAKAAIAAAqIAeghIAAgJIAKAAIAAA/gAuAldIAAgeIgdAAIAAAeIgLAAIAAg/IALAAIAAAZIAdAAIAAgZIAMAAIAAA/gAvHldIAAgqIgbAiIAAAIIgNAAIAAg/IANAAIAAAqIAbghIAAgJIAMAAIAAA/gAwPldIAAg2IgIAAIAAgJIAVAAIAAA/gAx0ldIAAg2IgJAAIAAgJIATAAIAAA/gATyluIANgNIAEgCIAAgDIgRgRIAHgFIASARIADAHIgDAGIgGAGIgMAIgATZluIANgNIAEgCIAAgDIgCgFIgPgMIAJgFIAQARIADAHIgDAGIgFAGIgNAIgAFClyIgGgGIgCgGIACgHIAQgRIAJAFIgQARIAAADIADACIANANIgGAEgAEplyIgGgGIgCgGIACgHIARgRIAIAFIgPAMIgBAFIAAADIADACIANANIgGAEgAL0l+IAAgLIAmAAIAAALgAjumZIAEgQIgEgCIgBgDQAAgHABAAIAHgEQAGAAAAAEIACAHIAAAFIgCAFIgEAGIgCAGgAIEmmIgKgIIgDgHIAHgCIAEAGIAJADIAHgDIAHgGIAGACIgGAKIgOAFgAsImmIgGgFIgEgDIgCgHIAGgCIAEAGIAJADIAIgDIAHgGIAFACQAAAFgFAFIgPAFgAvammIgHgFIgDgDIgFgHIAIgCIAFAGIAIADIAIgDIAFgGIAIACIgIAKIgNAFgAwPmpIgBgFIABgHIAFgCIAGACIACAHIgCAFIgGADgAx3mpIgCgFIACgHIAGgCIAHACIACAHIgCAFIgHADgAREmrIgCgGIACgEIAGgEIAGAEIACAEIgCAGIgGACgAQpmrIgCgGIACgEIADgEQAHAAAAAEIACAEIgCAGQAAACgHAAgAMdnWIAAhQIgDgKIAKgEIAEAJIAIgHIALgCQANAAAFAJQAHAFAAATIgCAPIgFAKQgGAHgEAAIgOAEIgFgDIgGAAIAAAcgAMyopIgIADIAAAsIAGAAIAHACQAKABACgJQAGgGABgNIgFgTQgCgFgLAAgAArnWIAAgcIgPgBIgKgJIgGgIIgCgPIACgMIAGgJIAKgIIAPgEIAAgZIAKAAIAAAZIAPAEIAKAIIAHAJIABAMIgBANQAAAIgHACIgKAJIgPABIAAAcgAA1n6QAKAAAHgGQAEgEAAgPQAAgMgEgEQgHgHgKABgAAaojIgEAQIAEATQAGAGALAAIAAgxgAzdnhIAAgSIg0AAIAAASIgMAAIAAgbIAGAAIAJgPIAHhCIAxAAIAABRIAGAAIAAAbgA0AohIAAAMIgCAKIgJAPIAoAAIAAhHIgZAAgAI+niIAAgRIgnAAIAAARIgKAAIAAgaIAFAAIAFgIIACgKIACgHIAAgIIACgLIAAgKIAmAAIAAA2IAIAAIAAAagAIhoCIgEAGIAcAAIAAgtIgRAAgAC3niIAAgRIgxAAIAAg/IANAAIAAA2IAbAAIAAg2IAMAAIAAA2IAJAAIAAAagAUgnzQgCAAAAgHIACgGIAHgCIAGACIACAGIgCAHIgGAEgATqnyIgIgDIAEgJIAJAEIAKAAIAKgCIAFgGIgFgJIgZgIIgEgGIgCgGIACgJIAEgGIAIgEIALgCIALACIAIAEIgCAGIgRgDIgLACIgDAIIABAEIACACIAHACIAEACIAOAEIAFAGIACAJQAAAIgHAHQgFAGgNAAgASsnyIgGgGIgFgQIAAgqIANAAIAAAqIACAKQACAFAIgBIAJAAIAGgGIAAgyIALAAIAAA0IAFAGIgHAGIgHgGIgIAGIgKADgAQznzQgFAAgDgHQgCAAgFgKIAAgbIAHgKIAIgHIAMgEIANAEIAGAHIAFAKIABAMIgDAFIgnAAIAFAQQAEAFALgBIAIAAIAIgCIAFAHIgJADIgMADgARMoXQAAgMgEgDQgCgFgJAAQgGAAgEAFIgFAPIAeAAIAAAAgALpnzIgKgHIgEgKIgCgPIACgMIAGgKIAIgJIANgCIALACIAIAJIAEAKIACAMIgEAFIglAAIADAQIAPAEIAJAAIAIgCIAEAHIgLADIgKADgAMCoXQAAgMgDgFQgFgDgGAAQgGAAgFAFIgDAPIAcAAIAAAAgAgunzIgIgHIgEgKIgCgPIACgMQAEgKACAAIAJgJIAMgCIAMACIAIAJIAHAKIAAAbIgHAKQgGAHgCAAIgMAEgAgromIgFATIAAALIAIAOIAJACQAKABACgJIAFgTIgFgTQgCgFgKAAQgIAAgEAFgAjKn1IgFgPIADgKIAEgHIASgEIANAAIAAgEIgEgLIgJgDIgSADIgCgIIAIgCIAOgCIALACQAHAAgBAEIAFAIIAAAoIAGAJIgIADIgGgGIgJAFQgFAEgHAAQgJAAgGgGgAjAoOQgEADAAAHIACAIIAJACIAKgCIAGgEIAAgQIgLAAgAlLnzQgDAAgGgHIgGgKIAAgPIACgMIAEgKIAJgJIAMgCIAPACIAIAJIAEAKIACAMIgCAPIgEAKIgIAHIgPAEgAlLomIgFATIAFATIAGAGIAGACQAKABACgJQAFgEAAgPQAAgOgFgFQgCgFgKAAQgIAAgEAFgAnXn1IgEgPIACgKIAEgHIASgEIANAAIAAgEIgEgLIgJgDIgSADIgCgIIAIgCIAPgCIAKACQAHAAgBAEIAFAIIAAAoIAGAJIgIADIgHgGIgIAFQgEAEgIAAQgJAAgGgGgAnNoOQgEADAAAHIACAIIAJACIAKgCIAGgEIAAgQIgKAAgAoHnzIgIgHIgFgKIgCgPIACgMQAFgKABAAIAJgJIAPgCIATAEIgFAIIgGgBIgLgCQgIAAgEAFIgEATIAAALIAEAIIAGAGIAPAAIAIgCIAFAHIgJADIgNADgAq6nzQgCAAgHgHQgCAAgEgKIAAgbIAGgKIAJgJIAMgCIANACIAGAJIAEAKIACAMIgEAFIgmAAIAFAQIAOAEIAIAAIAJgCIAEAHIgIADIgNADgAqhoXQgBgMgEgFQgDgDgHAAQgGAAgEAFIgFAPIAeAAIAAAAgAxIn1QgFgDAAgMIAAgKIAHgHIASgEIAKAAIAAgEIgBgLIgJgDIgSADIgCgIIAHgCIAPgCIAKACQAHAAAAAEIAEAIIAAAoIAFAJIgHADIgGgGIgIAFQgJAEgEAAQgJAAgFgGgAw+oOQgEADgBAHIACAIIAJACIALgCIADgEIAAgQIgIAAgAy1nzIgIgHIgFgKIgBgPIABgMIAFgKIAIgJIANgCIAMACIAIAJIAFAKIAAAMIgFAFIgjAAIAEAQIAMAEIALAAIAIgCIACAHIgIADIgNADgAyaoXIgEgRIgKgDQgHAAgEAFIgEAPIAdAAgAR+oLIgCgCIgEACIgPAZIgKgBIAUggIgSgdIAKgCIAPAZIAEAAIAPgZIAIACIgRAdIATAgIgKABgAKUn1IAJgLIABgIIAEgqIAoAAIAAA/IgNAAIAAg2IgQAAIgEAhIgEAMIgIAKgAHZoLIgCgCIgDAAIgCACIgRAZIgIgBIATggIgRgdIAJgEIAOAZIACACIADgCIAOgZIALAEIgUAdIAWAgIgLABgAh3oLIAAgCIgCAAIgCACIgQAZIgJgBIATggIgTgdIAKgEIAPAZIACACIACgCIAPgZIAIAEIgQAdIAUAgIgKABgAmhn1IAIgLIACgIIAFgqIAnAAIAAA/IgMAAIAAg2IgRAAIgEAhIgEAMQAAAFgHAFgAwSn1IAIgLIACgIIAEgqIAoAAIAAA/IgNAAIAAg2IgRAAIgDAhIgFAMQAAAFgGAFgAPinzIAAhaIAMAAIAABRIAsAAIAAAJgAOGnzIAAg/IAbAAIAOACIAHANIgCAIIgFAGIAHAHIACAIQAAAMgEACQgFAFgMAAgAORn8IASAAIAHgCIADgIIgDgHIgJgDIgQAAgAORoZIAQAAIAGgCIADgGIgDgHIgIgBIgOAAgANmnzIAAg2IgIAAIAAgJIATAAIAAA/gAJ/nzIAAgqIgdAhIAAAJIgMAAIAAg/IAMAAIAAAqIAdghIAAgJIALAAIAAA/gAGinzIAAgqIgbAhIAAAJIgMAAIAAg/IAMAAIAAAqIAbghIAAgJIAMAAIAAA/gAFdnzIAAgbIgdAAIAAAbIgMAAIAAg/IAMAAIAAAZIAdAAIAAgZIALAAIAAA/gAEWnzIAAgqIgdAhIAAAJIgKAAIAAg/IAKAAIAAAqIAdghIAAgJIALAAIAAA/gADQnzIAAg2IgJAAIAAgJIATAAIAAA/gABnnzIAAg2IgGAAIAAgJIATAAIAAA/gAjqnzIAAgbIgdAAIAAAbIgKAAIAAg/IAKAAIAAAZIAdAAIAAgZIANAAIAAA/gApunzIAAg/IAcAAIAQACIAFANIgDAIIgEAGIAHAHIACAIQAAAMgFACQgEAFgMAAgApjn8IATAAIAGgCIAFgIIgFgHIgIgDIgRAAgApjoZIARAAIAGgCIACgGIgCgHIgJgBIgOAAgAslnzIAAg/IANAAIAAA2IASAAIAAg2IANAAIAAA2IATAAIAAg2IAMAAIAAA/gAtCnzIAAg2IgIAAIAAgJIATAAIAAA/gAtknzIAAgbIgbAAIAAAbIgMAAIAAg/IAMAAIAAAZIAbAAIAAgZIANAAIAAA/gAvJnzIAAg/IAKAAIAAAZIARAAIAKACIAHAEIADAGIAAAHIgDAOQgFAFgKAAgAu/n8IAOAAIAJgCIAEgIIgEgIIgJgCIgOAAgAxynzIAAg2IgVAAIAAgJIA0AAIAAAJIgVAAIAAA2gANko+IgBgGIABgHIAHgCIAGACIACAHIgCAGIgGACgAEBo8IgDgFIgHgDIgCgHIAJgCIADAHIAJACIAIgCIAEgHIAGACQABAIgHACIgMAFgADNo+IgCgGIACgHIAGgCIAHACIACAHIgCAGIgHACgABno+IgCgGIACgHIAHgCIADACIADAHIgDAGIgDACgAtEo+IgCgGIACgHIAGgCIAFACIACAHIgCAGIgFACg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.urText, new cjs.Rectangle(-132.7,-59,265.4,118), null);


(lib.t4_3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AMOCGQg2g2gBhPQABhEArg2QA4hCBaAAQA1AAApAbIAABAQgugng0AAQg2AAgoAnQglAqAAA3QAAA6AlAoQAqAlA2AAQAgAAAQgIIAXgMIAZgTIAABAQguAbg0ABQhNgBg2g2gACMChQgagbgLg0IA4gMQAFAfAHAMQAQAXAiAAQAZAAASgRQAQgQAAgbIgCgTIgLgRIgQgMQgLgKgMgCIgjgPQhKgjABg6QgBgoAggcQAhgbAsAAQA+AAAkA8IgsAbQgNgVgMgGQgIgJgVABQgZAAgMAMQgPAMAAAVQAAAbAlAPIAmAOQAqATAWAYQATAZAAAmQAAAzghAgQggAhgxABQgzgBgdgbgAjECSQgkgnABg2IAAjqIA2AAIAADbQAAAuAOAVQAZAfAoAAQAoAAAZgfQAOgQAAgzIAAjbIA1AAIAADqQAAA6giAjQgqAqg4ABQg4gBgqgqgAIkC2IAAlrIA3AAIAAE3IBqAAIAAA0gAlWC2IhPiLIhTCLIg8AAIBwi9IhkiuIA/AAIBEB8IBJh8IA/AAIhpCuIBsC9gAsdC2IAAlrIDFAAIAAAzIiPAAIAABYICLAAIAAAzIiLAAIAAB5ICPAAIAAA0gAvyC2IAAlrIA2AAIAAE3IBrAAIAAA0g");
	this.shape.setTransform(-1.4,0.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Слой_3
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AklA/IAAh9IJLAAIAAB9g");
	this.shape_1.setTransform(0,0,4.165,4.165);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.t4_3, new cjs.Rectangle(-122.5,-26,245.1,52.1), null);


(lib.t4_2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AFBCUIAAgwIiKAAIAAisIARAAIAACbIBeAAIAAibIASAAIAACbIAZAAIAABBgAj9giIgbCGIgTAAIAqi4IBECdIBFidIAqC4IgRAAIgdiGIhBCQgAgWBPQgbgbAAglQAAgnAbgZQAYgbAoAAQAnAAAZAbQAbAZAAAnQAAAlgbAbQgZAZgnAAQgoAAgYgZgAgJgnQgVAVAAAhQAAAfAVAXQATAVAgAAQAfAAAVgVQAUgXAAgfQAAghgUgVQgVgUgfAAQggAAgTAUgAnYBPQgXgZAAgnQAAgrAbgZQAXgXAiAAQAjAAAZAZQAXAbAAAnIiWAAQAAAhAVAVQAVAVAdAAQAnAAAVgoIAPAIQgZAug0AAQgoAAgXgZgAlbAAQgGg7g6AAQg7AAgGA7ICBAAIAAAAgAHEBkIAAisIARAAIAACsgAF1BkIAAisIAQAAIAACsgAHQiCQAAgRARAAQAPAAAAARQAAAOgPAAQgRAAAAgOgAGpiCQAAgRAOAAQAPAAAAARQAAAOgPAAQgOAAAAgOgAFuiCQAAgRAPAAQARAAAAARQAAAOgRAAQgPAAAAgOg");
	this.shape.setTransform(1.9,-1.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Слой_3
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AisA3IAAhtIFZAAIAABtg");
	this.shape_1.setTransform(0,0,4.165,4.165);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.t4_2, new cjs.Rectangle(-72,-23,144.1,46.1), null);


(lib.t4_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgfC/IAAkOIATAAIAAAdQAXghAqgBQAlAAAaAbQAXAaAAAkQAAAngXAZQgaAbglAAQgwABgRgkIAACCgAAHgyQgVAVgBAgQABAiARAWQATAXAfAAQAgAAASgXQAQgVAAghQAAghgUgUQgRgTgdAAQgbAAgTARgAGfgqIgbCHIgTAAIAqi5IBFCeIBGieIApC5IgRAAIgdiHIhBCRgAC8hPIARAAIAACKIB9iVIAAC3IgTAAIAAiJIh7CTgAleBHQgZgYAAgoQAAgmAZgaQAZgbAnAAQAkABAZAUIAAAXQgXgbgmAAQgfAAgSAVQgVAVAAAgQAAAjAWAWQAWASAaAAQAkAAAbgfIAAAXQgXAXgogBQgnAAgZgZgAouBHQgXgYAAgoQAAgqAbgZQAXgYAjAAQAkAAAWAaQAXAbAAAmIiTAAQgBAhAWAVQASAVAdAAQAqAAATgoIAPAJQgZAtg1AAQgoAAgWgZgAmvgGQgDgbgSgRQgSgRgaAAQg4AAgKA9ICDAAIAAAAgAM6BdIAAisIARAAIAACsgALqBdIAAhRIhiAAIAABRIgQAAIAAisIAQAAIAABLIBiAAIAAhLIARAAIAACsgAiOBdIAAieIg8AAIAAgOICKAAIAAAOIg9AAIAACegAqSBdIAAiRIirAAIAACRIgSAAIAAkbIASAAIAAB3ICrAAIAAh3IASAAIAAEbgAMyiKQgBgQARgBQAOABAAAQQAAAPgOAAQgRAAABgPg");
	this.shape.setTransform(1.5,3.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Слой_3
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AkFA3IAAhtIILAAIAABtg");
	this.shape_1.setTransform(0,0,4.165,4.165);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.t4_1, new cjs.Rectangle(-109,-23,218.1,46), null);


(lib.t3_2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("Aj4DEIAAkOIARAAIAAAdQAZghAsAAQAlAAAXAbQAXAZAAAlQAAAngXAbQgXAbgoAAQglAAgdglIAACBgAjSgrQgVATAAAjQAAAhAQAVQATAXAfAAQAgAAASgXQATgVAAghQAAgjgVgTQgSgSgeAAQgbAAgSASgAMjCSIAAgwIiIAAIAAisIARAAIAACdIBeAAIAAidIAQAAIAACdIAZAAIAAA/gAksCSIAAgwIiSAAIAAAwIgQAAIAAg/QAZgCAGgXQAIgOAAgfIAAhXIBxAAIAACdIAbAAIAAA/gAmWARQAAAwgXASIBmAAIAAiMIhPAAgAsoCSIAAgwIiUAAIAAAwIgOAAIAAg/QAZgEAGgVQAGgKAAgjIAAhXIBzAAIAACdIAbAAIAAA/gAuSARQAAAwgXASIBmAAIAAiMIhPAAgAHRhKIARAAIAACLIB7iVIAAC2IgRAAIAAiIIh7CSgABEBRQgdgbAAhBQAAhpA2gjQASgKAwgLQAigIAGgPIAVAAQgLAbg0APQglAEgXATQgmAdgEBFIACAAQARguA6AAQAoAAAZAZQAXAZAAApQAAApgbAZQgZAZgoAAQghAAgbgXgABMgmQgTAWAAAdQAAAZARAZQAVAZAhAAQAmAAAUgZQARgVAAgdQAAgdgTgWQgSgXgiAAQghAAgXAXgArlBNQgbgbAAglQAAgnAbgZQAZgbAnAAQAoAAAZAbQAbAZAAAnQAAAlgbAbQgZAbgoAAQgnAAgZgbgArZgpQgVAVAAAhQAAAfAVAXQAVAVAfAAQAfAAAVgVQAVgXAAgfQAAghgVgVQgVgUgfAAQgfAAgVAUgANXBiIAAisIATAAIAABJIAnAAQAhAAANAOQAMAQAAATQAAAVgQAQQgNANgdAAgANqBTIAnAAQARAAAKgIQANgIAAgTQAAgRgNgKQgIgIgTAAIgnAAgAGCBiIAAhRIhiAAIAABRIgQAAIAAisIAQAAIAABMIBiAAIAAhMIARAAIAACsgAgbBiIAAisIARAAIAACsgAgjiEQAAgRAQAAQAPAAAAARQAAAQgPAAQgQAAAAgQg");
	this.shape.setTransform(-2.5,-0.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Слой_3
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AkeA3IAAhtII9AAIAABtg");
	this.shape_1.setTransform(0,0,4.165,4.165);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.t3_2, new cjs.Rectangle(-119.4,-23,238.9,46), null);


(lib.t3_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AE5B4QgagZAAgqQAAgqAYgYQAWgYAmAAQAtAAAXAjIAAgfIARAAIAACuIgRAAIAAggQgUAkgwAAQgkAAgWgZgAFFgCQgVAUAAAhQAAAfATAXQATAXAfAAQAfAAATgXQAQgVAAghQAAgjgWgSQgTgTgZAAQgbAAgVATgAgeB4QgZgZAAgqQAAgqAXgYQAXgYAkAAQAuAAAXAjIAAgfIARAAIAACuIgRAAIAAggQgVAkgwAAQggAAgZgZgAgSgCQgUAUAAAhQAAAfASAXQATAXAfAAQAfAAASgXQARgVAAghQAAgjgXgSQgTgTgYAAQgbAAgVATgACvCNIAAiuIBeAAIAAAQIhNAAIAACegAjdCNIAAiuIA5AAQAYAAAMAKQARARAAAPQAAAbgVAJIAXAKQAPAPAAAVQAAAbgTAKQgPANgbAAgAjNB8IAyAAQAVAAAIgIQANgJAAgQQAAgPgLgKQgOgJgRAAIgyAAgAjNArIApAAQANAAALgJQAMgIAAgPQAAgNgMgIQgJgHgPAAIgpAAgAl+CNIAmhQIhvjNIAVAAIBkC5IBTi5IATAAIiBEdg");
	this.shape.setTransform(-2.9,0.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Слой_3
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AiiA3IAAhtIFFAAIAABtg");
	this.shape_1.setTransform(0,0,4.165,4.165);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.t3_1, new cjs.Rectangle(-67.8,-23,135.8,46), null);


(lib.t2_2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("An4CKIAAkPIARAAIAAAeQAZgiArgBQAmAAAXAbQAXAZAAAmQAAAogXAaQgXAbgoAAQgvAAgTgkIAACBgAnThnQgWAVAAAiQAAAhATAUQASAXAfAAQAgAAATgXQASgUABghQgBgigUgVQgUgSgdAAQgaAAgUASgAC0ASQgXgZABgnQAAgsAbgZQAWgWAigBQAjAAAZAZQAXAbAAAqIiUAAQAAAfAVAUQATAVAdAAQAnAAAVgmIAPAHQgbAwgyAAQgoAAgXgbgAExg9QgGg8g6AAQgZAAgTASQgRASgEAYICBAAIAAAAgAkOAUQgagZAAgpQAAgqAYgZQAWgZAoAAQArABAXAiIAAgeIARAAIAACrIgRAAIAAgdQgXAkgrAAQgkAAgYgZgAkAhnQgVAVAAAiQAAAfARAWQATAXAfAAQAfAAATgXQASgWAAgfQAAgjgWgWQgVgQgZAAQgbAAgTASgAI3AmIAAirIARAAIAABIIAqAAQAdAAAOARQANAMAAAWQAAAXgPANQgMAMgdAAgAJIAXIAqAAQAQAAALgHQANgNAAgNQAAgQgNgLQgNgHgQAAIgoAAgAHoAmIAAhOIhiAAIAABOIgQAAIAAirIAQAAIAABMIBiAAIAAhMIATAAIAACrgAB0AmIhLhOIgIAKIAABEIgTAAIAAhEIgIgKIhLBOIgWAAIBXhYIhRhTIAWAAIBNBTIAAhTIATAAIAABTIBMhTIAYAAIhSBTIBXBYgAqpAmIAAirIA5AAQAYAAANAKQAOALAAAWQAAAXgSANQAKAAALAKQAQAMAAAYQABAVgUAPQgMAKgdAAgAqYAXIAyAAQATAAAKgHQAMgJAAgPQAAgPgMgKQgKgJgTAAIgyAAgAqYg7IAoAAQAQAAAIgGQALgKAAgNQAAgMgLgLQgIgGgQAAIgoAAg");
	this.shape.setTransform(-2.6,4.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Слой_3
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AjYA3IAAhtIGxAAIAABtg");
	this.shape_1.setTransform(0,0,4.165,4.165);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.t2_2, new cjs.Rectangle(-90.4,-23,180.8,46), null);


(lib.t2_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AEaB4QgZgZAAgqQAAgqAXgYQAXgZAlAAQAuAAAXAkIAAgfIARAAIAACrIgRAAIAAgdQgXAkguAAQgjAAgXgZgAEmgCQgVAUABAhQgBAfAUAXQASAXAfAAQAfAAAUgXQAQgXAAgfQAAgjgXgUQgTgRgZAAQgdAAgTATgAg9B4QgYgZAAgqQAAgqAWgYQAYgZAlAAQAtAAAXAkIAAgfIAQAAIAACrIgQAAIAAgdQgXAkgtAAQghAAgagZgAgwgCQgVAUAAAhQAAAfATAXQASAXAgAAQAeAAATgXQAQgXABgfQAAgjgXgUQgTgRgYAAQgeAAgSATgACQCKIAAirIBfAAIAAAQIhOAAIAACbgAh7CKIh9iFIgEAGIAAB/IgTAAIAAh/IgGgGIh9CFIgXAAICHiQIh+iKIAZAAIB4CFIAAiFIATAAIAACFIB2iFIAZAAIh9CKICICQg");
	this.shape.setTransform(-2,1.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Слой_3
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AibA3IAAhtIE3AAIAABtg");
	this.shape_1.setTransform(0,0,4.165,4.165);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.t2_1, new cjs.Rectangle(-65,-23,130,46), null);


(lib.t1_2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("ACKChIAAj7IAQAAIAAAdQAXgiAoAAQAjAAAXAZQAVAXAAAjQAAAlgVAZQgXAZgjAAQguAAgRgiIAAB4gACtg9QgVASAAAfQAAAfARAUQAQAWAdAAQAeAAATgWQAQgUAAgfQAAgfgTgSQgTgRgYAAQgcAAgQARgAhzBzIAAgsIiIAAIAAAsIgQAAIAAg9QASAAAMgUQAHgPAAgcIAAhRIBqAAIAACQIAXAAIAAA9gAjYgDQABAqgUAPIBfAAIAAiCIhMAAgAIkA/QgPgPgEgJIAPgKQAGAMALAJQAMALAQAAQAWAAAKgLQANgJAAgSQAAgOgLgKQgIgGgWAAIgQAAIAAgPIAMAAQAPAAAJgGQAKgJAAgMQAAgQgIgFQgJgIgRAAQgZAAgMAXIgNgLQARgdAhAAQAYAAAMANQAPAKAAAVQgBAXgSALIATAKQAKAJAAAVQAAAbgTANQgPAMgbAAQgXAAgSgMgAFkAyQgZgZAAgiQAAgkAZgZQAZgZAkAAQAjAAAZAZQAXAZAAAkQAAAigXAZQgZAZgjAAQgkAAgZgZgAFug8QgSAWAAAdQAAAcASAUQAWAWAdAAQAdAAASgWQAUgUgBgcQABgdgUgWQgSgSgdAAQgdAAgWASgAg1AyQgZgZAAgiQAAgkAZgZQAZgZAiAAQAkAAAZAZQAXAZgBAkQABAigXAZQgZAZgkAAQgiAAgZgZgAgqg8QgUAWABAdQgBAcAUAUQAUAWAcAAQAeAAASgWQAVgUAAgcQAAgdgVgWQgSgSgeAAQgcAAgUASgAoMA0QgZgZAAgkQAAgmAVgXQAXgZAjAAQAqAAAVAiIAAgdIAQAAIAAChIgQAAIAAgeQgXAigoAAQghAAgVgXgAoCg9QgSASAAAfQAAAdAQAVQATAXAdAAQAeAAAQgXQARgVAAgdQAAghgVgSQgTgPgZAAQgYAAgUARgAK6BHIAAihIAPAAIAAChgApkBHIAAhKIhZAAIAABKIgQAAIAAihIAQAAIAABGIBZAAIAAhGIARAAIAAChgAKziRQAAgPAPAAQAMAAAAAPQAAAPgMAAQgPAAAAgPg");
	this.shape.setTransform(3.2,0.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Слой_3
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AjiA3IAAhtIHFAAIAABtg");
	this.shape_1.setTransform(0,0,4.166,4.167);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1_2, new cjs.Rectangle(-94.5,-23,189.1,46.1), null);


(lib.t1_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AmoCzIAAj7IARAAIAAAbQAXgfAnAAQAkAAAWAZQAVAXAAAiQAAAmgVAXQgWAZgkAAQguAAgQgiIAAB5gAmFgtQgUATAAAgQAAAgAQASQARAVAdAAQAfAAARgVQARgSAAggQAAgegTgTQgRgSgbAAQgbAAgRAQgABgCDIAAgrIiHAAIAAArIgOAAIAAg6QAVAAAIgVQAGgMAAggIAAhQIBpAAIAACRIAXAAIAAA6gAgBANQAAArgVARIBdAAIAAiCIhIAAgAMzBFQgXgZAAgkQAAgkAXgXQAWgZAmAAQAfAAAZAVIAAAVQgXgbghAAQgdAAgTAUQgTAVAAAcQAAAgAVAUQAVARAZAAQAhAAAZgdIAAAXQgZAVghAAQgmAAgWgXgAF1BFQgVgXAAgmQAAgmAXgZQAXgVAfAAQAhAAAVAZQAXAXAAAkIiJAAQAAAgASASQATATAbAAQAoAAAQglIANAIQgZAsguAAQglAAgVgXgAHpgFQgIg4g0AAQgXAAgRAQQgQARgEAXIB4AAIAAAAgAjRBFQgVgXAAgmQAAgmAZgZQAXgVAfAAQAhAAAVAZQAVAXAAAkIiKAAQAAAgAVASQATATAZAAQAoAAAQglIANAIQgTAsg0AAQgmAAgUgXgAhdgFQgCgXgRgRQgQgQgXAAQg0AAgJA4IB3AAIAAAAgApdBFQgVgXAAgmQAAgmAZgZQAXgVAfAAQAhAAAVAZQAXAXAAAkIiLAAQAAAgAUASQATATAZAAQAoAAAQglIAPAIQgZAsguAAQglAAgXgXgAnmgFQgDgXgSgRQgRgQgXAAQg0AAgIA4IB5AAIAAAAgAsKBFQgXgZAAgkQAAgkAXgXQAZgZAlAAQAgAAAXAVIAAAVQgXgbggAAQgdAAgVAUQgSAVAAAcQAAAgAUAUQAVARAZAAQAiAAAZgdIAAAXQgZAVgiAAQgjAAgZgXgAvWBFQgXgZAAgkQAAgiAXgZQAZgZAjAAQAkAAAZAZQAZAZAAAiQAAAkgZAZQgZAXgkAAQgjAAgZgXgAvKgpQgSAVAAAcQAAAeASAUQATATAdAAQAdAAAVgTQATgUAAgeQAAgcgTgVQgVgUgdAAQgbAAgVAUgAzGAmIARgJQAVAwA0AAQAbAAATgOQAXgRAAghQAAg6hHAAIgXAAIAAgQIAXAAQAVAAAOgNQARgPAAgZQAAgWgNgNQgOgPgXAAQgkAAgXAiIgMgLQAXglAyAAQAdAAATARQATASAAAdQAAAogkATQA2AMAAA4QAAAngfAXQgVARgjAAQhBAAgZg2gARaBYIAAigIARAAIAABDIAmAAQAbAAAOANQANANAAAVQAAASgPAPQgMANgbAAgARrBJIAmAAQASAAAHgIQAMgJAAgOQAAgRgMgIQgJgJgQAAIgmAAgAP0BYIAAiRIg4AAIAAgPIB/AAIAAAPIg4AAIAACRgALdBYIAAigIAPAAIAACggAKUBYIAAhLIhbAAIAABLIgPAAIAAigIAPAAIAABHIBbAAIAAhHIAPAAIAACggAE4BYIhEhJIgJAIIAABBIgQAAIAAhBIgJgIIhEBJIgXAAIBRhUIhLhMIAVAAIBJBMIAAhMIAQAAIAABMIBJhMIAVAAIhNBMIBTBUgALXh+QAAgPAPAAQAMAAAAAPQAAAPgMAAQgPAAAAgPg");
	this.shape.setTransform(3,2.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Слой_3
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AlWA3IAAhtIKtAAIAABtg");
	this.shape_1.setTransform(0,0,4.166,4.167);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1_1, new cjs.Rectangle(-143,-23,286,46.1), null);


(lib.logoW = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ag8BGQgegcAAgqQAAgqAdgbQAbgbAnAAQAogBAdAaIgPATQgYgTgfAAQgbAAgUAUQgUAUAAAgQAAAcAUAVQAVAWAbAAQAVAAAPgLQAPgJAFgSIg5AAIAAgYIBXAAQAAAlgaAaQgZAYgjAAQgkAAgdgbg");
	this.shape.setTransform(57.6,11.6,0.253,0.253);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AA1BeIhiiHIgDgGIABAHIAACGIgaAAIAAi8IAWAAIBgCGIAEAGIgBgHIAAiFIAaAAIAAC8g");
	this.shape_1.setTransform(51.9,11.6,0.253,0.253);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgMBeIAAi8IAZAAIAAC8g");
	this.shape_2.setTransform(47.4,11.6,0.253,0.253);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhJBeIBmiiIgGAAIhQAAIAAgaICDAAIhjCgIgDADIAGAAIBdAAIAAAZg");
	this.shape_3.setTransform(43.4,11.6,0.253,0.253);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AA1BeIgYg9Ig6AAIgYA9IgbAAIBIi8IAQAAIBJC8gAgUAJIAoAAIgTgzIgBgGg");
	this.shape_4.setTransform(38.4,11.6,0.253,0.253);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("ABDBeIAAiJIAAgHIgCADIg8BPIgJAAIg8hMIgCgFIAAAIIAACHIgaAAIAAi8IAWAAIBGBdIBGhdIAXAAIAAC8g");
	this.shape_5.setTransform(32.5,11.6,0.253,0.253);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AA0BeIgWg9Ig8AAIgXA9IgbAAIBIi8IAQAAIBJC8gAgVAJIApAAIgUgzIAAgGg");
	this.shape_6.setTransform(26.6,11.6,0.253,0.253);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("Ag2BeIAAi8IBoAAIAAAZIhOAAIAAA8IBMAAIAAAXIhMAAIAAA4IBTAAIAAAYg");
	this.shape_7.setTransform(19.3,11.6,0.253,0.253);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("Ag2BIQgcgdAAgrQgBgpAbgbQAagdAoABQAtgBAZAeIgTARQgUgVgfAAQgbAAgTAUQgUAUAAAfQAAAhAWAVQAUASAXAAQAiAAAWgaIASAQQgLAQgTAJQgUAKgYAAQgkAAgbgZg");
	this.shape_8.setTransform(14.1,11.6,0.253,0.253);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AA2BeIhmiNIABAHIAACGIgaAAIAAi8IAWAAIBkCMIAAgHIAAiFIAZAAIAAC8g");
	this.shape_9.setTransform(8.4,11.6,0.253,0.253);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ag2BeIAAi8IBoAAIAAAZIhOAAIAAA8IBNAAIAAAXIhNAAIAAA4IBTAAIAAAYg");
	this.shape_10.setTransform(3,11.6,0.253,0.253);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgMBeIAAi8IAZAAIAAC8g");
	this.shape_11.setTransform(-1,11.6,0.253,0.253);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAjBeIhMhYIAABYIgZAAIAAi8IA8AAQAZAAARARQAQAQAAAXQAAAWgRAQQgPAPgVAAIBFBPgAgpgEIAeAAQARAAAKgKQAJgJAAgQQAAgLgJgJQgKgKgQAAIgfAAg");
	this.shape_12.setTransform(-4.9,11.6,0.253,0.253);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("Ag2BeIAAi8IBoAAIAAAZIhOAAIAAA8IBNAAIAAAXIhNAAIAAA4IBTAAIAAAYg");
	this.shape_13.setTransform(-10.1,11.6,0.253,0.253);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("Ag6BeIAAi8IA4AAQAcABARAQQAQAQAAAaQAAAXgRAQQgRAQgXAAIgiAAIAABKgAgggDIAcAAQAQAAAKgJQAKgJAAgQQAAgPgKgIQgLgJgRAAIgaAAg");
	this.shape_14.setTransform(-14.7,11.6,0.253,0.253);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAyBeIgyhNIgyBNIgeAAIBBhiIg5haIAfAAIAlA4IAFAKIArhCIAdAAIg5BZIBBBjg");
	this.shape_15.setTransform(-19.9,11.6,0.253,0.253);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("Ag2BeIAAi8IBoAAIAAAZIhOAAIAAA8IBNAAIAAAXIhNAAIAAA4IBTAAIAAAYg");
	this.shape_16.setTransform(-24.7,11.6,0.253,0.253);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AG5DVQhCgBg6gsQg7gtAAg3IAAjuIj7CeIE1DhIjtAAIjGiSIjnCSIxjAAQh3AAg8g7Qg5g3AAhlIAAjSIChAAIAAD1QAABfBdAAIFRAAQAfhSBAgqIhrAAQAKhbBRg+QBTg+B6gBII5AAIDGCRIDliRIEBAAIAAD8QAABYBlgBIEKAAIAAlTICgAAIAAFTIIVAAQAWABAOgOQAMgNAAgSQgBgtgxAAIniAAQAAhaA3hEQBKhcCXAAIGLAAIAABUIl0AAQg1AAggAXQgdAWgKAnIGFAAQBFAAAoAoQAlAkAAA0QABA0glAkQgoAphFAAgAucCAIIhAAIC5h0IkBi6IAAAuIllAAQg3AAgjAdQgbAXgHAgIHCAAIAABRIlSAAQhdAAgLBbg");
	this.shape_17.setTransform(16.8,-3,0.253,0.253);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AmxEoQiYh5AAivQABi2Cjh5QCmh7D/AAQB/AABHATQAhAIADASQABANgNAQQjrEig5BvQgVApANATQANASAwAAIHJAAQAbAAAPgoQAOglAAg3QAAhvg5hWQg/heh9gzIAagoQCMA4BUBpQBUBpAAB5QAABegqBLQgQAdgQANQgTAPgZAAIo9AAQhqAAgpg6Qgqg5AuhSQAqhGBRhyQBKhoA5hHQAYgfgDgKQgDgJgaAAQjLAAiRBzQiQBxAACYQAAClCHBoQCIBpDgAAQD3AACKh8IBjAAQhQBbiQAvQh5AniLAAQkOAAijiDg");
	this.shape_18.setTransform(-45.2,-3.3,0.253,0.253);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.logoW, new cjs.Rectangle(-60,-14.1,120,28.2), null);


(lib.img2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.img2_1();
	this.instance.parent = this;
	this.instance.setTransform(-77.5,-21.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.img2, new cjs.Rectangle(-77.5,-21.5,155,43), null);


(lib.grad2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["#FFFFFF","rgba(255,255,255,0)"],[0,1],0,0,0,0,0,142.7).s().p("AvoPpQmemfAApKQAApJGemfQGfmeJJAAQJKAAGfGeQGeGfAAJJQAAJKmeGfQmfGepKAAQpJAAmfmeg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.grad2, new cjs.Rectangle(-141.5,-141.5,283,283), null);


(lib.grad = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.502,1],-41.5,0,41.5,0).s().p("AmePyIAA/jIM9AAIAAfjg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.grad, new cjs.Rectangle(-41.5,-101,83,202.1), null);


(lib.bgImg8_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.bgImg8();
	this.instance.parent = this;
	this.instance.setTransform(-150,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bgImg8_1, new cjs.Rectangle(-150,-300,300,600), null);


(lib.bgImg2_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.bgImg2();
	this.instance.parent = this;
	this.instance.setTransform(-150,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bgImg2_1, new cjs.Rectangle(-150,-300,300,600), null);


(lib.bgImg1_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.bgImg1();
	this.instance.parent = this;
	this.instance.setTransform(-150,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bgImg1_1, new cjs.Rectangle(-150,-300,300,600), null);


(lib.bg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.bg, new cjs.Rectangle(-150,-300,300,600), null);


(lib.arrowMc = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.arrow();
	this.instance.parent = this;
	this.instance.setTransform(-62,-6);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.arrowMc, new cjs.Rectangle(-62,-6,124,12), null);


(lib.bgImg7_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("Aj0K/QlPgOm1gWIlrgTIg6hVQJRAqExANQDRAJFtACQFMADBxgEQBjgEBRgKQBTgLAOgNQAOgLAKgWQAJgSAAgJQgBgNADgLQADgQAKAFQAKAGAEAoQAEAggBAqQAAAXAEAdQgCASglAFQhNALkAAHQiJAEiKAAQjSAAjVgJgAH1ANQhkh3gPgQQgRgTgNgGQgKgFgBACQgCACiiiwQghgkAUgpQAmg1AZglQAgguBXhcIBQhRQAggBgBABIgNAUIgVAWQgXAYgQATQgXAbgnAyQgsA5gRAXQgaAngLA8QgEATAOAfQAGAPAHAMQAAABB3CGQAeAhDDD7IAAAAIhehygAtHlVQg0gmAAg6QAAg8A4gnQA5gnBYAAQArAAAZAHQALADABAEQAAACgEAFIg7BFQglAsgLAVQgHAOAEAGQAFAGAQAAICkAAQAJAAAFgOQAFgMAAgTQAAhIhUghIAIgNQAxASAaAfQAbAfAAAoQAAAngKASQgFAIgGADQgFACgKAAIjFAAQhAAAgHgQQgFgKAUgiQAUggBFhSQAJgLgBgDQgBgDgKAAQhGAAgzAkQgzAjAAAyQAAA2AzAhQAxAhBPAAQApAAAagGQAmgIAagXIAjAAQgyA2h1AAQhcAAg4gpgAItmzIAYgbQAFgFAagSIApgbQALgIASgRIAigeQAagVBNgqIgXArIgJAPQgMATgPAcQgPAdAjACQASABAUgEIBKgNIBwgWQApgJBvgVQB1gVAhgEQAdgEAsgOIAlgMQAAABAKgCIAKgCIACAeQgBACgRADIgzAXQhRAYgiAIQgcAHh2AVQh5AWgaADIi0AcQikAagiADIgMABQgYAAAKgQg");
	mask.setTransform(-31.9,123.9);

	// Слой_3
	this.instance = new lib.grad();
	this.instance.parent = this;
	this.instance.setTransform(-356.2,46.4,3.075,2.168,30,0,0,0,-0.1);
	this.instance.compositeOperation = "lighter";
	this.instance._off = true;

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(9).to({_off:false},0).to({x:311.7,y:153.7},30).wait(2));

	// Слой_1
	this.instance_1 = new lib.bgImg7();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-170,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(41));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-170,-300,340,600);


(lib.bgImg6_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AD9ZuQmygDmBkGQlQjljLlfQlHo2AHmiQgLiHAXi6QAwl0Cvj8QDplRFgh5QGYiNHbDCQD7BmDcDFQDVC/CeEAQCdEABQEfQBSEngLEiQgLEghiD4QheDtijCwQigCsjQBcQjOBcjjAAIgIAAgAA7WSQBNAOBvgMQA4gGApgJIA5gZIAmgCIAbgFQBQggBfgwQA8geBThOIBIhIIgCgUIAqgtQAKgHASgXQAmgsAvhPQAvhOAuiQIAliAIgSgbIAKhLIAcgwQgGiTgCh2QgBhJgXhvQgMg4gLgpIgmghIgWhVIAegeIhpjtQgag8hYh+Qgrg/gmgzIgZAFIg6hEIANgWIgggjIg1g1QgPgOhAgzQhOg+gXgUQgkgehYgvQgsgXglgSIgcAKIhDgeIAAgPQACgCglgQQgzgVhRgVQhQgUiNADQhGACg2AFIglAPIg8AKIgFgMQguAJhMAhQiXBCiRB1QiRB1hvD7Qg3B9gaBmIgPAUQACgCABAaQABAbgJAOQgJAOgMACQgGABgDgCIhEhBIAAAAIAAAAQgIBdgCAqQgCAlAEBkQAEBvAHBDQAKBgAtCyIA0gKQAQgEAMAIIAKAIIARBaIgjAKIgqANIAAAAIAAAAQBPDBArBZQArBaCxD6QAHgRAQgXQAJgOALgFIAKgDIAqAoIAjAoIBqBeQB2BnA7ArQA8ArBeAuQBRAmACgCIA1AZQCYAmB6AWgAyfE5IAAAAIAAAAIAAAAg");
	mask.setTransform(-1.8,22.9);

	// Слой_3
	this.instance = new lib.grad();
	this.instance.parent = this;
	this.instance.setTransform(-262.2,-39.7,2.398,2.651,20.5,0,0,-0.1,0.1);
	this.instance.compositeOperation = "lighter";

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:244.7,y:108.3},24).wait(2));

	// Слой_1
	this.instance_1 = new lib.bgImg6();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-150,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(26));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,-300,300,600);


(lib.bgImg5_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AFKIbIg0gBQhEgDhLgJQhQgJjbg6QiSgmirgyQhbgahUgpQhCghAAgEQAAgBAMgEIACgqIALgNQAGgkAKgbQAKgbA2hSQAGgKAcgcIAggjQAJgMAMgbQADgHAJhJIAIhIQAKgSACAdQgBgBgCApIgCA9QAAAUgCAWQgCATgBgBIgFAJIgFAIIgJAHIgKAIQgBgBhABHQgLAMgOAYIgZAuQgLAUgKAhIgIAbQAAAcgBgBIAIAUQBwAzBGAbQAwATDYA0QC/AvByAYQBRAQBbAFQBOADgEgDQgBgBALgKIAEgIIAEgJIAKAbIgHACIgHADIgCAFIgDAGQgBAdgBAAIAAAAgADKEKIhyiQQgTgaAFgSQACgHARgRQAUgUA8gqQARgMAlgVIAegTQgBgBAPABIgKAQIgMAJIgMAIQAAgBg5AoQgfAWgoAqQgPAQAFAPQACAIAFAEIAZAlIBoCSIAkA0IhFhYgAEdA6QAqgUARgJQATgLAkgQIAegMIgHALIgIAHIgYAVQgZASAkACQAOAACWgPQCigRA1gVQAUgJADAHQACADgDADIgOAKQgQAMgGADQgHADhkAOQgvAHh1AKQh2AKg+ACIgMAAQgnAAAVgNgAGtgKIAAAAgApwgRQAAgCgtgtQgHgHg7hVIhBhcQgHgIALgUIAMgSIBfioIAIgVIA7g3QAFAdgCARQgBANABAmIACA1QABASAFAbQAGAeAGAKQAFAKADAaIAEAjQABAKgCAoIgDAlIgygxQgNgOgwg+IgHAUQAeAqAiArQAVAZAVANIARAJQAAAEgTAxIgTAwIAAAAg");
	mask.setTransform(-61.3,-3.7);

	// Слой_4
	this.instance = new lib.grad();
	this.instance.parent = this;
	this.instance.setTransform(-201.6,-25.1,1,1,30,0,0,-0.1,-0.1);
	this.instance.compositeOperation = "lighter";

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(5).to({x:60.2,y:11.4},34).wait(30));

	// Слой_1
	this.instance_1 = new lib.bgImg5();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-170,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(69));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-170,-300,340,600);


(lib.bgImg3_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(25));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AXwSKQACiygEg4QgFhGgThIQgNgzgNgeQgNgdgMgLQgfgahcgdQgkgLuYjuQtejggpgYQg8gkgygtQg7g0gcgzQgUglgWguQgOgZgMAIQgPAKgFgGQgGgHAPgVIAkgzIAWABIADgQIADgEQAGgFATgBQAdgCKXBPQAQgKAAABQAiABAAABIAQAWICrAUICrATIALgGQANgGAIgBQAPgBAHAAQAMABAAAFIACAWICzAYICzAXIAogbQAAABB4AQQB+ARAhACIBIAGQAgAEABABIAEgCIAEgDQCOAPAAABIAYgFQASgKgggRQg7ggADAGQgggLABABQhshKiAhRQh1hLhdgwQh/hCiJgxQi6hClgh5QmJiIhFgTQhHgVmRhrQmFhnhkgaIiygtIAAh+ID0A9QEFBAA1AOQBZAXDBAtQDYAyAlADIBgAJQA7AEAdgEQA9gKAVgLQAJgFAXgHIAdgLQAIgDALgIIAJgGIADgJQAHgKATABIAqADQAVAFAJAQQALAUAxA5QA0A8AiAgQAhAfChBmQCUBeBfA2QByBAHtEcQBIApBgBDQBTA6APAPQAbAcgBATQAAAJAMAHQAGADAHABQABABAJArQABABgGARQABAAADAZIAgBfIAIAWQgFBLgFA/QgEAmABCkIAADNQAABTgGDCQgGDogFAkIgBAFQgDAAABh2gAooiBIgrAuIgPATIgHAJQAKAcAIAQQAJASAmAgQAKAIGyB3QGSBtBWAWINWDTQAtgUgBAAIALgQQAQgVAOgXQATgfADhDQAEhFgSgsQgZg9hDhKIgcADIglgQQgVACgbgBQgSAAgIgGIgNgPQgHgIg8gNIhcgTQgqgIlkg6Ql4g+hegMQiLgSn1g5IBAAWIgCAYIAAAAIgeAfg");
	mask.setTransform(-14.7,-107.6);

	// Слой_3
	this.instance = new lib.grad();
	this.instance.parent = this;
	this.instance.setTransform(-334.2,-203.5,3.075,2.168,30,0,0,0,-0.1);
	this.instance.compositeOperation = "lighter";

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:288.7,y:17.8},24).wait(1));

	// Слой_1
	this.instance_1 = new lib.bgImg3();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-170,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(25));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-170,-300,340,600);


(lib.arrow_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.arrowMc();
	this.instance.parent = this;
	this.instance.filters = [new cjs.BlurFilter(3, 3, 1)];
	this.instance.cache(-64,-8,128,16);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.arrow_1, new cjs.Rectangle(-64,-8,132,20), null);


(lib.bgImg4_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.instance = new lib.arrow_1();
	this.instance.parent = this;
	this.instance.setTransform(63.1,61.1,1,1,-63.7,0,0,101,0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({rotation:33.8,x:63.2,y:61.2},5).wait(1).to({rotation:33,y:61.1},0).wait(1).to({rotation:33.8,y:61.2},0).to({scaleX:1,scaleY:1,rotation:-32.6,y:61.1},15).to({scaleX:1,scaleY:1,rotation:33.8,y:61.2},4).wait(1).to({rotation:33,y:61.1},0).wait(1).to({rotation:33.8,y:61.2},0).wait(1).to({rotation:33,y:61.1},0).wait(1).to({rotation:33.8,y:61.2},0).to({rotation:-63.7,x:63.1,y:61.1},22).wait(17));

	// Слой_1
	this.instance_1 = new lib.bgImg4();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-150,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(69));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,-300,300,600);


(lib.banner = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_149 = function() {
		this.bg3.play();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(149).call(this.frame_149).wait(426));

	// logo
	this.instance = new lib.logoW();
	this.instance.parent = this;
	this.instance.setTransform(0,0,1.717,1.715);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(514).to({_off:false},0).to({alpha:1},10).wait(30).to({alpha:0},10).to({_off:true},1).wait(10));

	// urText
	this.instance_1 = new lib.urText();
	this.instance_1.parent = this;
	this.instance_1.setTransform(0.6,223);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(514).to({_off:false},0).to({alpha:1},10).wait(30).to({alpha:0},10).to({_off:true},1).wait(10));

	// bg
	this.instance_2 = new lib.bg();
	this.instance_2.parent = this;
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(504).to({_off:false},0).to({alpha:1},10).wait(50).to({alpha:0},10).wait(1));

	// logo
	this.instance_3 = new lib.logoW();
	this.instance_3.parent = this;
	this.instance_3.setTransform(0,259,1.4,1.399);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(575));

	// bg
	this.instance_4 = new lib.bg();
	this.instance_4.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({alpha:0},15).wait(24).to({alpha:1},10).to({alpha:0},15).wait(60).to({alpha:1},10).to({alpha:0},15).wait(85).to({alpha:1},5).to({alpha:0},5).wait(35).to({alpha:1},10).to({alpha:0},15).wait(45).to({alpha:1},5).to({alpha:0},5).wait(35).to({alpha:1},10).to({alpha:0},15).to({_off:true},95).wait(61));

	// t4_3
	this.instance_5 = new lib.t4_3();
	this.instance_5.parent = this;
	this.instance_5.setTransform(277.5,-126.6);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(454).to({_off:false},0).to({x:27.5},10,cjs.Ease.get(1)).to({_off:true},50).wait(61));

	// t4_2
	this.instance_6 = new lib.t4_2();
	this.instance_6.parent = this;
	this.instance_6.setTransform(328,-189.6);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(444).to({_off:false},0).to({x:78},10,cjs.Ease.get(1)).to({_off:true},60).wait(61));

	// t4_1
	this.instance_7 = new lib.t4_1();
	this.instance_7.parent = this;
	this.instance_7.setTransform(291,-249.6);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(434).to({_off:false},0).to({x:41},10,cjs.Ease.get(1)).to({_off:true},70).wait(61));

	// t3_2
	this.instance_8 = new lib.t3_2();
	this.instance_8.parent = this;
	this.instance_8.setTransform(-269.6,-189.2);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(314).to({_off:false},0).to({x:-29.6},10,cjs.Ease.get(1)).to({_off:true},30).wait(221));

	// t3_1
	this.instance_9 = new lib.t3_1();
	this.instance_9.parent = this;
	this.instance_9.setTransform(-321.2,-249.2);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(304).to({_off:false},0).to({x:-81.2},10,cjs.Ease.get(1)).to({_off:true},40).wait(221));

	// t2_2
	this.instance_10 = new lib.t2_2();
	this.instance_10.parent = this;
	this.instance_10.setTransform(-239.6,-189.2);
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(199).to({_off:false},0).to({x:-59.6},10,cjs.Ease.get(1)).to({_off:true},30).wait(336));

	// t2_1
	this.instance_11 = new lib.t2_1();
	this.instance_11.parent = this;
	this.instance_11.setTransform(-265,-249.2);
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(189).to({_off:false},0).to({x:-85},10,cjs.Ease.get(1)).to({_off:true},40).wait(336));

	// t1_2
	this.instance_12 = new lib.t1_2();
	this.instance_12.parent = this;
	this.instance_12.setTransform(345.4,88.8);
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(89).to({_off:false},0).to({x:55.4},10,cjs.Ease.get(1)).to({_off:true},35).wait(441));

	// t1_1
	this.instance_13 = new lib.t1_1();
	this.instance_13.parent = this;
	this.instance_13.setTransform(297,28.8);
	this.instance_13._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(79).to({_off:false},0).to({x:7},10,cjs.Ease.get(1)).to({_off:true},45).wait(441));

	// bgImg4
	this.instance_14 = new lib.bgImg4_1("single",0);
	this.instance_14.parent = this;
	this.instance_14.alpha = 0;
	this.instance_14._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(179).to({_off:false},0).to({alpha:1},5).wait(5).to({mode:"synched",loop:false},0).to({_off:true},50).wait(336));

	// img1
	this.instance_15 = new lib.img2();
	this.instance_15.parent = this;
	this.instance_15.setTransform(-25.5,-124.5);
	this.instance_15.alpha = 0;
	this.instance_15._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_15).wait(74).to({_off:false},0).to({alpha:1},5).to({_off:true},55).wait(441));

	// grad2
	this.instance_16 = new lib.grad2();
	this.instance_16.parent = this;
	this.instance_16.setTransform(-8.4,-78.5,1.497,1.13,10,0,0,0,-0.1);
	this.instance_16.compositeOperation = "lighter";
	this.instance_16._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_16).wait(405).to({_off:false},0).wait(19).to({alpha:0},10).to({_off:true},1).wait(140));

	// bgImg1
	this.instance_17 = new lib.bgImg1_1();
	this.instance_17.parent = this;

	this.instance_18 = new lib.bgImg2_1();
	this.instance_18.parent = this;

	this.bg3 = new lib.bgImg3_1();
	this.bg3.name = "bg3";
	this.bg3.parent = this;
	this.bg3.setTransform(-20,0);
	this.bg3._off = true;

	this.instance_19 = new lib.bgImg5_1("synched",0);
	this.instance_19.parent = this;
	this.instance_19.setTransform(20,0);
	this.instance_19._off = true;

	this.instance_20 = new lib.bgImg6_1("single",0);
	this.instance_20.parent = this;

	this.instance_21 = new lib.bgImg7_1("synched",0,false);
	this.instance_21.parent = this;
	this.instance_21.setTransform(-20,0);
	this.instance_21._off = true;

	this.instance_22 = new lib.bgImg8_1();
	this.instance_22.parent = this;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_17}]}).to({state:[{t:this.instance_18}]},49).to({state:[{t:this.bg3}]},85).to({state:[{t:this.bg3}]},50).to({state:[{t:this.instance_19}]},55).to({state:[{t:this.instance_19}]},50).to({state:[{t:this.instance_20,p:{mode:"single",loop:undefined}}]},1).to({state:[{t:this.instance_20,p:{mode:"synched",loop:false}}]},34).to({state:[{t:this.instance_21}]},30).to({state:[{t:this.instance_21}]},50).to({state:[{t:this.instance_22}]},1).to({state:[]},109).wait(61));
	this.timeline.addTween(cjs.Tween.get(this.bg3).wait(134).to({_off:false},0).to({x:20},50).to({_off:true},55).wait(336));
	this.timeline.addTween(cjs.Tween.get(this.instance_19).wait(239).to({_off:false},0).to({x:-20},50).to({_off:true},1).wait(285));
	this.timeline.addTween(cjs.Tween.get(this.instance_21).wait(354).to({_off:false},0).to({x:20},50).to({_off:true},1).wait(170));

	// bg
	this.instance_23 = new lib.bg();
	this.instance_23.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_23).wait(575));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,-300,300,600);


// stage content:
(lib._300x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// cover
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#666666").ss(2,1,1).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// banner
	this.instance = new lib.banner();
	this.instance.parent = this;
	this.instance.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(149,299,302,602);
// library properties:
lib.properties = {
	id: '98B8480EF87040C5BA3C0D381DCA1DA0',
	width: 300,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/arrow.png", id:"arrow"},
		{src:"images/bgImg1.jpg", id:"bgImg1"},
		{src:"images/bgImg2.jpg", id:"bgImg2"},
		{src:"images/bgImg3.jpg", id:"bgImg3"},
		{src:"images/bgImg4.jpg", id:"bgImg4"},
		{src:"images/bgImg5.jpg", id:"bgImg5"},
		{src:"images/bgImg6.jpg", id:"bgImg6"},
		{src:"images/bgImg7.jpg", id:"bgImg7"},
		{src:"images/bgImg8.jpg", id:"bgImg8"},
		{src:"images/img2_1.png", id:"img2_1"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['98B8480EF87040C5BA3C0D381DCA1DA0'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;