(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.bgImg = function() {
	this.initialize(img.bgImg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.dev = function() {
	this.initialize(img.dev);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,275,51);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.V = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00BFC3").s().p("Ag2UEQgVgSgMgdMgRXgnuIDTAAMAPfAkcMAPkgkcIDHAAMgRXAnuQgNAegUASQgZAVgeAAQgdAAgZgWg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.V, new cjs.Rectangle(-119.9,-130.5,239.8,261.2), null);


(lib.urText = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AE+CSIgCgDIgBgDIABgDIACgDIAEgBIADABIACADIABADIgBADIgCADIgDABgAgcCTIABgJIADAAQABAAAAAAQABAAAAAAQABgBAAAAQABAAAAAAQABgCABgEIABgiIAnAAIAAAxIgKAAIAAgpIgTAAIgBARIgCAPQgBAFgDACQgDACgGABgAhHCPQgGgEgDgFQgDgFAAgIQAAgHADgGQADgGAGgDQAGgDAHgBQAIABAFADQAGADADAGQAEAFAAAIQAAAIgEAFQgDAFgGAEQgFAEgIAAQgHAAgGgEgAhCBqQgDADgCAEQgCADAAAFQAAAFACAEQACAEADACQAEACAEAAQAEAAAEgCQAEgCACgEQACgEAAgFQAAgFgCgDQgCgEgEgDIgIgCIgIACgAjwCPQgGgEgDgFQgDgGAAgHQAAgGADgHQADgGAGgDQAGgDAHgBQAIABAFADQAGADADAGQAEAHAAAGQAAAHgEAGQgDAFgGAEQgGAEgHAAQgHAAgGgEgAjrBqQgDACgCAFQgCADAAAFQAAAFACAEQACAEADACQAEACAEAAQAEAAAEgCQADgCADgEQACgEAAgFQAAgFgCgDQgDgFgDgCIgIgCIgIACgAEmCSIAAgkIgZAkIgJAAIAAgxIAJAAIAAAjIAagjIAIAAIAAAxgADtCSIAAgjIgQAVIgGAAIgQgVIAAAjIgJAAIAAgxIAJAAIATAZIATgZIAJAAIAAAxgACmCSIAAgxIAJAAIAAAxgACOCSIAAgWIgYAAIAAAWIgKAAIAAgxIAKAAIAAATIAYAAIAAgTIAKAAIAAAxgABICSIAAgpIgRAAIAAgIIAsAAIAAAIIgRAAIAAApgAAkCSIAAgxIAJAAIAAAxgAhoCSIAAgWIgYAAIAAAWIgJAAIAAgxIAJAAIAAATIAYAAIAAgTIAKAAIAAAxgAi+CSIAAgxIAVAAQAKAAAEAEQAEACAAAHQAAAEgBACQgDADgDACQAFAAACADQADAEAAAEQAAADgCAEQgCADgEABQgEADgGAAgAi1CLIANAAQAGAAACgCQACgCAAgEQAAgHgKAAIgNAAgAi1B2IALAAQAFAAACgCQADgCAAgDQAAgHgKAAIgLAAgAkRCSIAAgpIgYAAIAAApIgJAAIAAgxIArAAIAAAxgACnBVIgCgCIgBgEIABgCIACgCIAEgBIADABIACACIABACQAAABAAABQAAAAAAABQgBAAAAAAQAAAAAAABIgCACIgDABgAAlBVIgCgCIgBgEIABgCIACgCIADgBIAEABIACACIABACIgBAEIgCACIgEABgAL4A7IAAhHIAKAAIAAAHQADgEAEgCQAEgDAGABQAGAAAFADQAFADADAGQAEAFAAAHQAAAIgEAFQgDAGgFADQgFADgGABQgGgBgEgCQgFgCgCgDIAAAegAMJgDQgEADgBADQgCADAAAFQAAAGACADQABADAEADQADACAFAAQAEAAAEgCQADgDACgDQACgDAAgGQAAgFgCgDQgCgDgDgDQgEgBgEAAQgFAAgDABgAGBAwIAAgNIgpAAIAAANIgIAAIAAgUIAGAAQACgEABgDIACghIAmAAIAAAoIAIAAIAAAUgAFkAIIgCAMIgCAIIAYAAIAAggIgUAAgAxqAwIAAgNIhDAAIAAgvIAJAAIAAAoIAUAAIAAgoIAJAAIAAAoIAUAAIAAgoIAKAAIAAAoIAHAAIAAAUgAPcAhQgGgDgDgGQgDgFAAgIQAAgHADgFQADgGAGgDQAFgDAGAAQAGgBAEADQADABAEAFIAAgHIAJAAIAAAvIgJAAIAAgGQgEADgDACQgEACgGABQgGgBgFgDgAPhgDQgDACgCAEQgCAEAAAEQAAAEACAFQACAEADACQADACAFAAQAFAAADgCQADgCACgEQACgDAAgGQAAgFgCgDQgCgEgDgCQgDgBgFAAQgFAAgDABgAN3AhQgGgEgDgFQgDgFAAgIQAAgHADgFQADgFAGgEQAGgDAIAAQAGgBAGADQAGADACAEIgGAFIgGgEQgEgCgEABQgGAAgCABIgGAGQgCAEAAAEQAAAEACAFQACAEADABQAEADAFAAQAEAAAEgCQADgBADgEIAGAHQgDAEgFACQgFADgHAAQgIgBgGgDgALHAhQgGgEgDgFQgDgFAAgHQAAgJADgEQADgGAGgDQAFgDAIAAQAIAAAFADQAGADADAGQADAFAAAIQAAAHgDAFQgDAFgGAEQgGADgHABQgHgBgGgDgALMgDQgEADgBADQgCADAAAGQAAAEACAEQABAEAEABQAEADAEAAQAEAAAEgDQADgBADgEQACgEAAgEQAAgGgCgDQgCgDgEgDIgIgBIgIABgAGQAlIABgJIADAAQAAAAABAAQAAAAABAAQAAgBABAAQAAAAABgBIABgEIACgiIAnAAIAAAvIgJAAIAAgnIgVAAIAAAQIgCAOQgBAGgEACQgCADgHAAgABbAlIACgJIACAAQABAAAAAAQABAAAAAAQABgBAAAAQABAAAAgBQACgBAAgDIABgiIAoAAIAAAvIgKAAIAAgnIgUAAIgBAQIgBAOQgCAGgDACQgDADgGAAgAggAkIgDgDIAAgDIAAgDIADgDIADgBIADABIADADIABADIgBADIgDADIgDABgAixAhQgGgEgDgFQgDgFAAgIQAAgHADgFQADgFAGgEQAFgDAIAAQAGgBAGADQAGADADAEIgGAFIgHgEQgDgCgFABQgFAAgDABQgEADgCADQgCAEAAAEQAAAEACAFQADAFADAAQAEADAEAAQAFAAADgCQAEgBADgEIAGAHQgEAEgFACQgEADgIAAQgHgBgGgDgAmCAhQgGgEgDgFQgDgFAAgIQAAgHADgFQAEgGAFgDQAFgDAHAAQAHAAAGACQAGAFACAEQADAFAAAHIAAAEIgmAAQAAAEACAEIAGAEQAEACAEAAIAJgCIAGgDIAFAGQgDADgFACQgGACgGABQgIgBgGgDgAlnAHQgBgGgEgDQgFgEgFABQgFgBgEAEQgFACAAAHIAdAAIAAAAgAnMAlIACgJIACAAQABAAAAAAQABAAAAAAQABgBAAAAQABAAAAgBQACgBAAgDIABgiIAoAAIAAAvIgKAAIAAgnIgUAAIgBAQIgBAOQgCAGgDACQgDADgGAAgAn7AhQgFgDgDgGQgDgFAAgIQAAgHADgFQADgGAFgDQAFgDAHAAQAFgBAEADQAFACACAEIAAgHIAKAAIAAAvIgKAAIAAgGQgCADgFACQgDACgGABQgGgBgGgDgAn1gDQgEADgBADQgCADAAAFQAAAGACADQABADAEADQADACAFAAQAEAAAEgCQADgDACgDQACgDAAgGQAAgFgCgDQgCgDgDgDQgEgBgEAAQgFAAgDABgAovAiQgGgCgDgDIAGgGQACACAEADQAEABAFAAQAFAAAEgCQADgCAAgEQAAgHgLAAIgKAAIAAgHIAIAAQAGAAACgCQADAAAAgEQAAgDgDgCQgCgBgFAAQgIgBgGAGIgFgFQADgEAFgDIALgBQAJAAAFADQAFAEAAAGQAAADgCADQgBADgEACQAEAAADADQACAEAAAEQAAAEgCAEQgCADgGACQgFACgGAAQgIgBgEgCgAp2AhQgGgDgDgGQgDgFAAgIQAAgHADgFIAJgJQAFgDAJAAQAGgBAGADQAFACADAFIgGAEQgCgCgEgCQgEgBgEAAQgFAAgDABQgDACgDACIgDAHIAZAAIAAAHIgZAAQABAGAFAFQAEAEAHAAQAEAAAEgCQAEgCACgCIAGAFQgDAEgFACQgFACgHABQgIgBgGgDgAqzAhQgFgDgDgGQgDgFAAgIQAAgHADgFQADgGAFgDQAFgDAHAAQAEgBAFADQAEACADAEIAAgHIAKAAIAAAvIgKAAIAAgGIgHAFQgEACgFABQgHgBgFgDgAqtgDQgDACgDAEQgCADAAAFQAAAGACADQADAEADACQACACAFAAQAFAAADgCQADgCADgEQACgFAAgEQAAgEgCgEQgDgEgDgCQgDgBgFAAQgFAAgCABgAtoAlIABgJIADAAQAAAAABAAQABAAAAAAQABgBAAAAQAAAAABgBIABgEIACgiIAnAAIAAAvIgJAAIAAgnIgVAAIAAAQIgCAOQgBAFgEADQgCADgHAAgAxQAhQgGgEgDgFQgDgFAAgHQAAgJADgEQADgGAGgDQAFgDAIAAQAIAAAFADQAGADADAGQADAFAAAIQAAAHgDAFQgDAFgGAEQgGADgHABQgHgBgGgDgAxLgDQgEADgBADQgDADAAAGQAAAEADAEQABAEAEABQAEADAEAAQAEAAAEgDQADgBADgEQACgFAAgDQAAgFgCgEQgCgDgEgDIgIgBQgEAAgEABgASgAjIAAgTIgLAAIgLATIgLAAIANgTQgGgCgDgDQgDgDAAgGQAAgGAFgEQAFgEAKAAIAWAAIAAAvgASMgDQgCADAAACQAAADACADQAEACAEAAIAMAAIAAgPIgMAAQgEAAgEACgARrAjIAAgVIgZAAIAAAVIgJAAIAAgvIAJAAIAAASIAZAAIAAgSIAJAAIAAAvgAQxAjIAAgVIgYAAIAAAVIgKAAIAAgvIAKAAIAAASIAYAAIAAgSIAKAAIAAAvgAOxAjIAAgnIgRAAIAAgIIArAAIAAAIIgRAAIAAAngANXAjIAAgjIgZAjIgJAAIAAgvIAJAAIAAAjIAZgjIAJAAIAAAvgAKtAjIgNgTIgCgCIgJAAIAAAVIgKAAIAAgvIAKAAIAAASIAIAAIABgBIACgBIANgQIAKAAIgRAWIASAZgAJ0AjIAAgjIgaAjIgIAAIAAgvIAJAAIAAAjIAZgjIAJAAIAAAvgAIdAjIAAgvIAVAAQAKAAAEADQAEAEAAAFQAAAEgBACQgDAEgDABQAFABACACQADAEAAAEQAAADgCAEQgCADgEABQgEACgGAAgAImAdIANAAQAGAAACgDQACgBAAgEQAAgHgKAAIgNAAgAImAHIALAAQAFAAACgBQADgCAAgDQAAgGgKAAIgLAAgAHuAjIAAgTIgLAAIgLATIgLAAIANgTQgGgCgDgDQgDgDAAgGQAAgGAFgEQAFgEAKAAIAWAAIAAAvgAHagDQgCADAAACQAAADACADQAEACAEAAIAMAAIAAgPIgMAAQgEAAgEACgAEnAjIAAgjIgaAjIgJAAIAAgvIAKAAIAAAjIAZgjIAJAAIAAAvgADwAjIgNgTIgBgCIgKAAIAAAVIgKAAIAAgvIAKAAIAAASIAIAAIACgBQAAAAAAAAQAAAAAAAAQABAAAAAAQAAgBAAAAIANgQIALAAIgRAWIARAZgACcAjIAAgvIAJAAIAAAQIALAAQALABAEADQAFAEAAAIQAAAIgFADQgGAEgJAAgAClAcIAKAAQALAAAAgIQAAgEgCgCQgEgCgFAAIgKAAgABIAjIAAgvIAKAAIAAAvgAAeAjIAAg9IgXAAIAAgJIA3AAIAAAJIgXAAIAAA9gAhUAjIAAgvIAKAAIAAAQIAKAAQALABAEADQAGAEAAAIQAAAIgGADQgFAEgKAAgAhKAcIAKAAQALAAAAgIQAAgEgDgCQgEgCgEAAIgKAAgAh4AjIAAgnIgRAAIAAgIIAsAAIAAAIIgRAAIAAAngAjSAjIAAgvIAKAAIAAAvgAjqAjIAAgVIgYAAIAAAVIgKAAIAAgvIAKAAIAAASIAYAAIAAgSIAKAAIAAAvgAkgAjIgMgTIgBgBIgCgBIgEAAIAAAVIgKAAIAAgVIgDAAIgCABIgBABIgMATIgLAAIAQgZIgQgWIALAAIANARIACABIADAAIAAgSIAKAAIAAASIAEAAIACgBIABgBIAMgQIALAAIgQAWIAQAZgArNAjIgNgTIgBgCIgKAAIAAAVIgJAAIAAgvIAJAAIAAASIAIAAIACgBIABgBIANgQIALAAIgRAWIARAZgAsGAjIAAgjIgZAjIgJAAIAAgvIAJAAIAAAjIAagjIAJAAIAAAvgAt4AjIgNgTIgBgCIgKAAIAAAVIgJAAIAAgvIAJAAIAAASIAIAAIACgBIABgBIANgQIALAAIgRAWIARAZgAuxAjIAAgjIgZAjIgJAAIAAgvIAJAAIAAAjIAagjIAJAAIAAAvgAwIAjIAAgvIAWAAQAJAAAEADQAFAEAAAFQAAAEgCACQgCAEgDABQAEAAADADQACAEAAAEQAAADgCAEQgCADgEABQgDACgGAAgAv/AdIANAAQAGAAACgDQADgBAAgEQAAgHgLAAIgNAAgAv/AHIALAAQAFAAADgBQADgDAAgCQAAgGgLAAIgLAAgABKgYIgCgDIgBgDIABgCIACgCIADgCIADACIACACIABACQAAABAAABQAAAAAAAAQAAABAAAAQAAAAgBAAIgCADIgDABgAjQgYIgDgDIgBgDIABgCIADgCQAAgBAAAAQAAAAABAAQAAAAABAAQAAgBABAAIADACIACACIABACIgBADIgCADIgDABgApVgxIACgJIAGABIAFgBIADgDIADgGIADgGIgVgxIAKAAIAPAmIAPgmIALAAIgdBCIgGAGQgFACgEAAgACIgxIAAhJIAJAAIAAAHQAEgEADgCQAFgCAFAAQAHgBAFAEQAFADADAGQADAGAAAHQAAAIgDAFQgDAGgFADQgFADgHAAQgGAAgEgCIgHgGIAAAggACYhwQgDACgCAEQgCADAAAFQAAAFACAEQACADADADQAEACAEAAQAFAAADgCQAEgDABgDQACgEAAgFQAAgFgCgDQgBgEgEgCQgDgCgFAAQgEAAgEACgAmCgxIAAhJIAKAAIAAAHQADgEAEgCQAEgCAFAAQAHgBAFAEQAFADADAGQADAHAAAGQAAAGgDAHQgDAGgFADQgFADgHAAQgGAAgDgCQgFgCgCgEIAAAggAlyhwQgDACgCAEQgCADAAAFQAAAFACAEQACADADADQAEACAEAAQAFAAADgCQAEgDABgDQACgEAAgFQAAgFgCgDQgBgEgEgCQgDgCgFAAQgEAAgEACgATAg7IAGgHQADgEAAgDIgFgCQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAgBAAAAQAAgBAAgBQABAAAAgBQAAAAABgBQAAAAABAAQAAgBABAAQAAAAABAAQABAAAAAAQADgBACADQACACAAAFQAAAGgDAFQgDAEgHAGgAEChLQgFgCgDgEIAFgFQADADADABIAJACQAFAAAEgCQADgCAAgEQAAgGgKAAIgKAAIAAgIIAIAAQAFAAADgBQACgCAAgEQAAgDgCgBQgCgCgGAAQgIAAgGAFIgFgFQADgEAFgCQAHgCAFAAQAJAAAFADQAFAEAAAGQAAAFgCACQgCADgEABQAFACACADQADADAAAEQAAAEgDAEQgCACgFADQgHACgFAAQgGAAgGgDgAkIhLQgFgBgEgFIAGgFQADADADABQAEACAFAAQAFAAAEgCQADgCAAgEQAAgGgKAAIgKAAIAAgIIAIAAQAFAAACgBQADgCAAgEQAAgDgCgBQgCgCgGAAQgIAAgGAFIgFgFQADgEAFgCQAHgCAFAAQAIAAAGADQAEAEAAAGQAAAEgBADQgDAEgDAAQAFACACADQACACAAAFQAAAFgCADQgCACgGADQgGACgFAAQgGAAgGgDgAqQhMQgGgDgDgGQgDgFAAgIQAAgHADgGQADgFAGgEQAFgEAIABQAGAAAGACQAGADADAEIgGAFQgDgDgDgBQgEgCgEAAQgFAAgDACQgDABgDADIgDAHIAYAAIAAAIIgYAAQABAFAEAFQAEADAIAAQAEAAAEgBQADgBADgDIAGAFQgDAEgGACQgGADgGAAQgGAAgHgEgAPyhMQgGgDgDgGQgDgFAAgHQAAgIADgGQAEgGAFgDQAFgEAIABQAIgBAFAEQAGADADAGQADAGAAAIQAAAHgDAFQgDAGgGADQgGADgHAAQgHAAgGgDgAP3hwIgGAGQgCAEAAAFQAAADACAFQADAEADABQAEADAEAAQAEAAAEgDQADgBADgEQACgFAAgDQAAgFgCgEQgCgEgEgCQgEgCgEAAQgEAAgEACgAJThMQgGgDgCgGQgEgFAAgIQAAgHADgGIAJgJQAGgEAIABQAGAAAGACQAGADACAEIgGAGQgCgDgEgCQgEgBgEAAQgFAAgDACQgEACgCAEQgCADAAAFQAAAFACAEQACAEAEABQADADAFAAQAFAAADgCQAEgCACgDIAGAGQgEAFgEACQgFACgHAAQgIAAgGgDgAFihJIABgIIADAAQABAAAAAAQABAAAAAAQABgBAAAAQABAAAAgBQABgBABgDIABgjIAoAAIAAAwIgKAAIAAgoIgUAAIgBARIgCAOQgBAGgDACQgDACgGAAgAE3hMQgFgDgEgGQgDgFAAgHQAAgIADgGQAEgGAFgDQAGgEAHABQAIgBAFAEQAGADADAGQAEAFAAAJQAAAHgEAFQgDAGgGADQgFADgIAAQgHAAgGgDgAE8hwQgDACgCAEQgCADAAAGQAAAFACADQACAEADABQAEADAEAAQAEAAAEgDQAEgBACgEQACgDAAgFQAAgGgCgDQgCgEgEgCIgIgCIgIACgADOhMQgGgDgDgGQgEgFAAgHQAAgJAEgFQADgGAGgDQAFgEAIABQAHgBAGAEQAFADAEAGQADAGAAAIQAAAHgDAFQgEAGgFADQgGADgHAAQgIAAgFgDgADThwQgEACgCAEQgCADAAAGQAAAEACAEQACAEAEABQAEADAEAAQAEAAAEgDQADgBACgEQACgDAAgFQAAgGgCgDQgCgEgDgCIgIgCIgIACgABYhMQgFgDgEgGQgDgFAAgIQAAgHADgGQADgGAGgDQAFgEAIABQAHAAAFACQAFAEAEAFQADAGAAAGIgBAFIgmAAQAAADADAFQABACAEACIAIACQAFAAAEgCIAHgDIAFAFQgDAFgGABQgFACgHAAQgIAAgGgDgABzhmQgBgGgEgEQgEgDgFAAQgGAAgEADQgEAEgBAGIAdAAIAAAAgAgehJIgDgDIgBgDIABgDIADgDIADAAIADAAIADADIAAADIAAADIgDADIgDAAgAoShMQgGgDgDgGQgDgFAAgIQAAgHADgGQADgFAGgEQAFgEAIABQAGAAAGACQAGAEADADIgGAGIgHgFQgDgBgFAAQgFAAgDACQgEACgCAEQgCADAAAFQAAAFACAEQADAEADABQAEADAEAAQAFAAADgCQAEgCADgDIAGAGQgEAFgFACQgEACgIAAQgHAAgGgDgArNhMQgGgEgDgFQgDgFAAgIQAAgHADgGQADgGAGgDQAFgEAGABQAGAAAEACQAEACADAEIAAgHIAKAAIAAAwIgKAAIAAgHQgCAEgFACQgEACgGAAQgGAAgFgDgArIhwQgDACgCAEQgCAEAAAEQAAAFACAEQACADADADQAEACAEAAQAFAAADgCQAEgDABgDQACgEAAgFQAAgFgCgDQgBgEgEgCQgDgCgFAAQgEAAgEACgAs5hMQgFgCgEgFQgDgFgBgHIgIAAIAAAVIgJAAIAAgwIAJAAIAAATIAJAAQAAgGAEgEQAEgFAEgDQAGgCAGAAQAHgBAFAEQAGADADAGQADAGAAAHQAAAIgDAFQgDAGgGADQgFADgHAAQgHAAgFgDgAs1hwQgEACgBAEQgCAFAAADQAAAEACAFQABAEAEABQADACAFAAQAFAAACgCQAEgDABgCQACgEAAgFQAAgFgCgDQgBgEgEgCQgCgCgFAAQgFAAgDACgAuYhJIACgIIACAAQABAAAAAAQABAAABAAQAAgBAAAAQABAAAAgBQACgBAAgDIACgjIAnAAIAAAwIgKAAIAAgoIgUAAIgBARQAAAKgBAEQgCAGgDACQgDACgGAAgAx9hMQgGgDgEgGQgDgFAAgIQAAgHADgGQAEgHAFgCQAFgEAIABQAHAAAFACQAGAFADAEQADAGAAAGIgBAFIgmAAQAAADADAFIAFAEQAEACAFAAIAIgCIAHgDIAFAFQgDAEgGACQgFACgHAAQgIAAgFgDgAxjhmQAAgFgFgFQgEgDgFAAQgFAAgFADQgEAEgBAGIAdAAIAAAAgASthKIAAgVIgYAAIAAAVIgJAAIAAgwIAJAAIAAATIAYAAIAAgTIAKAAIAAAwgAR0hKIAAgjIgZAjIgJAAIAAgwIAJAAIAAAkIAagkIAJAAIAAAwgAQuhKIAAgoIgRAAIAAgIIAsAAIAAAIIgRAAIAAAogAPXhKIgOgUIgKAAIAAAUIgJAAIAAgwIAJAAIAAATIAJAAIABAAQAAAAABgBQAAAAAAAAQAAAAAAAAQAAgBAAAAIANgRIALAAIgRAXIASAZgAOehKIAAgwIAKAAIAAAwgAOGhKIAAgVIgYAAIAAAVIgJAAIAAgwIAJAAIAAATIAYAAIAAgTIAKAAIAAAwgAMbhKIAAgwIAKAAIAAASIAKAAQAKgBAFAEQAFADAAAJQAAAIgFAEQgFADgKAAgAMlhRIAKAAQALAAAAgIQAAgEgDgCQgEgCgEAAIgKAAgAL3hKIAAgoIgRAAIAAgIIArAAIAAAIIgQAAIAAAogALThKIAAgjIgZAjIgJAAIAAgwIAJAAIAAAkIAagkIAIAAIAAAwgAKNhKIAAgoIgRAAIAAgIIArAAIAAAIIgRAAIAAAogAIzhKIAAgwIAJAAIAAAwgAIbhKIAAgjIgQAWIgGAAIgQgWIAAAjIgJAAIAAgwIAJAAIATAZIATgZIAJAAIAAAwgAGjhKIAAgwIAJAAIAAASIALAAQAKgBAFAEQAFADAAAJQAAAIgFAEQgGADgJAAgAGshRIAKAAQALAAAAgIQAAgEgCgCQgEgCgFAAIgKAAgAA9hKIgFgNIghAAIgFANIgKAAIAbhHIAJAAIAbBHgAA0hgIgNgiIgMAiIAZAAgAhUhKIAAgwIAVAAQAKAAAEADQAEADAAAGQAAAFgBACQgCADgDABQAEABACAEQADACAAAFQAAAFgCACQgCADgEABQgEACgGAAgAhLhRIANAAQAGAAACgCQACgBAAgEQAAgHgKAAIgNAAgAhLhmIALAAQAFABADgCQACgCAAgEQAAgGgKAAIgLAAgAhshKIAAgwIAKAAIAAAwgAiBhKIgOgUIgKAAIAAAUIgJAAIAAgwIAJAAIAAATIAJAAIABAAQABAAAAgBQAAAAAAAAQAAAAAAAAQAAgBAAAAIANgRIALAAIgRAXIASAZgAi5hKIAAgjIgaAjIgIAAIAAgwIAJAAIAAAkIAZgkIAJAAIAAAwgAkkhKIAAgjIgZAjIgJAAIAAgwIAJAAIAAAkIAagkIAJAAIAAAwgAmuhKIgNgSIgNASIgLAAIASgYIgSgYIALAAIANASIAOgSIALAAIgTAYIATAYgAnmhKIAAgwIAJAAIAAAwgArthKIAAgUQgHADgHAAQgGAAgEgCQgEgCgCgEQgCgDAAgGIAAgOIAJAAIAAANQAAAFADACQACACAGAAQAHAAAFgCIAAgUIAJAAIAAAwgAunhKIgNgTIgCgBIgJAAIAAAUIgKAAIAAgwIAKAAIAAATIAIAAIACAAIAOgTIALAAIgRAXIARAZgAvghKIAAgjIgZAjIgJAAIAAgwIAJAAIAAAkIAZgkIAJAAIAAAwgAw3hKIAAgwIAWAAQAJAAAEADQAFAEAAAFQAAAEgCADQgCADgDABQADABAEAEQACACAAAFQAAAFgCACQgDADgDABQgEACgGAAgAwuhRIANAAQAGAAACgCQACgBAAgEQAAgHgKAAIgNAAgAwuhmIALAAQAFABADgCQACgCAAgEQAAgGgKAAIgLAAgAyhhKIAAggIgkAAIAAAgIgKAAIAAhHIAKAAIAAAeIAkAAIAAgeIAKAAIAABHgAOgiGIgCgDQAAAAgBAAQAAAAAAgBQAAAAAAAAQAAgBAAAAIABgDIACgDIADgBIADABIACADIABADIgBACIgCADIgDABgAI0iGIgCgDQAAAAAAAAQAAAAAAgBQgBAAAAAAQAAgBAAAAIABgDIACgDIADgBIAEABIACADIABADIgBACIgCADIgEABgAhqiGIgDgDIgBgCIABgDIADgDIADgBIADABIACADIABADIgBACIgCADIgDABgAnliGIgCgDIgBgCIABgDIACgDIADgBIADABIADADIABADIgBACIgDADIgDABg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.urText, new cjs.Rectangle(-123.2,-14.6,246.5,29.3), null);


(lib.t1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Aj4H5IAAjdIApAAIAAAQQAJgKALgFQAKgFAOAAQAUAAAPAKQAQAJAJATQAJARAAAXQAAAWgJASQgJARgQALQgQAKgTAAQgOAAgKgFQgLgFgJgKIAABZgAi/FDQgIAFgEAJQgFAJAAAMQAAALAFAJQAEAKAIAFQAIAFALAAQALAAAIgFQAJgGADgJQAFgJgBgLQABgMgFgJQgDgIgJgGQgIgFgLAAQgLAAgIAFgAJeGwQgIgEgCgFQgEgGAAgIQAAgHAEgFQADgGAHgEQAGgEAGAAQAHAAAHAEQAGAEADAGQADAFAAAHQAAAIgDAGQgDAFgGAEQgGAEgIAAQgHAAgFgEgAgkGpQgSgKgKgSQgKgTAAgUQAAgVAKgTQAKgSARgKQATgKAUAAQAXAAAPAJQASALAJAQQAKAQAAAUIgBASIhqAAQAEAOAKAHQAKAIAQAAQAMAAAKgEQALgDAIgGIATAfQgJAIgTAFQgQAGgUAAQgXAAgTgLgAAjFWQgDgMgJgIQgHgIgOAAQgMAAgKAIQgIAHgCANIBBAAIAAAAgAmYGqQgPgLgJgRQgJgSAAgWQAAgXAJgRQAKgTAOgJQAQgKAUAAQAOAAALAFQAKAFAJAKIAAgQIAqAAIAACUIgqAAIAAgQQgJAKgKAFQgLAFgOAAQgTAAgRgKgAl+FDQgIAGgEAIQgFAJAAAMQAAALAFAJQAEAJAIAGQAIAFALAAQALAAAIgFQAJgGAEgJQAEgJAAgLQAAgMgEgJQgEgIgJgGQgIgFgLAAQgLAAgIAFgAIGGwIAAiUIAqAAIAACUgAGSGwIAAhxIgvAAIAAgjICHAAIAAAjIguAAIAABxgABqGwIAAiUIAqAAIAABxIAwAAIAAhxIAqAAIAABxIAwAAIAAhxIAqAAIAACUgAoGGwIAAhaIhbAAIAABaIgrAAIAAjWIArAAIAABUIBbAAIAAhUIArAAIAADWgAIOEAQgFgDgDgGQgEgGAAgHQAAgFAEgHQADgFAFgEQAHgEAGAAQAGAAAHAEQAGAEADAFQADAFAAAHQAAAIgDAFQgDAGgGADQgGADgHAAQgHAAgGgDgAFnBTQgEgDgCgEQgDgFAAgFQAAgFADgFQACgEAEgDQAGgDAFAAQAEAAAGADQADACADAFQADAEAAAGQAAAGgDAEQgDAFgDACQgFADgFAAQgGAAgFgDgAgTBHQgZgOgOgZQgPgZAAgfQAAgfAPgaQAPgaAYgOQAYgOAfAAQAeAAAaAOQAYAOAPAaQAOAaAAAfQAAAfgOAZQgOAZgZAOQgbAPgdAAQgeAAgZgPgAgEhhQgRALgLATQgKATAAAYQAAAYAKASQALATARAKQARALAXAAQAXAAASgLQASgLAJgSQALgSAAgYQAAgYgLgTQgKgTgRgLQgTgKgWAAQgWAAgSAKgAkLBHQgagPgOgYQgOgZAAgfQAAgfAOgaQAPgZAZgPQAZgOAfAAQAeAAAZAOQAYAOAPAaQAOAYAAAhQABAXgIAQQgHAUgMAOIAdAhIggAAIgPgRQgOAKgQAFQgSAGgQAAQgfAAgZgPgAj8hhQgSALgLATQgKATAAAYQAAAYAKASQALATASAKQASALAXAAQAaAAATgOIgsgxIASgQIAsAwQAIgLADgNQAFgKAAgRQgBgYgJgTQgLgTgSgLQgSgKgWAAQgXAAgSAKgADKBOQgUgIgNgNIAPgVQALAKAQAHQARAGASAAQAOAAAKgEQALgEAFgIQAHgIAAgMQAAgMgIgHQgFgHgMgFQgMgFgQgFQgYgHgLgGQgNgGgJgLQgJgLAAgTQAAgSAJgNQAKgNAQgGQAQgHAXAAQAVAAATAGQATAHANAMIgPAVQgLgJgOgFQgPgFgRAAQgVAAgMAHQgMAIAAAOQAAAJAHAIQAFAGAKAEIAaAJQAXAHAOAHQAOAHAKAMQAKAMAAAVQAAAVgKANQgIAOgSAHQgSAHgWAAQgXAAgVgHgAmJBSIAAjVIAdAAIAADVgANxj6IAAglIh5AAIAAAlIgZAAIAAg+IARAAQAGgGAEgPQADgKABgcIACg+IB0AAIAAB5IAWAAIAAA+gAMalyQgBAZgDAMQgCANgFAIIBIAAIAAhhIg8AAgAgkklQgSgLgKgRQgJgRAAgWQAAgXAJgRQALgSAQgJQARgKAUAAQATAAARAJQARALAJAPQAKAQgBAVIgBANIhxAAQABANAGAKQAHAJAKAGQAMAFAMAAQAMAAAOgFQALgEAIgIIAQATQgIAKgSAHQgSAHgSAAQgXAAgRgKgAArl1QgDgTgMgKQgLgKgRAAQgRAAgMAKQgMAKgCATIBWAAIAAAAgAKmkfIAAiSIAdAAIAACSgAIGkfIAAiSIBBAAQAbAAAOAKQANAKAAASQAAAMgFAIQgFAIgLAEQAOAEAHAJQAHAKAAAMQAAAMgGAJQgGAJgMAGQgNAFgPAAgAIik0IAnAAQAQAAAHgGQAHgFABgLQgBgVgeAAIgnAAgAIilzIAhAAQAPAAAHgFQAIgFAAgLQAAgUgeAAIghAAgAF7kfIAAh6IhJAAIAAB6IgdAAIAAiSICDAAIAACSgADQkfIAAhrIhNBrIgaAAIAAiSIAcAAIAABqIBMhqIAbAAIAACSgAjdkfIAAiSIBBAAQAbAAANAKQAOAKAAASQAAALgGAJQgEAJgLADQANAEAIAJQAGAJABANQAAAMgHAJQgGAKgLAFQgNAFgQAAgAjBk0IAmAAQAQAAAIgGQAHgGAAgKQAAgVgfAAIgmAAgAjBlzIAgAAQAPAAAIgFQAIgFAAgLQAAgUgfAAIggAAgAmYkfIAAiSIAdAAIAACSgAngkfIAAhAIhIAAIAABAIgcAAIAAiSIAcAAIAAA5IBIAAIAAg5IAdAAIAACSgAqMkfIAAiSIAdAAIAACSgArZkfIAAijIhBBnIgTAAIhAhoIAACkIgcAAIAAjWIAcAAIBKB2IBKh2IAdAAIAADWgAldllIAAgZIBiAAIAAAZgACTnQQgKgFgHgKQgHgKgCgPIAWAAQACAMAHAGQAIAGAMAAQAKAAAIgGQAHgGACgMIAWAAQgBAOgHALQgHAKgLAFQgMAGgLAAQgOAAgLgGgAKqnVQgDgBgDgFQgDgFAAgFQAAgEADgFQADgFADgCQAFgCAEAAQAGAAAEACQAEADADAEQACAEAAAFQAAAGgCAEQgDAEgEACQgDADgHAAQgFAAgEgDgAmTnVQgDgBgEgFQgCgFAAgFQAAgEACgFQAEgFADgCQAEgCAFAAQAEAAAGACQAEADACAEQADAFAAAEQAAAFgDAFQgCAEgEACQgEADgGAAQgGAAgDgDgAqHnVQgDgBgEgFQgDgFAAgFQAAgEADgFQADgFAEgCQAFgCAFAAQAEAAAFACQAEADACAEQADAEAAAFQAAAGgDAEQgCAEgEACQgEADgFAAQgGAAgEgDg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1, new cjs.Rectangle(-90.6,-50.4,181.3,101), null);


(lib.r_part = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#34303D").s().p("AhijHQBSAAA5A7QA6A6AABSQAABTg6A6Qg5A7hSAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.r_part, new cjs.Rectangle(-9.9,-20,19.9,40), null);


(lib.logo_veev = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AyaECIhEhDQgEgEgEgCIgJgBIk2AAQhgAAg3gvQgZgUgOgeQgOgeAAghIAAkFQABgMAIgIQAJgIALAAIFiAAQBfAAA4AuQAaAVAOAeQAOAdgBAhIAAB6QAAAMgIAJQgJAHgLABIgKAAQgMAAgIgIQgIgJAAgMIAAh6QAAgRgIgRQgIgRgNgLQgVgRgZgGQgggIgfAAIkzAAQgDAAgDADQgDADAAADIAADWQAAASAHAQQAHAQAPAMQAUARAaAGQAeAIAgAAIFJAAQAJAAAHAEQAJACAGAHIBSBRQAIAJAAALQAAANgIAHIgHAHIAAAAQgJAJgLgBQgMABgIgJgASQC4QgFAAgEgFQgEgEABgGIAAmlQAAgGADgEQAFgDAFAAIE1AAIAAAcIknAAIAAGIIEnAAIAAAdgAL4C4QgGAAgDgFQgEgDgBgHIAAmlQABgGAEgEQAEgDAFAAIE0AAIAAAcIklAAIAAGIIElAAIAAAdgAkCC4QhBAAgxguIgPgOQgHgIgCgMQABgLAHgJIAHgHQAIgIALgBQAMAAAJAIIAPAOQAcAcAoAAIDeAAQAbAAAagGQAUgEARgNQAJgGAEgJQAEgLgBgOQABgOgEgLQgEgKgJgGQgQgMgVgEQgWgFgfAAIi7AAQhXAAgtgjQgVgQgLgXQgKgXAAgZIAAgOQAAgZAKgXQALgWAVgQQAugkBWAAIDLAAQA/AAAuArIAUARQAIAHABANQAAALgHAIIgHAIQgIAIgLABQgMAAgIgIIgUgRQgcgaglABIjMAAQgaAAgdAGQgTAEgSAMQgHAGgFAJQgEAOABAMQgBANAEAMQAFAKAHAGQASANATADQAbAGAcAAIC7AAQBWAAAtAjQAUAQALAWQALAXAAAZIAAAOQABAZgLAXQgLAXgVAPQgsAkhXAAgAtrC4QhgAAg3gvQgZgUgOgeQgOgeABghIAAiCQgBghAOgdQAOgeAZgVQA3guBgAAICzAAQBgAAA3AuQAaAVANAeQAOAdAAAhIAACCQAAAhgOAeQgNAegZAUQg4AvhgAAgAuqi/QgaAHgUAQQgNAMgIAQQgHARAAARIAACCQAAASAHARQAIAQANALQAWARAYAHQAeAHAhABICzAAQAhgBAegHQAZgIAVgQQANgLAIgQQAIgQgBgTIAAiCQABgSgIgQQgGgQgPgMQgVgRgZgGQghgIgeAAIizAAIgDAAQgdAAgfAIgA+RC4QgLAAgJgJQgIgIAAgMIAAmIQAAgLAIgJQAJgIALAAIAKAAQAMAAAJAIQAHAJAAALIAAGJQABALgJAIQgJAJgLAAgAHNC3QgJABgEgJIjCm4IAfAAIADAJICtGFICsmGIACgIIAgAAIjCG4QgDAIgHAAIgCAAgAbcC2QgHgBgCgGIjCm4IAgAAIACAJICsGFICsmGIADgIIAgAAIjBG4QgCAFgEACIgHABIgEgBgATOgaIAAgdIDXAAIAAAdgAM2gaIAAgdIDXAAIAAAdg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.logo_veev, new cjs.Rectangle(-196.5,-26.6,393.1,53.3), null);


(lib.l_part = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#34303D").s().p("AgoCNQg7g6AAhTQAAhSA7g6QA5g7BTAAIAAGPQhTAAg5g7g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.l_part, new cjs.Rectangle(-9.9,-20,19.9,40), null);


(lib.dev_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(0,0,0,0.298)").s().p("ABEASIAAgjIBKAAIAAAjgAgBASIAAgjIAzAAIAAAjgAhOASIAAgjIA+AAIAAAjgAiNASIAAgjIA1AAIAAAjg");
	this.shape.setTransform(-4.5,-3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(0,0,0,0.298)").s().p("AAsASIAAgjIA0AAIAAAjgAggASIAAgjIA9AAIAAAjgAhfASIAAgjIA1AAIAAAjg");
	this.shape_1.setTransform(-9.1,-3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("rgba(0,0,0,0.298)").s().p("AABASIAAgjIA+AAIAAAjgAg9ASIAAgjIA1AAIAAAjg");
	this.shape_2.setTransform(-12.5,-3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("rgba(0,0,0,0.298)").s().p("AgaASIAAgjIA1AAIAAAjg");
	this.shape_3.setTransform(-16.1,-3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},5).to({state:[{t:this.shape_3}]},5).to({state:[]},5).wait(1));

	// Слой_1
	this.instance = new lib.dev();
	this.instance.parent = this;
	this.instance.setTransform(-137.5,-25.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(17));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-137.5,-25.5,275,51);


(lib.btn_txt = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAxAvQgIgFgEgIQgEgHAAgLQAAgLAEgHQAEgHAIgGQAHgEAJAAQAIAAAFADQAGADAEAGIAAgKIAOAAIAABDIgOAAIAAgKQgEAGgGACQgFADgIAAQgJAAgHgEgAA5gEQgFADgDAEQgCAGAAAHQAAAGACAGQADAFAFADQAFADAGAAQAGAAAEgDQAFgDADgFQADgGAAgGQAAgHgDgGQgDgEgFgDQgEgDgGAAQgGAAgFADgAgXAvQgIgEgFgJQgEgIAAgKQAAgKAEgHQAFgJAIgEQAGgFAMAAQAIAAAIADQAHAEAFAGIgJAIQgEgEgFgCQgFgDgEAAQgIAAgEADQgFADgDAEQgDAGAAAHQAAAHADAFQACAFAGADQAFADAHAAQAEAAAFgCQAFgCAEgFIAJAIQgFAHgHADQgHADgIAAQgLAAgIgEgAiQAvQgGgEgFgJQgFgIABgKQgBgKAFgIQAFgIAGgFQAIgEAJAAQAHAAAHADQAFADAEAGIAAgKIANAAIAABDIgNAAIAAgKQgEAGgFACQgHADgHAAQgJAAgIgEgAiIgEQgEADgDAEQgCAFgBAIQABAHACAFQADAFAEADQAFADAHAAQAFAAAGgDQAEgDADgFQACgFABgHQgBgIgCgFQgDgEgEgDQgGgDgFAAQgHAAgFADgADeAyIAAg4IgXAAIAAgLIA8AAIAAALIgXAAIAAA4gACqAyIAAgyIgjAyIgNAAIAAhDIAOAAIAAAwIAjgwIANAAIAABDgAjBAyIAAgtIg0AAIAAAtIgNAAIAAhjIANAAIAAAqIA0AAIAAgqIAOAAIAABjgACOggQgFgCgDgFQgDgEgBgHIAKAAQABAEAEAEQADADAGAAQAFAAADgDQAEgDAAgFIALAAQgBAFgDAGQgDAFgFACQgEADgHAAQgIAAgEgDg");
	this.shape.setTransform(0,-1.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.btn_txt, new cjs.Rectangle(-25.9,-6.7,51.8,10.3), null);


(lib.btn_round = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#34303D").s().p("AiMCNQg7g6AAhTQAAhSA7g6QA6g7BSAAQBTAAA6A7QA7A6AABSQAABTg7A6Qg6A7hTAAQhSAAg6g7g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.btn_round, new cjs.Rectangle(-20,-20,40,40), null);


(lib.btn_bg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#34303D").s().p("AlfDIQhSAAg6g6Qg6g5gBhTIAAgCQABhSA6g6QA6g7BSAAIK+AAQBTAAA6A7QA6A6AABSIAAACQAABSg6A6Qg6A6hTAAg");
	this.shape.setTransform(-0.2,0);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.btn_bg, new cjs.Rectangle(-55.2,-20,110.1,40), null);


(lib.bgImg_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.bgImg();
	this.instance.parent = this;
	this.instance.setTransform(-150,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bgImg_1, new cjs.Rectangle(-150,-300,300,600), null);


(lib.bg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00D1D2").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.bg, new cjs.Rectangle(-150,-300,300,600), null);


(lib.btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// txt
	this.instance = new lib.btn_txt();
	this.instance.parent = this;
	this.instance.setTransform(0,8.9);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(12).to({_off:false},0).to({y:0.7,alpha:1},8).wait(1));

	// r_part
	this.instance_1 = new lib.r_part();
	this.instance_1.parent = this;
	this.instance_1.setTransform(9.2,0,0.909,0.909,0,0,0,0.1,0);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(9).to({_off:false},0).to({regX:0,x:41.1},8,cjs.Ease.get(1)).to({_off:true},1).wait(3));

	// l_part
	this.instance_2 = new lib.l_part();
	this.instance_2.parent = this;
	this.instance_2.setTransform(-9.1,0,0.909,0.909,0,0,0,-0.1,0);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(9).to({_off:false},0).to({regX:0,x:-40.3},8,cjs.Ease.get(1)).to({_off:true},1).wait(3));

	// Слой_5
	this.instance_3 = new lib.btn_bg();
	this.instance_3.parent = this;
	this.instance_3.setTransform(0,0,0.009,0.909);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(9).to({_off:false},0).to({scaleX:0.91},8,cjs.Ease.get(1)).wait(4));

	// Слой_1
	this.instance_4 = new lib.btn_round();
	this.instance_4.parent = this;
	this.instance_4.setTransform(0,0,0.012,0.012);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({scaleX:1.09,scaleY:1.09},5,cjs.Ease.get(1)).to({scaleX:0.91,scaleY:0.91},4,cjs.Ease.quadInOut).to({_off:true},9).wait(3));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-0.2,-0.2,0.5,0.5);


(lib.banner = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// urText
	this.instance = new lib.urText();
	this.instance.parent = this;
	this.instance.setTransform(0,272);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(123));

	// logo
	this.instance_1 = new lib.logo_veev();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-0.2,-256,0.481,0.481,0,0,0,-0.5,-0.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(123));

	// btn
	this.instance_2 = new lib.btn("synched",0,false);
	this.instance_2.parent = this;
	this.instance_2.setTransform(0.2,91.6,1,1,0,0,0,0.1,0.1);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(61).to({_off:false},0).wait(51).to({startPosition:20},0).to({alpha:0},10).wait(1));

	// dev
	this.instance_3 = new lib.dev_1("single",0);
	this.instance_3.parent = this;
	this.instance_3.setTransform(290,7);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(51).to({_off:false},0).to({x:0},10,cjs.Ease.cubicOut).wait(16).to({mode:"synched",loop:false},0).wait(35).to({startPosition:16},0).to({x:-290},10,cjs.Ease.cubicIn).wait(1));

	// t1
	this.instance_4 = new lib.t1();
	this.instance_4.parent = this;
	this.instance_4.setTransform(0,160.8);
	this.instance_4.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({alpha:1},10).wait(30).to({alpha:0},10).wait(1).to({y:-110},0).to({alpha:1},10).wait(51).to({alpha:0},10).wait(1));

	// V
	this.instance_5 = new lib.V();
	this.instance_5.parent = this;
	this.instance_5.setTransform(0,27);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(40).to({_off:false},0).to({alpha:1},10).wait(62).to({alpha:0},10).wait(1));

	// bg
	this.instance_6 = new lib.bg();
	this.instance_6.parent = this;
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(40).to({_off:false},0).to({alpha:1},10).wait(62).to({alpha:0},10).wait(1));

	// bgImg
	this.instance_7 = new lib.bgImg_1();
	this.instance_7.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(123));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,-300,300,600);


// stage content:
(lib._300x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// cover
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#666666").ss(2,2,0,3).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// banner
	this.instance = new lib.banner();
	this.instance.parent = this;
	this.instance.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(149,299,302,602);
// library properties:
lib.properties = {
	id: '0A6E3F5DF6B342F4AF907DBE848CDF8D',
	width: 300,
	height: 600,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/bgImg.jpg", id:"bgImg"},
		{src:"images/dev.png", id:"dev"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['0A6E3F5DF6B342F4AF907DBE848CDF8D'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;