(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 300,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	manifest: [
		{src:"images/bgImg.jpg", id:"bgImg"},
		{src:"images/camry.png", id:"camry"},
		{src:"images/corolla.png", id:"corolla"},
		{src:"images/gradient.png", id:"gradient"},
		{src:"images/img1.png", id:"img1"},
		{src:"images/img2.png", id:"img2"},
		{src:"images/l.png", id:"l"},
		{src:"images/prado.png", id:"prado"},
		{src:"images/pradoWhite.png", id:"pradoWhite"},
		{src:"images/rav4.png", id:"rav4"},
		{src:"images/toyotaLogo.png", id:"toyotaLogo"}
	]
};



// symbols:



(lib.bgImg = function() {
	this.initialize(img.bgImg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.camry = function() {
	this.initialize(img.camry);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,221,161);


(lib.corolla = function() {
	this.initialize(img.corolla);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,216,155);


(lib.gradient = function() {
	this.initialize(img.gradient);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,380,379);


(lib.img1 = function() {
	this.initialize(img.img1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,267);


(lib.img2 = function() {
	this.initialize(img.img2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,284);


(lib.l = function() {
	this.initialize(img.l);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,80,55);


(lib.prado = function() {
	this.initialize(img.prado);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,216,179);


(lib.pradoWhite = function() {
	this.initialize(img.pradoWhite);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,216,179);


(lib.rav4 = function() {
	this.initialize(img.rav4);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,212,168);


(lib.toyotaLogo = function() {
	this.initialize(img.toyotaLogo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,256,63);


(lib.urText = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAYDpIgIgCIABgKIAJACIAHAAQAGAAADgCQAEgDABgFIADgIIgGAAIgJgBIgGgEIgEgGIgDgJIgNgxIAMgDIANAxIACAGIACADIAEADIAFABIAGgBIAQg9IALADIgUBNIgEAKIgGAGIgIAEIgJAAIgJAAgAHKDGIgFACIgFADIgHACIgIAAIgJgBIgIgEQgEgCgCgEQgCgFAAgFQAAgGADgFQACgDADgDQAEgDAFgCIAKgBIATAAIAAgCQAAgKgDgDQgEgDgIAAIgKAAIgLADIgEgKIAMgCIAOgBQAJAAAFACQAFACADADQADADABAGQABAFAAAHIAAAcIAGAJIgJAHgAGpCuQgDADAAAGIAAAFIAEAEIAFADIAFAAQAGAAAFgDIAIgEIAAgRIgTAAQgGAAgFADgAF/DGQgFADgHACQgGACgHAAQgHAAgFgCQgFgCgDgEQgDgDgCgGQgBgEAAgFIAAgsIANAAIAAArQAAAJAEADQAEAFAHAAQAGAAAFgDIAJgEIAAg1IANAAIAAA2IAFAJIgJAHgAErDLQgCgDAAgEQAAgFACgDQACgBAFAAQAFAAACABQADADgBAFQABAEgDADQgCACgFAAQgFAAgCgCgAENDGIgFACIgGADIgGACIgIAAIgKgBIgIgEQgDgCgCgEQgCgFAAgFQAAgGADgFQACgDADgDQAEgDAFgCIAKgBIATAAIAAgCQAAgKgDgDQgEgDgIAAIgKAAIgMADIgDgKIALgCIAPgBQAJAAAFACQAFACADADQADADABAGIABAMIAAAcIAGAJIgJAHgADsCuQgEADAAAGQAAADABACIADAEIAGADIAEAAQAHAAAFgDIAIgEIAAgRIgUAAQgGAAgEADgABqDLQgHgEgEgEQgEgFgBgHQgCgHAAgHQAAgIACgHQACgGAEgFQAEgFAHgDQAGgCAJAAQAIAAAHACQAGADAEAFQAFAFACAGQACAHAAAIQAAAHgCAHQgCAHgEAFQgEAEgHAEQgHACgIAAQgKAAgGgCgABqCVQgGAHAAANQAAANAGAGQAGAHAKAAQAKAAAFgHQAGgGAAgNQAAgNgGgHQgFgGgKAAQgKAAgGAGgAguDLQgHgEgEgEQgEgFgBgHQgCgHAAgHQAAgIACgHQACgGAEgFQAEgFAHgDQAGgCAJAAQAJAAAGACQAGADAEAFQAFAFAAAGQACAHAAAIQAAAHgCAHQAAAHgEAFQgEAEgHAEQgHACgJAAQgJAAgGgCgAguCVQgGAHAAANQAAANAGAGQAGAHAKAAQAKAAAFgHQAGgGAAgNQAAgNgGgHQgFgGgKAAQgKAAgGAGgAiUDLQgCgDAAgEQAAgFACgDQADgBAEAAQAFAAACABQADADgBAFQABAEgDADQgCACgFAAQgEAAgDgCgAjGDMQgFgBgEgDQgFADgFABQgFABgFAAQgGAAgFgBQgEgBgCgDIgEgGIgCgHIgGgzIAOgBIAEAyIACAFIADADIAEACIAEAAIAGgBIAFgDIAAg4IAMAAIAAA4IAGADIAGABIADAAIAFgCIADgDIABgFIAGgyIAMABIgGAzIgBAHIgEAGQgDADgEABQgEABgGAAQgFAAgFgBgAkyDMIgJgEIgJAEQgFABgGAAQgGAAgEgBQgEgBgDgDIgEgGIgCgHIgFgzIANgBIAFAyIACAFIADADIAEACIAEAAIAGgBIAFgDIAAg4IAMAAIAAA4IAFADIAGABIAEAAIAEgCIADgDIACgFIAFgyIAMABIgFAzIgCAHIgEAGQgDADgEABQgEABgGAAQgFAAgFgBgAmdDMIgJgEIgKAEQgFABgFAAQgHAAgDgBQgFgBgCgDIgFgGIgBgHIgFgzIAMgBIAGAyIABAFIADADIAEACIAEAAIAGgBIAFgDIAAg4IANAAIAAA4IAEADIAHABIADAAIAEgCIADgDIACgFIAGgyIAMABIgFAzIgCAHIgEAGQgEADgEABQgDABgGAAQgGAAgEgBgAC7DMQgFgBgCgDQgDgDgCgEQgCgEAAgHIAAgmIgKAAIAAgJIAKAAIAAgUIANAAIAAAUIAWAAIAAAJIgWAAIAAAkQAAAIACADQAEAEAGAAIAHgBIAGgCIADAKIgJACIgJABIgJgBgAhhDMQgEgBgDgDIgEgHQgCgEAAgHIAAgmIgKAAIAAgJIAKAAIAAgUIAMAAIAAAUIAYAAIAAAJIgYAAIAAAkQAAAIADADQAEAEAFAAIAHgBIAHgCIACAKIgJACIgJABIgJgBgAEABAIAAhTIgFgMIALgEIAFAHIAKgFQAFgCAHAAQAPAAAIAJQAIALAAAPQAAAIgCAHQgCAHgEAFQgFAFgHADQgHACgIAAIgIAAIgJgCIAAAdgAEWgWIgKAEIAAArIAIACIAKAAIAIgBQAEgCACgEQADgCACgGQACgEgBgIIAAgKQgCgFgCgCQgDgEgEgCIgIgBQgFABgEABgAI5AeIgKAFQgFADgIgBIgKgBIgIgDQgEgDgCgEQgBgEAAgFQAAgGABgFQADgEAEgCQAEgCAFgCIAKgBIASAAIAAgEQAAgIgDgEQgEgDgJAAIgKAAIgKAEIgEgJIAMgEQAGgBAIgBQAJAAAFACQAFACADAEIAEAJIABAKIAAAeIAGAIIgJAHgAIaAHQgEACAAAHIABAFQAAABABAAQAAABAAAAQABABAAAAQAAAAABABQAAAAABAAQABABAAAAQABAAAAAAQABABAAAAIAGAAQAGAAAEgCIAIgFIAAgRIgSAAQgGABgEADgAF9AeIgKAFQgGADgHgBIgKgBQgFgBgDgCQgEgDgCgEQgCgEAAgFQAAgGACgFQADgEAEgCQADgCAFgCIAKgBIASAAIAAgEQAAgIgDgEQgEgDgIAAIgKAAIgLAEIgDgJIALgEQAGgBAJgBQAIAAAFACQAFACAEAEIADAJIABAKIAAAeIAGAIIgJAHgAFeAHQgEACgBAHIACAFIADAEQAAAAABAAQABABAAAAQABAAAAAAQABABAAAAIAGAAQAGAAAEgCIAIgFIAAgRIgSAAQgGABgEADgAASAeIgKAFQgFADgHgBIgJgBQgFgBgDgCQgDgDgCgEQgCgEAAgFQAAgGACgFQACgEAEgCIAIgEIAKgBIARAAIAAgEQAAgIgEgEQgDgDgIAAIgIAAIgMAEIgDgJIALgEQAGgBAHgBQAIAAAGACQAFACADAEQADADABAGQABAFAAAFIAAAeIAGAIIgJAHgAgLAHQgFACAAAHQABADABACQAAABABAAQAAABAAAAQABABAAAAQAAAAABABQAAAAABAAQABABAAAAQABAAAAAAQABABAAAAIAGAAQAEAAAEgCIAIgFIAAgRIgQAAQgHABgDADgAiWAjQgHgDgEgFQgDgFgCgHQgCgGAAgJQAAgFACgHQACgHAEgFQAEgFAHgDQAGgDAJAAQAJAAAHADQAGADAEAFQAEAFACAHQACAHAAAFQAAAIgCAHQgCAHgEAFQgEAFgGADQgHACgJAAQgJAAgHgCgAiWgRQgGAGABALQgBANAGAHQAGAHAKAAQAKAAAGgHQAFgHAAgNQAAgLgFgGQgGgHgKAAQgKAAgGAHgAk1AjQgHgDgEgFQgEgFgBgHQgCgGgBgJQABgFACgHQACgHAEgFQAFgFAGgDQAGgDAJAAQAJAAAGADQAHADADAFQAFAFACAHQACAHAAAFQAAAIgCAHQgCAHgEAFQgEAFgHADQgGACgKAAQgIAAgHgCgAk1gRQgFAGAAALQAAANAFAHQAFAHALAAQAKAAAFgHQAGgHAAgNQAAgLgGgGQgFgHgKAAQgLAAgFAHgADRAFIgJAAIAAAeIgMAAIAAhEIAMAAIAAAcIAGAAIAEgBIACgCIANgSIAFgFQACgCAEAAIAEAAIADABIgBAKIgBAAIgBAAIgEAAIgDAEIgLAQIgBABIgBABIAZAcIgJAIgAB0AkIgGgBIACgKIAEAAIAGABIAEgBIAFgBIADgEIADgFIABgDQgHAAgFgEQgGgDgCgFIgUg6IAMgEIATA3QACAGADABQAEAAAFAAIAVg+IANAEIgaBIIgFALIgGAHIgIADQgEACgGgBIgGAAgAHsAjIAAgfIgiAAIAAAfIgMAAIAAhEIAMAAIAAAcIAiAAIAAgcIANAAIAABEgAGeAjIAAg6IgJAAIAAgKIAVAAIAABEgAhHAjIAAg5IgZAAIAAgLIA+AAIAAALIgYAAIAAA5gAjFAjIAAgrIgiAhIAAAKIgMAAIAAhEIAMAAIAAArIAighIAAgKIANAAIAABEgAlrAjIAAhVIgfAAIAAgLIBMAAIAAALIggAAIAABVgAoZAjIAAhgIANAAIAABggAo8AjIAAhgIAOAAIAABggApdAjIAAhVIgxAAIAABVIgNAAIAAhgIBLAAIAABggAJ5AQIASgNIAFgDIAAAAIAAgEIgFgDIgTgMIAHgJIAUANIAHAGQADADAAAFQAAACgDAEIgIAGIgTAOgAJYAQIASgNIAEgDQAAAAABAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQgBAAAAgBIgEgDIgSgMIAGgJIAUANIAHAGQADADAAAFQAAACgEAEIgIAGIgSAOgAmxALIgHgGQgDgCAAgDQAAgFADgDIAIgHIATgNIAGAJIgSAMIgFADIgBADIABABIAFADIATAOIgHAIgAnTALQgEgDgDgDQgDgCABgDQAAgFACgDIAIgHIATgNIAHAJIgSAMIgFADIgBADQAAAAAAABQAAAAAAAAQABAAAAAAQAAAAAAAAIAFADIASAOIgGAIgAAwAAIAAgLIArAAIAAALgAjmgwQgHgFgCgJIALgDQABAFAEAEQAEADAGAAQAHAAAEgDQADgEACgFIAKADIgDAJQgCADgEACQgDACgFACIgJAAQgKAAgHgEgAGqgvQgCgEAAgCQAAgEACgDQACgDAEAAQAEAAADADQACADAAAEQAAACgCAEQgDACgEAAQgEAAgCgCgAGLgvQgBgEAAgCQAAgEABgDQADgDAEAAQAEAAACADQACADAAAEQAAACgCAEQgCACgEAAQgEAAgDgCgALQhlIAAhWIgEgLIAMgFIADAHIAKgEQAGgCAHAAQAPAAAHAJQAJAKAAARQAAAJgDAGQgCAIgEAEQgEAGgHACQgHADgJAAIgHAAIgJgCIAAAdgALmi9IgJADIAAAsIAHACIAKABIAIgBQAEgCADgDQADgDACgFQABgFABgIQgBgHgBgFQgBgFgDgDQgDgDgDgBIgIgBQgGAAgEACgADNhlIAAhWIgFgLIAMgFIAEAHIAKgEQAGgCAGAAQAPAAAIAJQAIAKABARQgBAJgCAGQgCAIgEAEQgFAGgGACQgIADgIAAIgIAAIgJgCIAAAdgADii9IgJADIAAAsIAIACIAJABIAIgBQAFgCADgDQACgDACgFQACgFAAgIQAAgHgCgFQgBgFgCgDQgDgDgEgBQgEgBgEAAQgFAAgFACgAqBhlIAAgbQgLgBgHgDQgHgDgFgFQgFgFgCgGQgCgHAAgGQAAgIADgGQACgHAFgEQAFgFAHgDQAHgDAKgBIAAgcIAMAAIAAAcQAKABAHADQAHADAFAFQAFAEACAHQACAGAAAIQAAAGgCAHQgDAGgEAFQgEAEgHAEQgIACgKACIAAAbgAqVi2QgHAGABAMQgBALAHAHQAGAGAOABIAAgzQgOAAgGAIgAp1iLQANgBAGgGQAGgHAAgLQAAgYgZgCgAgdhyIAAgRIgzAAIAAAPIgMAAIAAgaIAIAAIAFgIQADgFABgGIACgIIABgJIAAgKIAAgMIAuAAIAAA6IAIAAIAAAcgAg+ifIgEAKIgFAHIAgAAIAAgvIgVAAQAAARgCANgAnkhyIAAgRIg4AAIAAhFIAMAAIAAA6IAiAAIAAg6IANAAIAAA6IAJAAIAAAcgAKPiDQgHgDgEgFQgEgEgBgIQgCgGAAgJQAAgHACgGQACgIAEgEQAFgGAGgCQAGgDAJAAQAJAAAGADQAGACAEAGQAFAEACAIQACAGAAAHQAAAIgCAHQgCAHgEAFQgEAFgHADQgGADgJAAQgJAAgHgDgAKPi5QgFAHgBAMQABANAFAIQAGAGAKAAQAKAAAFgGQAGgIAAgNQAAgMgGgHQgFgHgKABQgKgBgGAHgAIDiDQgGgCgEgEQgDgEgCgHQgDgFAAgHIgOAAIAAAdIgNAAIAAhFIANAAIAAAeIAOAAQABgIACgGQACgFAEgFQAEgDAGgCQAGgDAIAAQAJAAAGADQAGACAEAGQAEAEABAIQACAGABAHQAAAIgCAHQgBAHgEAFQgFAFgGADQgGADgJAAQgJAAgGgDgAICi5QgEAHAAAMQAAANAEAIQAGAGAKAAQAKAAAFgGQAEgIAAgNQAAgMgEgHQgFgHgKABQgKgBgGAHgAF6iDQgHgDgDgGQgEgGgCgHQgCgIAAgKQAAgKABgHQABgIAEgHQADgGAGgFQAFgEAIgCIAIgCIAHgCIAFgCIADgHIALAEIgBAFIgCAEIgCADIgDACIgDABIgFACIgGABIgGACIgIADIgHAEQgDADAAAEIgCAJIAKgHQAHgCAHgBQAIAAAGACQAGAEAEADQADAFABAFQACAGAAAHQAAAHgCAHQgCAGgEAFQgEAGgGACQgIADgIAAQgKAAgGgDgAGFi4IgGADIgGACIgDAEIAAAEIAAACIAAALIADAKQADAEAEACQAEADAGAAQALABAFgHQAGgGgBgMQAAgWgUAAIgGABgABWiDQgHgCgFgGQgEgFgBgGQgCgHgBgHQAAgJADgGQACgHAFgFQAEgGAHgCQAHgDAIAAQAJAAAGACIAKADIgDAJIgLgCIgKgBQgFAAgFACQgEABgDAEQgDAEgCAEQgBAGAAAGQAAAMAGAHQAFAGALAAIALgBIALgDIAEAKIgMADQgGACgIAAQgKAAgGgDgAr3iEQgJgFgFgGQgGgIgDgJQgCgKAAgJQAAgLACgIQADgKAGgHQAGgGAJgFQAIgEAMgBQAMABAJAEQAJAFAFAGQAFAHAEAKQACAIAAALQAAAJgDAKQgCAJgGAIQgFAGgKAFQgIAEgMAAQgMAAgJgEgArwjYQgGADgEAGQgEAFgCAHQgCAHAAAJQAAAIACAIQACAHAEAFQAEAFAGAEQAGADAIAAQAIAAAGgDQAGgEAEgFQAEgFACgHQACgIAAgIQAAgJgCgHQgCgHgEgFQgEgGgGgDQgGgEgIAAQgIAAgGAEgAJSiDIAAg6IgYAAIAAgLIA+AAIAAALIgYAAIAAA6gAFMiDIAAgtIgjAjIAAAKIgMAAIAAhFIAMAAIAAAtIAjgjIAAgKIAMAAIAABFgACciDIAAg6IgYAAIAAgLIA+AAIAAALIgYAAIAAA6gAAmiDIAAgtIgiAjIAAAKIgLAAIAAhFIALAAIAAAtIAigjIAAgKIANAAIAABFgAiPiDIAAgtIgiAjIAAAKIgMAAIAAhFIAMAAIAAAtIAigjIAAgKIANAAIAABFgAjeiDIAAgtIgiAjIAAAKIgMAAIAAhFIAMAAIAAAtIAigjIAAgKIAOAAIAABFgAksiDIAAgeIgiAAIAAAeIgNAAIAAhFIANAAIAAAcIAiAAIAAgcIANAAIAABFgAl7iDIAAgtIgiAjIAAAKIgNAAIAAhFIANAAIAAAtIAigjIAAgKIANAAIAABFgAnKiDIAAg7IgIAAIAAgKIAVAAIAABFgAo8iDIAAg7IgIAAIAAgKIAVAAIAABFgAG5i9IAAgoIAMAAIAAAogAiwjXQgHgFgCgJIALgEQABAFAEAEQAEADAGAAQAHAAAEgDQADgEACgFIAKAEIgDAHQgCAEgEADIgIADIgJABQgKAAgHgEgAmcjXQgHgFgCgJIAKgEQACAFAEAEQAEADAGAAQAHAAADgDQAEgEACgFIAKAEQgBAEgDADQgBAEgEADIgIADIgJABQgKAAgHgEgAnKjXQgDgCAAgEQAAgDADgDQACgDAEAAQAEAAACADQACADABADQgBAEgCACQgCADgEAAQgEAAgCgDgAo9jXQgDgCABgEQgBgDADgDQACgDAFAAQAEAAACADQACADAAADQAAAEgCACQgCADgEAAQgFAAgCgDg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-78.5,-23.4,157.1,46.8);


(lib.toyotaP2 = function() {
	this.initialize();

	// Слой 4 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AmdG3IAAttIM8AAIAANtg");
	mask.setTransform(-141.5,-13);

	// Слой 2
	this.instance = new lib.toyotaLogo();
	this.instance.setTransform(-166,-44);

	this.instance.mask = mask;

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-166,-44,66,63);


(lib.toyotaP1 = function() {
	this.initialize();

	// Слой 3 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AviFtIAArYIfFAAIAALYg");
	mask.setTransform(-2.5,-11.4);

	// Слой 2
	this.instance = new lib.toyotaLogo();
	this.instance.setTransform(-166,-44);

	this.instance.mask = mask;

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-102,-44,192,63);


(lib.t3_2 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AivDPQgOgFgKgMQgJgLgFgPQgEgPAAgSQAAgRAFgQQAGgPAKgLQALgMAPgFQAPgGAVAAQAQAAAMADIAZAIIgKAbIgPgGIgKgCIgTgCQgWAAgNAOQgMAOAAAaQAAAcAMANQANAOAWAAIALgBIAVgFIAOgGIAKAaIgOAGIgOAEIgOADIgQABQgXAAgPgHgAkTClIg+AAIgOAxIghgIIAmh+QADgJADgFQAEgGAEgDQAFgEAGgCQAHgCAJAAQAKAAAGACQAGABAFAEQADAEAEAGIAFANIAnB/IghAIgAkbCJIgPg1IgDgFQgCgCgDAAQgBAAAAAAQgBAAgBAAQAAABgBAAQAAAAgBABQgCABgBAEIgQA1IAvAAgAHrDSIAAhcIg9BGIAAAWIgiAAIAAieIAiAAIAABdIA9hEIAAgZIAiAAIAACegAFMDSIAAhCIhAAAIAABCIgiAAIAAieIAiAAIAAA/IBAAAIAAg/IAiAAIAACegACqDSIAAhcIg+BGIAAAWIgiAAIAAieIAiAAIAABdIA+hEIAAgZIAiAAIAACegAgWDSIAAiCIgvAAIAAgcIB9AAIAAAcIgvAAIAACCgAm0DSIAAg5IgQACIgSACQgYAAgMgIQgNgHgEgRIgDgJIAAhAIAiAAIAAA4IACAHQACAHAGADQAFACAMAAIAQgBIANgDIAAhHIAiAAIAACegAFhg2QgQgHgIgKQgKgMgEgPQgFgPABgSQgBgRAGgPQAFgRALgJQAKgLAQgHQAPgGAUAAQARAAAMAEQAOADAKAEIgKAbIgZgIIgJgCIgJAAQgXAAgMAPQgNAOAAAZQAAAbANAOQANANAVAAIAMAAIAVgFIANgGIALAaIgcAKIgPADIgQABQgWAAgPgGgAD8hhIg+AAIgOAwIghgGIAnh/QADgIADgFQACgFAFgFQAGgEAFgCQAHgCAKAAQAKAAAFACQAIACADAEQAFAEADAFIAEAMIAnCBIghAGgAD0h9IgOg1IgEgGQgCgBgCAAQgBAAgBAAQgBAAAAAAQgBABAAAAQgBAAAAAAQgCACgBAEIgQA1IAuAAgAhDhhIg+AAIgOAwIghgGIAnh/IAFgNQACgEAGgGQAFgEAGgCQAGgCAKAAQAKAAAGACQAIADADADQAFAEACAFIAFAMIAnCBIghAGgAhKh9IgPg1QgCgEgCgCQAAAAgBAAQAAAAgBgBQAAAAgBAAQgBAAgBAAQAAAAgBAAQgBAAAAAAQgBABAAAAQgBAAAAAAQgCACgCAEIgPA1IAvAAgAmWhhIg/AAIgPAwIgfgGIAmh/IAFgNQACgEAGgGQAEgEAIgCQAGgCAJAAQAKAAAGACQAIADADADQADADAEAGIAFAMIAnCBIgiAGgAmeh9IgQg1QgBgEgCgCQgBAAAAAAQgBAAAAgBQgBAAAAAAQgBAAgBAAIgEABIgEAGIgPA1IAvAAgAkcg2QgQgFgKgIIAPgYIAKAGIALAFQAGACAHAAIALABIALgBIAKgDQAEgDADgFQACgEAAgFIgBgJQgCgEgDgCQgDgDgGgBQgFgCgKAAIgdAAIAAgbIAcAAQAGAAAHgCQAFgCADgDQADgEABgDIABgHQAAgKgHgEQgHgFgKAAQgKABgKADIgVAJIgOgYIAKgFIAOgFIAPgFIAUgBQAPAAAJADQAKAEAHAFQAHAHACAGQADAJAAAJQAAAMgGAIQgGALgMAFQAOADAHAJQAJAKgBAPQAAALgDAIQgEAIgIAIQgIAFgMAEQgLAEgQAAQgUAAgPgFgAJ5g0IAAieIAhAAIAACegAI4g0IAAhCIhAAAIAABCIgiAAIAAieIAiAAIAAA/IBAAAIAAg/IAiAAIAACegABcg0IAAiCIg+AAIAACCIgfAAIAAieIB/AAIAACegAo3g0IAAhCIhAAAIAABCIgiAAIAAieIAiAAIAAA/IBAAAIAAg/IAiAAIAACeg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-66.6,-21.4,133.3,42.9);


(lib.t3_1 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AF7BgIAAggIhnAAIAAicIAhAAIAACAIA7AAIAAiAIAhAAIAACAIAMAAIAAA8gAkjA+QgRgGgJgKQgKgKgGgQQgFgRAAgQQAAgRAGgPQAFgPAKgLQALgMAPgGQAPgGAVAAQAOAAAQAEIAYAIIgKAaIgXgHIgKgCIgKgBQgUAAgMALQgMAKgEAUIA+AAIAAAaIg+AAQAEAUAMAJQALAKAVAAIALAAIALgCIAXgIIAKAaQgLAGgPADQgOAEgQAAQgVAAgPgGgAL1BAIAAhZIg+BDIAAAWIghAAIAAicIAhAAIAABcIA+hDIAAgZIAhAAIAACcgAJVBAIAAhAIhAAAIAABAIgiAAIAAicIAiAAIAABAIBAAAIAAhAIAiAAIAACcgAGzBAIAAicIAiAAIAACcgACnBAIAAicIAiAAIAACcgABnBAIAAhAIhAAAIAABAIgiAAIAAicIAiAAIAABAIBAAAIAAhAIAiAAIAACcgAg4BAIAAheIgRAdQgHAKgHAFQgGAEgIgBQgIAAgHgEQgGgEgHgKIgQgdIAABeIghAAIAAicIAfAAIApBJIADAEIADABIADgBIADgEIAohJIAeAAIAACcgAmLBAIAAhZIg+BDIAAAWIghAAIAAicIAhAAIAABcIA+hDIAAgZIAhAAIAACcgAp2BAIAAicIA9AAQALAAALADQAKADAIAGQAHAGAFAKQAEALAAANQAAAMgEAKQgEAKgIAGQgIAFgKAEQgKADgNAAIgbAAIAAA2gApVgQIAYAAIAKgBQADgBAFgCQAEgDACgFQADgFAAgHQAAgJgCgEQgCgEgEgEIgJgDIgKgBIgYAAgAq2BAIAAh/Ig9AAIAAB/IgiAAIAAicICBAAIAACcg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-79,-9.6,158.1,19.3);


(lib.t1 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("ABWJIQgZgLgPgUQgQgTgGgaQgHgYAAgcQAAgbAHgZQAIgbAPgSQAQgUAZgMQAagLAhAAQAkAAAZALQAZAMAQAUQAOASAIAbQAGAYABAcQAAAcgIAYQgHAagQATQgQAUgYALQgYAMgkAAQgjAAgagMgABzFzQgNAHgJANQgIAMgFARQgEASAAASQAAARAEATQAFASAIALQAKANAMAGQAOAIASAAQATAAAOgIQANgGAIgNQAJgMAFgRQADgQAAgUQAAgVgDgPQgEgQgKgNQgHgMgOgIQgOgHgTAAQgSAAgOAHgAm1JIQgYgLgQgUQgQgUgGgZQgHgaAAgaQAAgbAHgZQAIgaAQgTQAPgUAZgMQAZgLAiAAQAkAAAaALQAZAMAPAUQAQAUAGAZQAHAZAAAbQAAAbgHAZQgHAZgRAUQgPAUgZALQgYAMgkAAQgkAAgZgMgAmYFzQgNAIgJAMQgJAOgDAPQgFARAAATQAAATAFARQADAQAJANQAKANAMAGQAOAIASAAQATAAAOgIQAMgGAKgNQAIgLAFgSQAEgTAAgRQAAgSgEgSQgFgRgIgMQgJgMgNgIQgPgHgSAAQgSAAgOAHgAKoIBIhqAAIgYBTIg3gNIBBjWQAEgNAFgKQAFgKAJgHQAGgGANgEQALgDARAAQAPAAALADQAMAEAGAGQAIAHAEAJQAFAGAEAPIBBDZIg4ANgAKaHSIgZhaQgDgIgCgCQgFgDgDAAQgGAAgCADQgDADgDAHIgbBaIBPAAgAFyJOIAAjeIhQAAIAAgwIDZAAIAAAwIhRAAIAADegAiOJOIAAhbQgQgFgJgMQgJgLgJgVIgzhxIAygVIA4B6QAEAHAEAEQAEADAEAAQAHAAACgDQAEgDAEgJIA5h5IAwAVIgyBuQgIASgLAPQgKANgPAGIAABbgAqPJOIAAjeIhQAAIAAgwIDZAAIAAAwIhRAAIAADegABHC6IAAg1IiNAAIAAA1Ig5AAIAAhkIAbAAQAEgFAHgMQAHgMADgKQADgKAEgTQADgSACgQIANh2ICiAAIAADcIAUAAIAABkgAgMgCQgDAbgGAZQgGAVgJAPIBXAAIAAisIg0AAgAF6BhIAegUIAGgFIAGgMQAEgLAAgLIAVisICnAAIAAELIg5AAIAAjbIg7AAIgQCBQgCATgDANQgFAPgIALQgLANgKAHQgOALgWALgAlGCAQgZgLgQgUQgPgUgGgZQgHgZAAgbQAAgcAHgXQAIgaAPgTQAQgTAZgMQAYgMAjAAQAjAAAaAMQAZAMAQATQAPAUAGAZQAIAXAAAcQAAAZgIAbQgIAagPATQgQAUgYALQgZAMgjAAQgkAAgZgMgAkphTQgOAHgIAMQgJAOgEAQQgEAOAAAUQAAAUAEAPQAEARAJAMQAJANANAHQANAHATAAQATAAAOgHQAMgGAJgOQAIgKAGgTQADgSAAgRQAAgRgDgRQgFgSgJgMQgJgMgMgHQgPgHgSAAQgSAAgOAHgAKZCFIAAkLIA4AAIAAELgAClCFIAAkLIDCAAIAAAvIiLAAIAAA6IBrAAIAAAuIhrAAIAABFICNAAIAAAvgAnrCFIAAiiIgcAvQgMAWgMAHQgLAHgNAAQgNAAgMgIQgMgIgLgUIgcgvIAACiIg3AAIAAkLIA0AAIBHB8IAEAHQACACAEAAQACAAACgCIAFgHIBGh8IAyAAIAAELgAD0kMIAAg1IiPAAIAAA1Ig4AAIAAhlIAaAAQAGgGAGgLQAFgJAEgNQAFgMADgQQACgMADgZIANh2ICkAAIAADeIAUAAIAABlgACgnLQgEAegFAYQgGAVgKAPIBaAAIAAiuIg3AAgAydlmIAWgOIAIgFIAFgGIAGgMQADgGACgQIAUiuICnAAIAAEOIg5AAIAAjeIg6AAIgQCDQgDATgDAOQgEAOgIAMQgIAKgOAKQgMAJgYANgAH3mOIhrAAIgZBTIg2gNIBBjWQAEgOAFgJQAGgKAIgHQAHgGAMgEQALgDAQAAQAQAAALADQAJADAJAHQAHAGAGAKQAFAJADAMIBCDZIg4ANgAHom9IgZhaQgCgIgDgCQgEgDgEAAQgFAAgDADQgDACgDAIIgbBaIBPAAgARllBIAAkOIA5AAIAAEOgAP4lBIAAhxIhtAAIAABxIg6AAIAAkOIA6AAIAABsIBtAAIAAhsIA5AAIAAEOgAJllBIAAkOIBnAAQARAAAUAFQASAGAMAKQANAKAIARQAHASAAAXQAAAUgHARQgIAQgNAMQgLAKgTAHQgTAGgVAAIgtAAIAABdgAKcnNIApAAQAJAAAIgCQAGgBAIgFQAHgGADgHQAFgIAAgMQAAgNgFgJQgDgIgHgFQgGgFgIgBIg6gCgAgolBIAAhxIhtAAIAABxIg5AAIAAkOIA5AAIAABsIBtAAIAAhsIA4AAIAAEOgAm7lBIAAkOIDCAAIAAAwIiKAAIAAA5IBrAAIAAAwIhrAAIAABFICMAAIAAAwgAqSlBIAAkOIC4AAIAAAwIh/AAIAADegAuAlBIAAkOIDCAAIAAAwIiKAAIAAA5IBqAAIAAAwIhqAAIAABFICNAAIAAAwg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-118.2,-59.7,236.5,119.4);


(lib.Symbol1 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AGDA3IAAgSIhZAAIAAhZIANAAIAABPIAcAAIAAhPIANAAIAABPIAcAAIAAhPIAMAAIAABPIAIAAIAAAcgAhAA3IAAgSIg2AAIAAASIgMAAIAAgbIAGAAIAFgHQACgEACgFIADgLIAGg1IAwAAIAABQIAHAAIAAAbgAhoANIgDAIIgDAHIAnAAIAAhGIgZAAgAENAIIgkAAIgKAfIgKgCIAZhNQABgFADgFQADgDAGAAIAGAAIAEACIADAEIACAHIAaBNIgNACgAELAAIgNgnIgBgDIgCgBIgCABIgBADIgMAnIAfAAgAlbAIIgkAAIgKAfIgKgCIAYhNQADgHACgDQADgDAGAAIAGAAIAEACIADAEIAbBUIgMACgAleAAIgMgnIgBgDIgCgBIgCABIgOAqIAfAAgAnNAlIgMgHIAFgIQAGAEAFACQAIACAGAAQAKAAAFgEQAFgGAAgIIgBgHQgBgDgCgCQgDgBgDgBQgEgBgGAAIgOAAIAAgKIANAAQAGABADgCIAGgEIADgFIABgGQAAgIgFgEQgEgDgIAAIgMABIgLAEIgEgHIALgFIASgDQAIAAAFACQAGACACACQAEADABAFQACADAAAGIgBAIIgEAHIgFAEIgFAEQAEAAADADQADABACADQADACABACQABAEAAAFQAAAGgCAFQgBAEgFAEQgEAFgGABQgFACgJAAQgKAAgJgCgABlgDIgMAAIAAAoIgMAAIAAhZIAMAAIAAAnIAIAAQADABACgCQACAAABgFIAPgaQABgDADgCQADgCAFAAIAEAAIADABIgBAIIgCAAIgCAAQAAAAgBAAQAAAAgBAAQAAAAAAAAQgBABAAAAIgDADIgPAcIgBABIAeAuIgMACgAiugDIgJAAIAAAoIgNAAIAAgoIgKAAIgdApIgMgCIAfgtIgBgCIgOgcIgDgEIgDAAIgCAAIgCAAIgBgIIAEgBIAEAAQAFAAACABQADADABADIANAaQACAEACABQABACAEgBIAFAAIAAgnIANAAIAAAnIAFAAQADABACgCQACAAABgFIANgaIAEgFQADgCAFAAIAEAAIAEABIgCAIIgCAAIgBAAIgEABIgCADIgNAaIgBACIgCACIAfAtIgMACgAGgAlIAAhZIA4AAIAAAKIgsAAIAAAcIAhAAIAAAKIghAAIAAAgIAuAAIAAAJgACbAlIAAhZIAoABQAGABAEADQAFAEACAFQACAFAAAIQAAAFgCAFQgCAGgEADQgEAEgFACQgHAAgHABIgQAAIAAAkgACngHIAOAAQAKAAAFgEQAGgFAAgJQAAgFgCgEQgBgEgDgCQgCgBgFgBIgIgBIgOAAgAASAlIAAg9IgoAyIAAALIgNAAIAAhZIANAAIAAA/IAogyIAAgNIAMAAIAABZgAk+AlIAAhZIAdAAQAHAAAFACQAFAAAEADQAEAEADAEQACAFAAAGQAAAFgDAGQgFAGgEABQAIAEAEAFQAEAFAAAIQAAAFgCAFQgDAGgDACIgKAGQgGABgGAAgAkxAcIASAAQAKAAAFgFQAEgEAAgIQAAgFgBgEIgFgCQgCgCgFgBIgYAAgAkxgNIARAAQAEABADgCQADgBACgCQADgCAAgDIABgGQAAgIgFgEQgEgDgKAAIgOAAg");
	this.shape.setTransform(0,0,0.496,0.495);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-23.5,-2.7,47,5.5);


(lib.round = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.gradient();
	this.instance.setTransform(-190,-189.5);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-190,-189.5,380,379);


(lib.rav4_1 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.rav4();
	this.instance.setTransform(-106,-84);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-106,-84,212,168);


(lib.pradoWhite_1 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.pradoWhite();
	this.instance.setTransform(-108,-90);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-108,-90,216,179);


(lib.prado_1 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.prado();
	this.instance.setTransform(-108,-90);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-108,-90,216,179);


(lib.pr = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AtvRNMAAAgiZIbfAAMAAAAiZg");
	this.shape.setTransform(88,110.1);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,176,220.3);


(lib.p2 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgnAPIAFgaIBJgDIAAAdg");
	this.shape.setTransform(97.3,0,3.559,3.565);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgnAPIAAgdIBKADIAFAag");
	this.shape_1.setTransform(-97.3,0,3.559,3.565);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-111.5,-5.5,223,11.1);


(lib.p1White = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ak6AJIAMgRIJdAAIAMARg");
	this.shape.setTransform(0.1,173.1,3.551,3.551);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AlyAHIAAgNILlAAIAAANg");
	this.shape_1.setTransform(0,181.9,3.551,3.551);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgWH8IAAv3IAtAAIAAP3g");
	this.shape_2.setTransform(123.6,-4.1,3.551,3.551);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgXH8IAAv3IAuAAIAAP3g");
	this.shape_3.setTransform(-123.5,-4.1,3.551,3.551);

	this.addChild(this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-132,-184.5,264,369.1);


(lib.p1 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CD0B1B").s().p("Ak6AJIAMgRIJdAAIAMARg");
	this.shape.setTransform(0.1,173.1,3.551,3.551);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#CD0B1B").s().p("AlyAHIAAgNILlAAIAAANg");
	this.shape_1.setTransform(0,181.9,3.551,3.551);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#CD0B1B").s().p("AgWH8IAAv3IAtAAIAAP3g");
	this.shape_2.setTransform(123.6,-4.1,3.551,3.551);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#CD0B1B").s().p("AgXH8IAAv3IAuAAIAAP3g");
	this.shape_3.setTransform(-123.5,-4.1,3.551,3.551);

	this.addChild(this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-132,-184.5,264,369.1);


(lib.log = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.l();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,80,55);


(lib.img2Mc = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.img2();
	this.instance.setTransform(-150,-142);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-150,-142,300,284);


(lib.img1Mc = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.img1();
	this.instance.setTransform(-145,-133);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-145,-133,300,267);


(lib.logo = function() {
	this.initialize();

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E1192C").s().p("AAnBjQgogpAAg6QAAg5AogqQApgpA8gBQA6ABApApQAqAqABA5QgBA6gqApQgpAqg6ABQg7gBgqgqgABTg+QgXAaABAkQgBAkAXAbQAXAaAiABQAggBAXgaQAXgbAAgkQAAgkgXgaQgXgbggABIgBAAQghAAgXAagAoFBjQgpgpAAg6QAAg5ApgqQAqgpA7gBQA6ABAqApQApAqABA5QgBA6gpApQgqAqg6ABQg7gBgqgqgAnYg+QgXAaAAAkQAAAkAXAbQAXAaAhABQAggBAXgaQAXgbAAgkQAAgkgXgaQgXgbggABIgBAAQghAAgWAagALYCGIgXg8IhsAAIgXA8IhHAAIBwkHIBLAAIBtEHgAJnAeIBLAAIglhggAF/CGIAAjXIhWAAIAAgwIDkAAIAAAwIhSAAIAADXgAipCGIAAhlIhpiiIBHAAIBABwIBDhwIBEAAIhpCiIAABlgArLCGIAAjXIhTAAIAAgwIDhAAIAAAwIhTAAIAADXg");
	this.shape.setTransform(-0.8,70.7);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-80.7,56.5,159.9,28.5);


(lib.dillers = function() {
	this.initialize();

	// Face
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACSOPIAAizIgLgcIAjgOIAJAOIAUgIQANgDALAAQAPAAANAFQAMAFAJAKQAHAIAHAQQAEAPAAATQAAASgEAPQgFAPgKAKQgIALgPAGQgOAGgUAAIgMAAIgOgDIAAA+gADLLbIgPAFIAABOIALADIANABQAGAAAGgDQAHgDAEgFQAGgFACgIQADgJAAgMQAAgXgIgLQgIgKgOAAQgHAAgGACgAmsNyIAAgjIhRAAIAAAhIgpAAIAAhDIASAAIAJgPQAEgKACgJQADgPABgRQACgTgBgfIBsAAIAAB0IASAAIAABFgAnZL5QgBAPgDALIgFAOIgFAMIApAAIAAhRIgYAAIgDAdgAjLM3IALgHQAFgEACgDQADgDACgGIACgPIAKhYIBsAAIAACWIgqAAIAAhzIgbAAIgHBAQgCAKgDAIQgBAGgGAIQgDAFgJAHQgKAHgPAHgAANNOQgOgGgIgKQgLgLgDgOQgEgOAAgSQAAgQAEgPQAFgOAJgLQAJgLANgHQAOgGARAAQAkAAAQAVQARAVAAAmIgNALIhUAAQAAAJACAEQADAFAEAFQAFAFAGACQAIADAIAAIAKAAIAmgKIAMAhQgNAFgPADQgOAEgWAAQgVAAgOgGgABGL2QAAgSgHgHQgHgIgMAAQgNAAgHAJQgHAIgBAQIA2AAIAAAAgAGeNPIAAiWIBMAAQANAAAIACQAJACAHAFQAHAEAEAIQADAIAAAKQAAALgEAIQgGAIgHAEQAFACADADQAEACAEAFQADADADAHQADAGgBAIQAAAVgOAMQgOALgbAAgAHIMwIAgAAQAJAAAEgEQAFgDAAgIQAAgGgCgDQgDgEgCgBIgHgCIgkAAgAHIL0IAaAAQAIAAAEgEQAFgDAAgHQAAgIgEgDQgEgDgIAAIgbAAgAFLNPIAAh0IgTAAIAAgiIA9AAIAACWgAkNNPIAAhMIgxAyIAAAaIgrAAIAAiWIArAAIAABNIAxgzIAAgaIArAAIAACWgAFKKhQgHgGAAgLQAAgKAHgHQAHgHAMAAQANAAAGAHQAIAHAAAKQAAAKgIAHQgGAHgNAAQgNAAgGgHgAnEINIAAg8QgVgBgPgHQgOgHgJgKQgIgJgFgOQgEgMAAgQQAAgOAFgNQAFgNAJgKQAJgKAOgHQAPgGATgDIAAg8IApAAIAAA8QAWADANAGQAPAJAIAIQAIAKAFANQAEANAAAOQAAAPgFAMQgFAPgHAIQgJAKgPAHQgQAIgSACIAAA7gAndFpQgJAKAAASQAAASAJALQAIALASADIAAhUQgRACgJALgAmcGvQAQgDAJgKQAJgLAAgSQAAgSgJgLQgJgKgQgDgAhmHwIAAgiIhvAAIAAiXIArAAIAAB1IAyAAIAAh1IAqAAIAAB1IARAAIAABEgAKHGdIgDgDIgDgBQAAAAgBAAQAAAAgBABQAAAAAAAAQAAAAgBAAIgDADIgsA3IgfgXIAwg6Igqg7IAigVIAjA3QAEAEACAAIAEgBIACgDIAmg2IAhAUIgqA7IAuA6IgfAXgAqaHNQgNgGgLgLQgIgLgFgPQgFgOAAgRQABgRAFgOQAEgOAKgLQAKgLAOgGQANgHAVAAQAUAAAOAHQAPAGAJALQAKAKAEAPQAFAQAAAPQAAAPgFAQQgEAOgLAMQgIALgPAGQgPAGgTAAQgVAAgPgGgAqPFiQgJALAAAWQAAAWAJAMQAJALAQAAQAPAAAKgMQAIgMAAgVQAAgWgIgLQgKgMgPAAQgRAAgIAMgAHuHOIAAhNIgxAzIAAAaIgqAAIAAiXIAqAAIAABNIAxgyIAAgbIArAAIAACXgAFBHOIAAg8IgzAAIAAA8IgqAAIAAiXIAqAAIAAA4IAzAAIAAg4IAqAAIAACXgACSHOIAAhNIgxAzIAAAaIgrAAIAAiXIArAAIAABNIAxgyIAAgbIAqAAIAACXgAgbHOIAAh1IgTAAIAAgiIA7AAIAACXgAkoHOIAAh1IgTAAIAAgiIA+AAIAACXgAgcEgQgGgHgBgKQABgLAGgGQAHgHAMAAQAKAAAIAHQAHAHAAAKQAAAKgHAHQgIAHgKAAQgNAAgGgHgAkoEgQgHgHAAgKQAAgLAHgGQAHgHAMAAQAMAAAHAHQAHAGAAALQAAAKgHAHQgHAHgMAAQgOAAgFgHgABoEgQgMgDgFgEQgJgGgFgHQgFgHgDgKIAegKQADAKAHAEQAHAGALAAQAJAAAIgGQAHgFACgJIAeAJQgCAJgGAJQgGAIgGAFQgIAEgJADQgKADgJAAQgJAAgKgDgALeCMIgSgEIAEgVIARADQAHACAKAAQAMAAAHgFQAIgFADgMIAFgRIgNAAQgMAAgGgCQgHgCgGgGQgFgFgEgJIgGgSIgbhqIAagGIAbBqIAEALQABAFADADQADAEAFABQAFACAGAAIALgBIAjiDIAYAGIgrCmQgDAMgFAJQgGAIgGAFQgJAFgIACQgIACgMAAgAqaCMIAAi1IgJgYIAYgLIAJAPQAKgFALgEQAMgEAPAAQAfAAARAUQASAUgBAjQABASgFAPQgFAPgJAKQgKALgNAGQgOAGgUAAIgRgBIgRgEIAAA/gApsgwIgSAJIAABcIAPAFIAUABQAJAAAJgDQAHgCAIgIQAGgIAEgKQADgMAAgOQAAgNgCgLQgFgLgEgGQgGgGgIgDQgHgDgJAAQgNAAgJADgAHDBvIAAgjIh4AAIAAiTIAbAAIAAB9IBJAAIAAh9IAbAAIAAB9IASAAIAAA5gAh3BLQgOgGgJgKQgIgKgEgPQgEgQAAgPQAAgPAFgOQAEgPAJgLQAKgKANgGQAPgGARAAQATAAAOAGQAOAGAJAKQAHAKAFAPQAFAPAAAOQAAAQgEAPQgFAQgIAKQgJAKgOAGQgNAHgUAAQgVAAgNgHgAh2gmQgNAPAAAaQAAAbANAPQALAOAWAAQAWAAALgOQAMgQAAgaQAAgagMgPQgLgOgWAAQgWAAgLAOgAnNBLQgOgGgJgKQgIgMgEgNQgEgQAAgPQAAgPAFgOQAEgQAJgKQAJgKAOgGQAPgGARAAQATAAAOAGQAOAGAJAKQAJALADAOQAFAPAAAOQAAAQgEAPQgFAQgIAKQgJAKgOAGQgNAHgUAAQgVAAgNgHgAnMgmQgNAPAAAaQAAAbANAPQALAOAWAAQAWAAALgOQAMgPAAgbQAAgbgMgOQgLgOgWAAQgWAAgLAOgAAcBLQgQgFgKgHIANgUIAKAGIALAEIAOADIANACQAQAAAJgGQAKgGAAgMQAAgKgHgHQgFgFgRAAIgkAAIAAgVIAgAAQAQAAAGgGQAGgHAAgJQAAgLgHgFQgJgFgNAAQgKAAgNAEQgQAEgGAEIgLgTIAJgEIAPgFIARgFIAUgBQAbAAAMALQANAKAAASQgBAXgUAMQANACAHAJQAGAIAAAOQABAVgRANQgQANgfAAQgSAAgRgFgAJLBMIAAh9IgUAAIAAgWIAvAAIAACTgAH9BMIAAh9IgRAAIAAgWIAsAAIAACTgAEEBMIAAheIhJBJIAAAVIgbAAIAAiTIAbAAIAABfIBJhJIAAgWIAbAAIAACTgAjdBMIAAh8IhGAAIAAB8IgbAAIAAiTIB8AAIAACTgArgBMIAAh8IhGAAIAAB8IgbAAIAAiTIB8AAIAACTgAH8hkQgGgFABgIQgBgJAGgFQAEgGAJAAQAJAAAFAGQAFAFAAAJQAAAIgFAFQgEAFgKAAQgKAAgDgFgAJlhmQgFgGABgIQgBgHAFgGQAEgFAKAAQAKAAADAFQAFAGAAAHQAAAIgFAGQgEAFgJAAQgJAAgFgFgAIkhmQgFgGAAgIQAAgHAFgGQADgFALAAQAJAAAEAFQAEAGAAAHQAAAHgEAHQgFAFgIAAQgKAAgEgFgAHokRIAAgiIh4AAIAAiVIAaAAIAAB+IBJAAIAAh+IAbAAIAAB+IATAAIAAA5gAolkRIAAgiIh4AAIAAiVIAbAAIAAB+IBJAAIAAh+IAbAAIAAB+IASAAIAAA5gAMzk0QgOgGgIgLQgIgKgFgPQgDgNAAgSQAAgQAEgPQAEgPAKgKQAJgLANgGQAOgGASAAQATAAAOAGQAPAHAHAKQAKAKAEAPQAEAMAAATQAAASgEANQgDANgKAMQgIALgOAGQgOAGgUAAQgUAAgOgGgAMzmnQgLAOAAAcQAAAbAMAPQALAPAWAAQAWAAAMgPQALgPAAgbQAAgcgLgOQgMgPgWAAQgWAAgMAPgAmLkwQgLgDgGgGQgIgFgDgJQgFgIAAgMQAAgOAFgIQAFgJAIgGQAIgHAKgCQAKgDALAAIAoAAIAAgJQAAgSgIgIQgHgHgRAAQgLAAgLACQgJABgPAGIgHgVQAMgEAMgDQAPgDARAAQAQAAAMAEQAMAEAGAIQAFAHADALQADAMgBAMIAABDIANASIgTAPIgOgPQgLAGgKAEQgNAFgQAAQgKAAgLgCgAmIlwQgIAGAAAOQAAAGADAFQADAGAEACIAKAEIALABQANAAAJgEIAQgKIAAgkIgmAAQgOAAgJAGgAshkzQgOgGgJgKQgJgKgEgPQgEgPAAgRQAAgQAEgOQAEgPAJgLQAJgKAOgHQANgHASAAQAiAAAQATQAQATAAAlIgOAMIheAAQAAAXAMAMQANAOAWAAIANgBIAmgJIAHAVIgYAIQgQADgSAAQgVAAgPgFgArcmKQAAgMgDgJQgDgHgFgGQgEgFgIgCQgHgDgIAAQgUAAgKAMQgKALgCAVIBQAAIAAAAgAxhk0QgOgFgIgLQgJgKgFgOQgEgNAAgTQAAgSAGgNQAEgPAKgLQAJgLAPgGQAPgGASAAQASAAANADQAMADAJAEIgIAVIgWgGQgJgCgMAAQgMAAgKAEQgIAFgHAHQgFAHgFALQgDALAAAMQABAbALAOQAOAPAWAAIAXgCQANgDALgEIAIAUQgLAFgOADQgOADgQAAQgUAAgQgGgAkUlFIAMgHIAHgHQACgCACgFIADgOIALhgIBhAAIAACVIgaAAIAAh+IgvAAIgMBeQgCAIgFAGQgEAGgGAFQgHAFgMAGgARrkzIAAiAIgRAAIAAgVIAsAAIAACVgAPCkzIAAiVIBHAAQAHAAAMACQAKACAGAEQAGAFAEAHQAEAJgBAJQAAAKgEAIQgGAIgIAFIAKAFIAIAHQAEAFACAGQACAFAAAIQAAAVgNAMQgOALgYAAgAPclIIAuAAQAMAAAIgGQAIgEAAgNQAAgJgEgFQgGgGgFgBIgIgCIgzAAgAPcmLIApAAQAKAAAIgFQAHgFAAgKQAAgLgGgFQgHgEgOAAIgnAAgALOkzIAAhCIhKAAIAABCIgbAAIAAiVIAbAAIAAA8IBKAAIAAg8IAbAAIAACVgAIjkzIAAiAIgSAAIAAgVIAtAAIAACVgADskzIAAiAIgRAAIAAgVIAsAAIAACVgACfkzIAAhCIhKAAIAABCIgaAAIAAiVIAaAAIAAA8IBKAAIAAg8IAbAAIAACVgAhikzIAAiVIAbAAIAAA7IAqAAQAQAAALAEQAIAEAHAGQAGAGACAJQACAIABAIQgBAVgOAMQgLAMgYAAgAhHlIIAqAAQALAAAJgGQAHgFAAgNQAAgMgIgGQgIgGgQAAIglAAgAnrkzIAAiAIgRAAIAAgVIAsAAIAACVgAuIkzIAAh+IhGAAIAAB+IgbAAIAAiVIB8AAIAACVgARpnmQgEgFgBgIQABgIAEgFQAGgGAIAAQAJAAAFAGQAFAFgBAIQABAIgFAFQgEAGgKAAQgJAAgFgGgAIhnmQgFgFAAgIQAAgIAFgFQAEgGAJAAQAKAAAFAGQAEAFAAAIQAAAIgEAFQgFAGgKAAQgKAAgDgGgADqnmQgEgFAAgIQAAgIAEgFQAFgGAJAAQAJAAAFAGQAFAGAAAHQAAAHgFAGQgEAGgKAAQgJAAgFgGgAntnmQgFgFABgIQgBgIAFgFQAGgGAIAAQAJAAAFAGQAEAFABAIQgBAIgEAFQgEAGgKAAQgJAAgFgGgALgp1IAAi3IgJgYIAXgLIAJAPIAWgJQAMgEAPAAQAeAAASAUQARAUAAAlQAAASgEAPQgFAOgKALQgKALgNAGQgOAGgTAAIgRgBIgSgEIAAA/gAMOszIgTAJIAABeIAQAFIAUABQAJAAAIgDQAIgDAHgHQAGgIAEgKQADgKAAgQQAAgPgCgLQgEgLgFgGQgFgGgIgDQgIgDgJAAQgNAAgIADgAt3qLIAAgqIiKAAIAAAqIgcAAIAAhBIAQAAQAGgGAGgKQAFgHAFgMIAHgaIAFgiIAKhbIB3AAIAAC6IAQAAIAABBgAvVsDIgGAXQgCAJgEAJIgKAOIBkAAIAAiiIhAAAgAOtq2QgPgGgIgKQgJgMgDgNQgFgQAAgPQAAgRAFgOQAFgPAIgLQALgKANgGQAOgGARAAQAUAAANAGQAOAGAJAKQAIAKAFAPQAFAPAAAQQgBAQgEAPQgFAQgHAKQgKAKgOAGQgMAHgVAAQgUAAgNgHgAOtspQgMAPAAAcQAAAbAMAPQAMAOAVAAQAXAAALgOQAMgQgBgaQABgcgMgPQgLgOgXAAQgVAAgMAOgADmq1QgOgFgJgLQgKgLgDgOQgEgPAAgQQAAgRAFgPQAFgOAJgLQAKgLAOgGQAPgGATAAQASAAAMADQALACAMAFIgJAVIgXgHQgIgCgMAAQgMAAgKAFQgJAEgGAIQgGAHgEALQgDALAAAMQAAAbAMAOQANAOAXAAIAWgCQAOgCALgFIAIAVQgLAFgOADQgOADgQAAQgVAAgPgGgABDq1QgPgFgJgLQgIgIgFgQQgEgPAAgRQAAgQAFgPQAEgQAIgJQAJgLAOgHQANgGASAAQAiAAAPASQARASgBAmIgMANIhgAAQABAXANAMQAMANAXAAIANAAIALgCIAMgDIANgEIAIAVIgZAHQgMAEgVAAQgVAAgOgGgACHsMQAAgMgDgJQgDgIgFgFQgEgEgIgDQgHgCgIAAQgTAAgLALQgLANgBATIBQAAIAAAAgAmdqyQgKgDgHgFQgHgGgEgIQgFgIAAgNQAAgMAFgKQAFgJAIgGQAJgGAJgCQAKgDAMAAIAnAAIAAgJQAAgTgIgHQgHgHgRAAQgMAAgKACQgIABgQAFIgGgUQAKgFANgCQAPgDARAAQARAAAMAEQAKADAHAIQAGAHACAMQACAJAAAOIAABDIANATIgSAOIgOgPQgLAGgKAEQgNAGgRAAQgKAAgLgDgAmZrxQgJAGABANQAAAIACAEQADAFAEACQADADAHACIAMABQANAAAIgFIAQgKIAAgkIgmAAQgNAAgJAHgArkq2QgQgEgKgIIAMgUIAJAGIAaAHIAOACQAQAAAJgGQAJgGAAgMQAAgLgGgGQgGgFgRAAIglAAIAAgXIAiAAQAQAAAFgGQAHgHAAgJQAAgLgIgFQgJgFgMAAQgLAAgNAEQgOAEgHAEIgLgTIAJgEIAOgFIARgFIAUgBQAcAAAMALQAMAKAAASQAAAXgVAMQAOAFAHAIQAGAJAAANQAAAVgQANQgQANgfAAQgTAAgQgFgAKZq1IAAh+IhGAAIAAB+IgbAAIAAiVIB8AAIAACVgAFdq1IAAiVIAbAAIAAA7IAqAAQAQAAALAEQALAEAGAHQAGAGACAIQADAHAAAKQAAAUgOAMQgOAMgYAAgAF4rKIAqAAQAMAAAIgGQAHgFABgMQgBgMgHgHQgJgFgPAAIgmAAgAhGq1IAAh+Ig1AAIAAgXICCAAIAAAXIgzAAIAAB+gAiwq1IAAhgIhJBLIAAAVIgbAAIAAiVIAbAAIAABhIBJhLIAAgWIAbAAIAACVgAn9q1IAAhCIhJAAIAABCIgbAAIAAiVIAbAAIAAA8IBJAAIAAg8IAbAAIAACVgAs0q1IAAh/IgRAAIAAgWIAsAAIAACVgAj2tqQgPgLgFgRIAXgIQADAJAIAJQAIAHAOAAQANAAAIgHQAKgIACgKIAWAIQgCAJgFAHQgEAHgIAFQgKAGgGABQgKADgKAAQgVAAgPgKgAs2tnQgFgFAAgIQAAgJAFgFQAEgGAJAAQAKAAAFAGQAEAGAAAIQAAAHgEAGQgFAFgKAAQgJAAgEgFg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-116.2,-91.1,232.4,182.3);


(lib.corolla_1 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.corolla();
	this.instance.setTransform(-108,-77);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-108,-77,216,155);


(lib.camry_1 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.camry();
	this.instance.setTransform(-110,-80);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-110,-80,221,161);


(lib.bgImg_1 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.bgImg();
	this.instance.setTransform(-150,-300);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-150,-300,300,600);


(lib.bg = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("EgXbAu3MAAAhdtMAu3AAAMAAABdtg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-150,-300,300,600);


(lib.ALWAYS_mc = function() {
	this.initialize();

	// red
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E0192C").s().p("ADsAXIgEgFIgEgDIgEgCIgEgBIgFAAIAAAoIgWAAIAAhqIAoAAQAJAAAGACQAHABAFAEQAFAEADAGQADAFAAAJQAAAGgCAFIgFAJIgHAFQgEADgFABIAEAEIAFAEIAXAcIgRANgADXgEIAPAAQAIAAAFgEQAFgEAAgIQAAgFgBgDQgCgDgCgCIgGgCIgHAAIgPAAgABiA0IAAhqIBNAAIAAATIg4AAIAAAXIArAAIAAARIgrAAIAAAcIA6AAIAAATgAAeA0IAAhXIgeAAIAAgTIBVAAIAAATIggAAIAABXgAg8A0IAAhXIgfAAIAAgTIBWAAIAAATIggAAIAABXgAizA0IAAhqIBOAAIAAATIg3AAIAAAXIAqAAIAAARIgqAAIAAAcIA5AAIAAATgAkXA0IAAhqIAqAAQAIAAAGACQAIABAFADQAEAEADAFQADAFAAAIQAAAIgEAFQgDAGgGADIAHAEIAGADQACADACAFQABAEAAAFQAAAIgCAGQgDAGgFAEQgFAEgHACQgHACgJAAgAkCAiIAYAAIAGgBQADgBACgCIAEgEQABgDABgDQgBgFgBgCQgCgDgDgCIgGgCIgIgBIgUAAgAkCgKIATAAQAHAAAFgDQAEgDAAgHQAAgHgEgDQgGgCgKAAIgPAAg");
	this.shape.setTransform(31.2,29.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#A6A8A9").s().p("AFWBuIgqAAIgKAhIgVgFIAahWIADgJIAGgHQACgCAGgCQAEgBAHAAIAKABIAIAEQADADABADIAEAJIAaBXIgXAFgAE+AzIgCAEIgLAkIAgAAIgKgkIgDgEIgCgBIgEABgADOCOQgGgCgFgDIgLAFQgFABgHAAQgJAAgFgCQgGgCgFgEQgDgEgCgGIgEgMIgJhPIAWgDIAKBOQABAIACADQAEADAGAAIAFAAIAFgCIAAhYIAXAAIAABYIAEACIAFAAQAGAAADgDQAEgDABgIIAJhOIAWADIgJBPIgDAMQgDAGgEAEQgEAEgFACQgHACgIAAQgHAAgFgBgAGgCNIAAglQgGgCgEgFIgHgMIgVguIAUgIIAXAxIADAEIAEABIAEgBIACgEIAXgxIAUAIIgUAsQgEAIgEAGQgEAFgGACIAAAlgAEYg/IgrAAIgKAhIgVgFIAahWIADgJIAGgHQADgCAFgCQAFgBAGAAIAKABIAIAEQADADABADIAEAJIAbBXIgXAFgAEAh6IgDAEIgKAkIAgAAIgLgkIgCgEIgDgBIgDABgABsgeIgLgDIgKgCIgHgDIAHgTQAJAEAJACIARACQALAAAGgEQAGgEAAgGQAAgEgCgCQgBgDgEgBIgGgDIgKgCIgOgDQgGgCgFgDQgFgEgEgFQgDgGAAgIQAAgHADgGQACgGAFgFQAGgEAIgDQAJgCALAAQAMAAAJACIARAFIgFASIgSgEQgIgCgIAAQgKAAgEADQgGADAAAGIABAFIAFAEIAGACIAJACIAOAEQAHABAGAEQAFAEAEAGQADAFABAJQAAAIgEAHQgDAGgGAFQgGAEgIADQgJACgLAAIgOAAgAg5g/IgqAAIgKAhIgWgFIAahWIAEgJIAFgHQADgCAFgCQAEgBAHAAIAKABIAIAEQADADACADIADAJIAaBXIgWAFgAhRh6IgCAEIgLAkIAgAAIgKgkIgDgEIgDgBIgDABgAjCgfQgGgCgFgDIgKAFQgGABgGAAQgJAAgGgCQgGgCgEgEQgEgEgCgGIgDgMIgJhPIAVgDIAKBOQABAIADADQADADAHAAIAEAAIAGgCIAAhYIAWAAIAABYIAFACIAFAAQAFAAAEgDQADgDABgIIAJhOIAXADIgKBPIgDAMQgCAGgEAEQgEAEgGACQgGACgIAAQgHAAgGgBgAmSg/IgrAAIgKAhIgVgFIAahWIADgJIAGgHQADgCAFgCQAFgBAGAAIAKABIAIAEQADADABADIAEAJIAbBXIgXAFgAmqh6IgDAEIgKAkIAgAAIgLgkIgCgEIgDgBIgDABgAAPggIAAglQgHgCgDgFIgFgMIgVguIAUgIIAUAxIAEAEIADABIAEgBIADgEIAWgxIAUAIIgUAsQgEAIgEAGQgEAFgGACIAAAlgAllggIAAhsIAWAAIAABZIA5AAIAAATg");
	this.shape_1.setTransform(50,20.8);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,99.9,41);


(lib.t3 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.t3_2();
	this.instance.setTransform(0,13.2);

	this.instance_1 = new lib.t3_1();
	this.instance_1.setTransform(0,-25);

	this.addChild(this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-79,-34.6,158.1,69.3);


(lib.logo_ = function() {
	this.initialize();

	// ЗАВЖДИ КРАЩЕ
	this.instance = new lib.log();
	this.instance.setTransform(0.5,42.5,1,1,0,0,0,40,27.5);

	// ALWAYS A BETTER WAY
	this.instance_1 = new lib.ALWAYS_mc("synched",0);
	this.instance_1.setTransform(-0.4,187.3,1,1,0,0,0,49.8,21.3);

	// logo
	this.instance_2 = new lib.logo();
	this.instance_2.setTransform(0.5,42,0.582,0.581);

	// Layer 5
	this.instance_3 = new lib.pr();
	this.instance_3.setTransform(0,106.5,0.693,0.967,0,0,0,88,110.1);

	this.addChild(this.instance_3,this.instance_2,this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-61,0,122,213);


(lib.img2P4 = function() {
	this.initialize();

	// Слой 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("A4WHaIgmtwICKg1ICqgWIAoBVIgND/IAjBDIBfAcICghzIBxgPIBGA0IBGCIICMghIBrAAIBQhzICUgSIFSh1IB1gDIFACtIDuiWIBhDPICggFIBVh/IAUilIDKgFIEHBXIhiLlIgKAAMgvngAIg");
	mask.setTransform(3.7,96.7);

	// Слой 1
	this.instance = new lib.img2Mc();

	this.instance.mask = mask;

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-150,48.5,300,93.6);


(lib.img2P3 = function() {
	this.initialize();

	// Слой 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AqzJyIhJiFIg+gtIhzANIiiBuIhggcIgjhDIAKkEIglhQIiqAZIiCA3IAMlzIBdiCIBEhGIBrgvIEQELIAaEqIBwAUICbkOIA5geIHUhkICHhEIB9AKIC0B2ICRhOIE+CoIBzgyIBdAoIBaC0IBSgKIB9g3IAmi0IgXlNIAHiHIBHgPIDRASIArOHIjIgPIjNgFIgUClIhQCEIilADIhajXIj6CYIi5hcIh/hQIhxAKIlVBwIiVAUIhQBxIhuAAIiKAeIAAAAg");
	mask.setTransform(0.8,34.6);

	// Слой 3
	this.instance = new lib.img2Mc();

	this.instance.mask = mask;

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-150,-28,300,125.3);


(lib.img2P2 = function() {
	this.initialize();

	// Слой 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AvULIIgXk0IkRkEIhtArIg/BGIhiCCIgDxaQAGgCEkADQAOAFASANQAmAcAXAuQAdA6AQAzQASA2gBAeQAAAZAEBCIAEA8IC2AcIBcBwIBgA2ICjgZICpBLIHTBYIBmgZIBxlDIFgh9IBQiQICKABIBbDfICwAdIC7hoIBzhnIBzgBIgcHRIjRgHIhIALIgJB/IAaFIIgmC3Ih4BBIhVACIhaivIhYgvIh9A3Ik4iqIiOBGIi0huIiFgFIiFBBInZBfIg0AlIiYEOIhzgRg");
	mask.setTransform(0.5,-20);

	// Слой 1
	this.instance = new lib.img2Mc();

	this.instance.mask = mask;

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-150,-93,300,146);


(lib.img2P1 = function() {
	this.initialize();

	// Слой 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("ABIKUIn3hiIh/gvIiyAFIhLg3IhQhiIilggIgWhdIghiqIhQiAQgMgUgogTQgVgKgRgGIjoAIIhTo9MAxnAAjIASL2IiHAFIiKBaIjFBTIijgIIhejXIiAgPIiOC0Ii5AcIitEpIg6BjIg/AQg");
	mask.setTransform(-1,-84.3);

	// Слой 1
	this.instance = new lib.img2Mc();

	this.instance.mask = mask;

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-150,-142,300,125.5);


(lib.img2_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.img2P1();
	this.instance.setTransform(0,11);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(150));

	// Слой 3
	this.instance_1 = new lib.img2P2();
	this.instance_1.setTransform(0,83.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({y:11},149).wait(1));

	// Слой 4
	this.instance_2 = new lib.img2P3();
	this.instance_2.setTransform(0,159.8);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({y:11},149).wait(1));

	// Слой 1
	this.instance_3 = new lib.img2P4();
	this.instance_3.setTransform(0,204.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({y:11},149).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-160.7,-141,324.2,490.2);


(lib.img1P4 = function() {
	this.initialize();

	// Слой 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("ApdCWIhpAvIg0BpIhGA3Ihug0IhLAtIjUgDIh9gKIiRgyIhYthMAxnAA3IgKG6IhpgoIiigDIiZArIjlg+Ij2BaIg7g/IgthaIhngvIhuAYIhQA1IhBAZIhmg/IhOAGIgwBBIgcHAIhLDXIhIA5Ig5ACg");
	mask.setTransform(-3.6,-87.7);

	// Слой 1
	this.instance = new lib.img1Mc();

	this.instance.mask = mask;

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-145,-133,300,103.3);


(lib.img1P3 = function() {
	this.initialize();

	// Слой 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AugKbIhYhiImpgRIh4jFIgMoxIBfgcICnAhICgAFIB9gKIBEgrIBpA1IBBg1IA3hrIBmgyIFyGsIA/gDIBBg1IBLjNIAPiOIAMk0IAwhIIBQgFIBkA8IBEgXIBSg2IBugXIBkA0IAoBTIA/BEIDyhgIDrBCICggtICgAEIBpAtIAMKEIj0ARIhTAMImwgZIhkA/Ig3DPIhJBxIiCgRIhwAEIjfiEIjcAoIhnFjIjegRIh2AjIh/B1Ii+AUg");
	mask.setTransform(-1.5,-32.7);

	// Слой 1
	this.instance = new lib.img1Mc();

	this.instance.mask = mask;

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-145,-113.5,300,161.5);


(lib.img1P2 = function() {
	this.initialize();

	// Слой 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AoTJgImLiMIgqhVIhBiTIhzgIImBAFIgjkEIBwhYIGuAPIBVBaIBECNIDDgSIB9h2IB4goIDhAXIA0i+QAhhuAPgrQAKgdBsgJQBmgJA3APQApALBDA0QAiAaAaAXIBagKICWAUIBIhuIA8jSIBfg3IDaAFIDUANIBVgIIBhAXICPA3IAMImIhaASIisgIIiEgjIjcBJIibAtIiMAFIijBBIhzgcQgZgBgaADQg0AFgEASQgIAehICjIiKBIIiMBdIh2BzIi2Aeg");
	mask.setTransform(-0.5,34.6);

	// Слой 1
	this.instance = new lib.img1Mc();

	this.instance.mask = mask;

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-145,-30.5,300,130.3);


(lib.img1P1 = function() {
	this.initialize();

	// Слой 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("A1UIRIkHmDIgPlwIFDgqICagDICAAqIBOCXIBcB2IDDAbICdAlIB5AtICugTIBqh7ICMhTICCgtIAyhYIAtigIClgHICdgUICFgwICUASICVhBICbg8IBrAlICZASICMgDIBVKVI53GGg");
	mask.setTransform(0.6,86);

	// Слой 1
	this.instance = new lib.img1Mc();

	this.instance.mask = mask;

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-145,30.8,300,103.3);


(lib.img1_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 5
	this.instance = new lib.img1P4();
	this.instance.setTransform(0,-158.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:-10.5},149).wait(1));

	// Слой 4
	this.instance_1 = new lib.img1P3();
	this.instance_1.setTransform(0,-102.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({y:-10.5},149).wait(1));

	// Слой 3
	this.instance_2 = new lib.img1P2();
	this.instance_2.setTransform(0,-51.7);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({y:-10.5},149).wait(1));

	// Слой 2
	this.instance_3 = new lib.img1P1();
	this.instance_3.setTransform(0,-10.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(150));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-163.7,-304.2,328.7,435);


(lib.banner = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// urText
	this.instance = new lib.urText();
	this.instance.setTransform(0,238,1.224,1.225);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(399).to({_off:false},0).to({alpha:1},10).wait(36).to({alpha:0},10).wait(1));

	// logoTxt
	this.instance_1 = new lib.Symbol1();
	this.instance_1.setTransform(99.2,-175.1,1.103,1.104);
	this.instance_1.shadow = new cjs.Shadow("#000000",0,0,5);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(384).to({scaleX:4.16,scaleY:4.16,x:0.2,y:79.5},15).wait(46).to({scaleX:1.1,scaleY:1.1,x:99.2,y:-175.1},10).wait(1));

	// logoZnack
	this.instance_2 = new lib.logo_("synched",0);
	this.instance_2.setTransform(133.4,-299.8,0.556,0.556,0,0,0,60.8,0);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(384).to({startPosition:0},0).to({regX:61,scaleX:1.71,scaleY:1.71,x:104,y:-299.9},15).wait(46).to({startPosition:0},0).to({regX:60.8,scaleX:0.56,scaleY:0.56,x:133.4,y:-299.8},10).wait(1));

	// dillers
	this.instance_3 = new lib.dillers();
	this.instance_3.setTransform(-280,0);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(334).to({_off:false},0).to({x:0},10,cjs.Ease.get(1)).wait(30).to({x:280},10,cjs.Ease.get(-1)).to({_off:true},1).wait(71));

	// bgImg
	this.instance_4 = new lib.bgImg_1();
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(324).to({_off:false},0).to({alpha:1},10).wait(122));

	// t3_2
	this.instance_5 = new lib.t3_2();
	this.instance_5.setTransform(0,32.7,1.72,1.719);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(219).to({_off:false},0).wait(25).to({x:268},10,cjs.Ease.get(-1)).to({_off:true},1).wait(201));

	// t3_1
	this.instance_6 = new lib.t3_1();
	this.instance_6.setTransform(0,-33,1.72,1.719);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(219).to({_off:false},0).wait(65).to({x:289},10,cjs.Ease.get(-1)).to({_off:true},1).wait(161));

	// toyota
	this.instance_7 = new lib.toyotaP2();
	this.instance_7.setTransform(-2,42);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(289).to({_off:false},0).to({x:38,y:9,alpha:1},10).to({_off:true},36).wait(121));

	// toyota
	this.instance_8 = new lib.toyotaP1();
	this.instance_8.setTransform(-2,42,0.01,0.01);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(249).to({_off:false},0).to({scaleX:1,scaleY:1},10,cjs.Ease.get(-1)).wait(30).to({x:38,y:9},10).to({_off:true},36).wait(121));

	// t3
	this.instance_9 = new lib.t3();
	this.instance_9.setTransform(0,-102);
	this.instance_9.alpha = 0;
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(184).to({_off:false},0).to({y:0,alpha:1},10).wait(15).to({scaleX:1.72,scaleY:1.72,y:10},10,cjs.Ease.get(-1)).to({_off:true},1).wait(236));

	// pradoWhite
	this.instance_10 = new lib.pradoWhite_1();
	this.instance_10.setTransform(0,-95);
	this.instance_10.alpha = 0;
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(184).to({_off:false},0).to({y:7,alpha:1},10).wait(15).to({x:283},10,cjs.Ease.get(-1)).to({_off:true},1).wait(236));

	// prado
	this.instance_11 = new lib.prado_1();
	this.instance_11.setTransform(0,-20);
	this.instance_11.alpha = 0;
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(149).to({_off:false},0).to({y:-95,alpha:1},10).wait(25).to({y:7},10).to({_off:true},1).wait(261));

	// rav4
	this.instance_12 = new lib.rav4_1();
	this.instance_12.setTransform(0,99);
	this.instance_12.alpha = 0;
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(114).to({_off:false},0).to({y:-14,alpha:1},10).wait(25).to({y:-51.5},5).to({y:-89,alpha:0},5).to({_off:true},1).wait(296));

	// camry
	this.instance_13 = new lib.camry_1();
	this.instance_13.setTransform(0,190);
	this.instance_13.alpha = 0;
	this.instance_13._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(79).to({_off:false},0).to({y:102,alpha:1},10).wait(25).to({y:45.5},5).to({y:-11,alpha:0},5).to({_off:true},1).wait(331));

	// corolla
	this.instance_14 = new lib.corolla_1();
	this.instance_14.setTransform(-283,193);
	this.instance_14._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(39).to({_off:false},0).wait(1).to({regY:0.5,x:-280.3,y:193.5},0).wait(1).to({x:-272.1},0).wait(1).to({x:-258},0).wait(1).to({x:-237.8},0).wait(1).to({x:-211.9},0).wait(1).to({x:-181.7},0).wait(1).to({x:-148.9},0).wait(1).to({x:-116},0).wait(1).to({x:-85.3},0).wait(1).to({x:-58.5},0).wait(1).to({x:-36.6},0).wait(1).to({x:-20},0).wait(1).to({x:-8.6},0).wait(1).to({x:-2},0).wait(1).to({regY:0,x:0,y:193},0).wait(25).to({y:149},5).to({y:105,alpha:0},5).to({_off:true},1).wait(366));

	// p2
	this.instance_15 = new lib.p2();
	this.instance_15.setTransform(-283.7,276.4);
	this.instance_15._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_15).wait(39).to({_off:false},0).wait(1).to({x:-281.1},0).wait(1).to({x:-272.9},0).wait(1).to({x:-258.8},0).wait(1).to({x:-238.6},0).wait(1).to({x:-212.7},0).wait(1).to({x:-182.5},0).wait(1).to({x:-149.7},0).wait(1).to({x:-116.8},0).wait(1).to({x:-86.1},0).wait(1).to({x:-59.3},0).wait(1).to({x:-37.4},0).wait(1).to({x:-20.8},0).wait(1).to({x:-9.4},0).wait(1).to({x:-2.8},0).wait(1).to({x:-0.7},0).wait(25).to({y:188.4},10).wait(25).to({y:75.4},10).wait(25).to({y:0.4},10).wait(25).to({y:102.4},10).wait(15).to({x:282.3},10,cjs.Ease.get(-1)).to({_off:true},1).wait(236));

	// p1White
	this.instance_16 = new lib.p1White();
	this.instance_16.setTransform(-1,116);
	this.instance_16.alpha = 0;
	this.instance_16._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_16).wait(184).to({_off:false},0).to({alpha:1},10).wait(15).to({x:282},10,cjs.Ease.get(-1)).to({_off:true},1).wait(236));

	// p1
	this.instance_17 = new lib.p1();
	this.instance_17.setTransform(-284,116);
	this.instance_17._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_17).wait(39).to({_off:false},0).wait(1).to({x:-281.4},0).wait(1).to({x:-273.2},0).wait(1).to({x:-259},0).wait(1).to({x:-238.8},0).wait(1).to({x:-213},0).wait(1).to({x:-182.7},0).wait(1).to({x:-149.9},0).wait(1).to({x:-117.1},0).wait(1).to({x:-86.4},0).wait(1).to({x:-59.6},0).wait(1).to({x:-37.7},0).wait(1).to({x:-21.1},0).wait(1).to({x:-9.6},0).wait(1).to({x:-3.1},0).wait(1).to({x:-1},0).to({_off:true},140).wait(262));

	// img2
	this.instance_18 = new lib.img2_1();
	this.instance_18.setTransform(0,432);
	this.instance_18._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_18).wait(184).to({_off:false},0).to({y:168},150).to({_off:true},1).wait(121));

	// img1
	this.instance_19 = new lib.img1_1();
	this.instance_19.setTransform(0,-424);
	this.instance_19._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_19).wait(184).to({_off:false},0).to({y:-177},150).to({_off:true},1).wait(121));

	// round
	this.instance_20 = new lib.round();
	this.instance_20.setTransform(0,39.6);
	this.instance_20.alpha = 0;
	this.instance_20._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_20).wait(249).to({_off:false},0).to({alpha:1},10).wait(197));

	// t1
	this.instance_21 = new lib.t1();
	this.instance_21.setTransform(0,0,0.01,0.01);

	this.timeline.addTween(cjs.Tween.get(this.instance_21).to({scaleX:1,scaleY:1},15).wait(25).to({x:2.5},0).wait(1).to({x:10.4},0).wait(1).to({x:23.9},0).wait(1).to({x:43.3},0).wait(1).to({x:68},0).wait(1).to({x:97},0).wait(1).to({x:128.4},0).wait(1).to({x:159.9},0).wait(1).to({x:189.3},0).wait(1).to({x:214.9},0).wait(1).to({x:235.9},0).wait(1).to({x:251.8},0).wait(1).to({x:262.7},0).wait(1).to({x:269},0).wait(1).to({x:271},0).to({_off:true},1).wait(401));

	// bgImg
	this.instance_22 = new lib.bgImg_1();

	this.timeline.addTween(cjs.Tween.get(this.instance_22).wait(456));

	// bg
	this.instance_23 = new lib.bg();

	this.timeline.addTween(cjs.Tween.get(this.instance_23).wait(456));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,-300,300,600);


// stage content:
(lib._300x600 = function() {
	this.initialize();

	// cover
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#666666").ss(2,1,1).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape.setTransform(150,300);

	// banner
	this.instance = new lib.banner();
	this.instance.setTransform(150,300);

	this.addChild(this.instance,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(149,299,302,602);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;