(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.bottle = function() {
	this.initialize(img.bottle);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,242,352);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.x = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAMA6IgOghIgcAhIgrAAIA1g9IgZg2IAoAAIAMAfIAYgfIArAAIgyA6IAbA5g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.x, new cjs.Rectangle(-7.4,-5.8,14.9,11.6), null);


(lib.waves = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_1 = new cjs.Graphics().p("EglYAHaQr0jEAAkWQAAkVL0jEQL0jEQtAAQQsAAL0DEQLzDEAAEVQAAEWrzDEQr0DEwsAAQwtAAr0jEg");
	var mask_graphics_2 = new cjs.Graphics().p("Egh/AHaQr0jEAAkWQAAkVL0jEQL0jEQtAAQQsAAL0DEQLzDEAAEVQAAEWrzDEQr0DEwsAAQwtAAr0jEg");
	var mask_graphics_3 = new cjs.Graphics().p("A+2HaQr0jEAAkWQAAkVL0jEQL0jEQtAAQQsAAL0DEQLzDEAAEVQAAEWrzDEQr0DEwsAAQwtAAr0jEg");
	var mask_graphics_4 = new cjs.Graphics().p("A8gHaQr0jEAAkWQAAkVL0jEQL0jEQsAAQQtAAL0DEQLzDEABEVQgBEWrzDEQr0DEwtAAQwsAAr0jEg");
	var mask_graphics_5 = new cjs.Graphics().p("A8gHaQr0jEAAkWQAAkVL0jEQL0jEQsAAQQtAAL0DEQLzDEABEVQgBEWrzDEQr0DEwtAAQwsAAr0jEg");
	var mask_graphics_6 = new cjs.Graphics().p("A8fHaQr0jEAAkWQAAkVL0jEQLzjEQsAAQQtAAL0DEQLzDEAAEVQAAEWrzDEQr0DEwtAAQwsAArzjEg");
	var mask_graphics_7 = new cjs.Graphics().p("A8gHaQr0jEAAkWQAAkVL0jEQL0jEQsAAQQtAAL0DEQL0DEAAEVQAAEWr0DEQr0DEwtAAQwsAAr0jEg");
	var mask_graphics_8 = new cjs.Graphics().p("A8fHaQr0jEAAkWQAAkVL0jEQLzjEQsAAQQtAAL0DEQL0DEgBEVQABEWr0DEQr0DEwtAAQwsAArzjEg");
	var mask_graphics_9 = new cjs.Graphics().p("A8gHaQr0jEAAkWQAAkVL0jEQL0jEQsAAQQtAAL0DEQL0DEAAEVQAAEWr0DEQr0DEwtAAQwsAAr0jEg");
	var mask_graphics_10 = new cjs.Graphics().p("A8fHaQr0jEAAkWQAAkVL0jEQLzjEQsAAQQtAAL0DEQLzDEAAEVQAAEWrzDEQr0DEwtAAQwsAArzjEg");
	var mask_graphics_11 = new cjs.Graphics().p("A8gHaQr0jEAAkWQAAkVL0jEQL0jEQsAAQQtAAL0DEQLzDEABEVQgBEWrzDEQr0DEwtAAQwsAAr0jEg");
	var mask_graphics_12 = new cjs.Graphics().p("A8gHaQr0jEAAkWQAAkVL0jEQL0jEQsAAQQtAAL0DEQLzDEABEVQgBEWrzDEQr0DEwtAAQwsAAr0jEg");
	var mask_graphics_13 = new cjs.Graphics().p("A8fHaQr0jEAAkWQAAkVL0jEQLzjEQsAAQQtAAL0DEQLzDEAAEVQAAEWrzDEQr0DEwtAAQwsAArzjEg");
	var mask_graphics_14 = new cjs.Graphics().p("A8gHaQr0jEAAkWQAAkVL0jEQL0jEQsAAQQtAAL0DEQL0DEAAEVQAAEWr0DEQr0DEwtAAQwsAAr0jEg");
	var mask_graphics_15 = new cjs.Graphics().p("A8fHaQr0jEAAkWQAAkVL0jEQLzjEQsAAQQtAAL0DEQL0DEgBEVQABEWr0DEQr0DEwtAAQwsAArzjEg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(1).to({graphics:mask_graphics_1,x:-314.9,y:-0.9}).wait(1).to({graphics:mask_graphics_2,x:-293.2,y:-0.9}).wait(1).to({graphics:mask_graphics_3,x:-273.1,y:-0.9}).wait(1).to({graphics:mask_graphics_4,x:-251.2,y:-0.9}).wait(1).to({graphics:mask_graphics_5,x:-217.4,y:-0.9}).wait(1).to({graphics:mask_graphics_6,x:-186.9,y:-0.9}).wait(1).to({graphics:mask_graphics_7,x:-159.6,y:-0.9}).wait(1).to({graphics:mask_graphics_8,x:-135.4,y:-0.9}).wait(1).to({graphics:mask_graphics_9,x:-114.6,y:-0.9}).wait(1).to({graphics:mask_graphics_10,x:-96.9,y:-0.9}).wait(1).to({graphics:mask_graphics_11,x:-82.4,y:-0.9}).wait(1).to({graphics:mask_graphics_12,x:-71.2,y:-0.9}).wait(1).to({graphics:mask_graphics_13,x:-63.1,y:-0.9}).wait(1).to({graphics:mask_graphics_14,x:-58.3,y:-0.9}).wait(1).to({graphics:mask_graphics_15,x:-56.7,y:-0.9}).wait(70));

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F68124").s().p("Az9DgQh0hNgjg/QgQgdABgmIAiAfQAqAmA2AYQCwBOEQhOQCiguE1h9QEVhxCwgpIAkgMQCRgqCWgUQHihCFuCtQFFCai8gDIAFAJQAuBRghAMQgiAMhpg8QilhdlQgFQlPgFj9BWQjpBViBAuQjpBSiiAoQjJAxicAAQjLAAh9hUg");
	this.shape.setTransform(34.3,-7.7);
	this.shape._off = true;

	var maskedShapeInstanceList = [this.shape];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1).to({_off:false},0).wait(84));

	// mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	var mask_1_graphics_4 = new cjs.Graphics().p("A/XHaQr0jEAAkWQAAkVL0jEQL0jEQtAAQQsAAL0DEQLzDEAAEVQAAEWrzDEQr0DEwsAAQwtAAr0jEg");
	var mask_1_graphics_5 = new cjs.Graphics().p("A9LHaQr0jEAAkWQAAkVL0jEQLzjEQtAAQQsAAL0DEQL0DEAAEVQAAEWr0DEQr0DEwsAAQwtAArzjEg");
	var mask_1_graphics_6 = new cjs.Graphics().p("A8gHaQr0jEAAkWQAAkVL0jEQL0jEQsAAQQtAAL0DEQL0DEAAEVQAAEWr0DEQr0DEwtAAQwsAAr0jEg");
	var mask_1_graphics_7 = new cjs.Graphics().p("A8gHaQr0jEAAkWQAAkVL0jEQL0jEQsAAQQtAAL0DEQLzDEABEVQgBEWrzDEQr0DEwtAAQwsAAr0jEg");
	var mask_1_graphics_8 = new cjs.Graphics().p("A8fHaQr0jEAAkWQAAkVL0jEQLzjEQsAAQQtAAL0DEQL0DEgBEVQABEWr0DEQr0DEwtAAQwsAArzjEg");
	var mask_1_graphics_9 = new cjs.Graphics().p("A8gHaQr0jEAAkWQAAkVL0jEQL0jEQsAAQQtAAL0DEQL0DEAAEVQAAEWr0DEQr0DEwtAAQwsAAr0jEg");
	var mask_1_graphics_10 = new cjs.Graphics().p("A8fHaQr0jEAAkWQAAkVL0jEQLzjEQsAAQQtAAL0DEQL0DEgBEVQABEWr0DEQr0DEwtAAQwsAArzjEg");
	var mask_1_graphics_11 = new cjs.Graphics().p("A8gHaQr0jEABkWQgBkVL0jEQL0jEQsAAQQtAAL0DEQLzDEABEVQgBEWrzDEQr0DEwtAAQwsAAr0jEg");
	var mask_1_graphics_12 = new cjs.Graphics().p("A8gHaQr0jEAAkWQAAkVL0jEQL0jEQsAAQQtAAL0DEQLzDEABEVQgBEWrzDEQr0DEwtAAQwsAAr0jEg");
	var mask_1_graphics_13 = new cjs.Graphics().p("A8fHaQr0jEAAkWQAAkVL0jEQLzjEQsAAQQtAAL0DEQL0DEAAEVQAAEWr0DEQr0DEwtAAQwsAArzjEg");
	var mask_1_graphics_14 = new cjs.Graphics().p("A8fHaQr0jEAAkWQAAkVL0jEQLzjEQsAAQQtAAL0DEQLzDEAAEVQAAEWrzDEQr0DEwtAAQwsAArzjEg");
	var mask_1_graphics_15 = new cjs.Graphics().p("A8gHaQr0jEAAkWQAAkVL0jEQL0jEQsAAQQtAAL0DEQL0DEAAEVQAAEWr0DEQr0DEwtAAQwsAAr0jEg");

	this.timeline.addTween(cjs.Tween.get(mask_1).to({graphics:null,x:0,y:0}).wait(4).to({graphics:mask_1_graphics_4,x:-276.4,y:29.1}).wait(1).to({graphics:mask_1_graphics_5,x:-262.4,y:26.1}).wait(1).to({graphics:mask_1_graphics_6,x:-241.5,y:23.4}).wait(1).to({graphics:mask_1_graphics_7,x:-218.9,y:21}).wait(1).to({graphics:mask_1_graphics_8,x:-198.9,y:18.9}).wait(1).to({graphics:mask_1_graphics_9,x:-181.6,y:17.1}).wait(1).to({graphics:mask_1_graphics_10,x:-167,y:15.6}).wait(1).to({graphics:mask_1_graphics_11,x:-155,y:14.3}).wait(1).to({graphics:mask_1_graphics_12,x:-145.7,y:13.3}).wait(1).to({graphics:mask_1_graphics_13,x:-139,y:12.6}).wait(1).to({graphics:mask_1_graphics_14,x:-135,y:12.2}).wait(1).to({graphics:mask_1_graphics_15,x:-133.7,y:12.1}).wait(70));

	// Слой_3
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#F68028").s().p("AqPCeQhSgGhEgIQA7ADBhgLQDBgWC+hIQENhkCggsQD5hGCVALQCYALA9BJQAxA7gbBAQggBLhxAbQhwAahRguIhDgqQghgVgagJQhCgYiOAIQiHAIjcA3QhtAchTAaQgjAGg+AAQg4AAhPgFg");
	this.shape_1.setTransform(40.7,11.4);
	this.shape_1._off = true;

	var maskedShapeInstanceList = [this.shape_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(4).to({_off:false},0).wait(81));

	// mask (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	var mask_2_graphics_0 = new cjs.Graphics().p("EgqdAHaQr0jEAAkWQAAkVL0jEQL0jEQtAAQQsAAL0DEQLzDEAAEVQAAEWrzDEQr0DEwsAAQwtAAr0jEg");
	var mask_2_graphics_1 = new cjs.Graphics().p("EgmoAHaQr0jEAAkWQAAkVL0jEQL0jEQtAAQQsAAL0DEQLzDEAAEVQAAEWrzDEQr0DEwsAAQwtAAr0jEg");
	var mask_2_graphics_2 = new cjs.Graphics().p("EgjEAHaQr0jEAAkWQAAkVL0jEQL0jEQtAAQQsAAL0DEQLzDEAAEVQAAEWrzDEQr0DEwsAAQwtAAr0jEg");
	var mask_2_graphics_3 = new cjs.Graphics().p("A/xHaQr0jEAAkWQAAkVL0jEQL0jEQtAAQQsAAL0DEQLzDEAAEVQAAEWrzDEQr0DEwsAAQwtAAr0jEg");
	var mask_2_graphics_4 = new cjs.Graphics().p("A8vHaQr0jEAAkWQAAkVL0jEQL0jEQtAAQQsAAL0DEQLzDEAAEVQAAEWrzDEQr0DEwsAAQwtAAr0jEg");
	var mask_2_graphics_5 = new cjs.Graphics().p("A8gHaQr0jEAAkWQAAkVL0jEQL0jEQsAAQQtAAL0DEQLzDEABEVQgBEWrzDEQr0DEwtAAQwsAAr0jEg");
	var mask_2_graphics_6 = new cjs.Graphics().p("A8fHaQr0jEAAkWQAAkVL0jEQLzjEQsAAQQtAAL0DEQL0DEgBEVQABEWr0DEQr0DEwtAAQwsAArzjEg");
	var mask_2_graphics_7 = new cjs.Graphics().p("A8gHaQr0jEAAkWQAAkVL0jEQL0jEQsAAQQtAAL0DEQLzDEAAEVQAAEWrzDEQr0DEwtAAQwsAAr0jEg");
	var mask_2_graphics_8 = new cjs.Graphics().p("A8gHaQr0jEAAkWQAAkVL0jEQL0jEQsAAQQtAAL0DEQL0DEAAEVQAAEWr0DEQr0DEwtAAQwsAAr0jEg");
	var mask_2_graphics_9 = new cjs.Graphics().p("A8gHaQr0jEAAkWQAAkVL0jEQL0jEQsAAQQtAAL0DEQL0DEAAEVQAAEWr0DEQr0DEwtAAQwsAAr0jEg");
	var mask_2_graphics_10 = new cjs.Graphics().p("A8gHaQr0jEAAkWQAAkVL0jEQL0jEQsAAQQtAAL0DEQL0DEAAEVQAAEWr0DEQr0DEwtAAQwsAAr0jEg");
	var mask_2_graphics_11 = new cjs.Graphics().p("A8gHaQr0jEAAkWQAAkVL0jEQL0jEQsAAQQtAAL0DEQL0DEAAEVQAAEWr0DEQr0DEwtAAQwsAAr0jEg");
	var mask_2_graphics_12 = new cjs.Graphics().p("A8fHaQr0jEAAkWQAAkVL0jEQLzjEQsAAQQtAAL0DEQLzDEAAEVQAAEWrzDEQr0DEwtAAQwsAArzjEg");
	var mask_2_graphics_13 = new cjs.Graphics().p("A8fHaQr0jEAAkWQAAkVL0jEQLzjEQsAAQQtAAL0DEQL0DEgBEVQABEWr0DEQr0DEwtAAQwsAArzjEg");
	var mask_2_graphics_14 = new cjs.Graphics().p("A8gHaQr0jEAAkWQAAkVL0jEQL0jEQsAAQQtAAL0DEQL0DEAAEVQAAEWr0DEQr0DEwtAAQwsAAr0jEg");
	var mask_2_graphics_15 = new cjs.Graphics().p("A8fHaQr0jEAAkWQAAkVL0jEQLzjEQsAAQQtAAL0DEQL0DEgBEVQABEWr0DEQr0DEwtAAQwsAArzjEg");

	this.timeline.addTween(cjs.Tween.get(mask_2).to({graphics:mask_2_graphics_0,x:-347.4,y:10.3}).wait(1).to({graphics:mask_2_graphics_1,x:-322.9,y:10.3}).wait(1).to({graphics:mask_2_graphics_2,x:-300.1,y:10.3}).wait(1).to({graphics:mask_2_graphics_3,x:-279,y:10.3}).wait(1).to({graphics:mask_2_graphics_4,x:-259.6,y:10.3}).wait(1).to({graphics:mask_2_graphics_5,x:-225.6,y:10.3}).wait(1).to({graphics:mask_2_graphics_6,x:-193.5,y:10.3}).wait(1).to({graphics:mask_2_graphics_7,x:-164.8,y:10.3}).wait(1).to({graphics:mask_2_graphics_8,x:-139.5,y:10.3}).wait(1).to({graphics:mask_2_graphics_9,x:-117.5,y:10.3}).wait(1).to({graphics:mask_2_graphics_10,x:-98.9,y:10.3}).wait(1).to({graphics:mask_2_graphics_11,x:-83.7,y:10.3}).wait(1).to({graphics:mask_2_graphics_12,x:-71.9,y:10.3}).wait(1).to({graphics:mask_2_graphics_13,x:-63.5,y:10.3}).wait(1).to({graphics:mask_2_graphics_14,x:-58.4,y:10.3}).wait(1).to({graphics:mask_2_graphics_15,x:-56.7,y:10.3}).wait(70));

	// Слой_4
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#DF4306").s().p("A6PHDIAAt6QACgCAVgDQAagDAjgCQBggEBiAQQCGAWBuA3QCJBFBcB1QBdB1C7A/QCXA0DNAQQDrASDRgcQALgGC6gtQDlg3DYgsQKiiKDUAoIAAJ7g");
	this.shape_2.setTransform(-10.6,18.4);

	var maskedShapeInstanceList = [this.shape_2];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(85));

	// mask (mask)
	var mask_3 = new cjs.Shape();
	mask_3._off = true;
	var mask_3_graphics_2 = new cjs.Graphics().p("EgliAHaQr0jEAAkWQAAkVL0jEQL0jEQtAAQQsAAL0DEQLzDEAAEVQAAEWrzDEQr0DEwsAAQwtAAr0jEg");
	var mask_3_graphics_3 = new cjs.Graphics().p("EgifAHaQr0jEAAkWQAAkVL0jEQL0jEQtAAQQsAAL0DEQLzDEAAEVQAAEWrzDEQr0DEwsAAQwtAAr0jEg");
	var mask_3_graphics_4 = new cjs.Graphics().p("A/6HaQr0jEAAkWQAAkVL0jEQL0jEQtAAQQsAAL0DEQLzDEAAEVQAAEWrzDEQr0DEwsAAQwtAAr0jEg");
	var mask_3_graphics_5 = new cjs.Graphics().p("A9zHaQr0jEAAkWQAAkVL0jEQL0jEQtAAQQsAAL0DEQLzDEAAEVQAAEWrzDEQr0DEwsAAQwtAAr0jEg");
	var mask_3_graphics_6 = new cjs.Graphics().p("A8fHaQr0jEAAkWQAAkVL0jEQLzjEQsAAQQtAAL0DEQLzDEAAEVQAAEWrzDEQr0DEwtAAQwsAArzjEg");
	var mask_3_graphics_7 = new cjs.Graphics().p("A8fHaQr0jEAAkWQAAkVL0jEQLzjEQsAAQQtAAL0DEQL0DEAAEVQAAEWr0DEQr0DEwtAAQwsAArzjEg");
	var mask_3_graphics_8 = new cjs.Graphics().p("A8fHaQr0jEAAkWQAAkVL0jEQLzjEQsAAQQtAAL0DEQL0DEAAEVQAAEWr0DEQr0DEwtAAQwsAArzjEg");
	var mask_3_graphics_9 = new cjs.Graphics().p("A8fHaQr0jEAAkWQAAkVL0jEQLzjEQsAAQQtAAL0DEQLzDEAAEVQAAEWrzDEQr0DEwtAAQwsAArzjEg");

	this.timeline.addTween(cjs.Tween.get(mask_3).to({graphics:null,x:0,y:0}).wait(2).to({graphics:mask_3_graphics_2,x:-315.9,y:-0.9}).wait(1).to({graphics:mask_3_graphics_3,x:-296.4,y:-0.9}).wait(1).to({graphics:mask_3_graphics_4,x:-279.9,y:-0.9}).wait(1).to({graphics:mask_3_graphics_5,x:-266.4,y:-0.9}).wait(1).to({graphics:mask_3_graphics_6,x:-253.7,y:-0.9}).wait(1).to({graphics:mask_3_graphics_7,x:-238.7,y:-0.9}).wait(1).to({graphics:mask_3_graphics_8,x:-229.7,y:-0.9}).wait(1).to({graphics:mask_3_graphics_9,x:-226.7,y:-0.9}).wait(76));

	// Слой_5
	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#5C6167").s().p("AnIBkQiEhTgVgaQgHgJAFgCIAHAAQBpAhB/AbQD/A3BwgkQBOgZDkh2QDAhkBRgGQBBgEgpBhQgUAwgiAxImuCKQhHAjhrANQgoAFgnAAQioAAiRhbg");
	this.shape_3.setTransform(-58.9,-10.4);
	this.shape_3._off = true;

	var maskedShapeInstanceList = [this.shape_3];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_3;
	}

	this.timeline.addTween(cjs.Tween.get(this.shape_3).wait(2).to({_off:false},0).wait(83));

	// mask (mask)
	var mask_4 = new cjs.Shape();
	mask_4._off = true;
	var mask_4_graphics_4 = new cjs.Graphics().p("EghAAHaQr0jEAAkWQAAkVL0jEQL0jEQtAAQQsAAL0DEQLzDEAAEVQAAEWrzDEQr0DEwsAAQwtAAr0jEg");
	var mask_4_graphics_5 = new cjs.Graphics().p("A9fHaQr0jEAAkWQAAkVL0jEQL0jEQtAAQQsAAL0DEQLzDEAAEVQAAEWrzDEQr0DEwsAAQwtAAr0jEg");
	var mask_4_graphics_6 = new cjs.Graphics().p("A8gHaQr0jEAAkWQAAkVL0jEQL0jEQsAAQQtAAL0DEQL0DEAAEVQAAEWr0DEQr0DEwtAAQwsAAr0jEg");
	var mask_4_graphics_7 = new cjs.Graphics().p("A8fHaQr0jEAAkWQAAkVL0jEQLzjEQsAAQQtAAL0DEQL0DEgBEVQABEWr0DEQr0DEwtAAQwsAArzjEg");
	var mask_4_graphics_8 = new cjs.Graphics().p("A8fHaQr0jEAAkWQAAkVL0jEQLzjEQsAAQQtAAL0DEQL0DEgBEVQABEWr0DEQr0DEwtAAQwsAArzjEg");
	var mask_4_graphics_9 = new cjs.Graphics().p("A8fHaQr0jEAAkWQAAkVL0jEQLzjEQsAAQQtAAL0DEQLzDEAAEVQAAEWrzDEQr0DEwtAAQwsAArzjEg");
	var mask_4_graphics_10 = new cjs.Graphics().p("A8fHaQr0jEAAkWQAAkVL0jEQLzjEQsAAQQtAAL0DEQL0DEgBEVQABEWr0DEQr0DEwtAAQwsAArzjEg");
	var mask_4_graphics_11 = new cjs.Graphics().p("A8fHaQr0jEAAkWQAAkVL0jEQLzjEQsAAQQtAAL0DEQLzDEABEVQgBEWrzDEQr0DEwtAAQwsAArzjEg");
	var mask_4_graphics_12 = new cjs.Graphics().p("A8fHaQr0jEAAkWQAAkVL0jEQLzjEQsAAQQtAAL0DEQLzDEAAEVQAAEWrzDEQr0DEwtAAQwsAArzjEg");
	var mask_4_graphics_13 = new cjs.Graphics().p("A8gHaQr0jEAAkWQAAkVL0jEQL0jEQsAAQQtAAL0DEQLzDEABEVQgBEWrzDEQr0DEwtAAQwsAAr0jEg");
	var mask_4_graphics_14 = new cjs.Graphics().p("A8gHaQr0jEAAkWQAAkVL0jEQL0jEQsAAQQtAAL0DEQLzDEABEVQgBEWrzDEQr0DEwtAAQwsAAr0jEg");
	var mask_4_graphics_15 = new cjs.Graphics().p("A8fHaQr0jEAAkWQAAkVL0jEQLzjEQsAAQQtAAL0DEQL0DEgBEVQABEWr0DEQr0DEwtAAQwsAArzjEg");

	this.timeline.addTween(cjs.Tween.get(mask_4).to({graphics:null,x:0,y:0}).wait(4).to({graphics:mask_4_graphics_4,x:-286.9,y:22.1}).wait(1).to({graphics:mask_4_graphics_5,x:-264.4,y:18.1}).wait(1).to({graphics:mask_4_graphics_6,x:-230.1,y:14.4}).wait(1).to({graphics:mask_4_graphics_7,x:-193.7,y:11.2}).wait(1).to({graphics:mask_4_graphics_8,x:-161.6,y:8.4}).wait(1).to({graphics:mask_4_graphics_9,x:-133.8,y:5.9}).wait(1).to({graphics:mask_4_graphics_10,x:-110.2,y:3.8}).wait(1).to({graphics:mask_4_graphics_11,x:-90.9,y:2.1}).wait(1).to({graphics:mask_4_graphics_12,x:-76,y:0.8}).wait(1).to({graphics:mask_4_graphics_13,x:-65.3,y:-0.2}).wait(1).to({graphics:mask_4_graphics_14,x:-58.8,y:-0.8}).wait(1).to({graphics:mask_4_graphics_15,x:-56.7,y:-0.9}).wait(70));

	// Слой_6
	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#5C6167").s().p("A0VEXIC2iyIbGmjIKvCyIgtHLIAAAAMgn+gAog");
	this.shape_4.setTransform(48.4,6.6);
	this.shape_4._off = true;

	var maskedShapeInstanceList = [this.shape_4];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_4;
	}

	this.timeline.addTween(cjs.Tween.get(this.shape_4).wait(4).to({_off:false},0).wait(81));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-178.6,-26.7,0,90.2);


(lib.t2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAMA6IgOghIgcAhIgrAAIA1g9IgZg2IAoAAIAMAfIAYgfIArAAIgyA6IAbA5g");
	this.shape.setTransform(51.9,-4.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#F58124").s().p("AIBDDIALgzIA2AAIBAkeIg2AAIALg0IBuAAIhWGFgArEDDIBWmFIBuAAIgLA0Ig2AAIhAEeIA2AAIgLAzgAGgC1QgGgGAAgJQAAgKAIgHQAHgIAKAAQAJAAAGAHQAGAGAAAJQAAAKgHAHQgIAIgKAAQgJAAgGgHgAgpCqQgWgTAAgdQAAglAagXQAYgXAkAAQAdAAATAPQAPAMAGAVIgqANQgCgKgIgHQgIgGgLAAQgRAAgKANQgLAMAAARQAAAMAIAJQAJAJAOAAQAIAAAJgFQAIgEAEgHIAiAVQgXAhgqAAQgfAAgWgRgAFYC5IgXg0IgLAMIgJAoIgrAAIAfiQIAsAAIgLAzIAvgzIA3AAIhFBDIAoBNgAC3C5IARhLIhGBLIgqAAIAgiQIAsAAIgQBGIBChGIAsAAIgfCQgAjbC5IAgiQIBMAAQASAAAMANQAMAMAAASQAAAUgNAQQgRAUgiAAIggAAIgKAtgAidBmIAaAAQAHAAAFgEQAFgDAAgGQAAgKgMAAIgaAAgAljC5IAgiQIBtAAIgJAmIhBAAIgDAOIBAAAIgJAmIhAAAIgDAQIBCAAIgJAmgAmtC5IAXhqIg0AAIgXBqIgsAAIAgiQICLAAIggCQgAGnCDIAOhaIAuAAIgZBagAE7g+QgWgSAAgeQAAgkAagYQAYgWAlAAQAdAAASAPQAQAMAGAUIgqAOQgCgKgIgHQgIgGgLAAQgRAAgMANQgLAMAAAQQAAANAJAJQAJAJAOAAQAJAAAIgFQAJgFAEgHIAiAWQgXAhgrAAQggAAgVgSgADpguIgBgRIg0AAIgJARIg0AAIBViQIA3AAIAVCQgADIhlIAcAAIgEgugAA8guIANg3Ig0AAIgMA3IgrAAIAgiQIArAAIgMAzIA0AAIALgzIAsAAIggCQgAhgguIgCgRIgzAAIgJARIg0AAIBViQIA3AAIAVCQgAiBhlIAcAAIgEgugAkNguIAMg3IgzAAIgMA3IgsAAIAgiQIArAAIgLAzIA0AAIALgzIAsAAIggCQgAmqguIgCgRIg0AAIgJARIgzAAIBViQIA2AAIAWCQgAnMhlIAdAAIgEgug");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.t2, new cjs.Rectangle(-70.9,-19.4,141.9,39), null);


(lib.t1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1.5,2).p("AEPgBQA0AAAggcQAfgcAAgrQAAguhBgZQgggLgNgEQgUgIAAgGQAAgFAFgDQAEgDAIAAQAUAAAWAIQAYAJAQAPIAxg4QgWgWgggMQgegLgiAAQg2AAghAfQgdAbAAAnQAAAuBBAZQAQAGAcAJQAUAHAAAHQAAAFgFADQgGAEgKAAQgcAAgZgLQgagMgOgSIgxA6QAUAYAkAOQAlAPAqAAgAgQiiIAKgrIAwAAQAWAAAAASQAAALgKAHQgJAHgMAAgAgygGIAThVIA8AAQA/AAAggmQAZgdAAgmQAAghgXgXQgXgYgiAAIiNAAIg8EOgAKFhyIANg8IhhAAIgNA8gAHigGIA7kOIhSAAIg7EOgAGzEZQAzAAAfgrIBxidIhDAAIg2BQIgShQIhDAAIAnCKQgJAJgNAAQgNAAgKgIIgiAtQARAQAiAAgAD1BRIgrDEIBnAAQAuAAAXgaQASgVAAgaQAAgYgRgPQgSgRgiAAIgiAAIAEgPIBoAAIALg0gAC5EVIgdjEIhKAAIhzDEIBFAAIAMgWIBHAAIACAWgABzDKIgnAAIAhg+gAE/DIQAMAAAAALQAAAGgGAFQgFADgJAAIgnAAIAGgZgApAgGIAThVIA+AAQA+AAAhgmQAYgdAAgmQAAghgWgXQgXgYgiAAIiPAAIg7EOgAodiiIAJgrIAxAAQAWAAAAASQAAALgJAHQgJAHgMAAgAiwgGIAQhHIh8AAIAHgeIB4AAIAQhHIh4AAIAFgbIB7AAIAQhHIjNAAIg7EOgAj5EZQAmAAAagUQAfgXATg1IASg0IAoAAIggCQIA8AAIArjEIiZAAIgiBjQgKAbgLALQgKAKgOAAgAlkEZQAzAAAigiQAhggAAgwQAAgngdgZQgdgZgsAAQgzAAghAhQgiAgAAAwQAAAnAeAaQAcAZAsAAgAlgDkQgUAAgMgLQgNgMAAgSQAAgXAPgRQAQgRAWAAQAUAAAMAMQAMAMAAASQAAAXgOARQgQAQgWAAgAnXEVIg2hpIBehbIhLAAIhABGIAPhGIg7AAIgrDEIA7AAIAMg2IAQgQIAeBGg");
	this.shape.setTransform(-1,7.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AmjAxIADgQIg8AAIARhPIAZAAIgNA7IAdAAIANg7IAYAAIgNA7IAHAAIgIAkgAIjAdIAOgTQAEADAGAAQAFAAAEgDIgQg4IAbAAIAIAhIAWghIAbAAIguA/QgNASgVAAQgOAAgHgGgACEAZQgNgLAAgPQAAgUAOgNQAOgOAVAAQASAAAMALQAMAKAAAQQAAATgNAOQgOANgVAAQgSAAgMgKgACXgTQgGAHAAAJQAAAHAFAFQAFAEAIAAQAJABAHgIQAGgGAAgJQAAgHgFgFQgFgEgIAAQgKAAgGAGgAAiATIAPgPQAJAKARgBQAKAAAAgFQAAgEgNAAIgQAAIAFgUIAQAAQANAAAAgFQAAgFgOABQgNAAgHAEIgIgQQALgKATAAQARAAAKAGQALAFAAALQAAAGgHAGQgHAGgIABQAPADAAAOQAAAKgKAIQgLAGgNAAQgeAAgLgQgAqHATIAQgPQAIAKARgBQAKAAAAgFQAAgEgNAAIgQAAIAFgUIAQAAQANAAAAgFQAAgFgOABQgNAAgHAEIgIgQQALgKATAAQARAAAKAGQALAFAAALQAAAGgHAGQgHAGgIABQAPADAAAOQAAAKgKAIQgLAGgNAAQgdAAgMgQgAICAhIAHgeIgdAAIgGAeIgZAAIAShPIAYAAIgGAcIAdAAIAGgcIAZAAIgSBPgAGlAhIAGgZIgQACQgQAAgHgJQgGgHADgPIAGgZIAZAAIgGAZQgCALALgBQAIAAAEgCIAIghIAYAAIgRBPgAFPAhIAJgoIgnAoIgXAAIARhPIAZAAIgJAoIAlgoIAZAAIgSBPgADgAhIANg5IgVAAIAFgWIBDAAIgEAWIgWAAIgNA5gAABAhIgLgdIgHAIIgFAVIgYAAIAShPIAYAAIgGAcIAZgcIAfAAIgnAlIAXAqgAh5AhIAShPIA9AAIgEAWIglAAIgCAIIAkAAIgFAUIgkAAIgCAJIAlAAIgFAUgAjCAhIAJgoIgnAoIgYAAIAShPIAZAAIgJAoIAlgoIAZAAIgSBPgAkgAhIAHgeIgdAAIgGAeIgZAAIAShPIAYAAIgGAcIAdAAIAGgcIAZAAIgSBPgAl9AhIAShPIAYAAIgRBPgAn+AhIgBgJIgdAAIgFAJIgdAAIAwhPIAfAAIAMBPgAoQADIAQAAIgDgZg");
	this.shape_1.setTransform(2,-31);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1, new cjs.Rectangle(-68,-35.9,134.9,74.9), null);


(lib.pineapple_mc = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#D24623").ss(0.1).p("AGLmIQAAgCAAgBQACgMAAgJAC1mKQgEAAgCAFQgEAKADAjQABAegDANAEWmwQgPAHgDAHQgDAGgDARQgBAKgEAXQgDARgDALAB9kLQgHAdABALQABASgGAQQgCAFgDAGAAzjQQADABABABQAGACAQAGQAPAGAHAEIAFADQAUANASAOQANALAZAYQAMAKAKALQAGAHAOAQQACACACADQAEgCAIAAQADAAABgCADxhgQAEgJAZADQAJAAALgDAE2i/QAGgKAGgMADihKQAFAHAIALQAJAPAFAJQACAFACAFADvBtQgEASgDALQgCAGgCAGAC7DsQgDAEgCAEQgOAVgSAYQgbAlgZAUQgCABgBACAk7gkQAHgJAIgJQAMgOAbgbQALgLAJgJAh3jHQATgHAcgIQABgBABAAIAAAAAkyFOQAAAAgBAAQgNgJgHgHQgHgGgGgIQgDgFgHgKQgBgCgBgCAjYGaIAAAAQgJgFgCgBQgWgMgJgOQgBgCgBgCAAbGDQgJAEgKAEQgeALgjALAmABkQAEgLAEgMQADgIADgHIAAAAAl5D1QAAgBAAAAQgMgXgFgVQgCgMAAgNAiDGvQgCAAgCABQgSABgOgCIAAAA");
	this.shape.setTransform(-9.2,6.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#ED7925").ss(0.1).p("ACpkbQADgrAFgZQABgHACgIQAGgWAIgSQAXgxBBgiIAHgEQAMgGACAAQAAABAEAMIAEALQAJAbACAZQADAZgDARQgFAUgDAEQgDAEgMADQgBAAAAAAQgIACgHABQgfAIgdAQQgdAQgZAYgAEDiNQgQAAgTgGQgCgBgCgBQgSgGgQgEQgJgDgOgDQgIgBgDgBQgFgBAAgCQgBgBABgFQAAgDACgJQACgIABgHQAHggAKgPQAHgKAWgRQArggAigMQAJgCAMgEQAYgFAogHIAKgCQAVgDAJAAQAIAAABACQABABgCAIQgBAGgEALIgEAPQgHAXgLAVQgIASgPAZQgUAhgTARQgaAXgiAAgABxirQgHAAgCgBIAAgEQAAgCgBgDQgEgZgHg3QgFgmgEgdQgFgegDgTQgLhBgMglQgEgLgBgEQAJAFAWAVQAbAZASAiQASAiAEAjQABAFAAAEQAAABABABQACAagEAbQAAAFgBAEIAAABQgFAcgQA7IgBAEQgBADgBABQgBAAgGAAgAFmgjQgFgBgIgCQgbgFgRgDQgUgDgPAAQgQAAgRAEQgTAFgSAAQgCAAgDAAQgRAAgQgGQgDAAgCgBQgCgBgBgBQgWgIgXgOQgagQgQgQQgKgKACgJQADgIARgIQAOgGATgDQAJgCAKAAQAgAAAkAQQAJAEAIAEQAlAQAXANQA1AcAcAcQADACACADgAgHjtQgDgCgDgDIgHgHQgigdgTgOQgggWgkgMIgCgBIAJgDQAGgBAHAAQATAAAjAJQAUAFAjALIAFACQAoAMATASQAPAOAHAYQAAABAAAAQABACAAACIADAMQAAABAAABQAAABAAABQACAHACAPQABALABAHQACAIgCABQgBACgHACQgHACgIAEQgKAFgGAGIgGAFIgCgUQgBgPgBgHQgCgKgEgHIgBgBAANAHQAAAAAAgDQABgGAEgJQACgHAEgPQAEgOABgEQAKgdALAAQAGAAAKAJIAVAUQANAMgBAIQgBAHgQAHQgLAEgPAGQgOAEgHADIgGACQgMAFgEAAgAgggGQgEAAgLgBIgMgCQgMgBgEgBQgHgBgCgCQgCgDABgKQABgGADgSQADgQADgOQADgLADgDQAFgEAPgGQASgHARAAQADAAAEABQAOABAGACQAKACACAFQAGALgTAfIgMAVQgMAVgGAFQgFAGgJAAgAEEBJQgPgYgUgNQgMgIgWgJQgWgJgLgIQgIgFgGgJQgIgKgGgNQAGADAHACQAOAEASADQATAEARACQATACALAKQAPANADAdIAFArgABHBsQgIAAgEgEQgDgEgHgTIgCgGQgLgZABgIQABgJAOgKIAEgEQAMgJANgHQAGgDAEgCQAEgBAEAAQAIAAAMAGQAHAEADAGQAEAGAAAMQAAARgBAIQgBAOgGAPQgEAMgHAFQgGADgPABIgJABQgJABgEAAgAHhh0QgVgGgTgDQgQgDgWgBQgIgBgIAAQgQAAgfAEQgaACgOAAIgHAAQAQgEAMgIQAJgGATgQIAQgOQAGgFACgBQACgCACAAQAEAAANAFIADABQASAGAXAQQAaAQASASIAEAEgACQCyQgBgBgCgCQgCgDgDgFQgFgJgDgFQgGgKAAgFQABgFAGgKQAJgOAFgOQAEgMAEgWQAEgPACgFQABABAAABQABABABADQARAlgDAWQgBAMgHAPQgEAKgMAZQgEAJgCABgAgrCkQgRgCgTAAIgXAAQgMAAgDgCQgCgDgBgLQAAgHABgWIAAgCQAAgJgBgJQgBgFgCgKQgDgSACgGQADgJAQgIQAMgFAOgDQANgDAOAAQAOAAAMADQAMAEAGAHQAIAIAAAMQgBATgCATQgBALgDAQIAAAEQgDAQgKAIQgJAHgLAAgAAVD2QgEAAgBgBQgBgDgDgLQgDgNgEgLIgDgIQgEgQABgFQABgFANgOQAJgIADgCQAGgHADgCQAEgBALgCIAJgCQAIgBAGAAQAMAAAGAFQAHAIAAAYIAAAEQAAAYgDAJQgEAPgRAKQgGADgGADQgGACgIABIgGACQgQACgEAAgABNEzIAAAAQgCgBAAgHQAAgJABgDQABgDAFgHQAEgEABgDQADgFADgGQAFgJADgKQADgGADgLQAHgUAFgMIACgDQAEAEACAHQACAFABAKQAAABAAABQABAIgBAIQgBAHgDAMQgFAUgEAHQgFAGgQANQgFADgDACQgBABAAABIgBAAQgGADgDAAgAgKFxQgJgBgEAAQgGgBgBgCQgDgEAEgNQAJghAJgLQAKgMAcgPQALgGAGAAQAFAAADAFQADAGAAAPQAAALgBAGQgBAGgCAHQgFASgFAFQgEAFgQAIQgMAGgPAAgAhmHJQACgDAFgFIAMgMQAWgWAMgIQAVgOAVgCIAHgBQAJAAAAAAIACAAQAAAAgBACQgCAEgBADQgFAJgFAHIAAAAQgHAJgHAGQgJAIgQAHQgJAEgJACQgEABgGABQgEAAgFABIgGABQgLACgEAAgAlYgwQAAgEACgEQACgGADgEQACgDAGgIIAEgFQARgVASgNQAYgRAXgDQAFAAAEAAQAEAAAFABQABAAABAAQAAAAABAAQABABAAAAQADAAABAAIAAAAQACABAAAAIAAABQgBADgCADQgBACgDADQgBABgEAEQgFAEgCABIgKAMQgOAPgIAFQgKAJgUAIQgLAGgIACQgKADgMACIgCAAgAlxA6QgJAAgCgDQgCgCAAgJQgBgLAAgGQABgJADgHQADgHAGgKQAEgIADgCQACgCAGgBIAegJQAGgCAEgBQAFgBAHAAIACAAQAIAAADACQACACACAJQADAMgCAIQgBAGgGAMQgDAHgCAGQgGANgDADQgFAFgLABQgQABgRACQgJABgFAAgAijAjQgHAAgLgFQgWgIgNgEQgGgCgKgDQgLgDgDgBQgFgCgCgEQgCgEADgXIAIgfQAFgTAUgIQAQgGAXAAQAIAAAKABQAXACAKACQAMADAEAGQAEAFAAANQgBALgFAWQgBAEgDAGQgEAOgEAFQgEAHgMALQgGAGgFACQgFADgEAAgAh4hnQgEAAgKgCQgMgCgHgBQgPgCgQgBQgPgBgCgCQAAgBABgCQADgEAFgGQAHgIALgKQABAAACgBQABgCACgBQADgCADgCQACgBACgCQACAAABgBQAVgLAXAAQAOAAAQAEQAUAFAJAGQAGAEAAAEQAAACAAABQgBADgEAEQgFAFgKAFQgbANgJAEQgKAFgIAAgAi1CxQgHAAgJgDQgSgFgXgIQgNgEgTgEQgLgDgCgDQgCgDABgPIAAgFQABgWAAgRQAAgNAJgGQAJgGAYgCQACgBALAAQAHAAADgBQAHAAAEAAQAfAAANAQQAPATgJArIgBAGQgFAWgDAGQgFAJgKAAgAiyFSQgDAAgLgCIgIgBQgFAAgFAAQgFAAgJABQgPABgKAAQgSAAgGgBQgJgBgEgEQgEgEgBgJQgCgHAAgTIgBgqQADgdAHgHQAEgEAIgDQAFgBAPgDIACAAQAPgDAMAAQAOAAAPAEQAUAEAHAFQAJAIADAXQACARgCARQgBASgFAPQgEASgEAFQgDAEgGAAgAhEE1QgFAAgDgBQgFAAgFAAIgMAAQgLAAgCgCQgDgDAAgNQAAgGgBgGQgBgEgCgIIgBgEQgBgGgDgIQgCgGAAgDQgBgFAAgHQAAgJATgKQARgJAQgEQAUgEALAAQANAAAGAGQAHAHABATQABAOgCAQQgDAPgEANQgDAJgGAFQgFAFgMAFQgIAEgKAAgAncCDQgBgCABgGQADgiANgTQAKgOAZgSIAMgJIAEgCQABAAACgBIgBAFQgBAGgFALQgEAIgHAOQgGANgDAGQgFALgDAKQgDAKgCACQgCACgJABQgCAAgCABQgEABgDABQgBAAgBABIgBAAQgDACgBAAgAlnDAQgCAAgMgBIgGgBQgDAAgGgBQgLgBgGAAQgKAAgEAAQgIgCgCgCQgCgDABgGQACgNABgIQABgKAAgMQABgSAMgKQAIgGAVgIQAHgDAJgCQAGgBALgCQANgCAEAAQAGAAADACQADADADAIQAEAKABAHQAAAJgEAOIgCAHQgEAQgDAJQgDAJgFAGQgFAGgLAFQgDABgFAAgAmSFnQgLAAgEgFQgDgEgFgTIgDgLQgIgdgCgUQgBgQAEgHQAGgJAXgKQAKgEAEgCQAHgCAIAAIAFABQAZABAKALQAKAKADAcQACASAAAIQABANgDAIQgHAUgfAMQgNAGgOABQgIABgFAAgAj8HQQgNAAgJgCQgOgCgKgGIgGgEQgJgFgBgCQgCgDADgHQAFgKAIgRIACgGQAGgMADgEQAEgFAIgEQAJgEAJgCQAKgCAKAAQAJAAAXADQATACAFAIQAFAIgFAQQgEAMgHAQQgIATgIAFQgIAGgRABQgLABgGAAgAloG5QgCAAgDgCQgMgFgWgWIgDgDQgDgCgBgCQAAgBAAgBQAAgBACgCQADgCAEgBIACgBQAQgHAHgCQAJgEAMgEQAOgEAGAAQAEAAAAABQACADgJASIgPAfQgEAHgCADQgBACgCAAQgBABgBAAgAkWH0QgHAAgHgEQgHgDgFgEQgEgEgEgGIgCgDIgBgBQADAAAEABQAoAHATADQAAAAACABIgEADQAAAAgBABQgFACgDACQgDABgCABQgDACgDAAIgGABQAAAAgBAAgAiaG3QgDAAgCgBQAAgBABgBQAAgDACgEQAGgLABgJQABgGgBgLIgBgMQgBgNAKgIQAHgHASgGQAJgDAHgCQAIgBAIgBIAGAAQAHgBABAAQAJAAAFAEQAEAEABAFQABAFgEALQgHAQgIAMQgIAKgNALQgOAMgMAEQgJAEgPACIgGAAQgGABgCAAgAjeH0QgFAAgFAAQACgCABgBQADgCAEgDQAUgNAUgHQANgEAdgHIAMgDIgCACQgCACgCACQgBAAgBABQgFAGgFAEQgHAHgGAEQgCABgCACQgBABgCABQgBAAgBABQAAAAgBAAQgQAIgkAAgAnvDtIAAgBQgEgSABgKQABgMAIgQIAEgIQACgEABgCQABgCABgBQABgCAEgDQAKgHADAAQABAAABADQABACAAAFQABAMgIAoQgIApgGAMQgDAIgCADQgBgDgCgFAnFFfQgDgFgDgGQgEgGgBgDIgCgCQAAAAAAgBIgGgJQgCgFgBgEQgBgBAAgBIAAgBQgBgLALgMQABADACAFQANAoAAAOIAAAFIgBADg");
	this.shape_1.setTransform(0.6,0);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#D24623").s().p("AinGwIAFgCIAIgFIABgBIAFgDIgDgBIg7gKIgHgBIABABIgBgBIABABIAAAAIgLgGQgVgMgKgOIgCgDQAAgBABAAQAAAAABAAQAAgBABAAQAAgBABAAIAFgKIAPgfQAJgSgCgDIgEgBQgGAAgOAEIgVAIIgXAJIgCABIgHADIgBAAQgNgJgHgHQgHgGgGgIIgKgPIgCgEIAAgFQABgOgNgoIgEgIQgLAMABALIAAABIABACIgBgCIABADIAAgBQgMgXgFgVQgCgMAAgNIAHAcIACAIIAGgLQAGgMAHgpQAJgogCgMIgBgHQAAgBAAAAQAAgBgBAAQAAAAAAgBQAAAAAAAAQgDAAgLAHIgFAFIgCADIAIgXIAGgPIAAAAIAHgCIgHACIAHgCIAEgBQAJgBACgCQACgCADgKIAIgVIAJgTIALgVQAFgLACgGIAAgFIgDABIgEADIAPgTQAMgOAbgbIAUgTIACgBQAMgBAKgDQAIgDALgFQAUgJALgIQAHgGAOgPIAKgLIAHgGIAFgFIAFgEIACgGIAAgCIgCAAIAvgPIACgBIAAAAIgDADIADgDIgDADIgCACQgMAJgHAJIgHAKIgCADQACACAPAAIAfADIATADIAPACQAHAAAKgEIAjgSQAKgFAFgFQAEgEABgDIAEACIAXAIIAVAKIAFADQAUANARAOQANALAaAYIAWAVIAUAXIAEAFIANASQAJAPAEAJIAFAKIgBgCQgDAFgDAPQgFAVgEAMQgFAOgJAOQgGAKAAAFQgBAFAGAKIAIAOIAFAJIgHAcIgEAMIAAgCIgDgPQgCgHgEgEIgCADQgFAMgHAUIgGARIgHATIgGALIgGAHIgGAKIAAAMQAAAHABABIABAAQACAAAHgDIAAAAIABgBIgEAHQgOAVgSAYQgcAlgYAUIgDADIAKgQIADgHIABgCIgCAAIgJAAIgIABQgVACgUAOQgMAIgWAWIgMAMIgGAIIABAAIAPgCIAFgBIAJgBIgUAIQgdALgjALIAJgIIAKgJIACgCIAEgEIADgCIgNADQgdAHgNAEQgTAHgVANIgHAGIgEAAIgQAAIgQAAgAihEvQgJACgJAEQgIAEgEAFIgJAQIgCAGIgNAbQgCAHABADQABACAJAFIAGAEQAKAGAOACQAKACAMAAIARgBQASgBAIgGQAHgFAJgTIAKgcQAFgQgFgIQgFgIgTgCQgXgDgJAAQgKAAgKACgAATERIgFAAIgQACIgQAFQgSAGgHAHQgKAIABANIABAMQABALgBAGQgBAJgFALIgDAHIgBACIAFABIAJgBIAFAAQAPgCAJgEQAMgEANgMQANgLAIgKQAJgMAGgQQAEgLgBgFQgBgFgDgEQgFgEgKAAIgIABgAB9DTQgdAPgJAMQgJALgJAhQgEANACAEQABACAHABIAMABIAEAAQARAAAMgGQAPgIAEgFQAFgFAGgSIACgNIABgRQAAgPgDgGQgDgFgFAAQgFAAgMAGgAklCdIgPAGQgXAKgFAJQgFAHABAQQACAUAIAdIADALQAFATADAEQAEAFALAAIAOgBQAOgBANgGQAegMAHgUQADgIgBgNIgCgaQgDgcgJgKQgKgLgZgBIgGgBQgIAAgGACgAhmENIAIABIAOACQAGAAADgEQAEgFAEgSQAFgPACgSQABgRgCgRQgCgXgKgIQgGgFgUgEQgQgEgOAAQgMAAgPADIgCAAIgUAEQgIADgEAEQgHAHgDAdIABAqQAAATACAHQABAJAEAEQAEAEAJABQAGABASAAIAZgBIAPgBIAJAAgAAYCBQgRAEgQAJQgTAKAAAJIABAMIACAJIAFAOIAAAEIADAMIABAMQAAANADADQACACALAAIALAAIAKAAIAIABQALAAAIgEQALgFAFgFQAGgFADgJQAEgNADgPQACgQgBgOQgBgTgHgHQgGgGgNAAQgLAAgTAEgACcBFIgIACIgQADQgCACgHAHIgLAKQgOAOgCAFQgBAFAFAQIADAIIAHAYIAFAOQAAAAAAAAQABABAAAAQABAAAAAAQABAAABAAIAUgCIAGgCIAOgDIAMgGQARgKAFgPQACgJAAgYIAAgEQAAgYgHgIQgGgFgMAAIgOABgAj9AQIgRADQgIACgIADQgVAIgIAGQgMAKAAASIgCAWIgDAVQgBAGACADQADACAHACIAOAAIARABIAJABIAGABIAOABQAFAAADgBQALgFAGgGQAEgGAEgJIAHgZIACgHQAEgOgBgJQAAgHgEgKQgEgIgDgDQgDgCgGAAIgRACgAh3gJIgLABIgNABQgYACgJAFQgJAGAAANIAAAnIgBAFQAAAPABADQACADALADIAgAIIApANQAJADAHAAQALAAAEgJQADgGAFgWIACgGQAJgrgQgTQgMgPggAAIgKAAgAASggQgOADgLAFQgQAIgDAJQgCAGADARIAEAPIAAASIAAACIAAAdQAAALACADQADACAMAAIAWAAQATAAARACIADAAQALAAAKgHQAKgIACgQIAAgEIAFgbQACgTAAgSQAAgMgIgIQgGgHgMgEQgMgDgOAAQgNAAgOADgAC9hDIgKAFQgNAHgMAJIgEAEQgOAKgBAJQgBAIALAYIACAGQAIATADAEQADAEAIAAIAOgBIAIgBQAPgBAHgDQAGgFAEgMQAGgPACgNIAAgZQABgMgEgGQgEgGgHgEQgMgHgIAAIgIACgAjZhgIgKACIgdAJQgHACgCACQgCACgFAIIgJARQgDAHAAAJIAAARQABAJACACQABADAJAAIAOgBIAhgDQALgBAFgFQADgDAGgNIAGgNQAFgMABgGQADgJgEgLQgBgJgDgCQgDgCgHAAIgDAAIgMABgAh4iUQgVAJgFATIgIAeQgDAXACAFQACAEAFACIAOAEIAQAFIAjAMQAMAFAGAAQAFAAAEgDIALgIQAMgLAEgHQAEgFAFgOIADgLQAGgWAAgKQAAgNgDgGQgFgFgMgDIghgFIgSgBQgXAAgPAGgAB/h1IgEASIgHAWIgEAQIgBADIABAAQADAAAMgFIAGgCIAVgIIAagKQAQgGABgIQACgHgNgNIgVgUQgKgIgHAAQgLAAgKAcgAAxiqQgQAFgFAFQgDADgCAKIgHAeIgDAZQgBAJACADQACACAGACIARACIAMABIAPABQAIAAAFgFQAHgGAMgVIANgVQASgfgGgKQgCgFgJgDIgWgDIgHAAQgQAAgSAHgAinGwIAAAAIAFgCIgFACIAAAAgADehPIgUgXIgWgVQgagYgNgLQgRgOgUgNIAFAEIAFgMQAGgQgCgSQAAgKAHgeIABABIAAAAIABABQAEAIACAJIACAXIADATIAFgFQAGgFALgFIAOgGQAHgCACgCQABgCgBgHIgDgTIgDgWIgBgCIAAgBIgDgNIgBgEQADgNgBgeQgDgjAFgKQABgFAEAAIAJBEIAMBQIAAAFIABAEQABABAHAAIABAAIAHgBIABgDIABgEQARg8AEgbIAAgBIAAgCQAEgKADgSIAFghQACgRADgGQAEgGAPgHIgDAPQgEAYgEArQAZgXAdgQQAdgQAfgIIAPgEIABAAIgCAVIgBADIgUAGQgjAMgrAgQgVAQgIAKQgJAPgIAhIgCAPIgDAMQgBAFABABQAAABAFABIALADIAXAFIAiALIAEABQgGANgGAJIgQgHQglgRggAAQgKAAgJACQgTADgOAHQgQAHgEAJQgCAIAKAKQAQARAbAQQAWANAWAJIADABIAFACQAQAFARABQgKAEgJgBQgZgDgEAJIgNgEQAGANAIAJQAAABgBAAQAAABgBAAQAAAAgBAAQAAAAgBAAQgIAAgEACIgEgFgAhJjUIAAAAgACsksIAAgBIABAEIgBgDg");
	this.shape_2.setTransform(-9.2,6.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#ED7925").s().p("AjhH0IACgDIAIgFQAUgNATgHQANgFAdgGIANgEIgDADIgDADIgCACIgLAKIgNALIANgLIgJAIIgEADIgDADIgEACIgBAAIgBABQgQAHgkABIgCAAIgJAAgAkPH0QgIAAgHgEQgHgDgEgEIgJgKIgCgDIAAgBIAGABIA7AKIADABIgEADIgCAAIgIAFIgFACIgGACIgGABIAAAAgAkMHOQgOgDgJgFIgHgFQgJgEgBgCQgBgDADgHIAMgbIADgGIAIgRQAEgEAIgEQAKgEAJgDQAJgCAKAAQAKAAAXAEQASACAFAIQAFAIgFAPIgKAcQgJATgHAGQgIAGgSABIgQAAQgNAAgKgBgAhfHIIAHgHIAMgMQAWgWAMgIQAUgOAWgCIAGgBIAKAAIACAAIgBACIgEAHIgKAQIgBAAQgFAJgHAGQgKAIgQAHQgIAEgKACIgKACIgJABIgFABIgQABgAlnG3QgMgGgWgVIgDgDIgDgFIgBgBQAAAAAAgBQAAAAABAAQAAgBABAAQAAgBABAAIAHgDIACgBIAWgKIAWgHQANgEAGAAIAEAAQACADgJATIgPAfIgFAJQgBABAAABQgBAAAAAAQAAABgBAAQAAAAgBAAIgBAAIgGgBgAiYG2IAAgCIADgHQAFgLABgJQABgGgBgMIgBgLQAAgNAJgJQAIgHASgFIAPgFIARgCIAFgBIAJAAQAJAAAFAEQAEADABAFQAAAGgEAKQgGARgJALQgHALgNALQgOAMgMAEQgKAEgPABIgFABIgJAAIgEAAgAgEFwIgMgBQgGgBgCgBQgCgEAEgNQAJghAJgMQAIgMAegPQALgFAGAAQAFAAACAFQADAGAAAPIgBAQIgCAOQgGARgFAGQgEAFgPAIQgMAFgQAAgAmbFiQgDgFgFgTIgDgKQgIgdgBgUQgCgQAFgHQAGgJAXgKIAOgGQAGgCAIAAIAGAAQAZACAKAKQAKAKADAdIACAaQAAANgDAIQgHAUgeAMQgNAFgOABIgNABQgMAAgEgEgAm/FeIgGgKIgFgJIgBgCIgBgBIgFgJIgEgIIgBgDIAAgBQgBgLALgMIAEAIQANAogBAOIAAAFIAAADgAi6FQIgIgBIgJAAIgOABIgZABQgTAAgGgBQgJgBgEgFQgEgDgBgJQgBgIgBgSIAAgrQACgcAHgIQAEgEAIgCIAVgEIACAAQAPgDAMAAQANAAAQADQAUAEAGAGQAKAIACAXQACARgBARQgCARgEAPQgFASgDAGQgDADgHABIgOgCgAhGE0IgKAAIgLAAQgMAAgCgDQgCgCAAgNIgCgNIgCgLIgBgEIgEgOIgDgJIgBgMQAAgJAUgKQAQgKARgDQATgFALABQAOAAAFAFQAHAHABAUQABANgCARQgCAPgFANQgDAIgFAFQgGAFgLAGQgIADgLABIgIgBgABTEzQgBgBAAgHIAAgNIAHgJIAFgIIAGgKIAIgTIAGgRQAGgVAFgLIACgEQAFAFACAHIACAOIAAADIAAAPIgEAUQgEATgFAHQgEAHgRAMIgHAGIgCABIAAAAQgGAEgDAAgAnhEMIgHgcIgBgDIAAgBQgDgSABgKQABgNAHgPIAEgIIADgGIACgDIAGgFQAKgHADAAQAAAAAAAAQAAAAAAABQABAAAAAAQAAABAAABIACAHQABAMgIAoQgIApgGAMIgFAKIgDgIgAAXD1IgFgOIgHgZIgCgHQgGgRACgFQABgEAOgOIALgLQAHgHADgBIAPgDIAIgCIAPgCQALAAAGAGQAIAIAAAYIAAAEQAAAXgDAKQgFAPgRAJIgMAHIgOADIgGACIgUACQgBAAAAAAQgBAAgBAAQAAgBgBAAQAAAAAAAAgAlvC/IgGgBIgIgBIgSgBIgOgBQgHgBgCgCQgDgEABgFIADgVIACgXQAAgRANgKQAHgHAWgIQAHgDAJgBIARgDIAQgCQAGAAADACQADACAEAJQAEAKAAAHQABAJgEANIgCAHIgHAaQgEAJgEAFQgGAHgKAFQgEABgEAAIgPgBgACTCvIgFgJIgIgOQgGgJABgFQAAgFAGgKQAJgOAFgPQAEgLAFgWQADgPADgFIABACIABAEQARAlgDAWQgBAMgGAPIgQAjQgFAIgCABIgDgCgAi/CuIgpgNIgfgIQgMgDgCgDQgBgDAAgPIABgGIAAgmQAAgNAJgGQAJgGAZgCIAMgBIALgBIALAAQAfAAAMAPQAQAUgJAqIgCAHQgEAVgEAHQgEAIgLAAQgGABgKgDgAglCkQgRgCgSAAIgYAAQgMAAgCgDQgDgCAAgLIAAgdIAAgDIAAgSIgDgOQgEgSACgGQADgJAQgIQAMgGAOgDQAOgCANAAQAPgBAMAEQALAEAHAGQAGAJAAAMQAAATgCATIgDAbIgBADQgCAQgKAJQgJAGgMABgAnVCDQgBgCABgHQACghAOgUQAJgNAZgSIAMgJIAEgDIADAAIAAAFQgCAGgFALIgKAWIgJATIgIAVQgEAKgCACQgCACgJABIgEABIgHACIgCABIAAAAIgFACgABCBnQgDgDgIgUIgCgFQgKgaABgHQAAgJAOgKIAFgEQAMgJANgHIAJgFIAIgBQAIAAAMAGQAHAEAEAGQAEAGAAAMIgBAZQgCAOgFAPQgFAMgGAFQgGADgQABIgIAAIgOABQgIAAgDgEgAELBJQgQgYgUgOQgLgIgXgIQgWgJgKgIQgIgFgHgJQgIgKgGgMIANAEIAhAIIAjAFQATADALAJQAPAMAEAeIAFAqgAl1A3QgCgCgBgKIAAgRQAAgIAEgHIAIgQQAFgJACgBQACgCAHgCIAdgJIALgDIALAAIADAAQAIAAACABQADADACAIQADAMgCAIQgBAGgGAMIgGAMQgFAOgEADQgFAFgLAAIghAEIgOABQgIgBgCgCgAivAeIgjgNIgQgEIgOgFQgFgBgBgEQgDgEAEgXIAIgfQAFgTAUgIQAPgGAXAAIASABIAhAEQANADAEAGQAEAFgBANQAAALgFAWIgEAKQgFANgDAGQgFAHgLALIgLAIQgFACgFAAQgGABgMgFgAATAHIABgDIAEgPIAHgWIAFgSQAKgcAKAAQAHgBAKAJIAVAUQANANgCAHQgBAIgPAGIgaAKIgVAHIgHACQgMAFgDAAgAgogHIgMgCIgRgCQgGgBgCgCQgCgDABgKIADgYIAHgeQADgLADgCQAEgFAQgFQASgIAQAAIAHABIAVADQAJADADAEQAFALgSAfIgNAVQgLAVgGAFQgGAGgIAAIgPgBgAFfgmIgrgIQgVgDgOAAQgRAAgQAEQgTAGgTgBIgEAAQgRAAgRgGIgFgBIgDgCQgWgIgWgNQgagRgQgQQgLgKADgIQADgJAQgIQAOgGATgDQAJgCALAAQAfAAAlARIAQAHQAlAQAYANQA0AcAcAcIAFAFIgNgDgAlQg4IAFgKIAIgKIAFgGQARgVASgMQAXgRAYgEIAIAAIAKABIABAAIABAAIACABIADABIABAAIACAAIgBACIgCAFIgEAFIgGAFIgGAFIgLAMQgOAPgHAGQgLAIgTAJQgLAFgJACQgKAEgMABIgCAAIgFABIACgIgAiAhpIgTgDIgfgDQgPAAgCgCIACgEIAHgKQAHgIAMgKIACgBIAEgDIAFgEIAFgDIACgBQAVgLAXAAQAOAAARAEQAUAFAJAGQAFAFABADIgBADQAAADgEAEQgGAFgKAFIgkARQgKAFgHAAIgPgCgAHohzQgWgHgSgDQgQgCgWgCIgRgBQgQABgeADQgbADgOAAIgGAAQAPgFANgIQAIgFAUgRIAPgOIAIgFQABgBAAAAQABgBAAAAQABAAABAAQAAgBABAAQADABAOAEIADABQARAHAYAPQAaAQASASIAEAEgAAsifIgCgXQgCgKgFgHIgBgBIAAAAIAAgBQgJgMgZgYIgGgFIgIgGQghgegUgOQgfgWgkgMIgDgBIAKgCIAMgBQAUgBAiAJIA3AQIAGACQAnAMATASQAQAPAGAXIAAABIAAAAIABAEIADAMIAAACIABACIADAWIADASQABAIgBABQgBACgIACIgOAGQgKAFgHAGIgFAFgADmiTIgEgBIgigLIgXgGIgLgCQgEgBgBgBQgBgCABgEIADgMIADgPQAHghAKgPQAHgKAWgQQAqghAjgLIAVgHQAYgFAogHIAKgBQAVgEAJAAQAHAAABACQACACgCAHIgFARIgFAPQgHAXgKAWQgJARgOAaQgUAggTARQgbAXghAAQgRAAgTgGgAB3irQgHAAgBgBIgBgDIAAgGIgMhQIgJhDIgHgxQgLhBgNglIgEgOQAIAEAXAVQAaAZASAiQASAjAFAjIABAIIAAADQACAZgDAbIgCAJIACgJIgBAIIgBABIAAACQgEAbgRA8IgBADIgBAEIgHAAgAC3lfIADgPQAGgWAIgSQAYgxBBgiIAHgEQALgGACAAIAFANIADALQAJAcADAYQADAZgEARQgEAUgDAFQgDADgNADIgBAAIgPAEQgfAHgdARQgdAQgZAXQAEgrAEgZg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.pineapple_mc, new cjs.Rectangle(-50.2,-51,100.5,102), null);


(lib.peach_mc = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#ED7925").ss(1.1).p("AD1h3QgHgYgHgRQgCgHgEgFQgIgLgMAFIiBAfQABAEAAAEQgHAKgEAEQglAlgvAUQgeALgmAAQgLAAgOgGQgPgIgHgEQgCgBgGgDQAAAAABgBIhMgkQgBAAgDAFQgVAVgGAfQgEARAEAcQADAYAGAUQANAmAQAXQAJALAFAHQAIAKAHAHQAbAbApAOQAgAMAoABQAnACAngIQApgIAkgRQAjgRAdgbQAggdARglQANgcAEggQAEgkABgOQABgdgGgTg");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#D24623").s().p("AgvCdIgSgEIgRgBQgLgCgHgCIgVgHIgVgIQgKgFgIgIIgPgRQgQgRgNgWQgOgZgDgVQgGghABgSQABgaANgVQACgEAGAAQAGAAAOAFIAWAIIgDASIAHgFIACAWIACAAIAKgMIADAXIACgBIAFgIIALAWIABgPQAHAAAEADQAEACACAGQACAJAFAAQACAAAEgCIAIADIAFgNIAEAGIAGAFIAFADIAGADIAFgKIAAgCIAAgCQACgGADAAIAFACIAGAFIAHAFIADACIAEACIABgEIAAgEQAAgGAEAAIAEABIAGADIAGADIADABQAEAAAAgGIAAgFIAAgHIAVANIACgCIgIgZIACgCIAeATQACgHgEgKQgFgKAAgFIAGADIAKAIIALAHIACABIADAAIAAgCIAAgDIgFgLIgFgLIgKgcQgBgEACgDQACgCAEAAIABAAIAPACIABAAIAFAAIgCgGIgHgMIA9gWQAtgQAOAAIADAAQAIABAHANIAHAUQAEAOABAUQABARgCAQIgDAfQgCAQgEAMQgJAcgKARQgMAVgTARQghAdgkAPIgcAMQgQAGgNADQgPADgSADIghADIgEAAQgHAAgLgCg");
	this.shape_1.setTransform(0.8,-0.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#ED7925").s().p("AgoC0QgogBgggMQgpgOgbgbIgPgRIgOgSQgQgXgNgmQgGgUgDgYQgEgcAEgRQAGgfAVgVIAEgFIBMAkIgBABIAIAEIAWAMQAOAGALAAQAmAAAegLQAvgUAlglIALgOIgBgIICBgfQAMgFAIALQAEAFACAHQAHARAHAYQAGATgBAdQgBAOgEAkQgEAggNAcQgRAlggAdQgdAbgjARQgkARgpAIQggAHgfAAIgPgBgAjNhTQgNAVgBAaQAAATAFAgQAEAWAOAYQAMAWARASIAPAQQAIAIAKAFIAVAIIAVAHQAHADAKABIASACIASADQAKADAHAAIAEgBIAhgDQASgCAPgEQANgDAQgGIAdgLQAkgPAhgeQATgQAMgVQAKgSAJgbQAEgNACgPIADgfQACgQgBgSQgBgUgFgNIgHgUQgGgNgIgBIgDgBQgOAAguARIg9AVIAIANIACAFIgFABIgBAAIgQgCIgBAAQgEAAgCACQgBACABAEIAKAcIAEAMIAGALIAAACIAAADIgDAAIgDgBIgKgIIgLgIIgFgCQAAAEAEALQAEAKgCAHIgegTIgCACIAIAZIgCACIgUgNIAAAGIAAAGQAAAGgEAAIgEgBIgFgEIgHgDIgDgBQgEAAAAAHIgBAEIgBAEIgDgCIgEgCIgGgGIgHgFIgEgCQgEAAgBAHIAAACIgBACIgFAKIgFgDIgGgEIgFgFIgFgFIgEANIgJgEQgDACgDAAQgEAAgDgIQgCgGgEgDQgEgCgHAAIgBAPIgLgWIgEAIIgCAAIgEgWIgJAMIgDgBIgBgVIgIAFIADgTIgVgHQgOgFgHAAQgGAAgCADg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.peach_mc, new cjs.Rectangle(-26.4,-19,53,38.2), null);


(lib.p6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#5F5F5F").s().p("AjcDBQANgsAlg/IAig2QAYgWAUgjQAnhIgUhFQgMgpAYgfQAWgdArgJQAtgKAuARQA0ATAkAuQAcAmALAyQANA7gRA5QgsCXjgBfQhSAjgsAAQhGAAAahYg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.p6, new cjs.Rectangle(-22.8,-28.1,45.6,56.2), null);


(lib.p5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F58124").s().p("AjkHCQCBhEBAhqQB+jSlCi1QikhcAFhhQAEhWB7g4QB3g2CQALQCgAMBdBbQCdCYgVCZQgKBNgqAtIoEHDg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.p5, new cjs.Rectangle(-39.1,-49.2,78.3,98.5), null);


(lib.p4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#5F5F5F").s().p("AivDEQhoirBYiMQBDhrCBgsQBEgXA5AHQAzAFAdAbQAcAagGAhQgGAjgrAcQhKAwgbBKQgOAlACAcQgXBjgqBCQglA9goAAQgyAAg1hZg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.p4, new cjs.Rectangle(-23.2,-28.5,46.5,57), null);


(lib.p3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#DF4306").s().p("AiPBOQgYgFgJgGQgQgLAcgVIAsgeQA2ghAwgVQCZhFApBVQAlBKinAcQg3AKhCACIgcAAQggAAgIgDg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.p3, new cjs.Rectangle(-18.2,-8.1,36.6,16.2), null);


(lib.p2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F68124").s().p("AieB1IAHhGQADgOAIgUQAPgoAVggQBGhnBvASQBoASgbBJQgNAkgiAgQgYAXgnAcQhLA4hDAVQgQAFgLAAQgeAAgDgfg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.p2, new cjs.Rectangle(-15.9,-14.8,31.9,29.6), null);


(lib.p1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#DF4306").s().p("AyGMTQAFghASgzQAmhnBDhiQBeiJCMhqQCtiFDshPIAVgGQEshlDEi4QDEi4A0jjQAQhFArg1QAtg4BDgbQBHgeBWAIQBdAKBmA2QDZB1AjCtQAhCgiCCkQiDCjj1BrQkFB0k7APQkpAOjoBgQi4BNiGB+QhgBag7BpQgeA1gMAkIijBag");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.p1, new cjs.Rectangle(-115.9,-88.4,231.9,176.9), null);


(lib.bottle_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.bottle();
	this.instance.parent = this;
	this.instance.setTransform(-83,-121,0.686,0.686);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bottle_1, new cjs.Rectangle(-83,-121,166,241.5), null);


(lib.bg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#0E0E0E","#2A2A2B"],[0,1],0,-188.5,0,188.6).s().p("A6PdeMAAAg67MA0fAAAMAAAA67g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.bg, new cjs.Rectangle(-168,-188.5,336,377.1), null);


(lib.pineapple = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.pineapple_mc();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({rotation:-10},15,cjs.Ease.quadInOut).to({rotation:0},15,cjs.Ease.quadInOut).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-49.3,-50.1,98.7,100.2);


(lib.peach = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.peach_mc();
	this.instance.parent = this;
	this.instance.setTransform(0.1,0.2,1,1,0,0,0,0.1,0.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regX:0.2,regY:0.1,rotation:10,x:0.2},15,cjs.Ease.quadInOut).to({regX:0.1,regY:0.2,rotation:0,x:0.1},15,cjs.Ease.quadInOut).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-26.4,-18.6,53,37.6);


(lib.banner = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// bg
	this.instance = new lib.bg();
	this.instance.parent = this;
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(157).to({_off:false},0).to({alpha:1},10).wait(1));

	// x
	this.instance_1 = new lib.x();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-32.4,-26.6,0.024,0.031,0,0,0,-2,1.6);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(64).to({_off:false},0).to({regX:-0.1,regY:0.1,scaleX:0.88,scaleY:0.88,x:-32.3,y:-26.7},5).wait(99));

	// t2
	this.instance_2 = new lib.t2();
	this.instance_2.parent = this;
	this.instance_2.setTransform(-164.2,-98.2,0.8,0.8,0,0,0,-0.1,0);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(44).to({_off:false},0).to({x:-31.4},15,cjs.Ease.quartOut).wait(109));

	// t1
	this.instance_3 = new lib.t1();
	this.instance_3.parent = this;
	this.instance_3.setTransform(-161.5,-147.4,0.8,0.8,0,0,0,-0.4,0.8);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(24).to({_off:false},0).to({x:-27.1},15,cjs.Ease.quartOut).wait(129));

	// peach
	this.instance_4 = new lib.peach();
	this.instance_4.parent = this;
	this.instance_4.setTransform(-66.7,-210.8,0.9,0.9,58,0,0,-0.1,0.6);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(5).to({_off:false},0).to({regX:0,regY:0.8,rotation:30,x:-66.6,y:166.4},9,cjs.Ease.get(-1)).wait(154));

	// bottle
	this.instance_5 = new lib.bottle_1();
	this.instance_5.parent = this;
	this.instance_5.setTransform(-25.7,64,0.018,0.018,0,0,0,-2.8,5.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).to({regX:-0.2,regY:0.5,scaleX:0.69,scaleY:0.69,rotation:360},15,cjs.Ease.get(1)).wait(6).to({regX:-0.1,x:2.8},23,cjs.Ease.quartInOut).wait(75).to({scaleX:0.9,scaleY:0.9,x:11.8,y:50.5},5,cjs.Ease.quadInOut).wait(10).to({scaleX:0.69,scaleY:0.69,x:2.8,y:64},5,cjs.Ease.quadInOut).wait(29));

	// pineapple
	this.instance_6 = new lib.pineapple();
	this.instance_6.parent = this;
	this.instance_6.setTransform(-14.1,99.4,0.45,0.45,-40,0,0,0,0.1);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(10).to({_off:false},0).to({regY:0,scaleX:0.9,scaleY:0.9,rotation:0,x:29.1,y:102.5},5,cjs.Ease.get(1)).wait(6).to({x:62.5},23,cjs.Ease.quartInOut).wait(124));

	// peach
	this.instance_7 = new lib.peach();
	this.instance_7.parent = this;
	this.instance_7.setTransform(122.8,-19,0.958,0.958,-47.1,0,0,-0.3,0.7);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(64).to({_off:false},0).to({x:-15.2},10,cjs.Ease.quartOut).wait(94));

	// pineapple
	this.instance_8 = new lib.pineapple();
	this.instance_8.parent = this;
	this.instance_8.setTransform(-143.4,-42.6,0.68,0.68,-16,0,0,-0.5,0.1);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(64).to({_off:false},0).to({x:-55.4},10,cjs.Ease.quartOut).wait(94));

	// p6
	this.instance_9 = new lib.p6();
	this.instance_9.parent = this;
	this.instance_9.setTransform(-18.5,64.2,0.9,0.9);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(13).to({_off:false},0).to({x:6.2,y:69.2},5,cjs.Ease.get(1)).to({x:-3.2,y:64.2},3).to({x:25.2},23,cjs.Ease.quartInOut).wait(124));

	// p5
	this.instance_10 = new lib.p5();
	this.instance_10.parent = this;
	this.instance_10.setTransform(-17.4,72.1,0.63,0.63,0,0,0,-0.1,0.1);
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(13).to({_off:false},0).to({regX:0,regY:0,scaleX:0.9,scaleY:0.9,x:-59,y:66.7},5,cjs.Ease.get(1)).to({x:-44.4,y:72.1},3).to({x:-15.9},23,cjs.Ease.quartInOut).wait(75).to({x:-36.6,y:78.7},5,cjs.Ease.quadInOut).wait(10).to({x:-15.9,y:72.1},5,cjs.Ease.quadInOut).wait(29));

	// p4
	this.instance_11 = new lib.p4();
	this.instance_11.parent = this;
	this.instance_11.setTransform(-9.1,37.3,0.9,0.9,-45,0,0,-0.1,-0.1);
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(13).to({_off:false},0).to({rotation:0,x:-25.3,y:-8.2},5,cjs.Ease.get(1)).to({y:-1.4},3).to({regX:0.1,x:3.3},23,cjs.Ease.quartInOut).wait(75).to({scaleX:1.17,scaleY:1.17,y:-18.5},5,cjs.Ease.quadInOut).wait(10).to({scaleX:0.9,scaleY:0.9,y:-1.4},5,cjs.Ease.quadInOut).wait(29));

	// p3
	this.instance_12 = new lib.p3();
	this.instance_12.parent = this;
	this.instance_12.setTransform(-0.1,25.6,0.72,0.72);
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(13).to({_off:false},0).to({scaleX:0.9,scaleY:0.9,x:73.9,y:2},5,cjs.Ease.get(1)).to({x:53.6,y:8.3},3).to({x:82.1},23,cjs.Ease.quartInOut).wait(75).to({x:103,y:-19.7},5,cjs.Ease.quadInOut).wait(10).to({x:82.1,y:8.3},5,cjs.Ease.quadInOut).wait(29));

	// p2
	this.instance_13 = new lib.p2();
	this.instance_13.parent = this;
	this.instance_13.setTransform(-1.8,25.7,0.72,0.72);
	this.instance_13._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(13).to({_off:false},0).to({regX:0.1,regY:-0.1,scaleX:0.9,scaleY:0.9,x:55.8,y:-54},5,cjs.Ease.get(1)).to({x:44.2,y:-40.5},3).to({x:72.7},23,cjs.Ease.quartInOut).wait(40).to({regX:0,regY:0,x:91.5,y:-60.9},5,cjs.Ease.cubicInOut).to({regX:0.1,regY:-0.1,x:72.7,y:-40.5},10,cjs.Ease.backOut).wait(5).to({regX:0,regY:0,x:91.5,y:-60.9},5,cjs.Ease.cubicInOut).to({regX:0.1,regY:-0.1,x:72.7,y:-40.5},10,cjs.Ease.backOut).to({x:94.3,y:-72},5,cjs.Ease.quadInOut).wait(10).to({x:72.7,y:-40.5},5,cjs.Ease.quadInOut).wait(29));

	// waves
	this.instance_14 = new lib.waves("synched",0,false);
	this.instance_14.parent = this;
	this.instance_14.setTransform(9.9,133.6,0.9,0.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(168));

	// p1
	this.instance_15 = new lib.p1();
	this.instance_15.parent = this;
	this.instance_15.setTransform(-110.3,160.4,0.27,0.27,0,0,0,-0.2,0.2);
	this.instance_15._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_15).wait(11).to({_off:false},0).to({regX:0,regY:0,scaleX:0.9,scaleY:0.9,x:-29.3,y:106.3},10,cjs.Ease.get(1)).to({x:4.1},23,cjs.Ease.quartInOut).wait(124));

	// bg
	this.instance_16 = new lib.bg();
	this.instance_16.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_16).wait(168));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-168,-188.5,336,379.3);


// stage content:
(lib._300x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// cover
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#666666").ss(2,1,1).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// banner
	this.instance = new lib.banner();
	this.instance.parent = this;
	this.instance.setTransform(150,300,1.607,1.607);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-689,297,1259,629.4);
// library properties:
lib.properties = {
	id: 'E4C79B78FAC14BB28747BE5252F8351E',
	width: 300,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/bottle.png", id:"bottle"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['E4C79B78FAC14BB28747BE5252F8351E'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;