(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.dev = function() {
	this.initialize(img.dev);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,559,558);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.urText = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AQfCSIAAhFIAJAAIAAAHQAFgJALABQAJgBAGAIQAGAGAAALQAAAKgGAHQgGAHgJAAQgLAAgFgIIAAAegAQsBYQgEAEAAAIQAAAHAEAFQAEADAGAAQAOAAAAgPQAAgIgEgEQgEgFgGABQgGgBgEAFgAlSCSIAAhFIAJAAIAAAHQAGgJAKABQAJgBAGAIQAHAGAAALQAAAKgHAHQgGAHgJAAQgKAAgGgIIAAAegAlFBYQgEAEAAAIQAAAHAEAFQAEADAGAAQAPAAAAgPQAAgIgEgEQgEgFgHABQgGgBgEAFgAnlCJIAAgOIg1AAIAAhEIAKAAIAAA7IAhAAIAAg7IAKAAIAAA7IAJAAIAAAXgAJdCGIAAgLIgnAAIAAALIgHAAIAAgTIAFAAQAEgFAAgOIABgTIAkAAIAAAmIAIAAIAAATgAJBBgQAAAOgDAFIAWAAIAAgeIgTAAgASMB2QAAgBAAgBQABAAAAgBQAAAAAAgBQABAAAAgBQABAAAAAAQABgBAAAAQABAAABAAQAAAAABAAQAGgBAAAHQAAAGgGAAQgHAAAAgGgAM1B1QgHgHAAgKQAAgLAHgGQAGgIAJABQAKgBAGAJIAAgHIAJAAIAAAuIgJAAIAAgHQgGAIgKAAQgJAAgGgHgAM7BYQgEAEAAAIQAAAHAEAFQAEADAHAAQAOAAAAgPQAAgIgEgEQgEgFgGABQgHgBgEAFgAL/B0IAFgFQAFAFAJAAQAMABAAgIQAAgGgKAAIgKAAIAAgHIAIAAQAKABAAgIQAAgGgJAAQgIAAgGAFIgFgFQAGgHANAAQASgBAAANQAAAIgHADQAJADAAAIQAAAGgGAEQgFAEgKAAQgNAAgGgIgAFxB1QgHgHAAgKQAAgLAHgGQAGgIAJABQAKgBAGAJIAAgHIAJAAIAAAuIgJAAIAAgHQgGAIgKAAQgJAAgGgHgAF4BYQgEAEAAAIQAAAHAEAFQAEADAGAAQAOAAAAgPQAAgIgEgEQgEgFgGABQgGgBgEAFgADlBzIAFgHQAIAIAMgBQAPAAAAgLQAAgIgTgFQgTgHAAgMQAAgSAXAAQAPAAAIAIIgFAGQgGgGgMAAQgOAAAAAJQAAAHATAGQATAHAAANQAAAUgYAAQgQAAgJgJgAARByQgKgKAAgPQAAgPAKgKQAKgKAPAAQAPAAAKAKQAKAKAAAPQAAAPgKAKQgKAKgPAAQgPAAgKgKgAAYBGQgHAHAAAMQAAALAHAIQAHAHALAAQALAAAHgHQAHgIAAgLQAAgMgHgHQgHgIgLAAQgLAAgHAIgAitB1QgGgHAAgKQAAgLAGgGQAGgIAKABQAKgBAFAJIAAgHIAJAAIAAAuIgJAAIAAgHQgFAIgKAAQgKAAgGgHgAimBYQgEAEAAAIQAAAHAEAFQAEADAGAAQAPAAAAgPQAAgIgEgEQgEgFgHABQgGgBgEAFgAkUB1QgHgHAAgKQAAgLAHgGQAGgIALABQAKgBAHAIQAHAGAAALQAAAKgHAHQgHAHgKAAQgLAAgGgHgAkOBYQgEAFAAAHQAAAHAEAFQAEADAHAAQAGAAAEgDQAEgFAAgHQAAgHgEgFQgEgEgGAAQgHAAgEAEgAnQB1QgHgGAAgLQAAgLAHgHQAGgGAKAAQAKAAAHAGQAGAHAAAJIAAAEIgkAAQABAOAOAAQAIAAAHgFIAFAFQgHAIgNAAQgLAAgHgHgAnNBfIAbAAQgBgMgNAAQgMAAgBAMgApIB2QAAgHAGABQAAAAABAAQABAAAAAAQABAAAAABQABAAAAAAQABABAAAAQABABAAAAQAAABAAAAQAAABAAABQAAAGgGAAQgGAAAAgGgAuPB7IABgIIACAAQAEAAABgCIACgMIAAgYIAmAAIAAAuIgJAAIAAgmIgUAAIAAAQQgBAMgDAGQgDAFgIAAgAu9B1QgHgHAAgKQAAgLAHgGQAHgIAKABQALgBAHAIQAGAGAAALQAAAKgGAHQgHAHgLAAQgKAAgHgHgAu2BYQgEAFAAAHQAAAHAEAFQAEADAGAAQAHAAAEgDQAEgFAAgHQAAgHgEgFQgEgEgHAAQgGAAgEAEgAxdB1QgHgHAAgKQAAgLAHgGQAGgIALABQAKgBAHAIQAHAGAAALQAAAKgHAHQgHAHgKAAQgLAAgGgHgAxXBYQgEAFAAAHQAAAHAEAFQAEADAHAAQAGAAAEgDQAFgFAAgHQAAgHgFgFQgEgEgGAAQgHAAgEAEgAR4B7IAAgUIgXAAIAAAUIgJAAIAAguIAJAAIAAASIAXAAIAAgSIAJAAIAAAugAP1B7IAAguIAhAAIAAAIIgYAAIAAAmgAOyB7IAQgYIgHABQgKAAgGgGQgHgGAAgLQAAgKAHgHQAHgGAKAAQAKAAAHAGQAHAHAAAKQAAAJgHAKIgRAbgAOxBDQgEAEAAAGQAAAHAEAEQAFAFAGAAQAHAAAEgFQAEgEAAgHQAAgGgEgFQgEgEgHAAQgGAAgFAFgAOOB7IAAg6IgTAIIAAgJIAUgJIAIAAIAABEgAK7B7IAAguIAVAAQARgBAAAMQAAAIgHADQAJACAAAJQAAANgRAAgALEB0IAMAAQAKAAAAgGQAAgIgKABIgMAAgALEBgIAKAAQAKABAAgIQAAgFgKAAIgKAAgAKkB7IAAguIAKAAIAAAugAKOB7IAAgUIgXAAIAAAUIgJAAIAAguIAJAAIAAASIAXAAIAAgSIAJAAIAAAugAIBB7IAAgOIgiAAIAAgHIAggvIAMAAIAAAuIAIAAIAAAIIgIAAIAAAOgAHpBlIAYAAIAAgigAHKB7IAAg6IgSAIIAAgJIAUgJIAHAAIAABEgAFXB7IAAgUIgXAAIAAAUIgKAAIAAguIAKAAIAAASIAXAAIAAgSIAJAAIAAAugACkB7IAAhEIAWAAQAQAAAKAJQAKAKAAAPQAAAQgKAJQgKAJgQAAgACtByIANAAQAaABAAgaQAAgNgHgGQgHgHgMABIgNAAgACKB7Igng1IAAA1IgJAAIAAhEIAJAAIAnA1IAAg1IAJAAIAABEgAgyB7IAAhEIAaAAQAUAAAAASQAAAKgIAEQALAFAAAMQAAAJgFAFQgFAFgJAAgAgoByIASAAQAMAAAAgKQAAgLgMAAIgSAAgAgoBVIAPAAQAMgBAAgKQAAgLgMAAIgPAAgAhrB7IAAgmIgQAAIAAgIIApAAIAAAIIgQAAIAAAmgAjBB7IgMgTQgBAAAAAAQAAgBgBAAQAAAAgBAAQAAAAgBAAIgHAAIAAAUIgJAAIAAguIAJAAIAAARIAIAAQAAAAABAAQAAAAABAAQAAAAAAAAQAAgBABAAIAMgQIAKAAIgQAVIARAZgAloB7IAAgmIgXAAIAAAmIgJAAIAAguIApAAIAAAugApcB7IAAgiIgYAiIgJAAIAAguIAJAAIAAAiIAYgiIAJAAIAAAugAqTB7IAAgiIgPAVIgGAAIgPgVIAAAiIgJAAIAAguIAJAAIASAYIASgYIAJAAIAAAugArWB7IAAguIAJAAIAAAugArtB7IAAgUIgXAAIAAAUIgJAAIAAguIAJAAIAAASIAXAAIAAgSIAJAAIAAAugAsvB7IAAgmIgQAAIAAgIIApAAIAAAIIgQAAIAAAmgAtSB7IAAguIAJAAIAAAugAvXB7IAAgUIgXAAIAAAUIgJAAIAAguIAJAAIAAASIAXAAIAAgSIAJAAIAAAugAwqB7IAAguIAVAAQARgBAAAMQAAAIgHADQAJADAAAIQAAANgQAAgAwhB0IAMAAQAKAAAAgGQAAgIgKABIgMAAgAwhBgIAKAAQAKABAAgIQAAgFgKAAIgKAAgAx4B7IAAgmIgXAAIAAAmIgJAAIAAguIApAAIAAAugAKjA8QAAgGAGABQAGgBAAAGQAAAGgGAAQgGAAAAgGgArYA8QAAgGAGABQAGgBAAAGQAAAGgGAAQgGAAAAgGgAtTA8QAAgGAGABQAGgBAAAGQAAAGgGAAQgGAAAAgGgALCAuIAAhEIAKAAIAAAHQAFgJAKABQAJgBAHAIQAGAGAAAKQAAAKgGAHQgHAHgJAAQgKAAgFgIIAAAegALPgLQgEAFAAAGQAAAHAEAFQAEADAGAAQAPABAAgQQAAgGgEgFQgEgFgHABQgGgBgEAFgAFdAiIAAgLIgmAAIAAALIgIAAIAAgTIAGAAQADgEABgOIABgTIAkAAIAAAlIAHAAIAAATgAFCgDQgBANgDAFIAXAAIAAgdIgTAAgAwgAiIAAgLIhAAAIAAgtIAJAAIAAAlIATAAIAAglIAJAAIAAAlIATAAIAAglIAJAAIAAAlIAHAAIAAATgAOWARQgHgHAAgKQAAgKAHgGQAGgIAJABQALgBAFAJIAAgHIAJAAIAAAtIgJAAIAAgHQgFAIgLAAQgJAAgGgHgAOdgLQgEAFAAAGQAAAHAEAFQAEADAGAAQAGAAAEgDQAEgFAAgHQAAgGgEgFQgEgFgGABQgGgBgEAFgAM2ARQgHgHAAgKQAAgJAHgHQAHgIALABQANgBAGAKIgGAFQgEgGgJAAQgHAAgEAEQgEAFAAAGQAAAHAEAEQAEAFAHgBQAJAAAEgFIAGAFQgGAJgNAAQgLAAgHgHgAKPARQgHgHAAgKQAAgKAHgGQAGgIALABQAKgBAHAIQAHAGAAAKQAAAKgHAHQgHAHgKAAQgLAAgGgHgAKWgLQgFAFAAAGQAAAHAFAFQAEADAGAAQAGAAAEgDQAFgFAAgHQAAgGgFgFQgEgEgGAAQgGAAgEAEgAFsAXIABgIIACAAQAEAAABgCIACgMIAAgXIAmAAIAAAtIgJAAIAAglIgUAAIAAAPQgBAMgDAGQgDAFgIAAgADsARQgHgHAAgKQAAgKAHgHQAGgGAKAAQAKAAAHAGQAGAGAAAKIAAADIglAAQACAOAOAAQAIAAAHgFIAEAFQgGAIgNAAQgLAAgHgHgADvgEIAbAAQgCgMgMAAQgMAAgBAMgAAYAXIABgIIADAAQAFAAACgEQABgGAAgNIABgkIAvAAIAABDIgJAAIAAg6IgdAAIAAAbQgBASgDAGQgEAIgJAAgAgQARQAAgFAGAAQABAAAAAAQABAAABAAQAAAAABABQAAAAABABQAAAAABAAQAAABAAAAQABABAAAAQAAABAAAAQAAAHgHAAQgGAAAAgHgAicARQgGgHAAgKQAAgJAGgHQAHgIALABQANgBAHAKIgGAFQgFgGgJAAQgHAAgEAEQgEAFAAAGQAAAHAEAEQAFAFAGgBQAJAAAFgFIAGAFQgHAJgNAAQgLAAgHgHgAliARQgHgHAAgKQAAgKAHgHQAGgGALAAQAKAAAGAGQAHAGAAAKIgBADIgkAAQABAOAOAAQAJAAAGgFIAFAFQgHAIgNAAQgLAAgHgHgAlfgEIAbAAQgBgMgMAAQgMAAgCAMgAmjAXIABgIIADAAQADAAACgCIABgMIABgXIAlAAIAAAtIgJAAIAAglIgUAAIAAAPQgBANgCAFQgEAFgIAAgAnUARQgGgHAAgKQAAgKAGgGQAGgIAKABQAKgBAFAJIAAgHIAJAAIAAAtIgJAAIAAgHQgFAIgKAAQgKAAgGgHgAnNgLQgEAFAAAGQAAAHAEAFQAEADAGAAQAPABAAgQQAAgGgEgFQgEgFgHABQgGgBgEAFgAoKAQIAFgFQAGAFAJAAQALABAAgIQAAgGgJAAIgKAAIAAgGIAIAAQAKABAAgIQAAgGgKAAQgIAAgFAFIgFgFQAGgHANAAQARgBAAANQAAAIgHADQAJABAAAJQAAAGgFAEQgGAEgJAAQgNAAgHgIgApKARQgGgHAAgKQAAgJAGgHQAHgIALABQANgBAHAJIgGAFQgFgGgJAAQgNAAgCANIAXAAIAAAGIgXAAQABANAOAAQAJABAFgHIAGAFQgGAJgOAAQgLAAgHgHgAqDARQgGgHAAgKQAAgKAGgGQAGgIAJABQALgBAFAJIAAgHIAJAAIAAAtIgJAAIAAgHQgFAIgLAAQgJAAgGgHgAp8gLQgEAFAAAGQAAAHAEAFQAEADAGAAQAPABAAgQQAAgGgEgFQgEgFgHABQgGgBgEAFgAsrAXIABgIIADAAQADAAACgCIABgMIABgXIAlAAIAAAtIgJAAIAAglIgTAAIgBAPQAAAMgDAGQgDAFgIAAgAwMARQgHgHAAgKQAAgKAHgGQAHgIAKABQALgBAHAIQAHAGAAAKQAAAKgHAHQgHAHgLAAQgKAAgHgHgAwFgLQgEAFAAAGQAAAHAEAFQAEADAGAAQAHAAAEgDQAEgFAAgHQAAgGgEgFQgEgEgHAAQgGAAgEAEgARVAXIAAgSIgKAAIgLASIgKAAIAMgTQgLgCAAgKQAAgOASAAIAVAAIAAAtgARAgIQAAAIAKgBIALAAIAAgOIgLAAQgKgBAAAIgAQiAXIAAgUIgXAAIAAAUIgJAAIAAgtIAJAAIAAASIAXAAIAAgSIAJAAIAAAtgAPsAXIAAgUIgXAAIAAAUIgKAAIAAgtIAKAAIAAASIAXAAIAAgSIAJAAIAAAtgANxAXIAAglIgQAAIAAgIIAqAAIAAAIIgRAAIAAAlgAMcAXIAAghIgYAhIgIAAIAAgtIAIAAIAAAhIAZghIAIAAIAAAtgAJ6AXIgMgTQAAAAgBAAQAAgBAAAAQgBAAAAAAQgBAAAAAAIgHAAIAAAUIgKAAIAAgtIAKAAIAAASIAHAAQABAAAAgBQABAAAAAAQAAAAAAAAQABgBAAAAIAMgQIALAAIgRAVIARAYgAJEAXIAAghIgYAhIgIAAIAAgtIAJAAIAAAhIAYghIAIAAIAAAtgAHxAXIAAgtIAVAAQARgBAAAMQAAAIgGADQAIABAAAJQAAANgQAAgAH6AQIANAAQAJAAAAgGQAAgIgJABIgNAAgAH6gDIALAAQAJABAAgIQAAgFgJAAIgLAAgAHFAXIAAgSIgKAAIgLASIgKAAIAMgTQgLgCAAgKQAAgOASAAIAWAAIAAAtgAGwgIQAAAIAKgBIALAAIAAgOIgLAAQgKgBAAAIgACaAXIAAgtIAJAAIAAAlIATAAIAAglIAJAAIAAAlIATAAIAAglIAJAAIAAAtgACEAXIAAghIgYAhIgIAAIAAgtIAIAAIAAAhIAZghIAIAAIAAAtgAg+AXIAAgtIAJAAIAAAQIAKAAQAUAAAAAOQAAAPgUAAgAg1APIAKAAQAKAAAAgHQAAgIgKAAIgKAAgAhgAXIAAglIgQAAIAAgIIApAAIAAAIIgQAAIAAAlgAi2AXIAAgtIAJAAIAAAtgAjMAXIAAgUIgXAAIAAAUIgJAAIAAgtIAJAAIAAASIAXAAIAAgSIAJAAIAAAtgAkAAXIgLgTQAAAAgBAAQAAgBAAAAQgBAAAAAAQgBAAAAAAIgEAAIAAAUIgJAAIAAgUIgDAAQgBAAAAAAQgBAAAAAAQgBAAAAABQAAAAAAAAIgMATIgKAAIAPgYIgPgVIAKAAIAMAQQAAAAAAABQAAAAABAAQAAAAAAAAQABABAAAAIAEAAIAAgSIAJAAIAAASIAEAAQABAAAAgBQABAAAAAAQAAAAAAAAQABgBAAAAIALgQIAKAAIgPAVIAQAYgAqXAXIgMgTQgBAAAAAAQAAgBgBAAQAAAAgBAAQAAAAgBAAIgHAAIAAAUIgJAAIAAgtIAJAAIAAASIAIAAQAAAAABgBQAAAAAAAAQABAAAAAAQAAgBAAAAIANgQIAKAAIgQAVIAQAYgArNAXIAAghIgYAhIgJAAIAAgtIAJAAIAAAhIAYghIAJAAIAAAtgAs6AXIgMgTQAAAAgBAAQAAgBAAAAQgBAAAAAAQgBAAAAAAIgHAAIAAAUIgKAAIAAgtIAKAAIAAASIAHAAQABAAAAgBQABAAAAAAQAAAAAAAAQABgBAAAAIAMgQIALAAIgRAVIARAYgAtwAXIAAghIgYAhIgIAAIAAgtIAJAAIAAAhIAYghIAIAAIAAAtgAvDAXIAAgtIAVAAQARgBAAAMQAAAIgGADQAIABAAAJQAAANgQAAgAu6AQIANAAQAJAAAAgGQAAgIgJABIgNAAgAu6gDIALAAQAJABAAgIQAAgFgJAAIgLAAgAi3gnQAAgFAGgBQAGABAAAFQAAAGgGAAQgGAAAAgGgAo2g2IABgHIAGABQAHgBAEgJIACgGIgTguIAJAAIAPAkIAOgkIAKAAIgWAzQgEALgEADQgEAFgHAAIgIgCgACCg2IAAhEIAJAAIAAAHQAGgIAKAAQAJAAAGAGQAHAHAAAKQAAALgHAHQgGAHgJAAQgKAAgGgIIAAAdgACPhvQgEAFAAAGQAAAIAEAFQAEADAGAAQAGAAAEgDQAEgFAAgIQAAgGgEgFQgEgFgGABQgGgBgEAFgAlug2IAAhEIAJAAIAAAHQAGgIAKAAQAJAAAGAGQAHAHAAAKQAAALgHAHQgGAHgJAAQgKAAgGgIIAAAdgAlhhvQgEAFAAAGQAAAIAEAFQAEADAGAAQAPABAAgRQAAgGgEgFQgEgFgHABQgGgBgEAFgASFg/QAHgGABgHQgGAAAAgGQAAgFAGAAQAHgBAAAJQAAALgMAKgAO8hSQgHgHAAgKQAAgKAHgIQAGgGALAAQAKAAAHAGQAHAIAAAKQAAAKgHAHQgHAHgKAAQgLAAgGgHgAPChvQgEAEAAAIQAAAHAEAFQAEADAHAAQAGAAAEgDQAFgFAAgHQAAgIgFgEQgEgEgGAAQgHAAgEAEgAIyhSQgHgHAAgLQAAgJAHgIQAGgGALAAQAOAAAGAJIgGAFQgFgGgJAAQgGAAgEAEQgFAFAAAGQAAAIAEAEQAFAEAGAAQAJABAFgHIAGAGQgGAJgOAAQgKAAgHgHgAFRhMIACgIIACAAQAEAAABgCIABgNIABgXIAlAAIAAAuIgJAAIAAgmIgTAAIgBAPQAAANgDAFQgDAGgIAAgAEkhSQgHgHAAgKQAAgKAHgIQAHgGAKAAQALAAAHAGQAGAIAAAKQAAAKgGAHQgHAHgLAAQgKAAgHgHgAErhvQgFAEAAAIQAAAHAFAFQAEADAGAAQAHAAAEgDQAEgFAAgHQAAgIgEgEQgFgEgGAAQgGAAgEAEgADuhTIAFgFQAGAFAIAAQAMAAAAgHQAAgHgKABIgJAAIAAgHIAHAAQAKABAAgIQAAgGgJAAQgIAAgGAFIgFgFQAGgIANABQASAAAAAMQAAAIgHADQAJACAAAJQAAAGgFAEQgGAEgKAAQgMAAgHgIgADAhSQgHgHAAgKQAAgKAHgIQAGgGALAAQAKAAAHAGQAHAIAAAKQAAAKgHAHQgHAHgKAAQgLAAgGgHgADGhvQgEAEAAAIQAAAHAEAFQAEADAHAAQAGAAAEgDQAEgFAAgHQAAgIgEgEQgEgEgGAAQgHAAgEAEgABQhSQgHgHAAgKQAAgLAHgHQAGgHAKABQAKgBAHAHQAGAGAAAKIAAAEIgkAAQABAOAOAAQAIAAAHgFIAFAFQgHAIgNAAQgLAAgHgHgABThnIAbAAQgBgNgNAAQgMAAgBANgAgfhSQAAgFAGAAQABAAAAAAQABAAABAAQAAAAABABQAAAAABABQAAAAABAAQAAABAAAAQABABAAAAQAAABAAAAQAAAHgHAAQgGAAAAgHgAkChTIAFgFQAFAFAJAAQAMAAAAgHQAAgHgKABIgJAAIAAgHIAHAAQAKABAAgIQAAgGgJAAQgIAAgGAFIgFgFQAGgIANABQASAAAAAMQAAAIgHADQAJACAAAJQAAAGgGAEQgFAEgKAAQgNAAgGgIgAn8hSQgGgHAAgLQAAgJAGgIQAHgGALAAQAOAAAFAJIgFAFQgFgGgJAAQgHAAgEAEQgEAFAAAGQAAAIAEAEQAEAEAHAAQAJABAFgHIAFAGQgFAJgOAAQgLAAgHgHgAp0hSQgGgHAAgLQAAgJAGgIQAHgGALAAQANAAAHAIIgGAFQgEgGgKAAQgNAAgCANIAXAAIAAAHIgXAAQACANAOAAQAIAAAFgGIAGAFQgGAJgOAAQgLAAgHgHgAqthSQgGgHAAgLQAAgKAGgHQAGgGAKAAQAKAAAFAIIAAgHIAJAAIAAAuIgJAAIAAgHQgFAIgKAAQgKAAgGgHgAqmhvQgEAFAAAGQAAAIAEAFQAEADAGAAQAPABAAgRQAAgGgEgFQgEgFgHABQgGgBgEAFgAsUhRQgGgGgBgJIgIAAIAAAUIgJAAIAAguIAJAAIAAASIAIAAQAEgTATAAQAKAAAHAGQAGAIAAAJQAAALgGAHQgHAHgKAAQgJAAgHgGgAsShkQAAARAOgBQAGAAAEgEQAEgEAAgIQAAgPgOAAQgOAAAAAPgAtphMIABgIIADAAQADAAACgCIABgNIABgXIAlAAIAAAuIgJAAIAAgmIgTAAIgBAPQAAANgDAFQgDAGgIAAgAxIhSQgHgHAAgKQAAgLAHgHQAGgHAKABQAKgBAHAHQAGAGAAAKIAAAEIglAAQACAOAOAAQAIAAAHgFIAEAFQgGAIgNAAQgLAAgHgHgAxGhnIAcAAQgCgNgMAAQgLAAgDANgARzhMIAAgUIgXAAIAAAUIgJAAIAAguIAJAAIAAASIAXAAIAAgSIAJAAIAAAugAQ9hMIAAgiIgZAiIgIAAIAAguIAJAAIAAAiIAYgiIAIAAIAAAugAP6hMIAAgmIgQAAIAAgIIApAAIAAAIIgQAAIAAAmgAOnhMIgMgSQAAgBgBAAQAAgBAAAAQgBAAAAAAQgBAAAAAAIgHAAIAAAUIgKAAIAAguIAKAAIAAASIAHAAQABAAAAgBQABAAAAAAQAAAAAAAAQABgBAAAAIAMgQIALAAIgRAVIARAZgANxhMIAAguIAJAAIAAAugANahMIAAgUIgXAAIAAAUIgJAAIAAguIAJAAIAAASIAXAAIAAgSIAJAAIAAAugAL0hMIAAguIAKAAIAAAQIAKAAQATAAAAAPQAAAPgTAAgAL+hUIAJAAQALAAAAgHQAAgIgLAAIgJAAgALShMIAAgmIgQAAIAAgIIApAAIAAAIIgQAAIAAAmgAKwhMIAAgiIgYAiIgIAAIAAguIAIAAIAAAiIAYgiIAJAAIAAAugAJthMIAAgmIgQAAIAAgIIApAAIAAAIIgQAAIAAAmgAIXhMIAAguIAKAAIAAAugAIBhMIAAgiIgPAVIgGAAIgPgVIAAAiIgJAAIAAguIAJAAIASAXIASgXIAJAAIAAAugAGPhMIAAguIAJAAIAAAQIAKAAQATAAAAAPQAAAPgTAAgAGYhUIAJAAQALAAAAgHQAAgIgLAAIgJAAgAA7hMIgFgOIgfAAIgFAOIgJAAIAahEIAHAAIAbBEgAAahhIAZAAIgNghgAhPhMIAAguIAVAAQARgBAAAMQAAAIgHADQAJACAAAJQAAANgRAAgAhGhTIAMAAQAKAAAAgHQAAgGgKAAIgMAAgAhGhnIAKAAQAKABAAgIQAAgFgKAAIgKAAgAhmhMIAAguIAJAAIAAAugAh5hMIgMgSQgBgBAAAAQAAgBgBAAQAAAAgBAAQAAAAgBAAIgHAAIAAAUIgJAAIAAguIAJAAIAAASIAIAAQAAAAABgBQAAAAAAAAQABAAAAAAQAAgBAAAAIANgQIAKAAIgQAVIAQAZgAivhMIAAgiIgYAiIgJAAIAAguIAJAAIAAAiIAYgiIAJAAIAAAugAkUhMIAAgiIgYAiIgJAAIAAguIAJAAIAAAiIAYgiIAJAAIAAAugAmXhMIgNgSIgNASIgKAAIASgYIgSgWIALAAIAMARIANgRIALAAIgSAWIASAYgAnNhMIAAguIAJAAIAAAugArHhMIAAgTQgGADgHgBQgSAAAAgQIAAgNIAKAAIAAAMQAAAJAKAAQAGABAFgDIAAgTIAJAAIAAAugAt4hMIgMgSQAAgBgBAAQAAgBAAAAQgBAAAAAAQgBAAAAAAIgHAAIAAAUIgKAAIAAguIAKAAIAAASIAHAAQABAAAAgBQABAAAAAAQAAAAAAAAQABgBAAAAIAMgQIALAAIgRAVIARAZgAuuhMIAAgiIgYAiIgIAAIAAguIAJAAIAAAiIAYgiIAIAAIAAAugAwBhMIAAguIAVAAQARgBAAAMQAAAIgGADQAIACAAAJQAAANgQAAgAv4hTIANAAQAJAAAAgHQAAgGgJAAIgNAAgAv4hnIALAAQAJABAAgIQAAgFgJAAIgLAAgAxlhMIAAgfIgjAAIAAAfIgJAAIAAhEIAJAAIAAAdIAjAAIAAgdIAKAAIAABEgANviLQAAgFAGgBQAGABAAAFQAAAGgGAAQgGAAAAgGgAIWiLQAAgFAGgBQAGABAAAFQAAAGgGAAQgGAAAAgGgAhniLQAAgFAGgBQAGABAAAFQAAAGgGAAQgGAAAAgGgAnPiLQAAgFAGgBQAGABAAAFQAAAGgGAAQgGAAAAgGg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.urText, new cjs.Rectangle(-117.6,-14.5,235.4,29.1), null);


(lib.t2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AIyB7IAAi3IAjAAIAAANQAGgIAKgEQAJgFAMAAQAQAAANAJQAOAIAGAPQAIAPAAASQAAASgIAPQgHAPgNAIQgOAJgPAAQgLAAgKgFQgJgEgHgIIAABKgAJigcQgHAEgEAIQgDAHAAAKQAAAJADAIQAEAHAHAFQAHAEAJAAQAJAAAHgEQAGgFAEgHQAEgIgBgJQABgKgEgHQgEgIgGgEQgHgEgJAAQgJAAgHAEgAmEBdIAAgfIhaAAIAAAfIgeAAIAAg8IAPAAQAEgHADgLQADgKABgSIACgvIBoAAIAABdIATAAIAAA8gAnAgLQgBAQgCAKQgCAKgEAIIAuAAIAAhAIgkAAgAARA+QgFgDgDgEQgDgGAAgGQAAgFADgFQADgFAFgDQAFgDAGAAQAGAAAFADQAEADAEAFQACAFAAAFQAAAGgCAGQgEAEgEADQgFAEgGAAQgGAAgFgEgAMbA+IAAgwIgsAAIAAAwIgkAAIAAh6IAkAAIAAAtIAsAAIAAgtIAjAAIAAB6gAG/A+IAAh6IBcAAIAAAdIg5AAIAABdgAEKA+IAng6IgKABQgQAAgPgHQgOgHgJgOQgHgOgBgSQAAgTAJgNQAJgPAPgIQAQgJASAAQAUABAOAHQAPAIAJAPQAIAOAAARQABAPgFAMQgEAMgLAQIgrBAgAEchTQgIAFgDAHQgFAGAAAKQAAAKAFAGQADAHAIAEQAHAFAJAAQAIAAAIgFQAIgFADgGQAFgIgBgIQAAgJgDgIQgFgHgHgEQgGgDgKAAQgKAAgGADgACpA+IAAiOIgwAWIAAghIA2gYIAdAAIAACxgAh7A+IAAh6IA7AAQAYAAALAJQAMAIAAAQQAAAKgFAGQgEAHgHADQAVAGAAAVQAAALgFAIQgFAIgKAFQgLAEgOAAgAhZAmIAXAAQATAAAAgOQABgHgFgDQgFgCgKAAIgXAAgAhZgKIATAAQAKAAAEgDQAGgEAAgGQAAgGgGgDQgEgDgKgBIgTAAgAi+A+IAAh6IAjAAIAAB6gAkBA+IAAgwIgsAAIAAAwIgkAAIAAh6IAkAAIAAAtIAsAAIAAgtIAjAAIAAB6gAp3A+IAAggIhZAAIAAgaIBQh3IAsAAIAABzIAWAAIAAAeIgWAAIAAAggAqnAAIAwAAIAAhJgAsNA+IAAiOIgwAWIAAghIA2gYIAcAAIAACxgAi3hUQgFgDgDgEQgCgFAAgGQAAgFACgFQADgEAFgDQAGgDAEAAQAHAAAEADQAFADACAEQADAFABAFQgBAGgDAFQgCAEgFADQgEADgHAAQgEAAgGgDg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t2, new cjs.Rectangle(-83,-12.3,166,24.6), null);


(lib.t1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AlrB5IAAi1IAZAAIAAASQAPgVAaAAQAZAAAQASQARASAAAbQAAAcgRASQgQASgZAAQgaAAgPgWIAABPgAlIgeQgLAMAAASQAAATALALQAKAMARAAQAQAAALgMQAKgLAAgTQAAgSgKgMQgLgLgQAAQgRAAgKALgAmYBcIAAggIhkAAIAAAgIgUAAIAAg0IANAAQAKgLABgmIADgzIBgAAIAABkIATAAIAAA0gAnggHQgCAigHANIA8AAIAAhQIgyAAgAHHAmQgagbAAgnQAAgoAagaQAagaAnAAQAnAAAZAaQAbAaAAAoQAAAngbAbQgZAagnAAQgnAAgagagAHZhOQgTAUAAAeQAAAeATATQASATAdAAQAdAAASgTQATgTAAgeQAAgegTgUQgSgTgdAAQgcAAgTATgAjKAuQgRgSAAgcQAAgbARgSQARgSAYAAQAbAAAOAVIAAgSIAZAAIAAB4IgZAAIAAgSQgOAWgbAAQgYAAgRgSgAi4geQgLAMABASQgBATALALQALAMAQAAQARAAALgMQAKgLAAgTQAAgSgKgMQgLgLgRAAQgQAAgLALgAtVAtQgRgSAAgbQAAgaARgSQARgTAeAAQAjAAAQAXIgPAPQgOgQgWAAQgRAAgMAMQgLALAAASQAAASALAMQALALASAAQAWAAAOgQIAPAPQgIALgNAGQgOAHgQAAQgdAAgSgTgAviAtQgSgSAAgbQAAgbARgSQASgSAaAAQAaAAARARQARARAAAZIgBAKIhgAAQACARALAKQALAJARAAQAYAAAOgOIAOAQQgIAJgPAFQgOAGgQAAQgdAAgRgTgAvPgiQgKAIgCAQIBIAAQgCgPgKgJQgKgJgOAAQgPAAgJAJgAQQA5QgRgGgKgLIAMgSQAVATAfAAQARAAALgHQALgIAAgOQAAgUgxgQQgygQAAghQAAgWARgNQARgMAbAAQAnAAAVAVIgLASQgUgRgcAAQgRAAgKAHQgLAGAAAMQAAANAQAIIAiAMQAyAQgBAkQAAAYgRAOQgRANgdAAQgUAAgRgGgANJA8IAAixIA6AAQArAAAZAYQAaAYAAApQAAApgaAYQgZAXgrAAgANiAmIAfAAQAhAAASgQQAUgRAAghQAAgggUgSQgSgRghAAIgfAAgAMEA8IhniJIAACJIgYAAIAAixIAYAAIBnCKIAAiKIAYAAIAACxgAEUA8IAAixIBFAAQAZAAANANQAOAMAAAVQAAAdgWAKQAOAFAJAMQAHAMAAAPQAAAVgOAOQgOANgYAAgAEtAnIAuAAQAQAAAJgIQAIgIAAgNQAAgdghAAIguAAgAEtgoIAnAAQAhAAAAgcQAAgbghAAIgnAAgABSA8IAAh4IA3AAQAWAAALAJQAMAIAAAPQAAAUgSAHQAXAFAAAXQAAAPgLAJQgLAJgWAAgABpArIAhAAQAaAAAAgSQAAgSgaAAIghAAgABpgIIAbAAQAaAAAAgSQAAgQgaAAIgbAAgAAYA8IAAhXIg/BXIgVAAIAAh4IAWAAIAABYIA/hYIAWAAIAAB4gAq5A8IAAhkIgqAAIAAgUIBsAAIAAAUIgpAAIAABkgAw8A8IAAibIg3AAIAAgWICIAAIAAAWIg4AAIAACbgApoADIAAgUIBRAAIAAAUgAgihbQgMgKgCgSIATAAQADAUAVAAQASAAADgUIATAAQgCASgLAKQgMAKgPAAQgRAAgMgKg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1, new cjs.Rectangle(-114,-12.1,228.1,24.2), null);


(lib.r_part = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhijHQBSAAA5A7QA6A6AABSQAABTg6A6Qg5A7hSAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.r_part, new cjs.Rectangle(-9.9,-20,19.9,40), null);


(lib.logo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFDFB").s().p("AETBdQgCgFACgFQADgGAFgCQAFgCAFACQAEACADAFQAJARAaAFQANADANgBQAOgCAJgIQAIgHAAgMQABgMgJgHQgHgGgXgGQgkgIgNgGQgZgNAAgaQAAgWAOgQQAPgOAYgEQAPgBAPADQAeAFARAUQADAFgBAGQAAAGgEADQgFADgFAAQgGgBgDgEQgMgOgVgDIgTgBIAAABQgdADAAAZQAAARAeAEQAoAJAPAIQAbAQAAAeQAAAXgPAPQgQAPgZADIgKAAQg8AAgTgogACvCFQgcAAgWgVQgUgWgBgeQgCgaACgbIAAgCQABgbAVgUQAUgUAcgBQAQgBACAOQABANgRACQghADgKAeIgBAKQgCAYABAbQABAUAOAOQANANATgBQASABAOgNQANgOABgUIABivQAAgHAEgFQAEgEAGAAQAFAAAEAEQAEAFABAHIAACwQgCAegVAWQgUAVgdAAgAA2CBQgEgFAAgGIgBhpQABgUgMgOQgNgNgTgCIgEAAQgSACgNANQgMAOAAAUIAABpQAAAGgEAFQgEAFgGgBQgFABgFgFQgDgFAAgGIAAhqQgBgfAVgVQAUgWAegBIAEAAQAeABAVAWQAUAVAAAfIAABjIAAAHQAAAGgEAFQgEAFgFgBQgGABgEgFgAisCFQgdAAgVgVQgUgWgCgeQgBgaABgbQACgcAVgVQAVgUAdgBIADAAQAdABAVAUQAWAVABAcIAAA1QgBAegVAWQgVAVgdAAgAjKgXQgMAMgCATQgBAaABAZQACAUAMAOQAOANATgBQASABANgNQAOgOABgUQABgZgBgaQgCgTgNgMQgMgNgTAAQgUAAgNANgAlbCFQgeAAgUgVQgVgWgBgeIAAiwQAAgHAEgFQAEgEAFAAQAGAAAEAEQAFAGAAAGQgCCJACAmQABAUAOAOQANANASgBQASABAOgNQANgOABgUQACgZgCgaIgCgKQgIgdgigFQgQgBABgNQABgOARABQAbABAVAUQAUAUABAbIAAACQACAbgCAaQgBAegUAWQgVAVgdAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.logo, new cjs.Rectangle(-42,-13.3,84,26.7), null);


(lib.l_part = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgoCNQg7g6AAhTQAAhSA7g6QA5g7BTAAIAAGPQhTAAg5g7g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.l_part, new cjs.Rectangle(-9.9,-20,19.9,40), null);


(lib.dev_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.dev();
	this.instance.parent = this;
	this.instance.setTransform(-150,-255);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.dev_1, new cjs.Rectangle(-150,-255,559,558), null);


(lib.btn_txt = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#35303E").s().p("AjsA8IAAgUIhJAAIAAAUIgNAAIAAghIAKAAQACgBACgHIADgNIAChAIBDAAIAABVIANAAIAAAhgAkjgNQAAAPgBAJQgCALgDAFIAvAAIAAhJIgoAAgADTAlQgIgEgFgIQgEgJAAgKQAAgIAEgJQAEgHAJgFQAIgGAKAAQAKABAHADQAHACAFAIIgJAIQgCgEgGgDQgGgCgGAAQgFABgGACQgFACgDAGQgCAEAAAHQAAAIACAEQADAFAFADQAFAEAGAAQAGgBAGgDQAGgBACgGIAJAJQgEAGgHAEQgKADgIABQgKgBgIgEgAgRAlQgIgFgDgHQgFgJAAgKQAAgJAFgIQADgHAIgFQAHgGAKAAQAFAAAGADQAGAEAEAFIAAgKIANAAIAABDIgNAAIAAgKQgDAGgHADQgGADgFAAQgKAAgHgFgAgJgNQgGADgBAFQgDAFAAAGQAAAIADAEQACAGAFACQAEADAFABQAIgBADgDQAFgBADgHQADgFAAgHQAAgGgDgFQgCgFgGgDQgEgEgHAAQgEAAgFAEgAisAnQgHgDgEgGIAHgHQAFAEAEABQAGADAGAAQAJAAADgEQAFgCAAgGQAAgIgPgBIgOAAIAAgJIALAAQAHAAAEgCQAEgCAAgFQAAgFgEgBQgCgEgIAAQgMABgHAHIgIgIQAGgFAGgDQAGgCAKgBQANABAHAFQAGAEAAAJQAAAFgCAFQgEADgEACQAGABADAEQAEAFAAAGQAAAFgEAGQgDAEgHADQgHACgJABQgKAAgHgDgAEMAoIAAhDIANAAIAAAZIAPAAQANAAAHAEQAHAFAAALQAAALgHAFQgGAGgOAAgAEZAeIAOAAQAPAAAAgMQAAgFgEgEQgEgCgHAAIgOAAgACnAoIAAgxIgkAxIgMAAIAAhDIANAAIAAAxIAjgxIAMAAIAABDgABDAoIAAg3IgXAAIAAgMIA7AAIAAAMIgXAAIAAA3gAg9AoIAAgeIgiAAIAAAeIgNAAIAAhDIANAAIAAAbIAiAAIAAgbIANAAIAABDgAjPAoIAAhDIANAAIAABDgAjNgrIgDgDIgCgEIACgFIADgDIAFgBIADABIAEADIABAFIgBAEIgEADIgDABIgFgBg");
	this.shape.setTransform(0,-0.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.btn_txt, new cjs.Rectangle(-32.3,-6.2,64.7,12), null);


(lib.btn_round = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AiMCNQg7g6AAhTQAAhSA7g6QA6g7BSAAQBTAAA6A7QA7A6AABSQAABTg7A6Qg6A7hTAAQhSAAg6g7g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.btn_round, new cjs.Rectangle(-20,-20,40,40), null);


(lib.btn_bg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Aq3DIQhSAAg6g6Qg7g5AAhTIAAgCQAAhSA7g6QA6g7BSAAIVvAAQBTAAA6A7QA6A6AABSIAAACQAABSg6A6Qg6A6hTAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.btn_bg, new cjs.Rectangle(-89.5,-20,179,40), null);


(lib.bgImg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#337EB1").s().p("AkAP6QiagOh/hSQiGhFhYiAQiZjfBRkwQAviwBbi6IB1jUQAhg7A7hWQB1irCCiAQDhjcENAXQCaAOB/BSQCGBGBYB/QCaDfhSEwQgvCwhbC5QguBdgkA6Ih/DPQh1CqiCCAIAAABQjLDHjvAAQgaAAgagCg");
	this.shape.setTransform(-145.5,100.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Слой_3
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#01A1E5").s().p("AidKtQhtgMhbg7QhggyhBhYQhxicAzjMQAdh1A8h8QAeg/AYgnIBWiJQBPhxBYhUQCZiRC+AWQBtANBbA6QBgAyBABZQBxCagzDNQgdB1g8B9QgeA+gYAmIgYApQgVAogoA4QhPByhZBUQiFB+igAAQgYAAgZgDg");
	this.shape_1.setTransform(171.8,-133.9);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

	// Слой_4
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#0F478A").s().p("AmydfQktgij5ihQkIiLiyj0Qk2mqCMozQBRlFCllXQAzhrA2hgIBsi7QA8huBticQDZk4D0jnQGkmQILA9QErAiD7ChQEHCLCyD0QE3GqiNIzQhRFFilFXQhSCrhBBqIhCBxQg8BuhsCcQjZE4j0DnQluFbm6AAQhDAAhEgIg");
	this.shape_2.setTransform(27.7,4.2);

	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(1));

}).prototype = getMCSymbolPrototype(lib.bgImg, new cjs.Rectangle(-231.5,-202.7,463.1,405.5), null);


(lib.bg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#1253A1").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.bg, new cjs.Rectangle(-150,-300,300,600), null);


(lib.btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_4
	this.instance = new lib.btn_txt();
	this.instance.parent = this;
	this.instance.setTransform(-0.2,8.9);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(12).to({_off:false},0).to({y:0.7,alpha:1},8).wait(1));

	// r_part
	this.instance_1 = new lib.r_part();
	this.instance_1.parent = this;
	this.instance_1.setTransform(10.1,0);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(9).to({_off:false},0).to({x:79.6},8,cjs.Ease.get(1)).to({_off:true},1).wait(3));

	// l_part
	this.instance_2 = new lib.l_part();
	this.instance_2.parent = this;
	this.instance_2.setTransform(-10,0);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(9).to({_off:false},0).to({x:-79.5},8,cjs.Ease.get(1)).to({_off:true},1).wait(3));

	// Слой_5
	this.instance_3 = new lib.btn_bg();
	this.instance_3.parent = this;
	this.instance_3.setTransform(0,0,0.01,1);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(9).to({_off:false},0).to({scaleX:1},8,cjs.Ease.get(1)).wait(4));

	// Слой_1
	this.instance_4 = new lib.btn_round();
	this.instance_4.parent = this;
	this.instance_4.setTransform(0,0,0.012,0.012);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({scaleX:1.2,scaleY:1.2},5,cjs.Ease.get(1)).to({scaleX:1,scaleY:1},4,cjs.Ease.quadInOut).to({_off:true},9).wait(3));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-0.2,-0.2,0.5,0.5);


(lib.banner = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_59 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(59).call(this.frame_59).wait(1));

	// urText
	this.instance = new lib.urText();
	this.instance.parent = this;
	this.instance.setTransform(0,267.8);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:0.801},15).wait(45));

	// btn
	this.instance_1 = new lib.btn("synched",0,false);
	this.instance_1.parent = this;
	this.instance_1.setTransform(-0.4,220.5,1,1,0,0,0,-0.4,0.7);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(30).to({_off:false},0).wait(30));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_15 = new cjs.Graphics().p("AzUCQIAAkfMAmpAAAIAAEfg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(15).to({graphics:mask_graphics_15,x:0,y:-168}).wait(45));

	// t2
	this.instance_2 = new lib.t2();
	this.instance_2.parent = this;
	this.instance_2.setTransform(0,-141.4);
	this.instance_2._off = true;

	var maskedShapeInstanceList = [this.instance_2];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(20).to({_off:false},0).to({y:-166.4},10,cjs.Ease.cubicOut).wait(30));

	// mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	var mask_1_graphics_15 = new cjs.Graphics().p("AzUCQIAAkfMAmpAAAIAAEfg");

	this.timeline.addTween(cjs.Tween.get(mask_1).to({graphics:null,x:0,y:0}).wait(15).to({graphics:mask_1_graphics_15,x:0,y:-206}).wait(45));

	// t1
	this.instance_3 = new lib.t1();
	this.instance_3.parent = this;
	this.instance_3.setTransform(0,-179.2);
	this.instance_3._off = true;

	var maskedShapeInstanceList = [this.instance_3];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(15).to({_off:false},0).to({y:-204.2},10,cjs.Ease.cubicOut).wait(35));

	// logo
	this.instance_4 = new lib.logo();
	this.instance_4.parent = this;
	this.instance_4.setTransform(1,-253.4,1.198,1.198,0,0,0,0.8,0.5);
	this.instance_4.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({alpha:1},15).wait(45));

	// dev
	this.instance_5 = new lib.dev_1();
	this.instance_5.parent = this;
	this.instance_5.setTransform(223,48);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(15).to({_off:false},0).to({x:-51},15,cjs.Ease.cubicOut).wait(30));

	// bgImg
	this.instance_6 = new lib.bgImg();
	this.instance_6.parent = this;
	this.instance_6.setTransform(-28,37);
	this.instance_6.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).to({alpha:1},15).wait(45));

	// bg
	this.instance_7 = new lib.bg();
	this.instance_7.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(60));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-259.5,-300,463.1,600);


// stage content:
(lib._300x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// banner
	this.instance = new lib.banner();
	this.instance.parent = this;
	this.instance.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(40.5,300,463.1,600);
// library properties:
lib.properties = {
	id: '0A6E3F5DF6B342F4AF907DBE848CDF8D',
	width: 300,
	height: 600,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/dev.png", id:"dev"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['0A6E3F5DF6B342F4AF907DBE848CDF8D'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;