(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.cup = function() {
	this.initialize(img.cup);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,162,240);


(lib.phone = function() {
	this.initialize(img.phone);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,130,262);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.wog = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AG5DDQgngRgegcQgdgcgRgmQgQgoAAgsQAAgrAQgoQASgnAegbQAdgeAogQQAqgPAtAAQBFAAA0AfQAwAeAcA3IhmAqQgOgagXgPQgZgQghAAQgwAAgfAgQgfAgAAAtQAAAyAcAeQAfAgA1ABQAmAAAcgTQAagRAFgZIiBAAIAAhTIDsAAQAJAxgLAtQgLArgcAhQgdAigqATQgrATgzAAQguAAgrgQgAgaDDQgogRgegdQgegbgRgmQgQgpAAgrQAAgrAQgoQARgmAegcQAegeAogPQAogQAuAAQAtAAAqAQQAoAPAeAeQAeAcARAmQAQAoAAArQAAArgQApQgRAmgeAbQgeAdgoARQgqAQgtAAQguAAgogQgAgQhNQgfAgAAAtQAAAtAfAgQAeAgAuAAQAtAAAgggQAfggAAgtQAAgtgfggQgggggtAAQguAAgeAggAl7DCQgRgQgIggIgQhHQgQhFgGglIgDAAQgFAkgRBGIgRBHQgGAggTAQQgSARgbAAQgdAAgSgQQgRgRgLggIhulcIB7AAIAqCZIAKAtQAHAmADAaIAEAAQACgbAIglQACgPAHghIAiiWIBqAAIAiCWIALAwQAGAlADAbIAEAAQADgaAHgmQAGgdAEgQIApiZIB7AAIhuFcQgJAggTARQgRAQgcAAQgcAAgTgRg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-73.9,-21.1,148,42.2);


(lib.urText = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AMvAuIAAgHIAOAAQAAAAAAAAQABAAAAgBQAAAAAAAAQAAAAABgBIADgKIgZg0IAKAAIAUArIAQgrIAIAAIgZBBIgEAFIgFABgAJ+AuIAAhHIAIAAIAAAIQAEgFAEgCQAGgCAFAAQALAAAHAHQAGAIAAALQAAAMgGAIQgHAHgLAAQgGAAgFgCQgEgDgDgEIAAAcgAKLgOQgFAFAAAJQAAAKAFAFQAEAFAIAAQAIAAAGgFQADgFAAgKQAAgJgDgFQgGgFgIAAQgIAAgEAFgAoMAmIAAgMIgmAAIAAAMIgIAAIAAgTIAFAAQACgJABgZIAAgKIApAAIAAAsIAGAAIAAATgAorAFIgCAOIAcAAIAAglIgZAAgAquAmIAAgMIgsAAIAAgzIAJAAIAAAsIAdAAIAAgsIAIAAIAAAsIAGAAIAAATgAHEAXQgIgEgDgIQgEgJAAgKQAAgLAEgJQADgIAIgEQAFgEALAAQAKAAAHAEQAHAEAEAIQADAIAAAMQAAALgDAIQgEAIgHAEQgIAFgJAAQgKAAgGgFgAHEgeQgGAHAAAPQAAANAGAIQAFAHALAAQALAAAFgHQAGgHAAgOQAAgQgGgGQgEgHgMAAQgLAAgFAHgAEtAXQgGgFgDgHQgEgKAAgJQAAgLAEgJQADgHAHgFQAGgEAKAAQALAAAHAFQAGAFACAJIgJAAQgCgMgPAAQgLAAgGAHQgFAIAAAOIAAADQADgGAGgDQAGgEAIAAQAHAAAGADQAHADACAFQAEAGAAAFQAAAIgEAFQgDAFgHADQgGADgHAAQgJAAgIgFgAEwgGQgGAEABAGQAAAFACAEIAHAFQAEACAGAAQAIAAAFgEQAFgDAAgJQAAgHgFgEQgFgEgIAAQgJAAgFAFgADmAXQgGgEgEgIQgEgJAAgKQAAgLAEgJQAEgIAGgEQAHgEAKAAQALAAAGAEQAHAEADAIQAEAIAAAMQAAALgEAIQgDAIgHAEQgGAFgLAAQgJAAgIgFgADmgeQgFAHAAAPQAAANAFAIQAGAHALAAQALAAAGgHQAFgHAAgOQAAgPgFgHQgGgHgLAAQgLAAgGAHgAiFAWQgHgFgBgKIAIAAQACANARAAQAJAAAFgEQAEgEABgJQAAgIgFgEQgDgEgKAAQgNAAgEAJIgJAAIACgnIAvAAIAAAIIgoAAIAAAWQAGgHAMAAQAIAAAFADQAGACADAGQAEAGAAAGQgBAHgDAGQgEAFgGADQgIAEgHAAQgMAAgGgGgAjHAXQgHgEgEgIQgDgJAAgKQAAgLADgJQAEgIAHgEQAGgEAKAAQALAAAGAEQAHAEAEAIQAEAIAAAMQAAALgEAIQgEAIgHAEQgHAFgKAAQgJAAgHgFgAjHgeQgGAHABAPQgBANAGAIQAFAHALAAQAMAAAFgHQAGgHAAgOQAAgQgGgGQgFgHgMAAQgLAAgFAHgALBAUQgGgHgBgNQABgMAGgHQAHgHAMAAQANAAAGAHQAIAHAAAMQAAAMgIAIQgGAHgNAAQgMAAgHgHgALIgOQgFAFAAAJQAAAKAFAFQADAFAJAAQAJAAAEgFQAFgFAAgKQAAgJgFgFQgEgFgJAAQgJAAgDAFgACNAWQgHgGgBgKIAIAAQADAOAQAAQALAAAEgEQAEgDAAgJQAAgHgEgEQgEgEgIAAIgHACIgFADIgEgFIAcgYIgnAAIAAgIIAxAAIAAAIIgYATIAFAAQAGAAAFACQAGADACAFQADAFAAAGQAAAHgEAFQgCAEgHAEQgFACgKAAQgNAAgGgFgAANAUQgHgIAAgMQAAgMAHgHQAHgHAMAAQAMAAAHAHQAHAHAAAMQAAANgHAHQgHAHgMAAQgMAAgHgHgAATgOQgEAEAAAKQAAALAEAEQAFAFAIAAQAIAAAFgFQAEgEAAgLQAAgKgEgEQgFgFgIAAQgIAAgFAFgAmLAWQgGgEgCgKIAJAAQABAHADACQAEADAGAAQAIAAADgCQADgCABgFQAAgHgLAAIgHAAIAAgHIAHAAQAJAAAAgIQAAgEgDgCQgFgCgEAAQgGAAgFACQgDADgBAGIgJAAQACgJAGgEQAFgFALAAQAIAAAHAEQAGAEAAAHQgBAJgHACQAJADAAAIQAAAIgGAEQgHAEgKAAQgKAAgFgFgAndAUQgHgIAAgMQAAgMAHgHQAHgHAMAAQAKAAAGAFQAHAFABAKIgJAAQgCgNgNAAQgIAAgEAEQgEADgBAJIAXAAIAAAGIgXAAQABAJADAEQAFAEAIAAQANAAACgNIAJAAQAAAKgIAFQgGAFgKAAQgMAAgHgHgAI3AaIAAgHIAPAAIAAgtIgPAAIAAgHIANAAIABgBIABgBIAAgIIAJAAIAAA+IAPAAIAAAHgABbAaIAAgHIAPAAIAAgtIgPAAIAAgHIANAAIABgBIABgBIAAgIIAJAAIAAA+IAPAAIAAAHgAlFAaIAAgHIAPAAIAAgtIgPAAIAAgHIAOAAIABgBIAAgJIAJAAIAAA+IAQAAIAAAHgAMfAaIgTgaIgJAGIAAAUIgJAAIAAgzIAJAAIAAAXIAagXIAKAAIgVATIAXAggAH7AaIAAgIIAigYIAHgIQACgFAAgDQAAgPgQAAQgRAAgBASIgJAAQABgMAHgHQAGgGANAAQALAAAHAFQAGAGABALQgBAIgFAGQgEAFgIAGIgWAPIApAAIAAAIgAF4AaIAAgIIAigYQAFgEADgEQABgDAAgFQAAgPgQAAQgRAAgBASIgJAAQABgMAHgHQAHgGAMAAQAMAAAGAFQAHAGAAALQAAAIgEAGQgGAGgIAFIgVAPIAoAAIAAAIgADGAaIAAgLIALAAIAAALgAgNAaIAAgsIgdAAIAAAsIgJAAIAAgzIAuAAIAAAzgAjnAaIAAgLIALAAIAAALgAkUAaIAhg9IgrAAIAAgIIAzAAIAAAIIggA9gAn5AaIAAgzIAIAAIAAAzgApkAaIAAgWIgQAAIgGABQAAAAAAAAQgBABAAAAQAAAAgBABQAAAAAAABIgBAHIgBAGIgBAFIgJAAQACgEABgJQAAgFACgDQABgCAEgCQgDgBgDgDQgCgDAAgFQAAgGAEgEQAFgEAJAAIAZAAIAAAzgAp7gQQgCACAAAEQAAAIAJAAIAQAAIAAgQIgRAAQgFAAgBACgAqcAaIAAgzIAIAAIAAAzgArtAaIgTgaIgJAGIAAAUIgJAAIAAgzIAJAAIAAAXIAagXIALAAIgVATIAXAggAskAaIgHgSIgkAAIgGASIgJAAIAchFIAMAAIAcBFgAsuAAIgPgkIgOAkIAdAAgAn6gjIAAgKIAKAAIAAAKgAqdgjIAAgKIAKAAIAAAKg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.urText, new cjs.Rectangle(-86.3,-4.5,172.7,9.1), null);


(lib.txt = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAdA8IAAhUIg2BUIghAAIAAh3IAeAAIAABTIA2hTIAhAAIAAB3g");
	this.shape.setTransform(88.7,0.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAoBKIAAgcIhQAAIAAAcIgdAAIAAg0IAMAAQACgNABgNIAChFIBrAAIAABfIAPAAIAAA0gAgcAWIA0AAIAAhHIgvAAQgBAxgEAWg");
	this.shape_1.setTransform(73.8,2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgRAxQgRgOgCgYIgWAAIAAAxIgeAAIAAh4IAeAAIAAAvIAWAAQADgXARgOQAQgMAZAAQAeAAARARQARAQAAAdQAAAegRAQQgQARgfAAQgaAAgQgOgAABgcQgIAIABAUQgBAUAIAJQAHAKARAAQARAAAIgKQAIgJAAgUQAAgUgIgIQgIgLgRAAQgQAAgIALg");
	this.shape_2.setTransform(56.5,0.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAgA8IAAhfIgrAAQAAAfgCAYQgBARgEAJQgEAJgGACQgIADgKAAIgQAAIAAgZIAOAAQAEAAABgDQACgHABgPIABhFIBmAAIAAB3g");
	this.shape_3.setTransform(38.1,0.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgtAuQgRgQAAgeQAAgSAIgPQAIgPAOgGQAOgIASAAQAdAAARARQARAQAAAdIgBAJIhfAAQADAfAfgBQAKAAAHgCQAGgDAEgHIAfAAQgFARgPAKQgQAJgWAAQgdAAgRgRgAAggLQgCgOgIgHQgHgHgPAAQgOAAgIAHQgIAHgDAOIBBAAIAAAAg");
	this.shape_4.setTransform(18.6,0.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AApBKIAAgcIhRAAIAAAcIgeAAIAAg0IANAAQADgLAAgPIAChFIBrAAIAABfIAQAAIAAA0gAgcAWIA1AAIAAhHIgwAAQAAAsgFAbg");
	this.shape_5.setTransform(4.1,2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgRAgIAAgSIAOAAQABAAAAgBQAAAAABAAQAAAAAAgBQAAAAAAAAIAAgKIgQAAIAAggIAjAAIAAAnQAAALgGAGQgGAFgKABg");
	this.shape_6.setTransform(-11.8,6.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAdA8IAAhUIg2BUIghAAIAAh3IAeAAIAABTIA1hTIAiAAIAAB3g");
	this.shape_7.setTransform(-22.4,0.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAoBKIAAgcIhQAAIAAAcIgdAAIAAg0IAMAAQACgNABgNIAChFIBrAAIAABfIAPAAIAAA0gAgcAWIA0AAIAAhHIgvAAQgBAxgEAWg");
	this.shape_8.setTransform(-37.3,2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgRAxQgQgNgDgZIgWAAIAAAxIgeAAIAAh4IAeAAIAAAvIAWAAQAEgXAQgOQAQgMAaAAQAdAAARARQARAQAAAdQAAAegRAQQgQARgeAAQgbAAgQgOgAAAgcQgHAJAAATQAAATAHAKQAJAKARAAQAQAAAIgKQAIgJAAgUQAAgUgIgIQgIgLgQAAQgRAAgJALg");
	this.shape_9.setTransform(-54.5,0.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgtAuQgRgQAAgeQAAgdARgQQASgRAdAAQAbAAAPAMQAQAOACAXIgeAAQgFgagaAAQgPAAgIALQgJAJABATQgBATAJAKQAHAKAQAAQAaAAAFgZIAeAAQgCAYgQAMQgQANgaAAQgeAAgRgRg");
	this.shape_10.setTransform(-72.2,0.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AhGBRIAAihIBUAAQAZAAAOALQAOALAAAVQAAAagXAJQANAEAHAKQAHAKAAAOQAAAVgPAMQgOAMgcAAgAgnA4IAyAAQAPgBAGgFQAGgEAAgNQAAgMgGgFQgHgGgOABIgyAAgAgngNIAyAAQAOAAAFgGQAGgEAAgLQAAgKgGgGQgFgFgOAAIgyAAg");
	this.shape_11.setTransform(-87.5,-1.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.txt, new cjs.Rectangle(-94.5,-9.6,189.1,19.2), null);


(lib.t1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AL8EnIAAjhIAoAAIAAAXQATgbAkAAQAjAAAVAXQAUAWAAAoQAAAogUAXQgVAWgjAAQgjAAgTgXIAABSgAMvBvQgKANAAAbQAAAbAKANQALANAXAAQAWAAAMgNQAKgNAAgbQAAgbgKgNQgMgMgWAAQgXAAgLAMgABZEnIAAgiIAtAAQAEAAACgEIAHgSIhOipIAtAAIA1B9IAuh9IAqAAIhPDFQgGAQgJAGQgJAGgOAAgAhmEnIAAjhIAnAAIAAAXQATgbAlAAQAjAAAUAXQAUAWAAAoQAAAogUAXQgUAWgjAAQgiAAgTgXIAABSgAgyBvQgLANAAAbQAAAbALANQAKANAWAAQAWAAALgNQALgNAAgbQAAgbgLgNQgLgMgWAAQgWAAgKAMgAldEOIAAgmIhuAAIAAAmIgoAAIAAhHIASAAQAEgWABhLIABggICSAAIAACBIAUAAIAABHgAm7DIIBIAAIAAhiIhBAAQgBBAgGAigARwDaQgWgSgEgiIgcAAIAABCIgqAAIAAiiIAqAAIAAA/IAcAAQAGggAWgRQAWgSAiAAQApAAAWAXQAXAWAAAoQAAAogXAXQgWAWgpAAQgkAAgWgSgASJBvQgLANAAAbQAAAbALANQALANAWAAQAXAAALgNQAKgNAAgbQAAgbgKgNQgLgMgXAAQgWAAgLAMgAEYDWQgXgXAAgoQAAgoAXgWQAXgXApAAQAiAAAWARQAXASADAfIgpAAQgCgSgKgIQgLgIgSAAQgWAAgLAJQgLAJgDAUIBBAAIAAAcIhCAAQADAVALAKQAMAKAWAAQAjAAAGgiIApAAQgDAfgXARQgWARgiAAQgpAAgXgWgAkZDgQgPgNAAgVQAAgZASgMQARgLAmgEQAZgCAIgDQALgFgBgJQAAgLgHgFQgJgFgSAAQgTAAgIAGQgJAGgBANIgnAAQADgaAVgPQATgQAiAAQAhAAATAPQASAQABAbIAABHQgBAFAGAAIAOAAIAAAgIgZAAQgNAAgHgGQgHgHAAgOQgJAOgPAIQgQAJgXAAQgbAAgQgMgAjaCjQgWADgHAFQgIAFAAAKQAAAUAaAAQAWAAAOgNQAOgNAAgXIAAgDQgOAHgZACgArcDgQgPgNAAgVQAAgYASgNQARgLAlgEQAagCAIgDQAKgEAAgKQAAgLgIgFQgIgFgRAAQgUAAgJAGQgHAGgCANIgnAAQADgaAVgPQATgQAiAAQAhAAATAPQASAQAAAbIAABHQABAFAEAAIAPAAIAAAgIgYAAQgbAAgBgbQgTAfgrAAQgcAAgQgMgAqcCjQgWADgIAFQgIAFAAAKQAAAUAbAAQAUAAAOgNQAPgNAAgXIAAgDQgOAHgYACgAxHDgQgPgNAAgVQAAgZASgMQARgLAlgEQAagCAIgDQAKgFAAgJQABgLgJgFQgIgFgSAAQgTAAgJAGQgIAGgBANIgmAAQADgaATgPQAVgQAgAAQAiAAATAPQASAQAAAbIAABHQAAAFAGAAIANAAIAAAgIgXAAQgPAAgGgGQgHgHAAgOQgJAOgPAIQgRAJgVAAQgdAAgPgMgAwHCjQgWADgJAFQgHAFAAAKQAAAUAbAAQAUAAAOgNQAPgNAAgXIAAgDQgPAHgXACgAPCDoIAAiiIAqAAIAACigAKwDoIAAhzIgsBzIgjAAIgqhxIAABxIgpAAIAAiiIA6AAIAsB1IArh1IA5AAIAACigAuTDoIAAiiIBfAAQAaAAAOALQAOAMAAAVQAAAbgZAJQAcAKAAAcQAAAVgPAMQgPALgbAAgAtrDLIAuAAQAOAAAFgEQAGgEgBgLQABgKgGgEQgFgFgOAAIguAAgAtrCIIAsAAQANAAAFgEQAGgEAAgKQAAgLgGgEQgFgEgNAAIgsAAgAyLDoIg0hKIgXAWIAAA0IgpAAIAAiiIApAAIAABCIBFhCIAxAAIhBA9IBIBlgAPBAtIAAglIAsAAIAAAlgAJQhOQgOgMAAgWQgBgYATgMQAQgMAmgDQAagDAHgDQALgEAAgKQAAgKgIgGQgIgFgSAAQgTAAgIAHQgJAFgBAOIgnAAQADgbAUgPQAVgPAgAAQAiAAATAPQASAPABAcIAABGQAAAFAEAAIAOAAIAAAhIgYAAQgOAAgGgHQgHgHgBgNQgTAfgrAAQgcAAgQgNgAKQiKQgWADgIAFQgIAEAAALQABATAaAAQAVAAAOgMQAPgNAAgYIAAgDQgOAHgZADgAhyhYQgWgWgBgoQABgoAWgXQAXgWApAAQApAAAXAWQAWAXAAAoQAAAogWAWQgXAXgpAAQgpAAgXgXgAhUi+QgLANAAAbQAAAbALANQALANAXAAQAXAAALgNQALgNAAgbQAAgbgLgNQgLgNgXAAQgXAAgLANgAnmhOQgPgMABgWQgBgYATgMQARgMAlgDQAZgDAJgDQAKgEAAgKQAAgKgIgGQgIgFgSAAQgTAAgJAHQgIAFgBAOIgnAAQADgbAUgPQAUgPAhAAQAhAAAUAPQASAPAAAcIAABGQAAAFAFAAIAOAAIAAAhIgYAAQgOAAgHgHQgGgHgBgNQgIAOgPAIQgRAJgWAAQgcAAgQgNgAmliKQgXADgIAFQgIAEAAALQAAATAbAAQAVAAANgMQAPgNABgYIAAgDQgPAHgXADgAwThOQgOgMAAgWQAAgYASgMQAQgMAmgDQAZgDAJgDQAKgEAAgKQAAgKgIgGQgJgFgSAAQgSAAgJAHQgIAFgBAOIgnAAQADgbATgPQAVgPAhAAQAhAAATAPQATAPAAAcIAABGQAAAFAFAAIAOAAIAAAhIgZAAQgaAAgBgbQgTAfgsAAQgcAAgPgNgAvTiKQgWADgIAFQgIAEAAALQAAATAbAAQAVAAANgMQAPgNABgYIAAgDQgOAHgZADgAFAhFIAAiiIAqAAIAACBIA2AAIAAiBIApAAIAACBIA2AAIAAiBIAqAAIAACigAD0hFIAAiiIAoAAIAACigAA/hFIAAiiIBfAAQAaAAAPALQAOALAAAVQAAAbgZAJQAbAKAAAcQAAAWgOALQgPAMgbAAgABnhiIAvAAQANAAAGgEQAFgFABgKQgBgLgFgEQgGgEgNAAIgvAAgABnilIAtAAQANAAAFgEQAGgFAAgKQAAgKgGgEQgFgEgNAAIgtAAgAkzhFIAAiiIBgAAQAaAAAOALQAOALAAAVQAAAbgZAJQAcAKAAAcQAAAWgOALQgPAMgbAAgAkJhiIAuAAQANAAAGgEQAFgFAAgKQAAgLgFgEQgGgEgNAAIguAAgAkJilIAsAAQANAAAFgEQAGgFgBgKQABgKgGgEQgFgEgNAAIgsAAgAophFIg1hKIgWAVIAAA1IgqAAIAAiiIAqAAIAABCIBEhCIAyAAIhCA9IBIBlgArphFIAAhzIhLBzIgtAAIAAiiIApAAIAABwIBJhwIAtAAIAACigAxmhFIAAheIhtAAIAABeIgrAAIAAjaIArAAIAABXIBtAAIAAhXIArAAIAADagAs6kFQgPgLgCgWIAjAAQABAKAGAEQAFADALAAQALAAAFgDQAGgEACgKIAjAAQgDAWgPALQgOAMgbAAQgaAAgPgMgADxkBIAAglIAtAAIAAAlg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1, new cjs.Rectangle(-128,-29.5,256,59), null);


(lib.phone_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.phone();
	this.instance.parent = this;
	this.instance.setTransform(-65,-131);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.phone_1, new cjs.Rectangle(-65,-131,130,262), null);


(lib.p3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#8BC53F").s().p("Ah3gYQgOgcAAgfQAAg4AognQAngnA3AAQA3AAAnAnQAnAnAAA4QAAAggNAbIh4Dyg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-13.4,-21.8,26.8,43.7);


(lib.p2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AjPjQQgYgyARg0QATg0AygZQAwgZA1ATQAzARAZAyICqFYQAUAmAAArQAAAsgUAmIhsDdg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-22.2,-40.2,44.3,80.4);


(lib.p1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AjPjQQgZgyATg0QARg0AygZQAygZA1ATQAzARAZAyICqFYQATAmAAArQAAAsgTAmIhuDdg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-22.2,-40.2,44.5,80.4);


(lib.logo_static = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_4
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#8BC53F").s().p("Ag7gLQgGgOAAgQQAAgbATgUQATgTAbAAQAbAAAUATQATAUAAAbQAAAQgHAOIg7B3g");
	this.shape.setTransform(-22.1,-9.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgNhmQgMgZAJgaQAJgaAXgMQAZgNAaAJQAaAJAMAZIBVCqQAJATAAAVQAAAWgJATIg2BtgAi/hmQgMgZAJgaQAJgaAYgMQAZgMAaAIQAaAJAMAZIBUCqQAJATAAAVQAAAWgJATIg1Btg");
	this.shape_1.setTransform(-44.5,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.logo_static, new cjs.Rectangle(-64.4,-19.9,129,39.9), null);


(lib.ic3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ABzMVQgPgOAAgaQAAgaAPgPQAOgOAZAAQAaAAAOAOQAPAPAAAZIAAAJIhUAAQACAbAdAAQARAAAGgMIAaAAQgIAfgpABQgbAAgOgPgAB9LiIA5AAQgDgYgZABQgZgBgEAYgAiMMVQgPgOAAgaQAAgaAPgPQAQgOAaAAQAaAAAPAOQAOAPAAAaQAAAagOAOQgPAPgaAAQgbAAgPgPgAh/LtQAAAhAdAAQAdAAAAghQAAgigdAAQgdAAAAAigAFxMhIAAgUIAogdQAYgRAIgKQAJgKAAgLQAAgZgbAAQgcAAgBAfIgZAAQABgYAOgPQAPgNAZAAQAYAAAOAMQAOALAAAWQAAAZglAbIggAXIBJAAIAAAXgAEOMhIAAgWIAfAAIAAhOIgeAAIAAgVIAbAAQABAAABAAQAAAAABgBQAAAAAAgBQAAgBAAAAIAAgQIAaAAIAAB2IAeAAIAAAWgAA3MhIAAg9QAAgZgYAAQgbAAgBAdIAAA5IgZAAIAAhoIAYAAIAAAOQAMgRAZAAQATAAAMAMQAMAMAAATIAABAgAjIMhIAAg9QAAgZgXAAQgbAAgBAdIAAA5IgaAAIAAiRIAaAAIAAA2QANgQAWAAQAUAAAMANQALAMAAATIAAA/gAmdMhIAAiNIBIAAQAXAAALAMQANALAAAVQAAATgNAMQgLALgXAAIgtAAIAAA3gAmCLVIArAAQAVAAAAgVQAAgVgVgBIgrAAgAnTMhIAAhoIAbAAIAABogAnUKoIAAgYIAcAAIAAAYgAhtJWIAAiRIAYAAIAAAOQANgQAYAAQAWAAAOAOQAMAPAAAaQAAAZgMAOQgOAPgWAAQgXAAgMgPIAAA1gAhUH6QAAAhAdAAQAcAAAAghQAAgjgcABQgdgBAAAjgAD9ISQAAgPAMgIQAKgIAZgCQAQgCAFgCQAHgCAAgHQAAgNgWABQgMAAgFADQgGAEgBAIIgZAAQACgRANgJQANgKAVAAQAuAAAAAlIAAAuQAAAAAAABQABAAAAABQAAAAABAAQABAAAAAAIAJAAIAAAWIgPAAQgSAAAAgSQgMAUgcAAQgmAAAAgegAEwICQgZACAAAMQAAAMARAAQAOAAAJgHQAKgJAAgPIAAgBQgKADgPADgAANISQAAgPAMgIQAKgIAYgCQARgCAFgCQAGgCAAgHQAAgNgVABQgWAAgCAPIgZAAQACgRANgJQANgKAVAAQAVAAANAKQAMAJAAASIAAAuQAAAAAAABQAAAAAAABQABAAAAAAQABAAABAAIAIAAIAAAWIgPAAQgRAAAAgSQgNAUgcAAQglAAAAgegAA/ICQgOAAgFAEQgFADAAAHQAAAMARAAQAOAAAIgHQAKgJAAgPIAAgBQgKADgPADgAHKIuIAAhKIgwBKIgdAAIAAhpIAaAAIAABJIAvhJIAdAAIAABpgACNIuIAAhpIA+AAQAQAAAJAIQAJAHAAANQAAASgPAGQARAGAAASQAAAOgJAHQgKAIgRAAgACnIbIAfAAQAPAAAAgNQAAgLgPAAIgfAAgACnHwIAdAAQAPAAAAgMQAAgMgPAAIgdAAgAjOIuIAAhpIBRAAIAAAVIg3AAIAABUgAkDIuIAAhKIgwBKIgcAAIAAhpIAaAAIAABJIAuhJIAeAAIAABpgAngIuIAAiNIBKAAQAWAAAMAKQAMAKAAASQAAAWgUAIQAXAIAAAZQAAAUgNAJQgNALgXAAgAnFIXIAtAAQAMAAAGgEQAFgEAAgLQAAgKgFgFQgGgEgMAAIgtAAgAnFHaIAsAAQAMABAFgEQAFgEAAgKQAAgSgWAAIgsAAgAGLGdIAXAAQAAALAOAAQAOAAABgLIAXAAQgEAdgiAAQgiAAgDgdgAlwBWQiYiYAAjXQAAjXCYiaQCZiZDXAAQDXAACaCZQCYCaAADXQAADXiYCYQiaCZjXAAQjWAAiaiZgAlbp2QiQCRAADMQAADMCQCPQCRCQDKAAQDLAACRiQQCQiPAAjMQAAjMiQiRQiRiPjLgBQjLABiQCPgAiCBMQgFAAgEgDQgDgEAAgFIAAhqQAAgGADgDQAEgEAFAAIBRAAIAAhFIgSAAQgEgBgEgDQgEgDAAgFIAAg2QgjgPgbgeIgKgMQgrAAgdgfQgogngPhWIgIhTQAAgEAEgEQADgDAFAAIA8AAIACgqQACgLALAAIGOAAQAMAAABALIACAqIA9AAQAFAAADADQAEAEAAAEIgIBTQgPBWgoAoQgfAggqgCIgKAMQgbAfgjAOIAAA2QAAAFgDADQgEADgFABIgRAAIAABFIBRAAQAGAAADAEQAEAEAAAFIAABqQAAAEgEAFQgDADgGAAgAh2AzIDuAAIAAhSIjuAAgAgZg3IAzAAIAAhFIgzAAgAg2iUIBtAAIAAgiQgcAIgbgBIAAAAQgbABgbgIgAAAi6IAAgNQAiACAhgOQAggNAXgaQAvg0APhkQAIg8gEhAIl5AAQgEBAAJA8QAPBkAuA0QAYAaAgANQAgAOAjgCgACnkRQAXgFARgRQAwgwAHiCIgwAAQgDB9gsBLgAj6mFQAOBBAeAdQAPAQAXAGQgrhMgDh8IgvAAQACArAJApg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.ic3, new cjs.Rectangle(-52.1,-80.3,104.3,160.7), null);


(lib.ic2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ABkOwIAAgWIAcAAQABAAAAAAQABAAAAAAQABgBAAAAQAAgBAAAAIAFgMIgyhsIAdAAIAiBQIAdhQIAbAAIgyB/QgGARgTAAgAPvN8QgPgOABgaQgBgaAPgPQAPgOAaAAQAWAAAPALQAOALACAVIgaAAQgEgWgXAAQgdAAAAAiQAAAhAdAAQAXAAAEgVIAaAAQgCAUgOALQgPALgWAAQgaAAgPgOgALwODQgKgJAAgOQAAgdAugDQARgCAFgCQAHgDAAgGQAAgOgWAAQgXAAgBARIgZAAQACgRANgKQAMgKAWAAQAWAAAMAKQALAKABARIAAAuQAAAAAAABQAAABAAAAQABAAAAABQABAAAAAAIAKAAIAAAVIgQAAQgQAAgBgSQgNAUgcAAQgRAAgKgHgAMZNbQgPACgFADQgEAEAAAGQAAANARAAQANAAAIgIQAKgJAAgPIAAgCQgKAFgOABgAiMN8QgPgOAAgaQAAgaAPgPQANgOAZAAQAaAAAPAOQAOAPAAAZIAAAJIhUAAQAEAaAbAAQASAAAFgLIAbAAQgJAfgpAAQgaAAgOgOgAiCNKIA4AAQgDgZgZAAQgZAAgDAZgApMODQgKgJAAgOQAAgdAugDQAQgCAGgCQAGgDAAgGQAAgOgVAAQgXAAgBARIgZAAQACgRANgKQAMgKAWAAQAtAAAAAlIAAAuQAAAAAAABQAAABABAAQAAAAABABQABAAAAAAIAJAAIAAAVIgPAAQgQAAgBgSQgNAUgcAAQgSAAgJgHgAojNbQgPACgGADQgEAEAAAGQAAANARAAQAOAAAIgIQAKgJAAgPIAAgCQgKAFgOABgAs9ODQgJgJgBgOQAAgdAvgDQAPgCAHgCQAGgDAAgGQAAgOgWAAQgWAAgCARIgYAAQACgRAMgKQANgKAVAAQAuAAAAAlIAAAuQAAAAAAABQAAABABAAQAAAAABABQAAAAABAAIAJAAIAAAVIgPAAQgRAAgBgSQgNAUgbAAQgSAAgKgHgAsUNbQgPACgEADQgGAEAAAGQABANAQAAQAOAAAJgIQAKgJAAgPIAAgCQgLAFgOABgAOwOIIAAgrIgwAAIAAArIgaAAIAAhoIAaAAIAAAoIAwAAIAAgoIAbAAIAABogAI9OIIAAhoIAaAAIAABTIAkAAIAAhTIAaAAIAABTIAjAAIAAhTIAbAAIAABogAGpOIIAAgWIAfAAIAAhOIgeAAIAAgVIAbAAQABAAAAAAQABgBAAAAQABgBAAAAQAAgBAAgBIAAgPIAZAAIAAB2IAfAAIAAAWgAAwOIIgigwIgOAOIAAAiIgaAAIAAhoIAaAAIAAAqIArgqIAhAAIgrAnIAuBBgAjLOIIAAgoIgeAAQgmAAAAggIAAggIAbAAIAAAeQAAANAOAAIAbAAIAAgrIAaAAIAABogAmpOIIAAhoIA9AAQAQAAAKAHQAJAHAAANQAAARgQAHQASAGAAASQAAAdglAAgAmPN1IAdAAQARAAgBgMQABgMgRAAIgdAAgAmPNKIAcAAQAPAAABgMQgBgMgPAAIgcAAgArGOIIAAhoIA9AAQAQAAAKAHQAJAHAAANQAAASgQAGQASAGAAASQAAAdglAAgAqtN1IAfAAQAPAAAAgMQAAgMgPAAIgfAAgAqtNKIAeAAQAPAAgBgMQABgMgPAAIgeAAgAttOIIghgwIgPAOIAAAiIgaAAIAAhoIAaAAIAAAqIAtgqIAfAAIgqAnIAuBBgAxMOIIAAgWIAgAAIAAhOIgfAAIAAgVIAcAAQABAAAAAAQABgBAAAAQAAgBAAAAQABgBAAgBIAAgPIAZAAIAAB2IAfAAIAAAWgAEKNqIAAgVIBbAAIAAAVgAEKM+IAAgUIBbAAIAAAUgAJ6KdIAcAAQACAOAWAAQAcAAAAgYIAAgOQgNAOgWAAQgXAAgMgNQgNgPAAgYQAAgZANgOQAMgOAXAAQAYAAAMAQIAAgNIAZAAIAABlQAAAUgNAMQgOANgcAAQgtAAgGgigAKSJfQAAAhAdAAQAcAAAAghQAAgggcAAQgdAAAAAggAO1KPQgJgIAAgOQAAgPALgIQAKgIAZgCIAVgDQAHgDAAgHQAAgNgWAAQgWAAgCARIgZAAQACgRANgKQANgKAWAAQAtAAAAAlIAAAtQAAABAAABQAAAAABABQAAAAABABQABAAAAAAIAJAAIAAAVIgQAAQgQAAgCgSQgMAUgbAAQgSAAgKgIgAPeJoQgPACgFADQgFADABAHQgBANASAAQAOAAAIgIQAJgJAAgPIAAgCQgJAFgPABgAM7KMQgLgNAAgUIAAg+IAbAAIAAA8QAAAZAXAAQAbAAABgdIAAg4IAbAAIAABoIgaAAIAAgPQgNARgYAAQgTAAgMgLgAIGKJQgPgOAAgbQAAgZAPgPQAPgOAbAAQAaAAAOAOQAPAPABAZQgBAbgPAOQgOAOgaAAQgbAAgPgOgAISJgQABAiAdAAQAdAAAAgiQAAghgdAAQgdAAgBAhgAgWKPQgKgIABgOQgBgPAMgIQALgIAXgCIAWgDQAGgDAAgHQABgNgXAAQgUAAgDARIgZAAQACgRANgKQANgKAVAAQAtAAABAlIAAAtQAAABAAABQAAAAAAABQABAAAAABQABAAABAAIAIAAIAAAVIgQAAQgQAAgBgSQgMAUgcAAQgRAAgKgIgAASJoQgOACgFADQgEADAAAHQAAANAQAAQANAAAJgIQAKgJAAgPIAAgCQgKAFgPABgAiKKJQgPgOAAgbQAAgZAPgPQAPgOAZAAQAZAAAPAOQAOAPAAAZIAAAJIhUAAQADAaAcAAQASAAAFgLIAbAAQgJAfgpAAQgaAAgPgOgAh/JWIA5AAQgEgYgYAAQgZAAgEAYgAljKJQgNgOAAgbQAAgZANgPQANgOAXAAQAWAAAMAPIAAg1IAbAAIAACRIgZAAIAAgPQgNARgXAAQgXAAgNgOgAlVJgQAAAiAdAAQAcAAAAgiQAAghgcAAQgdAAAAAhgAndKJQgPgOAAgbQAAgZAPgPQAOgOAaAAQAZAAAOAOQAPAPAAAZIAAAJIhUAAQACAaAdAAQASAAAEgLIAbAAQgIAfgpAAQgbAAgOgOgAnSJWIA5AAQgEgYgYAAQgaAAgDAYgApYKJQgPgOAAgbQAAgZAPgPQAOgOAZAAQAaAAAPAOQAOAPgBAZIAAAJIhTAAQADAaAbAAQARAAAHgLIAbAAQgFAOgMAJQgOAIgUAAQgaAAgOgOgApOJWIA5AAQgDgYgaAAQgYAAgEAYgAuLKJQgQgOABgbQgBgZAQgPQAOgOAaAAQAbAAAPAOQAOAPAAAZQAAAbgOAOQgPAOgbAAQgaAAgOgOgAt/JgQAAAiAcAAQAeAAAAgiQAAghgeAAQgcAAAAAhgAwGKJQgPgOAAgbQAAgZAPgPQAOgOAbAAQAWAAAOALQAOALACAVIgaAAQgEgWgWAAQgdAAAAAhQAAAiAdAAQAWAAAEgVIAaAAQgCAUgOALQgOALgWAAQgbAAgOgOgAL9KVIAAgeIAeAAIAAAegAGyKVIgUhKIgVBKIgdAAIgghoIAbAAIAWBMIAVhMIAaAAIAUBMIAWhMIAZAAIgfBogAEmKVIAAgeIAgAAIAAAegAD0KVIAAg9QAAgZgWAAQgYAAgCAZIgBA9IgaAAIAAg9QAAgZgVAAQgbAAAAAdIAAA5IgaAAIAAhoIAaAAIAAAOQALgRAYAAQAWAAANATQALgTAbAAQATAAALAMQAMAMAAAUIAAA/gAjoKVIAAhoIAYAAIAAAPQANgSAYAAIAJAAIAAAYIgWAAQgVAAgCAYIAAA7gAqvKVIAAhTIgVAAIAAgVIAVAAIAAgQQAAgLAIgIQAIgGAKAAIAkAAIAAAWIggAAQgBAAAAAAQgBAAAAAAQAAABAAAAQgBABAAAAIAAARIAjAAIAAAVIgjAAIAABTgAsLKVIAAhTIgWAAIAAgVIAWAAIAAgQQgBgLAJgIQAGgGALAAIAlAAIAAAWIghAAQgBAAgBAAQAAAAgBAAQAAABAAAAQAAABAAAAIAAARIAkAAIAAAVIgkAAIAABTgAl6HKIAAgWIAdAAQABAAAAAAQABgBAAAAQABAAAAgBQABAAAAgBIAFgLIgzhtIAdAAIAiBQIAdhQIAbAAIgyB/QgHASgRAAgAn5HKIAAiRIAZAAIAAAOQAMgQAXAAQAXAAANAOQANAPAAAZQAAAagNAOQgNAPgXAAQgWAAgMgPIAAA1gAngFtQAAAiAcAAQAdAAAAgiQAAgigdAAQgcAAAAAigALaGGQAAgQAMgHQAKgIAYgCQAQgCAGgCQAGgCABgHQAAgNgXAAQgXAAAAAQIgaAAQACgRANgJQANgKAVAAQAVAAANAKQAMAJAAASIAAAtQAAABAAABQAAAAABABQAAAAABAAQAAAAABAAIAKAAIAAAWIgRAAQgPAAgCgSQgMAUgcAAQgmAAABgegAMMF1QgPABgFAEQgEADAAAHQAAAMARAAQANAAAJgIQAKgIAAgPIAAgCQgKAEgPACgAJuGVQgPgOAAgaQAAgZAPgPQAPgOAaAAQAXAAANALQAPALACAUIgbAAQgEgWgWAAQgdAAAAAiQAAAiAdAAQAWAAAEgWIAbAAQgCAUgPALQgNAMgXAAQgaAAgPgPgAG4GGQAAgQAMgHQALgIAYgCQAQgCAFgCQAHgCAAgHQAAgNgXAAQgWAAgBAQIgZAAQACgRANgJQAMgKAWAAQAWAAALAKQAMAJAAASIAAAtQAAABABABQAAAAAAABQABAAAAAAQABAAABAAIAJAAIAAAWIgQAAQgRAAAAgSQgMAUgcAAQgmAAAAgegAHqF1QgOABgFAEQgFADAAAHQAAAMARAAQAOAAAJgIQAJgIABgPIAAgCQgLAEgPACgAAnGVQgPgOAAgaQAAgZAPgPQAOgOAZAAQAaAAAPAOQAOAOAAAaIgBAIIhTAAQADAaAbAAQARAAAHgLIAbAAQgKAggpAAQgaAAgOgPgAAxFjIA5AAQgEgYgZAAQgYAAgEAYgArWGVQgPgOgBgaQABgZAPgPQAPgOAaAAQAWAAAOALQAOALACAUIgbAAQgEgWgWAAQgcAAAAAiQAAAiAcAAQAWAAAEgWIAbAAQgCAUgOALQgOAMgWAAQgaAAgPgPgAtSGVQgPgOAAgaQAAgZAPgPQAPgOAaAAQAXAAANALQAOALACAUIgZAAQgEgWgYAAQgZAAgEAYIAqAAIAAASIgqAAQACAbAbAAQAYAAAEgWIAZAAQgCATgOALQgNAMgXAAQgaAAgPgPgAvPGVQgOgOAAgaQAAgZAPgPQAOgOAZAAQAZAAAPAOQAPAOAAAaIgBAIIhUAAQADAaAcAAQARAAAGgLIAbAAQgDAPgOAIQgOAJgSAAQgaAAgQgPgAvFFjIA7AAQgFgYgZAAQgYAAgFAYgARFGiIAAhpIAbAAIAABpgAP1GiIAAhUIglAAIAAgVIBlAAIAAAVIgmAAIAABUgAOlGiIAAhKIgvBKIgcAAIAAhpIAZAAIAABJIAvhJIAdAAIAABpgAGJGiIAAgsIgvAAIAAAsIgaAAIAAhpIAaAAIAAAoIAvAAIAAgoIAbAAIAABpgADkGiIgigwIgOAOIAAAiIgbAAIAAhpIAbAAIAAAqIAsgqIAgAAIgrAnIAvBCgAgXGiIAAgoIgeAAQgRAAgKgJQgKgIAAgPIAAghIAaAAIAAAfQAAANAPAAIAaAAIAAgsIAaAAIAABpgAi0GiIAAhKIgwBKIgcAAIAAhpIAaAAIAABJIAuhJIAeAAIAABpgApJGiIAAhUIgmAAIAAgVIBnAAIAAAVIgmAAIAABUgAxfGiIAAiNIBIAAQAWAAAMALQAMAMAAAUQAAAUgMALQgMAMgWAAIgtAAIAAA3gAxEFVIArAAQAVAAAAgVQAAgVgVAAIgrAAgANmERIAYAAQABAKANAAQAOAAABgKIAXAAQgDAdgjAAQgiAAgEgdgAjzERIAXAAQACAKANAAQANAAACgKIAXAAQgEAdgiAAQgiAAgEgdgAREEoIAAgXIAcAAIAAAXgAlxg1QiZiZAAjXQAAjYCZiZQCZiZDXAAQDXAACZCZQCZCZAADYQAADXiZCZQiZCYjXAAQjWAAiaiYgAlcsCQiQCRAADMQAADLCQCRQCQCPDLAAQDLAACRiPQCQiRAAjLQAAjMiQiRQiRiQjLAAQjMAAiPCQgAish9IAAphIA/AAIAAAeIAeAAIAAgeIBAAAIAAAeIAdAAIAAgeIA/AAIAAAeIAeAAIAAgeIBAAAIAAJhgAibiOIE1AAIAAo/IgeAAIAAAeIhAAAIAAgeIgdAAIAAAeIg/AAIAAgeIgeAAIAAAeIhAAAIAAgeIgdAAgAhXj+IAAgRICtAAIAAARgAg9kuIAAgRIB4AAIAAARgAg9lfIAAgQIB4AAIAAAQgAhXmOIAAgRICtAAIAAARgAhXm/IAAgRICtAAIAAARgAg9nvIAAgRIB4AAIAAARgAg9odIAAgRIB4AAIAAARgAhXpMIAAgRICtAAIAAARg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.ic2, new cjs.Rectangle(-112,-94.4,224,188.8), null);


(lib.ic1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AEPMXQgSgUAAgiQAAgjATgTQATgUAiAAQAdAAATAOQASAOADAZIgdAAQgGgegiAAQgXAAgKAMQgLAMAAAbQAAAbALAMQAKAMAXAAQAmAAAFgkIguAAIAAgTIBIAAIAABKIgXAAIAAgVQgRAYghAAQggAAgSgTgABuMWQgTgTAAgiQAAgjATgTQATgUAjAAQAiABATASQATAUAAAjQAAAigTATQgTAUgiAAQgjAAgTgUgAB3LhQAAAzAtAAQAsAAAAgzQAAgzgsAAQgtAAAAAzgAkaMLQAAgOAMgJQAKgIAYgCQARgBAFgCQAGgDAAgHQAAgMgVAAQgWAAgCAQIgZAAQACgRANgKQANgKAVAAQAuAAAAAlIAAAtQAAABAAABQAAABABAAQAAABAAAAQABAAABAAIAIAAIAAAVIgPAAQgRAAAAgSQgNAVgbgBQgmAAAAgegAjoL6QgOADgFADQgFADAAAHQAAAMARAAQAOAAAIgIQAKgJAAgOIAAgCQgKAEgPABgAAKMnIgbhpIgdBpIghAAIgniMIAcAAIAdBtIAehtIAdAAIAdBuIAdhuIAcAAIgpCMgAlIMnIAAgrIgwAAIAAArIgaAAIAAhoIAaAAIAAAoIAwAAIAAgoIAaAAIAABogAHQJcIAAgWIAdAAQABAAAAAAQABAAABgBQAAAAAAAAQABgBAAAAIAFgMIgyhtIAcAAIAiBQIAehQIAaAAIgyB/QgHASgRAAgAi9JcIAAgWIAdAAQABAAAAAAQABAAAAgBQABAAAAAAQAAgBABAAIAEgMIgyhtIAcAAIAjBQIAehQIAbAAIg0B/QgGASgSAAgAm3JcIAAgWIAdAAQAAAAABAAQAAAAABgBQAAAAAAAAQABgBAAAAIAFgMIgyhtIAdAAIAiBQIAdhQIAbAAIgyB/QgHASgSAAgADbIYQAAgPALgIQALgIAYgCQAQgBAGgCQAGgDAAgHQAAgMgWAAQgXAAgBAPIgYAAQABgRAOgJQAMgKAWAAQAVAAAMAKQAMAJAAASIAAAtQAAABAAABQAAAAABABQAAAAABAAQAAABABAAIAJAAIAAAVIgPAAQgRAAgBgSQgMAUgcAAQglAAAAgegAENIHQgOABgGAEQgEADAAAHQAAAMARAAQAOAAAIgIQAKgIAAgPIAAgBQgJAEgQABgAFbI0IAAhpIA9AAQAjAAAAAcQAAARgPAHQARAGAAASQAAANgKAIQgJAIgRAAgAF1IhIAeAAQAPAAAAgMQAAgNgPAAIgeAAgAF1H1IAcAAQAPAAAAgLQAAgMgPAAIgcAAgAC1I0IgigwIgPAOIAAAiIgaAAIAAhpIAaAAIAAAqIAtgqIAfAAIgqAoIAuBBgAAII0IAAhKIgvBKIgcAAIAAhpIAaAAIAABJIAthJIAeAAIAABpgAj0I0IAAhTIgvAAIAABTIgbAAIAAhpIBlAAIAABpgAnZI0IgvhGIgWAWIAAAwIgbAAIAAiNIAbAAIAAA/IBAg/IAhAAIg3A1IA8BYgAg2GjIAXAAQABAKAOAAQANAAACgKIAVAAQgDAdghAAQgiAAgEgdgAl3BPQiYiXAAjYQAAjXCYiaQCZiYDYAAQDWAACZCYQCYCaAADXQAADYiYCXQiZCajWgBQjYABiZiagAlip8QiQCRAADLQAADNCQCOQCQCRDMgBQDKABCQiRQCRiOAAjNQAAjLiRiRQiQiQjKAAQjMAAiQCQgAjHAHQgKAAAAgIIgGhQQgOgBgKgMQgLgMABgQQABgQANgLIgEgEQgLgNABgQQABgPANgMIgEgDQgLgNABgQQABgPANgMIgHgHQgJgOADgPQADgRANgJIgGhhIgLAAQgKAAAAgJIAAgnQAAgVAUgIIAAgzQAAgMAJgJQAJgJAMAAIEAAAQAMAAAJAJQAIAJAAAMIAAAzQAUAIAAAVIAAAnQAAAJgKAAIgKAAIgFBCIAmAOIAGAEIBLBfIAoAAQAGAAAEAEQAFAFAAAGIAACnQAAAHgFAEQgEAEgGABIgqAAIgeASQgVALgXgGIhAgUIgDAuQgBAIgJAAgAi+gLIDaAAIAIiAIi/AAQAFAJAAAKQAAARgMALQgLAMgQgBIgGAAgAg2ldQgHAGAAALQAAAKAHAHQAIAHAKAAIAzAAQAHAAAFAHIAiAzQACADAAAGIgLCuIBEAVQAPAEANgHIAfgTQAEgCADAAIAnAAIAAifIglAAQgIAAgEgFIhMhfIhLgcIg9AAQgKAAgIAIgAjfiFQgGAEAAAJQAAAJAGAFQAGAGAIAAIAUAAQAIAAAGgGQAFgFAAgJQAAgJgFgEQgGgHgIABIgUAAQgIgBgGAHgAiCkkQgDAPgKAJIADADQALANgBAQQgBAQgMALQAKAJADAPQACANgIANICuAAIAGhRIgggwIgwAAQgOABgLgJQgMgJgFgNIg6AAQAIANgCANgAjfjBQgGAGAAAJQAAAHAGAGQAGAGAIAAIAnAAQAJAAAFgGQAGgGAAgHQAAgJgGgGQgFgGgJAAIgnAAQgIAAgGAGgAjXkBQgOAEAAAPQAAAIAGAFQAGAHAIgBIAnAAQAJABAFgHQAGgFAAgIQAAgJgGgFQgFgGgJAAIgnAAgAjfk3QgGAFAAAIQAAAIAGAHQAGAFAIABIAnAAQAJgBAFgFQAGgHAAgIQAAgIgGgFQgFgHgJAAIgnAAQgIAAgGAHgAjUlRICEAAQABgRANgLQANgLARAAIA+AAIAFAAIAVAIIAEg7IkTAAgAjsniQgDADAAAEIAAAdIE7AAIAAgdQAAgEgCgDQgDgEgEAAIkoAAQgEAAgDAEgAjborIAAAyIEUAAIAAgyQAAgEgDgDQgDgCgEAAIkAAAQgKAAAAAJg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.ic1, new cjs.Rectangle(-57,-81,114.1,162), null);


(lib.cup_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.cup();
	this.instance.parent = this;
	this.instance.setTransform(-81,-120);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.cup_1, new cjs.Rectangle(-81,-120,162,240), null);


(lib.btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#BB384F").s().p("AqNBDIAAgXIhDAAIAAAXIgdAAIAAgwIAMAAQAEgTAAgrIAAgUIBfAAIAABSIAOAAIAAAwgArDgFQAAANgCAMIAqAAIAAg7IgnAAgAKhAjQgMgLAAgUQAAgNAFgJQAGgJAKgFQAJgFAOAAQAWAAALALQAMALAAASIAAAIIg+AAQABAHAFAEQAFAEAHAAIAJgBQADgBACgDIAcAAQgCAMgLAHQgMAGgRAAQgVAAgMgLgALSgEQgCgHgEgDQgEgCgHAAQgOAAgDAMIAiAAIAAAAgACsAhQgLgMAAgZQAAgZAJgNQAJgMAUgEIARgCQABAAAAgBQABAAAAAAQAAgBAAAAQAAgBAAAAIAAgDIAdAAIAAADQAAAMgEAGQgFAGgJABIglAHQgFABgCADQgCAEAAADIAAAGQAKgMATAAQAUAAALAJQALAKAAAQQAAAMgGAIQgFAIgLAFQgKAEgOAAQgYAAgMgNgADCgDQgEADAAAIQAAAIAEAEQAFAFAIAAQAJAAAFgEQAEgEAAgJQAAgIgEgDQgFgEgJAAQgIAAgFAEgAg/AjQgMgLAAgUQAAgTAMgLQANgLAWAAQATAAALAIQAMAJABARIgcAAQgCgMgOAAQgJAAgDAFQgFAEAAAKQAAAKAFAFQADAFAJAAQAOAAACgMIAcAAQgBARgMAIQgLAJgTAAQgWAAgNgLgAlnAoQgIgGAAgLQAAgIAEgHQADgFAKgDQAKgCANgBIAMgBQADAAACgCQAAAAAAgBQABAAAAAAQAAgBAAAAQAAgBAAgBQAAgEgDgBQgDgCgHAAQgGAAgEACQgDADgBAEIgbAAQACgOAKgIQALgHASAAQATAAAKAIQAKAHAAAPIAAAbIABABIABABIAHAAIAAAWIgRAAQgGAAgEgCQgEgDgBgGQgIANgVAAQgQAAgIgGgAlDAKQgJABgDACQgEACAAAEQAAAHALAAQAJAAAFgFQAGgFAAgIIAAgBgAosAmQgKgIgCgQIAcAAQAAAGAFADQADACAJAAQANAAAAgHQAAgBAAAAQgBgBAAAAQAAgBAAAAQgBgBAAAAQgDgCgFAAIgLAAIAAgQIAKAAQAJAAAAgGQAAgHgNAAQgIAAgDADQgEADAAAFIgcAAQACgPALgIQALgIAVAAQASAAALAGQALAHAAAKQAAAGgEAFQgDADgGADQAPAGAAAMQAAAMgMAHQgNAGgSAAQgVAAgLgIgAIGAsIAAhPIAcAAIAAA5IAVAAIAAg5IAcAAIAAA5IAVAAIAAg5IAcAAIAABPgAGlAsIAAhPIAdAAIAAAcIAWAAQAPAAAIAHQAIAFAAANQAAANgIAGQgJAHgOAAgAHCAZIAPAAQAFAAACgCQACgBAAgFQAAgEgCgCQgCgCgFAAIgPAAgAF0AsIAAg5IgXAAIgCAoIgDAJQgDAEgFACQgEACgIAAIgOAAIAAgWIAJAAIABgBIACgBIACgMIAAgrIBNAAIAABPgAEOAsIAAhPIAcAAIAABPgAAfAsIAAhPIAcAAIAAAcIAXAAQAPAAAHAHQAJAGAAAMQAAAMgJAHQgIAHgOAAgAA7AZIAQAAQAEAAADgCQABgBAAgFQAAgEgBgCQgDgCgEAAIgQAAgAh3AsIAAgsIgfAsIgcAAIAAhPIAcAAIAAApIAdgpIAeAAIAABPgAj2AsIAAg5IgcAAIAAgWIBVAAIAAAWIgcAAIAAA5gAmaAsIAAgeIgcAAIAAAeIgcAAIAAhPIAcAAIAAAcIAcAAIAAgcIAdAAIAABPgApkAsIAAhPIAdAAIAABPgAENgtIAAgVIAeAAIAAAVgApkgtIAAgVIAdAAIAAAVg");
	this.shape.setTransform(-0.2,0.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Слой_3
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("ArPDIQhKAAg1g1Qg1g0AAhLIAAgnQAAhKA1g1QA0g1BLAAIWfAAQBKAAA1A1QA1A1AABKIAAAnQAABLg1A0Qg1A1hKAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.btn, new cjs.Rectangle(-89.9,-20,180,40), null);


(lib.bg3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#BB384F").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.bg3, new cjs.Rectangle(-150,-300,300,600), null);


(lib.bg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#009345").s().p("Egz0Az1Q1f1eAA+XQAA+WVf1eQVe1feWAAQeXAAVeVfQVfVeAAeWQAAeX1fVeQ1eVf+XAAQ+WAA1e1fg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.bg, new cjs.Rectangle(-469.1,-469.1,938.3,938.3), null);


(lib.logo_anim = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("ApGiBIgBgCIABgCIACgBIACABIABACIgBACIgCABIgCgBg");
	var mask_graphics_1 = new cjs.Graphics().p("ApLhIQgOgOAAgTQAAgTAOgOQAOgOATAAQAUAAANAOQAOAOAAATQAAATgOAOQgNAOgUAAQgTAAgOgOg");
	var mask_graphics_2 = new cjs.Graphics().p("ApQgPQgbgaAAgmQAAgmAbgaQAbgbAlAAQAmAAAbAbQAaAaAAAmQAAAmgaAaQgbAagmAAQglAAgbgag");
	var mask_graphics_3 = new cjs.Graphics().p("ApiAdQgngmAAg4QAAg4AngoQAognA4AAQA4AAAoAnQAnAoAAA4QAAA4gnAmQgoAog4AAQg4AAgogog");
	var mask_graphics_4 = new cjs.Graphics().p("ApiBmQg1g1AAhJQAAhLA1g0QA0g1BLAAQBKAAA1A1QA0A0AABLQAABJg0A1Qg1A0hKAAQhLAAg0g0g");
	var mask_graphics_5 = new cjs.Graphics().p("ApjCfQhChCAAhdQAAhcBChCQBBhBBdAAQBdAABCBBQBBBCAABcQAABdhBBCQhCBBhdAAQhdAAhBhBg");
	var mask_graphics_6 = new cjs.Graphics().p("ApkC+QhPhPAAhvQAAhuBPhPQBOhPBwAAQBvAABPBPQBPBPAABuQAABvhPBPQhPBPhvAAQhwAAhOhPg");
	var mask_graphics_7 = new cjs.Graphics().p("AplDeQhchcAAiCQAAiBBchcQBchbCCAAQCCAABbBbQBcBcAACBQAACChcBcQhbBbiCAAQiCAAhchbg");
	var mask_graphics_8 = new cjs.Graphics().p("ApmD9QhphpAAiUQAAiTBphpQBphpCUAAQCVAABpBpQBoBpAACTQAACUhoBpQhpBpiVAAQiUAAhphpg");
	var mask_graphics_9 = new cjs.Graphics().p("ApnEdQh2h2AAinQAAimB2h2QB2h2CnAAQCnAAB2B2QB0B2AACmQAACnh0B2Qh2B2inAAQinAAh2h2g");
	var mask_graphics_10 = new cjs.Graphics().p("AplE8QiDiDAAi5QAAi4CDiDQCDiDC5AAQC6AACBCDQCDCDAAC4QAAC5iDCDQiBCDi6AAQi5AAiDiDg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:-58.4,y:-13.5}).wait(1).to({graphics:mask_graphics_1,x:-60.2,y:-15.3}).wait(1).to({graphics:mask_graphics_2,x:-62,y:-17.1}).wait(1).to({graphics:mask_graphics_3,x:-65,y:-20.1}).wait(1).to({graphics:mask_graphics_4,x:-66.4,y:-20.5}).wait(1).to({graphics:mask_graphics_5,x:-67.8,y:-19.3}).wait(1).to({graphics:mask_graphics_6,x:-69.2,y:-15.5}).wait(1).to({graphics:mask_graphics_7,x:-70.6,y:-11.8}).wait(1).to({graphics:mask_graphics_8,x:-72,y:-8}).wait(1).to({graphics:mask_graphics_9,x:-73.4,y:-4.3}).wait(1).to({graphics:mask_graphics_10,x:-74.5,y:-0.3}).wait(11));

	// p1
	this.instance = new lib.p1("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(-107.7,0);

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(21));

	// Слой_6 (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	var mask_1_graphics_2 = new cjs.Graphics().p("AmTiCIgBgCIABgCIACgBIACABIABACIgBACIgCAAIgCAAg");
	var mask_1_graphics_3 = new cjs.Graphics().p("AmYhJQgOgOAAgTQAAgUAOgNQAOgOATAAQATAAAOAOQAOANAAAUQAAATgOAOQgOAOgTAAQgTAAgOgOg");
	var mask_1_graphics_4 = new cjs.Graphics().p("AmdgQQgbgaAAgmQAAgmAbgaQAagbAmAAQAmAAAaAbQAbAaAAAmQAAAmgbAaQgaAagmAAQgmAAgagag");
	var mask_1_graphics_5 = new cjs.Graphics().p("AmvAcQgngnAAg4QAAg3AngoQAogoA4AAQA4AAAnAoQAoAoAAA3QAAA4goAnQgnAng4AAQg4AAgogng");
	var mask_1_graphics_6 = new cjs.Graphics().p("AmwBlQg0g1AAhJQAAhLA0g1QA1g0BKAAQBLAAA0A0QA1A1AABLQAABJg1A1Qg0A0hLAAQhKAAg1g0g");
	var mask_1_graphics_7 = new cjs.Graphics().p("AmxCfQhBhCAAhdQAAhcBBhCQBChBBdAAQBdAABCBBQBBBCAABcQAABdhBBCQhCBBhdAAQhdAAhChBg");
	var mask_1_graphics_8 = new cjs.Graphics().p("AmxC+QhPhPAAhvQAAhuBPhPQBOhPBwAAQBvAABPBPQBNBPAABuQAABvhNBPQhPBPhvAAQhwAAhOhPg");
	var mask_1_graphics_9 = new cjs.Graphics().p("AmyDeQhchcAAiCQAAiBBchcQBbhbCCAAQCCAABbBbQBcBcAACBQAACChcBcQhbBbiCAAQiCAAhbhbg");
	var mask_1_graphics_10 = new cjs.Graphics().p("AmzD9QhphpAAiUQAAiTBphpQBphpCUAAQCVAABnBpQBpBpAACTQAACUhpBpQhnBpiVAAQiUAAhphpg");
	var mask_1_graphics_11 = new cjs.Graphics().p("Am0EdQh2h2AAinQAAimB2h2QB2h2CnAAQCmAAB1B2QB2B2AACmQAACnh2B2Qh1B2imAAQinAAh2h2g");
	var mask_1_graphics_12 = new cjs.Graphics().p("AmyE8QiDiDAAi5QAAi4CDiDQCCiDC6AAQC4AACDCDQCDCDAAC4QAAC5iDCDQiDCDi4AAQi6AAiCiDg");

	this.timeline.addTween(cjs.Tween.get(mask_1).to({graphics:null,x:0,y:0}).wait(2).to({graphics:mask_1_graphics_2,x:-40.5,y:-13.6}).wait(1).to({graphics:mask_1_graphics_3,x:-42.3,y:-15.4}).wait(1).to({graphics:mask_1_graphics_4,x:-44.1,y:-17.2}).wait(1).to({graphics:mask_1_graphics_5,x:-47.1,y:-20.2}).wait(1).to({graphics:mask_1_graphics_6,x:-48.5,y:-20.6}).wait(1).to({graphics:mask_1_graphics_7,x:-49.9,y:-19.5}).wait(1).to({graphics:mask_1_graphics_8,x:-51.3,y:-15.8}).wait(1).to({graphics:mask_1_graphics_9,x:-52.7,y:-12}).wait(1).to({graphics:mask_1_graphics_10,x:-54.1,y:-8.3}).wait(1).to({graphics:mask_1_graphics_11,x:-55.5,y:-4.5}).wait(1).to({graphics:mask_1_graphics_12,x:-56.6,y:-0.6}).wait(9));

	// p2
	this.instance_1 = new lib.p2("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(-71.8,0);
	this.instance_1._off = true;

	var maskedShapeInstanceList = [this.instance_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(2).to({_off:false},0).wait(19));

	// p3
	this.instance_2 = new lib.p3("synched",0);
	this.instance_2.parent = this;
	this.instance_2.setTransform(-44.7,3.5,0.02,0.02,0,0,0,-2.5,20);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(10).to({_off:false},0).to({regX:0,regY:21.8,scaleX:1,scaleY:1},4).wait(7));

	// Слой_7 (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	var mask_2_graphics_13 = new cjs.Graphics().p("ArFJvQkBkCAAltQAAlsEBkCQECkBFtAAQFsAAEBEBQECECAAFsQAAFtkCECQkBEBlsAAQltAAkCkBg");
	var mask_2_graphics_14 = new cjs.Graphics().p("ApuJvQkBkCAAltQAAlsEBkCQECkBFsAAQFtAAECEBQEBECAAFsQAAFtkBECQkCEBltAAQlsAAkCkBg");
	var mask_2_graphics_15 = new cjs.Graphics().p("ApuJvQkBkCAAltQAAlsEBkCQECkBFsAAQFtAAECEBQEBECAAFsQAAFtkBECQkCEBltAAQlsAAkCkBg");
	var mask_2_graphics_16 = new cjs.Graphics().p("ApuJvQkBkCAAltQAAlsEBkCQECkBFsAAQFtAAECEBQEBECAAFsQAAFtkBECQkCEBltAAQlsAAkCkBg");
	var mask_2_graphics_17 = new cjs.Graphics().p("ApuJvQkBkCAAltQAAlsEBkCQECkBFsAAQFtAAECEBQEBECAAFsQAAFtkBECQkCEBltAAQlsAAkCkBg");
	var mask_2_graphics_18 = new cjs.Graphics().p("ApuJvQkBkCAAltQAAlsEBkCQECkBFsAAQFtAAECEBQEBECAAFsQAAFtkBECQkCEBltAAQlsAAkCkBg");
	var mask_2_graphics_19 = new cjs.Graphics().p("ApuJvQkBkCAAltQAAlsEBkCQECkBFsAAQFtAAECEBQEBECAAFsQAAFtkBECQkCEBltAAQlsAAkCkBg");
	var mask_2_graphics_20 = new cjs.Graphics().p("ApuJvQkBkCAAltQAAlsEBkCQECkBFsAAQFtAAECEBQEBECAAFsQAAFtkBECQkCEBltAAQlsAAkCkBg");

	this.timeline.addTween(cjs.Tween.get(mask_2).to({graphics:null,x:0,y:0}).wait(13).to({graphics:mask_2_graphics_13,x:-96.7,y:4.1}).wait(1).to({graphics:mask_2_graphics_14,x:-82.9,y:4.1}).wait(1).to({graphics:mask_2_graphics_15,x:-60.4,y:4.1}).wait(1).to({graphics:mask_2_graphics_16,x:-37.9,y:4.1}).wait(1).to({graphics:mask_2_graphics_17,x:-15.4,y:4.1}).wait(1).to({graphics:mask_2_graphics_18,x:7.1,y:4.1}).wait(1).to({graphics:mask_2_graphics_19,x:29.6,y:4.1}).wait(1).to({graphics:mask_2_graphics_20,x:52.1,y:4.1}).wait(1));

	// wog
	this.instance_3 = new lib.wog("synched",0);
	this.instance_3.parent = this;
	this.instance_3.setTransform(56,5.2);
	this.instance_3._off = true;

	var maskedShapeInstanceList = [this.instance_3];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(13).to({_off:false},0).wait(8));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-116.7,-26.9,0.5,0.5);


(lib.banner = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// logo_anim
	this.instance = new lib.logo_anim("synched",0,false);
	this.instance.parent = this;
	this.instance.setTransform(0,0,0.6,0.6,0,0,0,-0.1,0);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(306).to({_off:false},0).wait(19).to({startPosition:19},0).to({y:-30,startPosition:20},10,cjs.Ease.quadInOut).wait(26).to({startPosition:20},0).to({alpha:0},10).wait(1));

	// txt
	this.instance_1 = new lib.txt();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-1.1,30.2,1,1,0,0,0,-0.1,0.4);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(325).to({_off:false},0).to({alpha:1},10).wait(26).to({alpha:0},10).wait(1));

	// bg
	this.instance_2 = new lib.bg();
	this.instance_2.parent = this;
	this.instance_2.setTransform(452.9,-656.1);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(291).to({_off:false},0).to({x:70,y:-104},15,cjs.Ease.cubicInOut).wait(55).to({alpha:0},10).wait(1));

	// logo
	this.instance_3 = new lib.logo_static();
	this.instance_3.parent = this;
	this.instance_3.setTransform(141.7,-260,0.822,0.821);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(372));

	// btn
	this.instance_4 = new lib.btn();
	this.instance_4.parent = this;
	this.instance_4.setTransform(-35.5,-103.5,0.01,0.013,0,0,0,0,-4);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(246).to({_off:false},0).to({regY:0,scaleX:1,scaleY:1},15,cjs.Ease.backOut).wait(9).to({regX:-0.1,regY:-0.1,scaleX:0.96,scaleY:0.96,x:-35.6},2).to({regX:0,regY:0,scaleX:1,scaleY:1,x:-35.5},2).wait(2).to({regX:-0.1,regY:-0.1,scaleX:0.96,scaleY:0.96,x:-35.6},2).to({regX:0,regY:0,scaleX:1,scaleY:1,x:-35.5},2).to({_off:true},26).wait(66));

	// ic3
	this.instance_5 = new lib.ic3();
	this.instance_5.parent = this;
	this.instance_5.setTransform(206.1,-135.4);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(125).to({_off:false},0).to({x:0},10,cjs.Ease.quadInOut).wait(25).to({x:-205.1},10,cjs.Ease.get(-1)).to({_off:true},1).wait(19).to({_off:false,regX:0.1,regY:-0.2,scaleX:0.49,scaleY:0.49,x:178.2,y:-84.5},0).to({x:105.7},10,cjs.Ease.quartOut).wait(35).to({x:-178.3},10,cjs.Ease.quartIn).to({_off:true},1).wait(126));

	// ic2
	this.instance_6 = new lib.ic2();
	this.instance_6.parent = this;
	this.instance_6.setTransform(266,-121.3);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(90).to({_off:false},0).to({x:0},10,cjs.Ease.quadInOut).wait(25).to({x:-265},10,cjs.Ease.quadInOut).to({_off:true},1).wait(49).to({_off:false,regX:0.1,regY:-0.2,scaleX:0.49,scaleY:0.49,x:207.3,y:-77.7},0).to({x:4.2},10,cjs.Ease.quartOut).wait(35).to({x:-207.4},10,cjs.Ease.quartIn).to({_off:true},1).wait(131));

	// ic1
	this.instance_7 = new lib.ic1();
	this.instance_7.parent = this;
	this.instance_7.setTransform(211,-136);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(55).to({_off:false},0).to({x:0},10,cjs.Ease.get(1)).wait(25).to({x:-210},10,cjs.Ease.quadInOut).to({_off:true},1).wait(79).to({_off:false,regX:0.2,regY:-0.2,scaleX:0.49,scaleY:0.49,x:180.6,y:-84.8},0).to({x:-97.4},10,cjs.Ease.quartOut).wait(35).to({x:-180.7},10,cjs.Ease.quartIn).to({_off:true},1).wait(136));

	// urText
	this.instance_8 = new lib.urText();
	this.instance_8.parent = this;
	this.instance_8.setTransform(0,288.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(372));

	// t1
	this.instance_9 = new lib.t1();
	this.instance_9.parent = this;
	this.instance_9.setTransform(2.9,-171.5);
	this.instance_9.alpha = 0;
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(5).to({_off:false},0).to({alpha:1},10).wait(30).to({alpha:0},10).wait(115).to({alpha:1},10).to({_off:true},126).wait(66));

	// phone
	this.instance_10 = new lib.phone_1();
	this.instance_10.parent = this;
	this.instance_10.setTransform(217,139);

	this.timeline.addTween(cjs.Tween.get(this.instance_10).to({x:63},15,cjs.Ease.quartOut).to({_off:true},291).wait(66));

	// cup
	this.instance_11 = new lib.cup_1();
	this.instance_11.parent = this;
	this.instance_11.setTransform(-234,149);

	this.timeline.addTween(cjs.Tween.get(this.instance_11).to({x:-42},15,cjs.Ease.quartOut).to({_off:true},291).wait(66));

	// bg
	this.instance_12 = new lib.bg3();
	this.instance_12.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(372));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-315,-300,597,600);


// stage content:
(lib._300x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// cover
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#666666").ss(2,1,1).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// banner
	this.instance = new lib.banner();
	this.instance.parent = this;
	this.instance.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-15,299,597,602);
// library properties:
lib.properties = {
	id: 'C6CFCF143BE44602932F386B1A77FDC2',
	width: 300,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/cup.png", id:"cup"},
		{src:"images/phone.png", id:"phone"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['C6CFCF143BE44602932F386B1A77FDC2'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;