(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.img1 = function() {
	this.initialize(img.img1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,220);


(lib.img2 = function() {
	this.initialize(img.img2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,220);


(lib.img3 = function() {
	this.initialize(img.img3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,220);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.white_line = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("A3bAZIAAgxMAu3AAAIAAAxg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,-2.5,300,5.1);


(lib.urText = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#342F3C").s().p("AvMDMIAAhYIAMAAIAAAJQADgFAGgDQAEgDAHAAQAIAAAGAEQAGAEAEAHQAEAIAAAJQAAAIgEAIQgEAHgGAEQgGAEgIAAQgHAAgEgDQgGgDgDgFIAAAmgAu4CAQgEACgCAFQgCAEAAAHQAAAGACAEQACAEAEAEQAFACAFAAQAFAAAEgCQAEgDACgFQADgFAAgFQAAgGgDgFQgCgFgEgCQgDgDgGAAQgGAAgEADgAFuCwIgDgDIgBgEIABgEIADgDIAEgBIAEABIACADQABAAAAABQAAAAABAAQAAABAAABQAAAAAAABIgCAEIgCADIgEABgAg2CwIACgKIADAAQAEAAABgCQACgCABgEIABgqIAvAAIAAA7IgLAAIAAgxIgZAAIAAAVQgBANgBAEQgCAGgEADQgDAEgIAAgAhuCtQgGgFgFgHQgDgHAAgIQAAgJADgHQAFgHAGgFQAIgEAIAAQAJAAAIAEQAGAFAEAHQAEAGAAAKQAAAJgEAGQgEAHgGAFQgIAEgJAAQgIAAgIgEgAhnCAQgFADgCAEQgDAFABAGQgBAFADAFQADAFAEACQAEADAFAAQAGAAAEgDQAEgCADgFQADgFgBgFQABgGgDgFQgCgEgFgDQgEgDgGAAQgFAAgEADgAk8CtQgIgFgDgHQgEgHAAgIQAAgJAEgHQADgHAIgFQAHgEAIAAQAJAAAIAEQAHAFADAHQAEAHAAAJQAAAIgEAHQgDAHgHAFQgIAEgJAAQgIAAgHgEgAk2CAQgFADgCAEQgCAEAAAHQAAAHACADQADAFAEACQAFADAEAAQAFAAAFgDQAEgCADgFQADgDgBgHQABgHgDgEQgCgEgFgDQgFgDgFAAQgEAAgFADgAq2CtQgHgFgDgGQgEgIAAgIQAAgJAEgIQADgGAHgFQAHgEAIAAQAGAAAFADQAFACADAGIAAgJIAMAAIAAA7IgMAAIAAgJQgDAGgFACQgFADgGAAQgIAAgHgEgAqvCAQgEACgDAFQgCAFAAAGQAAAFACAFQADAFAEADQAEACAFAAQAFAAAFgCQAFgEACgEQACgFAAgFQAAgGgCgFQgCgFgFgCQgEgDgGAAQgGAAgDADgAsvCtQgHgFgEgHQgDgGgBgJQABgJADgHQAEgHAHgEQAHgFAKAAQAHAAAHADQAHAEADAFIgHAHQgDgEgFgCIgJgCQgGAAgEADQgFACgCAFQgDAGAAAFQAAAFADAFQACAFAFACQADADAHAAQAFAAAFgCQAEgCADgEIAHAHQgDAFgHAEQgHADgHAAQgJAAgIgEgAwJCtQgIgFgEgHQgDgHAAgIQAAgJADgHQAEgHAIgFQAHgEAIAAQAJAAAHAEQAIAFADAHQAEAHAAAJQAAAIgEAHQgDAHgIAFQgHAEgJAAQgIAAgHgEgAwECAQgEADgCAEQgCAEgBAHQABAHACADQACAFAEACQAGADAEAAQAFAAAFgDQAEgCACgFQADgDAAgHQAAgHgDgEQgCgEgEgDQgFgDgFAAQgEAAgGADgAFOCvIAAgrIggArIgKAAIAAg7IALAAIAAArIAfgrIALAAIAAA7gAEICvIAAgqIgTAaIgIAAIgTgaIAAAqIgMAAIAAg7IAMAAIAXAfIAXgfIALAAIAAA7gAC3CvIAAg7IALAAIAAA7gACWCvIAAgaIgdAAIAAAaIgLAAIAAg7IALAAIAAAXIAdAAIAAgXIAMAAIAAA7gABACvIAAgxIgVAAIAAgKIA1AAIAAAKIgUAAIAAAxgAAYCvIAAg7IAMAAIAAA7gAiZCvIAAgaIgdAAIAAAaIgLAAIAAg7IALAAIAAAXIAdAAIAAgXIAMAAIAAA7gAj/CvIAAg7IAbAAQAKAAAHAEQAFAEAAAHQAAAFgCAEQgCADgEACQAFABADAEQADAEAAAFQAAAEgCAEQgEAFgEABQgGACgGAAgAjzCnIAQAAQAGAAADgDQADgCAAgEQAAgJgMAAIgQAAgAjzCNIANAAQAHAAADgCQACgCAAgEQAAgIgMAAIgNAAgAlnCvIAAgxIgeAAIAAAxIgLAAIAAg7IA1AAIAAA7gAnBCvIAAgXIgOAAIgOAXIgMAAIAPgYQgGgBgEgEQgEgEAAgIQAAgJAHgEQAGgFALAAIAbAAIAAA7gAnZB/QgEAEAAADQAAAFAEACQADADAHAAIAOAAIAAgTIgOAAQgGAAgEACgAoFCvIAAgaIgeAAIAAAaIgMAAIAAg7IAMAAIAAAXIAeAAIAAgXIALAAIAAA7gApOCvIAAgaIgdAAIAAAaIgNAAIAAg7IANAAIAAAXIAdAAIAAgXIALAAIAAA7gAruCvIAAgxIgUAAIAAgKIA1AAIAAAKIgVAAIAAAxgAtaCvIAAgrIgeArIgLAAIAAg7IAMAAIAAArIAegrIALAAIAAA7gAwpCvIgQgXIgCgCIgCgBIgJAAIAAAaIgLAAIAAg7IALAAIAAAXIAKAAIACAAIABgCIAQgVIAOAAIgWAcIAWAfgAxxCvIAAgrIgfArIgLAAIAAg7IAMAAIAAArIAegrIALAAIAAA7gAzXCvIAAg7IAaAAQALAAAFAEQAGAEAAAHQAAAEgCAFQgCADgFACQAGABADAEQADAEAAAFQAAAEgDAEQgDAFgEABQgGACgGAAgAzMCnIAQAAQAGAAADgDQADgCAAgEQAAgJgMAAIgQAAgAzMCNIANAAQAHAAACgCQAEgCAAgEQAAgIgNAAIgNAAgAC4BmIgCgDIgBgEIABgEIACgCIAEgBIAEABQAAAAABAAQAAAAABABQAAAAAAAAQABABAAAAIABAEIgBAEIgDADIgEABgAAaBmIgDgDIAAgEIAAgEIADgCIAEgBIAEABIADACIABAEIgBAEIgDADIgEABgAsnAvQADgDADgFQADgEABgFQgEgBgCgCQgCgBAAgEQAAgCACgDQACgCAEAAQADAAAEACQACAEAAAFQAAAGgEAIQgEAGgIAGgARMAsIAAgPIgyAAIAAAPIgKAAIAAgZIAHAAQACgCACgGQABgFAAgKIACgZIAvAAIAAAwIAJAAIAAAZgAQnAKIgEAJIAeAAIAAgmIgYAAgAqfAsIAAgPIhSAAIAAg6IALAAIAAAwIAZAAIAAgwIALAAIAAAwIAYAAIAAgwIAMAAIAAAwIAJAAIAAAZgARZAeIABgKIAEAAQACAAACgCQACgCABgEIACgpIAvAAIAAA6IgLAAIAAgwIgZAAIgBAUQAAALgCAGQgCAGgEAEQgDADgHAAgAPAAbQgHgFgEgGQgEgHAAgJQAAgJAEgHQAEgGAGgFQAIgEAIAAQAHAAAHAEQAIAEADAHQAEAHAAAIIgBAEIguAAQAAADADAGQADAEAEACQAEACAGAAQAGAAAEgCQAFgBADgEIAHAIQgFAFgGACQgHADgIAAQgJAAgHgEgAPhgFQgCgIgFgDQgFgFgGAAQgIAAgEAFQgFADgBAIIAkAAIAAAAgAKkAeIACgLIADABQAEAAADgDQACgDAAgGIADhAIA8AAIAABVIgMAAIAAhKIglAAIAAAjQgBARgCAHQgBAJgFAEQgFAEgIAAgAJ6AeIgDgDIgCgEIACgEIADgDIADgBIAFABIACADIABAEIgBAEIgCADIgFABgAHNAbQgIgFgDgHQgDgGgBgJQABgIADgHQAEgIAHgDQAHgFAJAAQAJAAAGAEQAHADADAFIgHAHQgCgDgGgDIgJgCQgGAAgFADQgFADgBAEQgDAFAAAFQAAAFADAFQACAFAEACQAEADAHAAQAFAAAEgCQAGgDACgDIAHAHQgDAGgHADQgHADgHAAQgKAAgHgEgADaAbQgHgFgEgGQgEgIAAgIQAAgIAEgIQADgGAIgFQAGgEAJAAQAHAAAIAEQAHAEADAHQAEAGAAAJIAAAEIgvAAQABAFACAEIAHAGQAEACAGAAQAGAAAFgCQADgBAFgEIAGAIQgEAEgHADQgHADgHAAQgJAAgIgEgAD6gFQgBgIgEgDQgFgFgHAAQgIAAgEAFQgFADgBAIIAjAAIAAAAgACAAeIACgKIACAAQADAAADgCQACgCAAgEIABgpIAxAAIAAA6IgNAAIAAgwIgYAAIgBAUQAAALgCAGQgBAGgEAEQgEADgIAAgABHAbQgGgEgEgHQgDgHAAgJQAAgJADgGQADgHAHgFQAHgEAIAAQAGAAAFADQAFADADAFIAAgJIAMAAIAAA6IgMAAIAAgJQgCAFgGADQgGADgFAAQgIAAgHgEgABOgRQgEACgDAFQgCAFAAAFQAAAFACAFQADAEAEAEQAFACAEAAQAGAAAEgCQAEgDACgFQADgFAAgFQAAgFgDgFQgCgFgEgCQgEgDgGAAQgEAAgFADgAAFAcQgFgDgEgEIAGgHQACADAFACIALACQAHAAAEgCQADgDAAgEQAAgJgMAAIgMAAIAAgHIAKAAQAFAAAEgCQADgCAAgEQAAgEgDgDQgCgCgHAAQgLAAgGAHIgGgHQAEgFAGgCQAGgDAIAAQALAAAGAFQAFAEAAAIQAAAEgCAEQgCADgFADQAGAAADAEQADAEAAAEQAAAGgDAEQgCADgHADQgHADgHAAQgIAAgHgDgAhJAbQgIgFgDgHQgEgHAAgIQAAgHAEgIQAEgIAHgDQAHgFAJAAQAJAAAGADQAHADAEAFIgIAHQgDgDgEgDQgFgCgFAAQgGAAgEACQgDACgEAEQgCAEgBAFIAdAAIAAAIIgdAAQABAIAGAEQAFAFAIAAQAFAAAFgCQAEgCADgEIAIAHQgFAGgGACQgGADgJAAQgIAAgIgEgAiTAbQgGgEgEgHQgDgHAAgJQAAgJADgGQAEgHAGgFQAHgEAIAAQAGAAAFADQAGADADAFIAAgJIALAAIAAA6IgLAAIAAgJQgDAFgGADQgGADgFAAQgIAAgHgEgAiMgRQgFACgCAFQgBAEAAAGQAAAGABAEQACAEAFAEQAFACAFAAQAFAAAEgCQAEgDADgFQACgDAAgHQAAgGgCgEQgDgFgEgCQgEgDgFAAQgFAAgFADgAlyAeIACgKIADAAQADAAACgCIACgGIACgpIAvAAIAAA6IgLAAIAAgwIgZAAIgBAUQAAAIgBAJQgCAGgEAEQgEADgHAAgAqEAbQgIgFgDgGQgFgIAAgIQAAgIAFgHQADgHAIgEQAHgFAJAAQAIAAAHAFQAIAEADAHQAEAGAAAJQAAAJgEAHQgDAGgIAFQgHAEgIAAQgJAAgHgEgAp/gRQgEADgCAEQgDAFAAAFQAAAFADAFQACAFAEACQAFADAGAAQAEAAAFgDQADgBAEgGQADgFAAgFQAAgFgDgFQgEgFgDgCQgFgDgEAAQgGAAgFADgAwuAbQgIgFgDgGQgEgIAAgIQAAgIAEgHQADgHAIgEQAHgFAJAAQAJAAAGAFQAIADADAIQAFAIAAAHQAAAIgFAIQgDAGgIAFQgHAEgIAAQgJAAgHgEgAwogRQgEADgDAEQgCAEAAAGQAAAHACADQADAFAEACQAFADAFAAQAEAAAFgDQAEgCADgFQACgDAAgHQAAgGgCgEQgDgEgEgDQgFgDgEAAQgFAAgFADgATMAdIAAgXIgNAAIgOAXIgNAAIAPgYQgGgBgEgEQgEgEAAgGQAAgJAGgFQAIgFAKAAIAbAAIAAA6gAS0gSQgDADAAAEQAAAFADADQAEACAFAAIAPAAIAAgTIgPAAQgFAAgEACgANTAdIAAg6IAMAAIAAAwIAYAAIAAgwIALAAIAAAwIAYAAIAAgwIAMAAIAAA6gAM0AdIAAgqIgfAqIgLAAIAAg6IALAAIAAAqIAggqIAKAAIAAA6gAI7AdIAAg6IAMAAIAAAVIANAAQAMAAAHAFQAFAEAAAJQAAAKgFAEQgHAFgMAAgAJHAUIANAAQANAAAAgKQAAgFgDgCQgEgDgGAAIgNAAgAIOAdIAAgwIgUAAIAAgKIA1AAIAAAKIgWAAIAAAwgAGqAdIAAg6IALAAIAAA6gAGJAdIAAgaIgcAAIAAAaIgMAAIAAg6IAMAAIAAAXIAcAAIAAgXIANAAIAAA6gAFMAdIgOgXIgBgCIgDgBIgEAAIAAAaIgMAAIAAgaIgEAAIgCABIgCACIgPAXIgNAAIAUgeIgUgcIANAAIAPAVQAAABAAAAQAAAAAAAAQAAABABAAQAAAAAAAAIACAAIAFAAIAAgXIAMAAIAAAXIAEAAIADAAIABgCIAPgVIANAAIgUAcIAUAegAixAdIgRgZIgDgBIgKAAIAAAaIgLAAIAAg6IALAAIAAAXIALAAIACAAIABgCIAQgVIANAAIgUAcIAUAegAj5AdIAAgqIgfAqIgLAAIAAg6IALAAIAAAqIAfgqIALAAIAAA6gAmAAdIgQgXIgBgCIgDgBIgJAAIAAAaIgMAAIAAg6IAMAAIAAAXIAKAAIACAAIABgCIAQgVIANAAIgUAcIAUAegAnIAdIAAgqIgfAqIgLAAIAAg6IALAAIAAAqIAggqIAKAAIAAA6gAovAdIAAg6IAbAAQALAAAFAEQAGAEAAAHQAAAFgCAEQgDAEgDABQAFAAADAEQADAEAAAFQAAAEgCAEQgEAFgEABQgGACgFAAgAojAVIAQAAQAFAAAEgDQADgCAAgEQAAgJgMAAIgQAAgAojgEIANAAQAHAAACgCQADgCAAgEQAAgIgMAAIgNAAgAtBAdIAAgaIgeAAIAAAaIgMAAIAAg6IAMAAIAAAXIAeAAIAAgXIALAAIAAA6gAuKAdIAAgqIgfAqIgLAAIAAg6IALAAIAAAqIAggqIAKAAIAAA6gAvhAdIAAgwIgUAAIAAgKIA0AAIAAAKIgVAAIAAAwgAxOAdIgPgXIgCgCIgCgBIgJAAIAAAaIgMAAIAAg6IAMAAIAAAXIAKAAIABAAIACgCIAPgVIAOAAIgVAcIAVAegAyOAdIAAg6IALAAIAAA6gAyvAdIAAgaIgdAAIAAAaIgLAAIAAg6IALAAIAAAXIAdAAIAAgXIANAAIAAA6gAGsgrIgDgDIgBgEIABgEQAAAAABgBQAAAAAAAAQABgBAAAAQABAAAAAAIADgBIAFABIACACIABAEIgBAEIgCADIgFABgAyNgrIgCgDIgBgEIABgEIACgCIAEgBIAFABIACACIABAEIgBAEIgCADIgFABgAnihWIACgKIAIABQADAAACgCIAEgDIAEgIIADgHIgZg8IAMAAIATAuIASguIANAAIgjBQQgEAGgEACQgDACgHAAgAGFhWIAAhZIAMAAIAAAJQAEgGAFgCQADgCAIAAQAIAAAGAEQAGADAEAIQAEAHAAAJQAAAJgEAHQgEAIgGADQgHAEgHAAQgHAAgEgDQgGgDgDgFIAAAngAGZijQgDACgEAFQgBAEgBAHQABAGABAEQADAFAEADQAFACAEAAQAGAAAEgCQAFgDACgFQACgFAAgFQAAgFgCgGQgDgFgEgCQgEgDgGAAQgEAAgFADgAjzhWIAAhZIANAAIAAAJQADgGAFgCQAFgCAGAAQAJAAAGAEQAGAEAEAHQADAHAAAJQAAAJgDAHQgEAHgGAEQgHAEgIAAQgFAAgGgDQgGgDgCgFIAAAngAjeijQgEACgDAFQgCAEAAAHQAAAHACADQADAFAEADQAEACAGAAQAEAAAFgCQAEgDADgFQACgEAAgGQAAgHgCgEQgEgFgDgCQgFgDgEAAQgGAAgEADgAO0h2QgIgFgDgGQgFgIAAgIQAAgIAFgIQADgHAHgEQAHgEAKAAQAIAAAGADQAHADAEAFIgHAHQgFgEgDgCIgKgCQgFAAgGADQgEADgCAEQgDAFAAAGQAAAFADAFQACAFAEACQAFADAGAAQAGAAAEgCQADgCAFgEIAGAHQgDAGgHADQgGADgIAAQgKAAgGgEgAKXhzIABgKIAEAAQADAAABgCQACgBABgEIACgrIAvAAIAAA7IgLAAIAAgxIgZAAIAAAVQgCAMgBAFQgCAHgEADQgDADgHAAgAJfh2QgGgFgFgGQgEgIAAgIQAAgIAEgIQAFgIAGgDQAHgEAJAAQAKAAAGAEQAGADAFAIQADAHAAAJQAAAJgDAHQgFAGgGAFQgIAEgIAAQgIAAgIgEgAJmijQgFADgCAEQgDAFAAAGQAAAFADAFQACAFAFACQADADAGAAQAHAAADgDQAEgCADgFQACgFAAgFQAAgGgCgFQgDgEgEgDQgEgDgGAAQgFAAgEADgAIch1QgHgDgDgEIAGgHQAEAEAFABQAEACAFAAQAIAAADgCQAFgDAAgEQAAgJgNAAIgMAAIAAgIIAJAAQAHAAADgCQAEgCAAgEQAAgFgEgCQgDgCgGAAQgLAAgGAHIgGgHQAEgFAGgCQAFgCAIAAQANAAAEAEQAHAFAAAHQAAAGgCACQgEAFgDABQAFABADAEQADAEAAAFQAAAFgDAEQgDAEgGACQgFADgKAAQgGAAgIgDgAHZh2QgHgFgDgGQgEgHgBgJQABgKAEgGQAEgIAGgDQAHgEAJAAQAKAAAGAEQAHAEAEAHQAEAIAAAIQAAAIgEAIQgDAGgIAFQgHAEgJAAQgIAAgIgEgAHgijQgEACgDAFQgDAFAAAGQAAAFADAFQADAGAEABQAEADAFAAQAHAAADgDQAFgCACgFQACgDAAgHQAAgHgCgEQgCgEgFgDQgEgDgGAAQgFAAgEADgAFIh2QgIgFgDgGQgFgIAAgIQAAgJAFgHQADgHAHgFQAHgDAJAAQAHAAAHADQAHAEAEAHQADAGABAJIgBAFIguAAQAAAFADAEQADAEAEACQADACAHAAIAKgBQAGgDACgDIAHAIQgFAEgHADQgHADgHAAQgJAAgHgEgAFoiWQgBgIgFgEQgFgFgGAAQgIAAgFAFQgEAEgBAIIAjAAIAAAAgAC4hzIgDgDIgCgEIACgEIADgDIADgBIAFABIACADIABAEIgBAEIgCADIgFABgAhbh1QgIgDgDgEIAHgHQADAEAFABQAEACAHAAQAGAAAEgCQAEgCAAgFQAAgJgNAAIgLAAIAAgIIAJAAQAHAAADgCQADgCAAgEQAAgEgDgDQgCgCgHAAQgLAAgHAHIgGgHQAFgFAFgCQAFgCAJAAQALAAAHAEQAFAEAAAIQAAAGgCACQgCAEgEACQAGABACAEQACAEABAFQAAAFgEAEQgCAEgHACQgEADgJAAQgJAAgGgDgAmRh2QgIgFgDgGQgEgHAAgJQAAgJAEgHQADgHAIgEQAFgEALAAQAIAAAGADQAHADAEAFIgHAHQgEgEgEgCIgKgCQgFAAgFADQgFADgCAEQgDAFAAAGQAAAFADAFQACAFAFACQADADAHAAQAGAAAEgCQAFgCADgEIAHAHQgEAGgHADQgGADgIAAQgJAAgHgEgAojh2QgHgEgEgHQgEgHAAgJQAAgJADgHQAFgHAHgEQAGgEAKAAQAJAAAGACQAGAEAEAEIgHAHQgCgDgFgDQgGgCgFAAIgJACIgHAGQgDAFgBAEIAeAAIAAAJIgeAAQACAIAFAEQAGAFAHAAQAGAAAFgCQADgBAEgFIAHAHQgEAFgGADQgHADgIAAQgJAAgHgEgApth2QgGgEgEgHQgEgHAAgJQAAgJAEgHQADgHAHgEQAGgEAIAAQAHAAAFACQAEACAEAGIAAgJIAMAAIAAA7IgMAAIAAgJQgDAFgFADQgGADgGAAQgHAAgHgEgApmijQgEACgDAFQgCAGAAAFQAAAFACAFQADAFAEADQAEACAFAAQAFAAAFgCQAFgEABgEQADgFAAgFQAAgFgDgGQgCgFgEgCQgFgDgFAAQgFAAgEADgArxh2QgHgEgDgGQgFgGAAgIIgKAAIAAAaIgLAAIAAg7IALAAIAAAXIAKAAQACgIAEgEQADgGAHgDQAGgDAHAAQAKAAAGAEQAGADAEAIQAEAHAAAJQAAAIgEAIQgEAGgGAFQgHAEgJAAQgHAAgHgEgArsijQgFAEgBADQgDAEAAAHQAAAGADAEQABAFAFACQAFADAEAAQAGAAADgDQAEgCADgFQACgEAAgGQAAgHgCgEQgCgEgFgDQgDgDgGAAQgEAAgFADgAtkhzIABgKIADAAQAEAAABgCIACgFIACgrIAwAAIAAA7IgMAAIAAgxIgYAAIgBAVQAAAIgCAJQgBAHgEADQgEADgHAAgAx3h2QgIgFgDgGQgEgIAAgIQAAgJAEgHQAEgHAGgFQAHgDAJAAQAIAAAHADQAHAEAEAHQADAGAAAJIgBAFIguAAQABAFACAEQADAEAEACQAEACAGAAIAKgBQAGgDACgDIAHAIQgEAEgHADQgHADgIAAQgIAAgIgEgAxXiWQgBgIgFgEQgEgFgHAAQgHAAgFAFQgEAEgCAIIAjAAIAAAAgASoh0IAAg7IALAAIAAAVIAOAAQAMAAAGAFQAFAFAAAJQAAAKgFAEQgGAFgMAAgASzh9IANAAQANAAAAgKQAAgFgDgCQgEgDgGAAIgNAAgAR6h0IAAgxIgUAAIAAgKIA0AAIAAAKIgUAAIAAAxgARMh0IAAgrIggArIgKAAIAAg7IALAAIAAArIAfgrIALAAIAAA7gAP1h0IAAgxIgVAAIAAgKIA1AAIAAAKIgVAAIAAAxgAORh0IAAg7IALAAIAAA7gAN1h0IAAgqIgUAaIgHAAIgUgaIAAAqIgLAAIAAg7IALAAIAXAfIAYgfIAKAAIAAA7gALmh0IAAg7IALAAIAAAVIAOAAQAMAAAGAFQAGAFAAAJQAAAJgGAFQgGAFgMAAgALxh9IANAAQANAAAAgKQAAgFgDgCQgEgDgGAAIgNAAgAEih0IgHgRIgnAAIgGARIgMAAIAghWIAKAAIAiBWgAEXiPIgPgqIgQAqIAfAAgAB5h0IAAg7IAbAAQALAAAGAEQAFAEAAAIQAAAEgCAEQgDAEgEABQAGABADAEQADAEAAAFQAAAEgDAEQgDAFgEABQgEACgIAAgACFh8IAQAAQAGAAADgDQADgCAAgEQAAgJgMAAIgQAAgACFiWIANAAQAHAAADgCQACgCAAgEQAAgIgMAAIgNAAgABhh0IAAg7IAMAAIAAA7gABNh0IgRgZIgMAAIAAAZIgLAAIAAg7IALAAIAAAXIAKAAIACAAIABgCIAQgVIAOAAIgWAcIAWAfgAAFh0IAAgrIgeArIgLAAIAAg7IAMAAIAAArIAdgrIALAAIAAA7gAiAh0IAAgrIgeArIgLAAIAAg7IALAAIAAArIAfgrIAKAAIAAA7gAkfh0IgQgWIgQAWIgOAAIAXgeIgXgdIAOAAIAQAWIAQgWIANAAIgWAeIAXAdgAlgh0IAAg7IAMAAIAAA7gAqQh0IAAgYQgJAEgHAAQgGAAgGgDQgGgDgCgEQgDgFAAgHIAAgRIAMAAIAAAQQAAAGADADQAEADAGAAQAJAAAFgDIAAgZIAMAAIAAA7gAtzh0IgPgXIgCgCIgMAAIAAAZIgLAAIAAg7IALAAIAAAXIAKAAIACAAQABAAAAAAQAAAAAAgBQAAAAAAAAQABAAAAgBIAPgVIAOAAIgVAcIAVAfgAu7h0IAAgrIgeArIgLAAIAAg7IALAAIAAArIAfgrIALAAIAAA7gAwhh0IAAg7IAbAAQALAAAFAEQAGAEgBAIQAAAEgCAEQgCADgEACQAGABACAEQADAEAAAFQAAAFgDADQgCAEgEACQgFACgHAAgAwWh8IAQAAQAGAAADgDQADgCAAgEQAAgJgMAAIgQAAgAwWiWIAOAAQAGAAADgCQADgCAAgEQAAgIgMAAIgOAAgAych0IAAgnIgtAAIAAAnIgMAAIAAhWIAMAAIAAAkIAtAAIAAgkIAMAAIAABWgAOSi9QAAAAgBgBQAAAAgBAAQAAgBAAAAQAAgBAAAAIgBgEIABgEIACgCIAEgBIAEABIACACIABAEIgBAEQAAAAAAABQAAAAAAABQgBAAAAAAQgBABAAAAIgEABgABki9IgEgDIgBgEIABgEIAEgCIADgBIAEABIADACIABAEIgBAEIgDADIgEABgAldi9QgBAAAAgBQgBAAAAAAQAAgBgBAAQAAgBAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBQgBAAAAgBIACgEIADgCIADgBIAEABIADACIABAEIgBAEIgDADIgEABg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-124,-20.4,248.1,40.8);


(lib.t3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#352E3C").s().p("AILB6IgKgCIAEgWQAIADAHAAIANgDQAGgCADgFIANggIgzh6IAZAAIAnBfIAlhfIAaAAIg5CIQgHAUgIAJQgFAKgKAHQgJADgOAAgAGBB4IAAi3IAYAAIAAATQAGgKALgHQAKgFAOAAQASAAANAIQAMAJAIAPQAHAOAAATQAAATgHAMQgIAPgMAJQgNAIgSAAQgOAAgKgFQgLgGgGgLIAABQgAGqgmQgHAEgGAKQgGAPAAAIQAAAJAGAMQAFAJAIAGQANAFAIAAQAIAAAKgFQAIgFAGgKQAFgJAAgMQAAgNgFgKQgGgLgIgDQgIgGgKAAQgLAAgKAGgAr1B4IAAi3IAYAAIAAATQAGgKAMgHQAKgFAOAAQARAAANAIQAMAJAIAPQAHAOAAATQAAATgHAMQgIAPgMAJQgNAIgRAAQgOAAgKgFQgMgGgGgLIAABQgArLgmQgIAEgGAKQgEALAAAMQAAAMAEAJQAFAJAJAGQAMAFAIAAQAJAAAKgFQAHgFAGgKQAGgJAAgMQAAgNgGgKQgGgLgHgDQgJgGgKAAQgKAAgKAGgAOHBbIAAggIhrAAIAAh6IAZAAIAABlIA7AAIAAhlIAZAAIAABlIATAAIAAA1gACYA2QgPgKgIgOQgIgPAAgQQAAgSAIgPQAJgRAOgGQAMgJAWAAQAPAAAPAHQAOAGAHALIgPAPQgKgKgGgCQgJgEgLAAQgNAAgJAFQgJAGgFAJQgFANAAAJQAAAGAFAPQAFAJAJAFQAKAGAMAAQAHAAANgFQAJgDAHgJIAPAPQgHALgOAHQgLAGgTAAQgTAAgPgIgAm3A2QgQgKgHgOQgIgPAAgQQAAgSAIgPQAJgRAOgGQAMgJAWAAQANAAARAHQAOAGAHALIgPAPQgKgKgGgCQgJgEgLAAQgNAAgJAFQgHAFgHAKQgFAJAAANQAAALAFAKQAFAJAJAFQAKAGAMAAQAHAAANgFQAJgDAHgJIAPAPQgHALgOAHQgMAGgSAAQgTAAgPgIgAtvA2QgPgJgJgPQgIgMAAgTQAAgSAIgPQAKgPAOgIQAMgJAVAAQASAAAOAJQAOAIAJAPQAIAPAAASQAAATgIAMQgJAOgOAKQgPAIgRAAQgTAAgOgIgAtjgmQgIAGgHAJQgFANAAAJQAAAJAFAMQAFAIAKAGQAHAFAOAAQAMAAAGgFQALgGAFgIQAFgMAAgJQAAgJgFgNQgFgJgLgGQgGgFgMAAQgOAAgHAFgAPzA7IAAh6IAYAAIAAB6gAOzA7IAAh5IAZAAIAAB5gALqA7IgggxIgEgEIgFgBIgTAAIAAA2IgYAAIAAh6IAYAAIAAAxIAUAAIAEgBIAEgEIAggsIAbAAIgrA6IAsBAgAEnA7IAAhlIgrAAIAAgUIBuAAIAAAUIgrAAIAABlgABHA7IAAg2Ig+AAIAAA2IgXAAIAAh6IAXAAIAAAxIA+AAIAAgxIAYAAIAAB6gAhIA7IAAh5IAYAAIAAB5gAi7A7IAAh5IAZAAIAAB5gAj1A7IAAg2Ig9AAIAAA2IgZAAIAAh6IAZAAIAAAxIA9AAIAAgxIAXAAIAAB6gAoIA7IAAhYIhABYIgWAAIAAh6IAXAAIAABYIBAhYIAXAAIAAB6gAuyA7Ig2hMIgEgDQAAgCgFAAIgXAAIAABRIgZAAIAAizIAZAAIAABMIAXAAIAGgBIAEgDIAxhIIAcAAIg7BXIA/BcgAO4hcIgHgGIgCgIIACgIIAHgGIAHgBIAIABIAGAGIABAIIgBAIIgGAGIgIACgAhEhcIgGgGIgBgIIABgIIAGgGIAIgBIAHABIAHAGIACAIIgCAIIgHAGIgHACgAi2hcIgHgGIgCgIIACgIIAHgGIAHgBIAIABIAGAGIABAIIgBAIIgGAGIgIACgAQKhgQgEgEAAgGQAAgGAEgEQADgEAHAAQAGAAAEAEQAEAEAAAGQAAAGgEAEQgFAFgFAAQgFAAgFgFgAPhhgQgFgFAAgFQAAgFAFgFQAEgEAGAAQAFAAAEAEQAFAEAAAGQAAAGgDAEQgGAFgFAAQgFAAgFgFg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t3, new cjs.Rectangle(-105.8,-12.2,211.6,24.5), null);


(lib.t2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#352E3C").s().p("AimEdIAAg6QgRAAgSgJQgPgJgHgOQgJgOAAgTQAAgRAJgOQAHgPAPgIQANgHAWgDIAAg7IAXAAIAAA7QAXADAMAHQAQAIAHAPQAJASAAAPQAAAOgJARQgHAOgQAJQgRAJgSAAIAAA6gAiPDMQAOAAAJgFQAIgFAGgKQAFgJAAgLQAAgNgFgJQgGgKgIgFQgHgEgQgCgAi8B/QgKAGgEAJQgGAJgBALQABAMAGAKQAEAJAKAGQAJAFANAAIAAhTQgQACgGAEgABZDbQgNgHgHgQQgJgRAAgRQAAgPAJgRQAHgPANgIQANgJASAAQALAAAMAGQAKAHAIAJIAAgSIAYAAIAAB6IgYAAIAAgSQgIAJgKAHQgMAGgLAAQgPAAgQgJgABnB+QgIAHgEAIQgGAJABAMQgBAOAGAJQAEAIAIAHQAJAFALAAQAMAAAIgFQAKgGAFgJQADgJAAgOQAAgLgDgKQgFgJgKgGQgIgFgMAAQgLAAgJAFgAnxDbQgNgHgIgQQgIgPAAgTQAAgRAIgPQAIgPANgIQANgJAQAAQAMAAAMAGQAJAFAJALIAAgSIAYAAIAAB6IgYAAIAAgSQgJALgJAFQgMAGgMAAQgNAAgQgJgAnjB+QgHAFgHAKQgFANAAAIQAAAKAFANQAHAKAHAFQAHAFAMAAQAOAAAGgFQAIgFAGgKQAFgJAAgOQAAgMgFgJQgGgKgIgFQgGgFgOAAQgMAAgHAFgAqnDjIACgWIAHAAQAIAAABgEQADgCADgJIADhYIBjAAIAAB6IgZAAIAAhmIgzAAIgCArQABAYgEAMQgEAOgHAFQgIAIgPAAgAG3DgIAAhZIhABZIgVAAIAAh6IAWAAIAABZIBBhZIAWAAIAAB6gAEvDgIgggxIgEgDQAAgBgFAAIgTAAIAAA1IgYAAIAAh6IAYAAIAAAwIAUAAIAFgBIADgDIAggsIAcAAIgsA6IAsBAgAAZDgIghgtIgiAtIgbAAIAug+Igug8IAdAAIAgAsIAhgsIAcAAIgvA8IAwA+gAkaDgIAAhZIhABZIgXAAIAAh6IAYAAIAABZIA/hZIAYAAIAAB6gAlNBLQgKgDgFgJQgGgJgBgLIATAAQABAKAHAEQAGAGAJAAQAIAAAIgGQAGgEACgKIATAAQgCAMgFAIQgGAJgJADQgKAFgLAAQgLAAgJgFgAHRhHIAAgfIhlAAIAAAfIgVAAIAAg0IANAAIAJgRIAGhVIBgAAIAABmIATAAIAAA0gAGFiOIgGATIA9AAIAAhSIgzAAgAgohsQgOgIgIgOQgJgOAAgTQAAgUAJgOQAIgPAOgIQANgIASAAQAQAAAPAIQAPAJAFANQAJAOgBAQIAAALIhgAAQADAOADAFQAIAJAIAEQAKAFAKAAQAMAAAIgFQAMgEAEgGIAPAQQgJAJgOAFQgRAGgMAAQgRAAgSgJgAAaiuQgCgRgKgHQgJgJgOAAQgPAAgJAJQgKAJgDAPIBIAAIAAAAgAnJhsQgQgIgIgOQgIgOAAgTQAAgTAIgPQAKgPAMgIQAOgIASAAQARAAAOAIQAPAJAHANQAHAOAAAQIgCALIhfAAQAAAKAHAJQAFAJAIAEQAMAFAJAAQAMAAAKgFQAMgFAFgFIAMAQQgHAJgOAFQgRAGgOAAQgQAAgRgJgAmHiuQgBgPgLgJQgKgJgOAAQgPAAgKAJQgJAHgDARIBJAAIAAAAgAk9hsQgMgIgKgOQgIgPAAgSQAAgTAIgPQALgQALgHQAOgIATAAQAVAAAMAIQANAHAJAQQAKAOgBAUQABATgKAOQgHAOgPAIQgMAIgVAAQgSAAgPgIgAkwjJQgJAHgFAIQgFAJAAAOQAAANAFAIQAFAJAJAHQANAFAHAAQAIAAAMgFQALgHADgJQAFgIAAgNQAAgOgFgJQgDgIgLgHQgMgFgIAAQgHAAgNAFgAKNhmIAAh7IAYAAIAAB7gAJThmIAAg3Ig+AAIAAA3IgYAAIAAh7IAYAAIAAAwIA+AAIAAgwIAXAAIAAB7gAEohmIAAhaIg/BaIgWAAIAAh7IAWAAIAABaIBAhaIAXAAIAAB7gABOhmIAAh7IA2AAQAYAAAKAJQALAIAAAPQABAKgEAHQgEAHgJAEQAMADAEAHQAHAGAAANQAAALgFAGQgFAGgKAHQgJAEgQAAgABmh4IAgAAQAOAAAGgFQAGgEAAgJQAAgRgaAAIggAAgABmitIAbAAQAMAAAHgEQAHgGAAgIQAAgQgaAAIgbAAgAh5hmIAAgzQgPAIgUAAQgOAAgKgFQgJgFgGgKQgHgLAAgNIAAgkIAYAAIAAAhQAAAOAHAFQAGAFAPAAQASAAALgFIAAg0IAYAAIAAB7gAoihmIAAhRIhcAAIAABRIgZAAIAAizIAZAAIAABKIBcAAIAAhKIAaAAIAACzgAKQj/IgEgFIgDgJIADgHIAEgFIAJgDIAHADIAHAFIABAHIgBAJIgHAFIgHADg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t2, new cjs.Rectangle(-68,-28.4,136.1,57), null);


(lib.t1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#352E3C").s().p("AqKEPIAAggIhlAAIAAAgIgVAAIAAg1IAOAAQAFgEADgOIAGhUIBhAAIAABmIATAAIAAA1gArVDIQgCAMgFAGIA9AAIAAhRIgzAAgAguDsQgSgGgKgMIANgSQAHAIAPAGQAMAFARAAQANAAAHgCQAGgDAHgIQAFgGABgKQAAgLgHgFQgFgIgJgDIgzgUQgMgEgIgKQgHgJAAgRQAAgPAHgKQAHgKAPgHQANgEATAAQATAAAOAEQAPAHAMAJIgMARQgHgGgNgFQgMgFgQAAQgQAAgKAHQgLAHAAALQAAAIAGAGQADAEAJAFIA0ATQAOAIAGAIQAJAOAAAPQAAASgJAKQgHALgOAHQgQAGgRAAQgSAAgSgGgAjnDmQgXgOgKgUQgNgTAAgdQAAgaANgVQALgWAWgLQAVgLAZAAQAaAAAVALQAVALAMAWQAMAZAAAWQAAAagMAWQgLAUgWAOQgVAMgaAAQgZAAgVgMgAjbBYQgPAKgJAPQgJAOAAAVQAAAXAJAOQAJAPAPALQASAIAQAAQARAAARgIQAPgLAJgPQAJgSAAgTQAAgRgJgSQgJgPgPgKQgRgJgRAAQgQAAgSAJgAm3DmQgXgOgKgUQgMgWAAgaQAAgWAMgZQALgWAWgLQAVgLAaAAQAaAAAUALQAWALALAWQAMAVAAAaQAAAWgGANQgFAQgMAMIAaAcIgcAAIgMgNIgaAMQgMAEgQAAQgaAAgVgMgAmrBYQgPAKgJAPQgIASgBARQABATAIASQAJAPAPALQASAIARAAQAWAAAQgNIglgpIAPgOIAkAqQAIgIADgMQADgKAAgPQAAgVgJgOQgGgNgRgMQgTgJgPAAQgRAAgSAJgAofDvIAAi0IAZAAIAAC0gAszDvIAAh7IAYAAIAAB7gAu4DvIAAh7IA4AAQASAAAQAIQAKALABANQAAALgGAGQgDAIgJACQAMAEAGAHQAEAHAAAMQAAALgEAHQgEAHgKAEQgLAFgNAAgAugDdIAhAAQALAAAHgEQAGgGABgIQAAgSgZAAIghAAgAugCoIAbAAQAOAAAFgEQAHgEgBgJQAAgQgZgBIgbAAgAsvBXIgGgHIgCgHIACgHIAGgHIAIgBIAIABIAFAHIADAHIgDAHIgFAHIgIABgAj8g4IAAgfIhlAAIAAAfIgVAAIAAg1IAOAAQAFgFACgNQAFgKAAgVIACg1IBhAAIAABmIATAAIAAA1gAlHh/QgGAQgCACIA9AAIAAhRIgyAAgALTheQgNgHgKgQQgIgOAAgSQAAgRAIgQQAKgPANgHQAOgJASAAQAVAAANAJQAOAHAJAPQAIAQAAARQAAASgIAOQgJAQgOAHQgNAJgVAAQgSAAgOgJgALgi5QgIAGgGAIQgGANAAAJQAAAKAGAMQAFAIAJAHQAHAEAMAAQAOAAAHgEQAJgHAFgIQAGgMAAgKQAAgJgGgNQgFgIgJgGQgHgGgOAAQgMAAgHAGgACdheQgMgHgLgQQgIgOABgSQgBgRAIgQQALgPAMgHQANgJAUAAQAUAAANAJQAOAHAKAPQAHAQAAARQAAASgHAOQgKAQgOAHQgNAJgUAAQgUAAgNgJgACqi5QgIAGgGAIQgGANAAAJQAAAKAGAMQAFAIAJAHQAHAEANAAQAOAAAGgEQAKgHAFgIQAFgMAAgKQAAgJgFgNQgFgIgKgGQgGgGgOAAQgNAAgHAGgAqThWIAEgWIAGACQAJAAABgEQAFgDAAgJIAEhZIBiAAIAAB8IgXAAIAAhnIg0AAIgBArQAAAXgEANQgDAPgJAFQgIAGgOAAgAuQhgQgVgNgNgVQgLgUAAgcQAAgZALgXQAPgXATgJQAVgMAaAAQAYAAAWAMQAUAJANAXQALAXAAAZQAAAcgLAUQgMAVgVANQgWALgYAAQgaAAgVgLgAuDjuQgSALgGAOQgJAOAAAVQAAAXAJAOQAGAOASAKQASAJAQAAQAQAAASgJQAQgJAHgPQAIgOABgXQgBgVgIgOQgHgPgQgKQgSgKgQABQgQgBgSAKgAOjhXIgkg1IgGgBIgTAAIAAA2IgYAAIAAh8IAYAAIAAAxIAUAAIAFgBIAkgwIAbAAIgrA6IArBCgAKChXIAAg2Ig+AAIAAA2IgYAAIAAh8IAYAAIAAAxIA+AAIAAgxIAYAAIAAB8gAH0hXIAAhaIhABaIgYAAIAAh8IAYAAIAABaIBAhaIAXAAIAAB8gAEZhXIAAh8IA3AAQAUAAAMAJQANAJAAAPQAAAHgFAJQgDAIgJADQAMADAFAIQAFAGAAANQAAALgFAHQgDAHgMADQgJAFgPABgAEwhpIAhAAQALAAAIgFQAGgFAAgJQAAgRgZAAIghAAgAEwieIAaAAQAQAAAFgFQAGgDAAgJQAAgRgbAAIgaAAgABMhXIAAg2Ig+AAIAAA2IgXAAIAAh8IAXAAIAAAxIA+AAIAAgxIAYAAIAAB8gAh6hXIAAhaIhABaIgWAAIAAh8IAXAAIAABaIBAhaIAXAAIAAB8gAmlhXIAAgwIgdAAIgdAwIgaAAIAggyQgQgDgGgJQgIgIABgPQAAgSANgLQAOgKAWAAIA4AAIAAB8gAnXi7QgIAHAAAIQAAALAIADQAGAFANAAIAfAAIAAgnIgfAAQgOAAgFAFgArphXIAAh8IBVAAIAAAVIg+AAIAABng");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1, new cjs.Rectangle(-95.8,-27.1,191.6,54.2), null);


(lib.red_line = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#DB3624").s().p("A3bAZIAAgxMAu3AAAIAAAxg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,-2.5,300,5.1);


(lib.point = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#DB3624").s().p("AhGBHQgdgdAAgqQAAgoAdgdQAdgeApAAQApAAAdAeQAeAdAAAoQAAAqgeAdQgdAdgpAAQgpAAgdgdg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-10,-10,20,20);


(lib.logo_iqos = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#342F3C").s().p("AuzFoQg9AAgygfQgwgdgcgxQgcgwgBg4QgCg7Afg1IClkeQAeg0A0gcQAxgcA4AAQA5AAAwAcQA0AcAeA0IClEeQAfA1gBA7QgBA4gdAwQgbAxgwAdQgzAfg9AAgAt8jUQgyAWgoAnQgmAngWAzQgWA0AAA5QAAA6AWA0QAWAyAmApQAoAnAyAUQA1AXA5AAQA6AAA1gXQAygUAognQAngpAUgyQAXg0AAg6QAAg5gXg0QgUgzgngnQgogngygWQg1gVg6gBQg5ABg1AVgAE1C7IgsgtIgFgDQgCgBgEAAIjJAAQg+AAgkgfQgigcAAgtIAAiqQAAgHAGgFQAGgGAHAAIDmAAQA9AAAkAeQAjAcAAAuIAABPQAAAIgGAFQgGAFgGAAIgHAAQgIAAgGgFQgEgFAAgIIAAhPQAAgLgFgLQgFgLgJgHQgLgKgUgGQgQgEgXgBIjIAAIgEABIgBAGIAACKQAAAMAEALQAFAKAJAIQALAKASAFQASAFAXAAIDVAAQAGAAAGABIAJAHIA1A2QAFAEAAAIQAAAIgFAFIgFAFQgFAFgHAAQgJAAgFgFgAOMCKQgVAAgTgHQgUgJgPgOIgJgIQgFgHgBgHQAAgHAFgGIAFgFQAFgEAHgCQAIAAAGAGIAKAJQAJAJALAEQALAFANAAICQAAQAVAAAPgDQAPgFAJgHQAFgFACgEQADgHAAgLQAAgKgDgFQgCgGgFgEQgJgIgPgDQgPgEgVAAIh6AAQg3AAgfgWQgagWAAgiIAAgKQAAgiAagVQAfgYA3AAICFAAQAUAAASAHQASAIAPAMIAMAMQAGAEABAIQAAAIgEAFIgFAFQgFAGgIAAQgHABgGgGIgMgKQgIgIgMgEQgMgFgLAAIiFAAQgTAAgQAFQgPADgKAHQgEADgDAHQgDAFAAALQAAALADAFQADAIAEADQAJAHAQAEQAQADATAAIB6AAQA5ABAdAWQAaAUAAAjIAAAKQAAAjgaAUQgdAYg5AAgAH7CKQg/AAgkgfQghgcAAgtIAAhUQAAguAhgcQAkgeA/AAIB1AAQA9AAAkAeQAiAcAAAuIAABUQAAAtgiAcQgkAfg9AAgAHShqQgSAGgNAKQgIAHgEALQgGALAAALIAABUQAAAMAGALQAEAKAIAIQANAKASAFQASAFAXAAIB1AAQAWAAASgFQASgFAMgKQAJgIAFgKQAFgLAAgMIAAhUQAAgNgFgJQgFgLgJgHQgMgKgSgGQgSgEgWgBIh1AAQgXABgSAEgAi2CKQgIAAgGgGQgFgEAAgIIAAj/QAAgJAFgEQAGgGAIAAIAFAAQAIAAAFAGQAGAFAAAIIAAD/QAAAIgGAEQgFAGgIAAg");
	this.shape.setTransform(-1.6,0);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.logo_iqos, new cjs.Rectangle(-118,-36,232.9,72), null);


(lib.img3_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.img3();
	this.instance.parent = this;
	this.instance.setTransform(-150,-110);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.img3_1, new cjs.Rectangle(-150,-110,300,220), null);


(lib.img2_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.img2();
	this.instance.parent = this;
	this.instance.setTransform(-150,-110);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.img2_1, new cjs.Rectangle(-150,-110,300,220), null);


(lib.img1_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.img1();
	this.instance.parent = this;
	this.instance.setTransform(-150,-110);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.img1_1, new cjs.Rectangle(-150,-110,300,220), null);


(lib.ic3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFA").ss(2.8).p("ABagiIAAg3Ig3AAAAjBaIA3AAIAAg3AgihZIg3AAIAAA3AhZAjIAAA3IA3AA");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-10.4,-10.4,20.8,20.8);


(lib.ic2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#342F3C").s().p("AhVB9QgGAAgGgCQgFgCgEgEQgEgFgDgFQgCgGAAgFIAAhUQAAgGACgFQADgFAEgEQAEgEAFgCQAGgDAGAAIAgAAIAzhbQACgGAHgEQAGgFAIgBQAHAAAIACQAHADAFAGQAFAGACAHQABAIgBAHIgPA5IAuAAQAHAAAGADQAGADAEAFQAEAFACAHQABAGgBAHIgWBWQgCAHgDAFQgEAGgGAEQgFAFgHACQgGACgHAAgAAWhwQgFABgEACQgEADgCAEIgyBcIgBACIAAB0QAAAAABABQAAAAAAABQAAAAABABQAAAAAAABQABAAAAAAQABAAAAABQABAAAAAAQABAAAAAAIBbAAQAFABAEgCQAFgCAEgDIAHgHIAEgJIAVhWQABgEgBgDQgBgEgCgEIgGgFQgEgCgEAAIg1AAIgDAAIgCgCIgBgCIAAgDIAQhAQABgEgBgFQgBgFgDgDQgDgEgFgCIgGgBIgDAAgAg2BxIgBgGIAAhwIgeAAIgHACIgGADIgEAFIgBAHIAABUQAAADABADIAEAGIAGAEIAHABIAfAAIAAAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-11.5,-12.5,23.1,25);


(lib.ic1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#342F3C").s().p("AiYBxQgFgCgDgEQgDgDAAgEIAAgHQAGgYAKgWQALgVAQgRQAWgYAhgRQAhgSArgJIAAgjQAAgFADgFQACgFAGgCQAFgDAFAAQAGABAEADIAAAAIBzBcIABABQAGAFAAAJQAAADgBAEIgFAGIhzBiQgEAEgGABQgFABgFgCQgGgCgDgFQgEgGABgGIAAgiQgkAAgfAHQgyAMgZAeIgBABQgHAGgHAAQgDAAgDgCgAAbhlIgDACQgCACAAADIAAAtIgFABQg8AMgpAdQg2AlgNBBIAAABIAAACIABADIABAAIADACIABAAIAGgDQAOgRAWgMQAXgMAcgGQAUgEAVgBQANgBAOABIAGAAIAAAtIABAFIAFADIAAAAQAAAAABAAQABABAAAAQABAAAAAAQABAAAAAAIADgCIBzhjIAAgBQABAAAAAAQABAAAAgBQAAAAAAgBQAAgBAAAAIAAgDIgDgCIhyhdIgEgBIgEABg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-16.4,-11.5,32.8,23);


(lib.btn_youtube = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgLBLQgFgEgBgHIAjAAQgBAHgFAEQgFAFgHAAQgGAAgFgFgAg0A2QgFAAgEgEQgEgEAAgFQAAgGAEgEQAEgDAFAAIADAAIAAgpQgBgRALgOQAMgOAQgDIAAgGQABgFADgEQADgDAEAAQAFAAADADQADAEABAFIAAAGQAQADAMAOQAKAOAAARIAAApIADAAQAFAAAEADQAEAEAAAGQAAAFgEAEQgEAEgGAAg");
	this.shape.setTransform(-49.9,0.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Слой_2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AjwBDIAAgUIg/AAIAAAUIgOAAIAAghIAJAAQAEgEABgHQACgKAAgKIACggIA9AAIAAA/IAMAAIAAAhgAkeAEIgCATQAAAGgEAFIAnAAIAAgyIggAAgAFJAsQgJgGgFgJQgFgIAAgMQAAgLAFgJQAFgJAJgGQAJgFAMAAQAKAAAJAEQAJAEAFAHIgKAKQgDgFgHgDQgGgDgGAAQgIAAgGADQgFAEgEAGQgDAFAAAIQAAAHADAGQADAHAGADQAFADAJAAQAGAAAGgCQAHgEADgEIAKAJQgGAIgHADQgIAEgMAAQgMAAgJgFgABAAsQgJgFgEgJQgFgKAAgLQAAgMAFgIQAEgJAJgGQAJgFAKAAQAHAAAIADQAGAEAFAGIAAgLIAPAAIAABMIgPAAIAAgLQgFAHgGADQgHADgIAAQgLAAgIgFgABJgOQgFADgEAHQgDAFAAAIQAAAIADAGQADAFAGAEQAGAEAGAAQAHAAAGgEQAGgEACgFQAEgHAAgHQAAgHgEgGQgDgHgFgDQgFgDgIAAQgHAAgFADgAgSAsQgJgGgFgJQgFgIAAgMQAAgLAFgJQAEgIAKgHQAJgFALAAQAKAAAJAEQAJAEAFAHIgKAKQgDgFgHgDQgGgDgGAAQgHAAgGADQgFADgEAHQgDAFAAAIQAAAHADAGQADAHAGADQAFADAIAAQAGAAAGgCQAHgEADgEIAKAJQgGAIgHADQgIAEgMAAQgLAAgJgFgAGOAvIAAhMIAQAAIAAAcIAQAAQAQAAAIAFQAIAGAAAMQAAANgIAGQgIAGgQAAgAGeAkIAQAAQARAAAAgOQAAgGgEgDQgEgDgJAAIgQAAgAEXAvIAAg3IgpA3IgOAAIAAhMIAPAAIAAA3IAog3IAOAAIAABMgACnAvIAAg/IgbAAIAAgNIBFAAIAAANIgbAAIAAA/gAhEAvIAAg3IgpA3IgOAAIAAhMIAPAAIAAA3IAog3IAOAAIAABMgAifAvIAAg/IgnAAIAAA/IgPAAIAAhMIBFAAIAABMgAlcAvIAAhMIAQAAIAABMgAmEAvIAAhiIg5AAIAABiIgQAAIAAhwIBYAAIAABwgAlZgwIgEgEIgBgEIABgFIAEgEIAFgBQADAAACABQAAAAABABQAAAAABABQAAAAABABQAAAAAAABIACAFIgCAEQAAACgDACIgFABg");
	this.shape_1.setTransform(10.9,-0.5);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

	// Слой_3
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#DB3624").s().p("Ar8C+QgVAAgOgPQgPgPAAgUIAAkXQAAgUAPgQQAOgOAVAAIX5AAQAUAAAPAOQAPAQAAAUIAAEXQAAAUgPAPQgPAPgUAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-81.5,-19,163,38);


(lib.bg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFDFB").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.bg, new cjs.Rectangle(-150,-300,300,600), null);


(lib.banner = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// ic3
	this.instance = new lib.ic3("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(123,-113);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(166));

	// nums
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgaA7QgLgJgFgOQgGgRAAgTQAAgSAGgQQAFgOALgKQAMgJAOAAQAPAAALAJQALAIAGAQQAGAQAAASQAAATgGARQgGAPgLAIQgKAJgQAAQgPAAgLgJgAgQgsQgGAGgEALQgEALAAAQQAAARAEALQADALAHAGQAHAGAJAAQAKAAAGgGQAHgGAEgLQAEgNAAgPQAAgPgEgMQgEgLgHgGQgHgGgJAAQgJAAgHAGg");
	this.shape.setTransform(-117,-109.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAIBBIAAhvIghAQIAAgRIAmgRIANAAIAACBg");
	this.shape_1.setTransform(-117,-109.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgmBDIAAgOIAxg1IAIgOQADgGAAgHQAAgKgHgGQgHgGgMAAQgIAAgHACIgPAGIgHgPIATgHQALgDAJAAQALAAAKAEQAKAFAFAIQAGAIAAAMQAAAJgDAJQgFAKgGAGQgFAIgLALIgYAbIA4AAIAAAQg");
	this.shape_2.setTransform(-117,-109.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},45).to({state:[{t:this.shape_2}]},55).wait(66));

	// nums
	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("ACwA8QgLgJgGgPQgFgQAAgUQAAgRAFgRQAGgPALgJQALgJAPABQAQgBALAJQALAJAGAPQAFARAAARQAAAUgFAQQgGAPgLAJQgKAIgRAAQgQAAgKgIgAC6gsQgHAGgEALQgDALAAAQQAAARADALQAEAMAHAFQAHAHAJAAQAKAAAHgHQAHgFADgMQAEgNAAgPQAAgOgEgNQgEgLgGgGQgHgGgKAAQgJAAgHAGgAA3A7QgLgIgGgQQgFgOAAgVQAAgUAFgPQAGgOALgKQALgIAPAAQAQAAALAIQALAKAFAOQAGAQAAATQAAAUgGAPQgFAQgLAIQgKAJgRAAQgQAAgKgJgABBgtQgHAHgEALQgDAKAAARQAAARADALQAEALAHAGQAHAGAJAAQAKAAAHgGQAHgGADgLQAEgLAAgRQAAgRgEgKQgEgLgGgHQgHgFgKAAQgJAAgHAFgAgFBCQgDgBgCgDQgBgCAAgFIABgFIAFgFQACgBADAAQAEAAACABQADACABADIACAFQAAAFgCACQgBADgDABQgCACgEAAIgFgCgAjkA7QgLgIgGgQQgFgOAAgVQAAgUAFgPQAGgOALgKQALgIAPAAQAPAAAMAIQALAKAFAOQAGAQAAATQAAAUgGAPQgFAQgLAIQgLAJgQAAQgQAAgKgJgAjagtQgHAHgEALQgDAKAAARQAAARADALQAEALAHAGQAHAGAJAAQAKAAAHgGQAHgGADgLQAEgLAAgRQAAgRgEgKQgEgLgGgHQgHgFgKAAQgJAAgHAFgAgFACIgFgDIgBgGIABgGQACgDADgCIAFgBQAEAAACABQADACABADIACAGIgCAGIgEADQgCACgEAAIgFgCg");
	this.shape_3.setTransform(-108.9,-109.7);

	this.timeline.addTween(cjs.Tween.get(this.shape_3).wait(166));

	// ic1
	this.instance_1 = new lib.ic1("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(-72.5,47.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(166));

	// ic2
	this.instance_2 = new lib.ic2("synched",0);
	this.instance_2.parent = this;
	this.instance_2.setTransform(-117,48.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(166));

	// point
	this.instance_3 = new lib.point("synched",0);
	this.instance_3.parent = this;
	this.instance_3.setTransform(-140,-81.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({x:140},165).wait(1));

	// red_line
	this.instance_4 = new lib.red_line("synched",0);
	this.instance_4.parent = this;
	this.instance_4.setTransform(-300,-82.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({x:0},165).wait(1));

	// red_line
	this.instance_5 = new lib.white_line("synched",0);
	this.instance_5.parent = this;
	this.instance_5.setTransform(0,-82.4);
	this.instance_5.alpha = 0.398;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(166));

	// img1
	this.instance_6 = new lib.img1_1();
	this.instance_6.parent = this;
	this.instance_6.setTransform(0,-190);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(155).to({_off:false},0).to({alpha:1},10).wait(1));

	// img3
	this.instance_7 = new lib.img3_1();
	this.instance_7.parent = this;
	this.instance_7.setTransform(0,-190);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(100).to({_off:false},0).to({alpha:1},10).wait(56));

	// img2
	this.instance_8 = new lib.img2_1();
	this.instance_8.parent = this;
	this.instance_8.setTransform(0,-190);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(45).to({_off:false},0).to({alpha:1},10).to({_off:true},56).wait(55));

	// img1
	this.instance_9 = new lib.img1_1();
	this.instance_9.parent = this;
	this.instance_9.setTransform(0,-190);

	this.timeline.addTween(cjs.Tween.get(this.instance_9).to({_off:true},56).wait(110));

	// t3
	this.instance_10 = new lib.t3();
	this.instance_10.parent = this;
	this.instance_10.setTransform(6.5,-40.2);
	this.instance_10.alpha = 0;
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(110).to({_off:false},0).to({x:-23.5,alpha:1},10,cjs.Ease.cubicOut).wait(35).to({alpha:0},10).wait(1));

	// t2
	this.instance_11 = new lib.t2();
	this.instance_11.parent = this;
	this.instance_11.setTransform(-32.9,-23.9);
	this.instance_11.alpha = 0;
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(55).to({_off:false},0).to({x:-62.9,alpha:1},10,cjs.Ease.cubicOut).wait(35).to({alpha:0},10).to({_off:true},1).wait(55));

	// t1
	this.instance_12 = new lib.t1();
	this.instance_12.parent = this;
	this.instance_12.setTransform(-4.5,-25.3);
	this.instance_12.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).to({x:-34.5,alpha:1},10,cjs.Ease.cubicOut).wait(35).to({alpha:0},10).to({_off:true},1).wait(110));

	// urText
	this.instance_13 = new lib.urText("synched",0);
	this.instance_13.parent = this;
	this.instance_13.setTransform(-6.1,257.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(166));

	// btn
	this.instance_14 = new lib.btn_youtube("synched",0);
	this.instance_14.parent = this;
	this.instance_14.setTransform(45.5,46.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(166));

	// logo
	this.instance_15 = new lib.logo_iqos();
	this.instance_15.parent = this;
	this.instance_15.setTransform(-73.1,201.9,0.48,0.48,0,0,0,-0.1,-0.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_15).wait(166));

	// bg
	this.instance_16 = new lib.bg();
	this.instance_16.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_16).wait(166));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-450,-300,600,600);


// stage content:
(lib._300x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// cover
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#666666").ss(2,2,0,3).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// banner
	this.instance = new lib.banner();
	this.instance.parent = this;
	this.instance.setTransform(150.1,300.1,1,1,0,0,0,0.1,0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,299,601,602);
// library properties:
lib.properties = {
	id: '0A6E3F5DF6B342F4AF907DBE848CDF8D',
	width: 300,
	height: 600,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/img1.jpg", id:"img1"},
		{src:"images/img2.jpg", id:"img2"},
		{src:"images/img3.jpg", id:"img3"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['0A6E3F5DF6B342F4AF907DBE848CDF8D'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;