(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.btn_bg = function() {
	this.initialize(img.btn_bg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,224,50);


(lib.cherries = function() {
	this.initialize(img.cherries);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,38,42);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.btn_txt2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D42B38").s().p("AAABAIAAhjIARAAIAAAHQAHgIALAAQAKAAAIAGQAEAFACAIQABAJAAAJQAAAWgHAIQgHAHgLAAQgKgBgIgGIAAAhgAATgMQgCAEAAAKQAAATANABQAGAAADgGQADgEAAgMQAAgKgDgFQgDgEgGgBQgIAAgDAIgAi+BAIAAhjIARAAIAAAHQAIgIAKAAQAMAAAGAGQAFAFABAIQACAJAAAJQAAAWgIAIQgGAHgMAAQgKgBgHgGIAAAhgAirgMQgBAEAAAKQAAATAMABQANAAAAgWQAAgUgNAAQgIAAgDAIgAGwAAQAAgQAIgKQAJgKAOAAQAOAAAJAJQAJAKAAAQIAAAHIguAAQABAQAQABIAIgCQAEgCAEgEIALALQgGAGgHADQgGADgJAAQghAAAAgmgAHdgFQgBgQgNAAQgNAAgBAQIAcAAIAAAAgACeAcQgJgKAAgSQAAgQAJgKQAJgKAPAAQAHAAAHADQAGADAEAEIgMAMQgGgFgGgBQgOAAAAAVQAAAUAOABQAGAAAGgHIAMANQgFAFgFACQgFADgJAAQgQAAgIgKgABSAdQgIgJAAgTQAAgTAIgJQAJgJAOAAQAOAAAJAJQAIAJAAASQAAAVgIAIQgJAIgOABQgOgBgJgIgABcACQAAATANABQAIAAADgIQACgEAAgJQAAgVgNAAQgNAAAAAWgAkOAAQAAgQAIgKQAJgKAOAAQAPAAAJAJQAIAKAAAQIAAAHIgtAAQABAQAPABIAJgCIAHgGIALALQgGAGgHADQgGADgIAAQgiAAAAgmgAjhgFQgBgQgNAAQgMAAgBAQIAbAAIAAAAgAmrAAQAAgQAJgKQAJgKAOAAQAOAAAJAJQAJAKAAAQIAAAHIguAAQABAQAQABIAIgCIAIgGIALALQgGAGgHADQgHADgIAAQgiAAAAgmgAl9gFQgBgQgNAAQgNAAgBAQIAcAAIAAAAgAFAAlIAAhIIATAAIAAA4IAUAAIAAg4IASAAIAAA4IAUAAIAAg4IASAAIAABIgAEaAlIAAhIIASAAIAABIgADnAlIAAg4IgVAAIAAgQIA8AAIAAAQIgUAAIAAA4gAgmAlIAAg4IgYAAIAAA4IgSAAIAAhIIA8AAIAABIgAkxAlIAAg4IgXAAIAAA4IgTAAIAAhIIA8AAIAABIgAnYAlIAAg4IgWAAIAAgQIA9AAIAAAQIgVAAIAAA4gAEagwIAAgPIASAAIAAAPg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.btn_txt2, new cjs.Rectangle(-49.4,-6.3,99,12.7), null);


(lib.btn_txt1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AKlBWIAAhtIhDBtIgdAAIAAirIAhAAIAABtIBChtIAeAAIAACrgAHcBWIAAiNIgtAAIAAgeIB7AAIAAAeIgtAAIAACNgAFzBWIAAhtIhCBtIgeAAIAAirIAhAAIAABtIBDhtIAdAAIAACrgAB8BWIAAirIBDAAQAYABAQAPQAQAPAAAXQAAAYgQANQgQAPgYAAIghAAIAABBgACegIIAfAAQALAAAHgGQAHgGAAgLQAAgLgHgGQgHgHgLAAIgfAAgAAzBWIAAirIAiAAIAACrgAhpBWIAAirIBEAAQAYAAAOANQAOANAAAVQAAAZgUAMQAHADAFAFQAKALAAATQAAAWgOAOQgNANgYAAgAhIA4IAjAAQAKAAAGgGQAGgGAAgKQAAgJgGgGQgGgFgKAAIgjAAgAhIgPIAhAAQAKgBAGgFQAGgFAAgJQAAgTgWgBIghAAgAj6BWIAAirIBwAAIAAAeIhPAAIAAApIBEAAIAAAcIhEAAIAAAqIBPAAIAAAegAmQBWIAAirIBCAAQAYABAQAPQAQAPAAAXQAAAYgQANQgQAPgYAAIghAAIAABBgAlvgIIAfAAQALAAAHgGQAHgGAAgLQAAgLgHgGQgHgHgLAAIgfAAgAohBWIAAirIBwAAIAAAeIhPAAIAAApIBDAAIAAAcIhDAAIAAAqIBPAAIAAAegApqBWIAAiNIg6AAIAACNIghAAIAAirIB8AAIAACrg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.btn_txt1, new cjs.Rectangle(-71,-8.5,142.1,17.1), null);


(lib.btn_light = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AtTCqQhHAAgygyQgygxABhHQgBhFAygzQAygxBHAAIanAAQBHAAAyAxQAxAzAABFQAABHgxAxQgyAyhHAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.btn_light, new cjs.Rectangle(-102.2,-17,204.5,34), null);


(lib.btn_bg_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.btn_bg();
	this.instance.parent = this;
	this.instance.setTransform(-112,-25);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.btn_bg_1, new cjs.Rectangle(-112,-25,224,50), null);


(lib.bg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#40C1FB").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.bg, new cjs.Rectangle(-150,-300,300,600), null);


(lib.banana_mc = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.cherries();
	this.instance.parent = this;
	this.instance.setTransform(-19,-21);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.banana_mc, new cjs.Rectangle(-19,-21,38,42), null);


(lib.btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// btn_txt2
	this.instance = new lib.btn_txt2();
	this.instance.parent = this;
	this.instance.setTransform(0,35.3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(12));

	// btn_txt1
	this.instance_1 = new lib.btn_txt1();
	this.instance_1.parent = this;
	this.instance_1.setTransform(0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1).to({scaleX:0.96,scaleY:0.96},2).to({scaleX:1,scaleY:1},2).wait(2).to({scaleX:0.96,scaleY:0.96},2).to({scaleX:1,scaleY:1},2).wait(1));

	// btn_light
	this.instance_2 = new lib.btn_light();
	this.instance_2.parent = this;
	this.instance_2.alpha = 0;
	this.instance_2.compositeOperation = "lighter";
	this.instance_2._off = true;
	this.instance_2.filters = [new cjs.BlurFilter(20, 20, 1)];
	this.instance_2.cache(-104,-19,209,38);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1).to({_off:false},0).to({scaleX:0.96,scaleY:0.96,alpha:0.23},2).to({scaleX:1,scaleY:1,alpha:0},2).wait(2).to({scaleX:0.96,scaleY:0.96,alpha:0.23},2).to({scaleX:1,scaleY:1,alpha:0},2).wait(1));

	// btn_bg.png
	this.instance_3 = new lib.btn_bg_1();
	this.instance_3.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(1).to({scaleX:0.96,scaleY:0.96},2).to({scaleX:1,scaleY:1},2).wait(2).to({scaleX:0.96,scaleY:0.96},2).to({scaleX:1,scaleY:1},2).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-112,-25,224,66.6);


(lib.banana = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.banana_mc();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({rotation:-1},0).wait(1).to({rotation:1},0).wait(1).to({rotation:-2},0).wait(1).to({rotation:2},0).wait(1).to({rotation:-3},0).wait(1).to({rotation:3},0).wait(1).to({rotation:-2},0).wait(1).to({rotation:2},0).wait(1).to({rotation:-1},0).wait(1).to({rotation:1},0).wait(1).to({rotation:0},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-19,-21,38,42);


(lib.banner = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// bg
	this.instance = new lib.bg();
	this.instance.parent = this;
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(229).to({_off:false},0).to({alpha:1},10).wait(1));

	// banana
	this.instance_1 = new lib.banana("single",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(79,-6);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(28).to({_off:false},0).wait(37).to({mode:"synched",loop:false},0).wait(48).to({startPosition:0},0).wait(48).to({startPosition:0},0).wait(79));

	// txt
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAnB8IAAhdIgkAFIgaABQgbAAgSgPQgTgQAAgcIAAhlIAxAAIAABZQAAAeAfgBQASAAAcgEIAAhyIAxAAIAAD3g");
	this.shape.setTransform(-108.5,-84.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("ACiB8IAAieIhhCeIgqAAIAAj3IAwAAIAACeIBhieIArAAIAAD3gAhTB8IAAhdIgkAFIgbABQgbAAgSgPQgTgQAAgcIAAhlIAwAAIAABZQAAAeAggBQASAAAdgEIAAhyIAwAAIAAD3g");
	this.shape_1.setTransform(-96.1,-84.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AFDB8IAAhoIhUAAIAABoIgxAAIAAj3IAxAAIAABlIBUAAIAAhlIAwAAIAAD3gAACB8IAAieIhgCeIgrAAIAAj3IAxAAIAACeIBgieIArAAIAAD3gAjzB8IAAhdIglAFIgbABQgaAAgTgPQgSgQAAgcIAAhlIAwAAIAABZQAAAeAfgBQATAAAdgEIAAhyIAwAAIAAD3g");
	this.shape_2.setTransform(-80.1,-84.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AE+B8IAAj3ICkAAIAAAsIhzAAIAAA5IBiAAIAAAqIhiAAIAAA9IBzAAIAAArgADUB8IAAhoIhUAAIAABoIgxAAIAAj3IAxAAIAABlIBUAAIAAhlIAwAAIAAD3gAhsB8IAAieIhhCeIgrAAIAAj3IAxAAIAACeIBhieIArAAIAAD3gAliB8IAAhdIglAFIgbABQgaAAgTgPQgSgQAAgcIAAhlIAwAAIAABZQAAAeAfgBQATAAAdgEIAAhyIAwAAIAAD3g");
	this.shape_3.setTransform(-69,-84.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AlOFDIAAjMIg7AAIAABIQAAAogFAZQgFAagJAOQgJAQgPAFQgOAHgVgBIgSAAIAAgrIAHAAQAJABAIgEQAIgDAFgLQAGgJADgTQADgRAAgeIAAhvICbAAIAAD2gAFHhLIAAj4ICkAAIAAAsIh0AAIAAA5IBiAAIAAArIhiAAIAAA9IB0AAIAAArgADchLIAAhoIhUAAIAABoIgxAAIAAj4IAxAAIAABlIBUAAIAAhlIAwAAIAAD4gAhkhLIAAifIhhCfIgqAAIAAj4IAwAAIAACfIBhifIArAAIAAD4gAlahLIAAhdIgkAFIgbABQgbAAgSgPQgTgQAAgdIAAhlIAwAAIAABZQAAAeAggBQASAAAdgEIAAhyIAwAAIAAD4g");
	this.shape_4.setTransform(-69.8,-64.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AhWFDIAAieIhhCeIgsAAIAAj2IAxAAIAACeIBgieIAsAAIAAD2gAlOFDIAAjMIg7AAIAABIQAAAogFAZQgFAagJAOQgJAQgPAFQgOAHgVgBIgSAAIAAgrIAHAAQAJABAIgEQAIgDAFgLQAGgJADgTQADgRAAgeIAAhvICbAAIAAD2gAFHhLIAAj4ICkAAIAAAsIh0AAIAAA5IBiAAIAAArIhiAAIAAA9IB0AAIAAArgADchLIAAhoIhUAAIAABoIgxAAIAAj4IAxAAIAABlIBUAAIAAhlIAwAAIAAD4gAhkhLIAAifIhhCfIgqAAIAAj4IAwAAIAACfIBhifIArAAIAAD4gAlahLIAAhdIgkAFIgbABQgbAAgSgPQgTgQAAgdIAAhlIAwAAIAABZQAAAeAggBQASAAAdgEIAAhyIAwAAIAAD4g");
	this.shape_5.setTransform(-69.8,-64.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AATFDIAAj2IAxAAIAADLIBHAAIAAjLIAwAAIAADLIBHAAIAAjLIAwAAIAAD2gAhWFDIAAieIhhCeIgsAAIAAj2IAxAAIAACeIBgieIAsAAIAAD2gAlOFDIAAjMIg7AAIAABIQAAAogFAZQgFAagJAOQgJAQgPAFQgOAHgVgBIgSAAIAAgrIAHAAQAJABAIgEQAIgDAFgLQAGgJADgTQADgRAAgeIAAhvICbAAIAAD2gAFHhLIAAj4ICkAAIAAAsIh0AAIAAA5IBiAAIAAArIhiAAIAAA9IB0AAIAAArgADchLIAAhoIhUAAIAABoIgxAAIAAj4IAxAAIAABlIBUAAIAAhlIAwAAIAAD4gAhkhLIAAifIhhCfIgqAAIAAj4IAwAAIAACfIBhifIArAAIAAD4gAlahLIAAhdIgkAFIgbABQgbAAgSgPQgTgQAAgdIAAhlIAwAAIAABZQAAAeAggBQASAAAdgEIAAhyIAwAAIAAD4g");
	this.shape_6.setTransform(-69.8,-64.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AFaFDIAAj2ICjAAIAAAqIhzAAIAAA7IBiAAIAAArIhiAAIAAA7IBzAAIAAArgAAAFDIAAj2IAxAAIAADLIBHAAIAAjLIAwAAIAADLIBHAAIAAjLIAwAAIAAD2gAhpFDIAAieIhhCeIgsAAIAAj2IAxAAIAACeIBgieIAsAAIAAD2gAlhFDIAAjMIg7AAIAABIQAAAogFAZQgFAagJAOQgJAQgPAFQgOAHgVgBIgSAAIAAgrIAHAAQAJABAIgEQAIgDAFgLQAGgJADgTQADgRAAgeIAAhvICbAAIAAD2gAE0hLIAAj4ICkAAIAAAsIh0AAIAAA5IBiAAIAAArIhiAAIAAA9IB0AAIAAArgADJhLIAAhoIhUAAIAABoIgxAAIAAj4IAxAAIAABlIBUAAIAAhlIAwAAIAAD4gAh3hLIAAifIhhCfIgqAAIAAj4IAwAAIAACfIBhifIArAAIAAD4gAlthLIAAhdIgkAFIgbABQgbAAgSgPQgTgQAAgdIAAhlIAwAAIAABZQAAAeAggBQASAAAdgEIAAhyIAwAAIAAD4g");
	this.shape_7.setTransform(-67.9,-64.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AI/FDIAAhmIhUAAIAABmIgwAAIAAj2IAwAAIAABkIBUAAIAAhkIAxAAIAAD2gADnFDIAAj2ICkAAIAAAqIhzAAIAAA7IBiAAIAAArIhiAAIAAA7IBzAAIAAArgAhxFDIAAj2IAwAAIAADLIBGAAIAAjLIAxAAIAADLIBHAAIAAjLIAwAAIAAD2gAjcFDIAAieIhhCeIgrAAIAAj2IAxAAIAACeIBgieIAsAAIAAD2gAnTFDIAAjMIg7AAIAABIQAAAogFAZQgFAagJAOQgJAQgPAFQgOAHgVgBIgTAAIAAgrIAHAAQAKABAIgEQAIgDAFgLQAGgJADgTQADgRAAgeIAAhvICbAAIAAD2gADBhLIAAj4ICkAAIAAAsIhzAAIAAA5IBiAAIAAArIhiAAIAAA9IBzAAIAAArgABXhLIAAhoIhUAAIAABoIgwAAIAAj4IAwAAIAABlIBUAAIAAhlIAwAAIAAD4gAjphLIAAifIhhCfIgrAAIAAj4IAxAAIAACfIBhifIArAAIAAD4gAnfhLIAAhdIglAFIgbABQgaAAgTgPQgSgQAAgdIAAhlIAwAAIAABZQAAAeAfgBQATAAAdgEIAAhyIAwAAIAAD4g");
	this.shape_8.setTransform(-56.5,-64.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AIzFDIAAj2IAxAAIAABdIAxAAQAkgBAXAWQAWAVAAAiQAAAjgWAVQgWAWglgBgAJkEYIAtAAQARABAKgKQAJgIAAgRQAAgPgJgJQgKgJgRAAIgtAAgAHJFDIAAhmIhUAAIAABmIgxAAIAAj2IAxAAIAABkIBUAAIAAhkIAwAAIAAD2gABxFDIAAj2ICkAAIAAAqIh0AAIAAA7IBiAAIAAArIhiAAIAAA7IB0AAIAAArgAjoFDIAAj2IAxAAIAADLIBHAAIAAjLIAwAAIAADLIBGAAIAAjLIAxAAIAAD2gAlSFDIAAieIhhCeIgrAAIAAj2IAwAAIAACeIBhieIArAAIAAD2gApJFDIAAjMIg8AAIAABIQAAAogFAZQgEAagKAOQgJAQgPAFQgOAHgUgBIgTAAIAAgrIAHAAQAKABAHgEQAIgDAFgLQAGgJADgTQADgRAAgeIAAhvICbAAIAAD2gABLhLIAAj4ICkAAIAAAsIh0AAIAAA5IBjAAIAAArIhjAAIAAA9IB0AAIAAArgAgfhLIAAhoIhUAAIAABoIgxAAIAAj4IAxAAIAABlIBUAAIAAhlIAwAAIAAD4gAlfhLIAAifIhhCfIgrAAIAAj4IAwAAIAACfIBhifIArAAIAAD4gApWhLIAAhdIgkAFIgbABQgbAAgSgPQgTgQAAgdIAAhlIAxAAIAABZQAAAeAfgBQATAAAcgEIAAhyIAxAAIAAD4g");
	this.shape_9.setTransform(-44.7,-64.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AMhFDIhXiAIAACAIgxAAIAAj2IAxAAIAAB1IBQh1IA6AAIhTBzIBcCDgAG9FDIAAj2IAxAAIAABdIAxAAQAjgBAXAWQAXAVAAAiQAAAjgXAVQgWAWgkgBgAHuEYIAtAAQARABAJgKQAKgIAAgRQAAgPgKgJQgJgJgRAAIgtAAgAFSFDIAAhmIhUAAIAABmIgwAAIAAj2IAwAAIAABkIBUAAIAAhkIAxAAIAAD2gAgFFDIAAj2ICjAAIAAAqIhzAAIAAA7IBiAAIAAArIhiAAIAAA7IBzAAIAAArgAleFDIAAj2IAwAAIAADLIBHAAIAAjLIAxAAIAADLIBHAAIAAjLIAwAAIAAD2gAnJFDIAAieIhhCeIgrAAIAAj2IAxAAIAACeIBgieIAsAAIAAD2gArAFDIAAjMIg7AAIAABIQAAAogFAZQgFAagJAOQgJAQgPAFQgOAHgVgBIgTAAIAAgrIAHAAQAKABAIgEQAIgDAFgLQAGgJADgTQADgRAAgeIAAhvICbAAIAAD2gAgrhLIAAj4ICjAAIAAAsIhzAAIAAA5IBiAAIAAArIhiAAIAAA9IBzAAIAAArgAiVhLIAAhoIhUAAIAABoIgxAAIAAj4IAxAAIAABlIBUAAIAAhlIAwAAIAAD4gAnWhLIAAifIhhCfIgrAAIAAj4IAxAAIAACfIBhifIArAAIAAD4gArMhLIAAhdIglAFIgbABQgaAAgTgPQgSgQAAgdIAAhlIAwAAIAABZQAAAeAfgBQATAAAdgEIAAhyIAwAAIAAD4g");
	this.shape_10.setTransform(-32.8,-64.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AMfEpQgLgLgGgRQgFgPgCgPIAAgyQAAgmAFgSQAFgSAOgPQAbgbApAAQAoAAAbAbQAZAaAAA4IgBA7IgCANIgFAPIgHAPQgGAJgEAEQgbAcgoAAQgpAAgbgcgANDCBQgIAKgCAOQgCAUAAAWIABAmQABALACAJQADAKAFAFQANANATAAQAUAAALgNQAHgIADgOQACgPAAglQAAgegCgNQgDgNgHgJQgMgNgTAAQgUAAgMANgAK/FCIhXiBIAACBIgxAAIAAj3IAxAAIAAB2IBQh2IA6AAIhTB0IBcCDgAFbFCIAAj3IAxAAIAABdIAxAAQAjAAAXAWQAXAVAAAiQAAAjgXAVQgWAVgkAAgAGMEXIAtAAQARAAAJgJQAKgJAAgQQAAgPgKgJQgJgKgRAAIgtAAgADwFCIAAhnIhUAAIAABnIgwAAIAAj3IAwAAIAABlIBUAAIAAhlIAxAAIAAD3gAhnFCIAAj3ICjAAIAAArIhyAAIAAA6IBhAAIAAArIhhAAIAAA8IByAAIAAArgAnAFCIAAj3IAwAAIAADMIBHAAIAAjMIAxAAIAADMIBHAAIAAjMIAwAAIAAD3gAorFCIAAieIhhCeIgrAAIAAj3IAxAAIAACfIBgifIAsAAIAAD3gAsiFCIAAjMIg7AAIAABIQAAAogFAZQgFAagJAOQgJAPgPAGQgOAGgVAAIgTAAIAAgrIAHAAQAKAAAIgDQAIgDAFgLQAGgJADgTQADgRAAgeIAAhwICbAAIAAD3gAiNhNIAAj3ICjAAIAAArIhyAAIAAA6IBhAAIAAArIhhAAIAAA8IByAAIAAArgAj3hNIAAhnIhUAAIAABnIgxAAIAAj3IAxAAIAABlIBUAAIAAhlIAwAAIAAD3gAo4hNIAAieIhhCeIgrAAIAAj3IAxAAIAACeIBhieIArAAIAAD3gAsuhNIAAhcIglAFIgbABQgaAAgTgPQgSgQAAgdIAAhlIAwAAIAABZQAAAdAfAAQATAAAdgFIAAhxIAwAAIAAD3g");
	this.shape_11.setTransform(-23,-64.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AunIMIAAj4IAxAAIAAD4gAMfBiQgLgLgGgRQgFgPgCgPIAAgxQAAgmAFgSQAFgSAOgPQAbgbApAAQAoAAAbAbQAZAaAAA4IgBA6IgCANIgFAPIgHAPQgGAJgEAEQgbAcgoAAQgpAAgbgcgANDhFQgIAKgCAOQgCAUAAAWIABAlQABALACAJQADAKAFAFQANANATAAQAUAAALgNQAHgIADgOQACgPAAgkQAAgegCgNQgDgNgHgJQgMgNgTAAQgUAAgMANgAK/B7IhXiAIAACAIgxAAIAAj2IAxAAIAAB2IBQh2IA6AAIhTB0IBcCCgAFbB7IAAj2IAxAAIAABdIAxAAQAjAAAXAWQAXAUAAAiQAAAjgXAVQgWAVgkAAgAGMBQIAtAAQARAAAJgJQAKgJAAgQQAAgPgKgJQgJgKgRAAIgtAAgADwB7IAAhnIhUAAIAABnIgwAAIAAj2IAwAAIAABlIBUAAIAAhlIAxAAIAAD2gAhnB7IAAj2ICjAAIAAArIhyAAIAAA6IBhAAIAAAqIhhAAIAAA8IByAAIAAArgAnAB7IAAj2IAwAAIAADLIBHAAIAAjLIAxAAIAADLIBHAAIAAjLIAwAAIAAD2gAorB7IAAidIhhCdIgrAAIAAj2IAxAAIAACeIBgieIAsAAIAAD2gAsiB7IAAjLIg7AAIAABIQAAAngFAZQgFAagJAOQgJAPgPAGQgOAGgVAAIgTAAIAAgrIAHAAQAKAAAIgDQAIgDAFgLQAGgJADgTQADgRAAgdIAAhwICbAAIAAD2gAiNkUIAAj3ICjAAIAAArIhyAAIAAA6IBhAAIAAArIhhAAIAAA8IByAAIAAArgAj3kUIAAhnIhUAAIAABnIgxAAIAAj3IAxAAIAABlIBUAAIAAhlIAwAAIAAD3gAo4kUIAAieIhhCeIgrAAIAAj3IAxAAIAACeIBhieIArAAIAAD3gAsukUIAAhcIglAFIgbABQgaAAgTgPQgSgQAAgdIAAhlIAwAAIAABZQAAAdAfAAQATAAAdgFIAAhxIAwAAIAAD3g");
	this.shape_12.setTransform(-23,-44.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AsTIIQgPgFgMgKQgMgKgIgOQgIgQgDgRIAwAAQAJAjAiAAQASAAALgKQALgJAAgPQAAgQgKgIQgJgJgTAAIggAAIAAgoIAgAAQARAAAIgIQAJgIAAgPQAAgPgKgHQgJgIgRAAQgSAAgKAKQgLAKgDAPIgxAAQADgTAIgOQAJgOALgKQAMgJAPgGQARgFAQAAQAkAAAZATQAYATAAAfQAAAjghASQAkAQAAAoQAAAhgZAVQgZAUgnAAQgQAAgQgFgAunILIAAj4IAxAAIAAD4gAMfBhQgLgLgGgRQgFgPgCgPIAAgxQAAgmAFgSQAFgSAOgPQAbgbApAAQAoAAAbAbQAZAaAAA4IgBA6IgCANIgFAPIgHAPQgGAJgEAEQgbAcgoAAQgpAAgbgcgANDhGQgIAKgCAOQgCAUAAAWIABAlQABALACAJQADAKAFAFQANANATAAQAUAAALgNQAHgIADgOQACgPAAgkQAAgegCgNQgDgNgHgJQgMgNgTAAQgUAAgMANgAK/B6IhXiAIAACAIgxAAIAAj2IAxAAIAAB2IBQh2IA6AAIhTB0IBcCCgAFbB6IAAj2IAxAAIAABdIAxAAQAjAAAXAWQAXAUAAAiQAAAjgXAVQgWAVgkAAgAGMBPIAtAAQARAAAJgJQAKgJAAgQQAAgPgKgJQgJgKgRAAIgtAAgADwB6IAAhnIhUAAIAABnIgwAAIAAj2IAwAAIAABlIBUAAIAAhlIAxAAIAAD2gAhnB6IAAj2ICjAAIAAArIhyAAIAAA6IBhAAIAAAqIhhAAIAAA8IByAAIAAArgAnAB6IAAj2IAwAAIAADLIBHAAIAAjLIAxAAIAADLIBHAAIAAjLIAwAAIAAD2gAorB6IAAidIhhCdIgrAAIAAj2IAxAAIAACeIBgieIAsAAIAAD2gAsiB6IAAjLIg7AAIAABIQAAAngFAZQgFAagJAOQgJAPgPAGQgOAGgVAAIgTAAIAAgrIAHAAQAKAAAIgDQAIgDAFgLQAGgJADgTQADgRAAgdIAAhwICbAAIAAD2gAiNkVIAAj3ICjAAIAAArIhyAAIAAA6IBhAAIAAArIhhAAIAAA8IByAAIAAArgAj3kVIAAhnIhUAAIAABnIgxAAIAAj3IAxAAIAABlIBUAAIAAhlIAwAAIAAD3gAo4kVIAAieIhhCeIgrAAIAAj3IAxAAIAACeIBhieIArAAIAAD3gAsukVIAAhcIglAFIgbABQgaAAgTgPQgSgQAAgdIAAhlIAwAAIAABZQAAAdAfAAQATAAAdgFIAAhxIAwAAIAAD3g");
	this.shape_13.setTransform(-23,-44.2);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AsTIIQgPgFgMgKQgMgKgIgOQgIgQgDgRIAwAAQAJAjAiAAQASAAALgKQALgJAAgPQAAgQgKgIQgJgJgTAAIggAAIAAgoIAgAAQARAAAIgIQAJgIAAgPQAAgPgKgHQgJgIgRAAQgSAAgKAKQgLAKgDAPIgxAAQADgTAIgOQAJgOALgKQAMgJAPgGQARgFAQAAQAkAAAZATQAYATAAAfQAAAjghASQAkAQAAAoQAAAhgZAVQgZAUgnAAQgQAAgQgFgAnpILIAAjNIhBAAIAAgrICzAAIAAArIhBAAIAADNgAunILIAAj4IAxAAIAAD4gAMfBhQgLgLgGgRQgFgPgCgPIAAgxQAAgmAFgSQAFgSAOgPQAbgbApAAQAoAAAbAbQAZAaAAA4IgBA6IgCANIgFAPIgHAPQgGAJgEAEQgbAcgoAAQgpAAgbgcgANDhGQgIAKgCAOQgCAUAAAWIABAlQABALACAJQADAKAFAFQANANATAAQAUAAALgNQAHgIADgOQACgPAAgkQAAgegCgNQgDgNgHgJQgMgNgTAAQgUAAgMANgAK/B6IhXiAIAACAIgxAAIAAj2IAxAAIAAB2IBQh2IA6AAIhTB0IBcCCgAFbB6IAAj2IAxAAIAABdIAxAAQAjAAAXAWQAXAUAAAiQAAAjgXAVQgWAVgkAAgAGMBPIAtAAQARAAAJgJQAKgJAAgQQAAgPgKgJQgJgKgRAAIgtAAgADwB6IAAhnIhUAAIAABnIgwAAIAAj2IAwAAIAABlIBUAAIAAhlIAxAAIAAD2gAhnB6IAAj2ICjAAIAAArIhyAAIAAA6IBhAAIAAAqIhhAAIAAA8IByAAIAAArgAnAB6IAAj2IAwAAIAADLIBHAAIAAjLIAxAAIAADLIBHAAIAAjLIAwAAIAAD2gAorB6IAAidIhhCdIgrAAIAAj2IAxAAIAACeIBgieIAsAAIAAD2gAsiB6IAAjLIg7AAIAABIQAAAngFAZQgFAagJAOQgJAPgPAGQgOAGgVAAIgTAAIAAgrIAHAAQAKAAAIgDQAIgDAFgLQAGgJADgTQADgRAAgdIAAhwICbAAIAAD2gAiNkVIAAj3ICjAAIAAArIhyAAIAAA6IBhAAIAAArIhhAAIAAA8IByAAIAAArgAj3kVIAAhnIhUAAIAABnIgxAAIAAj3IAxAAIAABlIBUAAIAAhlIAwAAIAAD3gAo4kVIAAieIhhCeIgrAAIAAj3IAxAAIAACeIBhieIArAAIAAD3gAsukVIAAhcIglAFIgbABQgaAAgTgPQgSgQAAgdIAAhlIAwAAIAABZQAAAdAfAAQATAAAdgFIAAhxIAwAAIAAD3g");
	this.shape_14.setTransform(-23,-44.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AsTIIQgPgFgMgKQgMgKgIgOQgIgQgDgRIAwAAQAJAjAiAAQASAAALgKQALgJAAgPQAAgQgKgIQgJgJgTAAIggAAIAAgoIAgAAQARAAAIgIQAJgIAAgPQAAgPgKgHQgJgIgRAAQgSAAgKAKQgLAKgDAPIgxAAQADgTAIgOQAJgOALgKQAMgJAPgGQARgFAQAAQAkAAAZATQAYATAAAfQAAAjghASQAkAQAAAoQAAAhgZAVQgZAUgnAAQgQAAgQgFgAlQILIAAj4IBkAAQAjAAAWATQAUASAAAgQAAAjgfARQALAFAIAIQAQARAAAaQAAAPgGAOQgFAOgKAIQgKAKgOAFQgPAFgQAAgAkfHgIAzAAQAPAAAIgJQAJgIAAgOQAAgOgJgIQgIgIgPAAIgzAAgAkfF4IAvAAQAPAAAJgIQAJgIAAgNQAAgNgJgIQgJgIgPAAIgvAAgAnpILIAAjNIhBAAIAAgrICzAAIAAArIhBAAIAADNgAunILIAAj4IAxAAIAAD4gAMfBhQgLgLgGgRQgFgPgCgPIAAgxQAAgmAFgSQAFgSAOgPQAbgbApAAQAoAAAbAbQAZAaAAA4IgBA6IgCANIgFAPIgHAPQgGAJgEAEQgbAcgoAAQgpAAgbgcgANDhGQgIAKgCAOQgCAUAAAWIABAlQABALACAJQADAKAFAFQANANATAAQAUAAALgNQAHgIADgOQACgPAAgkQAAgegCgNQgDgNgHgJQgMgNgTAAQgUAAgMANgAK/B6IhXiAIAACAIgxAAIAAj2IAxAAIAAB2IBQh2IA6AAIhTB0IBcCCgAFbB6IAAj2IAxAAIAABdIAxAAQAjAAAXAWQAXAUAAAiQAAAjgXAVQgWAVgkAAgAGMBPIAtAAQARAAAJgJQAKgJAAgQQAAgPgKgJQgJgKgRAAIgtAAgADwB6IAAhnIhUAAIAABnIgwAAIAAj2IAwAAIAABlIBUAAIAAhlIAxAAIAAD2gAhnB6IAAj2ICjAAIAAArIhyAAIAAA6IBhAAIAAAqIhhAAIAAA8IByAAIAAArgAnAB6IAAj2IAwAAIAADLIBHAAIAAjLIAxAAIAADLIBHAAIAAjLIAwAAIAAD2gAorB6IAAidIhhCdIgrAAIAAj2IAxAAIAACeIBgieIAsAAIAAD2gAsiB6IAAjLIg7AAIAABIQAAAngFAZQgFAagJAOQgJAPgPAGQgOAGgVAAIgTAAIAAgrIAHAAQAKAAAIgDQAIgDAFgLQAGgJADgTQADgRAAgdIAAhwICbAAIAAD2gAiNkVIAAj3ICjAAIAAArIhyAAIAAA6IBhAAIAAArIhhAAIAAA8IByAAIAAArgAj3kVIAAhnIhUAAIAABnIgxAAIAAj3IAxAAIAABlIBUAAIAAhlIAwAAIAAD3gAo4kVIAAieIhhCeIgrAAIAAj3IAxAAIAACeIBhieIArAAIAAD3gAsukVIAAhcIglAFIgbABQgaAAgTgPQgSgQAAgdIAAhlIAwAAIAABZQAAAdAfAAQATAAAdgFIAAhxIAwAAIAAD3g");
	this.shape_15.setTransform(-23,-44.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AhaHyQgMgNgFgQQgGgTAAgKIgBgzQAAgjAFgVQAFgSAOgPQAbgbApAAQAoAAAaAbQAZAaAAA4IgBA7IgCANIgFAPQgDAKgEAFQgFAJgFAFQgaAbgoAAQgpAAgbgbgAg2FKQgHAIgCAPQgCAOAAAdIAAAlQABALACAJQADAKAFAFQAOAOASAAQAUAAAKgOQAHgHADgPQACgOAAgmQAAgegCgNQgDgOgHgHQgKgOgUAAQgUAAgMAOgAsTIIQgPgFgMgKQgMgKgIgOQgIgQgDgRIAwAAQAJAjAiAAQASAAALgKQALgJAAgPQAAgQgKgIQgJgJgTAAIggAAIAAgoIAgAAQARAAAIgIQAJgIAAgPQAAgPgKgHQgJgIgRAAQgSAAgKAKQgLAKgDAPIgxAAQADgTAIgOQAJgOALgKQAMgJAPgGQARgFAQAAQAkAAAZATQAYATAAAfQAAAjghASQAkAQAAAoQAAAhgZAVQgZAUgnAAQgQAAgQgFgAlQILIAAj4IBkAAQAjAAAWATQAUASAAAgQAAAjgfARQALAFAIAIQAQARAAAaQAAAPgGAOQgFAOgKAIQgKAKgOAFQgPAFgQAAgAkfHgIAzAAQAPAAAIgJQAJgIAAgOQAAgOgJgIQgIgIgPAAIgzAAgAkfF4IAvAAQAPAAAJgIQAJgIAAgNQAAgNgJgIQgJgIgPAAIgvAAgAnpILIAAjNIhBAAIAAgrICzAAIAAArIhBAAIAADNgAunILIAAj4IAxAAIAAD4gAMfBhQgLgLgGgRQgFgPgCgPIAAgxQAAgmAFgSQAFgSAOgPQAbgbApAAQAoAAAbAbQAZAaAAA4IgBA6IgCANIgFAPIgHAPQgGAJgEAEQgbAcgoAAQgpAAgbgcgANDhGQgIAKgCAOQgCAUAAAWIABAlQABALACAJQADAKAFAFQANANATAAQAUAAALgNQAHgIADgOQACgPAAgkQAAgegCgNQgDgNgHgJQgMgNgTAAQgUAAgMANgAK/B6IhXiAIAACAIgxAAIAAj2IAxAAIAAB2IBQh2IA6AAIhTB0IBcCCgAFbB6IAAj2IAxAAIAABdIAxAAQAjAAAXAWQAXAUAAAiQAAAjgXAVQgWAVgkAAgAGMBPIAtAAQARAAAJgJQAKgJAAgQQAAgPgKgJQgJgKgRAAIgtAAgADwB6IAAhnIhUAAIAABnIgwAAIAAj2IAwAAIAABlIBUAAIAAhlIAxAAIAAD2gAhnB6IAAj2ICjAAIAAArIhyAAIAAA6IBhAAIAAAqIhhAAIAAA8IByAAIAAArgAnAB6IAAj2IAwAAIAADLIBHAAIAAjLIAxAAIAADLIBHAAIAAjLIAwAAIAAD2gAorB6IAAidIhhCdIgrAAIAAj2IAxAAIAACeIBgieIAsAAIAAD2gAsiB6IAAjLIg7AAIAABIQAAAngFAZQgFAagJAOQgJAPgPAGQgOAGgVAAIgTAAIAAgrIAHAAQAKAAAIgDQAIgDAFgLQAGgJADgTQADgRAAgdIAAhwICbAAIAAD2gAiNkVIAAj3ICjAAIAAArIhyAAIAAA6IBhAAIAAArIhhAAIAAA8IByAAIAAArgAj3kVIAAhnIhUAAIAABnIgxAAIAAj3IAxAAIAABlIBUAAIAAhlIAwAAIAAD3gAo4kVIAAieIhhCeIgrAAIAAj3IAxAAIAACeIBhieIArAAIAAD3gAsukVIAAhcIglAFIgbABQgaAAgTgPQgSgQAAgdIAAhlIAwAAIAABZQAAAdAfAAQATAAAdgFIAAhxIAwAAIAAD3g");
	this.shape_16.setTransform(-23,-44.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AhaHyQgMgNgFgQQgGgTAAgKIgBgzQAAgjAFgVQAFgSAOgPQAbgbApAAQAoAAAaAbQAZAaAAA4IgBA7IgCANIgFAPQgDAKgEAFQgFAJgFAFQgaAbgoAAQgpAAgbgbgAg2FKQgHAIgCAPQgCAOAAAdIAAAlQABALACAJQADAKAFAFQAOAOASAAQAUAAAKgOQAHgHADgPQACgOAAgmQAAgegCgNQgDgOgHgHQgKgOgUAAQgUAAgMAOgAsTIIQgPgFgMgKQgMgKgIgOQgIgQgDgRIAwAAQAJAjAiAAQASAAALgKQALgJAAgPQAAgQgKgIQgJgJgTAAIggAAIAAgoIAgAAQARAAAIgIQAJgIAAgPQAAgPgKgHQgJgIgRAAQgSAAgKAKQgLAKgDAPIgxAAQADgTAIgOQAJgOALgKQAMgJAPgGQARgFAQAAQAkAAAZATQAYATAAAfQAAAjghASQAkAQAAAoQAAAhgZAVQgZAUgnAAQgQAAgQgFgAB2ILIAAj4IAxAAIAAD4gAlQILIAAj4IBkAAQAjAAAWATQAUASAAAgQAAAjgfARQALAFAIAIQAQARAAAaQAAAPgGAOQgFAOgKAIQgKAKgOAFQgPAFgQAAgAkfHgIAzAAQAPAAAIgJQAJgIAAgOQAAgOgJgIQgIgIgPAAIgzAAgAkfF4IAvAAQAPAAAJgIQAJgIAAgNQAAgNgJgIQgJgIgPAAIgvAAgAnpILIAAjNIhBAAIAAgrICzAAIAAArIhBAAIAADNgAunILIAAj4IAxAAIAAD4gACiD7IAAgrIAnAAIAAArgABUD7IAAgrIAnAAIAAArgAMfBhQgLgLgGgRQgFgPgCgPIAAgxQAAgmAFgSQAFgSAOgPQAbgbApAAQAoAAAbAbQAZAaAAA4IgBA6IgCANIgFAPIgHAPQgGAJgEAEQgbAcgoAAQgpAAgbgcgANDhGQgIAKgCAOQgCAUAAAWIABAlQABALACAJQADAKAFAFQANANATAAQAUAAALgNQAHgIADgOQACgPAAgkQAAgegCgNQgDgNgHgJQgMgNgTAAQgUAAgMANgAK/B6IhXiAIAACAIgxAAIAAj2IAxAAIAAB2IBQh2IA6AAIhTB0IBcCCgAFbB6IAAj2IAxAAIAABdIAxAAQAjAAAXAWQAXAUAAAiQAAAjgXAVQgWAVgkAAgAGMBPIAtAAQARAAAJgJQAKgJAAgQQAAgPgKgJQgJgKgRAAIgtAAgADwB6IAAhnIhUAAIAABnIgwAAIAAj2IAwAAIAABlIBUAAIAAhlIAxAAIAAD2gAhnB6IAAj2ICjAAIAAArIhyAAIAAA6IBhAAIAAAqIhhAAIAAA8IByAAIAAArgAnAB6IAAj2IAwAAIAADLIBHAAIAAjLIAxAAIAADLIBHAAIAAjLIAwAAIAAD2gAorB6IAAidIhhCdIgrAAIAAj2IAxAAIAACeIBgieIAsAAIAAD2gAsiB6IAAjLIg7AAIAABIQAAAngFAZQgFAagJAOQgJAPgPAGQgOAGgVAAIgTAAIAAgrIAHAAQAKAAAIgDQAIgDAFgLQAGgJADgTQADgRAAgdIAAhwICbAAIAAD2gAiNkVIAAj3ICjAAIAAArIhyAAIAAA6IBhAAIAAArIhhAAIAAA8IByAAIAAArgAj3kVIAAhnIhUAAIAABnIgxAAIAAj3IAxAAIAABlIBUAAIAAhlIAwAAIAAD3gAo4kVIAAieIhhCeIgrAAIAAj3IAxAAIAACeIBhieIArAAIAAD3gAsukVIAAhcIglAFIgbABQgaAAgTgPQgSgQAAgdIAAhlIAwAAIAABZQAAAdAfAAQATAAAdgFIAAhxIAwAAIAAD3g");
	this.shape_17.setTransform(-23,-44.2);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AhaHyQgMgNgFgQQgGgTAAgKIgBgzQAAgjAFgVQAFgSAOgPQAbgbApAAQAoAAAaAbQAZAaAAA4IgBA7IgCANIgFAPQgDAKgEAFQgFAJgFAFQgaAbgoAAQgpAAgbgbgAg2FKQgHAIgCAPQgCAOAAAdIAAAlQABALACAJQADAKAFAFQAOAOASAAQAUAAAKgOQAHgHADgPQACgOAAgmQAAgegCgNQgDgOgHgHQgKgOgUAAQgUAAgMAOgAsTIIQgPgFgMgKQgMgKgIgOQgIgQgDgRIAwAAQAJAjAiAAQASAAALgKQALgJAAgPQAAgQgKgIQgJgJgTAAIggAAIAAgoIAgAAQARAAAIgIQAJgIAAgPQAAgPgKgHQgJgIgRAAQgSAAgKAKQgLAKgDAPIgxAAQADgTAIgOQAJgOALgKQAMgJAPgGQARgFAQAAQAkAAAZATQAYATAAAfQAAAjghASQAkAQAAAoQAAAhgZAVQgZAUgnAAQgQAAgQgFgAGSILIAAiQIgwBdIghAAIgvhdIAACQIgxAAIAAj4IAwAAIBBCGIBBiGIAvAAIAAD4gAB2ILIAAj4IAxAAIAAD4gAlQILIAAj4IBkAAQAjAAAWATQAUASAAAgQAAAjgfARQALAFAIAIQAQARAAAaQAAAPgGAOQgFAOgKAIQgKAKgOAFQgPAFgQAAgAkfHgIAzAAQAPAAAIgJQAJgIAAgOQAAgOgJgIQgIgIgPAAIgzAAgAkfF4IAvAAQAPAAAJgIQAJgIAAgNQAAgNgJgIQgJgIgPAAIgvAAgAnpILIAAjNIhBAAIAAgrICzAAIAAArIhBAAIAADNgAunILIAAj4IAxAAIAAD4gACiD7IAAgrIAnAAIAAArgABUD7IAAgrIAnAAIAAArgAMfBhQgLgLgGgRQgFgPgCgPIAAgxQAAgmAFgSQAFgSAOgPQAbgbApAAQAoAAAbAbQAZAaAAA4IgBA6IgCANIgFAPIgHAPQgGAJgEAEQgbAcgoAAQgpAAgbgcgANDhGQgIAKgCAOQgCAUAAAWIABAlQABALACAJQADAKAFAFQANANATAAQAUAAALgNQAHgIADgOQACgPAAgkQAAgegCgNQgDgNgHgJQgMgNgTAAQgUAAgMANgAK/B6IhXiAIAACAIgxAAIAAj2IAxAAIAAB2IBQh2IA6AAIhTB0IBcCCgAFbB6IAAj2IAxAAIAABdIAxAAQAjAAAXAWQAXAUAAAiQAAAjgXAVQgWAVgkAAgAGMBPIAtAAQARAAAJgJQAKgJAAgQQAAgPgKgJQgJgKgRAAIgtAAgADwB6IAAhnIhUAAIAABnIgwAAIAAj2IAwAAIAABlIBUAAIAAhlIAxAAIAAD2gAhnB6IAAj2ICjAAIAAArIhyAAIAAA6IBhAAIAAAqIhhAAIAAA8IByAAIAAArgAnAB6IAAj2IAwAAIAADLIBHAAIAAjLIAxAAIAADLIBHAAIAAjLIAwAAIAAD2gAorB6IAAidIhhCdIgrAAIAAj2IAxAAIAACeIBgieIAsAAIAAD2gAsiB6IAAjLIg7AAIAABIQAAAngFAZQgFAagJAOQgJAPgPAGQgOAGgVAAIgTAAIAAgrIAHAAQAKAAAIgDQAIgDAFgLQAGgJADgTQADgRAAgdIAAhwICbAAIAAD2gAiNkVIAAj3ICjAAIAAArIhyAAIAAA6IBhAAIAAArIhhAAIAAA8IByAAIAAArgAj3kVIAAhnIhUAAIAABnIgxAAIAAj3IAxAAIAABlIBUAAIAAhlIAwAAIAAD3gAo4kVIAAieIhhCeIgrAAIAAj3IAxAAIAACeIBhieIArAAIAAD3gAsukVIAAhcIglAFIgbABQgaAAgTgPQgSgQAAgdIAAhlIAwAAIAABZQAAAdAfAAQATAAAdgFIAAhxIAwAAIAAD3g");
	this.shape_18.setTransform(-23,-44.2);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AhaHyQgMgNgFgQQgGgTAAgKIgBgzQAAgjAFgVQAFgSAOgPQAbgbApAAQAoAAAaAbQAZAaAAA4IgBA7IgCANIgFAPQgDAKgEAFQgFAJgFAFQgaAbgoAAQgpAAgbgbgAg2FKQgHAIgCAPQgCAOAAAdIAAAlQABALACAJQADAKAFAFQAOAOASAAQAUAAAKgOQAHgHADgPQACgOAAgmQAAgegCgNQgDgOgHgHQgKgOgUAAQgUAAgMAOgAsTIIQgPgFgMgKQgMgKgIgOQgIgQgDgRIAwAAQAJAjAiAAQASAAALgKQALgJAAgPQAAgQgKgIQgJgJgTAAIggAAIAAgoIAgAAQARAAAIgIQAJgIAAgPQAAgPgKgHQgJgIgRAAQgSAAgKAKQgLAKgDAPIgxAAQADgTAIgOQAJgOALgKQAMgJAPgGQARgFAQAAQAkAAAZATQAYATAAAfQAAAjghASQAkAQAAAoQAAAhgZAVQgZAUgnAAQgQAAgQgFgAKJILIAAifIhhCfIgsAAIAAj4IAxAAIAACfIBhifIArAAIAAD4gAGSILIAAiQIgwBdIghAAIgvhdIAACQIgxAAIAAj4IAwAAIBBCGIBBiGIAvAAIAAD4gAB2ILIAAj4IAxAAIAAD4gAlQILIAAj4IBkAAQAjAAAWATQAUASAAAgQAAAjgfARQALAFAIAIQAQARAAAaQAAAPgGAOQgFAOgKAIQgKAKgOAFQgPAFgQAAgAkfHgIAzAAQAPAAAIgJQAJgIAAgOQAAgOgJgIQgIgIgPAAIgzAAgAkfF4IAvAAQAPAAAJgIQAJgIAAgNQAAgNgJgIQgJgIgPAAIgvAAgAnpILIAAjNIhBAAIAAgrICzAAIAAArIhBAAIAADNgAunILIAAj4IAxAAIAAD4gACiD7IAAgrIAnAAIAAArgABUD7IAAgrIAnAAIAAArgAMfBhQgLgLgGgRQgFgPgCgPIAAgxQAAgmAFgSQAFgSAOgPQAbgbApAAQAoAAAbAbQAZAaAAA4IgBA6IgCANIgFAPIgHAPQgGAJgEAEQgbAcgoAAQgpAAgbgcgANDhGQgIAKgCAOQgCAUAAAWIABAlQABALACAJQADAKAFAFQANANATAAQAUAAALgNQAHgIADgOQACgPAAgkQAAgegCgNQgDgNgHgJQgMgNgTAAQgUAAgMANgAK/B6IhXiAIAACAIgxAAIAAj2IAxAAIAAB2IBQh2IA6AAIhTB0IBcCCgAFbB6IAAj2IAxAAIAABdIAxAAQAjAAAXAWQAXAUAAAiQAAAjgXAVQgWAVgkAAgAGMBPIAtAAQARAAAJgJQAKgJAAgQQAAgPgKgJQgJgKgRAAIgtAAgADwB6IAAhnIhUAAIAABnIgwAAIAAj2IAwAAIAABlIBUAAIAAhlIAxAAIAAD2gAhnB6IAAj2ICjAAIAAArIhyAAIAAA6IBhAAIAAAqIhhAAIAAA8IByAAIAAArgAnAB6IAAj2IAwAAIAADLIBHAAIAAjLIAxAAIAADLIBHAAIAAjLIAwAAIAAD2gAorB6IAAidIhhCdIgrAAIAAj2IAxAAIAACeIBgieIAsAAIAAD2gAsiB6IAAjLIg7AAIAABIQAAAngFAZQgFAagJAOQgJAPgPAGQgOAGgVAAIgTAAIAAgrIAHAAQAKAAAIgDQAIgDAFgLQAGgJADgTQADgRAAgdIAAhwICbAAIAAD2gAiNkVIAAj3ICjAAIAAArIhyAAIAAA6IBhAAIAAArIhhAAIAAA8IByAAIAAArgAj3kVIAAhnIhUAAIAABnIgxAAIAAj3IAxAAIAABlIBUAAIAAhlIAwAAIAAD3gAo4kVIAAieIhhCeIgrAAIAAj3IAxAAIAACeIBhieIArAAIAAD3gAsukVIAAhcIglAFIgbABQgaAAgTgPQgSgQAAgdIAAhlIAwAAIAABZQAAAdAfAAQATAAAdgFIAAhxIAwAAIAAD3g");
	this.shape_19.setTransform(-23,-44.2);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AlNHyQgMgNgFgQQgGgTAAgKIgBgzQAAgjAFgVQAFgSAOgPQAbgbApAAQApAAAaAbQAZAaAAA4IgBA7IgCANIgFAPQgDAKgEAFQgFAJgFAFQgaAbgpAAQgpAAgbgbgAkpFKQgGAIgDAPQgCAOAAAdIAAAlQABALACAJQAEAKAEAFQAOAOASAAQAUAAALgOQAHgHADgPQADgOAAgmQAAgegDgNQgDgOgHgHQgLgOgUAAQgTAAgNAOgAwGIIQgPgFgMgKQgMgKgIgOQgIgQgDgRIAxAAQAIAjAiAAQASAAALgKQALgJAAgPQAAgQgJgIQgKgJgTAAIggAAIAAgoIAhAAQAQAAAJgIQAIgIABgPQAAgPgLgHQgJgIgQAAQgTAAgKAKQgKAKgEAPIgxAAQAEgTAIgOQAIgOAMgKQALgJAQgGQAQgFARAAQAjAAAZATQAYATAAAfQAAAjghASQAkAQAAAoQAAAhgYAVQgaAUgnAAQgPAAgRgFgARRILIAAgvIAxAAIAAAvgAGWILIAAifIhhCfIgrAAIAAj4IAwAAIAACfIBhifIAsAAIAAD4gACfILIAAiQIgvBdIgiAAIgvhdIAACQIgwAAIAAj4IAvAAIBBCGIBBiGIAvAAIAAD4gAh7ILIAAj4IAwAAIAAD4gApDILIAAj4IBkAAQAjAAAWATQAUASABAgQAAAjggARQALAFAIAIQAQARAAAaQAAAPgGAOQgFAOgKAIQgKAKgOAFQgPAFgQAAgAoSHgIAzAAQAPAAAJgJQAIgIABgOQgBgOgIgIQgJgIgPAAIgzAAgAoSF4IAwAAQAPAAAIgIQAJgIAAgNQAAgNgJgIQgJgIgOAAIgwAAgArcILIAAjNIhAAAIAAgrICyAAIAAArIhBAAIAADNgAyaILIAAj4IAxAAIAAD4gARSG9IAAgKQAAgTAOgRIAaghQAKgOAAgKQAAgMgIgIQgIgIgMAAQgOAAgHAIQgIAJABAMIguAAQAAggAVgTQAVgTAgAAQAeAAAWATQAWATAAAgQgBAVgRAWIgaAiQgFAIgBAKIAAAHgAhQD7IAAgrIAnAAIAAArgAidD7IAAgrIAmAAIAAArgAIsBhQgLgLgGgRQgFgPgBgPIgBgxQAAgmAFgSQAFgSAOgPQAbgbApAAQAoAAAbAbQAZAaAAA4IgBA6IgCANIgFAPIgHAPQgGAJgEAEQgaAcgpAAQgpAAgbgcgAJQhGQgHAKgDAOQgBAUAAAWIAAAlQABALACAJQAEAKAEAFQAOANASAAQAUAAALgNQAHgIADgOQADgPAAgkQAAgegDgNQgDgNgHgJQgLgNgUAAQgUAAgMANgAHNB6IhYiAIAACAIgxAAIAAj2IAxAAIAAB2IBRh2IA5AAIhTB0IBcCCgABoB6IAAj2IAxAAIAABdIAxAAQAkAAAWAWQAXAUAAAiQAAAjgXAVQgVAVglAAgACZBPIAtAAQARAAAJgJQAKgJAAgQQAAgPgKgJQgJgKgRAAIgtAAgAgCB6IAAhnIhTAAIAABnIgxAAIAAj2IAxAAIAABlIBTAAIAAhlIAwAAIAAD2gAlZB6IAAj2ICjAAIAAArIhzAAIAAA6IBiAAIAAAqIhiAAIAAA8IBzAAIAAArgAqzB6IAAj2IAxAAIAADLIBHAAIAAjLIAwAAIAADLIBHAAIAAjLIAwAAIAAD2gAsdB6IAAidIhhCdIgsAAIAAj2IAxAAIAACeIBgieIAsAAIAAD2gAwVB6IAAjLIg7AAIAABIQAAAngFAZQgFAagJAOQgJAPgPAGQgOAGgVAAIgSAAIAAgrIAHAAQAJAAAIgDQAIgDAFgLQAGgJADgTQADgRAAgdIAAhwICbAAIAAD2gAl/kVIAAj3ICkAAIAAArIh0AAIAAA6IBiAAIAAArIhiAAIAAA8IB0AAIAAArgAnqkVIAAhnIhUAAIAABnIgxAAIAAj3IAxAAIAABlIBUAAIAAhlIAwAAIAAD3gAsrkVIAAieIhhCeIgqAAIAAj3IAwAAIAACeIBhieIArAAIAAD3gAwhkVIAAhcIgkAFIgbABQgbAAgSgPQgTgQAAgdIAAhlIAwAAIAABZQAAAdAgAAQASAAAdgFIAAhxIAwAAIAAD3g");
	this.shape_20.setTransform(1.3,-44.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape}]},3).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},2).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},2).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_12}]},2).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_14}]},2).to({state:[{t:this.shape_15}]},1).to({state:[{t:this.shape_16}]},1).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_18}]},1).to({state:[{t:this.shape_19}]},1).to({state:[{t:this.shape_20}]},4).wait(210));

	// btn
	this.instance_2 = new lib.btn("single",0);
	this.instance_2.parent = this;
	this.instance_2.setTransform(-0.5,327.5);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(44).to({_off:false},0).to({y:85.5},10,cjs.Ease.quartOut).wait(11).to({mode:"synched",loop:false},0).wait(48).to({startPosition:0},0).wait(48).to({startPosition:0},0).wait(79));

	// bg
	this.instance_3 = new lib.bg();
	this.instance_3.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(240));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,-300,300,600);


// stage content:
(lib._300x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// cover
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#666666").ss(2,1,1).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// banner
	this.instance = new lib.banner();
	this.instance.parent = this;
	this.instance.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(149,299,302,602);
// library properties:
lib.properties = {
	id: 'A5B0E578675B46D2B874D0B363E0747B',
	width: 300,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/btn_bg.png", id:"btn_bg"},
		{src:"images/cherries.png", id:"cherries"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['A5B0E578675B46D2B874D0B363E0747B'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;