(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.bgImg1 = function() {
	this.initialize(img.bgImg1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.btn_bg = function() {
	this.initialize(img.btn_bg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,202,46);


(lib.car = function() {
	this.initialize(img.car);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,256,138);


(lib.fari = function() {
	this.initialize(img.fari);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,66,50);


(lib.girl = function() {
	this.initialize(img.girl);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,304,288);


(lib.video05 = function() {
	this.initialize(img.video05);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,470,200);


(lib.video06 = function() {
	this.initialize(img.video06);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,470,200);


(lib.video07 = function() {
	this.initialize(img.video07);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,470,200);


(lib.video08 = function() {
	this.initialize(img.video08);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,470,200);


(lib.video09 = function() {
	this.initialize(img.video09);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,470,200);


(lib.video10 = function() {
	this.initialize(img.video10);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,470,200);


(lib.video11 = function() {
	this.initialize(img.video11);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,470,200);


(lib.video12 = function() {
	this.initialize(img.video12);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,470,200);


(lib.video13 = function() {
	this.initialize(img.video13);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,470,200);


(lib.video14 = function() {
	this.initialize(img.video14);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,470,200);


(lib.video15 = function() {
	this.initialize(img.video15);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,470,200);


(lib.video16 = function() {
	this.initialize(img.video16);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,470,200);


(lib.video41 = function() {
	this.initialize(img.video41);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,470,200);


(lib.video42 = function() {
	this.initialize(img.video42);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,470,200);


(lib.wheel = function() {
	this.initialize(img.wheel);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,42,42);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.wheel_mc = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.wheel();
	this.instance.parent = this;
	this.instance.setTransform(-21,-21);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.wheel_mc, new cjs.Rectangle(-21,-21,42,42), null);


(lib.t2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgcDpIAAgjIhdAAIAAAjIgiAAIAAhCIAUAAQAHgLADgNQACgNAAgRIAAg5IBpAAIAABvIAYAAIAABCgAhZB3QAAAQgCAKQgCALgFALIAtAAIAAhPIgkAAgAIpDDQgMgGgGgMQgHgMgBgWIgYAAIAAA3IgjAAIAAiOIAjAAIAAA3IAYAAQABgUAHgNQAHgNALgFQAOgGATAAQAVAAAOAHQANAIAGAPQAGAQAAAbQAAAcgGAPQgGARgOAGQgNAHgVAAQgUAAgNgFgAI5BbQgFAFgCAHQgCAIAAAQQAAARACAHQACAIAFAFQAGAEALAAQALAAAEgEQAGgFACgIQACgIAAgQQAAgQgCgHQgDgJgFgEQgFgEgKAAQgKAAgHAEgAD4DCQgPgGgHgQQgIgQAAgdQAAgcAIgQQAHgQAPgGQANgHAYAAIAlAFIAAAhQgRgFgSAAQgLAAgIADQgHADgEAJQgEAJAAAQQAAARAEAIQAEAJAHADQAGAEANAAQASAAARgFIAAAhIglAEQgYAAgNgGgAtrDEIAAggIAXAEIAUABQAOAAAFgDQAFgDAAgIQAAgHgEgDQgFgDgMAAIgZAAIAAgdIAZAAQAMAAAFgDQAEgDAAgHQAAgIgFgDQgFgDgOAAIgSABIgXAEIAAggQAXgFARAAQAUAAAPAEQANAEAGAJQAGAKAAAPQAAALgEAHQgDAHgEACIgKAEIAKAFQAEADADAGQAEAHAAALQAAAPgGAJQgGAJgNAEQgPAEgUAAQgUAAgWgEgAKdDGIAAgjIAjAAIAAAjgAF3DGIAAhuIgoAAIAAggIB2AAIgGAgIglAAIAABugACgDGIAAiOIAiAAIAACOgABnDGIgvhAIAABAIgjAAIAAiOIAjAAIAABCIAshCIAqAAIgzBIIA3BGgAjPDGIAAhVIg1BVIgdAAIAAiOIAiAAIAABUIA0hUIAeAAIAACOgAmoDGIAAiOIA9AAQAPAAALAEQAKADAGAIQAFAIAAAOQAAANgFAIQgFAHgKADQANAEAFAHQAGAIAAAQQAAAPgFAJQgFAIgMAEQgMADgRAAgAmGCpIAWAAQAKAAADgBQAEgCACgDQACgDAAgFQAAgGgCgEQgBgDgFgBQgDgBgJAAIgXAAgAmGBxIAUAAQAJAAADgCQAFgBABgDQABgDAAgGQAAgFgBgDQgCgDgEAAQgDgBgJAAIgUAAgAp8DGIAAiOIAiAAIAABuIAnAAIAAhuIAiAAIAABuIApAAIAAhuIAiAAIAACOgArsDGIAAiOIAjAAIAACOgAnxgQIAAgjIhdAAIAAAjIgiAAIAAhCIAUAAQAHgOACgKQADgLAAgTIAAg5IBoAAIAABvIAZAAIAABCgAouiCQAAAMgCAOQgCAKgFAMIAtAAIAAhPIgkAAgAHtg4QgNgGgHgRQgGgRAAgaQAAgaAGgRQAGgPAOgIQAOgHAWAAQAWAAAOAHQANAHAGAQQAHAQAAAbQAAAcgHAPQgGARgNAGQgOAHgWAAQgWAAgOgHgAIAieQgFAEgDAJQgCAJAAAOQAAAPACAJQACAIAGAFQAGAEALAAQALAAAGgEQAGgFACgIQACgLAAgNQAAgMgCgLQgDgJgFgEQgGgEgLAAQgLAAgGAEgAj+gzIAAggQAGABAGAAQAFAAACgCQAEgBABgEIADgFIgwhjIAmAAIAcA+IAZg+IAmAAIg4B4QgFALgIAHQgIAGgMAAQgLAAgIgCgArVgzIAAggQAGABAGAAQAFAAADgCQADgCACgDIACgFIgwhjIAmAAIAcA+IAZg+IAmAAIg4B4QgEAKgJAIQgIAGgMAAQgKAAgJgCgAM4gzIAAiOIAiAAIAACOgAL4gzIAAiOIAiAAIAACOgAK4gzIAAg3IgvAAIAAA3IgiAAIAAiOIAiAAIAAA3IAvAAIAAg3IAjAAIAACOgAGYgzIAAhjIgpBAIgrhAIAABjIgiAAIAAiOIAsAAIAhA1IAfg1IAtAAIAACOgACdgzIAAiOIBAAAQAXAAANAMQANALAAAcQAAAdgNALQgNALgXAAIgdAAIAAAogADAh7IAXAAQAMAAAEgEQAEgEAAgLQAAgLgEgEQgFgEgLAAIgXAAgABqgzIgJgbIgzAAIgJAbIgkAAIAxiOIArAAIAxCOgABYhrIgRg0IgQA0IAhAAgAhSgzIAAiOIBfAAIgGAgIg2AAIAABugAm/gzIAAiOIAjAAIAAAtIAcAAQAZAAAMAKQANAMAAAaQAAAcgNAKQgMALgZAAgAmchTIAXAAQALAAAEgDQAFgFAAgJQAAgJgFgEQgFgEgKAAIgXAAgAtlgzIAAiOIBsAAIgGAgIhDAAIAAATIAcAAQARAAAKAEQALADAGAKQAGAKAAARQAAAagNALQgNAKgYAAgAtChTIAXAAQALAAAEgDQAFgEAAgIQAAgHgFgEQgFgEgKAAIgXAAgANOjLIAAgdIAeAAIAAAdgAMmjLIAAgdIAdAAIAAAdg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t2, new cjs.Rectangle(-87.6,-23.3,175.3,46.7), null);


(lib.t1_2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("An/CcQAKgHADgGIgQgoIAHAAIAMAjIANgjIAHAAIgOAjQgFAPgOAIgAjRCaIAAgJIggAAIAAAJIgGAAIAAgPIAEAAQAFgEAAgMIAAgUIAeAAIAAAkIAGAAIAAAPgAjoB7QAAAMgEAEIAWAAIAAgeIgSAAgAliCaIAAgJIghAAIAAAJIgGAAIAAgPIAFAAQAEgFABgLIAAgUIAdAAIAAAkIAGAAIAAAPgAl6B7QAAAKgDAGIAVAAIAAgeIgSAAgAi/CMQgFgEAAgMQAAgWATABQATgBAAAWQAAAMgFAEQgEAFgKAAQgKAAgEgFgAi6BvQgEAEAAAJQAAAJAEAEQACACAHAAQAHAAADgCQACgEAAgJQAAgJgCgEQgDgDgHAAQgHAAgCADgAkhB/IgGAAIAAASIgGAAIAAgqIAGAAIAAASIAGAAQABgSARAAQAKAAAEAEQAFAFgBAMQABAMgFAEQgEAFgKAAQgRAAgBgSgAkYBvQgDAEAAAJQAAAJADAEQADACAGAAQAHAAACgCQAEgEAAgJQAAgJgEgEQgCgDgHAAQgGAAgDADgAlXCPIAAgFQAGABAIAAQALABgBgIQAAgGgJAAIgJAAIAAgFIAJAAQAJAAAAgGQABgHgLAAQgIAAgGACIAAgGQAGgCAHABQASAAAAALQAAAHgHACQAHADAAAHQAAAMgSAAQgIAAgFgCgAnDCPIAAgFQAGABAIAAQALABgBgIQAAgGgJAAIgJAAIAAgFIAJAAQAJAAAAgGQABgHgLAAQgIAAgGACIAAgGQAGgCAHABQASAAAAALQAAAHgHACQAHADAAAHQAAAMgSAAQgIAAgFgCgAqICMQgFgEAAgMQAAgMAFgFQAEgEALAAIALABIAAAGQgGgCgFAAQgHAAgDADQgDAEAAAJQAAAJADAEQADACAHAAQAFAAAGgBIAAAFQgDACgIAAQgLAAgEgFgAoZCRIAAgkIgQAAIAAgGIAkAAIAAAGIgPAAIAAAkgAo3CRIAAgqIAGAAIAAAqgApiCRIAAgqIAQAAQAQAAAAAKQAAAHgHADQAIACAAAIQAAAMgQAAgApdCLIALAAQALAAAAgHQAAgGgJgBIgNAAgApdB5IANAAQAHAAAAgHQABgFgLAAIgKAAgAo4BfIAAgGIAIAAIAAAGgAAqBFIAAg4IAHAAIAAACQAGgEAGABQASgBAAAWQAAAVgSABQgIAAgEgDIAAARgAAxAUIAAAbQAEABAGABQAIgBADgDQADgEAAgIQAAgIgDgEQgDgEgIAAQgFABgFACgAhnBAIAAgLIggAAIAAALIgGAAIAAgQIAEAAQAFgEAAgLIAAgUIAeAAIAAAjIAGAAIAAAQgAh+AgQAAALgEAFIAVAAIAAgeIgRAAgAkZBAIAAgLIggAAIAAALIgGAAIAAgQIAEAAQAFgEAAgLIAAgUIAeAAIAAAjIAGAAIAAAQgAkvAgQAAALgFAFIAWAAIAAgeIgRAAgAJuApQAAgMAPABQAGAAAHABIAAgHQAAgHgMAAIgMACIAAgFQAHgCAFAAQASgBAAANIAAAdIgFAAIAAgCQgGAEgJAAQgOAAAAgOgAJ0ApQAAAFADACQACABAGAAQAGAAAFgCIAAgLIgLgBQgLAAAAAGgAHpAhQgBgWAUABQATgBAAAWQAAAVgTABQgUgBABgVgAHzAVQgEADAAAJQAAAJAEAEQACADAHAAQAGAAADgDQAEgEgBgJQABgJgEgDQgDgDgGgBQgHABgCADgAFIAyQgEgFAAgMQAAgWASABQAKgBADAFQAEAEAAALIAAAEIgdAAQAAAJAEACQACADAIAAQAHAAAGgCIAAAFQgGACgIABQgLAAgEgFgAFhAeQAAgNgLAAQgLAAgBANIAXAAIAAAAgADYApQAAgMAOABQAHAAAHABIAAgHQAAgHgNAAIgLACIAAgFQAGgCAGAAQASgBgBANIAAAdIgEAAIgBgCQgFAEgJAAQgOAAAAgOgADeApQAAAFACACQADABAFAAQAGAAAGgCIAAgLIgLgBQgLAAAAAGgABXApQAAgMAPABQAGAAAGABIAAgHQAAgHgLAAIgMACIAAgFQAHgCAFAAQASgBAAANIAAAdIgFAAIgBgCQgFAEgIAAQgPAAAAgOgABeApQgBAFADACQACABAGAAQAGAAAEgCIAAgLIgKgBQgKAAAAAGgAguAhQAAgWATABQATgBAAAWQAAAVgTABQgTgBAAgVgAgkAVQgDADgBAJQABAJADAEQACADAHAAQAGAAADgDQAEgEAAgJQAAgJgEgDQgDgDgGgBQgHABgCADgAjLApQAAgMAOABQAGAAAHABIAAgHQAAgHgLAAIgNACIAAgFQAIgCAFAAQARgBABANIAAAdIgGAAIAAgCQgFAEgJAAQgOAAAAgOgAjFApQAAAFADACQABABAHAAQAFAAAFgCIAAgLIgKgBQgLAAAAAGgAlrAhQAAgWAUABQATgBAAAWQAAAVgTABQgUgBAAgVgAlkAhQAAAJADAEQADADAHAAQAGAAADgDQAEgEAAgJQAAgJgEgDQgDgDgGgBQgNABAAAPgAmaA2IAAgFIACAAQAFAAAAgHIAAgdIAeAAIAAAoIgGAAIAAgjIgSAAIAAAZQAAAMgJAAgAnFAhQAAgWATABQATgBAAAWQAAAVgTABQgTgBAAgVgAm7AVQgEADABAJQgBAJAEAEQACADAHAAQAGAAADgDQAEgEAAgJQAAgJgEgDQgDgDgGgBQgHABgCADgApXApQAAgMAOABQAGAAAIABIAAgHQAAgHgMAAIgMACIAAgFQAHgCAGAAQARgBAAANIAAAdIgFAAIgBgCQgFAEgJAAQgOAAAAgOgApQApQAAAFACACQACABAGAAQAGAAAFgCIAAgLIgLgBQgLAAABAGgAJiA1IgUgVIAAAVIgGAAIAAgoIAGAAIAAASIASgSIAIAAIgSATIAUAVgAI1A1IAAgSIgVAAIAAASIgHAAIAAgoIAHAAIAAARIAVAAIAAgRIAGAAIAAAogAHYA1IAAgoIAGAAIAAAogAHGA1IAAgjIgXAAIAAAjIgGAAIAAgoIAjAAIAAAogAGXA1IAAggIgQAUIgPgUIAAAgIgGAAIAAgoIAHAAIAOATIAOgTIAHAAIAAAogAE0A1IAAgQQgHADgHAAQgOAAAAgOIAAgNIAFAAIAAAMQABAJAJAAQAGAAAHgDIAAgSIAFAAIAAAogADIA1IAAgSIgWAAIAAASIgGAAIAAgoIAGAAIAAARIAWAAIAAgRIAGAAIAAAogACOA1IAAgjIgOAAIAAgFIAkAAIAAAFIgPAAIAAAjgAAcA1IgUgVIAAAVIgGAAIAAgoIAGAAIAAASIASgSIAIAAIgTATIAVAVgAhYA1IAAgoIAQAAQARAAgBAKQAAAHgGACQAIACgBAIQAAAHgDACQgEACgIAAgAhSAxIALAAQALgBAAgGQgBgHgIAAIgNAAgAhSAeIANAAQAHAAABgHQAAgFgLAAIgKAAgAkKA1IAAgoIAHAAIAAAjIAQAAIAAgjIAGAAIAAAjIARAAIAAgjIAHAAIAAAogAnWA1IAAggIgPAUIgPgUIAAAgIgHAAIAAgoIAIAAIAOATIAOgTIAIAAIAAAogAoNA1IAAgfIgXAfIgFAAIAAgoIAGAAIAAAfIAWgfIAGAAIAAAogApoA1IAAgXIgcAAIAAAXIgGAAIAAg0IAGAAIAAAWIAcAAIAAgWIAHAAIAAA0gAomgDIAGAAQAAAFAIAAQAIAAABgFIAFAAQAAAJgOAAQgOAAAAgJgAHYAFIAAgGIAHAAIAAAGgAnAgYIAAhsIAYAAIAAAFQAFgDADgBQAFgCAHAAQARAAAHAJQAJAJAAAWQAAAUgIAKQgHALgRAAQgLgBgKgFIAAAigAmohuIAAAiQAFACAJAAQAEAAAFgCQAEgBAAgFQABgDAAgIQAAgHgBgFQAAgDgEgDQgDgCgGABQgKgBgEADgAo1geIAAgYIhCAAIAAAYIgYAAIAAguIAOAAQAFgJACgIQACgHAAgOIAAgoIBJAAIAABOIASAAIAAAugAphhcQgCAJgEAHIAgAAIAAg4IgZAAgAFIgkIAAgSIgwAAIAAASIgYAAIAAgnIAKAAQAHgFAAgQIAAgkIBBAAIAAA5IAPAAIAAAngAEnhUQgBAGgDADIAXAAIAAgkIgSAAgAC6gkIAAgSIgwAAIAAASIgZAAIAAgnIALAAQAIgFgBgQIAAgkIBBAAIAAA5IAPAAIAAAngACZhUQAAAGgEADIAYAAIAAgkIgTAAgAAug5QgIgCgFgKQgFgIABgQQAAgXAKgIQAKgJASAAQAUAAAJAJQAKAIAAAXQAAAQgEAIQgFAKgJACQgJAEgMABQgLgBgKgEgAA7hvQgDACgBAEQgCAEAAAIQAAAIACAEQABAEADABQADACAFAAQAGAAADgCQADgBABgEQACgEAAgIQAAgIgCgEQgBgEgDgCQgDgCgGABQgFgBgDACgAhCg2IAAgTIAGABQAJAAAAgJIAAgzIBBAAIAABOIgYAAIAAg6IgUAAIAAAmQAAAJgFAGQgFAHgOAAgAoQg7QgHgGAAgNQAAgKADgFQAEgEAFgCQAGgCAKAAIAKAAIAIACIAAgFQAAgEgDgDQgFgDgHABIgNAAIgKACIAAgUQANgCANAAQARgBAKAGQAJAGAAANIAAA3IgTAAIgDgGQgHAHgOABQgOAAgGgHgAn8hVQgCADAAAEQAAAEACABQABACAGAAIAHgBIAFgBIAAgMQgGgBgGAAQgFAAgCABgADdg2IAAhOIAZAAIAABOgAhmg2IAAhOIAZAAIAABOgAjBg2IAAhkIBLAAIgEAWIgvAAIAAANIAUAAQAKABAJACQAHADAEAHQAFAGAAANQgBASgIAIQgJAHgRAAgAiphMIAQAAQAHgBAEgCQADgDAAgFQAAgFgDgDQgDgCgIAAIgQAAgAk/g2IASgZQgIgDgEgFQgFgGAAgLQAAgMAFgGQADgGAIgCQAGgCANAAIAkAAIAABNIgYAAIAAgXIgFAAIgQAYgAkhhwQgBAAAAAAQgBABAAAAQgBAAAAABQAAAAAAAAIgBAGIABAFQAAABAAAAQAAAAABABQAAAAABAAQAAAAABABIAIAAIAKAAIAAgQIgKAAIgIAAgAloh2IAFgqIAaAAIgLAqgADciLIAAgVIAaAAIAAAVgAhmiLIAAgVIAZAAIAAAVg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1_2, new cjs.Rectangle(-65.6,-16.1,131.2,32.2), null);


(lib.t1_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ar0EyQAXgKAHgLIglhlIAhAAIAVBDIAThDIAiAAIgeBVQgDALgIARQgIALgKAJQgLAKgSAFgABQEfQgLgFgHgMQgGgNAAgUQAAgTAGgNQAGgMAMgGQAOgFARAAQAPAAAPAEIAAAeQgLgEgPAAQgJAAgFACQgGACgDAFQgDAHAAAJQAAAKADAGQADAGAGACQAGACAIAAQANAAANgEIAAAdQgPAEgPAAQgTAAgMgFgAtbEhIAAgdIAjAEQAIAAAGgCQAEgCAAgEQAAgEgEgCQgDgBgKAAIgTAAIAAgXIAdgBQAEAAACgCQAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAAAgBQAAgFgEgCQgDgCgLAAQgLAAgYAEIAAgcQAZgEAJAAQATAAALADQAKACAHAHQAFAHAAAMQAAAKgEAFIgEAGIgJAEIAFABQAFACADAGQAEAGAAAJQAAALgFAHQgGAHgLADQgMACgSAAgAEYEiIAAgiIAhAAIAAAigADeEiIAAggIgIAAIgWAgIgkAAIAZgiQgLgDgGgIQgFgIgBgOQAAgQAGgJQAEgIALgDQAKgDARAAIAxAAIAABqgADFDUQgEABgBACIgBAHIABAHQACADADABIAZABIAAgXIgOAAQgJAAgCABgAAEEiIAAg8IgkA8IgdAAIAAhqIAgAAIAAA8IAjg8IAfAAIAABqgAiLEiIAAhOIggAAIAAgcIBgAAIgDAcIgcAAIAABOgAjaEiIAAggIgHAAIgWAgIglAAIAagiQgMgDgFgIQgFgHgBgPQAAgRAGgIQAFgIAJgDQALgDAQAAIAyAAIAABqgAjzDUQgCABgCACIgBAHIABAHQACADACABIAZABIAAgXIgNAAQgJAAgDABgAlOEiIAAgnIgfAAIAAAnIghAAIAAhqIAhAAIAAAmIAfAAIAAgmIAhAAIAABqgAnHEiIAAg8IgkA8IgeAAIAAhqIAgAAIAAA8IAlg8IAeAAIAABqgApCEiIAAhMIgfAAIAABMIgiAAIAAhqIBiAAIAABqgAlpBMIAAgZIhCAAIAAAZIghAAIAAg1IAPAAQAJgIAAgUIAAgxIBZAAIAABNIATAAIAAA1gAmVgKQAAAMgCAIQgBAJgDAEIAfAAIAAgwIgZAAgAr+BMIAAgZIhCAAIAAAZIggAAIAAg1IAOAAQAKgIAAgUIAAgxIBZAAIAABNIASAAIAAA1gAspgKQAAAMgCAIQgBAIgEAFIAfAAIAAgwIgYAAgAKEAwQgMgFgGgMQgHgMAAgUQAAgeAOgNQANgMAaAAQAaAAAOAMQANANAAAeQAAAUgHAMQgFAMgMAFQgMAFgRAAQgSAAgKgFgAKWgZQgFACgCAGQgCAEAAAMQAAALACAEQACAGAFACQAEACAGAAQAGAAAFgCQAFgCABgGQADgGAAgJQAAgKgDgGQgBgGgFgCQgFgCgGAAQgGAAgEACgAGkAwQgLgGgHgLQgFgMAAgUQAAgVAFgMQAHgMALgFQAMgFATAAQAQAAAOAEIAAAdQgNgEgNAAQgJAAgGACQgFADgCAFQgEAGAAAKQAAAKAEAFQACAFAFADQAJACAGAAQANAAANgEIAAAdQgOAEgQAAQgTAAgMgFgAEjAsQgIgIAAgTQAAgMAEgFQAEgHAJgCQAIgDANAAIANABIALADIAAgIQgBgHgEgDQgFgDgLAAIgQABIgPADIAAgbQAQgEATAAQAZAAAMAIQAMAIAAASIAABJIgZAAIgEgJQgKALgTAAQgTAAgJgJgAE/AKQgDADAAAEQAAAGADADQACACAHAAIAKgBIAHgCIAAgQQgIgBgJAAQgHAAgCACgAklAwQgMgFgGgMQgGgMAAgUQAAgeAOgNQANgMAZAAQAaAAANAMQAOANAAAeQAAAUgGAMQgGAMgMAFQgLAFgSAAQgRAAgLgFgAkTgZQgFACgCAGQgCAEAAAMQAAALACAEQACAGAFACQAGACAEAAQAFAAAGgCQAFgCACgGQACgEAAgLQAAgMgCgEQgCgGgFgCQgGgCgFAAQgEAAgGACgAorAsQgNgJgCgXIgNAAIAAAnIghAAIAAhpIAhAAIAAAnIANAAQACgXANgJQAMgJAXAAQARAAAKAFQALAFAGAMQAGAMAAAVQAAAUgGAMQgGAMgLAFQgKAFgRAAQgXAAgMgJgAoTgZQgEACgCAGQgBAFAAALQAAAKABAFQACAGAEACQAFACAGAAQAFAAAFgCQADgCACgGQACgEABgLQgBgMgCgEQgCgGgDgCQgGgCgEAAQgGAAgFACgArAA0IgTgDIAAgcIAjAEQALAAAEgCQAEgCAAgFQAAgDgDgCQgEgCgKAAIgUAAIAAgWIAUAAIAKAAQAFgBABgBQAAgBAAAAQAAgBABAAQAAgBAAAAQAAgBAAgBQAAgFgEgBQgDgCgMAAQgMAAgWAEIAAgdQAWgDAMAAQAVAAAJADQAMADAEAGQAGAHAAALQAAAKgEAFQgDAGgBABIgJADIAFABQAFABADAGQAEAHAAAIQAAAMgGAHQgEAGgMADQgMADgSAAgAI3AzIAAgnIggAAIAAAnIghAAIAAhpIAhAAIAAAmIAgAAIAAgmIAgAAIAABpgADnAzIAAgmQgGAFgGACQgFACgMAAQgTAAgIgIQgKgIAAgPIAAgtIAhAAIAAAkQAAAHAEACQAEAEAJAAQAKAAAGgEIAAgtIAhAAIAABpgAA5AzIAAhpIA1AAQAOAAAGACQAIACAEAGQAFAGAAAMQAAAJgEAGQgDAFgKADQAKACAGAFQAEAGAAALQAAAMgEAHQgFAGgJADQgHACgQAAgABZAZIAQAAQAIAAACgCQADgBAAgFQAAgFgDgCQgCgBgIAAIgQAAgABZgMIAOAAQAIAAACgCQACgCAAgEQAAgEgCgCQgCgCgIAAIgOAAgAiSAFIAAgdICFAAIAAAdgAgWiUIAAiRIAfAAIAAAHQADgDAJgEQAIgCAIAAQAVAAALAMQAMAMAAAfQAAAbgLAOQgJANgYAAQgRAAgLgGIAAAsgAAJkHIAAAtQAHAEAMAAQAIAAAEgDQAFgCABgFQACgIAAgIQAAgJgCgIQgBgGgFgCQgEgCgIAAQgMAAgHAEgAGoijIAAgZIhPAAIAAhpIAgAAIAABMIAfAAIAAhMIAgAAIAABNIAQAAIAAA1gAp1ijIAAgZIhCAAIAAAZIggAAIAAg0IAOAAQAJgIAAgWIAAgwIBZAAIAABOIATAAIAAA0gAqhj5QAAANgCAIQgBAIgDAFIAfAAIAAgxIgZAAgAkVi6IgTgDIAAgcIAUACIAPABQALAAADgCQAEgBAAgFQAAgEgDgBQgEgCgJAAIgUAAIAAgXIAUAAIAKgBQAEAAABgCQAAAAAAAAQABgBAAAAQAAgBAAgBQAAAAAAgBQAAgFgEgCQgDgBgLAAQgNAAgVADIAAgcQATgDAOAAQASAAANACQALADAFAHQAFAHAAALQAAAKgDAFQgDAGgCAAIgJAEIAGACQADAAAFAHQADAGAAAJQAAAMgFAGQgFAHgLADQgKACgVAAgAtAjAQgOgHgFgPQgHgPAAgaQAAgbAHgPQAFgPAOgHQAMgGAWAAQAWAAANAGQAMAHAGAPQAGAPAAAbQAAAagGAPQgGAPgNAHQgMAGgWAAQgWAAgMgGgAsukiQgGAEgCAIQgCAHAAAQQAAAPACAHQADAJAFADQAFAEALAAQALAAAEgEQAGgDACgJQACgHABgPQgBgQgCgHQgBgIgHgEQgFgEgKAAQgLAAgFAEgAMDi8IAAhpIA1AAQAOAAAGACQAJACAEAGQAFAGgBALQAAAKgDAFQgFAGgJADQALABAFAGQAFAHAAAKQAAANgFAGQgEAHgJACQgIACgQAAgAMkjWIARAAQAHAAACgBQACgBABgGQgBgFgCgBQgCgCgHAAIgRAAgAMkj8IAOAAQAIAAABgBQADgCAAgEQAAgFgDgBQgBgCgIAAIgOAAgALLi8IAAhpIAhAAIAABpgAKTi8IAAhMIggAAIAABMIggAAIAAhpIBgAAIAABpgAIZi8IAAg7IgkA7IgdAAIAAhpIAgAAIAAA8IAlg8IAeAAIAABpgAEhi8IAAgmIghAAIAAAmIghAAIAAhpIAhAAIAAAlIAhAAIAAglIAgAAIAABpgACni8IAAg7IgkA7IgeAAIAAhpIAgAAIAAA8IAlg8IAeAAIAABpgAhPi8IAAhMIggAAIAABMIghAAIAAhpIBhAAIAABpgAmJi8IAAgmIghAAIAAAmIggAAIAAhpIAgAAIAAAlIAhAAIAAglIAgAAIAABpgAoDi8IAAg7IglA7IgdAAIAAhpIAgAAIAAA8IAlg8IAeAAIAABpgALKkvIAAgcIAjAAIAAAcg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1_1, new cjs.Rectangle(-86.5,-33.2,173,66.5), null);


(lib.logo2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAPDcIgLgGIgKgEQgGgCgOgJQgMgIgIgCQgFgBgHABIgNACQgIAAgEgBQgHgBgEgFQgHgGABgCQACgCAGAAIANgBQAIAAACgBIgFgKIgFgLQgGgMACgLQAEgGgHgIIgEgGQAAgBAAAAQgBgBAAgBQAAAAABgBQAAAAAAgBIAIABQAQAAACAOQADALgJANQABAJAJAJIAQAOIAYAJIAXAJQAdAJAWABIAaABQARABAEADQgfAGgiALIgFABQgHAAgJgFgAAcC5QgDgCgBgDQgCgDACgEQgJgBgLACIgTACQgFABgCgHIgBgGIgCgFIABgaQACgQgCgKQgDgGACgCQAAgBAFgBQAFgBABgBQADgCgBgGIACgLQACgHgEABIgHADIgHADQgIAEgGgEQgIgGADgGQACgFAKgBIANgDIAOgDQARgDAHgHQAEgDADgHIADgLIADgLQACgFADgDQAGAAAFAEQAFADADAFQAAAIgIAHIgPALQgFAEAFAAIAJgBQAMgBAHADQAJAFgHALQgGABgQgBQgOgBgIACQgHgBgCADQgCACAAAGIgBAJQgCAFgEACQgDAEADgDIAIgEQAEgDAGgCQAGgCAFABQANABABANQgCAVgBAZQgCATAAAbQgBACgDABQgDAAgDgDgAARCHQAEAGgDADQgDACgIAAQgHABgDACQgFADACAGQACAGAKgCIAJgDQAGgBADABIAAgdIAAgTQAAgLgDgHQgCACgGABIgKAAQgMABABAIQAAAHADABQADAAAEgCQAGgEADAAQAFAAABAHQgCADgEABIgJADQgEABgCADQgDADABAGQAAABAAABQAAABABAAQAAABAAAAQABAAABAAIAFgCIAIgDIABAAQAEAAACACgAhHA3QgFgDgDgGQgDgFABgEQAAgFAFgCQADgBAFAEQAEADAEAFQADAFAAAFQAAAEgFABIgDABQgDAAgDgCgAgJAtQgFgBgDgHQABgCgDgFIgGgIQgDgEgBgDQAAAAAAgBQAAAAABgBQAAAAABAAQABgBABAAQAGAAAGADQAFAEADAGQAFAEAAAFQAAAFgCADQgCADgDAAIgCAAgAgIgGQgFgEgFgLQgIgIAGgBQADAAAKADQABgKAAgOIAAgXIgVAUQgNALgKAHQgIAFgJADQgMAFABgFIAagXQAQgNAKgLQAFgEgBgBQAAgCgGAEQgJACgKAFIgQAKIgOgIQgIgEgBgGQANgFAVgFIAhgIQAGgBAAgCQAAAAgBAAQAAAAAAgBQgBAAAAgBQgBAAgBgBIgEgDQgBgCAFgBQAHABACgCQABgCgBgEIAAgGQABgDAFABIACgJIAAgLQAAgOgJAFQADAHgBAIQgCAIgHAGQgKAKgHAFQgLAHgKAAQADgHALgMQALgMAEgIQACgHgJAEQgLAGgDABIgGgDIgGgDQgHgEAAgFQAdgJARgHQAOAAgDgJQgCgEgJgMQgJgBgJgGQgKgHACgHQASgFAUgCIAmgDQANgBAHADQALAEgCAKQgRAFgaASQgKAJAMABIATAAQAHgEAGACIAMAJQADAFgCADQgCADgHABIgMADQgGACgDADQgMAAgGALQgDAEgBAHIgDAMQgHAIAFACQAFACAIgDIAOgBIANgBQAQgCAKAGQAGgCAEAEQAEAEABAFQABAGgDADQgDADgGgCQgKgHgPgBIgNAAIgNAAQgKAAgDABQgGABADAIQAJAMARAKIAdARIAIAFIAKAFQAMAIgNgBQgSABgNgFQgQgHgGgOIgEgGIgFgHQgHgJgDAEQAAAPgCAMQgCAPgEAMQgCAJgEAAQAAAAgBAAQAAAAgBAAQAAAAgBgBQAAAAgBgBgAAXikQgEABgCACQgFAHADABQADABAGgDQAGgDADgDQADgEgGAAIgHABgAAXjTIgGABQgBACgHABIgKACIgHADQgCADAEADQADAAAFAFQAFADADgEIAKgKIAJgKIgGABg");
	this.shape.setTransform(-0.3,-0.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Слой_3
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#EA0C19").s().p("Ah3EgQgBgIAAAIQgGgBgCgCQgDgIgCgBQgDACgCgNQgBgBAAgPIAAnaIAAgNIAAgJQAAgLABgEQACgJADgDIADgJQABgEABAEQACgGACABIAEACQABAJAAgJQABgBAAAAQAAgBABAAQAAAAABABQAAAAABABQAAABAAAAQABAAAAABQAAAAABAAQAAAAABAAIACgCQABAAAAAAQAAAAABAAQAAAAABAAQABgBABAAQAAAAAAAAQABAAAAAAQABAAAAAAQABABAAAAQAAAAABABQAAAAABAAQAAAAABAAQABABABAAIAEgCQACgBAEABQADABACgBQAFgGAHAGQADABAKgBIAPAAQACACAFgBQAEgCACABQADgDAFABIAIACQADgCAEABIAHABIAHgCQAFgBACADQALADAFgDQAHACAHgCIAOAAQAKACAEgCQAHgDAEADIALAAQAEACAFgCQADgCAFACQAAABABABQAAABAAAAQABABAAAAQAAgBAAAAIAEgDIACADIABgDQABAOAAgOQAAAAABAAQAAgBABABQAAAAABAAQABABABABQAAAAABABQAAAAABAAQAAAAAAAAQABAAAAAAQADgGADAPQACADACAKIAAIMQAAAJgEAEQgBAGgFADIgIADQAAAAAAgBQAAAAAAAAQAAAAgBAAQAAABAAAAQAAAAgBAAQAAAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAAAAAAAQgBAAAAAAQgBAAgBAAQAAAAAAAAQAAAAgBAAQAAAAAAAAQgBAAAAAAIgRAAQgHgBgEABQgHACgEgCQgDgBgEAAIgHABIgHABQgEAAgDgBQgCgBgFAAIgHABQgFgFgLAFIgOAAQgEgBgKABQgDgBgFABQgFABgDgBQgFADgIgDQgLgBgEABIgNAAQgIABgEgBQgDABgCAAIgGgBIgEAAQgBAAgBAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgFgBgDABQAAAAAAABQgBAAAAAAQAAAAgBAAQAAgBAAAAQgBAAAAAAQgBAAAAAAQAAAAgBAAQAAAAAAAAIgCACQgBAAAAAAQAAAAAAgBQAAAAAAAAQAAgBgBAAgABLEQIATACIAEACQABAAABAAQAAAAABAAQAAAAABAAQAAgBABAAIAKgCQAGgBACgFQADAAAFgIIADgGIAAgFIgBgMIABgQQACAAAAgPIgFjMIACgKIAEjIIgCgRIgBgIIgBgHQABgHgBgIIgGgJIgKgCQgCgDgCABIgFAAIgUgDIgJAAIgGAAQAAAAgBgBQgBAAAAAAQgBAAAAAAQgBABAAAAIgFABQgDABgCgCQgBgBgBAAQAAgBgBAAQAAgBgBABQAAAAgBAAIgFACIgFAAQgDABgCgBIgJAAQgGADgEgCQgCgBgDAAIgGABIgIAAQgHgDgEADQAAAAgEADQgDACgDgGQgGgDgEADQgCgEgIAEQgCgCgDABQgBAAAAAAQgBABgBAAQAAAAgBgBQAAAAAAAAQgIgEgDAEIgKABIgFABQgEACgCgDQAAABgBAAQAAABgBAAQAAAAgBAAQAAAAgBgBQgEAAgCABQgGgDgEAFIgFADQgDACgBgCQgHgCgDAFQgDAGgDgBIgCAJIAAAGIAAAHQADAPABACIACAlIgGGaIAEAPQABAHAFADQAGAHACgBQAFACADADQADABAFAAQAEABAFgBQAFgDAFACIASgBQADABAEAAIAAgCIAAABIADgBIAJABIADgBQABAAABAAQAAAAABAAQAAAAABAAQAAAAABABQADgBAGACQAAAAABAAQAAAAABABQAAAAABAAQAAAAABAAIAFgBIAJAAQAEgDAEAEQADgCAGADIADgBQADAAADABQACADAHgDQADACAGgBQAEAEAFgEQABABAIAAQAEgDAFAEIAFABIACAAQAAAAAAAAQABAAAAAAQAAAAABAAQAAABAAAAgABpD3QgEgDgFADQgBAAgHgCIgIgBIgJgCQgCACgIgDQgFACgEgCQgFgBgFABQgFgCgEABIgJAAIgFABQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAAAgBgBIgIAAIgBAAQgGADgHgEIgQgBQgHgCgDABIgJAAIgFgBIgGAAQgCgBgHACIgJABIgJACIgIAAQgFgCgEACIgIgCQgEgDgDgFIgDgOIACghQABgaAAhbIACigQAAgNABgdIABgFIgChWIgBgPIAKgDQAEACAGgEQAEAEAGgFQACACAEgCQABgBAAAAQABAAABAAQAAgBABAAQAAAAAAABQAIgCAEABQAFAIAFgIQACgBAIACQAGACAEgCQAHAEADgDQACgBAEACQADABACgBIAFAAQADgCACACQADABAGgBQAGgBAFABQADgDAHACIAFABQADAAACgBQAEABAFgCIAGAAQACACADgCIAKAAIALAAIAeAEIgCAlIACANIABBLQAEAKgBAKIgCARIACAHIgCgEIgCAdQAEgEABgJQAAALgDAJIAGCvIAAAAIAAACIAAAqIAAALIAAANIAAALIgCAPIgBALQAAABgBABQAAABAAABQgBAAAAAAQAAAAgBAAIgBAFIgBADIAAgBQAAAAAAABQgBAAAAAAQAAABAAAAQgBAAAAAAIgCgCIgBACIgCgBgAhng6IABgHIgDgCgAgKj0IABABIAEgBIgCgBIgDABg");

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.logo2, new cjs.Rectangle(-14,-29,28,58), null);


(lib.logo_w = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ah4BvIAHgJIgHgMQgEgJgBgKIAIAAQABAHADAJIAEAJIAFgJQADgIAAgIIAIAAQAAAQgKAOIgMAQgADkBjQgEgEAAgIQAAgJAEgFQAEgDAIAAQAIAAAEADQAEAFAAAJQAAAIgEAEQgEAEgIAAQgIAAgEgEgADqBQQgCABAAAGQAAAEACACQABADAFAAQAEAAACgDQACgCAAgEQAAgGgCgCQgCgCgEAAQgFAAgBADgAC6BkQgCgBAAgHIAAgPIgGAAIAAgGIAGAAIAAgJIAIAAIAAAJIAKAAIAAAGIgKAAIAAAOIABAEQAAAAABAAQAAABAAAAQABAAAAAAQABAAABAAIAGAAIAAAGIgJABQgGAAgCgDgACKBmIgEgDIAAADIgIAAIAAgsIAIAAIAAAPQAEgEAGABQAGAAAEADQAEAFAAAJQAAAIgEAEQgEAEgGAAIgGgBgACGBQIAAANQAEADAEAAQAEAAACgCQACgCAAgFQAAgGgCgCQgCgCgEAAQgEAAgEADgAgwBkQgCgCAAgFIAAgWIAIAAIAAATQAAABAAABQAAAAAAABQAAAAABABQAAAAAAAAQABABAAAAQAAAAABABQAAAAABAAQAAAAABAAQADAAAFgDIAAgWIAIAAIAAAfIgIAAIAAgCQgGADgFAAQgFAAgDgDgAhVBjQgEgEAAgIQAAgJAEgFQAEgDAIAAQAIAAAEADQAEAFAAAJQAAAIgEAEQgEAEgIAAQgIAAgEgEgAhPBQQgCABAAAGQAAAEACACQACADAEAAQAFAAABgDQACgCAAgEQAAgGgCgCQgBgCgFAAQgEAAgCADgAiqBjQgEgEAAgIQAAgJAEgFQADgDAIAAQAIgBAEAFQADADAAAIIAAAEIgWAAQAAAFACABQACACAFAAIAGgBIAFgCIAAAHIgFABIgHABQgIAAgEgEgAikBNQgCACAAAEIAOAAIgBgFQgCgDgEAAQgDAAgCACgAEcBmIAAgUQAAAAAAgBQAAgBAAAAQAAgBgBAAQAAgBAAAAIgEgBQgDAAgFACIAAAXIgIAAIAAgfIAHAAIAAACQAHgEAFABQAFAAADACQACADAAAFIAAAWgADRBmIAAgfIAIAAIAAAfgAClBmIAAgfIAIAAIAAAfgABuBmIAAgUIgBgEIgEgBQgEAAgEADIAAAWIgIAAIAAgUQAAAAAAgBQAAgBgBAAQAAgBAAAAQAAgBgBAAIgDgBQgEAAgFACIAAAXIgIAAIAAgfIAIAAIAAACQAGgEAFABQAHAAACADIAGgCIAHgBQAFAAACACQADADAAAFIAAAWgAAzBmIAAgIIAAgCIgTAAIAAACIAAAIIgJAAIAAgIQAAgKAFgJIAEgIIADgHIABgBIALAAIABABIADAHIAEAIQAFAJAAAKIAAAIgAAlBKIgFALIATAAIgFgLIgEgJIgFAJgAgMBmIAAgfIAIAAIAAACIAEgCIAHgBIAAAIIgHABIgEABIAAAWgAjFBmIgHgLQgEgJAAgKIAAgBIAHAAQAAAIADAIIAFAJIAEgJQADgIAAgIIAIAAIAAABQAAAKgEAJIgHALgAjfBmIAAgfIAIAAIAAAfgAj4BmIAAgfIAIAAIAAACIAFgCIAHgBIAAAIIgHABIgFABIAAAWgAkjBmIAAgrIAPAAQAKAAAFAFQAFAEAAANQAAALgFAGQgFAEgKAAgAkbBfIAHAAQAGAAADgEQADgDAAgHQAAgIgDgDQgDgEgGAAIgHAAgADQA9IAFgGIAFAGIgFAEgACkA9IAFgGIAFAGIgFAEgAjgA9IAFgGIAFAGIgFAEgAB5AQIAAgMIAQACIAIgBQAAAAAAgBQABAAAAAAQAAgBAAAAQAAgBAAgBIgBgCIgEgDIgLgFQgFgDgCgDQgDgDAAgGQAAgIAFgEQAEgDAMAAIAQABIAAAMIgHgBIgJAAIgHABQAAAAAAAAQgBAAAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAAAAAABQAAAAABAAQAAABAAAAIAFADIAKAEQAFACACAEQADAEAAAFQAAAJgFAEQgFADgMABIgQgCgAAQAKQgFgGAAgOQAAgQAFgGQAGgHANAAQANAAAGAHQAFAGAAAQQAAAOgFAGQgGAIgNAAQgNAAgGgIgAAagXQgCADAAAKQAAAJACACQACAEAHABQAHgBACgEQACgCAAgJQAAgKgCgDQgCgEgHAAQgHAAgCAEgAhTAKQgFgGAAgOQAAgQAFgGQAGgHANAAQANAAAFAHQAGAGAAAQQAAAOgGAGQgFAIgNAAQgNAAgGgIgAhJgXQgCADAAAKQAAAJACACQACAEAHABQAGgBADgEQACgCAAgJQAAgKgCgDQgDgEgGAAQgHAAgCAEgABjARIgMgTIgGAAIAAATIgMAAIAAg3IAXAAQAKAAAFADQAEAFAAAKQAAAGgDAFQgDAEgFABIAOAVgABRgNIAKAAQAEAAACgCQABgBAAgEQAAgEgBgBQgCgCgEAAIgKAAgAgUARIAAgrIgQAAIAAgMIAqAAIAAAMIgOAAIAAArgAhuARIAAgmIgRAbIgRgbIAAAmIgNAAIAAg3IARAAIANAWIANgWIAQAAIAAA3gABjg7IAAgMIAHAAIAKABIAHgBQABAAAAAAQAAAAAAgBQABAAAAgBQAAAAAAgBIgBgEIgEgCIgLgGQgFgCgDgDQgCgEAAgFQAAgJAEgEQAFgDAMAAIAPABIAAAMIgGAAIgJgBIgHABQAAAAAAAAQgBABAAAAQAAAAAAABQAAAAAAABQAAAAAAAAQAAABAAAAQAAABABAAQAAAAAAAAIAFADIAKAFQAFACACADQADAFAAAGQAAAJgFADQgFAEgMAAIgRgBgAgchNIAAgmIAMAAIAAAlQAAAFADACQACABAFAAQAFAAABgBQADgCAAgFIAAglIAMAAIAAAmQAAATgVAAQgWAAAAgTgAhLg7IAAgMIARABIAHgBQAAAAABAAQAAAAAAgBQAAAAABgBQAAAAAAgBIgBgEIgFgCIgLgGQgFgCgCgDQgDgEAAgFQAAgJAFgEQAFgDALAAIAQABIAAAMIgGAAIgJgBIgHABQgBAAAAAAQAAABAAAAQgBAAAAABQAAAAAAABQAAAAAAAAQAAABABAAQAAABAAAAQAAAAABAAIAEADIAKAFQAFACADADQADAFAAAGQAAAJgFADQgFAEgMAAIgRgBgADLg7IAAg4IAMAAIAAA4gACzg7IAAgWIgUAAIAAAWIgMAAIAAg4IAMAAIAAAXIAUAAIAAgXIANAAIAAA4gABNg7IAAg4IANAAIAAA4gAAag7IAAg4IAYAAQAJAAAEADQAEAEAAAIQAAAFgDAEIgFADQAEACACACQADADAAAHQAAAHgEAEQgFAFgJgBgAAmhGIALAAQADABACgCQAAAAAAgBQABAAAAgBQAAAAAAgBQAAgBAAgBQAAgDgBgBIgFgBIgLAAgAAmhcIAJAAQAEAAABgCQABAAAAgBQAAAAAAgBQABAAAAgBQAAgBAAAAQAAgBAAgBQAAAAgBgBQAAAAAAgBQAAAAgBgBQgBgBgEAAIgJAAgAhtg7IAAgsIgPAAIAAgMIAqAAIAAAMIgPAAIAAAsgAiRg7IAAg4IAMAAIAAA4gAipg7IAAgnIgRAcIgRgcIAAAnIgMAAIAAg4IAQAAIANAXIANgXIARAAIAAA4g");
	this.shape.setTransform(-0.4,19.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#EA0B19").s().p("AA2COIg2hfIBtAAIA3BfgAijCOIA3hfIBsAAIg2BfgAAAAvIg2hdIA2hfIA2BfIg2BdgAAAAvg");
	this.shape_1.setTransform(-0.5,-10.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.logo_w, new cjs.Rectangle(-29.6,-24.5,58.4,55.9), null);


(lib.logo_b = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#EA0B19").s().p("AA2COIg2hfIBtAAIA3BfgAijCOIA3hfIBsAAIg2BfgAAAAvIg2hdIA2hfIA2BfIg2Bdg");
	this.shape.setTransform(-0.5,-10.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("Ah4BvIAHgJIgHgMQgEgJgBgKIAIAAQABAHADAJIAEAJIAFgJQADgIAAgIIAIAAQAAAQgKAOIgMAQgADkBjQgEgEAAgIQAAgJAEgFQAEgDAIAAQAIAAAEADQAEAFAAAJQAAAIgEAEQgEAEgIAAQgIAAgEgEgADqBQQgCABAAAGQAAAEACACQABADAFAAQAEAAACgDQACgCAAgEQAAgGgCgCQgCgCgEAAQgFAAgBADgAC6BkQgCgBAAgHIAAgPIgGAAIAAgGIAGAAIAAgJIAIAAIAAAJIAKAAIAAAGIgKAAIAAAOIABAEQAAAAABAAQAAABAAAAQABAAAAAAQABAAABAAIAGAAIAAAGIgJABQgGAAgCgDgACKBmIgEgDIAAADIgIAAIAAgsIAIAAIAAAPQAEgEAGABQAGAAAEADQAEAFAAAJQAAAIgEAEQgEAEgGAAIgGgBgACGBQIAAANQAEADAEAAQAEAAACgCQACgCAAgFQAAgGgCgCQgCgCgEAAQgEAAgEADgAgwBkQgCgCAAgFIAAgWIAIAAIAAATQAAABAAABQAAAAAAABQAAAAABABQAAAAAAAAQABABAAAAQAAAAABABQAAAAABAAQAAAAABAAQADAAAFgDIAAgWIAIAAIAAAfIgIAAIAAgCQgGADgFAAQgFAAgDgDgAhVBjQgEgEAAgIQAAgJAEgFQAEgDAIAAQAIAAAEADQAEAFAAAJQAAAIgEAEQgEAEgIAAQgIAAgEgEgAhPBQQgCABAAAGQAAAEACACQACADAEAAQAFAAABgDQACgCAAgEQAAgGgCgCQgBgCgFAAQgEAAgCADgAiqBjQgEgEAAgIQAAgJAEgFQADgDAIAAQAIgBAEAFQADADAAAIIAAAEIgWAAQAAAFACABQACACAFAAIAGgBIAFgCIAAAHIgFABIgHABQgIAAgEgEgAikBNQgCACAAAEIAOAAIgBgFQgCgDgEAAQgDAAgCACgAEcBmIAAgUQAAAAAAgBQAAgBAAAAQAAgBgBAAQAAgBAAAAIgEgBQgDAAgFACIAAAXIgIAAIAAgfIAHAAIAAACQAHgEAFABQAFAAADACQACADAAAFIAAAWgADRBmIAAgfIAIAAIAAAfgAClBmIAAgfIAIAAIAAAfgABuBmIAAgUIgBgEIgEgBQgEAAgEADIAAAWIgIAAIAAgUQAAAAAAgBQAAgBgBAAQAAgBAAAAQAAgBgBAAIgDgBQgEAAgFACIAAAXIgIAAIAAgfIAIAAIAAACQAGgEAFABQAHAAACADIAGgCIAHgBQAFAAACACQADADAAAFIAAAWgAAzBmIAAgIIAAgCIgTAAIAAACIAAAIIgJAAIAAgIQAAgKAFgJIAEgIIADgHIABgBIALAAIABABIADAHIAEAIQAFAJAAAKIAAAIgAAlBKIgFALIATAAIgFgLIgEgJIgFAJgAgMBmIAAgfIAIAAIAAACIAEgCIAHgBIAAAIIgHABIgEABIAAAWgAjFBmIgHgLQgEgJAAgKIAAgBIAHAAQAAAIADAIIAFAJIAEgJQADgIAAgIIAIAAIAAABQAAAKgEAJIgHALgAjfBmIAAgfIAIAAIAAAfgAj4BmIAAgfIAIAAIAAACIAFgCIAHgBIAAAIIgHABIgFABIAAAWgAkjBmIAAgrIAPAAQAKAAAFAFQAFAEAAANQAAALgFAGQgFAEgKAAgAkbBfIAHAAQAGAAADgEQADgDAAgHQAAgIgDgDQgDgEgGAAIgHAAgADQA9IAFgGIAFAGIgFAEgACkA9IAFgGIAFAGIgFAEgAjgA9IAFgGIAFAGIgFAEgAB5AQIAAgMIAQACIAIgBQAAAAAAgBQABAAAAAAQAAgBAAAAQAAgBAAgBIgBgCIgEgDIgLgFQgFgDgCgDQgDgDAAgGQAAgIAFgEQAEgDAMAAIAQABIAAAMIgHgBIgJAAIgHABQAAAAAAAAQgBAAAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAAAAAABQAAAAABAAQAAABAAAAIAFADIAKAEQAFACACAEQADAEAAAFQAAAJgFAEQgFADgMABIgQgCgAAQAKQgFgGAAgOQAAgQAFgGQAGgHANAAQANAAAGAHQAFAGAAAQQAAAOgFAGQgGAIgNAAQgNAAgGgIgAAagXQgCADAAAKQAAAJACACQACAEAHABQAHgBACgEQACgCAAgJQAAgKgCgDQgCgEgHAAQgHAAgCAEgAhTAKQgFgGAAgOQAAgQAFgGQAGgHANAAQANAAAFAHQAGAGAAAQQAAAOgGAGQgFAIgNAAQgNAAgGgIgAhJgXQgCADAAAKQAAAJACACQACAEAHABQAGgBADgEQACgCAAgJQAAgKgCgDQgDgEgGAAQgHAAgCAEgABjARIgMgTIgGAAIAAATIgMAAIAAg3IAXAAQAKAAAFADQAEAFAAAKQAAAGgDAFQgDAEgFABIAOAVgABRgNIAKAAQAEAAACgCQABgBAAgEQAAgEgBgBQgCgCgEAAIgKAAgAgUARIAAgrIgQAAIAAgMIAqAAIAAAMIgOAAIAAArgAhuARIAAgmIgRAbIgRgbIAAAmIgNAAIAAg3IARAAIANAWIANgWIAQAAIAAA3gABjg7IAAgMIAHAAIAKABIAHgBQABAAAAAAQAAAAAAgBQABAAAAgBQAAAAAAgBIgBgEIgEgCIgLgGQgFgCgDgDQgCgEAAgFQAAgJAEgEQAFgDAMAAIAPABIAAAMIgGAAIgJgBIgHABQAAAAAAAAQgBABAAAAQAAAAAAABQAAAAAAABQAAAAAAAAQAAABAAAAQAAABABAAQAAAAAAAAIAFADIAKAFQAFACACADQADAFAAAGQAAAJgFADQgFAEgMAAIgRgBgAgchNIAAgmIAMAAIAAAlQAAAFADACQACABAFAAQAFAAABgBQADgCAAgFIAAglIAMAAIAAAmQAAATgVAAQgWAAAAgTgAhLg7IAAgMIARABIAHgBQAAAAABAAQAAAAAAgBQAAAAABgBQAAAAAAgBIgBgEIgFgCIgLgGQgFgCgCgDQgDgEAAgFQAAgJAFgEQAFgDALAAIAQABIAAAMIgGAAIgJgBIgHABQgBAAAAAAQAAABAAAAQgBAAAAABQAAAAAAABQAAAAAAAAQAAABABAAQAAABAAAAQAAAAABAAIAEADIAKAFQAFACADADQADAFAAAGQAAAJgFADQgFAEgMAAIgRgBgADLg7IAAg4IAMAAIAAA4gACzg7IAAgWIgUAAIAAAWIgMAAIAAg4IAMAAIAAAXIAUAAIAAgXIANAAIAAA4gABNg7IAAg4IANAAIAAA4gAAag7IAAg4IAYAAQAJAAAEADQAEAEAAAIQAAAFgDAEIgFADQAEACACACQADADAAAHQAAAHgEAEQgFAFgJgBgAAmhGIALAAQADABACgCQAAAAAAgBQABAAAAgBQAAAAAAgBQAAgBAAgBQAAgDgBgBIgFgBIgLAAgAAmhcIAJAAQAEAAABgCQABAAAAgBQAAAAAAgBQABAAAAgBQAAgBAAAAQAAgBAAgBQAAAAgBgBQAAAAAAgBQAAAAgBgBQgBgBgEAAIgJAAgAhtg7IAAgsIgPAAIAAgMIAqAAIAAAMIgPAAIAAAsgAiRg7IAAg4IAMAAIAAA4gAipg7IAAgnIgRAcIgRgcIAAAnIgMAAIAAg4IAQAAIANAXIANgXIARAAIAAA4g");
	this.shape_1.setTransform(-0.4,19.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Слой_3
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ak6FjIAArFIJ1AAIAALFg");

	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(1));

}).prototype = getMCSymbolPrototype(lib.logo_b, new cjs.Rectangle(-31.5,-35.5,63,71), null);


(lib.img14 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.video42();
	this.instance.parent = this;
	this.instance.setTransform(-235,-100);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.img14, new cjs.Rectangle(-235,-100,470,200), null);


(lib.img13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.video41();
	this.instance.parent = this;
	this.instance.setTransform(-235,-100);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.img13, new cjs.Rectangle(-235,-100,470,200), null);


(lib.img12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.video16();
	this.instance.parent = this;
	this.instance.setTransform(-235,-100);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.img12, new cjs.Rectangle(-235,-100,470,200), null);


(lib.img11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.video15();
	this.instance.parent = this;
	this.instance.setTransform(-235,-100);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.img11, new cjs.Rectangle(-235,-100,470,200), null);


(lib.img10 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.video14();
	this.instance.parent = this;
	this.instance.setTransform(-235,-100);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.img10, new cjs.Rectangle(-235,-100,470,200), null);


(lib.img9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.video13();
	this.instance.parent = this;
	this.instance.setTransform(-235,-100);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.img9, new cjs.Rectangle(-235,-100,470,200), null);


(lib.img8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.video12();
	this.instance.parent = this;
	this.instance.setTransform(-235,-100);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.img8, new cjs.Rectangle(-235,-100,470,200), null);


(lib.img7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.video11();
	this.instance.parent = this;
	this.instance.setTransform(-235,-100);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.img7, new cjs.Rectangle(-235,-100,470,200), null);


(lib.img6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.video10();
	this.instance.parent = this;
	this.instance.setTransform(-235,-100);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.img6, new cjs.Rectangle(-235,-100,470,200), null);


(lib.img5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.video09();
	this.instance.parent = this;
	this.instance.setTransform(-235,-100);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.img5, new cjs.Rectangle(-235,-100,470,200), null);


(lib.img4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.video08();
	this.instance.parent = this;
	this.instance.setTransform(-235,-100);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.img4, new cjs.Rectangle(-235,-100,470,200), null);


(lib.img3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.video07();
	this.instance.parent = this;
	this.instance.setTransform(-235,-100);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.img3, new cjs.Rectangle(-235,-100,470,200), null);


(lib.img2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.video06();
	this.instance.parent = this;
	this.instance.setTransform(-235,-100);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.img2, new cjs.Rectangle(-235,-100,470,200), null);


(lib.img1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.video05();
	this.instance.parent = this;
	this.instance.setTransform(-235,-100);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.img1, new cjs.Rectangle(-235,-100,470,200), null);


(lib.grad = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.instance = new lib.video41();
	this.instance.parent = this;
	this.instance.setTransform(-65,-30,0.3,0.3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.grad, new cjs.Rectangle(-65,-30,141,60), null);


(lib.girl_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.girl();
	this.instance.parent = this;
	this.instance.setTransform(-152,-144);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.girl_1, new cjs.Rectangle(-152,-144,304,288), null);


(lib.fari_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.fari();
	this.instance.parent = this;
	this.instance.setTransform(-33,-25);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.fari_1, new cjs.Rectangle(-33,-25,66,50), null);


(lib.car_mc = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.car();
	this.instance.parent = this;
	this.instance.setTransform(-128,-69);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.car_mc, new cjs.Rectangle(-128,-69,256,138), null);


(lib.btn_bg_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.btn_bg();
	this.instance.parent = this;
	this.instance.setTransform(-101,-23);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.btn_bg_1, new cjs.Rectangle(-101,-23,202,46), null);


(lib.bgImg1_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.bgImg1();
	this.instance.parent = this;
	this.instance.setTransform(-150,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bgImg1_1, new cjs.Rectangle(-150,-300,300,600), null);


(lib.bg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.bg, new cjs.Rectangle(-150,-300,300,600), null);


(lib.wheel_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.wheel_mc();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({rotation:-360},20,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-21,-21,42,42);


(lib.car_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// wheel
	this.instance = new lib.wheel_1("synched",0,false);
	this.instance.parent = this;
	this.instance.setTransform(110.6,12.1,0.315,0.707,0,0,0,0.3,0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(21));

	// wheel
	this.instance_1 = new lib.wheel_1("synched",0,false);
	this.instance_1.parent = this;
	this.instance_1.setTransform(13.5,30,0.643,1);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(21));

	// car
	this.instance_2 = new lib.car_mc();
	this.instance_2.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(21));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-128,-69,256,138);


(lib.btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Isolation Mode
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Aq8BKIAAgdIhVAAIAAAdIgVAAIAAgwIAPAAQAIgKABgJQADgKAAgNIAAg3IBRAAIAABhIASAAIAAAwgAr2gMQgBAKgCALQgCAJgFAIIAxAAIAAhNIgnAAgAE6AtIAAgTQAEACAGAAQAGAAAEgFQADgDAAgNIAAhOIBTAAIAAB0IgVAAIAAhgIgqAAIAAA/QAAASgIAJQgJAHgOABQgGAAgGgCgAg+ApQgMgFgGgNQgFgOAAgVQAAgXAFgNQAFgMAMgHQAMgFARgBIARABQAJACAHACIAAAUQgOgFgQAAQgLAAgJAEQgGADgEAJQgCAIAAARQAAAOACAKQAEAHAGAEQAJAEALAAQAQAAAOgEIAAATQgHADgJAAIgRACQgSAAgKgGgApvAqIAAgTQAUAFAPgBQAOAAAGgDQAFgEAAgJQAAgJgFgDQgEgDgMAAIgUAAIAAgSIAUAAQAMAAAEgEQAFgDAAgJQAAgJgFgDQgGgEgOAAQgOABgTAFIAAgUQARgFAPAAQAZAAALAIQALAHAAASQAAALgGAIQgFAGgHACQAHACAFAHQAGAFAAAMQAAATgLAHQgLAIgZAAQgTgBgPgEgALYAtIAAh0IBMAAIAAAUIg4AAIAAAdIA2AAIAAASIg2AAIAAAdIA7AAIgFAUgAIqAtIAAh0IAVAAIAABgIAoAAIAAhgIAWAAIAABgIAqAAIAAhgIAVAAIAAB0gAHAAtIAAh0IAUAAIAAApIAaAAQAUAAAKAIQAKAIAAAVQAAAVgKAIQgKAJgUAAgAHUAZIAWAAQAKABAEgCQAFgCADgEQABgEAAgHQAAgHgBgEQgDgEgFgCQgGgCgIAAIgWAAgAEUAtIAAh0IAVAAIAAB0gACpAtIAAh0IBTAAIgDAUIg7AAIAAAYIAaAAQANAAAJAEQAJADAFAIQAEAHAAANQABAUgLAIQgKAJgUAAgAC+AZIAWAAQANABAFgEQAFgDAAgLQAAgJgFgDQgFgFgNAAIgWAAgAATAtIAAh0IAVAAIAAApIAZAAQAVAAALAIQAJAIABAVQgBAVgJAIQgLAJgVAAgAAoAZIAXAAQAIABAFgCQAEgCADgEQACgFAAgGQAAgHgCgEQgDgEgEgCQgHgCgGAAIgXAAgAh/AtIAAhRIg3BRIgRAAIAAh0IAUAAIAABRIA2hRIASAAIAAB0gAkRAtIAAhgIgjAAIAAgUIBdAAIgEAUIghAAIAABggAlDAtIgJgbIgxAAIgJAbIgWAAIArh0IAZAAIArB0gAlTAAIgSgyIgSAyIAkAAgAnAAtIAAgwIgyAAIAAAwIgVAAIAAh0IAVAAIAAAwIAyAAIAAgwIAVAAIAAB0gAqYAtIAAh0IAVAAIAAB0g");
	this.shape.setTransform(-0.5,1.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Слой_1
	this.instance = new lib.btn_bg_1();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.btn, new cjs.Rectangle(-101,-23,202,46), null);


(lib.banner = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_293 = function() {
		if(num >= 2){
			this.stop();
		}else{
			num++;
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(293).call(this.frame_293).wait(17));

	// img
	this.instance = new lib.img1();
	this.instance.parent = this;
	this.instance.setTransform(0,-130,0.96,0.96);

	this.instance_1 = new lib.img2();
	this.instance_1.parent = this;
	this.instance_1.setTransform(0,-130,0.96,0.96);

	this.instance_2 = new lib.img3();
	this.instance_2.parent = this;
	this.instance_2.setTransform(0,-130,0.96,0.96);

	this.instance_3 = new lib.img4();
	this.instance_3.parent = this;
	this.instance_3.setTransform(0,-130,0.96,0.96);

	this.instance_4 = new lib.img5();
	this.instance_4.parent = this;
	this.instance_4.setTransform(0,-130,0.96,0.96);

	this.instance_5 = new lib.img6();
	this.instance_5.parent = this;
	this.instance_5.setTransform(0,-130,0.96,0.96);

	this.instance_6 = new lib.img7();
	this.instance_6.parent = this;
	this.instance_6.setTransform(0,-130,0.96,0.96);

	this.instance_7 = new lib.img8();
	this.instance_7.parent = this;
	this.instance_7.setTransform(0,-130,0.96,0.96);

	this.instance_8 = new lib.img9();
	this.instance_8.parent = this;
	this.instance_8.setTransform(0,-130,0.96,0.96);

	this.instance_9 = new lib.img10();
	this.instance_9.parent = this;
	this.instance_9.setTransform(0,-130,0.96,0.96);

	this.instance_10 = new lib.img11();
	this.instance_10.parent = this;
	this.instance_10.setTransform(0,-130,0.96,0.96);

	this.instance_11 = new lib.img12();
	this.instance_11.parent = this;
	this.instance_11.setTransform(0,-130,0.96,0.96);

	this.instance_12 = new lib.img13();
	this.instance_12.parent = this;
	this.instance_12.setTransform(0,-130,0.96,0.96);

	this.instance_13 = new lib.img14();
	this.instance_13.parent = this;
	this.instance_13.setTransform(0,-130,0.96,0.96);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance}]},170).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_2}]},1).to({state:[{t:this.instance_3}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_5}]},1).to({state:[{t:this.instance_6}]},1).to({state:[{t:this.instance_7}]},1).to({state:[{t:this.instance_8}]},1).to({state:[{t:this.instance_9}]},1).to({state:[{t:this.instance_10}]},1).to({state:[{t:this.instance_11}]},1).to({state:[{t:this.instance_12}]},46).to({state:[{t:this.instance_13}]},1).to({state:[]},1).wait(81));

	// btn
	this.instance_14 = new lib.btn();
	this.instance_14.parent = this;
	this.instance_14.setTransform(0,187,0.02,0.02,0,0,0,0,2.5);
	this.instance_14._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(249).to({_off:false},0).to({regY:0,scaleX:1,scaleY:1},10,cjs.Ease.get(1)).wait(15).to({scaleX:0.98,scaleY:0.98},0).wait(2).to({scaleX:1,scaleY:1},0).wait(2).to({scaleX:0.98,scaleY:0.98},0).wait(2).to({scaleX:1,scaleY:1},0).wait(14).to({alpha:0},15).wait(1));

	// logo_w
	this.instance_15 = new lib.logo_w();
	this.instance_15.parent = this;
	this.instance_15.setTransform(0.5,-146.7,2.2,2.2,0,0,0,-0.2,-0.2);
	this.instance_15.alpha = 0;
	this.instance_15._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_15).wait(229).to({_off:false},0).to({alpha:1},15).wait(50).to({alpha:0},15).wait(1));

	// bg
	this.instance_16 = new lib.bg();
	this.instance_16.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_16).to({alpha:0},15).wait(140).to({alpha:1},15).wait(140));

	// logo
	this.instance_17 = new lib.logo_b();
	this.instance_17.parent = this;
	this.instance_17.setTransform(-85.5,-264.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_17).to({_off:true},170).wait(140));

	// logo2
	this.instance_18 = new lib.logo2();
	this.instance_18.parent = this;
	this.instance_18.setTransform(113.3,236.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_18).to({_off:true},170).wait(140));

	// bg
	this.instance_19 = new lib.bg();
	this.instance_19.parent = this;
	this.instance_19.alpha = 0;
	this.instance_19._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_19).wait(45).to({_off:false},0).to({alpha:1},15).to({alpha:0},15).to({_off:true},1).wait(234));

	// fari
	this.instance_20 = new lib.fari_1();
	this.instance_20.parent = this;
	this.instance_20.setTransform(-45,18);
	this.instance_20.compositeOperation = "lighter";
	this.instance_20._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_20).wait(125).to({_off:false},0).to({_off:true},3).wait(3).to({_off:false},0).to({_off:true},3).wait(176));

	// fari
	this.instance_21 = new lib.grad();
	this.instance_21.parent = this;
	this.instance_21.setTransform(-114.5,12,2,2);
	this.instance_21.alpha = 0.102;
	this.instance_21.compositeOperation = "lighter";

	this.instance_22 = new lib.grad();
	this.instance_22.parent = this;
	this.instance_22.setTransform(-54.5,16.3,2,2);
	this.instance_22.compositeOperation = "lighter";

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_22},{t:this.instance_21}]},125).to({state:[]},2).to({state:[{t:this.instance_22},{t:this.instance_21}]},4).to({state:[]},2).wait(177));

	// t2
	this.instance_23 = new lib.t2();
	this.instance_23.parent = this;
	this.instance_23.setTransform(39.6,-163.5);
	this.instance_23.alpha = 0;
	this.instance_23._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_23).wait(95).to({_off:false},0).to({alpha:1},15).to({_off:true},60).wait(140));

	// car
	this.instance_24 = new lib.car_1("synched",0,false);
	this.instance_24.parent = this;
	this.instance_24.setTransform(236.6,-18,0.7,0.7);
	this.instance_24._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_24).wait(75).to({_off:false},0).to({scaleX:1,scaleY:1,x:-6,y:28,startPosition:20},20,cjs.Ease.get(1)).to({_off:true},75).wait(140));

	// t1_2
	this.instance_25 = new lib.t1_2();
	this.instance_25.parent = this;
	this.instance_25.setTransform(19.9,222.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_25).to({_off:true},61).wait(249));

	// t1_1
	this.instance_26 = new lib.t1_1();
	this.instance_26.parent = this;
	this.instance_26.setTransform(39.5,-172.7);

	this.timeline.addTween(cjs.Tween.get(this.instance_26).to({_off:true},61).wait(249));

	// girl
	this.instance_27 = new lib.girl_1();
	this.instance_27.parent = this;
	this.instance_27.setTransform(18,43);

	this.timeline.addTween(cjs.Tween.get(this.instance_27).to({_off:true},61).wait(249));

	// bgImg1
	this.instance_28 = new lib.bgImg1_1();
	this.instance_28.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_28).wait(310));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,-300,320,600);


// stage content:
(lib._300x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// cover
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#666666").ss(2,1,1).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// banner
	this.instance = new lib.banner();
	this.instance.parent = this;
	this.instance.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(149,299,321,602);
// library properties:
lib.properties = {
	id: 'C5EF0452715C469FAA6212D6F25D74F5',
	width: 300,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/bgImg1.jpg", id:"bgImg1"},
		{src:"images/btn_bg.png", id:"btn_bg"},
		{src:"images/car.png", id:"car"},
		{src:"images/fari.png", id:"fari"},
		{src:"images/girl.png", id:"girl"},
		{src:"images/video05.png", id:"video05"},
		{src:"images/video06.png", id:"video06"},
		{src:"images/video07.png", id:"video07"},
		{src:"images/video08.png", id:"video08"},
		{src:"images/video09.png", id:"video09"},
		{src:"images/video10.png", id:"video10"},
		{src:"images/video11.png", id:"video11"},
		{src:"images/video12.png", id:"video12"},
		{src:"images/video13.png", id:"video13"},
		{src:"images/video14.png", id:"video14"},
		{src:"images/video15.png", id:"video15"},
		{src:"images/video16.png", id:"video16"},
		{src:"images/video41.png", id:"video41"},
		{src:"images/video42.png", id:"video42"},
		{src:"images/wheel.png", id:"wheel"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['C5EF0452715C469FAA6212D6F25D74F5'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;