(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.bgImg = function() {
	this.initialize(img.bgImg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.dev = function() {
	this.initialize(img.dev);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,130,298);


(lib.dev_blur = function() {
	this.initialize(img.dev_blur);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,130,298);


(lib.img1 = function() {
	this.initialize(img.img1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,238,240);


(lib.shadow = function() {
	this.initialize(img.shadow);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,218,132);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.urText = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1,2,0,3).p("ArZGGIWzAAIAAsLI2zAAg");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("ABcFRIAAghQgCAEgFACQgFADgFAAQgHAAgFgEQgGgEgDgFQgDgGAAgIQAAgIADgGQADgFAGgEQAFgEAHAAQAFAAAFADQAFACACAEIAAgHIAKAAIAABMgABFEPIgGAGQgCAFAAAEQAAAEACAFQADAEADACQAEADAEAAQAEAAAEgDQAEgCACgEQACgEAAgFQAAgFgCgEQgCgEgEgCQgEgDgEAAQgEAAgEADgAl8FRIAAhMIAKAAIAAAHQADgEAEgCQAFgDAFAAQAHAAAFAEQAGAEADAFQACAGAAAIQAAAIgCAGQgDAFgGAEQgFAEgHAAQgFAAgFgDQgEgCgDgEIAAAhgAlrEPIgGAGQgCAFAAAEQAAAEACAFQADAEADACQAEADAEAAQAEAAAEgDQAEgCACgEQABgDAAgGQAAgGgBgDQgCgEgEgCQgEgDgEAAQgEAAgEADgAqYFRIAAhMIAKAAIAAAHQADgEAFgCQAEgDAFAAQAIAAAFAEQAGAEACAFQAEAGAAAIQAAAIgEAGQgCAFgGAEQgFAEgIAAQgFAAgEgDQgFgCgDgEIAAAhgAqHEPQgDACgCAEQgCADAAAGQAAAGACADQACAEADACQAEADAFAAQAEAAAEgDQADgCACgEQADgDAAgGQAAgGgDgDQgCgEgDgCQgEgDgEAAQgFAAgEADgAjTFEIAAgNIgrAAIAAgyIAKAAIAAAqIAYAAIAAgqIALAAIAAAqIAHAAIAAAVgAFyE4IgCgDIgBgDIABgEIACgCIAEgBIAEABIACACIABAEIgBADIgCADIgEABgAE8E1QgGgEgDgFQgDgGAAgIQAAgIADgGQADgFAGgEQAFgEAHAAQAFAAAFADQAEACADAEIAAgHIAKAAIAAAyIgKAAIAAgHQgDAEgEACQgFADgFAAQgHAAgFgEgAFCEPQgEACgCAEQgCADAAAGQAAAGACADQACAEAEACQADADAFAAQAEAAAEgDQADgCACgEQACgDAAgGQAAgGgCgDQgCgEgDgCQgEgDgEAAQgFAAgDADgAEDE2QgEgCgEgFQgDgFAAgGIAAgfIAKAAIAAAdQAAAHADADQAEADAFAAQAGAAADgDQAEgEAAgGIAAgdIAKAAIAAAfQAAAGgDAFQgDAFgFACQgGADgGAAQgGAAgFgDgADjE4IgCgDIgBgDIABgEIACgCIAEgBIADABIACACIABAEIgBADIgCADIgDABgAB+E1QgFgDgEgGQgDgGAAgIQAAgIADgGQAEgGAFgDQAIgEAGAAQAIAAAFAEQAHAEADAFQADAHAAAHQAAAIgDAGQgDAFgHAEQgFAEgIAAQgGAAgIgEgACEEPQgEACgCAEQgCAEAAAFQAAAGACADQADAEADACQADACAFAAQAFAAADgCQAFgCABgEQACgFAAgEQAAgEgCgFQgBgEgFgCQgDgCgFAAQgFAAgDACgAgvE1QgHgEgCgFQgDgGgBgIQABgIADgGQACgFAHgEQAEgEAIAAQAFAAAEADQAFACADAEIAAgHIAKAAIAAAyIgKAAIAAgHQgDAEgFACQgEADgFAAQgIAAgEgEgAgqEPQgEACgBAEQgDAEAAAFQAAAFADAEQABAEAEACQAEADAEAAQAFAAADgDQAFgCACgEQACgFAAgEQAAgEgCgFQgCgEgFgCQgDgDgFAAQgEAAgEADgAk0E1QgHgEgCgFQgDgGgBgIQABgIADgGQACgFAHgEQAEgEAIAAQAFAAAEADQAFACADAEIAAgHIAKAAIAAAyIgKAAIAAgHQgDAEgFACQgEADgFAAQgIAAgEgEgAkvEPIgFAGQgDAFAAAEQAAAEADAFQACAEADACQAEADAEAAQAEAAAEgDQAEgCACgEQACgEABgFQgBgFgCgEQgCgEgEgCQgEgDgEAAQgEAAgEADgAneE1QgGgEgDgFQgEgGAAgIQAAgIAEgFQADgHAGgDQAHgEAHAAQAGAAAHADQAFADAEAEIgHAGIgHgFQgDgBgFAAQgFAAgEACQgEACgBAEQgDAFAAAEIADAJQACAEADACQAEACAFAAQAFAAADgBIAHgFIAHAGQgEAEgFADQgHADgGAAQgIAAgGgEgAoTE1QgHgDgDgGQgEgGAAgIQAAgHAEgGQAEgHAFgDQAHgEAHAAQAHAAAGADQAFACAEAFIgGAGQgDgEgEgCQgDgBgGAAQgEAAgEACQgEABgBAEIgEAHIAZAAIAAAHIgZAAQACAHAEAEQAFAEAGAAQAGAAADgBIAHgFIAGAGQgEAEgFACQgGADgHAAQgIAAgFgEgApPE1QgGgDgEgGQgCgGAAgIQAAgIACgGQAFgHAFgCQAFgEAIAAQAHAAAFAEQAGADADAGQAEAFAAAHIgBAFIgnAAIACAIQADADADACQAEACAFAAQAFAAAEgCQAEgBADgDIAFAGQgDAEgHACQgGADgGAAQgIAAgGgEgApNEPQgDAEgBAHIAeAAQgCgHgDgEQgFgDgFAAQgFAAgGADgAC3E3IgJgFIAFgHIAIAEIAIABQAEAAADgCQAEgCAAgDQAAAAgBgBQAAgBAAAAQAAgBAAAAQgBAAAAgBIgEgCIgQgFQgEgBgCgDQgDgDAAgFQAAgFADgDQADgEADgBQAFgCAHAAIAKACQAEABAFADIgFAHIgGgDIgIgBQgFAAgDABQgCACAAADIABADIADACIARAFQADACADADQADADAAAFQgBAEgCAEQgBADgGADQgFABgFAAIgNgBgAAdE3IAAgyIAKAAIAAAygAhRE3IAAgWIgZAAIAAAWIgKAAIAAgyIAKAAIAAAUIAZAAIAAgUIAKAAIAAAygAikE3IAAgyIAKAAIAAAygAi/E3IAAgyIAKAAIAAAygAmiE3IAAgqIgSAAIAAgIIAtAAIAAAIIgRAAIAAAqgAAfD4IgDgCIAAgDIAAgDIADgDIADgBIADABIADADIABADIgBADIgDACIgDABgAi+D4IgCgCIgBgDIABgDIACgDIADgBIADABIADADIABADIgBADIgDACIgDABgAibD3QgBgBAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAgBABAAQAAgBAAAAQABgBAAAAQABAAABAAQAAAAABAAQABAAAAAAQABAAAAAAQABAAAAABQABAAAAABQAAAAABABQAAAAAAABQAAAAAAABQABAAAAABQAAAAgBABQAAAAAAABQAAAAAAABQgBAAAAABQAAAAgBABQAAAAgBAAQAAABgBAAQAAAAgBAAQgBAAAAAAQgBAAgBgBQAAAAgBAAQAAgBAAAAgAisD3QgBgBAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAgBABAAQAAgBABAAQAAgBABAAQAAAAABAAQAAAAABAAQABAAAAAAQABAAAAAAQABAAAAABQABAAAAABQAAAAABABQAAAAAAABQAAAAAAABQABAAAAABQAAAAgBABQAAAAAAABQAAAAAAABQgBAAAAABQAAAAgBABQAAAAgBAAQAAABgBAAQAAAAgBAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQgBgBAAAAgAF/DfIgEgBIABgJIAHABIAEgBIAFgDIADgHIACgGIgVgzIAKAAIAQAoIAQgoIALAAIgeBFQgDAEgEACQgDACgFAAgABHDUIAAgPIg6AAIAAhKIALAAIAABAIAlAAIAAhAIAKAAIAABAIAKAAIAAAZgAE4DDQgHgEgCgGQgDgGAAgIQAAgHADgGQADgHAGgDQAFgDAHAAQAFAAAFACQAEADADAEIAAgIIAKAAIAAAzIgKAAIAAgIQgDAEgEADQgFACgFAAQgGAAgGgDgAE9CcQgDACgCAEQgCAEAAAFQAAAGACAEQACAEADACQAFACADAAQAFAAAEgCQAEgDACgDQACgEAAgGQAAgFgCgEQgCgDgEgDQgEgCgFAAQgDAAgFACgAEDDEQgGgCgDgEIAFgHQACADAFACQAEACAFAAQAGAAADgCQADgCAAgEQABgHgLAAIgLAAIAAgHIAIAAQAGAAADgCQADgCgBgEQABgDgDgCQgDgCgFAAQgJAAgGAGIgFgGIAJgGQAFgCAHAAQAJAAAGAEQAEAEAAAGQAAADgCAEQgCADgDACQAFABACADQADAEAAADQAAAFgDAEQgDADgFACQgHACgFAAQgHAAgFgCgAC0DDQgGgEgDgGQgDgGAAgIQAAgHADgGQAEgHAFgDQAFgDAHAAQAFAAAEACQAFADADAEIAAgIIAKAAIAAAzIgKAAIAAgIQgDAEgFADQgEACgFAAQgGAAgGgDgAC6CcQgEADgCADQgCAEAAAFQAAAGACAEQACADAEADQADACAEAAQAFAAAEgCQADgDADgDIABgKQAAgEgBgFQgDgDgDgDQgEgCgFAAQgEAAgDACgAgfDFIgCgCIgBgEIABgDIACgDIAEgBIADABIADADIABADIgBAEIgDACIgDABgAl9DGIABgJIADAAQABAAAAAAQABAAAAgBQABAAAAAAQABAAAAgBQABgBABgEIACgkIAoAAIAAAzIgKAAIAAgqIgVAAIAAARQgBAKgBAFQgBAGgEACQgDADgHAAgAIJDDQgHgEgDgGQgEgHAAgGQAAgHAEgHQADgGAHgEQAFgDAIAAQAIAAAGADQAGAFADAFQAEAFgBAJQABAIgEAFQgDAFgGAFQgHADgHAAQgIAAgFgDgAIOCcIgGAGQgCAEAAAGQAAAFACAEQADAEADACQADACAFAAQAFAAADgCQAFgDABgDQADgFgBgEQABgFgDgFQgBgDgFgDQgDgCgFAAQgFAAgDACgAmoDDQgHgFgCgFQgEgFAAgIQAAgJAEgFQACgFAHgFQAGgDAHAAQAJAAAFADQAGAEAEAGQADAHAAAHQAAAGgDAHQgEAGgGAEQgGADgIAAQgHAAgGgDgAmjCcQgEADgBADQgDAFAAAFQAAAEADAFQABADAEADQAEACAEAAQAFAAADgCQAEgCADgEQABgEAAgFQAAgGgBgEQgDgDgEgDQgDgCgFAAQgEAAgEACgApTDDQgIgFgCgFQgDgFgBgIQABgJADgFQACgFAIgFQAFgDAIAAQAIAAAGADQAFAEAEAGQADAHAAAHQAAAGgDAHQgEAGgFAEQgHADgHAAQgIAAgFgDgApPCcQgEADgBADQgDAFAAAFQAAAEADAFQABADAEADQAEACAFAAQAFAAADgCQAEgCACgEQACgEAAgFQAAgGgCgEQgCgDgEgDQgDgCgFAAQgFAAgEACgAKTDFIAAglIgaAlIgJAAIAAgzIAJAAIAAAlIAbglIAJAAIAAAzgAI6DFIAAgzIAXAAQAKAAAEAEQAFAEAAAFQAAADgCAEQgCADgEACQAFAAADAEQACADAAAFQAAAEgCADQgCADgEACQgDACgHAAgAJEC9IAOAAQAFAAADgCQADgBgBgEQABgHgLAAIgOAAgAJECoIAMAAQAFAAADgCQACgCAAgEQAAgHgKAAIgMAAgAHoDFIAAglIgRAXIgGAAIgQgXIAAAlIgKAAIAAgzIAKAAIATAaIAUgaIAKAAIAAAzgACTDFIAAgWIgYAAIAAAWIgLAAIAAgzIALAAIAAAUIAYAAIAAgUIAKAAIAAAzgABaDFIAAgzIAJAAIAAAzgAg2DFIAAglIgaAlIgJAAIAAgzIAJAAIAAAlIAbglIAJAAIAAAzgAhwDFIAAglIgQAXIgHAAIgRgXIAAAlIgJAAIAAgzIAJAAIAUAaIAUgaIAJAAIAAAzgAi5DFIAAgzIAKAAIAAAzgAjQDFIAAgWIgZAAIAAAWIgKAAIAAgzIAKAAIAAAUIAZAAIAAgUIAKAAIAAAzgAkXDFIAAgqIgSAAIAAgJIAuAAIAAAJIgSAAIAAAqgAk7DFIAAgzIAKAAIAAAzgAnJDFIAAgWIgZAAIAAAWIgKAAIAAgzIAKAAIAAAUIAZAAIAAgUIAKAAIAAAzgAoiDFIAAgzIAXAAQAJAAAFAEQAEAEABAFQgBAEgBADQgDAEgDABQAFABADADQACAEAAAEQAAAEgCADQgCADgEACQgEACgGAAgAoYC9IAOAAQAGAAACgCQACgBAAgEQAAgHgKAAIgOAAgAoYCoIALAAQAGAAACgCQADgCAAgEQAAgHgLAAIgLAAgAp1DFIAAgqIgZAAIAAAqIgKAAIAAgzIAtAAIAAAzgABbCGIgCgDIgBgDIABgDIACgCIADgBIAEABIACACIABADIgBADIgCADIgEABgAi3CGIgDgDIAAgDIAAgDIADgCIAEgBIACABIADACIABADIgBADIgDADIgCABgAk6CGIgCgDIgBgDIABgDIACgCIADgBIAEABIACACIABADIgBADIgCADIgEABgABQBrIAAhLIAKAAIAAAHQADgFAEgCQADgCAHAAQAGAAAFAEQAFACAEAHQADAGAAAIQAAAIgDAGQgEAGgFADQgFADgGAAQgHAAgDgCQgEgBgDgFIAAAggABhAqQgDABgDAFQgCADAAAGQAAAFACAEQACAEAEACQADACAFAAQAFAAADgCQADgCACgEIACgJQAAgEgCgFQgDgFgCgBQgEgDgEAAQgFAAgDADgAk3BfIAAgNIgqAAIAAANIgJAAIAAgVIAGAAQACgDACgFIACgiIAnAAIAAAqIAIAAIAAAVgAlWBCQgBAFgDADIAZAAIAAgiIgUAAgAmuBQQgHgDgDgHQgDgFAAgIQAAgIADgGQAEgGAFgDQAGgEAHAAQAIAAAFADQAGAEADAFQAEAGgBAHIAAAFIgoAAQAAAEADAEQADADADACQADACAGAAQAFAAADgCQAEgCADgCIAFAGQgDAEgGACQgGADgGAAQgHAAgHgEgAmsAqQgEADgBAHIAeAAQAAgFgEgFQgFgDgGAAQgGAAgEADgAqcBTIACgJIADAAQADAAACgCQABgCABgGIACg4IA0AAIAABKIgKAAIAAhBIggAAIgBAeQABAOgCAIQgDAIgDADQgEAEgHAAgAE8BQQgGgEgDgFQgDgGAAgIQAAgIADgGQAEgGAFgDQAFgEAHAAQAGAAAEACQAEACADAFIAAgHIAKAAIAAAyIgKAAIAAgHQgDAEgEACQgEACgGAAQgHAAgFgDgAFCAqQgDABgDAFQgCAFAAAEIACAJQADAEADACQACACAGAAQAEAAAEgCQAEgCABgEQADgFAAgEQAAgFgDgEQgCgFgDgBQgEgDgEAAQgFAAgDADgADTBQQgFgDgEgHQgDgGAAgHQAAgIADgGQADgGAGgDQAGgEAIAAQAGAAAHADQAGADADAEIgGAGQgDgDgEgCQgEgBgFAAQgEAAgEACIgGAGQgCADAAAGQAAAFACAEQACAEAEACQAFACADAAQAFAAAEgCQAFgCACgDIAGAHQgEAFgFACQgFACgIAAQgIAAgGgDgAAcBQQgGgDgDgHQgEgHAAgGQAAgHAEgHQAEgHAFgCQAFgEAJAAQAHAAAGAEQAFACAEAHQAEAHAAAHQAAAGgEAHQgDAHgGADQgGADgHAAQgJAAgFgDgAAhAqQgDACgCAEQgCAEAAAFQAAAFACAEQACAEADACQAEACAFAAQAEAAAEgCQADgBACgFQADgEAAgFQAAgEgDgFQgCgEgDgCQgDgCgFAAQgGAAgDACgAkoBTIACgJIACAAQABAAABAAQABAAAAAAQABAAAAgBQABAAAAAAIACgFIABgkIApAAIAAAyIgKAAIAAgqIgVAAIgDAhQgBAFgDADQgDACgGAAgAIJBSIAAgTIgLAAIgNATIgLAAIANgUQgFgCgEgDQgDgEAAgGQABgIAFgDQAFgEAJAAIAYAAIAAAygAH0ApQgCADgBADQABAEACACQACACAGAAIANAAIAAgQIgNAAQgGAAgCACgAHRBSIAAgWIgZAAIAAAWIgKAAIAAgyIAKAAIAAAUIAZAAIAAgUIAKAAIAAAygAGVBSIAAgWIgZAAIAAAWIgKAAIAAgyIAKAAIAAAUIAZAAIAAgUIAKAAIAAAygAEPBSIAAgqIgSAAIAAgIIAuAAIAAAIIgSAAIAAAqgACyBSIAAglIgaAlIgKAAIAAgyIAKAAIAAAkIAbgkIAJAAIAAAygAAABSIgMgUIgCgBIgCgBIgIAAIAAAWIgKAAIAAgyIAKAAIAAATIAKAAIABgBIANgSIALAAIgQAXIARAbgAg6BSIAAglIgbAlIgJAAIAAgyIAKAAIAAAkIAagkIAKAAIAAAygAiVBSIAAgyIAXAAQAJAAAFADQAEADABAHQgBAEgBADQgDADgDABQAFABADADQACADAAAFQAAAFgCACQgCAEgEABQgEACgGAAgAiLBLIAOAAQAFAAADgCQACgBAAgFQAAgHgKAAIgOAAgAiLA1IAMAAQAFAAADgCQACgBAAgEQAAgHgKAAIgMAAgAjFBSIAAgTIgLAAIgNATIgLAAIAOgUQgHgCgCgDQgDgEgBgGQABgHAFgEQAFgEAKAAIAXAAIAAAygAjZApQgEADAAADQAAAEAEACQACACAGAAIAMAAIAAgQIgMAAQgGAAgCACgAoNBSIAAgyIAKAAIAAAqIAUAAIAAgqIAKAAIAAAqIAUAAIAAgqIAKAAIAAAygAolBSIAAglIgbAlIgJAAIAAgyIAKAAIAAAkIAagkIAJAAIAAAygApRgSIAAgNIhHAAIAAgzIAKAAIAAAqIAVAAIAAgqIAKAAIAAAqIAUAAIAAgqIAKAAIAAAqIAIAAIAAAWgAIlgfIgCgDIgBgDIABgDIACgDIADgBIAEABIACADIABADIgBADIgCADIgEABIgDgBgAGOgiQgFgCgFgHQgCgGAAgIQAAgHACgGQAEgGAGgEQAGgDAIAAQAIAAAEACQAHAEACADIgGAHQgCgEgEgBQgGgCgDAAQgEAAgEACIgHAGQgBAFAAAEQAAAGABADQAEAFADABQAEADAEAAQAFAAAEgCQAEgCACgDIAGAGQgCAFgHACQgEADgIAAQgIAAgGgEgAC0giQgFgDgEgGQgDgGAAgIQAAgHADgHQAEgGAFgDQAGgDAHAAQAIAAAFADQAGAEADAFQAEAFgBAHIAAAFIgoAAQAAAFADADQACADAEACQAFACAEAAQAFAAADgCQAEgBADgDIAFAHQgDAEgFACQgGACgHAAQgIAAgHgEgAC3hHQgEADgBAHIAeAAQAAgGgEgEQgFgEgGAAQgGAAgEAEgABogeIABgJIADAAQABAAAAAAQABAAAAgBQABAAAAAAQABAAAAgBQABgBABgEIACgkIAoAAIAAAzIgKAAIAAgrIgVAAIAAASQgBAJgBAGQgBAFgEADQgDADgHAAgAA3giQgFgCgEgHQgDgGAAgIQAAgHADgHQAEgGAFgDQAFgDAHAAQAGAAAEACQAEACADAEIAAgHIAKAAIAAAzIgKAAIAAgIQgDAFgEACQgEACgGAAQgHAAgFgEgAA9hIQgEACgCAEQgCAFAAAEQAAAEACAFQACAEAEADQADACAFAAQAEAAAEgCQAEgDABgEQACgDAAgGQAAgFgCgEQgBgEgEgCQgEgCgEAAQgFAAgDACgAAAggQgEgDgEgEIAGgGQACAEADABQAFACAEAAQAGAAAEgCQADgCAAgEQAAgIgKAAIgLAAIAAgGIAIAAQAEAAAEgCQADgCABgEQgBgEgDgBQgCgCgFAAQgJAAgFAGIgGgGIAIgGQAFgCAHAAQAKAAAFADQAFAFAAAGQAAAEgCADQgCADgDABQAEACADADQACADAAAEQAAAFgCADQgEAEgEACQgFACgIAAQgHAAgFgCgAhIgiQgFgCgFgHQgEgHAAgHQAAgGAEgHQACgFAIgFQAFgDAIAAQAJAAAEACQAFACAEAFIgGAGQgDgEgEgBIgIgCQgEAAgFACQgCABgDAEQgCADgCAFIAaAAIAAAHIgaAAQACAHAEADQAEAEAIAAIAIgBIAHgFIAGAGQgDAEgGADQgEACgJAAQgIAAgFgEgAiIgiQgFgCgEgHQgDgGAAgIQAAgHADgHQAEgGAFgDQAFgDAHAAQAGAAAEACQAEACADAEIAAgHIAKAAIAAAzIgKAAIAAgIQgDAFgEACQgEACgGAAQgHAAgFgEgAiDhIQgDACgCAEQgCAFAAAEQAAAEACAFQACAEADADQAEACAFAAQAEAAAEgCQAEgDACgEQABgDAAgGQAAgFgBgEQgCgEgEgCQgEgCgEAAQgFAAgEACgAlFgeIACgJIACAAQABAAABAAQAAAAABgBQAAAAABAAQAAAAAAgBQACgCAAgDIABgkIAqAAIAAAzIgLAAIAAgrIgVAAIgCAhQgBAFgEADQgDADgGAAgAo2giQgGgCgDgHQgEgGAAgIQAAgIAEgFQADgHAGgDQAGgDAHAAQAJAAAFADQAFADAEAHQADAGAAAHQAAAIgDAGQgEAHgFACQgFAEgJAAQgHAAgGgEgAoxhIIgGAGQgCAFAAAEQAAAEACAFQADAEADACQAEADAEAAQAFAAADgDQAFgCABgEQACgDAAgGQAAgFgCgEQgBgDgFgDQgDgCgFAAQgEAAgEACgAHvgfIAAgzIAKAAIAAASIALAAQALAAAFAEQAGAEAAAIQAAAIgGAEQgFAFgLAAgAH5gnIALAAQAMAAAAgJQgBgEgDgCQgDgCgFAAIgLAAgAHKgfIAAgrIgSAAIAAgIIAuAAIAAAIIgSAAIAAArgAFsgfIAAgzIAKAAIAAAzgAFTgfIAAgXIgZAAIAAAXIgKAAIAAgzIAKAAIAAAUIAZAAIAAgUIAKAAIAAAzgAEbgfIgOgWIgGAAIAAAWIgKAAIAAgWIgGAAIgBABIgMAVIgMAAIARgbIgRgYIAMAAIAMASIABABIACABIAEAAIAAgUIAKAAIAAAUIAFAAIABgBIABgBIANgSIALAAIgRAYIASAbgAijgfIgOgVIgBgBIgKAAIAAAWIgKAAIAAgzIAKAAIAAAUIAJAAIABgBIABgBIAOgSIALAAIgSAYIASAbgAjegfIAAglIgbAlIgJAAIAAgzIAKAAIAAAlIAaglIAJAAIAAAzgAlVgfIgOgVIgBgBIgKAAIAAAWIgKAAIAAgzIAKAAIAAAUIAIAAIACgBIABgBIAOgSIALAAIgSAYIASAbgAmRgfIAAglIgaAlIgJAAIAAgzIAJAAIAAAlIAbglIAJAAIAAAzgAnrgfIAAgzIAXAAQAHAAAGADQAFAEAAAGQAAAEgBADQgDAEgDAAQAFACACADQADACgBAFQAAAFgBADQgEADgDACQgGACgEAAgAnignIAOAAQAGAAACgCQACgCAAgDQAAgIgKAAIgOAAgAnig8IAMAAQAEAAAEgCQACgDABgDQAAgHgLAAIgMAAgAFuheIgDgDIgBgDIABgDIADgDIADAAIADAAIADADIABADIgBADIgDADIgDAAgAoXh5IAAhMIAKAAIAAAIQAEgFADgCQAFgCAFAAQAGAAAGADQAFADAEAHQADAGAAAIQAAAHgDAGQgEAIgFACQgFADgHAAQgGAAgEgCQgDgBgEgGIAAAhgAoGi7QgDACgCAEQgCAEgBAGQABAFACAEQACAEADACQADACAFAAQAFAAADgCQAEgCACgEQACgFAAgEIgCgKQgCgDgEgDQgDgCgFAAQgFAAgDACgAJNiDIAGgHQADgEAAgDIgEgDQgBAAAAgBQAAAAgBAAQAAgBAAgBQAAAAAAgBIACgFIAEgBQAEAAABACQADADAAAEQAAAFgDAHQgEAGgGAEgAF3iUQgHgDgDgHQgDgFgBgIQABgIADgGQADgGAHgEQAFgDAIAAQAHAAAHADQAFAEAEAGQADAGAAAIQAAAHgDAGQgEAHgFADQgGADgIAAQgIAAgFgDgAF7i6IgGAGQgCAFAAAEQAAAEACAFQADAEADACQAEACAFAAQAEAAAEgCQAEgCACgEQACgEAAgFQAAgGgCgDQgCgEgEgCQgEgDgEAAQgFAAgEADgAg4iUQgGgDgEgHQgDgGAAgHQAAgIADgGQADgGAHgDQAFgEAIAAQAIAAAFADQAGACADAFIgGAGQgCgDgFgCQgEgCgFAAQgEAAgEADQgEABgCAFQgCADAAAGQAAAFACAEQACAEAEACQAEACAEAAQAEAAAFgCQAEgBADgEIAGAGQgDAFgGADQgGACgHAAQgIAAgFgDgAk0iRIACgJIACAAQABAAAAAAQABAAABAAQAAAAABgBQAAAAABAAIACgFIABglIAoAAIAAAzIgKAAIAAgqIgVAAIAAASIgCAOQgCAGgDADQgEACgFAAgAlgiUQgGgDgEgHQgDgGAAgHQAAgIADgGQAEgGAGgEQAFgDAIAAQAIAAAGADQAGAFADAFQADAGAAAIQAAAIgDAFQgDAGgGAEQgGADgIAAQgIAAgFgDgAlbi6IgGAGQgCADAAAGQAAAFACAEQADAEADACQADACAFAAQAFAAADgCQAEgCADgEQABgFAAgEQAAgEgBgFQgDgEgEgCQgDgDgFAAQgEAAgEADgAmYiTQgFgCgEgEIAGgGIAHAFIAJABQAFAAAEgCQADgCAAgEQAAgHgLAAIgKAAIAAgHIAJAAQAFAAADgCQACgCAAgDQAAgEgCgCQgCgCgGAAQgJAAgGAGIgFgGIAJgGQAEgCAHAAQAKAAAFAEQAFADAAAHQAAAFgCACQgCAEgEABQAGABABADQADADAAAFQAAAEgDAEQgDAEgFABQgEACgHAAQgIAAgFgCgAnPiUQgGgDgDgHQgDgFgBgIQABgIADgGQADgGAGgEQAHgDAHAAQAIAAAFADQAGAEAEAGQADAHABAHQgBAGgDAHQgEAHgGADQgFADgIAAQgIAAgGgDgAnKi6QgCACgDAEQgCAEgBAFQABAFACAEQADAEACACQAEACAFAAQAGAAACgCQAEgCACgEQACgEAAgFQAAgGgCgDQgCgEgEgCQgDgDgFAAQgFAAgEADgApIiUQgHgDgDgHQgEgFAAgIQAAgJAEgFQADgGAGgEQAGgDAHAAQAHAAAGADQAGADADAGQADAGAAAHIgBAEIgnAAQABAFACADQABADAFADQAEABAEAAIAJgBQAEgCADgDIAFAHQgDAEgGACQgFACgIAAQgIAAgFgDgApGi6QgFAEAAAGIAeAAQgBgGgEgEQgEgDgGAAQgHAAgDADgAI5iSIAAgWIgZAAIAAAWIgKAAIAAgzIAKAAIAAAUIAZAAIAAgUIAKAAIAAAzgAH/iSIAAglIgbAlIgJAAIAAgzIAJAAIAAAlIAbglIAJAAIAAAzgAG1iSIAAgqIgRAAIAAgJIAtAAIAAAJIgSAAIAAAqgAFaiSIgOgWIgCAAIgIAAIAAAWIgKAAIAAgzIAKAAIAAAUIAIAAIACAAIAOgUIAMAAIgSAYIATAbgAEfiSIAAgzIAKAAIAAAzgAEGiSIAAgWIgZAAIAAAWIgKAAIAAgzIAKAAIAAAUIAZAAIAAgUIAKAAIAAAzgACXiSIAAgzIAKAAIAAATIAKAAQAMAAAEAEQAGADgBAJQABAIgGAEQgEAEgMAAgAChiaIAKAAQALAAAAgIQAAgEgCgDQgCgCgHAAIgKAAgABxiSIAAgqIgRAAIAAgJIAtAAIAAAJIgSAAIAAAqgABLiSIAAglIgaAlIgJAAIAAgzIAJAAIAAAlIAbglIAJAAIAAAzgAACiSIAAgqIgRAAIAAgJIAtAAIAAAJIgSAAIAAAqgAhaiSIAAgzIAKAAIAAAzgAhziSIAAgkIgRAWIgGAAIgQgWIAAAkIgKAAIAAgzIAKAAIATAbIAUgbIAJAAIAAAzgAjxiSIAAgzIAKAAIAAATIALAAQALAAAFAEQAFAEABAIQgBAIgFAEQgFAEgLAAgAjniaIALAAQAMAAAAgIQAAgEgEgDQgCgCgGAAIgLAAgApliSIgGgOIgiAAIgEAOIgLAAIAchKIAJAAIAdBKgAqJipIAbAAIgOgkgAEhjRIgCgCIgBgEIABgDIACgCIADgBIADABIADACIAAADIAAAEIgDACIgDABgAhZjRIgCgCIgBgEIABgDIACgCIADgBIAEABIACACIABADIgBAEIgCACIgEABgAACjqIgCgBIAAgJIAHABIAEgBIAEgDIAGgNIgVgzIAKAAIAQAnIAQgnIAKAAIgYA4QgDAJgDADQgDAFgDACQgDACgGAAgADajrIAAhMIAKAAIAAAHQADgEAEgCQAEgDAGAAQAFAAAIAEQAGAEACAFQADAGAAAIQAAAIgDAGQgDAGgFADQgGAEgHAAQgGAAgEgDQgEgCgDgEIAAAhgADrktQgDACgDAEQgCAEAAAFQAAAGACADQADAFADABQAEADAFAAQAEAAAEgDQACgBADgFQACgDAAgGQAAgFgCgEQgCgEgDgCQgEgCgEAAQgFAAgEACgAJMkEIgCgDIgBgDIABgDIACgDIAEgBIADABIADADIABADIgBADIgDADIgDABgAFZkFQgFgCgEgFIAGgGQACADAFACQAEACAFAAQAFAAAEgDQADgCAAgDQAAgIgKAAIgLAAIAAgHIAIAAQAGAAADgCQADgBAAgEQAAgEgDgBQgDgCgFAAQgJAAgGAGIgGgGIAJgGQAGgDAHAAQAIAAAGAEQAFAEAAAHQAAAEgCADQgDADgDABQAFACADADQACADAAAEQAAAEgCAEQgDADgFADQgFACgHAAQgJAAgEgCgABEkHQgGgDgEgGQgDgHAAgHQAAgIADgFQAEgHAFgDQAHgEAIAAQAHAAAFADQAGACADAFIgGAHQgDgEgEgBQgEgCgEAAQgEAAgFACQgEACgCAEQgCAEAAAFQAAAGACADQACAEAEACQADACAGAAQAEAAAEgBQADgBAEgEIAGAGQgDAEgGADQgGADgGAAQgJAAgFgEgAg+kHQgGgDgEgGQgDgGAAgIQAAgHADgGQAFgHAFgDQAGgEAIAAQAGAAAGADQAHADACAEIgGAGQgCgDgFgCQgDgCgFAAQgFAAgDACQgEABgCAEIgDAHIAZAAIAAAIIgZAAQABAHAEADQAGAEAGAAQAFAAADgBIAHgFIAGAGQgDAEgGACQgGADgGAAQgJAAgFgEgAh+kHQgFgDgDgGQgEgGAAgIQAAgIAEgGQACgFAGgEQAGgEAGAAQAFAAAFADQAFACACAEIAAgHIAKAAIAAAyIgKAAIAAgHQgCAEgFACQgFADgFAAQgHAAgFgEgAh4ktIgGAGIgCAJQAAAEACAFQADAFADABQAEADAEAAQAEAAAEgDQAEgBACgFQACgEAAgFQAAgEgCgFQgCgEgEgCQgDgCgFAAQgGAAgCACgAjvkGQgFgDgEgGQgDgGAAgGIgJAAIAAAWIgJAAIAAgyIAJAAIAAAUIAJAAQABgHADgEQADgFAGgDQAFgDAHAAQAHAAAGAEQAGAEADAFQADAGAAAIQAAAIgDAGQgDAFgGAEQgGAEgHAAQgHAAgGgDgAjqktQgDACgDAEQgCAEAAAFQAAAGACADQADAEADACQADACAFAAQAFAAADgCQADgDACgDQACgEAAgFQAAgFgCgEQgCgDgDgDIgIgCQgEAAgEACgAlRkEIACgJIACABQABAAAAAAQABAAABgBQAAAAABAAQAAAAAAgBIADgFIABgkIApAAIAAAyIgKAAIAAgqIgVAAIgBASQAAAIgCAHQgCAFgDADQgDADgGAAgApAkHQgHgEgCgFQgEgGAAgIQAAgIAEgGQACgFAHgEQAGgEAGAAQAHAAAGAEQAGADAEAGQACAFAAAHIAAAFIgoAAQABAFACADQACADAEACQAEACAEAAQAFAAAEgCQAFgBACgDIAGAGQgDAEgGACQgHADgGAAQgIAAgGgEgAo+ksQgDADgBAHIAeAAQgBgHgFgDQgDgEgHAAQgGAAgEAEgAIUkFIAAgyIAXAAQAKAAAEADQAFAEAAAGQAAADgCAEQgCADgDABQADABAEAEQACACAAAFQAAAEgCAEIgGAFQgEABgGAAgAIekMIAOAAQAEAAAEgCQADgCAAgDQgBgIgKAAIgOAAgAIekiIALAAQAGAAACgBQADgDAAgDQAAgHgLAAIgLAAgAH7kFIAAgyIAKAAIAAAygAHmkFIgNgUIgCgBIgCgBIgIAAIAAAWIgKAAIAAgyIAKAAIAAAUIAIAAIACgBQABAAAAAAQAAAAAAAAQAAAAAAgBQAAAAAAAAIAOgSIALAAIgSAYIATAagAGrkFIAAgkIgbAkIgJAAIAAgyIAKAAIAAAlIAaglIAJAAIAAAygAE8kFIAAgkIgaAkIgJAAIAAgyIAJAAIAAAlIAbglIAJAAIAAAygACskFIgNgSIgOASIgMAAIAUgZIgUgZIAMAAIAOASIAOgSIALAAIgTAZIATAZgABykFIAAgyIAKAAIAAAygAigkFIAAgUQgGADgHAAQgGAAgFgCQgEgDgCgEQgDgEAAgGIAAgOIAKAAIAAAOQAAAFADACQAEADAFAAQAGAAAFgDIAAgVIAKAAIAAAygAlhkFIgOgUIgBgBIgCgBIgIAAIAAAWIgKAAIAAgyIAKAAIAAAUIAJAAIABgBIABgBIAOgSIALAAIgRAYIASAagAmckFIAAgkIgbAkIgJAAIAAgyIAKAAIAAAlIAaglIAJAAIAAAygAn3kFIAAgyIAWAAQALAAADADQAFAEABAGQgBADgCAEQgBADgEABQAFACADADQACACAAAFQAAAEgCAEQgCACgEADQgEABgGAAgAnukMIAOAAQAEAAAEgCQADgCAAgDQAAgIgLAAIgOAAgAnukiIAMAAQAFAAADgBQACgCAAgEQABgHgLAAIgMAAgAplkFIAAghIgmAAIAAAhIgLAAIAAhKIALAAIAAAfIAmAAIAAgfIALAAIAABKgAH+lEIgDgCIgBgDIABgDIADgDIADgBIADABIACADIABADIgBADIgCACIgDABIgDgBgABzlEIgCgCIgBgDIABgDIACgDIADgBIADABIADADIABADIgBADIgDACIgDABIgDgBg");
	this.shape_1.setTransform(-0.5,1.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.urText, new cjs.Rectangle(-74,-39.9,148,80), null);


(lib.t3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AkJBgQgTgIgLgLIAOgTQAMAKANAFQAPAFALAAQAOAAAJgEQAKgFAFgJQAFgIAAgMQAAgSgLgJQgNgKgWAAIgyAAIAAhlIBxAAIAAAYIhYAAIAAA3IAZAAQAjAAATAQQATAPAAAbQAAATgIAPQgJAOgPAIQgPAHgVAAQgTAAgSgGgABLBjIAuhGQgJAEgMAAQgTAAgOgJQgPgIgKgPQgIgNAAgVQAAgTAJgQQAKgRAPgHQAQgJAUAAQATAAARAIQAQAJAJAPQAJAQAAATQAAAPgEAMQgEAMgLASIgzBMgABShHQgKAFgGAKQgGAKAAANQAAANAGAKQAGAKAKAFQAKAFAMAAQAMAAAKgFQAKgFAGgKQAGgKAAgNQAAgNgGgKQgFgKgLgFQgJgGgNAAQgNAAgJAGgAhcBjIAuhGQgJAEgMAAQgTAAgPgJQgQgIgIgPQgJgOAAgUQAAgTAJgQQAKgQAQgIQAQgJAUAAQATAAARAIQAQAJAJAPQAIAQAAATQAAAOgEANQgEAOgLAQIgyBMgAhWhHQgKAFgFAKQgGAKAAANQAAAOAGAJQAFAKAKAFQAKAFANAAQAMAAAKgFQAJgFAHgKQAFgLAAgMQAAgNgFgKQgGgKgKgFQgJgGgNAAQgOAAgJAGgADuAjQgGgCgFgEQgFgFgDgGQgCgGAAgHQAAgGACgHIgHAAIAAgOIASAAIAOgKIggAAIAAgOIA0AAIAGgHQACgDAAgFQAAgHgFgEQgGgEgJAAIgHAAIgHADIgIAEIgIAGIAAgVQANgJAPAAIAQACQAHADAFAEQAFADADAHQADAFAAAJIgBAHIgDAHIALAAIAAAOIgaAAIgPAKIApAAIAAAOIg5AAIgEAHQgBACAAAEIABAGIAEAFIAGAEQAEABAFAAIAJgBIAJgEIAJgFIAHgHIAAAWQgIAGgIADQgJADgLAAQgGAAgIgDg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t3, new cjs.Rectangle(-29.5,-10.2,59.2,20.5), null);


(lib.t2_2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AHHBoQgRgKgLgSQgKgSAAgVQAAgWAKgSQALgSARgKQATgKAXAAQAXAAASAKQASALAJARQAKAQAAAYQAAAWgKARQgJARgSALQgSAKgXAAQgXAAgTgKgAHeACQgKAFgEAJQgEAJAAAMQAAALAEAJQAEAIAKAFQAIAFALAAQAKAAAJgFQAIgFAEgIQAFgJAAgLQAAgMgFgJQgEgJgIgFQgKgFgJAAQgLAAgIAFgACMBoQgRgLgLgRQgKgSAAgVQAAgWAKgSQALgRARgLQASgKAYAAQAXAAASAKQASALAKARQAKASAAAWQAAAVgKASQgKARgSALQgSAKgXAAQgYAAgSgKgACjACQgJAEgFAKQgEAJAAAMQAAALAEAJQAGAJAIAEQAIAFALAAQAKAAAJgFQAIgFAEgIQAGgJAAgLQAAgNgGgIQgEgJgIgFQgKgFgJAAQgKAAgJAFgAmDBoQgQgKgJgSQgJgSAAgWQAAgXAJgRQAJgRAQgKQAPgLAUABQAPAAAKAEQALAGAIAJIAAgQIArAAIAACVIgrAAIAAgRQgIAKgLAGQgKAEgPAAQgUABgPgLgAlqABQgHAEgFAKQgFAJAAAMQAAAMAFAJQAFAKAHAEQAJAFAKABQALgBAJgFQAIgEAFgKQAEgJAAgMQAAgMgEgJQgFgKgIgEQgJgEgLgBQgKABgJAEgAolBtQgQgHgJgKIAVgaQARAPAXAAQAPAAAIgEQAHgEAAgJQAAgIgGgDQgGgEgMAAIgcAAIAAgbIAYAAQAXAAAAgQQAAgHgFgDQgHgEgLAAQgXAAgRAOIgUgZQAKgKARgHQAQgFATAAQAfAAAPALQAQALAAATQAAAMgGAJQgEAIgLAEQAaAKAAAYQABAPgJAKQgIAKgQAHQgQAFgVAAQgVAAgRgFgAEjBvIAAiVIBvAAIAAAkIhGAAIAABxgAgyBvIAAiVIBGAAQAcAAAOALQAOAKAAATQAAALgFAIQgGAJgIADQAaAKAAAZQAAAMgHAJQgFAJgNAHQgOAFgQABgAgKBRIAbAAQAYAAAAgQQAAgIgGgEQgGgEgMAAIgbAAgAgKAWIAWAAQAMAAAGgEQAGgEgBgIQABgHgGgDQgGgEgMAAIgWAAgAiBBvIAAhbIg7BbIgnAAIAAiVIApAAIAABaIA6haIAnAAIAACVgAi4hDQgNgHgHgMQgJgNAAgOIAgAAQACAKAFAGQAHAGAKAAQALAAAGgGQAGgGACgKIAfAAQAAAOgIANQgHALgNAIQgMAGgQAAQgQAAgLgGg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t2_2, new cjs.Rectangle(-57.5,-11.4,115.1,22.9), null);


(lib.t2_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AsdCVIAAjeIAqAAIAAAQQAJgJALgGQAKgFAOAAQAVAAAPAKQAQAKAJASQAJASAAAWQAAAWgJASQgJASgQAKQgPAKgVAAQgOAAgKgFQgLgFgJgKIAABagArjghQgIAEgFAKQgEAJAAALQAAAKAEALQAFAJAIAFQAIAFALAAQALAAAIgFQAIgFAFgJQAEgLAAgKQAAgLgEgJQgFgKgIgEQgIgGgLAAQgLAAgIAGgAOABFQgTgLgJgSQgLgRAAgWQAAgVALgSQAJgSATgKQASgLAXAAQAXAAASALQATAKAJASQAKATAAAUQAAAWgKARQgJASgTALQgSAKgXAAQgXAAgSgKgAOWghQgIAFgFAKQgFAJAAAKQAAAMAFAIQAFAKAIAEQAJAFAKAAQALAAAIgFQAIgFAFgJQAFgIAAgMQAAgLgFgIQgFgKgIgFQgJgFgKAAQgKAAgJAFgAJFBFQgRgKgLgTQgKgRAAgWQAAgUAKgTQALgSARgKQATgLAWAAQAYAAASALQASALAJARQAKARAAAWQAAAXgKAQQgJASgSALQgSAKgYAAQgWAAgTgKgAJbghQgJAGgEAJQgEAJAAAKQAAAMAEAIQAEAJAJAFQAJAFAKAAQALAAAIgFQAJgFAEgJQAFgIAAgMQAAgKgFgJQgEgJgJgGQgJgFgKAAQgKAAgJAFgAhaBFQgSgLgKgSQgKgQAAgXQAAgWAKgRQAKgSASgKQATgLAXAAQAXAAASALQARALAKARQAKARAAAWQAAAXgKAQQgKASgRALQgSAKgXAAQgXAAgTgKgAhDghQgJAGgEAJQgFAKAAAJQAAALAFAJQAEAJAJAFQAIAFALAAQALAAAIgFQAJgFAEgJQAEgIAAgMQAAgKgEgJQgEgJgJgGQgJgFgKAAQgKAAgJAFgAmUBFQgSgLgJgSQgKgSAAgVQAAgUAJgTQAKgSASgKQASgLAZAAQAUAAASAHQARAIAKAMIgYAdQgIgIgKgEQgLgFgLAAQgMAAgIAFQgIAFgGAJQgEAJAAALQAAAMAEAJQAGAJAIAEQAIAFAMAAQAMAAAJgEQAKgFAJgHIAYAcQgKAMgRAIQgRAHgVAAQgYAAgTgKgApGBFQgTgLgJgSQgKgQAAgXQAAgWAKgRQAJgSATgKQASgLAXAAQAXAAASALQATAKAJASQAKARAAAWQAAAXgKAQQgJASgTALQgSAKgXAAQgXAAgSgKgAowghQgJAGgEAJQgFAIAAALQAAAMAFAIQAEAJAJAFQAJAFAKAAQALAAAIgFQAIgFAFgJQAFgIAAgMQAAgKgFgJQgFgKgIgFQgJgFgKAAQgKAAgJAFgALbBLIAAiUIBwAAIAAAkIhGAAIAABwgAHXBLIAAg3QgSAHgRAAQgRAAgNgHQgOgHgHgNQgHgLAAgTIAAgrIAqAAIAAAnQAAANAGAFQAHAGANAAQANAAAMgFIAAg6IAqAAIAACUgAEuBLIAAiUIArAAIAACUgADdBLIAAg7Ig1AAIAAA7IgrAAIAAiUIArAAIAAA3IA1AAIAAg3IAqAAIAACUgAjnBLIAAhwIgvAAIAAgkICHAAIAAAkIguAAIAABwgAtzBLIAAiuIhZAAIAACuIgrAAIAAjWICvAAIAADWgAE3hlQgFgDgEgGQgEgHAAgGQAAgGAEgGQADgFAGgEQAHgEAGAAQAFAAAHAEQAGAEADAFQAEAGAAAGQAAAGgEAHQgDAGgGADQgHAEgFAAQgGAAgHgEg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t2_1, new cjs.Rectangle(-101.6,-14.9,203.3,29.8), null);


(lib.t1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AMyBFQgMgKgHgSQgHgSABgWQgBgUAHgTQAHgSAMgJQANgKARAAQARAAANAKQAMAKAHARQAGASAAAVQAAAXgGARQgHASgMAKQgOAJgQAAQgRAAgNgJgAM9gxQgHAHgFANQgEANAAARQAAASAEAOQAFANAHAHQAIAGALAAQALAAAIgGQAHgHAEgNQAEgOABgSQgBgRgEgNQgEgNgHgHQgJgHgKAAQgLAAgIAHgALuBMIgGgFQgBgDAAgEQAAgDABgDIAGgFQADgCAEAAQADAAADACIAGAFQABADAAADQAAAEgBADIgGAFQgCACgEAAQgFAAgCgCgAB5BEQgQgJgLgSQgKgSAAgWQAAgVAKgRQALgSAQgKQASgKAVAAQAVAAASAKQARAKAKASQAJAQABAWQgBAXgJARQgKARgRAKQgSAKgVAAQgVAAgSgKgACEgwQgMAHgIANQgHAOAAAPQAAARAHANQAHANANAIQANAHAPAAQAPAAANgHQANgIAHgNQAHgMAAgSQAAgPgHgOQgIgNgMgHQgNgHgPAAQgQAAgMAHgAgSBJQgOgGgIgJIAKgOQAJAHAKAEQALAFAMAAQAJAAAIgDQAIgEADgFQAFgFgBgIQAAgJgEgFQgFgFgHgDIgUgHQgOgFgJgDQgIgEgIgIQgGgIAAgNQAAgNAGgJQAIgJAKgEQAMgFAOAAQAQAAAMAFQAMAEAKAJIgKAPQgIgHgKgEQgLgDgKAAQgOAAgIAFQgJAFABAKQgBAHAFAFQAEAEAGADIASAGIAZAKQAJADAIAJQAHAKAAAOQAAANgHAKQgHAKgLAFQgLAFgRAAQgQAAgOgFgArcBHQgLgHgIgMQgGgLAAgQQAAgQAGgKQAIgMALgHQAMgHAPAAQAQAAALAHQANAHAGAMQAHAKAAAQQAAAQgHALQgGAMgNAHQgLAHgQAAQgPAAgMgHgArRgEQgIAEgEAHQgEAIAAAKQAAAKAEAIQAEAIAIAEQAGAEAKAAQALAAAGgEQAIgEADgIQAFgIAAgKQAAgKgFgIQgDgHgIgEQgHgFgKAAQgJAAgHAFgAF+BMIAAiUIAUAAIAACUgAJ6BLIAAgPIAlgpIASgUQAHgHADgIQAEgGAAgIQgBgNgHgGQgJgHgOAAQgHAAgKACIgSAHIgHgQQALgGAKgDQALgDAMAAQANAAAMAFQALAFAGAJQAHAJAAAOQAAAMgFAJQgDAJgIAJQgHAKgMALIgbAfIBAAAIAAARgAG4BLIAAiTIAxAAQAYAAAQAJQASAJAKARQAKARAAAVQAAAXgKARQgKARgRAJQgRAIgYAAgAHNA5IAbAAQASAAAMgGQAMgFAIgNQAIgNAAgTQAAgQgIgNQgGgMgOgHQgPgHgPAAIgbAAgAEJBLIAAiTIAUAAIAACBIBFAAIAAASgAiCBLIAAiYIATAAIAACYgAi1BLIAAhkIAVAAIAABkgAjmBLIAAiYIATAAIAACYgAlHBLIAAhJIg1BJIgTAAIAAhkIAUAAIAABJIA0hJIATAAIAABkgAm/BLIAAhJIg0BJIgTAAIAAhkIATAAIAABJIA1hJIATAAIAABkgAp1BLIAAhkIAuAAQARAAALAHQAJAIAAALQAAAIgEAGQgDAFgIADQALAEAEAFQAFAGAAAJQAAAJgEAGQgFAHgIADQgHADgNAAgAphA9IAbAAQAMAAAEgEQAFgEAAgHQAAgPgVAAIgbAAgAphASIAWAAQALAAAFgEQAFgEABgHQAAgNgWAAIgWAAgAslBLIAAhDIhNAAIAABDIgUAAIAAiTIAUAAIAAA+IBNAAIAAg+IAUAAIAACTgAlyguQgHgEgFgHQgFgHgBgKIAQAAQABAIAGAEQAEAFAIAAQAIAAAGgFQAFgFAAgHIAQAAQAAAJgGAIQgFAHgHAEQgIAEgJAAQgIAAgJgEgAixgxIgFgFQgBgDgBgEIACgGIAFgFIAGgCIAHACQADACACADQACADAAADQAAAEgCADIgFAFQgDABgEAAQgDAAgDgBg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1, new cjs.Rectangle(-90.3,-7.8,180.6,15.7), null);


(lib.shadow_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.shadow();
	this.instance.parent = this;
	this.instance.setTransform(-109,-66);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.shadow_1, new cjs.Rectangle(-109,-66,218,132), null);


(lib.lil_logo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAMHTQgEAAgDgDQgCgDAAgEIAAh1QAAgEACgDQADgDAEAAQAFAAADADQACADAAAEIAABrIBEAAQAEAAADADQACADAAAEQAAAEgCADQgDADgEAAgAkFHKQgNgIgEgNQgCgEACgEQACgEAEgBQAEgCADACQAEACACAEQACAHAIAFQAHAFAKAAQAMAAAIgHQAIgGAAgKQAAgGgDgEQgHgIgSgCQgTgCgLgKQgMgLAAgPQAAgPANgLQAMgKARAAQANAAALAHQALAHAEALQACAEgCADQgCAEgEACQgEABgDgCQgEgCgCgDQgCgGgFgDQgGgDgHAAQgJAAgGAEQgGAFAAAHQAAAHAGAFQAGAFALABQAbADALAOQAIAJABAOQAAASgPAMQgOANgUAAQgQAAgNgJgAC4HSQgEAAgDgDQgDgCAAgFIAAh0QAAgEADgDQADgDAEAAIAcAAQAcAAAUAUQAUAUAAAcQAAAcgUAUQgUAUgcAAgADCG+IASAAQAUAAAOgOQAOgOAAgUQAAgUgOgOQgOgOgUAAIgSAAgACAHPQgDgCAAgFIAAh0QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAB0QAAAFgDACQgDADgEAAQgEAAgDgDgAiLG+QgUgUAAgcQAAgcAUgUQAUgUAcAAQAcAAAUAUQAVAUAAAcQAAAcgUAUQgUAUgdAAQgcAAgUgUgAh9FsQgOAOAAAUQAAAUAOAOQAOAOAUAAQAUAAAOgOQAPgOAAgUQAAgUgOgOQgPgPgUAAQgUAAgOAPgACxDjQgPgPAAgVIAApeQAAgVAPgPQAPgPAVAAQAVAAAOAPQAPAPAAAVIAAJeQAAAVgPAPQgOAPgVAAQgVAAgPgPgAgiDjQgPgPAAgVIAAmUQAAgVAPgPQAOgOAUAAQAVAAAPAOQAPAPAAAVIAAGUQAAAVgPAPQgPAPgVAAQgUAAgOgPgAj3DjQgPgPAAgVIAApeQAAgVAPgPQAPgPAVAAQAVAAAOAPQAPAPAAAVIAAJeQAAAVgPAPQgOAPgVAAQgVAAgPgPgAgmlFQgQgRAAgXQAAgXAQgQQAQgQAWAAQAXAAARAQQAQAQAAAXQAAAXgQARQgRAQgXAAQgWAAgQgQg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.lil_logo, new cjs.Rectangle(-28,-46.6,56,93.4), null);


(lib.ligth = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["rgba(255,255,255,0.149)","rgba(255,255,255,0)"],[0,1],0,0,0,0,0,201.7).s().p("A2GWHQpJpLAAs8QAAs7JJpLQJKpJM8AAQM8AAJKJJQJKJLAAM7QAAM8pKJLQpKJJs8AAQs8AApKpJg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.ligth, new cjs.Rectangle(-200,-200,400,400), null);


(lib.iqos_logo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhAB1IgUgUIhBAAQgQAAgKgCQgNgDgIgHQgLgKAAgUIAAg4QAAgEADgCQACgCAEAAIBJAAQAPAAALACQANADAIAHQAKAKABATIAAA5IAQAQQACACAAAEQgBADgCADQgDADgDAAQgDAAgDgDgAi9A3QABANAGAHIACABQAHAGAOAAIBJAAIAAgyQgBgNgGgHIgBgBQgHgFgOgBIhKAAgAChBgQgUgBgKgFQgGgFgCgJIAAgBQAAgDACgCQADgCADAAQAEAAADABIACAEIABABQACAEAFACIAMABIAoAAQAVAAAHgDQAFgDAAgKIAAAAQAAgIgEgDQgEgEgPAAIg0AAQgTAAgHgHQgIgGAAgPIAAgGQAAgNAKgFQALgHAfAAIAaAAQAXAAALAGQAJADABAKIAAABQAAADgCACQgDACgEAAQgEAAgCgBQAAgBgBAAQAAgBgBAAQAAgBAAAAQAAgBAAAAIgBgCQgDgEgGgBIgSgBIgdAAQgTAAgFACQgGADAAAIIAAAEQAAAHAEADQAEADAMAAIAtAAQAWAAAJAFQAMAGABAUIAAAAQAAAUgRAGQgJAEgWAAgAAPBgQgZAAgNgHQgSgKAAgZIAAgXQAAgZASgJQANgHAZAAIAZAAQAaAAANAHQASAJAAAZIAAAXQAAAZgSAKQgNAHgaAAgAgNAJQgKAHAAAQIAAAVQAAAQAKAHQAHAFAQAAIAjAAQARAAAHgFQAKgHAAgQIAAgVQAAgQgKgHQgHgFgRAAIgjAAQgQAAgHAFgAj8BeQgCgCAAgEIAAhZQAAgEACgDQADgCAEAAQAEAAADACQABADAAAEIAABZQAAAEgBACQgDACgEAAQgEAAgDgCgAAlhXQgGgFAAgIQAAgIAGgFQAFgGAIAAQAFAAAFADQAEACADAEIgGAEQgEgGgHAAQgEAAgEADQgEAEABAFQgBAFAEADQAEAEAEAAQAHAAAEgGIAGAEQgDAEgEACQgFADgFAAQgIAAgFgGgAgHhWQgEgEgBgHIAAgVIAIAAIAAAWQAAAEACACQACACADAAQAEAAABgCQADgCAAgEIAAgWIAIAAIAAAVQAAAHgFAEQgEAFgHAAQgGAAgEgFgAhmhXQgGgFAAgIQAAgIAGgFQAGgGAIAAQAIAAAGAGQAFAFABAIQgBAIgFAFQgGAGgIAAQgJAAgFgGgAhghtQgEAEAAAFQAAAFAEADQADAEAFAAQAFAAAEgEQADgDAAgFQAAgFgDgEQgEgDgFAAQgFAAgDADgAjKhRIgVgXIAAAWIgHAAIAAglIACAAIAVAWIAAgVIAIAAIAAAlgADrhSIAAgOIgNgWIAIAAIAJAOIAIgOIAIAAIgNAWIAAAOgAC7hSIAAgkIAOAAQAEAAAEADQADADAAAEQAAAEgCACQAGADAAAGQAAAFgEADQgDADgFAAgADDhYIAIAAQABAAABAAQAAAAABgBQAAAAABAAQAAAAABgBIABgDIgBgDIgFgBIgIAAgADDhoIAFAAIADgBQABAAAAAAQAAgBABAAQAAAAAAgBQAAAAAAgBIgCgDIgDgBIgFAAgAB1hSIAAgkIAMAAQAJAAAFAFQAGAFAAAIQAAAIgGAFQgFAFgJAAgAB8hZIAFAAQAGAAADgDQAEgDgBgFQABgGgEgCQgDgDgGAAIgFAAgABOhSIAAgkIAZAAIAAAHIgRAAIAAAHIANAAIAAAGIgNAAIAAAJIASAAIAAAHgAg4hSIAAgkIAMAAQAJAAAFAFQAGAFAAAIQAAAIgGAFQgFAFgJAAgAgxhZIAFAAQAFAAAEgDQADgDABgFQgBgGgDgCQgEgDgFAAIgFAAgAh8hSIgJgNIgGAAIAAANIgIAAIAAgkIAPAAQAFAAAEADQADADAAAFQABAEgCADIgFAEIALAOgAiLhlIAHAAQAAAAABAAQAAAAABgBQAAAAABAAQAAAAAAgBQABAAAAgBQAAAAABAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBQgBAAAAAAQAAgBgBAAQAAgBAAAAQgBAAAAAAQgBgBAAAAQgBAAAAAAIgHAAgAiwhSIAAgdIgMAAIAAgHIAfAAIAAAHIgMAAIAAAdgAj9hSIAAgkIAIAAIAAAkg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.iqos_logo, new cjs.Rectangle(-25.5,-12,51,24), null);


(lib.img2_mc = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.img1();
	this.instance.parent = this;
	this.instance.setTransform(-119,-120);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.img2_mc, new cjs.Rectangle(-119,-120,238,240), null);


(lib.img1_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.img1();
	this.instance.parent = this;
	this.instance.setTransform(-119,-120);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.img1_1, new cjs.Rectangle(-119,-120,238,240), null);


(lib.dev_blur_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.dev_blur();
	this.instance.parent = this;
	this.instance.setTransform(-65,-149);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.dev_blur_1, new cjs.Rectangle(-65,-149,130,298), null);


(lib.dev_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.dev();
	this.instance.parent = this;
	this.instance.setTransform(-65,-149);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.dev_1, new cjs.Rectangle(-65,-149,130,298), null);


(lib.bg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.bgImg();
	this.instance.parent = this;
	this.instance.setTransform(-150,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bg, new cjs.Rectangle(-150,-300,300,600), null);


(lib.img2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.img2_mc();
	this.instance.parent = this;
	this.instance.filters = [new cjs.BlurFilter(30, 30, 1)];
	this.instance.cache(-121,-122,242,244);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.img2, new cjs.Rectangle(-134,-135,272,274), null);


(lib.banner = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// t3
	this.instance = new lib.t3();
	this.instance.parent = this;
	this.instance.setTransform(75.9,-114.4);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(45).to({_off:false},0).to({x:95.9,alpha:1},10,cjs.Ease.get(1)).wait(64).to({alpha:0},10).wait(1));

	// urText
	this.instance_1 = new lib.urText();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-42.6,231.1);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({alpha:1},10).wait(109).to({alpha:0},10).wait(1));

	// t2_2
	this.instance_2 = new lib.t2_2();
	this.instance_2.parent = this;
	this.instance_2.setTransform(-90.4,-181.3);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(35).to({_off:false},0).to({x:-59.4,alpha:1},10,cjs.Ease.get(1)).wait(74).to({alpha:0},10).wait(1));

	// t2_1
	this.instance_3 = new lib.t2_1();
	this.instance_3.parent = this;
	this.instance_3.setTransform(-46.4,-214);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(30).to({_off:false},0).to({x:-13.6,alpha:1},10,cjs.Ease.get(1)).wait(79).to({alpha:0},10).wait(1));

	// t1
	this.instance_4 = new lib.t1();
	this.instance_4.parent = this;
	this.instance_4.setTransform(-57.7,-251.9);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(25).to({_off:false},0).to({x:-24.4,alpha:1},10,cjs.Ease.get(1)).wait(84).to({alpha:0},10).wait(1));

	// lil_logo
	this.instance_5 = new lib.lil_logo();
	this.instance_5.parent = this;
	this.instance_5.setTransform(93.4,202.4,0.58,0.58,0,0,0,-0.1,0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(130));

	// logo
	this.instance_6 = new lib.iqos_logo();
	this.instance_6.parent = this;
	this.instance_6.setTransform(93.8,266.8,1,1,0,0,0,-0.9,8.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(130));

	// dev
	this.instance_7 = new lib.dev_blur_1();
	this.instance_7.parent = this;
	this.instance_7.setTransform(-291.3,228.9,1,1,45);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(1).to({rotation:41.5,x:-270.3,y:212.8},0).wait(1).to({rotation:38.1,x:-250.3,y:197.3},0).wait(1).to({rotation:34.8,x:-231,y:182.4},0).wait(1).to({rotation:31.7,x:-212.6,y:168.3},0).wait(1).to({rotation:28.8,x:-195.1,y:154.8},0).wait(1).to({rotation:26,x:-178.4,y:141.9},0).wait(1).to({rotation:23.3,x:-162.6,y:129.7},0).wait(1).to({rotation:20.8,x:-147.6,y:118.2},0).wait(1).to({rotation:18.4,x:-133.5,y:107.3},0).wait(1).to({rotation:16.2,x:-120.3,y:97.1},0).wait(1).to({rotation:14.1,x:-107.9,y:87.6},0).wait(1).to({rotation:12.1,x:-96.3,y:78.7},0).wait(1).to({rotation:10.3,x:-85.6,y:70.4},0).wait(1).to({rotation:8.7,x:-75.8,y:62.9},0).wait(1).to({rotation:7.1,x:-66.8,y:55.9},0).wait(1).to({rotation:5.8,x:-58.7,y:49.7},0).wait(1).to({rotation:4.5,x:-51.4,y:44.1},0).wait(1).to({rotation:3.5,x:-45,y:39.1},0).wait(1).to({regX:0.1,regY:0.1,rotation:2.5,x:-39.3,y:34.9},0).wait(1).to({regX:0,regY:0,rotation:1.8,x:-34.7,y:31.2,alpha:0.694},0).wait(1).to({rotation:1.1,x:-30.9,y:28.2,alpha:0.444},0).wait(1).to({rotation:0.6,x:-27.9,y:25.9,alpha:0.25},0).wait(1).to({rotation:0.3,x:-25.8,y:24.2,alpha:0.111},0).wait(1).to({rotation:0.1,x:-24.5,y:23.2,alpha:0.028},0).wait(1).to({rotation:0,x:-24,y:23,alpha:0},0).to({_off:true},1).wait(104));

	// dev
	this.instance_8 = new lib.dev_1();
	this.instance_8.parent = this;
	this.instance_8.setTransform(-291.3,228.9,1,1,45);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).to({rotation:0,x:-24,y:23},25,cjs.Ease.get(1)).wait(94).to({alpha:0},10).wait(1));

	// img1
	this.instance_9 = new lib.img2();
	this.instance_9.parent = this;
	this.instance_9.setTransform(149.3,-153.9);
	this.instance_9.alpha = 0;
	this.instance_9.compositeOperation = "lighter";
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(19).to({_off:false},0).to({alpha:0.5},6).wait(94).to({alpha:0},10).wait(1));

	// img1
	this.instance_10 = new lib.img2();
	this.instance_10.parent = this;
	this.instance_10.setTransform(-21,41);
	this.instance_10.alpha = 0;
	this.instance_10.compositeOperation = "lighter";
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(19).to({_off:false},0).to({alpha:0.5},6).wait(94).to({alpha:0},10).wait(1));

	// img1
	this.instance_11 = new lib.img1_1();
	this.instance_11.parent = this;
	this.instance_11.setTransform(149.3,-153.9);
	this.instance_11.alpha = 0.102;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).to({alpha:1},25).wait(94).to({alpha:0.102},10).wait(1));

	// img1
	this.instance_12 = new lib.img1_1();
	this.instance_12.parent = this;
	this.instance_12.setTransform(-21,41);
	this.instance_12.alpha = 0.102;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).to({alpha:1},25).wait(94).to({alpha:0.102},10).wait(1));

	// Слой_8
	this.instance_13 = new lib.ligth();
	this.instance_13.parent = this;
	this.instance_13.alpha = 0;
	this.instance_13.compositeOperation = "lighter";
	this.instance_13._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(19).to({_off:false},0).to({alpha:1},6).wait(94).to({alpha:0},10).wait(1));

	// shadow
	this.instance_14 = new lib.shadow_1();
	this.instance_14.parent = this;
	this.instance_14.setTransform(-311,308,1,1,22.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_14).to({rotation:0,x:40,y:117},25,cjs.Ease.cubicInOut).wait(94).to({alpha:0},10).wait(1));

	// bg
	this.instance_15 = new lib.bg();
	this.instance_15.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_15).wait(130));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-442.6,-300,710.9,710.3);


// stage content:
(lib._300x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// cover
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#666666").ss(2,2,0,3).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// banner
	this.instance = new lib.banner();
	this.instance.parent = this;
	this.instance.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-142.6,299,710.9,711.3);
// library properties:
lib.properties = {
	id: '0A6E3F5DF6B342F4AF907DBE848CDF8D',
	width: 300,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/bgImg.jpg", id:"bgImg"},
		{src:"images/dev.png", id:"dev"},
		{src:"images/dev_blur.png", id:"dev_blur"},
		{src:"images/img1.png", id:"img1"},
		{src:"images/shadow.png", id:"shadow"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['0A6E3F5DF6B342F4AF907DBE848CDF8D'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;