(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.b1 = function() {
	this.initialize(img.b1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1022,244);


(lib.b2 = function() {
	this.initialize(img.b2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1109,201);


(lib.g1 = function() {
	this.initialize(img.g1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1022,244);


(lib.g2 = function() {
	this.initialize(img.g2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1109,201);


(lib.glitch1 = function() {
	this.initialize(img.glitch1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,582,519);


(lib.glitch2 = function() {
	this.initialize(img.glitch2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1174,782);


(lib.glitch3 = function() {
	this.initialize(img.glitch3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,582,658);


(lib.glitch4 = function() {
	this.initialize(img.glitch4);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,585,585);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.x = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.txt.text = oddsX;
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(6));

	// Слой_2
	this.txt = new cjs.Text("", "bold 20px 'Arial'", "#FFFFFF");
	this.txt.name = "txt";
	this.txt.textAlign = "center";
	this.txt.lineHeight = 22;
	this.txt.lineWidth = 52;
	this.txt.parent = this;
	this.txt.setTransform(0,-8);

	this.timeline.addTween(cjs.Tween.get(this.txt).wait(6));

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00BEF5").s().p("AkuAhIhKgMICikAIIDAuIhXhXICjBbIgtCsIhoAOICqAMIANCuIs1Bag");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(6));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-41.1,-27.7,82.3,55.4);


(lib.w2Txt = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AEDCvIAegQQAFAMAMAAQAJAAAAgGQAAgEgSgEQghgIAAgZQAAgQAMgJQANgKARAAQAfAAAMAZIgdANQgFgJgIAAQgIAAAAAFQAAAEASAEQAiAHAAAaQAAATgOAIQgNAIgSAAQgjAAgMgYgABQC3QgQgQAAgXQAAgWAQgRQARgQAWAAQAYAAAQAQQAQAQAAAXQAAAYgQAPQgQAQgYAAQgXAAgQgQgABpCBQgGAGAAAJQAAAKAGAGQAFAGAJAAQAKAAAFgGQAGgGAAgKQAAgJgGgGQgFgGgKAAQgJAAgFAGgAjYC8QgLgMAAgVIAAg/IAiAAIAAA6QAAARAQAAQARAAAAgTIAAg4IAjAAIAABoIgjAAIAAgKQgJANgUAAQgRAAgKgLgAleCqIAggSQAGALANAAQAQAAAAgPIAAhhIAlAAIAABiQAAAYgOANQgPANgYAAQgkAAgPgdgAC+DEIAAhoIAjAAIAAAUQADgKAJgGQAIgGALAAIAAAmQgMgBgKAGQgJAGAAAOIAAArgAAODEIAAhoIAjAAIAABogAgmDEIAAg6QAAgQgQAAQgRAAAAATIAAA3IgiAAIAAhoIAiAAIAAALQAKgOATAAQASAAAKAMQALAMAAAVIAAA+gAARBOQgFgGAAgIQAAgJAFgFQAHgGAIAAQAIAAAGAGQAGAFAAAJQAAAIgGAGQgGAGgIAAQgIAAgHgGgACEhBQgOgRAAgXQAAgWAOgRQAOgPAVAAQATAAALAMIAAgKIAjAAIAABpIgjAAIAAgKQgLAMgTAAQgVAAgOgPgACfh5QgGAGAAAKQAAALAGAGQAGAGAKAAQAKAAAGgGQAGgGAAgLQAAgKgGgGQgGgGgKAAQgKAAgGAGgAAbhBQgPgQAAgYQAAgXAPgQQARgPAXAAQAhAAAOAaIgdARQgGgKgMAAQgJAAgGAGQgGAGAAAJQAAAKAGAGQAGAGAJAAQANAAAFgLIAdARQgOAbghAAQgXAAgRgPgAhdhBQgQgQAAgYQAAgWAQgQQAQgQAYAAQAXAAAQAQQAPAQAAAWQAAAYgPAQQgQAPgXAAQgXAAgRgPgAhEh4QgGAGAAAJQAAAKAGAGQAGAGAJAAQAJAAAGgGQAGgGAAgKQAAgJgGgGQgGgGgJAAQgJAAgGAGgAjmg0IAAiSIA6AAQAWAAANALQANALAAATQAAATgOAKQASALAAAWQAAAUgNALQgNAMgWAAgAjBhWIAXAAQAGAAAEgDQADgEAAgFQAAgMgNAAIgXAAgAjBiOIAUAAQAFAAADgDQADgDAAgFQAAgMgLAAIgUAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.w2Txt, new cjs.Rectangle(-35.1,-19.9,70.2,39.8), null);


(lib.w2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.txt.text = oddsW2;
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(6));

	// Слой_2
	this.txt = new cjs.Text("", "bold 20px 'Arial'", "#FFFFFF");
	this.txt.name = "txt";
	this.txt.textAlign = "center";
	this.txt.lineHeight = 22;
	this.txt.lineWidth = 52;
	this.txt.parent = this;
	this.txt.setTransform(3.5,-8);

	this.timeline.addTween(cjs.Tween.get(this.txt).wait(6));

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00BEF5").s().p("AmnCLIBGiaIBwAAIg1gvIBXh6IIkAPIhOhJIChBLIh7Gag");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(6));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-42.3,-24.3,84.7,48.7);


(lib.w1Txt = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ADdC4QgQgQAAgXQAAgXAPgRQAQgPAYAAQAYAAAPAPQAPAQAAAXQAAAHgBAGIhIAAQAFANASAAQALAAAIgHIAZARQgPATgeAAQgaAAgQgPgAEYCFQgDgOgQAAQgQAAgFAOIAoAAIAAAAgAgIC4QgQgQAAgXQAAgYAQgQQAPgPAYAAQAhAAAOAaIgdARQgGgKgMAAQgJAAgGAGQgGAGAAAKQAAAJAGAGQAGAGAJAAQANAAAFgLIAdARQgOAbghAAQgYAAgPgPgAj6C8QgLgMAAgVIAAg/IAjAAIAAA6QAAARAPAAQARAAAAgTIAAg4IAjAAIAABpIgjAAIAAgLQgIANgUAAQgSAAgKgLgAGMDFIAAg6QAAgRgQAAQgRAAAAATIAAA4IgiAAIAAhpIAiAAIAAALQAKgNATAAQASAAAKALQALAMAAAVIAAA/gACdDFIAAg6QAAgRgQAAQgRAAAAATIAAA4IgjAAIAAiSIAjAAIAAA0QAJgNAUAAQARAAAKALQALAMAAAVIAAA/gAhIDFIAAg6QAAgRgPAAQgRAAAAATIAAA4IgjAAIAAhpIAjAAIAAALQAIgNAVAAQARAAAKALQALAMAAAVIAAA/gAk+DFIAAhPIgkA7IgDAAIgkg7IAABPIglAAIAAiSIAlAAIAlA+IAmg+IAlAAIAACSgAhHgLIAAggQALAAAGgDQAFgDAEgHIgqhkIAnAAIAVA8IAQg8IAmAAIgjBmQgIAYgQAKQgNAJgVAAIgFAAgAArhBQgQgQAAgXQAAgXAPgQQAQgQAYAAQAYAAAPAPQAPAQAAAXIgBANIhIAAQAFANASAAQALAAAIgHIAZARQgPAUgeAAQgaAAgQgQgABmh0QgEgOgPAAQgQAAgFAOIAoAAIAAAAgAjEhBQgOgQAAgXQAAgYAOgPQANgQAWAAQATAAALAMIAAgJIAiAAIAABoIgiAAIAAgKQgLANgTAAQgVAAgOgQgAiph5QgGAGAAALQAAAKAGAGQAGAGAKAAQAKAAAGgGQAGgGAAgKQAAgLgGgGQgHgGgJAAQgKAAgGAGgAEpg0IAAg6QAAgRgQAAQgRAAAAATIAAA4IgiAAIAAhoIAiAAIAAAKQAKgNATAAQASAAAKALQALAMAAAVIAAA/gACXg0IAAhoIAiAAIAAATQADgKAJgGQAJgFALAAIAAAmQgMgCgKAGQgKAGAAAPIAAArgAlLg0IAAiSIA6AAQAWAAANALQANALAAATQAAATgOAKQASAMAAAVQAAAUgNALQgOAMgVAAgAkmhWIAXAAQAGAAAEgDQADgDAAgGQAAgFgDgEQgEgDgGAAIgXAAgAkmiOIAUAAQALAAAAgLQAAgMgLAAIgUAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.w1Txt, new cjs.Rectangle(-43,-19.9,86.2,39.8), null);


(lib.w1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.txt.text = oddsW1;
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(6));

	// Слой_2
	this.txt = new cjs.Text("", "bold 20px 'Arial'", "#FFFFFF");
	this.txt.name = "txt";
	this.txt.textAlign = "center";
	this.txt.lineHeight = 22;
	this.txt.lineWidth = 52;
	this.txt.parent = this;
	this.txt.setTransform(1.3,-8);

	this.timeline.addTween(cjs.Tween.get(this.txt).wait(6));

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00BEF5").s().p("AlBBFIAygbIh+gRIgajAIChhLIhPBJIJggPICdFDIrVBog");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(6));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-42.5,-24.3,84.9,53.7);


(lib.vs = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ag1BjQgXgOgJgZIAwgcQAMAdAeAAQAZAAAAgPQAAgKgOgFIgbgJQhBgTAAgwQAAgfAWgSQAWgTAgAAQAbAAAVANQAVANALAYIguAbQgLgYgXAAQgUAAAAAOQAAAIAIAFQAIAFAVAGIAZAJQAJAEANAIQAWAOAAAgQAAAggWATQgXASgmAAQghAAgXgPg");
	this.shape.setTransform(10.5,0);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AggBuIhHjbIA9AAIAqCWIAriWIA9AAIhHDbg");
	this.shape_1.setTransform(-8.8,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.vs, new cjs.Rectangle(-19.1,-11.4,38.3,22.8), null);


(lib.txt2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#39E55A").s().p("AjdCaIAMhxIBCAAIgeBxgAFeBJQgbgkAAg6QAAg8AbgkQAcgkAyAAQAxAAAbAkQAcAkAAA8QAAA6gcAkQgbAkgxAAQgyAAgcgkgAGEgVQAABDAoAAQAoAAAAhDQAAhFgoAAQgoAAAABFgAB8BJQgcgjAAg7QAAg9AcgjQAbgkAyAAQAxAAAbAkQAcAkAAA8QAAA6gcAkQgbAkgxAAQgyAAgbgkgAChgVQAABDAoAAQAoAAAAhDQAAhFgoAAQgoAAAABFgAhmBJQgcgjAAg7QAAg9AcgjQAbgkAyAAQAwAAAbAkQAcAkAAA8QAAA6gcAkQgbAkgwAAQgyAAgbgkgAhBgVQAABDAoAAQAnAAAAhDQAAhFgnAAQgoAAAABFgAlFBoIAAi4IgsALIgPg2IBEgYIA4AAIAAD7gAnYBoIAAi4IgsALIgPg2IBEgYIA3AAIAAD7g");
	this.shape.setTransform(-5.5,30.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AK0GIIAlgUQAJAVAYAAQATABAAgLQAAgIgLgEIgVgHQgygOAAgnQAAgXARgOQAQgOAZgBQAtABASAlIgkAWQgIgTgSAAQgQAAAAALQAAAGAGADQAGAFARAFIAUAGQAGACAKAHQARALAAAaQAAAYgRAOQgRAPgdAAQg2AAgPgrgAsgGZQgZgaAAgkQAAglAZgZQAZgaAmAAQAlAAAZAaQAaAZAAAlQAAAkgaAaQgZAaglAAQglAAgagagAsCE6QgNANAAAUQAAAUANANQAOANATgBQATABANgNQANgNAAgUQAAgUgNgNQgNgNgTAAQgTAAgOANgANIGvIAAioIBEAAQAjAAAYAYQAXAZAAAjQAAAkgXAYQgYAYgjAAgAN0GGIAYAAQASAAALgMQALgMAAgTQAAgSgLgNQgLgMgSAAIgYAAgAKCGvIgdg3IgQAAIAAA3IgrAAIAAioIBDAAQAaAAARAQQASAQAAAaQAAAPgIAMQgIAOgNAGIAjA/gAJVFUIAYAAQAIABAFgGQAFgFAAgJQAAgIgFgFQgFgGgIAAIgYAAgAvdGvIAAioIBFAAQAjAAAXAYQAXAZAAAjQAAAkgXAYQgXAYgjAAgAuxGGIAZAAQARAAALgMQALgLAAgUQAAgTgLgMQgLgMgRAAIgZAAgAQnAmQgZgaAAgkQAAglAZgZQAYgZAnAAQAWAAAUAKQATALALASIglAWQgKgUgZABQgVAAgMAMQgMANAAAUQAAAVAMALQAMANAVAAQAZgBAKgTIAlAWQgLASgTALQgTAKgXAAQgmAAgZgYgALfAzQgRgLgIgTIAlgVQAJAWAYAAQAUgBAAgKQAAgIgLgEIgVgGQgygPAAglQAAgXAQgQQAQgOAaABQAtgBARAmIgkAWQgHgTgTAAQgPAAAAALQAAAGAGAEQAFADARAGQAJACALAEQAHACAJAHQASAMAAAYQAAAZgSAOQgRANgdAAQgaAAgSgLgAIrAlQgZgZAAgkQAAglAZgZQAZgZAmAAQAlAAAZAZQAaAZAAAlQAAAkgaAZQgZAZglAAQglAAgagZgAJJg5QgNANAAAUQAAAUANALQANAOAUAAQASAAAOgOQANgLAAgUQAAgUgNgNQgNgMgTAAQgUAAgNAMgADDAlQgZgZAAgkQAAglAZgZQAZgZAmAAQAlAAAZAZQAaAZAAAlQAAAjgaAaQgZAZglAAQglAAgagZgADig5QgNANAAAUQAAAUANALQANAOATAAQATAAANgOQANgLAAgUQAAgUgNgNQgMgMgUAAQgUAAgMAMgAkdAlQgZgZAAgkQAAglAZgZQAagZAlAAQAmAAAZAZQAZAZAAAlQAAAkgZAZQgaAZglAAQgkAAgbgZgAj+g5QgNANAAAUQAAAUANALQANAOATAAQATAAAOgOQANgLAAgUQAAgUgNgNQgNgMgUAAQgUAAgMAMgAqNAzQgRgLgHgTIAkgVQAKAWAXAAQAUgBAAgKQAAgIgLgEIgVgGQgygPAAglQAAgXAQgQQARgOAZABQAtgBASAmIgkAWQgJgTgSAAQgPAAAAALQAAAGAGAEQAGADARAGQAIACALAEQAIADAJAGQARAMAAAYQAAAYgRAPQgSANgdAAQgaAAgSgLgAsoAvQgSgRAAgaIAAhwIArAAIAABsQAAAVAXAAQAYAAAAgVIAAhsIArAAIAABwQAAAZgTASQgTAPgdAAQgdAAgTgPgAyFAlQgagZAAgkQAAglAagZQAZgZAlAAQAmAAAZAZQAZAZAAAlQAAAkgZAZQgaAZglAAQglAAgZgZgAxng5QgNANAAAUQAAAUANALQANAOATAAQATAAAOgOQANgLAAgUQAAgUgNgNQgNgMgUAAQgUAAgMAMgAS+A7IAAinIBrAAIAAAoIhAAAIAAAXIA6AAIAAAoIg6AAIAAAXIBBAAIAAApgAPPA7IAAinIArAAIAACngANbA7IAAinIArAAIAAB9IA5AAIAAAqgAFuA7IAAinIBEAAQAjAAAYAYQAXAYAAAkQAAAjgXAYQgYAYgjAAgAGaARIAYAAQASAAALgLQALgMAAgSQAAgSgLgNQgLgLgSAAIgYAAgAB1A7Igdg2IgPAAIAAA2IgrAAIAAinIBDAAQAZAAASAQQASAQAAAaQAAAPgIANQgIAMgNAHIAjA+gABJgfIAYAAQAIAAAFgFQAFgFAAgIQAAgJgFgGQgFgEgIAAIgYAAgAhyA7IAAinIBDAAQAZAAAPANQAOANAAAWQAAAVgPAMQAVANAAAXQAAAWgPAOQgPAOgaAAgAhHAVIAbAAQAGAAAFgFQAEgDAAgHQAAgNgPAAIgbAAgAhHgsIAWAAQAOAAAAgNQAAgMgOAAIgWAAgAnaA7IAAinIBFAAQAiAAAYAYQAYAYAAAkQAAAjgYAYQgYAYgiAAgAmtARIAYAAQARAAAMgLQALgMAAgSQAAgSgLgNQgLgLgSAAIgYAAgAt0A7Ig8hTIAABTIgrAAIAAinIAiAAIA7BVIAAhVIArAAIAACngA0pA7IAAinIBCAAQAaAAAPANQAPANAAAWQAAAUgQANQAVANAAAXQAAAXgPANQgPAOgaAAgAz+AVIAbAAQAGAAAEgFQAEgDAAgHQAAgGgEgDQgEgEgGAAIgbAAgAz+gsIAWAAQAOAAAAgNQAAgFgEgEQgEgDgGAAIgWAAgALzh5IgaglIAkAAIAKANIAJgNIAkAAIgZAlgAJ8jsIAigTQAIANARAAQALABAHgGQAGgGAAgKIAAgLQgMAOgVAAQgZABgQgTQgRgQAAgaQAAgaARgRQAQgSAZAAQAVgBAMAQIAAgMIAoAAIAABzQAAAcgUAQQgSAMgaAAQgrAAgQgdgAKjlSQgHAGAAAMQAAAJAHAJQAIAGALAAQALAAAHgGQAHgJAAgJQAAgMgHgGQgHgIgLABQgLgBgIAIgAjJjSIAAioIAoAAIAAALQANgOAVAAQAYAAAQASQAQASAAAbQAAAagQATQgQASgYAAQgWAAgMgOIAAA7gAialRQgHAHAAAMQAAALAHAIQAHAHALAAQALAAAHgHQAHgIAAgLQAAgMgHgHQgGgHgMgBQgLABgHAHgAwejSIAAioIAoAAIAAALQANgOAVAAQAYAAAQASQAQASAAAbQAAAagQATQgQASgYAAQgWAAgMgOIAAA7gAvvlRQgHAHAAAMQAAALAHAIQAHAHALAAQALAAAHgHQAHgIAAgLQAAgMgHgHQgGgHgMgBQgLABgHAHgAyokPQgSgRAAgaIAAhwIArAAIAABsQAAAWAXgBQAYABAAgWIAAhsIArAAIAABwQAAAbgTAQQgSAQgeAAQgdAAgTgQgAQhkNIAAALIgoAAIAAioIAoAAIAAA7QAMgOAWAAQAZAAAPASQARARAAAcQAAAbgRASQgPASgZAAQgWAAgMgOgAQolRQgHAHAAAMQAAALAHAIQAHAHALAAQAMAAAHgHQAHgIAAgLQAAgMgHgHQgHgHgMgBQgLABgHAHgANwkRQgQgTAAgaQAAgbAQgSQAQgSAYAAQAWAAAMAOIAAgLIAoAAIAAB4IgoAAIAAgLQgMAOgWAAQgYAAgQgSgAOPlRQgHAHAAAMQAAALAHAIQAHAHALAAQALAAAHgHQAHgIAAgLQAAgMgHgHQgGgHgMgBQgLABgHAHgAgokRQgTgTAAgaQAAgbATgSQASgSAaAAQAcAAARASQATASAAAbQAAAagTATQgSASgbAAQgZAAgTgSgAgMlQQgHAHAAALQAAALAHAHQAHAHAJAAQALAAAHgHQAGgHAAgLQAAgLgGgHQgHgHgLAAQgJAAgHAHgAlGkRQgSgSAAgbQAAgbASgSQASgSAcAAQAbAAARASQASARAAAcQAAAJgCAGIhTAAQAHAOAUAAQAOAAAIgJIAdAVQgRAWgjAAQgeAAgTgSgAkvlLIAuAAQgFgRgRAAQgTAAgFARgAnbkRQgQgTAAgaQAAgbAQgSQAQgSAYAAQAWAAAMAOIAAg7IAoAAIAACoIgoAAIAAgLQgMAOgWAAQgYAAgQgSgAm8lRQgHAHAAAMQAAALAHAIQAHAHALAAQALAAAHgHQAHgIAAgLQAAgMgHgHQgGgHgMgBQgLABgHAHgAtBkRQgQgSAAgbQAAgcAQgRQAQgSAYAAQAWAAAMAOIAAgLIAoAAIAAB4IgoAAIAAgLQgMAOgWAAQgYAAgQgSgAsilRQgHAHAAAMQAAALAHAIQAHAHALAAQALAAAHgHQAHgIAAgLQAAgMgHgHQgGgHgMgBQgLABgHAHgAEakIQgPgMAAgcIAAgkIgSAAIAAgmIASAAIAAgVIAogMIAAAhIAZAAIAAAmIgZAAIAAAjQAAAHAGADQAFACAOgBIAAAkIgSABQgWAAgKgHgAqgkIQgOgMAAgcIAAgkIgSAAIAAgmIASAAIAAgVIAogMIAAAhIAZAAIAAAmIgZAAIAAAjQAAAHAGADQAFACAOgBIAAAkIgTABQgWAAgKgHgASNkCIAAh4IAoAAIAAB4gAMOkCIAAh4IAoAAIAAAWQADgLAKgHQAKgGANgBIAAAtQgNgCgMAGQgLAIAAAQIAAAygAIKkCIAAgbIArg4IgoAAIAAglIBdAAIAAAbIgqA4IAtAAIAAAlgAGXkCIAAh4IAoAAIAAB4gADDkCIAAh4IAoAAIAAB4gABNkCIAAgbIAqg4IgoAAIAAglIBdAAIAAAbIgqA4IAtAAIAAAlgApbkCIAAh4IAoAAIAAB4gAuKkCIAAiwIAoAAIAACwgASRmLQgHgGAAgKQAAgJAHgHQAHgGAJgBQAKABAGAGQAHAHAAAJQAAAKgHAGQgGAHgKAAQgJAAgHgHgAGamLQgGgGAAgKQAAgJAGgHQAHgGAKgBQAJABAHAGQAHAHAAAJQAAAKgHAGQgHAHgJAAQgKAAgHgHgADGmLQgGgGAAgKQAAgJAGgHQAHgGAKgBQAJABAHAGQAHAHAAAJQAAAKgHAGQgHAHgJAAQgKAAgHgHgApXmLQgHgGAAgKQAAgJAHgHQAHgGAJgBQAKABAGAGQAHAHAAAJQAAAKgHAGQgGAHgKAAQgJAAgHgHg");
	this.shape_1.setTransform(0,-2.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.txt2, new cjs.Rectangle(-132.2,-45.8,264.4,91.6), null);


(lib.p4_mc = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.instance = new lib.glitch4();
	this.instance.parent = this;
	this.instance.setTransform(-59,-59,0.2,0.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой_1
	this.instance_1 = new lib.glitch4();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-59,-59,0.2,0.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.p4_mc, new cjs.Rectangle(-59,-59,117,117), null);


(lib.p3_mc = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.instance = new lib.glitch3();
	this.instance.parent = this;
	this.instance.setTransform(-58,-66,0.2,0.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой_1
	this.instance_1 = new lib.glitch3();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-58,-66,0.2,0.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.p3_mc, new cjs.Rectangle(-58,-66,116.4,131.6), null);


(lib.p2_mc = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.instance = new lib.glitch2();
	this.instance.parent = this;
	this.instance.setTransform(-117,-78,0.2,0.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой_1
	this.instance_1 = new lib.glitch2();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-117,-78,0.2,0.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.p2_mc, new cjs.Rectangle(-117,-78,234.8,156.4), null);


(lib.p1_mc = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.instance = new lib.glitch1();
	this.instance.parent = this;
	this.instance.setTransform(-58,-52,0.2,0.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой_1
	this.instance_1 = new lib.glitch1();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-58,-52,0.2,0.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.p1_mc, new cjs.Rectangle(-58,-52,116.4,103.8), null);


(lib.mainTxt = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ABnGPIAJg2IAUAEIgMA1gAFTFiQgSgVAAgfIAAgKQAAgfASgVQARgTAagBQAYABATATQARAVAAAfIAAAKQAAAfgRAVQgTATgYAAQgaAAgRgTgAFhD/QgMAOAAAXIAAAKQAAAXAMAOQAMAPARAAQAQAAAMgPQAMgOAAgXIAAgKQAAgXgMgOQgMgOgQgBQgRABgMAOgAgOFiQgRgVAAgfIAAgKQAAgfARgVQARgTAZgBQAaABAQATQASAVAAAfIAAAKQAAAfgSAVQgQATgaAAQgZAAgRgTgAAAD/QgMAOAAAXIAAAKQAAAXAMAOQALAPARAAQAQAAANgPQALgOAAgXIAAgKQAAgXgLgOQgNgOgQgBQgRABgLAOgAk7FlQgPgPAAgYQAAgYAPgRQAQgPAXAAQAWAAAQAPQARAQAAAYIgBAKIhYAAQACAMAKAIQAKAIANAAQAKAAAJgFQAIgEAEgIIASAHQgHANgNAHQgMAJgRgBQgWAAgSgQgAkrEgQgJAIgCANIBFAAQgCgNgKgIQgJgIgOAAQgNAAgKAIgAJTFqQgOgLgGgRIAUgGQADALAIAHQAKAGALABQAOgBAKgIQAJgJAAgPQAAgOgIgKQgKgJgMAAQgJAAgIAFQgIADgHAIIgUgFIAAhKIBiAAIAAATIhOAAIAAApQAGgHALgEQALgFAIAAQATAAAOAQQANAQgBAUQAAAYgOANQgOAPgYAAQgSAAgOgKgAodFqQgKgLAAgRIAAhFIATAAIAABBQAAAKAHAHQAGAGAKAAQALAAAHgHQAHgHAAgIIAAhCIAUAAIAABpIgUAAIAAgMIgCACQgMAMgRAAQgPAAgLgKgAqWFqQgOgLgGgRIASgHQAEAMAJAHQAKAGALABQAQgBAKgJQAJgKAAgRIAAhcIAVAAIAABeQAAAYgQAOQgQAQgYAAQgSAAgOgKgAHKFyIAAgYIBFgzIAIgHIAEgIIACgIQAAgOgJgIQgKgJgNAAQgYAAgJAcIgUgFQAHgUANgLQAMgLAVAAQAXAAAOAOQAPAOAAAWQAAAWgjAaIgpAeIBMAAIAAAUgADMFyIAAgYIA9gsIAQgOIAEgIIACgIQAAgOgJgIQgKgJgMAAQgaAAgIAcIgTgFQAGgTANgMQAMgLAWAAQAWAAAOAOQAPANAAAXQAAAWgjAaIgpAeIBMAAIAAAUgAiUFyIAAgYIA9gsIAOgOIAFgIQACgEAAgEQAAgOgJgIQgKgJgMAAQgZAAgJAcIgTgFQAGgTANgMQAMgLAWAAQAVAAAPAOQAPANAAAXQAAAWgjAaIgpAeIBMAAIAAAUgAlyFyIAAg9QABgNgHgGQgHgIgLABQgKAAgJAHQgIAIAAALIAAA9IgUAAIAAhpIAUAAIAAAPIADgEQAMgNASABQARgBAKALQAMAMAAASIAABCgANPBqQgVgTAAgdIAAh+IAxAAIAAB5QAAAYAaAAQAbAAAAgYIAAh5IAwAAIAAB+QAAAdgVATQgVASghAAQggAAgWgSgAKOBgQgbgcgBgrQABgpAbgcQAcgdArAAQAZAAAXANQAWAMAMAUIgqAYQgFgJgLgHQgLgFgNAAQgXAAgOAOQgOANAAAXQAAAYAOANQAOAOAXABQANgBALgFQALgGAFgKIAqAYQgNAVgVAMQgWAMgaAAQgqAAgdgcgAh5BfQgdgcAAgqQAAgoAdgdQAdgdAqAAQApAAAcAdQAdAdAAAoQAAAqgdAcQgcAdgpAAQgqAAgdgdgAhXgLQgPAOAAAWQAAAWAPAPQAOAOAXABQAVgBAPgOQAOgPAAgWQAAgWgOgOQgPgOgVAAQgXAAgOAOgAsbBqQgVgTABgdIAAh+IAvAAIAAB5QAAAYAbAAQAbAAAAgYIAAh5IAwAAIAAB+QAAAdgVATQgUASgiAAQghAAgVgSgAxfBgQgcgcAAgrQAAgpAcgcQAcgdArAAQAaAAAVANQAXAMAMAUIgqAYQgMgVgcAAQgXAAgOAOQgOAOAAAWQAAAWAOAPQAOAOAXABQAcgBAMgVIAqAYQgNAVgVAMQgWAMgaAAQgrAAgcgcgAPuB4IAAi8IBKAAQAdAAAUASQATATAAAdQAAAcgTASQgUATgdAAIgZAAIAAA5gAQfARIAZAAQAJAAAFgFQAGgHAAgHQAAgJgGgFQgFgGgJAAIgZAAgAF5B4IAAi8IBOAAQAngBAaAcQAbAbAAAnQAAAogbAcQgaAbgnAAgAGsBJIAbAAQATAAANgNQAMgNABgWQgBgWgMgMQgNgNgTAAIgbAAgAD0B4IAAi8IAwAAIAACNIBBAAIAAAvgACsB4Ighg9IgSAAIAAA9IgwAAIAAi8IBMAAQAeAAASASQAUATAAAcQAAAQgIAOQgJAOgPAJIAnBGgAB5ARIAbAAQAJABAGgGQAGgGgBgJQABgJgGgGQgGgGgJAAIgbAAgAkAB4IgfhrIgeBrIg0AAIg0i8IA0AAIAdB2IAih2IAmAAIAiB2IAeh2IAzAAIg0C8gAp7B4IAAi8IBKAAQAdAAARAOQARAOAAAaQAAAXgSANQAZAPAAAcQAAAagSAOQgRAPgdAAgApLBNIAfAAQAHgBAFgEQAEgEAAgIQAAgGgEgFQgFgFgHAAIgfAAgApLAEIAZAAQAHAAAEgEQAFgDAAgIQAAgGgFgEQgEgEgHAAIgZAAgAuyB4IAAi8IAxAAIAACNIBBAAIAAAvgAHvjRQgJgIABgLQgBgLAJgJQAJgIALAAQAMAAAIAIQAIAJAAALQAAALgIAIQgIAJgMAAQgMAAgIgJgADAjcQgSgUAAggQAAgfASgTQASgVAcAAQAYAAAOAQIAAgMIAtAAIAACHIgtAAIAAgNQgOARgYAAQgcAAgSgUgADjklQgIAIAAANQAAAOAIAIQAIAIANAAQAMAAAIgIQAIgJAAgNQAAgMgIgJQgIgIgMAAQgNAAgIAIgAA6jZIAAANIgsAAIAAi9IAsAAIAABCQAPgQAYAAQAbAAASAVQATAUgBAeQABAggTAUQgSAUgbAAQgYAAgPgRgABDklQgJAJAAAMQAAANAJAJQAHAIANAAQANAAAHgIQAIgIAAgOQAAgNgIgIQgHgIgNAAQgNAAgHAIgAjmjcQgWgVAAgfQAAgeAWgUQAUgVAeAAQAgAAATAVQAWAVAAAdQAAAegWAWQgUAUgfAAQgdAAgVgUgAjHkkQgIAIAAAMQAAANAIAHQAIAIALAAQAMAAAJgIQAHgHAAgNQAAgMgHgIQgJgIgMAAQgLAAgIAIgAmFjcQgVgWAAgeQAAgdAVgVQAWgVAeAAQAeAAAVAVQAVAUAAAeQAAAfgVAVQgVAUgeAAQgeAAgWgUgAllkkQgHAIAAAMQAAANAHAHQAIAIAMAAQAMAAAHgIQAIgHAAgNQAAgMgIgIQgHgIgMAAQgMAAgIAIgAg/jTQgQgMAAghIAAgoIgVAAIAAgrIAVAAIAAgZIAtgNIAAAmIAcAAIAAArIgcAAIAAAnQgBAIAHADQAFACARgBIAAApIgWABQgXAAgMgIgAGijMIAAjFIAtAAIAADFgAFbjMIAAjFIAsAAIAADFgAoejMIAAi9IB1AAIAAAvIhEAAIAAAeIBCAAIAAAvIhCAAIAABBgAHvknQgJgJABgLQgBgMAJgIQAJgJALAAQAMAAAIAJQAIAIAAAMQAAALgIAJQgIAIgMAAQgMAAgIgIg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.mainTxt, new cjs.Rectangle(-114.8,-40.2,229.6,80.5), null);


(lib.logo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#14A0FF").s().p("AJAHRICwrFIkMAAIA0jcINHAAIg3DcIkfAAIiwLFgAnfHRIDmuhILSAAIgzDcIm4AAIgiCCIG8AAIgzDbIm/AAIghCMIIUAAIg1DcgAzzHRIhri3IC4rpIHsgBQCkAABMBSQBIBNgeB4QgbBrhVA2IAAACQAuAYARAxQASAzgRBGQgiCKh8BPQh4BMivAAgAw9D1IDfAAQBKAAAkgZQAbgSAIgkQAJgkgSgTQgYgahKAAIjeAAgAvlhyIDJAAQA/AAAggWQAWgQAIgdQAHgegOgOQgUgThBAAIjJAAg");
	this.shape.setTransform(75.1,0);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AHbHRQiFAAhGgfQgtgUgggqIhhimIkiEDIp1AAIB7nvIAchKIieCcIgDj2IEmkOIDlAAIjaNxIMOrSIABABICnigIGYAAIm2GHIBbCYIAAAAIDgGCgAkonQIEtAAQCTAABJBrIABACIkpERg");
	this.shape_1.setTransform(-129.4,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.logo, new cjs.Rectangle(-212.6,-46.5,425.2,93), null);


(lib.ic2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AibFwQhIgeg3g3Qg4g4gdhHQgghLAAhRQAAhRAghKQAdhIA4g3QA3g4BIgeQBKgfBRAAQBRAABLAfQBHAeA4A4QA3A3AeBIQAgBKAABRQAABRggBLQgeBHg3A4Qg4A3hHAeQhLAghRAAQhRAAhKggg");

	// Слой_6
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["rgba(0,0,0,0)","rgba(0,0,0,0.298)"],[0.416,1],0,0,0,0,0,40.1).s().p("AibFwQhIgeg3g3Qg4g4gdhHQgghLAAhRQAAhRAghKQAdhIA4g3QA3g4BIgeQBKgfBRAAQBRAABLAfQBHAeA4A4QA3A3AeBIQAgBKAABRQAABRggBLQgeBHg3A4Qg4A3hHAeQhLAghRAAQhRAAhKggg");

	var maskedShapeInstanceList = [this.shape];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Слой_7
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#F2D648").s().p("Ai6FfIgUgWQgVgYgJgPIA4g0IADACIAKAHQAQAKASAJQA6AdA7AAIAcBIQgMAGgQAFQggAMgYAAQg8gKg2gdgAEEEiQASgaACgHIAhgMIgBACQghAogmAdIATgagAByC1IgNgqQgOg2gKg6QgDgCAOgPQANgNATgSQAWgUATgPQAYgRAOgGIAAgBQADAAAOAIQAPAIARALQATAOAPAOQARARAIAPIgCAQQgDAVgFAVQgPBBgcAmIgKAEQgNAEgPADQgcAFgdAAQgXAAgWgDgAmOAYIAOAWIgBAQIgDAeQgIghgCgjgAkLAxQgwgkgOgYQACgbAGgiQAOhDAWgdQAJgHARgGQAhgMAmAAQAYAAAYAFIAMArQAOA3AMA6IgwAuQgzAygWAQQgUgNgYgSgAGIgYQgJgWgGgIQACgKgBgVQAAgTgCgOQABgCAEgBQASA5AAA+IAAAAIgHgWgAAoknQgSgEgRgCIgIAAIgEAAIgRhJQAngPAmAAQAnAAAjAPQAdAMAaAVQATAPAPASIAMAPIhIAxQg5glg7gOgAkQknIAAAAIAGgGQANgLANgKIgVAdQgRAWgDAKIghAMQATgZAXgVg");
	this.shape_1.setTransform(0.1,0.3);

	var maskedShapeInstanceList = [this.shape_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

	// Слой_8
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#F2D648").s().p("AATF3IgZgCIABgDIAYABQAfABAfgCQAsgEAngKQAwgNAlgXIACADQglAXgyANQgmAKgsAEQgXACgWAAIgSAAgAgTEyIAMgHQAQgJASgNQA4goAog6IADADQgpA5g4ApQgSAMgQAKIgNAHgAkAEiQgjgOgMgIIACgDQALAIAkAOIAiALIgBAEIgjgMgAEXDpQgKgrgPgVIACgCQARAVAJAsQAGAWACASIgDAAQgDgRgFgWgAjTCOQgEgZgCgaIgBgWIADAAIABAVQACAbAFAYQANBOAYAeIgDACQgZgfgNhOgAmDBBQAKgbAfgaQAQgMAOgJIACADQgOAHgPANQggAagJAagAgOACIhUgZIABgDIBUAaQBWAaAKAHIgCADQgKgIhVgagAEmAVIAMgGQAPgIAMgIQAqgbAKgZIADABQgLAagqAbQgNAJgPAHIgLAHgADKhIIAAgQQgBgUgDgVQgKhCgcgtIACgCQAdAuAKBDQAEAUABAVIAAAQgAF0h9QgNgZgRgZQgYgigcgcQgjgigmgVIABgDQAoAVAiAjQAdAcAYAiQARAZAOAaIAKAVIgDABIgLgVgAkbjIQAAgvAJgUIAEABQgKAUABAuQgBAYADATIgDAAQgCgTgBgYgAiIi2IAKgNQANgQAPgPQAxgxA0gYIABADQgzAYgxAwIgcAfIgKANgAjOlWQAcgSAlgIQAegGAiAAQAYABAYADIATAEIgBADIgTgDQgXgEgYAAQgigBgdAGQgkAIgcASg");
	this.shape_2.setTransform(-0.5,-0.5);

	var maskedShapeInstanceList = [this.shape_2];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(1));

	// mask
	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#1C4B98").s().p("AibFwQhIgeg3g3Qg4g4gdhHQgghLAAhRQAAhRAghKQAdhIA4g3QA3g4BIgeQBKgfBRAAQBRAABLAfQBHAeA4A4QA3A3AeBIQAgBKAABRQAABRggBLQgeBHg3A4Qg4A3hHAeQhLAghRAAQhRAAhKggg");

	this.timeline.addTween(cjs.Tween.get(this.shape_3).wait(1));

}).prototype = getMCSymbolPrototype(lib.ic2, new cjs.Rectangle(-40,-40,80,80), null);


(lib.ic1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AibFwQhIgeg3g3Qg4g4gdhHQgghLAAhRQAAhRAghKQAdhIA4g3QA3g4BIgeQBKgfBRAAQBRAABLAfQBHAeA4A4QA3A3AeBIQAgBKAABRQAABRggBLQgeBHg3A4Qg4A3hHAeQhLAghRAAQhRAAhKggg");

	// Слой_15
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["rgba(0,0,0,0)","rgba(0,0,0,0.298)"],[0.416,1],0,0,0,0,0,40.1).s().p("AibFwQhIgeg3g3Qg4g4gdhHQgghLAAhRQAAhRAghKQAdhIA4g3QA3g4BIgeQBKgfBRAAQBRAABLAfQBHAeA4A4QA3A3AeBIQAgBKAABRQAABRggBLQgeBHg3A4Qg4A3hHAeQhLAghRAAQhRAAhKggg");

	var maskedShapeInstanceList = [this.shape];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Слой_14
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#EC3347").s().p("Ai6FfIgUgWQgVgYgJgPIA4g0IADACIAKAHQAQAKASAJQA6AdA7AAIAcBIQgMAGgQAFQggAMgYAAQg8gKg2gdgAEEEiQASgaACgHIAhgMIgBACQghAogmAdIATgagAByC1IgNgqQgOg2gKg6QgDgCAOgPQANgNATgSQAWgUATgPQAYgRAOgGIAAgBQADAAAOAIQAPAIARALQATAOAPAOQARARAIAPIgCAQQgDAVgFAVQgPBBgcAmIgKAEQgNAEgPADQgcAFgdAAQgXAAgWgDgAmOAYIAOAWIgBAQIgDAeQgIghgCgjgAkLAxQgwgkgOgYQACgbAGgiQAOhDAWgdQAJgHARgGQAhgMAmAAQAYAAAYAFIAMArQAOA3AMA6IgwAuQgzAygWAQQgUgNgYgSgAGIgYQgJgWgGgIQACgKgBgVQAAgTgCgOQABgCAEgBQASA5AAA+IAAAAIgHgWgAAoknQgSgEgRgCIgIAAIgEAAIgRhJQAngPAmAAQAnAAAjAPQAdAMAaAVQATAPAPASIAMAPIhIAxQg5glg7gOgAkQknIAAAAIAGgGQANgLANgKIgVAdQgRAWgDAKIghAMQATgZAXgVg");
	this.shape_1.setTransform(0.1,0.3);

	var maskedShapeInstanceList = [this.shape_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

	// Слой_13
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#58595D").s().p("AATF3IgZgCIABgDIAYABQAfABAfgCQAsgEAngKQAwgNAlgXIACADQglAXgyANQgmAKgsAEQgXACgWAAIgSAAgAgTEyIAMgHQAQgJASgNQA4goAog6IADADQgpA5g4ApQgSAMgQAKIgNAHgAkAEiQgjgOgMgIIACgDQALAIAkAOIAiALIgBAEIgjgMgAEXDpQgKgrgPgVIACgCQARAVAJAsQAGAWACASIgDAAQgDgRgFgWgAjTCOQgEgZgCgaIgBgWIADAAIABAVQACAbAFAYQANBOAYAeIgDACQgZgfgNhOgAmDBBQAKgbAfgaQAQgMAOgJIACADQgOAHgPANQggAagJAagAgOACIhUgZIABgDIBUAaQBWAaAKAHIgCADQgKgIhVgagAEmAVIAMgGQAPgIAMgIQAqgbAKgZIADABQgLAagqAbQgNAJgPAHIgLAHgADKhIIAAgQQgBgUgDgVQgKhCgcgtIACgCQAdAuAKBDQAEAUABAVIAAAQgAF0h9QgNgZgRgZQgYgigcgcQgjgigmgVIABgDQAoAVAiAjQAdAcAYAiQARAZAOAaIAKAVIgDABIgLgVgAkbjIQAAgvAJgUIAEABQgKAUABAuQgBAYADATIgDAAQgCgTgBgYgAiIi2IAKgNQANgQAPgPQAxgxA0gYIABADQgzAYgxAwIgcAfIgKANgAjOlWQAcgSAlgIQAegGAiAAQAYABAYADIATAEIgBADIgTgDQgXgEgYAAQgigBgdAGQgkAIgcASg");
	this.shape_2.setTransform(-0.5,-0.5);

	var maskedShapeInstanceList = [this.shape_2];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(1));

	// mask
	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AibFwQhIgeg3g3Qg4g4gdhHQgghLAAhRQAAhRAghKQAdhIA4g3QA3g4BIgeQBKgfBRAAQBRAABLAfQBHAeA4A4QA3A3AeBIQAgBKAABRQAABRggBLQgeBHg3A4Qg4A3hHAeQhLAghRAAQhRAAhKggg");

	this.timeline.addTween(cjs.Tween.get(this.shape_3).wait(1));

}).prototype = getMCSymbolPrototype(lib.ic1, new cjs.Rectangle(-40,-40,80,80), null);


(lib.CTA_txt = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AHNDhIAAgbIAFAAQAIAAADgFQAEgEAAgJIAAhnIAbAAIAABwQAAAOgKALQgKALgRAAgAFDCpQgRgPAAgZQAAgYARgQQAQgQAYAAQATAAAMAJQAOAIAIAPIgZAMQgEgIgHgGQgIgEgJAAQgNAAgIAIQgJAJAAANQAAANAJAJQAIAIANAAQAJAAAHgEQAHgFAEgHIAZALQgHAPgOAIQgOAIgRAAQgXAAgRgQgAkWCpQgQgQAAgYQAAgYAQgQQAPgQAXAAQAYAAAQAQQAQAQAAAYIgBALIhQAAQACAKAHAFQAIAFAKAAQAGAAAIgDQAHgEADgFIAZAJQgHANgNAHQgOAIgPAAQgYAAgQgQgAkABnQgHAFgCAKIA1AAQgBgJgIgGQgIgFgKAAQgKAAgHAFgAKEC0QgFgGAAgIQAAgIAFgFQAFgGAIAAQAHAAAGAGQAFAFAAAIQAAAIgFAGQgFAFgIAAQgIAAgFgFgAIcCtQgKgKAAgSIAAhEIAbAAIAAA+QAAAJAFAFQAFAFAIAAQAJAAAFgFQAGgFAAgHIAAhAIAbAAIAABoIgbAAIAAgKIgBAAQgLANgRAAQgPAAgLgLgADPCvQgJgJAAgNQAAgOAJgIQAJgJAQgCIAdgEIAAgBQAAgHgFgEQgFgFgIAAQgHAAgGAEQgFADgCAHIgagJQAFgNAMgIQANgIAPAAQASAAAOALQAOALAAAQIAABEIgbAAIAAgOIgDAEQgLANgRAAQgOAAgJgJgADuCNQgNABAAAJQAAAEAEACQADADAHAAQALAAAFgFQAGgFAAgJIAAgDgAo5CvQgJgIAAgOQAAgOAJgIQAJgJAQgCIAdgEIAAgBQAAgHgFgEQgFgFgIAAQgHAAgGAEQgFAEgCAGIgagJQAFgNAMgIQANgIAPAAQASAAAPALQAOAMAAAPIAABEIgcAAIAAgOIgDAEQgLANgQAAQgPAAgJgJgAoZCNQgOABAAAJQAAAEAEACQADADAHAAQALAAAFgFQAGgFAAgJIAAgDgAGxC1IAAhoIAbAAIAABogACdC1IgigmIgFAAIAAAmIgbAAIAAicIAbAAIAABbIAFAAIAignIAjAAIgtA0IAtA0gAAqC1IAAhPIgpAAIAABPIgaAAIAAhPIgVAAIAAgZIAVAAIAAgQQAAgPALgLQAMgKAPAAIAQAAIAAAZIgMAAQgHAAgFAFQgEAEAAAIIAAAKIBEAAIAABogAhZC1IAAhoIAbAAIAABogAimC1IAAhoIAbAAIAAAOIABgBQALgOARAAIAGAAIAAAbIgFAAQgNAAgIAGQgIAHgBAJIAAA4gAl4C1IgmhoIAcAAIAbBQIAchQIAdAAIgnBogAqmC1IAAgcIA1g0Ig1AAIAAgYIBYAAIAAAcIg6A1IA6AAIAAAXgAKECGIgChiIAdAAIgCBigAHjA7QgFgFAAgHQAAgHAFgFQAFgEAHAAQAHAAAEAEQAFAFAAAHQAAAHgFAFQgEAFgHAAQgHAAgFgFgAGzA7QgFgFAAgHQAAgGAFgGQAEgEAHAAQAHAAAFAEQAFAGAAAGQAAAHgFAFQgFAFgHAAQgHAAgEgFgAAsA7QgFgFAAgHQAAgGAFgGQAFgEAHAAQAHAAAEAEQAFAGAAAGQAAAHgFAFQgEAFgHAAQgHAAgFgFgAhXA7QgFgFAAgHQAAgHAFgFQAFgEAHAAQAHAAAEAEQAFAFAAAHQAAAHgFAFQgEAFgHAAQgHAAgFgFgAIyhUQgSgUAAgfIAAgLQAAgeASgVQASgUAZAAQAaAAARAUQARAUAAAfIAAALQAAAggRATQgSAUgZAAQgZAAgSgUgAJFixQgKAMAAATIAAALQAAATAKANQAKAMAOAAQAOAAAKgMQAJgNAAgTIAAgLQAAgUgJgLQgKgNgOAAQgOAAgKANgAA8hQQgQgQAAgYQAAgYAQgQQAPgQAXAAQAXAAARAQQAQAQAAAYIgBALIhQAAQACAKAHAFQAIAFAKAAQAIAAAGgDQAHgDADgGIAZAJQgHAOgNAHQgNAHgQAAQgYAAgQgQgABSiSQgHAFgCAKIA1AAQgBgKgIgFQgIgFgKAAQgKAAgHAFgAg0hQIgFgFIAAARIgbAAIAAicIAbAAIAABGIAFgGQANgQAVAAQATAAAPAQQAOAQAAAYQAAAXgOARQgPAQgTAAQgVAAgNgQgAgwiOQgIAJgBANIAAABQABANAIAIQAJAJANAAQANAAAIgJQAIgIAAgOQAAgNgIgJQgIgIgNAAQgNAAgJAIgAuJhQQgQgQAAgYQAAgYAPgQQAQgQAXAAQAXAAAQAQQARAQAAAYIgCALIhQAAQADAKAHAFQAIAFAJAAQAIAAAHgDQAGgDADgGIAZAJQgHAOgNAHQgMAHgRAAQgXAAgQgQgAtziSQgIAFgCAKIA2AAQgCgKgHgFQgHgFgLAAQgLAAgGAFgAN8hLQgQgJgHgQIAagNQAEAKAIAGQAIAGALAAQAKAAAHgFQAGgFAAgIQAAgHgHgEQgFgEgQgDQgZgFgMgLQgNgMAAgSQAAgTAOgMQAOgMAVAAQATAAAPAKQAPAKAHAQIgaAKQgEgKgIgFQgIgFgJAAQgKAAgGAFQgGAEAAAIQAAAHAGAEQAIAFANACQAYAFAOAMQAOAMAAASQAAATgPAMQgPAMgWAAQgUAAgOgKgAG8hLQgNgLgGgRIAbgJQACAJAHAFQAHAGAJAAQALAAAIgHQAHgHAAgMQAAgLgGgHQgHgHgKAAQgOAAgMAMIgbgHIAAhLIBjAAIAAAaIhIAAIAAAgQAJgHAHgDQAIgDAJAAQASAAANAPQAMAOAAAWQAAAXgOAOQgPAPgXAAQgTAAgPgKgAsPhMQgKgKAAgSIAAhEIAbAAIAAA+QAAAJAFAFQAGAFAHAAQAHAAAHgFQAGgFAAgHIAAhAIAbAAIAABoIgbAAIAAgLIgBABQgLANgRAAQgQAAgKgLgAPjhEIAAiRIA6AAQATAAARAJQAPAIALASQAJAQAAAVQAAAQgFAOQgHAOgJAJQgIAJgOAGQgNAFgPAAgAP/heIAcAAQATAAAOgNQANgNAAgVQAAgUgNgNQgOgNgTAAIgcAAgAM4hEIgkgzIgVAAIAAAzIgbAAIAAiRIBAAAQAWAAAPANQAOANAAAVQAAASgKAMQgLAMgRACIAmA2gAL/iRIAjAAQAKAAAIgGQAHgGAAgJQAAgJgHgGQgHgGgLAAIgjAAgAE0hEIAAgeIA5gpIAHgGIAHgGIAEgHIABgHQAAgLgHgGQgIgHgJAAQgVAAgGAXIgbgIQAGgSAOgMQANgMAVAAQAVAAAPAPQAQAOAAAWQAAAYghAWIgiAZIBDAAIAAAagADbhEQgSAAgKgIQgKgJAAgPIAAgvIgTAAIAAgZIATAAIAAgdIAbgFIAAAiIAeAAIAAAZIgeAAIAAAoQAAAGAEAEQAEAEAHAAIAPAAIAAAZgAiEhEIAAhoIAbAAIAABogAjShEIAAhoIAcAAIAAAOIAAgBQALgOARAAIAGAAIAAAbIgFAAQgNAAgIAHQgIAGAAAKIAAA3gAkdhEIAAhPIgVAAIAAgZIAVAAIAAgQQAAgPALgKQAMgLAQAAIAQAAIAAAZIgMAAQgHAAgFAFQgEAFAAAHIAAAKIAgAAIAAAZIggAAIAABPgAmVhEIAAhoIAbAAIAABogAnFhEIAAg9QAAgIgFgGQgFgFgHAAQgIAAgFAFQgFAGAAAIIgBAAIAAA9IgbAAIAAg9QAAgJgEgFQgFgFgHAAQgIAAgFAFQgGAHAAAGIAAA+IgbAAIAAhoIAbAAIAAALQALgNAQAAQAPAAAKAKIAGAJIAFgGQAKgNARAAQAOAAALAKQAKALAAASIAABDgAqshEIAAgcIA2g0Ig2AAIAAgYIBYAAIAAAcIg5A1IA5AAIAAAXgAvfhEIAAhoIAbAAIAAAPIABgCQALgOARAAIAGAAIAAAbIgFAAQgNAAgIAHQgIAHgBAJIAAA3gAxjhEIAAiRIA/AAQAXAAAOAOQAPAPAAAVQAAAVgQAPQgPAPgXAAIgiAAIAAAsgAxIiKIAiAAQALAAAIgHQAIgIAAgKQAAgKgIgHQgIgHgLAAIgiAAgAiCi+QgFgFAAgHQAAgHAFgEQAEgFAHAAQAHAAAFAFQAFAFAAAGQAAAGgFAGQgFAFgHAAQgHAAgEgFgAmTi+QgFgFAAgHQAAgHAFgEQAEgFAHAAQAIAAAEAFQAFAEAAAHQAAAHgFAFQgEAFgIAAQgHAAgEgFg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Слой_4
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#002B72").s().p("AHNDhIAAgbIAFAAQAIAAADgFQAEgEAAgJIAAhnIAbAAIAABwQAAAOgKALQgKALgRAAgAFDCpQgRgPAAgZQAAgYARgQQAQgQAYAAQATAAAMAJQAOAIAIAPIgZAMQgEgIgHgGQgIgEgJAAQgNAAgIAIQgJAJAAANQAAANAJAJQAIAIANAAQAJAAAHgEQAHgFAEgHIAZALQgHAPgOAIQgOAIgRAAQgXAAgRgQgAkWCpQgQgQAAgYQAAgYAQgQQAPgQAXAAQAYAAAQAQQAQAQAAAYIgBALIhQAAQACAKAHAFQAIAFAKAAQAGAAAIgDQAHgEADgFIAZAJQgHANgNAHQgOAIgPAAQgYAAgQgQgAkABnQgHAFgCAKIA1AAQgBgJgIgGQgIgFgKAAQgKAAgHAFgAKEC0QgFgGAAgIQAAgIAFgFQAFgGAIAAQAHAAAGAGQAFAFAAAIQAAAIgFAGQgFAFgIAAQgIAAgFgFgAIcCtQgKgKAAgSIAAhEIAbAAIAAA+QAAAJAFAFQAFAFAIAAQAJAAAFgFQAGgFAAgHIAAhAIAbAAIAABoIgbAAIAAgKIgBAAQgLANgRAAQgPAAgLgLgADPCvQgJgJAAgNQAAgOAJgIQAJgJAQgCIAdgEIAAgBQAAgHgFgEQgFgFgIAAQgHAAgGAEQgFADgCAHIgagJQAFgNAMgIQANgIAPAAQASAAAOALQAOALAAAQIAABEIgbAAIAAgOIgDAEQgLANgRAAQgOAAgJgJgADuCNQgNABAAAJQAAAEAEACQADADAHAAQALAAAFgFQAGgFAAgJIAAgDgAo5CvQgJgIAAgOQAAgOAJgIQAJgJAQgCIAdgEIAAgBQAAgHgFgEQgFgFgIAAQgHAAgGAEQgFAEgCAGIgagJQAFgNAMgIQANgIAPAAQASAAAPALQAOAMAAAPIAABEIgcAAIAAgOIgDAEQgLANgQAAQgPAAgJgJgAoZCNQgOABAAAJQAAAEAEACQADADAHAAQALAAAFgFQAGgFAAgJIAAgDgAGxC1IAAhoIAbAAIAABogACdC1IgigmIgFAAIAAAmIgbAAIAAicIAbAAIAABbIAFAAIAignIAjAAIgtA0IAtA0gAAqC1IAAhPIgpAAIAABPIgaAAIAAhPIgVAAIAAgZIAVAAIAAgQQAAgPALgLQAMgKAPAAIAQAAIAAAZIgMAAQgHAAgFAFQgEAEAAAIIAAAKIBEAAIAABogAhZC1IAAhoIAbAAIAABogAimC1IAAhoIAbAAIAAAOIABgBQALgOARAAIAGAAIAAAbIgFAAQgNAAgIAGQgIAHgBAJIAAA4gAl4C1IgmhoIAcAAIAbBQIAchQIAdAAIgnBogAqmC1IAAgcIA1g0Ig1AAIAAgYIBYAAIAAAcIg6A1IA6AAIAAAXgAKECGIgChiIAdAAIgCBigAHjA7QgFgFAAgHQAAgHAFgFQAFgEAHAAQAHAAAEAEQAFAFAAAHQAAAHgFAFQgEAFgHAAQgHAAgFgFgAGzA7QgFgFAAgHQAAgGAFgGQAEgEAHAAQAHAAAFAEQAFAGAAAGQAAAHgFAFQgFAFgHAAQgHAAgEgFgAAsA7QgFgFAAgHQAAgGAFgGQAFgEAHAAQAHAAAEAEQAFAGAAAGQAAAHgFAFQgEAFgHAAQgHAAgFgFgAhXA7QgFgFAAgHQAAgHAFgFQAFgEAHAAQAHAAAEAEQAFAFAAAHQAAAHgFAFQgEAFgHAAQgHAAgFgFgAIyhUQgSgUAAgfIAAgLQAAgeASgVQASgUAZAAQAaAAARAUQARAUAAAfIAAALQAAAggRATQgSAUgZAAQgZAAgSgUgAJFixQgKAMAAATIAAALQAAATAKANQAKAMAOAAQAOAAAKgMQAJgNAAgTIAAgLQAAgUgJgLQgKgNgOAAQgOAAgKANgAA8hQQgQgQAAgYQAAgYAQgQQAPgQAXAAQAXAAARAQQAQAQAAAYIgBALIhQAAQACAKAHAFQAIAFAKAAQAIAAAGgDQAHgDADgGIAZAJQgHAOgNAHQgNAHgQAAQgYAAgQgQgABSiSQgHAFgCAKIA1AAQgBgKgIgFQgIgFgKAAQgKAAgHAFgAg0hQIgFgFIAAARIgbAAIAAicIAbAAIAABGIAFgGQANgQAVAAQATAAAPAQQAOAQAAAYQAAAXgOARQgPAQgTAAQgVAAgNgQgAgwiOQgIAJgBANIAAABQABANAIAIQAJAJANAAQANAAAIgJQAIgIAAgOQAAgNgIgJQgIgIgNAAQgNAAgJAIgAuJhQQgQgQAAgYQAAgYAPgQQAQgQAXAAQAXAAAQAQQARAQAAAYIgCALIhQAAQADAKAHAFQAIAFAJAAQAIAAAHgDQAGgDADgGIAZAJQgHAOgNAHQgMAHgRAAQgXAAgQgQgAtziSQgIAFgCAKIA2AAQgCgKgHgFQgHgFgLAAQgLAAgGAFgAN8hLQgQgJgHgQIAagNQAEAKAIAGQAIAGALAAQAKAAAHgFQAGgFAAgIQAAgHgHgEQgFgEgQgDQgZgFgMgLQgNgMAAgSQAAgTAOgMQAOgMAVAAQATAAAPAKQAPAKAHAQIgaAKQgEgKgIgFQgIgFgJAAQgKAAgGAFQgGAEAAAIQAAAHAGAEQAIAFANACQAYAFAOAMQAOAMAAASQAAATgPAMQgPAMgWAAQgUAAgOgKgAG8hLQgNgLgGgRIAbgJQACAJAHAFQAHAGAJAAQALAAAIgHQAHgHAAgMQAAgLgGgHQgHgHgKAAQgOAAgMAMIgbgHIAAhLIBjAAIAAAaIhIAAIAAAgQAJgHAHgDQAIgDAJAAQASAAANAPQAMAOAAAWQAAAXgOAOQgPAPgXAAQgTAAgPgKgAsPhMQgKgKAAgSIAAhEIAbAAIAAA+QAAAJAFAFQAGAFAHAAQAHAAAHgFQAGgFAAgHIAAhAIAbAAIAABoIgbAAIAAgLIgBABQgLANgRAAQgQAAgKgLgAPjhEIAAiRIA6AAQATAAARAJQAPAIALASQAJAQAAAVQAAAQgFAOQgHAOgJAJQgIAJgOAGQgNAFgPAAgAP/heIAcAAQATAAAOgNQANgNAAgVQAAgUgNgNQgOgNgTAAIgcAAgAM4hEIgkgzIgVAAIAAAzIgbAAIAAiRIBAAAQAWAAAPANQAOANAAAVQAAASgKAMQgLAMgRACIAmA2gAL/iRIAjAAQAKAAAIgGQAHgGAAgJQAAgJgHgGQgHgGgLAAIgjAAgAE0hEIAAgeIA5gpIAHgGIAHgGIAEgHIABgHQAAgLgHgGQgIgHgJAAQgVAAgGAXIgbgIQAGgSAOgMQANgMAVAAQAVAAAPAPQAQAOAAAWQAAAYghAWIgiAZIBDAAIAAAagADbhEQgSAAgKgIQgKgJAAgPIAAgvIgTAAIAAgZIATAAIAAgdIAbgFIAAAiIAeAAIAAAZIgeAAIAAAoQAAAGAEAEQAEAEAHAAIAPAAIAAAZgAiEhEIAAhoIAbAAIAABogAjShEIAAhoIAcAAIAAAOIAAgBQALgOARAAIAGAAIAAAbIgFAAQgNAAgIAHQgIAGAAAKIAAA3gAkdhEIAAhPIgVAAIAAgZIAVAAIAAgQQAAgPALgKQAMgLAQAAIAQAAIAAAZIgMAAQgHAAgFAFQgEAFAAAHIAAAKIAgAAIAAAZIggAAIAABPgAmVhEIAAhoIAbAAIAABogAnFhEIAAg9QAAgIgFgGQgFgFgHAAQgIAAgFAFQgFAGAAAIIgBAAIAAA9IgbAAIAAg9QAAgJgEgFQgFgFgHAAQgIAAgFAFQgGAHAAAGIAAA+IgbAAIAAhoIAbAAIAAALQALgNAQAAQAPAAAKAKIAGAJIAFgGQAKgNARAAQAOAAALAKQAKALAAASIAABDgAqshEIAAgcIA2g0Ig2AAIAAgYIBYAAIAAAcIg5A1IA5AAIAAAXgAvfhEIAAhoIAbAAIAAAPIABgCQALgOARAAIAGAAIAAAbIgFAAQgNAAgIAHQgIAHgBAJIAAA3gAxjhEIAAiRIA/AAQAXAAAOAOQAPAPAAAVQAAAVgQAPQgPAPgXAAIgiAAIAAAsgAxIiKIAiAAQALAAAIgHQAIgIAAgKQAAgKgIgHQgIgHgLAAIgiAAgAiCi+QgFgFAAgHQAAgHAFgEQAEgFAHAAQAHAAAFAFQAFAFAAAGQAAAGgFAGQgFAFgHAAQgHAAgEgFgAmTi+QgFgFAAgHQAAgHAFgEQAEgFAHAAQAIAAAEAFQAFAEAAAHQAAAHgFAFQgEAFgIAAQgHAAgEgFg");
	this.shape_1.setTransform(1,1);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.CTA_txt, new cjs.Rectangle(-112.4,-22.5,225.9,46), null);


(lib.bg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#002B72").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.bg, new cjs.Rectangle(-150,-300,300,600), null);


(lib.p4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		//let sc = Math.random()*.7 +.3;
		//this.p.scaleX = this.p.scaleY = Math.random();
	}
	this.frame_17 = function() {
		this.parent.parent.removeChild(this.parent);
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(17).call(this.frame_17).wait(1));

	// Слой_2
	this.p = new lib.p4_mc();
	this.p.name = "p";
	this.p.parent = this;
	this.p.setTransform(-58.2,-0.1,1,1,0,0,0,-58,-0.2);

	this.timeline.addTween(cjs.Tween.get(this.p).wait(1).to({scaleX:2.18},15,cjs.Ease.cubicInOut).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-59.2,-58.9,117,117);


(lib.p3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		//let sc = Math.random()*.7 +.3;
		//this.p.scaleX = this.p.scaleY = Math.random();
	}
	this.frame_17 = function() {
		this.parent.parent.removeChild(this.parent);
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(17).call(this.frame_17).wait(1));

	// Слой_2
	this.p = new lib.p3_mc();
	this.p.name = "p";
	this.p.parent = this;
	this.p.setTransform(-58.2,-0.1,1,1,0,0,0,-58,-0.2);

	this.timeline.addTween(cjs.Tween.get(this.p).wait(1).to({scaleX:2.18},15,cjs.Ease.cubicInOut).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-58.2,-65.9,116.4,131.6);


(lib.p2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		//this.p.scaleX = this.p.scaleY = Math.random();
	}
	this.frame_15 = function() {
		this.parent.parent.removeChild(this.parent);
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(15).call(this.frame_15).wait(44));

	// Слой_2
	this.p = new lib.p2_mc();
	this.p.name = "p";
	this.p.parent = this;
	this.p.setTransform(-58.4,-9.6);

	this.timeline.addTween(cjs.Tween.get(this.p).wait(1).to({regX:-117,regY:0.2,x:-175.4,y:-9.4},0).to({_off:true},3).wait(1).to({_off:false,scaleX:0.61},0).to({_off:true},1).wait(2).to({_off:false,scaleX:1.44},0).to({_off:true},3).wait(2).to({_off:false,scaleX:1},0).to({_off:true},2).wait(44));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-175.4,-87.6,234.8,156.4);


(lib.p1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		//let sc = Math.random()*.7 +.3;
		//this.p.scaleX = this.p.scaleY = Math.random();
	}
	this.frame_15 = function() {
		this.parent.parent.removeChild(this.parent);
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(15).call(this.frame_15).wait(1));

	// Слой_2
	this.p = new lib.p1_mc();
	this.p.name = "p";
	this.p.parent = this;
	this.p.setTransform(-0.2,0.1);

	this.timeline.addTween(cjs.Tween.get(this.p).to({_off:true},1).wait(1).to({_off:false,regX:58.4,regY:-0.1,x:58.2,y:0},0).to({regX:58.3,scaleX:2.2,x:58},12,cjs.Ease.cubicIn).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-58.2,-51.9,116.4,103.8);


(lib.CTA = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// CTA_txt
	this.instance = new lib.CTA_txt();
	this.instance.parent = this;
	this.instance.setTransform(-5.9,2.7);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(8));

	// Слой_3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00BEF5").s().p("AzQlqMAhQACbIiziDIIFCNIhqIDMgjzAAtg");
	this.shape.setTransform(-4.4,-2.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(8));

	// Слой_4
	this.instance_1 = new lib.g2();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-98,-37,0.2,0.2);

	this.instance_2 = new lib.b2();
	this.instance_2.parent = this;
	this.instance_2.setTransform(-98,-37,0.2,0.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1}]}).to({state:[{t:this.instance_2}]},4).wait(4));

	// Слой_1
	this.instance_3 = new lib.b1();
	this.instance_3.parent = this;
	this.instance_3.setTransform(-125,-10,0.2,0.2);

	this.instance_4 = new lib.g1();
	this.instance_4.parent = this;
	this.instance_4.setTransform(-125,-10,0.2,0.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_3}]}).to({state:[{t:this.instance_4}]},4).wait(4));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-127.7,-39,251.6,77.8);


(lib.particle2Movie = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
		this.gotoAndStop(Math.ceil(Math.random()*10));
		//this.gotoAndStop(1);
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(10));

	// Слой_1
	this.instance = new lib.p1();
	this.instance.parent = this;

	this.instance_1 = new lib.p2();
	this.instance_1.parent = this;
	this.instance_1.setTransform(733.1,238,1,1,0,0,0,733.1,238);

	this.instance_2 = new lib.p3();
	this.instance_2.parent = this;

	this.instance_3 = new lib.p4();
	this.instance_3.parent = this;
	this.instance_3.setTransform(0,0,1,1,0,0,0,0,-0.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance,p:{skewY:0}}]}).to({state:[{t:this.instance,p:{skewY:180}}]},2).to({state:[{t:this.instance_1,p:{regX:733.1,regY:238,skewY:0,x:733.1,y:238}}]},1).to({state:[{t:this.instance_1,p:{regX:-58,regY:-9.5,skewY:180,x:-58,y:-9.5}}]},1).to({state:[{t:this.instance_2,p:{skewY:0}}]},1).to({state:[{t:this.instance_2,p:{skewY:180}}]},1).to({state:[{t:this.instance_3,p:{skewY:0}}]},1).to({state:[{t:this.instance_3,p:{skewY:180}}]},1).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-58.2,-51.9,116.4,103.8);


(lib.chips = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		var cloneParticle = new lib.particle2Movie();
		cloneParticle.x = Math.random()*300;
		cloneParticle.y = Math.random()*600;
		cloneParticle.scaleX = cloneParticle.scaleY = Math.random()*.2 +.8;;
		this.addChild(cloneParticle);
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(6));

	// Слой_1
	this.particle = new lib.particle2Movie();
	this.particle.name = "particle";
	this.particle.parent = this;
	this.particle.setTransform(387.8,-29.3,1,1,0,0,0,519,154);

	this.timeline.addTween(cjs.Tween.get(this.particle).wait(6));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-189.4,-235.2,116.4,103.8);


(lib.banner = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// logo
	this.instance = new lib.logo();
	this.instance.parent = this;
	this.instance.setTransform(0,-259.2,0.215,0.215,0,0,0,-0.2,0.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(196));

	// CTA
	this.instance_1 = new lib.CTA();
	this.instance_1.parent = this;
	this.instance_1.setTransform(6,231.7);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(196));

	// txt2
	this.instance_2 = new lib.txt2();
	this.instance_2.parent = this;
	this.instance_2.setTransform(0,-37,0.01,0.01);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(120).to({_off:false},0).to({scaleX:1,scaleY:1},15,cjs.Ease.backOut).wait(45).to({scaleX:0.01,scaleY:0.01},15,cjs.Ease.backIn).wait(1));

	// w2
	this.w2 = new lib.w2();
	this.w2.name = "w2";
	this.w2.parent = this;
	this.w2.setTransform(-190.5,67.5,1,1,0,0,0,26.5,-24.4);

	this.timeline.addTween(cjs.Tween.get(this.w2).wait(35).to({regX:28.6,regY:-22.8,scaleX:0.01,scaleY:0.01,rotation:-67.5,x:124.8},0).to({regX:26.5,regY:-24.4,scaleX:1,scaleY:1,rotation:0},10,cjs.Ease.backOut).wait(60).to({regX:28.6,regY:-22.8,scaleX:0.01,scaleY:0.01,rotation:-67.5},10,cjs.Ease.cubicIn).wait(81));

	// x
	this.oddsX = new lib.x();
	this.oddsX.name = "oddsX";
	this.oddsX.parent = this;
	this.oddsX.setTransform(-196.6,81.1,1,1,0,0,0,21.6,-27.8);

	this.timeline.addTween(cjs.Tween.get(this.oddsX).wait(30).to({regX:20.2,regY:-29.2,scaleX:0.01,scaleY:0.01,rotation:-79.8,x:22.5,y:81.2},0).to({regX:21.6,regY:-27.8,scaleX:1,scaleY:1,rotation:0,x:22.4,y:81.1},10,cjs.Ease.backOut).wait(65).to({regX:20.2,regY:-29.2,scaleX:0.01,scaleY:0.01,rotation:-79.8,x:22.5,y:81.2},10,cjs.Ease.backIn).wait(81));

	// w1
	this.w1 = new lib.w1();
	this.w1.name = "w1";
	this.w1.parent = this;
	this.w1.setTransform(-243,67.6,1,1,0,0,0,-26.1,-24.3);

	this.timeline.addTween(cjs.Tween.get(this.w1).wait(25).to({regX:-27.4,regY:-19.4,scaleX:0.01,scaleY:0.01,rotation:81.3,x:-123},0).to({regX:-26.1,regY:-24.3,scaleX:1,scaleY:1,rotation:0},10,cjs.Ease.backOut).wait(70).to({regX:-27.4,regY:-19.4,scaleX:0.01,scaleY:0.01,rotation:81.3},10,cjs.Ease.backIn).wait(81));

	// w2Txt
	this.instance_3 = new lib.w2Txt();
	this.instance_3.parent = this;
	this.instance_3.setTransform(193.7,-53.9);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(10).to({_off:false},0).to({x:81.7},15,cjs.Ease.cubicOut).wait(80).to({x:193.7},15,cjs.Ease.cubicIn).to({_off:true},1).wait(75));

	// ic2
	this.instance_4 = new lib.ic2();
	this.instance_4.parent = this;
	this.instance_4.setTransform(194,22,1,1,179);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(10).to({_off:false},0).to({rotation:0,x:82},15,cjs.Ease.cubicOut).wait(80).to({rotation:179,x:194},15,cjs.Ease.cubicIn).to({_off:true},1).wait(75));

	// w1Txt
	this.instance_5 = new lib.w1Txt();
	this.instance_5.parent = this;
	this.instance_5.setTransform(-197.1,-53.7);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(10).to({_off:false},0).to({x:-81.1},15,cjs.Ease.cubicOut).wait(80).to({x:-195.1},15,cjs.Ease.cubicIn).to({_off:true},1).wait(75));

	// ic1
	this.instance_6 = new lib.ic1();
	this.instance_6.parent = this;
	this.instance_6.setTransform(-198,22,1,1,-179,0,0,-0.1,-0.1);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(10).to({_off:false},0).to({regX:0,regY:0,rotation:0,x:-82},15,cjs.Ease.cubicOut).wait(80).to({rotation:-179,x:-196},15,cjs.Ease.cubicIn).to({_off:true},1).wait(75));

	// vs
	this.instance_7 = new lib.vs();
	this.instance_7.parent = this;
	this.instance_7.setTransform(-0.2,21.7,0.013,0.022);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(10).to({_off:false},0).to({scaleX:1,scaleY:1,x:-0.1},15,cjs.Ease.backOut).wait(80).to({scaleX:0.01,scaleY:0.02,x:-0.2},15,cjs.Ease.backIn).to({_off:true},1).wait(75));

	// mainTxt
	this.instance_8 = new lib.mainTxt();
	this.instance_8.parent = this;
	this.instance_8.setTransform(0,-160.9,0.01,0.01);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).to({scaleX:1,scaleY:1},15,cjs.Ease.backOut).wait(90).to({scaleX:0.01,scaleY:0.01},15,cjs.Ease.backIn).to({_off:true},1).wait(75));

	// glitch
	this.instance_9 = new lib.chips();
	this.instance_9.parent = this;
	this.instance_9.setTransform(-150,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(196));

	// bg
	this.instance_10 = new lib.bg();
	this.instance_10.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(196));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-339.3,-535.1,489.4,835.2);


// stage content:
(lib._300x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// cover
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#666666").ss(2,1,1).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// banner
	this.instance = new lib.banner();
	this.instance.parent = this;
	this.instance.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-39.3,64.9,490.4,836.2);
// library properties:
lib.properties = {
	id: '04B76919AEF842B6A6F01C7C9A429D40',
	width: 300,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/b1.png", id:"b1"},
		{src:"images/b2.png", id:"b2"},
		{src:"images/g1.png", id:"g1"},
		{src:"images/g2.png", id:"g2"},
		{src:"images/glitch1.png", id:"glitch1"},
		{src:"images/glitch2.png", id:"glitch2"},
		{src:"images/glitch3.png", id:"glitch3"},
		{src:"images/glitch4.png", id:"glitch4"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['04B76919AEF842B6A6F01C7C9A429D40'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;