(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 300,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	manifest: [
		{src:"images/bgImg.jpg", id:"bgImg"},
		{src:"images/igor.png", id:"igor"},
		{src:"images/milk.png", id:"milk"},
		{src:"images/playBtn.png", id:"playBtn"},
		{src:"images/tanya.png", id:"tanya"}
	]
};



// symbols:



(lib.bgImg = function() {
	this.initialize(img.bgImg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.igor = function() {
	this.initialize(img.igor);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,231,472);


(lib.milk = function() {
	this.initialize(img.milk);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,172);


(lib.playBtn = function() {
	this.initialize(img.playBtn);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,35,39);


(lib.tanya = function() {
	this.initialize(img.tanya);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,247,451);


(lib.urText = function() {
	this.initialize();

	// Layer 5
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0067AD").s().p("ALUBHQgGgBgDgEQgDgEgDgFQgCgEAAgHQAAgHACgEQADgGADgDIAJgGQAEgCAHAAQAHAAAEACQAEACAEAEQAEADACAFQACAHAAAFIgCALQgBAFgFAEIgIAFQgEACgHAAQgGAAgFgCgALXAaQgEABgCADIgFAHQgCAEABAFQgBAFACADQABAEAEADQABADAFACIAIABQAFAAADgBQAEgCADgDIAEgHQABgDAAgFQAAgFgBgEQgBgDgDgEQgDgDgEgBQgEgCgEAAIgIACgAj2BHQgFgBgEgEQgEgEgCgFQgCgGAAgFIACgLIAGgJIAJgGQAEgCAGAAQAHAAAEACQAGACADAEIAGAIQACAFAAAHQAAAGgCAFIgGAJQgCADgHACQgEACgHAAQgGAAgEgCgAj0AaQgDABgDADIgFAHQgBAEAAAFQAAAFABADQACAEADADQADADADACIAIABQAFAAAEgBQAEgCADgDQADgDAAgEQACgDAAgFQAAgFgCgEIgDgHQgDgDgEgBQgEgCgFAAIgIACgAqiBHQgFgBgEgEQgEgEgBgFQgDgFAAgGQAAgFADgGQABgFAEgEIAIgGQAFgCAHAAQAGAAAFACQAEACAFAEIAFAIQACAFAAAHQAAAGgCAFQgCAGgDADQgDADgGACQgFACgGAAQgHAAgEgCgAqfAaQgEABgDADIgFAHQgBAEAAAFQAAAFABADIAFAHQADADAEACIAIABQAFAAADgBQAEgCACgDQADgDACgEQABgDABgFQAAgFgCgEIgFgHQgDgDgDgBQgDgCgFAAIgIACgAubBHQgFgBgEgEQgEgEgCgFQgCgFAAgGIACgLIAGgJIAJgGQAEgCAHAAQAGAAAEACQAFACAEAEIAGAIQACAFAAAHQAAAGgCAFQgDAGgDADQgCADgHACQgEACgGAAQgHAAgEgCgAuZAaQgDABgDADIgEAHQgCAEAAAFQAAAFACADIAEAHQADADADACIAJABQAEAAAEgBQAEgCADgDQACgDACgEIABgIQAAgFgCgEIgDgHQgDgDgEgBQgEgCgEAAIgJACgAw1BJIgFgCIgEgDIgDgDIAEgEIACACIAEACIAEACIADAAIAFAAIAEgCIACgEQABAAAAAAQAAgBAAAAQAAgBAAgBQABAAAAgBQAAgEgDgCQgDgDgFAAIgGAAIAAgGIAFAAIAEgBIADgBIACgDIAAgEQAAgEgCgDQgCgCgGAAQgDAAgDACQgDABgCADIgFgEIAHgGQAFgCAFAAQAIAAAEAEQAEAEAAAGQAAAEgCADQgBADgFADQAGABABADQADADAAAGQAAADgCADIgDAFQgCACgEABIgIABgA1eBHQgFgBgEgEQgDgEgDgFQgCgGAAgFIACgLIAGgJIAJgGQAEgCAHAAQAGAAAFACQAEACAEAEIAGAIQACAFAAAHQAAAGgCAFQgDAGgDADQgDADgFACQgFACgGAAQgHAAgEgCgA1bAaQgEABgDADIgEAHQgCAEAAAFQAAAFACADQABAEADADQADADAEACIAIABQAEAAAEgBQADgCADgDQAEgDABgEIABgIQAAgFgBgEIgFgHQgDgDgDgBQgEgCgEAAIgIACgAVkBIIgBgDIABgDQAAgBABAAQAAAAABAAQAAgBABAAQAAAAAAAAQABAAAAAAQABAAAAABQAAAAABAAQAAAAAAABIACADIgCADIgDABgAVRBJIgHgRIgZAAIgHARIgGAAIAWg3IAGAAIAXA3gAVHAyIgKgXIgKAXIAUAAgAUQBJIAAgZIgeAAIAAAZIgHAAIAAg2IAHAAIAAAXIAeAAIAAgXIAGAAIAAA2gATPBJIAAg2IAHAAIAAA2gAS6BJIgHgRIgZAAIgGARIgHAAIAXg3IAFAAIAYA3gASxAyIgKgXIgKAXIAUAAgARnBJIAAg2IAOAAQAGAAADABIAHAEQACADABACIABAGQAAAEgCADQAAACgDADIgGAEQgDABgGAAIgDAAIgFAAIAAAVgARtAuIAFAAIADAAQAHAAACgDQAEgDAAgFQAAgFgDgCQgDgDgHAAIgIAAgARRBJIgYgcIAXgaIAIAAIgYAZIAZAdgAQxBJIAAg2IAGAAIAAA2gAQABIIgDgBIACgGIACABIADABQAAAAABAAQAAAAABgBQAAAAAAAAQABgBAAAAIADgEIABgCIgYgoIAHAAIAUAiIAPgiIAGAAIgSApQgDAHgDADQgDADgEAAgANzBJIAAgUIgKAAIgOAUIgIAAIAQgVIgFgDIgDgDIgCgEIgBgGIABgGQABgFADgBIAHgEIAVgBIAAA2gANmAaIgEACIgDAEIAAAEIAAAEIADADIACACIAEACIALAAIAAgWIgHAAgAM+BJIAAg2IAGAAIAAA2gAMKBJIAAg2IAPAAQAGAAADABIAGAEIAEAFIAAAGIgBAHIgEAFIgFAEQgEABgFAAIgIAAIAAAVgAMRAuIADAAIAFAAQAGAAADgDQADgDAAgFQAAgFgCgCQgEgDgGAAIgIAAgAKkBJIAAgwIgTAAIAAgGIAsAAIAAAGIgTAAIAAAwgAJ+BJIAAgrIghArIgGAAIAAg2IAHAAIAAArIAggrIAGAAIAAA2gAImBJIAAg2IANAAQAHAAADABIAHAEQABACABADIABAGIgBAHIgDAFIgGAEQgEABgFAAIgIAAIAAAVgAIsAuIAEAAIAEAAQAGAAADgDQADgDABgFQAAgFgDgCQgDgDgHAAIgIAAgAH1BJIAAg2IAfAAIAAAGIgYAAIAAARIAVAAIAAAHIgVAAIAAASIAZAAIAAAGgAHPBJIAAgwIgSAAIAAgGIAsAAIAAAGIgTAAIAAAwgAGbBIIgBgDIABgDQAAgBABAAQAAAAABAAQAAgBABAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAABAAQAAAAAAABIABADIgBADIgCABgAFbBJIgYgcIAYgaIAIAAIgZAZIAaAdgAE8BJIAAg2IAGAAIAAA2gAEnBJIgGgRIgZAAIgHARIgHAAIAYg3IAFAAIAXA3gAEdAyIgJgXIgKAXIATAAgADmBJIAAgwIgcAAIAAAwIgHAAIAAg2IAqAAIAAA2gACaBJIgHgRIgZAAIgHARIgGAAIAWg3IAHAAIAWA3gACQAyIgKgXIgKAXIAUAAgABGBJIAAg2IAPAAQAFAAAFABIAGAEQACACAAADIABAGIgBAHIgDAFIgGAEQgDABgGAAIgDAAIgFAAIAAAVgABNAuIAEAAIAEAAQAGAAAEgDQACgDAAgFQAAgFgCgCQgCgDgIAAIgIAAgAAgBJIAAgwIgTAAIAAgGIAtAAIAAAGIgTAAIAAAwgAgZBJIAAg2IAcAAIAAAGIgWAAIAAARIAUAAIAAAHIgUAAIAAASIAXAAIAAAGgAhABJIAAgwIgSAAIAAgGIAsAAIAAAGIgTAAIAAAwgAjAATIAPAAIAIABIAFACIADAFIABAFQAAAEgDAEQgCADgEABQAGACACADQADADAAAFQAAAEgBADIgFAFIgGADIgWABgAi5BCIADABIAFAAQAGAAADgDQADgCAAgFQAAgFgDgCQgCgCgHAAIgIAAgAi5AqIAIAAIAEAAIADgCIADgDIABgEQgBgIgKAAIgIAAgAkmBJIAAgwIgTAAIAAgGIAsAAIAAAGIgTAAIAAAwgAnOBIIgDgBIACgGIACABIACABIAEgCIADgEIAAgCIgYgoIAHAAIAUAiIAPgiIAHAAIgSApQgDAHgEADQgDADgEAAgAn7BJIAAgwIgTAAIAAgGIAtAAIAAAGIgTAAIAAAwgAocBJIgYgcIAXgaIAIAAIgYAZIAaAdgAo8BJIAAg2IAGAAIAAA2gApsBJIAAg2IAfAAIAAAGIgZAAIAAARIAWAAIAAAHIgWAAIAAASIAZAAIAAAGgArfBJIAAg2IANAAQAGAAAEABIAGAEQADADAAACIABAGQAAAEgBADQAAACgDADIgHAEQgDABgFAAIgEAAIgEAAIAAAVgArZAuIAEAAIADAAQAHAAADgDQAEgDAAgFQgBgFgDgCQgDgDgGAAIgIAAgAr6BJIAAgwIgeAAIAAAwIgGAAIAAg2IAqAAIAAA2gAtlBJIAAg2IAOAAQAGAAADABIAHAEQACACABADIABAGIgBAHIgEAFIgGAEQgDABgGAAIgDAAIgFAAIAAAVgAtfAuIAFAAIADAAQAHAAACgDQAEgDAAgFQAAgFgDgCQgDgDgHAAIgIAAgAvLBJIAAgwIgTAAIAAgGIAsAAIAAAGIgTAAIAAAwgAvmBJIgGgRIgZAAIgHARIgHAAIAYg3IAGAAIAWA3gAvvAyIgKgXIgKAXIAUAAgAxYBJIAAg2IAGAAIAAA2gAx0BJIAAgZIgeAAIAAAZIgGAAIAAg2IAGAAIAAAXIAeAAIAAgXIAGAAIAAA2gAytBJIgGgRIgZAAIgHARIgHAAIAYg3IAGAAIAWA3gAy2AyIgKgXIgKAXIAUAAgAz2BJIAAg2IAeAAIAAAGIgXAAIAAAwgA0oBJIAAg2IAOAAQAGAAADABIAHAEQACACABADIABAGIgBAHIgEAFIgGAEQgEABgFAAIgDAAIgFAAIAAAVgA0iAuIAFAAIADAAQAHAAACgDQAEgDAAgFQAAgFgDgCQgDgDgHAAIgIAAgAF9BDIAKgOIgLgNIAEgDIAPAQIAAABIgPAQgAFtBDIAMgOIgMgNIAFgDIAOAQIAAABIgOAQgAhuA2IAAgBIAPgQIAEADIgLANIALAOIgEADgAh8A2IAAgBIAOgQIAFADIgMANIALAOIgEADgAOiA3IAAgGIAvAAIAAAGgAmKAwIAAgFIAwAAIAAAFgATWANIgBgDIABgCIADgBIADABIABACIgBADIgDABgATKANIgBgDIABgCIADgBIACABIABACIgBADIgCABgAOsgIIAAgKIgqAAIAAAKIgFAAIAAgQIAFAAIADgEIACgHIACgLQACgGAAgJIAAgLIAhAAIAAAwIAHAAIAAAQgAOQgrIgFAQIgCADIAcAAIAAgpIgTAAgArSgIIAAgKIgqAAIAAAKIgGAAIAAgQIAGAAIACgEQACgCABgFIACgLQABgGAAgJIABgLIAgAAIAAAwIAIAAIAAAQgArugrIgFAQIgCADIAbAAIAAgpIgTAAgAVTgTIgGgEQgCgCgBgEIgBgIQgBgIADgFQADgGADgFIAJgHQAEgEAFAAIACAEIgHADIgHAFIgEAHIgDAJIAEgFQADgCAGAAIAGABIAEAEQADACABADQABADAAAEQAAAEgBADIgFAFIgEAEQgDABgEAAQgEAAgEgCgAVWgsIgDACIgCACIgCADIABAFIACAFIAEADIAFABIAEgBIAEgCIACgEIAAgEIAAgEIgCgEIgEgCIgEgBgAQ6gTQgEgCgDgFIAEgFQACAEAEACIAHACQAEAAAEgDQACgDABgEQgBgEgDgDQgDgCgEAAIgFAAIAAgGIAEAAIADgBIADgCIADgDIAAgEQAAgEgCgCQgCgCgEAAQgFAAgCACQgDABgBAEIgEgFQABgEAFgCQAEgCAFAAQAHAAAEADQAEAEAAAGQAAAEgDAEQgBAEgEABIAEACIADADIACAEIABAEQAAAFgBACIgEAFIgFADIgHABQgFAAgFgCgAPNgTQgFgCgEgEQgDgDgDgFQgCgFAAgHQAAgGACgFIAGgIIAJgGQAEgCAHAAQAGAAAFACQAFACADADQAEAEACAFQACAFAAAGQAAAHgCAEQgCAGgEADQgEAEgEACIgLACIgLgCgAPQhBIgHAFQgDADgBAEQgCAEAAAEQAAAFACAEQABAEADADQACACAFACIAIACQAEAAAEgCQADgBADgDIAFgHQABgEAAgFQAAgEgBgEQgCgEgDgDIgGgFQgEgBgEAAIgIABgANGgTIgGgEQgCgCgBgEIgCgIQAAgHADgGQACgGAEgFIAIgHQAGgEADAAIADAEIgHADIgGAFQgEAEgBADQgCADgCAGIAGgFQACgCAGAAIAFABIAGAEQACACAAADQACADAAAEQAAAEgCADIgDAFIgGAEQgDABgDAAQgFAAgDgCgANJgsIgDACIgDACIgBADIABAFIACAFIAEADIAFABIAEgBIADgCIADgEIABgEIgBgEIgDgEIgDgCIgFgBgAKCgWQAJgBAGgHQAFgFACgKQgCAEgDABQgEACgDAAQgEAAgDgCIgFgDIgDgFQgBgDgBgEQABgEABgDIAEgGIAFgDIAHgBQAFAAADABIAGAEIADAHIABAIQAAAIgCAGQgDAHgDADIgIAIIgLADgAKJhBIgEACIgCADIgBAFIABAEIACADIAEADIAEABIAFgBIADgCIACgCIABgDIAAgFIgCgFIgEgDIgFgBgAIXgRIgEgCIgEgCIgCgEIADgFQACAEAEABQADACADAAIAFgBIADgCIACgEIABgEIgBgFIgDgEIgEgCIgFgBIgFABIgEABIAEgcIAYAAIAAAHIgTAAIgCAOIACAAIADAAIAGABIAGADIADAFQABADAAAEQAAAFgBADIgEAFQgDADgDABQgDABgDAAgAGygSIgFgCIgEgCIgDgDIAEgFQAAABABAAQAAABAAAAQABAAAAAAQABABAAAAIAEACIADABIADABIAGgBIADgCIADgDIABgEQAAgFgDgCQgEgCgEAAIgGAAIAAgGIAFAAIAEgBIADgCIACgDIAAgDQAAgFgCgCQgEgCgDAAQgEAAgDABQgDACgDADIgDgEQADgEAEgCQAEgCAFAAQAIAAAEADQAEAEAAAHQAAAEgCADQgBADgFACIAAABQAFABADADQACADAAAFQAAAEgCADQgCAEgBABIgGADIgHABgAoNgTIgJgFIgGgJQgCgFAAgHQAAgGACgEQABgFAEgEQAEgEAFgCQAEgCAHAAQAFAAAEABQAEABAEADIgDAFIgGgDIgIgBIgIABQgEACgDADIgEAHQgBAEAAAEQAAAGABADQADAFACACQACACAEACQAFACAEAAIAHgBIAHgEIADAFIgEADIgIADIgGAAQgFAAgFgCgAsugTQgGgCgDgEQgFgEgBgEQgCgFAAgHQAAgGACgFQABgEAFgEQADgEAFgCQAFgCAGAAQAHAAAEACQAGACADADQAEAEACAFQACAGAAAFQAAAGgCAFQgCAFgEAEQgEAEgFACQgGACgFAAQgEAAgGgCgAsshBIgHAFIgDAHQgCADAAAFQAAAFACAEIADAHQAEADADABQAEACAEAAQAFAAAEgCQAEgCACgCQADgDABgEQACgEAAgFQAAgFgCgDIgEgHIgGgFQgEgBgFAAQgEAAgEABgAukgTQgGgCgDgEIgGgIQgCgFAAgHQAAgGACgFQADgGADgCIAJgGQADgCAIAAQAGAAAEACIAJAFQAEAEACAFIACALQAAAFgCAGQgCAGgEADQgEAEgFACIgKACIgLgCgAuihBIgHAFIgDAHQgCAEAAAEQAAAFACAEIADAHQADADAFABIAIACIAIgCQAEgBADgDIADgHQACgEAAgFQAAgEgCgEQgBgEgDgDIgGgFQgEgBgEAAQgFAAgEABgA0DgTQgFgCgDgEQgEgDgDgFQgBgHAAgFIABgLQADgFAEgDQAEgEAEgCQAFgCAGAAQAGAAAFACQAGACADADIAGAJQABAFAAAGQAAAHgBAEIgGAJQgEAEgFACIgLACIgLgCgA0AhBIgHAFQgDADgBAEQgBAEAAAEQAAAFABAEQABAEADADQAEADADABIAIACQAFAAAEgCQADgBADgDQADgEABgDQACgEgBgFQABgEgCgEIgEgHIgHgFQgDgBgFAAIgIABgAV4gTIgBgDIABgDIADgBIAEABIABADIgBADIgEACQAAAAAAAAQgBAAAAgBQgBAAAAAAQgBAAAAgBgAUCgTQgDgCgDgEIgDgIIAAgMIAAgLQABgFACgDQACgEAEgCQAEgCAEAAQAFAAADACQADACACAEIAEAIIABALIgBAMIgEAIQgCAEgDACQgCACgGAAQgEAAgEgCgAUCg9QgDAHAAAJQAAAKADAGQADAGAFAAQAHAAACgGQACgGAAgKQAAgJgCgHQgDgFgGAAQgGAAgCAFgAS5gTIgBgDIABgDQAAAAAAAAQABAAAAAAQAAgBABAAQAAAAABAAIADABIABADIgBADIgDACQAAAAgBAAQAAAAgBgBQAAAAAAAAQgBAAAAgBgARjgTIgCgDIACgDQAAAAAAAAQABAAAAAAQAAgBABAAQAAAAABAAIADABIABADIgBADIgDACQgBAAAAAAQAAAAgBgBQAAAAAAAAQgBAAAAgBgAL2gTQgFgCgBgEIgDgIIgBgMIABgLIACgIQADgEADgCQAEgCAEAAQAEAAAEACQADACACAEIADAIIABALIgBAMIgDAIQgCAEgDACQgDACgFAAQgFAAgCgCgAL1g9QgDAHAAAJQAAALADAFQADAGAFAAQAGAAACgGQADgGAAgKQAAgJgDgHQgCgFgGAAQgFAAgDAFgAKsgTIgCgDIACgDQAAAAAAAAQABAAAAAAQAAgBABAAQAAAAABAAQABAAAAAAQABAAAAABQAAAAABAAQAAAAAAAAIABADIgBADQAAABAAAAQgBAAAAAAQAAABgBAAQAAAAgBAAQgBAAAAAAQAAAAgBgBQAAAAAAAAQgBAAAAgBgAJXgTQgDgCgCgEIgEgIIAAgMIAAgLIADgIQADgEADgCQAEgCAEAAQAFAAADACQAEACABAEIAEAIIABALIgBAMIgEAIQgCAEgDACQgCACgGAAQgFAAgDgCgAJWg9QgCAHAAAJQAAAKACAGQADAGAGAAQAHAAACgGQACgGAAgKQAAgJgCgHQgDgFgGAAQgGAAgDAFgAI7gTIgCgDIACgDQAAAAAAAAQAAAAAAAAQABgBAAAAQABAAAAAAIAEABIABADIgBADIgEACQAAAAAAAAQgBAAAAgBQgBAAAAAAQAAAAAAgBgAmPgRIgFgBIgGAAIAAg1IADgBIALAAIAIABQADABADACIADAEIABAGQAAAFgDADQgCADgFABIAAAAQAFABADADQADADAAAGQAAAEgBADQgCAEgCABQgCACgEABIgIABgAmUgYIAIAAQAHAAADgCQADgCAAgFQAAgFgDgCQgEgCgFAAIgJAAgAmUhBIAAARIAJAAIAEgBIADgBIACgDIACgEQAAgJgMAAIgEAAgAtjgRIgFgBIgGAAIAAg1IACgBIAMAAIAIABQADABADACIADAEIABAGQAAAFgDADQgCADgFABIAAAAQAFABADADQADADAAAGQAAAEgBADQgCAEgCABQgCACgEABIgIABgAtogYIAIAAQAHAAADgCQADgCAAgFQAAgFgDgCQgEgCgFAAIgJAAgAtohBIAAARIAJAAIAEgBIADgBIACgDIABgEQAAgJgLAAIgEAAgAUxgSIAAgtIgIAGIgDgFIANgKIAFAAIAAA2gATMgSIAAgFIAPgQIAGgJQADgFAAgEQAAgEgDgCQgCgDgEAAQgDAAgDACQgDADgBAEIgFgDIABgFIAEgEIAFgCIAFgBQAEAAACABQADABADACIACAEIABAFIgCAIIgDAHIgFAHIgMAOIAYAAIAAAFgASggSIAAgtIgIAGIgCgFIAMgKIAFAAIAAA2gAR/gSIAAgtIgHAGIgEgFIAOgKIADAAIAAA2gAQegSIAAgtIgIAGIgEgFIAOgKIAEAAIAAA2gAMlgSIAAgtIgJAGIgCgFIAMgKIAFAAIAAA2gAK/gSIAAgFIAHgHIAOgSQADgFgBgEQAAgDgBgDQgCgDgGAAQgCAAgDACQgEADAAAEIgFgDIACgFIADgEIAFgCIAFgBQAEAAADABIAFADIACAEIABAFIgBAIIgIAOIgOAOIAZAAIAAAFgAH2gSIAAgtIgIAGIgDgFIAOgKIADAAIAAA2gAFwgSIAAgvIgTAAIAAgHIAsAAIAAAHIgTAAIAAAvgAE0gSIAAg2IAeAAIAAAHIgXAAIAAARIAWAAIAAAGIgWAAIAAASIAYAAIAAAGgAEagSIAAgYIgeAAIAAAYIgGAAIAAg2IAGAAIAAAYIAeAAIAAgYIAGAAIAAA2gADDgSIAAg2IAPAAQAGAAAEACIAGADIADAGIABAGIgBAGIgEAGQgDADgDAAQgEACgEAAIgJAAIAAAUgADKhBIAAAUIAEABIAEAAQAGAAAEgDQADgEAAgEQAAgFgDgDQgDgDgGAAgACUgSIAAg2IAeAAIAAAHIgYAAIAAARIAVAAIAAAGIgVAAIAAASIAYAAIAAAGgABugSIAAgvIgTAAIAAgHIAsAAIAAAHIgTAAIAAAvgABHgSIAAgYIgeAAIAAAYIgGAAIAAg2IAGAAIAAAYIAeAAIAAgYIAHAAIAAA2gAAHgSIAAg2IAGAAIAAA2gAgqgSIAAg2IAGAAIAAA2gAhBgSIgVgcIAUgaIAJAAIgXAaIAXAcgAhegSIAAg2IAGAAIAAA2gAh+gSIAXgcIgWgaIAIAAIAVAaIgWAcgAingSIAAg2IAeAAIAAAHIgYAAIAAARIAWAAIAAAGIgWAAIAAASIAZAAIAAAGgAjZgSIAAg2IAOAAQAGAAAEACIAFADIAEAGIABAGQAAADgBADQgBADgDADQgDADgDAAQgEACgEAAIgIAAIAAAUgAjShBIAAAUIADABIAFAAQAGAAADgDQADgDAAgFQAAgFgDgDQgDgDgGAAIgFAAgAkJgSIAAg2IAeAAIAAAHIgXAAIAAARIAVAAIAAAGIgVAAIAAASIAYAAIAAAGgAkkgSIAAgrIgTAbIgBAAIgTgbIAAArIgHAAIAAg2IAHAAIAUAcIAUgcIAGAAIAAA2gAnKgSIAAgUIgKAAIgOAUIgHAAIAPgVIgFgCIgDgDIgDgFIAAgFIABgHIAEgGIAHgDQAEgCAFAAIAMAAIAAA2gAnXhBIgEADIgDADIAAAFIAAAEIACADIAEACIADABIALAAIAAgVIgEgBIgDAAgApLgSIAAg2IAHAAIAAAUIAIAAQAKAAAFAFQAEAEABAIQgBAJgFAEQgGAEgKAAgApEgtIAAAVIAHAAQAGAAAEgDQAEgCAAgGQAAgFgEgDQgEgDgGAAIgEAAgApxgSIAAgvIgSAAIAAgHIAsAAIAAAHIgTAAIAAAvgAqXgSIAAgrIghArIgGAAIAAg2IAHAAIAAAsIAhgsIAFAAIAAA2gAvigSIAAg2IAOAAQAGAAADACQAFABACACIADAGIABAGIgBAGIgEAGQgDADgDAAQgDACgGAAIgHAAIAAAUgAvbhBIAAAUIADABIAEAAQAHAAACgDQAEgDAAgFQAAgFgDgDQgDgDgHAAIgDAAgAv8gSIAAgvIgeAAIAAAvIgGAAIAAg2IAqAAIAAA2gAxcgSIAAgvIgTAAIAAgHIAsAAIAAAHIgSAAIAAAvgAx8gSIgZgcIAYgaIAIAAIgYAaIAZAcgAydgSIAAg2IAHAAIAAA2gAzMgSIAAg2IAeAAIAAAHIgYAAIAAARIAWAAIAAAGIgWAAIAAASIAYAAIAAAGgA1AgSIAAg2IAOAAQAGAAAEACIAFADIAEAGIABAGQAAADgBADQgBADgDADQgDADgDAAQgDACgFAAIgIAAIAAAUgA05hBIAAAUIADABIAEAAQAGAAAEgDQADgEAAgEQAAgFgDgDQgDgDgGAAIgFAAgA1bgSIAAgvIgdAAIAAAvIgHAAIAAg2IArAAIAAA2g");
	this.shape.setTransform(0,0,1.03,1.031);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-145.8,-31.8,291.7,63.7);


(lib.tanya_1 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.tanya();
	this.instance.setTransform(-123,-225);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-123,-225,247,451);


(lib.t4 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAoC0QgFhGAEh1QgDh8gHg0QAAgFgfgDIAGEyQABA4gGAaQgLAkgbADIgIAAQgMgCgKgEQgRgGAEgUQAFgUAXAGIAHAAQALgHAAhKQABgZgDglIgCgrQABgbgBgtIgCh/QgZgDgCgGQgHggAVAAQAbgBAhAEIAyADQASAAgBBGIACA3IAAAqQAAAsAJDXQADAlgKABQgGAEgFAAQgUAAgFg6g");
	this.shape.setTransform(32.2,25.4,0.8,0.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhVDnQgKgQAEg/QABgOAHgsIAKg8QABgMAThTIAVhbQAIgtAGgOQAMghAPALQAIAGAIAxIAXCTQANBYAPA+QAWBWgGASQgcARgLgZQgCgDgNg8IgZhvIABAAIgBAAQgFACgLAAIgVAAQgLAogGA2QgLBfgDAAQgKAFgHAAQgIAAgFgGgAgIg4IgKAyQATAAADgCQAAg+gHgEIAAAAQgCAAgDASg");
	this.shape_1.setTransform(17.7,25.8,0.8,0.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgLDlQgOgOACg0IADijQAChXAAhHIAAguQADgVAPgHQAPgIAFAiIAEB+QACAlgFBuQgFBoADAtQAAALgIAEQgHAEgEAAQgGAAgFgGg");
	this.shape_2.setTransform(6.5,25.8,0.8,0.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhBD4QgMgCgDgdIAAl6QAAhTAIgBQALgHAzAFQA1AEAUAPQANAJAEAsQAEAwgdAeQgKALglAEQgfADAAADQAMAAgXDxIgBA7QgEAagRAAIgJgCgAgmjNQgFAEAIBKQAAAIAhgCQAfAAALgMQAGgHABgZQACgZgIgIQgJgMgjgCIgLAAQgaAAACAHg");
	this.shape_3.setTransform(-3.5,25,0.8,0.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgtDLQgKh4gIihQAAgUgHhBQgEgvAWgLQAGgCBFgMQARgCAJAHQAJAJgIANQgIAOgbABQgdACgLAHQAAAdAFAyQAFA2gBAbQAgAGgDASQgBAJgXAJQACAVAEBFQAEA8ACAcQAogLAbANQAGAEgEANQgFAOgGAAIhUAHQgUAAAAghg");
	this.shape_4.setTransform(-18.3,25.8,0.8,0.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAGDvQglAAgTgfQgOgXgHhPIgFhxQgDiKAKgiQAQgzAqgIQAYgDAZAQQAQAJAKAhQAHAUgQAKQgQAKgGgLQgMgdgQgFQgTgGgIAhQgDAPgBApQgDCSAJBQQAJBXAYgFQAXgEADgNQADgOAOgFQAIgCAIAIQAFAHAAAEQACAFgOAVQgUAdglAAIgCAAg");
	this.shape_5.setTransform(-31.5,25.9,0.8,0.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgKD0QgZgEgKgIQgPgKgBg2IgJkJIgEg5IgEg9QAAgXAQgGIAUABQAOAAABAkIACA1IADBpQBCgdAaBOQANBMgGA8QgMBYgnAQQgKAFgPAAIgLgBgAgSgPQgDACAAACIAECdQACA2AIAEQAJADAOgPQAMgPACgMQAMhGgMhHQgHgrgXAAQgIAAgKAEg");
	this.shape_6.setTransform(53.4,-25.5,0.8,0.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAFDvQglAAgSggQgPgYgGhNIgFhxQgDiNAKggQAQgzAqgHQAZgEAYARQARAKAIAgQAIAUgRAKQgPALgGgMQgNgdgPgFQgUgGgHAhQgDAPgBApQgECPAJBTQAKBXAYgFQAXgEACgNQADgOAPgFQAIgCAHAIQAGAGAAAFQABAGgNAUQgUAdgmAAIgCAAg");
	this.shape_7.setTransform(38.6,-24.8,0.8,0.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgvDxQgMAAgGgKQgFgaABhLQABgkgChdQgBhNACg0IABhcQABgVAOAAQAWABAFAiQACARgCAuIgCDWIAJghQAjhiAChEQAAgKAFgcIAGgjQAEgcAOgFQAOgFADAOQAHA0AABRIAACOQABAdgDAzQgDA7ABARQgBAlgUgGQgMAFgHgRQgFgOABgVIALjTQggC4gYA/QgLAQgNAAIgBgBg");
	this.shape_8.setTransform(23.3,-24.5,0.8,0.8);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgJDrQgUgJADhTQABgNgCgQIAAgcQAAiPAIh9QgBAIgqgLQgagHACgUQABgXBAgDQALAABIADQATAEAEAVQAGAWgLAAQgIADgYgDQgUgDAAAFQgIA1AAByQACCCgDAyIAAAbIAAAdQgDAWgOAAQgEAAgHgEg");
	this.shape_9.setTransform(8.8,-25.1,0.8,0.8);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgvDxQgLAAgGgKQgGgaABhLIAAiBQgChaACgnIABhcQACgVANAAQAWABAFAiQACALgBA0IgCDVIAJggQAjhlABhBQAAgIAFgeIAGgjQAEgcAPgFQAOgFADAOQAHAwgBBVIAACOQABAagCA2QgDA7AAARQAAAlgVgGQgMAFgGgRQgFgOAAgVIALjTQggC5gYA+QgLAQgMAAIgCgBg");
	this.shape_10.setTransform(-6.3,-24.5,0.8,0.8);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgMD0QgYgEgKgIQgOgKgCg2IgJkJIgEg5QgCglACgQQADgeAsgGQApgFAcAYQAUATAHAOQAPAigMAjQgKAhgeAUQAYApAHAeQAUBIgGA+QgNBYglAQQgLAFgPAAIgMgBgAgXguIAFDAQACA3AIADQAKADANgPQAMgOADgNQAMhGgMhHQgOhFgkgFQgBABAAAAQgBABAAAAQgBABAAAAQAAABAAAAgAgcjPQAAAWACAfIADA3QAbACARgUQASgWgGgdQgDgTgTgNQgLgIgQAAIgMABg");
	this.shape_11.setTransform(-21.2,-25.5,0.8,0.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgvDxQgLAAgGgKQgGgaABhLIAAiBQgChaACgnIABhcQACgVANAAQAWABAFAiQACALgBA0IgCDVIAJggQAihjAChDQAAgIAFgeIAGgjQAEgcAPgFQAOgFACAOQAIAvgBBWIAACOQABAagCA2QgEA0ABAYQAAAlgVgGQgMAFgGgRQgFgOAAgVIALjTQghC8gXA7QgLAQgMAAIgCgBg");
	this.shape_12.setTransform(-36.4,-24.5,0.8,0.8);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AhWEPQgIgIABgSQAJhIACgFQAHgPAWgEQAHghABgZQACgSABgsIAAg9QACgUACg1IAChPQACggACgQQgZgEgBgGQgGggAVAAQAVgBAnAEIArAEQATAAAABFIgBA3IgCAqQgDA0AACiIACAlQASADABAPIgEBWQAAAHgNAFQgNAGgFgHQgOgaAKgpIg2gFQgRgBgcABQgGAMgBAfQAAAbgOAJQgGADgFAAQgFAAgFgEgAADi+IgDCIIgDCXQAAAfgHAUIAqABQgGg+AFiEQAEh5gDg3QAAgEgagDg");
	this.shape_13.setTransform(-52.2,-22.2,0.8,0.8);

	this.addChild(this.shape_13,this.shape_12,this.shape_11,this.shape_10,this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-59.7,-45.1,119.5,90.2);


(lib.t3_3 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AglAlQgPgPAAgWQAAgVAPgPQARgQAUAAQAVAAARAQQAPAPAAAVQAAAWgPAPQgRAQgVAAQgUAAgRgQg");
	this.shape.setTransform(53.3,-19.1,0.35,0.35);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AglAmQgPgQAAgWQAAgVAPgPQARgQAUAAQAVAAARAQQAPAPAAAVQAAAWgPAQQgRAPgVAAQgUAAgRgPg");
	this.shape_1.setTransform(43.6,-19.2,0.35,0.35);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgkAmQgQgQAAgWQAAgVAQgPQAPgQAVAAQAWAAAPAQQAQAPAAAVQAAAWgQAQQgPAPgWAAQgVAAgPgPg");
	this.shape_2.setTransform(48.7,-19.2,0.35,0.35);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgnHuQgQgNgBgVQgCgKAGgJQAUggAzgEIAXAHQAaAMACAaQADAagYAQQgaAQgZAAIgDABQgTAAgPgPgAgpFAQgIgMAAgNQgDgOAAgYQADgcgKhYQgYjlAQjEIAAibQAAgSASgYQAPgTAVgGIANgCQAzAFgEA3IgDCBQAAA4gCAjQgBBUADCpQAAANADAVIAZDCQAFAVgHAaQgHAsgqAFIgJABQgfAAgWgeg");
	this.shape_3.setTransform(75.7,2.8,0.35,0.35);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgUHZIgMgMQgMgRAFgYQACgaAVgOQANgIAaAAQAfABAQAZQAQAXgKAZQgPApgpAAQgZAAgPgOgAAFEXQgWgGgKgUIAAgJIAAgBIgBgBIABACQgKgMADgUQAKhhgKh4QgEg4ARg1IAehLQAchGAEgRQALgxAAgnQAAgMgBgGQgIgYgRgDQgTgEgUAQQgmAcAABLQADAbgdAPQgdARgcgQQgQgIAAgSQACglAVhHQAThABMgbQBDgVAmAXIAUAMQA3AfACBKQADA0gOAqQgEAVgCAFIgDANIgqBkQgLAbgBAMQgMBDAGBSIAKCJIAAAbQgBAXgbAYQgCADgCAAQgLAFgLAAQgKAAgLgEg");
	this.shape_4.setTransform(61,3.8,0.35,0.35);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgZHuQgegeADhvIAHlgQAGjxAAhmIgCg1QAAgfACgQQADguAigPQAkgRAKBJQgBgFAJEWQAFBfgMDgQgKDZAGBoQAAAYgRAKQgOAHgKAAQgPAAgKgNg");
	this.shape_5.setTransform(50.6,3,0.35,0.35);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgZHuQgegeADhvIAHlgQAGjxAAhmIgCg1QAAgfACgQQADguAigPQAkgRAKBJQgBgFAJEWQAFBfgMDgQgKDZAGBoQAAAZgRAJQgOAHgKAAQgPAAgKgNg");
	this.shape_6.setTransform(43.3,3,0.35,0.35);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("Ag8H4QgVgVgLhVQgHgzgmqaIgHg7QgEgiAAgRQgBg0AkgLIAoABQAXAAARgDQBOgQAfgCQBFgDAEAmQAGAshQAQQgeAFglAEIgzAFQgDAUAKCbQALCiAPCPQAQC1ADA9QAAAMAEApIAFA2QABA+gTALQgWAOgRAAQgNAAgIgJg");
	this.shape_7.setTransform(33.5,2.8,0.35,0.35);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("Ah3G7QgcgtgDggQgHgsADghQADg1ABhtQAEiLACgnIAAivQAAiqAagvQAhg5AsgIQBvgTA5BUQAaAoAABfIACDYQACBigHBcIgHBYQgGA9AAAlQgFB2geAwQgkA5gxAEIgRABQhPAAgohFgAgOmiQgrAQgJBBQgEAYAEBvQADBKgCB6IgCC5QAAASgFBAQgDAxADAZQAJBMBFABQAhAAAGhHIADg8QABgjADgOQAtjtgbkyQgGg0gPgiQgIgNgSgIQgLgEgKAAQgIAAgIAEg");
	this.shape_8.setTransform(18.9,2.8,0.35,0.35);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("ABXGFQgMidAJj5QgGkBgPh7QAAgKhGgHIAABUQABBMAGDYIAIEfQADB3gQA5QgXBOg6AHQgLAAgHgBQgbgDgVgKQgkgMAKgsQAJgrAzANIAPABQAWgRAAifQACgzgEhSIgFhdQACgugDhvIgGipQAAg/ACgqQg1gIgEgNQgShFAvAAQA1gCBPAIIBrAIQApAAgECWQADAzABBEIABBaQgBBhAVHQQAHBQgWAEQgNAHgLAAQgtAAgJh8g");
	this.shape_9.setTransform(3.6,2.7,0.35,0.35);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ah3G7QgcgtgDggQgHgxADgcQADg+ABhkQAEiLACgnIAAivQAAiqAagvQAhg5AsgIQBvgTA6BUQAZApAABeIACDYQACBigHBcIgHBYQgGA9AAAlQgFB2geAwQgkA5gxAEIgRABQhPAAgohFgAgOmiQgrAQgJBBQgEAYAEBvQADBKgCB6IgCC5QAAASgFBAQgCAxACAZQAJBMBFABQAhAAAGhHIADg8QABgjADgOQAtjtgbkyQgFg0gQgiQgIgNgSgIQgLgEgKAAQgIAAgIAEg");
	this.shape_10.setTransform(-10.9,2.8,0.35,0.35);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("Ah6IFQgcAAgDhkIAChcQADhCAAgZIABooQAAiDABgJQAFgWANgNQATgPAaAKQAVAKgBDCQgCDFAHAIQAAAHA6gEQAzgCAEgEQAHgJgGisQgHizALgcQAQgkAVAAQAhAAAAAOQAXIPABGyQAAAogbANQgcAJgUgQQgNgZAAhIQABjQgMi8QgLgRhjAUQgYAAATFWQAHB4gRAfQgGAJgeAAIgQAAg");
	this.shape_11.setTransform(-25,2.7,0.35,0.35);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("ACVITQghgWgnh7IgfiLQgVhagRgpQAAAFgeBlQgFARgKAYIgQAqQgGASgNArIgVA8QgdBEgsAVQgaAJAAgLIgRgYQgQgSANgcQAEgKAJgPQAKgSACgHQCNlWAAhVQACgSh7ktQgfhaACgZQAAgWAVgQQAWgRAYAOQAFACAiBQQBfDwAFAIQB4lOgEACQAPgUANgCQAHAAAVALQALAHAMAbQANAZhJDGQhPDYgCAIQAABUCJF6QAcBJgRAcQgGgBgWAIQgJAFgKAAQgIAAgIgDg");
	this.shape_12.setTransform(-41.8,2.3,0.35,0.35);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AhkG4QgXkfgOlDQgCg3gOiAQgIhkAugYQAHgECdgbQAmgGAUARQASATgQAbQgSAfg5ADQhCADgYAQQAAA7ALBwQALB1gBA4QBGAOgHAmQgDAXgzASQAGAxAICRQAIB+AHBBQBYgYA4AcQAOAJgKAcQgKAdgOAAQhbAKhcAHQgsAAAAhHg");
	this.shape_13.setTransform(-57.6,3,0.35,0.35);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgUH9QgtgUAIiyQABghgDggIgBg8QAAkoASkbQgCAPhagWQg4gQADgqQADgyCKgGQAngBCOAHQAoAGAKAwQALAugWAAQgRAHg0gHQgrgGAAAMQgSBzABD1QADEfgFBnIAAA7QABAngDAWQgHAwgdAAQgKAAgPgHg");
	this.shape_14.setTransform(-71.6,2.8,0.35,0.35);

	this.addChild(this.shape_14,this.shape_13,this.shape_12,this.shape_11,this.shape_10,this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-78.2,-21,156.6,42.1);


(lib.t3_2 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhFFgQgRAAgJgPQgIgnAChsIgBi9QgCh6ADhCIABiHQACgeAUAAQAfABAIAxQADAWgCBHIgDE6IANgxQA0iSAChhQAAgNAHgrIAJgzQAGgpAVgHQAVgIAEAWQAKBEgBB9IAADQQACAmgEBPQgEBQABAeQgBA2gegHQgSAGgJgYQgHgWAAgdIARk1QgvENgkBcQgQAXgSAAIgCgBg");
	this.shape.setTransform(4.9,0.1,0.35,0.35);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAzFWQgJgSAAgwQACiKgJiBQgHgLhDANQg6AFgDg+IgBioQAAhWABgIQADgQAKgIQAMgKARAHQAPAGgBCDQgECHAGAHQAAAIAogJQAkgCABgCQAGgHgFhzQgFh3AIgVQAKgZAOAAQAXAAAAAKQAQFmAAEjQAAAbgSAJQgHACgGAAQgLAAgJgHg");
	this.shape_1.setTransform(-5,-0.3,0.35,0.35);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-8.5,-12.5,17.1,25);


(lib.t3_1 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgkAmQgQgRAAgVQAAgVAQgQQAPgPAVAAQAWAAAQAPQAPAQAAAVQAAAVgPARQgQAPgWAAQgVAAgPgPg");
	this.shape.setTransform(51.8,-21.7,0.35,0.35);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgkAmQgQgRAAgVQAAgVAQgQQAPgPAVAAQAWAAAQAPQAPAQAAAVQAAAVgPARQgQAPgWAAQgVAAgPgPg");
	this.shape_1.setTransform(42,-21.7,0.35,0.35);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgkAmQgQgRAAgVQAAgVAQgQQAPgPAVAAQAWAAAQAPQAPAQAAAVQAAAVgPARQgQAPgWAAQgVAAgPgPg");
	this.shape_2.setTransform(47.1,-21.7,0.35,0.35);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgZHuQgegdADhwIAHlgQAGjxAAhmIgCg1QAAgfACgQQAEgvAhgNQAkgSAKBKQgBgGAJEWQAFBfgMDgQgKDZAGBoQAAAagRAIQgOAHgKAAQgPAAgKgNg");
	this.shape_3.setTransform(49.2,0.2,0.35,0.35);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgZHuQgegdADhwIAHlgQAGjxAAhmIgCg1QAAgfACgQQAEgvAhgNQAkgSAKBJQgCgEAKEVQAFBfgMDgQgKDZAGBoQAAAagRAIQgOAHgKAAQgPAAgKgNg");
	this.shape_4.setTransform(41.8,0.2,0.35,0.35);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("ABkJLQgfg4AVhYIgZgCQgdACgtAAQhdgBgqgDQgcACgBhlQgBgfABg9IAEqDQAAiDACgJQADgWAPgNQARgPAbAKQAVAJgBDCQgBLAAHAHQAAAHA5gFQA0gCADgDQAJgKgHqlQgIiwAMgeQAPglAVAAQAiAAAAAOQAVH5ACGeQAoAGACAhQgCBUgGBnQAAAOgcALQgMAFgJAAQgLAAgGgIg");
	this.shape_5.setTransform(30.6,2.6,0.35,0.35);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AhnIKQgZAAgNgXQgMg2ADikQABhdgDi6QgDi8AFhbIABjHQAEgtAdAAQAuABAMBJQAEAZgDBwIgEHSIAThJQBOjXADiSQAAgTALg/IANhMQAIg8AggLQAfgLAFAgQAQBmgCC4QgBD8ABA4QADA9gFBwQgHByABAyQgBBQgsgMQgaAIgOgiQgLgeABguIAYnJQhGGRg2CFQgXAigcAAIgCAAg");
	this.shape_6.setTransform(14.4,0.5,0.35,0.35);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("Ai8JJQgSgSAFgmQATigAEgHQAOgfAwgJQAPhHADg3QAFg6AAhLIACiGQADgrAEh0IAFipQADg5AEgwQgzgIgEgMQgNhFAuAAQAugDBWAJIBcAIQApAAABCWQAAAugDBIIgEBbQgHBkAAFrQAAAXADAtIABANQAnAGACAgQgCBPgGBsQAAAOgcALQgcALgKgOQgfg3AVhZIhzgKQgxgEg0ADQgOAZgBBFQAAA5gdAUQgNAHgLAAQgMAAgLgJgAAHmbQgFCMgCCYIgJFIQAABDgPArIBcACQgKiCAJkiQAKkAgIh7QABgKg5gHg");
	this.shape_7.setTransform(-1.5,2.7,0.35,0.35);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("Ai5HyQgXgjAKiHQADguAOhOQAQhfAFgiQADgdApiyIAtjFQARhfAMgiQAbhGAiAYQARAMASBqIAxE+QAeDEAfCBQAwC7gNAmQg9AlgYg2QgCgFgeiEIg0jvQgKAEgcAAQgmAAgHACQgXBOgPB7QgXDPgGAAQgUAIgQAAQgSAAgLgNgAgTh6IgVBtQArAAAGgFQAAiGgRgIIAAgBQgDAAgIAng");
	this.shape_8.setTransform(-17.1,0.2,0.35,0.35);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AiNIZQgbgGgFg9IAAsyQAAi0APgDQAagOBsAKQB0AKAsAgQAeAVAIBdQAIBog/BBQgUAWhQAJQhHAHAAAHQAZAAgvIKQgCAPAAAvQAAAtgDAVQgHA3gjAAQgKAAgKgDgAhUm8QgKAIAPChQAAAQBIgCQBIgDAVgYQAOgQACg0QADg3gPgSQgUgbhPgCIgWgBQg6AAAFAPg");
	this.shape_9.setTransform(-31.2,-0.6,0.35,0.35);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgUH9QgsgUAGizQACgZgDgnIgCg8QAAkgATkkQgCAQhbgWQg3gRACgqQADgyCKgFQAbgCCaAHQApAHAKAwQALAugXAAQgQAHg0gHQgrgFAAAKQgSB2ABDzQADEjgGBjIAAA7QACAngDAWQgHAwgeAAQgJAAgPgHg");
	this.shape_10.setTransform(-47,0,0.35,0.35);

	this.addChild(this.shape_10,this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-53.6,-23.5,107.3,47.1);


(lib.t2_2 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgnHuQgQgOgBgVQgCgJAGgJQATggA0gEIAXAHQAZALADAbQADAagYAPQgaARgZAAIgDABQgTAAgPgPgAgpFAQgIgMAAgOQgDgMAAgZQADgYgKhcQgYjnAQjCIAAibQAAgTASgXQAPgUAVgGIANgBQAzAEgEA4IgDCBQAAA4gCAiQgBA6ADDEQAAANADAUIAZDDQAFATgHAcQgHArgqAGIgLABQgdAAgWgeg");
	this.shape.setTransform(105.2,21.2,0.315,0.315);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhkG3QgXkZgPlIQgBg0gOiDQgJhkAvgZQAKgECagaQAlgGAUARQASASgPAcQgTAfg4ACQhDADgYARQAAA2AMB0QALBygCA8QBHANgHAmQgDAXgzATQAHBAAHCCQAHB6AIBFQBYgXA4AbQAOAIgKAcQgKAegOAAQhSAIhmAJQgrAAAAhIg");
	this.shape_1.setTransform(93.2,21.4,0.315,0.315);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ah6IFQgcABgDhkIABhdQADhCAAgYIACopQAAiDABgIQAEgWAOgNQASgQAbAKQAVAKgCDCQgBDHAHAGQAAAHA5gEQA1gDADgDQAHgKgGirQgHixALgeQAPgkAVAAQAiAAAAAOQAWIKACG3QAAAngbAPQgbAIgWgPQgMgZAAhJQABjFgMjGQgLgShjAUQgYAAASFXQAHB4gRAeQgFAJgdAAIgRAAg");
	this.shape_2.setTransform(80.9,21.1,0.315,0.315);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("Ai6HyQgWgjAKiHQADguAOhOQAQhfAFgiQADgdApiyIAtjFQAShhALggQAahHAjAZQARALASBrIAxE+QAfDGAeB/QAwC8gNAlQg+AlgXg2QgCgEgeiFIg0jvIAAAAIAAAAQgLAEgbAAQgmAAgHACQgXBOgPB7QgXDPgGAAQgUAIgQAAQgTAAgLgNgAgTh6QgGAWgPBXQArAAAGgFQAAiFgRgJIAAAAQgDAAgIAmg");
	this.shape_3.setTransform(67.4,21.4,0.315,0.315);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgcIPQgygIgYgSQgfgVgDh1IgOliIgFjdQAAgggJhaQgFhMAEgnQAHhABfgNQBZgLA9A0QAtAqAOAeQAgBJgZBLQgYBIg/ArQAzBYAQBCQAtCegOCFQgbC+hSAhQgVALghAAQgNAAgQgCgAg0hkIAGDOIAFDSQAFB3AQAGQAXAIAegiQAZgeAGgdQAaiVgaibQgeiXhPgJQgHADAAAFgAg/nBQgBAtAFBGIAHB4QA+AEAjgtQAmgtgNhAQgGgqgogaQgagTgjAAQgMAAgOACg");
	this.shape_4.setTransform(53.7,20.9,0.315,0.315);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("Ah3G7QgcgtgCggQgIgwADgdQADg1AChtQACh3ADg7IAAiuQAAisAbguQAgg4AsgJQBwgTA5BUQAZAnAABgIADDZQABBhgHBcIgHBYQgFA2AAAsQgGB4gdAuQglA6gwADIgTABQhOAAgohFgAgOmiQgrARgJBAQgDAYADBvQADBKgBB6IgDC5QAAAagEA4QgDAxADAZQAIBMBFABQAiAAAFhHIADg8QACghACgQQAtjsgakzQgGgzgPgjQgIgNgTgIQgLgEgKAAQgIAAgIAEg");
	this.shape_5.setTransform(39.8,21.3,0.315,0.315);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AiBHLQgTgRADgiQADgrAcgOQAZgMAWATIAdAdQANAOAKAGQAWAOAsgUQAggPAKhmQAFg0gJg5QgGhJgVgPQgMgLgvALQgwAKgVgJQgXgJgPgZQgRggAOgfQACgEBJgvQA4gpAWhAQAph2gQhEQgRg0g1AAQgvAAgnBTQgEAGgHAgQgIAdgHAMQgTAtgngYQghgTACgxIANgnQAqimCGgVQBGgKBGBLQA4A9gKCKQAAgEgZB4QgCAPgbAnQgXAhABAQQAAAPAXAWQAaAaAEAGQBGCFgeCtQgLBNgnAuQgqAqhFAHIgSAAQhSAAg8g5g");
	this.shape_6.setTransform(25.3,21,0.315,0.315);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhnIKQgZAAgNgXQgMg2ADikQABhAgDjXQgDi8AFhbIABjHQAEgtAeAAQAtABAMBJQAEAegDBrIgEHQIAUhHQBOjaACiPQAAgTALg/IANhMQAIg8AggLQAfgLAFAgQAQBmgCC4QgBD8ABA4QADA9gFBwQgHB2ABAuQgBBQgsgMQgaAIgOgiQgLgeABguIAYnJQhGGRg2CFQgXAigcAAIgCAAg");
	this.shape_7.setTransform(10.7,21.7,0.315,0.315);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AiNIZQgbgGgGg9IAAsyQAAi0AQgDQAagOBsAKQB0AKAsAgQAeAVAIBdQAIBog/BBQgUAWhQAJQhHAHAAAHQAZAAgvIKQgCAPAAAvQAAAtgDAVQgHA3gjAAQgJAAgLgDgAhUm8QgKAIAPChQAAAQBIgCQBIgDAVgYQAOgQACg0QADg3gPgSQgUgbhPgCIgWgBQg5AAAEAPg");
	this.shape_8.setTransform(-1.9,20.7,0.315,0.315);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AhkG3QgXkZgPlIQAAgrgPiMQgIhlAugYQAKgECagaQAlgGAUARQASASgPAcQgTAfg4ACQhDADgYARQAAA2AMB0QALBygCA8QBHANgHAmQgDAXgzATQAHBAAHCCQAHB6AIBFQBYgXA4AbQAOAIgKAcQgKAegOAAQhSAIhmAJQgrAAAAhIg");
	this.shape_9.setTransform(-15.3,21.4,0.315,0.315);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgUH9QgsgUAGizQACgZgDgnIgCg8QAAkgATkkQgCAQhbgWQg3gRACgqQADgyCKgFQAbgCCaAHQApAHAKAwQALAugWAAQgRAGg0gGQgrgFAAAKQgSB2ABDzQADEjgGBjIAAA7QACAngDAWQgHAwgeAAQgJAAgPgHg");
	this.shape_10.setTransform(-27.9,21.2,0.315,0.315);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AANIFQhTgCgohDQgegygOipIgLj1QgGkrAVhKQAihuBcgQQA1gIA2AkQAiAUAVBGQAQArgjAWQghAXgNgZQgcg/gigKQgrgOgQBJQgIAjgCBVQgHE4AUCzQAVC7A2gLQAxgIAFgdQAHgfAfgJQASgFAPARQANAOAAAKQADALgeAtQgqA/hTAAIgDAAg");
	this.shape_11.setTransform(-41,21.5,0.315,0.315);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("Ai6HyQgWgiAKiIQADgrANhRQARhgAEghQAFgfAoiwIAtjFQAQhcANglQAahHAjAZQARALASBrIAxE+QAfDGAeB/QAwC8gNAlQg9AlgYg2QgEgIgciBIg0jvIAAAAIAAAAQgLAEgbAAQgmAAgHACQgXBPgPB6QgYDPgFAAQgVAIgPAAQgTAAgLgNgAgUh6QgGAbgOBSQArAAAGgFQAAiFgRgJIAAAAQgDAAgJAmg");
	this.shape_12.setTransform(-55.2,21.4,0.315,0.315);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("Ah+H6QgXgEAChOQAAgTAEg0IADhGQAAlMgHhZIgEhbQgFhJACguQABiVApAAIBcgJQBVgHAvACQAtAAgNB0IgBA1QAABmAFDxIAHFgQADBvgdAeQgSAWgigRQgRgIAAgZQAGhogKjZQgLjgAEhgQAHi6gBgvIgRACQhcgDADAMQgJB7AJEBQAKD/gKCBQgGCRgwAAQgKAAgLgGg");
	this.shape_13.setTransform(-68.5,21.5,0.315,0.315);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AjCAsQgIgCgHAAQgQAAgXgYIAAgNQAAgFABgDQAKgZAdAAQAPAAAaADIAfABIC1gMQA3gBAOgCQAkgEAmAAQAagBAWAPQAOAIgBASQAAAIgIAHQgTAQgSAAQhdAAgTgCQglgDg7AKIgcAGIgOgGQgLAKgdAAQgfABg/AAg");
	this.shape_14.setTransform(100.3,-17,0.315,0.315);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("Ai5HyQgXgiAKiIQACglAPhXQARhgAEghQAFgkAnirIAtjFQAQhbANgmQAbhHAiAZQARALASBrIAxE+QAfDGAfB/QAvC7gNAmQg9AlgYg2QgCgFgeiEQgzjlgBgKQgLAEgbAAQgmAAgHACQgYBPgNB6QgYDPgGAAQgUAIgQAAQgTAAgKgNgAgTh6IgVBtQAqAAAIgFQAAiGgSgIIAAAAQgDAAgIAmg");
	this.shape_15.setTransform(84.2,-20.3,0.315,0.315);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AiNIZQgbgGgFg9IAAsyQAAi0APgDQAZgOBtAKQBzAKAtAgQAeAVAIBdQAIBog/BBQgUAWhQAJQhHAHAAAHQAZAAgvIKQgCAPAAAvQAAArgCAXQgIA3gjAAQgJAAgLgDgAhUm8QgKAIAQChQAAAQBHgCQBIgDAVgYQAOgPADg1QACg3gPgSQgUgbhPgCIgWgBQg6AAAFAPg");
	this.shape_16.setTransform(71.6,-21,0.315,0.315);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgUH9QgsgUAGizQACgWgDgqIgBg8QAAkoASkcQgCAQhagWQg4gRADgqQACgyCLgFQAagCCbAHQAoAHAKAwQALAugWAAQgRAGg0gGQgrgFAAAKQgSB2ABDzQADEugGBYIAAA7QACAngDAWQgIAwgdAAQgJAAgPgHg");
	this.shape_17.setTransform(57.4,-20.5,0.315,0.315);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgYIPQg0gIgYgSQgfgWgCh0IgOliQAAgbgDhMIgDh2QAAgXgIhjQgJh1AAgNQgBg0AkgLIAqABQAfAAABBNQACBGACAtQAHC3AAAsQCTg/A2CqQAdClgOCCQgaC9hTAiQgVAKggAAQgMAAgQgBgAgpghQgHADAAAGQADAoABBaIAGDSQAEB3ARAGQAWAIAegiQAZgeAGgdQAaiVgaibQgPhgg0AAQgSAAgWALg");
	this.shape_18.setTransform(43.5,-20.9,0.315,0.315);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("ABXGFQgMiWAIkAQgFkBgQh7QAAgJhFgIIAABUQACCDAFChIAIEfQADB4gQA4QgXBPg6AGQgLAAgIgBQgbgDgUgKQgkgNAJgrQAKgrAyANIAQABQAWgRAAifQACg2gFhPIgEhdQACgzgDhqIgGipQAAg/ACgqQg1gIgFgNQgQhEAuAAQAtgDBXAIIBrAJQApAAgECVIAEB3IABBaQgBBhAVHQQAHBQgXAEQgMAHgLAAQgsAAgKh8g");
	this.shape_19.setTransform(28.9,-20.6,0.315,0.315);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AhCHyQgQgGAaiuQAMhSAgitIAqj/IiYi3Qgog4gCgNQAAgYAZgMQAYgJAYANQAZAOAvA+QAxBCATANQAGgQAFg6QAGg4AKgWQAOgYAVgJQAXgKAaATQAPAJggDNQgEAegaCSIgZCdQgGA0gXB8QgXCCgGAuQgUBngIAFIgSABQgjAAgPgNg");
	this.shape_20.setTransform(16.4,-20.6,0.315,0.315);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AhnIKQgaAAgMgXQgNg5ADihQAChAgDjXQgCi8ADhbIACjHQAEgtAdAAQAvABAKBJQAFAegDBrIgEHPIAThGQBOjZADiQQAAgVALg9QAOhSgCAGQAJg8AggLQAegLAGAgQAQBrgCCzQgBD8ABA4QADA/gGBuQgHB+ACAmQgCBQgrgMQgbAIgNgiQgMggACgsIAYnJQhHGVg1CBQgXAigdAAIgBAAg");
	this.shape_21.setTransform(-7.2,-20.1,0.315,0.315);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AiyHzQgGiKASk/QATlHgDh4QgDguAFgTQAIgaAUgNQAZgOAYAVQACAaAEBZIAEB1QAbgVAnhcQArhgAbgXQAOgLAXgEQAagDAGASQAJAagoBLQhoDdgnBIQBCB4BoEXQAyB+gLAsQgGAVgZAHQgZAHgOgLQgcgRgOgyQgzi6hXjYQgPBeAAF/QAAAYguABIgGABQgoAAAAgUg");
	this.shape_22.setTransform(-20.1,-20.3,0.315,0.315);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgYIPQg0gIgYgSQgegVgDh1IgOliQAAgbgDhMIgDh2QAAgXgIhjQgJh1AAgNQgBg0AkgLIAqABQAfAAABBNQACBGACAtQAHC3AAAsQCTg/A2CqQAeCjgPCEQgaC9hTAiQgVAKghAAQgLAAgQgBgAgpghQgHADAAAGQADAlABBdIAGDSQAEB3ARAGQAXAIAdgiQAaggAFgbQAaiVgaibQgPhgg0AAQgSAAgWALg");
	this.shape_23.setTransform(-34.4,-20.9,0.315,0.315);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("ABXGFQgMiWAIkAQgFkBgQh7QAAgJhFgIIAABUQACCDAFChIAIEfQADB4gQA4QgXBPg6AGQgLAAgIgBQgbgDgUgKQgkgNAJgrQAKgrAzANIAPABQAWgRAAifQACg2gFhPIgEhdQACgzgDhqIgGipQAAg/ACgqQg1gIgFgNQgQhEAuAAQAugDBWAIIBrAJQApAAgECVIAEB3IABBaQgBBhAVHQQAHBQgXAEQgMAHgLAAQgsAAgKh8g");
	this.shape_24.setTransform(-49.1,-20.6,0.315,0.315);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgaHuQgcgdAChwIAHlgQAFjSAAiFIAAhkQAFgvAhgNQAkgSAKBKQgBgGAJEWQAEBogLDXQgJDXAFBqQAAAagRAIQgOAHgKAAQgPAAgLgNg");
	this.shape_25.setTransform(-58.6,-20.3,0.315,0.315);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgUH9QgsgUAGizQACgZgDgnIgCg8QAAksATkYQgCAQhbgWQg4gRADgqQADgyCKgFQAbgCCaAHQApAHAKAwQALAugXAAQgQAHg0gHQgrgFAAAKQgSB0ABD1QADEfgGBnIAAA7QACAngDAWQgHAwgeAAQgJAAgPgHg");
	this.shape_26.setTransform(-68.5,-20.5,0.315,0.315);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AkRAnQgIgCgIAAQgPAAgYgYIAAgNQAAgFACgDQAJgZAdAAQAPAAAaADIAgABIBtgIQANgBCKADICVABQAngEAjAAQAZgCAWAQQAOAIAAAQQAAAKgIAHQgTAPgRAAQheAAgUgBQi0gPhKAMQgGACgWAEIgPgGQgLAKgdAAQgeABhAAAg");
	this.shape_27.setTransform(-97.8,-16.9,0.315,0.315);

	this.addChild(this.shape_27,this.shape_26,this.shape_25,this.shape_24,this.shape_23,this.shape_22,this.shape_21,this.shape_20,this.shape_19,this.shape_18,this.shape_17,this.shape_16,this.shape_15,this.shape_14,this.shape_13,this.shape_12,this.shape_11,this.shape_10,this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-108.2,-38,216.4,76.2);


(lib.t2_1 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhqDbIAAgbIhpAAIAAAbIgZAAIAAg0IAQAAQADgDADgHQAEgIADgMIAGgcQAEgSAAgUIACgeIBeAAIAAB+IAUAAIAAA0gAivB3IgFAXIgGAQIgFAJIA/AAIAAhlIgpAAgAHAC+QgMgFgKgJQgJgHgIgOQgGgKgCgRIgZAAIAABAIgbAAIAAiXIAbAAIAAA+IAZAAQADgOAGgMQAFgKAKgKQAKgIANgGQAMgEAPAAQASAAANAFQAOAFAKALQALALAFANQAGAOAAATQAAASgGANQgFAOgLAKQgJALgPAGQgOAGgRAAQgNAAgOgFgAHJBDQgIAEgHAHQgFAGgFALQgEALAAALQAAAKAEALQAEAKAGAHQAIAHAHAEQAKAEAJAAQAMAAAJgEQAKgFAFgHQAFgGAEgKQADgKAAgLQAAgNgEgJQgDgJgGgIQgHgHgIgEQgKgEgKAAQgJAAgKAEgAoTC9QgQgGgJgKQgLgKgGgOQgGgOAAgSQAAgRAGgOQAFgOALgLQALgLAOgFQAPgGARAAQASAAANAFQAOAFALALQALAKAGAOQAGAPAAASQAAARgGAOQgHAPgKAJQgKALgPAGQgOAGgRAAQgQAAgPgGgAoIBDQgJAEgHAHQgHAHgEAKQgEALAAALQAAAKAEALQAEAKAHAHQAIAIAIADQAKAEAKAAQAMAAAJgEQAKgFAGgHQAHgGADgKQAEgJAAgMQAAgLgEgLQgEgKgHgHQgJgIgHgDQgKgEgKAAQgKAAgKAEgAKjDAIg9hOIAABOIgbAAIAAiXIAbAAIAABIIA7hIIAgAAIg+BGIBCBRgAD2DAIAAh+IgxAAIAAgZIB9AAIAAAZIgxAAIAAB+gACuDAIgQgnIhAAAIgQAnIgbAAIBAiXIAXAAIBACXgACUCBIgWg2IgWA2IAsAAgAgyDAIAAiXIArAAQAQAAAKAEQALAEAHAHQAGAGADAJQADAJAAAJQAAAKgDAJQgEAIgHAHQgHAHgKAEQgLAEgLAAIgJAAIgLAAIAAA2gAgYBCIAAAuIAKABIAJAAIAJgBQAHgCACgDQAEgDACgEQACgGAAgFQAAgMgHgGQgHgGgMAAIgJAAIgKABgAkiDAIAAhAIhGAAIAABAIgaAAIAAiXIAaAAIAAA+IBGAAIAAg+IAaAAIAACXgApsDAIg+hOIAABOIgaAAIAAiXIAaAAIAABIIA8hIIAgAAIg/BGIBDBRgAnqhFQgOgGgKgKQgLgKgFgPQgGgOAAgRQAAgPAFgPQAGgOAKgLQALgKANgGQAPgGAQAAQAQAAAOAGQANAFALALQAKALAGANQAFAPAAAQQAAAQgFAPQgGAOgKALQgLAKgNAGQgPAGgPAAQgQAAgOgGgAnljKQgLAEgKAKQgIAJgFAMQgFAMAAAOQAAAPAFAMQAFALAIAKQAJAJAMAFQAMAFANAAQAMAAANgFQAMgFAIgJQAJgKAEgLQAFgNAAgOQAAgOgFgMQgFgMgIgJQgKgKgLgEQgKgFgOAAQgPAAgKAFgAlZhBIAAiXIATAAIAKgBIAIAAQAPAAALAEQALAEAGAHQAFAFAEAJQACAJAAAIQAAAKgDAHQgDAJgHAGQgHAHgKADQgKAEgOAAIgZgBIAAA9gAlNiJIAZABQAVAAAKgKQALgJAAgQQAAgHgDgHQgCgGgFgFQgGgFgGgCQgHgCgMAAIgaAAgAp3hBIAAiXIBTAAIAAALIhHAAIAACMgAq8hBIAAiXIAMAAIAACXg");
	this.shape.setTransform(0,0,0.8,0.8);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-56.7,-17.6,113.6,35.2);


(lib.t1_2 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgoHuQgPgNgBgVQgCgJAGgKQAUggAzgEIAXAHQAZALADAbQADAagYAQQgaAQgZAAIgDABQgTAAgQgPgAgpFAQgIgLAAgOQgDgNAAgZQADgYgKhcQgYjnAQjCIAAibQAAgSASgYQAOgTAWgGIANgCQAzAFgFA3IgCCBQAAA4gCAjQgBA5ADDEQAAAKACAYIAaDCQAFATgHAcQgHAsgqAFIgKABQgeAAgWgeg");
	this.shape.setTransform(97.9,23.4,0.35,0.35);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhjG4QgYkYgOlKQgCg0gNiDQgJhkAugYQAHgECdgbQAngGATARQASATgQAbQgSAfg5ADQhCADgYAQQAAA1ALB2QALB4gBA1QBHAOgIAmQgCAXgzASQAEAuAKCUQAHB7AHBEQBYgYA4AcQAOAJgKAcQgKAdgNAAQhcAKhcAHQgrAAAAhHg");
	this.shape_1.setTransform(84.6,23.6,0.35,0.35);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AiyHzQgGiSASk3QATk+gDiCQgDguAGgSQAGgaAWgNQAZgOAXAVQAEAtACBFIAEB2QAbgWAohbQAqhfAbgYQAQgMAVgDQAagDAGASQAKAbgpBKQhsDjgjBCQBDB5BnEWQAyB9gLAtQgGAVgZAHQgZAHgOgLQgcgRgOgyQg1jBhVjSQgPBcAAGCQAAAYguABIgGABQgoAAAAgUg");
	this.shape_2.setTransform(70.9,23.7,0.35,0.35);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgYIOQgygGgagTQgegWgDh0IgOljIgGjcQAAgXgIhkQgJh0AAgNQAAg0AjgLIAqABQAfAAABBNQACBNADAlIAHDkQCSg/A2CqQAeCjgPCEQgaC9hSAiQgWAKgeAAQgNAAgRgCgAgpghQgHADAAAFQADAmABBdIAGDSQAEB3ARAGQAXAHAdghQAaggAFgbQAbiWgbiaQgPhgg0AAQgSAAgWALg");
	this.shape_3.setTransform(55,23.1,0.35,0.35);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAMIFQhRgCgphDQgegzgPioIgLj1QgFkvAVhGQAhhuBcgQQA2gIA1AkQAjAUAVBGQAPArgiAWQgiAXgNgaQgcg+ghgKQgsgOgPBIQgHAegDBbQgHE+ATCtQAVC6A2gKQAxgJAGgcQAHgeAegKQASgGAQASQAMAOAAAKQADALgdAtQgqA/hTAAIgEAAg");
	this.shape_4.setTransform(40.1,23.7,0.35,0.35);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AiOIZQgagGgGg+IAAsxQAAi0AQgDQAZgOBtAKQBzAKAtAgQAdAUAIBeQAJBng/BCQgWAXhPAIQhGAGAAAIQAZAAgwIJQgBAQAAAvQAAAwgDASQgHA3gkAAQgJAAgLgDgAhUm9QgKAJAPCgQAAARBHgDQBJgDAUgXQAOgPADg2QADg2gPgSQgUgbhPgDIgRAAQg/AAAFAOg");
	this.shape_5.setTransform(25.5,22.9,0.35,0.35);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AhkG4QgXkfgOlDQgCg3gOiAQgIhkAugYQAHgECdgbQAmgGAUARQASATgQAbQgSAfg5ADQhCADgYAQQAAA7ALBwQALB1gBA4QBGAOgHAmQgDAXgzASQAGAxAICRQAIB+AHBBQBYgYA4AcQAOAJgKAcQgKAdgOAAQhbAKhcAHQgsAAAAhHg");
	this.shape_6.setTransform(10.6,23.6,0.35,0.35);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("ABaH2QgCgCAAhzQAAmNAQj1QgKAGg0BdQgXAjgHAHQgGAEgJgEQgogHghhqQgIgVgHgGIgDCNQAABugHCMQgBAvAABZQABBZgDAlQgHBqgTAJQgfANgNgZQgHgWgCi1IgDhGQgCgrACgbQAHh6ADipIAElkQAIgmA3AKQAPAAAVBAIAZBVQAKAWAFAVQAdBCAEAEQgDgHBwjRQARgbADgBQAkgVAVAfQAEACgEBtQgMF7gCHbQAAAkgmAIQgIACgHAAQgSAAgLgTg");
	this.shape_7.setTransform(-4.5,23.2,0.35,0.35);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AiOIZQgagGgGg+IAAsxQAAi0AQgDQAZgOBtAKQBzAKAtAgQAdAUAIBeQAJBng/BCQgVAWhQAJQhGAGAAAIQAZAAgwIJIgBA/QAAAtgDAVQgIA3gjAAQgJAAgLgDgAhUm9QgKAIAPChQAAARBHgDQBJgDAUgXQAOgPADg2QADg2gPgSQgUgbhPgDIgRAAQg/AAAFAOg");
	this.shape_8.setTransform(-19.9,22.9,0.35,0.35);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AhjG4QgYkYgOlKQgCg3gOiAQgIhkAugYQAHgECdgbQAngGATARQASATgQAbQgSAfg5ADQhCADgYAQQAAA7ALBwQALB1gBA4QBHAOgIAmQgDAXgyASQAFA1AICNQAIB+AHBBQBYgYA4AcQAOAJgKAcQgKAdgNAAQhcAKhcAHQgrAAAAhHg");
	this.shape_9.setTransform(-34.8,23.6,0.35,0.35);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgzHrQgDgVAAgtIgBg/Qgwm2AaAAQAAgGhJgHQhCgJgVgWQg/hCAJhnQAIheAegVQAtggBngKQAagCASAAIAMhBQAZgyAlAcQAqAcgRAvQCEgNBBBcQAuAsAKBIQAKA/gpBBQgrBEhwAGIg/AGIAAIUQgGA+gaAGQgKADgIAAQgjAAgIg3gAA3lVQgSCbAOALQgGARBQgTQA1gIASgaQAPgSgHgnQgHgzgOgQQgTgYgqgGQhDAIAAAQgAiIlxQg4ADgRAbQgOASADA2QADA1ALAQQASAXAzADQA9ADAAgRQAMihgIgIQAFgOgyAAIgTAAg");
	this.shape_10.setTransform(-53.4,22.7,0.35,0.35);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AhnIKQgZAAgNgWQgNg5ADihQAChBgDjXQgCi7ADhbIACjIQAEgtAdAAQAvACALBIQAEAfgDBqIgEHQIAThHQBOjZADiQQAAgVALg9QAOhQgCAEQAJg8AggLQAegLAGAgQAQBrgCCzQgBD9ABA4QADA+gGBvQgHB9ACAmQgCBQgrgMQgbAJgNgjQgMggACgrIAYnKQhGGRg2CFQgWAigdAAIgCAAg");
	this.shape_11.setTransform(11.7,-22.4,0.35,0.35);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AiyHzQgGiSASk3QATlHgDh5QgDgtAFgTQAIgbAUgMQAagOAXAVQAEAtACBFIAEB2QAbgWAnhbQAqhfAcgYQAQgMAVgDQAagDAGASQAKAbgpBKQhsDjgjBCQBDB5BnEWQAyB9gLAtQgGAVgZAHQgZAHgOgLQgcgRgOgyQg1i/hVjUQgPBeAAGAQAAAYguABIgGABQgoAAAAgUg");
	this.shape_12.setTransform(-2.7,-22.7,0.35,0.35);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgYIOQgzgHgZgSQgegWgDh0IgOljQAAgbgDhLIgDh2QAAgXgIhkQgJh0AAgNQgBg0AkgLIAqABQAfAAABBNQACBNADAlQAGC+AAAmQCTg/A2CqQAeCigPCFQgaC9hTAiQgVAKgfAAQgMAAgRgCgAgpghQgHADAAAFQADAlABBeIAGDSQAEB3ARAGQAXAHAdghQAaggAFgbQAaiWgaiaQgPhgg0AAQgSAAgWALg");
	this.shape_13.setTransform(-18.6,-23.3,0.35,0.35);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("ABXGFQgMidAIj5QgFkBgQh7QAAgKhFgHIAABUQABBMAGDYIAIEfQADB5gQA3QgXBOg6AHQgLAAgHgBQgcgDgUgKQgkgMAJgsQALgrAyAMIAPACQAWgRAAifQACg3gFhOIgEhdQACgzgDhrIgGioQAAg/ACgqQg1gIgFgNQgQhFAuAAQAzgCBRAIIBrAIQApAAgECWQACAjACBUIABBaQgBBhAVHQQAHBQgXAEQgMAHgLAAQgsAAgKh8g");
	this.shape_14.setTransform(-34.9,-23.1,0.35,0.35);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgaHuQgcgdAChwIAHlgQAGjlAAhxIgCg2QAAgeACgRQADguAigOQAkgSAKBKQgBgGAJEWQAEBngLDYQgJDXAFBrQAAAYgRAJQgOAHgKAAQgPAAgLgNg");
	this.shape_15.setTransform(-45.4,-22.7,0.35,0.35);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgUH9QgsgUAGiyQACgagDgnIgCg8QAAkgATkjQgCAPhbgWQg3gQACgqQADgyCKgGQAbgCCaAHQApAIAKAvQALAugXAAQgQAHg0gHQgrgGAAAMQgSB1ABDzQADEjgGBjIAAA7QACAogDAVQgHAwgeAAQgJAAgPgHg");
	this.shape_16.setTransform(-56.4,-23,0.35,0.35);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AkRAnQgIgDgIAAQgOAAgZgXIAAgNQAAgFACgDQAJgZAdAAQAOAAAbADIAgABIBtgIQAWgCCBADICVACQAggEAqAAQAZgCAWAPQAOAJAAAQQAAAKgIAHQgTAPgRAAQheAAgUgBQi0gPhKAMQgJADgTADQgDAAgMgGQgLAKgdAAQgeABhAAAg");
	this.shape_17.setTransform(-89,-18.9,0.35,0.35);

	this.addChild(this.shape_17,this.shape_16,this.shape_15,this.shape_14,this.shape_13,this.shape_12,this.shape_11,this.shape_10,this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-100.5,-41.8,201.1,83.7);


(lib.t1_1 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ADGDJQgPgGgKgJQgKgLgGgOQgGgPAAgSQAAgPAGgPQAFgOALgLQAKgKAOgGQARgHAPABQASAAAOAFQAOAGALAKQAKAKAGAPQAGAOAAARQAAASgGAOQgGAOgKALQgLAKgOAGQgPAFgRAAQgSAAgNgFgADRBQQgJAEgHAGQgGAIgEAJQgEALAAAKQAAALAEALQAEAKAGAHQAHAGAKAFQAJAEAKAAQAMAAAKgEQAKgFAGgGQAFgGAFgLQADgKAAgMQAAgKgEgLQgDgJgHgIQgHgGgKgEQgJgEgLgBQgJABgLAEgApkDNIABgbIAGAAQAEgBACgDQAEgCADgHIAGgQQACgJADgSIAEgnIACgeIBfAAIAACYIgaAAIAAh/IgsAAIgDAdQgDAegGAXQgGAUgHAKQgHALgJACQgGACgHAAIgIAAgAFXDMIAAiWIAJgBIAjAAQAOAAAJACQAKADAFAFQAGAFADAHQADAHAAAIQAAANgGAIQgGAIgKAFIAAABQALACAIAJQAIAJAAAPQAAAMgFAIQgFAJgHAFQgHAGgKADQgJACgOAAgAFyC0IARAAQAOAAAHgFQAHgGAAgKQAAgLgHgEQgHgFgMABIgTAAgAFyBOIAAAmIASAAQAJAAAHgFQAGgEAAgLQAAgJgGgFQgHgFgLABgAjdDMIAAiWIAIgBIAkAAQANAAAKACQAJADAGAFQAGAFADAHQACAJAAAGQAAANgGAIQgFAJgKAEIAAABQAKACAJAJQAHAJAAAPQAAAMgEAIQgFAJgHAFQgGAFgMAEQgIACgOAAgAjDC0IASAAQANAAAIgFQAHgGAAgKQAAgLgHgEQgHgFgNABIgTAAgAjDBOIAAAmIASAAQAKAAAGgFQAHgEAAgLQAAgJgHgFQgGgFgLABgAJIDNIgPgoIhBAAIgQAoIgbAAIBAiYIAYAAIBACYgAIuCNIgWg2IgWA2IAsAAgABZDNIAAhBIhFAAIAABBIgYAAIAAiYIAYAAIAAA+IBFAAIAAg+IAbAAIAACYgAhQDNIAAiYIAaAAIAACYgAlEDNIAAh/IgxAAIAAgZIB8AAIAAAZIgxAAIAAB/gAmuDNIAAiYIAaAAIAACYgAJVg1IgWg0IhJAAIgWA0IgMAAIBCiZIAKAAIBCCZgAI6h0IgfhJIggBJIA/AAgAGog1IAAhIIhfAAIAABIIgMAAIAAiXIAMAAIAABFIBfAAIAAhFIALAAIAACXgAD9g1IAAg7IgiAAIgqA7IgOAAIAtg9QgGgBgGgEIgLgKQgEgFgDgHQgDgIAAgIQAAgHADgLQAEgJAHgGQAIgIAKgDQAKgDAPgBIARAAIAJABIAHAAIAACXgADTi+QgJADgEAFQgFAEgDAHQgCAFAAAJQAAAHACAGQADAGAEAEQAEADAGAEQAEACAHABIAjAAIAAhFIgYgBQgKAAgIAEgABSg1IAAiMIg4AAIAAgLIB8AAIAAALIg4AAIAACMgAhPg1IAAiXIBSAAIAAALIhGAAIAAA6IBBAAIAAALIhBAAIAAA8IBIAAIAAALgAixg1IAAiMIg4AAIAAgLIB8AAIAAALIg4AAIAACMg");
	this.shape.setTransform(0,0,0.8,0.8);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-49,-16.5,98.2,33.1);


(lib.playBtn_1 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.playBtn();
	this.instance.setTransform(-13.2,-15.7);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-13.2,-15.7,35,39);


(lib.milk_1 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.milk();
	this.instance.setTransform(-150,-86);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-150,-86,300,172);


(lib.logo = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ah2EbQg3gYgrgqQgpgogZg7QgXg3AAg/QAAhAAXg3QAZg5ApgoQArgqA3gXQA4gZA/AAQA/AAA3AZQA4AXApAqQApApAZA4QAYA4AAA/QAAA+gYA4QgZA6gpApQgpAqg4AYQg3AYg/AAQg/AAg4gYgAhYjSQgpARggAfQgfAggSAqQgSAqAAAuQAAAvASAqQASAqAfAfQAeAeArAUQAqASAuAAQAvAAAqgSQAsgUAdgeQAfggASgpQASgqAAgvQAAgugSgqQgRgpggghQgfgegqgSQgqgTgvAAQguAAgqATgABDCgIhJh3IgsAAIAAB3IhBAAIAAlKIBzAAQBGABAcAdQAdAdAAAtQAAAigUAaQgUAYgfAJIBYCFgAgygFIAvAAQAaAAAUgQQATgRAAgbQAAgagSgQQgTgQggAAIgrAAg");
	this.shape.setTransform(51,-56.9,0.195,0.195);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#0068AD").s().p("AhPBAIhqB3IhrhaIFJl0IBrBbIhqB3ID/DWIh4CHg");
	this.shape_1.setTransform(35.8,31.7,0.195,0.195);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#0068AD").s().p("AkGhYIDlidQBSg5BMALQBDAKApA5QAmA1gLA/QgNBMhUA4IhSA4IBPBvIiWBngAgUh6IghAXIBDBfIAhgXQBEgvgigvQgRgYgaAAQgaAAggAXg");
	this.shape_2.setTransform(26.9,41.1,0.195,0.195);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#0068AD").s().p("AkQjPIDphPIE7GCIi2A9IhBhUIiFAtIADBrIitA6gAh8iMIADCYIBggfIhgh6g");
	this.shape_3.setTransform(18.8,46.6,0.195,0.195);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#0068AD").s().p("AknBLIAkgCQAogtAKg4QAGgigFg9IgLiVIGmgfIAaFUIAygEIARDlIi2ANIgIhoIjSAQIAIBnIi2AOgAgyikIAFA5QAEA0gGAjQgIAqgZAmIB+gKIgRjcg");
	this.shape_4.setTransform(4.8,49.6,0.195,0.195);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#0068AD").s().p("AAcDwIAYirIh4gQIgXCrIi1gZIBAnNIC1AXIgWChIB3AQIAWihIC1AZIhAHNg");
	this.shape_5.setTransform(-8.8,48.2,0.195,0.195);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#0068AD").s().p("ABSDeIAIhpIiDg0IhFBRIiqhCIFMl0IDlBaIgUHugAASgcIBeAkIAKiZIgDgBg");
	this.shape_6.setTransform(-22.6,45.7,0.195,0.195);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#0068AD").s().p("AkXC1IDJkGIiChfIBVhvIGTEmIhUBuIiChdIjGEIg");
	this.shape_7.setTransform(-29.6,38.8,0.195,0.195);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#0068AD").s().p("Ai7CnQhVhnAGhjQAGhhBWhEQBRhABcAJQBrALBdBxQAdAkAiA9IAFAKIhiBLQgRgwgdgjQglgsgxgGQgugGgpAgQgkAdgKAjQgOA1AvA6QAYAdAwAfIhhBOQg7gqgogwg");
	this.shape_8.setTransform(-38,33,0.195,0.195);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#0068AD").s().p("AlgCzIAzisIEBBJIABgCIjfi5IA8jJIHICCIgzCsIkEhKIgBACIDjC6Ig8DJgADICcQgEgmANgtQANgsAYgdQAqg0BBAIIgHBSQgYgGgTAZQgLAPgHAYQgSBDAnANIgpBKQg7gbgGhDg");
	this.shape_9.setTransform(48.7,14.1,0.195,0.195);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#0068AD").s().p("AjtBMIEJgBIAAgDIkKh0IAAjRIHcgBIAAC0IkPAAIAAADIEQBzIAADSIncABg");
	this.shape_10.setTransform(49.7,0.2,0.195,0.195);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#0068AD").s().p("AjTB6ICpgwIghhwIiqAtIgziqIHJiCIAzCsIifAtIAiBxICfgrIAyCqInJCCg");
	this.shape_11.setTransform(47.7,-13.4,0.195,0.195);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#0068AD").s().p("Aj6CrICMhUQgugugegsQheiXCBhOICXhbIBdCZIh/BOQgjAVAaArQAQAaAcAVICahbIBgCWImVD2g");
	this.shape_12.setTransform(43.8,-25.5,0.195,0.195);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#0068AD").s().p("AAPEEQhfgBhahVQhbhWgEhdQgFheBQhRQBQhRBgACQBfABBaBVQBaBWAFBdQAFBehQBRQhOBPheAAIgEAAgAANhlQgbAOgmAmQgmAngNAbQgUAtAgAfQAhAfAtgWQAbgOAmgmQAmgnANgbQAVgtghgfQgTgSgXAAQgRAAgTAJg");
	this.shape_13.setTransform(34,-35.4,0.195,0.195);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#0068AD").s().p("AglDeICgksIhPgpIgmBIQhBB6grAjQhDA1higyQgngUgmggIA5hpQAWARALAFQAoAVApg3QAOgSA1hiIBGiEIF9DEIjdGdg");
	this.shape_14.setTransform(22.5,-43,0.195,0.195);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#0068AD").s().p("AgzDsQh7gag3hPQg2hNAZhsQAYhuBTgxQBTgwB4AaQB7AaA3BPQA2BNgYBsQgZBuhSAwQg2AghHAAQgkAAgrgJgAgphdQgSAbgLA0QgMAyAEAgQAHAxAsAJQAqAKAbgqQASgaAMg1QALgzgEgfQgHgxgsgJQgJgCgHAAQgfAAgWAig");
	this.shape_15.setTransform(10.2,-47.7,0.195,0.195);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#0068AD").s().p("AlhjJIEOgZIBVD3IADAAIAikCIEOgZIAtHQIijAPIgklsIgEAAIg6F1IiWAOIh+lkIgFABIAkFsIicAOg");
	this.shape_16.setTransform(-5.3,-48.7,0.195,0.195);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#0068AD").s().p("AldgMICThqICiDVIACgCIhBkbICqh8IEcF2IiUBrIiejRIgDABIA+EYIiqB8gAlbizIA4g/QAaAfA7goQA5grgYghIBOgjQAeA5gkA5QgUAfgmAdQgnAcgmAJQgRAEgQAAQgtAAghggg");
	this.shape_17.setTransform(-30.3,-39.5,0.195,0.195);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#0068AD").s().p("AlaA9IBuiNIDaCgIACgCIiRj+ICBinIF7EbIhvCNIjVidIgBADICMD7IiCCmg");
	this.shape_18.setTransform(-40.4,-29.2,0.195,0.195);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#0068AD").s().p("AmGD0IA4ikIFDBqIAXhJIlChqIA4iiIFCBrIAZhJIlChqIA4ikIFCBqIAQgvIDiBKIg4CkIhhggIixIGg");
	this.shape_19.setTransform(-47.1,-14.8,0.195,0.195);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#0068AD").s().p("AjtBMIEPgBIAAgDIkPhzIgCjRIHcgDIABCzIkKACIAAADIELByIABDSIncADg");
	this.shape_20.setTransform(-50.7,0.8,0.195,0.195);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#0068AD").s().p("AkGADQgbhcAfg3QAWgnAtgMQAogMAkARQAlARAUAnIACgBQgGgpAQgiQAUgrAvgOQB8giA1C6IBNEDInJCBgAh8ggQgRAFgIAQQgKASAJAhIANAsIBZgZIgMgpQgLgkgWgLQgJgFgJAAQgGAAgHACgAA3hWQgvANAVBFIALAlIBegaIgNgqQgKgkgXgMQgJgFgLAAQgGAAgHACg");
	this.shape_21.setTransform(-48.4,14.3,0.195,0.195);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#0068AD").s().p("AsxdqQl6ickjkdQkjkdiglzQill+AAmjQAAmBCPloQAgAmA+BOQAuA6A7BFIB3CMQBLBNBZAbQBXAcB9gKQCKgLA1ALQA9AMBEBAQAKAJBZBhQAGgigDgUIgmjJQgLgJgOgFQgNgFgeAAQgfACgOgHQADgYAeglQApgzAGgKIAFgLIAAgDQgLhFgCgiQgCghAGgeQhKAygdAQQg1AeguAHQhpASiehdQhgg5jUg4QhEgSgRgNQgXgSAfgcQBFg+BngcQB8giBoArIBuAwQBAAdApAMQB3AkBxgrQAdgKAagGQAKgLASgFIAlgHIAfAOQAnAcAmBHQAdA3AHB7QAFBZgFCaQgGCThWFUQhdFvg7AdQgeAPgWAAQgcAKgYAPIg2AyQhLBTgPBHQgTBYA2BzQAaA2AMBOQAQBiAKAjQAUBBBKBCQBPBGAPg9QAIgdgTgZQgJgMgmggQhHg8AHhIQACgNARhEQAKgogKgnQgbg6gNghQgYg+AbgZQAggqBWAQIBEAOQAmAIAUgDQAdAGAkAEQBvAQBQgMQgjBIAfBVQAdBNBGA5QBdBIAmA6QAbAqAMAqQADAKABAkQAAAfAGAMQAPAcA2gVQAcgKAugdQAtgcAagkQAagpAAgtIAAgzQABgcAIgWQAIgVATgXQAXgZALgOQAog0ANgTQAegsAKggQAXhOg+hQQg5hHhZglQgngPg3ACQgmABg5AMQg3ALgxASQANgVALgMQAagdBojUQByjqBYh+QBfiGAujXQAUhtAKguQARhRATgpQAghDBRg5QBSg5AfhDQAVgrABg3QAAgegIhIQgPiKAlhOQAtheBfhRQAvgqAngVQgggkg7goQh2hPiGgWQhagPihAcQi5AfgpAAQg9AAh1geQhtgcg3AFQgiADgpAKQhSAUgoAiQhIA8gaBpQgUgKgrgQQhIgagugmQhIg9gMgHQg8gngjAlQglAoAjBYQAlBfAjAtQAkAvBRA1IA4AmQAdAVARAJQgKAQgxBIQglA2gRAoQgGAMgBAMQhsAYh1gVQiFgXhMglQg3gZhygHQhhgGhqAbQhjAZhMArQEIoDHykzQIAk9JeABQJXgBH7E0QHsEsEMH3Qhtg0iKgHQiOgIhvAuQhZAmhXBQQBSgYBrgKQB5gLCiAbQCiAcAoAoQA1AzAGAYQAJAjhNAAQghAAg8gMIhqgXQiLgXhpAuQhwAwg9BKQgVAagdAvIg0BUQgkA2gMASQBsBSDNAwQCVAjBqhEQAggVA1gxQA6g1AegWQAlgaBKgoQBCgkAagXQBGEDAAELQAAGjilF+QigFzkjEdQkjEdl6CcQmHCjmrgBQmrABmGijgApBXuQgpAGgPAhQgPAjASAZQAJANAaASQBHAxBqAPQBkAOBagUQAigJAmgSQAZgMAqgaQAYgNAjgiQAWgUAEgHQAIgQgZgBQgLAAgUAJQgZAMgGACQgYAHgrAEQhDAHhigUQgcgHhEgTQg8gSgjgGQgfgEgWAAIgSABgASUKUQgWAXg5BIQgtA5gVAPQhDAxiVA8QiVA7hCAwQhHA1iECpQh4CbhcAxIgjArQgNAPgEANQgFAPAFARQBkAKCJibQBIhUAjgmQA8hCAsgXQBHglBPgYQARgGBxgcQCcgpB1hXQCEhgAwhCQBLhmg6haQgYgmgiAAQgpAAg4A7gAJwk3QArAqAAA7QAAAqgYAjQgXAjgmARQBFgBAxg2QAwg3AAhNQAAgigMgjIBtAcQAxAJALgPQAMgSg4gqQghgZhag3Qg9gkhEgLQg6gKg1ALQhEAOglAnQgnAqAHA5QADAeAOALQAMAJAXgEIAHgJQAsgpA5AAQA9AAAqAqgASO2QIhnBaQgvAohGAVIiIAkQhOAVgOAtQgPAxA1BhQA9BvBrg1QAlgSA9gwIBohRQBehEAfh4QALgugCgoQgDgmgOgOQgIgJgNAAQgWAAgiAZgAjxQJQgTgQgEgfQgIhMBIgvQBNgxA6ABQA8gBAIA0QALA3grAKIgrAGQgbAFgPAJQgYAOgQAnQgOAhgXAGQgJACgIAAQgTAAgOgMg");
	this.shape_22.setTransform(-0.4,0.1,0.195,0.195);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#0068AD").s().p("AG6eVQgfgiAEguQACgaARgnQDSnpAfoRQAeoeiintQidnek8mRQk3mMmxkVQgugegIgIQgfgcgHgsQgFgdASgMQASgNAZAQQHWEtFXG9QFaG/CnIMQCtIbgXIuQgYI3jdIEQgLAZgUACIgEAAQgVAAgXgag");
	this.shape_23.setTransform(45.8,-13.2,0.195,0.195);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#0068AD").s().p("AyTI9QgngOAJg3QAIgwAfgUQASgMARAAQKLgCJSkDQJUkBG4nXIAVgMQAXgDAFA1QAEArgVAjQgGAJgaAcQm4HVpUEDQpSEDqLACIgPABQgQAAgNgFg");
	this.shape_24.setTransform(21.7,49.5,0.195,0.195);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#0068AD").s().p("EACHAvIIgKgDQoDjImilsQmmlvkBngQj/nahRomQhPocBioXQBqo+E1nxQE6n3HYlYQH/l1JtiRQJtiRJ1BqQBWASgGBKQgFAzglAKIgmAAQn6hVn6BMQoBBNm9DpQmoDelSFPQlWFTjWGhQiREZhSEpQhWEygOEyQgPE6BBFFQA/E8CGErQD4IqG/GmQG/GnI8DeQAhAMAHAGQAeAXABAzQABA5glAHIgLACQgGAAgIgCg");
	this.shape_25.setTransform(-24.5,-2,0.195,0.195);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("EgT0Au7QpIj3nEnDQnDnEj4pJQkApdAAqXQAAqVEApeQD4pJHDnDQHEnEJIj3QJekAKWAAQKWAAJeEAQJKD3HCHEQHEHDD3JJQEAJdAAKWQAAKXkAJdQj3JJnEHEQnCHDpKD3QpdEAqXAAQqWAApekAg");
	this.shape_26.setTransform(0,0,0.195,0.195);

	this.addChild(this.shape_26,this.shape_25,this.shape_24,this.shape_23,this.shape_22,this.shape_21,this.shape_20,this.shape_19,this.shape_18,this.shape_17,this.shape_16,this.shape_15,this.shape_14,this.shape_13,this.shape_12,this.shape_11,this.shape_10,this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-63.5,-63.5,127,127);


(lib.igor_1 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.igor();
	this.instance.setTransform(-115,-236);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-115,-236,231,472);


(lib.bgImg_1 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.bgImg();
	this.instance.setTransform(-150,-300);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-150,-300,300,600);


(lib.banner = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// urText
	this.instance = new lib.urText();
	this.instance.setTransform(0,286.5);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(159).to({_off:false},0).to({alpha:1},10).wait(70).to({alpha:0},10).wait(1));

	// logo
	this.instance_1 = new lib.logo();
	this.instance_1.setTransform(91.2,163.9,0.8,0.8);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(120).to({x:89.2},0).wait(1).to({x:83.2},0).wait(1).to({x:73.2},0).wait(1).to({x:60},0).wait(1).to({x:45},0).wait(1).to({x:30.1},0).wait(1).to({x:17.2},0).wait(1).to({x:7.6},0).wait(1).to({x:1.9},0).wait(1).to({x:0},0).wait(111).to({x:1.9},0).wait(1).to({x:7.7},0).wait(1).to({x:17.8},0).wait(1).to({x:31.4},0).wait(1).to({x:47},0).wait(1).to({x:62.3},0).wait(1).to({x:75.1},0).wait(1).to({x:84.2},0).wait(1).to({x:89.5},0).wait(1).to({x:91.2},0).wait(1));

	// milk
	this.instance_2 = new lib.milk_1();
	this.instance_2.setTransform(0,214);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(250));

	// playBtn
	this.instance_3 = new lib.playBtn_1();
	this.instance_3.setTransform(0,-149.1,0.01,0.01);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(169).to({_off:false},0).wait(1).to({regX:4.2,regY:3.8,scaleX:0.02,scaleY:0.02,x:0.1,y:-149.4},0).wait(1).to({scaleX:0.05,scaleY:0.05,y:-150.9},0).wait(1).to({scaleX:0.1,scaleY:0.1,y:-153.2},0).wait(1).to({scaleX:0.17,scaleY:0.17,y:-156.4},0).wait(1).to({scaleX:0.26,scaleY:0.26,y:-160.3},0).wait(1).to({scaleX:0.36,scaleY:0.36,y:-164.9},0).wait(1).to({scaleX:0.47,scaleY:0.47,x:0,y:-169.8},0).wait(1).to({scaleX:0.57,scaleY:0.57,y:-174.7},0).wait(1).to({scaleX:0.68,scaleY:0.68,y:-179.5},0).wait(1).to({scaleX:0.77,scaleY:0.77,y:-183.8},0).wait(1).to({scaleX:0.85,scaleY:0.85,y:-187.5},0).wait(1).to({scaleX:0.92,scaleY:0.92,y:-190.4},0).wait(1).to({scaleX:0.96,scaleY:0.96,y:-192.6},0).wait(1).to({scaleX:0.99,scaleY:0.99,y:-193.8},0).wait(1).to({regX:0,regY:0,scaleX:1,scaleY:1,x:-4.2,y:-198},0).wait(11).to({rotation:-7,x:-4.7},0).wait(1).to({rotation:0,x:-4.2},0).wait(1).to({rotation:-7,x:-4.7},0).wait(1).to({rotation:0,x:-4.2},0).wait(1).to({rotation:-7,x:-4.7},0).wait(1).to({rotation:0,x:-4.2},0).wait(9).to({rotation:-7,x:-4.7},0).wait(1).to({rotation:0,x:-4.2},0).wait(1).to({rotation:-7,x:-4.7},0).wait(1).to({rotation:0,x:-4.2},0).wait(1).to({rotation:-7,x:-4.7},0).wait(1).to({rotation:0,x:-4.2},0).wait(11).to({rotation:-7,x:-4.7},0).wait(1).to({rotation:0,x:-4.2},0).wait(1).to({rotation:-7,x:-4.7},0).wait(1).to({rotation:0,x:-4.2},0).wait(1).to({rotation:-7,x:-4.7},0).wait(1).to({rotation:0,x:-4.2},0).wait(9).to({alpha:0},10).wait(1));

	// t4
	this.instance_4 = new lib.t4();
	this.instance_4.setTransform(0,-148.3,0.01,0.01);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(169).to({_off:false},0).wait(1).to({scaleX:0.02,scaleY:0.02,y:-148.1},0).wait(1).to({scaleX:0.05,scaleY:0.05,y:-147.4},0).wait(1).to({scaleX:0.1,scaleY:0.1,y:-146.2},0).wait(1).to({scaleX:0.17,scaleY:0.17,y:-144.5},0).wait(1).to({scaleX:0.26,scaleY:0.26,y:-142.4},0).wait(1).to({scaleX:0.36,scaleY:0.36,y:-140},0).wait(1).to({scaleX:0.47,scaleY:0.47,y:-137.5},0).wait(1).to({scaleX:0.57,scaleY:0.57,y:-134.9},0).wait(1).to({scaleX:0.68,scaleY:0.68,y:-132.4},0).wait(1).to({scaleX:0.77,scaleY:0.77,y:-130.1},0).wait(1).to({scaleX:0.85,scaleY:0.85,y:-128.2},0).wait(1).to({scaleX:0.92,scaleY:0.92,y:-126.7},0).wait(1).to({scaleX:0.96,scaleY:0.96,y:-125.6},0).wait(1).to({scaleX:0.99,scaleY:0.99,y:-124.9},0).wait(1).to({scaleX:1,scaleY:1,y:-124.6},0).wait(55).to({alpha:0},10).wait(1));

	// t3_3
	this.instance_5 = new lib.t3_3();
	this.instance_5.setTransform(0,-78.4,0.018,0.018);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(119).to({_off:false},0).wait(1).to({scaleX:0.03,scaleY:0.03,y:-77.7},0).wait(1).to({scaleX:0.08,scaleY:0.08,y:-75.6},0).wait(1).to({scaleX:0.17,scaleY:0.17,y:-71.8},0).wait(1).to({scaleX:0.29,scaleY:0.29,y:-66.4},0).wait(1).to({scaleX:0.45,scaleY:0.45,y:-59.4},0).wait(1).to({scaleX:0.65,scaleY:0.65,y:-51.1},0).wait(1).to({scaleX:0.85,scaleY:0.85,y:-42},0).wait(1).to({scaleX:1.06,scaleY:1.06,y:-32.9},0).wait(1).to({scaleX:1.26,scaleY:1.26,y:-24.5},0).wait(1).to({scaleX:1.43,scaleY:1.43,y:-17.1},0).wait(1).to({scaleX:1.56,scaleY:1.56,y:-11.2},0).wait(1).to({scaleX:1.67,scaleY:1.67,y:-6.7},0).wait(1).to({scaleX:1.74,scaleY:1.74,y:-3.7},0).wait(1).to({scaleX:1.78,scaleY:1.78,y:-2},0).wait(1).to({scaleX:1.79,scaleY:1.79,y:-1.3},0).wait(26).to({scaleX:1.77,scaleY:1.77,x:1.8,y:-8.5},0).wait(1).to({scaleX:1.7,scaleY:1.7,x:7.2,y:-29.3},0).wait(1).to({scaleX:1.59,scaleY:1.59,x:15.5,y:-61.8},0).wait(1).to({scaleX:1.46,scaleY:1.46,x:25.9,y:-102},0).wait(1).to({scaleX:1.32,scaleY:1.32,x:36.9,y:-144.8},0).wait(1).to({scaleX:1.19,scaleY:1.19,x:47.3,y:-185},0).wait(1).to({scaleX:1.08,scaleY:1.08,x:56,y:-218.5},0).wait(1).to({scaleX:0.99,scaleY:1,x:62.3,y:-243.2},0).wait(1).to({scaleX:0.95,scaleY:0.95,x:66.1,y:-257.9},0).wait(1).to({scaleX:0.93,scaleY:0.93,x:67.4,y:-262.7},0).wait(70).to({alpha:0},10).wait(1));

	// t3_2
	this.instance_6 = new lib.t3_2();
	this.instance_6.setTransform(0,-79.1,0.018,0.018);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(119).to({_off:false},0).wait(1).to({scaleX:0.03,scaleY:0.03,y:-79},0).wait(1).to({scaleX:0.08,scaleY:0.08,y:-78.8},0).wait(1).to({scaleX:0.17,scaleY:0.17,y:-78.3},0).wait(1).to({scaleX:0.29,scaleY:0.29,y:-77.7},0).wait(1).to({scaleX:0.45,scaleY:0.45,y:-76.9},0).wait(1).to({scaleX:0.65,scaleY:0.65,y:-75.9},0).wait(1).to({scaleX:0.85,scaleY:0.85,y:-74.8},0).wait(1).to({scaleX:1.06,scaleY:1.06,y:-73.8},0).wait(1).to({scaleX:1.26,scaleY:1.26,y:-72.8},0).wait(1).to({scaleX:1.43,scaleY:1.43,y:-71.9},0).wait(1).to({scaleX:1.56,scaleY:1.56,y:-71.2},0).wait(1).to({scaleX:1.67,scaleY:1.67,y:-70.7},0).wait(1).to({scaleX:1.74,scaleY:1.74,y:-70.4},0).wait(1).to({scaleX:1.78,scaleY:1.78,y:-70.2},0).wait(1).to({scaleX:1.79,scaleY:1.79,y:-70.1},0).wait(26).to({scaleX:1.77,scaleY:1.77,x:-0.6,y:-75.1},0).wait(1).to({scaleX:1.7,scaleY:1.7,x:-2.4,y:-89.9},0).wait(1).to({scaleX:1.59,scaleY:1.59,x:-5.2,y:-112.8},0).wait(1).to({scaleX:1.46,scaleY:1.46,x:-8.7,y:-141.3},0).wait(1).to({scaleX:1.32,scaleY:1.32,x:-12.4,y:-171.5},0).wait(1).to({scaleX:1.19,scaleY:1.19,x:-15.9,y:-199.9},0).wait(1).to({scaleX:1.08,scaleY:1.08,x:-18.8,y:-223.6},0).wait(1).to({scaleX:0.99,scaleY:1,x:-21,y:-241},0).wait(1).to({scaleX:0.95,scaleY:0.95,x:-22.2,y:-251.4},0).wait(1).to({scaleX:0.93,scaleY:0.93,x:-22.6,y:-254.8},0).wait(70).to({alpha:0},10).wait(1));

	// t3_1
	this.instance_7 = new lib.t3_1();
	this.instance_7.setTransform(0,-79.9,0.018,0.018);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(119).to({_off:false},0).wait(1).to({scaleX:0.03,scaleY:0.03,y:-80.5},0).wait(1).to({scaleX:0.08,scaleY:0.08,y:-82.6},0).wait(1).to({scaleX:0.17,scaleY:0.17,y:-86.1},0).wait(1).to({scaleX:0.29,scaleY:0.29,y:-91.2},0).wait(1).to({scaleX:0.45,scaleY:0.45,y:-97.8},0).wait(1).to({scaleX:0.65,scaleY:0.65,y:-105.6},0).wait(1).to({scaleX:0.85,scaleY:0.85,y:-114.2},0).wait(1).to({scaleX:1.06,scaleY:1.06,y:-122.8},0).wait(1).to({scaleX:1.26,scaleY:1.26,y:-130.8},0).wait(1).to({scaleX:1.43,scaleY:1.43,y:-137.7},0).wait(1).to({scaleX:1.56,scaleY:1.56,y:-143.3},0).wait(1).to({scaleX:1.67,scaleY:1.67,y:-147.5},0).wait(1).to({scaleX:1.74,scaleY:1.74,y:-150.4},0).wait(1).to({scaleX:1.78,scaleY:1.78,y:-152},0).wait(1).to({scaleX:1.79,scaleY:1.79,y:-152.4},0).wait(26).to({scaleX:1.77,scaleY:1.77,x:-2.5,y:-155.3},0).wait(1).to({scaleX:1.7,scaleY:1.7,x:-9.7,y:-164},0).wait(1).to({scaleX:1.59,scaleY:1.59,x:-20.9,y:-177.4},0).wait(1).to({scaleX:1.46,scaleY:1.46,x:-34.7,y:-194.1},0).wait(1).to({scaleX:1.32,scaleY:1.32,x:-49.5,y:-211.8},0).wait(1).to({scaleX:1.19,scaleY:1.19,x:-63.3,y:-228.4},0).wait(1).to({scaleX:1.08,scaleY:1.08,x:-74.9,y:-242.4},0).wait(1).to({scaleX:0.99,scaleY:1,x:-83.4,y:-252.6},0).wait(1).to({scaleX:0.95,scaleY:0.95,x:-88.4,y:-258.7},0).wait(1).to({scaleX:0.93,scaleY:0.93,x:-90.1,y:-260.6},0).wait(70).to({alpha:0},10).wait(1));

	// t2_2
	this.instance_8 = new lib.t2_2();
	this.instance_8.setTransform(-27.4,3.2,0.021,0.059);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(69).to({_off:false},0).wait(1).to({scaleX:0.03,scaleY:0.07,x:-27.2,y:1.2},0).wait(1).to({scaleX:0.05,scaleY:0.09,x:-26.5,y:-4.9},0).wait(1).to({scaleX:0.1,scaleY:0.13,x:-25.3,y:-15.5},0).wait(1).to({scaleX:0.16,scaleY:0.2,x:-23.5,y:-30.7},0).wait(1).to({scaleX:0.24,scaleY:0.27,x:-21.2,y:-50.4},0).wait(1).to({scaleX:0.34,scaleY:0.37,x:-18.4,y:-74},0).wait(1).to({scaleX:0.45,scaleY:0.47,x:-15.4,y:-100.3},0).wait(1).to({scaleX:0.57,scaleY:0.58,x:-12.2,y:-127.7},0).wait(1).to({scaleX:0.68,scaleY:0.69,x:-9.1,y:-154},0).wait(1).to({scaleX:0.78,scaleY:0.78,x:-6.3,y:-177.8},0).wait(1).to({scaleX:0.86,scaleY:0.86,x:-4,y:-197.6},0).wait(1).to({scaleX:0.92,scaleY:0.93,x:-2.2,y:-213},0).wait(1).to({scaleX:0.97,scaleY:0.97,x:-1,y:-223.7},0).wait(1).to({scaleX:0.99,scaleY:0.99,x:-0.2,y:-229.9},0).wait(1).to({scaleX:1,scaleY:1,x:0,y:-231.8},0).wait(25).to({alpha:0},10).to({_off:true},1).wait(130));

	// t2_1
	this.instance_9 = new lib.t2_1();
	this.instance_9.setTransform(-210,48.8);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(59).to({_off:false},0).to({x:-85.8},10,cjs.Ease.get(1)).wait(40).to({alpha:0},10).to({_off:true},1).wait(130));

	// t1_2
	this.instance_10 = new lib.t1_2();
	this.instance_10.setTransform(15.3,7.1,0.025,0.06);
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(10).to({_off:false},0).wait(1).to({scaleX:0.03,scaleY:0.07,x:15.1,y:4.9},0).wait(1).to({scaleX:0.06,scaleY:0.1,x:14.5,y:-1.8},0).wait(1).to({scaleX:0.12,scaleY:0.15,x:13.6,y:-13.3},0).wait(1).to({scaleX:0.19,scaleY:0.22,x:12.2,y:-29.7},0).wait(1).to({scaleX:0.28,scaleY:0.31,x:10.4,y:-50.7},0).wait(1).to({scaleX:0.39,scaleY:0.41,x:8.3,y:-75.4},0).wait(1).to({scaleX:0.51,scaleY:0.52,x:6,y:-102.2},0).wait(1).to({scaleX:0.63,scaleY:0.64,x:3.7,y:-129.2},0).wait(1).to({scaleX:0.74,scaleY:0.75,x:1.5,y:-154.3},0).wait(1).to({scaleX:0.83,scaleY:0.84,x:-0.3,y:-175.9},0).wait(1).to({scaleX:0.91,scaleY:0.91,x:-1.7,y:-192.8},0).wait(1).to({scaleX:0.96,scaleY:0.96,x:-2.8,y:-204.8},0).wait(1).to({scaleX:0.99,scaleY:0.99,x:-3.4,y:-211.8},0).wait(1).to({scaleX:1,scaleY:1,x:-3.5,y:-214},0).wait(25).to({alpha:0},10).to({_off:true},1).wait(190));

	// t1_1
	this.instance_11 = new lib.t1_1();
	this.instance_11.setTransform(203,69.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_11).to({x:94.6},10,cjs.Ease.get(1)).wait(39).to({alpha:0},10).to({_off:true},1).wait(190));

	// igor
	this.instance_12 = new lib.igor_1();
	this.instance_12.setTransform(268,64);
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(59).to({_off:false},0).to({x:34},10,cjs.Ease.get(1)).wait(40).to({x:268},10,cjs.Ease.get(-1)).to({_off:true},1).wait(39).to({_off:false,scaleX:0.62,scaleY:0.62,x:223},0).to({x:79},10).wait(70).to({x:223},10,cjs.Ease.get(-1)).wait(1));

	// tanya
	this.instance_13 = new lib.tanya_1();
	this.instance_13.setTransform(-275,75);

	this.timeline.addTween(cjs.Tween.get(this.instance_13).to({x:-27},10,cjs.Ease.get(1)).wait(39).to({x:-275},10,cjs.Ease.get(-1)).to({_off:true},1).wait(99).to({_off:false,scaleX:0.62,scaleY:0.62,x:-227,y:70},0).to({x:-74},10).wait(70).to({x:-227},10,cjs.Ease.get(-1)).wait(1));

	// bgImg
	this.instance_14 = new lib.bgImg_1();

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(250));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-398,-300,650.1,601);


// stage content:
(lib._300x600 = function() {
	this.initialize();

	// cover
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#666666").ss(2,1,1).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape.setTransform(150,300);

	// banner
	this.instance = new lib.banner();
	this.instance.setTransform(150,300);

	this.addChild(this.instance,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-98,299,650.1,602);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;