(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.bgImg1 = function() {
	this.initialize(img.bgImg1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,367);


(lib.bgImg2 = function() {
	this.initialize(img.bgImg2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,367);


(lib.bgImg3 = function() {
	this.initialize(img.bgImg3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,367);


(lib.bgImg4 = function() {
	this.initialize(img.bgImg4);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,367);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.urText_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ARbCoIAAhJIAJAAIAAAIQACgEAFgDQAEgCAGAAQAGAAAFADQAGAEADAFQADAGAAAIQAAAHgDAGQgDAGgGADQgGAEgFAAQgGAAgEgDQgFgDgCgDIAAAfgARrBpQgEADgBADQgCAEAAAFQAAAFACAEQABADAEACQADADAFAAQAEAAAEgDQADgDACgCQACgEAAgFQAAgFgCgEQgCgDgDgDQgEgCgEAAQgFAAgDACgAvECoIAAhJIAJAAIAAAIQACgEAFgDQAEgCAGAAQAGAAAFADQAGAEADAFQADAGAAAIQAAAHgDAGQgDAGgGADQgGAEgFAAQgGAAgEgDQgFgDgCgDIAAAfgAu0BpQgEADgBADQgCAEAAAFQAAAFACAEQABADAEACQADADAFAAQAEAAAEgDQADgDACgCQACgEAAgFQAAgFgCgEQgCgDgDgDQgEgCgEAAQgFAAgDACgASXCRIgCgDIgBgDIABgDIACgDIAEgBIADABIACADIABADIgBADIgCADIgDABgAO8CMQgGgEgDgIQgDgJAAgKQAAgLADgJQACgIAHgFQAGgFAIAAQAJAAAGAFQAGAFADAIQADAJAAALQAAAKgDAJQgDAIgGAEQgGAFgJABQgJgBgFgFgAPBBUQgEADgCAHQgCAHAAAIQAAAHACAHQACAHAEADQAEADAFAAQAGAAADgDQAEgDACgHQACgFAAgJQAAgKgCgFQgCgGgEgEQgDgEgGAAQgFAAgEAEgANrCRIgCgDIgBgDIABgDIACgDIAEgBIADABIACADIABADIgBADIgCADIgDABgAMICMQgGgEgDgIQgDgJAAgKQAAgLADgJQACgIAHgFQAGgFAIAAQAJAAAGAFQAGAFADAIQADAJAAALQAAAKgDAJQgDAIgGAEQgGAFgJABQgJgBgFgFgAMNBUQgEADgCAHQgCAHAAAIQAAAHACAHQACAHAEADQAEADAFAAQAGAAADgDQAEgDACgHQACgFAAgJQAAgKgCgFQgCgGgEgEQgDgEgGAAQgFAAgEAEgALpCRIgCgDIgBgDIABgDIACgDIAEgBIADABIACADIABADIgBADIgCADIgDABgAJ5COQgFgDgDgGQgDgGAAgHQAAgIADgGQADgFAFgEQAFgDAHAAQAFAAAEACQAEADADAEIAAgIIAKAAIAAAxIgKAAIAAgHQgDAEgEACQgEADgFAAQgGAAgGgEgAJ/BpQgDACgDAEQgCAFAAAEQAAADACAGQADADADACQACADAGAAQAFAAACgDQADgCADgDQACgEAAgFQAAgFgCgEQgDgEgDgCQgCgCgFAAQgGAAgCACgAGoCOQgGgCgDgHQgEgHAAgGQAAgGAEgIQADgGAGgDQAHgDAGAAQAHAAAGADQAFAEAEAGQADAFAAAIQAAAHgDAGQgEAHgFACQgGAEgHAAQgGAAgHgEgAGtBpQgDABgDAFQgCAEAAAFQAAAFACAEQADADADACIAIADIAIgDQADgCACgDQACgEAAgFQAAgFgCgEQgCgFgDgBQgEgCgEAAQgEAAgEACgAEvCOQgFgDgDgGQgDgGAAgHQAAgIADgGQADgFAFgEQAFgDAHAAQAFAAAEACQAEADADAEIAAgIIAKAAIAAAxIgKAAIAAgHQgDAEgEACQgEADgFAAQgGAAgGgEgAE1BpQgDACgDAEQgCAFAAAEQAAADACAGQADADADACQACADAGAAQAFAAACgDQADgCADgDQACgEAAgFQAAgFgCgEQgDgEgDgCQgCgCgFAAQgGAAgCACgAC9CNQgIgFgEgIQgFgIAAgLQAAgLAFgJQAEgIAIgFQAIgFAJAAQAJABAIAEQAIADAFAHIgIAGQgDgFgGgDQgHgDgGAAQgGAAgGADQgFADgEAHQgDAGAAAJQAAAIADAGQAEAHAFADQAGADAGAAQAHAAAGgDQAFgCAEgGIAIAFQgFAHgIAEQgIAFgJAAQgJAAgIgFgACHCRIgCgDIgBgDIABgDIACgDIAEgBIADABIACADIABADIgBADIgCADIgDABgAjRCRIABgIIADAAQAAAAABgBQAAAAABAAQABAAAAAAQAAgBABAAIABgEIACgkIAnAAIAAAxIgJAAIAAgpIgVAAIAAASIgCAOQgBAFgEADQgDADgGAAgAj/COQgGgCgDgHQgEgHAAgGQAAgGAEgIQADgGAGgDQAHgDAGAAQAHAAAGADQAFAEAEAGQADAFAAAIQAAAHgDAGQgEAHgFACQgGAEgHAAQgGAAgHgEgAj6BpQgDABgDAFQgCAEAAAFQAAAFACAEQADADADACIAIADIAIgDQADgCACgDQACgEAAgFQAAgFgCgEQgCgFgDgBQgEgCgEAAQgEAAgEACgAmpCOQgGgCgDgHQgEgHAAgGQAAgGAEgIQADgGAGgDQAHgDAGAAQAHAAAGADQAFAEAEAGQADAFAAAIQAAAHgDAGQgEAHgFACQgGAEgHAAQgGAAgHgEgAmkBpQgDABgDAFQgCAEAAAFQAAAFACAEQADADADACIAIADIAIgDQADgCACgDQACgEAAgFQAAgFgCgEQgCgFgDgBQgEgCgEAAQgEAAgEACgArgCOQgFgDgDgGQgDgGAAgHQAAgIADgGQADgFAFgEQAFgDAHAAQAFAAAEACQAEADADAEIAAgIIAKAAIAAAxIgKAAIAAgHQgDAEgEACQgEADgFAAQgGAAgGgEgAraBpQgDACgDAEQgCAFAAAEQAAADACAGQADADADACQACADAGAAQAFAAACgDQADgCADgDQACgEAAgFQAAgFgCgEQgDgEgDgCQgCgCgFAAQgGAAgCACgAtDCOQgGgCgDgHQgEgHAAgGQAAgHAEgGQACgGAGgEQAHgDAHAAQAGAAAGACQAGAEADADIgHAHQgCgEgEgBQgDgCgFAAQgDAAgFACQgDACgDAEQgCAEAAAFQAAAFACAEQACADAEACQADADAFAAQAFAAADgCIAGgFIAGAGQgCAEgGADQgGADgGAAQgHAAgGgEgAv3COQgGgCgDgHQgEgHAAgGQAAgGAEgIQADgGAGgDQAHgDAGAAQAHAAAGADQAFAEAEAGQADAFAAAIQAAAHgDAGQgEAHgFACQgGAEgHAAQgGAAgHgEgAvyBpQgDABgDAFQgCAEAAAFQAAAFACAEQADADADACIAIADIAIgDQADgCACgDQACgEAAgFQAAgFgCgEQgCgFgDgBQgEgCgEAAQgEAAgEACgAQtCQIAAg9IgTAJIAAgJIAVgKIAIAAIAABHgAPqCQIAAgHIAbgeIAEgHIACgHQAAgGgEgDQgDgEgHAAIgJACIgIADIgEgIIAKgEIALgCQAGAAAGADQAGACADAEQADAFAAAHQAAADgCAHQgCADgEAGIgWAZIAfAAIAAAIgAN8CQIAAgHIAbgeIAEgHIACgHQAAgGgEgDQgDgEgHAAIgJACIgIADIgEgIIAKgEIALgCQAGAAAGADQAGACADAEQADAFAAAHQAAADgCAHQgCADgEAGIgWAZIAfAAIAAAIgAM2CQIAAgHIAbgeIAEgHIACgHQAAgGgEgDQgDgEgHAAIgJACIgIADIgEgIIAKgEIALgCQAGAAAGADQAGACADAEQADAFAAAHQAAADgCAHQgCADgEAGIgWAZIAfAAIAAAIgALPCQIAAg9IgTAJIAAgJIAVgKIAIAAIAABHgAJWCQIAAgVIgYAAIAAAVIgJAAIAAgxIAJAAIAAATIAYAAIAAgTIAKAAIAAAxgAIKCQIAAgjIgQAWIgGAAIgQgWIAAAjIgJAAIAAgxIAJAAIATAaIATgaIAJAAIAAAxgAGECQIAAgVIgYAAIAAAVIgJAAIAAgxIAJAAIAAATIAYAAIAAgTIAKAAIAAAxgAEBCQIAAgpIgRAAIAAgIIAsAAIAAAIIgRAAIAAApgABtCQIAAgjIgaAjIgJAAIAAgxIAKAAIAAAkIAZgkIAJAAIAAAxgAA0CQIAAgjIgQAWIgGAAIgQgWIAAAjIgJAAIAAgxIAJAAIATAaIATgaIAJAAIAAAxgAgOCQIAAgxIAJAAIAAAxgAgpCQIAAgVIgYAAIAAAVIgKAAIAAgxIAKAAIAAATIAYAAIAAgTIAKAAIAAAxgAhwCQIAAgpIgRAAIAAgIIAsAAIAAAIIgRAAIAAApgAiQCQIAAgxIAJAAIAAAxgAkjCQIAAgVIgYAAIAAAVIgKAAIAAgxIAKAAIAAATIAYAAIAAgTIAKAAIAAAxgAl2CQIAAgxIAVAAQAKABAEADQAEADAAAGQAAAEgBADIgGAEQAGACABACQADAEAAAEQAAACgCAFIgGAEQgEACgGAAgAltCJIANAAQAGAAACgCQACgBAAgEQAAgHgKAAIgNAAgAltB0IALAAQAFAAACgCQADgCAAgDQAAgGgKAAIgLAAgAnNCQIAAgpIgYAAIAAApIgKAAIAAgxIAsAAIAAAxgAoWCQIAAgTIgLAAIgMATIgKAAIAMgUQgGgBgDgDQgDgEAAgFQAAgIAGgDQAFgFAJAAIAWAAIAAAxgAoqBpQgDABAAAFQAAADADACQACADAFAAIANAAIAAgQIgNAAQgFAAgCACgApPCQIAAgVIgYAAIAAAVIgKAAIAAgxIAKAAIAAATIAYAAIAAgTIAKAAIAAAxgAqLCQIAAgVIgYAAIAAAVIgKAAIAAgxIAKAAIAAATIAYAAIAAgTIAKAAIAAAxgAsOCQIAAgpIgRAAIAAgIIAsAAIAAAIIgRAAIAAApgAtmCQIAAgjIgaAjIgJAAIAAgxIAKAAIAAAkIAZgkIAJAAIAAAxgAwRCQIgNgUIgBgBIgCAAIgIAAIAAAVIgKAAIAAgxIAKAAIAAATIAIAAIACAAIABgBIANgSIALAAIgRAYIARAZgAxMCQIAAgjIgaAjIgJAAIAAgxIAKAAIAAAkIAZgkIAJAAIAAAxgAygCQIAAgxIAVAAQAKABAEADQAEADAAAGQAAAEgBADIgGAEQAGACABACQADAEAAAEQAAACgCAFIgGAEQgEACgGAAgAyXCJIANAAQAGAAACgCQACgBAAgEQAAgHgKAAIgNAAgAyXB0IALAAQAFAAACgCQADgCAAgDQAAgGgKAAIgLAAgAgNBUIgCgCIgBgEIABgDIACgCIADgBIAEABIACACIABADIgBAEIgCACIgEABgAiPBUIgCgCIgBgEIABgDIACgCIADgBIAEABIACACIABADIgBAEIgCACIgEABgAs9AnIAFgHQACgDABgFIgEgBQgBgBAAAAQAAgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAgBQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAABgBQAAAAABAAQABAAAAAAQADAAADACQACAEAAAEQAAAFgEAFQgEAHgFADgALjAlIAAgNIgoAAIAAANIgJAAIAAgVIAGAAQACgDABgEQABgEAAgIIABgUIAnAAIAAAnIAHAAIAAAVgALGgDIgCALQgBAGgBACIAYAAIAAgfIgUAAgArNAlIAAgNIhDAAIAAgvIAJAAIAAAnIAUAAIAAgnIAJAAIAAAnIAUAAIAAgnIAJAAIAAAnIAIAAIAAAVgALuAZIABgJIADAAQAAAAABAAQAAAAABAAQAAAAABAAQAAgBABAAIABgEIACgiIAnAAIAAAvIgJAAIAAgnIgVAAIAAAQQAAAHgCAHQgBAFgEADQgDACgGAAgAJwAWQgGgCgDgHQgEgHAAgGQAAgFAEgIQADgFAFgEQAGgDAHAAQAHAAAFADQAGADADAGQADAFAAAHIAAAEIgnAAIADAHQADADADACQADACAFAAQAFAAADgCIAHgEIAFAGQgDAEgGACQgGACgGAAQgGABgHgEgAKKgEQgBgGgDgDQgEgDgGAAQgGAAgEADQgDADgCAGIAdAAIAAAAgAGGAZIACgJIADAAQADAAACgCQABgBABgHIACg0IAyAAIAABGIgKAAIAAg9IgeAAIgBAdIgCAUQgBAHgEADQgEAEgHgBgAFjAYIgCgCIgBgDIABgEIACgCIAEAAIADAAIACACIABAEIgBADIgCACIgDABgADWAWQgGgCgDgHQgEgHAAgGQAAgGAEgGQACgGAGgEQAHgDAHAAQAGAAAGADQAGADADAEIgHAFQgCgDgEgBQgDgCgFAAQgDAAgFACQgDACgDAEQgCAEAAAEQAAAFACADQACAEAEACQADACAFAAQAFAAADgBIAGgFIAGAGQgCAEgGADQgGACgGAAQgHABgGgEgAAOAWQgGgCgDgHQgEgHAAgGQAAgFAEgIQADgFAFgEQAGgDAHAAQAHAAAFADQAGADADAGQADAFAAAHIAAAEIgnAAIADAHQADADADACQADACAFAAQAFAAADgCIAHgEIAFAGQgDAEgGACQgGACgGAAQgGABgHgEgAAogEQgBgGgDgDQgEgDgGAAQgGAAgEADQgDADgCAGIAdAAIAAAAgAg7AZIABgJIADAAQAAAAABAAQAAAAABAAQAAAAABAAQAAgBABAAIABgEIACgiIAnAAIAAAvIgJAAIAAgnIgVAAIAAAQIgCAOQgBAFgEADQgDACgGAAgAhqAWQgFgDgDgGQgDgGAAgHQAAgHADgGQADgFAFgEQAFgDAHAAQAFAAAEADQAEABADAFIAAgHIAKAAIAAAvIgKAAIAAgHQgDAEgEACQgEACgFAAQgGABgGgEgAhkgOQgDACgDAEQgCAFAAADQAAAEACAEQADAFADABQACACAGAAQAFAAACgCQADgBADgFQACgDAAgFQAAgFgCgDQgDgEgDgCQgCgCgFAAQgGAAgCACgAigAXQgGgCgDgEIAGgFQACACAEACQAEABAFAAQAGAAADgCQADgCAAgDQAAgHgKAAIgLAAIAAgGIAIAAQAGAAACgBQADgCAAgEQAAgDgCgCQgDgCgFAAQgIAAgGAGIgFgGQADgDAFgDQAHgCAFAAQAIAAAGAEQAEAEAAAGQAAAEgCADQgBACgEACQAFAAACADQACADAAAFQAAAEgCADQgCADgGACQgGACgFAAQgGAAgGgCgAjhAWQgGgCgDgHQgDgGAAgHQAAgGADgGQADgGAGgEQAHgDAGAAQAGAAAGADQAGACADAEIgGAGQgDgDgDgCIgIgCIgIACQgEACgCADIgDAHIAYAAIAAAGIgYAAQABAHAEAEQAEADAIAAQAEAAAEgCQADgBADgDIAGAFQgDAEgGADQgGACgGAAQgGABgHgEgAkeAWQgFgDgDgGQgDgGAAgHQAAgHADgGQADgFAFgEQAFgDAHAAQAFAAAEADQAEABADAFIAAgHIAKAAIAAAvIgKAAIAAgHQgDAEgEACQgEACgFAAQgGABgGgEgAkYgOQgDACgDAEQgCAFAAADQAAAEACAEQADAFADABQACACAGAAQAFAAACgCQADgBADgFQACgDAAgFQAAgFgCgDQgDgEgDgCQgCgCgFAAQgGAAgCACgAnVAZIABgJIADAAQAAAAABAAQABAAAAAAQABAAAAAAQAAgBABAAIABgEIACgiIAnAAIAAAvIgJAAIAAgnIgVAAIAAAQIgCAOQgBAFgEADQgDACgGAAgAq3AWQgGgCgDgHQgEgHAAgGQAAgFAEgIQADgGAGgDQAHgDAGAAQAHAAAGADQAFADAEAHQADAFAAAHQAAAIgDAFQgEAHgFACQgGAEgHgBQgGABgHgEgAqygNQgDABgDAEQgCAEAAAEQAAAFACADQADAFADABIAIACIAIgCQADgBACgFQACgDAAgFQAAgEgCgEQgCgEgDgBQgEgDgEAAQgEAAgEADgAwVAWQgGgCgDgHQgEgHAAgGQAAgFAEgIQADgGAGgDQAHgDAGAAQAHAAAGADQAFADAEAHQADAFAAAHQAAAIgDAFQgEAHgFACQgGAEgHgBQgGABgHgEgAwQgNQgDABgDAEQgCAEAAAEQAAAFACADQADAFADABIAIACIAIgCQADgBACgFQACgDAAgFQAAgEgCgEQgCgEgDgBQgEgDgEAAQgEAAgEADgANNAYIAAgTIgLAAIgMATIgKAAIAMgUQgGgBgDgDQgDgCAAgHQAAgGAGgFQAFgDAJAAIAWAAIAAAvgAM5gOQgDABAAAEQAAAFADABQACACAFAAIANAAIAAgPIgNAAQgFAAgCACgAIXAYIAAgvIAJAAIAAAnIAUAAIAAgnIAJAAIAAAnIAUAAIAAgnIAJAAIAAAvgAH9AYIAAgjIgaAjIgJAAIAAgvIAKAAIAAAiIAZgiIAJAAIAAAvgAExAYIAAgvIAJAAIAAARIALAAQAKAAAFADQAFAEAAAHQAAAJgFADQgGAEgJAAgAE6AQIAKAAQALAAAAgIQAAgEgCgBQgDgCgGAAIgKAAgAELAYIAAgnIgRAAIAAgIIAsAAIAAAIIgRAAIAAAngAC5AYIAAgvIAJAAIAAAvgACeAYIAAgVIgYAAIAAAVIgJAAIAAgvIAJAAIAAATIAYAAIAAgTIAKAAIAAAvgABsAYIgMgUIgBAAIgCgBIgEAAIAAAVIgJAAIAAgVIgEAAIgCABIgBAAIgMAUIgLAAIAQgZIgQgWIALAAIAMARIABABIACABIAEAAIAAgTIAJAAIAAATIAEAAIACgBIABgBIAMgRIALAAIgQAWIAQAZgAk3AYIgNgUIgBAAIgCgBIgIAAIAAAVIgJAAIAAgvIAJAAIAAATIAIAAIACgBIABgBIANgRIALAAIgRAWIARAZgAlyAYIAAgjIgaAjIgJAAIAAgvIAKAAIAAAiIAZgiIAJAAIAAAvgAnhAYIgNgUIgBAAIgCgBIgIAAIAAAVIgJAAIAAgvIAJAAIAAATIAIAAIACgBIABgBIANgRIALAAIgRAWIARAZgAocAYIAAgjIgaAjIgJAAIAAgvIAKAAIAAAiIAZgiIAJAAIAAAvgApxAYIAAgvIAWAAQAKgBAEAEQAEADAAAGQAAAEgBADIgGAEQAGABABACQADAEAAAEQAAACgCAEIgGAGQgEABgGAAgApnARIANAAQAGAAACgCQACgCAAgDQAAgHgKAAIgNAAgApngDIALAAQAFAAACgBQADgCAAgEQAAgHgKABIgLAAgAtTAYIAAgVIgYAAIAAAVIgKAAIAAgvIAKAAIAAATIAYAAIAAgTIAKAAIAAAvgAuOAYIAAgjIgaAjIgJAAIAAgvIAKAAIAAAiIAZgiIAJAAIAAAvgAvWAYIAAgnIgRAAIAAgIIAsAAIAAAIIgRAAIAAAngAwvAYIgNgUIgBAAIgCgBIgIAAIAAAVIgKAAIAAgvIAKAAIAAATIAIAAIACgBIABgBIANgRIALAAIgRAWIARAZgAxkAYIAAgvIAJAAIAAAvgAx/AYIAAgVIgYAAIAAAVIgJAAIAAgvIAJAAIAAATIAYAAIAAgTIAKAAIAAAvgAC6gkIgCgCIgBgCIABgEIACgCIADgBIAEABIACACIABAEIgBACIgCACIgEACgAxjgkIgCgCIgBgCIABgEIACgCIADgBIAEABIACACIABAEIgBACIgCACIgEACgAouhGIgEgBIACgIIAGABIAFgBIADgEIAEgGIACgFIgVgyIALAAIAPAnIAPgnIAKAAIgcBDQgDADgEACQgDADgFAAgACbhHIAAhJIAJAAIAAAHQACgDAFgCQAEgDAGAAQAGAAAFAEQAGACADAHQADAGAAAGQAAAIgDAGQgDAGgGADQgGADgFAAQgGAAgEgCQgFgCgCgEIAAAfgACriGQgEACgBAEQgCAEAAAEQAAAGACADQABAEAEADQADABAFAAQAEAAAEgBQADgDACgEQACgDAAgGQAAgEgCgEQgCgDgDgDQgEgCgEAAQgFAAgDACgAlshHIAAhJIAJAAIAAAHQACgDAFgCQAEgDAGAAQAGAAAFAEQAGACADAHQADAGAAAGQAAAIgDAGQgDAGgGADQgGADgFAAQgGAAgEgCQgFgCgCgEIAAAfgAlciGQgEACgBAEQgCAEAAAEQAAAGACADQABAEAEADQADABAFAAQAEAAAEgBQADgDACgEQACgDAAgGQAAgEgCgEQgCgDgDgDQgEgCgEAAQgFAAgDACgAJmhhQgGgCgDgHQgEgHAAgHQAAgGAEgGQACgFAGgEQAHgEAHAAQAGAAAGADQAGADADADIgHAGQgCgCgEgCQgDgCgFAAQgDAAgFACQgDACgDAEQgCAEAAAEQAAAGACADQACAEAEADQAFABADAAQAFAAADgBQAEgCACgDIAGAGQgCAEgGADQgGACgGAAQgHAAgGgDgAF8heIABgJIADAAQAAAAABAAQABAAAAAAQAAAAABAAQAAgBABAAIABgFIACgjIAnAAIAAAxIgJAAIAAgpIgVAAIAAARQAAAIgCAHQgBAFgEADQgDACgGAAgAFOhhQgGgCgDgHQgEgHAAgGQAAgHAEgGQADgHAGgCQAHgEAGAAQAHAAAGAEQAFADAEAGQADAFAAAIQAAAHgDAGQgEAHgFACQgGADgHAAQgGAAgHgDgAFTiFQgDAAgDAFQgCADAAAGQAAAFACADQADAEADADIAIABIAIgBQADgDACgEQACgDAAgFQAAgGgCgDQgCgFgDAAQgEgDgEAAQgEAAgEADgAEXhgQgGgCgDgEIAGgGQACADAEACQAEACAFgBQAGAAADgBQADgCAAgFQAAgGgKAAIgLAAIAAgHIAIAAQAGAAACgBQADgDAAgDQAAgEgCgBQgDgCgFAAQgIAAgGAGIgFgGQADgEAFgCQAHgCAFAAQAIAAAGAEQAEAEAAAGQAAAEgCADQgBACgEACQAFACACACQACACAAAFQAAAEgCAEQgCADgGADQgGABgFAAQgGAAgGgCgADghhQgGgCgDgHQgEgHAAgGQAAgHAEgGQADgHAGgCQAHgEAGAAQAHAAAGAEQAFADAEAGQADAFAAAIQAAAHgDAGQgEAHgFACQgGADgHAAQgGAAgHgDgADliFQgDAAgDAFQgCADAAAGQAAAFACADQADAEADADIAIABIAIgBQADgDACgEQACgDAAgFQAAgGgCgDQgCgFgDAAQgEgDgEAAQgEAAgEADgABohhQgGgCgDgHQgEgHAAgGQAAgHAEgGQADgHAFgCQAGgEAHAAQAHAAAFAEQAGADADAFQADAFAAAHIAAAEIgnAAIADAIQADADADACQADACAFAAQAFAAADgBIAHgFIAFAGQgDAEgGACQgGACgGAAQgGAAgHgDgACCh7QgBgHgDgDQgEgDgGgBQgGABgEADQgDACgCAIIAdAAIAAAAgAgOheIgCgDIgBgEIABgCIACgDIAEgBIADABIACADIABACIgBAEIgCADIgDAAgAjwhgQgGgCgDgEIAGgGQACADAEACQAEACAFgBQAGAAADgBQADgCAAgFQAAgGgKAAIgLAAIAAgHIAIAAQAGAAACgBQADgDAAgDQAAgEgCgBQgDgCgFAAQgIAAgGAGIgFgGQADgEAFgCQAHgCAFAAQAIAAAGAEQAEAEAAAGQAAAEgCADQgBACgEACQAFACACACQACACAAAFQAAAEgCAEQgCADgGADQgGABgFAAQgGAAgGgCgAnvhhQgGgCgDgHQgEgHAAgHQAAgGAEgGQACgFAGgEQAHgEAHAAQAGAAAGADQAGADADADIgHAGQgCgCgEgCQgDgCgFAAQgDAAgFACQgDACgDAEQgCAEAAAEQAAAGACADQACAEAEADQAFABADAAQAFAAADgBQAEgCACgDIAGAGQgCAEgGADQgGACgGAAQgHAAgGgDgApnhhQgGgCgDgHQgDgGAAgIQAAgGADgGQADgFAGgEQAHgEAGAAQAGAAAGADQAGACADAEIgGAGQgDgEgDgBIgIgCIgIACQgEABgCAEIgDAHIAYAAIAAAHIgYAAQABAHAEAEQAEADAIAAQAEAAAEgBQADgCADgDIAGAFQgDAEgGADQgGACgGAAQgGAAgHgDgAqkhhQgFgDgDgGQgDgGAAgIQAAgGADgGQADgHAFgCQAFgEAHAAQAFAAAEADQAEACADADIAAgHIAKAAIAAAxIgKAAIAAgHQgDAEgEACQgEACgFAAQgGAAgGgDgAqeiGQgDACgDAEQgCAFAAADQAAAEACAFQADAEADADQACABAGAAQAFAAACgBQADgDADgEQACgDAAgGQAAgEgCgEQgDgEgDgCQgCgCgFAAQgGAAgCACgAtvheIABgJIADAAQAAAAABAAQABAAAAAAQAAAAABAAQAAgBABAAIABgFIACgjIAnAAIAAAxIgJAAIAAgpIgVAAIAAARQAAAIgCAHQgBAFgEADQgDACgGAAgAxRhhQgGgCgDgHQgEgHAAgGQAAgHAEgGQADgHAFgCQAGgEAHAAQAHAAAFAEQAGADADAFQADAFAAAHIAAAEIgnAAIADAIQADADADACQADACAFAAQAFAAADgBIAHgFIAFAGQgDAEgGACQgGACgGAAQgGAAgHgDgAw3h7QgBgHgDgDQgEgDgGgBQgGABgEADQgDACgCAIIAdAAIAAAAgAsRhgQgFgEgDgEQgEgHAAgGIgIAAIAAAWIgJAAIAAgxIAJAAIAAAUIAIAAQABgHAEgEQACgEAGgDQAGgDAFAAQAGAAAHAEQAFACAEAHQADAGAAAGQAAAIgDAGQgDAFgGAEQgGADgHAAQgGAAgGgCgAsMiGQgDACgDAEQgBAEAAAEQAAAGABADQADAFADABQACACAFAAQAFAAADgCQADgBACgFQACgDAAgGQAAgEgCgEQgCgEgDgCQgEgCgEAAQgDAAgEACgAMvhfIAAgxIAJAAIAAASIALAAQAKAAAFAEQAFAEAAAHQAAAJgFADQgGAEgJAAgAM4hnIAKAAQALABAAgJQAAgEgCgCQgDgCgGAAIgKAAgAMJhfIAAgpIgRAAIAAgIIAsAAIAAAIIgRAAIAAApgALjhfIAAgjIgaAjIgJAAIAAgxIAKAAIAAAkIAZgkIAJAAIAAAxgAKbhfIAAgpIgRAAIAAgIIAsAAIAAAIIgRAAIAAApgAJJhfIAAgxIAJAAIAAAxgAIyhfIAAgjIgQAVIgGAAIgQgVIAAAjIgJAAIAAgxIAJAAIATAZIATgZIAJAAIAAAxgAG9hfIAAgxIAJAAIAAASIALAAQAKAAAFAEQAFAEAAAHQAAAJgFADQgGAEgJAAgAHGhnIAKAAQALABAAgJQAAgEgCgCQgDgCgGAAIgKAAgABJhfIgGgOIggAAIgFAOIgKAAIAbhHIAIAAIAcBHgABAh2IgNghIgNAhIAaAAgAhAhfIAAgxIAVAAQAKAAAEAEQAEADAAAGQAAAEgBADIgGAEQAGACABACQADADAAAEQAAAEgCADIgGAGQgEABgGAAgAg3hmIANAAQAGAAACgCQACgCAAgDQAAgHgKAAIgNAAgAg3h7IALAAQAFAAACgBQADgDAAgDQAAgGgKgBIgLAAgAhUhfIAAgxIAJAAIAAAxgAhlhfIgNgTIgBgBIgCgBIgIAAIAAAVIgJAAIAAgxIAJAAIAAAUIAIAAIACgBIABgBIANgSIALAAIgRAXIARAagAighfIAAgjIgaAjIgJAAIAAgxIAKAAIAAAkIAZgkIAJAAIAAAxgAkOhfIAAgjIgaAjIgJAAIAAgxIAKAAIAAAkIAZgkIAJAAIAAAxgAmRhfIgOgSIgNASIgLAAIASgZIgSgYIALAAIAOASIANgSIALAAIgSAYIASAZgAnGhfIAAgxIAJAAIAAAxgArBhfIAAgUQgGADgHAAQgGAAgEgCQgEgCgCgEQgDgEAAgGIAAgOIAKAAIAAAOQAAAFADACQACACAGAAQAHAAAEgCIAAgVIAKAAIAAAxgAt7hfIgNgTIgBgBIgCgBIgIAAIAAAVIgJAAIAAgxIAJAAIAAAUIAIAAIACgBIABgBIANgSIALAAIgRAXIARAagAu2hfIAAgjIgaAjIgJAAIAAgxIAKAAIAAAkIAZgkIAJAAIAAAxgAwLhfIAAgxIAWAAQAKAAAEAEQAEADAAAGQAAAEgBADIgGAEQAGACABACQADADAAAEQAAAEgCADIgGAGQgEABgGAAgAwBhmIANAAQAGAAACgCQACgCAAgDQAAgHgKAAIgNAAgAwBh7IALAAQAFAAACgBQADgDAAgDQAAgGgKgBIgLAAgAxwhfIAAggIglAAIAAAgIgKAAIAAhHIAKAAIAAAdIAlAAIAAgdIAKAAIAABHgAJKicIgCgBIgBgDIABgEIACgCIADgBIAEABIACACIABAEIgBADIgCABIgEABgAhTicIgCgBIgBgDIABgEIACgCIADgBIAEABIACACIABAEIgBADIgCABIgEABgAnFicIgCgBIgBgDIABgEIACgCIADgBIAEABIACACIABAEIgBADIgCABIgEABg");
	this.shape.setTransform(14.5,0);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.urText_1, new cjs.Rectangle(-104,-16.8,237.1,33.6), null);


(lib.t1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AGdEjIAAjHIAlAAIAAAOQAIgJAKgEQAJgFAMAAQASAAAOAJQAPAJAHAQQAJAQAAAUQAAAUgJAQQgIAQgOAJQgNAKgTAAQgLAAgKgFQgKgEgIgKIAABRgAHQB/QgHAEgEAIQgEAJAAAKQAAAKAEAJQAEAJAHAEQAHAEAKAAQAKAAAHgEQAGgEAFgJQAEgIAAgLQAAgLgEgIQgFgIgGgEQgHgFgKAAQgKAAgHAFgAJdDbQgOgJgIgQQgJgRABgTQgBgUAJgQQAIgQAOgJQAPgJARAAQANAAAJAFQAKAEAHAJIAAgOIAmAAIAACFIgmAAIAAgPQgGAJgLAFQgLAFgLAAQgRAAgPgKgAJ0B/QgHAFgEAHQgEAJAAAKQAAAKAEAJQADAIAIAFQAIAEAJAAQAKAAAHgEQAHgEAFgJQAEgIAAgLQAAgLgEgIQgFgIgHgEQgHgFgKAAQgJAAgIAFgABdDgIAJghQAIACAJAAQAJAAADgCQAFgEADgEQAEgEADgKIhFiIIArAAIAvBhIAthhIArAAIhICPQgJATgKALQgIALgLAGQgLAGgOAAQgPAAgMgFgAvSDjIAGgiIAGABQAGAAADgDQADgDACgIIABgXIADhBIByAAIAACFIgmAAIAAhmIgoAAIgBAjQgBAYgFARQgFAQgKAHQgMAHgQAAIgQgCgAnXDbQgQgJgJgQQgJgQAAgTQAAgUAJgQQAJgQAQgKQARgJAUAAQAUAAASAJQAQAKAIAQQAJAQAAAUQAAATgJAQQgIAPgQAKQgRAJgVAAQgUAAgRgJgAnCB/QgIAFgFAIQgDAJAAAKQAAAKADAIQAGAIAHAEQAHAEAJAAQAKAAAHgEQAHgDAFgJQAEgIAAgKQAAgKgEgJQgFgJgHgEQgGgEgLAAQgKAAgGAEgAPhDhIAAiFIAlAAIAACFgAOWDhIAAg1IgwAAIAAA1IgmAAIAAiFIAmAAIAAAxIAwAAIAAgxIAmAAIAACFgAL7DhIAAiFIAmAAIAACFgAFXDhIgbgvQgBgEgDgBQgCgBgEAAIgQAAIAAA1IglAAIAAiFIAlAAIAAAvIARAAQAEAAABgBIAEgFIAbgpIArAAIgqA9IArBIgAh0DhIAAiFIA/AAQAZAAANAJQAMAJAAARQABAKgFAIQgEAHgJAEQAWAIAAAWQAAALgFAJQgFAJgMAFQgJAFgQAAgAhQDGIAYAAQAWAAAAgOQAAgHgGgEQgEgDgMAAIgYAAgAhQCSIAUAAQALAAAFgEQAGgEgBgGQABgHgGgEQgFgDgLAAIgUAAgAj7DhIAAg1IgwAAIAAA1IgmAAIAAiFIAmAAIAAAxIAwAAIAAgxIAmAAIAACFgAo5DhIAAhRIg1BRIgiAAIAAiFIAkAAIAABRIA1hRIAiAAIAACFgAsdDhIAAiFIAmAAIAAArIAVAAQAcAAAPALQAOAKAAAYQAAAXgPALQgOALgcAAgAr3DEIASAAQAXAAAAgRQAAgIgGgEQgGgEgLAAIgSAAgAwMDhIAAiFIAmAAIAACFgAxODhIAAhPIgfAsIgaAAIgggtIAABQIgkAAIAAiFIAkAAIAsA7IAsg7IAlAAIAACFgAprBBQgKgGgHgLQgHgKgBgOIAcAAQABAIAGAGQAGAGAJAAQAJAAAGgGQAFgFACgJIAcAAQAAAOgHAKQgHALgLAGQgKAGgPAAQgOAAgLgGgAPpBDQgHgEgBgFQgDgEAAgHQAAgGADgFQABgFAHgDQAFgDAFAAQAHAAAFADQAFACADAGQADAFAAAGQAAAHgDAEQgDAGgFADQgFADgHAAQgFAAgFgDgAwFBDQgFgEgDgFQgDgEAAgHQAAgGADgFQADgFAFgDQAGgDAGAAQAGAAAFADQAFACADAGQADAFAAAGQAAAHgDAEQgDAGgFADQgFADgGAAQgGAAgGgDgAMcBAQgDgCgEgFQgCgEAAgGQAAgFACgFQAEgFADgCQAGgDAEAAQAGAAAEADQAFADACAEQACAEAAAGQAAAGgCAEQgDAFgEACQgEADgGAAQgEAAgGgDgALrBAQgEgCgDgFQgCgDAAgHQAAgGACgEQACgEAFgDQAEgDAGAAQAFAAAFADQADACAEAFQACAFAAAFQAAAGgCAEQgEAFgDACQgFADgFAAQgGAAgEgDgARphkQgPgJgJgPQgJgQAAgUQAAgUAIgQQAKgPAOgJQAPgJATAAQAUAAAOAJQAOAIAJAPQAIAPAAASIgBALIhoAAQACAMAFAJQAHAJAJAEQAJAFANAAQALAAANgEQAJgEAIgHIAOARQgIAJgQAGQgPAGgSAAQgUAAgQgJgASxirQgCgRgLgJQgKgKgQAAQgQAAgKAKQgKAJgDARIBOAAIAAAAgAJWhkQgQgJgHgQQgJgQAAgTQAAgTAJgQQAHgPAQgKQAQgJAUAAQATAAAPAHQAPAIAHALIgQAQQgHgJgKgEQgLgFgLAAQgMAAgKAGQgLAGgFAKQgFALAAAMQAAANAFALQAFAKALAGQAKAFAMAAQALAAALgEQALgFAGgJIAQARQgHALgPAHQgPAHgSAAQgVAAgQgJgAG1hkQgOgJgIgPQgIgQAAgUQAAgUAIgPQAIgQAOgJQAPgJARAAQAOAAAMAGQAKAFAJAMIAAgTIAaAAIAACDIgaAAIAAgUQgIALgLAGQgMAGgOAAQgRAAgPgJgAHFjHQgKAFgFAKQgFAKAAAOQAAAOAFAKQAFAKAKAGQAJAGALAAQAMAAAKgGQAJgGAFgKQAGgKAAgOQAAgOgGgKQgFgKgJgFQgKgGgMAAQgMAAgIAGgAg2hiQgUgHgLgLIAPgUQAJAKAPAGQAPAFAQAAQANAAAHgDQAKgEAGgHQAFgIAAgKQAAgLgGgHQgGgGgKgEQgGgEgTgGQgUgGgKgFQgNgGgHgKQgJgKAAgRQAAgQAJgMQAHgLAQgGQANgGAVAAQAVAAAOAGQARAFAMAMIgMATQgLgJgNgEQgNgFgOAAQgTAAgKAHQgLAGAAAOQgBAIAGAGQAGAGAIAEIAYAIQAVAHALAFQAOAHAIALQAIALABATQAAASgJANQgJANgPAGQgRAGgSAAQgUAAgTgHgAj8hoQgXgMgNgXQgNgXAAgcQAAgcANgYQAOgXAWgMQAVgNAcAAQAcAAAXANQAVAMAOAXQANAYAAAcQAAAcgNAXQgOAXgVAMQgWANgdAAQgcAAgVgNgAjvkAQgRAKgJARQgJASAAAVQAAAVAJASQAKARAQAJQAQAJAUAAQAVAAAQgJQAPgJAKgRQAKgSAAgVQAAgVgKgSQgJgRgQgKQgRgJgUAAQgTAAgRAJgAnZhoQgWgMgNgXQgNgXAAgcQAAgcANgYQAOgXAVgMQAXgNAcAAQAcAAAVANQAWAMAOAXQANAYAAAcQAAASgGASQgHASgLAMIAaAeIgdAAIgNgPQgNAJgPAFQgOAEgQAAQgdAAgWgNgAnLkAQgRAKgIARQgKASAAAVQAAAVAKASQAJARAQAJQAQAJAVAAQAXAAARgMIgngtIARgPIAmAsQAHgJAEgMQAEgNAAgMQAAgVgJgSQgKgRgQgKQgRgJgTAAQgVAAgQAJgAsFhgQgOgGgKgLIAPgPQAJAIAJAEQAJAEANAAQARAAAIgGQAJgFAAgKQAAgSgcAAIgbAAIAAgTIAVAAQAOAAAIgFQAGgEAAgKQABgJgHgFQgHgFgNAAQgXAAgQAQIgNgQQAIgJAOgGQANgGASAAQAZAAANAKQANAKAAARQAAAKgFAIQgFAIgKAEQAMADAHAJQAGAHAAAMQAAAMgHAJQgIAJgMAFQgMAFgTAAQgSAAgOgFgAQjheIghg0IgDgEIgFgBIgKAAIAAA5IgaAAIAAg5IgJAAIgGABIgDAEIghA0IgeAAIAthGIgsg9IAdAAIAhAvIACADIAFABIALAAIAAgzIAaAAIAAAzIALAAIAEgBIAEgDIAggvIAdAAIgrA9IAsBGgAMGheIAAiDIA7AAQAYAAAMAJQANAJAAAQQAAAKgFAIQgGAIgIADQAMADAHAJQAGAJAAAKQAAALgFAIQgGAJgKAEQgLAFgPAAgAMghxIAiAAQAPAAAHgFQAGgFAAgKQAAgSgcAAIgiAAgAMgipIAdAAQAOAAAGgFQAIgFAAgJQAAgSgcAAIgdAAgAFjheIAAg6IhBAAIAAA6IgaAAIAAiDIAaAAIAAAzIBBAAIAAgzIAaAAIAACDgACRheIAAiDIAaAAIAACDgApNheIAAjAIAbAAIAADAgAuHheIAAhgIhEBgIgYAAIAAiDIAZAAIAABfIBEhfIAYAAIAACDgAwkheIAAiTIg7BdIgRAAIg6hdIAACTIgaAAIAAjAIAaAAIBCBqIBEhqIAZAAIAADAgACVkBQgDgCgDgEQgDgFAAgEQAAgDADgFIAGgGQAEgDAEAAQAFAAAEADQAEACACAEQADAFgBADQABAEgDAFQgCAEgEACQgEACgFAAQgEAAgEgCg");
	this.shape.setTransform(11,0);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1, new cjs.Rectangle(-111.7,-29.1,245.5,58.2), null);


(lib.r_part = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#34303D").s().p("AhijHQBSAAA5A7QA6A6AABSQAABTg6A6Qg5A7hSAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.r_part, new cjs.Rectangle(-9.9,-20,19.9,40), null);


(lib.logo_iqos = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AirCpIgsgtIgFgDQgCgCgEAAIjJAAQg/AAgkgeQgigdAAgsIAAiqQAAgHAGgGQAGgGAHABIDnAAQA9AAAkAdQAjAdAAAtIAABPQAAAJgGAFQgGAFgGgBIgHAAQgIABgGgFQgEgFAAgJIAAhPQAAgLgFgKQgFgLgJgHQgLgLgUgGQgQgEgXAAIjJAAIgEABIgBAFIAACLQAAAMAEAKQAFALAJAHQALAKATAGQASAEAXABIDVAAQAGAAAGABIAJAHIA1A1QAFAFAAAIQAAAIgFAEIgFAGQgFAFgHgBQgJABgFgFgAGrB3QgVABgTgIQgUgJgPgNIgJgJQgFgGgBgHQAAgIAFgGIAFgEQAFgFAHgBQAIAAAGAGIAKAJQAJAIALAFQALAEANABICQAAQAVAAAPgEQAPgEAJgHQAFgFACgEQADgIAAgKQAAgKgDgGQgCgFgFgFQgJgHgPgCQgPgEgVgBIh6AAQg3ABgfgXQgagWAAgiIAAgKQAAgjAagVQAfgYA3ABICFAAQAUAAASAHQASAHAPANIAMALQAGAFABAHQAAAIgEAGIgFAEQgFAHgIgBQgHABgGgFIgMgLQgIgIgMgEQgMgEgLAAIiFAAQgTAAgQAEQgPADgKAHQgEAEgDAGQgDAGAAAKQAAALADAGQADAHAEADQAJAIAQADQAQAEATAAIB6AAQA5AAAdAWQAaAWAAAhIAAALQAAAigaAVQgdAXg5AAgAAaB3Qg+AAgkgeQghgdAAgsIAAhVQAAgtAhgdQAkgdA+AAIB1AAQA9AAAkAdQAiAdAAAtIAABVQAAAsgiAdQgkAeg9AAgAgOh9QgSAGgNALQgIAHgEALQgGAKAAALIAABVQAAAMAGAKQAEALAIAHQANAKASAGQARAEAXABIB1AAQAWgBASgEQASgGAMgKQAJgHAFgLQAFgKAAgMIAAhVQAAgMgFgJQgFgLgJgHQgMgLgSgGQgSgEgWAAIh1AAQgXAAgRAEgAqXB3QgIABgGgGQgFgFAAgIIAAj+QAAgJAFgFQAGgGAIABIAFAAQAIgBAFAGQAGAGAAAIIAAD+QAAAIgGAFQgFAGgIgBg");
	this.shape.setTransform(46.5,1.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AikFoQg9AAgygfQgwgdgcgxQgcgwgBg4QgCg7Afg1IClkeQAeg0A0gcQAxgcA3AAQA5AAAwAcQA0AcAeA0IClEeQAfA1gBA7QgBA4gdAwQgcAxgvAdQgzAfg9AAgAhujUQgyAWgnAnQgmAngWAzQgXA0ABA5QgBA6AXA0QAWAyAmApQAnAnAyAUQA2AXA4AAQA6AAA1gXQAxgUApgnQAmgpAVgyQAXg0AAg6QAAg5gXg0QgVgzgmgnQgpgngxgWQg1gVg6gBQg4ABg2AVg");
	this.shape_1.setTransform(-79.8,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.logo_iqos, new cjs.Rectangle(-118,-36,232.9,72), null);


(lib.l_part = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#34303D").s().p("AgoCNQg7g6AAhTQAAhSA7g6QA5g7BTAAIAAGPQhTAAg5g7g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.l_part, new cjs.Rectangle(-9.9,-20,19.9,40), null);


(lib.btn_txt = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AlGBCIAAgYIhQAAIAAAYIgOAAIAAglIAMAAQADgDABgFIADgPIADhFIBIAAIAABcIAOAAIAAAlgAmBgOQAAANgCAOQgCALgDAFIAzAAIAAhOIgrAAgAFuAoQgHgEgGgKQgFgKAAgKQAAgJAFgKQAEgJAJgEQAIgFALAAQAJAAAJAEQAIAFAFAJQAFAIAAAJIgBAGIg5AAQABAIADAEQADAEAFADQAGADAHAAQAGAAAGgCQAHgDADgEIAIAJQgFAFgIAEQgJADgJAAQgMAAgJgEgAGWAAQgBgIgGgFQgGgGgIAAQgIAAgHAGQgGAFgBAIIArAAIAAAAgAg8AsIACgNIAEAAQAEAAACgBQACgDAAgFIADgzIA6AAIAABHIgPAAIAAg7IgdAAIgBAYQAAAOgDAIQgCAIgFAEQgEADgJAAgAiEAoQgIgFgFgJQgFgIAAgMQAAgKAFgJQAFgJAIgEQAHgFAKAAQAIAAAGADQAHAEAEAFIAAgKIAOAAIAABHIgOAAIAAgKQgEAGgHADQgGADgIAAQgKAAgHgEgAh8gPQgGAFgCAEQgDAGAAAGQAAAHADAHQADAFAFAEQAFACAHAAQAGAAAFgCQAGgEADgFQACgHAAgHQAAgGgCgGQgDgFgGgEQgFgDgGAAQgHAAgFADgAkgAoQgIgEgGgKQgFgJAAgLQAAgKAFgJQAFgJAIgEQAIgFALAAQAKAAAIAEQAJAGAEAIQAFAJAAAIIgBAGIg5AAQAAAHAEAFQADAEAFADQAGADAHAAQAGAAAGgCQAGgCAFgFIAHAJQgEAGgJADQgIADgKAAQgMAAgIgEgAj4AAQgCgIgGgFQgGgGgIAAQgIAAgHAGQgGAFgBAIIAsAAIAAAAgADoAqIAAhHIAPAAIAAA8IAdAAIAAg8IAOAAIAAA8IAeAAIAAg8IAOAAIAABHgADEAqIAAhHIAOAAIAABHgACjAqIAAgfIgkAAIAAAfIgPAAIAAhHIAPAAIAAAcIAkAAIAAgcIAOAAIAABHgAAmAqIAAhHIAPAAIAAAaIAQAAQAPAAAHAFQAIAGAAAMQAAALgIAGQgHAGgPgBgAA1AfIAPAAQAQAAAAgMQAAgGgEgDQgDgDgJAAIgPAAgAjIAqIAAg7IgaAAIAAgMIBBAAIAAAMIgZAAIAAA7gADGgvIgDgDQgBgBAAAAQAAgBAAAAQgBgBAAgBQAAAAAAgBIACgEIADgEQABAAAAgBQABAAAAAAQABAAAAAAQABgBABAAQABAAAAABQABAAAAAAQABAAAAAAQABABAAAAIAEAEIABAEQAAABAAAAQAAABAAABQAAAAgBABQAAAAAAABIgEADQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAgBAAQgBAAgBAAQAAAAgBAAQAAAAgBAAQAAgBgBAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.btn_txt, new cjs.Rectangle(-42,-6.5,84.2,13.1), null);


(lib.btn_round = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#34303D").s().p("AiMCNQg7g6AAhTQAAhSA7g6QA6g7BSAAQBTAAA6A7QA7A6AABSQAABTg7A6Qg6A7hTAAQhSAAg6g7g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.btn_round, new cjs.Rectangle(-20,-20,40,40), null);


(lib.btn_bg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#34303D").s().p("AnVDIQhSAAg6g6Qg7g5AAhTIAAgCQAAhSA7g6QA6g7BSAAIOrAAQBTAAA6A7QA6A6AABSIAAACQAABSg6A6Qg6A6hTAAg");
	this.shape.setTransform(-0.3,0);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.btn_bg, new cjs.Rectangle(-67.2,-20,133.8,40), null);


(lib.bgImg4_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.bgImg4();
	this.instance.parent = this;
	this.instance.setTransform(-150,-184);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bgImg4_1, new cjs.Rectangle(-150,-184,300,367), null);


(lib.bgImg3_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.bgImg3();
	this.instance.parent = this;
	this.instance.setTransform(-150,-184);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bgImg3_1, new cjs.Rectangle(-150,-184,300,367), null);


(lib.bgImg2_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.bgImg2();
	this.instance.parent = this;
	this.instance.setTransform(-150,-184);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bgImg2_1, new cjs.Rectangle(-150,-184,300,367), null);


(lib.bgImg1_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.bgImg1();
	this.instance.parent = this;
	this.instance.setTransform(-150,-184);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bgImg1_1, new cjs.Rectangle(-150,-184,300,367), null);


(lib.bg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00D1D2").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.bg, new cjs.Rectangle(-150,-300,300,600), null);


(lib.btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_4
	this.instance = new lib.btn_txt();
	this.instance.parent = this;
	this.instance.setTransform(-0.6,8.9);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(12).to({_off:false},0).to({y:0.7,alpha:1},8).wait(1));

	// r_part
	this.instance_1 = new lib.r_part();
	this.instance_1.parent = this;
	this.instance_1.setTransform(10.1,0);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(9).to({_off:false},0).to({x:57.1},8,cjs.Ease.get(1)).to({_off:true},1).wait(3));

	// l_part
	this.instance_2 = new lib.l_part();
	this.instance_2.parent = this;
	this.instance_2.setTransform(-10,0);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(9).to({_off:false},0).to({x:-57.3},8,cjs.Ease.get(1)).to({_off:true},1).wait(3));

	// Слой_5
	this.instance_3 = new lib.btn_bg();
	this.instance_3.parent = this;
	this.instance_3.setTransform(0,0,0.01,1);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(9).to({_off:false},0).to({scaleX:1},8,cjs.Ease.get(1)).wait(4));

	// Слой_1
	this.instance_4 = new lib.btn_round();
	this.instance_4.parent = this;
	this.instance_4.setTransform(0,0,0.012,0.012);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({scaleX:1.2,scaleY:1.2},5,cjs.Ease.get(1)).to({scaleX:1,scaleY:1},4,cjs.Ease.quadInOut).to({_off:true},9).wait(3));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-0.2,-0.2,0.5,0.5);


(lib.banner = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{loop:50});

	// timeline functions:
	this.frame_210 = function() {
		this.gotoAndPlay('loop');
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(210).call(this.frame_210).wait(1));

	// t1
	this.instance = new lib.t1();
	this.instance.parent = this;
	this.instance.setTransform(-29.6,123.3);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(10).to({_off:false},0).to({x:-9.6,alpha:1},10,cjs.Ease.cubicOut).wait(191));

	// urText_1
	this.instance_1 = new lib.urText_1();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-18.8,264.4);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({alpha:1},10).wait(201));

	// btn
	this.instance_2 = new lib.btn("synched",0,false);
	this.instance_2.parent = this;
	this.instance_2.setTransform(-53.8,188.7);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(15).to({_off:false},0).wait(196));

	// logo
	this.instance_3 = new lib.logo_iqos();
	this.instance_3.parent = this;
	this.instance_3.setTransform(0.6,-258.3,0.505,0.505,0,0,0,-0.1,-0.4);
	this.instance_3.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({alpha:1},10).wait(201));

	// bgImg4
	this.instance_4 = new lib.bgImg4_1();
	this.instance_4.parent = this;
	this.instance_4.setTransform(0,-116.5);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(130).to({_off:false},0).to({alpha:1},10).wait(30).to({alpha:0},10).wait(31));

	// bgImg3
	this.instance_5 = new lib.bgImg3_1();
	this.instance_5.parent = this;
	this.instance_5.setTransform(0,-116.5);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(90).to({_off:false},0).to({alpha:1},10).to({_off:true},40).wait(71));

	// bgImg2
	this.instance_6 = new lib.bgImg2_1();
	this.instance_6.parent = this;
	this.instance_6.setTransform(0,-116.5);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(50).to({_off:false},0).to({alpha:1},10).to({_off:true},40).wait(111));

	// bgImg1
	this.instance_7 = new lib.bgImg1_1();
	this.instance_7.parent = this;
	this.instance_7.setTransform(0,-116.5);
	this.instance_7.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).to({alpha:1},10).wait(201));

	// bg
	this.instance_8 = new lib.bg();
	this.instance_8.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(211));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,-300.5,300,600.5);


// stage content:
(lib._300x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// cover
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#666666").ss(2,2,0,3).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// banner
	this.instance = new lib.banner();
	this.instance.parent = this;
	this.instance.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(149,299,302,602);
// library properties:
lib.properties = {
	id: '0A6E3F5DF6B342F4AF907DBE848CDF8D',
	width: 300,
	height: 600,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/bgImg1.jpg", id:"bgImg1"},
		{src:"images/bgImg2.jpg", id:"bgImg2"},
		{src:"images/bgImg3.jpg", id:"bgImg3"},
		{src:"images/bgImg4.jpg", id:"bgImg4"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['0A6E3F5DF6B342F4AF907DBE848CDF8D'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;