(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.bgImg1 = function() {
	this.initialize(img.bgImg1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.bgImg2 = function() {
	this.initialize(img.bgImg2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.dev = function() {
	this.initialize(img.dev);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,414,330);


(lib.holder = function() {
	this.initialize(img.holder);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,362,428);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.urText = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AA1DQIAAhGIAIAAIAAAKQAIgMAMAAQALAAAHAIQAJAIgBANQABAMgJAIQgHAIgLAAQgMAAgIgMIAAAbgABDCWQgHAGAAAJQAAAJAHAGQAGAFAHAAQAIAAAGgFQAFgGAAgKQAAgJgFgGQgGgFgIAAQgIAAgFAGgAj2DQIAAhGIAIAAIAAAKQAJgMALAAQALAAAHAIQAJAIAAANQAAAMgJAIQgHAIgLAAQgLAAgJgMIAAAbgAjpCWQgFAGAAAJQAAAJAFAGQAHAFAHAAQAIAAAGgFQAFgGAAgKQAAgJgGgGQgFgFgIAAQgHAAgHAGgAphDOIADgHQADACAFAAQAEAAACgCQACgBADgHIgZg1IAJAAIAUAsIARgsIAJAAIgWA3QgFAJgDADQgEADgGAAQgIAAgEgCgADmDNIAAgOIgvAAIAAg1IAIAAIAAAuIAfAAIAAguIAIAAIAAAuIAIAAIgCAVgAIrC8QgGgEAAgIQAAgJAGgEQAIgFAJAAQAIAAAJACIAAgBQAAgHgFgEQgEgEgHAAQgJAAgIAEIgCgHQAKgEAJAAQANAAAFAGQAFAFABALIAAAgIgIAAIAAgIQgIAKgMAAQgIAAgGgFgAIyCnQgFADAAAFQAAAFAEADQAEADAGAAQAHAAAFgEQAFgEABgGIAAgFQgJgDgHAAQgHAAgEADgAHyC4QgIgJAAgKQAAgLAIgJQAIgJAMAAQAMAAAJAKIgFAFQgHgHgKAAQgIAAgGAGQgFAGAAAJQAAAIAFAGQAHAGAIAAQAIAAAIgIIAFAFQgJALgMAAQgMAAgIgJgAGVC8QgGgEAAgIQAAgJAGgEQAHgFAKAAQAHAAAJACIAAgBQABgHgEgEQgFgEgIAAQgHAAgJAEIgCgHQAKgEAJAAQANAAAEAGQAHAFAAALIAAAgIgJAAIAAgIQgHAKgMAAQgIAAgGgFgAGbCnQgEADAAAFQAAAFAEADQAEADAFAAQAIAAAFgEQAGgEgBgGIAAgFQgIgDgHAAQgIAAgEADgAB9C8QgGgEAAgIQAAgJAGgEQAHgFAKAAQAHAAAKACIAAgBQAAgHgFgEQgDgEgJAAQgHAAgJAEIgCgHQAKgEAJAAQANAAAEAGQAHAFAAALIAAAgIgIAAIAAgIQgIAKgMAAQgIAAgGgFgACECnQgFADAAAFQAAAFAEADQAEADAGAAQAHAAAFgEQAGgEAAgGIAAgFQgJgDgHAAQgIAAgDADgAg0C4QgHgJAAgKQAAgLAHgJQAJgJAMAAQAMAAAJAKIgFAFQgIgHgJAAQgIAAgGAGQgFAGAAAJQAAAIAFAGQAHAGAIAAQAIAAAIgIIAFAFQgJALgMAAQgMAAgJgJgAhvC4QgJgJABgKQgBgMAJgIQAHgJAMAAQANAAAIAKIgEAFQgIgIgJAAQgHAAgFAGQgGAEgBAIIAZAAIAAAHIgZAAQABAIAGAEQAFAGAHAAQAKAAAHgJIAFAFQgDAEgGAEQgGADgHAAQgLAAgIgJgAisC5QgHgIgBgMQAAgMAIgIQAHgJALAAQAMAAAHAJQAGAHABANIAAADIgrAAQABAIAFAFQAFAFAIAAQAJAAAIgIIAFAFQgKAKgNAAQgLAAgIgIgAiJChQAAgIgFgFQgEgFgIAAQgGAAgFAFQgFAGgBAHIAiAAIAAAAgAnXC4QgJgJABgKQAAgMAIgIQAIgJAMAAQALAAAJAJQAIAJAAALQAAALgJAIQgHAJgNAAQgLAAgIgJgAnSCWQgFAGAAAJQAAAIAFAGQAHAGAIAAQAJAAAFgGQAGgFgBgJQABgJgGgGQgGgGgJAAQgIAAgGAGgAq2C8QgGgEAAgIQAAgJAGgEQAIgFAJAAQAHAAAKACIAAgBQAAgHgFgEQgDgEgJAAQgIAAgIAEIgCgHQAKgEAJAAQANAAAEAGQAGAFABALIAAAgIgIAAIAAgIQgIAKgMAAQgIAAgGgFgAqvCnQgFADAAAFQAAAFAEADQAEADAGAAQAHAAAFgEQAGgEAAgGIAAgFQgJgDgHAAQgIAAgDADgAsDC1IAFgGQALALAPAAQAGAAAFgEQAGgEAAgGQgBgHgFgEQgFgDgJAAIgIAAIAAgHIAIAAQAIAAAFgDQAFgEAAgGQAAgGgFgEQgEgDgHAAQgNAAgJAIIgFgGQAGgFAGgCQAGgDAJAAQAKAAAHAGQAHAFAAAJQAAAMgNAFQAGACAFAFQAEAFAAAGQAAAJgHAGQgHAGgLAAQgSAAgNgMgAL6C/IAAgLIAKAAIAAALgALeC/IAAg1IAIAAIAAA1gAK4C/IAAguIgTAAIAAgHIAvAAIAAAHIgUAAIAAAugAKNC/IAAgqIghAqIgHAAIAAg1IAIAAIAAAqIAggqIAIAAIAAA1gAF+C/IAAgXIgfAAIAAAXIgIAAIAAg1IAIAAIAAAXIAfAAIAAgXIAIAAIAAA1gAEcC/IAAg1IAIAAIAAA1gAD+C/IAAg1IAIAAIAAA1gAAQC/IAAguIgSAAIAAgHIAtAAIAAAHIgTAAIAAAugAkyC/IAAgqIggAqIgIAAIAAg1IAIAAIAAAqIAggqIAIAAIAAA1gAmWC/IAAg1IAaAAQAIAAAFADQAEAEABAGQAAAJgJADQAMAEgBAKQAAAHgEADQgGAEgJAAgAmOC5IASAAQAGAAADgDQAEgCgBgFQABgDgEgDQgDgCgHAAIgRAAgAmOChIARAAQAEAAAEgDQACgCAAgEQAAgEgCgBQgDgDgFAAIgRAAgAnyC/IAAgpIgUAcIgUgcIAAApIgIAAIAAg1IAHAAIAVAcIAUgcIAIAAIAAA1gAJzB+QgEgEgBgFIAGgBQACAHAHAAQAGAAADgHIAGABQgCAGgEADQgEAEgFAAQgGAAgEgEgAElCBIAAgJIAJAAIAAAJgAESCBIAAgJIAKAAIAAAJgALdB+IAAgJIAKAAIAAAJgAD9B+IAAgJIAJAAIAAAJgAmKBhIADgGQAEACAEAAQAEAAACgCQADgCACgGIgZg2IAJAAIAUAtIARgtIAJAAIgWA4QgFAIgDAEQgFADgFAAQgHAAgFgDgAKwBkIAAhHIAIAAIAAALQAJgMAMAAQAKAAAIAIQAHAHABANQgBANgHAIQgIAHgKAAQgMAAgJgLIAAAbgAK9ApQgFAGAAAJQAAAJAFAGQAHAGAHAAQAIAAAGgGQAFgFAAgKQAAgKgGgFQgEgGgJAAQgHAAgHAGgAhRBkIAAhHIAIAAIAAALQAIgMAMAAQALAAAHAIQAJAHgBANQABANgJAIQgHAHgLAAQgMAAgIgLIAAAbgAhDApQgHAGAAAJQAAAJAHAGQAFAGAIAAQAIAAAGgGQAFgFAAgKQAAgKgFgFQgGgGgIAAQgIAAgFAGgANmBQQgGgFAAgIQAAgIAGgFQAHgEAKAAQAJAAAIACIAAgCQAAgHgFgEQgEgDgHAAQgJAAgIAEIgCgHQAKgFAJAAQANAAAFAGQAFAGABAKIAAAhIgIAAIAAgIQgIAJgMAAQgIAAgGgEgANtA7QgFADAAAFQAAAFAEADQAEADAGAAQAHAAAFgEQAFgEABgHIAAgFQgHgCgJAAQgHAAgEADgAL7BMQgJgIAAgMQABgLAHgJQAHgIALAAQAMAAAHAIQAGAIABANIAAACIgrAAQABAJAFAFQAGAEAHAAQAJAAAIgHIAFAEQgKAKgNAAQgLAAgHgIgAMeA1QgBgJgFgEQgEgFgIAAQgFAAgGAFQgFAFgBAIIAjAAIAAAAgAJ2BQQgGgFAAgIQAAgIAGgFQAHgEAKAAQAJAAAHACIAAgCQAAgHgDgEQgFgDgIAAQgIAAgIAEIgCgHQAKgFAJAAQANAAAEAGQAHAGAAAKIAAAhIgJAAIAAgIQgHAJgMAAQgIAAgGgEgAJ9A7QgFADAAAFQAAAFAEADQAEADAFAAQAIAAAFgEQAGgEgBgHIAAgFQgGgCgJAAQgIAAgDADgAHPBMQgJgJABgLQgBgLAJgJQAHgIANAAQAMAAAJAKIgFAFQgHgIgKAAQgIAAgGAGQgFAHAAAIQAAAJAFAGQAGAGAJAAQAIAAAIgIIAFAFQgJAKgMAAQgNAAgHgIgAF1BMIAEgGQAHAHALAAQAGAAADgCQAEgCAAgFQAAgFgEgCQgDgCgHAAIgHAAIAAgHIAIAAQAFAAADgCQAEgDAAgEQAAgDgEgDQgCgCgGAAQgKAAgGAFIgEgFQAIgHAMAAQALAAAEAEQAFAEAAAGQAAAKgJADQALAEAAAJQgBAHgFAFQgHAEgJAAQgMAAgKgIgAiSBMQgJgJAAgLQABgLAIgJQAIgIAMAAQAMAAAIAIQAIAJAAALQAAAMgJAIQgHAIgNAAQgMAAgHgIgAiMApQgGAHAAAIQAAAJAGAGQAFAGAJAAQAJAAAFgGQAGgFgBgKQABgIgGgHQgGgGgJAAQgIAAgFAGgAn9BQQgGgFAAgIQAAgIAGgFQAHgEAKAAQAJAAAHACIAAgCQAAgHgDgEQgEgDgIAAQgJAAgIAEIgCgHQAKgFAKAAQALAAAGAGQAFAGAAAKIAAAhIgIAAIAAgIQgHAJgMAAQgIAAgGgEgAn3A7QgEADAAAFQAAAFAEADQAEADAFAAQAIAAAGgEQAEgEAAgHIAAgFQgGgCgJAAQgHAAgFADgAp1BQQgGgFAAgIQAAgIAGgFQAHgEAKAAQAJAAAHACIAAgCQAAgHgDgEQgFgDgIAAQgIAAgIAEIgCgHQAKgFAJAAQANAAAEAGQAHAGAAAKIAAAhIgJAAIAAgIQgHAJgMAAQgIAAgGgEgApvA7QgEADAAAFQAAAFAEADQAEADAFAAQAIAAAFgEQAGgEgBgHIAAgFQgGgCgJAAQgIAAgEADgAquBMIAEgGQAHAHALAAQAGAAADgCQAEgCAAgFQAAgFgEgCQgDgCgHAAIgGAAIAAgHIAHAAQAFAAADgCQAEgDAAgEQAAgDgEgDQgCgCgGAAQgJAAgHAFIgEgFQAIgHAMAAQAKAAAFAEQAFAEAAAGQAAAKgIADQAJAEABAJQAAAHgHAFQgFAEgKAAQgNAAgJgIgAr/BMQgIgIAAgMQABgLAHgJQAHgIALAAQAMAAAHAIQAGAIABANIAAACIgrAAQABAJAFAFQAGAEAHAAQAJAAAIgHIAFAEQgKAKgNAAQgLAAgIgIgArbA1QgBgJgFgEQgEgFgIAAQgFAAgGAFQgFAFgBAIIAjAAIAAAAgAvQBMQgIgIAAgMQAAgLAIgJQAHgIALAAQAMAAAHAIQAGAIAAANIAAACIgqAAQABAJAEAFQAGAEAIAAQAJAAAIgHIAEAEQgJAKgNAAQgMAAgHgIgAutA1QgBgJgEgEQgFgFgHAAQgGAAgGAFQgEAFgBAIIAiAAIAAAAgAQrBTIAAgLIAKAAIAAALgAQOBTIAAgrIghArIgHAAIAAg2IAIAAIAAArIAggrIAIAAIAAA2gAPQBTIAAgpIgVAbIgTgbIAAApIgIAAIAAg2IAHAAIAUAdIAVgdIAIAAIAAA2gAM/BTIAAgvIgTAAIAAgHIAvAAIAAAHIgUAAIAAAvgAJMBTIAAg2IAlAAIAAAHIgdAAIAAAvgAIuBTIAAgrIggArIgIAAIAAg2IAIAAIAAArIAggrIAIAAIAAA2gAE/BTIAAg2IAIAAIAAA2gAEpBTIAAgXIgfAAIAAAXIgIAAIAAg2IAIAAIAAAXIAfAAIAAgXIAIAAIAAA2gADtBTIAAgXIgfAAIAAAXIgIAAIAAg2IAIAAIAAAXIAfAAIAAgXIAIAAIAAA2gACtBTIAAgTIgPAAIgPATIgKAAIARgVQgHgBgDgEQgFgEAAgHQABgIAFgEQAFgFAKAAIAZAAIAAA2gACTAnQgEADAAAEQABAGADACQAEADAGAAIAQAAIAAgVIgRAAQgFAAgEADgAB1BTIAAgXIgfAAIAAAXIgIAAIAAg2IAIAAIAAAXIAfAAIAAgXIAIAAIAAA2gAASBTIAAg2IAaAAQAIAAAFAEQAEAEAAAGQABAJgKADQAMADAAAKQAAAIgEADQgHAEgIAAgAAaBMIASAAQAFAAAEgCQAEgCAAgFQAAgEgEgCQgEgCgGAAIgRAAgAAaA0IARAAQAFAAADgCQACgCAAgEQAAgDgCgDQgCgCgGAAIgRAAgAgKBTIAAg2IAIAAIAAA2gAitBTIAAgvIgeAAIAAAvIgIAAIAAg2IAvAAIAAA2gAktBTIAAg2IAaAAQAIAAAFAEQAFAEAAAGQgBAJgIADQALADABAKQAAAIgGADQgGAEgIAAgAklBMIASAAQAGAAADgCQADgCAAgFQAAgEgDgCQgEgCgGAAIgRAAgAklA0IAQAAQAGAAACgCQAEgCAAgEQAAgDgEgDQgCgCgFAAIgRAAgAmeBTIgQgWIgRAWIgJAAIAWgbIgVgbIAJAAIAQAVIAQgVIAJAAIgUAaIAVAcgAoVBTIAAgvIgeAAIAAAvIgIAAIAAg2IAvAAIAAA2gAtcBTIAAg2IAHAAIAAAvIAbAAIAAgvIAIAAIAAAvIAZAAIAAgvIAIAAIAAA2gAtyBTIAAgXIgeAAIAAAXIgIAAIAAg2IAIAAIAAAXIAeAAIAAgXIAIAAIAAA2gAvwBTIAAg7IgaAnIgBAAIgagnIAAA7IgIAAIAAhJIAIAAIAbAoIAagoIAIAAIAABJgAE+ARIAAgIIAKAAIAAAIgAgLARIAAgIIAJAAIAAAIgArqgIIAAhGIAIAAIAAALQAJgMALAAQALAAAHAHQAIAIAAANQAAANgIAHQgHAIgLAAQgMAAgIgMIAAAbgArchCQgHAGAAAJQAAAJAHAGQAFAGAIAAQAHAAAHgGQAFgFAAgKQAAgKgFgFQgGgGgIAAQgIAAgFAGgAyXgIIAAhGIAHAAIAAALQAJgMAMAAQALAAAHAHQAIAIAAANQAAANgIAHQgHAIgLAAQgNAAgIgMIAAAbgAyKhCQgGAGAAAJQAAAJAGAGQAGAGAIAAQAHAAAGgGQAFgFABgKQAAgKgGgFQgFgGgIAAQgIAAgGAGgAE8gLIAAgNIgrAAIgCANIgGAAIAAgUIAGAAQAHgOAAgYIAAgJIAmAAIAAAvIAIAAIAAAEIABgEIAEABIADgBIAEgDIADgHIABglIAnAAIAAA2IgJAAIAAgvIgWAAIAAAWIgDAOQgBAFgDACQgCADgDABIgGABIgGgBIgBANgAEehAQAAAUgHANIAeAAIAAgoIgXAAgAzugLIAAgNIgsAAIgBANIgHAAIAAgUIAHAAQAGgOABgYIAAgJIAmAAIAAAvIAIAAIgBAUgA0MhAQAAAUgHANIAdAAIAAgoIgWAAgAUIgfQgHgIAAgOIABgRIACgHIADgHIAGgFQAEgCAEgBIAegHIABAHIgdAHQgGACgFAFQgEAFAAAHQAGgLAQAAQALAAAIAHQAHAJAAAKQAAAMgIAIQgHAIgMAAQgNAAgIgIgAUOhBQgEAGAAAJQgBAIAGAGQAFAGAJAAQAIAAAFgGQAFgFABgJQgBgJgFgGQgFgGgIAAQgIAAgHAGgAStgfQgHgJgBgLQABgLAHgJQAJgIAMAAQAMAAAJAJIgFAGQgIgIgJAAQgIAAgGAGQgFAHAAAIQAAAIAFAHQAGAGAJAAQAIAAAIgIIAFAFQgJAKgMAAQgMAAgJgIgARogfQgIgJAAgLQgBgLAJgJQAIgIAMAAQALAAAJAIQAIAJAAALQAAALgIAJQgIAIgMAAQgMAAgIgIgARthCQgFAHAAAIQAAAIAFAHQAHAGAIAAQAJAAAFgGQAFgGABgJQgBgIgFgHQgGgGgIAAQgJAAgGAGgALhgfQgHgJgBgLQAAgLAJgJQAHgIANAAQALAAAJAIQAIAJAAALQAAALgIAJQgIAIgNAAQgLAAgJgIgALohCQgGAHAAAIQAAAIAGAHQAFAGAJAAQAJAAAFgGQAGgGAAgJQAAgIgGgHQgGgGgJAAQgIAAgFAGgAIjgfQgHgJgBgLQAAgLAJgJQAHgIANAAQALAAAJAIQAIAJAAALQAAALgIAJQgIAIgNAAQgLAAgJgIgAIqhCQgGAHAAAIQAAAIAGAHQAFAGAJAAQAJAAAFgGQAGgGAAgJQAAgIgGgHQgGgGgJAAQgIAAgFAGgAlzgfQgJgJAAgLQABgMAHgIQAIgIALAAQAMAAAGAIQAHAIAAAMIAAADIgrAAQAAAIAGAFQAGAFAHAAQAJAAAIgIIAFAFQgKAKgNAAQgLAAgHgIgAlQg2QgBgIgFgFQgEgFgHAAQgIAAgEAFQgGAFAAAIIAjAAIAAAAgApjgfIAEgGQAJAHAJAAQAFAAAFgDQADgCAAgFQAAgDgDgDQgDgCgHAAIgHAAIAAgHIAHAAQAFAAAEgDQADgCAAgEQAAgEgDgCQgDgCgGAAQgJAAgHAFIgEgFQAJgHAMAAQAIAAAGAEQAFADAAAHQAAAJgJAEQALADgBAKQABAHgHAEQgGAFgJAAQgMAAgKgIgAxNgfQgIgJAAgLQAAgLAJgJQAHgIAMAAQAMAAAIAIQAJAJgBALQAAALgIAJQgIAIgMAAQgLAAgJgIgAxHhCQgFAHAAAIQAAAIAFAHQAGAGAIAAQAJAAAGgGQAFgGAAgJQAAgIgFgHQgHgGgIAAQgJAAgFAGgAzZgfQgIgJAAgLQAAgLAIgJQAIgIANAAQAKAAAKAIQAHAJABALQAAALgJAJQgHAIgNAAQgMAAgIgIgAzThCQgGAHAAAIQAAAIAGAHQAGAGAJAAQAIAAAFgGQAGgGAAgJQAAgIgGgHQgFgGgJAAQgJAAgFAGgA1RgfIAEgGQAJAHAJAAQAGAAAEgDQADgCABgFQgBgDgDgDQgDgCgHAAIgHAAIAAgHIAHAAQAGAAADgDQADgCABgEQgBgEgDgCQgCgCgHAAQgIAAgHAFIgFgFQAJgHAMAAQAJAAAFAEQAFADABAHQAAAJgJAEQAKADAAAKQAAAHgGAEQgHAFgJAAQgLAAgLgIgAMagYIABgHIAEABIADgBIAEgDIACgHIACglIAnAAIAAA2IgIAAIAAgvIgXAAIgBAWIgCAOQgCAFgCACQgCADgDABIgGABgAgPgYIABgHIAEABIADgBIAEgDIACgHIABglIAnAAIAAA2IgIAAIAAgvIgXAAIgBAWIgCAOQgCAFgCACQgBADgDABIgGABgAnugcQgGgEAAgIQAAgJAGgEQAHgFAKAAQAHAAAJADIAAgCQAAgHgDgEQgGgEgHAAQgGAAgKAEIgCgGQAKgFAJAAQANAAAEAGQAHAGAAAKIAAAhIgJAAIAAgIQgHAJgMAAQgIAAgGgFgAnogwQgEADAAAFQAAAFAEADQAEACAFAAQAJAAAEgEQAGgDgBgHIAAgFQgGgCgJAAQgIAAgEADgAVIgYIAAgLIAKAAIAAALgATmgYIAAg2IAIAAIAAA2gAQugYIgQgWIgRAWIgJAAIAWgcIgVgaIAJAAIAQAVIAQgVIAJAAIgUAaIAVAcgAPsgYIAAg2IAIAAIAAA2gAPWgYIAAgYIgfAAIAAAYIgIAAIAAg2IAIAAIAAAXIAfAAIAAgXIAIAAIAAA2gAOKgYIAAgvIgTAAIAAgHIAuAAIAAAHIgTAAIAAAvgANggYIAAg2IAIAAIAAA2gALIgYIAAgYIgfAAIAAAYIgIAAIAAg2IAIAAIAAAXIAfAAIAAgXIAIAAIAAA2gAJlgYIAAg2IAaAAQAHAAAGAEQAFADgBAGQABAJgKAEQANADAAAKQgBAHgFAEQgGAEgIAAgAJtgfIASAAQAGAAADgDQAEgCAAgEQAAgEgEgCQgEgDgGAAIgRAAgAJtg3IAQAAQAFAAADgCQADgCAAgFQAAgDgDgCQgCgCgFAAIgRAAgAIJgYIAAgvIgeAAIAAAvIgIAAIAAg2IAuAAIAAA2gAGsgYIAAgUIgPAAIgPAUIgKAAIAQgVQgGgCgEgEQgDgEAAgGQAAgIAEgEQAGgFAKAAIAZAAIAAA2gAGShEQgDACAAAFQAAAFADADQAEACAFAAIARAAIAAgUIgRAAQgGAAgDADgADVgYIAAgrIghArIgHAAIAAg2IAIAAIAAArIAggrIAIAAIAAA2gACXgYIgSgZIgMAMIAAANIgIAAIAAg2IAIAAIAAAfIAegfIAJAAIgWAXIAXAfgAA1gYIAAg2IAIAAIAAAUIAPAAQAKAAAEAEQAHAEgBAIQAAAIgFAFQgFAFgJAAgAA9gfIAPAAQAFAAAEgDQADgDAAgFQAAgEgDgDQgEgCgFAAIgPAAgAgjgYIAAg2IAIAAIAAA2gAhJgYIAAgvIgTAAIAAgHIAuAAIAAAHIgTAAIAAAvgAiSgYIAAgrIghArIgHAAIAAg2IAIAAIAAArIAggrIAIAAIAAA2gAjYgYIAAgrIggArIgIAAIAAg2IAIAAIAAArIAggrIAIAAIAAA2gAkVgYIAAgYIgfAAIAAAYIgIAAIAAg2IAIAAIAAAXIAfAAIAAgXIAIAAIAAA2gAmSgYIAAgWIgIADIgKABQgJAAgEgEQgFgDABgJIAAgUIAHAAIAAATQABAFADADQACACAFAAQALAAAGgFIAAgYIAIAAIAAA2gAoFgYIAAgYIgfAAIAAAYIgIAAIAAg2IAIAAIAAAXIAfAAIAAgXIAIAAIAAA2gAp8gYIAAgrIggArIgIAAIAAg2IAIAAIAAArIAggrIAIAAIAAA2gAsIgYIAAhCIgoAAIAABCIgIAAIAAhJIA5AAIAABJgAt2gYIAAgLIAJAAIAAALgAuPgYIAAgUIgPAAIgOAUIgKAAIAQgVQgHgCgDgEQgEgEAAgGQAAgIAFgEQAFgFAKAAIAaAAIAAA2gAuphEQgDACAAAFQAAAFADADQAEACAGAAIAQAAIAAgUIgRAAQgFAAgEADgAwMgYIAAg2IAaAAQAIAAAFAEQAFADAAAGQAAAJgJAEQAMADAAAKQAAAHgFAEQgGAEgJAAgAwEgfIASAAQAHAAACgDQAEgCAAgEQAAgEgEgCQgEgDgFAAIgSAAgAwEg3IARAAQAFAAADgCQADgCAAgFQAAgDgDgCQgCgCgFAAIgSAAgAvThNQAHgDAAgFIAAgBIgEAAIAAgLIAKAAIAAAJQgBAHgCADQgDAEgGAAgAishZQgFgFAAgFIAFgBQADAIAGAAQAIAAACgIIAGABQgCAGgEAEQgDADgHAAQgFAAgEgDgATlhaIAAgJIAKAAIAAAJgAPrhaIAAgJIAKAAIAAAJgANfhaIAAgJIAJAAIAAAJgAgkhaIAAgJIAJAAIAAAJgAK1h0IAAhGIAIAAIAAAKQAJgMALAAQALAAAHAIQAIAIAAANQAAAMgIAIQgHAIgLAAQgLAAgJgMIAAAbgALDiuQgHAGAAAJQAAAJAHAGQAGAFAHAAQAIAAAGgFQAFgGAAgKQAAgJgFgGQgGgFgIAAQgIAAgFAGgAH+h2IACgHQAEACAFAAQAEAAACgCQADgBACgHIgYg1IAJAAIATAsIASgsIAIAAIgXA3QgDAJgFADQgDADgHAAQgGAAgFgCgAv4h0IAAhGIAIAAIAAAKQAJgMAMAAQAKAAAIAIQAIAIAAANQAAAMgIAIQgIAIgKAAQgMAAgJgMIAAAbgAvqiuQgGAGAAAJQAAAJAGAGQAHAFAGAAQAJAAAGgFQAEgGAAgKQABgJgGgGQgFgFgJAAQgHAAgGAGgASFh3IAAgOIgsAAIgBAOIgHAAIAAgVIAGAAQAHgNAAgYIAAgJIAnAAIAAAuIAIAAIgBAFIABgEIAEAAIAEAAIADgDIACgHIACglIAnAAIAAA1IgIAAIAAguIgXAAIgBAWIgCANQgCAFgCADQgCADgDAAIgGABIgGgBIAAAOgARmisQAAATgGANIAdAAIAAgnIgXAAgAmXiLQgLAIgNAAQgQAAgLgLQgKgLAAgQQAAgPAKgMQALgLAQAAQARAAAKALQALAMgBAPQABAOgJAKIAKAIIgGAHgAnDi+QgJAIAAANQAAAMAJAJQAIAJAMAAQAKAAAHgFIgNgMIAFgGIAOAMQAGgIAAgLQAAgNgIgIQgIgJgNAAQgNAAgHAJgAM8iLIAEgGQAJAHAJAAQAFAAAFgDQADgDAAgEQAAgEgDgCQgEgDgGAAIgHAAIAAgGIAHAAQAFAAAEgDQADgDAAgEQAAgDgDgCQgEgDgFAAQgJAAgHAGIgEgGQAJgHAMAAQAIAAAGAEQAFAFAAAGQAAAIgIAEQAKAEgBAJQABAHgHAFQgFAFgKAAQgNAAgJgIgAJBiMQgHgJAAgKQAAgLAHgJQAJgJAMAAQAMAAAJAKIgFAFQgIgHgJAAQgIAAgGAGQgFAGAAAJQAAAIAFAGQAHAGAIAAQAIAAAIgIIAFAFQgJALgMAAQgMAAgJgJgAGsiMQgJgJABgKQgBgMAJgIQAHgJAMAAQANAAAIAKIgEAFQgIgIgIAAQgIAAgFAGQgGAEgBAIIAZAAIAAAHIgZAAQABAIAGAEQAFAGAIAAQAJAAAHgJIAFAFQgDAEgGAEQgGADgHAAQgLAAgIgJgAFtiIQgGgEAAgIQAAgJAGgEQAIgFAJAAQAIAAAJACIAAgBQgBgHgEgEQgEgEgHAAQgJAAgIAEIgCgHQAKgEAKAAQALAAAGAGQAFAFAAALIAAAgIgHAAIAAgIQgIAKgMAAQgIAAgGgFgAF0idQgFADAAAFQAAAFAEADQAEADAGAAQAHAAAFgEQAFgEABgGIAAgFQgJgDgHAAQgHAAgEADgADxiKQgHgIgBgKIgMAAIAAAXIgIAAIAAg1IAIAAIAAAXIAMAAQACgLAGgHQAIgHAKAAQANAAAGAJQAIAHAAANQAAALgIAIQgHAJgMAAQgKAAgIgHgAD2iuQgFAGAAAJQAAAIAFAHQAFAFAIAAQAJAAAFgFQAEgGAAgJQAAgKgEgFQgFgGgJAAQgHAAgGAGgAh5iLQgJgIABgMQAAgMAHgIQAIgJALAAQALAAAHAJQAHAHgBANIAAADIgqAAQABAIAFAFQAFAFAIAAQAKAAAHgIIAFAFQgKAKgMAAQgMAAgHgIgAhWijQgCgIgEgFQgEgFgHAAQgHAAgGAFQgEAGgBAHIAjAAIAAAAgAlwiOQgKgLAAgQQAAgPAKgMQALgLAQAAQARAAAKALQALAMgBAPQABAQgLALQgLALgQAAQgQAAgLgLgAlpi+QgJAIAAANQAAAMAJAJQAIAJAMAAQANAAAIgJQAIgIAAgNQAAgNgIgIQgIgJgNAAQgNAAgHAJgAr8iIQgGgEAAgIQAAgJAGgEQAHgFAKAAQAHAAAJACIAAgBQAAgHgDgEQgFgEgIAAQgHAAgJAEIgCgHQAKgEAJAAQANAAAEAGQAHAFAAALIAAAgIgJAAIAAgIQgHAKgMAAQgIAAgGgFgAr2idQgEADAAAFQAAAFAEADQAEADAFAAQAIAAAFgEQAGgEgBgGIAAgFQgIgDgHAAQgIAAgEADgAtniMQgIgJAAgKQAAgLAIgJQAJgJALAAQAMAAAJAKIgFAFQgHgHgJAAQgJAAgFAGQgGAGAAAJQAAAIAGAGQAGAGAIAAQAJAAAHgIIAGAFQgKALgMAAQgLAAgJgJgAw5iMQgIgJAAgKQAAgMAIgIQAIgJAMAAQAMAAAJAJQAHAJAAALQABALgJAIQgIAJgMAAQgMAAgIgJgAwziuQgFAGgBAJQABAIAFAGQAGAGAIAAQAKAAAFgGQAFgFAAgJQAAgJgFgGQgHgGgIAAQgIAAgGAGgACQiFIABgGIAEAAIADAAIAEgDIADgHIABglIAnAAIAAA1IgJAAIAAguIgWAAIAAAWIgDANQgBAFgDADQgCADgDAAIgFABgAkiiPIAGgGIAMAIQAGACAGAAQAHAAAGgDQAEgEAAgGQAAgFgEgDQgDgDgMgCQgNgDgGgFQgGgFAAgJQABgIAGgGQAIgGAJAAQAPAAALAJIgFAHQgKgIgLAAQgFAAgGADQgEAEgBAFQABAFAEADQAEADALADQANADAFAFQAHAEgBAJQABAJgIAGQgGAFgMAAQgQAAgOgLgAT0iFIAAgTIgPAAIgPATIgKAAIARgUQgHgCgEgEQgEgEAAgHQAAgHAGgFQAGgEAIAAIAaAAIAAA1gATZixQgCADAAAFQAAAEADADQAEADAFAAIARAAIAAgUIgRAAQgFAAgFACgAQdiFIAAgqIggAqIgIAAIAAg1IAIAAIAAAqIAggqIAIAAIAAA1gAPfiFIgTgYIgLALIAAANIgIAAIAAg1IAIAAIAAAfIAdgfIAKAAIgWAXIAXAegAObiFIAAgqIghAqIgHAAIAAg1IAIAAIAAAqIAggqIAIAAIAAA1gAMjiFIAAgqIggAqIgIAAIAAg1IAIAAIAAAqIAggqIAIAAIAAA1gAJ6iFIAAg1IAIAAIAAA1gAFRiFIAAgWIgIAEIgKABQgHAAgGgEQgFgEABgIIAAgUIAIAAIAAATQAAAFADACQACADAFAAQAKAAAHgFIAAgYIAIAAIAAA1gACEiFIgTgYIgMALIAAANIgIAAIAAg1IAIAAIAAAfIAegfIAKAAIgXAXIAXAegAA/iFIAAgqIggAqIgIAAIAAg1IAIAAIAAAqIAggqIAIAAIAAA1gAgkiFIAAg1IAaAAQAIAAAEADQAEAEAAAGQABAJgJADQALAEAAAKQAAAHgEADQgFAEgJAAgAgciLIASAAQAFAAAEgDQACgCAAgFQAAgDgCgDQgEgCgGAAIgRAAgAgcijIARAAQAEAAAEgDQACgCAAgEQAAgEgCgBQgDgDgFAAIgRAAgAiTiFIAAgXIgfAAIAAAXIgIAAIAAg1IAIAAIAAAXIAfAAIAAgXIAIAAIAAA1gAnuiFIAAhIIAIAAIAABIgAoniFIAAgTIgPAAIgPATIgKAAIAQgUQgGgCgEgEQgDgEAAgHQAAgHAEgFQAGgEAJAAIAaAAIAAA1gApCixQgCADAAAFQgBAEAEADQAEADAFAAIARAAIAAgUIgRAAQgGAAgEACgApfiFIAAgXIgfAAIAAAXIgIAAIAAg1IAIAAIAAAXIAfAAIAAgXIAIAAIAAA1gAqbiFIAAgXIgfAAIAAAXIgIAAIAAg1IAIAAIAAAXIAfAAIAAgXIAIAAIAAA1gAsjiFIAAguIgSAAIAAgHIAtAAIAAAHIgTAAIAAAugAuJiFIAAgqIghAqIgIAAIAAg1IAIAAIAAAqIAhgqIAHAAIAAA1gAxTiFIgTgYIgLALIAAANIgIAAIAAg1IAIAAIAAAfIAdgfIAKAAIgWAXIAWAegAyXiFIAAgqIghAqIgIAAIAAg1IAIAAIAAAqIAhgqIAHAAIAAA1gA0OiFIAAhIIAfAAQANAAAGAGQAFAFgBAHQABAMgMAFQAQAEAAAOQAAAJgIAFQgGAFgNAAgA0GiMIAYAAQAJAAAEgDQAGgEgBgGQABgGgGgDQgEgEgKAAIgXAAgA0GitIAWAAQAGAAAGgDQAFgEAAgGQAAgGgFgDQgEgDgIAAIgWAAgAJ5jGIAAgJIAKAAIAAAJg");
	this.shape.setTransform(0.3,0);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Слой_3
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#FFFFFF").ss(1,2,0,3).p("A2Gj7MAsNAAAIAAH3MgsNAAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.urText, new cjs.Rectangle(-142.4,-26.2,285,52.5), null);


(lib.t3_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACjCEIAZgbQAlAoAvAAQAvAAAlgmQAVgUAPgeQAOgeAEgeQgQAUgaAQQgbAQggAAQgyAAgfgdQgegcAAgsQAAg1AoglQAogmA5AAQA0AAAhAgQAiAjABBAQgBAzgSAxQgUAwggAgQgzAyg/AAQhAAAgrgxgAEKh4QgbAbAAAlQgBAeAVAVQAUATAnAAQAoABAbgaQAcgaAAgkQAAgfgUgTQgWgXglAAQgpAAgbAagAidCEIAbgbQAkAoAvAAQAvAAAlgmQAUgUAPgeQAOgeAEgeQgPAUgaAQQgbAQghAAQgxAAgfgdQgegcAAgsQAAg1AnglQAogmA5AAQA0AAAhAgQAjAjgBBAQABAzgUAxQgTAwgfAgQg0Ayg+AAQg/AAgtgxgAg1h4QgbAbAAAlQAAAeAUAVQAUATAmAAQAoABAcgaQAbgaAAgkQAAgfgUgTQgXgXgkAAQgpAAgaAagAndCEIAagbQAlAoAvAAQAvAAAlgmQAVgUAPgeQAOgeAEgeQgQAUgaAQQgbAQggAAQgyAAgfgdQgegcAAgsQAAg1AoglQAogmA5AAQA0AAAhAgQAiAjABBAQgBAzgSAxQgUAwggAgQgzAyg/AAQg/AAgtgxgAl1h4QgbAbAAAlQgBAeAVAVQAUATAnAAQApABAagaQAcgaAAgkQAAgfgUgTQgWgXglAAQgqAAgaAagApwCvIBTk0IhHAVIgBgjIBegeIAdAAIheFggAIPAVQgKgDgHgGQgHgGgDgHQgEgLAAgIQAAgHACgJQADgIACgFIAIgJIALgJIgZgGIAEgMIAlAJIAZgKIg4gQIAEgLIBDARQAIgGADgGQAEgGAAgLQAAgFgCgFQgBgEgDgDQgEgDgFgDQgFgCgHAAQgJAAgFACIgLAGIgIAEQgDACgDAAIgCgBIgCgCIgFgMQALgKAMgFQAOgFAOAAQAMAAAJAEQAJADAHAHQAGAGADAHQADAJAAAIQAAAOgDAJQgFAKgFAFIAUAFIgFAMIgcgHIgWAMIAtALIgFANIg8gQIgMAHIgJAHQgEAFgCAGQgCAGAAAIQAAAMAIAGQAIAFAPAAQAKAAAHgDIAMgFIAKgIQAEgCACAAIADABIACACIAGAMQgLAKgPAHQgPAHgRAAQgOAAgJgDg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t3_1, new cjs.Rectangle(-62.4,-18.1,124.9,36.2), null);


(lib.t2_2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AjvBQQgagZAAgmQAAgeAQgcQAPgcAcgSQAbgRAhAAQAnAAAZAZQAZAYAAAnQABAegQAcQgPAcgcASQgbARghAAQgoAAgYgZgAjDhFQgVAPgNAXQgLAXAAAYQAAAfASASQASAUAeAAQAaAAAWgPQAVgPAMgXQAMgXAAgYQAAgfgSgSQgSgUgfAAQgZAAgWAPgAMlBmIAVhOIg3AAIhNBOIgeAAIBShRQgpgMAAgnQAAghAbgTQAZgTAuAAIBRAAIg3DLgALshDQgUANAAAYQAAARANAJQANAJAWAAIA4AAIAXhVIg0AAQglAAgSANgAJVBmIAZhcIh1AAIgYBcIgYAAIA3jLIAXAAIgYBaIB0AAIAZhaIAXAAIg3DLgAF4BmIAZhcIh0AAIgZBcIgWAAIA2jLIAXAAIgYBaIB1AAIAXhaIAYAAIg3DLgACfBmIA3jLIAXAAIg2DLgAgfBmIA1jLIBAAAQAnAAAUASQAOAQAAAWQAAAjgcAUQgcATgtABIgwAAIgTBIgAAPAJIAsAAQAlAAATgNQAUgOAAgZQAAgPgKgJQgNgNgbAAIgtAAgAm6BmIA3jLICFAAIgFAVIhvAAIgwC2gApMBmIgJg2IhvAAIgnA2IgZAAICUjNIAWAAIAmDNgApYAcIgThoIhLBoIBeAAgAtfBmIAxi2IhFAAIAGgVIChAAIgHAVIhFAAIgwC2g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t2_2, new cjs.Rectangle(-88.3,-10.5,176.7,21.1), null);


(lib.t2_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ALUBQQgWgYAAgoIAAgGIgrAAIgYBcIgXAAIA2jLIAXAAIgYBbIAoAAQAKgpAfgbQAegbAnABQAlAAAXAXQAXAZAAAlQAAAigQAcQgOAdgbARQgaAQgfAAQgmAAgWgZgALwg1QgaAeAAApQAAAdAQATQARATAbAAQAkAAAZgeQAagfAAgpQAAgdgQgTQgRgTgbAAQgkABgZAegAAOBQQgZgZAAgmQAAgeAPgcQAPgcAcgSQAbgRAhAAQAoAAAZAZQAZAYAAAnQAAAegPAcQgQAcgcASQgbARghAAQgoAAgYgZgAA6hFQgVAPgMAXQgMAXAAAYQAAAfASASQASAUAeAAQAaAAAWgPQAWgPAMgXQAMgXAAgYQAAgfgTgSQgSgUgeAAQgaAAgWAPgAnmBfQgUgKgKgRIASgMQATAdAnAAQAXAAAQgLQAPgNAAgQQAAgSgPgJQgOgKgUAAIgSAAIAFgSIAUAAQAaAAASgLQASgLAAgSQAAgPgMgKQgMgJgTAAQgcAAgZAUIgNgPQAdgaAnABQAcgBASAOQATAPAAAWQAAAWgQAOQgQAOgbAEQASAFAKAMQALALAAASQAAAZgXARQgXARghAAQgaAAgTgKgAITBmIAZhcIh1AAIgYBcIgXAAIA2jLIAXAAIgYBaIB1AAIAYhaIAXAAIg3DLgADeBmIA2jLICFAAIgFAVIhuAAIgxC2gAjtBmIA2jLIBNAAQAeAAAQANQARANAAAVQAAAVgOAOQgPAPgWAEQAkALAAAeQAAAbgXARQgXARgoAAgAjRBRIBEAAQAcAAAQgLQAQgLAAgTQAAgPgNgIQgOgIgUAAIg+AAgAi4gKIA6AAQAaAAARgMQAQgJAAgUQAAgOgKgIQgLgIgUAAIg6AAgAq5BmIA2jLICSAAIgFAVIh7AAIgTBFIBuAAIgGAVIhuAAIgTBHIB9AAIgGAVgAuBBmIA3jLICOAAIgGAVIh3AAIgRA+IA5AAQAfAAASAOQARAMAAAYQAAAjgbASQgbARguAAgAtkBRIA3AAQAiAAASgMQATgMAAgYQAAgOgMgJQgMgJgVABIg8AAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t2_1, new cjs.Rectangle(-89.7,-10.5,179.6,21.1), null);


(lib.t1_2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AQGBgIANgSQALAHAOAAQAYgBAYgeIgvibIAZAAIAnCEIBliEIAbAAIh6CgQgjAuglAAQgZABgMgKgAAUBfQgUgKgJgRIARgMQATAdAnAAQAXAAAQgLQAPgNAAgQQAAgSgPgJQgOgKgUAAIgSAAIAFgSIAUAAQAaAAASgLQASgLAAgSQAAgPgMgKQgMgJgTAAQgcAAgZAUIgNgPQAdgaAnABQAcgBASAOQATAPAAAWQAAAWgQAOQgQAOgbAEQASAFAKAMQALALAAASQAAAZgXARQgXARghAAQgaAAgTgKgAPUBmIgshYIhVBYIgeAAIBohpIgzhiIAZAAIArBTIBRhTIAeAAIhlBlIA1BmgAMPBmIgKg2IhvAAIgnA2IgZAAICUjNIAWAAIAmDNgAMCAcIgThoIhKBoIBdAAgAIXBmIAxi2IhxAAIgxC2IgXAAIA2jLICgAAIg3DLgAFXBmIgKg2IhvAAIgnA2IgZAAICUjNIAWAAIAmDNgAFKAcIgThoIhKBoIBdAAgAkYBmIA2jLICSAAIgFAVIh7AAIgTBFIBuAAIgGAVIhuAAIgTBHIB9AAIgGAVgApYBmIA2jLIAXAAIgxC2IBhAAIAxi2IAXAAIgxC2IBhAAIAxi2IAWAAIg2DLgAqpBmIAZhcIh1AAIgYBcIgXAAIA2jLIAXAAIgYBaIB1AAIAYhaIAXAAIg3DLgAvyBmIA3jLICSAAIgGAVIh7AAIgTBFIBuAAIgFAVIhuAAIgTBHIB8AAIgFAVgAxABmIAsilIhnBtIgBAAIgthsIgsCkIgXAAIA3jLIAVAAIAsBuIBphuIAZAAIg3DLg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1_2, new cjs.Rectangle(-126,-10.5,252.2,21.1), null);


(lib.t1_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ai+B/IANguIijAAIgPAuIgUAAIARhDIAUAAQArgvAZhbIANgsICDAAIgxC2IAbAAIgVBDgAj8g8QgLAngPAdQgOAggTAUIBxAAIArihIhWAAgAFWBMIANgSQALAFAOABQAYAAAYgfIgvibIAZAAIAnCFIBliFIAbAAIh6CgQgjAvglAAQgZAAgMgJgApLBKQgUgJgKgRIASgOQATAeAnAAQAYAAAPgMQAPgMAAgQQAAgSgOgIQgPgKgTAAIgSAAIAEgTIAVAAQAZABATgLQARgMAAgTQAAgPgMgIQgMgKgSABQgcAAgaATIgNgPQAegaAmAAQAcAAASAOQATAOAAAXQAAAXgQANQgQAOgbAFQASAFAKAMQALAKAAARQAAAagXARQgWASgiAAQgaAAgTgLgAPPBRIgJg2IhwAAIgnA2IgZAAICVjMIAVAAIAmDMgAPCAGIgThnIhKBnIBdAAgAK7BRIAxi2IhFAAIAGgVIChAAIgGAVIhFAAIgxC2gAERBRIAsilIhoBtIgBAAIgshsIgtCkIgWAAIA3jLIAVAAIAsBvIBphvIAZAAIg3DLgAAYBRIAtinIilCnIgWAAIA2jLIAYAAIgtCnICkinIAXAAIg3DLgAsdBRIA2jLICRAAIgFAVIh7AAIgTBGIBuAAIgGAUIhuAAIgSBHIB8AAIgGAVgAvlBRIA2jLICOAAIgFAVIh3AAIgRA+IA4AAQAfAAASAOQASANAAAXQAAAjgbASQgbARgvAAgAvJA8IA4AAQAhAAATgMQATgMAAgXQgBgOgMgJQgLgJgVAAIg9AAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1_1, new cjs.Rectangle(-99.8,-12.6,199.7,25.3), null);


(lib.logo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhqBqIgighIhwAAQgZAAgSgEQgYgFgMgNQgSgSAAggIAAhiQAAgGADgDQAFgEAHAAIB8AAQAbAAARAEQAXAEANANQASASAAAiIAABdIAcAfQADADAAAGQABAFgGAFQgFAEgFAAIgCABQgEAAgEgFgAk/ABQABAXALAKIADADQAMAJAYAAIB8AAIAAhUQABgWgMgMIgCgDQgNgJgZAAIh8AAgAEWBHIAAACQgjgCgPgLQgNgHgCgOIAAgCQAAgIAFgCQADgDAHAAQAGAAAEACQADADABAEIADAEQACAEAJADIAVADIBEAAQAkAAAKgGQAKgEgBgSIAAgBQABgNgHgFQgIgHgZAAIhZAAQgfAAgNgKQgNgLAAgaIAAgLQAAgXAQgKQAUgMAyAAIAwAAQApAAARAKQAMAHADAQIAAACQAAAIgEACQgDAFgHAAQgHAAgDgEQgDgCgBgFIgDgBQgEgJgLgCQgIgCgWAAIgzAAQgeAAgKAFQgJAEAAAQIAAAGQgBALAIAFQAHAGAUAAIBMAAQAmAAAPAHQAWAMAAAhQAAAjgdALQgQAHglAAgAmpBFQgFgFAAgIIAAiXQAAgHAFgEQADgEAHAAQAHAAAFAEQADAEAAAHIAACXQAAAIgDAFQgFAEgHAAQgHAAgDgEgAAeBHQgsAAgWgLQgegRgBgrIAAgmQABgrAegRQAWgMAsAAIApAAQAtAAAWAMQAfARAAArIAAAmQAAArgfARQgWALgtAAgAgVhMQgPALAAAdIAAAjQAAAbAPALQAOAKAbAAIA8AAQAdAAANgKQAQgLAAgbIAAgjQAAgdgQgLQgNgJgdAAIg8AAQgbAAgOAJg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.logo, new cjs.Rectangle(-43.1,-11,86.2,22.1), null);


(lib.holder_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.holder();
	this.instance.parent = this;
	this.instance.setTransform(-181,-214);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.holder_1, new cjs.Rectangle(-181,-214,362,428), null);


(lib.dev_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.dev();
	this.instance.parent = this;
	this.instance.setTransform(-207,-165);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.dev_1, new cjs.Rectangle(-207,-165,414,330), null);


(lib.bgImg2_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.bgImg2();
	this.instance.parent = this;
	this.instance.setTransform(-150,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bgImg2_1, new cjs.Rectangle(-150,-300,300,600), null);


(lib.bgImg1_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.bgImg1();
	this.instance.parent = this;
	this.instance.setTransform(-150,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bgImg1_1, new cjs.Rectangle(-150,-300,300,600), null);


(lib.bg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#92642C","#F8DE91"],[0,1],0.1,300.1,0.1,-299.8).s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.bg, new cjs.Rectangle(-150,-300,300,600), null);


(lib.arrow = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#E3B47D").ss(2,2,0,3).p("AgcgtIArAkAAUgFIAHAFIgHAHAAJAPIglAg");
	this.shape.setTransform(13.3,0);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#E3B47D").s().p("ACBAKIkLAAIAAgTIEQAAIAFAAIAAAEIAAAHIAAAEIAAAEg");
	this.shape_1.setTransform(1.4,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.arrow, new cjs.Rectangle(-12.5,-6,30,12.1), null);


(lib.btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// arrow
	this.instance = new lib.arrow();
	this.instance.parent = this;
	this.instance.setTransform(33.9,-0.7,1,1,0,0,0,0.3,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({x:36.3},3,cjs.Ease.get(1)).to({x:33.9},2).wait(3).to({x:36.3},3,cjs.Ease.get(1)).to({x:33.9},2).wait(1));

	// Слой_5
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AjHA/IAAgWIhIAAIgCAWIgQAAIAAgmIAKAAQANgaAAgtIAAgPIBHAAIAABWIANAAIgDAmgAj5ghQAAAigLAYIAvAAIAAhGIgkAAgACPAoIABgPIAHABQAJAAAEgLQAHgPAAgpIAAgUIBGAAIAABmIgSAAIAAhWIgkAAIAAAJQAAAtgIASQgIAPgQAAIgMgCgAEQApIAAhmIASAAIAABmgABsApIgKgZIgxAAIgKAZIgTAAIAthnIARAAIAtBngABbAAIgSgoIgRAoIAjAAgAgfApIAAhVIggAAIAAgRIBSAAIAAARIggAAIAABVgAihApIAAhmIBLAAIAAAQIg5AAIAAAbIAzAAIAAAQIgzAAIAAAbIA6AAIAAAQg");
	this.shape.setTransform(-20.7,0.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(15));

	// Слой_4
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(255,255,255,0.2)").s().p("ArUDDIAAmFIWpAAIAAGFg");
	this.shape_1.setTransform(0,0,1.069,1);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(15));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-77.5,-19.5,155,39);


(lib.banner = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_156 = function() {
		/*
		if(num >= 4){
			this.stop();
		}else{
			num++;
		}
		*/
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(156).call(this.frame_156).wait(16));

	// logo
	this.instance = new lib.logo();
	this.instance.parent = this;
	this.instance.setTransform(-0.1,-253.1,1.32,1.32,0,0,0,-0.1,-0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(172));

	// urText
	this.instance_1 = new lib.urText();
	this.instance_1.parent = this;
	this.instance_1.setTransform(0.5,266.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(172));

	// btn
	this.instance_2 = new lib.btn("single",0);
	this.instance_2.parent = this;
	this.instance_2.setTransform(-0.5,201.9,1,1,0,0,0,-0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(134).to({mode:"synched",loop:false},0).wait(38));

	// t3_1
	this.instance_3 = new lib.t3_1();
	this.instance_3.parent = this;
	this.instance_3.setTransform(-217,126.9);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(115).to({_off:false},0).to({x:8},10,cjs.Ease.get(1)).wait(31).to({x:214},10,cjs.Ease.get(-1)).to({_off:true},1).wait(5));

	// holder
	this.instance_4 = new lib.holder_1();
	this.instance_4.parent = this;
	this.instance_4.setTransform(258.5,-226.9);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(100).to({_off:false},0).to({x:78,y:-100},15,cjs.Ease.get(1)).to({x:49,y:-73},41).to({x:-265.9,y:220},15,cjs.Ease.get(-1)).wait(1));

	// dev
	this.instance_5 = new lib.dev_1();
	this.instance_5.parent = this;
	this.instance_5.setTransform(-357,152.1);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(100).to({_off:false},0).to({x:-174,y:-65},15,cjs.Ease.get(1)).to({x:-146,y:-90},41).to({x:42,y:-455.9},15,cjs.Ease.get(-1)).wait(1));

	// t2_2
	this.instance_6 = new lib.t2_2();
	this.instance_6.parent = this;
	this.instance_6.setTransform(280,147.5);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(50).to({_off:false},0).to({x:0},10,cjs.Ease.get(1)).wait(30).to({x:-278},10,cjs.Ease.get(-1)).to({_off:true},1).wait(71));

	// t2_1
	this.instance_7 = new lib.t2_1();
	this.instance_7.parent = this;
	this.instance_7.setTransform(-252,110);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(50).to({_off:false},0).to({x:0},10,cjs.Ease.get(1)).wait(30).to({x:252},10,cjs.Ease.get(-1)).to({_off:true},1).wait(71));

	// t1_2
	this.instance_8 = new lib.t1_2();
	this.instance_8.parent = this;
	this.instance_8.setTransform(280,147.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).to({x:0},10,cjs.Ease.get(1)).wait(30).to({x:-278},10,cjs.Ease.get(-1)).to({_off:true},1).wait(121));

	// t1_1
	this.instance_9 = new lib.t1_1();
	this.instance_9.parent = this;
	this.instance_9.setTransform(-252,112.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_9).to({x:0},10,cjs.Ease.get(1)).wait(30).to({x:252},10,cjs.Ease.get(-1)).to({_off:true},1).wait(121));

	// bg
	this.instance_10 = new lib.bg();
	this.instance_10.parent = this;
	this.instance_10.alpha = 0;
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(89).to({_off:false},0).to({alpha:1},11).wait(56).to({alpha:0},15).wait(1));

	// bgImg2
	this.instance_11 = new lib.bgImg2_1();
	this.instance_11.parent = this;
	this.instance_11.alpha = 0;
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(40).to({_off:false},0).to({alpha:1},10).to({_off:true},50).wait(72));

	// bgImg1
	this.instance_12 = new lib.bgImg1_1();
	this.instance_12.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(172));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-351.8,-300,758,600);


// stage content:
(lib._300x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// cover
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#666666").ss(2,1,1).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// banner
	this.instance = new lib.banner();
	this.instance.parent = this;
	this.instance.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-51.8,299,758,602);
// library properties:
lib.properties = {
	id: 'B12536D93F55493D883A9CFDBC1C5E1B',
	width: 300,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/bgImg1.jpg", id:"bgImg1"},
		{src:"images/bgImg2.jpg", id:"bgImg2"},
		{src:"images/dev.png", id:"dev"},
		{src:"images/holder.png", id:"holder"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['B12536D93F55493D883A9CFDBC1C5E1B'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;