(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.billet = function() {
	this.initialize(img.billet);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,320,80);


(lib.box1 = function() {
	this.initialize(img.box1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,202,230);


(lib.box2 = function() {
	this.initialize(img.box2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,182,214);


(lib.img1 = function() {
	this.initialize(img.img1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.img2 = function() {
	this.initialize(img.img2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.img3 = function() {
	this.initialize(img.img3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.img4 = function() {
	this.initialize(img.img4);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.plashka = function() {
	this.initialize(img.plashka);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,172,170);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.t4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AthA8IAKAAQAGgBACgFQACgDACgPQACgOAAgWIgMAAIgBgXIB3gEIAAAXIgLABIABA7IATgBIACA7IgiABIgBghIhIACIABAhIghABgAsnAAQACAigKAYIAlgBIgCg5gAkQBDIhoADIgBgXIAMAAIgCg/IgMAAIgBgWIA6gCIABAXIgMAAIACA8IAkgBIgBg8IgNABIgBgYIA7gCIAAAYIgLAAIACA8IAUgBIACA6IghABgAGMBHIALAAIgDhvIgNABIAAgYIAugBIABASQALgUAVAAQATgBANAPQANAPAAAZQACAWgPASQgOAQgZAAQgKABgMgDIAAAcIANAAIAAAXIg6ACgAG8giQgGAHABAHIABAmQAIABALAAQAKAAAHgJQAFgIAAgNQgBgOgFgIQgHgHgKgBQgJACgFAFgAvpBDIAMgBIgFhpIgLAAIgBgXIA8gCIABAXIgLAAIADBqIALAAIABAXIg7ACgArLBHIARgRQADACAEAAQAHAAACgMQACgKgBgoIgMAAIgBgWIB3gEIAAAXIgMABIACA+IAMgBIABAYIg6ABIgBgXIAMAAIgCg8IgaABQACAwgJASQgJAUgXAAIgCAAQgPAAgMgLgAo1A1IALAAIAQgUQgLgDgGgJQgFgIgCgLQAAgOALgLQAMgLARAAIBIgCIAAAXIgMABIACA+IAMAAIABAWIg6ACIgBgWIAMgBIAAgSIgLAAIgOATIALAAIABAWIg5ACgAoCgIQgGAAgEADQgEADAAADQAAAEAFADQACACAIAAIASgBIAAgRgAjjArIAMgBIgCg+IgNAAIgBgXIAugCIAEBWIAMAAIAAAWIg6ACgAigA2IARgSQADADAEAAQAHAAACgNQABgOgBgkIgMABIgBgXIB2gEIABAXIgMAAIACA/IANAAIAAAXIg6ACIgBgYIANAAIgDg8IgaACQACAvgJASQgJAUgYAAQgRAAgKgKgAAEAsQgPgPgBgZQAAgZAOgPQAQgQAagCQAZgBASAQQARAQAAAXQABAZgQARQgPAQgbABIgDAAQgYAAgQgPgAAtgcQgLAAgHAKQgGAIgBAMQACAOAGAJQAIAIAKAAQALAAAHgJQAHgJgBgOQAAgMgHgJQgIgIgJAAIgBAAgAB3AgIANgBIgDg/IgMABIAAgXIAugBIACBVIANgBIABAYIg7ABgAEGAbIAMgBIgDg+IgLAAIgBgXIA6gCIABAYIgMAAIAAATIARgMIAFgIIgEABIgBgYIA6gCIABAYIgMAAIgWAXIAcAnIAMAAIABAXIg7ABIAAgWIAKAAIgOgXIgTAOIABAKIAMgBIABAXIg7ACgAIZAhQgMgJAAgPQAAgPAOgLQANgKAYgBIARAAIAAgCQgBgHgFgFQgEgDgIAAQgLAAgHADIAAALIgcABIgBgbQASgNAZgBQAYAAAQAKQAPALABARIABAwIAMAAIABAWIguACIAAgNQgMAPgTABIgDAAQgPAAgJgJgAI1gFQgGAFAAAGQAAAEAFAEQAFACAFAAQAJAAAFgIQAFgHAAgJQgGgCgGABQgJAAgHAEgAKQAPIALgBIgBg+IgMAAIgCgXIAvgBIADBVIAMgBIAAAYIg5ABgALZAMIAMgBIgCg+IgMAAIgBgWIA6gCIABAXIgMAAIABASIAngBIgBgSIgMAAIAAgXIA6gCIAAAYIgLAAIABA+IANAAIABAWIg7ADIgBgYIAMAAIAAgSIgoABIABASIAMAAIABAXIg6ACgANpAIIALgBIgBg+IgMAAIgBgXIA6gCIAAAXIgLABIABAmIAng/IAtgBIABAWIgMABIACA+IANAAIABAXIg7ACIgBgXIANAAIgCgmIgnA+IguABgAjchXIAigBIABAZIgiABgABlhiIAigBIABAbIgiAAgACZhjIAigBIABAaIgiABgAJ+hzIAigBIABAaIgiABgAKxh0IAigBIABAaIgiABg");
	this.shape.setTransform(-0.5,9.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// billet.png
	this.instance = new lib.billet();
	this.instance.parent = this;
	this.instance.setTransform(-160,-40);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.t4, new cjs.Rectangle(-160,-40,320,80), null);


(lib.t3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AyvBKQgXgWgBgjQAAgiAVgWQAWgWAjgCQAhAAAXANIACAjIgeABIgBgRQgLgEgNABQgRAAgLAKQgMAKgDAPIBMgBIABAbIhNADQAEARANAJQANAKAQgBQAYAAAMgQIAVAVQgWAXgkAAIgDAAQgjAAgVgTgAGLBFIAMgBIgEhvIgMAAIgBgXIAugBIABARQAMgSAVgBQASgBANAPQANAPABAZQABAYgPAQQgOAQgZABQgMAAgKgEIABAdIAMAAIABAXIg6ACgAHJgrQgIAAgGAHQgFAGAAAHIABAmQANACAGgBQALAAAGgJQAGgIAAgNQgBgOgGgHQgHgIgJAAIgBAAgAheAgIAKAAQAGgBACgEQADgFACgOQABgMAAgYIgMAAIgBgXIB2gDIABAXIgMAAIACA8IASgBIACA6IgiABIgBggIhHACIABAgIghACgAgkgaQACAfgJAaIAkgBIgCg5gAvyBAIAMAAIgCg/IgMAAIgBgWIA6gCIABAXIgMAAIAAASIAogCIgBgRIgMABIgBgXIA7gCIAAAXIgMAAIACA/IANgBIAAAXIg6ACIgBgXIAMAAIAAgUIgoABIABAUIAMgBIABAXIg6ACgAtZBKQgKgIgBgPQgBgRAOgKQAPgLAWgBIARAAIAAgCQAAgHgGgDQgEgEgIAAIgSADIAAALIgcAAIgBgZQATgOAZAAQAXgBAQALQAPAKABARIABAxIAMgBIABAXIguACIAAgOQgNAQgSAAIgEAAQgOAAgJgJgAs8AkQgHAEAAAHQAAAFAFADQAEADAGAAQAJgBAFgHQAGgIgBgKIgMgBQgKABgFAEgArcBBQgQgPgBgaQgBgYAQgQQAQgQAZgBQAZgBARAKIABAbIgdABIAAgMIgKAAQgMABgIAIQgHAJABANQAAANAIAJQAIAJAMgBQAOAAAHgIIATARQgPARgbAAIgEAAQgXAAgQgOgAp+A1IAMgBIgCg+IgMAAIgBgXIAugBIADBVIANAAIAAAXIg6ABgAo6AyIAMAAIgCg+IgMAAIgBgXIA6gCIABAXIgMABIAAARIAogCIgBgRIgMABIgBgXIA7gCIAAAXIgMAAIACA/IAMgBIABAXIg6ACIgBgXIAMAAIAAgUIgoABIABAUIAMAAIABAWIg7ACgAmrAuIAMgBIgCg+IgMABIgBgYIA7gBIAAAXIgMAAIABASIAngBIAAgSIgNAAIAAgXIA6gCIABAXIgNABIADA+IAMAAIABAXIg7ABIgBgXIANAAIgBgUIgnACIAAATIANAAIAAAXIg6ACgAKKAJIALgBQAEAAADgFQADgDACgOQACgOgBgYIgMABIAAgXIB2gEIABAXIgMAAIACA8IATgBIACA6IgiABIgCggIhHACIABAhIgiABgALFgyQABAigJAXIAkgBIgCg5gAkfApIALAAIAPgUQgKgDgGgJQgHgJAAgJQAAgPAKgLQALgKASAAIBIgDIABAXIgNABIADA+IAMAAIAAAXIg6ABIgBgXIAMAAIAAgSIgKAAIgOATIALAAIAAAXIg4ABgAjtgUQgFAAgEADQgEADAAAEQABAFADACQAEACAGAAIATAAIgBgTgAA4AsIARgRQADACAEAAQAHAAACgMQABgLgBgnIgMAAIgBgXIB3gDIAAAWIgMABIACA+IANAAIAAAXIg6ACIgBgXIAMgBIgCg7IgaABQACAwgJASQgJATgXAAIgCAAQgPAAgLgKgADOAaIAKgBIAQgUQgLgDgGgIQgFgIgBgKQgBgQALgKQALgKASgBIBIgCIAAAXIgMAAIACA+IAMAAIABAXIg6ACIgBgXIAMgBIAAgSIgLAAIgNATIAKAAIABAXIg5ACgAEAgkQgGABgEACQgEAEABADQAAAEAEADQAEADAGgBIASAAIAAgTgAIdAYQgRgPgBgYQAAgZAPgRQARgQAZgBQAaAAARAPQARAOAAAaQACAYgQAQQgQARgaABIgEAAQgXAAgQgPgAI0gnQgHAKAAANQABANAHAIQAIAIAKAAQALAAAGgJQAHgIAAgOQgBgOgHgIQgHgIgLAAQgLABgGAIgAMiAHIAMgBIgCg+IgMAAIgBgXIA6gCIABAXIgMABIABAmIAng+IAugCIABAXIgMAAIACA/IAMgBIABAXIg6ACIgBgXIAMAAIgBgmIgnA+IguACgAOzACIAMAAIgCg/IgMABIgBgXIA6gCIABAXIgMAAIAAASIAogBIgBgSIgMABIgBgYIA7gCIAAAYIgMAAIACA/IAMAAIABAWIg6ACIgBgXIAMAAIAAgTIgoABIABATIAMgBIABAXIg6ACgARCgBIAMgBIgCg/IgMAAIgBgXIA7gCIAAAXIgMABIACAmIAmg/IAugBIABAXIgMAAIACBAIAMgBIABAWIg6ACIgBgWIAMAAIgBgnIgnA+IguABgAp2hNIAigBIABAaIgiABg");
	this.shape.setTransform(1,9.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// billet.png
	this.instance = new lib.billet();
	this.instance.parent = this;
	this.instance.setTransform(-160,-40);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.t3, new cjs.Rectangle(-160,-40,320,80), null);


(lib.t2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AoOBhIAMAAIgDhvIgNAAIAAgXIAugCIAAASQAMgTAVgBQATAAANAPQAMAPABAYQABAXgPASQgOAQgYAAQgNAAgKgDIABAdIANgBIAAAYIg6ABgAndgIQgGAGAAAGIACAnQAJADAJgBQALAAAGgJQAGgIAAgOQAAgNgHgIQgGgIgLAAQgIAAgFAHgAzrBIIAMgBIgEhqIgMAAIAAgXIA7gBIABAXIgLAAIABAlIBBgBIgBgmIgMAAIAAgXIA8gCIAAAXIgLABIADBqIAMgBIABAXIg8ACIgBgXIAMAAIgCgoIhBACIABAoIAMAAIABAXIg8ACgAwxBLQgRgPgCgZQAAgaAOgPQAOgQAZgBQAZAAAPAPQAPAOABAZIAAALIhKACQACAJAIAGQAIAFALAAQAQgBAIgIIATARQgRARgbAAIgEAAQgZAAgPgOgAwaAIQgGAGgCAIIApgBQAAgIgGgGQgGgFgIAAQgIABgFAFgAuPA9IAMgBIgCg+IgMAAIgBgXICDgEIAAAXIgMABIACA+IANgBIAAAXIg6ACIgBgXIAMAAIgCg8IgmABIACA8IAMAAIABAXIg7ABgAr0BBQgRgPgBgaQAAgYAPgQQARgRAZAAQAagBARAPQARAPAAAZQABAZgQAQQgPARgaAAIgDAAQgYAAgQgOgAreABQgGAIAAAOQABAOAHAIQAHAJALAAQALgBAGgJQAHgJgBgNQAAgOgHgIQgHgIgLAAQgLABgHAIgAptAzIAMAAIgCg8IgIABIABALIgdAAIgBgkIBqgEIACAlIgdABIAAgLIgIAAIACA8IAMgBIABAXIg6ACgAmNAsIANAAIgCg+IgNAAIgBgXIAvgCIACBWIANgBIABAXIg7ACgAk9AzQgQgPgBgaIAAgUQgBgSAEgNQACgLAHgIQAGgIAIgFQAJgFAHgCIARgFIAOgEIAAgLIAcgBIABAWQgHAIgLAFQgLAFgIAAIgRAEQgHACgFAIQgEAGAAAOQANgTAWgBQAUAAANAPQANAQAAAXQABAZgPAQQgQARgZAAIgDAAQgXAAgPgOgAkmgLQgGAJAAAMQAAANAHAJQAHAIAKAAQAKgBAGgIQAGgKgBgMQAAgNgHgIQgGgJgLAAQgJABgGAJgAjUAmIANAAIgCg+IgNAAIgBgXIA7gCIABAXIgNABIABASIAngCIAAgSIgMABIgBgXIA6gCIABAXIgMAAIACA+IAMAAIABAXIg7ACIAAgXIAMAAIgBgUIgnABIAAAUIANgBIABAXIg7ACgAg4ArQgQgQgBgZQgBgYAQgQQAPgQAagBQAagBAQAPQARAPABAZQAAAYgPARQgPAQgaABIgDAAQgYAAgQgOgAgQgeQgJAAgIAKQgHAJABAMQAAANAHAJQAIAJAKgBQAKAAAHgJQAHgJgBgNQAAgNgIgJQgGgIgKAAIgBAAgABzAcIAMgBIgCg+IgNABIAAgYICCgEIABAXIgMABIACA+IAMAAIABAXIg6ACIgBgXIAMgBIgCg7IgmABIACA7IAMAAIABAXIg7ACgAEOAgQgRgPgBgYQgBgZAQgRQAPgQAbgBQAaAAARAPQAQAOABAaQABAZgQAPQgPAQgaACIgDAAQgYAAgQgPgAEkgfQgGAJAAAOQABAMAHAJQAIAIAKAAQALAAAGgJQAHgKgBgMQAAgOgHgIQgHgIgLAAQgLABgHAIgAGLAcQgQgPgBgYQgBgZAQgRQAPgQAagBQAZAAARAJIABAcIgdABIAAgNIgKABQgMAAgIAJQgHAKABANQAAAMAIAJQAIAJAMgBQAOAAAHgJIATARQgPAQgbACIgDAAQgYAAgQgPgAHpAQIAMAAIgCg/IgMABIgBgXICDgFIABAYIgMAAIACA+IAMAAIABAXIg7ACIAAgXIAMgBIgCg7IgnABIACA7IANAAIAAAXIg6ACgAJ4ALIAMAAIgCg+IgMAAIgBgXIAugBIADBVIAMAAIABAXIg6ABgAK8AJIAMAAIgCg/IgMABIgBgXIA6gCIABAXIgMAAIACA8IAcgBIgCg8IgNABIAAgXIA6gCIABAXIgMAAIACA8IAcgBIgCg8IgNABIAAgXIA6gCIABAXIgNAAIADA/IAMgBIABAXIi3AGgAOHASQgKgJgBgOQAAgQAOgLQANgKAYgBIAQAAIAAgCQAAgIgFgEQgFgDgIAAQgJAAgJADIABALIgdABIgBgbQATgNAZgBQAZgBAOALQAQAKAAASIACAwIAMAAIABAWIguACIgBgOQgLAQgUAAIgDAAQgOAAgKgIgAOkgUQgGAFAAAGQABAFADADQAFADAGgBQAJAAAFgHQAGgGgBgLQgFgCgHAAQgJAAgHAFgAQNAAIAMgBIgCg8IgIAAIAAAMIgcABIgBgmIBqgDIABAlIgcABIgBgMIgHAAIACA9IAMAAIABAWIg7ACgARqgDIAMgBIgCg/IgMAAIgBgXIA7gCIAAAXIgMABIACAmIAng/IAtgBIABAXIgMAAIACBAIAMgBIABAWIg6ACIgBgWIAMAAIgBgnIgnA+IguACgAmFhVIAigBIABAZIgiABgAKAh2IAigBIABAaIgiABg");
	this.shape.setTransform(5,9.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// billet.png
	this.instance = new lib.billet();
	this.instance.parent = this;
	this.instance.setTransform(-160,-40);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.t2, new cjs.Rectangle(-160,-40,320,80), null);


(lib.t1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AyEBZIjWAHIgBgXIAMAAIgEhqIgLAAIgBgXIA7gCIABAXIgLAAIAEBlIAzgCIgDhkIgMAAIgBgXIA8gCIAAAXIgLABIADBkIA0gBIgDhlIgMAAIgBgXIA8gCIABAXIgLABIADBkIAZAAIADBCIglABgAxGBJQgQgPgCgZQAAgZAQgPQAPgQAagBQAagCARAQQARAOAAAZQACAZgQARQgPAQgbABIgDAAQgYAAgQgPgAweAAQgKAAgHAKQgHAJABANQAAAOAIAIQAGAIAMAAQAKAAAHgJQAGgJAAgOQgBgNgHgJQgHgIgJAAIgCAAgAH/A+IANAAIgEhvIgMAAIgBgXIAugCIAAASQAMgTAWgBQASAAANAPQANAPAAAZQABAXgPAQQgOARgYAAQgMAAgLgDIACAdIAMgBIAAAYIg6ABgAIwgrQgFAGgBAHIABAmQANACAGAAQALAAAGgJQAHgIAAgNQgBgNgHgJQgGgIgLAAQgHAAgGAHgAvIBFQgPgPgBgZIgBgWQAAgQADgNQAEgOAFgGQAFgGAJgGQAIgEAJgDIARgFIAOgFIgBgLIAdgBIAAAXQgGAIgMAEQgKAFgJABIgQAEQgJADgDAGQgFAIABANQANgTAWgBQAUAAAMAPQANAOABAYQABAagQAQQgPAQgZABIgDAAQgXAAgQgPgAuhgCQgKAAgFAIQgHAIABAPQABANAGAIQAHAJAJgBQAKAAAGgJQAGgIAAgOQgBgNgGgJQgHgHgJAAIgBAAgABzAXIALAAQAEgBADgEQAEgGABgMQACgMAAgaIgMABIgBgXIB3gEIAAAXIgLAAIACA8IASgBIACA7IgiABIgCghIhHADIABAgIgiABgACugkQABAjgJAWIAkgBIgBg5gAsfA3IALAAIgBg/IgNABIgBgYIA7gBIABAXIgMAAIAAARIAngBIAAgRIgMAAIgBgXIA6gCIABAXIgMABIACA+IAMAAIABAXIg6ACIgBgXIAMgBIgBgUIgnACIABATIAMAAIAAAXIg6ACgAqGBBQgMgJAAgPQAAgQAOgLQAOgKAWgBIASAAIAAgCQgCgHgEgDQgFgEgIAAIgRADIAAAKIgcABIgBgaQARgMAagCQAYAAAQAKQAPALABASIABAvIAMAAIAAAXIguABIAAgNQgMAPgSAAIgEAAQgPAAgIgIgApqAaQgGAFAAAGQAAAFAFADQAEADAGAAQAIAAAGgHQAFgIAAgKQgGgCgGAAQgKABgGAEgAoJA3QgQgPgBgZQgBgYAPgRQARgQAZgBQAYAAASAKIABAcIgeAAIAAgMIgKAAQgNABgGAIQgHAIAAAOQABANAHAJQAIAJANgBQANAAAIgJIASARQgPARgbABIgDAAQgXAAgQgPgAmrArIAMAAIgCg/IgMABIgBgXIAugCIADBWIAMgBIABAXIg7ACgAlnApIAMAAIgCg/IgNABIgBgXIA7gCIABAXIgNAAIABASIAogBIgBgSIgNAAIgBgXIA7gCIABAYIgMAAIACA+IAMAAIABAXIg6ACIgBgXIAMgBIgBgTIgnABIABATIALAAIABAXIg6ACgAjZAkIANAAIgCg+IgNAAIAAgXIA6gCIABAXIgNABIABASIAogCIgBgSIgMABIgBgXIA7gCIABAXIgNAAIACA/IAMgBIABAXIg6ACIgBgXIAMAAIAAgUIgoABIABAUIAMgBIABAXIg6ACgAhNAgIALAAIAQgUQgKgEgHgIQgGgHgBgLQAAgQALgKQALgLASAAIBHgCIABAXIgNAAIACA/IAMgBIABAXIg5ACIgBgXIAMAAIAAgTIgLABIgOASIALAAIABAXIg5ACgAgagdQgFAAgEADQgFACAAAFQAAAEAFACQADADAHAAIASgBIAAgTgAEYAeQgQgPgBgZQgCgYAQgRQARgQAZgBQAZgBASAPQAQAPACAaQAAAYgQAQQgPARgaAAIgDAAQgYAAgQgOgAEughQgGAIAAAOQABANAHAIQAHAJALAAQALgBAGgJQAHgJgBgMQAAgOgHgIQgHgJgLAAQgLABgHAJgAGXAaQgQgPgBgZIgBgWQAAgRACgNQAEgNAGgHQAFgGAKgGQAHgFAJgCIAQgFIAPgEIgBgLIAcgBIABAWQgHAIgLAFQgIADgLACIgRAEQgIADgDAHQgFAHAAANQANgTAWgBQAVAAAMAPQAMAOABAaQACAXgQARQgQARgZAAIgDAAQgWAAgPgOgAGtgkQgGAJABANQAAANAGAIQAHAIAJAAQALgBAGgIQAGgJAAgNQgBgNgGgJQgHgIgKAAQgKABgGAJgAKTASQgSgPgBgZQAAgZAOgQQAOgQAZgBQAYgBAQAPQAPAQABAZIAAALIhLACQADAKAIAEQAHAFAMgBQAPAAAIgIIATARQgPAQgcABIgEAAQgYAAgQgOgAKpgwQgGAFgBAJIAogBQAAgJgGgFQgFgFgIAAQgIAAgGAGgAM1ADIANAAIADg/IgLABIAAgXIAzgCIAeA5IAZg7IA0gBIAAAXIgKAAIAIA/IANAAIABAWIg7ACIgBgXIANAAIgEgmIgaA9IgVABIgeg8IgBAmIANgBIAAAXIg7ACgAP3AMQgKgJgBgOQAAgPAOgMQAOgLAXAAIAQAAIAAgCQAAgHgFgEQgGgEgHAAQgKAAgIADIABALIgdABIgBgbQATgMAZgBQAZgBAOAKQAPAKABATIACAwIAMAAIAAAWIgtABIgBgNQgMAPgTABQgRAAgKgJgAQkgeQgKAAgGAEQgGAFAAAGQAAAFAEADQAEADAHAAQAIAAAFgHQAHgHgBgLIgJgBIgDAAgAR8gGIANAAIgDg9IgIAAIABAMIgcABIgCgmIBrgDIABAmIgcABIgBgMIgIAAIACA8IANAAIABAWIg7ACgATagJIAMAAIgChAIgMAAIgBgWIA6gCIABAXIgMAAIABAnIAng/IAugCIABAXIgMABIACA/IAMAAIABAWIg6ACIgBgWIAMgBIgBgnIgnA+IguACgAmjhWIAigCIABAaIgjABg");
	this.shape.setTransform(5.5,9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// billet.png
	this.instance = new lib.billet();
	this.instance.parent = this;
	this.instance.setTransform(-160,-40);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1, new cjs.Rectangle(-160,-40,320,80), null);


(lib.plashka_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.plashka();
	this.instance.parent = this;
	this.instance.setTransform(-86,-85);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.plashka_1, new cjs.Rectangle(-86,-85,172,170), null);


(lib.logo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#6F2A30").s().p("AtsFyQgkgggmhHQg8hvgohzQhJjQA4hIQAsg4ELgpQC5gbEOgSQE6gUFLABQFLAAEQAVQAyAEAYAGQAiAJASAVQAXAcgEAzQgGA8gWCKQgNBQgBAPQgDAqgoAOQgfALh4ALIhrALQliAnmlBMQmnBNk6BTQgTAFgRAAQgpAAgkgggAkrlUQkMARjGAfQjtAkghArQgWAcAIBDQAIBEAlBiQAnBpAzBeQArBRAlAXQAaAQAigKQE8hTGohNQGnhNFjgnIBsgLQBqgKAZgGQAZgHABgRQABgRAOhSQAViBAGhCQADgigNgPQgKgMgbgGQgUgEgpgDQkTgVlRAAQlDAAkzATgAtCC0Qgmg0gCg/QAAg4AqgoQAogoBIgSIAAABQAWgGAWgDQAVgDARAAQAUAAAUADIAQADIACBpIglgCQgnAAgQAQIgDAEQgKANADASQACAQAMALQASARAXAAQAPAAARgHIAUgJQAAA8AZAoIABACIAGAKIgJAFQhDAkg7AFIgTAAQhZAAgwhCgAoYC2QgSgfgDgnQgBgYABgJQAIgpAzgPQAPgEAPAAQANAAAMADIAAgGIAxgNIAxgKIAMAmQAQA4AEAuIACAjIhhAbIAAgTIgCAAIgFAGQgUAZgaAGQgLADgIAAQgkAAgUgigAnHBbQgFAOAGAMQAGAOAMAAQAKAAAKgLIgJgqIgIgBQgSAAgEAOgAlJgWIgJgWIBTgUIAEAMIAPAsIAdgEQgFgYgOggIBggSQATA6AIAhQANAyACAqIhcATQgEgpgIgkIgfAJIAJBPIhOATQgFhTgghVgAgiBlQgCgLAGgHQAFgHALgCQAVgEADAUQABAEgCAEIgcAFQADAKALgCQAGgBAEgGIAIAFQgFAJgMACIgIABQgSAAgEgUgAgMBTQgJABAAAKIATgDIAAgCQgBgHgHAAIgCABgAASBpIAFgBIgEgYIgGAAIgBgJIATgDIADARIAGgEIADgGIgCAAIgBgJIAWgDIABAJIgJACIgFAKIANANIAJgBIABAKIgQADIgFgDIgNgOIgCACIABAJIAEAAIABAIIgWADgABIBTQgCgLAFgHQAFgHAKgCQAEAAAHACIABgDIAIgBIADASIgKACIgCgHQgDgCgEAAQgKACACANQADAPAMgBQAHgCAEgGIAHAFQgEAKgOACIgIAAQgSAAgDgUgADsBdIAGgBIgHguIgFAAIgBgJIARgDIABADIAAAAIADgDQAFgDAHgBQAVgDADAWQABALgEAIQgFAIgKABQgGABgFgBIgDgBIgBAAIACAPIAGgBIAAAJIgXADgAECAoQgEABgDACIgCADIADAVIACABQAEABAEAAQAMgCgDgQQgBgHgDgCQgCgCgEAAIgDAAgAB6BYIAFgBIgDgYIgFAAIgBgJIA1gJIACAJIgFACIAEAZIAGgBIAAAJIgSADIgFgiIgSACIAEAZIAGAAIAAAJIgXADgAC1BCQgCgLAGgHQAGgHALgCQAVgDADATQABAFgCADIgdAFQACAKAMgCQAHgBAEgFIAHAFQgEAJgOACIgHAAQgTAAgDgUgADLAwQgJABAAAKIATgCIAAgCQgBgHgHAAIgCAAgAExA9IAFgBIgDgZIgIABIAAAIIgJACIgCgSIAAAAIApgFIAJgCIACASIgKABIgBgIIgIABIADAaIAGgBIAAAJIgXADgAF7A6IgFgDIAEgIIAEACQAGACAGAAQAKgCgBgFQAAgFgKACIgGAAIgBgIIAHAAQAGgCAAgGQgBgEgGABQgFAAgCADIAAAEIgKACIgCgPIAJgBIABACQAFgEAFgBQAIgBAFADQAFACABAGQABAFgGAGQAJABABAIQABAGgGAGQgGAFgJABIgHAAQgHAAgEgCgAHEAqIAFgBIgDgZIgFAAIAAgJIASgCIACARIASgDIgBgIIgEgBIgBgHIAWgDIABAKIgEABIADAZIAFAAIABAIIgTADIgCgTIgSADIABAKIAEAAIAAAHIgVADgAICAgQgBgIAKgFQAGgDANgDIAAgBQAAgIgIABQgFAAgCADIgBAFIgKABIgBgOIAIgBIACABQAFgDAHgBQARgBACAQIACATIAGAAIAAAIIgQACIgCgEQgDAGgLABIgFAAQgMAAgBgLgAIQAdQAAAGAIgBQAGAAACgFIgBgIQgQADABAFgAI2APQgBgKAFgGQAGgHAKgBQAGAAAFADIABgDIAJgBIABARIgKABIgCgHQgDgBgEAAQgKAAACAOQABAPANgBQAGgBAFgGIAGAGQgEAJgOABIgEAAQgVAAgDgWgAJoAYIAGgBIgDgYIgFAAIAAgJIASgCIAEAiIAFAAIAAAJIgXACgAKGAVIAFgBIgBgXIgFAAIgBgKIATgBIABAQIASgCIgBgIIgDAAIgBgHIAWgCIABAJIgFABIACAYIAGAAIAAAJIgTABIgBgSIgSACIABAKIAEAAIAAAIIgWABgALFAQIAFgBIgBgXIgFgBIAAgJIASgBIABARIASgBIAAgJIgEAAIAAgIIAWgBIAAAJIgEABIABAYIAGAAIAAAJIgTABIgBgSIgSABIAAAKIAEABIAAAHIgWABgAMCAMIAIAAIAEgIQgKgEAAgHQgBgOAWgCIAZgBIABAJIgEABIABAZIAFAAIAAAIIgTABIgBgOIgHAAIgFALIgDAEIgPABgAMRgIQAAAIAJgBIAHAAIgBgNIgFAAQgKABAAAFgAhXACQgJgggTg9IgEgNIhfASIgIgSQgfhTBKg6QAygnBNgKQAVgDARAAQARAAAVADIAQADIACBqIghgCQgdAAgSALQgNAIgDAPQgEAPAKANQARAXAdAAQAIAAAIgCIAYgGQgCAaAIAXQAHAaAQASQhCAXgxAAQgSAAgVgEgAmsglIABAAIgBgBIgBgDIAAACIABACIgCAAQgMAHghgCIgWgCIgJgDIgCgBIAFgBIABAAQAEgBARgOIAOgLQAMgJANgCIABAAIAAgBQgSABgjgSIgXgMIgKgIIgCgCIAIABIAAAAQAHABAZgIIAUgGQASgEAPADIAAgCIgBgBQgNgFgUgbIgMgSIgEgIIAAgDIAEAEIABAAQAEAEAVADIAQADQAJACAHAEQgFgHgEgJIgGgQQgHgVgDgDIgFgFIACAAIAKADIATAJQAMAHAIAGQAAgHACgHIACgHQAFgOABgHQAAgKgFgSIgCgIIAGAGQAJAHAPAUQAOATAEAOQAAgNAGgUIAHgUQACgGACgDIACgCIAAAGIAAABQAAAFAKASIAIAQIADAHQADgFAGgEIAFgDQAMgHAEgEQAGgHAGgOIADgHIABAHQADAKgCAWQgBATgFAMQAJgJAPgKIASgLQAJgFADAAIgEAFIAAAAQgDAFgFAUIgCAJQgGAMgEAMIgDANIgDgDIgBgBQgTgSgdgIQgcgHgbAGIAAABIgCAAQgOADgNAIIgLAHQgeAVgLAjIgBADIAAABIgBADQgCAIgBAPIAAASIAAACQADAUAKASIAEAGIAIALIALALIACACIgGACIgCgCIgBADIgJACIAFgKIgBgBIgNAMIAAABIgFABIADgEIANgNIgBgCQgNAKgKALIgFAAQALgMAOgNIgBAAIgQALQgJAHgFAIIgHACQAPgfAOgJgAnagkQAMABALgEIAPgHIAAgBQgeAKgagBgAnFgwIgnAIIgCABQAYABAggMIAAgCgAnRg1IgRAIIgFACIAhgIIAOgEIAAgBIgHAAQgJAAgJADgAnFhCQgIACgGAEIgZARIAJgEQAKgHAHgCQAOgFAKAAIgBgHIgKACgAnqhhQANAGAPABIAUgBIAAgBQgsgGgXgKgAm6hhIAAgCIgTgDIgwgJIgDAAQAcAOAqAAgAnvhwIgHABIAqAGQAJACAJAAIAAgCQgPgHgPgBIgIgBIgPACgAnYh1QARAAAOAGIABgIIgMgDQgKgCgIACIgVAEIgQAEIALgBQAMgDAJAAIADABgAnSilQAHAKALAGIAOAGIABgBQgZgNgSgXgAnDifQAMAIAIAEIAAgBIgrgiIgDgBQAKAMAQAMgAmtiXIAAgBQgGgKgMgIQgJgFgIgCIgFgCgAnPi0QANAEAFADQANAJAGAHIAFgFIgIgHQgHgFgHgCIgdgHgAmujBQACAGAGAGIAIAHIAFgFQgLgHgIgKQgEgFgGgMIgEgIgAm0jWQAEAHAHAJQAJAKALAFIABAAIgigjgAjnjhQgEAMgEAGQgJAMgHAHIABABIAEADIAHgHQAFgHACgGIAFgRIAEgNgAm5jfIAnAmIABgBQgUgcgWgLgAmNi8IAAgBIgIgNQgIgKgKgFIgRgIQAUALAXAagAj8jMIgJAMIABABQAMgHAGgLIAJgRIACgFgAmIjlIgDAHQgDAKAFAKQAFAFACAEIADgCQgFgIgCgOIACgTQACgKgCgKQABALgFAQgAkJjCIABAAIAjgqIABgCQgTAOgSAegAj2jkQgKAHgGAKIgHAOIABABQAQgaAVgQgAmBjsIABARQACAOAFAGIACAAQgEgfgHgYQACAHgBALgAmGkMQALAZALAoIAEgBQAAgRgXguIgEgEgAkPkJQgFAXgQAiIADABQAJgLALgsIAAgGgAkbjQQAMgPACgiQgGAmgIALgAlojQQAAgYgYgeQAWAlACARgAkdjxIgJANQgEAGgBAGIgBAFIABABQAPgXAJgUQgFAIgFAEgAkmjwIgFADQgJAFgCAJIAAACIAAAJIADAAQAEgMAEgGIAMgMQAHgGAEgIQgFAIgNAIgAlWj7QgEALACAMIAEAQIABgBQgEgbAGgdgAlQjVIACgBIAAg2IgBgDQgGAWAFAkgAlLjWIABAAQAEgNgBgMQgBgJgDgKIgCgFgAlJkDQAFANAAAGQACAQgCAJIAFAAIACgHIAAgDQAAgIgDgHIgMgcgABYgSQgagWgHgqIgBgQQgCgYAQgPQAOgNAYgGQAMgDALAAQAQAAATAGIACgGIBagLIAYCQIhYANIgCgOIgFAEQgSAVggAAQgbAAgUgQgACUhjQgFAIADAJQACAKAIAFQAEADAFAAQAKAAAHgGIgHgjQgFgCgGAAQgLAAgFAIgAmkgqQgWgmAMgrQAMgrAngXQAogWAqAMQAfAJAVAXIgBAGQgUgZgggJQgqgLglAVQglAWgMApQgLApAVAlQAKASARANIgGACQgPgNgKgSgAJogYQgBgGAJgBQAHgBABAHQABAHgIABIgCAAQgHAAAAgHgAmBgWQgFgFAGgFQAGgGAEAFQAFAEgGAGQgCACgDABQgDAAgCgCgAEXjEIBQgKIAEA2IAaAAIgEg3QALgDAegDQAcgCAOAAIAFAAIANClIhTAIIgIg/IgdADIAIA/IhGAHgAlfghQgCgDAAgDIADAHIgBgBgAmUguQgCgCABgDQAAgDACgDQAGgFAEAEQAFAFgGAGQgDADgCAAQgBAAgBgBQAAAAgBAAQAAAAgBgBQAAAAgBAAgAlxgxQgCgCAAgDQAAgDADgCQAFgGAFAFQACACAAADIgDAAIABADIgBACQgCACgDABIgBAAQgBAAAAgBQgBAAAAAAQgBAAAAgBQgBAAAAAAgAHsjYIBQgHIAEBEQATgmANggQANgDAggBQAegBADACIAIClIhIADIgGhQQgQAkgTAwIhGAEgAMehBIADhHQgTAMgTAAQgSAAgRgJQgKgHgDgIQgFgLACgZQABgoACgOIACgNIBJgHIgGAtIgDAVQgBAMACAJIAIABQAIAAAFgFIAJhTIBGgFIgODGgAmBhIQgEgFAFgFQAGgGAFAFQAEAEgFAGQgDADgDAAQgCAAgDgCgAmhhNQgEgEAFgGQAGgFAEAEQAFAFgGAFQgCADgDAAIgBAAQAAAAgBAAQAAAAgBAAQAAgBgBAAQAAAAgBgBgAmChiQgFgFAGgFQAFgGAFAFQAFAEgGAGQgDADgDAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQgBgBAAAAgAkXhqQgEgEAFgGQAGgFAEAEQAFAFgGAFQgCADgDAAQgDAAgCgCgAmchvQgFgEAGgGQAGgGAEAFQACACAAADQAAADgDACQgDADgDAAQgCAAgCgCgAj9h5QgEgEAGgGQADgDACAAIADANQgDACgCAAQgCAAgDgCgAl2h/QgFgFAGgFQAFgGAFAFQAFAFgGAFQgCACgDABIgBAAQgBAAAAgBQgBAAAAAAQgBAAAAgBQgBAAAAAAgAkliAQgFgFAGgGQAFgFAFAEQAFAFgGAFQgDADgDAAQgBAAAAAAQgBAAAAAAQgBAAAAgBQgBAAAAAAgAk9iOQgCgCABgDQAAgDACgCQAGgGAFAFQAEAEgFAGQgEADgCAAQgBAAAAAAQgBAAgBAAQAAgBgBAAQAAAAgBgBgAmNiOQgEgFAFgFQAGgGAFAFQAEAEgFAGQgDADgDAAQgCAAgDgCgAkMiPQgFgFAGgGQAFgFAFAEQAFAFgGAFQgDADgDAAQgBAAAAAAQgBAAAAAAQgBAAAAgBQgBAAAAAAgAlaiRQgFgEAGgGQAFgFAFAEQAFAFgGAFQgCADgDAAIgBAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQgBAAAAgBgAknijQgFgFAGgGQAFgFAFAEQACACAAADQgBAEgCACQgDADgDAAQgBAAAAgBQgBAAAAAAQgBAAAAgBQgBAAAAAAgAlwilQgCgCABgDQAAgDACgDQAGgFAFAEQAEAFgFAGQgCACgEAAIgBAAQAAAAgBAAQAAAAgBAAQAAAAgBgBQAAAAgBAAgAlJitQgCgCABgDQAAgDACgCQADgCADgBQADAAACACQAEAEgFAGQgEADgCAAQgBAAAAAAQgBAAgBAAQAAgBgBAAQAAAAgBgBg");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#F3DA52").s().p("AuSGOQglgkgohJIAAAAQg2hkgphvQgvh/gFhVQgEhVAmgxQAWgcAugUQAugVBQgSQB/gcDKgWQDBgTDvgMQDugLDzAAQFUAAEWAVQA4AFAcAHQAwAOAaAfQAlAqgHBHQgGA8gWCNQgMBHgBAVQgGBLhOAYQgiAKh2ALIhrALQlgAmmkBNQmkBMk5BTQgZAGgXAAQg/AAg0gygAktl9QkOASi5AbQkLApgsA4Qg4BIBJDQQAoByA8BvQAmBHAkAhQAkAfApAAQARAAATgEQE6hTGnhNQGlhNFigmIBrgLQB4gMAfgKQAogOADgqQABgPANhRQAWiJAGg9QAEgygXgcQgSgVgigJQgYgGgygFQkQgUlLAAIgQgBQlDAAkyAUgAtCFeQglgWgrhRQgzhegnhpQglhjgIhDQgIhDAWgcQAhgrDtgkQDGgfEMgRQEzgTFDgBQFRAAETAWQApADAUAEQAbAGAKAMQANAOgDAjQgGBCgVCBQgOBSgBARQgBARgZAGQgZAHhqAKIhsALQljAnmnBMQmoBOk8BTQgMAEgMAAQgTAAgRgLgAtAgfQgqAoAAA4QACA/AmAzQAwBDBZAAIATAAQA7gGBDgkIAJgEIgGgKIgBgCQgZgoAAg9IgUAJQgRAIgPAAQgXAAgSgSQgMgLgCgQQgDgRAKgNIADgFQAQgQAnAAIAlADIgChpIgQgDQgUgDgUAAQgRAAgVADQgWACgWAHIAAgBQhIASgoAogAnyAXQgzAPgIApQgBAIABAZQADAnASAfQAUAiAkgBQAIAAALgCQAagGAUgZIAFgHIACABIAAASIBhgbIgCgiQgEgvgQg3IgMgmIgxAKIgxAMIAAAHQgMgDgNAAQgPgBgPAFgAlSgtIAJAXQAgBVAFBTIBOgTIgJhPIAfgJQAIAjAEApIBcgSQgCgqgNgzQgIgggTg6IhgASQAOAfAFAYIgdAEIgPgrIgEgMIhTATgAgOBKQgLABgFAIQgGAGACAMQAEAYAagFQAMgCAFgJIgIgFQgEAFgGACQgLACgDgKIAcgGQACgDgBgFQgDgQgOAAIgHABgAAXBoIgFABIACAJIAWgDIgBgIIgEAAIgBgJIACgCIANANIAFAEIAQgEIgBgJIgJABIgNgNIAFgKIAJgDIgBgJIgWAEIABAJIACAAIgDAGIgGAEIgDgRIgTADIABAJIAGgBgABaA4QgKACgFAHQgFAHACALQADAYAagEQAOgCAEgKIgHgFQgEAGgHACQgMABgDgPQgCgOAKgBQAEAAADACIACAHIAKgDIgDgRIgIABIgBADQgFgCgEAAIgCAAgADlAlIABAJIAFAAIAHAuIgGABIACAJIAXgEIAAgIIgGABIgCgPIABAAIADABQAFABAGgBQAKgCAFgHQAEgJgBgKQgDgWgVADQgHABgFADIgDADIAAAAIgBgDgAB2A1IABAJIAFAAIADAZIgFABIACAJIAXgDIAAgJIgGAAIgEgZIASgCIAFAiIASgEIAAgIIgGAAIgEgYIAFgCIgCgJgADKAnQgLABgGAIQgGAGACAMQAEAYAZgEQAOgCAEgJIgHgGQgEAGgHABQgMACgCgKIAdgFQACgEgBgEQgCgQgRAAIgFAAgAE2A7IgFACIACAJIAXgDIAAgJIgGAAIgDgZIAIgBIABAIIAKgBIgCgSIgJACIgpAFIAAAAIACASIAJgCIAAgIIAIgBgAF2A3IAFADQAHADALgCQAJAAAGgGQAGgFgBgHQgBgHgJgCQAGgFgBgFQgBgGgFgCQgFgDgIABQgFABgFAEIgBgDIgJABIACAQIAKgCIAAgFQACgCAFAAQAGgBABAEQAAAFgGACIgHABIABAIIAGgBQAKgBAAAEQABAGgKABQgGABgGgCIgEgCgAHBAGIAAAKIAFAAIADAYIgFABIACAJIAVgCIAAgIIgEAAIgBgJIASgDIACATIATgDIgBgJIgFAAIgDgYIAEgBIgBgKIgWADIABAHIAEABIABAIIgSADIgCgSgAIeAMIAAABQgNADgGADQgKAEABAIQABAOARgCQALgBADgHIACAFIAQgCIAAgIIgGAAIgCgTQgCgRgRACQgHAAgFAEIgCgCIgIABIABAPIAKgBIABgGQACgCAFgBIABAAQAHAAAAAIgAJKgJQgKABgGAHQgFAFABALQADAYAZgCQAOgBAEgKIgGgFQgFAGgGABQgNABgBgPQgCgOAKgBQAEAAADACIACAHIAKgBIgBgRIgJAAIgBAEQgEgDgFAAIgCAAgAJmgKIAAAJIAFAAIADAYIgGABIACAJIAXgCIAAgJIgFAAIgEgigAKEgNIABAJIAFAAIABAYIgFABIACAJIAWgBIAAgIIgEAAIgBgKIASgCIABASIATgCIAAgIIgGAAIgCgYIAFgBIgBgKIgWADIABAHIADAAIABAIIgSACIgBgQgALEgSIAAAJIAFAAIABAYIgFABIABAJIAWgCIAAgHIgEAAIAAgKIASgCIABATIATgBIAAgJIgGAAIgBgZIAEgBIAAgJIgWACIAAAHIAEAAIAAAJIgSACIgBgRgAMZgXQgWABABAPQAAAHAKAEIgEAIIgIAAIABAKIAPgBIADgEIAFgLIAHgBIABAPIATgBIAAgIIgFAAIgBgZIAEgBIgBgJgAhzhbQATA8AJAhQAVADASAAQAxAABCgXQgQgSgHgZQgIgXACgaIgYAGQgIACgIAAQgdAAgRgYQgKgMAEgPQADgQANgHQASgLAdAAIAhACIgChrIgQgCQgVgDgRAAQgRAAgVADQhNAJgyAoQhKA6AfBTIAIASIBfgSgAnJADIAHgCQAFgIAJgHIAQgLIABAAQgOANgLAMIAFgBQAKgKANgKIABABIgNAOIgDADIAFgBIAAAAIANgMIABABIgFAKIAJgCIABgDIACABIAGgCIgCgBIgLgLIgIgLIgEgGQgKgSgDgUIAAgDIAAgSQABgOACgIIABgDIAAgCIABgCQALgjAegVIALgHQANgIAOgDIACAAIAAgBQAbgGAcAHQAdAIATASIABABIADADIADgNQAEgMAGgMIACgJQAFgVADgEIAAgBIAEgEQgDgBgJAFIgSAMQgPAKgJAJQAFgMABgTQACgXgDgJIgBgHIgDAHQgGANgGAHQgEAEgMAIIgFADQgGADgDAGIgDgHIgIgQQgKgTAAgFIAAgBIAAgFIgCACQgCADgCAGIgHAUQgGATAAAOQgEgPgOgSQgPgUgJgHIgGgGIACAIQAFASAAAJQgBAIgFAOIgCAHQgCAHAAAGQgIgFgMgHIgTgJIgKgDIgCAAIAFAFQADADAHAVIAGAPQAEAKAFAGQgHgDgJgDIgQgDQgVgDgEgDIgBgBIgEgDIAAACIAEAJIAMASQAUAbANAFIABABIAAACQgPgDgSAEIgUAGQgZAIgHgBIAAAAIgIgCIACADIAKAIIAXAMQAjASASgBIAAABIgBAAQgNABgMAKIgOAKQgRAOgEABIgBAAIgFABIACACIAJADIAWACQAhACAMgHIACgBQgOAKgPAfgABqidQgYAGgOANQgQAQACAXIABAQQAHArAaAVQAUARAbAAQAgAAASgVIAFgFIACAPIBYgNIgYiRIhaAMIgCAFQgTgFgQAAQgLAAgMACgAl7i9QgnAWgMAsQgMAqAWAnQAKASAPAMIAGgBQgRgNgKgSQgVglALgpQAMgpAlgWQAlgVAqALQAgAJAUAYIABgFQgVgXgfgJQgPgEgPAAQgaAAgaAOgAJwgfQgJABABAGQAAAIAJgCQAIAAgBgHQgBgHgGAAIgBABgAmAggQgGAFAFAFQACABADAAQADAAACgCQAGgGgFgEQAAgBgBAAQAAgBgBAAQAAAAgBAAQAAgBgBAAQgDAAgDAEgAEXjEIAZCkIBGgIIgIg+IAdgDIAIA/IBTgIIgNilIgFgBQgOAAgcADQgeADgLACIAEA4IgaAAIgEg2gAlfghIABABIgDgHQAAADACADgAmTg5QgCACAAAEQgBACACACQAFAFAFgGQAGgFgFgFQAAgBgBAAQAAAAgBgBQAAAAgBAAQAAAAgBAAQgDAAgDADgAlwg7QgDACAAACQAAAEACACQACACADgBQADAAACgCIABgCIgBgDIADgBQAAgCgCgCQgBgBAAAAQgBgBAAAAQgBAAAAAAQgBgBAAAAQgDAAgDAEgAHsjZIATClIBGgFQATgvAQgkIAGBQIBIgEIgIilQgDgBgeABQggABgNADQgNAfgTAnIgEhEgAMehBIBGAAIAOjHIhGAGIgJBTQgFAEgIAAIgIAAQgCgJABgNIADgUIAGgtIhJAHIgCANQgCANgBApQgCAZAFALQADAIAKAHQARAJASAAQATAAATgNgAmAhTQgFAGAEAEQAFAFAGgGQAFgFgEgFQgBAAAAAAQgBgBAAAAQgBAAAAgBQgBAAAAAAQgDAAgEADgAmghXQgFAGAEAEQACADADgBQADgBACgCQAGgFgFgFQAAgBgBAAQAAAAgBgBQAAAAgBAAQAAAAgBAAQgDAAgDADgAmBhtQgGAGAFAFQAEAEAGgGQAGgFgFgFQgCgCgCAAQgDAAgDADgAkWh0QgFAFAEAFQACACADAAQADgBACgCQAGgFgFgFQAAgBgBAAQAAAAgBgBQAAAAgBAAQAAAAgBAAQgDAAgDADgAmbh5QgGAFAFAFQAFAFAFgGQADgCAAgEQAAgDgCgBQAAgBgBAAQAAgBgBAAQAAAAgBAAQAAgBgBAAQgDAAgDAEgAj7iDQgGAGAEAEQAFAEAFgEIgDgNIAAAAQgCAAgDADgAl1iKQgGAGAFAEQACADADgBQADAAACgDQAGgFgFgFQgBAAAAAAQgBgBAAAAQgBAAAAAAQgBgBAAAAQgDAAgDADgAkkiLQgGAGAFAEQAEAFAGgGQAGgFgFgFQgCgCgCAAQgDAAgDADgAk8iZQgCADAAADQgBADACACQAFAEAGgFQAFgGgEgFQgCgCgDAAQgDAAgDADgAmMiZQgFAGAEAFQAFAEAGgGQAFgFgEgFQgBAAAAAAQgBgBAAAAQgBAAAAAAQgBgBAAAAQgDAAgEADgAkLiaQgGAFAFAFQAEAFAGgGQAGgGgFgEQgBgBAAAAQgBAAAAgBQgBAAAAAAQgBAAAAAAQgDAAgDADgAlZibQgGAFAFAFQACACADAAQADAAACgDQAGgFgFgFQgBgBAAAAQgBAAAAgBQgBAAAAAAQgBAAAAAAQgDAAgDADgAkmiuQgGAGAFAEQAEAFAGgGQACgCABgDQAAgDgCgCQgCgCgCAAQgDAAgDADgAlviwQgCADAAACQgBAEACABQACADADgBQAEAAACgCQAFgGgEgFQgBgBAAAAQgBAAAAgBQgBAAAAAAQgBAAAAAAQgDAAgEADgAlCi6QgDAAgDACQgCADAAADQgBADACACQAFAEAGgFQAFgGgEgEQAAgBgBAAQAAAAgBgBQAAAAgBAAQAAAAgBAAIgBAAgAnGB0QgGgLAFgOQAEgOASAAIAIAAIAJArQgKAKgKABQgMgBgGgOgAgMBTQAJgCABAIIAAACIgTADQAAgKAJgBgAD+BEIgCgBIgDgVIACgDQADgDAEAAQAGgBADACQADACABAIQADAQgMABIgDABIgFgBgADLAwQAJgCABAJIAAACIgTACQAAgLAJAAgAIQAdQgBgFAQgDIABAIQgCAFgGAAIgBAAQgHAAAAgFgAMRgIQAAgFAKgBIAFAAIABAMIgHAAIgCABQgHAAAAgHgAnagkIgSgCQAaABAegKIAAABIgPAHQgIADgKAAIgFAAgAmsgmIgBgCIAAgBIABADIABAAgAnugoIACAAIAngJIAPgDIAAACQgdALgWAAIgFgBgAniguIARgIQAMgDANABIAAABIgOAEIghAIgAnTg8QAGgFAIgCIAKgBIABAHQgKAAgOAEQgHADgKAGIgJAFgACchDQgIgGgCgJQgDgJAFgIQAFgIALAAQAGAAAFACIAHAjQgHAFgKAAQgFABgEgDgAnqhhIgTgMQAXALAsAFIAAABIgUABQgPAAgNgGgAoAhvIADAAIAwAIIATADIAAADQgqAAgcgOgAnMhpIgqgHIAHAAQAKgCANABQAPABAPAHIAAACQgJAAgJgCgAnYh2QgKAAgOADIgLABIAQgEIAVgEQAIgCAKACIAMACIgBAIQgOgFgRgBgAnAiVQgLgHgHgJIgKgPQASAXAZANIgBABIgOgGgAnDifQgQgMgKgMIADABIArAiIAAAAQgIgEgMgHgAnVi0IAFADQAIACAJAFQAMAIAGAJIAAACgAm9itQgFgDgNgEIgJgEIAdAIQAHACAHAFIAIAHIgFAFQgGgIgNgIgAmmi1QgGgGgCgGIgMgcIAEAIQAGAMAEAFQAIAJALAIIgFAFIgIgHgAmpjGQgHgJgEgHIgCgFIAiAjIgBABQgLgFgJgKgAj+i7IgBgCQAHgGAJgNQAEgFAEgMIAEgJIgEANIgFARQgCAGgFAGIgHAIIgEgDgAm5jfIgCgDQAWAMAUAcIgBABgAm4jiIARAIQAKAGAIAKIAIANIAAAAQgXgZgUgMgAkFjAIAJgMIAVgbIgCAFIgJARQgGAKgMAHgAmJjKQgFgKADgKIADgHQAFgQgBgLQACAKgCAJIgCATQACAPAFAIIgDACQgCgEgFgFgAkJjCQASgeATgOIgBACIgjAqgAkNjFIAHgOQAGgLAKgGIAPgKQgVAQgQAagAmAjbIgBgSQABgKgCgIQAHAZAEAeIgCABQgFgHgCgNgAmGkMIgBgEIAEAFQAXAuAAARIgEABQgLgpgLgYgAkkjRQAQghAFgXIACgDIAAAFQgLAtgJAKgAkNkBQgCAhgMAQQAIgLAGgmgAmAkHQAYAfAAAXQgCgQgWgmgAksjTIABgFQABgGAEgHIAJgMQAFgEAFgJQgJAVgPAWgAk2jUIAAgJIAAgCQACgJAJgFIAFgDQANgIAFgIQgEAHgHAGIgMANQgEAGgEAMgAlYjlQgCgLAEgMIAFgRQgGAcAEAcIgBABIgEgRgAlPkQIABAEIAAA2IgCABQgFgkAGgXgAlLjWIgCgxIACAFQADAJABAKQABAMgEANgAlEjXQACgKgCgPQAAgGgFgNIgDgJIAMAcQADAHAAAIIAAADIgCAHg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.logo, new cjs.Rectangle(-113.9,-44.8,227.8,89.6), null);


(lib.img4_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.img4();
	this.instance.parent = this;
	this.instance.setTransform(-150,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.img4_1, new cjs.Rectangle(-150,-300,300,600), null);


(lib.img3_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.img3();
	this.instance.parent = this;
	this.instance.setTransform(-150,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.img3_1, new cjs.Rectangle(-150,-300,300,600), null);


(lib.img2_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.img2();
	this.instance.parent = this;
	this.instance.setTransform(-150,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.img2_1, new cjs.Rectangle(-150,-300,300,600), null);


(lib.img1_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.img1();
	this.instance.parent = this;
	this.instance.setTransform(-150,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.img1_1, new cjs.Rectangle(-150,-300,300,600), null);


(lib.btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_16
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ADQBnIAAgYIAMAAIAAhwIgMAAIAAgXIAuAAIAAASQANgTAVAAQATAAAMAPQAMARAAAYQAAAYgPAQQgQAPgXAAQgMAAgLgDIAAAcIANAAIAAAYgAEFgZQgHAGAAAIIAAAlQALADAIAAQALAAAGgJQAHgIAAgNQAAgNgGgIQgHgJgKAAQgIAAgFAGgAJHAoQgRgQAAgZQAAgZARgQQAQgQAaAAQAaAAAQAQQARAQAAAZQAAAZgRAQQgQAPgaAAQgbAAgPgPgAJfgXQgHAKAAAMQAAAMAHAJQAHAJALAAQALAAAGgJQAIgIgBgNQABgNgIgJQgGgJgLAAQgLAAgHAJgAHaAoQgRgRABgYQgBgZARgQQARgQAZAAQAYAAARALIAAAcIgcAAIAAgNIgKAAQgNAAgHAJQgIAJABANQgBAOAIAHQAHAJANAAQAOAAAHgHIASARQgPAQgcAAQgaAAgPgPgAFlAoQgRgQAAgZQAAgZAPgQQAQgQAYAAQAYAAAPAQQAPAQAAAaIAAAJIhLAAQACAJAIAGQAIAGALgBQAQABAHgJIATATQgQAPgdAAQgbAAgQgPgAGfgMQAAgIgGgGQgGgGgHAAQgIAAgGAFQgGAHgBAIIAoAAIAAAAgAgFAoQgPgRAAgYQAAgZAQgQQAPgQAaAAQAXAAASALIAAAcIgdAAIAAgNIgKAAQgMAAgHAJQgIAJAAANQAAAOAIAHQAHAJAMAAQAPAAAIgHIASARQgQAQgcAAQgZAAgQgPgAtfAhIASgSQANAMAbAAQALAAAGgGQAHgFAAgJQAAgHgGgGQgGgEgIAAIgbAAIAAgdIAWAAQAIAAAEgFQAEgEAAgHQAAgJgFgEQgFgFgJAAQgHAAgKABIAAASIgeAAIAAgiQAUgOAfAAQAXAAAPAMQAOALAAASQAAAYgPAKQALAEAHALQAHALAAANQAAATgRAMQgRAMgcAAQgjAAgXgWgAoYAtQgLgJAAgPQAAgRAPgIQAOgLAYAAIAQAAIAAgCQAAgGgFgFQgFgEgHAAQgKAAgIADIAAAKIgdAAIAAgbQATgLAaAAQAXAAAPALQAPALAAARIAAAwIANAAIAAAXIgvAAIAAgNQgMAPgUgBQgQAAgKgJgAn6AHQgGAEAAAHQAAAFADADQAFADAGAAQAJAAAFgGQAGgJAAgJIgMgCQgJAAgHAEgArTAtQgKgJAAgPQAAgRAOgIQAPgLAWAAIARAAIAAgCQABgGgGgFQgFgEgIAAQgJAAgIADIAAAKIgdAAIAAgbQAUgLAZAAQAYAAAOALQAPALABARIAAAwIALAAIAAAXIguAAIAAgNQgMAPgTgBQgRAAgKgJgAq1AHQgGAEgBAHQABAFAEADQADADAIAAQAIAAAFgGQAHgIgBgKIgLgCQgKAAgHAEgAMkA1IAAgXIAOAAIgDgmIgcA9IgVAAIgcg9IgCAmIANAAIAAAXIg7AAIAAgXIANAAIAFg/IgLAAIAAgXIA0AAIAcA5IAbg5IA0AAIAAAXIgKAAIAFA/IANAAIAAAXgABzA1IAAgXIAMAAIAAg8IgIAAIAAAMIgcAAIAAgmIBqAAIAAAmIgcAAIAAgMIgIAAIAAA8IAMAAIAAAXgAhXA1IAAgXIANAAIAAgmIgqA9IgtAAIAAgXIALAAIAAg/IgLAAIAAgXIA6AAIAAAXIgNAAIAAAmIAqg9IAuAAIAAAXIgNAAIAAA/IANAAIAAAXgAkAA1IAAgXIANAAIAAg8IgIAAIAAAMIgcAAIAAgmIBqAAIAAAmIgdAAIAAgMIgHAAIAAA8IAMAAIAAAXgAleA1IAAgXIANAAIAAgUIgoAAIAAAUIAMAAIAAAXIg6AAIAAgXIAMAAIAAg/IgMAAIAAgXIA6AAIAAAXIgMAAIAAASIAoAAIAAgSIgNAAIAAgXIA7AAIAAAXIgMAAIAAA/IAMAAIAAAXg");
	this.shape.setTransform(0,0.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(2));

	// Слой_17
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#D53335").s().p("AvnD6IAAnzIfPAAIAAHzg");
	this.shape_1.setTransform(0,-2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#B82929").s().p("AvnAUIAAgnIfPAAIAAAng");
	this.shape_2.setTransform(0,25);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#2A8929").s().p("AvnAUIAAgnIfPAAIAAAng");
	this.shape_3.setTransform(0,25);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#2AAC20").s().p("AvnD6IAAnzIfPAAIAAHzg");
	this.shape_4.setTransform(0,-2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1}]}).to({state:[{t:this.shape_4},{t:this.shape_3}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-100,-27,200,54);


(lib.box2_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.box2();
	this.instance.parent = this;
	this.instance.setTransform(-91,-107);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.box2_1, new cjs.Rectangle(-91,-107,182,214), null);


(lib.box1_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.box1();
	this.instance.parent = this;
	this.instance.setTransform(-101,-115);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.box1_1, new cjs.Rectangle(-101,-115,202,230), null);


(lib.banner = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// plashka
	this.instance = new lib.plashka_1();
	this.instance.parent = this;
	this.instance.setTransform(0.1,-469.9,1,1,30,0,0,0,-85);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(210).to({_off:false},0).to({rotation:0,x:0,y:-340},15,cjs.Ease.cubicOut).wait(40).to({y:-470},15,cjs.Ease.cubicIn).wait(1));

	// btn
	this.instance_1 = new lib.btn("single",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(0,219.2,0.01,0.01);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(210).to({_off:false},0).to({scaleX:1,scaleY:1},15,cjs.Ease.backOut).wait(14).to({scaleX:0.96,scaleY:0.96,startPosition:1},0).wait(2).to({scaleX:1,scaleY:1},0).wait(24).to({startPosition:1},0).to({y:445.2},15,cjs.Ease.cubicIn).wait(1));

	// t4
	this.instance_2 = new lib.t4();
	this.instance_2.parent = this;
	this.instance_2.setTransform(0,341.3,0.938,0.938);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(195).to({_off:false},0).to({y:113.5},15,cjs.Ease.cubicOut).wait(55).to({y:342.3},15,cjs.Ease.cubicIn).wait(1));

	// box1
	this.instance_3 = new lib.box1_1();
	this.instance_3.parent = this;
	this.instance_3.setTransform(-286,11,1,1,-49.5);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(195).to({_off:false},0).to({rotation:0,x:-56},15,cjs.Ease.cubicOut).wait(55).to({rotation:-49.5,x:-286},15,cjs.Ease.cubicIn).wait(1));

	// box2
	this.instance_4 = new lib.box2_1();
	this.instance_4.parent = this;
	this.instance_4.setTransform(280,9,1,1,60);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(195).to({_off:false},0).to({rotation:0,x:68},15,cjs.Ease.cubicOut).wait(55).to({rotation:60,x:280},15,cjs.Ease.cubicIn).wait(1));

	// img4
	this.instance_5 = new lib.img4_1();
	this.instance_5.parent = this;
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(180).to({_off:false},0).to({alpha:1},15).wait(70).to({alpha:0},15).wait(1));

	// logo
	this.instance_6 = new lib.logo();
	this.instance_6.parent = this;
	this.instance_6.setTransform(-81,-262.2,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(281));

	// t3
	this.instance_7 = new lib.t3();
	this.instance_7.parent = this;
	this.instance_7.setTransform(0,355.3,0.938,0.938);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(130).to({_off:false},0).to({y:211},15,cjs.Ease.cubicOut).to({_off:true},50).wait(86));

	// img3
	this.instance_8 = new lib.img3_1();
	this.instance_8.parent = this;
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(115).to({_off:false},0).to({alpha:1},15).to({_off:true},65).wait(86));

	// t2
	this.instance_9 = new lib.t2();
	this.instance_9.parent = this;
	this.instance_9.setTransform(0,355.3,0.938,0.938);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(65).to({_off:false},0).to({y:211},15,cjs.Ease.cubicOut).to({_off:true},50).wait(151));

	// img2
	this.instance_10 = new lib.img2_1();
	this.instance_10.parent = this;
	this.instance_10.alpha = 0;
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(50).to({_off:false},0).to({alpha:1},15).to({_off:true},65).wait(151));

	// t1
	this.instance_11 = new lib.t1();
	this.instance_11.parent = this;
	this.instance_11.setTransform(0,355.3,0.938,0.938);

	this.timeline.addTween(cjs.Tween.get(this.instance_11).to({y:211},15,cjs.Ease.cubicOut).to({_off:true},51).wait(215));

	// img1
	this.instance_12 = new lib.img1_1();
	this.instance_12.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(281));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,-300,300,692.8);


// stage content:
(lib._300x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// banner
	this.instance = new lib.banner();
	this.instance.parent = this;
	this.instance.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(150,300,300,692.8);
// library properties:
lib.properties = {
	id: '0A6E3F5DF6B342F4AF907DBE848CDF8D',
	width: 300,
	height: 600,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/billet.png", id:"billet"},
		{src:"images/box1.png", id:"box1"},
		{src:"images/box2.png", id:"box2"},
		{src:"images/img1.jpg", id:"img1"},
		{src:"images/img2.jpg", id:"img2"},
		{src:"images/img3.jpg", id:"img3"},
		{src:"images/img4.jpg", id:"img4"},
		{src:"images/plashka.png", id:"plashka"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['0A6E3F5DF6B342F4AF907DBE848CDF8D'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;