(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.bgImg = function() {
	this.initialize(img.bgImg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,355);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.urText = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1,2).p("A02i4MAptAAAIAAFxMgptAAAg");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Aq7BoIAAhEIAFAAIAAAMQAIgNANAAQAJABAIAGQAHAIAAAMQAAAMgHAIQgIAHgJAAQgOAAgHgMIAAAbgAqwAuQgHAHAAAJQAAAKAHAGQAGAGAIAAQAJAAAFgGQAGgGAAgKQAAgKgGgGQgGgGgIAAQgIAAgGAGgAxLBoIAAhEIAFAAIAAAMQAIgNANAAQAJABAIAGQAHAIAAAMQAAAMgHAIQgIAHgJAAQgOAAgHgMIAAAbgAxAAuQgHAHAAAJQAAAKAHAGQAGAGAIAAQAJAAAFgGQAGgGAAgKQAAgKgGgGQgGgGgIAAQgIAAgGAGgAEvBmIAAgPIguAAIgBAPIgEAAIAAgSIAHAAQAHgNAAgXIAAgMIAiAAIAAAwIAIAAIgBASgAEPAzQAAAVgHAMIAfAAIAAgrIgYAAgAyYBmIAAgPIguAAIgBAPIgEAAIAAgSIAHAAQAHgNAAgXIAAgMIAiAAIAAAwIAIAAIgBASgAy4AzQAAAVgHAMIAfAAIAAgrIgYAAgAS/BRQgIgHAAgNQAAgQADgHQAEgLAMgDIAdgIIABAFIgcAIQgOADgCARQAHgNAPAAQAKABAIAHQAHAIAAAKQAAALgIAIQgHAIgLAAQgLAAgHgIgATDAwQgGAGAAAIQAAAJAGAHQAGAGAIABQAJgBAGgGQAGgHAAgJQAAgIgGgGQgGgHgJAAQgJAAgFAHgARuBRQgIgIAAgLQAAgLAIgIQAHgHALgBQAMAAAJAKIgEAEQgIgJgJAAQgIAAgGAHQgGAGAAAJQAAAJAGAHQAGAGAJABQAJgBAHgIIAEADQgKAKgLAAQgLAAgHgIgAQyBRQgIgIAAgLQAAgKAIgJQAHgHAMgBQALABAHAHQAIAIAAALQAAALgIAIQgHAIgMAAQgLAAgHgIgAQ2AvQgGAGAAAJQAAAJAGAHQAGAGAJABQAIgBAGgGQAGgHAAgJQAAgJgGgGQgGgHgJAAQgIAAgGAHgALKBRQgIgIAAgLQAAgKAIgJQAHgHAMgBQALABAHAHQAIAIAAALQAAALgIAIQgHAIgMAAQgLAAgHgIgALOAvQgGAGAAAJQAAAJAGAHQAGAGAJABQAIgBAGgGQAGgHAAgJQAAgJgGgGQgGgHgJAAQgIAAgGAHgAIWBRQgIgIAAgLQAAgKAIgJQAHgHAMgBQALABAHAHQAIAIAAALQAAALgIAIQgHAIgMAAQgLAAgHgIgAIaAvQgGAGAAAJQAAAJAGAHQAGAGAJABQAIgBAGgGQAGgHAAgJQAAgJgGgGQgGgHgJAAQgIAAgGAHgAlPBRQgIgHAAgMQAAgLAHgIQAHgHAKgBQALAAAGAIQAHAHAAAMIAAACIgrAAQABAJAGAGQAFAFAIABQALgBAHgHIADACQgIAKgNAAQgKAAgHgIgAlMAtQgFAHgBAIIAmAAQgCgUgRAAQgHAAgGAFgAnJBVQgGgEAAgJQAAgHAGgFQAGgEAKAAQAIAAAJADIAAgDQAAgPgRAAQgIAAgIADIgCgDQAJgFAJAAQALAAAFAFQAGAGAAAJIAAAfIgFAAIAAgIQgHAKgNAAQgIAAgFgEgAnKBIQAAAMAPABQAHgBAGgEQAGgFAAgHIAAgFQgHgCgKgBQgRABAAALgAwBBRQgIgIAAgLQAAgKAIgJQAHgHAMgBQALABAHAHQAIAIAAALQAAALgIAIQgHAIgMAAQgLAAgHgIgAv9AvQgGAGAAAJQAAAJAGAHQAGAGAJABQAIgBAGgGQAGgHAAgJQAAgJgGgGQgGgHgJAAQgIAAgGAHgAyDBRQgIgIAAgLQAAgKAIgJQAHgHAMgBQALABAHAHQAIAIAAALQAAALgIAIQgHAIgMAAQgLAAgHgIgAx/AvQgGAGAAAJQAAAJAGAHQAGAGAJABQAIgBAGgGQAGgHAAgJQAAgJgGgGQgGgHgJAAQgIAAgGAHgAL5BXIABgEIAEABQAGAAACgHQADgJAAgcIAAgEIAjAAIAAAzIgFAAIAAguIgZAAIAAABQAAAegEAJQgDAIgJgBgAE3BXIABgEIAEABQAGAAACgHQADgJAAgcIAAgEIAjAAIAAAzIgFAAIAAguIgZAAIAAABQAAAegEAJQgDAIgJgBgAgIBXIABgEIAEABQAFAAACgHQADgJAAgcIAAgEIAjAAIAAAzIgFAAIAAguIgZAAIAAABQAAAegEAJQgDAIgIgBgAo+BRIADgEQAIAHAKAAQAFAAAEgDQAEgDAAgEQAAgKgOAAIgHAAIAAgEIAHAAQANAAAAgKQAAgKgMABQgJAAgHAEIgDgEQAIgFALAAQARAAAAAOQAAAIgIADQAKADAAAKQAAAGgFAEQgGAFgIgBQgLAAgKgHgAz6BRIADgEQAIAHAKAAQAFAAAEgDQAEgDAAgEQAAgKgOAAIgHAAIAAgEIAHAAQANAAAAgKQAAgKgMABQgJAAgHAEIgDgEQAIgFALAAQARAAAAAOQAAAIgIADQAKADAAAKQAAAGgFAEQgGAFgIgBQgLAAgKgHgAT1BXIAAgIIAGAAIAAAIgASmBXIAAgzIAFAAIAAAzgAP5BXIgSgWIgSAWIgGAAIAVgaIgUgZIAGAAIARAXIARgXIAGAAIgUAZIAVAagAPABXIAAgzIAFAAIAAAzgAOrBXIAAgXIgiAAIAAAXIgFAAIAAgzIAFAAIAAAYIAiAAIAAgYIAEAAIAAAzgANfBXIAAguIgUAAIAAgFIAsAAIAAAFIgUAAIAAAugAM+BXIAAgzIAFAAIAAAzgAKxBXIAAgXIgiAAIAAAXIgFAAIAAgzIAFAAIAAAYIAiAAIAAgYIAEAAIAAAzgAJOBXIAAgzIAXAAQAIAAAEAEQAFAEAAAGQAAAIgJADQALACAAALQAAANgSAAgAJTBUIATAAQANAAAAgLQAAgKgPAAIgRAAgAJTA8IARAAQANAAAAgKQAAgJgMAAIgSAAgAH7BXIAAguIggAAIAAAuIgFAAIAAgzIAqAAIAAAzgAGeBXIAAgTIgRAAIgPATIgGAAIAQgTQgPgDAAgNQAAgHAFgEQAFgFAJAAIAXAAIAAAzgAF+A0QAAAMAPgBIARAAIAAgWIgSAAQgOAAAAALgADRBXIAAgsIgiAsIgFAAIAAgzIAFAAIAAAtIAigtIAFAAIAAAzgACTBXIgUgYIgMANIAAALIgFAAIAAgzIAFAAIAAAhIAfghIAHAAIgXAYIAXAbgAA8BXIAAgzIAFAAIAAAVIAPAAQATAAAAAOQAAAIgFAEQgFAEgIAAgABBBUIAPAAQAOAAAAgNQAAgKgOgBIgPAAgAgTBXIAAgzIAFAAIAAAzgAg4BXIAAguIgUAAIAAgFIAsAAIAAAFIgUAAIAAAugAh4BXIAAgsIgiAsIgFAAIAAgzIAFAAIAAAtIAigtIAFAAIAAAzgAi0BXIAAgsIgiAsIgFAAIAAgzIAFAAIAAAtIAigtIAFAAIAAAzgAjwBXIAAgXIgiAAIAAAXIgFAAIAAgzIAFAAIAAAYIAiAAIAAgYIAEAAIAAAzgAlvBXIAAgVQgKAEgIAAQgRAAAAgOIAAgUIAFAAIAAAUQAAAKAMAAQAKAAAIgGIAAgYIAFAAIAAAzgAngBXIAAgXIgiAAIAAAXIgFAAIAAgzIAFAAIAAAYIAiAAIAAgYIAEAAIAAAzgApOBXIAAgsIgiAsIgFAAIAAgzIAFAAIAAAtIAigtIAFAAIAAAzgArZBXIAAhAIgsAAIAABAIgFAAIAAhGIA2AAIAABGgAs+BXIAAgIIAGAAIAAAIgAtXBXIAAgTIgRAAIgPATIgGAAIAQgTQgPgDAAgNQAAgHAFgEQAFgFAJAAIAXAAIAAAzgAt3A0QAAAMAPgBIARAAIAAgWIgSAAQgOAAAAALgAvJBXIAAgzIAXAAQAIAAAEAEQAFAEAAAGQAAAIgJADQALACAAALQAAANgSAAgAvEBUIATAAQANAAAAgLQAAgKgPAAIgRAAgAvEA8IARAAQANAAAAgKQAAgJgMAAIgSAAgAuRAiQAGgCAAgFIAAgBIgDAAIAAgJIAHAAIAAAIQAAAIgJAEgAiXARIAFgBQABAHAIAAQAIAAABgHIAEABQgCAMgLAAQgLAAgDgMgASmAXIAAgHIAGAAIAAAHgAPAAXIAAgHIAGAAIAAAHgAM+AXIAAgHIAGAAIAAAHgAgTAXIAAgHIAGAAIAAAHgAHrgRIACgEQADABAFAAQAIABAFgMIgZg0IAGAAIAVAuIATguIAFAAIgWA1QgGAPgLAAQgGAAgEgCgAKZgPIAAhEIAFAAIAAAMQAIgNANAAQAJAAAIAIQAHAHAAAMQAAAMgHAIQgIAHgJAAQgOAAgHgMIAAAbgAKkhJQgHAHAAAJQAAAKAHAGQAGAGAIAAQAJAAAFgFQAGgHAAgKQAAgJgGgHQgGgGgIAAQgIAAgGAGgAvOgPIAAhEIAFAAIAAAMQAIgNANAAQAJAAAIAIQAHAHAAAMQAAAMgHAIQgIAHgJAAQgOAAgHgMIAAAbgAvDhJQgHAHAAAJQAAAKAHAGQAGAGAIAAQAJAAAFgFQAGgHAAgKQAAgJgGgHQgGgGgIAAQgIAAgGAGgARKgRIAAgOIguAAIgBAOIgEAAIAAgTIAHAAQAHgMAAgYIAAgLIAiAAIAAAvIAIAAIgBATgAQqhEQAAAUgHAMIAfAAIAAgqIgYAAgAl7gmQgJAIgNAAQgQAAgKgLQgJgLAAgOQAAgPAJgLQALgLAPABQAQgBAKALQAJALAAAPQAAAOgJALIAKAIIgEAEgAmmhZQgJAKAAANQAAANAJAJQAIAJANAAQALAAAIgGIgOgMIAEgEIANAMQAIgJAAgMQAAgNgJgKQgIgJgNAAQgNAAgIAJgAIvgmQgIgIAAgLQAAgLAIgHQAHgJALAAQAMAAAJAKIgEADQgIgIgJAAQgIAAgGAGQgGAHAAAJQAAAKAGAGQAGAHAJgBQAJAAAHgJIAEAEQgKAKgLAAQgLAAgHgIgAGZgmQgIgIAAgLQAAgLAIgHQAHgJALAAQAMAAAIAKIgDADQgIgIgJAAQgIAAgGAFQgFAHgBAIIAaAAIAAAEIgaAAQAAAIAGAHQAGAFAJAAQAJAAAHgJIAEAEQgIAKgNAAQgKAAgIgIgAFbgiQgGgEAAgJQAAgHAGgEQAGgFAKAAQAIAAAJADIAAgDQAAgPgRAAQgIAAgIADIgCgDQAJgFAJAAQALAAAFAGQAGAFAAAJIAAAgIgFAAIAAgJQgHAKgNAAQgIAAgFgEgAFagvQAAAMAPAAQAHABAGgFQAGgFAAgGIAAgGQgHgDgKABQgRgBAAAMgADlglQgGgHgBgLIgMAAIAAAYIgFAAIAAg0IAFAAIAAAYIAMAAQABgLAHgGQAHgIAKAAQALAAAHAJQAHAHAAALQAAALgHAIQgHAIgLAAQgLAAgHgHgADphJQgFAHAAAJQAAAKAFAGQAFAHAJgBQAJABAFgHQAFgGAAgKQAAgJgFgHQgFgGgJAAQgJAAgFAGgAh4gmQgIgHAAgMQAAgLAHgHQAHgJAKAAQALABAGAHQAHAIAAALIAAACIgrAAQABAJAGAGQAFAGAIgBQALAAAHgHIADADQgIAJgNAAQgKAAgHgIgAh1hKQgFAHgBAIIAmAAQgCgUgRAAQgHAAgGAFgAlbgpQgJgLAAgOQAAgPAJgLQALgLAPABQAQgBAKALQAJALAAAPQAAAOgJALQgLALgPAAQgQAAgKgLgAlWhZQgJAKAAANQAAANAJAJQAIAJANAAQANAAAIgJQAJgJAAgNQAAgNgJgKQgIgJgNAAQgNAAgIAJgArcgiQgGgEAAgJQAAgHAGgEQAGgFAKAAQAIAAAJADIAAgDQAAgPgRAAQgIAAgIADIgCgDQAJgFAJAAQALAAAFAGQAGAFAAAJIAAAgIgFAAIAAgJQgHAKgNAAQgIAAgFgEgArdgvQAAAMAPAAQAHABAGgFQAGgFAAgGIAAgGQgHgDgKABQgRgBAAAMgAtIgmQgIgIAAgLQAAgLAIgHQAHgJALAAQAMAAAJAKIgEADQgIgIgJAAQgIAAgGAGQgGAHAAAJQAAAKAGAGQAGAHAJgBQAJAAAHgJIAEAEQgKAKgLAAQgLAAgHgIgAwGgmQgIgIAAgLQAAgLAIgHQAHgJAMAAQALAAAHAJQAIAHAAALQAAALgIAIQgHAIgMAAQgLAAgHgIgAwChJQgGAHAAAJQAAAKAGAGQAGAHAJgBQAIABAGgHQAGgGAAgKQAAgJgGgHQgGgGgJAAQgIAAgGAGgARSgfIABgFIAEABQAGAAACgGQADgKAAgdIAAgDIAjAAIAAA0IgFAAIAAgvIgZAAIAAACQAAAcgEAKQgDAIgJAAgAMWgmIADgEQAIAHAKAAQAFAAAEgDQAEgDAAgFQAAgJgOAAIgHAAIAAgEIAHAAQANgBAAgJQAAgJgMAAQgJAAgHAEIgDgDQAIgGALAAQARAAAAAOQAAAIgIADQAKAEAAAIQAAAHgFAEQgGAEgIABQgLgBgKgHgACIgfIABgFIAEABQAGAAACgGQADgKAAgdIAAgDIAjAAIAAA0IgFAAIAAgvIgZAAIAAACQAAAcgEAKQgDAIgJAAgAkWgpIAEgFQALALAOAAQAIAAAFgEQAFgEAAgGQAAgLgUgEQgNgDgFgEQgGgEAAgJQAAgIAHgFQAGgFAKAAQANAAALAIIgEAEQgIgHgNgBQgHABgFAEQgFADAAAGQAAALAVAEQAXAFAAAPQAAAIgHAFQgGAGgKAAQgQgBgNgKgAS5gfIAAgUIgRAAIgPAUIgGAAIAQgUQgPgDAAgNQAAgHAFgEQAFgEAJgBIAXAAIAAA0gASZhDQAAALAPAAIARAAIAAgWIgSAAQgOAAAAALgAPsgfIAAgtIgiAtIgFAAIAAg0IAFAAIAAAtIAigtIAFAAIAAA0gAOugfIgUgZIgMAMIAAANIgFAAIAAg0IAFAAIAAAiIAfgiIAHAAIgXAYIAXAcgAN0gfIAAgtIgiAtIgFAAIAAg0IAFAAIAAAtIAigtIAFAAIAAA0gAMGgfIAAgtIgiAtIgFAAIAAg0IAFAAIAAAtIAigtIAFAAIAAA0gAJngfIAAg0IAFAAIAAA0gAE9gfIAAgXQgKAGgIAAQgRAAAAgPIAAgUIAFAAIAAAUQAAAKAMAAQAKAAAIgFIAAgZIAFAAIAAA0gAB6gfIgUgZIgMAMIAAANIgFAAIAAg0IAFAAIAAAiIAfgiIAHAAIgXAYIAXAcgABAgfIAAgtIgiAtIgFAAIAAg0IAFAAIAAAtIAigtIAFAAIAAA0gAgigfIAAg0IAXAAQAIABADADQAFADAAAHQAAAIgIADQAKADAAAKQAAAOgRAAgAgdgkIATAAQAMAAAAgKQAAgKgOAAIgRAAgAgdg7IARAAQAMgBAAgJQAAgJgLAAIgSAAgAiRgfIAAgYIgiAAIAAAYIgFAAIAAg0IAFAAIAAAYIAiAAIAAgYIAEAAIAAA0gAnOgfIAAhHIAFAAIAABHgAoIgfIAAgUIgRAAIgPAUIgGAAIAQgUQgPgDAAgNQAAgHAFgEQAFgEAJgBIAXAAIAAA0gAoohDQAAALAPAAIARAAIAAgWIgSAAQgOAAAAALgAo/gfIAAgYIgiAAIAAAYIgFAAIAAg0IAFAAIAAAYIAiAAIAAgYIAEAAIAAA0gAp7gfIAAgYIgiAAIAAAYIgFAAIAAg0IAFAAIAAAYIAiAAIAAgYIAEAAIAAA0gAsDgfIAAgvIgUAAIAAgFIAsAAIAAAFIgUAAIAAAvgAthgfIAAgtIgiAtIgFAAIAAg0IAFAAIAAAtIAigtIAFAAIAAA0gAwXgfIgUgZIgMAMIAAANIgFAAIAAg0IAFAAIAAAiIAfgiIAHAAIgXAYIAXAcgAxRgfIAAgtIgiAtIgFAAIAAg0IAFAAIAAAtIAigtIAFAAIAAA0gAy9gfIAAhHIAdAAQAKAAAGAGQAGAEAAAIQAAAMgLAFQAPAEAAANQAAAIgHAFQgGAGgMAAgAy4gkIAZAAQAJAAAGgEQAFgEAAgGQAAgOgVAAIgYAAgAy4hFIAXAAQASAAAAgPQAAgMgRAAIgYAAgAJnhfIAAgHIAGAAIAAAHg");
	this.shape_1.setTransform(-0.6,-0.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.urText, new cjs.Rectangle(-134.5,-19.5,269,39), null);


(lib.t1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Al7EsIAGgNQALAFAPAAQAMAAAIgIQAJgIAIgUIhJiYIARAAIBACJIA3iJIAQAAIhCCfQgKAXgNALQgLAJgRAAQgQAAgPgGgAq/EsIAFgNQALAFAPAAQAMAAAJgIQAJgIAIgUIhJiYIARAAIA/CJIA4iJIAQAAIhCCfQgKAXgNALQgMAJgQAAQgQAAgPgGgAt7ExIAAjJIAPAAIAAAjQAYgmAnAAQAdAAAVAVQAYAXAAAkQAAAkgYAXQgVAVgdAAQgoAAgXglIAABRgAtaCFQgTAUAAAcQAAAdATATQASASAZAAQAaAAARgRQARgTAAgeQAAgdgSgTQgRgSgZAAQgZAAgSASgAu1EtIAAgsIiMAAIgDAsIgMAAIAAg5IAUAAQAXglAAhGIAAghIBmAAIAACMIAZAAIgDA5gAwXCRQAAAegGAbQgGAbgJAPIBeAAIAAh+IhJAAgAJsDtQgdAYgnAAQgvAAgeghQgdgfAAgtQAAgsAdgfQAfghAuAAQAvAAAeAgQAdAfAAAtQAAAsgcAeIAeAaIgLAMgAHoBVQgZAbAAAoQAAAoAZAbQAaAcAmAAQAgAAAYgUIgpgjIALgMIApAlQAWgbAAgmQAAgngZgbQgagcgmAAQgnAAgZAbgALaDkQgdgfAAgtQAAgsAdgfQAeghAvAAQAuAAAeAgQAdAfAAAtQAAAtgdAfQgeAhgvAAQguAAgeghgALmBVQgZAbAAAoQAAAoAaAbQAZAcAnAAQAmAAAagcQAZgbAAgoQAAgngZgbQgagcgnAAQgmAAgaAbgABgD5QgRgNAAgYQAAgXASgNQASgNAeAAQAbAAAYAGIAAgGQAAgXgNgMQgNgMgYAAQgZAAgXAMIgGgNQAdgNAaAAQAfAAARARQAQAPAAAcIAABfIgPAAIAAgZQgUAdgmAAQgZAAgRgMgABrC6QgNAJAAARQAAARANAJQAMAJAUAAQAXAAARgNQARgNAAgVIAAgRQgZgHgaAAQgYAAgOAKgAO3DjIAKgMQASAQARAIQASAHAXAAQAXAAAPgMQAPgLAAgTQAAgSgMgJQgNgLgjgHQglgHgRgOQgQgOAAgYQAAgYATgQQATgQAdAAQAWAAASAHQAPAFARAOIgKAMQgcgYgjAAQgWAAgPAMQgOAMAAARQAAARAMAKQAOALAjAIQAlAHAQAOQAQAOAAAXQAAAZgTAQQgUAQgeAAQgwAAglghgAFuEBIAAjSIAQAAIAADSgAASEBIAAhHIhkAAIAABHIgPAAIAAiZIAPAAIAABEIBkAAIAAhEIAPAAIAACZgAoBEBIAAiZIBlAAIAAAOIhWAAIAACLgAjdgsIAAjJIAPAAIAAAjQAYgmAnAAQAdAAAVAVQAYAXAAAkQAAAkgYAXQgVAVgdAAQgoAAgXglIAABRgAi8jYQgTAUAAAcQAAAdATATQASASAZAAQAaAAARgRQARgTAAgeQAAgdgSgTQgRgSgZAAQgZAAgSASgAqZh5QgYgeAAguQAAgtAYgfQAZggAnAAQAnAAAYAgQAXAfAAAtQAAAtgXAfQgZAhgnAAQgnAAgYghgAqNkHQgTAcAAAmQAAAmATAcQAUAdAgAAQAfAAAUgdQATgbAAgnQAAgmgTgbQgUgdggAAQgfAAgUAcgAt3h5QgXgeAAguQAAgtAXgfQAZggAnAAQAnAAAYAgQAYAfAAAtQAAAtgYAfQgZAhgnAAQgnAAgYghgAtrkHQgTAcAAAmQAAAmATAcQAUAdAgAAQAfAAAUgdQATgbAAgnQAAgmgTgbQgUgdggAAQgfAAgUAcgABehcIAAhHIhkAAIAABHIgPAAIAAiZIAPAAIAABEIBkAAIAAhEIAPAAIAACZgAlvhcIAAiZIBlAAIAAAOIhWAAIAACLgAxGhcIAAgLIBOhHQAagYAKgQQALgPAAgRQAAgUgOgNQgOgMgTAAQgUAAgPAKQgNAJgOAUIgMgIQAPgXAQgKQASgMAaAAQAbAAASARQARARAAAZQAAAUgMATQgLAQgdAaIhAA6IB3AAIAAAPg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1, new cjs.Rectangle(-110.5,-30.6,221.1,61.3), null);


(lib.logo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AiCCCIgpgpIiIAAQghAAgVgFQgcgHgPgPQgWgVAAgpIAAh1QAAgIAFgEQAFgFAJAAICWAAQAhAAAVAFQAcAGAQAPQAWAWAAAoIAAB0IAiAiQAFAFgBAHQAAAHgGAGQgGAGgHAAIgBAAQgGAAgFgFgAmEAAQAAAdAOANIADACQAOAMAeAAICXAAIAAhmQAAgcgOgOIgCgCQgPgLgegBIiXAAgAFUBYIAAAAQgrgBgTgMQgPgKgDgSIAAgDQAAgHAFgEQAFgEAIAAQAHAAAFADQAFADABAFIACADQAEAIAKADQAJACARABIBRAAQAuAAAMgHQALgGAAgUIAAgCQAAgQgHgGQgKgIgeAAIhtAAQgmAAgQgOQgQgNAAgfIAAgNQAAgcAUgMQAYgPA9AAIA8AAQAwAAAVAMQAQAKADATIAAADQAAAIgFAEQgEAEgIAAQgHAAgFgEQgFgDgCgFIgBgDQgFgJgOgDQgKgCgbAAIg9AAQgmAAgMAGQgLAFAAASIAAAIQAAAOAHAGQAKAHAZAAIBdAAQAuAAATAJQAaAOAAAoIAAABQAAApgjAOQgUAIgsAAgAoIBTQgFgFAAgIIAAi6QAAgIAFgFQAFgFAJAAQAIAAAFAFQAFAFAAAIIAAC6QAAAIgFAFQgFAFgIAAQgJAAgFgFgAAkBYQg1AAgbgPQgmgVAAg0IAAguQAAg1AmgUQAbgPA1AAIAzAAQA3AAAbAPQAlAUAAA1IAAAuQAAA0glAVQgbAPg3AAgAgZhcQgTAOAAAiIAAArQAAAhATAOQAQALAiAAIBJAAQAjAAAQgLQAUgOAAghIAAgrQAAgigUgOQgQgLgjAAIhJAAQgiAAgQALg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.logo, new cjs.Rectangle(-52.6,-13.5,105.2,27), null);


(lib.img1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.bgImg();
	this.instance.parent = this;
	this.instance.setTransform(-150,-178);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.img1, new cjs.Rectangle(-150,-178,300,355), null);


(lib.btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AC0BIIAAgaIhfAAIgCAaIgLAAIAAgmIAMAAQASgcAAg3IAAgUIBMAAIAABnIAPAAIgCAmgABygqQAAAagEARQgFAWgGALIBCAAIAAhbIgzAAgADpAeQgQgRAAgYQgBgYASgSQAQgSAaAAQAaAAARASQARARAAAZQgBAYgQARQgRASgaAAQgaAAgRgSgADzgtQgNAOAAAUQAAAUAOANQAMAOAUAAQAVAAAMgOQANgNAAgUQAAgUgNgOQgNgOgUAAQgVAAgMAOgAguAeQgQgRAAgYQAAgYAQgSQARgSAaAAQAZAAARASQARARAAAZQgBAYgQARQgRASgZAAQgaAAgRgSgAgkgtQgNAOAAAUQAAAUAOANQAMAOAUAAQATAAANgOQANgNAAgUQAAgUgNgOQgNgOgTAAQgVAAgMAOgAneAdIAIgJQATARAXAAQALAAAHgGQAJgHAAgJQAAgLgJgEQgJgGgOAAIgNAAIAAgLIANAAQANAAAIgFQAIgGAAgLQgBgJgGgFQgIgGgLAAQgUAAgPANIgIgJQAIgHALgFQAKgEAOAAQAQAAAMAJQALAJAAANQAAAUgVAIQALAEAHAGQAGAGAAALQAAAOgLAKQgNAJgQAAQgcAAgWgTgAHRAuIAAhdIgqA+IgBAAIgqg+IAABdIgOAAIAAhzIAOAAIArBAIAqhAIAOAAIAABzgAhZAuIgtg3IgZAYIAAAfIgOAAIAAhzIAOAAIAABFIBDhFIARAAIgyAzIA0BAgAkMAuIgOgeIg/AAIgOAeIgOAAIA2h0IAMAAIA1B0gAkeAEIgbg7IgbA7IA2AAg");
	this.shape.setTransform(-0.3,1.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Слой_3
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(255,255,255,0.22)").s().p("AqkCvIAAldIVJAAIAAFdg");

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.btn, new cjs.Rectangle(-67.6,-17.4,135.4,35), null);


(lib.bg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#956630","#F9DF8B"],[0,1],0,299,0,-298.9).s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.bg, new cjs.Rectangle(-150,-300,300,600), null);


(lib.banner = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{loop:30});

	// timeline functions:
	this.frame_99 = function() {
		this.gotoAndPlay('loop');
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(99).call(this.frame_99).wait(1));

	// urText
	this.instance = new lib.urText();
	this.instance.parent = this;
	this.instance.setTransform(0,264.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(100));

	// logo
	this.instance_1 = new lib.logo();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-88,192.6,0.9,0.9,0,0,0,-0.1,0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(100));

	// btn
	this.instance_2 = new lib.btn();
	this.instance_2.parent = this;
	this.instance_2.setTransform(63.7,191.9,0.02,0.02,0,0,0,0,2.5);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(20).to({_off:false},0).to({regY:0,scaleX:1,scaleY:1},10,cjs.Ease.get(1)).wait(19).to({scaleX:0.96,scaleY:0.96},2).to({scaleX:1,scaleY:1},2).wait(7).to({scaleX:0.96,scaleY:0.96},2).to({scaleX:1,scaleY:1},2).wait(36));

	// t1
	this.instance_3 = new lib.t1();
	this.instance_3.parent = this;
	this.instance_3.setTransform(-23.9,117.6);
	this.instance_3.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({alpha:1},15).wait(85));

	// bg
	this.instance_4 = new lib.bg();
	this.instance_4.parent = this;
	this.instance_4.setTransform(0,300,1,0.443,0,0,0,0,300);
	this.instance_4.alpha = 0.449;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(100));

	// bg
	this.instance_5 = new lib.bg();
	this.instance_5.parent = this;
	this.instance_5.setTransform(0,301.1,1,0.41,0,0,0,0,300.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(100));

	// img1
	this.instance_6 = new lib.img1();
	this.instance_6.parent = this;
	this.instance_6.setTransform(0,-122);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(100));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,-300,300,601);


// stage content:
(lib._300x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// cover
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#666666").ss(2,1,1).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// banner
	this.instance = new lib.banner();
	this.instance.parent = this;
	this.instance.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(149,299,302,602);
// library properties:
lib.properties = {
	id: 'E5F08688052A497EA765790B818200C2',
	width: 300,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/bgImg.jpg", id:"bgImg"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['E5F08688052A497EA765790B818200C2'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;