(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.bgImg = function() {
	this.initialize(img.bgImg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.logo = function() {
	this.initialize(img.logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,41,41);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.t1_7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AC6BAIAJAAIAIgCQAFgCACgCQAEgCACgEIAEgHIgghWIAPAAIAaBIQAIgTAEgOIAMgnIANAAIgVBBIgPAeQgFAHgEAEQgFAFgIADQgIADgMAAgAF2AjQgHgGAAgSIAAg0IANAAIAAA1QAAAKAFAGQAFAFAKAAQAFAAAGgDQAGgCAEgFIAAhAIAOAAIAABTIgMAAIgBgHIgLAGQgGADgHAAQgRAAgHgJgAEnAoQgHgEgEgGQgFgGgDgJQgCgIAAgHQAAgHACgJQADgIAFgGQAEgGAHgEQAHgDAJAAQAJAAAIADQAGAEAFAGQAGAHABAIQACAHAAAIQAAAIgCAIQgBAHgGAHQgFAHgGADQgIAEgJAAQgJAAgHgEgAEtgeQgFADgDAFQgDAFgBAFQgCAHAAAFQAAAGACAGQABAGADAFQADAEAFADQAEADAGAAQAGAAAFgDQAEgDAEgEQADgFACgGQABgGAAgGIgBgMQgCgFgDgFQgEgGgEgCQgFgCgGAAQgGAAgEACgABdAoQgIgEgEgGQgFgGgCgJQgDgIAAgHQAAgHADgJQACgGAFgIQAEgGAIgEQAHgDAJAAQAJAAAHADQAIAFAEAFQAFAHACAIQACAIABAHQgBAHgCAJQgCAHgFAHQgEAGgIAEQgHAEgJAAQgJAAgHgEgABigeQgEADgDAFQgEAFgBAFQgCAHABAFQgBAGACAGQABAGAEAFQADAEAEADQAFADAGAAQAGAAAFgDQAEgDAEgEQADgFABgGQABgGAAgGIgBgMQgBgFgDgFQgEgGgEgCQgFgCgGAAQgFAAgGACgAAfAnQgFgFAAgKIAAg2IgOAAIAAgLIAOAAIAAgXIANAAIAAAXIAVAAIAAALIgVAAIAAA1QgBAFADADQADACADAAQAGAAAFgEIAEAKIgHADQgEACgHAAQgIAAgFgFgAiOAgQgLgLAAgVQAAgLADgHQACgHAEgGQAEgFAIgEQAGgDAIAAQAJAAAHADQAGADAFAGQAEAFACAIQACAIAAAKIg5AAQgBAOAIAKQAGAJAOAAQAGAAAHgCQAHgEAEgEIADALIgEAEIgGADIgSADQgSAAgKgMgAhhgLQAAgGgCgEQgCgEgCgCQgDgDgEgBIgIgBQgIAAgFAEQgFAGgDALIAqAAIAAAAgAlMAoQgGgDgGgHQgEgFgDgKQgCgFAAgKQAAgIACgIQACgGAFgIQAEgGAHgEQAIgDAJAAQAJAAAHADQAIAFAEAFQAFAHACAIQACAIAAAHQAAAHgCAJQgCAHgFAHQgEAGgIAEQgHAEgJAAQgJAAgHgEgAlHgeQgFADgDAFQgDAFAAAFIgCAMQAAAGACAGQAAAFAEAGQADAEAEADQAFADAGAAQAGAAAFgDQAEgDADgEQAEgFABgGQABgGAAgGIgBgMQgBgFgEgFQgDgFgEgDQgFgCgGAAQgGAAgFACgAhAAqIAAhTIAMAAIABAIIAKgHQAFgDAGAAIAHABIgBAMIgHgBQgFAAgGADIgJAIIAAA+gAjFAqIgTg8IgTA8IgMAAIgZhTIAPAAIARBAIAUhAIAIAAIAUBAIARhAIAPAAIgZBTgAmyAqIAAh1IAjAAQATAAAJAJQAKAJgBASQAAARgJAJQgKAJgTAAIgUAAIAAAugAmkgQIAVAAQAKAAAHgGQAHgFAAgNQAAgMgHgFQgGgGgLAAIgVAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1_7, new cjs.Rectangle(-43.5,-7.6,87,15.2), null);


(lib.t1_6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AEpA6QgHgCgGgGQgGgFgDgJQgEgIAAgMQAAgKADgIQADgIAGgFQAFgGAHgDQAIgEAIAAQAIAAAHAEQAGABAGAHQAGAHABAHQADAIAAAMIAAAEIg3AAQABAKAGAGQAGAEAKAAIAIgBIAHgBIAFgDIADgDIAGASIgEADIgHADIgJACIgMABQgJAAgHgDgAFGAGIgCgHIgDgFIgFgDIgFgBQgGAAgFAFQgGAEAAAHIAgAAgABoA5QgIgEgFgGQgFgGgDgJQgCgJAAgHQAAgHACgJQACgHAGgGQAGgIAHgCQAIgFAJAAQAKAAAIAFQAIADAFAHQAFAGADAHQACAJAAAHQAAAHgCAJQgEAJgEAGQgFAGgIAEQgIAEgKAAQgJAAgIgEgABxgGQgDABgDAEIgEAHIgBAKIABAKQACAFACADQADAEADACQADACAFAAQAFAAAEgCQADgCADgEQADgFAAgDQACgEAAgGQAAgGgCgEQAAgFgDgCQgDgEgDgBQgEgCgFgBQgEABgEACgAgoA7QgFgCgEgEQgFgDgCgFQgCgFAAgGQAAgGACgFQAEgGADgDQADgCAHgDIALgDIAKgCIAIAAIAAgBQAAgHgEgCQgDgEgHAAIgHABIgGADIgIAEIgHgPIAEgDIAIgDIAJgDQAFgCAGAAQAGAAAHADQAGACADADQAFAFACAFQACAHAAAHIAAA3IgTAAIgBgHQgDAFgGABQgGADgGAAQgEAAgGgCgAgYAVQgIABgCAEQgDADAAAEQAAAFADACQADADAGgBQAFABADgCIAHgEIAAgSgAiDA5QgGgEgFgFQgFgIgCgHQgCgJAAgIQAAgHACgJQACgHAGgGQAGgHAGgDQAIgFAKAAQAGAAAJADIAAghIAVAAIAAB1IgUAAIAAgHIgIAGQgGADgGAAQgJAAgHgEgAh2gGQgEACgDADIgEAHIgBAJIABAKIAEAJQACAEAEACQADACAFAAQAFAAAEgCQADgCADgEIAAgoQgGgCgGgBQgGABgEACgAjeA5QgHgEgFgGQgFgGgDgJQgCgHAAgJQAAgKACgGQACgHAGgGQAGgHAGgDQAJgFAJAAQAKAAAIAFQAHADAGAHQAFAGADAHQACAJAAAHQAAAHgCAJQgEAJgEAGQgEAGgJAEQgIAEgKAAQgJAAgJgEgAjUgGQgDABgDAEQgCABgCAGIgBAKIABAKIAEAIIAGAGQADACAFAAQAFAAAEgCQADgCADgEQADgFAAgDQACgEAAgGQAAgGgCgEQAAgFgDgCQgDgEgDgBQgEgCgFgBQgFABgDACgADpA7IAAgwQAAgKgEgFQgEgFgHAAQgFAAgFADIgHAFIAAA8IgWAAIAAhUIAUAAIABAGQAFgEAHgCQAGgDAHAAQAGAAAGADQAEABAGAFQADAEADAIQACAHAAAIIAAAzgAAjA7IAAhCIgLAAIAAgSIALAAIAAgFQAAgGACgIIAGgJQAEgEAFgBIALgCQAJAAAFACIAGABIgDASIgEgBIgIgBQgFAAgDADQgDACAAAHIAAAEIASAAIAAASIgSAAIAABCgAkwA7Igrh1IAYAAIAeBZIAdhZIAWAAIgpB1g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1_6, new cjs.Rectangle(-34.8,-6.1,69.7,12.2), null);


(lib.t1_5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AnoA9IAAgVIg8AAIAAAVIgLAAIAAgfIAGAAQAGgJADgKIAHgUIACgMIABgNIABgYIAxAAIAABYIAHAAIAAAfgAoLgbIgDAUIgDAKIgLAbIAsAAIAAhOIgaAAIgBAVgAGzAgQgJgJAAgTQAAgIACgGQACgHAEgFQAEgFAFgCQAHgDAGAAQAHAAAGADQAFADAEAEQAFAGABAGQACAGAAAIIgxAAQAAANAFAIQAGAIALAAQAGAAAGgDIAJgFIADAJIgEADIgGACIgGACIgIABQgPAAgJgKgAHZgEQAAgFgBgDIgEgGQgDgDgDAAQgDgCgDAAQgGAAgGAFQgFAEgBAKIAjAAIAAAAgABRAnQgGgDgEgGQgEgGgBgHQgCgHAAgKQAAgaAHgOQAIgNARAAIAFAAQAFAAACgBQADgCAAgEIAJABQgBAJgEADQgFAEgIAAIgHAAQgFAAgEADQgEACgCAEIgEAIIgBAKQAEgGAFgDQAFgDAJAAQAGAAAGADQAGACADAFQAEAFACAGQACAGAAAHQAAAIgCAFQgCAGgEAGQgEAEgGAEQgGADgIAAQgIAAgGgDgABWgRIgGAGQgCADgCAFIgBAJIABAJQACAGACADQADAEADACQAFACAEAAQAGAAADgCQAFgCACgEIAEgIIABgKIgBgIIgEgJQgCgDgFgDQgDgCgGAAQgFAAgEACgAhRAoQgFgCgFgFQgEgFgDgHQgDgHAAgJQAAgJADgHQACgHAFgFQAEgEAGgDQAFgCAGAAQAHAAADACIAIAEIAFAEIADAFIgIAGIgHgJQgEgDgHAAIgHACIgHAGIgEAJQgCAFAAAFQAAAIACAEQACAGADADIAGAGIAJACQAGAAAFgDQAEgBAEgEIADAJQgDADgHADQgFACgIAAQgGAAgGgCgAkdAoIgHgEQgDgCgCgFQgCgEAAgGQAAgHAEgFQAEgGAGgBIANgEIAOgBIAAgBQAAgJgEgEQgEgEgGAAIgKACQgEACgFAEIgEgJIAJgFQAHgDAIAAQALAAAGAGQAHAGAAAPIAAAtIgKAAIgBgGQgEAFgEABQgEACgGAAIgJgCgAkMAEIgKACQgFACgCADQgDADAAAGQAAAEABACIADAEIAFACIAEABQAFAAAEgDIAIgFIAAgWgAmmApIgHgDIgFgEIgEgDIAGgJIADAEIAEADIAGADQADABAFAAQAHAAAEgDQAEgEAAgGQAAgFgDgDQgEgDgFgBIgLAAIAAgIIAKAAQAGgBADgDQADgEAAgEQAAgGgEgCQgEgDgGAAQgGAAgFADQgFAEgDAFIgIgFIAFgGIAFgFIAIgEIAKgBQALAAAGAFQAGAFAAAJQAAAGgDAFQgEADgGACQAHABAEAEQAEAFAAAHQAAAKgHAGQgIAGgMAAgAE+AoIAAhGIALAAIAAA9IAdAAIAAg9IALAAIAAA9IAdAAIAAg9IALAAIAABGgAD3AoIAAhGIALAAIAAAWIARAAQAGAAAHACQADABAFAEQAEADABADQACAFAAAFQAAAFgCAFIgFAIQgDADgFACQgHACgGAAgAECAfIARAAQAQAAAAgQQAAgIgEgDQgEgEgIAAIgRAAgADYAoIAAg9IgYAAIgBAaIgCARQgCAJgEAEQgFAFgJAAIgEAAIAAgJIADAAIADgBIADgBIADgDIACgGIADgyIAtAAIAABGgACPAoIAAhGIALAAIAABGgAAIAoIAAgZIgSAAIgEAOIgFAHQgDADgCAAIgFABIgHAAIAAgJIAEAAIADgBIADgBIADgFQACgFAAgGIgEgCIgFgEIgDgGQgBgDAAgFQAAgLAHgGQAHgGANAAIAaAAIAABGgAgTgRQgEAEAAAGQAAAHAEADQAEADAHAAIAQAAIAAgbIgQAAQgGAAgFAEgAiAAoIAAgwIghAnIAAAJIgLAAIAAhGIALAAIAAAwIAhgnIAAgJIALAAIAABGgAjXAoIAAg9IgWAAIAAgJIA2AAIAAAJIgVAAIAAA9gAlFAoIAAggIgiAAIAAAgIgLAAIAAhGIALAAIAAAeIAiAAIAAgeIAKAAIAABGgAnOAoIAAhGIALAAIAABGgAILAaIAXgYIgVgXIAHgGIAcAeIgeAdgACQgsQgDgDAAgDQAAgEADgBQABgCAEAAQADAAACACQACABAAAEQAAAEgCACQgCABgDAAQgEAAgBgBgAnNgsQgDgDAAgDQAAgEADgBQACgCADAAQADAAACACQACABAAAEQAAAEgCACQgCABgDAAIgFgBg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1_5, new cjs.Rectangle(-56,-6.1,112,12.3), null);


(lib.t1_4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACPBFIAAhqIALAAIABAGQAGgFAEgBQAFgCAGAAQAIAAAGADQAGAFADAEQADAGACAHQABAHAAAHQAAALgCAFQgDAIgFAGQgDAEgIAEQgGACgJAAQgHAAgGgCIAAAfgACkgbQgFADgDADIAAAwQACACACABIAHABQAGAAAFgCQAEgCAEgEQADgDADgHQACgEAAgJIgBgKIgDgJQgCgDgFgEQgEgCgGgBQgFAAgEACgAgLAkQgGgEgFgJQgFgHgCgKQgCgIAAgLQAAgLACgJQACgJAFgIQAFgJAGgEQAGgFAJAAQAKAAAHAFQAGAEAEAJQAFAIADAJIABAUIgBATQgDAKgFAHQgEAJgGAEQgHAFgKAAQgJAAgGgFgAgFg0QgFAEgDAFIgEAOQgCAHAAAJQAAAIACAHQABAGADAHQADAGAFAFQAEADAFABQAHgBADgDQAFgFADgGQADgEABgJQACgHAAgIQAAgJgCgHIgEgOQgDgFgFgEQgDgFgHAAQgFAAgEAFgAhaAlQgFgDgFgGQgEgGgBgIQgCgHgBgIQABgPAEgNQAEgMAHgJQAIgJAKgEQALgEANAAIACAJQgGAAgJACQgGADgHAEQgFAEgFAGQgDAHgDAJQAEgDAEgCQAFgBAFAAQAIAAAFADQAGADAEAEQADAGACAGIADAMQAAAIgDAGQgBAEgFAIQgDADgGAEQgGADgIAAQgIAAgHgEgAhWgQIgIAEIgBALIABALIADAKQADAFAEACQAEADAFAAQAFAAAEgCIAGgFQACgEABgEIABgJQABgFgCgEIgDgIIgHgFQgDgCgGAAQgFAAgFACgAjHAnIgIgFQgDgDgCgEQgCgEAAgHQAAgHAEgGQAEgDAGgEQAIgEAHgBIAPgBIAAgBQAAgJgEgEQgEgFgHAAQgGAAgEACQgGACgFAEIgEgJQAEgDAGgDQAHgDAJAAQAMABAHAGQAGAHABAPIAAAxIgLAAIAAgHQgEAEgFADQgFABgGAAQgFAAgFgBgAi1AAIgKACQgGACgCADQgDAEAAAGQgBAEACACQACADABACIAFACIAFABQAGAAAEgCIAIgGIAAgXgAkJAoIgIgDIgFgFIgEgDIAGgJIADADIAGAEIAFADIAIABQAKAAADgDQAEgEAAgHQAAgFgDgEQgEgDgFgBIgNAAIAAgIIAMAAQAGgBADgEQACgDABgGQAAgGgFgCQgEgDgGAAQgHAAgFAEQgFADgEAHIgIgGIAFgHIAGgFQADgCAFgCQAFgBAFgBQAMABAHAFQAGAFAAAJQAAAHgDAGQgEAFgGABQAIABADADQAFAFgBAHQABANgIAFQgIAHgOgBgAEPAnIAAgjIgkAAIAAAjIgMAAIAAhMIAMAAIAAAgIAkAAIAAggIAMAAIAABMgABWAnIAAhMIAvAAIAAAKIgjAAIAABCg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1_4, new cjs.Rectangle(-28.3,-6.9,56.6,13.8), null);


(lib.t1_3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AEcA7IAIAAIAHgBIAHgDIAFgGIAEgHIgdhOIANAAIAXBCIAWhCIANAAIgUA8IgNAbQgDAEgFAGQgEADgIAEQgJACgJAAgAnEA7IAIAAIAHgBIAHgDIAFgGIAEgHIgdhOIANAAIAXBCIAWhCIANAAIgUA8IgNAbQgDAEgFAGQgEADgIAEQgJACgJAAgAKrA5IAAgRIg3AAIAAARIgMAAIAAgbIAFAAQAFgDADgFQADgFABgHIADgNIAAghIAyAAIAABCIAIAAIAAAbgAKHAAIgCALIgEALIgFAIIAnAAIAAg3IgcAAgAHZAfQgJgJAAgVQAAgJACgGQADgIAEgFQAEgFAGgCQAGgEAHAAQAIAAAGAEQAGADAEAEQAEAGACAHQACAGAAAJIg1AAQAAAPAHAHQAGAJAMgBQAHAAAFgCQAFgCAFgEIADAKIgEADIgGADIgHACIgJAAQgQAAgKgKgAIDgIQAAgDgCgFIgEgGIgGgFIgHgBQgHAAgFAFQgFAFgDAKIAnAAIAAAAgADSAoIgIgCIgGgFIgEgDIAGgJIAEADIAFAEIAGADIAIABQAJAAADgDQAEgEAAgGQAAgHgDgCQgCgDgHgCIgMAAIAAgIIALgBQAGAAADgEQADgDAAgFQAAgHgEgCQgFgDgGAAQgGAAgGAEQgFAFgDAFIgIgGIAEgHIAGgFQADgDAFgBQAFgBAGgBQAMABAHAFQAGAGAAAIQAAAHgEAGQgEAEgGACQAHAAAFAEQAEAEAAAIQAAAMgIAGQgHAHgOgBgAAmAoIgIgCIgGgFIgEgDIAGgJIAEADIAFAEQACACAEABIAIABQAJAAADgDQAEgEAAgGQAAgHgDgCQgCgDgHgCIgMAAIAAgIIALgBQAGAAADgEQADgDAAgFQAAgHgEgCQgFgDgGAAQgGAAgGAEQgFAFgDAFIgIgGIAEgHIAGgFQADgDAFgBIALgCQAMABAGAFQAHAFAAAJQAAAHgEAGQgEAEgGACQAIABADADQAFAEAAAIQAAAMgIAGQgHAHgOgBgAgrAfQgJgJAAgVQAAgIACgHQADgHAEgGQAEgFAGgCQAGgEAHAAQAIAAAGAEQAGADADAEQAEAGACAHIACAPIg0AAQAAANAHAJQAGAJAMgBQAIAAAEgCQAEgCAFgEIADAKIgEADIgFADIgHACIgJAAQgQAAgKgKgAgBgIQAAgFgCgDIgEgGIgGgFIgHgBQgHAAgFAFQgGAFgBAKIAmAAIAAAAgAksAoIgIgFQgDgCgCgFQgCgEAAgHQAAgHAEgGQADgEAHgEQAIgDAHAAQAHgCAIAAIAAgBQAAgJgEgEQgEgFgHAAQgGAAgFADQgFABgFAEIgEgJQAEgDAGgCQAGgEAJAAQANABAGAGQAHAHAAAPIAAAxIgKAAIgBgHQgDAFgGACQgEABgHAAQgEABgFgCgAkaABQgFAAgGADIgIAEQgDAFAAAFQAAAEACACQABAEACABIAFACIAFAAQAGAAAEgBIAIgGIAAgYgAo9AnQgFgCgGgFQgFgGgDgGQgDgIAAgKQAAgKADgHQAEgJAEgEQAEgFAHgCQAGgCAGgBQAGABAEABIAIAFIAGAEIADAFIgJAHQgDgGgEgDQgEgEgHAAQgFAAgDADQgEACgDADIgFAKQgCAFAAAHQAAAHACAFIAFAKQAEAFADABQAEABAFAAQAIAAAEgBQAFgDAEgEIADAKQgDAEgHADQgGABgJAAQgHABgFgDgAqRAmQgGgDgEgGQgFgGgCgHQgCgHAAgIQAAgHACgHQADgHADgFQAFgGAGgDQAGgDAJgBQAIABAHADQAGAEAEAFQAFAIACAFQACAJAAAFIgCAOQgCAHgFAGQgEAGgGADQgHADgIAAQgJAAgGgDgAqMgZQgEADgDAEQgDAEgBAFIgBALQAAAGABAFQABAFADAEQAEAGADABQADACAHAAQAGAAAEgCQAEgCADgFIAEgJQABgFAAgGIgBgLIgEgJQgDgEgEgDQgFgDgFAAQgGAAgEADgAJQAoIAAgjIgkAAIAAAjIgLAAIAAhMIALAAIAAAgIAkAAIAAggIAMAAIAABMgAG+AoIgWgjIgMAAIAAAjIgLAAIAAhMIALAAIAAAgIAIAAIADAAIADgDIAKgVIAFgEIAEgDIANgBIAAALIgEAAQgFAAgCACQgDACgDAGIgEAKIgEAFIAbAogAFwAoIAAhMIAMAAIAABMgACnAoIAAhMIAMAAIAABMgABdAoIAAhMIAfAAQALABAGAEQAGAGAAAJQAAAIgDAEQgDAEgFABIAFABIAFADIADAGIABAHQAAALgGAFQgGAGgKAAgABpAeIAVAAIAFAAIAEgCIADgFIABgFQAAgFgEgDQgDgEgHAAIgUAAgABpgDIASAAQAIAAACgDQADgEAAgFQAAgLgLABIgUAAgAiDAoIAAhqIA3AAIAAALIgrAAIAAAgIASAAQASAAAIAIQAJAJAAANQAAARgJAHQgIAJgRAAgAh3AdIATAAQAJAAAGgFQAGgFAAgLQAAgLgGgEQgFgFgKAAIgTAAgAlwAoIAAhMIAvAAIAAALIgjAAIAABBgAnZAoIAAhBIgaAAIAAAFIgEApQgCAKgFADQgEAGgKAAIgFAAIAAgKIAHAAIADgCQABgBAAAAQABAAAAgBQAAAAAAgBQABAAAAgBIACgGIACgPIABgnIAxAAIAABMgArEAoIAAhfIgyAAIAABfIgMAAIAAhqIBKAAIAABqgALcAYIAYgYIgWgZIAIgHIAdAgIggAfgAK/AYIAYgYIgWgaIAHgGIAfAgIghAfgAi8AAIAeggIAIAGIgWAaIAYAYIgHAHgAjZAAIAeggIAHAHIgWAZIAZAYIgIAHgACngzQgCgCAAgEQAAgDACgDQACgCAEAAQADAAACACQADADAAADQAAAEgDACQgCACgDAAQgEAAgCgCgAF/g4QgCgCAAgDQAAgEACgCQADgCADAAQADAAACACQACACAAAEQAAADgCACQgDACgCAAQgDAAgDgCgAFkg4QgDgCAAgDQAAgEADgCQACgCADAAQADAAADACQACACAAAEQAAADgCACQgDACgDAAQgCAAgDgCg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1_3, new cjs.Rectangle(-77.1,-7,154.3,14.1), null);


(lib.t1_2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ArbBWIAAiEIAXAAIABAHQADgDAGgEQAGgDAIAAQAJAAAIAEQAHAFAFAHQAGAHACAIQACALAAAIQAAAJgDAJQgDAKgFAGQgHAIgIAEQgKAEgMAAQgGAAgHgCIAAAlgAq7gZQgFADgCADIAAAuQAGACAFABQAHgBAFgCQAFgCADgEQADgEACgFQABgFAAgGIgBgKQgBgEgDgGQgCgDgEgDQgFgDgFAAQgFAAgEADgAKiAwQgIgCgHgHQgHgIgDgIQgEgJAAgNQAAgMADgJQAEgJAGgHQAGgGAIgDQAHgDAKgBQAKAAAHADQAIAEAGAFQAFAIAEAJQADAKAAANIAAAEIg+AAQABANAGAEQAHAGALAAIAJgBIAIgCIAGgDIADgCIAHATIgFADQgCACgFACIgLACIgOABQgJAAgIgDgALDgKQAAgDgCgGIgEgFQgDgDgDgBIgGgBQgGAAgGAFQgGAFgBAJIAlAAIAAAAgAHHAvQgIgFgGgHQgGgHgCgJQgDgJAAgJQAAgJADgJQACgIAGgIQAFgGAJgGQAKgEALAAQALAAAJAEQAIAFAGAHQAGAIADAIQADAJAAAJQAAAJgDAJQgEAKgFAGQgGAIgIAEQgIAEgMAAQgMAAgJgEgAHSgZQgEADgCADQgDAEgCAFQgBAFAAAGQAAAGABAFIAEAJQADAEAEADQAEACAGAAQAFAAAEgCQAEgDADgEQADgEABgFQABgFAAgGQAAgGgBgFQgBgFgDgEQgDgFgEgBQgEgDgFAAQgGAAgEADgAEkAxQgFgCgFgEQgFgEgCgGQgDgGAAgGQAAgIADgFQACgGAFgDQAEgDAHgCQAIgEAFAAQAFgBAGgBIAJgBIAAgBQAAgHgEgEQgEgEgHAAIgIABIgHADIgJAFIgIgRIANgHIAKgEIANgBQAJAAAFACQAIADAEAEQAEAFADAGQADAGAAALIAAA9IgXAAIgBgIQgEAFgGADQgHACgHAAQgHAAgEgCgAE+AEIgIACQgHABgEAFQgDADAAAFQAAAEADAEQAEADAGAAQAGAAAEgCIAHgGIAAgTgAC+AvQgIgEgFgIQgEgGgEgJQgCgLAAgIQAAgIACgKQADgIAGgIQAHgHAHgFQAJgEALAAQAHABAKACIAAglIAYAAIAACEIgWAAIgBgIQgFAFgEACQgGADgIAAQgJAAgIgEgADMgZIgHAGQgDAEgCAFIgBAKIABAMQABAEADAFQADAEAEADQAEACAFAAQAFAAAFgCQAFgDACgDIAAgvQgJgDgFAAQgHAAgEADgABXAvQgIgEgGgIQgGgHgDgJQgDgJAAgJQAAgJADgJQADgIAGgIQAHgHAHgFQAJgEALAAQALAAAKAEQAJAGAFAGQAGAIADAIQACAKAAAIQAAAIgCAKQgDAJgGAHQgGAHgIAFQgJAEgMAAQgLAAgJgEgABigZQgEABgDAFIgEAJQgBAFAAAGQAAAGABAFIAEAJQACAEAFADQAEACAFAAQAGAAAEgCQAEgDADgEIAEgJQABgFAAgGQAAgGgBgFIgEgJQgDgEgEgCQgEgDgGAAQgFAAgEADgAiZAxIgLgDIgJgFIgFgEIAMgSQADAEAIAEQAGADAKABQAHgBAFgCQAFgCAAgFQAAgFgEgDQgDgDgKAAIgJAAIAAgRIAJAAQAJgBADgDQADgDAAgFQAAgFgFgDQgEgCgGAAQgGAAgGAEQgFAEgEAHIgRgLQAGgMAKgGQAIgFAQgBQARAAAKAIQAKAGAAANQAAAHgDAGQgDAGgIADQAJACAEAFQADAGAAAIQAAAJgDAFQgFAHgFACQgFAEgIABIgPACQgIAAgGgCgAmiAvQgJgFgFgHQgGgHgDgJQgDgJAAgJQAAgJADgJQACgIAHgIQAFgGAJgGQAJgEALAAQALAAAJAEQAJAFAGAHQAGAIACAIQADAJAAAJQAAAJgDAJQgDAJgFAHQgHAIgIAEQgIAEgMAAQgLAAgJgEgAmXgZQgFADgCADQgDAEgBAFQgCAFAAAGQAAAGACAFIAEAJQADAEAEADQADACAGAAQAGAAAEgCQADgDADgEQAEgEAAgFQACgFAAgGQAAgGgCgFQAAgFgEgEQgDgFgDgBQgEgDgGAAQgGAAgDADgAoAAxIgLgDIgIgFIgGgEIAMgSQAEAEAHAEQAHADAJABQAHgBAFgCQAFgCAAgFQAAgFgEgDQgDgDgKAAIgJAAIAAgRIAJAAQAJgBADgDQADgDAAgFQAAgFgEgDQgEgCgGAAQgIAAgEAEQgGAEgDAHIgSgLQAHgNAJgFQAJgFAPgBQARAAAKAIQAKAGAAANQAAAHgDAGQgDAGgIADQAKACADAFQAEAGAAAIQAAAIgEAGQgEAGgFADQgGAEgIABIgPACQgIAAgGgCgApkAxQgGgCgEgEIgHgKQgDgGAAgGQAAgIADgFQADgGAFgDQAEgDAHgCIAMgEIAUgDIAAgBQAAgIgEgDQgDgEgIAAIgIABIgHADIgJAFIgIgRIAFgDQAEgDAEgBIALgEIAMgBQAJAAAGACQAGACAFAFQAFAFADAGQACAIAAAJIAAA9IgWAAIgBgIQgFAGgGACQgGACgHAAQgHAAgFgCgApKAEIgIACQgIABgDAFQgDAEAAAEQAAAFAEADQAEADAGAAQAFAAAEgCIAIgGIAAgTgAJaAxIAAg2QAAgLgFgGQgEgGgJAAQgFAAgFADIgJAGIAABEIgYAAIAAhfIAWAAIABAHQAGgEAHgDQAJgCAGgBQAIAAAGACQAHAEAEAEQAFAGACAHQACAHAAAMIAAA4gAF6AxIAAhLIgMAAIAAgUIAMAAIAAgFQAAgJADgHQACgFAEgGQAFgEAGgCQAEgBAIAAQAKgBAFACIAHACIgDAVIgFgCIgJgBQgFAAgEADQgDADAAAHIAAAFIAVAAIAAAUIgVAAIAABLgAgFAxIgxiEIAbAAIAhBjIAhhjIAZAAIguCEgAj+AxIgCg2IgUA2IgMAAIgVg2IgCA2IgXAAIAEhfIAYAAIAYA9IAWg9IAZAAIAEBfg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1_2, new cjs.Rectangle(-73.2,-8.6,146.4,17.3), null);


(lib.t1_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AosBBIAIAAIAJgCQAEAAAFgDQADgCADgEIADgEIgnhgIAaAAIAbBJIAWhJIAYAAQgGAYgKAcQgIAYgIARIgIAPQgEAGgHAHQgGAGgKADQgJADgRABgAFkBXIAAiFIAWAAIABAIQACgDAHgEQAGgDAIAAQAKAAAHAEQAIAFAEAGQAFAHADAJQACAIAAAKQAAAJgCAKQgDAJgGAHQgGAGgJAFQgJAFgNAAQgHAAgGgDIAAAmgAGDgYQgFADgCADIAAAtQAGADAGAAQAFAAAGgCQAFgCADgFQADgDACgGQABgFAAgFIgBgKQgBgFgDgFQgCgEgEgDQgEgCgFAAQgGAAgEADgAhdBXIAAiFIAXAAIABAIIAJgHQAGgDAHAAQALAAAHAEQAHAFAFAGQAFAHADAJQACAKAAAIQAAAKgDAJQgDAJgGAHQgEAGgLAFQgJAFgMAAQgGAAgHgDIAAAmgAg+gYQgEACgCAEIAAAtQAGADAFAAQAGAAAGgCQAFgDADgEQADgDABgGQACgFAAgFIgBgKQgCgHgCgDQgCgDgFgEQgEgCgFAAQgEAAgGADgAIOBGIAAgUIg6AAIAAAUIgYAAIAAgpIAKAAQAKgOADgPQAFgOAAgVIAAgLIBGAAIAABLIAJAAIAAApgAHqAFQgDAOgHAKIAlAAIAAg2IgWAAQAAARgFANgAmDBGIAAgUIg6AAIAAAUIgZAAIAAgpIAKAAQAKgNAEgQQAEgOAAgVIAAgLIBGAAIAABLIAJAAIAAApgAmnAFQgEAPgHAJIAmAAIAAg2IgXAAQgBAUgDAKgAtQAwQgMgFgJgKIAPgVQAGAJAIAEQAJAFAJAAQAKAAAGgFQAGgFAAgJQAAgJgHgEQgGgFgKAAIgPAAIAAgVIAOAAQAKAAAGgGQAFgFAAgIQAAgGgEgFQgFgFgJAAQgKAAgHAFQgHAEgFAIIgRgOQAJgOALgFQALgGARAAQATAAAMAJQALAKAAAQQAAAMgEAIQgGAIgGAEQAKAEAEAHQAGAHAAALQAAAVgNAKQgOAKgWAAQgPAAgLgEgAJNAvQgJgEgFgHQgGgJgDgHQgDgKAAgJQAAgIADgJQADgJAGgHQAFgHAJgFQAIgEAMAAQANAAAHAEQAJAFAGAHQAGAHACAJQADAJAAAIQAAAJgDAKQgCAIgGAIQgFAGgJAFQgJAFgMAAQgLAAgJgFgAJYgZQgEACgDAEQgDAFgBAFQgBAFAAAFQAAAHABAFQABAFADAEQADAEAEACQAEACAFAAQAGAAAEgCQAEgCACgEQADgEACgFQABgFAAgHQAAgFgBgFQgCgFgDgFQgCgDgEgDQgEgCgGAAQgEAAgFACgAEOAvQgJgFgFgGQgGgJgDgHQgCgIAAgLQAAgKACgHQADgJAGgHQAFgHAJgFQAIgEANAAQAMAAAIAEQAJAFAFAHQAGAHADAJQADAJAAAIQAAAJgDAKQgDAHgGAJQgFAHgJAEQgIAFgMAAQgMAAgJgFgAEZgZIgHAGIgEAKQgBAFAAAFQAAAHABAFIAEAJQAEAFADABQAEACAGAAQAFAAAEgCQADgBAEgFIAEgJQABgFAAgHQAAgFgBgFQgCgGgCgEQgEgEgDgCQgEgCgFAAQgGAAgEACgAAfAvQgKgFgEgGQgGgHgDgJQgDgKAAgJQAAgIADgJQAEgLAFgFQAEgHAKgFQAIgEAMAAQANAAAHAEQAJAFAGAHQAFAFADALQADAJAAAIQAAAJgDAKQgDAJgFAHQgFAGgKAFQgIAFgMAAQgLAAgJgFgAAqgZQgFADgCADQgDAFgBAFIgBAKIABAMQABAFADAEQADAEAEACQAEACAFAAQAGAAAEgCQAEgCACgEQADgEACgFIABgMIgBgKQgCgFgDgFQgCgDgEgDQgFgCgFAAQgEAAgFACgAp7AvQgIgDgGgJQgGgIgDgKQgCgIAAgOQAAgNACgLQACgNAGgJQAGgLAIgGQAJgHANgBIAIAAQAFgBACgCQACgCABgGIAUAEIgDAMQgCAEgDAEIgIAEIgUADQgJABgGAGQgFAGgDANQACgFAIgDQAIgDAIAAQALAAAIAFQAHAEAGAHQAFAHACAHQACAIAAAGQAAALgDAJQgEAIgGAHQgGAHgJADQgHAEgLAAQgMAAgJgFgAp2gMQgGAHAAAKQAAALAGAHQAFAHALAAQALAAAFgHQAGgHAAgLQAAgKgGgHQgFgIgLAAQgLAAgFAIgArjAyIgKgGQgDgDgEgHQgDgGAAgHQAAgGADgGQADgGAEgDQAGgEAFgCIANgDIAUgDIAAgBQAAgIgEgEQgFgDgGAAIgIABIgHACIgFADIgEADIgIgRIAFgEIASgHIANgBQAJAAAGACQAGACAFAFQAFAEADAHQACAIAAAJIAAA9IgWAAIgBgIQgFAFgGACQgGADgHAAQgHAAgFgCgArJAFIgIACQgIABgDAEQgDAEAAAFQAAAEAEADQAEADAGAAQAFAAAEgCIAIgFIAAgTgANNAyIAAg0IglAkIAAAQIgYAAIAAhgIAYAAIAAAzIAlgjIAAgQIAZAAIAABggALeAyIAAgnIgjAAIAAAnIgZAAIAAhgIAZAAIAAAlIAjAAIAAglIAZAAIAABggADWAyIgXgmIgMAAIAAAmIgZAAIAAhgIAZAAIAAAlIAFAAQADAAACgCIAEgGIAGgMQADgJAGgEQAFgEAIAAIAQAAIAAAVIgIAAQgEAAgDACQgCACgCAFQgFALgDAEIAiAzgAiOAyIAAhLIgiAAIAABLIgZAAIAAhgIBTAAIAABggAlYAyIAAhgIAYAAIAAAZIAXAAQASAAALAKQAKAKAAAOQAAAIgDAIQgDAHgGAFQgEAEgJACQgHADgIAAgAlAAfIATAAQAJAAAEgFQAEgGAAgHQAAgGgEgFQgEgEgJAAIgTAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1_1, new cjs.Rectangle(-87,-8.8,174,17.6), null);


(lib.redLine = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E60000").s().p("EgsQAElIAAkbMAs6gs2MArnAI7MgBQBMQMgvMAENg");
	this.shape.setTransform(141.8,-42);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.redLine, new cjs.Rectangle(-141.6,-328.1,566.7,572.1), null);


(lib.logo_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.instance = new lib.logo();
	this.instance.parent = this;
	this.instance.setTransform(-21,-21);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.logo_1, new cjs.Rectangle(-21,-21,41,41), null);


(lib.bgImg_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.bgImg();
	this.instance.parent = this;
	this.instance.setTransform(-120,-240,0.8,0.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bgImg_1, new cjs.Rectangle(-120,-240,240,480), null);


(lib.banner = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_109 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(109).call(this.frame_109).wait(31));

	// t1_7
	this.instance = new lib.t1_7();
	this.instance.parent = this;
	this.instance.setTransform(-263.5,-46.7,1.045,1.045);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(64).to({_off:false},0).to({regX:-0.1,regY:0.1,x:-53.2,y:-46.6},10,cjs.Ease.get(1)).wait(66));

	// t1_6
	this.instance_1 = new lib.t1_6();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-274,-66.9,1.045,1.045);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(64).to({_off:false},0).to({regX:-0.1,regY:0.1,x:-63.7,y:-66.8},10,cjs.Ease.get(1)).wait(66));

	// t1_5
	this.instance_2 = new lib.t1_5();
	this.instance_2.parent = this;
	this.instance_2.setTransform(-251.8,-105.7,1.045,1.045,0,0,0,-0.1,-0.1);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(99).to({_off:false},0).to({regX:0,regY:0,x:-41.4,y:-105.6},10,cjs.Ease.get(1)).wait(31));

	// t1_4
	this.instance_3 = new lib.t1_4();
	this.instance_3.parent = this;
	this.instance_3.setTransform(-280.6,-138.3,1.045,1.045,0,0,0,-0.1,-0.1);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(89).to({_off:false},0).to({regX:0,regY:0,x:-70.2,y:-138.2},10,cjs.Ease.get(1)).wait(41));

	// t1_3
	this.instance_4 = new lib.t1_3();
	this.instance_4.parent = this;
	this.instance_4.setTransform(-228.5,-154,1.045,1.045,0,0,0,-0.1,-0.1);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(84).to({_off:false},0).to({x:-18.1},10,cjs.Ease.get(1)).wait(46));

	// t1_2
	this.instance_5 = new lib.t1_2();
	this.instance_5.parent = this;
	this.instance_5.setTransform(-232.7,-186.1,1.045,1.045);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(54).to({_off:false},0).to({regX:-0.1,regY:-0.1,x:-22.4,y:-186.2},10,cjs.Ease.get(1)).wait(76));

	// t1_1
	this.instance_6 = new lib.t1_1();
	this.instance_6.parent = this;
	this.instance_6.setTransform(-219.1,-207.1,1.045,1.045,0,0,0,-0.1,-0.1);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(49).to({_off:false},0).to({x:-8.7},10,cjs.Ease.get(1)).wait(81));

	// logo
	this.instance_7 = new lib.logo_1();
	this.instance_7.parent = this;
	this.instance_7.setTransform(-66,11.3,0.01,0.01);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(19).to({_off:false},0).to({scaleX:1,scaleY:1},10).wait(111));

	// redLine
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E60000").s().p("AMMN2I7q7rIIhAAIWcbrg");
	this.shape.setTransform(-158.7,-63.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#E60000").s().p("AMIN2I7r7rIOvAAIQXbrg");
	this.shape_1.setTransform(-158.3,-63.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#E60000").s().p("AMEN2I7r7rIUpAAIKmbrg");
	this.shape_2.setTransform(-157.9,-63.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#E60000").s().p("AMAV3I7q7rIVwwCMAJlArtg");
	this.shape_3.setTransform(-157.5,-114.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#E60000").s().p("AL9VZI7q7rIT9vGIJOAFMACQAqsg");
	this.shape_4.setTransform(-157.2,-111.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#E60000").s().p("AJfV3I7q7rIUHwCIQQAoMgE1ArFg");
	this.shape_5.setTransform(-141.4,-114.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#E60000").s().p("AGGWGI7r7rIWAwgIVLCqMgLiAphg");
	this.shape_6.setTransform(-119.7,-116.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#E60000").s().p("ACYV8I7q7rIWtwMIb4BuMgS2AqJg");
	this.shape_7.setTransform(-95.9,-115.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#E60000").s().p("AjCWII7s7rIW4wkMAmlAAjMgdkArsg");
	this.shape_8.setTransform(-61.2,-116.4);

	this.instance_8 = new lib.redLine();
	this.instance_8.parent = this;
	this.instance_8.setTransform(-67,6.1,1,1,-90,0,0,-122.4,-27.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape}]},34).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.instance_8}]},1).wait(97));

	// bgImg
	this.instance_9 = new lib.bgImg_1();
	this.instance_9.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(140));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-120,-240,240,480);


// stage content:
(lib._300x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// cover
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#666666").ss(1,1,1).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// banner
	this.instance = new lib.banner();
	this.instance.parent = this;
	this.instance.setTransform(150,299.8,1.25,1.25);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(149,299,302,602);
// library properties:
lib.properties = {
	id: 'E49A7E84608F4EF98DB08C6FFBD329FB',
	width: 300,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/bgImg.jpg", id:"bgImg"},
		{src:"images/logo.png", id:"logo"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['E49A7E84608F4EF98DB08C6FFBD329FB'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;