(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 300,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	manifest: [
		{src:"images/bgImg1.jpg", id:"bgImg1"},
		{src:"images/bgImg2.jpg", id:"bgImg2"},
		{src:"images/bgImg3.jpg", id:"bgImg3"},
		{src:"images/bgImg4.jpg", id:"bgImg4"},
		{src:"images/bgImg5.jpg", id:"bgImg5"},
		{src:"images/bgImg6.jpg", id:"bgImg6"},
		{src:"images/l.png", id:"l"}
	]
};



// symbols:



(lib.bgImg1 = function() {
	this.initialize(img.bgImg1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.bgImg2 = function() {
	this.initialize(img.bgImg2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.bgImg3 = function() {
	this.initialize(img.bgImg3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.bgImg4 = function() {
	this.initialize(img.bgImg4);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.bgImg5 = function() {
	this.initialize(img.bgImg5);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.bgImg6 = function() {
	this.initialize(img.bgImg6);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.l = function() {
	this.initialize(img.l);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,80,55);


(lib.urText = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAkA/IABgHIAIABIACAAIACgDIAAgCIgEgBIgEgBIgCgDIgBgEIgGgWIAJgCIAFAUIACAEIACABIACAAIAGgZIAJACIgJAjQgBAFgDACQgDACgFAAgADTAxIgEACIgHABIgGgBIgDgDIgCgEIgBgFIAAgUIAJAAIAAAUQAAAAAAABQAAABAAAAQABABAAAAQAAABABAAIADABIAEAAIACgBIAAgYIAKAAIAAAZIACAEIgGAFgAD2AxIgDACIgHABIgEgBIgFgBIgCgDIgBgFIABgFIADgDIAEgCIAMAAIAAgCIgBgDIgFgBIgDAAIgGABIgCgGIAMgDIAHABIAEADIACAEIABAFIAAAMIADAFIgGAEgADrAnQgBAAAAAAQAAAAAAABQAAAAAAABQAAAAAAABIABACQAAAAAAABQAAAAAAAAQABAAAAAAQABAAAAAAIAEAAIADgBIAAgGIgHAAgACdAxIgEACIgHABIgEgBIgEgBIgCgDIgBgFQAAgBAAgBQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBQAAAAABgBQAAAAAAAAQABgBAAAAIAFgCIALAAIAAgCQAAAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAAAIgFgBIgDAAIgGABIgCgGIANgDIAGABIAFADIACAEIAAAFIAAAMIADAFIgGAEgACRAnQAAAAgBAAQAAABAAAAQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAAAQAAABAAAAQABAAAAAAQAAAAAAABQABAAAAAAQAAAAABAAQAAAAABAAIAEAAIACgBIAAgGIgGAAIgDABgAB2AzIgEgBIgDgEIAAgFIAAgOIgEAAIAAgIIAEAAIAAgIIAJAAIAAAIIAJAAIAAAIIgJAAIAAANIABAEIADABIAGgBIACAGIgCABIgDABIgCAAIgDAAgABPAzIgFgEQgCgCgBgDIgBgHIABgGIADgGIAGgDQACgCAEAAQAFAAADACIAFADQACACABAEIABAGIgBAHQgBADgCACIgFAEQgDABgFAAQgEAAgDgBgABRAcQgBADAAAEQAAAFABACQADADACAAQADAAADgDQACgCgBgFQABgJgIAAQgCAAgDACgAAFAzIgFgEQAAgCgBgDIgBgHIABgGQABgEAAgCIAFgDQAEgCADAAQAFAAADACIAFADQACACABAEIABAGIgBAHQgBADgCACIgFAEQgDABgFAAQgEAAgDgBgAAHAcQgCADAAAEQAAAFACACQACADADAAQADAAADgDQABgCABgFQAAgJgIAAQgDAAgCACgAgTAzIgEgBIgBgEIgBgFIAAgOIgFAAIAAgIIAFAAIAAgIIAJAAIAAAIIAJAAIAAAIIgJAAIAAANQAAABAAABQAAAAAAABQAAAAAAAAQABABAAAAIADABIAGgBIABAGIgBABIgDABIgDAAIgCAAgAhDAzQAAAAgBAAQAAAAgBAAQAAAAgBgBQAAAAAAAAIgFABIgEABIgGgBIgDgBIgCgDIgBgEIgDgXIAJgBIADAXIABABIABABIABAAIABABIADgBIAAgZIAJAAIAAAZIADABIABgBIABAAIABgBIAAgBIADgXIAJABIgDAXIAAADIgCADIgEACIgEABgAh1AzIgFgBQAAAAgBAAQAAABgBAAQAAAAgBAAQAAAAgBAAIgFABIgEgBIgEgBIgCgDIgBgEIgDgXIAKgBIACAXIABABIAAABIABAAIABABIAEgBIAAgZIAJAAIAAAZIADABIABgBIABAAIABgBIAAgBIADgXIAKABIgEAXIgBADIgCADIgDACIgFABgAipAzQgBAAAAAAQgBAAAAAAQgBAAAAgBQgBAAAAAAIgEABIgFABIgFgBIgEgBIgCgDIgBgEIgCgXIAJgBIACAXIABABIABABIABAAIACABIADgBIAAgZIAJAAIAAAZIACABIABgBIACAAIABgBIAAgBIADgXIAJABIgCAXIgBADQgBABAAAAQAAABAAAAQgBAAAAABQAAAAgBAAIgDACIgFABgACsAyIAAgDIAAgEQABgBAAAAQABAAAAAAQABgBAAAAQABAAAAAAQABAAABAAQAAAAABABQAAAAABAAQAAAAABABIABAEIgBADQgBABAAAAQgBAAAAAAQgBABAAAAQgBAAgBAAQAAAAgBAAQAAAAgBgBQAAAAgBAAQAAAAgBgBgAgrAyIgBgDIABgEQAAgBABAAQAAAAABAAQAAgBABAAQAAAAABAAQABAAAAAAQABAAAAABQABAAAAAAQABAAAAABIABAEIgBADQAAABgBAAQAAAAgBAAQAAABgBAAQAAAAgBAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQgBAAAAgBgAFegUIAAgcIgDgEIAEgCIACADIACgCIAFgBQAEAAADADQACADABAGIgBAFIgCAEIgEADIgFABIgDAAIgCgBIAAAKgAFkgyIgDACIAAAPIACABIADAAQAEAAABgDQACgCAAgFQAAgEgCgDQAAAAAAgBQAAAAgBAAQAAgBgBAAQgBAAAAAAgAARgUIAAgcIgDgEIAEgCIACADIADgCIAEgBQAFAAACADQACADABAGIgBAFIgCAEIgEADIgFABIgCAAIgCgBIAAAKgAAXgyIgCACIAAAPIACABIACAAQAEAAABgDQACgCAAgFIgBgHQAAAAgBgBQAAAAgBAAQAAgBgBAAQgBAAAAAAgAiYgUIAAgcIgCgEIAEgCIABADIADgCIAEgBQAGAAACADQACADAAAGIgBAFIgCAEIgEADIgEABIgDAAIgCgBIAAAKgAiRgyIgDACIAAAPIACABIADAAQADAAACgDQABgCAAgFQAAgEgBgDQAAAAAAgBQgBAAAAAAQgBgBAAAAQgBAAgBAAgAmwgUIAAgJIgGgBIgEgDIgCgEIgBgEIABgFIADgEIADgCIAGgCIAAgJIADAAIAAAJIAGACIAEACIACAEIABAFIgBAEIgCAEIgEACQgCACgEAAIAAAJgAmtggQAFgBACgCQACgCAAgEQAAgFgCgCQgCgCgFgBgAm2gwQgCADAAAEQAAADACADQABADAFAAIAAgTQgFABgBACgAjmgYIAAgGIgPAAIAAAGIgEAAIAAgJIACAAIACgDIACgKIAAgHIAOAAIAAAUIADAAIAAAJgAjwgnIgCAGIAJAAIAAgRIgGAAgAl9gYIAAgGIgRAAIAAgXIAEAAIAAAUIAKAAIAAgUIAFAAIAAAUIADAAIAAAJgAHDggIgDACIgFABQgDAAgCgCQgCgCAAgEIAAgDIADgCIADgCIAIAAIAAgBIgBgFIgEgBIgGACIgCgDIAJgCIAFABIABACIACADIAAAOIACADIgDACgAG6goQgBAAAAAAQAAABgBAAQAAABAAAAQAAABAAAAIABAEIADABIAEgBIACgCIAAgGIgEAAgAGFggIgDACIgFABQgDAAgCgCQgCgCAAgEIAAgDIADgCIADgCIAIAAIAAgBIgBgFIgEgBIgGACIgBgDIAIgCIAEABIACACIACADIAAAOIACADIgDACgAF7goQAAAAAAAAQAAABgBAAQAAABAAAAQAAABAAAAIABAEIADABIAEgBIACgCIAAgGIgEAAgAENggIgDACIgEABQgDAAgDgCQgCgCAAgEIAAgDIACgCIAEgCIAIAAIAAgBIgBgFIgEgBIgHACIgBgDIAJgCIAFABIACACIABADIAAAOIACADIgDACgAEEgoIgBADIABAEIACABIADgBIADgCIAAgGIgEAAgADXgeIgDgDIgCgEIgBgFIABgFIACgEQABAAAAgBQAAAAABAAQAAgBABAAQAAAAABAAIAEgBIAFABIADACIACAEIABAFIgBAFIgCAEIgDADIgFABIgFgBgADYgxQgCADAAAEIABAEIABADIABACIADABQAEAAABgDQABgCABgFQgBgEgBgCQgBgDgEAAQgBAAAAAAQgBAAgBABQAAAAgBAAQAAABAAAAgACjgeIgDgDIgDgEIAAgFIABgFIACgEIADgCIAEgBIAFABIAEACIACAEIABAFIgBAFIgCAEIgEADIgFABIgEgBgACjgxQgCADABAEIAAAEIABADIACACIACABQAFAAAAgDQACgCAAgFQAAgEgCgCQAAgDgFAAQAAAAgBAAQgBAAAAABQgBAAAAAAQgBABAAAAgAgEgeIgDgDIgBgEIgBgFIABgFIACgEIADgCIADgBIAEABIAEACIACAEIAAAFIAAAFIgCAEIgEADIgEABIgEgBgAgDgxQgBADgBAEIABAEIABADIABACIACABQADAAABgDIABgHIgBgGQgBgDgDAAQAAAAAAAAQgBAAgBABQAAAAgBAAQAAABAAAAgAgwgeIgDgCIgBgEIgBgEIgFAAIAAAKIgEAAIAAgXIAEAAIAAAJIAFAAIABgEIACgDIADgCIAFgBIAEABIAEACIABAEIAAAFIAAAFIgBAEIgEADQgBABgEAAgAgwgxIgBAHIAAAEIABADIADACIADABQADAAABgDQABgBAAgGIAAgDIgBgDIgCgCIgCgBQgEAAgCACgAhfgeQAAAAgBgBQAAAAgBAAQAAgBgBAAQAAgBAAAAIgCgFIgBgLIACgFIADgEIAEgCIAGgCIABgCIAEABIgCADIAAABIgBABIgDAAIgGACIgCACIgBACIAAADIADgCQAAAAABAAQAAAAABgBQAAAAABAAQABAAABAAIADABIAEACIABAEIABAEIgBAEIgCAEIgEADIgEABQgBAAgBAAQgBAAAAgBQgBAAAAAAQgBAAAAAAgAhegwIgCADIAAAGIABAEIABACIAEABQADAAABgDQACgCAAgEQAAgDgCgDQAAAAAAgBQAAAAgBAAQAAAAgBgBQgBAAAAAAgAi/geIgDgDIgBgDIgBgFIABgFIABgEIAEgDIAFgBIAEAAIADACIgBADIgDgBIgDgBQgEAAgBACQgCADAAAFIAAADIACADIACACIADABIADgBIADgBIABADIgDABIgFABIgFgBgAnXgeIgEgEIgCgFIgBgHIABgHIADgGQABgDACAAQAEgCADAAQAEAAACACQACAAACADIADAGIABAHIgBAHIgDAFIgEAEIgGABgAnUg7IgEADIgBAEIAAALIABAEIAEADQAAAAAAABQABAAAAAAQABAAAAAAQABAAABAAIAFgBQAAAAAAAAQABgBAAAAQAAAAABgBQAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAAAgBQAAgBAAAAIABgFIgBgGIgBgEIgDgDIgEgBgAGqgeIAAgLIgLAAIAAALIgEAAIAAgXIAEAAIAAAJIALAAIAAgJIAFAAIAAAXgAGPgeIAAgUIgCAAIAAgDIAHAAIAAAXgAFOgoIgDAAIAAAKIgFAAIAAgXIAFAAIAAAJIADAAIABgBIADgGIACgCIACgBIABAAIABABIgBACIAAAAIAAAAIgBAAIgEAIIgBABIAHALIgDABgAEwgeIgCAAIAAgDIACAAIADAAIABAAIABgCIABgCIABgBIgDAAIgBgBIgCgCIgHgVIAEgBIAGAUIABABIABAAIACABIAHgWIAEABIgKAdIgCACIgCABgADxgeIAAgUIgIAAIAAgDIATAAIAAADIgIAAIAAAUgADHgeIAAgPIgKAMIAAADIgFAAIAAgXIAFAAIAAAPIAKgMIAAgDIAEAAIAAAXgACRgeIAAgeIgJAAIAAgDIAXAAIAAADIgKAAIAAAegABhgeIAAghIAEAAIAAAhgABUgeIAAghIAFAAIAAAhgABHgeIAAgdIgPAAIAAAdIgEAAIAAghIAXAAIAAAhgAgXgeIAAgUIgIAAIAAgDIAUAAIAAADIgHAAIAAAUgAhvgeIAAgPIgLAMIAAADIgEAAIAAgXIAEAAIAAAPIALgMIAAgDIAEAAIAAAXgAiogeIAAgUIgIAAIAAgDIATAAIAAADIgHAAIAAAUgAjOgeIAAgPIgLAMIAAADIgFAAIAAgXIAFAAIAAAPIALgMIAAgDIADAAIAAAXgAkLgeIAAgPIgKAMIAAADIgFAAIAAgXIAFAAIAAAPIAKgMIAAgDIAFAAIAAAXgAklgeIAAgPIgKAMIAAADIgFAAIAAgXIAFAAIAAAPIAKgMIAAgDIAFAAIAAAXgAk/geIAAgLIgLAAIAAALIgDAAIAAgXIADAAIAAAJIALAAIAAgJIAFAAIAAAXgAlZgeIAAgPIgLAMIAAADIgEAAIAAgXIAEAAIAAAPIALgMIAAgDIAFAAIAAAXgAl0geIAAgUIgDAAIAAgDIAIAAIAAAXgAmageIAAgUIgCAAIAAgDIAHAAIAAAXgAHVgkIAGgGIABgBIgBgBIgGgFIADgCIAFAEIABACIABACIgBADIgHAFgAHMgkIAEgFIACgBIABgBIgBgBIgGgFIADgCIAFAEIABACIABACIgBADIgHAFgACCgmIgCgCIgBgCIABgDIABgCIAGgEIACACIgFAEIgBABIAAABIAAABIAGAGIgCABgAB4gmIgCgCIAAgCIAAgDIACgCIAFgEIACACIgGAFIAAACIACABIAFAFIgDABgAEYgqIAAgEIANAAIAAAEgAhKg1IACgFIgCgBIgBgBIABgDIADgBIACABIABADIAAABIAAABIgBACIgBACIgBACgADAg5IgCgBIgCgCIgBgCIADgBIABACQABAAAAAAQAAAAAAABQABAAAAAAQABAAAAAAIAEgBIABgCIADABIgDAEIgFABgAkSg5IgCgBIgBgCIgBgCIACgBIABACIAEABIADgBIABgCIADABIgDAEQAAAAAAAAQgBAAAAAAQgBABAAAAQgBAAgBAAgAlhg5IgCgBIgBgCIgBgCIACgBIACACIAEABIACgBIACgCIADABIgDAEIgEABgAl0g6IgBgCIABgCIADgBIACABIAAACIAAACIgCABIgDgBgAmag6IgBgCIABgCIACgBIACABIABACIgBACIgCABIgCgBgAGUg7IAAgCIAAgCIADgBIABABIABACIgBACIgBABIgDgBgAGKg7IgBgCIABgCIACgBIACABIAAACIAAACIgCABIgCgBg");
	this.shape.setTransform(0,0,2.555,2.556);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-122.5,-16.6,245,33.3);


(lib.t1_2 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#2D3538").s().p("AFKBlIAAioIgJgWIAVgLIAIAOIAUgHQALgFAPAAQAcAAAQATQARAUAAAhQAAAKgFATQgDALgKAMQgKALgLAEQgQAGgQAAIgQgBIgQgEIAAA7gAF0hJIgSAIIAABWIAhAGQAJAAAIgEQAGgBAIgIIAIgOQAEgMAAgNIgCgYQgFgMgEgEQgBgDgLgGIgPgDQgNAAgHAEgAKhAqQgOgGgHgJQgJgJgEgOQgEgLAAgQQAAgSAFgMQAEgLAKgNQAIgJAOgGQAPgGAPAAQARAAALADQAJACANAFIgJATIgUgGIgTgCQgLAAgKAEQgJAEgFAIIgJAQIgCAWQAAAXALANQAMANAVAAQAOAAAHgCIAXgGIAGATIgXAIIgcACQgOAAgSgFgADHApQgOgGgHgJQgHgJgEgOQgEgLAAgRQAAgPAEgOQAGgPAHgIQAKgKALgFQAPgGAOAAQASAAANAGQALAFALAKQAHAKAEANQAEAOAAAPIgDAaQgCAMgKANQgHAJgOAGQgPAGgRAAQgQAAgPgGgADIhAQgMAOAAAZQAAAZAMANQALAOATAAQAVAAALgOQAKgNAAgZQAAgZgKgOQgLgNgVAAQgTAAgLANgAiMAqQgJgCgKgLQgIgKgEgKQgFgNAAgKIgdAAIAAA4IgYAAIAAiJIAYAAIAAA8IAdAAQAAgKAFgPQADgIAKgNQAGgGANgGQAPgFANAAQAQAAANAGQAOAGAHAJQAHAKAEANQAEAOAAAPQAAAQgEAKQgEAOgHALQgIAKgNAFQgNAGgQAAQgTAAgKgFgAiOhAQgJANAAAaQAAAZAJANQALAOAUAAQATAAAKgOQAJgNAAgZQAAgagJgNQgJgNgUAAQgWAAgJANgAloApQgNgFgIgKQgHgJgEgOQgEgLAAgRQAAgPAEgOQACgLAKgMQALgKALgFQAPgGAOAAQAQAAAPAGQANAFAHAKQAJAJAEAOQAEAOAAAPQAAAQgEAKQgEAOgHALQgIAJgOAGQgNAGgSAAQgQAAgPgGgAlnhAQgMAOAAAZQAAAZAMANQAKAOAUAAQAVAAAKgOQALgNAAgZQAAgZgLgOQgJgNgWAAQgVAAgJANgAsJAgIgTAKQgKAFgSAAIgTgCQgKgDgFgFQgIgGgDgHQgEgHAAgMQAAgMAFgGQAEgKAHgEIARgJIAUgDIAlAAIAAgHQAAgSgIgGQgFgIgRAAIgUADQgPACgHAEIgHgTIAWgHIAdgDQARAAALADQAKAEAFAIQAFAFADALIADAXIAAA7IALASIgSAOgAtHgMQgIAHAAAJIACAKIAGAIIAKAEIAKABQAOAAAHgFIAPgJIAAgfIgkAAQgOAAgGAGgABOgRIgSAAIAAA7IgYAAIAAiJIAYAAIAAA4IANAAIAGgBIAFgEIAYgmIALgJQAGgEAIAAIAFAAIAHACIgCAUIgFAAIgHABIgGAFIgWAiIgCACIgCADIAyA5IgSAQgAONAqIAAiJIAYAAIAAA3IAnAAQAOAAAMAEQALAEAEAGQAGAHACAGIACANQAAASgMANQgNALgWAAgAOlAWIAnAAQAMAAAGgFQAIgFAAgMQAAgIgIgGQgGgFgPAAIgkAAgAMtAqIAAhzIgwAAIAAgWIB6AAIAAAWIgwAAIAABzgAJEAqIAAhYIhEBEIAAAUIgYAAIAAiJIAYAAIAABbIBEhGIAAgVIAZAAIAACJgAoYAqIAAiJIBBAAIASADIAOAFQAHAFADAHQACADAAANQAAAJgDAIQgDAFgKAHIAJAEIAHAIIAHAJIABAKQAAAUgNALQgOAKgUAAgAoAAWIAqAAQAMAAAHgEQAHgGAAgLQAAgFgEgHQgFgFgEAAIgIgCIgvAAgAoAgnIAlAAQALAAAGgDQAHgEAAgKQAAgLgGgDQgFgEgOAAIgkAAgAp4AqIAAhzIgxAAIAAgWIB7AAIAAAWIgxAAIAABzgAugAqIAAg8IhFAAIAAA8IgZAAIAAiJIAZAAIAAA4IBFAAIAAg4IAYAAIAACJg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-102.4,-10.1,204.8,20.3);


(lib.t1_1 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#2D3538").s().p("AJKCCIgQgEIAEgUIAQADIAOACQAOAAAEgEQAIgGAEgLIAEgQIgMABIgRgDIgMgHQgFgEgCgHIgHgTIgahiIAZgFIAZBiIAHASIAIAFIAKACIAKgBIAhh6IAXAFIgoCaIgIAUIgMANIgQAGgAEoCCIAAioIgJgYIAWgJIAIAPIAVgJQALgEAMAAQAeAAAPARQAQASAAAiQAAASgDAMQgDAMgKANQgJAKgOAFQgLAFgUAAIgfgEIAAA7gAFTgtIgSAIIAABXIAOAEIATABIAQgCQAIgEAFgHQAIgGADgKQACgHAAgSQAAgQgCgGQgCgJgGgGQgIgIgFgBQgEgCgLAAgAvICCIAAioIgJgYIAWgJIAJAPIATgJQAMgEAOAAQAdAAAPARQARAVAAAfQAAATgFALQgEAQgJAJQgKAKgMAFQgLAFgTAAIgigEIAAA7gAuegtIgSAIIAABXIAQAEIATABIAQgCQAJgGAEgFQAFgFAEgLQAEgKAAgPIgDgWQgDgKgGgFQgEgIgHgBQgFgCgKAAgAOhBGQgOgDgHgLQgJgJgFgOQgDgMAAgTQAAgMADgOIAOgXQAGgJAOgHQALgGASAAQAgAAAOARQAPASAAAiIgMAKIhZAAQAAAVAMALQAMANAVAAIAXgCIAXgHIAIATIgYAHIgfADQgUAAgMgFgAPggIQABgLgEgIIgHgNIgLgGIgOgDQgSAAgKAMQgJAIgDAVIBLAAIAAAAgADtA9IgUAJQgKAFgQAAQgOAAgFgDQgJgBgIgGQgFgEgFgIQgFgLAAgJQAAgKAFgKQADgFAIgIQAJgEAJgDQAHgDANABIAlAAIAAgJQAAgPgHgKQgJgGgOAAQgNAAgHACIgXAGIgGgUIAWgGIAegCQARAAAKAEIAQAKIAHASIACBSIAMAQIgSAOgACuAOQgHAHAAALIADAMIAGAGQADADAGABIALABQAMAAAHgEIAQgJIAAgiIgkAAQgLAAgKAGgApxBGQgPgGgHgKQgHgKgEgOQgEgMAAgRQAAgOAFgMQAEgNAIgLQAHgIAOgHQALgFAUAAQASAAALAFQAOAHAIAIIAMAYQAEAOAAAMQAAARgEAMQgEAOgIAKQgIALgNAFQgMAFgTAAQgVAAgKgFgApxgjQgMAOAAAWQAAAbAMANQALAOAVAAQASAAAMgOQALgMgBgcQABgZgLgLQgMgOgSAAQgVAAgLAOgAw/BGQgLgCgKgMQgJgJgDgOQgEgMAAgTQAAgMAEgOQADgOAKgJQAHgKANgGQALgGASAAQAgAAAOARQAOAQAAAkIgLAKIhYAAQAAAVALALQAMANAWAAIAVgCIAYgHIAIATIgXAHIggADQgWAAgLgFgAwAgIIgCgTQgDgJgFgEIgKgGIgOgDQgSAAgKAMQgJAIgCAVIBJAAgAzrBEQgTgJgKgMQgMgMgEgVQgEgOgBgZQAAgZAHgOQAFgQAMgQQALgOAUgHQATgIAXAAQAWAAAPADQASAGAJADIgIAVIgdgJIgagDQgiABgRAUQgTATABAnQAAAnAQAVQASASAhABIARAAIAbgHIAQgGIAIAUQgMAGgVAEQgPAEgUAAQgbAAgTgHgAnpBGIgYgLIALgUQACADAHADQAIADACAAIANAFIANABQAOgBAJgGQAIgDABgOQAAgJgHgFQgFgGgPAAIgiAAIAAgSIAeAAQAOAAAGgHQAHgGAAgHQAAgMgIgEQgGgFgNAAQgLAAgMAEIgTAIIgKgSIAWgJIAPgEIATgBQAaAAALAKQALAKAAAPQAAAWgTAMQANABAFAIQAHAKAAALQgBAUgPAMQgNAMgeAAQgSAAgOgEgATTBGIAAhzIgwAAIAAgUIB7AAIAAAUIgxAAIAABzgAR1BGIAAg9IhGAAIAAA9IgYAAIAAiHIAYAAIAAA3IBGAAIAAg3IAZAAIAACHgANEBGIAAhcIgXAjQgFAJgGAEIgLACIgMgCIgLgMIgWgkIAABcIgaAAIAAiHIAYAAIApBCIADADIADABIADgBIAshFIAXAAIAACHgAHFBGIAAiHIBfAAIAAAUIhGAAIAABzgAAgBGIAAhXIhDBEIAAATIgYAAIAAiHIAYAAIAABWIBDhCIAAgUIAYAAIAACHgAh6BGIAAhXIhEBEIAAATIgYAAIAAiHIAYAAIAABWIBEhCIAAgUIAZAAIAACHgAkWBGIAAg9IhDAAIAAA9IgZAAIAAiHIAZAAIAAA3IBDAAIAAg3IAaAAIAACHgArNBGIAAhXIhEBEIAAATIgYAAIAAiHIAYAAIAABWIBEhCIAAgUIAZAAIAACHgAgghgQgOgKgEgRIAWgGQABAJAJAGQAIAIAKAAQANAAAHgIQAHgDADgMIAVAGIgGAQIgMALIgPAHQgFACgNAAQgSAAgOgJgAsPhgQgOgKgEgRIAWgGQABAJAJAGQAHAIAOAAQAMAAAIgIQAGgDAEgMIAUAGIgGAQIgMALIgPAHQgFACgMAAQgVAAgOgJg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-131,-13,262,26.1);


(lib.pr = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AtvRNMAAAgiZIbfAAMAAAAiZg");
	this.shape.setTransform(88,110.1);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,176,220.3);


(lib.log = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.l();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,80,55);


(lib.logo = function() {
	this.initialize();

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E1192C").s().p("AAnBjQgogpAAg6QAAg5AogqQApgpA8gBQA6ABApApQAqAqABA5QgBA6gqApQgpAqg6ABQg7gBgqgqgABTg+QgXAaABAkQgBAkAXAbQAXAaAiABQAggBAXgaQAXgbAAgkQAAgkgXgaQgXgbggABIgBAAQghAAgXAagAoFBjQgpgpAAg6QAAg5ApgqQAqgpA7gBQA6ABAqApQApAqABA5QgBA6gpApQgqAqg6ABQg7gBgqgqgAnYg+QgXAaAAAkQAAAkAXAbQAXAaAhABQAggBAXgaQAXgbAAgkQAAgkgXgaQgXgbggABIgBAAQghAAgWAagALYCGIgXg8IhsAAIgXA8IhHAAIBwkHIBLAAIBtEHgAJnAeIBLAAIglhggAF/CGIAAjXIhWAAIAAgwIDkAAIAAAwIhSAAIAADXgAipCGIAAhlIhpiiIBHAAIBABwIBDhwIBEAAIhpCiIAABlgArLCGIAAjXIhTAAIAAgwIDhAAIAAAwIhTAAIAADXg");
	this.shape.setTransform(-0.8,70.7);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-80.7,56.5,159.9,28.5);


(lib.corolla = function() {
	this.initialize();

	// Layer 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("EhjeAMpIAA5RMDG9AAAIAAZRg");
	mask.setTransform(636.7,81);

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#2D3538").s().p("AtVLFQi2gCg5hOQg3hLA1iZQBDjQCJjvQCPj7CQiXQB5h+DHhGQC7hCDEADIP9AAImSEaInDAAQjIgDh4BOQhuBHhjCuQh5DshyEOIUAAAIlOE0g");
	this.shape.setTransform(112.2,71.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#2D3538").s().p("ArZLQQkpglgzjPQgvjACklgQCMkhCYiSQDEi9ESgWQB/gNBbgCQCtgIC7AJQCOAHDJAVQCHAOBaBBQBeBDAgBxQAfBwglCJQggB5hYDaQgnBkgnBZQgmBXgYAoQg7Bih4BBQioBakMAQIitACIiQAAQlaAAkDgOgAAUm7QgYAAgzAEQiYAOhcB+QgjAvgrBVQgyBngdA3QhyDxgHBOQgLBuCGAOQBtAGCEgDIDpgFQAOgCAbAAQCagHA+gsQAYgRARgaQAKgPARgfQAohDBTixQBgjJAThHQAvh8gTgoQgTgsh0gHQhvgKhwAAQhlAAiEAIg");
	this.shape_1.setTransform(294.8,73.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#2D3538").s().p("AG1MKQnOmbk+onIKXAKQA9gEAfg/QAahRAPgkQAWhFgPgeQgRgjhJgGIp0gOImlRkIojAAIJq2EINxAAQFNgCCrBxQCiBrgKC/QgKCigsBzQhHC4iSAaIk0AAQE8FCGHEPQBFAvBlBBg");
	this.shape_2.setTransform(498.8,81.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#2D3538").s().p("ArYLOQhvgMhNgnQikhRgGi/QgGizCFkcQAihFAJgQQCDj4CWiDQC5ihD7gVQB8gNBegCQCtgIC7AJQCOAHDIAVQCLAPBbBCQBdBEAeBvQAeBvglCHQgjCChRDLQhgD0gxBQQg6Bih4BBQioBakMAQIitACIiFAAQlkAAkCgQgAATm9IhMAGQiYAOhcB9QgiAvgrBVQgyBmgdA3QhxDzgHBNQgLBuCEANQBwAHCCgCQBLgCCegFIArAAQCYgHA+gsQAYgRARgaQAKgPARgfQAnhCBViyQBgjIAThIQAuh8gTgpQgTgrh0gJQhtgIhyAAQhgAAiJAGg");
	this.shape_3.setTransform(696.2,73.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#2D3538").s().p("AZnLIICDmhIiFAMQmRAqjyBBIkNEqI5MAAIBjjvIj4DvI2gAAIJc16IJjAAQizCHg9CTQi6GehUE/QgTBDAeAKQAMAEAeAAIBEgCIN+AAIHUxGIJhAAQipCKgpBXQiXFCh9GLQgpB3ATAYQAHAJASAAIAgAAIHMAAIK0qeQESkMFVhpQC7g4DTgMQDMgMDuAdIk+V6gAZlkRQiuBmihDMIIngGIB6mTQiuAIikBfg");
	this.shape_4.setTransform(1025.7,71.5);

	this.shape.mask = this.shape_1.mask = this.shape_2.mask = this.shape_3.mask = this.shape_4.mask = mask;

	this.addChild(this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0.1,1273.4,161.9);


(lib.bgImg6_1 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.bgImg6();
	this.instance.setTransform(-150,-300);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-150,-300,300,600);


(lib.bgImg5_1 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.bgImg5();
	this.instance.setTransform(-150,-300);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-150,-300,300,600);


(lib.bgImg4_1 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.bgImg4();
	this.instance.setTransform(-150,-300);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-150,-300,300,600);


(lib.bgImg3_1 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.bgImg3();
	this.instance.setTransform(-150,-300);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-150,-300,300,600);


(lib.bgImg2_1 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.bgImg2();
	this.instance.setTransform(-150,-300);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-150,-300,300,600);


(lib.bgImg1_1 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.bgImg1();
	this.instance.setTransform(-150,-300);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-150,-300,300,600);


(lib.bg = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("EgXbAu3MAAAhdtMAu3AAAMAAABdtg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-150,-300,300,600);


(lib.ALWAYS_mc = function() {
	this.initialize();

	// red
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#AAABAB").s().p("ADsAXIgEgFIgEgDIgEgCIgEgBIgFAAIAAAoIgWAAIAAhqIAoAAQAJAAAGACQAHABAFAEQAFAEADAGQADAFAAAJQAAAGgCAFIgFAJIgHAFQgEADgFABIAEAEIAFAEIAXAcIgRANgADXgEIAPAAQAIAAAFgEQAFgEAAgIQAAgFgBgDQgCgDgCgCIgGgCIgHAAIgPAAgABiA0IAAhqIBNAAIAAATIg4AAIAAAXIArAAIAAARIgrAAIAAAcIA6AAIAAATgAAeA0IAAhXIgeAAIAAgTIBVAAIAAATIggAAIAABXgAg8A0IAAhXIgfAAIAAgTIBWAAIAAATIggAAIAABXgAizA0IAAhqIBOAAIAAATIg3AAIAAAXIAqAAIAAARIgqAAIAAAcIA5AAIAAATgAkXA0IAAhqIAqAAQAIAAAGACQAIABAFADQAEAEADAFQADAFAAAIQAAAIgEAFQgDAGgGADIAHAEIAGADQACADACAFQABAEAAAFQAAAIgCAGQgDAGgFAEQgFAEgHACQgHACgJAAgAkCAiIAYAAIAGgBQADgBACgCIAEgEQABgDABgDQgBgFgBgCQgCgDgDgCIgGgCIgIgBIgUAAgAkCgKIATAAQAHAAAFgDQAEgDAAgHQAAgHgEgDQgGgCgKAAIgPAAg");
	this.shape.setTransform(31.2,29.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#A6A8A9").s().p("AFWBuIgqAAIgKAhIgVgFIAahWIADgJIAGgHQACgCAGgCQAEgBAHAAIAKABIAIAEQADADABADIAEAJIAaBXIgXAFgAE+AzIgCAEIgLAkIAgAAIgKgkIgDgEIgCgBIgEABgADOCOQgGgCgFgDIgLAFQgFABgHAAQgJAAgFgCQgGgCgFgEQgDgEgCgGIgEgMIgJhPIAWgDIAKBOQABAIACADQAEADAGAAIAFAAIAFgCIAAhYIAXAAIAABYIAEACIAFAAQAGAAADgDQAEgDABgIIAJhOIAWADIgJBPIgDAMQgDAGgEAEQgEAEgFACQgHACgIAAQgHAAgFgBgAGgCNIAAglQgGgCgEgFIgHgMIgVguIAUgIIAXAxIADAEIAEABIAEgBIACgEIAXgxIAUAIIgUAsQgEAIgEAGQgEAFgGACIAAAlgAEYg/IgrAAIgKAhIgVgFIAahWIADgJIAGgHQADgCAFgCQAFgBAGAAIAKABIAIAEQADADABADIAEAJIAbBXIgXAFgAEAh6IgDAEIgKAkIAgAAIgLgkIgCgEIgDgBIgDABgABsgeIgLgDIgKgCIgHgDIAHgTQAJAEAJACIARACQALAAAGgEQAGgEAAgGQAAgEgCgCQgBgDgEgBIgGgDIgKgCIgOgDQgGgCgFgDQgFgEgEgFQgDgGAAgIQAAgHADgGQACgGAFgFQAGgEAIgDQAJgCALAAQAMAAAJACIARAFIgFASIgSgEQgIgCgIAAQgKAAgEADQgGADAAAGIABAFIAFAEIAGACIAJACIAOAEQAHABAGAEQAFAEAEAGQADAFABAJQAAAIgEAHQgDAGgGAFQgGAEgIADQgJACgLAAIgOAAgAg5g/IgqAAIgKAhIgWgFIAahWIAEgJIAFgHQADgCAFgCQAEgBAHAAIAKABIAIAEQADADACADIADAJIAaBXIgWAFgAhRh6IgCAEIgLAkIAgAAIgKgkIgDgEIgDgBIgDABgAjCgfQgGgCgFgDIgKAFQgGABgGAAQgJAAgGgCQgGgCgEgEQgEgEgCgGIgDgMIgJhPIAVgDIAKBOQABAIADADQADADAHAAIAEAAIAGgCIAAhYIAWAAIAABYIAFACIAFAAQAFAAAEgDQADgDABgIIAJhOIAXADIgKBPIgDAMQgCAGgEAEQgEAEgGACQgGACgIAAQgHAAgGgBgAmSg/IgrAAIgKAhIgVgFIAahWIADgJIAGgHQADgCAFgCQAFgBAGAAIAKABIAIAEQADADABADIAEAJIAbBXIgXAFgAmqh6IgDAEIgKAkIAgAAIgLgkIgCgEIgDgBIgDABgAAPggIAAglQgHgCgDgFIgFgMIgVguIAUgIIAUAxIAEAEIADABIAEgBIADgEIAWgxIAUAIIgUAsQgEAIgEAGQgEAFgGACIAAAlgAllggIAAhsIAWAAIAABZIA5AAIAAATg");
	this.shape_1.setTransform(50,20.8);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,99.9,41);


(lib.logo_ = function() {
	this.initialize();

	// ЗАВЖДИ КРАЩЕ
	this.instance = new lib.log();
	this.instance.setTransform(0.5,42.5,1,1,0,0,0,40,27.5);

	// ALWAYS A BETTER WAY
	this.instance_1 = new lib.ALWAYS_mc("synched",0);
	this.instance_1.setTransform(-0.4,187.3,1,1,0,0,0,49.8,21.3);

	// logo
	this.instance_2 = new lib.logo();
	this.instance_2.setTransform(0.5,42,0.582,0.581);

	// Layer 5
	this.instance_3 = new lib.pr();
	this.instance_3.setTransform(0,106.5,0.693,0.967,0,0,0,88,110.1);

	this.addChild(this.instance_3,this.instance_2,this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-61,0,122,213);


(lib.banner = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// urText
	this.instance = new lib.urText();
	this.instance.setTransform(0,151.8);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(275).to({_off:false},0).to({alpha:1},10).wait(36).to({alpha:0},10).to({_off:true},1).wait(10));

	// logoZnack
	this.instance_1 = new lib.logo_("synched",0);
	this.instance_1.setTransform(138.1,-299.9,0.631,0.631,0,0,0,60.9,0);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(260).to({startPosition:0},0).to({regX:61,scaleX:1.71,scaleY:1.71,x:104},15).wait(46).to({startPosition:0},0).to({regX:60.9,scaleX:0.63,scaleY:0.63,x:138.1},10).wait(11));

	// bgImg
	this.instance_2 = new lib.bgImg6_1();
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(250).to({_off:false},0).to({alpha:1},10).wait(71).to({alpha:0},10).wait(1));

	// corolla
	this.instance_3 = new lib.corolla();
	this.instance_3.setTransform(-47.6,-7.9,0.138,0.138,0,0,0,636.7,81.1);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(169).to({_off:false},0).to({alpha:1},30,cjs.Ease.get(-0.5)).to({_off:true},61).wait(82));

	// t1_2
	this.instance_4 = new lib.t1_2();
	this.instance_4.setTransform(-32.7,-52.9);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(139).to({_off:false},0).to({alpha:1},14).to({_off:true},107).wait(82));

	// t1_1
	this.instance_5 = new lib.t1_1();
	this.instance_5.setTransform(-4.6,-84.6);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(125).to({_off:false},0).to({alpha:1},14).to({_off:true},121).wait(82));

	// bgImg
	this.instance_6 = new lib.bgImg5_1();
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(100).to({_off:false},0).to({alpha:1},25).to({_off:true},135).wait(82));

	// bgImg
	this.instance_7 = new lib.bgImg4_1();
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(75).to({_off:false},0).to({alpha:1},25).to({_off:true},25).wait(217));

	// bgImg
	this.instance_8 = new lib.bgImg3_1();
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(50).to({_off:false},0).to({alpha:1},25).to({_off:true},25).wait(242));

	// bgImg
	this.instance_9 = new lib.bgImg2_1();
	this.instance_9.alpha = 0;
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(25).to({_off:false},0).to({alpha:1},25).to({_off:true},25).wait(267));

	// bgImg
	this.instance_10 = new lib.bgImg1_1();

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(342));

	// bg
	this.instance_11 = new lib.bg();

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(342));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,-300,300,600);


// stage content:
(lib._300x600 = function() {
	this.initialize();

	// cover
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#666666").ss(2,1,1).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape.setTransform(150,300);

	// banner
	this.instance = new lib.banner();
	this.instance.setTransform(150,300);

	this.addChild(this.instance,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(149,299,302,602);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;