(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.bg = function() {
	this.initialize(img.bg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.bg2 = function() {
	this.initialize(img.bg2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.ob1 = function() {
	this.initialize(img.ob1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,272,294);


(lib.ob2 = function() {
	this.initialize(img.ob2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,260,344);


(lib.ob3 = function() {
	this.initialize(img.ob3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,278,334);


(lib.ob4 = function() {
	this.initialize(img.ob4);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,188,314);


(lib.ob5 = function() {
	this.initialize(img.ob5);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,264,278);


(lib.shadow = function() {
	this.initialize(img.shadow);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,242,26);


(lib.toy1 = function() {
	this.initialize(img.toy1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,54,124);


(lib.toy2 = function() {
	this.initialize(img.toy2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,38,102);


(lib.toy3 = function() {
	this.initialize(img.toy3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,50,162);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.urText = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AUsApIAAgEQAIABAFgMIABgCIgVgtIAFAAIASAnIAQgnIAFAAIgTAwQgGAOgLAAIgBAAgAPcApIAAgEQAJABAFgMIABgCIgVgtIAFAAIASAnIAQgnIAEAAIgTAwQgFAOgLAAIgCAAgATxApIAAg+IAFAAIAAAKQAGgLANAAQAJAAAHAHQAHAGAAAJQAAALgHAGQgHAHgJAAQgOAAgFgLIAAAcgAT7gMQgGAFABAHQgBAJAGAFQAFAGAJAAQAHAAAGgGQAFgGABgIQgBgGgFgGQgGgGgHAAQgJAAgFAGgADJApIAAg+IAEAAIAAAKQAGgLANAAQAKAAAHAHQAGAGABAJQgBALgGAGQgHAHgKAAQgOAAgFgLIAAAcgADTgMQgGAGAAAGQAAAIAGAGQAFAGAIAAQAIAAAGgGQAFgFAAgJQAAgHgFgFQgGgGgIAAQgIAAgFAGgAmBApIAAg+IAEAAIAAAKQAHgLANAAQAJAAAHAHQAHAGAAAJQAAALgHAGQgGAHgKAAQgOAAgGgLIAAAcgAl3gMQgFAGgBAGQABAIAFAGQAGAGAHAAQAJAAAFgGQAGgFgBgJQABgHgGgFQgFgGgJAAQgHAAgGAGgAyRApIAAg+IAEAAIAAAKQAGgLAOAAQAJAAAHAHQAHAGAAAJQAAALgHAGQgGAHgKAAQgOAAgGgLIAAAcgAyHgMQgFAGgBAGQABAIAFAGQAGAGAHAAQAJAAAFgGQAGgFgBgJQABgHgGgFQgFgGgJAAQgHAAgGAGgAPNAjIAAgMIgnAAIAAAMIgEAAIAAgQIAFAAQAFgHAAgMIAAgVIAfAAIAAAoIAHAAIAAAQgAOwAAQAAALgEAIIAbAAIAAgkIgXAAgACeAjIAAgMIgmAAIAAAMIgFAAIAAgQIAFAAQAFgHAAgMIAAgVIAgAAIAAAoIAGAAIAAAQgACCAAQgBAMgDAHIAaAAIAAgkIgWAAgAmRAjIAAgMIgnAAIAAAMIgFAAIAAgQIAGAAQAEgHAAgMIAAgVIAgAAIAAAoIAGAAIAAAQgAmuAAQAAALgEAIIAaAAIAAgkIgWAAgAVTAXQgDgDADgDQADgDACADQADADgDADIgDABIgCgBgAzDASQgGgHAAgKQAAgKADgGQADgGAKgGIANgFQAGgDAAgFIAEACQgBAFgEADIgEACIgLAFIgKAGQgDADgBAHQAHgKAMAAQAJAAAGAGQAFAGAAAIQAAAJgGAGQgGAGgJAAQgKAAgHgGgAy/gIQgFAEAAAGQAAAHAEAGQAGAFAIAAQAGAAAGgFQAFgFAAgHQAAgGgFgFQgFgFgHAAQgGAAgHAFgAS5ARQgHgGAAgLQAAgJAHgGQAHgHAKAAQANAAAGALIAAgKIAEAAIAAAsIgEAAIAAgKQgGALgNAAQgKAAgHgHgAS8gMQgGAGABAGQgBAIAGAGQAFAGAJAAQAHAAAGgGQAFgFABgJQgBgHgFgFQgGgGgHAAQgJAAgFAGgARQARQgGgHgBgKQABgIAGgHQAIgHAJAAQAKAAAHAHQAHAHAAAIQAAAKgHAHQgGAHgLAAQgKAAgHgHgARUgMQgFAFAAAHQAAAJAFAFQAGAGAHAAQAIAAAGgGQAGgGgBgIQABgGgGgGQgGgGgIAAQgHAAgGAGgAJtARQgGgGAAgLQAAgJAGgGQAIgHAJAAQAKAAAGAHQAIAGAAAJQAAALgIAGQgGAHgKAAQgKAAgHgHgAJxgMQgGAGAAAGQAAAIAGAGQAFAGAIAAQAIAAAGgGQAFgGAAgIQAAgGgFgGQgGgGgIAAQgIAAgFAGgAIQARQgHgGAAgLQAAgJAHgGQAIgHAJAAQAJAAAIAHQAGAGABAJQgBALgGAGQgHAHgKAAQgKAAgHgHgAIUgMQgGAGAAAGQAAAIAGAGQAFAGAIAAQAIAAAGgGQAFgFAAgJQAAgHgFgFQgGgGgIAAQgIAAgFAGgAE/ARQgHgHAAgKQAAgIAHgHQAHgHAKAAQANAAAGALIAAgKIAEAAIAAAsIgEAAIAAgKQgGALgNAAQgKAAgHgHgAFCgMQgGAGABAGQgBAIAGAGQAHAGAHAAQAHAAAGgGQAGgGAAgIQAAgGgGgGQgGgGgHAAQgHAAgHAGgAEIARQgGgGgBgLQABgJAGgGQAGgHALAAQAJAAAGAHQAHAHAAAJIAAACIgpAAQAAAHAGAFQAGAFAHAAQAMAAADgJIAFADQgHAKgNAAQgLAAgGgHgAEqgBQAAgIgFgEQgFgFgHAAQgIAAgFAFQgFAFgBAHIAkAAIAAAAgAhCARQgGgHgBgKQABgIAGgHQAIgHAJAAQAOAAAGALIgDADQgFgKgMAAQgIAAgFAGQgFAFAAAHQAAAJAFAFQAFAGAIAAQAMAAAFgKIADADQgGALgOAAQgKAAgHgHgAk1ANIAEgCQADAJAKAAQAMAAAAgJQAAgJgKAAIgFAAIAAgDIAEAAQAJAAAAgIQAAgJgKAAQgJAAgDAIIgEgDQAFgJALAAQAGAAAFAEQAEAEAAAEQAAAIgGACQAIADAAAIQAAANgRAAQgNAAgEgLgApJARQgGgGAAgLQAAgJAGgGQAHgHAKAAQAKAAAGAHQAGAHABAJIAAACIgqAAQABAHAGAFQAFAFAHAAQAMAAAEgJIAEADQgGAKgOAAQgKAAgHgHgAongBQABgIgGgEQgFgFgHAAQgIAAgEAFQgFAFgCAHIAkAAIAAAAgAq4ARQgGgGAAgLQAAgJAGgGQAIgHAJAAQAKAAAHAHQAHAHAAAIQAAAKgHAHQgGAHgLAAQgKAAgHgHgAq0gMQgFAFAAAHQAAAJAFAFQAFAGAIAAQAJAAAFgGQAFgGAAgIQAAgGgFgGQgFgGgJAAQgIAAgFAGgAvcARQgGgHAAgKQAAgJAGgGQAHgHAKAAQAKAAAGAHQAGAHAAAJIAAACIgpAAQACAHAEAFQAGAFAIAAQAKAAAFgJIAEADQgGAKgOAAQgKAAgHgHgAu6gBQgBgIgEgEQgFgFgHAAQgIAAgFAFQgFAFgBAHIAkAAIAAAAgAxRARQgHgGAAgLQAAgJAHgGQAHgHAJAAQANAAAHALIAAgKIAEAAIAAAsIgEAAIAAgKQgHALgNAAQgKAAgGgHgAxOgMQgGAFAAAHQAAAJAGAFQAGAGAHAAQAJAAAFgGQAGgGAAgIQAAgGgGgGQgFgGgJAAQgHAAgGAGgAz7ARQgHgHAAgKQAAgIAHgHQAHgHAKAAQAJAAAHAHQAIAHgBAIQABAKgIAHQgGAHgKAAQgKAAgHgHgAz4gMQgGAGAAAGQAAAIAGAGQAGAGAIAAQAHAAAGgGQAGgFAAgJQAAgHgGgFQgGgGgHAAQgIAAgGAGgA02AKIAEgCQADALAPAAQAQAAAAgNQAAgFgEgDQgEgEgHAAIgHAAIAAgEIAFAAQAGAAAFgEQADgDAAgGQAAgNgOAAQgMAAgEALIgEgCQAFgNAPAAQAIAAAGAFQAGAFAAAHQAAAKgKAEQAMAEAAALQgBAJgFAEQgGAFgJAAQgSAAgEgOgAM+AXIAAgEQALABAAgQIAAgZIAfAAIAAAsIgEAAIAAgoIgXAAIAAAVQAAATgNAAIgCAAgAFyAXIAAgEQAKABAAgQIAAgZIAfAAIAAAsIgEAAIAAgoIgXAAIAAAVQAAATgMAAIgCAAgASFAXIAAgsIAUAAQAOAAAAAMQAAAHgGACQAJACgBAJQABAMgOAAgASKATIASAAQAJAAAAgJQAAgIgJAAIgSAAgASKgBIAPAAQAJAAAAgIQAAgIgJAAIgPAAgAQwAXIAAgoIgQAAIAAgEIAlAAIAAAEIgRAAIAAAogAOSAXIAAgSIgKAAIgOASIgFAAIAOgSQgNgCABgKQgBgHAEgDQAGgEAFAAIASAAIAAAsgAN+gOQgDADAAAEQAAAEADADQADABAEAAIANAAIAAgSIgNAAQgEAAgDADgAMgAXIAAgsIAdAAIAAAEIgYAAIAAAogAMMAXIAAgkIgcAkIgEAAIAAgsIAEAAIAAAkIAcgkIAFAAIAAAsgAK8AXIAAgsIAUAAQAOAAgBAMQAAAHgFACQAHACAAAJQAAAMgNAAgALBATIARAAQAJAAAAgJQAAgIgJAAIgRAAgALBgBIAPAAQAJAAAAgIQAAgIgJAAIgPAAgAJFAXIAAgsIAcAAIAAAEIgXAAIAAAogAH4AXIAAgUIgcAAIAAAUIgEAAIAAgsIAEAAIAAAUIAcAAIAAgUIAFAAIAAAsgAGsAXIAAgsIAEAAIAAARIANAAQAGAAAEAEQAFADAAAGQAAAGgFAEQgDAEgHAAgAGwATIANAAQAKAAAAgKQAAgEgCgDQgDgCgFAAIgNAAgABkAXIAAgsIAEAAIAAAsgAA0AXIAAgsIAVAAQANAAAAAMQgBAHgFACQAIACAAAJQAAAMgOAAgAA5ATIARAAQAKAAAAgJQAAgIgKAAIgRAAgAA5gBIAQAAQAIAAAAgIQAAgIgIAAIgQAAgAgRAXIAAgsIAEAAIAAARIANAAQAFAAAGAEQADADAAAGQAAAGgDAEQgFAEgGAAgAgNATIANAAQAEAAADgDQADgDAAgEQAAgEgDgDQgDgCgEAAIgNAAgAhaAXIAAgkIgcAkIgEAAIAAgsIAEAAIAAAkIAdgkIAEAAIAAAsgAiZAXIAAgoIgQAAIAAgEIAlAAIAAAEIgQAAIAAAogAi4AXIAAgSIgJAAIgPASIgFAAIAOgSQgNgCAAgKQAAgGAEgEQAGgEAFAAIASAAIAAAsgAjMgOQgDADAAAEQAAAIAKAAIANAAIAAgSIgNAAQgEAAgDADgAjmAXIAAgUIgcAAIAAAUIgFAAIAAgsIAFAAIAAAUIAcAAIAAgUIAEAAIAAAsgAlFAXIAAgsIAFAAIAAAsgAnMAXIAAgsIAFAAIAAAsgAn8AXIAAgsIAUAAQAOAAAAAMQAAAHgGACQAIACAAAJQAAAMgOAAgAn3ATIARAAQAJAAAAgJQAAgIgJAAIgRAAgAn3gBIAPAAQAKAAgBgIQABgIgKAAIgPAAgApZAXIgUgWIAAAWIgEAAIAAgWIgUAWIgGAAIAVgXIgUgVIAGAAIATAUIAAgUIAEAAIAAAUIATgUIAGAAIgUAVIAUAXgArQAXIAAglIgQAZIgBAAIgRgZIAAAlIgFAAIAAgsIAGAAIARAZIAQgZIAFAAIAAAsgAslAXIAAgSIgJAAIgOASIgGAAIAOgSQgNgBABgLQAAgGAEgEQAFgEAGAAIARAAIAAAsgAs5gOQgDADAAAEQAAAIALAAIAMAAIAAgSIgMAAQgFAAgDADgAtTAXIAAgUIgcAAIAAAUIgFAAIAAgsIAFAAIAAAUIAcAAIAAgUIAEAAIAAAsgAuIAXIAAgUIgcAAIAAAUIgFAAIAAgsIAFAAIAAAUIAcAAIAAgUIAEAAIAAAsgAvsAXIgUgWIAAAWIgFAAIAAgWIgTAWIgGAAIAVgXIgUgVIAFAAIATAUIAAgUIAFAAIAAAUIATgUIAFAAIgUAVIAVAXgA1NgaIgFAIIgDgCIAFgHIgJAAIAAgEIAJAAIgFgHIADgCIAFAHIAEgHIAEACIgFAHIAJAAIAAAEIgJAAIAFAHIgEACgABigkQAAgDAEAAQABAAABAAQAAAAABABQAAAAAAABQAAABAAAAQABAEgEAAQgEAAAAgEgAlHgkQAAAAABgBQAAgBAAAAQABgBAAAAQABAAABAAQAEAAAAADQAAAEgEAAQgDAAgBgEgAnOgkQAAgDAFAAQAAAAABAAQABAAAAABQABAAAAABQAAABAAAAQAAAEgDAAQgFAAAAgEg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.urText, new cjs.Rectangle(-136.9,-4.1,273.9,8.2), null);


(lib.toy3_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgEEsIAApXIAJAAIAAJXg");
	this.shape.setTransform(0,-21);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Слой_1
	this.instance = new lib.toy2();
	this.instance.parent = this;
	this.instance.setTransform(-19,-51);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.toy3_1, new cjs.Rectangle(-19,-51,38,102), null);


(lib.toy2_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgEIXIAAwtIAJAAIAAQtg");
	this.shape.setTransform(-0.2,-27.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Слой_1
	this.instance = new lib.toy3();
	this.instance.parent = this;
	this.instance.setTransform(-25,-81);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.toy2_1, new cjs.Rectangle(-25,-81,50,162), null);


(lib.toy1_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgEFyIAArjIAJAAIAALjg");
	this.shape.setTransform(0,-25);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Слой_1
	this.instance = new lib.toy1();
	this.instance.parent = this;
	this.instance.setTransform(-27,-62);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.toy1_1, new cjs.Rectangle(-27,-62,54,124), null);


(lib.t7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#EA1873").s().p("AkeJUIAAlWIBOAAIAAFWgAmIJUIAAh3QgbALgfAAQg0AAgkgeQgjgeAAg0IAAh6IBPAAIAABuQAAAYAMAMQANAMAVAAQAfAAAZgLIAAiTIBPAAIAAFWgAslJUIAAlWIDVAAIAABLIiHAAIAAA5IB6AAIAABKIh6AAIAAA9ICJAAIAABLgAwnJUIAAlWICCAAQAzAAAiAiQAjAiAAAxQAAAygjAhQgiAjgzAAIgzAAIAABrgAvYGfIAzAAQASAAAMgMQAMgNAAgTQAAgSgMgNQgMgNgSAAIgzAAgAn2B/Qg0gzAAhMQAAhKA0g0QAzgzBLAAQBLAAAzAzQA0A0AABKQAABMg0AzQgzAzhLAAQhLAAgzgzgAm/hIQgdAdAAArQAAAtAdAdQAcAcArAAQArAAAcgcQAdgdAAgtQAAgsgdgcQgcgdgrAAQgrAAgcAdgAPRCsIAAiJIhsAAIAACJIhPAAIAAlWIBPAAIAACDIBsAAIAAiDIBOAAIAAFWgAG4CsIAAhMIAjAAQAbgmAAhLIAAiZIDmAAIAAEKIAkAAIAABMgAJEgQQAABKgWAmIBfAAIAAjBIhJAAgAFZCsIAAlWIBOAAIAAFWgAD5CsIg6hjIg5BjIhZAAIBmivIhiinIBaAAIA0BaIA1haIBZAAIhhCnIBmCvgAi3CsIAAlWIDcAAIAABLIiNAAIAAA0IA2AAQA0AAAgAeQAgAcAAAxQAAAwggAeQggAeg0AAgAhoBiIA2AAQAnAAAAgiQAAgjgnAAIg2AAgAsDCsIAAlWIDVAAIAABLIiHAAIAAA5IB7AAIAABJIh7AAIAAA9ICKAAIAABMgAtsCsIAAiJIhsAAIAACJIhOAAIAAlWIBOAAIAACDIBsAAIAAiDIBOAAIAAFWgAQ6CrIAAlVIBOAAIAAFVgAtNj9IAAgXQAkAFATgcQATgcAAhHIAAjFIDZAAIAAFWIgbAAIAAk+IikAAIAACtQAABTgaAhQgVAegqAAIgLgBgADnj9IAAkmIjLEmIgXAAIAAlWIAaAAIAAEmIDLkmIAXAAIAAFWgAgxj9IisipIAACpIgaAAIAAlWIAaAAIAACfICnifIAiAAIitCmICyCwgAn0j9IAAlWIAaAAIAACCIBbAAQAuAAAeAeQAfAfAAAtQAAAugfAeQgeAeguAAgAnakVIBbAAQAjAAAXgXQAXgXAAgkQAAgjgXgXQgYgXgiAAIhbAAgAt9j9IAAlWIAaAAIAAFWgAwbj9IAAk+IhsAAIAAgYIDyAAIAAAYIhsAAIAAE+g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t7, new cjs.Rectangle(-115.9,-59.6,232,119.3), null);


(lib.t6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AJ6DuIAAioIAkAAIAAAMQAMgPAYAAQAXAAARASQAQASAAAbQAAAbgQASQgQASgYABQgYgBgMgPIAAA8gAKmBtQgJAIABANQgBAOAJAHQAHAJANgBQAMABAIgJQAJgHgBgOQABgNgJgIQgIgIgMAAQgNAAgHAIgAi3DeIAAggIhCAAIAAAgIgjAAIAAhBIAOAAQAKgPgBgbIAAgtIBhAAIAABXIAQAAIAABBgAjiBzQABAagHAQIAhAAIAAg2IgbAAgAMfCvQgRgSAAgbQAAgbARgSQAQgSAYAAQAXAAANAPIAAgMIAkAAIAAB4IgkAAIAAgMQgNAPgXABQgYgBgQgSgAM6BtQgIAIAAANQAAAOAIAHQAIAJANgBQAMABAIgJQAIgHAAgOQAAgNgIgIQgIgIgMAAQgNAAgIAIgAFyCvQgSgSAAgbQAAgbASgSQASgSAcAAQARAAAOAJQAOAHAJAOIggATQgHgNgQAAQgMAAgIAHQgHAIAAAMQAAAMAHAIQAIAIAMAAQARAAAGgNIAgASQgJAOgOAIQgOAIgRABQgcgBgSgSgApSCvQgRgSAAgdQAAgfAIgPQAKgSAcgOIAcgPQAKgGAEgMIAfARQgEAOgMAKQgJAHgUAIQgZAKgHANQAMgLAWAAQASAAAPANQAQAQAAAYQAAAYgQAPQgSAQgbABQgegBgRgSgAo1B3QgIAHAAALQgBAKAIAHQAIAHALAAQAKAAAIgGQAHgHAAgKQAAgLgHgHQgIgHgLAAQgKAAgHAGgArjCvQgTgSAAgbQAAgbATgSQASgSAbAAQAaAAATASQASASAAAbQAAAbgSASQgTASgaABQgbgBgSgSgArKBuQgHAIgBAMQABANAHAHQAIAJAMgBQAMABAHgJQAIgHAAgNQAAgMgIgIQgHgIgMAAQgMAAgIAIgAtyCvQgSgRAAgcQAAgbARgSQATgSAbAAQAaAAASASQARASAAAbQABAIgCAHIhVAAQAGAQAXAAQAOABAJgKIAdAQQgSAZgiABQgegBgTgSgAsrB2QgGgTgUAAQgVAAgEATIAzAAIAAAAgAOuC+IAAh4IA8AAQAUAAAKAKQAKAJAAAPQAAAQgLAJQAQAIABATQAAAPgLAKQgLAJgUAAgAPQCgIAaAAQALAAAAgJQAAgIgLAAIgaAAgAPQB0IAWAAQALAAAAgJQAAgIgLAAIgWAAgAI2C+IAAhWIgoAAIAABWIgkAAIAAh4IBwAAIAAB4gADqC+IgXggIgVAgIgqAAIArg9Igqg7IAqAAIAUAeIAVgeIAqAAIgqA7IArA9gABfC+IAAg8IgzA8IgbAAIAAh4IAjAAIAAA8IA0g8IAaAAIAAB4gAgxC+IAAgrIgpAAIAAArIgkAAIAAh4IAkAAIAAArIApAAIAAgrIAkAAIAAB4gAlVC+IAAh4IAkAAIAAB4gAmQC+IgXggIgWAgIgpAAIArg9Igpg7IAoAAIAVAeIAWgeIAoAAIgpA7IArA9gAvBC+IAAgrIgpAAIAAArIgkAAIAAh4IAkAAIAAArIApAAIAAgrIAkAAIAAB4gAlSA1QgGgGgBgJQABgIAGgHQAGgHAJAAQAJAAAGAHQAGAHABAIQgBAJgGAGQgGAHgJAAQgJAAgGgHgAuLgmIAAgfIh/AAIAAAfIgNAAIAAgsIAOAAQARgTAAgoIAAhgIBnAAIAACbIASAAIAAAsgAvriNQAAAmgPAVIBdAAIAAiPIhOAAgAB4hVQgSgSAAgbQAAgaASgSQASgRAagBQAjABAQAdIAAgbIANAAIAAB4IgNAAIAAgbQgQAdgjAAQgZAAgTgSgACBimQgPAPAAAVQAAAWAPAPQAPAPAVAAQAVAAAPgPQAOgPAAgWQAAgVgOgPQgQgPgUAAQgVAAgPAPgAmKhVQgRgRAAgcQAAgbARgRQARgSAdAAQARAAAOAIQAOAJAGAOIgKAFQgFgLgLgHQgLgGgOAAQgWAAgPAOQgPAQAAAUQAAAWAPAPQAOAPAXAAQAdAAANgZIALAGQgIAOgOAIQgOAIgRAAQgdAAgRgSgAtthFIAAgMQAOACAGgJQAIgKgBgWIAAhFIBVAAIAAB4IgMAAIAAhsIg9AAIAAA5QAAAzgjAAIgEAAgAK1hFIgog0IgpA0IgOAAIAvg+Igtg6IAPAAIAmAxIAlgxIAPAAIgtA6IAwA+gAIshFIAAhjIhLBjIgLAAIAAh4IAMAAIAABjIBMhjIALAAIAAB4gAENhFIAAh4IAMAAIAABsIA+AAIAAhsIAMAAIAABsIA9AAIAAhsIAMAAIAAB4gAgPhFIAAh4IA0AAQAQAAAKAJQAKAJAAAOQAAASgPAIQAUAHAAAVQAAAPgJAJQgKAKgSAAgAgEhRIAtAAQAMAAAHgGQAGgGABgKQAAgVgaAAIgtAAgAgEiIIApAAQAYAAgBgVQAAgJgFgGQgHgGgLABIgpAAgAiAhFIgog0IgpA0IgOAAIAwg+Igtg6IAOAAIAmAxIAmgxIAOAAIgtA6IAwA+gAkJhFIAAh4IAMAAIAAB4gAoShFIAAh4IA1AAQASAAAJAJQAJAJAAAOQAAASgPAIQAVAHAAAVQAAAPgKAJQgJAKgSAAgAoGhRIAuAAQAMAAAGgGQAHgGAAgKQAAgVgZAAIguAAgAoGiIIApAAQAYAAAAgVQAAgJgGgGQgHgGgLABIgpAAgAqMhFIAAgvIgbAAIglAvIgQAAIAngwQgPgBgJgKQgKgKAAgPQgBgPAMgLQAKgKASAAIAvAAIAAB4gArDirQgIAIAAAKQAAAMAIAGQAIAIALgBIAkAAIAAgxIgkAAQgLAAgIAGgAkMjkQgBgJALAAQAJAAAAAJQAAAKgJAAQgLAAABgKg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t6, new cjs.Rectangle(-104.7,-23.8,209.5,47.6), null);


(lib.t5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AD1DuIAAgiQAMAAAHgDQAGgEAEgJIguh2IAlAAIAcBKIAXhKIAnAAIgqB0QgSA0guAAIgEAAgApSDuIAAioIAkAAIAAALQANgOAXAAQAYAAARASQAQASABAbQgBAbgQASQgRASgYAAQgXAAgNgPIAAA8gAomBtQgHAHgBAOQABANAHAIQAJAIAMAAQAMAAAJgIQAHgIABgNQgBgOgHgHQgJgIgMAAQgMAAgJAIgAH/CvQgRgSAAgbQAAgbARgSQARgSAYAAQAWAAAOAOIAAgLIAkAAIAAB4IgkAAIAAgMQgNAPgXAAQgYAAgRgSgAIaBtQgHAHgBAOQABANAHAIQAJAIAMAAQAMAAAJgIQAHgIABgNQgBgOgHgHQgJgIgMAAQgMAAgJAIgAB9CvQgSgSAAgbQAAgbASgSQATgSAbAAQARAAAPAIQAOAIAIAOIgfASQgHgNgRAAQgLAAgIAIQgIAIAAAMQAAAMAIAIQAIAIALAAQASAAAGgOIAfASQgIAOgOAJQgPAIgRAAQgbAAgTgSgAibCvQgRgSAAgbQAAgbARgSQARgSAYAAQAXAAANAOIAAgLIAkAAIAAB4IgkAAIAAgMQgNAPgXAAQgYAAgRgSgAiABtQgHAHgBAOQABANAHAIQAJAIAMAAQAMAAAJgIQAHgIABgNQgBgOgHgHQgJgIgMAAQgMAAgJAIgAmrCvQgSgSAAgbQAAgbARgSQASgSAcAAQAaAAASASQARASAAAbQAAAIgBAGIhWAAQAHARAWAAQAPAAAJgJIAcAQQgSAZgiAAQgeAAgSgSgAlkB1QgGgTgUAAQgVAAgFATIA0AAIAAAAgArXCvQgSgSAAgbQAAgbASgSQASgSAbAAQAbAAASASQASASABAbQgBAbgSASQgSASgbAAQgbAAgSgSgAq+BtQgHAIAAANQAAAMAHAIQAIAIAMAAQAMAAAIgIQAHgIABgMQgBgNgHgIQgIgHgMAAQgMAAgIAHgAk3C+IAAgiQARAGAAgYIAAhEIBiAAIAAB4IgkAAIAAhWIgaAAIAAAkQAAAbgOANQgLAKgTAAIgJAAgANSC+IAAg8Ig0A8IgbAAIAAh4IAjAAIAAA8IA0g8IAbAAIAAB4gAKoC+IAAhWIglAAIAAgiIBtAAIAAAiIglAAIAABWgAF1C+IAAh4IA7AAQATAAAMAKQAKAJAAAPQAAAQgLAIQAQAJAAASQAAAQgLAJQgLAKgTAAgAGWCgIAaAAQALAAAAgJQAAgIgLAAIgaAAgAGWBzIAWAAQALAAAAgIQAAgIgLAAIgWAAgAA+C+Igng1IAAA1IgjAAIAAh4IAjAAIAAA0IAkg0IArAAIgsA8IAtA8gAsmC+IAAhWIgqAAIAABWIgkAAIAAh4IByAAIAAB4gAnHgWIAAgLQAXACANgeIACgGIg3h6IANAAIAxBqIAphqIANAAIg0CCQgGASgNAKQgMAJgNAAIgDAAgAh8hVQgTgSABgaQgBgbATgSQASgSAZAAQAjAAARAeIAAgbIAMAAIAAB3IgMAAIAAgbQgRAegjAAQgZAAgSgSgAh0imQgOAQAAAVQAAAVAOAPQAPAPAWAAQAVAAAOgPQAPgPAAgVQAAgWgPgPQgPgPgUAAQgVAAgQAPgAG9hGIAAhjIhMBjIgLAAIAAh3IANAAIAABjIBMhjIAKAAIAAB3gAExhGIAAh3IAMAAIAAB3gAD7hGIAAg2IhLAAIAAA2IgLAAIAAh3IALAAIAAA2IBLAAIAAg2IAMAAIAAB3gABvhGIAAg2IhMAAIAAA2IgMAAIAAh3IAMAAIAAA2IBMAAIAAg2IALAAIAAB3gAkFhGIAAh3IA1AAQASAAAJAJQAJAIAAAOQAAATgPAIQAVAHAAAVQAAAPgJAJQgKAJgSAAgAj5hRIAuAAQAZAAAAgWQAAgVgZAAIguAAgAj5iIIApAAQAYAAAAgVQAAgKgGgFQgHgGgLAAIgpAAgAF5jSIAAgLIA9AAIAAALgAEtjkQAAgJAKAAQAKAAgBAJQABAKgKAAQgKAAAAgKg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t5, new cjs.Rectangle(-88.4,-23.8,176.9,47.6), null);


(lib.t4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAbDXIAAinIAkAAIAAALQANgPAXAAQAYAAAQASQARATAAAaQAAAcgRASQgQASgYAAQgXAAgNgPIAAA7gABHBWQgIAIAAANQAAAOAIAIQAIAIANAAQAMAAAIgIQAIgIAAgOQAAgNgIgIQgIgHgMgBQgNABgIAHgAmaDXIAAinIAkAAIAAALQANgPAXAAQAXAAARASQARATAAAaQAAAcgRASQgRASgXAAQgYAAgMgPIAAA7gAluBWQgIAIAAANQAAAOAIAIQAIAIAMAAQANAAAIgIQAIgIAAgOQAAgNgIgIQgIgHgNgBQgMABgIAHgADACZQgRgSAAgcQAAgaARgTQARgSAXAAQAXAAANAPIAAgLIAkAAIAAB3IgkAAIAAgLQgMAPgYAAQgXAAgRgSgADbBWQgIAIAAANQAAAOAIAIQAIAIANAAQAMAAAIgIQAIgIAAgOQAAgNgIgIQgIgHgMgBQgNABgIAHgAhlCYQgRgSAAgdQAAgeAIgQQAKgRAbgOIAdgPQAKgGAFgLIAdAQQgDAOgMAJQgJAIgVAHQgZAKgGAOQAMgMAVAAQATAAAOAOQAQAPAAAYQAAAZgQAPQgRAQgbAAQgeAAgRgTgAhJBgQgIAIAAAKQAAAKAIAHQAHAIALAAQALgBAIgGQAHgHAAgKQAAgKgIgIQgHgGgLAAQgKAAgIAFgAISCnIAAg8IgzA8IgaAAIAAh3IAiAAIAAA7IA0g7IAaAAIAAB3gAFpCnIAAhVIglAAIAAgiIBsAAIAAAiIgkAAIAABVgAiyCnIAAg8Ig0A8IgaAAIAAh3IAjAAIAAA7IAzg7IAbAAIAAB3gAndCnIAAhVIgpAAIAABVIgkAAIAAh3IBxAAIAAB3gAgBhrQgSgSAAgaQAAgbASgSQARgTAbABQASgBAOAJQAOAJAGANIgJAGQgGgLgLgHQgMgHgOAAQgUAAgQAPQgOAPAAAWQAAAVAOAPQAPAPAVgBQAOABAMgIQALgGAGgMIAKAGQgHAOgOAJQgPAIgRAAQgbAAgRgSgAiYhrQgSgTAAgZQAAgbASgSQASgSAbAAQAbAAARASQATASAAAbQAAAZgTATQgSASgaAAQgbAAgSgSgAiPi8QgPAPAAAWQAAAUAPAQQAQAPAUgBQAVABAPgPQAPgQAAgUQAAgWgPgPQgPgPgVAAQgUAAgQAPgAnchrQgSgTAAgZQAAgbASgSQASgSAaAAQAjAAAQAeIAAgbIANAAIAAB3IgNAAIAAgbQgQAegjAAQgaAAgSgSgAnTi8QgPAOAAAXQAAAVAPAPQAPAPAVgBQAUABAQgPQAOgPAAgVQAAgXgOgOQgQgPgUAAQgVAAgPAPgApgh2IAKgFQAIAWAdAAQAPAAAIgGQAJgHAAgKQAAgLgHgFQgIgHgMAAIgQAAIAAgLIAMAAQALAAAHgHQAHgFAAgLQAAgJgIgGQgIgHgMAAQgYAAgJATIgKgFQALgZAgAAQASAAALAKQALAJAAAOQAAAUgRAHQALAEAGAIQAGAIAAAKQAAAPgMAKQgMAKgUAAQgkAAgLgdgAJVhcIAAhjIhNBjIgKAAIAAh3IAMAAIAABjIBMhjIALAAIAAB3gAHIhcIAAhlIgtBGIgBAAIgthHIAABmIgMAAIAAh3IAOAAIArBEIAshEIAOAAIAAB3gAErhcIAAgvIgaAAIgmAvIgPAAIAmgvQgPgCgJgJQgKgKAAgPQAAgQALgLQAMgKAQABIAwAAIAAB3gAD0jBQgIAHAAALQAAALAIAHQAIAHALAAIAkAAIAAgyIgkAAQgLAAgIAHgACZhcIAAhsIgrAAIAAgLIBjAAIAAALIgsAAIAABsgAkChcIAAh3IBLAAIAAALIg/AAIAABsg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t4, new cjs.Rectangle(-60.8,-21.5,121.8,43.1), null);


(lib.t3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AjcBvIAAgLQAXABAMgdIADgHIg4h5IANAAIAxBqIAphqIAOAAIg0CCQgHASgNAKQgLAJgOAAIgCAAgAIzBvIAAinIAjAAIAAALQAOgOAWAAQAYAAAQASQASASgBAaQABAbgSASQgQASgYAAQgWAAgOgOIAAA7gAJfgRQgJAIAAAMQAAANAJAIQAHAIANAAQANAAAHgIQAIgIAAgNQAAgMgIgIQgHgIgNAAQgNAAgHAIgAD+BfIAAggIhEAAIAAAgIgiAAIAAhCIAOAAQAKgOAAgaIAAgtIBhAAIAABVIAQAAIAABCgADTgLQAAAagHAOIAiAAIAAg1IgbAAgAGuAwQgRgRAAgcQAAgaARgSQATgSAbAAQAbAAARASQARASAAAaQABAIgCAGIhVAAQAGARAXAAQAPAAAHgJIAeARQgTAYgiAAQgeAAgTgSgAH1gIQgEgTgVAAQgVAAgFATIAzAAIAAAAgAp3AwQgSgSAAgbQAAgaASgSQASgSAbAAQARAAAPAJQAOAIAGAOIgKAGQgFgMgLgGQgLgHgPAAQgUAAgQAPQgOAPAAAUQAAAWAOAOQAPAPAVAAQAeAAANgZIAKAGQgGAOgPAIQgPAJgRAAQgbAAgSgSgAsWAwQgSgTAAgaQAAgZASgSQASgTAaAAQAjAAAQAeIAAgbIANAAIAAB3IgNAAIAAgbQgQAegjAAQgZAAgTgSgAsNggQgPAPAAAUQAAAVAPAPQAPAPAVAAQAUAAAQgPQAOgPAAgVQAAgUgOgPQgQgPgUAAQgVAAgPAPgAl4A/IAAgLQAPABAGgJQAHgJAAgWIAAhFIBUAAIAAB3IgLAAIAAhrIg9AAIAAA5QAAAygjAAIgFAAgAOKA/IAAg8IgyA8IgbAAIAAh3IAjAAIAAA7IAzg7IAaAAIAAB3gALhA/IAAhUIgkAAIAAgjIBrAAIAAAjIgjAAIAABUgAFLA/IAAhUIgkAAIAAgjIBsAAIAAAjIgkAAIAABUgABfA/IAAh3IAkAAIAAB3gAgfA/IAAh3IA7AAQATAAALAKQAKAJAAAPQAAAQgLAIQAQAIAAATQAAAPgLAJQgKAKgUAAgAABAhIAbAAQAKAAAAgJQAAgIgKAAIgbAAgAABgKIAWAAQALAAAAgJQAAgIgLAAIgWAAgAmfA/IAAhiIhMBiIgKAAIAAh3IALAAIAABiIBNhiIALAAIAAB3gAtVA/IAAg2IhMAAIAAA2IgLAAIAAh3IALAAIAAA2IBMAAIAAg2IAMAAIAAB3gABihJQgGgGAAgJQAAgJAGgGQAGgHAJAAQAJAAAHAHQAGAGAAAJQAAAJgGAGQgHAHgJAAQgJAAgGgHg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t3, new cjs.Rectangle(-94.1,-11,188.3,22.2), null);


(lib.t2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AkuBVIAAgLQAWACANgeIADgGIg3h5IAMAAIAxBpIAphpIAOAAIg0CBQgHASgNAKQgLAKgOAAIgCgBgAnLBVIAAimIANAAIAAAbQAHgOANgIQAOgIARAAQAbAAARASQASASAAAbQAAAZgSASQgSASgaAAQgRAAgOgIQgNgIgHgOIAABLgAmwg6QgOAQAAAVQAAAVAOAOQAQAPAUAAQAVAAAPgPQAPgOAAgVQAAgVgPgQQgPgPgVAAQgUAAgQAPgAApAXQgSgTAAgZQAAgbASgSQATgTAaAAQAbAAASATQATASAAAbQAAAZgTATQgSASgbAAQgaAAgTgSgABDgqQgIAIAAANQAAAMAIAIQAHAHAMAAQAMAAAIgHQAIgIAAgMQAAgNgIgIQgIgIgMAAQgMAAgHAIgApXAWQgTgSABgZQgBgbATgSQARgSAcAAQAaAAASASQASASAAAbQAAAZgSASQgTASgZAAQgcAAgRgSgApPg6QgPAQAAAVQAAAVAPAOQAQAPAVAAQAUAAAPgPQAPgOAAgVQAAgWgPgPQgPgPgUAAQgVAAgQAPgAKgAlIAAg6Ig0A6IgZAAIAAh2IAiAAIAAA8IAzg8IAbAAIAAB2gAH2AlIAAhUIgkAAIAAgiIBsAAIAAAiIgkAAIAABUgAGbAlIAAg6Ig0A6IgZAAIAAh2IAiAAIAAA8IAzg8IAbAAIAAB2gAELAlIAAg8IgaAoIgEAAIgbgoIAAA8IgjAAIAAh2IAjAAIAdAtIAcgtIAjAAIAAB2gAglAlIAAhVIgoAAIAABVIgkAAIAAh2IBwAAIAAB2gArCAlIAAh2IBLAAIAAALIg/AAIAABrg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t2, new cjs.Rectangle(-70.7,-8.5,141.4,17.1), null);


(lib.t1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AguDvIAAghQAMAAAHgEQAGgDAEgKIgvh2IAnAAIAbBKIAWhKIAmAAIgpB1QgRAzgtAAIgFAAgADbCxQgRgTAAgbQAAgaARgTQARgSAYAAQAWAAANAPIAAgMIAkAAIAAB4IgkAAIAAgLQgMAPgXAAQgYAAgRgSgAD2BuQgIAIAAANQAAAOAIAIQAIAIANAAQAMAAAIgIQAIgIAAgOQAAgNgIgIQgIgIgMAAQgNAAgIAIgAkrCxQgSgTAAgbQAAgaASgTQATgSAaAAQAbAAASASQATATAAAaQAAAbgTATQgSASgbAAQgaAAgTgSgAkRBvQgIAIAAAMQAAANAIAIQAHAIAMAAQAMAAAIgIQAIgIAAgNQAAgMgIgIQgIgIgMAAQgMAAgHAIgAoVCmIAdgRQAEAOARAAQAOAAAAgJQAAgIgLAAIgRAAIAAgeIANAAQAMAAAAgJQAAgIgMAAQgNAAgGAOIgdgRQAOgcAiAAQAVAAANALQAMAKAAAPQAAASgNAIQARAJAAAUQAAAPgMAKQgOALgXAAQglAAgNgdgAItC/IAAg8IgzA8IgaAAIAAh4IAjAAIAAA8IAzg8IAaAAIAAB4gAGEC/IAAhVIgkAAIAAgjIBrAAIAAAjIgjAAIAABVgABQC/IAAh4IA8AAQAUAAAKAKQALAJAAAQQAAAQgLAIQAQAJAAASQAAAPgLAKQgLAJgTAAgAByCiIAaAAQALAAAAgJQAAgJgLAAIgaAAgAByB1IAWAAQALAAAAgIQAAgJgLAAIgWAAgAiRC/IAAhVIgkAAIAAgjIBsAAIAAAjIgkAAIAABVgAmbC/IAAh4IBUAAIAAAjIgwAAIAABVgAhEgUIAAgLQAXABANgdIACgHIg3h6IANAAIAwBrIAphrIANAAIgzCDQgHASgMAKQgMAJgOAAIgCAAgAKkgUIAAioIAMAAIAAAcQAIgPANgIQAOgIARAAQAaAAASATQASASAAAaQAAAagSATQgSASgaAAQgkAAgQgfIAABMgAK/ikQgPAPAAAVQAAAVAPAPQAQAPAUAAQAUAAAQgPQAPgPAAgVQAAgVgPgPQgQgPgUAAQgUAAgQAPgAN+hSQgRgPgDgZIgaAAIAAA2IgMAAIAAh4IAMAAIAAA2IAaAAQACgYASgQQASgRAYAAQAbAAASATQASASAAAaQAAAZgSAUQgSASgbAAQgYAAgSgRgAOEikQgOAOAAAWQAAAWAOAOQAQAPAUAAQAVAAAPgPQAPgPAAgVQAAgVgPgPQgPgPgVAAQgUAAgQAPgAIchTQgSgSAAgbQAAgaASgTQARgSAbAAQAbAAAQATQARATAAAZIgBAGIhsAAQACAUAOANQAPAMAUAAQAdAAAMgWIALAGQgRAcgkAAQgbAAgSgSgAJ3iFQgCgWgNgMQgOgMgSAAQgTAAgPANQgNAMgCAVIBgAAIAAAAgAEFhTQgSgSAAgbQAAgbARgSQASgSAbAAQAbAAAQATQAQATAAAZIAAAGIhsAAQACAUAOANQAPAMATAAQAdAAANgWIAKAGQgHANgOAHQgOAIgRAAQgbAAgSgSgAFgiFQgCgVgNgNQgOgMgSAAQgUAAgOANQgOANgBAUIBgAAIAAAAgAlMhTQgSgTAAgaQAAgaASgSQASgTAbAAQAaAAASATQATASAAAaQAAAZgTAUQgSASgaAAQgaAAgTgSgAlDikQgPAPAAAVQAAAVAPAPQAPAPAVAAQAUAAAQgPQAOgOAAgWQAAgWgOgOQgQgPgUAAQgVAAgPAPgAvOhaQgYgZAAglQAAglAYgYQAZgZAmAAQAXAAATALQATAKALATIgMAGQgHgOgRgLQgQgJgUAAQghAAgVAVQgVAVAAAgQAAAgAVAVQAVAVAhAAQATAAARgJQAQgKAJgQIALAHQgKASgUALQgTAMgXAAQgmAAgZgZgAHdhEIAAgvQgQAIgVAAQgXAAgMgLQgNgLAAgUIAAgnIAMAAIAAAnQAAAeAkAAQAUAAARgHIAAg+IAMAAIAAB4gAB9hEIAAh4IA2AAQAQAAAKAJQAJAJAAAOQAAATgPAHQAVAHAAAWQAAAPgJAJQgKAJgSAAgACJhQIAuAAQAZAAAAgWQAAgVgZAAIguAAgACJiHIAqAAQAXAAAAgVQAAgUgXAAIgqAAgAi/hEIAAh4IA1AAQARAAAKAJQAJAJAAAOQAAATgPAHQAVAHAAAWQAAAPgKAJQgJAJgSAAgAizhQIAuAAQAZAAAAgWQAAgVgZAAIguAAgAiziHIApAAQAYAAAAgVQAAgUgYAAIgpAAgAl3hEIhAg7IAAA7IgMAAIAAh4IAMAAIAAA2IA9g2IARAAIhBA6IBDA+gAoUhEIAAhsIgsAAIAAgMIBjAAIAAAMIgrAAIAABsgApmhEIAAgvIgaAAIgmAvIgPAAIAmgvQgPgCgJgKQgKgKAAgOQAAgQALgLQALgKARAAIAwAAIAAB4gAqdipQgIAHAAALQAAALAIAHQAHAHAMAAIAkAAIAAgyIgkAAQgLAAgIAHgAsnhEIAAh4IA2AAQARAAAJAJQAJAJAAAOQAAATgPAHQAVAHAAAWQAAAPgJAJQgKAJgSAAgAsbhQIAuAAQAZAAAAgWQAAgVgZAAIguAAgAsbiHIAqAAQAXAAAAgVQAAgJgGgGQgGgFgLAAIgqAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1, new cjs.Rectangle(-99.9,-23.9,199.9,47.8), null);


(lib.shadow_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.instance = new lib.shadow();
	this.instance.parent = this;
	this.instance.setTransform(-121,-13);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой_1
	this.instance_1 = new lib.shadow();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-121,-13);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.shadow_1, new cjs.Rectangle(-121,-13,242,26), null);


(lib.p4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["#FFFFFF","rgba(255,255,255,0)"],[0,1],0.1,0,0,0.1,0,2.6).s().p("AgQARQgIgGAAgLQAAgKAIgGQAGgIAKAAQALAAAGAIQAIAGAAAKQAAALgIAGQgGAIgLAAQgKAAgGgIg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.p4, new cjs.Rectangle(-2.5,-2.5,5,5), null);


(lib.p3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["#FFFFFF","rgba(255,255,255,0)"],[0,1],0.1,0,0,0.1,0,5.1).s().p("AgiAjQgPgOAAgVQAAgUAPgOQAOgPAUAAQAVAAAOAPQAPAOAAAUQAAAVgPAOQgOAPgVAAQgUAAgOgPg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.p3, new cjs.Rectangle(-5,-5,10,10), null);


(lib.p2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAVA+IgBgBIgEgLIAAACIgCABIgBAAIgBgBIAAgBIACgFIgCgHIgDAHIgBABIgCAAIgBgBIAAgCIAFgKIgDgJIgHAOQAAAAAAABQAAAAAAAAQAAAAAAAAQAAAAgBAAIgBAAIAAAAIgBgBIgFgPIgEAJIAEALIAAACIgBABIgCAAIgBgCIgDgHIgCAGIACAGIgBABIgBABIgBAAIgBgBIgBgCIgFAKIgBABIgBAAIgBgBIAAgBIAFgKIgCABIgCgBIgBgBIAAgBIACgCIAFgCIADgFIgHACIgCAAIgBgBIAAgBIABgCIALgEIAFgIIgQAFIgBAAIgBAAQAAgBAAAAQAAAAAAgBQAAAAAAAAQAAgBAAAAIAGgOIgJADIgFAKIgBABIgBAAIgBgBIAAgBIADgHIgHACIgCAFIgBABIgBAAIgBgBIAAgBIABgCIgLAEIgCAAIgBgBIAAgBIABgBIALgFIgCgBIgBgBIAAgBIABgBIACAAIAFACIAHgCIgHgDIgBgBIAAgCIABgBIABAAIALAGIAJgEIgOgHQAAAAgBAAQAAAAAAAAQAAAAAAAAQAAAAAAgBIAAgBIABAAIAPgGIgJgEIgLAEIgCAAIgBgBIABgCIABgBIAHgCIgGgDIgGACIgBAAIgBgBIAAgCIABgBIACgBIgLgEIgBgBIAAgCIABgBIACAAIAKAFIAAgCIAAgCIABgBIABAAIABABIACAGIAHADIgDgHIAAgCIABgBIABAAIABABIAEAMIAJADIgFgPIAAgBIABgBIACAAIAOAHIgDgJIgLgGIgBgBIAAgBIABgBIACAAIAHADIgCgGIgGgDIgBgBIAAgBIABgBIACAAIACABIgEgLIAAgBIABgBIABAAIABABIAEALIABgCIABgBIACAAIABABIAAABIgDAFIADAHIADgHIABgBIABAAIABABIAAACIgFAKIAEAJIAGgOQAAAAAAgBQAAAAAAAAQAAAAABAAQAAAAAAAAIABAAIABABIAGAPIAEgJIgEgLIAAgCIABgBIACAAIABACIACAHIADgGIgCgGIAAgBIABgBIACAAIABABIABACIAEgKIABgBIACAAIABABIAAABIgFAKIACAAIABAAIABABIAAABIgBACIgFACIgDAGIAHgDIABAAIABABIAAABIgBACIgLADIgEAJIAPgFIACAAIAAABQABAAAAAAQAAAAAAABQAAAAAAAAQAAABAAAAIgHAOIAJgDIAFgKIABgBIACAAIABABIAAABIgEAHIAHgCIACgFIACgBIABAAIABABIAAABIgBACIALgEIABAAIABABIAAABIgBABIgLAFIACABIABABIAAABIgBABIgBAAIgGgCIgGACIAHADIABABIAAACIgBABIgCAAIgKgGIgJAEIAOAGQABAAAAAAQAAAAAAAAQAAABAAAAQAAAAAAABIAAABIgBABIAAgBIgPAGIAJAEIALgEIABAAIABABIAAACIgBABIgHACIAGADIAGgCIABAAIABABIAAACIgBABIgCABIAKAEIABABIAAACIgBABIgBAAIgLgFIABACIAAACIgBABIgCAAIgBgBIgCgGIgGgDIADAHIAAACIgBABIgCAAIgBgBIgEgMIgJgDIAGAPIAAABIgBABIgCAAIgPgHIAEAJIAKAGIABABIAAABIgBABIgBAAIgHgDIACAGIAFADIABABIAAABIgBABIgBAAIgCgBIAEALIAAABIgBABIgBABIgBgBgAgGAUIAGAOIAFgOIgFgPgAAXAZIgFgOIgPgHIAGAPIAOAGgAgSAJIgGAOIAPgFIAGgOgAAFAAIAOAGIAPgFIgOgFgAghAAIAOAFIAPgFIgPgFgAAKgRIgHAPIAPgGIAHgOgAgCgDIgGgPIgOgGIAFAOIAPAHgAgEgTIAEAPIAHgPIgGgNg");
	this.shape.setTransform(1.3,-0.7,1,1,0,0,0,1.3,-0.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.p2, new cjs.Rectangle(-6.2,-6.3,12.5,12.6), null);


(lib.p1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AArB9IgCgCIgIgVIgBADIgDACIgDAAIgCgCQAAAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAIAFgKIgFgOIgGAPIgCABIgDAAIgCgCIAAgDIAKgVIgHgSIgOAcQAAABAAABQAAAAAAAAQgBAAAAABQgBAAAAgBIgCAAIgBgBIgBgBIgLgdIgJARIAIAWQAAAAABABQAAAAAAABQAAAAAAAAQgBABAAAAIgCACIgDAAIgCgCIgFgPIgGAMIAEAMQAAAAAAABQAAAAAAAAQAAABAAAAQAAAAAAABIgCABIgDAAIgCgBIgBgFIgKAWIgCABIgDAAIgCgCIAAgDIAKgVIgEACIgDgBIgCgCIAAgCIACgDIALgDIAGgNIgPAFIgDAAIgCgCIABgDIACgCIAWgIIAIgRIgfAKIgCAAIgCgBQAAgBAAAAQgBgBAAAAQAAgBAAAAQAAgBABgBIAMgcIgSAGIgKAVIgCACIgDAAIgCgCIABgDIAGgOIgNAFIgFALIgCABQgBABAAAAQAAAAgBAAQAAAAAAgBQAAAAgBAAIgCgCIAAgDIACgEIgWAJQAAAAAAAAQgBAAAAAAQAAAAgBgBQAAAAAAAAIgCgCIAAgDIACgCIAWgIIgEgCIgCgCIAAgDIACgCIADAAIAKAGIAOgGIgPgGIgCgCIABgDIACgCIADABIAVAJIASgHIgcgNQgBgBAAAAQgBAAAAAAQAAAAgBgBQAAAAAAgBIABgCQAAAAAAgBQAAAAAAAAQABAAAAAAQAAAAABAAIAdgMIgRgIIgWAHIgDAAIgCgCIAAgCIACgCIAPgGIgNgGIgLAFIgDgBIgCgCIAAgDIACgCIAEgBIgVgKIgBgCIAAgDIACgCQAAAAABAAQAAgBAAAAQABAAAAABQAAAAABAAIAVAJIgCgDIAAgDIACgCIADAAIACACIAFALIAMAGIgFgOIAAgEIACgCIADAAIACACIAIAXIASAIIgLgfIAAgCIABgBQABgBAAAAQABAAAAAAQABAAABAAQAAAAABAAIAdAMIgHgSIgVgKIgCgBIAAgDIACgDIADABIAOAGIgFgMIgLgGIgCgCIABgCIACgDIADAAIADADIgHgXQAAAAgBAAQAAAAAAgBQAAAAAAgBQABAAAAAAIACgCIADAAIACACIAIAVIACgDIACgCQAAgBAAAAQABAAAAAAQAAAAABABQAAAAAAAAIACACIAAADIgFAKIAFAOIAHgPIACgCIADAAIACACIgBAEIgJAVIAGASIAOgcQAAgBAAgBQAAAAABAAQAAAAABgBQABAAAAABIACAAIACACIAAAAIAMAdIAIgRIgJgWIABgDIACgCIADAAIACACIAFAPIAGgMIgEgMIAAgDIACgBIADAAIACABIACAFIAJgVIACgCQABAAAAAAQAAgBABAAQAAAAABABQAAAAAAAAIACACIAAADIgKAVIAEgBIADAAIACABIAAADIgCADIgLADIgGANIAPgFIACAAIACACIAAADIgCACIgWAIIgIARIAegKQABAAAAAAQAAAAABAAQAAAAAAAAQAAAAABAAIABABQABABAAAAQAAABAAAAQABABAAAAQgBABAAABIgNAcIASgGIAKgWIACgBIADAAIACACIAAADIgHAOIANgFIAFgLIADgCIADABIACACIAAADIgCAEIAVgIIADAAIACACIAAADQAAAAAAABQAAAAgBAAQAAAAAAABQgBAAAAAAIgWAIIAEACIACACIAAADIgCACIgDAAIgLgGIgNAGIAOAGIACACIAAADIgCACIgDgBIgVgJIgSAHIAdANQAAAAABAAQAAABAAAAQABABAAAAQAAABAAABIgBABIgCACIAAgBIgdAMIARAIIAWgHIADAAIACACIAAACIgCACIgPAGIANAGIALgFIADABIACACIgBADIgCACIgEABIAVAKIACACIAAADIgCACQgBAAAAAAQAAABgBAAQAAAAAAgBQgBAAAAAAIgVgJIABADQAAABABAAQAAABAAAAQAAAAAAAAQgBABAAAAIgCACIgDAAIgCgCIgEgLIgMgGIAFAOQAAABAAAAQAAABAAAAQAAAAAAABQAAAAAAABIgCACIgDAAIgCgCIgIgXIgSgIIALAfIAAACIgBABQgBABAAAAQgBABAAAAQgBAAAAAAQgBAAAAgBIgegMIAHASIAVAKIACABIAAADIgCADIgDgBIgOgGIAFAMIAKAGIACACIAAACIgCADIgDAAIgEgDIAIAXIAAACIgCACIgBABIgCgBgAgNAnIALAdIANgcIgLgegAAuAyIgKgdIgegOIAMAfIAcAMgAgkASIgNAcIAdgKIAOgdgAAKAAIAdAOIAdgLIgcgNgAhDgCIAcANIAegLIgdgNgAAVgjIgOAeIAegMIANgcgAgGgGIgLgfIgcgMIAKAdIAdAOgAgKgnIALAeIANgdIgLgdg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.p1, new cjs.Rectangle(-12.5,-12.5,25.1,25.1), null);


(lib.ob5_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.ob5();
	this.instance.parent = this;
	this.instance.setTransform(-132,-139);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.ob5_1, new cjs.Rectangle(-132,-139,264,278), null);


(lib.ob4_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.ob4();
	this.instance.parent = this;
	this.instance.setTransform(-94,-157);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.ob4_1, new cjs.Rectangle(-94,-157,188,314), null);


(lib.ob3_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.ob3();
	this.instance.parent = this;
	this.instance.setTransform(-139,-167);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.ob3_1, new cjs.Rectangle(-139,-167,278,334), null);


(lib.ob2_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.ob2();
	this.instance.parent = this;
	this.instance.setTransform(-130,-172);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.ob2_1, new cjs.Rectangle(-130,-172,260,344), null);


(lib.ob1_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.ob1();
	this.instance.parent = this;
	this.instance.setTransform(-136,-147);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.ob1_1, new cjs.Rectangle(-136,-147,272,294), null);


(lib.logo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AlRD8IAAhTIASAAIAAAFQAGgHAMAAQALAAAIAJQAJAJAAAOQAAANgJAJQgIAJgLAAQgMAAgGgHIAAAdgAk7C8QgEAEAAAHQAAAGAEAEQAEAEAGAAQAGAAAEgEQAEgEAAgGQAAgHgEgEQgEgEgGAAQgGAAgEAEgAmrD0IAAgQIgiAAIAAAQIgRAAIAAggIAHAAQAFgIABgNIAAgWIAvAAIAAArIAIAAIAAAggAnAC/QgBANgDAIIARAAIAAgbIgNAAgAhSDdQgIgJAAgNQAAgOAIgJQAJgJAMAAQALAAAGAHIAAgFIASAAIAAA7IgSAAIAAgFQgGAHgLAAQgMAAgJgJgAhEC8QgEAEAAAHQAAAGAEAEQAEAEAGAAQAGAAAEgEQAEgEAAgGQAAgHgEgEQgEgEgGAAQgGAAgEAEgAkGDdQgJgJAAgNQAAgOAJgJQAJgJAOAAQANAAAJAJQAJAJAAAOQAAANgJAJQgJAJgNAAQgOAAgJgJgAj5C8QgFAEAAAHQAAAGAFAEQADAEAHAAQAFAAAEgEQAEgEAAgGQAAgHgEgEQgEgDgFAAQgHAAgDADgAmRDdQgIgJAAgNQAAgOAIgJQAJgJALAAQALAAAGAHIAAgFIASAAIAAA7IgSAAIAAgFQgGAHgLAAQgLAAgJgJgAmEC8QgDAEAAAHQAAAGADAEQAFAEAFAAQAHAAAEgEQADgEAAgGQAAgHgDgEQgEgEgHAAQgFAAgFAEgAoUDdQgIgJgBgNQABgOAIgJQAJgJAOAAQANAAAJAJQAJAJAAAOQAAANgJAJQgJAJgNAAQgOAAgJgJgAoHC8QgEAEAAAHQAAAGAEAEQAEAEAGAAQAGAAAEgEQADgEAAgGQAAgHgDgEQgEgDgGAAQgGAAgEADgAqODdQgJgJAAgNQAAgOAJgJQAJgJANAAQAJAAAHAEQAIAEADAHIgPAJQgCgDgDgBQgCgCgFAAQgFAAgEAEQgEADAAAHQAAAGAEAEQAEADAFAAQAFAAACgBQADgCACgDIAPAJQgDAHgIAEQgHAEgJAAQgNAAgJgJgArODdQgKgJAAgNQAAgOAKgJQAIgJAOAAQANAAAJAJQAKAJAAAOQAAANgKAJQgJAJgNAAQgOAAgIgJgArCC8QgEAEAAAHQAAAGAEAEQAEAEAGAAQAGAAADgEQAEgEABgGQgBgHgEgEQgDgDgGAAQgGAAgEADgAhqDkIgUgaIAAAaIgSAAIAAg7IASAAIAAAaIASgaIAWAAIgXAeIAXAdgAipDkIAAgRIgOABQgKAAgHgFQgGgGgBgKIAAgWIASAAIAAATQAAAIAKAAQAFAAAFgCIAAgZIASAAIAAA7gAozDkIAAgrIgUAAIAAArIgSAAIAAg7IA4AAIAAA7gAsBDkIAAg7IAqAAIAAARIgYAAIAAAqgALPBYQgkgSgZggQgaAggjASQgnATgqAAQgqAAgmgTQglgSgZggQASgYAJgaQALgcgBgdQABAqAeAdQAeAeAsAAQArAAAfgeQAegeAAgrIBMAAQAAArAeAeQAfAeArAAIAABLQgqAAgngTgAiDBYQglgSgZggQASgYAJgaQAKgcAAgdQABAqAeAdQAeAeAsAAQArAAAegeQAegeAAgrIAAgCQAAgeAKgbQAKgcASgXQAZghAkgSQAngTAqAAQAqAAAmATQAkASAaAhQgSAXgKAcQgJAbgBAeQAAgqgfgeQgegfgrAAQgrAAgfAfQgfAfABArIAAABQgBAsgUAlQgUAmgjAZQgXAQgZAJQgbAIgcAAQgqAAgmgTgAqxBdQghgNgZgZQgYgZgOgfQgOgiAAgkIBLAAQABArAeAeQAeAeAsAAQArAAAfgeQAegeAAgrIAAgCQAAgrAUgmQATglAigZQAXgRAbgJQAbgJAeAAQAdAAAbAJQAaAJAXAQIgBARIAAB+QgBgpgegeQgegfgrAAQgsAAgeAfQgeAfAAArIAAACQgBAdgKAcQgJAagTAYQgZAggkASQgmATgqAAQglAAghgOg");
	this.shape.setTransform(0,7.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#EA1873").s().p("ABoFbIAAjCQAjgZAUglQAUgnABgsQAAArAeAeQAfAeArABQArgBAfgeQAegfAAgrIAAgCQABgdAJgbQAKgcASgXQAZghAlgSQAmgTAqAAQAlAAAhAPQAgANAZAZQAZAZAOAgQAOAhAAAkIhLAAQAAgqgfgfQgfgfgrABQgrgBgfAfQgeAfAAAqIAAACQAAAdgKAcQgKAbgSAYQgZAgglASQglAUgrgBQgdAAgbgIQgagJgWgQIAADCgAlrCnQglgSgZggQASgYAKgbQAJgcABgdQAAAqAeAeQAfAeArABQArgBAfgeQAegfAAgrIAAgDIAAh9IABgRQADgeANgbQAOgcAXgWQAXgWAfgOQAggPAjgFQAbgDAXgMQAWgLAPgSIA5AxQgXAcgjASQgjASgqAGQgtAHgdAZQgaAXgGAgQAWgQAagJQAagIAbAAQArAAAlATQAlASAZAhQgSAXgKAcQgJAbgBAdQAAgpgegeQgfgfgrABQgqgBgfAfQgeAfAAAqIAAACQgBAdgJAcQgKAbgSAYQgZAgglASQgmAUgqgBQgrABglgUgArrAHQAAgkAOghQAOggAZgZQAZgZAggNQAhgPAlAAQAcAAAaAIQAZAJAXAPQgMhFg9ggQgfgSgrgHQgdgFggAAIAAhLQAqAAAnAHQAzAJAnAWQAyAbAcArQAdArAGA6QgiAZgUAlQgTAngBApQAAgpgegeQgfgfgrABQgrgBgfAfQgeAfAAAqg");
	this.shape_1.setTransform(-5.2,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.logo, new cjs.Rectangle(-80,-34.7,160,69.5), null);


(lib.bg2_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.bg2();
	this.instance.parent = this;
	this.instance.setTransform(-150,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bg2_1, new cjs.Rectangle(-150,-300,300,600), null);


(lib.bg_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.bg();
	this.instance.parent = this;
	this.instance.setTransform(-150,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bg_1, new cjs.Rectangle(-150,-300,300,600), null);


(lib.particleMcMc = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
		this.gotoAndStop(Math.ceil(Math.random()*4));
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(5));

	// Слой 2
	this.instance = new lib.p1();
	this.instance.parent = this;
	this.instance.setTransform(0,-0.3,1,1,0,0,0,-0.1,0.1);

	this.instance_1 = new lib.p2();
	this.instance_1.parent = this;
	this.instance_1.setTransform(0,0.8,1,1,0,0,0,0.1,-0.1);

	this.instance_2 = new lib.p3();
	this.instance_2.parent = this;
	this.instance_2.setTransform(-1.3,-1.7,1,1,0,0,0,-1.6,-0.3);

	this.instance_3 = new lib.p4();
	this.instance_3.parent = this;
	this.instance_3.setTransform(-1.3,-1.7,1,1,0,0,0,-1.6,-0.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance_1}]},2).to({state:[{t:this.instance_2}]},1).to({state:[{t:this.instance_3}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-12.4,-13,25.1,25.1);


(lib.particle2mc = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.particleMcMc();
	this.instance.parent = this;
	this.instance.setTransform(-15,-0.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:0.8,scaleY:0.8,x:0},20,cjs.Ease.get(-1)).to({scaleX:1,scaleY:1,x:15},20,cjs.Ease.get(1)).to({scaleX:1.2,scaleY:1.2,x:0,y:-0.1},20,cjs.Ease.get(-1)).to({scaleX:1,scaleY:1,x:-15,y:-0.2},20,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-27.4,-13.2,25.1,25.1);


(lib.particle2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.particle2mc();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({rotation:360},64).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-27.4,-13.2,25.1,25.1);


(lib.particle2Movie = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_84 = function() {
		this.parent.removeChild(this);
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(84).call(this.frame_84).wait(1));

	// Слой 1
	this.instance = new lib.particle2();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:350.5},74).to({y:397.8,alpha:0},10).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-27.4,-13.2,25.1,25.1);


(lib.snowFront = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		//var animbool = 0;
		
		//this.addEventListener("tick", addParticles.bind(this));
		
		//function addParticles() {
		//	if(animbool == 0){
		//		animbool = 1;
		//		var cloneParticle = new lib.particle2Movie();
		//		cloneParticle.x = Math.random()*500;
		//		cloneParticle.scaleX = cloneParticle.scaleY = Math.random()*.7 +.3;
		//		this.addChild(cloneParticle);
		//	}else {
		//		animbool = 0;
		//		var cloneParticle1 = new lib.particle2Movie();
		//		cloneParticle1.x = -Math.random()*500;
		//		cloneParticle1.scaleX = cloneParticle1.scaleY = Math.random()*.7 +.3;
		//		this.addChild(cloneParticle1);
		//	}
		//}
		for(var i=0; i<3; i++){
			var cloneParticle = new lib.particle2Movie();
			cloneParticle.x = Math.random()*600;
			cloneParticle.scaleX = cloneParticle.scaleY = Math.random()*.5 +.5;
			this.addChild(cloneParticle);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(2));

	// particles
	this.particle = new lib.particle2Movie();
	this.particle.name = "particle";
	this.particle.parent = this;
	this.particle.cache(-29,-15,29,29);

	this.timeline.addTween(cjs.Tween.get(this.particle).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-27.4,-13.2,25.1,25.1);


(lib.banner = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// t7
	this.instance = new lib.t7();
	this.instance.parent = this;
	this.instance.setTransform(-268.5,39);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(260).to({_off:false},0).to({x:1.5},10,cjs.Ease.get(-1)).wait(45).to({x:267.5},10,cjs.Ease.get(-1)).wait(11));

	// toy3
	this.instance_1 = new lib.toy3_1();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-204,54.5,1,1,69.5,0,0,0,-51);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(260).to({_off:false},0).to({rotation:45,x:65.9},10,cjs.Ease.get(-1)).to({regX:0.1,regY:-50.9,rotation:-20,x:66},16,cjs.Ease.quadInOut).to({regX:0,regY:-51,rotation:10,x:65.9},14,cjs.Ease.quadInOut).to({regX:0.1,regY:-50.9,rotation:-5,x:66},15,cjs.Ease.quadInOut).to({regY:-50.8,rotation:80,x:331.9},10,cjs.Ease.get(-1)).wait(11));

	// toy2
	this.instance_2 = new lib.toy2_1();
	this.instance_2.parent = this;
	this.instance_2.setTransform(-188,54.5,1,1,68.7,0,0,0,-81);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(260).to({_off:false},0).to({regX:0.1,rotation:45,x:82},10,cjs.Ease.get(-1)).to({rotation:-20,y:54.4},16,cjs.Ease.quadInOut).to({rotation:10,y:54.5},14,cjs.Ease.quadInOut).to({regY:-80.9,rotation:-5},15,cjs.Ease.quadInOut).to({rotation:80,x:348},10,cjs.Ease.get(-1)).wait(11));

	// toy1
	this.instance_3 = new lib.toy1_1();
	this.instance_3.parent = this;
	this.instance_3.setTransform(-239.9,55,1,1,68.2,0,0,0.1,-62);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(260).to({_off:false},0).to({regY:-61.9,rotation:45,x:30,y:55.1},10,cjs.Ease.get(-1)).to({regY:-61.8,rotation:-20},16,cjs.Ease.quadInOut).to({regX:-0.1,regY:-61.9,rotation:10,x:29.9,y:55},14,cjs.Ease.quadInOut).to({regX:0,regY:-61.8,rotation:-5,x:30,y:55.1},15,cjs.Ease.quadInOut).to({rotation:80,x:296,y:55},10,cjs.Ease.get(-1)).wait(11));

	// logo
	this.instance_4 = new lib.logo();
	this.instance_4.parent = this;
	this.instance_4.setTransform(8.5,-226.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(250).to({x:-31.5,y:-61.5},10,cjs.Ease.quadInOut).wait(65).to({x:8.5,y:-226.5},10,cjs.Ease.quadInOut).wait(1));

	// t6
	this.instance_5 = new lib.t6();
	this.instance_5.parent = this;
	this.instance_5.setTransform(-8.9,-141.1);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(260).to({_off:false},0).to({alpha:1},10).wait(45).to({alpha:0},10).wait(11));

	// ob
	this.instance_6 = new lib.ob5_1();
	this.instance_6.parent = this;
	this.instance_6.setTransform(76,21,0.01,1);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(200).to({_off:false},0).to({scaleX:1,x:1},5,cjs.Ease.get(1)).wait(35).to({x:-349},10,cjs.Ease.get(-1)).to({_off:true},1).wait(85));

	// shadow
	this.instance_7 = new lib.shadow_1();
	this.instance_7.parent = this;
	this.instance_7.setTransform(93,161,0.01,1,0,0,0,5,0);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(200).to({_off:false},0).to({regX:0,scaleX:1,x:76},5,cjs.Ease.get(1)).wait(35).to({x:-274},10,cjs.Ease.get(-1)).to({_off:true},1).wait(85));

	// ob
	this.instance_8 = new lib.ob4_1();
	this.instance_8.parent = this;
	this.instance_8.setTransform(5,21,0.01,1);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(150).to({_off:false},0).to({scaleX:1,x:1},5,cjs.Ease.get(1)).wait(38).to({scaleX:0.5},0).wait(1).to({skewY:180,x:7},0).wait(1).to({scaleX:1,x:13},0).wait(1).to({scaleX:0.5,x:7},0).wait(1).to({skewY:0,x:1},0).wait(1).to({scaleX:1},0).wait(1).to({scaleX:0.5},0).to({_off:true},1).wait(136));

	// shadow
	this.instance_9 = new lib.shadow_1();
	this.instance_9.parent = this;
	this.instance_9.setTransform(17,181,0.01,1,0,0,0,-5,0);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(150).to({_off:false},0).to({regX:0,scaleX:1,x:4},5,cjs.Ease.get(1)).wait(38).to({scaleX:0.5},0).wait(2).to({scaleX:1},0).wait(1).to({scaleX:0.5},0).wait(2).to({scaleX:1},0).wait(1).to({scaleX:0.5},0).to({_off:true},1).wait(136));

	// ob
	this.instance_10 = new lib.ob3_1();
	this.instance_10.parent = this;
	this.instance_10.setTransform(-19,20,0.01,1);
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(100).to({_off:false},0).to({scaleX:1,x:1},5,cjs.Ease.get(1)).wait(38).to({scaleX:0.5,x:-8},0).wait(1).to({skewY:180,x:-29},0).wait(1).to({scaleX:1,x:-39},0).wait(1).to({scaleX:0.5,x:-29},0).wait(1).to({skewY:0,x:-8},0).wait(1).to({scaleX:1,x:1},0).wait(1).to({scaleX:0.5,x:-8},0).to({_off:true},1).wait(186));

	// shadow
	this.instance_11 = new lib.shadow_1();
	this.instance_11.parent = this;
	this.instance_11.setTransform(-19,186,0.01,1,0,0,0,-5,0);
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(100).to({_off:false},0).to({regX:0,scaleX:1,x:-18},5,cjs.Ease.get(1)).wait(38).to({scaleX:0.5},0).wait(2).to({scaleX:1},0).wait(1).to({scaleX:0.5},0).wait(2).to({scaleX:1},0).wait(1).to({scaleX:0.5},0).to({_off:true},1).wait(186));

	// ob
	this.instance_12 = new lib.ob2_1();
	this.instance_12.parent = this;
	this.instance_12.setTransform(31,19,0.01,1,0,0,0,-5,0);
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(50).to({_off:false},0).to({regX:0,scaleX:1,x:-3},5,cjs.Ease.get(1)).wait(38).to({scaleX:0.5,x:14},0).wait(1).to({skewY:180,x:50},0).wait(1).to({scaleX:1,x:68},0).wait(1).to({scaleX:0.5,x:50},0).wait(1).to({skewY:0,x:14},0).wait(1).to({scaleX:1,x:-3},0).wait(1).to({scaleX:0.5,x:14},0).to({_off:true},1).wait(236));

	// shadow
	this.instance_13 = new lib.shadow_1();
	this.instance_13.parent = this;
	this.instance_13.setTransform(41,192,0.01,1);
	this.instance_13._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(50).to({_off:false},0).to({scaleX:1,x:32},5,cjs.Ease.get(1)).wait(38).to({scaleX:0.5},0).wait(2).to({scaleX:1},0).wait(1).to({scaleX:0.5},0).wait(2).to({scaleX:1},0).wait(1).to({scaleX:0.5},0).to({_off:true},1).wait(236));

	// ob
	this.instance_14 = new lib.ob1_1();
	this.instance_14.parent = this;
	this.instance_14.setTransform(287,16);

	this.timeline.addTween(cjs.Tween.get(this.instance_14).to({x:0},10,cjs.Ease.get(1)).wait(33).to({scaleX:0.51,x:16},0).wait(1).to({regX:-5,skewY:180,x:48.5},0).wait(1).to({regX:0,scaleX:1,x:65},0).wait(1).to({regX:-5,scaleX:0.51,x:48.5},0).wait(1).to({regX:0,skewY:0,x:16},0).wait(1).to({scaleX:1,x:0},0).wait(1).to({scaleX:0.51,x:16},0).to({_off:true},1).wait(286));

	// shadow
	this.instance_15 = new lib.shadow_1();
	this.instance_15.parent = this;
	this.instance_15.setTransform(309,164);

	this.timeline.addTween(cjs.Tween.get(this.instance_15).to({x:22},10,cjs.Ease.get(1)).wait(33).to({scaleX:0.51,x:32},0).wait(1).to({skewY:180,x:32.1},0).wait(1).to({scaleX:1,x:32},0).wait(1).to({scaleX:0.51,x:32.1},0).wait(1).to({skewY:0,x:32},0).wait(1).to({scaleX:1},0).wait(1).to({scaleX:0.51},0).to({_off:true},1).wait(286));

	// t5
	this.instance_16 = new lib.t5();
	this.instance_16.parent = this;
	this.instance_16.setTransform(252,238);
	this.instance_16._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_16).wait(200).to({_off:false},0).to({x:0},10,cjs.Ease.get(1)).wait(30).to({x:-350},10,cjs.Ease.get(-1)).to({_off:true},1).wait(85));

	// t4
	this.instance_17 = new lib.t4();
	this.instance_17.parent = this;
	this.instance_17.setTransform(252,240.2);
	this.instance_17._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_17).wait(150).to({_off:false},0).to({x:0},10,cjs.Ease.get(1)).wait(30).to({x:-250},10,cjs.Ease.get(-1)).to({_off:true},1).wait(135));

	// t3
	this.instance_18 = new lib.t3();
	this.instance_18.parent = this;
	this.instance_18.setTransform(252,224.6);
	this.instance_18._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_18).wait(100).to({_off:false},0).to({x:0},10,cjs.Ease.get(1)).wait(30).to({x:-250},10,cjs.Ease.get(-1)).to({_off:true},1).wait(185));

	// t2
	this.instance_19 = new lib.t2();
	this.instance_19.parent = this;
	this.instance_19.setTransform(252,227.2);
	this.instance_19._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_19).wait(50).to({_off:false},0).to({x:0},10,cjs.Ease.get(1)).wait(30).to({x:-250},10,cjs.Ease.get(-1)).to({_off:true},1).wait(235));

	// t1
	this.instance_20 = new lib.t1();
	this.instance_20.parent = this;
	this.instance_20.setTransform(252,237.8);

	this.timeline.addTween(cjs.Tween.get(this.instance_20).to({x:0},10,cjs.Ease.get(1)).wait(30).to({x:-250},10,cjs.Ease.get(-1)).to({_off:true},1).wait(285));

	// urText
	this.instance_21 = new lib.urText();
	this.instance_21.parent = this;
	this.instance_21.setTransform(0,291.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_21).wait(336));

	// bg
	this.instance_22 = new lib.bg_1();
	this.instance_22.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_22).wait(250).to({alpha:0},10).wait(65).to({alpha:1},10).wait(1));

	// snow
	this.instance_23 = new lib.snowFront();
	this.instance_23.parent = this;
	this.instance_23.setTransform(-169.1,-312.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_23).wait(336));

	// bg2
	this.instance_24 = new lib.bg2_1();
	this.instance_24.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_24).wait(336));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-196.6,-325.3,626.6,625.3);


// stage content:
(lib._300x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// cover
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#666666").ss(2,1,1).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// banner
	this.instance = new lib.banner();
	this.instance.parent = this;
	this.instance.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(103.4,274.7,626.6,626.3);
// library properties:
lib.properties = {
	id: '00507DB37BBE4ADC811A42BF278CC4E2',
	width: 300,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/bg.jpg", id:"bg"},
		{src:"images/bg2.jpg", id:"bg2"},
		{src:"images/ob1.png", id:"ob1"},
		{src:"images/ob2.png", id:"ob2"},
		{src:"images/ob3.png", id:"ob3"},
		{src:"images/ob4.png", id:"ob4"},
		{src:"images/ob5.png", id:"ob5"},
		{src:"images/shadow.png", id:"shadow"},
		{src:"images/toy1.png", id:"toy1"},
		{src:"images/toy2.png", id:"toy2"},
		{src:"images/toy3.png", id:"toy3"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['00507DB37BBE4ADC811A42BF278CC4E2'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;