(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.bgImg1 = function() {
	this.initialize(img.bgImg1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,364);


(lib.bgImg2 = function() {
	this.initialize(img.bgImg2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,364);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.urText = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AizCiIgDgBIABgIIAGABIAFgBIADgEIAGgLIgVgwIAKAAIAPAlIAPglIAKAAIgWA1IgGAMIgGAFQgDACgFAAgAM8ChIAAgeQgDAEgEACQgDACgGAAQgHAAgEgDQgGgEgDgFQgDgGAAgIQAAgGADgGQADgGAGgDQAEgEAHAAQAEAAAFADQAEABADAFIAAgHIAKAAIAABHgAMmBjQgDACgCAEQgCAFAAADQAAAEACAFQACAEADACQADACAFAAQAFAAACgCQAEgCACgEQACgFAAgEQAAgDgCgFQgDgEgDgCQgEgCgDAAQgEAAgEACgAGHChIAAhHIAJAAIAAAHQADgFAEgBQAFgDAEAAQAHAAAFAEQAFADADAGQADAGAAAGQAAAIgDAGQgDAFgFAEQgFADgHAAQgFAAgEgCQgDgCgEgEIAAAegAGXBjQgDACgCAEQgCAFAAADQAAAEACAFQACAEADACQADACAFAAQAFAAACgCQAEgCACgEQACgFAAgEQAAgDgCgFQgDgEgDgCQgEgCgDAAQgEAAgEACgAB/ChIAAhHIAJAAIAAAHQACgEAFgCQAFgDAEAAQAHAAAFAEQAEACAEAHQADAGAAAGQAAAIgDAGQgDAFgFAEQgFADgHAAQgFAAgEgCQgFgDgCgDIAAAegACPBjQgEADgBADQgCAEAAAEQAAAGACADQABADAEADQADACAFAAQAEAAADgCQAEgDABgDQACgDAAgGQAAgEgCgEQgBgDgEgDIgHgCIgIACgAnhCYIAAgOIg3AAIAAhGIAKAAIAAA9IAjAAIAAg9IAJAAIAAA9IAKAAIAAAXgAImCVIAAgLIgqAAIAAgwIAKAAIAAAoIAXAAIAAgoIAKAAIAAAoIAHAAIAAATgAQVCIQgFgEgDgFQgDgGAAgIQAAgGADgGQADgGAFgDQAFgEAHAAQAEAAAFADQAEABADAFIAAgHIAJAAIAAAwIgJAAIAAgHQgEAEgDACQgEACgFAAQgGAAgGgDgAQbBjQgDACgDAEQgCAFAAADQAAAEACAFQACAEAEACQACACAFAAQAFAAADgCQADgCACgEQACgFAAgEQAAgDgCgFQgCgEgDgCQgEgCgEAAQgDAAgEACgAPcCJQgEgCgEgFQgCgEAAgHIAAgdIAJAAIAAAcQAAAFADAEQADADAGAAQAFAAADgDQADgEAAgFIAAgcIAKAAIAAAdQAAAGgDAFQgDAFgFACQgEACgGAAQgHAAgEgCgAO/CKIgCgCIgBgEIABgDIACgCIADgBIAEABIACACIABADIgBAEIgCACIgEABgAOTCJIgJgFIAEgHIAHAEIAJACQAEgBADgBQACgDAAgCQAAAAAAgBQAAAAAAgBQAAAAgBgBQAAAAAAAAIgEgCIgPgFIgGgEQgCgDAAgEQAAgFACgDIAHgFQAEgCAGAAIAKACQAFABADADIgEAHIgHgEIgHgBQgEABgDABQgDACAAADIACACIADACIAPAFIAGAEQADADAAAFQAAAEgDADQgCAEgEACQgEACgGAAQgHAAgEgCgANcCIQgGgFgDgEQgDgGAAgIQAAgHADgFQADgGAGgDQAFgEAIAAQAHAAAFAEQAGADADAGQADAGAAAGQAAAIgDAGQgDAFgGAEQgFADgHAAQgHAAgGgDgANhBkIgGAFQgCAFAAADQAAAEACAFQACAEAEACIAIACQADAAAEgCQAEgCACgEQACgEAAgFQAAgEgCgEQgBgDgFgCQgCgDgFAAQgFAAgDADgAK/CIQgFgEgDgFQgDgGAAgIQAAgGADgGQADgHAFgCQAFgEAGAAQAEAAAFADQAEABADAFIAAgHIAKAAIAAAwIgKAAIAAgHQgDAEgEACQgDACgGAAQgGAAgFgDgALEBjQgDACgCAEQgCAEAAAEQAAAGACADQACAEADACQADACAFAAQAFAAACgCQAEgCACgEQACgDAAgGQAAgEgCgEQgDgEgDgCQgEgCgDAAQgEAAgEACgAHKCIQgFgEgDgFQgDgGAAgIQAAgGADgGQADgGAFgDQAFgEAHAAQAEAAAFADQAEABADAFIAAgHIAJAAIAAAwIgJAAIAAgHQgEAEgDACQgEACgFAAQgGAAgGgDgAHQBjQgDACgDAEQgCAFAAADQAAAEACAFQACAEAEACQACACAFAAQAFAAADgCQADgCACgEQACgFAAgEQAAgDgCgFQgCgEgDgCQgEgCgEAAQgDAAgEACgAEuCIQgGgEgDgFQgDgGAAgIQAAgGADgGQADgGAGgDQAFgEAIAAQAGAAAGADQAFADADAEIgGAFQgCgCgEgCQgDgCgFAAQgFAAgDADQgEABgBAEQgCAEAAAEQAAAFACAEQABAEAEACQADACAFAAQAFAAADgBIAGgGIAGAHQgDAEgFACQgFACgHABQgHAAgGgDgAD9CIQgGgEgDgFQgDgGAAgIQAAgGADgGQADgGAGgDQAFgEAJAAQAFAAAGADQAFACAEAEIgGAGIgGgFQgEgBgEgBQgFABgDABQgEACgBADIgDAHIAXAAIAAAHIgXAAQABAGAEAEQAEADAHABQAEgBAEgBQADgBADgEIAFAGQgDAFgFACQgEACgHAAQgIAAgGgDgADDCIQgGgEgDgFQgDgGAAgIQAAgGADgGQADgGAFgDQAFgEAIAAQAGAAAGAEQAEACAEAGQADAGAAAGIAAAEIgmAAQAAAEADADQACADADADQAEABAEABQAFgBAEgBIAGgFIAFAHQgDAEgFACQgGACgGAAQgIAAgFgDgADdBuQgBgHgEgDQgEgDgFgBQgGABgEADQgEADgBAHIAdAAIAAAAgAgxCIQgGgFgDgEQgDgGAAgIQAAgHADgFQADgGAGgDQAFgEAIAAQAHAAAFAEQAGADADAGQADAGAAAGQAAAIgDAGQgDAFgGAEQgFADgHAAQgHAAgGgDgAgsBkIgGAFQgCAFAAADQAAAEACAFQACAEAEACIAIACQADAAAEgCQAEgCACgEQACgEAAgFQAAgEgCgEQgBgDgFgCQgCgDgFAAQgFAAgDADgAj1CIQgGgEgDgFQgDgGAAgIQAAgGADgGQADgGAGgDQAFgEAGAAQAEAAAFADQAEABADAFIAAgHIAKAAIAAAwIgKAAIAAgHQgDAEgEACQgDACgGAAQgGAAgFgDgAjwBjQgDACgCAEQgCAFAAADQAAAEACAFQACAEADACQADACAFAAQAFAAACgCQAEgCACgEQACgFAAgEQAAgDgCgFQgDgEgDgCQgEgCgDAAQgEAAgEACgAkrCJQgFgCgDgEIAFgGQADADAEACQAEABAEAAQAGAAADgCQADgCAAgEQAAgGgKgBIgKAAIAAgGIAIAAQAFAAADgBQACgDAAgDQAAgEgCgBQgCgBgFgBQgJABgFAFIgGgGIAJgFIALgDQAIAAAGAEQAEAEAAAGQAAAEgCADQgBACgEACQAEABADADQACAEAAADQAAAEgCADQgCADgGADQgEABgHABQgHAAgFgCgAl1CIQgFgEgDgFQgDgGAAgIQAAgGADgGQAEgHAEgCQAFgEAHAAIAJADQAFADACADIAAgHIAJAAIAAAwIgJAAIAAgHQgCADgFADQgEACgFAAQgGAAgGgDgAlvBjQgEADgBADQgCAEAAAEQAAAGACADQABADAEADQADACAFAAQAEAAADgCQAEgDABgDQACgDAAgGQAAgEgCgEQgBgDgEgDIgHgCIgIACgApACKIgCgCIgBgEIABgDIACgCIADgBIAEABIACACIABADIgBAEIgCACIgEABgAuSCLIABgJIADAAQAAAAABAAQABAAAAAAQAAgBABAAQAAAAABAAQAAgBAAAAQABgBAAAAQAAgBAAgBQAAAAAAgBIACgiIAmAAIAAAwIgJAAIAAgoIgUAAIgBAQQAAAJgBAGQgCAFgDACQgCACgGABgAu/CIQgGgEgDgFQgDgHAAgHQAAgGADgGQADgGAGgDQAFgEAIAAQAHAAAGAEQAFADADAGQADAGAAAGQAAAIgDAGQgDAEgFAFQgGADgHAAQgHAAgGgDgAu6BkIgGAFQgCAFAAADQAAAEACAFQACAEAEACIAIACIAIgCQADgDACgDQACgEAAgFQAAgEgCgEQgBgDgEgCQgEgDgEAAQgFAAgDADgAxlCIQgGgEgDgFQgDgGAAgIQAAgGADgGQADgGAGgDQAFgEAHAAQAIAAAFAEQAGADADAGQADAGAAAGQAAAIgDAGQgDAEgGAFQgGADgHAAQgHAAgFgDgAxgBkQgFACgBADQgCAEAAAEQAAAFACAEQACAEAEACQAEACADAAIAIgCQAEgCACgEQACgFAAgEQAAgDgCgFIgGgFQgDgDgFAAQgFAAgCADgAMFCKIAAgwIAJAAIAAAwgAKdCKIAAgWIgYAAIAAAWIgJAAIAAgwIAJAAIAAATIAYAAIAAgTIAJAAIAAAwgAJVCKIAAgwIAJAAIAAAwgAI3CKIAAgwIAKAAIAAAwgAFiCKIAAgoIgQAAIAAgIIAqAAIAAAIIgQAAIAAAogABSCKIAAgjIgZAjIgIAAIAAgwIAIAAIAAAiIAZgiIAJAAIAAAwgAAACKIAAgwIAVAAQAJAAAEADQAFAEAAAGIgCAGQgCACgDACQAEABADADQACACAAAFQAAAEgCADQgCADgEACQgEACgFAAgAAJCDIAMAAQAGgBACgBQACgCAAgEQAAgGgKgBIgMAAgAAJBuIAKAAQAGAAACgBQACgCAAgEQAAgGgKAAIgKAAgAhQCKIAAgjIgQAVIgGAAIgQgVIAAAjIgJAAIAAgwIAJAAIATAYIATgYIAJAAIAAAwgAmXCKIAAgWIgXAAIAAAWIgKAAIAAgwIAKAAIAAATIAXAAIAAgTIAKAAIAAAwgAnLCKIAAgwIAJAAIAAAwgApaCKIAAgjIgZAjIgIAAIAAgwIAJAAIAAAiIAYgiIAJAAIAAAwgAqSCKIAAgjIgPAVIgGAAIgQgVIAAAjIgJAAIAAgwIAJAAIATAYIASgYIAJAAIAAAwgArTCKIAAgwIAJAAIAAAwgArtCKIAAgWIgYAAIAAAWIgJAAIAAgwIAJAAIAAATIAYAAIAAgTIAJAAIAAAwgAszCKIAAgoIgQAAIAAgIIAqAAIAAAIIgQAAIAAAogAtSCKIAAgwIAJAAIAAAwgAviCKIAAgWIgXAAIAAAWIgKAAIAAgwIAKAAIAAATIAXAAIAAgTIAKAAIAAAwgAw0CKIAAgwIAWAAQAIAAAFADQAEAEAAAGQAAADgBADIgGAEQAFABACADQACACAAAFQAAAEgBADQgCADgEACQgEACgGAAgAwrCDIANAAQAGgBACgBQACgCAAgEQAAgGgKgBIgNAAgAwrBuIALAAQAFAAADgBQACgCAAgEQAAgGgKAAIgLAAgAyICKIAAgoIgYAAIAAAoIgJAAIAAgwIAqAAIAAAwgAMGBOIgCgCIgBgDIABgDIACgCIADgBIADABIADACIABADIgBADIgDACIgDABgAI5BOIgCgCIgBgDIABgDIACgCIADgBQAAAAABAAQAAAAABAAQAAAAAAABQABAAAAAAIACACIABADIgBADIgCACIgDABgAnKBOIgCgCIgBgDIABgDIACgCIAEgBIADABIACACIABADIgBADIgCACIgDABgArSBOIgCgCIgBgDIABgDIACgCIADgBIADABIADACIAAADIAAADIgDACIgDABgAtRBOIgCgCIgBgDIABgDIACgCIADgBIADABIACACIABADIgBADIgCACIgDABgAJdBNQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAAAgBQABAAAAAAQAAAAABAAQABAAAAAAQABAAAAAAQABAAABAAQAAAAAAAAQABABAAAAQABAAAAABQAAAAAAABQABAAAAABQAAAAAAABQAAABAAAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAAAAAQgBAAgBAAQAAAAgBAAQAAAAgBAAQgBAAAAAAQAAAAgBAAQAAgBgBAAgAJNBNQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAIAEgBQABAAAAAAQABAAABAAQAAAAAAAAQABABAAAAQABAAAAABQAAAAAAABQABAAAAABQAAAAAAABQAAABAAAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAAAAAQgBAAgBAAQAAAAgBAAIgEgBgAKPAvIAAhGIAKAAIAAAHQACgFAEgBQAFgDAFAAQAGAAAFADQAFAEADAFQADAGAAAHQAAAHgDAFQgCAGgGADQgFADgGAAQgGAAgEgCQgEgDgCgDIAAAfgAKfgOQgDACgCADQgCAEAAAFQAAAEACAEQACAEADACQADABAFAAQAEAAAEgBQADgCACgEQACgEAAgEQAAgFgCgEQgCgDgDgCQgEgCgEAAQgEAAgEACgAEpAjIAAgMIgnAAIAAAMIgIAAIAAgUIAFAAQADgEAAgDIACgfIAmAAIAAAmIAHAAIAAAUgAEMAIIgDAHIAYAAIAAgeIgUAAgAxoAjIAAgMIhBAAIAAguIAJAAIAAAmIATAAIAAgmIAKAAIAAAmIATAAIAAgmIAJAAIAAAmIAIAAIAAAUgANvAVQgFgDgDgGQgDgFAAgHQAAgHADgGQADgGAFgDQAFgDAGAAQAFAAAFADQAEABACAFIAAgHIAKAAIAAAuIgKAAIAAgHQgCADgEADQgEACgGAAQgGAAgFgDgAN0gOQgDACgCADQgCAEAAAFQAAAEACAEQACAEADACQAEABAEAAQAEAAAEgBQADgCACgEQACgEAAgEQAAgFgCgEQgCgDgDgCQgEgCgEAAQgEAAgEACgAMNAVQgFgEgDgFQgDgGAAgGQAAgHADgGQADgFAFgEQAGgDAHAAQAGAAAGADQAGACADAFIgGAFQgCgDgFgBQgDgCgEAAQgGAAgCACQgEABgCAEQgCAEAAAFQAAAEACADQACAEADADQAEABAFAAQAEABAEgCIAGgFIAGAGQgDAEgGADQgEACgHAAQgIAAgGgDgAJeAVQgGgDgDgGQgEgHAAgFQAAgHAEgGQADgFAGgEQAFgDAHAAQAIAAAFADQAGAEADAFQADAHAAAGQAAAFgDAHQgDAFgGAEQgGADgHAAQgHAAgFgDgAJigOIgFAFQgCAGAAADQAAADACAEQACAEADADIAIABIAIgBQAEgDACgEQACgEAAgDQAAgDgCgGIgGgFQgDgCgFAAQgEAAgEACgAE0AYIABgJIADAAQAAAAABAAQABAAAAAAQABAAAAAAQAAgBABAAIACgEIABghIAmAAIAAAuIgJAAIAAgmIgUAAIAAAPIgCAOQgCAGgDACQgCACgGAAgAC5AVQgFgDgEgGQgDgGAAgGQAAgHADgGQADgGAFgDQAGgDAHAAQAHAAAFADQAFADADAGQADAFAAAGIAAAEIgmAAIADAHQACADAEACQACACAGAAQAEAAAEgCQAEgBACgDIAFAGQgDAEgFACQgFACgHAAQgHAAgGgDgADTgEQgBgGgEgDQgDgEgGAAQgGAAgEAEQgDACgCAHIAdAAIAAAAgAgrAXIABgIIAEAAQADABACgDQACgCAAgFIACg0IAwAAIAABFIgKAAIAAg8IgdAAIAAAcIgCAUQgCAHgDADQgEADgHAAgAhNAXIgCgCIgBgEIABgDIACgBIADgBIAEABIACABIABADIgBAEIgCACIgEABgAjYAVQgFgEgDgFQgDgGAAgGQAAgHADgGQADgFAFgEQAGgDAHAAQAGAAAGADQAGACADAFIgGAFQgCgDgFgBIgHgCQgGAAgCACQgEABgCAEQgCAEAAAFQAAAEACADQACAEADADQAEABAFAAQAEABAEgCIAGgFIAGAGQgDAEgGADQgEACgHAAQgIAAgGgDgAmbAVQgGgDgDgGQgDgGAAgGQAAgIADgFQAEgGAFgDQAFgDAHAAQAHAAAFADQAFADADAGQADAFAAAGIAAAEIglAAQAAAEACADQACADAEACQADACAFAAIAIgCQAEgBADgDIAFAGQgEAEgFACQgFACgHAAQgHAAgGgDgAmBgEQgBgHgEgCQgDgEgGAAQgGAAgEAEQgDADgBAGIAcAAIAAAAgAnkAYIACgJIACAAQABAAAAAAQABAAAAAAQABAAAAAAQABgBAAAAQABAAAAgBQAAAAAAgBQABAAAAgBQAAgBAAAAIABghIAnAAIAAAuIgKAAIAAgmIgTAAIgBAPIgCAOQgBAGgDACQgDACgGAAgAoRAVQgFgDgDgGQgDgFAAgHQAAgHADgGQADgGAFgDQAFgDAGAAQAFAAAFADQAEABACAFIAAgHIAKAAIAAAuIgKAAIAAgHQgCADgEADQgEACgGAAQgGAAgFgDgAoMgOQgDACgCADQgCAEAAAFQAAAEACAEQACAEADACQAEABAEAAQAEAAAEgBQADgCACgEQACgEAAgEQAAgFgCgEQgCgDgDgCQgEgCgEAAQgEAAgEACgApGAWQgFgCgEgEIAGgFQACADAEABQAEABAEAAQAHAAACgCQADgCAAgDQAAgHgKAAIgKAAIAAgGIAIAAQAGAAACgBQACgCAAgEQAAgCgCgCQgCgCgFAAQgJAAgFAFIgFgGQADgCAFgDQAHgCAEAAQAJAAAFADQAFAFAAAFIgCAHQgDAEgDAAQAFABACADQACACAAAFQAAAFgCACQgCADgFADQgFABgHAAQgHAAgEgCgAqGAVQgGgDgDgGQgDgGAAgGQAAgHADgGQADgFAGgEQAFgDAIAAQAGAAAGADQAFABADAFIgFAFQgDgDgDgBQgEgCgEAAIgIACIgGAEIgDAHIAYAAIAAAHIgYAAQACAGAEAEQAFADAGAAIAIgCQAEgBACgDIAFAFQgDAFgFACQgEACgIAAQgHAAgGgDgArBAVQgFgDgDgGQgDgFAAgHQAAgHADgGQADgGAFgDQAFgDAGAAQAFAAAEADQAEABADAFIAAgHIAKAAIAAAuIgKAAIAAgHQgDAEgEACQgDACgGAAQgGAAgFgDgAq8gOQgDABgCAEQgCAFAAAEQAAAEACAEQACAEADACQADABAFAAQAEAAAEgBQADgCACgEQACgEAAgEQAAgFgCgEQgCgDgDgCQgEgCgEAAQgEAAgEACgAt1AYIACgJIACAAQABAAAAAAQABAAABAAQAAAAAAAAQABgBAAAAIACgEIABghIAnAAIAAAuIgKAAIAAgmIgUAAIAAAPQAAAJgCAFQgBAGgDACQgDACgGAAgAxSAVQgEgDgFgGQgDgGAAgGQAAgHADgGQAEgGAFgDQAGgDAHAAQAHAAAGADQAFAEAEAFQADAGAAAHQAAAGgDAGQgEAGgFADQgGADgHAAQgHAAgGgDgAxNgOQgDACgCADQgCAEAAAFQAAAFACACQACAFADACIAIABIAIgBQADgCACgFQACgCAAgFQAAgFgCgEQgCgDgDgCQgEgCgEAAQgEAAgEACgAQ0AXIAAgTIgLAAIgLATIgKAAIAMgTQgGgCgDgCQgDgDAAgGQAAgHAGgEQAFgEAIABIAWAAIAAAugAQggOQgCACAAADQAAAEADACQADACAEAAIAMAAIAAgPIgMAAQgFAAgDACgAP9AXIAAgVIgYAAIAAAVIgJAAIAAguIAJAAIAAASIAYAAIAAgSIAJAAIAAAugAPCAXIAAgVIgYAAIAAAVIgJAAIAAguIAJAAIAAASIAYAAIAAgSIAKAAIAAAugANCAXIAAgmIgRAAIAAgIIArAAIAAAIIgRAAIAAAmgALrAXIAAgiIgZAiIgIAAIAAguIAJAAIAAAhIAZghIAIAAIAAAugAJEAXIgMgTIgCgBIgJAAIAAAUIgJAAIAAguIAJAAIAAASIAIAAIABAAIACgBIAMgRIALAAIgRAWIARAYgAIKAXIAAgiIgZAiIgIAAIAAguIAJAAIAAAhIAZghIAIAAIAAAugAG4AXIAAguIAVAAQAJAAAEACQAFAEAAAGQAAAEgCADIgFADQAEABADADQACADAAAEQAAADgCADIgGAGQgDABgGAAgAHBAQIANAAQAFAAACgCQADgCAAgDQAAgHgKAAIgNAAgAHBgEIALAAQAFAAACgBQADgCAAgDQAAgHgKABIgLAAgAGRAXIAAgTIgLAAIgLATIgLAAIANgTQgGgCgDgCQgDgDAAgGQAAgHAFgEQAFgEAJABIAWAAIAAAugAF9gOQgCACAAADQAAADACADQAEACAEAAIAMAAIAAgPIgMAAQgFAAgDACgABhAXIAAguIAKAAIAAAmIATAAIAAgmIAJAAIAAAmIATAAIAAgmIAKAAIAAAugABIAXIAAgiIgZAiIgIAAIAAguIAJAAIAAAhIAZghIAIAAIAAAugAh/AXIAAguIAKAAIAAARIAKAAQAKgBAFAEQAFADAAAHQAAAJgFADQgGAEgJAAgAh1APIAKAAQAKABAAgJQAAgDgCgCQgDgCgFAAIgKAAgAijAXIAAgmIgRAAIAAgIIArAAIAAAIIgRAAIAAAmgAj0AXIAAguIAKAAIAAAugAkOAXIAAgVIgXAAIAAAVIgKAAIAAguIAKAAIAAASIAXAAIAAgSIAKAAIAAAugAk/AXIgNgUIgFAAIAAAUIgKAAIAAgUIgFAAIgNAUIgLAAIAQgYIgQgWIALAAIAMARIABABIABAAIAEAAIAAgSIAKAAIAAASIAEAAIABAAIABgBIAMgRIALAAIgQAWIAQAYgAraAXIgMgTIgCgBIgJAAIAAAUIgKAAIAAguIAKAAIAAASIAIAAIABAAIABgBIANgRIALAAIgRAWIARAYgAsUAXIAAgiIgZAiIgIAAIAAguIAJAAIAAAhIAZghIAIAAIAAAugAuAAXIgNgTIgBgBIgKAAIAAAUIgJAAIAAguIAJAAIAAASIAIAAIACAAIABgBIANgRIAKAAIgQAWIARAYgAu6AXIAAgiIgZAiIgJAAIAAguIAJAAIAAAhIAZghIAJAAIAAAugAwNAXIAAguIAWAAQAIAAAFACQAEAEAAAGQAAAEgBADQgCACgDABQAEABACADQADADAAAEQAAADgCADIgGAGQgEABgFAAgAwDAQIAMAAQAGAAACgCQACgBAAgEQAAgHgKAAIgMAAgAwDgEIAKAAQAGAAACgBQACgCAAgDQAAgHgKABIgKAAgAjygjIgCgDIgBgCIABgDIACgDIADgBIADABIACADIABADIgBACIgCADIgDABgApIhDIACgIIAGABIAEgBQABAAAAAAQABgBAAAAQABAAAAgBQAAAAABgBIADgHIACgGIgUgvIAKAAIAPAlIAPglIAKAAIgcBAQgDAFgDACQgEABgFAAgAB1hDIAAhHIAJAAIAAAHQAEgFADgBQAEgDAGABQAHAAAEADQAFADADAGQADAFAAAIQAAAHgDAFQgDAHgFACQgFADgGAAQgGAAgEgCQgDgCgEgDIAAAegACFiBQgDACgCAEQgCAFAAAEQAAADACAGQACAEADABQADACAFAAQAFAAACgCQADgBADgEQACgGAAgDQAAgEgCgFQgDgEgDgCQgDgCgEAAQgEAAgEACgAmHhDIAAhHIAKAAIAAAHQACgEAEgCQAFgDAFABQAGAAAFADQAFADADAGQADAFAAAIQAAAHgDAFQgDAHgFACQgFADgGAAQgGAAgEgCQgEgCgCgDIAAAegAl3iBQgDACgCAEQgCADAAAGQAAAFACAEQACAEADABQAEACAEAAQAEAAAEgCQADgBACgEQACgEAAgFQAAgGgCgDQgCgEgDgCQgEgCgEAAQgEAAgEACgASbhMIAFgHIADgHIgEgCQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAgBAAAAQABgBAAgBQAAAAAAgBQABAAAAgBQABAAAAAAQAAAAABgBQAAAAABAAQABAAAAAAQAEAAABACQACACAAAEQAAAGgDAGQgEAGgFADgAPIhdQgHgEgCgFQgDgFAAgHQAAgHADgGQADgGAGgDQAFgDAHAAQAIAAAFADQAGADADAGQADAHAAAGQAAAGgDAGQgDAFgGAEQgGADgHAAQgHAAgFgDgAPNiBQgEADgCADQgCADAAAGQAAAGACACQACADAEADQAEACADAAIAIgCQAEgDACgDQACgEAAgEQAAgEgCgFIgGgGQgDgBgFAAQgFAAgCABgAI2hdQgGgDgDgGQgDgFAAgHQAAgHADgGQAEgHAFgCQAFgDAIAAQAGgBAGADQAGADACAEIgGAGQgCgDgEgCQgDgCgFABQgEAAgEABQgDACgCAEQgCAFAAAEQAAAFACADQACAEADACQAEACAEAAQAFAAADgCIAGgEIAGAFQgDAFgFACQgEACgIAAQgHAAgGgDgAFRhaIACgIIACAAQABAAAAAAQABAAABAAQAAgBAAAAQABAAAAgBIACgEIABgiIAnAAIAAAvIgKAAIAAgnIgUAAIAAARQAAAIgCAFQgBAGgDACQgDACgGAAgAEkhdQgGgEgCgFQgEgFAAgHQAAgIAEgFQADgGAFgDQAGgDAHAAQAIAAAFADQAGADADAGQADAGAAAHQAAAHgDAFQgDAFgGAEQgFADgIAAQgHAAgGgDgAEpiBIgFAGQgCAFAAAEQAAAEACAEQACADADADIAIACQAEAAAEgCQAEgDABgDQACgCAAgGQAAgGgCgDQgBgDgEgDQgDgBgFAAQgEAAgEABgADvhcQgGgCgDgDIAFgGQADADAEABQAEACAEAAQAHAAACgCQADgCAAgDQAAgIgKAAIgKAAIAAgGIAIAAQAFAAADgCQACgCAAgDQAAgDgCgCQgCgCgFABQgJgBgFAGIgFgGQADgEAFgCQAHgBAEAAQAJAAAFADQAEAEAAAGQAAADgBADQgDAEgDABQAFABACADQACADAAAEQAAAFgCADQgCADgFACQgFABgHAAQgHAAgEgCgAC5hdQgGgEgDgFQgDgFAAgHQAAgHADgGQAEgGAFgDQAFgDAIAAQAHAAAFADQAFACAEAHQADAGAAAHQAAAHgDAFQgDAGgGADQgFADgHAAQgHAAgGgDgAC+iBIgGAGQgCADAAAGQAAAGACACQADAEADACIAIACIAHgCQADgCADgEQACgCAAgGQAAgGgCgDIgGgGQgDgBgEAAQgFAAgDABgABDhdQgGgEgCgFQgEgFAAgHQAAgHADgHQAFgFAEgDQAFgDAHAAQAHAAAFACQAGAFADAEQADAGAAAGIAAAEIgmAAQABAFACADQABADAEABQAEACAEABIAJgCQADgBADgDIAFAGQgDADgGACQgEACgHAAQgIAAgGgDgABeh3QgCgFgDgEQgFgEgFABQgFgBgEAEQgEAEgBAFIAdAAIAAAAgAgwhaIgCgDIgBgCIABgEIACgCIAEgBIADABIACACIABAEIgBACIgCADIgDAAgAkNhcQgGgCgDgDIAGgGQACADAEABIAIACQAHAAACgCQADgCAAgDQAAgIgKAAIgKAAIAAgGIAIAAQAGAAACgCQADgCAAgDQAAgCgDgDQgDgCgEABQgJgBgFAGIgFgGIAIgGQAGgBAFAAQAJAAAFADQAFADAAAHQAAAEgCACQgCADgEACQAFABACADQADAEAAADQAAAEgDAEQgDADgEACQgFABgHAAQgHAAgEgCgAoHhdQgGgDgDgGQgDgFAAgHQAAgHADgGQAEgGAFgDQAFgDAIAAQAGgBAGADQAGADACAEIgGAGQgCgDgEgCQgDgCgFABQgEAAgEABQgDACgCAEQgCADAAAGQAAAFACADQABADAEADQADACAFAAQAFAAADgCIAGgEIAGAFQgDAFgFACQgFACgHAAQgHAAgGgDgAp8hdQgFgDgEgGQgDgFAAgHQAAgHADgGQAFgHAEgCQAFgDAIAAQAGgBAGADQAFADADADIgFAGIgHgFQgDgCgFABQgEgBgDACIgGAFIgDAHIAYAAIAAAHIgYAAQABAFAEAFQAFAEAGAAIAIgCQAEgBADgDIAFAFQgCAEgGACQgFACgHAAQgHAAgGgDgAq3hdQgGgCgDgHQgDgFAAgHQAAgIADgFQADgGAGgDQAEgDAHAAQAFgBAEADQAEACADAEIAAgHIAJAAIAAAvIgJAAIAAgGIgHAFQgDACgGAAQgHAAgEgDgAqyiBQgDACgCAEQgCADAAAGQAAAFACAEQACAEADABQADACAFAAQAFAAACgCQADgBADgEQABgEAAgFQAAgFgBgEQgDgEgDgCQgDgCgEAAQgEAAgEACgAsihdQgFgCgDgFQgEgGAAgGIgIAAIAAAVIgJAAIAAgvIAJAAIAAASIAIAAQABgFADgFQADgEAGgDQAFgDAGABQAHAAAFADQAGADADAGQADAFAAAIQAAAHgDAFQgDAFgGAEQgFADgHAAQgGAAgGgDgAseiBQgEADgBADQgCAFAAAEQAAAEACAEQACADADADQAEACAEAAQADAAAEgCQAEgDABgDQACgFAAgDQAAgEgCgFQgBgDgEgDQgCgBgFAAQgFAAgDABgAt/haIACgIIACAAQABAAAAAAQABAAABAAQAAgBAAAAQABAAAAgBIACgEIABgiIAnAAIAAAvIgJAAIAAgnIgUAAIgBARIgCANQgBAGgDACQgDACgGAAgAxbhdQgHgEgCgFQgEgFAAgHQAAgIAEgGQADgFAFgDQAFgDAHAAQAHAAAFACQAGAEADAFQADAGAAAGIAAAEIgmAAQAAAEADAEQACADADABQAEACAEABIAJgCQADgBADgDIAFAGQgDADgGACQgEACgHAAQgIAAgFgDgAxBh3QgCgFgDgEQgFgEgFABQgFgBgEAEQgEAEgBAFIAdAAIAAAAgASGhbIAAgVIgYAAIAAAVIgJAAIAAgvIAJAAIAAASIAYAAIAAgSIAJAAIAAAvgARMhbIAAgiIgZAiIgJAAIAAgvIAJAAIAAAjIAZgjIAJAAIAAAvgAQFhbIAAgnIgQAAIAAgIIAqAAIAAAIIgQAAIAAAngAOuhbIgMgTIgCgBIgJAAIAAAUIgJAAIAAgvIAJAAIAAASIAIAAIACAAIABgBIAMgRIALAAIgRAXIARAYgAN6hbIAAgvIAKAAIAAAvgANghbIAAgVIgXAAIAAAVIgKAAIAAgvIAKAAIAAASIAXAAIAAgSIAKAAIAAAvgAL7hbIAAgvIAJAAIAAARIALAAQAIAAAGADQAFAEAAAIQAAAIgFAEQgFADgJAAgAMEhiIAKAAQALAAAAgIQAAgDgDgDQgDgCgFABIgKAAgALWhbIAAgnIgQAAIAAgIIAqAAIAAAIIgQAAIAAAngAKxhbIAAgiIgZAiIgJAAIAAgvIAJAAIAAAjIAZgjIAJAAIAAAvgAJrhbIAAgnIgRAAIAAgIIAqAAIAAAIIgQAAIAAAngAIahbIAAgvIAJAAIAAAvgAIEhbIAAghIgQAVIgGAAIgQgVIAAAhIgJAAIAAgvIAJAAIATAZIATgZIAJAAIAAAvgAGRhbIAAgvIAJAAIAAARIALAAQAIAAAGADQAFAEAAAIQAAAIgFAEQgFADgJAAgAGahiIAKAAQALAAAAgIQAAgDgDgDQgDgCgFABIgKAAgAAlhbIgFgNIggAAIgEANIgKAAIAahFIAIAAIAbBFgAAdhwIgNgiIgNAiIAaAAgAhhhbIAAgvIAVAAQAJAAAEADQAFAEAAAFQAAAEgCADIgFAEQAEABADADQACADAAAEQAAAFgCACQgBACgFADQgDABgGAAgAhYhhIANAAQAFgBACgCQADgBAAgDQAAgIgKAAIgNAAgAhYh2IAKAAQAFAAADgCQADgBAAgDQAAgHgLAAIgKAAgAh1hbIAAgvIAKAAIAAAvgAiFhbIgOgUIgJAAIAAAUIgKAAIAAgvIAKAAIAAASIAIAAIABAAIABgBIANgRIALAAIgRAXIARAYgAi/hbIAAgiIgZAiIgIAAIAAgvIAJAAIAAAjIAYgjIAJAAIAAAvgAkrhbIAAgiIgYAiIgJAAIAAgvIAJAAIAAAjIAZgjIAIAAIAAAvgAmrhbIgNgRIgNARIgLAAIASgXIgSgYIALAAIANARIANgRIALAAIgSAYIASAXgAnfhbIAAgvIAKAAIAAAvgArUhbIAAgTQgGADgHAAQgEAAgFgCQgEgCgDgEQgCgDAAgGIAAgOIAKAAIAAANQAAAFACACQACACAGAAQAHAAAEgCIAAgUIAKAAIAAAvgAuKhbIgOgUIgJAAIAAAUIgKAAIAAgvIAKAAIAAASIAIAAIABAAIABgBIANgRIALAAIgRAXIARAYgAvEhbIAAgiIgZAiIgIAAIAAgvIAJAAIAAAjIAYgjIAJAAIAAAvgAwWhbIAAgvIAVAAQAJAAAEADQAFAEAAAFQAAAEgCADIgFAEQAEABADADQACADAAAEQAAAFgCACQgBACgFADQgDABgGAAgAwNhhIANAAQAFgBACgCQADgBAAgDQAAgIgKAAIgNAAgAwNh2IAKAAQAGAAACgCQACgBAAgDQAAgHgKAAIgKAAgAx5hbIAAgfIglAAIAAAfIgJAAIAAhFIAJAAIAAAdIAlAAIAAgdIAJAAIAABFgAN8iVIgCgDIgBgDIABgDIACgCIADgBIADABIACACIABADIgBADIgCADIgDAAgAIbiVIgCgDIgBgDIABgDIACgCIAEgBIADABIACACIABADIgBADIgCADIgDAAgAhziVIgCgDIgBgDIABgDIACgCIADgBIADABIACACIABADIgBADIgCADIgDAAgAndiVIgCgDIgBgDIABgDIACgCIADgBIADABIACACIABADIgBADIgCADIgDAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.urText, new cjs.Rectangle(-119.4,-16.2,238.9,32.4), null);


(lib.t1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#23BACC").s().p("ACuCDIA4hUQgFABgKAAQgYAAgVgLQgUgLgMgUQgMgTAAgZQAAgZANgWQAMgUAXgMQAVgNAcAAQAbAAAWAMQAVAKANAVQANAUAAAbQAAAUgHASQgHASgOAVIg+BegADHhOQgLAHgFAJQgGALAAANQAAANAGAKQAGAKAKAFQALAGAMAAQANAAALgGQAKgEAGgLQAGgLAAgNQAAgMgGgLQgGgKgKgGQgLgGgNAAQgMAAgLAGgAgvCDIA3hUQgFABgJAAQgYAAgVgLQgUgLgMgUQgMgTAAgZQAAgZANgWQANgUAWgMQAVgNAbAAQAaAAAXAMQAVALANAUQANAUAAAbQAAAUgHASQgHASgOAVIg+BegAgWhOQgLAHgFAJQgGALAAANQAAANAGAKQAGAKAKAFQALAGALAAQANAAALgGQAKgEAGgLQAGgLAAgNQAAgMgGgLQgGgKgKgGQgLgGgNAAQgLAAgLAGgAkjCDIAAgnIBXhdQAKgMAGgLQAGgLAAgMQAAgQgMgKQgLgKgUAAQgOAAgPAFQgNADgPAIIgTgpQASgLAUgFQAVgGAVAAQAbAAAUAJQAUAIAMASQALARAAAZQAAASgHASQgHARgLAOQgMAPgUAUIgkAlIBgAAIAAAtgAmHCDIAAjOIhFAfIAAguIBPgiIAoAAIAAD/gAGFArQgIgDgHgFQgHgFgDgHQgEgIAAgJIABgIIADgIIgNAAIAAgVIAdAAIALgKIAMgKIg0AAIAAgWIBFAAIABgGQAAgKgFgEQgFgEgGAAQgIAAgHADQgHADgFAFIgOgVQAHgJAMgEQAJgEAPAAQALAAAGADQAIADAGAEQAFAFAEAHQADAHAAAIIgBAIQgBAEgCACIAPAAIAAAWIgcAAIgXAUIAzAAIAAAVIhGAAIgDAGIgBAFQAAAHAGAFQAHAFAKAAQAIAAAIgDQAIgDAHgHIAOASQgHALgNAGQgOAFgPAAQgIAAgJgCg");
	this.shape.setTransform(-20.5,34.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AGtD7QgQgJgJgPQgJgQAAgTQAAgTAJgRQAKgPAPgJQAQgJATAAQAUAAAPAJQAPAJAJAQQAJAQAAATQAAATgJAQQgJAPgPAJQgPAKgUAAQgTAAgQgKgAG6CZQgJAFgGALQgFALAAAMQAAAMAFAMQAGAKAJAFQAKAGAMgBQALABAKgGQAKgFAFgKQAGgKAAgOQAAgOgGgJQgFgLgKgFQgJgGgMAAQgMAAgKAGgAD0D/QgLgGgFgKQgGgMAAgOIAAhAIgfAAIAAgUIANgBQAFAAAGgDQAEgDACgEQABgEAAgHIAAgaIAaAAIAAAtIA3AAIAAAXIg3AAIAAA8QAAAOAGAHQAHAHANAAQAQAAAMgNIANARQgHAJgNAFQgLAGgPAAQgNgBgMgFgAABD8QgNgIgJgRQgIgPAAgUQAAgVAIgPQAIgPAOgJQAPgJARAAQAOAAALAGQAMAGAHALIAAhXIAaAAIAADGIgaAAIAAgTQgIALgLAGQgMAFgNABQgRgBgPgIgAAQCYQgIAFgGALQgFALAAANQAAAMAFAMQAFAKAJAGQAJAFAMAAQAMAAAJgFQAJgGAGgKQAFgMAAgMQAAgNgFgLQgGgLgJgFQgJgFgMgBQgMABgJAFgAl0D7QgQgJgJgPQgJgQAAgTQAAgUAJgQQAIgPAQgJQAPgJATAAQARAAAQAJQAOAHAJAPQAJAQAAASIgBALIhoAAQABAMAGAIQAFAJALAFQALAFALAAQAMAAALgFQAMgEAGgHIAOARQgJAKgPAFQgQAHgRAAQgUAAgQgKgAluCaQgLAKgCAQIBPAAQgDgRgKgJQgLgJgPAAQgRAAgKAJgAKPEBIAAhOQAAgOgJgJQgIgJgOAAQgLAAgJAFQgJAFgGAIIAABcIgaAAIAAiDIAZAAIAAARQAHgJALgGQALgFANAAQAPAAALAGQALAGAHALQAHANAAAPIAABTgAFVEBIAAiDIAaAAIAACDgACREBIAAiDIAaAAIAACDgAiwEBIAAjAIB4AAIAAAYIhdAAIAAA6IBVAAIAAAYIhVAAIAAA+IBgAAIAAAYgAnwEBIgwiTIgyCTIgXAAIg/jAIAcAAIAwCVIAxiVIAXAAIAvCVIAxiVIAcAAIhBDAgAFZBfQgDgDgDgDQgCgEAAgFQAAgEACgEQADgEADgCQAEgCAEgBQAFABAEACQAEACACAEQACAEAAAEQAAAFgCAEQgCADgEADQgEACgFAAQgEAAgEgCgACVBfQgDgDgDgDQgCgEAAgFQAAgEACgEIAGgGQAEgCAFgBQAEABAEACQAEACACAEQADAEAAAEQAAAFgDAEQgCADgEADQgEACgEAAQgFAAgEgCgAIIhKQgWgNgNgWQgNgVAAgeQAAgeANgWQANgWAWgMQAXgNAbgBQAbABAXANQAXANANAVQANAYAAAcQAAAcgNAXQgNAWgXANQgXANgbAAQgbAAgXgNgAIWjhQgQAJgKARQgJASAAAVQAAAVAJARQAKASAQAIQAQAKAUAAQAVAAAQgKQAQgIAJgSQAKgRAAgVQAAgWgKgRQgJgRgQgJQgQgJgVAAQgUAAgQAJgAE9hGQgRgIgKgRQgJgPAAgXIAAh7IAaAAIAAB4QAAAPAGAMQAGALAMAGQAMAHAOgBQAPABALgHQALgFAGgMQAGgMAAgPIAAh4IAaAAIAAB7QAAAXgJAPQgKARgQAIQgSAJgWAAQgWAAgSgJgAlGhKQgWgNgOgWQgMgWAAgdQAAgeAMgWQAOgWAWgMQAXgNAbgBQAbABAXANQAWAMANAWQANAYAAAcQAAAcgNAXQgNAWgWANQgXANgbAAQgbAAgXgNgAk5jhQgPAJgKARQgJASAAAVQAAAVAJARQAJASAQAIQAQAKAVAAQAUAAAQgKQARgIAJgSQAJgSAAgUQAAgVgJgSQgKgRgQgJQgQgJgUAAQgVAAgQAJgAokhKQgXgNgMgWQgNgVAAgeQAAgeANgWQAMgVAXgNQAXgNAbgBQAbABAXANQAXANAMAVQANAYAAAcQAAAUgGAQQgGARgMANIAaAeIgdAAIgNgPQgMAIgPAGQgPAEgQAAQgbAAgXgNgAoXjhQgPAJgKARQgJASAAAVQAAAVAJARQAJASAQAIQAQAKAVAAQAYAAARgNIgogtIARgOIAnAsQAHgIAEgNQADgNAAgMQAAgWgJgRQgKgRgQgJQgPgJgVAAQgVAAgQAJgAh+hEQgTgHgLgMIAOgTQAKAJAOAHQAPAFAQAAQANAAAJgEQAJgEAGgGQAFgJAAgJQAAgLgGgHQgHgHgJgDIgZgJQgQgGgPgGQgMgFgJgLQgIgKAAgQQAAgRAJgLQAJgNAOgEQAPgHAUAAQASABASAFQARAGALALIgNATQgKgIgMgFQgPgFgOAAQgSAAgLAHQgLAGAAAOQAAAIAFAGQAGAHAIADIAYAIQAQAFARAHQANAGAJAMQAJALAAATQAAASgJAMQgJANgPAGQgPAHgVgBQgVAAgSgGgABRhAIAAjAIA/AAQAeAAAXAMQAXALAMAWQANAVAAAeQAAAdgMAXQgNAUgXAMQgYAMgdAAgABrhYIAjAAQAWAAASgIQARgIAJgQQAKgQAAgYQAAgYgKgQQgKgQgQgIQgSgJgWAAIgjAAgAqVhAIAAjAIAaAAIAADAg");
	this.shape_1.setTransform(0,-21.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1, new cjs.Rectangle(-68,-47.6,136.1,95.2), null);


(lib.r_part = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhijHQBSAAA5A7QA6A6AABSQAABTg6A6Qg5A7hSAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.r_part, new cjs.Rectangle(-9.9,-20,19.9,40), null);


(lib.l_part = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgoCNQg7g6AAhTQAAhSA7g6QA5g7BTAAIAAGPQhTAAg5g7g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.l_part, new cjs.Rectangle(-9.9,-20,19.9,40), null);


(lib.iqos_logo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhxGrIgegeIgEgCIgDgBIiGAAQgqAAgYgVQgXgSAAgeIAAhyQABgFADgDQAEgEAFAAICZAAQApAAAZAUQAWATAAAeIAAA1QAAAGgDADQgEADgEABIgFAAQgFgBgEgDQgDgDAAgGIAAg1QAAgIgDgGQgEgHgFgGQgIgGgNgEQgLgDgQAAIiFAAIgDABIgBADIAABdQAAAIAEAHQACAHAHAFQAHAHANADQAMADAPAAICOAAIAHABIAGAFIAkAkQADADAAAFQAAAFgDAEIgDADQgEADgEAAQgHAAgCgDgAEcGKQgOAAgNgFQgNgGgJgJIgHgGQgDgDgBgGQABgFADgDIADgEQADgDAFAAQAFAAAEADIAHAHQAGAFAHADQAHADAJAAIBgAAQAOABAKgDQAKgDAGgEIAFgHQACgEAAgHQAAgHgCgDQgCgEgDgEQgGgEgKgDQgKgCgOAAIhRAAQglAAgVgQQgRgOAAgXIAAgGQAAgYARgOQAVgPAlAAIBZAAQANAAAMAFQAMAEAKAJIAIAIQAEADAAAFQAAAFgCAEIgDADQgEAEgFAAQgFABgEgEIgIgHQgFgFgJgEQgHgCgHAAIhZAAQgNAAgLACQgKADgGAFQgDACgCAEQgBAEAAAHQAAAHABAEQACAEADADQAGAFAKACQALACANABIBRAAQAmgBATAQQASANAAAYIAAAGQAAAYgSAOQgTAPgmAAgAARGKQgoAAgZgVQgWgSAAgeIAAg5QAAgeAWgTQAZgUAoAAIBOAAQApAAAYAUQAWATABAeIAAA5QgBAegWASQgYAVgpAAgAgJDnQgMAEgJAGQgFAGgDAHQgEAGABAIIAAA5QgBAIAEAHQADAHAFAFQAJAHAMADQALADAPAAIBOAAQAPAAAMgDQAMgDAHgHQAHgFADgHQAEgHAAgIIAAg5QAAgJgEgFQgDgHgHgGQgHgGgMgEQgMgDgPAAIhOAAQgPAAgLADgAm6GKQgEAAgFgDQgDgEAAgFIAAirQAAgFADgDQAFgEAEAAIAEAAQAGAAADAEQAEAEAAAEIAACrQAAAFgEAEQgDADgGAAgAhtAxQgpABghgVQgggTgTggQgSgggBgmQgBgmAUgkIBvi/QAUgiAigTQAhgTAkAAQAmAAAgATQAiATAUAiIBvC/QAUAkgBAmQgBAmgSAgQgTAgggATQgiAVgogBgAhJlLQghAOgaAaQgaAbgOAhQgPAkAAAmQAAAnAPAiQAOAhAaAcQAaAZAhANQAkAQAlAAQAmAAAkgQQAhgNAagZQAagcAOghQAPgiAAgnQAAgmgPgkQgOghgagbQgagaghgOQgkgPgmAAQglAAgkAPg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.iqos_logo, new cjs.Rectangle(-45.5,-43,91,86), null);


(lib.btn_txt = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#35303E").s().p("AhPBDIAAgUIhDAAIAAhLIAQAAIAAA+IAlAAIAAg+IAPAAIAAA+IAMAAIAAAhgAFJAwIgEgEIgBgFIABgFIAEgEIAFgCQADABACABIAEAEIABAFQAAAEgCADQgDADgFAAIgFgBgAjkAsQgJgFgEgJQgFgJAAgMQAAgLAFgJQAEgJAJgFQAJgGAJAAQAJAAAGAEQAHAEAEAGIAAgLIAPAAIAABLIgPAAIAAgLQgEAGgHAEQgIADgHAAQgJABgJgGgAjbgOQgGAEgDAGQgDAGAAAHQAAAHADAGQADAHAGADQAEADAIABQAHgBAFgDQAFgDADgHQADgFAAgIQAAgIgDgFQgDgGgFgEQgHgDgFAAQgHAAgFADgAlFAtQgLgEgHgFIAIgMQAGAFAJADQAIACAJABQAMgBAGgEQAHgFAAgKQAAgJgFgFQgFgDgLAAIgTAAIAAgOIAQAAQAKAAAFgEQAFgFAAgJQAAgIgGgFQgGgFgKAAQgQAAgOAKIgHgLQAHgGAKgDQAJgEAMAAQALAAAIAEQAJAEAEAGQAFAHAAAKQAAAIgEAHQgDAGgHAEQAHADAGAHQAFAHAAAKQAAAKgFAHQgFAIgKADQgJAEgMAAQgLAAgLgEgAEkAvIAAg3IgoA3IgNAAIAAhLIAOAAIAAA3IAog3IANAAIAABLgAC1AvIAAg+IgaAAIAAgNIBEAAIAAANIgbAAIAAA+gACAAvIAAg3IgoA3IgNAAIAAhLIAOAAIAAA3IAog3IAOAAIAABLgAApAvIAAgiIgmAAIAAAiIgOAAIAAhLIAOAAIAAAdIAmAAIAAgdIAPAAIAABLgAgxAvIAAhLIAPAAIAABLgAFHAPIAAhPIAPAAIgBBPgAgugvIgEgEIgBgEIABgGQABAAAAAAQAAgBABAAQAAgBABAAQAAAAABAAQAAgBABAAQAAAAABgBQAAAAABAAQABAAAAAAIAGACIADACIABAGIgBAEIgDAEIgGACQAAAAgBgBQgBAAAAAAQgBAAAAAAQgBgBAAAAg");
	this.shape.setTransform(0.2,-0.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.btn_txt, new cjs.Rectangle(-34.2,-7.2,68.9,13.4), null);


(lib.btn_round = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AiMCNQg7g6AAhTQAAhSA7g6QA6g7BSAAQBTAAA6A7QA7A6AABSQAABTg7A6Qg6A7hTAAQhSAAg6g7g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.btn_round, new cjs.Rectangle(-20,-20,40,40), null);


(lib.btn_bg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AmGDIQhSAAg6g6Qg6g5gBhTIAAgCQABhSA6g6QA6g7BSAAIMMAAQBTAAA7A7QA5A6AABSIAAACQAABSg5A6Qg7A6hTAAg");
	this.shape.setTransform(0.2,0);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.btn_bg, new cjs.Rectangle(-58.7,-20,117.9,40), null);


(lib.bgImg2_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.bgImg2();
	this.instance.parent = this;
	this.instance.setTransform(-150,-182);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bgImg2_1, new cjs.Rectangle(-150,-182,300,364), null);


(lib.bgImg1_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.bgImg1();
	this.instance.parent = this;
	this.instance.setTransform(-150,-182);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bgImg1_1, new cjs.Rectangle(-150,-182,300,364), null);


(lib.bg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#35303E").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.bg, new cjs.Rectangle(-150,-300,300,600), null);


(lib.btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_4
	this.instance = new lib.btn_txt();
	this.instance.parent = this;
	this.instance.setTransform(0,8.9);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(12).to({_off:false},0).to({y:0.7,alpha:1},8).wait(1));

	// r_part
	this.instance_1 = new lib.r_part();
	this.instance_1.parent = this;
	this.instance_1.setTransform(10.1,0);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(9).to({_off:false},0).to({x:49.6},8,cjs.Ease.get(1)).to({_off:true},1).wait(3));

	// l_part
	this.instance_2 = new lib.l_part();
	this.instance_2.parent = this;
	this.instance_2.setTransform(-10,0);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(9).to({_off:false},0).to({x:-48.8},8,cjs.Ease.get(1)).to({_off:true},1).wait(3));

	// Слой_5
	this.instance_3 = new lib.btn_bg();
	this.instance_3.parent = this;
	this.instance_3.setTransform(0,0,0.01,1);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(9).to({_off:false},0).to({scaleX:1},8,cjs.Ease.get(1)).wait(4));

	// Слой_1
	this.instance_4 = new lib.btn_round();
	this.instance_4.parent = this;
	this.instance_4.setTransform(0,0,0.012,0.012);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({scaleX:1.2,scaleY:1.2},5,cjs.Ease.get(1)).to({scaleX:1,scaleY:1},4,cjs.Ease.quadInOut).to({_off:true},9).wait(3));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-0.2,-0.2,0.5,0.5);


(lib.banner = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{loop:65});

	// timeline functions:
	this.frame_165 = function() {
		this.gotoAndPlay('loop');
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(165).call(this.frame_165).wait(1));

	// logo
	this.instance = new lib.iqos_logo();
	this.instance.parent = this;
	this.instance.setTransform(99.7,207.2,0.647,0.647,0,0,0,0.3,-0.6);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:1},15).wait(151));

	// urText
	this.instance_1 = new lib.urText();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-8.9,268.1,1,1,0,0,0,0.1,0.3);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({regY:0.2,scaleX:1,alpha:1},15).wait(151));

	// btn
	this.instance_2 = new lib.btn("synched",0,false);
	this.instance_2.parent = this;
	this.instance_2.setTransform(-79.1,215.9,0.86,0.86,0,0,0,-0.3,0.6);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(25).to({_off:false},0).wait(66).to({startPosition:20},0).wait(2).to({regX:-0.5,regY:0.7,scaleX:0.82,scaleY:0.82},0).wait(2).to({regX:-0.3,regY:0.6,scaleX:0.86,scaleY:0.86},0).wait(3).to({startPosition:20},0).wait(2).to({regX:-0.5,regY:0.7,scaleX:0.82,scaleY:0.82},0).wait(2).to({regX:-0.3,regY:0.6,scaleX:0.86,scaleY:0.86},0).wait(64));

	// t1
	this.instance_3 = new lib.t1();
	this.instance_3.parent = this;
	this.instance_3.setTransform(-22.5,129.1);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(15).to({_off:false},0).to({x:-62.5,alpha:1},10,cjs.Ease.cubicOut).wait(141));

	// bgImg
	this.instance_4 = new lib.bgImg2_1();
	this.instance_4.parent = this;
	this.instance_4.setTransform(0,-118);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(65).to({_off:false},0).to({alpha:1},10).wait(40).to({alpha:0},10).to({_off:true},1).wait(40));

	// bgImg
	this.instance_5 = new lib.bgImg1_1();
	this.instance_5.parent = this;
	this.instance_5.setTransform(0,-118);
	this.instance_5.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).to({alpha:1},15).wait(151));

	// bg
	this.instance_6 = new lib.bg();
	this.instance_6.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(166));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,-300,300,600);


// stage content:
(lib._300x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// cover
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#666666").ss(2,2,0,3).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// banner
	this.instance = new lib.banner();
	this.instance.parent = this;
	this.instance.setTransform(150.1,300.1,1,1,0,0,0,0.1,0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(149,299,302,602);
// library properties:
lib.properties = {
	id: '0A6E3F5DF6B342F4AF907DBE848CDF8D',
	width: 300,
	height: 600,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/bgImg1.jpg", id:"bgImg1"},
		{src:"images/bgImg2.jpg", id:"bgImg2"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['0A6E3F5DF6B342F4AF907DBE848CDF8D'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;