(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 300,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	manifest: [
		{src:"images/img1.jpg", id:"img1"},
		{src:"images/img2.jpg", id:"img2"},
		{src:"images/img3.jpg", id:"img3"},
		{src:"images/img4.jpg", id:"img4"},
		{src:"images/img7.jpg", id:"img7"}
	]
};



// symbols:



(lib.img1 = function() {
	this.initialize(img.img1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.img2 = function() {
	this.initialize(img.img2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.img3 = function() {
	this.initialize(img.img3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.img4 = function() {
	this.initialize(img.img4);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.img7 = function() {
	this.initialize(img.img7);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.t4 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACFBYIAAgMIghAAIAAAMIgKAAIAAgWIAEAAQAHgJAAgUIAAgQIAlAAIAAAtIAGAAIAAAWgABwAmQgBATgFAJIAVAAIAAgkIgPAAgAGHBJQgKgIAAgRQAAgRAKgHQAHgFAKAAQAJAAAHAFQAKAHAAARQAAARgKAIQgHAEgJAAQgKAAgHgEgAGIAwQABAUAPAAQAPAAAAgUQgBgKgFgFQgEgEgFAAQgPAAgBATgAESBNIAAgKIAFABQAEAAACgFIgWgqIAMAAIAQAfIALgfIANAAIgVAuQgDAKgJAAgAAnBJQgLgIAAgRQAAgRALgHQAGgFAKAAQAIAAAHAFQALAHAAARQAAARgLAIQgHAEgIAAQgKAAgGgEgAAnAwQABAUAPAAQAOAAAAgUQAAgTgOAAQgPAAgBATgAhlBNIAAgKIAFABQADAAACgFIgWgqIANAAIAPAfIALgfIAOAAIgVAuQgEAKgJAAgAHgBMIgRgYIgGAFIAAATIgLAAIAAg3IALAAIAAAWIAWgWIAOAAIgWAWIAYAhgAFlBMIAAgZIgVAAIAAAZIgLAAIAAg3IALAAIAAAVIAVAAIAAgVIAMAAIAAA3gADVBMIAAg3IAZAAQARAAABARQgBAGgDAFQgEAHgLAAIgMAAIAAAUgADhAuIAKAAQAJAAAAgIQgBgIgJAAIgJAAgAC+BMIgEgLIgUAAIgDALIgNAAIAUg3IANAAIATA3gAC4A3IgIgWIgHAWIAPAAgAAEBMIAAguIgTAAIAAAuIgMAAIAAg3IArAAIAAA3gACLgEIAAgLIghAAIAAALIgLAAIAAgVIAFAAQAHgJgBgUIAAgRIAmAAIAAAuIAFAAIAAAVgAB2g1QgBATgFAJIAUAAIAAgkIgOAAgAHGgPIAAgJIAFABQADAAACgFIgWgrIANAAIAPAfIALgfIAOAAIgVAvQgEAKgJAAgAEVgTQgLgHAAgRQAAgRALgHQAHgFAJAAQAJAAAHAFQAKAHAAARQAAARgKAHQgHAFgJAAQgJAAgHgFgAEWgrQAAATAPAAQAPAAAAgTQAAgTgPAAQgPAAAAATgAi+gPIAAgJIAFABQAEAAACgFIgWgrIAMAAIAPAfIAMgfIANAAIgUAvQgEAKgKAAgAnjgTQgLgHAAgRQAAgRALgHQAHgFAIAAQAKAAAGAFQALAHAAARQAAARgLAHQgGAFgKAAQgIAAgHgFgAnigrQgBATAPAAQAQAAgBgTQABgTgQAAQgPAAABATgAGlgPIAAgZIgWAAIAAAZIgLAAIAAg4IALAAIAAAVIAWAAIAAgVIAMAAIAAA4gAFLgPIAAg4IApAAIAAAKIgdAAIAAALIAOAAQAIAAAGAFQAFAFAAAIQAAARgTAAgAFXgZIANAAQAIAAAAgIQAAgHgIAAIgNAAgADWgPIAAg4IAZAAQARAAAAASQAAAGgDAFQgEAHgLAAIgMAAIAAAUgADigtIAKAAQAJAAAAgIQgBgIgJAAIgJAAgACggPIAAg4IApAAIAAAKIgdAAIAAALIAaAAIAAAKIgaAAIAAAPIAeAAIAAAKgAAvgPIAAg4IAaAAQARAAAAASQAAAGgEAFQgFAHgJAAIgOAAIAAAUgAA6gtIALAAQAJAAAAgIQAAgIgKAAIgKAAgAAYgPIgDgMIgUAAIgDAMIgLAAIARg4IAOAAIATA4gAATgkIgIgWIAAAAIgHAWIAPAAgAg3gPIAAg4IAoAAIAAAKIgcAAIAAAugAhogPIAAgoIgYAoIgLAAIAAg4IALAAIAAAnIAWgnIANAAIAAA4gAjdgPIAAgvIgLAvIgLAAIgKgvIgBAAIAAAvIgKAAIAAg4IARAAIAJAsIABAAIAJgsIASAAIAAA4gAkigPIAAgoIgWAoIgNAAIAAg4IAMAAIAAAnIAWgnIANAAIAAA4gAl7gPIAAg4IAZAAQARAAAAASQAAAGgDAFQgFAHgJAAIgNAAIAAAUgAlvgtIALAAQAIAAAAgIQAAgIgKAAIgJAAgAmhgPIAAguIgRAAIAAgKIAtAAIAAAKIgQAAIAAAugAiBhXIAFAAQABAGAGAAQAHAAABgGIAFAAQAAALgNAAQgKAAgCgLg");
	this.shape.setTransform(0,0,4.173,4.173);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-206.7,-36.8,413.5,73.7);


(lib.t3 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AG/BSIAAgKIAEABQAEAAACgEIgWgrIANAAIAPAfIALgfIANAAIgUAuQgEAKgJAAgAgbBSIAAgKIAFABQADAAACgEIgWgrIANAAIAPAfIALgfIAMAAIgTAuQgEAKgIAAgAGBBRIAAg3IAaAAQAQAAABARQAAAHgEAEQgEAIgKgBIgOAAIAAAUgAGMAzIAMAAQAIAAAAgIQAAgIgKAAIgKAAgAFoBRIAAgnIgBAAIgWAnIgMAAIAAg3IAMAAIAAAmIAVgmIAOAAIAAA3gAEfBRIAAguIgRAAIAAgJIAtAAIAAAJIgRAAIAAAugADcBRIAAg3IAaAAQAQAAAAARQAAAHgDAEQgEAIgKgBIgNAAIAAAUgADoAzIAKAAQAJAAAAgIQAAgIgKAAIgJAAgADFBRIgDgLIgUAAIgFALIgLAAIATg3IANAAIAUA3gADAA8IgIgVIgHAVIAPAAgABoBRIAAg3IAbAAQAIAAAFAFQAEADAAAGQAAAJgHACQAJAEAAAJQAAARgXAAgABzBHIAOAAQAJABAAgJQAAgGgIAAIgPAAgABzAwIAOAAQAHgBAAgFQABgHgJAAIgNAAgABPBRIgRgYIgFAFIAAATIgMAAIAAg3IAMAAIAAAXIAWgXIAOAAIgXAXIAZAggAg8BRIAAgYIgVAAIAAAYIgLAAIAAg3IALAAIAAAVIAVAAIAAgVIAMAAIAAA3gAiCBRIAAguIgRAAIAAgJIAtAAIAAAJIgRAAIAAAugAiiBRIgDgLIgVAAIgEALIgLAAIAUg3IAMAAIAUA3gAioA8IgHgVIAAAAIgHAVIAOAAgAjfBRIAAgYIgVAAIAAAYIgMAAIAAg3IAMAAIAAAVIAVAAIAAgVIAMAAIAAA3gAkYBRIAAguIgBAAIgKAuIgMAAIgKguIAAAuIgLAAIAAg3IARAAIAKAsIAKgsIARAAIAAA3gAldBRIAAg3IAMAAIAAA3gAl0BRIgRgYIgGAFIAAATIgLAAIAAg3IALAAIAAAXIAVgXIAPAAIgWAXIAXAggAnnBRQAAgMANgJQAIgGADgDQADgDAAgFQgBgHgHgBQgIAAAAALIgKAAQAAgUARAAQAJABAFAEQAFAFAAAIQAAAKgLAHQgLAIgCACIAYAAIAAAKgAm4BCIAAgIIAWAAIAAAIgAGCgKIAAgJIAFABQADAAADgEIgWgrIAMAAIAPAeIAMgeIANAAIgVAuQgDALgKgBgAEPgKIAAgJIAFABQADAAADgEIgXgrIANAAIAPAeIALgeIAOAAIgVAuQgEALgJgBgAHYgKIAAgnIgBAAIgXAnIgLAAIAAg3IALAAIAAAmIAWgmIANAAIAAA3gAFigKIAAguIgWAAIAAAuIgLAAIAAg3IAsAAIAAA3gADwgKIgSgZIgFAGIAAATIgMAAIAAg3IAMAAIAAAWIAWgWIAOAAIgWAWIAYAhgAG/hSIAFAAQACAGAFAAQAHAAABgGIAFAAQAAAMgNgBQgMABAAgMg");
	this.shape.setTransform(0,0,4.173,4.173);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-203.6,-34.6,407.3,69.3);


(lib.t2 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACLBYIAAgMIghAAIAAAMIgLAAIAAgWIAFAAQAGgJAAgUIAAgQIAmAAIAAAtIAFAAIAAAWgAB1AmQAAATgFAJIAUAAIAAgkIgPAAgAGNBJQgKgIAAgRQAAgRAKgHQAHgFAJAAQAKAAAGAFQALAHAAARQAAARgLAIQgGAEgKAAQgJAAgHgEgAGOAwQAAAUAPAAQAPAAAAgUQAAgTgPAAQgPAAAAATgAEYBNIAAgKIAFABQADAAADgFIgXgqIANAAIAPAfIAMgfIANAAIgVAuQgEAKgJAAgAAsBJQgKgIAAgRQAAgRAKgHQAHgFAJAAQAJAAAHAFQALAHAAARQAAARgLAIQgHAEgJAAQgJAAgHgEgAAtAwQAAAUAPAAQAPAAAAgUQAAgTgPAAQgPAAAAATgAhfBNIAAgKIAEABQAEAAACgFIgWgqIANAAIAPAfIALgfIANAAIgUAuQgEAKgJAAgAixBNIAAgKIAEABQAEAAACgFIgWgqIANAAIAPAfIALgfIANAAIgUAuQgEAKgJAAgAHmBMIgRgYIgGAFIAAATIgLAAIAAg3IALAAIAAAWIAVgWIAPAAIgWAWIAYAhgAFrBMIAAgZIgVAAIAAAZIgMAAIAAg3IAMAAIAAAVIAVAAIAAgVIAMAAIAAA3gADbBMIAAg3IAZAAQARAAAAARQAAAGgDAFQgFAHgKAAIgNAAIAAAUgADmAuIALAAQAIAAAAgIQAAgIgKAAIgJAAgADEBMIgEgLIgUAAIgEALIgMAAIAUg3IANAAIATA3gAC+A3IgIgWIgHAWIAPAAgAAKBMIAAguIgTAAIAAAuIgMAAIAAg3IArAAIAAA3gAjfBMIAAguIgRAAIAAgJIAtAAIAAAJIgRAAIAAAugAj/BMIgDgLIgVAAIgDALIgNAAIAUg3IANAAIAUA3gAkFA3IgHgWIgHAWIAOAAgAk8BMIAAgZIgWAAIAAAZIgLAAIAAg3IALAAIAAAVIAWAAIAAgVIALAAIAAA3gAl2BMIAAguIgKAuIgMAAIgKguIAAAuIgLAAIAAg3IARAAIAKArIAKgrIARAAIAAA3gAm6BMIAAg3IAMAAIAAA3gAnSBMIgRgYIgFAFIAAATIgMAAIAAg3IAMAAIAAAWIAVgWIAPAAIgXAWIAYAhgAHMgPIAAgJIAEABQAEAAACgFIgWgrIANAAIAPAfIALgfIANAAIgUAvQgEAKgJAAgABUgPIAAgJIAEABQAEAAACgFIgWgrIANAAIAPAfIALgfIANAAIgUAvQgEAKgJAAgAjQgTQgLgHAAgRQAAgRALgHQAHgFAJAAQAJAAAHAFQAKAHAAARQAAARgKAHQgHAFgJAAQgJAAgHgFgAjPgrQAAATAPAAQAPAAAAgTQAAgTgPAAQgPAAAAATgAGrgPIAAgZIgWAAIAAAZIgLAAIAAg4IALAAIAAAVIAWAAIAAgVIALAAIAAA4gAFwgPIAAgZIgVAAIAAAZIgMAAIAAg4IAMAAIAAAVIAVAAIAAgVIAMAAIAAA4gAE5gPIgEgMIgUAAIgEAMIgMAAIATg4IAOAAIATA4gAEzgkIgIgWIAAAAIgHAWIAPAAgADbgPIAAg4IAbAAQARAAAAAOQAAAJgHADQAJADAAAKQAAARgXAAgADmgZIAOAAQAJAAAAgIQAAgHgIAAIgPAAgADmgxIAOAAQAIAAAAgGQAAgGgJAAIgNAAgACpgPIAAgoIgBAAIgWAoIgMAAIAAg4IALAAIAAAnIAWgnIANAAIAAA4gAA0gPIAAgvIgLAvIgLAAIgKgvIAAAvIgLAAIAAg4IARAAIAKAsIAAAAIAKgsIARAAIAAA4gAgOgPIAAgoIgXAoIgMAAIAAg4IALAAIAAAnIAWgnIANAAIAAA4gAhogPIAAg4IAaAAQARAAAAASQAAAGgEAFQgEAHgKAAIgNAAIAAAUgAhcgtIALAAQAIAAAAgIQAAgIgKAAIgJAAgAiOgPIAAguIgQAAIAAgKIAtAAIAAAKIgRAAIAAAugACThQQgDgDAAgEIAFAAQACAGAGAAQAGAAABgGIAFAAQAAALgMAAQgHAAgDgEg");
	this.shape.setTransform(0,0,4.173,4.173);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-209.1,-36.8,418.3,73.7);


(lib.t1 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AG9BSIAAgKIAFABQADAAADgEIgWgrIAMAAIAQAfIALgfIANAAIgVAuQgDAKgJAAgAgcBSIAAgKIAFABQADAAACgEIgWgrIANAAIAPAfIALgfIAMAAIgTAuQgFAKgIAAgAF/BRIAAg3IAaAAQARAAAAARQAAAHgDAEQgEAIgLgBIgNAAIAAAUgAGLAzIALAAQAJAAAAgIQgBgIgJAAIgKAAgAFmBRIAAgnIAAAAIgWAnIgMAAIAAg3IALAAIAAAmIAWgmIANAAIAAA3gAEdBRIAAguIgQAAIAAgJIAsAAIAAAJIgQAAIAAAugADbBRIAAg3IAZAAQARAAAAARQAAAHgDAEQgFAIgJgBIgOAAIAAAUgADmAzIALAAQAJAAgBgIQAAgIgKAAIgJAAgADEBRIgEgLIgUAAIgEALIgMAAIAUg3IANAAIAUA3gAC+A8IgHgVIgIAVIAPAAgABmBRIAAg3IAbAAQARAAAAAOQAAAJgHACQAJAEAAAJQAAARgWAAgABxBHIAPAAQAIABABgJQAAgGgJAAIgPAAgABxAwIAOAAQAIgBAAgFQAAgHgIAAIgOAAgABOBRIgRgYIgFAFIAAATIgMAAIAAg3IAMAAIAAAXIAVgXIAPAAIgXAXIAYAggAg9BRIAAgYIgWAAIAAAYIgLAAIAAg3IALAAIAAAVIAWAAIAAgVIAMAAIAAA3gAiEBRIAAguIgQAAIAAgJIAtAAIAAAJIgRAAIAAAugAijBRIgDgLIgVAAIgEALIgMAAIAUg3IANAAIAUA3gAipA8IgHgVIgBAAIgHAVIAPAAgAjhBRIAAgYIgVAAIAAAYIgLAAIAAg3IALAAIAAAVIAVAAIAAgVIAMAAIAAA3gAkaBRIAAguIgBAAIgJAuIgMAAIgKguIAAAuIgLAAIAAg3IARAAIAKAsIAKgsIAQAAIAAA3gAlfBRIAAg3IAMAAIAAA3gAl2BRIgRgYIgGAFIAAATIgLAAIAAg3IALAAIAAAXIAWgXIAOAAIgWAXIAXAggAnYBRIAAgmIgNAAIAAgHIACAAQAMAAABgKIAJAAIAAA3gAm5BCIAAgIIAWAAIAAAIgAGBgKIAAgJIAFABQADAAADgEIgXgrIANAAIAPAeIALgeIAOAAIgVAuQgEALgJgBgAEOgKIAAgJIAEABQAEAAACgEIgXgrIAOAAIAOAeIAMgeIANAAIgUAuQgFALgJgBgAHWgKIAAgnIAAAAIgXAnIgMAAIAAg3IALAAIAAAmIAXgmIAMAAIAAA3gAFggKIAAguIgWAAIAAAuIgLAAIAAg3IAsAAIAAA3gADugKIgRgZIgFAGIAAATIgMAAIAAg3IAMAAIAAAWIAVgWIAPAAIgXAWIAYAhgAHAhLQgCgDgBgEIAGAAQABAGAGAAQAGAAABgGIAGAAQAAAMgNgBQgHABgDgFg");
	this.shape.setTransform(0,0,4.173,4.172);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-203,-34.6,406,69.3);


(lib.logo = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgCAXQAAAAAAAAQAAAAAAAAQAAgBAAAAQgBAAAAAAIAAgrIABgBIAEAAQAAAAABAAQAAAAAAAAQAAAAAAABQAAAAAAAAIAAArQAAAAAAAAQAAAAAAABQAAAAAAAAQgBAAAAAAg");
	this.shape.setTransform(21.6,24.9,0.613,0.613);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgBAXQgBAAAAAAQAAAAAAAAQAAgBAAAAQAAAAAAAAIAAglIgRAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAgBAAAAIAAgFIAAgBIAmAAQAAAAABAAQAAAAAAAAQAAAAAAABQABAAAAAAIAAAFQAAAAgBABQAAAAAAAAQAAAAAAAAQgBAAAAAAIgPAAIAAAlQAAAAgBAAQAAAAAAABQAAAAAAAAQgBAAAAAAg");
	this.shape_1.setTransform(18.6,24.9,0.613,0.613);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgOARQgHgHAAgKQAAgJAHgHQAHgGAJgBQAMAAAHALQABAAAAAAQAAAAAAAAQAAABAAAAQAAAAgBAAIgEADQAAAAAAAAQgBABAAAAQAAAAAAgBQAAAAAAAAQgGgIgIAAQgGAAgEAGQgFAEAAAGQAAAHAFAEQAEAFAGAAQAIAAAGgHIABgBIAEAEQABAAAAAAQAAABAAAAQAAAAAAAAQAAAAgBABQgHAJgMABQgJgBgHgGg");
	this.shape_2.setTransform(14.6,24.9,0.613,0.613);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgBAXQgBAAAAAAQAAAAAAAAQAAgBAAAAQAAAAAAAAIAAgrIABgBIADAAQAAAAABAAQAAAAAAAAQAAAAAAABQABAAAAAAIAAArQAAAAgBAAQAAAAAAABQAAAAAAAAQgBAAAAAAg");
	this.shape_3.setTransform(11.4,24.9,0.613,0.613);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AATAXQAAAAgBAAQAAAAAAAAQAAgBAAAAQgBAAAAAAIABggIgBAAIgOAgQAAAAAAAAQgBAAAAABQAAAAAAAAQgBAAAAAAIgCAAIgBgBIgPggIgBAAIABAgQAAAAAAAAQAAAAAAABQAAAAgBAAQAAAAAAAAIgFAAQgBAAAAAAQAAAAAAAAQAAgBAAAAQgBAAAAAAIAAgrIACgBIAHAAIACABIAOAhIAAAAIAPghIACgBIAHAAIABABIAAArQAAAAAAAAQAAAAAAABQAAAAAAAAQAAAAgBAAg");
	this.shape_4.setTransform(7.9,24.9,0.613,0.613);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgSAXQAAAAgBAAQAAAAAAAAQAAgBAAAAQAAAAAAAAIAAgrQAAAAAAAAQAAgBAAAAQAAAAAAAAQABAAAAAAIAVAAQAGAAAFAEQADAEAAAFQAAAGgFACIAAABQAIABAAAHQABAGgFAFQgFAEgGAAgAgLAQIAQAAQAHAAAAgIQAAgGgHgBIgQAAgAgLgEIAPAAQAFAAAAgFQABgGgHAAIgOAAg");
	this.shape_5.setTransform(1.1,24.9,0.613,0.613);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgQARQgHgHAAgKQAAgJAHgHQAIgGAIgBQAJABAIAGQAGAHABAJQgBAKgGAHQgIAGgJABQgIgBgIgGgAgKgKQgFAFAAAFQAAAHAFAEQAEAFAGAAQAGAAAFgFQAFgEAAgHQAAgFgFgFQgFgGgGAAQgGAAgEAGg");
	this.shape_6.setTransform(-5.6,24.9,0.613,0.613);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgBAXQAAAAgBAAQAAAAAAAAQAAgBAAAAQgBAAAAAAIAAglIgQAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQgBgBAAAAIAAgFIABgBIAnAAIABABIAAAFQAAAAgBABQAAAAAAAAQAAAAAAAAQAAAAAAAAIgRAAIAAAlQAAAAAAAAQAAAAAAABQAAAAAAAAQgBAAAAAAg");
	this.shape_7.setTransform(-9.5,24.9,0.613,0.613);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgOARQgHgHAAgKQAAgJAHgHQAHgGAJgBQAMAAAHALQAAAAABAAQAAAAAAAAQAAABAAAAQgBAAAAAAIgEADQAAAAAAABQgBAAAAAAQAAAAAAAAQAAgBAAAAQgGgIgIAAQgFAAgFAGQgFAFAAAFQAAAHAFAEQAFAFAFAAQAIAAAGgHIABgBIAEAEQAAAAABAAQAAABAAAAQAAAAAAAAQgBAAAAABQgHAJgMABQgJgBgHgGg");
	this.shape_8.setTransform(-13.5,24.9,0.613,0.613);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgBAXQAAAAgBAAQAAAAAAAAQAAgBAAAAQgBAAAAAAIAAgrQAAAAABAAQAAgBAAAAQAAAAAAAAQABAAAAAAIADAAQAAAAABAAQAAAAAAAAQAAAAAAABQAAAAAAAAIAAArQAAAAAAAAQAAAAAAABQAAAAAAAAQgBAAAAAAg");
	this.shape_9.setTransform(-16.7,24.9,0.613,0.613);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AATAXQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAAAIAAggIgPAgIgCABIgBAAIgCgBIgPggIAAAgQAAAAAAAAQAAAAAAABQAAAAgBAAQAAAAAAAAIgFAAQAAAAgBAAQAAAAAAAAQAAgBAAAAQAAAAAAAAIAAgrQAAAAAAAAQAAgBAAAAQAAAAAAAAQABAAAAAAIAIAAQAAAAAAAAQAAAAABAAQAAAAAAABQAAAAAAAAIAOAhIAAAAIAPghIACgBIAIAAIABABIAAArQAAAAgBAAQAAAAAAABQAAAAAAAAQAAAAAAAAg");
	this.shape_10.setTransform(-20.2,24.9,0.613,0.613);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AvYAGIAAgKIexAAIAAAKg");
	this.shape_11.setTransform(0,19.2,0.613,0.613);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAtBDIAAgqIgvAAIggAqIgtAAIAngvQgHgCgFgFQgHgGgFgHQgEgIAAgKQAAgSAGgLQAGgMALgDQAKgEAQAAIBjAAIAACFgAgdgiQgEAEAAAKQAAALAEAEQAEAEAJAAIA9AAIAAglIg+AAQgJAAgDAEg");
	this.shape_12.setTransform(55.5,11.7,0.613,0.613);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgQBDIAAiFIAhAAIAACFg");
	this.shape_13.setTransform(46.5,11.7,0.613,0.613);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AAsBDIAAhoIhEAAIAAA3QAAAxgnAAIgPAAIAAgeIABAAQAIAAAEgCQADgCABgEQACgFAAgLIAAhPICKAAIAACFg");
	this.shape_14.setTransform(37,11.7,0.613,0.613);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("Ag5BDIAAiFIByAAIAAAdIhPAAIAABog");
	this.shape_15.setTransform(26.4,11.7,0.613,0.613);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAmBDIAAg3IhLAAIAAA3IgjAAIAAiFIAjAAIAAAyIBLAAIAAgyIAjAAIAACFg");
	this.shape_16.setTransform(15,11.7,0.613,0.613);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AA2BDIgQgiIhLAAIgRAiIgoAAIBIiFIAuAAIAAAAIBHCFgAAXAFIgXgrIgWArIAtAAg");
	this.shape_17.setTransform(2.1,11.7,0.613,0.613);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AA2BDIgRgiIhJAAIgRAiIgpAAIBHiFIAvAAIABAAIBGCFgAAXAFIgXgrIgWArIAtAAg");
	this.shape_18.setTransform(-17.7,11.7,0.613,0.613);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AhJBDIAAiFIBfAAQAPAAAKADQAMAEAEAIQAGAHAAAMQAAAPgEAHQgEAFgGACQAIADAFAEQAGAIAAAPQAAAPgFAHQgFAKgLAEQgKAEgPAAgAgmAmIA7AAQAJAAADgBQADAAACgEIABgIIgBgIQgBgDgDgBQgEgBgHAAIg9AAgAgmgNIA9AAQAFAAADgDQADgEAAgGQAAgGgDgDQgDgDgGAAIg8AAg");
	this.shape_19.setTransform(-30.8,11.7,0.613,0.613);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgbBDQgNAAgKgDQgIgCgHgGQgGgGgDgJQgDgIAAgNIAAgmQAAgOADgJQACgJAGgGQAHgGAJgCQAIgCAPAAIA4AAQASAAAKAEQALAEAFALQAFAKAAATIAAAmQAAAMgCAKQgDAJgFAFQgGAGgKADQgKACgNAAgAghgiQgFABgCAEQgBAEgBALIAAAfQAAAHACAGQACAEAEACQAGABAJAAIAnAAQALAAAEgBQAFgCABgEQACgEAAgJIAAggQAAgJgCgFQgCgEgFgCQgEgCgKAAIgnAAQgKABgEACg");
	this.shape_20.setTransform(-43.5,11.7,0.613,0.613);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAmBDIAAg3IhMAAIAAA3IgiAAIAAiFIAiAAIAAAyIBMAAIAAgyIAjAAIAACFg");
	this.shape_21.setTransform(-55.9,11.7,0.613,0.613);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AAHB1IgNAAQgaAAgfACQAwgnAAg3IgBgZQgYAEgmAVQgIAFgBgDQgCgDAEgMQALgcAAgDQAAgIgLgdQgEgMACgDQABgDAIAEQAmAVAWAFQgFgVgTgrQgEgJADgBQADgCAKAEIAZALIAFABIAAAAIAGgBQAGgCATgJQAKgEADACQADABgEAJQgTApgFAXQAWgFAmgVQAPgIgJAWQgKAcAAAJQAAADAKAcQAEAMgBADQgBADgIgFQgqgVgUgEIgBAZQAAA3AwAnQgfgCgaAAg");
	this.shape_22.setTransform(0,-18.7,0.613,0.613);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AAAA5IgTgjQgTgggZgkQgNgTAEgBQAEgBAEgGQAEgEAAgEQACgLAFgMQAGgNABAIIAIAsQAHAdANAOQAIgJAGgSIAGgXQADgHADADQADACABAKQAEAbADAHQAGANATAJQAJAEAAAEQAAADgHAAIgUAAQgQAAgKAEIAKARQAgAvAgARQgeAKgaAPQgJgfgJgZg");
	this.shape_23.setTransform(-17.3,-14.9,0.613,0.613);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AhJBYQAggRAggvIAJgRQgJgEgQAAIgUAAQgHAAAAgDQAAgEAJgEQATgJAGgNQADgHAEgbQABgKADgCQADgDADAHIAFAXQAHASAIAJQAMgOAIgdIAHgsQACgIAGANQAGAMABALQAAAEAEAEQAEAGAEABQAEABgNATQgZAkgTAgQgNAWgGANQgJAYgJAgQgagPgegKg");
	this.shape_24.setTransform(17.3,-14.9,0.613,0.613);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AAAAIQgHgBgFgEQgFgDABgBQAAgEAGgCQAFgBAGABQAHABAFADQAFADgBACQgBAEgFACIgHABIgEgBg");
	this.shape_25.setTransform(9.4,-12.6,0.613,0.613);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgeATQANgIAJgIQAKgIANgbIAFAlQADAPAIANQgggKgdgEg");
	this.shape_26.setTransform(8.9,-12.2,0.613,0.613);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AACAuQgCgHgDAAIgFgBQgDAAgIAEQgIAGgDAAQAIgGAEgJQAFgIAAgEQgBgLgLgKQgEgBgDABQgEACABAFQAAAIADAEQgHgEgDgFQgFgGAAgHQAAgLAEgFQAFgFAIACQAHACAGAKQAGAKACAGIgBgMQgCgIABgKQACgMAHgHQAGgHAEgDIAIAOQAEAIgCAMQgBAKgFAIIgGAKIAEgEIAKgIQAJgJAIABQAHABADAHQADAEgEAJQgDAJgGAFIgIADIgFABQAEgDADgGQACgGgDgDQgCgDgFABQgFACgFAFQgGAFgBAEQgBAFAAALQABAKACADQgCAAgEgHg");
	this.shape_27.setTransform(9.7,-14.4,0.613,0.613);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgKAIQgFgCgBgEQgBgCAFgDQAFgDAHgBQAQgDABAJQABABgFADQgFAEgHABIgEABIgHgBg");
	this.shape_28.setTransform(-9.4,-12.6,0.613,0.613);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgTAFIADgXIABgOIAJAPQAIAQAHAEQAJAIANAIQgfAFgeAJQAIgNADgPg");
	this.shape_29.setTransform(-8.9,-12.2,0.613,0.613);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgEAoQAAgLgBgFQgBgEgGgFQgGgFgFgCQgEgBgDADQgCADACAGQADAGAEADQgIAAgFgEQgGgEgDgKQgEgJADgEQADgHAHgBQAIgBAJAJQAJAFAFAHIgGgKQgFgJgBgJQgDgMAFgIIAIgOIAKAKQAMAMgEAZIgBAMIAIgQQAGgKAIgCQAHgCAFAFQAFAFgBALQAAAHgFAGQgBAEgFACIgEADQADgEAAgIQABgFgEgCQgDgBgEABQgLAJgBAMQAAAEAEAIQAFAJAIAGQgDAAgIgGQgIgEgDAAIgFABQgDAAgCAHQgDAHgDAAQADgDAAgKg");
	this.shape_30.setTransform(-9.8,-14.4,0.613,0.613);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgNAdQhUABg/gOQhGgQgHgXIAHgGIAAABQAAASA9AOQBAAQBcAAIAbAAQBcAABAgQQA8gOAAgSIAAgBIAIAGQgHAXhGAQQg/AOhUgBg");
	this.shape_31.setTransform(0,-1.2,0.613,0.613);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("ACZARQg/gMhMAAIgbAAQhNAAg+AMQhDAMgVAUIgGgYIgGgYQAsgWA/gNQBBgPBKAAIANAAQBJAABCAPQA/ANAsAWIgGAYIgGAYQgVgUhDgMg");
	this.shape_32.setTransform(0,-6.1,0.613,0.613);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("ACUgFQhCgPhLAAIgNAAQhLAAhCAPQhAAMgtAZIgDgKQAsgXBBgPQBEgPBMAAIANAAQBMAABDAPQBBAPAtAXIgDAKQgtgZhAgMg");
	this.shape_33.setTransform(0,-8.6,0.613,0.613);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("Ax6ISQggAAgWgWQgWgXAAgfIAAuLQAAgfAWgXQAWgWAgAAMAj2AAAQAfAAAWAWQAWAXAAAfIAAOLQAAAfgWAXQgWAWgfAAgAynnyQgTATAAAaIAAOLQAAAaATATQATASAaAAMAj2AAAQAaAAATgSQASgTAAgaIAAuLQAAgagSgTQgTgTgaAAMgj2AAAQgaAAgTATg");
	this.shape_34.setTransform(0,0,0.613,0.613);

	this.addChild(this.shape_34,this.shape_33,this.shape_32,this.shape_31,this.shape_30,this.shape_29,this.shape_28,this.shape_27,this.shape_26,this.shape_25,this.shape_24,this.shape_23,this.shape_22,this.shape_21,this.shape_20,this.shape_19,this.shape_18,this.shape_17,this.shape_16,this.shape_15,this.shape_14,this.shape_13,this.shape_12,this.shape_11,this.shape_10,this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-75,-32.5,150,65);


(lib.lines = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Egg3AHHIAAgfMBBwAAAIAAAfgEgg3gGnIAAgeMBBwAAAIAAAeg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-210.5,-45.5,421,91);


(lib.img4_1 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.img4();
	this.instance.setTransform(-150,-300);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-150,-300,300,600);


(lib.img3_1 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.img3();
	this.instance.setTransform(-150,-300);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-150,-300,300,600);


(lib.img2_1 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.img2();
	this.instance.setTransform(-150,-300);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-150,-300,300,600);


(lib.img1_1 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.img1();
	this.instance.setTransform(-150,-300);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-150,-300,300,600);


(lib.gradient = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.502)","rgba(255,255,255,0)"],[0,0.341,1],-24.5,0,24.5,0).s().p("AjzQUMAAAggnIHnAAMAAAAgng");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-24.5,-104.5,49,209);


(lib.gift = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FC0D1B").s().p("ABjBEIgyg3IhhAAQgWASgcAlQg6BLgiBhIh3hSQAMgeAYgjQAwhFA9gUQgSACgYgEQgwgGghggQhEhDAjgkQAgghgCgaQgBgTAGgGQAKgNAngCQAygDAxAcQA7AiA0BKIA1AAQA0hKA7giQAxgcAyADQAnACAKANQAGAHgBASQgCAaAgAhQARARgGAXQgHAbgmAkQghAggwAGIgpACQA9AUAwBFQAYAjAMAeIh4BSQghhhg6hLgAgqg/QgGAQAKASIBNAAQAKgSgGgQIgJgNIhEAAgADJjBQhGAOhIBWIAKAOQAKASgEATIBFghQBSgiA/gEQgIgHgIgNQgQgbgBgeQgMgGgQAAQgMAAgPADgAhKgqQgEgTAKgSQAFgJAFgFQhIhWhGgOQgjgHgUAKQgBAegQAbQgIANgIAHQA/AEBSAiQApARAcAQIAAAAg");
	this.shape.setTransform(0,-10.3,0.5,0.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgNDpIAAnRIAbAAIAAHRg");
	this.shape_1.setTransform(11.2,9.5,0.5,0.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgNDpIAAnRIAbAAIAAHRg");
	this.shape_2.setTransform(6.8,9.5,0.5,0.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgNDpIAAnRIAbAAIAAHRg");
	this.shape_3.setTransform(2.3,9.5,0.5,0.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgNDpIAAnRIAbAAIAAHRg");
	this.shape_4.setTransform(-2.2,9.5,0.5,0.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgNDpIAAnRIAbAAIAAHRg");
	this.shape_5.setTransform(-6.7,9.5,0.5,0.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgNDpIAAnRIAbAAIAAHRg");
	this.shape_6.setTransform(-11.2,9.5,0.5,0.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AkPD+QgUAAgPgPQgOgOAAgUIAAm1QAAgIAGgHQAGgGAJAAQAJAAAGAGQAGAHAAAIIAAG1QAAAHAHAAIIfAAQAHAAAAgHIAAm1QAAgIAGgHQAGgGAJAAQAIAAAHAGQAGAHAAAIIAAG1QAAAUgPAOQgOAPgUAAg");
	this.shape_7.setTransform(0,9.5,0.5,0.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AlLBoQgUAAgPgOQgOgPAAgUIAAhtQAAgVAOgOQAPgOAUAAIKXAAQAUAAAPAOQAOAOAAAVIAABtQAAAUgOAPQgOAOgVAAgAlSg2IAABtQAAAHAHAAIKXAAQAHAAAAgHIAAhtQAAgHgHAAIqXAAQgHAAAAAHg");
	this.shape_8.setTransform(0,-6.6,0.5,0.5);

	this.addChild(this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-19,-22.2,38.2,44.5);


(lib.btnText = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Aq7ADIAAgFIV3AAIAAAFg");
	this.shape.setTransform(0,-13.5,1.478,1.478);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Aq7ACIAAgDIV3AAIAAADg");
	this.shape_1.setTransform(0,13.6,1.478,1.478);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgpAyIAAgDIADAAQAEAAADgCQAAAAABAAQAAAAABgBQAAAAAAgBQABgBAAAAIAAhJQABgKgCgCQgDgDgGAAIgDAAIAAgDIBLAAIABAWIgDAAQgCgIgBgDQgCgDgEgBIgKgBIgaAAIAAAoIAUAAQAIAAAEgDQAEgDAAgJIACAAIAAAhIgCAAIgCgJQgBgDgEgCQgDgBgGAAIgUAAIABApIABADIAHAAIAbgBQAEgBADgDQAGgHAEgHIACAAIgIAZg");
	this.shape_2.setTransform(92.9,0.5,1.478,1.478);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhHAyIAAgDIADAAQAFAAADgDQACgCAAgLIAAg9QAAgLgCgCQgDgDgIAAIAAgDIAnAAIAAADQgIABgCADQgCACAAAKIABBHQAAABAAAAQAAABAAAAQABAAAAAAQAAABABAAIAGAAIATAAQAIAAABgBQABgBAAgLIAAg9QAAgKgCgCQgCgDgHgBIAAgDIAjAAIAAADQgIABgBADQgCACAAAKIAAA9QAAALABABQABABAIAAIAUAAIAGAAIABgCIABhIQAAgJgCgDQgCgDgIgBIAAgDIAnAAIAAADQgGAAgDACQgCABgBADIgBAKIAABHIADAEQADACAHAAIAAADg");
	this.shape_3.setTransform(74.8,0.5,1.478,1.478);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgmAyIAAgDQAJAAADgDQACgDAAgJIAAg+QAAgKgCgDQgDgDgJAAIAAgDIApAAIAAADQgHAAgDADQgCACAAALIAAAbIAEAAQARAAAIACQAKABAEAGQAFAHAAAJQAAALgIAIQgIAJgVAAgAgJABIAAArIAJABQAIAAAHgGQAIgGAAgLQAAgKgIgHQgHgFgLAAg");
	this.shape_4.setTransform(56.8,0.5,1.478,1.478);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgtAwQgDgCAAgEIACgGQAAAAABAAQABgBAAAAQABAAAAAAQABgBAAAAQADABADACQADACADAAQAHAAADgKQAFgKAAgdIAAgVQgBgKgCgDQgCgCgKAAIAAgDIBPAAIAAADQgJAAgDACQgCADAAAKIAAA+QAAAJACADQADADAJABIAAACIgrAAIAAgCQAKgCACgCQACgCAAgKIAAhLIgdAAIAAAcQAAApgHANQgHANgNgBQgGABgDgDg");
	this.shape_5.setTransform(42.8,0.6,1.478,1.478);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgUAyIAAgDIADAAQAHAAACgEQACgCABgJIAAg/IgCgKQAAAAAAgBQAAAAgBgBQAAAAAAAAQgBgBgBAAIgHgCIgDAAIAAgDIApAAIAAADIgEAAQgFAAgEAEQgCACAAAJIAAA/IABAKIAEADQADACADAAIAEAAIAAADg");
	this.shape_6.setTransform(31.6,0.5,1.478,1.478);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgmAyIAAgDQAKAAACgDQACgCAAgKIAAg+QAAgJgBgCQAAAAAAgBQgBAAAAgBQgBAAAAgBQgBAAAAAAQgCgCgHAAIAAgDIBFAAIABAWIgDAAQgCgKgFgDQgFgDgMAAIgPAAIAAAoIAEAAQARAAAIACQAJABAFAGQAFAGAAAKQAAALgIAIQgIAJgVAAgAgJABIAAArIAJABQAIAAAHgGQAIgGAAgLQAAgLgIgGQgIgFgKAAg");
	this.shape_7.setTransform(21.2,0.5,1.478,1.478);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAHAyIAAgDIADAAQAGAAADgDQACgDAAgJIAAgdIgLAAIggAvIgbAAIAAgDQAJgBAFgDQAEgDAIgKIAUgdQgMgBgGgHQgGgGAAgKQAAgJAFgGQAGgGAHgCQAJgDANAAIAkAAIAAADIgDAAQgGAAgDADQgCACAAAKIAAA/QAAAJACACQACAEAHAAIADAAIAAADgAgFglQgFAGgBAJQAAAKAIAGQAFAGAPAAIAEAAIAAgqIgMgBQgJAAgFAGg");
	this.shape_8.setTransform(1.6,0.5,1.478,1.478);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgiAiQgKgPAAgSQAAgNAHgNQAGgLAMgIQANgHALAAQALAAALAFIAEACIAEgBIADgGIACAAIACAiIgCAAQgEgPgJgHQgJgHgLAAQgIAAgJAFQgIAGgEALQgFALAAAOQAAANAEALQAFAKAJAFQAIAGAKAAQAJAAAIgFQAHgDAJgNIADABQgIAOgKAGQgKAGgOAAQgWAAgPgSg");
	this.shape_9.setTransform(-13.1,0.5,1.478,1.478);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAIBCIAAgCQAKgBACgCQADgDAAgKIAAg3IgtA6IABAIIAEAEQACABAIAAIAAACIgsAAIAAgCQAJgBAEgCQACgDAAgKIAAg+QAAgJgCgDQgEgDgJAAIAAgDIAsAAIAAADQgKAAgCADQgDADAAAJIAAA5IAtg7QAAgIgDgDQgCgCgKAAIAAgDIAsAAIAAADQgJAAgEADQgCADAAAJIAAA+QAAAKACADQAEACAJABIAAACgAgUgwQgHgEAAgHQAAgCACgCQABgBAAAAQABgBAAAAQABAAAAAAQABgBAAAAQAAAAABABQAAAAABAAQAAAAABABQAAAAABABIAFAIQAEAJAIAAQAIAAAGgJIAEgIQABgBAAAAQABgBAAAAQABAAAAAAQABgBABAAQAAAAABABQAAAAABAAQAAAAABABQAAAAAAABIACAEQAAAHgHAEQgGAGgPgBQgNABgHgGg");
	this.shape_10.setTransform(-28.7,-2,1.478,1.478);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AANAzIAAgCIAIgDQABAAAAgBQABAAAAgBQAAAAAAgBQAAAAAAgBQAAgDgDgHIgGgPIglAAIgGARQgCAEgBAEQAAABABAAQAAABAAAAQAAABABAAQAAABAAAAQACABAIACIAAACIggAAIAAgCIAJgEQADgCAFgMIAjhRIABAAIAjBSQAEAKAEADQACACAHACIAAACgAgUAMIAgAAIgPgmg");
	this.shape_11.setTransform(-45,0.3,1.478,1.478);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAIAyIAAgDIAEAAQAGAAADgEQACgDAAgIIAAgfIgtAAIAAAfIABAKIADADQAEACADAAIADAAIAAADIgrAAIAAgDIAEAAQAGAAADgEQACgDAAgIIAAg/IgBgKQAAAAAAgBQgBAAAAgBQAAAAgBAAQAAgBgBAAIgHgCIgEAAIAAgDIArAAIAAADIgDAAIgHACQgBAAAAABQgBAAAAAAQAAABgBAAQAAABAAAAIgBAKIAAAdIAtAAIAAgdIgBgKQAAAAAAgBQgBAAAAgBQgBAAAAAAQgBgBgBAAQgDgCgDAAIgEAAIAAgDIAsAAIAAADIgEAAQgEAAgDACQgBAAAAABQgBAAAAAAQAAABgBAAQAAABAAAAIgBAKIAAA/IABAKIADADQADACAEAAIAEAAIAAADg");
	this.shape_12.setTransform(-61.1,0.5,1.478,1.478);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AggAgIADgCQAEAHAHAEQAHAEAIAAQAIAAAGgGQAFgHAAgJQAAgKgHgHQgIgGgNAAIAAgDQALAAAEgDQAGgCADgFQAEgHAAgGQAAgHgFgGQgFgFgGAAQgLAAgGAGQgGAIgCAIIgCAAIAAgdIACAAQABAFAFAAIAHgCQAJgDAGAAQANAAAHAHQAIAIAAAKQAAAJgGAHQgHAHgIACQAKABAGAGQAHAHAAALQAAANgKAHQgJAIgOAAQgUAAgMgUg");
	this.shape_13.setTransform(-75.1,0.5,1.478,1.478);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgUAyIAAgDIAEAAQAGAAADgEQABgCAAgJIAAg/IAAgKQgBAAAAgBQAAAAAAgBQgBAAAAAAQgBgBAAAAIgHgCIgEAAIAAgDIApAAIAAADIgDAAQgHAAgCAEQgCACAAAJIAAA/IABAKIADADQADACAEAAIADAAIAAADg");
	this.shape_14.setTransform(-84.2,0.5,1.478,1.478);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAuBAQgCgKgFgHQgFgHgGgCQgIgDgIAAIgYAAQgQAAgIAJQgIAKgCAKIgCAAIAAgfQANgCAGgNQAIgNADgRQACgWABgKQgBgIgBgDQgCgDgDgBIgKgBIAAgDIBRAAIAAADQgJAAgDADQgCACAAAKIAAA2QAAAQACAEQABAEAKAAIAAAfgAgPACQgGATgIAJIAjAAQALAAACgCQABgCAAgJIAAhLIgcAAQgBAsgGAQg");
	this.shape_15.setTransform(-95.7,2.6,1.478,1.478);

	this.addChild(this.shape_15,this.shape_14,this.shape_13,this.shape_12,this.shape_11,this.shape_10,this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-103.5,-14,207,28.1);


(lib.btnBg = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ArUC1QgPAAgKgKQgLgKAAgPIAAkjQAAgOALgKQAKgLAPAAIWqAAQAOAAALALQAKAKAAAOIAAEjQAAAPgKAKQgLAKgOAAgArpimQgJAJAAAMIAAEjQAAAMAJAJQAIAIANAAIWqAAQAMAAAJgIQAIgJAAgMIAAkjQAAgMgIgJQgJgIgMAAI2qAAQgNAAgIAIg");
	this.shape.setTransform(0,0,1.478,1.478);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["rgba(0,0,0,0)","rgba(0,0,0,0.651)","rgba(0,0,0,0.949)"],[0.008,0.275,1],0,17.6,0,-17.5).s().p("ArVCvQgMAAgJgIQgIgJAAgMIAAkjQAAgMAIgJQAJgIAMAAIWrAAQALAAAJAIQAJAJAAAMIAAEjQAAAMgJAJQgJAIgLAAg");
	this.shape_1.setTransform(0,0.1,1.478,1.478);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-112.5,-26.8,225,53.7);


(lib.img7_1 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("AAzHUQABgQAEgJQAHgPAUgOQAVgPAFgGQAIgJAAgKQAAgIgEgGQgFgGgKAAQgMAAgFAJQgCAGAAALIgbAAQAAgdASgMQAMgIAPAAQAVAAANAMQANALAAAVQAAAagcASQgbARgEAIIA7AAIAAAYgALcg8IBNiMIAPAAIhNCMgAJHiCQAAhGAwAAQAZAAALARQALARAAAkQAABGgvAAQgwAAAAhGgAJnioQgEALAAAbQAAAbAEALQAEALAMAAQALAAAFgLQAEgLAAgbQAAgbgEgLQgFgLgLAAQgMAAgEALgAMfhHQgKgLAAgOQAAgPAKgKQAKgKAPAAQAOAAALAKQAKAKAAAPQAAAOgKALQgLAKgOAAQgPAAgKgKgAMthrQgEAEAAAHQAAAGAEAFQAFAEAGAAQAGAAAFgEQAEgFAAgGQAAgHgEgEQgFgFgGAAQgGAAgFAFgALEiMQgKgLAAgOQAAgPAKgKQALgKAOAAQAPAAAKAKQAKAKAAAPQAAAOgKALQgKAKgPAAQgOAAgLgKgALSiwQgEAEAAAHQAAAGAEAEQAFAFAGAAQAGAAAFgFQAEgEAAgGQAAgHgEgEQgFgFgGAAQgGAAgFAFgAlJlYQgLgRAAgkQAAhGAvAAQAZAAALARQALARAAAkQAABGgvAAQgYAAgMgRgAk1mzQgEALAAAbQAAAbAEALQAFALALAAQAMAAAEgLQAEgLAAgbQAAgbgEgLQgEgLgMAAQgLAAgFALgAnImNQAAhGAwAAQAYAAALARQAMARAAAkQAABGgwAAQgvAAAAhGgAmomzQgEALAAAbQAAAbAEALQAEALALAAQAMAAAEgLQAEgLAAgbQAAgbgEgLQgEgLgMAAQgLAAgEALgAo8mNQAAhGAwAAQAZAAALARQALARAAAkQAABGgvAAQgwAAAAhGgAocmzQgEALAAAbQAAAbAEALQAEALAMAAQALAAAFgLQAEgLAAgbQAAgbgEgLQgFgLgLAAQgMAAgEALgArtmMQAAhHAzAAQARAAAMAKQALAKAAAOIgaAAQgCgNgOAAQgVAAgCAmIABAAQAHgLASAAQAUAAAMAOQAKALAAARQAAAXgMAOQgNANgUAAQgxAAAAhFgArMmIQgGAGAAAMQAAALAGAHQAGAHAJAAQATAAAAgZQAAgMgHgGQgFgFgIAAQgIAAgGAFgAs5lLIAAheIghAAIAAgTIAEAAQAhAAABgXIAWAAIAACIg");
	this.shape.setTransform(58.3,-234.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("A2iIwIAAgPMAs+AAAIAAAPgAFwHuIAAgdIhRAAIAAAdIgbAAIAAg0IAMAAQAKgOADgRQADgPAAgcIAAgpIBeAAIAABzIANAAIAAA0gAE7FyQABAcgDAOQgDAQgJAOIA0AAIAAhbIgmAAgAPSHJQgbgTABgqQgBgqAbgSQARgNAXAAQAXAAARANQAbASAAAqQAAAqgbATQgRAMgXAAQgXAAgRgMgAPhFlQgNANAAAaQAAAaANANQALAKAOAAQAPAAAKgKQANgNAAgaQAAgagNgNQgKgJgPAAQgOAAgLAJgAG8HJQgbgTAAgqQAAgqAbgSQARgNAXAAQAXAAARANQAbASgBAqQABAqgbATQgRAMgXAAQgXAAgRgMgAHLFlQgMANAAAaQAAAaAMANQALAKAOAAQAOAAALgKQANgNAAgaQAAgagNgNQgLgJgOAAQgOAAgLAJgAn3HJQgbgTAAgqQAAgqAbgSQARgNAXAAQAXAAARANQAaASABAqQgBAqgaATQgRAMgXAAQgXAAgRgMgAnnFlQgNANgBAaQABAaANANQAJAKAPAAQAPAAAKgKQANgNAAgaQAAgagNgNQgKgJgPAAQgPAAgJAJgAuaHDQgSgUAAgiQAAgkASgTQASgSAcgBQAcAAARARQANAOACATIgdAAQgDgLgFgFQgHgJgQAAQgNAAgKAJQgMANAAAbQAAAUAJANQAIAPASAAQAagBAFgaIAdAAQgFAYgPANQgPAOgaAAQgcAAgRgSgAw3GnIAbAAQAAAXAegBQANAAAJgFQAHgGAAgIQAAgLgHgFQgIgGgKAAIgOAAIAAgXIANAAQAWAAAAgSQAAgQgZAAQgZAAgDAVIgbAAQABgSAOgNQAOgOAZAAQAbAAAPANQAMAKgBAOQAAAZgYAHQANACAIAJQAJAKAAAPQAAASgOALQgPAMgcAAQg6AAAAgugAy4HJQgbgTAAgqQAAgqAbgSQAQgNAXAAQAYAAAQANQAbASAAAqQAAAqgbATQgQAMgYAAQgXAAgQgMgAyqFlQgNANABAaQgBAaANANQALAKAOAAQAPAAAKgKQANgNAAgaQAAgagNgNQgKgJgPAAQgOAAgLAJgAUrHRIAAiKIBFAAQAXAAALAMQAJAKgBAOQAAATgQAJQAVAHAAAaQAAAPgJAKQgOARgggBgAVIG6IAjAAQAXgBAAgUQAAgQgVgBIglAAgAVIF9IAiAAQAVAAAAgQQAAgOgWAAIghAAgATsHRIAAiKIAcAAIAACKgASwHRIgqg9IgPAOIAAAvIgcAAIAAiKIAcAAIAAA4IA1g4IAmAAIg4A4IA8BSgAM0HRIAAiKIA/AAQAVAAALAMQALAMAAAVQAAAOgIAMQgMASgYAAIgiAAIAAAxgANQGHIAbAAQAXABAAgWQAAgKgHgFQgFgEgOAAIgYAAgAAKHRIgJgcIgwAAIgKAcIgfAAIAyiKIAhAAIAvCKgAgoGdIAmAAIgUg3IAAAAgAiKHRIgrg9IgOAOIAAAvIgdAAIAAiKIAdAAIAAA4IA1g4IAmAAIg5A4IA9BSgAkfHRIAAg5QgMACgYAAQgTAAgLgKQgNgLAAgWIAAgoIAdAAIAAAoQAAATAVAAQARAAAMgCIAAg5IAdAAIAACKgAqVHRIAAiKIA/AAQAVAAALAMQALAMAAAVQAAAOgIAMQgLASgZAAIghAAIAAAxgAp4GHIAbAAQAVABAAgWQABgKgHgFQgFgEgOAAIgXAAgAr0HRIAAhyIgqAAIAAgYIBxAAIAAAYIgqAAIAABygA1XHRIAAiKIA/AAQAUAAAMAMQAMAMAAAVQgBAOgHAMQgMASgYAAIgiAAIAAAxgA06GHIAbAAQAVABABgWQgBgKgFgFQgHgEgNAAIgXAAgAB8GrIAAgVIA2AAIAAAVgAGGDkIAAgdIhRAAIAAAdIgbAAIAAg1IANAAQAJgPADgQQADgPAAgbIAAgqIBeAAIAABzIANAAIAAA1gAFSBnQAAAcgDAOQgDAPgJAPIA0AAIAAhbIglAAgAQPC+QgagSAAgqQAAgqAagUQARgMAXABQAXgBARAMQAaAUAAAqQAAAqgaASQgRAMgXAAQgXAAgRgMgAQeBbQgNANABAaQgBAaANAMQAKAKAPAAQAPAAAKgKQANgMAAgaQAAgbgNgMQgKgKgPAAQgPAAgKAKgAJlC+QgagSAAgqQAAgqAagUQARgMAYABQAWgBASAMQAbAUgBAqQABAqgbASQgSAMgWAAQgYAAgRgMgAJ1BbQgNANAAAaQAAAaANAMQAKAKAPAAQAPAAAJgKQANgMABgaQgBgbgNgMQgJgKgPAAQgPAAgKAKgAHKC4QgSgUAAgiQAAgkASgTQARgSAcAAQAdgBAQASQANANACASIgdAAQgGgYgZAAQgNAAgJAKQgNANAAAaQAAAUAJANQAJAPARAAQAZAAAGgbIAdAAQgEAYgQANQgPAOgZAAQgdAAgQgSgAg8CcIAbAAQAAAWAeAAQALABAIgGQAIgFAAgKQAAgKgIgFQgHgGgJABIgOAAIAAgYIANAAQAVAAgBgSQAAgQgXAAQgZAAgCAWIgbAAQABgUANgMQAPgOAZABQAYAAAPAMQAMAKAAAOQAAAZgYAHQANACAHAKQAJAJAAAPQAAASgOALQgPAMgZAAQg6AAAAgugAWEDHIgJgdIgzAAIgKAdIgeAAIAxiLIAiAAIAwCLgAVPCSIAmAAIgTg2IgBAAgASYDHIAAiLIBEAAQAXAAALANQAJAJAAANQAAAUgRAJQAVAIAAAZQAAAPgIALQgOAQgiAAgAS1CvIAjAAQAWgBAAgTQABgJgHgFQgGgDgJAAIgkAAgAS1ByIAiAAQAUAAAAgPQAAgPgVAAIghAAgAPCDHIgrg9IgNANIAAAwIgeAAIAAiLIAeAAIAAA4IA1g4IAlAAIg5A4IA8BTgAMODHIAAhzIgrAAIAAgYIByAAIAAAYIgrAAIAABzgADiDHIAAiLIAdAAIAACLgABRDHIAAiLIBFAAQAXAAALANQAJAJgBANQAAAUgQAJQAUAIABAZQAAAPgJALQgNAQgiAAgABuCvIAjAAQAXgBAAgTQAAgJgHgFQgFgDgJAAIglAAgABuByIAiAAQAUAAAAgPQABgPgWAAIghAAgAi9DHIAAiLIBmAAIAAAYIhKAAIAAAcIBEAAIAAAZIhEAAIAAAmIBOAAIAAAYgAlMDHIAAiLIBmAAIAAAYIhJAAIAAAcIAkAAQAVAAANAMQANAMAAAUQAAAUgNALQgNAMgVAAgAkvCvIAhAAQAKgBAHgFQAFgGAAgIQAAgTgWABIghAAgAQjglIAAgdIhSAAIAAAdIgbAAIAAg1IAMAAQAKgOADgRQADgPAAgcIAAgpIBeAAIAABzIAOAAIAAA1gAPtiiQAAAcgDAOQgDAQgIAOIA0AAIAAhbIgmAAgAGVhLQgagTAAgqQAAgpAagUQARgLAYgBQAWABARALQAbAUAAApQAAAqgbATQgRAMgWAAQgYAAgRgMgAGliuQgNAMAAAaQAAAaANANQAKAKAPAAQAOAAAKgKQANgNAAgaQAAgagNgMQgKgKgOAAQgPAAgKAKgAD5hSQgSgTAAgjQAAgiATgUQARgTAcAAQAcABARAQQANAOACATIgdAAQgDgLgFgFQgIgJgPAAQgOAAgJAKQgMANAAAaQAAAUAJANQAJAPARAAQAZAAAGgbIAdAAQgKAzgyAAQgdAAgRgTgAN+hCIAAiLIAeAAIAACLgALthCIAAiLIBFAAQAXAAALANQAIAJAAANQAAAUgRAJQAWAIgBAZQAAAPgIAKQgOAQghABgAMKhaIAjAAQAXAAAAgVQgBgIgGgEQgGgFgIAAIglAAgAMKiWIAiAAQAUgBABgPQgBgPgVAAIghAAgAJ0hCIgrg9IgOAOIAAAvIgdAAIAAiLIAdAAIAAA5IA1g5IAmAAIg5A5IA8BSgABkhCIAAiLIBnAAIAAAYIhKAAIAAAcIBEAAIAAAYIhEAAIAAAnIBNAAIAAAYgAAkhCIAAg/Ig0AAIAAA/IgcAAIAAiLIAcAAIAAA0IA0AAIAAg0IAdAAIAACLgAi+hCIAAiLIBEAAQAXAAALANQAJAJAAANQAAAUgRAJQAVAIABAZQAAAPgJAKQgOAQgiABgAihhaIAjAAQAWAAAAgVQABgIgHgEQgGgFgJAAIgkAAgAihiWIAiAAQAUgBAAgPQAAgPgVAAIghAAgAk7hCIAAhjIgBAAIg5BjIgfAAIAAiLIAdAAIAABgIA4hgIAgAAIAACLgAnThCIAAhjIg5BjIggAAIAAiLIAdAAIAABgIA4hgIAgAAIAACLgArthCIAAiLIAdAAIAABzIAkAAIAAhzIAcAAIAABzIAlAAIAAhzIAdAAIAACLgAt2hCIAAiLIA/AAQAVAAALAMQALAMAAAUQABAPgJAMQgMARgYAAIghAAIAAAzgAtZiMIAbAAQAWAAgBgWQABgKgHgEQgFgFgOAAIgXAAgAv+hCIAAiLIBnAAIAAAYIhKAAIAAAcIBDAAIAAAYIhDAAIAAAnIBNAAIAAAYgAw+hCIAAhzIg2AAIAABzIgdAAIAAiLIBwAAIAACLgAl5j1IANAAQADANAQAAQAKAAAFgFQACgCACgGIAMAAQAAAJgGAIQgJALgQAAQgcAAgEgcgAmFkwIAAgeIhSAAIAAAeIgbAAIAAg1IANAAQAJgPADgQQADgPAAgcIAAgpIBeAAIAABzIAOAAIAAA1gAm6msQAAAbgDAOQgDAPgJAPIA0AAIAAhbIglAAgAyTkwIAAgeIhjAAIAAiKIAdAAIAABzIA2AAIAAhzIAdAAIAABzIAOAAIAAA1gAN5l4IAbAAQAAAXAegBQANAAAIgFQAIgFgBgJQABgLgIgFQgHgGgLAAIgOAAIAAgWIANAAQALAAAFgGQAHgEAAgIQgBgQgYgBQgaABgCAUIgbAAQABgSAOgNQAOgOAZAAQAbAAAPANQAMAKAAAOQAAAZgZAHQANADAIAIQAIALABAOQAAASgOALQgPANgcAAQg6gBAAgugAU2lOIAAg/IABgLIgBAAIgXBKIgVAAIgYhKIAAAAIAABKIgZAAIAAhmIAlAAIAWBGIABAAIAWhGIAlAAIAABmgARklOIgJgcIg0AAIgKAcIgeAAIAxiKIAiAAIAxCKgAQvmCIAlAAIgTg3gAMClOIAAg+Ig2AAIAAA+IgdAAIAAiKIAdAAIAAA1IA2AAIAAg1IAdAAIAACKgAImlOIAAiKIBAAAQAUAAAMAMQALAMAAAVQAAAOgIAMQgMASgYAAIgiAAIAAAxgAJDmXIAbAAQAWAAAAgVQAAgLgGgFQgGgEgOAAIgXAAgAGplOIAAiKIBjAAIAAAYIhGAAIAABygAoqlOIAAiKIAeAAIAACKgAq7lOIAAiKIBFAAQAWAAAMAMQAIAKAAAOQAAATgQAJQAUAIAAAaQAAAOgIAKQgOARghgBgAqellIAjAAQAXAAAAgVQgBgIgGgEQgFgEgJgBIglAAgAqemhIAiAAQAUAAAAgQQAAgPgVAAIghAAgAsylOIgJgcIgzAAIgKAcIgdAAIAwiKIAiAAIAxCKgAtmmCIAlAAIgTg3IAAAAgAvMlOIAAg+Ig2AAIAAA+IgdAAIAAiKIAdAAIAAA1IA2AAIAAg1IAdAAIAACKgAxflOIAAiKIAdAAIAACKgAVnmyQABgKACgFQAFgKAMgJIARgNQAFgFAAgHQAAgMgMAAQgMAAAAAQIgRAAQAAgeAdAAQANAAAHAGQAJAIAAANQAAAQgSAMQgSAMgCADIAmAAIAAAPgA2iogIAAgPMAs+AAAIAAAPg");
	this.shape_1.setTransform(0,-234);

	// Слой 4
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["#000000","rgba(0,0,0,0)"],[0.247,1],0,-100,0,100).s().p("A3bPoIAA/OMAu3AAAIAAfOg");
	this.shape_2.setTransform(0,-200);

	// Слой 2
	this.instance = new lib.logo();
	this.instance.setTransform(0,-20,1.3,1.3);

	// Слой 1
	this.instance_1 = new lib.img7();
	this.instance_1.setTransform(-150,-300);

	this.instance_2 = new lib.logo();
	this.instance_2.setTransform(0,0,0.696,0.695);

	this.addChild(this.instance_2,this.instance_1,this.instance,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-150,-300,300,600);


(lib.banner = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// img
	this.instance = new lib.img1_1();
	this.instance.setTransform(-300,0);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(317).to({_off:false},0).to({x:0},10,cjs.Ease.get(1)).wait(1));

	// btnText
	this.instance_1 = new lib.btnText();
	this.instance_1.setTransform(0,143.5,0.01,0.01);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(250).to({_off:false},0).to({scaleX:1,scaleY:1,y:143.1},10,cjs.Ease.get(1)).wait(68));

	// btnBg (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_276 = new cjs.Graphics().p("AwvEMQgVAAgQgPIAAAAQgQgQAAgVIAAAAIAAmuQAAgWAQgPIAAAAQAQgQAVAAIAAAAMAhgAAAQAVAAAPAQIAAAAQAPAPABAWIAAAAIAAGuQgBAVgPAQIAAAAQgPAPgVAAIAAAAgAxOj1QgNAMAAATIAAAAIAAGuIAAmuQAAgTANgMIAAAAQANgNASAAIAAAAMAhgAAAQARAAAOANIAAAAQAMAMAAATIAAAAQAAgTgMgMIAAAAQgOgNgRAAIAAAAMghgAAAQgSAAgNANg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(276).to({graphics:mask_graphics_276,x:0,y:143.5}).wait(52));

	// grad
	this.instance_2 = new lib.gradient();
	this.instance_2.setTransform(-180.5,127.8,1.81,1.222,30);
	this.instance_2._off = true;

	this.instance_2.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(276).to({_off:false},0).to({x:173.6,y:159.8},25).wait(27));

	// btnBg
	this.instance_3 = new lib.btnBg();
	this.instance_3.setTransform(0,143.5,0.01,0.01);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(250).to({_off:false},0).to({scaleX:1,scaleY:1},10,cjs.Ease.get(1)).wait(68));

	// img
	this.instance_4 = new lib.img7_1();
	this.instance_4.setTransform(-300,0);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(240).to({_off:false},0).to({x:0},10,cjs.Ease.get(1)).to({_off:true},77).wait(1));

	// gift
	this.instance_5 = new lib.gift();
	this.instance_5.setTransform(131.5,-236.4,0.009,0.008);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(70).to({_off:false},0).to({scaleX:0.69,scaleY:0.69},10,cjs.Ease.get(1)).wait(40).to({scaleX:0.01,scaleY:0.01},10,cjs.Ease.get(-1)).to({_off:true},1).wait(59).to({_off:false},0).to({scaleX:0.69,scaleY:0.69},10,cjs.Ease.get(1)).wait(40).to({scaleX:0.01,scaleY:0.01},10,cjs.Ease.get(-1)).to({_off:true},1).wait(77));

	// t4
	this.instance_6 = new lib.t4();
	this.instance_6.setTransform(309.6,-183.2,0.693,0.693);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(70).to({_off:false},0).to({x:2.1},10,cjs.Ease.get(1)).wait(40).to({alpha:0},10).to({_off:true},1).wait(197));

	// t3
	this.instance_7 = new lib.t3();
	this.instance_7.setTransform(311.8,-183.2,0.693,0.693);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(130).to({_off:false},0).to({x:4.3},10,cjs.Ease.get(1)).wait(40).to({alpha:0},10).to({_off:true},1).wait(137));

	// t2
	this.instance_8 = new lib.t2();
	this.instance_8.setTransform(307.9,-183.2,0.693,0.693);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(190).to({_off:false},0).to({x:0.4},10,cjs.Ease.get(1)).wait(40).to({alpha:0},10).to({_off:true},1).wait(77));

	// t1
	this.instance_9 = new lib.t1();
	this.instance_9.setTransform(312.2,-183.2,0.693,0.693);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(10).to({_off:false},0).to({x:4.7},10,cjs.Ease.get(1)).wait(40).to({alpha:0},10).to({_off:true},1).wait(257));

	// logo
	this.instance_10 = new lib.logo();
	this.instance_10.setTransform(-63,-255.5,0.008,0.008);

	this.timeline.addTween(cjs.Tween.get(this.instance_10).to({scaleX:0.8,scaleY:0.8,x:-79,y:-262.5},10,cjs.Ease.get(1)).to({_off:true},240).wait(78));

	// lines
	this.instance_11 = new lib.lines();
	this.instance_11.setTransform(0.8,-183,0.002,0.693);

	this.timeline.addTween(cjs.Tween.get(this.instance_11).to({scaleX:0.69},10,cjs.Ease.get(1)).to({_off:true},240).wait(78));

	// img
	this.instance_12 = new lib.img2_1();
	this.instance_12.alpha = 0;
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(180).to({_off:false},0).to({alpha:1},10).to({_off:true},60).wait(78));

	// img
	this.instance_13 = new lib.img3_1();
	this.instance_13.setTransform(-300,0);
	this.instance_13._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(120).to({_off:false},0).to({x:0},10,cjs.Ease.get(1)).to({_off:true},60).wait(138));

	// img
	this.instance_14 = new lib.img4_1();
	this.instance_14.alpha = 0;
	this.instance_14._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(60).to({_off:false},0).to({alpha:1},10).to({_off:true},60).wait(198));

	// img
	this.instance_15 = new lib.img1_1();

	this.timeline.addTween(cjs.Tween.get(this.instance_15).to({_off:true},70).wait(258));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,-300,300,600);


// stage content:



(lib._300x600 = function() {
	this.initialize();

	// cover
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#666666").ss(2,2,0,3).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape.setTransform(150,300);

	// banner
	this.instance = new lib.banner();
	this.instance.setTransform(150,300);

	this.addChild(this.instance,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(149,299,302,602);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;