(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.bgImg = function() {
	this.initialize(img.bgImg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,366);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.urText_v = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AsfCeIAAhIIAKAAIAAAHQACgEAEgDQAFgCAFAAQAGAAAGADQAFADADAGQADAHAAAHQAAAHgDAGQgDAGgFADQgGAEgGAAQgFAAgFgDQgEgDgCgDIAAAfgAsPBfQgEADgBADQgCADAAAGQAAAFACAEQABACAEADQADACAFABQAEgBAEgCQADgDACgCQACgEAAgFQAAgGgCgDQgCgDgDgDQgEgCgEAAQgFAAgDACgAEtCGIgDgCIAAgDIAAgEIADgCIADgBIADABIADACIAAAEIAAADIgDACIgDACgAgsCHIABgIIADAAQABAAAAgBQABAAAAAAQABAAAAAAQABgBAAAAIACgEIABgjIAmAAIAAAwIgIAAIAAgoIgUAAIgBARIgCAOQgBAFgEACQgDADgGABgAo7CEQgFgDgDgGQgDgGAAgHQAAgHADgHQADgGAFgDQAFgDAHAAQAFAAAEACQAEACADAFIAAgHIAKAAIAAAwIgKAAIAAgHQgDAEgEACQgEADgFAAQgHAAgFgEgAo1BfQgDACgDAEQgBAFAAAEQAAADABAGQADADADACQADACAFABQAFgBACgCQAEgCACgDQACgEAAgFQAAgGgCgDQgCgEgEgCQgCgCgFAAQgFAAgDACgAqeCEQgFgDgEgGQgDgGAAgHQAAgIADgFQADgFAGgFQAGgDAHAAQAGAAAHACQAFAEADAEIgGAGQgDgEgEgBQgDgCgFAAQgDAAgFACQgDACgCAEQgCADAAAGQAAAFACAEQABADAEACQADACAFABQAFgBADgCQAEgBADgDIAGAGQgDAEgFADQgHADgGAAQgHAAgGgEgAhaCEQgGgEgDgFQgDgGAAgHQAAgHADgHQADgGAGgDQAHgDAGAAQAHAAAGADQAGADADAGQAEAGAAAIQAAAHgEAGQgDAFgGAEQgFADgIAAQgHAAgGgDgAhVBfQgDACgDAEQgCADAAAGQAAAFACAEQADADADACIAIADIAIgDQADgCACgDQACgEABgFQgBgGgCgDQgCgEgDgCIgIgCIgIACgAkECEQgGgEgDgFQgDgGAAgHQAAgHADgHQAEgGAFgDQAHgDAGAAQAHAAAGADQAFADAEAGQADAGABAIQgBAHgDAGQgDAFgGAEQgFADgIAAQgHAAgGgDgAj/BfQgDACgDAEQgCADAAAGQAAAFACAEQADADADACIAIADIAIgDQADgCACgDQADgEAAgFQAAgGgDgDQgCgEgDgCIgIgCIgIACgAtSCEQgGgEgDgFQgDgGAAgHQAAgHADgHQAEgGAFgDQAHgDAGAAQAHAAAGADQAGADADAGQAEAGgBAIQABAHgEAGQgDAFgGAEQgFADgIAAQgHAAgGgDgAtNBfQgDACgCAEQgCADAAAGQAAAFACAEQACADADACIAIADIAIgDQADgCADgDQABgEAAgFQAAgGgBgDQgDgEgDgCIgIgCIgIACgAESCGIAAgkIgaAkIgIAAIAAgwIAJAAIAAAjIAZgjIAJAAIAAAwgADZCGIAAgjIgQAWIgHAAIgPgWIAAAjIgKAAIAAgwIAKAAIATAZIATgZIAJAAIAAAwgACWCGIAAgwIAJAAIAAAwgAB7CGIAAgVIgXAAIAAAVIgKAAIAAgwIAKAAIAAASIAXAAIAAgSIAKAAIAAAwgAA0CGIAAgoIgRAAIAAgIIAsAAIAAAIIgRAAIAAAogAAUCGIAAgwIAKAAIAAAwgAh+CGIAAgVIgXAAIAAAVIgKAAIAAgwIAKAAIAAASIAXAAIAAgSIAKAAIAAAwgAjRCGIAAgwIAWAAQAJAAAEADQAFADAAAGQAAAEgCADIgFAEQAEABADADQACADAAAFQAAACgCAFIgGAEQgEACgFAAgAjIB/IANAAQAGAAACgCQACgBABgEQAAgHgLAAIgNAAgAjIBqIALAAQAEAAADgCQADgBABgDQAAgIgLABIgLAAgAknCGIAAgoIgYAAIAAAoIgKAAIAAgwIArAAIAAAwgAlyCGIAAgTIgLAAIgLATIgKAAIAMgUQgGgBgDgDQgCgEAAgFQgBgHAGgFQAFgDAJAAIAWAAIAAAwgAmFBfQgDABAAAFQAAADADACQADACAEABIAMAAIAAgQIgMAAQgEgBgDADgAmqCGIAAgVIgYAAIAAAVIgJAAIAAgwIAJAAIAAASIAYAAIAAgSIAKAAIAAAwgAnmCGIAAgVIgXAAIAAAVIgKAAIAAgwIAKAAIAAASIAXAAIAAgSIAKAAIAAAwgApoCGIAAgoIgSAAIAAgIIAsAAIAAAIIgRAAIAAAogArBCGIAAgkIgaAkIgIAAIAAgwIAJAAIAAAjIAZgjIAJAAIAAAwgAtsCGIgMgTIgCgCIgCAAIgIAAIAAAVIgJAAIAAgwIAJAAIAAASIAIAAIACAAIACgBIAMgRIALAAIgRAXIARAZgAunCGIAAgkIgZAkIgJAAIAAgwIAJAAIAAAjIAagjIAIAAIAAAwgAv7CGIAAgwIAWAAQAJAAAEADQAFADAAAGQAAAEgCADIgFAEQAEABADADQACADAAAFQAAACgCAFIgGAEQgEACgFAAgAvyB/IANAAQAGAAACgCQACgBABgEQAAgHgLAAIgNAAgAvyBqIALAAQAEAAADgCQADgBABgDQAAgIgLABIgLAAgACXBKIgCgDIgBgDIABgDIACgCIAEgBIADABIACACIABADIgBADIgCADIgDABgAAWBKIgCgDIgBgDIABgDIACgCIACgBIAEABIACACIABADIgBADIgCADIgEABgAqYAnIAFgHQACgDACgFIgFgBQAAgBgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAAAgBQABAAAAgBQABAAABAAQAAAAABAAQACAAADACQACADAAAFQAAAFgEAFQgDAHgGADgAOIAlIAAgNIgpAAIAAANIgHAAIAAgVIAFAAQADgDAAgEIACgMIAAgUIAmAAIAAAnIAJAAIAAAVgANrgDIgBALQgCAGgBACIAYAAIAAgfIgUAAgAopAlIAAgNIhCAAIAAgvIAKAAIAAAnIATAAIAAgnIAKAAIAAAnIATAAIAAgnIAJAAIAAAnIAIAAIAAAVgAOTAZIABgJIADAAQABAAAAAAQABAAAAAAQABAAAAAAQABgBAAAAIABgEIACgiIAoAAIAAAvIgKAAIAAgnIgVAAIAAAQIgCAOQAAAFgEADQgEACgFAAgAMVAWQgGgCgDgHQgDgGAAgHQAAgHADgGQADgFAGgEQAFgDAIAAQAHAAAFADQAFADADAGQAEAFgBAHIAAAEIgmAAIACAHQADADADACQAEACAEAAQAFAAAEgCQAEgCACgCIAFAGQgDAEgGACQgFACgGAAQgHABgHgEgAMwgEQgCgGgDgDQgDgDgGAAQgHAAgEADQgDADgBAGIAdAAIAAAAgAIrAZIABgJIAEAAQADAAACgCQACgCABgGIACg0IAxAAIAABGIgKAAIAAg9IgeAAIgBAdQAAAMgBAIQgCAHgEADQgEAEgGgBgAIIAYIgCgCIAAgDIAAgEIACgCIAEgBIADABIACACIABAEIgBADIgCACIgDABgAF7AWQgGgCgDgHQgDgHgBgGQABgGADgGQACgGAHgEQAGgDAHAAQAGAAAGADQAGADADAEIgGAFQgCgDgFgBQgDgCgFAAQgDAAgFACQgDACgCAEQgDADAAAFQAAAFADADQABAEAEACQAEACAEAAQAFAAADgCQAFgBACgDIAFAGQgCAEgGADQgGACgGAAQgHABgGgEgACzAWQgGgCgDgHQgDgGAAgHQAAgHADgGQADgFAGgEQAFgDAIAAQAGAAAFADQAGADADAGQADAFAAAHIAAAEIgnAAIADAHQADADADACQAEACAEAAQAFAAAEgCQAEgCADgCIAEAGQgDAEgGACQgGACgFAAQgHABgHgEgADOgEQgBgGgEgDQgEgDgFAAQgHAAgDADQgEADgCAGIAeAAIAAAAgABpAZIABgJIADAAQABAAAAAAQABAAAAAAQABAAAAAAQABgBAAAAIABgEIACgiIAoAAIAAAvIgKAAIAAgnIgVAAIAAAQIgCAOQAAAFgEADQgEACgFAAgAA6AWQgFgDgDgGQgDgGAAgHQAAgHADgGQADgFAFgEQAFgDAHAAQAEAAAFADQAEABADAFIAAgHIAKAAIAAAvIgKAAIAAgHQgDAEgEACQgFACgEAAQgHABgFgEgABAgOQgDACgDAEQgBAFAAADQAAADABAFQADAFADABQACACAFAAQAGAAACgCQAEgBACgFQACgDAAgFQAAgEgCgEQgCgEgEgCQgCgCgGAAQgFAAgCACgAAEAXQgFgCgDgEIAFgFQACACAEACQAEABAFAAQAGAAADgCQADgCAAgDQAAgHgLAAIgKAAIAAgGIAIAAQAGAAACgBQADgCAAgEQAAgDgDgCQgBgCgGAAQgIAAgGAGIgEgGQACgDAFgDIALgCQAKAAAFAEQAEADAAAHQAAAEgCADQgBADgEABQAFAAACADQADADAAAFQAAAEgDADQgCADgFACQgHACgFAAQgGAAgGgCgAg8AWQgGgCgDgHQgEgHAAgGQAAgGAEgGQADgGAGgEQAHgDAGAAQAHAAAGADQAGACACAEIgFAFQgDgDgEgBQgFgCgEAAIgHACQgDACgCADIgEAHIAYAAIAAAGIgYAAQACAIADADQAEADAIAAQAEAAAEgCQAEgBADgDIAFAFQgCAEgGADQgGACgHAAQgGABgHgEgAh5AWQgFgDgDgGQgDgGAAgHQAAgHADgGQADgFAFgEQAFgDAHAAQAEAAAFADQAEABADAFIAAgHIAKAAIAAAvIgKAAIAAgHQgDAEgEACQgFACgEAAQgHABgFgEgAhzgOQgDACgDAEQgBAFAAADQAAADABAFQADAFADABQACACAFAAQAGAAACgCQAEgBACgFQACgDAAgFQAAgEgCgEQgCgEgEgCQgCgCgGAAQgFAAgCACgAkwAZIABgJIADAAQABAAAAAAQABAAAAAAQABAAAAAAQABgBAAAAIACgEIABgiIAnAAIAAAvIgJAAIAAgnIgUAAIgBAQIgCAOQgBAFgEADQgCACgHAAgAoSAWQgGgDgDgGQgDgGAAgHQAAgHADgGQAEgGAFgDQAHgDAGAAQAHAAAGADQAFADAEAGQADAGABAHQgBAIgDAFQgDAGgGADQgFADgIAAQgHAAgGgDgAoNgOQgDACgDAEQgCAEAAAEQAAAFACADQADAFADABIAIACIAIgCQADgBACgFQADgDAAgFQAAgEgDgEQgCgEgDgCIgIgCIgIACgAtwAWQgGgDgDgGQgDgGAAgHQAAgHADgGQADgGAGgDQAHgDAGAAQAHAAAGADQAFADAEAGQADAGABAHQgBAIgDAFQgDAGgGADQgFADgIAAQgHAAgGgDgAtrgOQgDACgCAEQgDAEAAAEQAAAFADADQACAFADABIAIACIAIgCQADgBADgFQACgDAAgFQAAgEgCgEQgDgEgDgCIgIgCIgIACgAPyAYIAAgTIgMAAIgLATIgKAAIAMgUQgGgBgDgDQgDgCAAgHQABgGAFgFQAFgDAJAAIAXAAIAAAvgAPegOQgDABAAAEQAAAFADABQACACAFAAIANAAIAAgPIgNAAQgFAAgCACgAK7AYIAAgvIAKAAIAAAnIAUAAIAAgnIAKAAIAAAnIATAAIAAgnIAKAAIAAAvgAKiAYIAAgjIgZAjIgJAAIAAgvIAJAAIAAAiIAZgiIAJAAIAAAvgAHWAYIAAgvIAKAAIAAARIAKAAQALAAAEAEQAFADAAAHQAAAJgFADQgFAEgKAAgAHgAQIAKAAQALAAgBgIQABgEgDgBQgDgCgFAAIgKAAgAGxAYIAAgnIgRAAIAAgIIArAAIAAAIIgRAAIAAAngAFeAYIAAgvIAJAAIAAAvgAFDAYIAAgVIgXAAIAAAVIgKAAIAAgvIAKAAIAAATIAXAAIAAgTIAKAAIAAAvgAESAYIgMgUIgCAAIgCgBIgDAAIAAAVIgKAAIAAgVIgEAAIgCABIgBAAIgMAUIgLAAIAQgZIgQgWIALAAIAMARIABABIACABIAEAAIAAgTIAKAAIAAATIADAAIACgBIACgBIAMgRIAKAAIgQAWIAQAZgAiSAYIgMgUIgCAAIgCgBIgHAAIAAAVIgKAAIAAgvIAKAAIAAATIAHAAIACgBIACgBIAMgRIALAAIgRAWIARAZgAjNAYIAAgjIgZAjIgJAAIAAgvIAJAAIAAAiIAagiIAIAAIAAAvgAk8AYIgMgUIgCAAIgCgBIgHAAIAAAVIgKAAIAAgvIAKAAIAAATIAIAAIABgBIACgBIAMgRIALAAIgRAWIASAZgAl3AYIAAgjIgZAjIgJAAIAAgvIAJAAIAAAiIAagiIAIAAIAAAvgAnLAYIAAgvIAWAAQAJgBAEAEQAEADABAGQgBAEgBADIgGAEQAFABADADQACACAAAFQAAACgCAEIgGAGQgEABgGAAgAnCARIANAAQAGAAACgCQACgCAAgDQAAgHgKAAIgNAAgAnCgDIALAAQAEAAADgBQAEgCAAgEQAAgGgLAAIgLAAgAquAYIAAgVIgXAAIAAAVIgKAAIAAgvIAKAAIAAATIAXAAIAAgTIAKAAIAAAvgArpAYIAAgjIgZAjIgJAAIAAgvIAJAAIAAAiIAagiIAIAAIAAAvgAswAYIAAgnIgRAAIAAgIIArAAIAAAIIgRAAIAAAngAuJAYIgOgUIgBAAIgCgBIgIAAIAAAVIgJAAIAAgvIAJAAIAAATIAIAAIACgBIABgBIAOgRIAKAAIgRAWIARAZgAu/AYIAAgvIAKAAIAAAvgAvZAYIAAgVIgZAAIAAAVIgJAAIAAgvIAJAAIAAATIAZAAIAAgTIAJAAIAAAvgAFggkIgDgCIgBgCIABgEIADgCIADgBIADABIACACIABAEIgBACIgCACIgDACgAu+gkIgBgCIgBgCIABgEIABgCIADgBIAEABIACACIABAEIgBACIgCACIgEACgAmNg8IADgJIAFABIAFgBIADgEIAEgGIACgGIgVgwIALAAIAPAmIAPgmIAKAAIgcBCQgDADgEADQgDACgFAAgAFAg8IAAhJIAJAAIAAAGQADgDAFgCQADgDAGAAQAHAAAEAEQAGACADAHQADAFAAAIQAAAHgDAGQgDAGgGADQgEADgHAAQgGABgDgDQgFgDgDgDIAAAggAFQh8QgDADgCADQgCADAAAGQAAAFACADQACADADAEQAEABAEAAQAFAAADgBQADgEACgDQACgDAAgFQAAgGgCgDQgCgDgDgDQgDgCgFAAQgEAAgEACgAjIg8IAAhJIAKAAIAAAGQACgDAFgCQAEgDAGAAQAGAAAFAEQAGACADAHQADAFAAAIQAAAHgDAGQgDAGgGADQgFADgGAAQgGABgEgDQgFgDgCgDIAAAggAi3h8QgEADgBADQgCADAAAGQAAAFACADQABADAEAEQAEABAEAAQAFAAADgBQAEgEABgDQACgDAAgFQAAgGgCgDQgBgDgEgDQgDgCgFAAQgEAAgEACgAMLhXQgGgCgDgHQgEgHABgHQgBgGAEgGQADgFAFgEQAIgEAGAAQAGAAAGADQAHADACADIgHAGQgBgDgFgBQgDgCgEAAQgEAAgFACQgDACgDAEQgBAEAAAEQAAAGABADQACAEAEADQADABAGAAQAEAAADgBQAFgCABgDIAHAGQgDAEgFADQgHADgGgBQgHAAgGgDgAIhhUIABgJIADAAQABAAAAAAQABAAAAAAQABAAAAAAQABgBAAAAIABgFIACgiIAoAAIAAAwIgKAAIAAgpIgVAAIAAARIgCAPQAAAGgEACQgEACgFAAgAG8hWQgFgCgDgEIAFgFQACACAEACQAFACAEgBQAGAAADgCQADgBAAgFQAAgGgLAAIgKAAIAAgHIAIAAQAFAAADgBQADgCAAgEQAAgEgDgBQgBgCgGAAQgIAAgGAGIgFgGQADgDAFgDIALgCQAJAAAGAEQAEAEAAAGQAAAEgCADQgBADgEABQAFACACACQADACAAAFQAAAFgDADQgCADgGADQgGABgFAAQgGABgGgDgAENhXQgGgCgDgHQgDgGAAgHQAAgIADgFQADgHAGgCQAFgEAIAAQAGAAAFAEQAGADADAFQADAFAAAHIAAAFIgnAAIADAHQADADADACQAEACAEAAQAFAAAEgCQAEgCADgCIAEAGQgDAEgGACQgGADgFgBQgHAAgHgDgAEohxQgBgIgEgCQgEgEgFAAQgHAAgDAEQgEACgCAIIAeAAIAAAAgACWhVIgCgCIAAgDIAAgEIACgCIAEgBIADABIACACIABAEIgBADIgCACIgDABgAhLhWQgGgCgDgEIAGgFQACACAEACQAFACAEgBQAGAAADgCQADgBAAgFQAAgGgKAAIgLAAIAAgHIAIAAQAGAAACgBQADgCAAgEQAAgEgDgBQgBgCgGAAQgIAAgGAGIgFgGQADgDAFgDIALgCQAKAAAEAEQAFAEABAGQgBAEgCADQgBADgEABQAFACACACQACACABAFQgBAFgCADQgCADgFADQgHABgFAAQgGABgGgDgAlKhXQgGgCgDgHQgDgGAAgIQAAgGADgGQACgFAHgEQAGgEAHAAQAGAAAHADQAGADACADIgGAGQgDgDgEgBQgDgCgFAAQgDAAgFACQgDACgCAEQgCAEgBAEQABAGACADQABAEAEADQAEABAEAAQAFAAADgBQAEgCADgDIAGAGQgCAEgGADQgHADgGgBQgHAAgGgDgAnChXQgGgCgDgHQgDgHgBgHQABgGADgGQADgFAGgEQAHgEAHAAQAFAAAGADQAGACADAEIgFAFQgDgCgEgCQgFgCgDAAIgIACQgDABgDAEIgDAHIAZAAIAAAHIgZAAQABAIAFADQAEADAHAAQAFAAADgCQAEgBADgDIAFAFQgDAEgGADQgGADgFgBQgHAAgHgDgAn+hXQgGgDgDgGQgDgGAAgHQAAgIADgFQADgHAGgCQAFgEAGAAQAGAAADADQAEACAEADIAAgGIAJAAIAAAwIgJAAIAAgHQgEAEgEACQgDADgGgBQgGAAgFgDgAn5h8QgDACgCAEQgCAFgBAEQABAEACAEQACAFADACQACABAGAAQAFAAACgBQADgCADgFQACgDAAgFQAAgGgCgDQgDgEgDgCQgCgCgFAAQgGAAgCACgArKhUIABgJIADAAQABAAAAAAQABAAAAAAQABAAAAAAQABgBAAAAIABgFIACgiIAoAAIAAAwIgKAAIAAgpIgVAAIAAARIgCAPQAAAGgEACQgEACgFAAgAushXQgFgCgEgHQgDgGAAgHQAAgIADgFQADgHAGgCQAFgEAHAAQAHAAAGAEQAFADADAFQADAFAAAHIAAAFIgmAAIACAHQADADADACQADACAFAAQAFAAADgCQAFgCACgCIAGAGQgEAEgFACQgHADgGgBQgGAAgHgDgAuRhxQgCgIgDgCQgDgEgHAAQgGAAgEAEQgDACgBAIIAdAAIAAAAgAHzhXQgGgDgDgGQgDgGAAgHQAAgIADgFQAEgHAFgCQAHgEAGAAQAHAAAGAEQAGACADAHQAEAFgBAIQABAHgEAGQgDAGgGADQgFADgIAAQgHAAgGgDgAH4h8QgDACgCAEQgCADAAAGQAAAFACADQACAFADACIAIABIAIgBQADgCADgFQABgDAAgFQAAgGgBgDQgDgEgDgCIgIgCIgIACgAGFhXQgGgDgDgGQgDgGAAgHQAAgIADgFQADgHAGgCQAHgEAGAAQAHAAAGAEQAGACADAHQADAFABAIQgBAHgDAGQgDAGgGADQgFADgIAAQgHAAgGgDgAGKh8QgDACgCAEQgCADgBAGQABAFACADQACAFADACIAIABIAIgBQADgCADgFQACgDAAgFQAAgGgCgDQgDgEgDgCIgIgCIgIACgAprhWQgGgDgDgFQgDgHgBgFIgIAAIAAAVIgKAAIAAgwIAKAAIAAATIAIAAQABgHAEgEQADgFAFgCQAGgDAGAAQAGAAAGAEQAGACADAHQADAFAAAIQAAAHgDAGQgDAGgGADQgFADgHAAQgHAAgFgCgApnh8QgDACgDAEQgBAEAAAFQAAAFABADQADAFADACQAEABAEAAQADABAEgDQADgBACgFQACgDAAgFQAAgFgCgEQgCgEgDgCQgEgCgDAAQgEAAgEACgAPUhVIAAgwIAJAAIAAARIALAAQAKAAAFAEQAFAEAAAHQAAAJgFADQgGAEgJAAgAPdhdIALAAQAKABABgJQgBgEgCgBQgCgDgGAAIgLAAgAOuhVIAAgpIgRAAIAAgHIAsAAIAAAHIgRAAIAAApgAOIhVIAAgkIgaAkIgIAAIAAgwIAJAAIAAAjIAZgjIAJAAIAAAwgANBhVIAAgpIgSAAIAAgHIAsAAIAAAHIgRAAIAAApgALuhVIAAgwIAKAAIAAAwgALXhVIAAgjIgQAVIgGAAIgQgVIAAAjIgKAAIAAgwIAKAAIATAYIATgYIAJAAIAAAwgAJihVIAAgwIAJAAIAAARIALAAQAKAAAFAEQAFAEAAAHQAAAJgFADQgGAEgJAAgAJrhdIAKAAQAMABAAgJQAAgEgDgBQgCgDgHAAIgKAAgADuhVIgGgOIgfAAIgGAOIgKAAIAbhHIAIAAIAcBHgADlhsIgMghIgNAhIAZAAgABkhVIAAgwIAVAAQAKAAAEADQAEADAAAGQAAAEgBADIgGAEQAGABABAEQADACAAAEQAAAEgCADIgGAGQgDABgHAAgABthcIANAAQAGAAACgCQADgCgBgDQAAgHgKAAIgNAAgABthwIALAAQAEAAAEgCQADgCAAgEQgBgGgKgBIgLAAgABQhVIAAgwIAJAAIAAAwgABAhVIgOgTIgBgBIgCgBIgHAAIAAAVIgKAAIAAgwIAKAAIAAATIAIAAIABgBIABgBIAOgRIAKAAIgRAWIASAagAAEhVIAAgkIgZAkIgIAAIAAgwIAJAAIAAAjIAYgjIAJAAIAAAwgAhphVIAAgkIgZAkIgJAAIAAgwIAJAAIAAAjIAagjIAIAAIAAAwgAjshVIgNgSIgOASIgLAAIASgZIgSgXIALAAIAOARIANgRIALAAIgTAXIATAZgAkhhVIAAgwIAJAAIAAAwgAochVIAAgUQgFADgIAAQgFAAgEgCQgEgCgDgEQgDgEABgGIAAgNIAJAAIAAAMQABAGACACQAEADAEgBQAHABAEgDIAAgUIALAAIAAAwgArVhVIgOgTIgBgBIgCgBIgIAAIAAAVIgJAAIAAgwIAJAAIAAATIAIAAIACgBIABgBIAOgRIAKAAIgRAWIARAagAsRhVIAAgkIgaAkIgIAAIAAgwIAJAAIAAAjIAZgjIAJAAIAAAwgAtlhVIAAgwIAVAAQAKAAAEADQAFADgBAGQABAEgCADIgGAEQAGABABAEQADACAAAEQAAAEgCADIgGAGQgDABgGAAgAtchcIANAAQAGAAACgCQACgCAAgDQABgHgLAAIgNAAgAtchwIALAAQAFAAADgCQACgCAAgEQAAgGgKgBIgLAAgAvKhVIAAggIgmAAIAAAgIgKAAIAAhHIAKAAIAAAdIAmAAIAAgdIAJAAIAABHgALwiSIgCgCIgBgCIABgEIACgCIACgBIAEABIACACIABAEIgBACIgCACIgEABgABSiSIgDgCIgBgCIABgEIADgCIADgBIADABIACACIABAEIgBACIgCACIgDABgAkgiSIgCgCIgBgCIABgEIACgCIAEgBIADABIACACIABAEIgBACIgCACIgDABg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.urText_v, new cjs.Rectangle(-102,-15.8,204,31.6), null);


(lib.t1_v = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#34303E").s().p("AjBD3IgLgCIAFgWQAIACAHAAQAHAAAFgCQAGgDADgFQAFgGAEgMIAGgOIg1iAIAaAAIAoBjIAmhjIAbAAIg6CNQgGAQgJAPQgHAKgKAGQgIAFgOAAIgLgBgAg/C3QgEgCgCgEQgDgEAAgFQAAgEADgEQACgEAEgDQADgCAFAAQAFAAAEACQAEADACAEQADAEAAAEQAAAFgDAEQgCAEgEACQgEACgFAAQgEAAgEgCgAnPCxQgNgJgJgPQgIgQAAgSQAAgTAIgQQAJgQANgHQANgJARAAQAPAAAKAGQAMAGAGAKIAAgTIAZAAIAAB/IgZAAIAAgTQgGALgMAFQgLAGgOAAQgQAAgOgIgAnABQQgJAGgFAKQgFAJAAAOQAAANAFAKQAFAJAJAGQAJAGALAAQALAAAJgGQAJgGAFgJQAFgKAAgNQAAgOgFgJQgFgKgJgGQgJgFgLAAQgLAAgJAFgAsFCxQgNgJgJgPQgIgQAAgSQAAgTAIgQQAJgQANgHQANgJARAAQAPAAAKAGQAMAGAGAKIAAgTIAZAAIAAB/IgZAAIAAgTQgGALgMAFQgLAGgOAAQgQAAgOgIgAr2BQQgJAGgFAKQgFAJAAAOQAAANAFAKQAFAJAJAGQAJAGALAAQALAAAJgGQAJgGAFgJQAFgKAAgNQAAgOgFgJQgFgKgJgGQgJgFgLAAQgLAAgJAFgAuSC0QgOgGgIgKIAOgPQAHAHAJAFQALAEAMAAQAPAAAIgGQAIgFAAgJQAAgSgbAAIgaAAIAAgSIAVAAQAOAAAHgFQAHgEAAgJQAAgJgHgFQgGgEgNAAQgXAAgOAPIgOgQQAJgJANgFQANgGARAAQAYAAAMAKQANAJAAARQAAAKgFAHQgFAIgJAEQAMADAGAIQAGAHAAALQAAAMgHAIQgGAJgNAFQgMAFgSAAQgRAAgOgFgAjvC2IgjgvIgjAvIgdAAIAxhAIgxg/IAeAAIAjAvIAjgvIAcAAIgwBAIAxA/gAojC2IAAhpIg/AAIAABpIgZAAIAAh/IBxAAIAAB/gAgZg2IAAi+IAZAAIAAATQAGgKALgGQAKgGAPAAQARAAANAJQAOAIAHAPQAIAPAAAUQAAATgIAPQgHAOgOAKQgOAIgQAAQgOAAgLgGQgKgFgHgLIAABSgAARjbQgJAGgFAKQgEAJAAAOQAAANAEAKQAFAJAJAGQAIAGAMAAQALAAAJgGQAJgGAFgJQAFgMAAgLQAAgMgFgLQgFgKgJgGQgJgFgLAAQgMAAgIAFgACeh7QgPgIgJgPQgIgQAAgSQAAgTAIgQQAJgPAOgIQAOgJATAAQARAAAOAIQAPAIAIAPQAIAOAAARIgBALIhkAAQACALAFAJQAGAJAJAEQAJAFANAAQALAAALgEQALgEAGgHIANAQQgIAJgPAGQgPAGgQAAQgUAAgPgJgACkjZQgKAKgCAQIBLAAQgCgQgKgKQgLgJgOAAQgPAAgLAJgAijh6QgNgJgJgPQgIgQAAgSQAAgTAIgQQAJgQANgHQANgJARAAQAPAAAKAGQAMAGAGAKIAAgTIAZAAIAAB/IgZAAIAAgTQgGALgMAFQgLAGgOAAQgQAAgOgIgAiUjbQgJAGgFAKQgFAJAAAOQAAANAFAKQAFAJAJAGQAJAGALAAQALAAAJgGQAJgGAFgJQAFgKAAgNQAAgOgFgJQgFgKgJgGQgJgFgLAAQgLAAgJAFgAoyh7QgOgIgJgPQgIgQAAgSQAAgSAIgQQAIgOAPgKQAPgJAUAAQASAAANAHQAPAHAIALIgQAPQgHgIgKgEQgJgFgMAAQgLAAgKAGQgKAFgFAKQgFAKAAANQAAANAFAJQAGAKAJAGQAJAFAMAAQAMAAAJgEQAKgFAHgIIAQAPQgIAMgOAHQgQAGgQAAQgUAAgPgJgAsPh6QgNgJgJgPQgIgQAAgSQAAgTAIgQQAJgQANgHQANgJARAAQAPAAAKAGQAMAGAGAKIAAgTIAZAAIAAB/IgZAAIAAgTQgGALgMAFQgLAGgOAAQgQAAgOgIgAsAjbQgJAGgFAKQgFAJAAAOQAAANAFAKQAFAJAJAGQAJAGALAAQALAAAJgGQAJgGAFgJQAFgKAAgNQAAgOgFgJQgFgKgJgGQgJgFgLAAQgLAAgJAFgANGh7QgPgIgJgPQgIgQAAgSQAAgTAIgPQAIgPAQgJQAOgJAUAAQAUAAAOAJQAOAIAJAQQAIAPAAATQAAATgIAPQgJAQgOAHQgOAJgUAAQgUAAgOgJgANTjaQgKAGgFAJQgFAKAAANQAAANAFAJQAGAKAJAFQAJAGAMAAQAMAAAIgGQAKgFAFgKQAFgKAAgMQAAgNgFgKQgFgJgKgGQgJgGgLAAQgLAAgKAGgAJCh7QgPgIgJgPQgIgQAAgSQAAgTAIgPQAIgPAQgJQAOgJAUAAQAUAAAOAJQAOAIAJAQQAIAPAAATQAAATgIAPQgJAQgOAHQgOAJgUAAQgUAAgOgJgAJPjaQgKAGgFAJQgFAKAAANQAAANAFAJQAGAKAJAFQAJAGAMAAQAMAAAIgGQAKgFAFgKQAFgKAAgMQAAgNgFgKQgFgJgKgGQgJgGgLAAQgLAAgKAGgALAh1IAAh/IBZAAIAAAWIhAAAIAABpgAHsh1IAAg4Ig/AAIAAA4IgZAAIAAh/IAZAAIAAAyIA/AAIAAgyIAZAAIAAB/gAEyh1IAAhpIgrAAIAAgWIBwAAIAAAWIgsAAIAABpgAknh1IAAh/IBZAAIAAAWIhAAAIAABpgAlkh1IAAhcIhCBcIgXAAIAAh/IAYAAIAABdIBChdIAXAAIAAB/gAt9h1IAAhpIgrAAIAAgWIBwAAIAAAWIgsAAIAABpg");
	this.shape.setTransform(-15.1,17.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AOrB6IAGgfIAQACQAEAAAHgCQAGgDADgFIAIgPIADgIIg1iAIAnAAIAhBWIAghWIAmAAIg3CIQgJAWgIAMQgIAMgLAGQgLAGgQAAQgPAAgJgEgAhRB6IAHgfIAQACQAEAAAHgCQAFgDAEgFIAIgPIADgIIg1iAIAoAAIAfBWIAghWIAmAAIg3CIQgIAWgIAMQgIAMgLAGQgLAGgQAAQgOAAgLgEgAA1BeQAKgIAGgJQAHgJADgJQgKgDgEgEQgFgGAAgIQAAgGACgEQADgFAFgDQAEgDAHAAQAGAAAGADQAGADADAGQADAGABAMQgBAKgFAMQgGANgJAKQgJAKgMAHgAnNBbIAAggIhdAAIAAAgIggAAIAAg+IAPAAQAFgHAEgLQACgLABgSIACgyIBrAAIAABhIAUAAIAAA+gAoMgQQAAAQgCALQgDALgEAHIAvAAIAAhDIglAAgAMQA+IAFghIAGAAQAFAAAEgCQACgEACgHQACgIgBgNIADg/IBuAAIAAB/IglAAIAAhhIgmAAIgBAiQgCAXgEAQQgEAOgLAHQgJAHgSAAIgOgBgAKdA2QgRgKgHgPQgJgQAAgRQAAgTAJgQQAIgPAPgJQAPgJATAAQATAAAPAJQAPAIAIAPQAIAOAAASIgBAOIhcAAQADALAIAHQAJAGAPAAQAKAAAKgCQALgFAFgDIARAaQgKAHgPAFQgPAFgPAAQgWgBgQgIgAKrgjQgHAHgCALIA5AAQgCgMgIgGQgHgGgMgBQgMABgHAGgAFxA2QgPgJgJgQQgJgOABgTQgBgTAJgPQAJgQAPgIQARgKATAAQATAAAQAKQAQAIAJAQQAIAQAAASQAAASgIAPQgJAQgQAJQgPAIgUABQgTgBgRgIgAGEghQgGADgFAIQgEAJAAAJQAAAJAEAIQAEAHAHAEQAIAFAJAAQAJAAAHgFQAHgEAEgHQAFgJAAgIQAAgIgFgKQgFgIgGgDQgHgFgJAAQgJAAgIAFgAryA5QgPgFgHgJIASgXQAPANAVAAQAMAAAGgDQAHgEAAgHQAAgGgFgDQgFgDgLgBIgYAAIAAgWIAUAAQAVgBAAgNQAAgGgFgEQgFgCgKAAQgUgBgOANIgTgWQAKgJAOgGQAPgFAPAAQAaAAAPAKQANAKAAARQAAALgEAHQgGAHgIAEQAXAHAAAUQAAANgHAJQgJAKgMAEQgOAFgTABQgSgBgOgFgAt6A2QgQgKgIgPQgIgQAAgRQAAgTAIgQQAIgPAPgJQAPgJATAAQATAAAPAJQAPAIAIAPQAIAOAAASIgBAOIhcAAQADALAIAHQAJAGAPAAQALAAAJgCQAKgFAHgDIAQAaQgKAHgOAFQgPAFgRAAQgVgBgQgIgAtrgjQgJAHgBALIA5AAQgCgMgIgGQgHgGgMgBQgMABgGAGgAJBA7IAAhhIgvAAIAABhIgkAAIAAh/IB3AAIAAB/gAEVA7IAAhhIguAAIAABhIglAAIAAh/IB3AAIAAB/gAiHA7IAAhLIgeAqIgZAAIgegqIAABLIgjAAIAAh/IAjAAIAqA5IArg5IAjAAIAAB/gAlAA7IAAhNIgzBNIgiAAIAAh/IAjAAIAABNIAzhNIAhAAIAAB/gAw5A7IAAi4IB6AAIAAAhIhVAAIAAAoIAkAAQAfAAASAOQARANABAbQgBAcgRAPQgSAOggAAgAwUAaIAjAAQAdAAAAgYQABgKgIgGQgIgGgOAAIgjAAg");
	this.shape_1.setTransform(0.7,-29.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1_v, new cjs.Rectangle(-108.8,-42.5,217.7,85.1), null);


(lib.r_part = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#35303E").s().p("AhijHQBSAAA5A7QA6A6AABSQAABTg6A6Qg5A7hSAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.r_part, new cjs.Rectangle(-9.9,-20,19.9,40), null);


(lib.logo_iqos = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AuzFoQg9AAgygfQgwgdgcgxQgcgwgBg4QgCg7Afg1IClkeQAeg0A0gcQAxgcA4AAQA5AAAwAcQA0AcAeA0IClEeQAfA1gBA7QgBA4gdAwQgbAxgwAdQgzAfg9AAgAt8jUQgyAWgoAnQgmAngWAzQgWA0AAA5QAAA6AWA0QAWAyAmApQAoAnAyAUQA1AXA5AAQA6AAA1gXQAygUAognQAngpAUgyQAXg0AAg6QAAg5gXg0QgUgzgngnQgogngygWQg1gVg6gBQg5ABg1AVgAE1C7IgsgtIgFgDQgCgBgEAAIjJAAQg+AAgkgfQgigcAAgtIAAiqQAAgHAGgFQAGgGAHAAIDmAAQA9AAAkAeQAjAcAAAuIAABPQAAAIgGAFQgGAFgGAAIgHAAQgIAAgGgFQgEgFAAgIIAAhPQAAgLgFgLQgFgLgJgHQgLgKgUgGQgQgEgXgBIjIAAIgEABIgBAGIAACKQAAAMAEALQAFAKAJAIQALAKASAFQASAFAXAAIDVAAQAGAAAGABIAJAHIA1A2QAFAEAAAIQAAAIgFAFIgFAFQgFAFgHAAQgJAAgFgFgAOMCKQgVAAgTgHQgUgJgPgOIgJgIQgFgHgBgHQAAgHAFgGIAFgFQAFgEAHgCQAIAAAGAGIAKAJQAJAJALAEQALAFANAAICQAAQAVAAAPgDQAPgFAJgHQAFgFACgEQADgHAAgLQAAgKgDgFQgCgGgFgEQgJgIgPgDQgPgEgVAAIh6AAQg3AAgfgWQgagWAAgiIAAgKQAAgiAagVQAfgYA3AAICFAAQAUAAASAHQASAIAPAMIAMAMQAGAEABAIQAAAIgEAFIgFAFQgFAGgIAAQgHABgGgGIgMgKQgIgIgMgEQgMgFgLAAIiFAAQgTAAgQAFQgPADgKAHQgEADgDAHQgDAFAAALQAAALADAFQADAIAEADQAJAHAQAEQAQADATAAIB6AAQA5ABAdAWQAaAUAAAjIAAAKQAAAjgaAUQgdAYg5AAgAH7CKQg/AAgkgfQghgcAAgtIAAhUQAAguAhgcQAkgeA/AAIB1AAQA9AAAkAeQAiAcAAAuIAABUQAAAtgiAcQgkAfg9AAgAHShqQgSAGgNAKQgIAHgEALQgGALAAALIAABUQAAAMAGALQAEAKAIAIQANAKASAFQASAFAXAAIB1AAQAWAAASgFQASgFAMgKQAJgIAFgKQAFgLAAgMIAAhUQAAgNgFgJQgFgLgJgHQgMgKgSgGQgSgEgWgBIh1AAQgXABgSAEgAi2CKQgIAAgGgGQgFgEAAgIIAAj/QAAgJAFgEQAGgGAIAAIAFAAQAIAAAFAGQAGAFAAAIIAAD/QAAAIgGAEQgFAGgIAAg");
	this.shape.setTransform(-1.6,0);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.logo_iqos, new cjs.Rectangle(-118,-36,232.9,72), null);


(lib.l_part = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#35303E").s().p("AgoCNQg7g6AAhTQAAhSA7g6QA5g7BTAAIAAGPQhTAAg5g7g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.l_part, new cjs.Rectangle(-9.9,-20,19.9,40), null);


(lib.btn_txt = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AF4BIIgFgCIACgMIAJABQAEABADgCQADgCACgDQACgDADgHIADgJIgehIIAPAAIAXA4IAWg4IAPAAIghBQQgFAMgEAGQgEAGgFADQgFADgIABgAlhA5IAAgXIhQAAIAAAXIgNAAIAAgkIALAAQADgDACgGIADgNIAChHIBIAAIAABdIAPAAIAAAkgAmcgXQAAANgCAOQgBALgEAGIA0AAIAAhPIgsAAgADuAfQgIgEgGgKQgEgIAAgKQAAgMAEgIQAFgIAJgFQAIgGALAAQAMAAAIAGQAJAFAFAIQAEAJAAALQAAAKgEAIQgGAKgIAEQgIAFgMAAQgLAAgIgFgAD2gXQgGADgDAGQgDAGAAAHQAAAGADAGQADAFAGAEQAFADAGAAQAIAAAEgDQAGgEADgFQADgGAAgGQAAgHgDgGQgDgGgGgDQgEgDgIAAQgGAAgFADgAB8AjIADgMIAEAAQAEAAACgCQABgDABgEIACg0IA7AAIAABIIgOAAIAAg7IgfAAIAAAZQgBAOgCAHQgCAGgFAFQgEAEgKAAgAA0AfQgHgEgFgKQgFgHAAgLQAAgLAFgJQAFgJAHgEQAIgGAKAAQAIAAAGADQAHAEADAGIAAgLIAPAAIAABIIgPAAIAAgLQgDAGgHAEQgGADgIAAQgKAAgIgFgAA8gXQgEADgEAGQgDAFAAAIQAAAGADAGQAEAGAEADQAGADAHAAQAGAAAFgDQAGgDACgGQADgGAAgGQAAgIgDgFQgCgFgGgEQgFgDgGgBQgHABgGADgAhxAfQgIgEgFgKQgEgHAAgLQAAgLAEgJQAFgJAIgEQAIgGAKAAQAHAAAHADQAGAEAFAGIAAgLIANAAIAABIIgNAAIAAgLQgFAGgGAEQgHADgHAAQgKAAgIgFgAhogXQgGADgCAGQgDAFAAAIQAAAGADAGQACAGAGADQAFADAGAAQAHAAAFgDQAFgDADgGQADgGAAgGQAAgIgDgFQgDgGgFgDQgFgDgHgBQgGABgFADgAk7AfQgIgEgGgKQgFgIAAgKQAAgLAFgJQAGgJAIgEQAIgGAMAAQAKAAAJAGQAJAFAEAIQAGAKAAAKQAAAIgGAKQgFAKgIAEQgJAFgKAAQgMAAgIgFgAk0gXQgFADgDAGQgDAGAAAHQAAAGADAGQADAFAFAEQAGADAHAAQAGAAAFgDQAFgDAEgGQACgGAAgGQAAgHgCgGQgDgGgGgDQgFgDgGAAQgHAAgGADgAE9AiIAAhIIAyAAIAAANIgkAAIAAA7gAgOAiIAAg7IgaAAIAAgNIBAAAIAAANIgZAAIAAA7gAiVAiIgUgdIgCgCIgDAAIgLAAIAAAfIgPAAIAAhIIAPAAIAAAdIALAAIADgBIAWgcIAQAAIgaAiIAaAmg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.btn_txt, new cjs.Rectangle(-44.7,-7.2,89.5,14.5), null);


(lib.btn_round = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#35303E").s().p("AiMCNQg7g6AAhTQAAhSA7g6QA6g7BSAAQBTAAA6A7QA7A6AABSQAABTg7A6Qg6A7hTAAQhSAAg6g7g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.btn_round, new cjs.Rectangle(-20,-20,40,40), null);


(lib.btn_bg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#35303E").s().p("AoRDIQhSAAg7g6Qg6g5AAhTIAAgCQAAhSA6g6QA7g7BSAAIQjAAQBSAAA7A7QA6A6AABSIAAACQAABSg6A6Qg7A6hSAAg");
	this.shape.setTransform(-0.2,0);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.btn_bg, new cjs.Rectangle(-73.1,-20,145.8,40), null);


(lib.bgImg_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.bgImg();
	this.instance.parent = this;
	this.instance.setTransform(-150,-183);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bgImg_1, new cjs.Rectangle(-150,-183,300,366), null);


(lib.bg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E3803C").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.bg, new cjs.Rectangle(-150,-300,300,600), null);


(lib.btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_4
	this.instance = new lib.btn_txt();
	this.instance.parent = this;
	this.instance.setTransform(0,8.9);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(12).to({_off:false},0).to({y:0.7,alpha:1},8).wait(1));

	// r_part
	this.instance_1 = new lib.r_part();
	this.instance_1.parent = this;
	this.instance_1.setTransform(10.1,0);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(9).to({_off:false},0).to({x:62.4},8,cjs.Ease.get(1)).to({_off:true},1).wait(3));

	// l_part
	this.instance_2 = new lib.l_part();
	this.instance_2.parent = this;
	this.instance_2.setTransform(-10,0);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(9).to({_off:false},0).to({x:-62.9},8,cjs.Ease.get(1)).to({_off:true},1).wait(3));

	// Слой_5
	this.instance_3 = new lib.btn_bg();
	this.instance_3.parent = this;
	this.instance_3.setTransform(0,0,0.01,1);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(9).to({_off:false},0).to({scaleX:1},8,cjs.Ease.get(1)).wait(4));

	// Слой_1
	this.instance_4 = new lib.btn_round();
	this.instance_4.parent = this;
	this.instance_4.setTransform(0,0,0.012,0.012);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({scaleX:1.2,scaleY:1.2},5,cjs.Ease.get(1)).to({scaleX:1,scaleY:1},4,cjs.Ease.quadInOut).to({_off:true},9).wait(3));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-0.2,-0.2,0.5,0.5);


(lib.banner = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_62 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(62).call(this.frame_62).wait(1));

	// logo
	this.instance = new lib.logo_iqos();
	this.instance.parent = this;
	this.instance.setTransform(0.9,-257.9,0.507,0.507,0,0,0,0.2,-0.3);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:1},15).wait(48));

	// btn
	this.instance_1 = new lib.btn("synched",0,false);
	this.instance_1.parent = this;
	this.instance_1.setTransform(-49.3,212.7,0.999,1,0,0,0,-0.1,0.3);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(25).to({_off:false},0).wait(38));

	// urText
	this.instance_2 = new lib.urText_v();
	this.instance_2.parent = this;
	this.instance_2.setTransform(-21.8,272.1,1,1,0,0,0,0.1,0.3);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(15).to({_off:false},0).to({regY:0.2,scaleX:1,alpha:1},10).wait(38));

	// t1
	this.instance_3 = new lib.t1_v();
	this.instance_3.parent = this;
	this.instance_3.setTransform(12.2,133.5);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(15).to({_off:false},0).to({x:-14.8,alpha:1},10,cjs.Ease.cubicOut).wait(38));

	// bgImg
	this.instance_4 = new lib.bgImg_1();
	this.instance_4.parent = this;
	this.instance_4.setTransform(0,-117);
	this.instance_4.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({alpha:1},15).wait(48));

	// bg
	this.instance_5 = new lib.bg();
	this.instance_5.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(63));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,-300,300,600);


// stage content:
(lib._300x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// cover
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#666666").ss(2,2,0,3).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// banner
	this.instance = new lib.banner();
	this.instance.parent = this;
	this.instance.setTransform(150.1,300.1,1,1,0,0,0,0.1,0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(149,299,302,602);
// library properties:
lib.properties = {
	id: '0A6E3F5DF6B342F4AF907DBE848CDF8D',
	width: 300,
	height: 600,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/bgImg.jpg", id:"bgImg"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['0A6E3F5DF6B342F4AF907DBE848CDF8D'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;