(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.bgImg = function() {
	this.initialize(img.bgImg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.dev_24 = function() {
	this.initialize(img.dev_24);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,190,256);


(lib.devs = function() {
	this.initialize(img.devs);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,150,316);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.urText = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AJmCSIACgGIAHABQAEAAACgCIAEgGIgVgvIAHAAIARAnIAPgnIAHAAIgTAwQgDAHgEAEQgDADgGAAQgFAAgEgCgAHGCUIAAg+IAHAAIAAAKQAHgLALABQAIAAAIAGQAGAHAAALQAAALgGAHQgHAGgJAAQgLAAgHgKIAAAYgAHSBhQgFAFAAAIQAAAIAFAFQAFAFAHAAQAGAAAGgFQAEgFAAgIQAAgIgFgFQgEgFgHAAQgHAAgFAFgAJfCRIAAgMIgmAAIgBAMIgGAAIAAgSIAFAAQAGgLAAgWIAAgIIAiAAIAAApIAHAAIgCASgAJEBjQAAARgFALIAZAAIAAgiIgUAAgAIEB/QgHgHAAgKQAAgJAHgIQAHgIAKABQAKgBAHAIQAHAIAAAJQAAAJgHAIQgGAHgLAAQgLAAgGgHgAIJBhQgFAFAAAIQAAAHAFAFQAFAGAHAAQAIAAAEgGQAFgEAAgIQAAgIgFgFQgFgGgHABQgIgBgEAGgAClB/QgHgHAAgKQAAgLAHgGQAHgIAKABQAKAAAIAIIgEAEQgHgGgIAAQgHgBgEAGQgFAFAAAIQAAAIAFAEQAEAGAIAAQAIAAAGgHIAFAEQgIAJgLAAQgLAAgGgHgAgOB/QgHgHAAgKQAAgJAHgIQAIgIAJABQAJgBAIAIQAHAIAAAJQAAAKgHAHQgHAHgKAAQgKAAgHgHgAgJBhQgEAGAAAHQAAAIAFAEQAEAGAHAAQAHAAAFgGQAFgEAAgIQAAgIgFgFQgFgGgHABQgGgBgGAGgAjpB/QgHgHAAgKQAAgJAHgIQAHgIALABQAKgBAHAIQAHAIAAAJQAAAJgHAIQgHAHgLAAQgKAAgHgHgAjkBhQgFAFAAAIQAAAHAFAFQAGAGAHAAQAHAAAFgGQAFgEAAgIQAAgIgFgFQgGgGgHABQgHgBgFAGgAnfCCQgFgEAAgGQAAgIAFgEQAGgEAJAAIAOACIAAgCQAAgFgEgEQgDgDgHAAQgHAAgHADIgCgFQAIgEAJAAQAKAAAFAFQAFAEAAAJIAAAdIgHAAIAAgHQgGAIgLAAQgIAAgEgEgAnaBwQgDAEAAADQAAAFADACQAEACAFABQAHgBAEgDQAEgDAAgGIAAgEIgOgCQgGAAgEACgArMB/QgHgHAAgKQAAgJAHgIQAHgIALABQAKgBAHAIQAHAIAAAJQAAAJgHAIQgHAHgLAAQgKAAgHgHgArHBhQgFAFAAAIQAAAHAFAFQAGAGAHAAQAHAAAFgGQAFgEAAgIQAAgIgFgFQgGgGgHABQgHgBgFAGgAs0B/QgHgHAAgKQAAgLAHgGQAHgIAKABQAKAAAIAIIgEAEQgHgGgIAAQgHgBgEAGQgFAFAAAIQAAAIAFAEQAEAGAIAAQAIAAAGgHIAFAEQgIAJgLAAQgLAAgGgHgAM2CFIAAgKIAIAAIAAAKgAMHCFIAAgvIAXAAQAHAAAEADQAEAFAAAEQAAAHgIAEQALACAAAKQAAAFgFAEQgEADgIAAgAMOB/IAQAAQAFAAADgCQADgCAAgDQAAgDgDgDQgDgCgGAAIgPAAgAMOBqIAPAAQAEAAADgCQACgBAAgEQAAgDgCgCQgCgBgFAAIgPAAgAL3CFIAAgvIAHAAIAAAvgALSCFIAAgoIgRAAIAAgHIApAAIAAAHIgRAAIAAAogAK5CFIgRgVIgJAKIAAALIgHAAIAAgvIAHAAIAAAbIAZgbIAJAAIgUAUIAUAbgAGuCFIAAgoIgaAAIAAAoIgHAAIAAgvIAoAAIAAAvgAFjCFIgPgTIgOATIgIAAIATgXIgSgYIAIAAIAOASIANgSIAIAAIgRAXIASAYgAEsCFIAAglIgcAlIgHAAIAAgvIAHAAIAAAlIAcglIAGAAIAAAvgADyCFIAAgUIgbAAIAAAUIgHAAIAAgvIAHAAIAAAUIAbAAIAAgUIAHAAIAAAvgACQCFIAAgvIAHAAIAAAvgAB/CFIAAgkIgRAYIgRgYIAAAkIgHAAIAAgvIAHAAIARAZIARgZIAHAAIAAAvgAAnCFIAAgvIAWAAQAHAAAEADQAEAEAAAFQAAAHgHAEQAKACAAAKQAAAFgFAEQgEADgIAAgAAuB/IAPAAQAGAAACgCQADgCAAgDQAAgDgDgDQgDgCgGAAIgOAAgAAuBqIAOAAQAFAAACgCQACgBAAgEQAAgDgCgCQgCgBgFAAIgOAAgAgpCFIAAgUIgbAAIAAAUIgHAAIAAgvIAHAAIAAAUIAbAAIAAgUIAHAAIAAAvgAhiCFIAAglIgcAlIgGAAIAAgvIAHAAIAAAlIAbglIAHAAIAAAvgAioCFIAAgoIgRAAIAAgHIAoAAIAAAHIgQAAIAAAogAj7CFIgQgVIgKAKIAAALIgHAAIAAgvIAHAAIAAAbIAZgbIAJAAIgUAUIAUAbgAktCFIAAgvIAHAAIAAAvgAlFCFIAAgUIgbAAIAAAUIgHAAIAAgvIAHAAIAAAUIAbAAIAAgUIAHAAIAAAvgAmUCFIAAgTIgHADIgIABQgIAAgEgEQgEgEAAgGIAAgSIAHAAIAAARQAAAFADACQACACAFAAQAIAAAGgFIAAgVIAHAAIAAAvgAoQCFIAAgvIAXAAQAGAAAFADQAEAFAAAEQAAAHgIAEQAKACAAAKQAAAFgEAEQgEADgJAAgAoJB/IAPAAQAGAAACgCQADgCAAgDQAAgDgDgDQgCgCgGAAIgPAAgAoJBqIAOAAQAFAAACgCQADgBAAgEQAAgDgDgCQgCgBgFAAIgOAAgAonCFIAAglIgcAlIgGAAIAAgvIAHAAIAAAlIAbglIAHAAIAAAvgApcCFIgPgVIgJAJIAAAMIgHAAIAAgMIgKgJIgPAVIgIAAIATgbIgSgUIAIAAIAYAbIAAgbIAHAAIAAAbIAXgbIAJAAIgTAUIAUAbgAroCFIAAgoIgaAAIAAAoIgHAAIAAgvIAoAAIAAAvgAL2BNIAAgJIAIAAIAAAJgACPBNIAAgJIAIAAIAAAJgAktBNIAAgJIAIAAIAAAJgAJ4AmIACgGQADACAEgBQAEAAACgCQACgBACgFIgVguIAIAAIAQAmIAPgmIAIAAIgUAvQgDAHgDAEQgEADgFAAQgGAAgEgCgAJBAoIAAg9IAHAAIAAAKQAHgLALAAQAIABAIAGQAGAHAAAKQAAAKgGAIQgHAGgJAAQgLAAgHgKIAAAYgAJNgKQgFAGAAAGQAAAHAFAGQAGAFAGAAQAGAAAFgFQAFgFAAgIQAAgHgFgFQgEgFgHAAQgHAAgFAFgA0IAoIAAg9IAHAAIAAAKQAHgLAKAAQAJABAHAGQAHAHAAAKQAAAKgHAIQgGAGgKAAQgLAAgGgKIAAAYgAz9gKQgFAFAAAHQAAAIAFAFQAGAFAGAAQAHAAAFgFQAEgFAAgIQAAgHgEgFQgFgFgHAAQgHAAgFAFgAIyAnIAAgOIg0AAIgBAOIgGAAIAAgUIAHAAQAJgRAAgcIAAgLIApAAIAAA4IAJAAIgCAUgAIOgWQAAAOgCAJQgCALgEAHIAjAAIAAgyIgbAAgAmPAlIAAgMIgmAAIgBAMIgGAAIAAgSIAFAAQAGgLAAgVIAAgIIAiAAIAAAoIAHAAIAAABIACAAIADgEIACgFIABgLIABgVIAhAAIAAAuIgHAAIAAgnIgUAAIAAASIgCALQgCAFgCACIgEADIgFABIgBAAIgBALgAmqgIQAAAQgFALIAZAAIAAghIgUAAgARgAZIABgGIADABIADAAIADgEQACgCAAgDIACgLIAAgVIAhAAIAAAuIgHAAIAAgnIgTAAIgBASIgCALQgBAEgDADIgEADIgFABgAQyATQgHgHAAgKQAAgIAHgIQAHgIALAAQAKAAAHAIQAHAGAAAKQAAAKgHAHQgHAHgLAAQgKAAgHgHgAQ3gKQgFAGAAAGQAAAHAFAFQAGAGAHAAQAHAAAFgGQAFgEAAgIQAAgHgFgFQgGgGgHABQgHgBgFAGgAOQATQgHgHAAgKQAAgIAHgIQAIgIAKAAQAJAAAIAIQAHAGAAAKQAAAKgHAHQgHAHgKAAQgLAAgHgHgAOVgKQgEAGAAAGQAAAIAFAEQAEAGAIAAQAHAAAFgGQAFgEAAgIQAAgHgFgFQgFgGgHABQgHgBgGAGgAGLATQgGgGAAgNIABgNIACgHIADgFQABgDADgCIAHgCIAagHIACAHIgaAFQgHADgDADQgCAEgBAHQAGgKANAAQAJAAAHAHQAGAHAAAIQAAALgGAGQgHAHgKAAQgLAAgHgHgAGRgJQgFAFAAAHQAAAHAFAFQAGAFAGAAQAHAAAFgFQAEgFAAgHQAAgHgFgFQgEgFgHAAQgIAAgEAFgAFKATQgHgIAAgJQAAgIAHgIQAHgIAKAAQALABAIAIIgFAEQgGgGgIAAQgHgBgFAGQgFAFAAAHQAAAIAFAEQAGAGAGAAQAIAAAHgHIAEAEQgIAJgLAAQgKAAgHgHgAERATQgHgHAAgKQAAgIAHgIQAIgIAJAAQAKAAAIAIQAGAGAAAKQAAAKgHAHQgGAHgLAAQgLAAgGgHgAEWgKQgFAGAAAGQAAAIAFAEQAFAGAHAAQAHAAAGgGQAEgEAAgIQAAgHgFgFQgEgGgIABQgHgBgFAGgAAAAZIABgGIADABIADAAIADgEIACgFIACgLIAAgVIAhAAIAAAuIgHAAIAAgnIgTAAIgBASIgCALQgBAFgCACIgFADIgFABgAgtATQgGgGAAgLQAAgKAHgGQAHgIAKAAQAKAAAHAIQAHAIAAAIQAAAJgHAIQgHAHgKAAQgLAAgHgHgAgogKQgEAGAAAGQAAAIAFAEQAEAGAIAAQAHAAAFgGQAFgEAAgIQAAgHgFgFQgFgGgHABQgHgBgGAGgAjOATQgHgGAAgLQAAgKAHgGQAHgIAKAAQAKAAAHAIQAHAIAAAIQAAAJgHAIQgHAHgKAAQgLAAgGgHgAjJgKQgFAFAAAHQAAAIAFAEQAFAGAHAAQAIAAAEgGQAFgFAAgHQAAgGgFgGQgFgGgHABQgIgBgEAGgAqfAZIABgGIADABIADAAIADgEQACgCAAgDIACgLIAAgVIAhAAIAAAuIgHAAIAAgnIgTAAIgBASIgCALQgBAEgDADIgEADIgFABgAvLAUQgGgHAAgLQAAgJAGgHQAHgIAJAAQAKAAAGAIQAGAHAAAJIgBACIgkAAQAAAHAFAFQAFAEAGAAQAIAAAHgGIAEADQgHAJgMAAQgKAAgHgGgAusAAQgBgHgEgEQgDgFgHABQgGgBgEAFQgEAEgBAHIAeAAIAAAAgAwsAWQgFgEAAgGQAAgIAGgEQAFgDAJAAIAOACIAAgCQAAgFgDgEQgEgDgGAAQgIAAgGADIgDgFQAIgEAJAAQAKAAAFAFQAFAEAAAJIAAAcIgHAAIAAgHQgGAIgKAAQgIAAgFgEgAwmAEQgEAEAAADQAAAFAEACQADACAFABQAHgBAEgDQAFgEAAgFIAAgEIgOgCQgGAAgEACgAyaATIADgFQAHAGAJAAQAFAAADgCQADgCAAgEQAAgDgDgDQgEgCgEAAIgHAAIAAgFIAHAAQAFAAACgCQADgBAAgFQAAgDgDgBQgCgCgFAAQgJAAgFAEIgEgEQAIgHAKAAQAJABAEADQAEAEAAAFQAAAHgHADQAIADAAAIQAAAHgFADQgEAEgJAAQgMAAgHgHgAVEAZIAAgkIgbAkIgHAAIAAguIAHAAIAAAkIAcgkIAGAAIAAAugAURAZIAAguIAHAAIAAAugAT5AZIAAgVIgbAAIAAAVIgHAAIAAguIAHAAIAAAUIAbAAIAAgUIAHAAIAAAugASzAZIAAgnIgQAAIAAgHIAoAAIAAAHIgRAAIAAAngASXAZIAAguIAHAAIAAAugAQXAZIAAgVIgbAAIAAAVIgHAAIAAguIAHAAIAAAUIAbAAIAAgUIAHAAIAAAugAPGAZIAAguIAWAAQAHAAAEADQAEAFAAAEQAAAHgHADQAKACAAAKQAAAFgFAEQgEADgIAAgAPNATIAPAAQAFAAADgCQADgCAAgDQAAgDgDgDQgDgCgGAAIgOAAgAPNgBIAOAAQAFAAACgCQACgBAAgEQAAgDgCgCQgCgBgFAAIgOAAgAN0AZIAAgnIgaAAIAAAnIgHAAIAAguIAoAAIAAAugAKqAZIAAguIAfAAIAAAHIgYAAIAAAngAHRAZIAAgKIAIAAIAAAKgAG/AZIAAgKIAJAAIAAAKgAF2AZIAAguIAHAAIAAAugADjAZIgPgTIgOATIgIAAIASgXIgRgXIAIAAIANASIAOgSIAIAAIgSAWIATAYgACyAZIAAguIAGAAIAAAugACZAZIAAgVIgaAAIAAAVIgHAAIAAguIAHAAIAAAUIAaAAIAAgUIAHAAIAAAugABUAZIAAgnIgRAAIAAgHIAoAAIAAAHIgQAAIAAAngAA4AZIAAguIAHAAIAAAugAhIAZIAAgVIgbAAIAAAVIgHAAIAAguIAHAAIAAAUIAbAAIAAgUIAHAAIAAAugAiZAZIAAguIAWAAQAIAAADADQAFAFAAAEQAAAHgIADQAKACAAAKQAAAFgFAEQgEADgIAAgAiSATIAPAAQAGAAACgCQADgCAAgDQAAgDgDgDQgDgCgGAAIgOAAgAiSgBIAOAAQAFAAACgCQADgBAAgEQAAgDgDgCQgCgBgFAAIgOAAgAjqAZIAAgnIgbAAIAAAnIgHAAIAAguIApAAIAAAugAk4AZIAAgRIgNAAIgNARIgJAAIAPgSQgGgCgDgDQgEgCAAgGQAAgGAFgEQAFgFAIAAIAWAAIAAAugAlPgMQgDACAAAFQAAAEADABQAEACAEABIAPAAIAAgRIgPAAQgEgBgEADgAnnAZIAAgkIgcAkIgHAAIAAguIAHAAIAAAkIAcgkIAHAAIAAAugAoYAZIgQgVIgKAKIAAALIgHAAIAAguIAHAAIAAAaIAagaIAIAAIgTAUIAUAagApoAZIAAguIAHAAIAAASIAMAAQAIAAAFADQAGAEAAAGQAAAHgFAEQgFAEgIAAgAphATIAMAAQAFAAAEgDQADgCAAgEQAAgDgDgDQgEgCgFAAIgMAAgAqoAZIAAguIAHAAIAAAugArNAZIAAgnIgQAAIAAgHIAoAAIAAAHIgRAAIAAAngAsKAZIAAgkIgcAkIgHAAIAAguIAHAAIAAAkIAcgkIAHAAIAAAugAtEAZIAAgkIgbAkIgHAAIAAguIAHAAIAAAkIAcgkIAGAAIAAAugAt+AZIAAgVIgaAAIAAAVIgHAAIAAguIAHAAIAAAUIAaAAIAAgUIAHAAIAAAugAvgAZIAAgTIgIADIgIABQgHAAgEgEQgEgEAAgFIAAgSIAHAAIAAARQAAAEACACQACACAFAAQAIAAAHgEIAAgVIAHAAIAAAugAxFAZIAAgVIgbAAIAAAVIgGAAIAAguIAGAAIAAAUIAbAAIAAgUIAHAAIAAAugAytAZIAAgkIgbAkIgHAAIAAguIAHAAIAAAkIAbgkIAHAAIAAAugA0gAZIAAg4IgjAAIAAA4IgHAAIAAg+IAxAAIAAA+gALpACIAAgGIBFAAIAAAGgAUugeQgDgDgBgFIAFgBQABAGAGAAQAHAAABgGIAFABQgBAFgDADQgDADgGAAQgFAAgDgDgAshgeQgDgDgBgFIAFgBQACAGAGAAQAGAAACgGIAEABQgBAFgDADQgDADgFAAQgFAAgEgDgAURgfIAAgIIAIAAIAAAIgASXgfIAAgIIAIAAIAAAIgAF2gfIAAgIIAIAAIAAAIgACxgfIAAgIIAIAAIAAAIgAA3gfIAAgIIAIAAIAAAIgAqpgfIAAgIIAIAAIAAAIgAQRhDIAAg+IAHAAIAAAKQAHgLAKAAQAJABAHAGQAHAHAAALQAAAKgHAIQgGAGgKAAQgLAAgGgKIAAAYgAQch2QgFAFAAAIQAAAIAFAFQAGAFAGAAQAHAAAFgFQAEgFAAgIQAAgIgEgFQgFgFgHAAQgHAAgFAFgAFwhDIAAg+IAHAAIAAAKQAIgLAKAAQAIABAIAGQAGAHAAALQAAALgGAHQgHAGgJAAQgLAAgHgKIAAAYgAF8h2QgFAFAAAIQAAAIAFAFQAFAFAHAAQAGAAAGgFQAEgFAAgIQAAgIgEgFQgFgFgHAAQgHAAgFAFgADjhFIACgGIAHABQAEAAABgCQACgBADgFIgVgvIAHAAIARAnIAPgnIAHAAIgTAwQgDAHgEAEQgDADgGAAQgFAAgEgCgAwahDIAAg+IAHAAIAAAKQAIgLAKAAQAIABAIAGQAGAHAAALQAAALgGAHQgHAGgJAAQgLAAgHgKIAAAYgAwOh2QgFAFAAAIQAAAIAFAFQAFAFAHAAQAHAAAFgFQAEgFAAgIQAAgIgEgFQgFgFgHAAQgHAAgFAFgAPOhGIAAgMIgmAAIgBAMIgGAAIAAgSIAFAAQAGgLAAgWIAAgIIAiAAIAAApIAHAAIgCASgAOzh0QAAARgFALIAZAAIAAgiIgUAAgAL1hGIAAgMIglAAIgCAMIgFAAIAAgSIAFAAQAGgLAAgWIAAgIIAhAAIAAApIAHAAIAAABIACAAIADgEIACgFIACgMIAAgVIAhAAIAAAvIgHAAIAAgoIgTAAIgBATIgCALQgBAFgCACIgEADIgFABIgBAAIgBALgALbh0QAAARgGALIAZAAIAAgiIgTAAgAoYhXQgIAGgMAAQgOAAgJgKQgJgIAAgOQAAgNAJgLQAJgJAOAAQAOAAAJAJQAJALAAANQAAALgHAJIAIAIIgFAFgAo+iEQgHAIAAALQAAAKAHAIQAHAIALAAQAIAAAHgFIgMgKIAFgGIALALQAGgHAAgJQAAgLgHgIQgIgHgKAAQgLAAgHAHgAROhYQgHgGAAgLQAAgLAHgGQAHgIAKAAQALAAAHAIQAHAIAAAJQAAAJgHAIQgHAHgLAAQgKAAgHgHgARTh2QgFAGAAAHQAAAIAFAEQAFAGAHAAQAHAAAGgGQAEgEAAgIQAAgIgFgFQgEgGgIABQgHgBgFAGgAPbhYQgHgHAAgKQAAgJAHgIQAIgIAKAAQAJAAAIAIQAHAGAAALQAAAKgHAHQgHAHgKAAQgLAAgHgHgAPgh2QgEAGAAAHQAAAIAFAEQAEAGAIAAQAHAAAFgGQAFgEAAgIQAAgIgFgFQgFgGgHABQgHgBgGAGgAN0hYIAEgFQAHAGAIAAQAGAAACgCQAEgCAAgEQAAgDgDgDQgEgCgFAAIgGAAIAAgGIAGAAQAFAAADgCQADgBAAgFQAAgDgDgBQgDgCgFAAQgIAAgGAEIgDgEQAHgHALAAQAIABAEADQAFAEAAAFQAAAHgIAEQAJADAAAIQAAAHgFADQgEAEgKAAQgLAAgIgHgAHfhYIADgFQAHAGAJAAQAFAAADgCQADgCAAgEQAAgDgDgDQgEgCgFAAIgGAAIAAgGIAHAAQAFAAACgCQADgBAAgFQAAgDgDgBQgCgCgFAAQgJAAgFAEIgEgEQAIgHAKAAQAIABAFADQAEAEAAAFQAAAHgHAEQAIADAAAIQAAAHgFADQgEAEgJAAQgMAAgHgHgAEZhYQgHgHAAgKQAAgLAHgGQAHgIAKAAQAKABAIAIIgEAEQgHgGgIAAQgHgBgEAGQgFAFAAAIQAAAIAFAEQAEAGAIAAQAIAAAGgHIAEAEQgHAJgLAAQgLAAgGgHgACfhYQgHgGAAgLQAAgLAGgGQAHgHAKgBQAMABAHAIIgEAEQgGgGgIAAQgGgBgGAFQgFAFAAAFIAVAAIAAAGIgVAAQAAAGAFAFQAGAFAGAAQAIAAAGgHIAFAEQgEAEgFADQgEACgGAAQgLAAgGgHgABthVQgFgEAAgGQAAgIAFgEQAGgEAJAAIAOACIAAgCQAAgFgEgEQgDgDgHAAQgHAAgHADIgCgFQAIgEAJAAQAKAAAFAFQAFAEAAAJIAAAdIgHAAIAAgHQgGAIgLAAQgIAAgEgEgAByhnQgDADAAAEQAAAFADACQAEACAFABQAHgBAEgDQAEgEAAgFIAAgEIgOgCQgGAAgEACgAAHhXQgGgFgBgLIgJAAIAAAVIgHAAIAAgvIAHAAIAAAVIAJAAQABgJAGgGQAGgHAKAAQAKAAAGAIQAHAGAAALQAAALgHAGQgFAHgLAAQgKAAgGgGgAALh2QgEAFAAAIQAAAIAEAFQAFAFAHAAQAHAAAEgFQAFgFAAgIQAAgHgFgGQgEgFgHAAQgHAAgFAFgAhHhSIgHAAIgQgVIgKAKIAAALIgHAAIAAgvIAHAAIAAAbIAagbIAIAAIgTAUIASAYIAAgDIAEABIADAAIADgEIACgFIACgcIAAgFIAhAAIAAAvIgHAAIAAgoIgTAAIgBATIgCALQgCAFgCACIgEADIgFABgAkehXQgHgHAAgLQAAgKAGgHQAHgIAJAAQAKAAAGAIQAGAHAAAKIAAACIglAAQABAHAEAFQAGAEAFAAQAJAAAGgHIAEAEQgHAJgMAAQgKAAgGgGgAkAhsQAAgHgEgEQgEgFgHABQgGgBgEAFQgEAEgBAHIAeAAIAAAAgAmzhbIAEgFQAGAEAFACQAEADAHAAQAHAAADgEQAEgCAAgGQAAgEgDgCQgEgEgJgCQgMgCgEgEQgFgDAAgJQAAgGAFgGQAHgFAIAAQAMAAAKAIIgEAGQgIgIgKABQgGAAgEACQgDADAAAFQAAAFADADQAEACAKACQAKACAFAEQAFAFAAAHQAAAJgGAEQgFAFgKAAQgOAAgMgKgAn2hbQgJgIAAgOQAAgNAJgLQAJgJAOAAQAOAAAJAJQAJALAAANQAAANgJAJQgJAKgOAAQgOAAgJgKgAnxiEQgHAIAAALQAAALAIAHQAHAIAKAAQALAAAHgIQAHgHAAgLQAAgMgHgHQgHgHgLAAQgKAAgIAHgAtRhVQgFgEAAgGQAAgIAGgEQAFgEAJAAIAOACIAAgCQAAgFgDgEQgEgDgHAAQgHAAgHADIgCgFQAIgEAJAAQAKAAAFAFQAFAFAAAIIAAAdIgHAAIAAgHQgGAIgLAAQgHAAgFgEgAtLhnQgEADAAAEQAAAFAEACQADACAFABQAHgBAEgDQAEgEAAgFIAAgEIgNgCQgGAAgEACgAujhYQgHgHAAgKQAAgLAHgGQAHgIAKAAQAKABAJAIIgFAEQgHgGgHAAQgHgBgFAGQgFAFAAAIQAAAIAFAEQAFAGAHAAQAIAAAGgHIAFAEQgIAJgLAAQgKAAgHgHgAxPhYQgHgHAAgKQAAgJAHgIQAHgIALAAQAKAAAHAIQAHAIAAAJQAAAJgHAIQgHAHgLAAQgKAAgHgHgAxKh2QgFAFAAAIQAAAHAFAFQAGAGAHAAQAHAAAFgGQAFgEAAgIQAAgHgFgGQgGgGgHABQgHgBgFAGgATyhSIAAgKIAJAAIAAAKgATihSIAAgRIgNAAIgNARIgIAAIAOgSQgGgCgDgDQgEgEAAgFQAAgGAFgEQAFgFAIAAIAWAAIAAAvgATLh4QgDACAAAFQAAAEAEACQADACAFABIAOAAIAAgSIgPAAQgEgBgEADgASDhSIAAgvIAXAAQAHAAAEADQAEAEAAAFQAAAHgIAEQAKACAAAKQAAAFgEAEQgEADgIAAgASKhYIAQAAQAFAAACgCQADgCAAgDQAAgDgDgDQgCgCgGAAIgPAAgASKhtIAOAAQAFAAACgCQADgBAAgEQAAgDgDgCQgCgBgEAAIgPAAgANMhSIAAgRIgNAAIgMARIgJAAIAOgSQgFgCgEgDQgDgDAAgGQAAgGAEgEQAGgFAHAAIAWAAIAAAvgAM2h4QgDACAAAFQAAAEADACQADACAFABIAOAAIAAgSIgOAAQgFgBgDADgAKdhSIAAglIgbAlIgHAAIAAgvIAHAAIAAAlIAbglIAHAAIAAAvgAJthSIgRgVIgJAKIAAALIgHAAIAAgvIAHAAIAAAbIAZgbIAJAAIgUAUIAUAbgAI1hSIAAglIgcAlIgHAAIAAgvIAHAAIAAAlIAcglIAHAAIAAAvgAHMhSIAAglIgcAlIgGAAIAAgvIAHAAIAAAlIAbglIAHAAIAAAvgAFEhSIAAgvIAHAAIAAAvgABahSIAAgTIgIADIgIABQgHAAgEgEQgEgDAAgHIAAgSIAHAAIAAARQAAAFACACQACACAFAAQAIAAAHgFIAAgVIAGAAIAAAvgAiGhSIAAglIgcAlIgGAAIAAgvIAHAAIAAAlIAbglIAHAAIAAAvgAjXhSIAAgvIAWAAQAHAAAEADQAEAFAAAEQAAAHgIAEQALACAAAKQAAAFgFAEQgEADgIAAgAjRhYIAQAAQAFAAADgCQADgCAAgDQAAgDgDgDQgDgCgGAAIgPAAgAjRhtIAPAAQAEAAADgCQACgBAAgEQAAgDgCgCQgCgBgFAAIgPAAgAk6hSIAAgVIgaAAIAAAVIgHAAIAAgvIAHAAIAAAUIAaAAIAAgUIAHAAIAAAvgApkhSIAAg/IAHAAIAAA/gAqShSIAAgRIgNAAIgNARIgJAAIAPgSQgGgCgDgDQgEgDAAgGQAAgGAFgEQAFgFAIAAIAWAAIAAAvgAqph4QgDACAAAFQAAAEADACQAEACAEABIAPAAIAAgSIgPAAQgFgBgDADgArIhSIAAgVIgbAAIAAAVIgHAAIAAgvIAHAAIAAAUIAbAAIAAgUIAHAAIAAAvgAsBhSIAAgVIgbAAIAAAVIgHAAIAAgvIAHAAIAAAUIAbAAIAAgUIAHAAIAAAvgAtshSIAAgoIgRAAIAAgHIAoAAIAAAHIgQAAIAAAogAu+hSIAAglIgcAlIgGAAIAAgvIAHAAIAAAlIAbglIAHAAIAAAvgAxhhSIgQgVIgKAKIAAALIgHAAIAAgvIAHAAIAAAbIAZgbIAJAAIgUAUIAUAbgAyZhSIAAglIgcAlIgGAAIAAgvIAGAAIAAAlIAcglIAHAAIAAAvgAz0hSIAAg/IAbAAQALAAAGAGQAEAEAAAGQAAAKgKAFQANADAAAMQAAAIgGAFQgGAEgLAAgAzthYIAWAAQAHgBAEgDQAEgCAAgGQAAgFgEgDQgFgCgIgBIgUAAgAzth1IATAAQAGAAAFgDQAEgDAAgGQAAgEgEgDQgEgCgGgBIgUAAgASxh5IACgYIAJAAIAAAAIgHAYgAFEiLIAAgIIAIAAIAAAIg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.urText, new cjs.Rectangle(-135.5,-14.7,271.1,29.5), null);


(lib.t2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACjAnQgPgQAAgXQAAgVAPgQQAQgQAYAAQAXAAAQAQQAPAPAAAWQAAAXgPAPQgQAQgYAAQgXAAgQgPgACxgZQgKALAAAOQAAAQAKALQAKALAQAAQAPAAAKgLQAKgLAAgQQAAgOgKgLQgKgLgQAAQgPAAgKALgAqRAnQgPgPAAgYQAAgVAPgQQAQgQAXAAQAXAAASAOIgMAOQgNgLgQAAQgPAAgKALQgKALAAAOQAAARAKAKQAKALAQAAQAPAAALgIIAAgUIgbAAIAAgPIAsAAIAAArQgSAQgZAAQgZAAgPgPgAsPAnQgQgQAAgXQAAgVAQgQQAQgQAYAAQAXAAAQAQQAPAPAAAWQAAAXgPAPQgQAQgYAAQgYAAgPgPgAsBgZQgKALAAAOQAAAQAKALQAKALAQAAQAPAAAKgLQAKgLAAgQQAAgOgKgLQgKgLgQAAQgPAAgKALgAHgA1IgahKIgaBKIgQAAIglhoIAUAAIAZBNIAahOIAQAAIAaBOIAZhNIATAAIglBogANsA1IAAgVIAUAAIAAAVgAMBA1IAAhoIAnAAQAZAAAQAPQAPAPAAAVQAAAXgPAPQgQAPgZAAgAMUAkIAUAAQARAAAKgKQAKgKAAgQQAAgOgKgKQgKgKgRAAIgUAAgALWA1IgaglIgXAAIAAAlIgSAAIAAhoIAvAAQASAAAKAJQALAJAAAPQAAAYgZAHIAcAogAKlAAIAbAAQAWAAAAgRQAAgRgWAAIgbAAgAJrA1IgLgaIgyAAIgKAaIgTAAIAuhpIARAAIAuBpgAJZALIgSgpIgSApIAkAAgAFaA1IgaglIgXAAIAAAlIgSAAIAAhoIAvAAQASAAAKAJQALAJAAAPQAAAYgZAHIAcAogAEpAAIAbAAQAWAAAAgRQAAgRgWAAIgbAAgAA1A1IAAhoIBOAAIAAARIg7AAIAAAcIA1AAIAAAQIg1AAIAAArgAggA1IAAgVIAUAAIAAAVgAhHA1IgaglIgXAAIAAAlIgTAAIAAhoIAvAAQATAAAKAJQAKAJAAAPQAAAYgZAHIAdAogAh4AAIAbAAQAKAAAGgEQAFgFAAgIQAAgRgVAAIgbAAgAjuA1IAAhoIBOAAIAAAQIg7AAIAAAcIA0AAIAAAPIg0AAIAAAcIA8AAIAAARgAkdA1IAAgtIgyAAIAAAtIgSAAIAAhoIASAAIAAArIAyAAIAAgrIATAAIAABogAmrA1IAAhXIghAAIAAgRIBVAAIAAARIghAAIAABXgAooA1IAAhoIBOAAIAAAQIg7AAIAAAcIA1AAIAAAPIg1AAIAAAcIA8AAIAAARgAteA1IAAhXIghAAIAAgRIBVAAIAAARIghAAIAABXg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t2, new cjs.Rectangle(-89.5,-5.4,179.1,10.9), null);


(lib.t1_2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AqkBiQgUgKgLgSIASgNQAVAfAogBQAYABAPgMQAPgNAAgRQAAgTgOgIQgOgKgVAAIgTAAIAFgTIAVAAQAdAAAQgMQASgKAAgUQAAgPgMgKQgMgJgUAAQgcAAgbAUIgNgQQAfgaAnAAQAdAAATAPQATAPAAAXQAAAXgQAOQgQAPgdADQATAGAKALQALALAAATQAAAagXASQgXARgiABQgcAAgTgLgAJ1BpIAtisIirCsIgWAAIA4jRIAYAAIguCsICrisIAWAAIg4DRgAGcBpIg0hoIg9AyIgOA2IgYAAIA4jRIAYAAIghB8ICWh8IAiAAIhxBcIA8B1gADJBpIguhmIg3AuIgPA4IgYAAIAPg6IgdgtIhiBnIggAAIB2h5Ig2hYIAaAAIBNB8IAhh8IAYAAIghB5ICMh5IAgAAIhpBbIA1B2gAiMBpIAtisIirCsIgWAAIA4jRIAYAAIguCsICrisIAWAAIg4DRgAl3BpIAaheIh4AAIgZBeIgYAAIA4jRIAYAAIgZBdIB4AAIAZhdIAYAAIg5DRg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1_2, new cjs.Rectangle(-70.8,-10.8,141.6,21.7), null);


(lib.t1_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AB7CdIANguIinAAIgPAuIgVAAIAShEIAUAAQAsgwAaheIANgtICHAAIgzC7IAcAAIgWBEgAA7gjQgKAlgQAiQgSAjgQASIBzAAIAtimIhYAAgAwgCdIANguIioAAIgPAuIgVAAIAShEIAUAAQAtgwAaheIANgtICHAAIgzC7IAcAAIgWBEgAxggjQgKAlgQAiQgSAjgRASIB0AAIAtimIhYAAgAJuBoQgTgKgMgSIATgNQAVAeAnAAQAYAAAQgMQAPgMAAgRQAAgTgPgJQgOgJgVAAIgSAAIAFgTIAVAAQAcAAARgMQASgLAAgTQAAgQgNgJQgMgJgTAAQgdAAgaAUIgOgQQAggaAmAAQAdAAATAPQAUAOAAAYQAAAXgRAOQgQANgcAFQASAGALALQALALAAASQAAAbgXASQgYARgiAAQgbAAgUgKgAF9BpIAPgTQAKAHAPAAQAZAAAYggIgxifIAaAAIApCIIBniIIAcAAIh+ClQgkAvgmAAQgZAAgNgJgAo4BpIAPgTQAKAHAPAAQAZAAAYggIgxifIAaAAIApCIIBniIIAcAAIh+ClQgkAvgmAAQgZAAgNgJgASPBvIAuipIhqBvIgCAAIguhvIgtCpIgYAAIA5jRIAWAAIAtBxIBrhxIAbAAIg5DRgAOQBvIAWhQIg5AAIhPBQIgfAAIBVhUQgrgLAAgpQAAgiAbgUQAbgTAvAAIBTAAIg5DRgANVg/QgUAOAAAYQAAASANAIQANAKAXAAIA5AAIAYhYIg2AAQgkAAgUAOgADIBvIA5jRIBCAAQAoAAAUATQAPAQAAAXQAAAkgdAUQgbAUgwAAIgyAAIgUBLgAD6APIAtAAQAmAAAUgOQAUgNAAgaQAAgQgKgJQgMgNgdAAIgvAAgAjJBvIAuisIirCsIgXAAIA5jRIAXAAIguCrICrirIAXAAIg5DRgArtBvIA5jRIBCAAQAoAAAUATQAPAQAAAXQAAAkgdAUQgbAUgwAAIgyAAIgUBLgAq7APIAtAAQAmAAAUgOQAUgNAAgaQAAgQgKgJQgMgNgdAAIgvAAgAsqBvIgJg4IhzAAIgnA4IgbAAICZjTIAXAAIAnDTgAs3AiIgThrIhNBrIBgAAgAjsh/QgJgJgBgRIAQgDQADAVATAAQALAAAIgGQAJgFAEgKIAQADQgGARgNAJQgNAKgRAAQgRAAgKgKg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1_1, new cjs.Rectangle(-124.8,-15.7,249.6,31.5), null);


(lib.logo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhwByIglgkIh3AAQgcAAgTgFQgYgGgOgNQgTgTAAgjIAAhlQgBgHAGgFQAEgEAIAAICDAAQAdAAASAGQAZAEAOAOQASARABAlIAABkIAdAeQAEAEABAGQgBAGgFAFQgFAFgGAAQgGAAgEgDgAlTAAQABAZANAMIABABQANAKAaACICEAAIAAhZQgBgZgLgMIgDgCQgMgKgbgBIiEAAgAEoBNQglgBgRgLQgMgIgDgPIAAgEQABgGAEgEQAFgDAFAAQAHAAAFADQADADACAEIABADQAFAGAHADQAIADAPAAIBHAAQAnAAAMgGQAFgCACgHQACgFABgJIAAgCQgBgOgFgFQgKgHgZAAIhgAAQghABgOgMQgNgNAAgaIAAgMQAAgXARgMQAVgMA1gBIA0AAQAqAAASALQAPAJACAQIAAADQAAAGgDADQgGAFgGAAQgGAAgFgEQgEgCgBgEIgBgDQgFgIgMgCQgJgCgYgBIg1AAQghAAgKAGQgKAEAAAQIAAAHQAAAMAGAGQAIAFAWAAIBSAAQAoAAARAJQAWAMAAAiQAAAlgeAMQgRAHgmAAgAAgBNQguAAgYgOQghgRAAguIAAgnQAAgvAhgSQAYgNAuAAIAtAAQAvAAAYANQAgASAAAvIAAAnQAAAuggARQgYAOgvAAgAgVhQQgRANAAAdIAAAmQAAAcARAMQAOAKAdAAIBAAAQAeAAAPgKQARgMAAgcIAAgmQAAgdgRgNQgPgKgeAAIhAAAQgdAAgOAKgAnFBJQgFgFAAgHIAAihQAAgIAFgDQAEgGAHAAQAIAAAEAGQAEADABAIIAAChQgBAHgEAFQgEAEgIAAQgHAAgEgEg");
	this.shape.setTransform(2.6,0.5,1,1,0,0,0,0.6,0);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.logo, new cjs.Rectangle(-43.9,-11.2,91.8,23.5), null);


(lib.dev_24_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Aj2F6QgeAVgigBQgoAAgagZQgagbAAgnQAAggAQgdQAPgdAdgSQAdgSAhAAQApAAAZAaQAaAaAAAnQAAAbgLAYQgLAYgTATIAVAXIgTAOgAlKDaQgXAPgMAYQgMAXAAAaQAAAeATAVQATAUAegBQAbAAAWgPIghgmIATgOIAfAnQAeggAAgrQAAgfgSgTQgTgUgfAAQgbAAgWAPgAh+F1QgagbAAgnQAAggAQgdQAPgdAdgSQAdgSAhAAQAoAAAZAaQAaAaAAAnQAAAhgQAcQgPAdgdASQgbATgigBQgoAAgagZgAhQDaQgXAPgMAYQgMAXAAAaQAAAeATAVQATAUAegBQAbAAAXgPQAUgPANgXQAMgYAAgaQAAgfgSgTQgSgUgfAAQgbAAgWAPgABKFmIASgPQAbAiAqgBQAXAAAPgLQAQgLAAgRQAAgMgKgJQgKgIgYgKQgggMgMgMQgNgMAAgUQAAgaAVgRQAWgSAiAAQAvABAcAgIgSAPQgYgagjAAQgXAAgOALQgNAKAAAQQAAANAKAHQAKAIAaAKQAcALANANQANAMAAAUQAAAcgWARQgXATgigBQg6AAgcgngALDGKIANgxIhtAAIgDgSICciQIAWAAIgmCOIAhAAIgFAUIghAAIgNAxgAJ/FFIBXAAIAchrgAIWGKIAJgfIAbAAIgIAfgAFYGKIAFgSIB4hbQATgOAIgMQAIgLAAgNQAAgOgLgJQgKgJgTAAQgdAAgcAdIgQgPQAhgkApAAQAcAAASAPQASAPAAAXQAAASgLAPQgLAPgXARIhhBKIBwAAIgGAVgAn7GKIA4jRIAYAAIg5DRgAqVGKIgJg3IhzAAIgnA3IgbAAICZjTIAXAAIAnDTgAqiE+IgThsIhNBsIBgAAgAuUGKIAZheIh3AAIgaBeIgXAAIA4jRIAYAAIgZBdIB3AAIAZhdIAYAAIg4DRgAO6FpIAQg9Ig+AAIAGgWIA+AAIAQg+IAXAAIgRA+IA+AAIgFAWIg+AAIgRA9gAEtgCQgngsAAhJQAAgxAQgyQARgyAbglQAcgmAqgZQAqgYAuABQBFgBAnAuQAnAsAABJQAAAxgQAxQgQAxgdAmQgcAngpAXQgpAYgvAAQhFAAgngsgAGJk6QgnAigVA1QgWA1AAA3QAAA0AaAhQAbAiAwgBQAsABAngjQAngiAWg0QAWg0AAg4QAAg1gbgiQgbgggwgBQgsAAgnAjgAiAgCQgngsAAhJQAAgxAQgyQARgyAbglQAcgmAqgZQApgYAuABQBFgBAnAuQAnAsAABJQAAAxgQAxQgQAxgdAmQgcAngpAXQgpAYguAAQhFAAgngsgAgkk6QgnAigVA1QgWA1AAA3QAAA0AaAhQAbAiAwgBQArABAngjQAngiAWg0QAWg0AAg4QAAg1gbgiQgbgggwgBQgsAAgmAjgApLAiIAKgjIDxi3QAmgdAPgWQARgWAAgaQAAgcgWgTQgUgRgmAAQg7AAg4A6IgggeQBDhIBSABQA3AAAkAdQAkAcAAAvQAAAkgWAfQgWAeguAjIjCCSIDhAAIgMAqgAsQh4IANgxICnAAIgMAxgALJjdQgNgDgJgKQgJgKAAgMQAAgSARgOIgVAAIADgTIB/AAIgDATIhHAAQgWALAAAPQAAATAjAAQAZAAATgJIgEAaQgVAJgYAAQgQgBgNgDgAKrlAIADgTIBNAAQAPgJAAgMQAAgSghAAQgYAAgSAIIAEgaQARgGAagBQAZAAAQAKQARAKAAATQAAAOgNALIASAAIgDATg");
	this.shape.setTransform(2,181.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Слой_1
	this.instance = new lib.dev_24();
	this.instance.parent = this;
	this.instance.setTransform(-83,-148);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.dev_24_1, new cjs.Rectangle(-104,-148,212.1,369.9), null);


(lib.dev_3duo_text = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Al5F7QgdAUgjAAQgoAAgagaQgagbAAgmQAAghAQgcQAQgdAdgTQAcgSAiAAQApAAAZAaQAaAbAAAmQAAAbgLAYQgLAZgUATIAVAXIgSANgAnNDaQgWAQgMAXQgNAYAAAaQAAAeATAVQATATAfAAQAaAAAXgPIghgnIATgNIAeAmQAfgfAAgrQAAgfgTgUQgSgTggAAQgagBgXAPgAPqF1QgagbAAgmQAAghAQgcQAQgdAdgTQAcgSAiAAQApAAAZAaQAaAbAAAmQAAAigQAcQgQAdgcASQgdASgiAAQgoAAgagagAQYDaQgWAQgMAXQgNAYAAAaQAAAeATAVQATATAfAAQAbAAAWgPQAWgPANgYQAMgXAAgaQAAgfgTgUQgSgTggAAQgagBgXAPgAkBF1QgagbAAgmQAAghAQgcQAQgdAdgTQAcgSAiAAQApAAAZAaQAaAbAAAmQAAAigQAcQgQAdgcASQgdASgiAAQgoAAgagagAjTDaQgWAQgMAXQgNAYAAAaQAAAeATAVQATATAfAAQAbAAAWgPQAWgPANgYQAMgXAAgaQAAgfgTgUQgSgTggAAQgagBgXAPgAMAF8QgUgSAAgfQAAgQAEgRIAehxIAYAAIggB4QgDAKAAAOQAAAVAOAOQAPANAagBQAcAAATgSQATgVAIgfIAgh5IAYAAIghB9QgLAogWAXQgbAZgnAAQgkAAgUgSgAD5GEQgSgLgKgTIATgMQARAfAnAAQAYAAARgNQAQgNAAgUQAAgSgOgJQgOgJgaAAIgJAAIgDgOIBVhLIhoAAIAGgVICJAAIgFASIhVBKQAZADAQANQAQANAAAXQAAAdgYAUQgZAVgjgBQgbABgSgLgAg3FmIASgOQAaAhAqAAQAWAAAQgLQAPgMAAgQQAAgMgJgJQgJgIgZgKQgfgMgMgMQgOgNAAgTQAAgaAVgSQAWgRAiAAQAvAAAbAgIgRAQQgYgagkAAQgWgBgOALQgOALAAAQQAAANAKAGQAKAJAbAKQAcAKANAOQANALAAAUQAAAcgXASQgXASgiAAQg4AAgcgogAHzGLIA4jSIAzAAQA1AAAdAcQAXAWAAAmQAAAxghAhQgoAohEAAgAIRF1IAsAAQA2AAAhghQAagbAAgmQAAgdgSgSQgVgVgqAAIggAAgAp+GLIA5jSIAXAAIg4DSgAsXGLIgKg3IhyAAIgoA3IgaAAICYjTIAXAAIAnDTgAslE/IgThsIhMBsIBfAAgAwXGLIAaheIh4AAIgZBeIgYAAIA4jSIAYAAIgZBdIB4AAIAZhdIAYAAIg5DSgAE7gBQgngsAAhJQAAgyAQgxQARgzAcglQAcgmApgYQAqgYAvAAQBFAAAnAtQAnAtAABIQAAAygRAxQgQAwgcAnQgcAngqAWQgpAZgvAAQhFgBgngrgAGYk6QgnAjgWA1QgWA1AAA3QAAAzAbAiQAaAhAwAAQAsAAAogiQAmgiAWg1QAWg0AAg4QAAg1gaghQgbghgwAAQgsAAgnAigAhygBQgngsAAhJQAAgyAQgxQARgzAcglQAcgmApgYQApgYAvAAQBFAAAnAtQAnAtAABIQAAAygRAxQgQAwgcAnQgcAngqAWQgpAZguAAQhFgBgngrgAgVk6QgnAjgWA1QgWA1AAA3QAAAzAbAiQAaAhAwAAQArAAAogiQAmgiAWg1QAWg0AAg4QAAg1gaghQgbghgwAAQgsAAgmAigAl5AjIAbhiIjaAAIgGgkIE3kgIAuAAIhMEcIBBAAIgLAoIhBAAIgaBigAoAhnICtAAIA6jWgAsfh4IAMgxICoAAIgNAxgALJjcQgOgEgIgJQgKgKAAgNQAAgSARgNIgVAAIADgTIB/AAIgDATIhHAAQgVAKAAAQQAAASAiAAQAaAAATgJIgEAaQgWAJgYAAQgQAAgMgDgAKqk/IAEgUIBMAAQAPgIAAgNQAAgRghAAQgXAAgSAIIAEgaQASgIAZAAQAYABARAJQARAKAAATQAAAOgNALIASAAIgDAUg");
	this.shape.setTransform(1.5,181.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(12));

	// Слой_3
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(126,114,104,0.6)").s().p("AghAcQgJgBgCgIQgCgFAFgHQAEgGAIgCQAHgDAIABQAHACAEADQAEAFgBAHQgBADgEADQgEADgJADQgHACgFAAIgDAAgAAIACQgHgDACgIQABgGAIgEIAMgFQAFgCAEAAQAGgBAEAGQADAEgBAHQgBAFgGAFIgHAEQgDACgIAAQgHAAgFgEg");
	this.shape_1.setTransform(-28.7,-6.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("rgba(126,114,104,0.6)").s().p("AgTAQQgJgGADgKQACgGAJgFIAPgGQAGgDAEAAQAIgBAFAHQAEAGgCAIQgBAGgHAGQgFAFgEACQgEACgIAAQgKAAgGgFg");
	this.shape_2.setTransform(-26.3,-7.7,0.8,0.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1}]}).to({state:[{t:this.shape_2}]},1).to({state:[]},10).wait(1));

	// Слой_1
	this.instance = new lib.devs();
	this.instance.parent = this;
	this.instance.setTransform(-56,-143,0.8,0.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(12));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-117.5,-143,238.2,364.9);


(lib.dev_3duo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(126,114,104,0.6)").s().p("AgpAiQgMgBgCgJQgCgHAGgIQAFgIAKgDQAJgDAJABQAJACAFAEQAFAHgBAIQgBAEgGAEQgEAEgLADQgJACgGAAIgEAAgAAKADQgJgFADgKQACgIAJgEIAQgGQAGgDAEAAQAIgBAFAHQAEAFgCAJQgBAHgHAGQgFADgEACQgEACgJAAQgKAAgGgEg");
	this.shape.setTransform(-40.9,12.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(126,114,104,0.6)").s().p("AgTAQQgJgGADgKQACgGAJgFIAPgGQAGgDAEAAQAIgBAFAHQAEAGgCAIQgBAGgHAGQgFAFgEACQgEACgIAAQgKAAgGgFg");
	this.shape_1.setTransform(-37.9,11.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},1).to({state:[]},10).wait(1));

	// Слой_1
	this.instance = new lib.devs();
	this.instance.parent = this;
	this.instance.setTransform(-75,-158);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(12));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-75,-158,150,316);


(lib.bgImg_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.bgImg();
	this.instance.parent = this;
	this.instance.setTransform(-150,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bgImg_1, new cjs.Rectangle(-150,-300,300,600), null);


(lib.bg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#ECD087","#A27B3A","#000000","#000000"],[0,1,1,1],0,-299,0,299).s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.bg, new cjs.Rectangle(-150,-300,300,600), null);


(lib.arrow = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#E3B47D").ss(2,2,0,3).p("Agbg2IA3A2Ig3A3");
	this.shape.setTransform(9.5,0.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#E3B47D").s().p("AhmAJIAAgRIDNAAIAAARg");
	this.shape_1.setTransform(0.4,0.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.arrow, new cjs.Rectangle(-9.9,-6.1,23.6,13.8), null);


(lib.btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// arrow
	this.instance = new lib.arrow();
	this.instance.parent = this;
	this.instance.setTransform(59.6,-0.7,1,1,0,0,0,0.3,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({x:62},3,cjs.Ease.get(1)).to({x:59.6},2).wait(3).to({x:62},3,cjs.Ease.get(1)).to({x:59.6},2).wait(1));

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ABNBAIAAgVIhKAAIgCAVIgPAAIAAgmIAKAAQANgbAAguIAAgPIBJAAIAABYIANAAIgDAmgAAaghQAAAkgLAXIAwAAIAAhHIglAAgAh+AcQgQgQAAgVQAAgXAQgPQAQgQAXgBQAYABAQAQQAPAPAAAXQAAAVgPAQQgQAQgYAAQgYAAgPgQgAhwgkQgKALAAAQQAAAPAKAKQAKALAPAAQAQAAAKgLQAKgKAAgPQAAgQgKgLQgLgLgPABQgPgBgKALgAosAbIAKgNQAPAOAUAAQAJAAAGgEQAGgFAAgGQAAgPgYAAIgMAAIAAgQIAMAAQAVABAAgQQAAgGgFgFQgGgDgJAAQgRgBgMAMIgKgLQARgQAYgBQAQAAAKAJQALAHAAAMQAAARgSAIQAUAGAAATQAAANgKAIQgLAJgRAAQgcAAgSgRgAIYArIAAgVIAUAAIAAAVgAHYArIAAhMIg1BMIgRAAIAAhpIASAAIAABMIA1hMIARAAIAABpgAFWArIAAhLIghAwIgBAAIghgvIAABKIgSAAIAAhpIAUAAIAgAyIAggyIATAAIAABpgADLArIgLgaIgxAAIgLAaIgTAAIAuhqIARAAIAuBqgAC6AAIgTgoIgSAoIAlAAgAi1ArIgkgvIgRAQIAAAfIgSAAIAAhpIASAAIAAA1IAyg1IAXAAIgsAtIAuA8gAlpArIgLgaIgxAAIgLAaIgTAAIAuhqIARAAIAuBqgAl6AAIgTgoIgSAoIAlAAgAIdAJIgGhBIAAgGIAWAAIAAAGIgGBBg");
	this.shape.setTransform(-17,1.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(15));

	// Слой_7
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AuDDSIAAmjIcHAAIAAGjg");
	this.shape_1.setTransform(-1.2,0);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(15));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-91.2,-21,180,42);


(lib.banner = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// urText
	this.instance = new lib.urText();
	this.instance.parent = this;
	this.instance.setTransform(0,275.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(241));

	// logo
	this.instance_1 = new lib.logo();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-0.1,-254.4,1.16,1.16,0,0,0,1.8,0.4);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({alpha:1},10).wait(40).to({alpha:0},10).to({_off:true},1).wait(120).to({_off:false,y:150.6},0).to({alpha:1},10).wait(39).to({x:-241.1},10,cjs.Ease.get(-1)).wait(1));

	// dev_3duo
	this.instance_2 = new lib.dev_3duo("single",0);
	this.instance_2.parent = this;
	this.instance_2.setTransform(226,-50);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(181).to({_off:false},0).to({x:-2},10).wait(5).to({mode:"synched",loop:false},0).wait(34).to({startPosition:11},0).to({x:-243},10,cjs.Ease.get(-1)).wait(1));

	// t3
	this.instance_3 = new lib.t2();
	this.instance_3.parent = this;
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(151).to({_off:false},0).to({alpha:1},10).wait(10).to({y:-263},10,cjs.Ease.quadInOut).wait(49).to({x:-241},10,cjs.Ease.get(-1)).wait(1));

	// dev_3duo_text
	this.instance_4 = new lib.dev_3duo_text("single",0);
	this.instance_4.parent = this;
	this.instance_4.setTransform(270,-50);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(105).to({_off:false},0).to({x:-2},10).wait(5).to({mode:"synched",loop:false},0).wait(20).to({startPosition:11},0).to({x:-273},10,cjs.Ease.get(-1)).to({_off:true},1).wait(90));

	// dev_24
	this.instance_5 = new lib.dev_24_1();
	this.instance_5.parent = this;
	this.instance_5.setTransform(256,-50);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(60).to({_off:false},0).to({x:-2},10).wait(25).to({x:-260},10,cjs.Ease.get(-1)).to({_off:true},1).wait(135));

	// btn
	this.instance_6 = new lib.btn("single",0);
	this.instance_6.parent = this;
	this.instance_6.setTransform(-0.5,214.5,0.02,0.02,0,0,0,0,2.5);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(60).to({_off:false},0).to({regX:-0.5,regY:0.5,scaleX:1,scaleY:1},10,cjs.Ease.get(1)).wait(141).to({mode:"synched",loop:false},0).wait(19).to({startPosition:14},0).to({x:-241.5},10,cjs.Ease.get(-1)).wait(1));

	// t1_2
	this.instance_7 = new lib.t1_2();
	this.instance_7.parent = this;
	this.instance_7.setTransform(224.8,21.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).to({x:0},10,cjs.Ease.get(1)).wait(15).to({y:162.1},10,cjs.Ease.quadInOut).wait(15).to({alpha:0},10).to({_off:true},1).wait(180));

	// t1_1
	this.instance_8 = new lib.t1_1();
	this.instance_8.parent = this;
	this.instance_8.setTransform(-278.5,-15.7);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).to({x:0.1},10,cjs.Ease.get(1)).wait(15).to({y:125.3},10,cjs.Ease.quadInOut).wait(15).to({alpha:0},10).to({_off:true},1).wait(180));

	// bgImg
	this.instance_9 = new lib.bgImg_1();
	this.instance_9.parent = this;
	this.instance_9.alpha = 0;
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(25).to({_off:false},0).to({alpha:1},10).wait(15).to({alpha:0},10).to({_off:true},1).wait(180));

	// bg
	this.instance_10 = new lib.bg();
	this.instance_10.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(241));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-403.3,-300,698.9,600);


// stage content:
(lib._300x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// cover
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#666666").ss(2,1,1).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// banner
	this.instance = new lib.banner();
	this.instance.parent = this;
	this.instance.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-103.3,299,698.9,602);
// library properties:
lib.properties = {
	id: 'D78E0080C82B4A91A29A8C60B712AE41',
	width: 300,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/bgImg.jpg", id:"bgImg"},
		{src:"images/dev_24.png", id:"dev_24"},
		{src:"images/devs.png", id:"devs"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['D78E0080C82B4A91A29A8C60B712AE41'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;