(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 300,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	manifest: [
		{src:"images/bgImg.jpg", id:"bgImg"},
		{src:"images/car.png", id:"car"},
		{src:"images/l.png", id:"l"},
		{src:"images/roundBg.png", id:"roundBg"}
	]
};



// symbols:



(lib.bgImg = function() {
	this.initialize(img.bgImg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.car = function() {
	this.initialize(img.car);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,321,170);


(lib.l = function() {
	this.initialize(img.l);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,80,55);


(lib.roundBg = function() {
	this.initialize(img.roundBg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,267,267);


(lib.urText = function() {
	this.initialize();

	// Print
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAeEcIgLgCIACgNIAUADQAGAAAFgDQAFgDACgHIACgKIgHAAQgGAAgFgBQgDgBgEgEQgDgCgCgGIgEgKIgPg+IAPgDIARBEIADAEQACADADAAIAGACIAHgBIAThMIAPADIgZBhQgCAHgDAFQgDAFgFACQgFAEgEABIgLABgAIVD5QgFgBgFgFQgEgDgDgFQgCgEAAgIQAAgGACgGQADgGAFgDQADgDAHgCQAGgBAHgBIAXAAIAAgDQAAgMgEgEQgFgEgJAAIgNABIgNAEIgFgMQAIgDAGgBQAHgCALAAQALAAAGACQAGADAEAFQADAEACAGIABA0IAHAKIgKAIIgIgJIgGAEIgHADIgIACIgJABIgMgBgAIXDUQgFADAAAHQAAAFABADQACADACABIAGADIAHAAQAHAAAGgDIAKgFIAAgVIgYAAQgHAAgFAEgAGzD3QgGgCgEgFQgDgEgCgGQgBgHAAgGIAAg3IAPAAIAAA2QAAALAFAFQAFAEAJABQAHAAAHgDIAKgFIAAhDIAQAAIAABFIAHAKIgLAIIgIgIQgGAEgIADQgJACgHAAQgKAAgGgDgAEnD5QgEgBgGgFQgDgBgEgHQgDgFAAgHQAAgHADgFQADgGAFgDQAEgDAGgCIAMgCIAYAAIAAgDQAAgLgEgFQgFgEgJAAIgNABIgOAEIgEgMQAIgDAGgBQAHgCALAAQAKAAAHACQAGADAEAFQAEAEABAGQABAIAAAHIAAAlIAHAKIgKAIIgJgJIgFAEIgHADIgIACIgJABQgHAAgFgBgAEpDUQgFADAAAHQAAAFABADQACADACABIAGADIAHAAQAHAAAGgDIAKgFIAAgVIgYAAQgHAAgFAEgACED3QgJgEgEgGQgEgGgDgJQgCgHAAgLQAAgJACgIQAEgKAEgFQAFgGAIgEQAIgDALAAQAMAAAHADQAIAEAFAGQAEAFAEAKQACAIAAAJQAAAJgCAJQgCAIgGAHQgEAGgJAEQgJADgKAAQgKAAgKgDgACEC0QgGAIAAAQQAAARAHAIQAHAIAMAAQAMAAAHgIQAHgJAAgQQAAgQgHgIQgGgIgNAAQgNAAgHAIgAg7D3QgJgEgEgGQgGgHgCgIQgCgHAAgLQAAgJADgIQADgKAFgFQAEgGAJgEQAHgDALAAQAMAAAHADQAIAEAFAGQAFAGADAJQAAAHAAAKQAAALAAAHQgCAIgFAHQgFAGgIAEQgKADgKAAQgKAAgJgDgAg7C0QgHAIAAAQQAAAQAHAJQAHAIAMAAQANAAAHgIQAGgJAAgQQAAgQgGgIQgHgIgNAAQgNAAgGAIgAj8D4QgGgBgFgEQgHAEgFABQgIACgFAAQgFAAgHgCQgFgCgDgDQgEgDgBgFQgCgCgBgHIgGg+IAPgCIAHA+IACAHQACADACAAIAFADIAEAAIAIgBQADgBADgDIAAhGIAPAAIAABGIAHAEIAHABIAFAAIAEgDQACAAACgDQACgBABgGIAGg+IAQACIgHA+QgBAHgCACQgBAGgEACQgDADgFACQgGACgGAAQgFAAgIgCgAmCD4IgMgFQgFAEgGABQgIACgFAAQgFAAgHgCQgEgBgFgEIgFgIIgCgJIgHg+IAQgCIAHA+QAAAEACADQACADACAAIAEADIAFAAIAHgBIAHgEIAAhGIAPAAIAABGQAEADADABIAHABIAEAAIAFgDQACAAACgDIACgHIAHg+IAPACIgGA+IgDAJQgBAFgEADQgFAEgDABQgHACgFAAQgFAAgIgCgAoID4QgFgBgHgEQgGAEgFABQgIACgFAAQgGAAgGgCQgFgCgEgDQgDgDgCgFIgCgJIgHg+IAQgCIAGA+IACAHIAEADIAFADIAFAAIAHgBQADgBAEgDIAAhGIAPAAIAABGIAGAEIAIABIAEAAIAFgDQACAAACgDQABgBABgGIAHg+IAPACIgHA+QAAAFgCAEQgCAGgDACQgEADgEACQgHACgFAAQgFAAgIgCgAF4D3QgCgEAAgFQAAgEACgEQADgDAGgBQAGABACADQADADAAAFQAAAFgDAEQgCADgGgBQgGABgDgDgAi7D3QgDgEAAgFQAAgEADgEQACgDAGgBQAGABADADQACAEAAAEQAAAFgCAEQgDADgGgBQgGABgCgDgADpD4QgFgCgDgDQgDgCgDgGQgCgEAAgJIAAgvIgMAAIAAgNIAMAAIAAgZIAQAAIAAAZIAcAAIAAANIgcAAIAAAsQAAAKADADQAEAEAHABIAQgDIADAMIgWADgAh7D4QgFgCgEgDQgCgCgDgGQgCgEAAgJIAAgvIgMAAIAAgNIAMAAIAAgZIAPAAIAAAZIAcAAIAAANIgcAAIAAAsQAAAKAEADQAEAEAHABIAQgDIADAMIgWADQgGAAgFgBgAFDBQIAAhoIgFgOIANgHIAGAJIAMgFQAIgCAHgBQATABAJAMQAKAKAAAVQAAALgCAIQgEAJgEAGQgGAFgIAEQgKAEgJAAIgUgDIAAAkgAFegcIgLAFIAAA1IAJADIAMABIAKgCQAFgDADgDQAEgEACgHQACgGAAgJQAAgFgCgHQgBgGgEgEQgDgEgEgCQgEgCgGAAQgFAAgHACgAKjAtQgFgBgFgDQgDgDgEgFQgCgHAAgFQAAgIADgGQADgFAEgCQAGgDAFgBQAGgCAGAAIAXAAIAAgFQAAgKgEgGQgFgDgKAAIgMABIgOADIgEgLQAHgDAHgCQAHgCALAAQAJABAIACQAFACAFAEQAEAFAAAGQACAGAAAIIAAAlIAHALIgLAIIgIgJIgMAHQgHADgKAAQgGAAgGgCgAKlAIQgFAEAAAHQAAAFACACQABAEADABIAFADIAHAAQAHAAAGgCIAJgHIAAgUIgWAAQgHgBgGAEgAG2AtQgFgBgFgDQgEgEgDgEQgCgHAAgFQAAgIADgGQACgFAFgCIALgEQAGgCAGAAIAXAAIAAgFQAAgLgFgFQgEgDgKAAIgMABIgOADIgEgLQAHgDAHgCQAGgCAMAAQAJABAIACQAFACAFAEQADAFABAGQACAGAAAIIAAAlIAHALIgLAIIgIgJIgMAHQgHADgKAAIgMgCgAG4AIQgFAEAAAHQAAAFABACQACADACACIAGADIAHAAQAHAAAFgCIAKgHIAAgUIgWAAQgHgBgGAEgAgQAtQgEgBgGgDQgDgDgDgFQgDgFAAgHQAAgJADgFQADgFAEgCQAGgDAFgBQAGgCAGAAIAVAAIAAgFQAAgMgEgEQgFgDgKAAIgKABIgOADIgEgLIAOgFQAHgCAJAAQAKABAHACQAGACAEAEQADAFACAGIABAOIAAAlIAHALIgLAIIgIgJIgMAHQgHADgIAAQgGAAgGgCgAgOAIQgFAEAAAHQAAAFACACQABADADACIAFADIAHAAQAFAAAGgCIAJgHIAAgUIgUAAQgHgBgGAEgAi8ArQgIgDgFgGQgEgGgDgKQgCgHAAgLQAAgGACgKQAEgIAEgGQAGgGAHgEQAKgDAJgBQAKABAJADQAHADAGAHQAEAGAEAIQACAKAAAGQAAAKgCAIQgCAJgGAHQgGAGgHADQgJAEgKAAQgLAAgJgEgAi8gWQgGAIAAAOQAAASAHAHQAHAJAMAAQANAAAGgJQAHgIAAgRQAAgOgHgIQgHgJgMABQgNgBgHAJgAmDArQgHgDgGgGQgFgJgCgHQgDgIAAgKQAAgHADgJQADgIAFgGQAFgHAIgDQAJgDAKgBQAJABAKADQAHAEAGAGQAFAGACAIQADAKAAAGQAAAKgDAIQgCAJgFAHQgFAGgIADQgJAEgKAAQgLAAgJgEgAmDgWQgHAJAAANQAAARAHAIQAHAJANAAQANAAAGgJQAHgIAAgRQAAgNgHgJQgGgJgNABQgNgBgHAJgAEIAGIgLAAIAAAmIgPAAIAAhVIAPAAIAAAjIAIAAIAEgBIADgDIAPgXQACgDAEgDQAEgDAFAAIADAAIAFACIgCAMIgBAAIgCAAIgEABIgEADIgOAXIgCABIAfAjIgLAKgACNArIACgNIALACIAGAAIAGgCIAEgFIAEgHIABgDQgJAAgGgEQgHgEgDgIIgZhHIAPgGIAYBFQACAIAEABQAEABAGAAIAbhPIAQAFIghBaQgDAKgDAEIgHAJIgKAEIgNABgAJsAsIAAgnIgrAAIAAAnIgPAAIAAhVIAPAAIAAAjIArAAIAAgjIAPAAIAABVgAIJAsIAAhIIgLAAIAAgNIAaAAIAABVgAhYAsIAAhIIgfAAIAAgNIBNAAIAAANIgfAAIAABIgAj2AsIAAg2IgrApIAAANIgPAAIAAhVIAPAAIAAA3IArgqIAAgNIAPAAIAABVgAnHAsIAAhrIgnAAIAAgNIBeAAIAAANIgnAAIAABrgApvAsIAAh4IAQAAIAAB4gAqbAsIAAh4IAQAAIAAB4gArHAsIAAhrIg8AAIAABrIgRAAIAAh4IBeAAIAAB4gAA+AAIAAgPIA1AAIAAAPgAMJgcIAAgwIAPAAIAAAwgALvgcIAAgwIAOAAIAAAwgAoKgcIAAgwIAPAAIAAAwgAokgcIAAgwIAOAAIAAAwgAkfg9QgJgFgCgKIAMgFQADAGAEAEQAFAFAIAAQAIAAAEgFQAEgEADgGIAMAFQAAAEgEAFQgCAEgFACQgDAEgGABIgLACQgMAAgJgHgAIYg8QgDgDAAgEQAAgFADgDQACgEAGAAQAGAAACAEQACACAAAGQAAAFgCACQgCADgGABQgFgBgDgDgAHyg8QgCgDAAgEQAAgGACgCQACgEAGAAQAGAAACAEQADADAAAFQAAAEgDADQgCADgGABQgGgBgCgDgAOJh4IAAhrIgGgOIAOgGIAFAJIANgGQAHgCAIAAQASAAAKALQAKALAAAXQAAAMgDAHQgDAJgFAFQgFAGgJAFQgJADgKAAIgUgDIAAAlgAOjjnIgLAFIAAA3IAJADIAMABIAKgCQAGgDACgDQAEgDACgIQADgGAAgIQAAgIgCgIQgBgFgEgFQgEgDgEgCQgEgCgFAAQgIAAgFACgAECh4IAAhrIgFgOIANgGIAGAJIAMgGQAIgCAHAAQATAAAJALQAKALAAAXQAAAMgCAHQgEAJgEAFQgGAGgIAFQgKADgJAAIgUgDIAAAlgAEdjnIgLAFIAAA3IAJADIAMABIAJgCQAFgCAEgEQAEgDACgIQACgFAAgJQAAgJgCgHQgBgFgEgFQgDgDgEgCQgEgCgGAAQgIAAgEACgAslh4IAAgiQgMgBgKgEQgJgEgGgGQgFgEgDgJQgDgKAAgHQAAgKADgIQADgIAGgGQAGgFAJgEQAJgDAMgBIAAgjIAPAAIAAAjQAMABAJADQAJAEAGAGQAFAGADAHQADAJAAAJQAAAHgDAJQgDAIgFAGQgFAFgJAEQgLAFgLABIAAAigAsWioQAQgBAIgIQAHgIAAgOQAAgdgfgEgAs9jeQgIAHAAAQQAAAOAIAIQAHAIARABIAAhAQgQABgIAJgAgliJIAAgUIg+AAIAAATIgPAAIAAghIAJAAIAHgLQAEgHABgHIACgJIACgnIA4AAIAABJIAKAAIAAAigAhOjAIgFAMIgFAJIAnAAIAAg8IgZAAQAAAVgEASgApgiJIAAgUIhFAAIAAhXIAPAAIAABJIAqAAIAAhJIAQAAIAABJIALAAIAAAigAM2ieQgJgEgEgGQgFgHgCgHQgCgIAAgKQAAgMACgGQACgJAGgGQAFgGAIgEQAKgEAJABQAJgBAKAEQAIAEAFAGQAFAGACAJQADAGAAAMQAAAKgCAIQgDAIgFAGQgFAGgIAEQgIAEgLAAQgMAAgIgEgAM2jhQgGAIAAARQAAAQAGAIQAHAJANAAQANAAAGgJQAHgIAAgQQAAgRgHgIQgHgJgMAAQgNAAgHAJgAKHidQgHgDgGgFQgFgHgCgGQgCgIgBgHIgSAAIAAAkIgPAAIAAhXIAPAAIAAAlIASAAQABgJADgHQADgHAEgFQAHgGAGgDQAHgCAKAAQAKgBAIAEQAIAEAFAGQAFAGACAJQACAIAAAKQAAAIgCAKQgCAGgFAIQgFAHgHADQgJAEgKAAQgLAAgHgDgAKGjhQgGAIAAARQAAAQAGAIQAGAJANAAQAMAAAGgJQAGgIAAgQQAAgRgGgIQgGgJgMAAQgNAAgGAJgAHaieQgJgEgEgHQgFgHgCgKQgCgJAAgNQAAgLACgKQABgKAFgIQADgHAHgHQAIgFAJgDIASgEIAGgEIAEgHIANAEIgBAHIgCAEIgDAEIgEADIgEABIgUAGIgLADIgHAHQgDAEgCAEIgCALQAEgEAJgFQAJgDAIAAQALAAAGADQAIAEAEAFQAEAFACAGQACAHAAAJQAAAKgCAIQgCAHgGAHQgFAFgIAFQgJADgKAAQgMAAgIgEgAHojgIgIADIgGAEIgFAFIgBAEIABARIAEAMQAEAGAEACQAGAEAHAAQANAAAHgIQAGgJAAgOQAAgbgYAAgABsidQgJgFgFgFQgFgGgCgIQgCgIAAgKQAAgMACgHQADgHAGgIQAGgHAIgDQAJgEAKABQALAAAGACIANADIgFANIgNgEIgMgBQgHAAgFACQgGADgDAEQgEAFgBAGQgCAFAAAJQAAAPAHAJQAHAHANAAIAOgBQAGgBAHgCIAFALQgGADgIACIgSACQgLAAgJgDgAu4igQgLgFgHgIQgHgKgDgLQgDgLAAgNQAAgMADgMQAEgMAHgIQAGgJALgFQALgGAPABQAOgBAMAGQALAFAGAJQAGAHAEANQADAMAAAMQAAANgDALQgDALgHAKQgHAIgLAFQgMAGgNAAQgPAAgLgGgAuwkIQgHAFgFAGQgFAGgCAKQgDAJAAAKQAAAJADALQACAIAFAIQAFAGAHAEQAHAEALAAQAKAAAHgEQAHgEAFgGQAFgIACgIQADgIAAgMQAAgMgDgHQgCgKgFgGQgFgHgHgEQgHgEgKAAQgLAAgHAEgALqidIAAhKIgeAAIAAgNIBMAAIAAANIgeAAIAABKgAGgidIAAg5IgqAsIAAANIgQAAIAAhXIAQAAIAAA4IAqgsIAAgMIAQAAIAABXgADFidIAAhKIgeAAIAAgNIBMAAIAAANIgeAAIAABKgAAwidIAAg5IgqAsIAAANIgOAAIAAhXIAOAAIAAA4IAqgsIAAgMIAQAAIAABXgAi0idIAAg5IgqAsIAAANIgQAAIAAhXIAQAAIAAA4IAqgsIAAgMIAQAAIAABXgAkWidIAAg5IgrAsIAAANIgPAAIAAhXIAPAAIAAA4IArgsIAAgMIAPAAIAABXgAl5idIAAgnIgqAAIAAAnIgQAAIAAhXIAQAAIAAAjIAqAAIAAgjIAQAAIAABXgAnbidIAAg5IgrAsIAAANIgPAAIAAhXIAPAAIAAA4IArgsIAAgMIAPAAIAABXgAo+idIAAhLIgKAAIAAgMIAZAAIAABXgArOidIAAhLIgKAAIAAgMIAZAAIAABXgAIqjnIAAgwIAOAAIAAAwgAjckHQgJgGgDgLIANgEQADAGAEAEQAEAEAIAAQAJAAAEgEQAEgEADgGIAMAEQAAAFgEAFIgHAHQgEADgFABQgHACgFAAQgLAAgJgGgAoEkHQgJgHgCgKIANgEQABAGAFAEQAEAEAJAAQAIAAAEgEQAFgEACgGIANAEQgCAGgDAEQgBADgGAEQgEADgFABIgLACQgLAAgKgGgAo/kGQgDgCAAgGQAAgEADgDQADgDAFAAQAGAAACADQADADAAAEQAAAFgDADQgCADgGAAQgFAAgDgDgArPkGQgDgDAAgFQAAgEADgDQACgDAGAAQAFAAADADQACAEAAADQAAAFgCADQgDADgFAAQgGAAgCgDg");
	this.shape.setTransform(0,9.6);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-98.4,-18.9,196.9,57.1);


(lib.t1_3 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Au2B3IAAgnIhpAAIAAAnIgqAAIAAhKIATAAQAGgFADgHIAHgQQADgHACgMIAOhxIB4AAIAACgIAPAAIAABKgAv0gSQgDAVgEAQQgFARgGAJIBBAAIAAh9IgoAAgAEtA2IAWgPIAEgEIAEgJQACgEACgMIAPh9IB6AAIAADDIgqAAIAAigIgqAAIgMBeQgBALgDANQgEALgGAIQgGAHgJAIQgLAIgQAIgAJ7BNQgSgHgNgOQgMgPgFgSQgFgSAAgVQAAgXAHgSQAGgTANgNQANgNATgJQATgHAZAAQAUAAARAEIAdAKIgMAhIgSgGIgOgEIgLgCIgMAAQgcAAgPASQgPARAAAgQAAAgAPARQAQARAbAAIAPgBIANgCIAegLIAMAgIgRAHIgjAJIgVABQgZAAgUgIgAj8BMQgTgIgLgOQgLgPgFgSQgFgVAAgQQAAgTAFgTQAGgTALgOQALgNATgKQASgIAZAAQAaAAATAIQASAJALAOQAMAPAFASQAFARAAAVQAAARgGAUQgFASgMAPQgLAOgSAIQgSAJgaAAQgaAAgSgJgAjnhNQgLAFgFAJQgHAJgDAMQgDAMAAAOQAAAOADALQADAMAHAJQAGAJAKAFQAKAGANAAQAOAAAKgGQAJgFAHgJQAHgKADgLQADgLAAgOQAAgOgDgMQgDgKgHgLQgGgJgKgFQgKgGgOAAQgNAAgKAGgAmlAAIgRAAIAABQIgpAAIAAjDIApAAIAABQIAJAAQAFAAACgBQACgBADgFIAkg2QAGgJAHgGQAJgGANAAIALABIAMADIgFAfIgEAAIgDAAQgFAAgEADIgmA2IgEAEIBFBRIgeAZgApxBNQgSgHgNgOQgKgNgHgUQgFgSAAgVQAAgXAHgSQAHgTAMgNQANgNATgJQATgHAZAAQAUAAARAEQAOAEAPAGIgMAhIgSgGIgNgEIgMgCIgLAAQgdAAgPASQgPARAAAgQAAAgAPARQAQARAbAAIAPgBIANgCIAegLIAMAgIgiANIgSADIgUABQgaAAgUgIgAtIBMQgSgIgLgOQgMgQgEgRQgFgSAAgTQAAgVAFgRQAGgSALgPQALgOATgJQASgIAZAAQAaAAATAIQATAKAKANQAMAPAEASQAGATAAATQAAARgGAUQgFARgMAQQgLAOgSAIQgSAJgaAAQgaAAgTgJgAsyhNQgKAFgHAJQgHALgCAKQgDAMAAAOQAAAOADALQACALAHAKQAHAJAKAFQAKAGANAAQAOAAAKgGQAKgFAGgJQAGgJADgMQADgLAAgOQAAgOgDgMQgDgMgGgJQgGgJgKgFQgKgGgOAAQgNAAgKAGgADtAYIhNAAIgSA9IgogJIAvibIAHgRQAFgIAFgEQAGgFAIgDQAJgCALAAQAKAAAJACQAJADAFAFQAGAEADAHQADAGADAKIAwCdIgpAJgADjgIIgShCQgCgGgCgBQgDgCgDAAQgEAAgCACIgEAHIgUBCIA6AAgAOzBQIAAjDIAqAAIAABLIApAAQAhAAARAPQASAOAAAcQAAAfgUAQQgUAQglAAgAPdAvIAeAAQAIAAAGgCQAHgBAEgDQAGgEACgFQADgFAAgJQAAgHgDgGQgEgFgDgBIgLgEIgtgBgAM5BQIAAigIg7AAIAAgjICeAAIAAAjIg6AAIAACggAH/BQIAAjDIApAAIAADDgAAlBQIAAhQIhNAAIAABQIgqAAIAAjDIAqAAIAABPIBNAAIAAhPIArAAIAADDg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-109.8,-11.9,219.7,24);


(lib.t1_2 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ar8BGIAMgIQAGgEAEgEQAFgFADgGQACgFADgKIACgKQgHgCgHgFQgGgEgHgHQgFgHgDgHQgCgIAAgLQAAgQAFgMQAFgMAKgIQAIgIAOgFQAMgEAQAAIBLAAIAADDIgpAAIAAhHIgcAAIgDANIgHAUQgCAHgHAJQgGAHgLAIQgJAHgOAGgAq9g/QgHABgEADQgGAFgBAEQgDAHAAAIQAAAOAKAHQAJAHAPAAIAcAAIAAg5IgdAAQgHAAgFABgAHMAPIgRAAIAABSIgpAAIAAjDIApAAIAABQIAIAAQAFAAADgBQACgBAEgFIAjg3QAGgIAHgGQAJgGANAAIALABQAGAAAGACIgFAgIgEgBIgDAAQgGAAgDADIgHAIIgbAqIgEAFIgEADIBFBRIgeAagABKBdQgUgHgKgOQgMgNgFgUQgGgTAAgUQAAgUAGgVQAHgSANgOQANgNATgIQAVgIAYAAQAUAAAQAEQAOAEAPAGIgMAiIgRgHIgPgDIgLgCIgLgBQgcABgPARQgPASgBAfQABAgAPASQAPAQAcAAIAOgBIANgCIAegKIAMAfIgQAIIgkAIIgVABQgcAAgRgIgAlUBdQgTgKgKgNQgLgOgGgTQgFgVAAgQQAAgSAFgTQAFgSANgPQALgPASgIQASgJAZAAQAbAAASAJQATAIAKAPQALAOAGATQAFARAAAUQAAAUgGARQgEATgMAOQgLAOgTAJQgSAJgagBQgaABgSgJgAk/g9QgKAFgGAKQgGAIgDAMQgEANAAANQAAANAEAMQADAOAGAHQAGAJAKAGQAKAFANAAQAOAAAKgFQAKgGAGgJQAHgKADgLQADgMAAgNQAAgNgDgNQgCgLgIgJQgFgKgLgFQgKgFgOAAQgNAAgKAFgALDApIhOAAIgSA8IgogJIAwibIAGgRQAFgIAFgDQAGgGAIgCQAJgDALAAQAKAAAKADQAIADAFAEQAGAGADAGIAHAPIAvCdIgoAJgAK4AGIgShAQgCgGgCgBQgDgCgDAAQgDAAgDACQgCADgCAEIgTBAIA5AAgADcBhIAAjDIApAAIAABKIAqAAQAgAAASAPQASANAAAeQAAAegUAQQgUARglAAgAEFA/IAgAAQAHAAAGgBQAGgCAFgDQAFgDADgGQACgGAAgHQAAgJgCgFQgCgEgFgDQgFgEgGgBIgNgBIghAAgAgwBhIAAhSIhPAAIAABSIgrAAIAAjDIArAAIAABPIBPAAIAAhPIAqAAIAADDgAnOBhIAAigIhNAAIAACgIgqAAIAAjDIChAAIAADDg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-76.6,-10.3,153.2,20.7);


(lib.t1_1 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AQHAqIhOAAIgSA8IgogJIAwibIAGgRQAEgGAGgGQAGgFAIgCQAIgDAMAAQANAAAHADQAHACAGAFQAGAGADAFIAHAQIAvCdIgpAJgAP8AHIgShAQgBgEgDgDQgCgCgEAAQgEAAgCACQgCACgCAFIgTBAIA5AAgAkUAqIhOAAIgSA8IgogJIAwibIAGgRQAEgGAGgGQAGgFAJgCQAHgDAMAAQANAAAHADQAHACAGAFQAGAGADAFIAHAQIAvCdIgpAJgAkeAHIgThAQgBgEgDgDQgCgCgEAAQgEAAgCACQgCACgCAFIgTBAIA6AAgAojBfQgSgGgOgKIASgeIANAHIAOAGIAPAEIAOABQAJAAAGgCQAHgBAFgDQAGgFACgEQADgFAAgIQAAgFgCgFQgBgDgEgFQgGgDgGgCQgGgCgMAAIglAAIAAggIAjAAQAJAAAHgCQAHgCADgFQAFgEAAgEIACgIQAAgNgJgGQgKgFgLAAQgMAAgOAFQgOAEgMAHIgRgdIANgHIAQgHIAVgFQAJgCAOAAQATAAAMAEQANAEAIAHQAIAHADAKQAEAJAAAMQAAAOgIAMQgHAMgQAHQASADAKALQAKANAAARQAAAOgFAKQgGAMgJAHQgKAJgOAEQgOAEgUAAQgZAAgTgGgArKBfQgTgGgOgKIATgeIAMAHIAPAGIAPAEIAOABQAIAAAGgCQAIgBAEgDQAGgFADgEQADgFAAgIIgCgKQgBgDgFgFQgFgDgGgCQgHgCgLAAIgmAAIAAggIAjAAQAJAAAIgCQAGgDAEgEQADgDACgFIABgIQAAgNgIgGQgKgFgMAAQgLAAgPAFQgOAFgLAGIgRgdIAMgHIARgHIAUgFQAKgCANAAQAUAAALAEQAOAEAHAHQAIAHAEAKQADAJAAAMQAAAOgHAMQgIAMgPAHQARADAKALQAKANAAARQAAAMgFAMQgFALgJAIQgKAIgPAFQgPAEgTAAQgYAAgTgGgAM/BiIAAhTIhQAAIAABTIgqAAIAAjDIAqAAIAABOIBQAAIAAhOIAqAAIAADDgAJ1BiIAAhIIgVAEQgKACgMAAQgdAAgQgKQgQgLgFgQIgDgbIAAhBIArAAIAABFIABAJQADAJAHADQAHAEAOAAIAVgCIAQgDIAAhZIAqAAIAADDgAFbBiIAAjDICNAAIAAAiIhlAAIAAAqIBPAAIAAAhIhPAAIAAAzIBoAAIAAAjgACuBiIAAjDIBMAAQAOAAAMADQAOAEAJAIQAKAHAFANQAGAMAAARQAAAPgGAMQgGALgJAIQgJAIgOAEQgMAFgQAAIghAAIAABEgADXgCIAdAAIAMgCQAGgBAFgEQAFgEADgFQADgFAAgKQAAgJgDgHQgCgFgGgEQgEgDgGgCIgqgBgAABBiIAAjDICOAAIAAAiIhmAAIAAAqIBPAAIAAAhIhPAAIAAAzIBoAAIAAAjgAhNBiIAAigIhNAAIAACgIgpAAIAAjDICgAAIAADDgAuJBiIAAjDICOAAIAAAiIhlAAIAAAqIBOAAIAAAhIhOAAIAAAzIBnAAIAAAjgAxABiIAAjDICKAAIAAAiIhhAAIAAApIArAAQAQAAAMADQAPAEAIAGQAJAHAFAJQAFAMAAAPQAAAfgVAQQgVARglAAgAwXBAIAugBQAHgCAFgDQAFgCADgGQADgGAAgIQAAgJgDgFQgDgFgFgDQgHgDgFgBIguAAg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-109,-10.2,218,20.5);


(lib.Symbol1 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AGDA3IAAgSIhZAAIAAhZIANAAIAABPIAcAAIAAhPIANAAIAABPIAcAAIAAhPIAMAAIAABPIAIAAIAAAcgAhAA3IAAgSIg2AAIAAASIgMAAIAAgbIAGAAIAFgHQACgEACgFIADgLIAGg1IAwAAIAABQIAHAAIAAAbgAhoANIgDAIIgDAHIAnAAIAAhGIgZAAgAENAIIgkAAIgKAfIgKgCIAZhNQABgFADgFQADgDAGAAIAGAAIAEACIADAEIACAHIAaBNIgNACgAELAAIgNgnIgBgDIgCgBIgCABIgBADIgMAnIAfAAgAlbAIIgkAAIgKAfIgKgCIAYhNQADgHACgDQADgDAGAAIAGAAIAEACIADAEIAbBUIgMACgAleAAIgMgnIgBgDIgCgBIgCABIgOAqIAfAAgAnNAlIgMgHIAFgIQAGAEAFACQAIACAGAAQAKAAAFgEQAFgGAAgIIgBgHQgBgDgCgCQgDgBgDgBQgEgBgGAAIgOAAIAAgKIANAAQAGABADgCIAGgEIADgFIABgGQAAgIgFgEQgEgDgIAAIgMABIgLAEIgEgHIALgFIASgDQAIAAAFACQAGACACACQAEADABAFQACADAAAGIgBAIIgEAHIgFAEIgFAEQAEAAADADQADABACADQADACABACQABAEAAAFQAAAGgCAFQgBAEgFAEQgEAFgGABQgFACgJAAQgKAAgJgCgABlgDIgMAAIAAAoIgMAAIAAhZIAMAAIAAAnIAIAAQADABACgCQACAAABgFIAPgaQABgDADgCQADgCAFAAIAEAAIADABIgBAIIgCAAIgCAAQAAAAgBAAQAAAAgBAAQAAAAAAAAQgBABAAAAIgDADIgPAcIgBABIAeAuIgMACgAiugDIgJAAIAAAoIgNAAIAAgoIgKAAIgdApIgMgCIAfgtIgBgCIgOgcIgDgEIgDAAIgCAAIgCAAIgBgIIAEgBIAEAAQAFAAACABQADADABADIANAaQACAEACABQABACAEgBIAFAAIAAgnIANAAIAAAnIAFAAQADABACgCQACAAABgFIANgaIAEgFQADgCAFAAIAEAAIAEABIgCAIIgCAAIgBAAIgEABIgCADIgNAaIgBACIgCACIAfAtIgMACgAGgAlIAAhZIA4AAIAAAKIgsAAIAAAcIAhAAIAAAKIghAAIAAAgIAuAAIAAAJgACbAlIAAhZIAoABQAGABAEADQAFAEACAFQACAFAAAIQAAAFgCAFQgCAGgEADQgEAEgFACQgHAAgHABIgQAAIAAAkgACngHIAOAAQAKAAAFgEQAGgFAAgJQAAgFgCgEQgBgEgDgCQgCgBgFgBIgIgBIgOAAgAASAlIAAg9IgoAyIAAALIgNAAIAAhZIANAAIAAA/IAogyIAAgNIAMAAIAABZgAk+AlIAAhZIAdAAQAHAAAFACQAFAAAEADQAEAEADAEQACAFAAAGQAAAFgDAGQgFAGgEABQAIAEAEAFQAEAFAAAIQAAAFgCAFQgDAGgDACIgKAGQgGABgGAAgAkxAcIASAAQAKAAAFgFQAEgEAAgIQAAgFgBgEIgFgCQgCgCgFgBIgYAAgAkxgNIARAAQAEABADgCQADgBACgCQADgCAAgDIABgGQAAgIgFgEQgEgDgKAAIgOAAg");
	this.shape.setTransform(0,0,0.496,0.495);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-23.5,-2.7,47,5.5);


(lib.roundBg_1 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.roundBg();
	this.instance.setTransform(-133.5,-133.5);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-133.5,-133.5,267,267);


(lib.round = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#990200").s().p("AoGTOQjwhmi4i5Qi5i5hljvQhpj4AAkPQAAkOBpj4QBljwC5i5QC4i4DwhmQD4hoEOAAQEPAAD4BoQDwBmC4C4QC5C5BlDwQBpD4AAEOQAAEPhpD4QhlDvi5C5Qi4C5jwBmQj4BpkPgBQkOABj4hpg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-133.5,-133.5,267,267);


(lib.pr = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AtvRNMAAAgiZIbfAAMAAAAiZg");
	this.shape.setTransform(88,110.1);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,176,220.3);


(lib.t_6 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACWJxIAAi+IgKgaIAZgLIAJAQQALgGALgEQAMgEAQAAQAgAAASAVQASAVAAAmQAAAUgEAOQgFAQgKALQgKAMgPAFQgOAGgVAAIgRgBIgSgDIAABBgADGGrIgUAJIAABjIAQAFIAVABQAKAAAIgDQAJgDAGgIQAIgHADgLQAEgMAAgQQAAgQgEgKQgDgLgFgHQgGgHgIgDQgHgDgLAAQgNAAgIADgAmgJTIAAgkIhwAAIAAAiIgaAAIAAg6IAQAAIAMgUQAFgKAEgPIAGgjIABgXIAAgcIBlAAIAACDIATAAIAAA8gAnqHxQgDAKgFALIgJARIBGAAIAAhrIgtAAQgBAogHAdgAANIvQgNgGgJgLQgJgKgEgPQgEgQgBgSQAAgQAFgQQAFgPAIgLQAJgMANgGQAPgHASAAQAjAAAQATQAQAUAAAmIgNAOIhjAAQABAWAMAOQANAOAYAAIAOgBIALgCIAMgDIAPgEIAIAWQgJAEgRAEQgNADgWAAQgXAAgOgFgABUHUQAAgNgCgIQgEgJgEgFQgGgFgHgDQgHgCgIAAQgUAAgMAMQgLAMgBAVIBSAAIAAAAgAjLIcIALgHIAIgHQACgCACgGIADgOIALhkIBmAAIAACbIgcAAIAAiDIgwAAIgNBiQgCAIgFAHQgFAGgHAFQgGAFgNAGgAGaIvIAAibIBJAAQANAAAIACQAJACAHAFQAIAEADAIQADAHAAALQABALgGAIQgEAJgJAFIAKAFIAIAIQAFAEACAGQACAHAAAHQAAAWgPAMQgOAMgZAAgAG2IZIAwAAQAMAAAJgGQAHgFABgNQgBgJgEgGQgGgFgFgCIgJgBIgJgBIgrAAgAG2HTIAqAAQALAAAIgFQAHgFABgLQAAgLgIgFQgGgEgPAAIgoAAgAFRIvIAAiFIgSAAIAAgWIAuAAIAACbgAkCIvIAAhlIhNBPIAAAWIgcAAIAAibIAcAAIAABlIBNhOIAAgXIAbAAIAACbgAFQF1QgFgFgBgJQABgJAFgFQAEgGAKAAQAJAAAFAGQAFAFAAAJQAAAJgFAFQgFAGgJAAQgKAAgEgGgAs/EyIgTgEIAEgXIASAEIARABQANAAAIgEQAJgGADgMIAEgSIgNABQgKAAgJgDQgGgCgIgGQgFgHgEgHIgGgUIgchwIAbgHIAgB9IAFAIQADAEAFABQAGACAGAAIALgBIAkiLIAaAHIgtCvQgDANgGAJQgFAIgIAFQgIAGgJABQgJACgMAAgAlmExIAAg+QgVgCgPgHQgQgIgIgJQgKgLgEgNQgEgPAAgOQAAgQAFgNQAEgNAKgKQAKgLAPgHQAOgHAUgCIAAg/IAsAAIAAA+QAXAEAMAGQARAIAHAKQAKAKAEANQAEAOAAAOQAAAPgEAOQgEAMgKAMQgJAKgPAIQgRAHgSACIAAA+gAl/CGQgKALAAATQAAASAKALQAIAMATADIAAhYQgTADgIALgAk8DPQARgDAJgKQAKgLgBgTQABgUgKgKQgJgMgRgCgAAFETIAAgkIhxAAIAAidIAsAAIAAB6IAzAAIAAh6IArAAIAAB6IASAAIAABHgAMSC9IgDgEIgDgBIgDABIgxA9IgggYIAxg8Igrg+IAigWIAmA5QADAFADAAIAEgBIACgEIAog4IAhAVIgrA9IAwA9IghAYgApDDuQgPgGgKgMQgKgKgEgQQgFgPAAgRQAAgSAFgPQAGgQAJgKQAKgLAPgHQARgHASAAQAUAAAQAHQAQAHAJALQAKAMAEAOQAGAOgBASQABAQgGARQgFAPgJALQgKALgQAHQgPAHgUAAQgUAAgQgHgAo5B/QgIAMgBAXQABAWAIAMQAJAMARAAQARAAAJgMQAJgMAAgXQAAgWgJgMQgJgMgRAAQgRAAgJAMgAJzDvIAAhQIgzA1IAAAbIgsAAIAAidIAsAAIAABQIAzg0IAAgcIAsAAIAACdgAG+DvIAAg+Ig0AAIAAA+IgsAAIAAidIAsAAIAAA6IA0AAIAAg6IAsAAIAACdgAEJDvIAAhQIg0A1IAAAbIgsAAIAAidIAsAAIAABQIA0g0IAAgcIAsAAIAACdgABTDvIAAh5IgUAAIAAgkIBAAAIAACdgAjCDvIAAh5IgUAAIAAgkIBAAAIAACdgABSA6QgHgHAAgLQAAgLAHgGQAHgIANAAQANAAAHAIQAHAHAAAKQAAALgHAHQgHAHgNAAQgOAAgGgHgAjEA6QgGgHAAgLQgBgKAIgHQAHgIANAAQAMAAAIAIQAHAHAAAKQAAAKgHAIQgIAHgMAAQgNAAgIgHgADcA6QgKgCgHgFQgHgFgHgIQgGgKgCgJIAegKQAEALAHAEQAHAGALAAQALAAAHgGQAHgFADgKIAfAKQgCAJgGAJQgFAIgIAGQgHAFgKACQgIADgMAAQgMAAgJgDgAGAhOQgPgGgJgLQgKgLgEgPQgEgQAAgRQAAgRAEgPQAFgPAJgLQAKgMANgGQAOgHAUAAQAiAAARATQAQAUAAAmIgNAOIhjAAQABAWAMAOQANAOAXAAIAOgBIAMgCIAagHIAIAWIgZAIQgNADgXAAQgUAAgQgFgAHHipQAAgNgDgJQgDgJgFgEQgFgFgHgDQgJgCgHAAQgVAAgLAMQgKAMgCAVIBTAAIAAAAgAm+hPQgQgJgHgLQgIgMgFgSQgEgQAAgXQABgVADgRQADgSAHgOQAHgOAMgKQALgKATgFIAhgIQAIgCACgEIAHgOIAZAJIgDALIgEAIIgFAGIgGAFIgHADIgkAKQgKACgKAFQgJAEgFAHQgGAGgDAIQgDAIgBALQAIgHAQgHQAPgHAQAAQASAAANAGQAMAFAJAKQAIAJAEANQADAMAAAOQAAARgEAPQgEAOgKAMQgKAKgOAHQgPAGgUAAQgVAAgOgGgAmljFIgOAFIgMAIIgJAIIAAAMQAAANACAMQACAOAFAIQAFAKAIAFQAKAGAPAAQAWAAAMgOQAMgOAAgcQAAgvgsAAQgIAAgGACgAjqhhQAJgFADgDIAIgGQACgDABgFQADgEABgKIAMhkIBlAAIAACbIgcAAIAAiEIgwAAIgKBQQgBANgDAGQgCAJgFAFQgFAHgFAFQgIAFgLAGgABxhOIAAibIAcAAIAACDIA2AAIAAiDIAcAAIAACDIA1AAIAAiDIAcAAIAACbgAgxhOIAAibIAcAAIAAA9IApAAQASAAAKAEQAMAEAGAHQAHAHACAIQADAJgBAIQAAAVgOANQgPANgYAAgAgVhkIAqAAQAMAAAIgGQAIgGAAgNQAAgNgJgGQgHgGgRAAIglAAgAkihOIAAiFIgRAAIAAgWIAuAAIAACbgAkjkIQgFgFAAgJQAAgJAFgFQAEgGALAAQAJAAAFAGQAEAGABAIQgBAJgEAFQgFAGgJAAQgLAAgEgGgApwljIAAgrIiRAAIAAArIgdAAIAAhDIASAAQAHgJAFgHQAEgHAGgOQAEgOADgNIAQiBIB7AAIAADBIARAAIAABDgArTnfIgGAXQgDAMgEAHQgDAGgGAJIBnAAIAAipIhCAAgAIZmOQgOgGgKgLQgJgKgFgQQgDgQAAgRQAAgSAEgOQAGgQAKgLQAJgLAQgHQAPgGAUAAQASAAANADIAXAIIgIAWIgYgHQgJgCgMAAQgNAAgKAEQgLAFgFAIQgGAHgEAMQgDANAAAKQgBAdANAOQAOAPAXAAQANAAALgCQAMgCANgFIAIAWQgJAEgQAEQgPADgRAAQgWAAgPgGgAFvmOQgOgFgKgLQgKgMgEgOQgEgPAAgTQAAgQAEgPQAFgQAKgLQAIgMAOgGQAOgHATAAQAjAAARAUQAQATAAAnIgOANIhjAAQABAXANANQANAOAYAAIANAAIAmgJIAIAVIgZAIQgPAEgUAAQgWAAgPgGgAG2npQAAgMgDgJQgEgKgEgEQgFgFgHgCQgJgDgHAAQgUAAgMAMQgJAMgDAVIBTAAIAAAAgAiDmLQgKgDgIgFQgIgGgFgJQgEgJAAgNQAAgMAFgKQAFgKAIgGQAJgGAKgDQAMgDALAAIApAAIAAgJQAAgUgIgIQgIgHgSAAQgLAAgLACQgIABgSAGIgGgVIAZgIQAOgDATAAQARAAAMAEQANAFAFAHQAGAHADAMQACAKAAAPIAABGIANATIgTAPIgPgQQgHAFgOAGQgOAGgRAAQgKAAgLgDgAiAnNQgIAHgBANQABAHACAFQADAGAEACQAEADAGACIANABQANAAAJgFIARgKIAAgmIgoAAQgOAAgJAHgAKKmgIANgIIAIgHIAGgHQADgEACgJIACgIQgQgFgHgKQgJgJAAgSQABgbAQgMQAPgNAbAAIBCAAIAACbIgcAAIAAg6IgmAAIgGAVQgDAJgIAKQgGAHgHAFQgJAHgKAEgAKwoMQgHAGgBAPQAAAHACAEQADAFAEACIAJAEIALABIAoAAIAAgxIgmAAQgOAAgJAFgAnYmPQgQgFgLgHIAMgVIAKAFQAHADAGACIAOADIAOACQARAAAKgGQAJgGAAgNQAAgLgHgGQgGgGgRAAIgmAAIAAgYIAiAAQAQAAAHgGQAGgHAAgKQAAgLgIgFQgIgGgOAAQgLAAgOAEQgMAEgKAFIgLgUIAYgKIASgEIAVgCQAdAAAMALQANAMAAASQgBAYgVAMQAPAGAGAIQAHAJAAAOQAAAXgRAMQgQAOghAAQgUAAgQgFgADfmOIAAiDIg3AAIAAgYICKAAIAAAYIg3AAIAACDgABxmOIAAhlIhMBPIAAAWIgcAAIAAibIAcAAIAABlIBMhOIAAgXIAcAAIAACbgAjnmOIAAhFIhNAAIAABFIgcAAIAAibIAcAAIAAA/IBNAAIAAg/IAcAAIAACbgAormOIAAiFIgSAAIAAgWIAuAAIAACbgAAopLQgPgKgFgTIAXgIQADAKAJAIQAIAHAOAAQAPAAAIgHQAJgIADgKIAXAIQgCAIgFAIQgHAJgGAEQgKAGgIACQgIADgMAAQgWAAgPgLgAoupIQgEgGAAgIQAAgHAEgHQAFgGAKAAQAKAAAFAGQAEAHAAAHQAAAIgEAGQgFAGgKAAQgKAAgFgGg");
	this.shape.setTransform(86.5,63.5);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,1,172.9,125.1);


(lib.log = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.l();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,80,55);


(lib.fari = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AHnBJIgHgZIgPgMIAMg6QDDgZAhgKQAggKBQgNIASgFQARABgKAdQgJAegBAVQgBAIABAEIAAAUQiWA0iqANgAsoA1QgIgDgIgIQgQgPgDgTQgDgRACgYQADgSADgGIAbgjQA8AgAXAIIBGAWIAlBTIg3ADIgWAbIgcAIg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-84.6,-9.3,169.3,18.8);


(lib.logo = function() {
	this.initialize();

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E1192C").s().p("AAnBjQgogpAAg6QAAg5AogqQApgpA8gBQA6ABApApQAqAqABA5QgBA6gqApQgpAqg6ABQg7gBgqgqgABTg+QgXAaABAkQgBAkAXAbQAXAaAiABQAggBAXgaQAXgbAAgkQAAgkgXgaQgXgbggABIgBAAQghAAgXAagAoFBjQgpgpAAg6QAAg5ApgqQAqgpA7gBQA6ABAqApQApAqABA5QgBA6gpApQgqAqg6ABQg7gBgqgqgAnYg+QgXAaAAAkQAAAkAXAbQAXAaAhABQAggBAXgaQAXgbAAgkQAAgkgXgaQgXgbggABIgBAAQghAAgWAagALYCGIgXg8IhsAAIgXA8IhHAAIBwkHIBLAAIBtEHgAJnAeIBLAAIglhggAF/CGIAAjXIhWAAIAAgwIDkAAIAAAwIhSAAIAADXgAipCGIAAhlIhpiiIBHAAIBABwIBDhwIBEAAIhpCiIAABlgArLCGIAAjXIhTAAIAAgwIDhAAIAAAwIhTAAIAADXg");
	this.shape.setTransform(-0.8,70.7);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-80.7,56.5,159.9,28.5);


(lib.car_1 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.car();
	this.instance.setTransform(-160.5,-85);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-160.5,-85,321,170);


(lib.camry = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#DE0015").s().p("EA37ANEIDeh9QEdirE+jjQhmjDiGiwQjVkajfiLIDNgIQDrgECWARIGDIxQFUkCFNkkIDEgFQDbgDB0AOQjcDDk+EEQp7IFnpFBQhwAMiMAGQhQAEhFAAQirAAhkgWgEAviAI6QhcgIhQgLIg9gKQjzikjsjXIioiiIAHgRIB1ADQC0AEC4ABQC7AAByhCQBJgrAvhNQAbgtgVgXIgcgOQhOgRlqAHIlbAKIhdEEIgbgBIAUASIjDIdIn3AAQDDlkB0l2QA6i9ATh1QRGgmGDAmQCoAQBHAhQA3AZAMAuQAYBTgjBYQgoBoh2BbQiKBojwA1QhLARhMAJIg9AGQEDC/EXB7QCLA+BYAXQh6AHh3AAQi3AAizgQgALBIdQAwj2A+kJQAgiCAWhUQAMguggAAQghABgoAyQgfAmj/FYIj6FSIlhAAIhMpHQgMhigOglQgNgkgZgIQgdgJgTAcIgOAdIkRLKIncAAQDRlZCel2QBQi8Alh3QCDgPCvgBQBzAACkAGQBgADApA4QAUAcACAbIA8GIIEnmNQAkgyBDgaQAigOAbgDQC6gTEhAFQCRACBrAGQhqEwhLGGQgmDFgQCHgEgtDAIdIEsjmINBAAIi3ogQkKB0niFUQiXBqiaB1Ih8BfIpsAAQEmjRLRmxQFojaEuiwIIHAAQBcFqCNF0QBHC7A0BzgEhZXAH2QhPgFg5gpQhxhSBwixQDtlzEAjxQGumVHMgZQGmgXHRAXQD/ANFuAeIlpEiQkKgkkpgMQpTgXiaB7QikCDiRCqQhpB6hSB8IgNAXQgOAagEAXQgMBIBcAEQD/AJFkABQIsABFFgcImVEyQk3AJlzABIh0AAQqJAAkSgggEAhyAAAg");
	this.shape.setTransform(0,0,0.151,0.151);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-89,-12.9,178,25.9);


(lib.bgImg_1 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.bgImg();
	this.instance.setTransform(-150,-300);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-150,-300,300,600);


(lib.bg = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("EgXbAu3MAAAhdtMAu3AAAMAAABdtg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-150,-300,300,600);


(lib.ALWAYS_mc = function() {
	this.initialize();

	// red
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E0192C").s().p("ADsAXIgEgFIgEgDIgEgCIgEgBIgFAAIAAAoIgWAAIAAhqIAoAAQAJAAAGACQAHABAFAEQAFAEADAGQADAFAAAJQAAAGgCAFIgFAJIgHAFQgEADgFABIAEAEIAFAEIAXAcIgRANgADXgEIAPAAQAIAAAFgEQAFgEAAgIQAAgFgBgDQgCgDgCgCIgGgCIgHAAIgPAAgABiA0IAAhqIBNAAIAAATIg4AAIAAAXIArAAIAAARIgrAAIAAAcIA6AAIAAATgAAeA0IAAhXIgeAAIAAgTIBVAAIAAATIggAAIAABXgAg8A0IAAhXIgfAAIAAgTIBWAAIAAATIggAAIAABXgAizA0IAAhqIBOAAIAAATIg3AAIAAAXIAqAAIAAARIgqAAIAAAcIA5AAIAAATgAkXA0IAAhqIAqAAQAIAAAGACQAIABAFADQAEAEADAFQADAFAAAIQAAAIgEAFQgDAGgGADIAHAEIAGADQACADACAFQABAEAAAFQAAAIgCAGQgDAGgFAEQgFAEgHACQgHACgJAAgAkCAiIAYAAIAGgBQADgBACgCIAEgEQABgDABgDQgBgFgBgCQgCgDgDgCIgGgCIgIgBIgUAAgAkCgKIATAAQAHAAAFgDQAEgDAAgHQAAgHgEgDQgGgCgKAAIgPAAg");
	this.shape.setTransform(31.2,29.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#A6A8A9").s().p("AFWBuIgqAAIgKAhIgVgFIAahWIADgJIAGgHQACgCAGgCQAEgBAHAAIAKABIAIAEQADADABADIAEAJIAaBXIgXAFgAE+AzIgCAEIgLAkIAgAAIgKgkIgDgEIgCgBIgEABgADOCOQgGgCgFgDIgLAFQgFABgHAAQgJAAgFgCQgGgCgFgEQgDgEgCgGIgEgMIgJhPIAWgDIAKBOQABAIACADQAEADAGAAIAFAAIAFgCIAAhYIAXAAIAABYIAEACIAFAAQAGAAADgDQAEgDABgIIAJhOIAWADIgJBPIgDAMQgDAGgEAEQgEAEgFACQgHACgIAAQgHAAgFgBgAGgCNIAAglQgGgCgEgFIgHgMIgVguIAUgIIAXAxIADAEIAEABIAEgBIACgEIAXgxIAUAIIgUAsQgEAIgEAGQgEAFgGACIAAAlgAEYg/IgrAAIgKAhIgVgFIAahWIADgJIAGgHQADgCAFgCQAFgBAGAAIAKABIAIAEQADADABADIAEAJIAbBXIgXAFgAEAh6IgDAEIgKAkIAgAAIgLgkIgCgEIgDgBIgDABgABsgeIgLgDIgKgCIgHgDIAHgTQAJAEAJACIARACQALAAAGgEQAGgEAAgGQAAgEgCgCQgBgDgEgBIgGgDIgKgCIgOgDQgGgCgFgDQgFgEgEgFQgDgGAAgIQAAgHADgGQACgGAFgFQAGgEAIgDQAJgCALAAQAMAAAJACIARAFIgFASIgSgEQgIgCgIAAQgKAAgEADQgGADAAAGIABAFIAFAEIAGACIAJACIAOAEQAHABAGAEQAFAEAEAGQADAFABAJQAAAIgEAHQgDAGgGAFQgGAEgIADQgJACgLAAIgOAAgAg5g/IgqAAIgKAhIgWgFIAahWIAEgJIAFgHQADgCAFgCQAEgBAHAAIAKABIAIAEQADADACADIADAJIAaBXIgWAFgAhRh6IgCAEIgLAkIAgAAIgKgkIgDgEIgDgBIgDABgAjCgfQgGgCgFgDIgKAFQgGABgGAAQgJAAgGgCQgGgCgEgEQgEgEgCgGIgDgMIgJhPIAVgDIAKBOQABAIADADQADADAHAAIAEAAIAGgCIAAhYIAWAAIAABYIAFACIAFAAQAFAAAEgDQADgDABgIIAJhOIAXADIgKBPIgDAMQgCAGgEAEQgEAEgGACQgGACgIAAQgHAAgGgBgAmSg/IgrAAIgKAhIgVgFIAahWIADgJIAGgHQADgCAFgCQAFgBAGAAIAKABIAIAEQADADABADIAEAJIAbBXIgXAFgAmqh6IgDAEIgKAkIAgAAIgLgkIgCgEIgDgBIgDABgAAPggIAAglQgHgCgDgFIgFgMIgVguIAUgIIAUAxIAEAEIADABIAEgBIADgEIAWgxIAUAIIgUAsQgEAIgEAGQgEAFgGACIAAAlgAllggIAAhsIAWAAIAABZIA5AAIAAATg");
	this.shape_1.setTransform(50,20.8);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,99.9,41);


(lib.logo_ = function() {
	this.initialize();

	// ЗАВЖДИ КРАЩЕ
	this.instance = new lib.log();
	this.instance.setTransform(0.5,42.5,1,1,0,0,0,40,27.5);

	// ALWAYS A BETTER WAY
	this.instance_1 = new lib.ALWAYS_mc("synched",0);
	this.instance_1.setTransform(-0.4,187.3,1,1,0,0,0,49.8,21.3);

	// logo
	this.instance_2 = new lib.logo();
	this.instance_2.setTransform(0.5,42,0.582,0.581);

	// Layer 5
	this.instance_3 = new lib.pr();
	this.instance_3.setTransform(0,106.5,0.693,0.967,0,0,0,88,110.1);

	this.addChild(this.instance_3,this.instance_2,this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-61,0,122,213);


(lib.banner = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// urText
	this.instance = new lib.urText();
	this.instance.setTransform(0,225.3,1,1.001);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(208).to({_off:false},0).to({alpha:1},10).wait(44).to({alpha:0},10).to({_off:true},1).wait(5));

	// logoTxt
	this.instance_1 = new lib.Symbol1();
	this.instance_1.setTransform(101.4,-183.7,1.256,1.256);
	this.instance_1.shadow = new cjs.Shadow("#000000",0,0,5);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(193).to({scaleX:3.91,scaleY:3.92,x:0,y:63.6},15).wait(54).to({scaleX:1.26,scaleY:1.26,x:101.4,y:-183.7},15).wait(1));

	// logoZnack
	this.instance_2 = new lib.logo_("synched",0);
	this.instance_2.setTransform(132.2,-300.3,0.515,0.515,0,0,0,60.8,0);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(193).to({startPosition:0},0).to({regX:61,scaleX:1.6,scaleY:1.61,x:97.9,y:-299.8},15).wait(54).to({startPosition:0},0).to({regX:60.8,scaleX:0.52,scaleY:0.52,x:132.2,y:-300.3},15).wait(1));

	// t6
	this.instance_3 = new lib.t_6();
	this.instance_3.setTransform(2.2,1.5,1.388,1.388,0,0,0,88,64.5);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(144).to({_off:false},0).to({alpha:1},10).wait(29).to({alpha:0},10).to({_off:true},1).wait(84));

	// bg
	this.instance_4 = new lib.bg();
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(134).to({_off:false},0).to({alpha:0.852},10).wait(118).to({alpha:0},15).wait(1));

	// t1_3
	this.instance_5 = new lib.t1_3();
	this.instance_5.setTransform(12.5,57.3);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(66).to({_off:false},0).to({x:-4.5,alpha:1},6).wait(62).to({alpha:0},10).to({_off:true},1).wait(133));

	// t1_2
	this.instance_6 = new lib.t1_2();
	this.instance_6.setTransform(-19.9,22.3);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(60).to({_off:false},0).to({x:-36.9,alpha:1},6).wait(68).to({alpha:0},10).to({_off:true},1).wait(133));

	// t1_1
	this.instance_7 = new lib.t1_1();
	this.instance_7.setTransform(13.3,-11.1);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(54).to({_off:false},0).to({x:-3.7,alpha:1},6).wait(74).to({alpha:0},10).to({_off:true},1).wait(133));

	// fari
	this.instance_8 = new lib.fari();
	this.instance_8.setTransform(-52.2,175.9);
	this.instance_8.alpha = 0;
	this.instance_8.compositeOperation = "lighter";
	this.instance_8._off = true;
	this.instance_8.filters = [new cjs.BlurFilter(4, 4, 1)];
	this.instance_8.cache(-87,-11,173,23);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(94).to({_off:false},0).to({alpha:0.379},2).wait(3).to({alpha:0},2).wait(3).to({alpha:0.379},2).wait(3).to({alpha:0},2).to({_off:true},1).wait(166));

	// car
	this.instance_9 = new lib.car_1();
	this.instance_9.setTransform(-10.5,183.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(134).to({alpha:0},10).to({_off:true},1).wait(117).to({_off:false},0).to({alpha:1},15).wait(1));

	// camry
	this.instance_10 = new lib.camry();
	this.instance_10.setTransform(-243,-230);
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(14).to({_off:false},0).to({x:-45},20,cjs.Ease.get(1)).wait(100).to({alpha:0},10).to({_off:true},1).wait(133));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("EgXbAlGMAAAhKLMAu3AAAMAAABKLg");
	mask.setTransform(0,-62.5);

	// round
	this.instance_11 = new lib.round();
	this.instance_11.setTransform(-0.6,308);
	this.instance_11.alpha = 0.73;
	this.instance_11._off = true;

	this.instance_11.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(14).to({_off:false},0).to({y:26},20).to({alpha:0.5},5).to({alpha:0},5).wait(100).to({_off:true},1).wait(133));

	// roundBg
	this.instance_12 = new lib.roundBg_1();
	this.instance_12.setTransform(-0.7,26);
	this.instance_12.alpha = 0;
	this.instance_12._off = true;

	this.instance_12.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(34).to({_off:false},0).to({alpha:1},10).wait(90).to({alpha:0},10).to({_off:true},1).wait(133));

	// bgImg
	this.instance_13 = new lib.bgImg_1();

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(278));

	// bg
	this.instance_14 = new lib.bg();

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(278));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-171,-300.3,321,600.3);


// stage content:
(lib._300x600 = function() {
	this.initialize();

	// cover
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#999999").ss(2,1,1).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape.setTransform(150,300);

	// banner
	this.instance = new lib.banner();
	this.instance.setTransform(150,300);

	this.addChild(this.instance,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(129,299,322,602);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;