(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 300,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	manifest: [
		{src:"images/img1.jpg", id:"img1"},
		{src:"images/img2.jpg", id:"img2"},
		{src:"images/l.png", id:"l"},
		{src:"images/logo3.png", id:"logo3"},
		{src:"images/speed1.png", id:"speed1"},
		{src:"images/speed2.png", id:"speed2"},
		{src:"images/wheel.png", id:"wheel"}
	]
};



// symbols:



(lib.img1 = function() {
	this.initialize(img.img1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1224,677);


(lib.img2 = function() {
	this.initialize(img.img2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.l = function() {
	this.initialize(img.l);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,80,55);


(lib.logo3 = function() {
	this.initialize(img.logo3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,172,171);


(lib.speed1 = function() {
	this.initialize(img.speed1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,100,100);


(lib.speed2 = function() {
	this.initialize(img.speed2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,100,100);


(lib.wheel = function() {
	this.initialize(img.wheel);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,40,40);


(lib.і = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgaBJIAPhRIgOAAIAFgVIApAAIgTBmgAAAgoQgCAAgCgDQgCgDgBgCIAAgGQAAgIAFgFQAEgGAJABQAEgBADACIAFADIADAGIABAGQAAAIgGAFQgFAFgJAAQgFAAgCgCg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-2.7,-7.4,5.5,14.8);


(lib.є = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgXA0QgGgDgGgGQgEgFgDgJQgCgIAAgJQAAgMAEgLQADgLAJgLQAHgJAMgGQAKgGAPAAQAIAAAIADQAHACAGAEIgKASIgKgFIgJgBQgHAAgEACIgGAFQgEAFgCAEIgDAJIAiAAIgEATIgiAAQgBAWAQABIALgCQAFgBAHgDIAFASIgQAHQgIACgKAAQgKAAgIgDg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-4.5,-5.5,9.1,11.1);


(lib.я = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgxAsQAJgIAHgIQAGgJAFgLIgGgFIgEgFIgCgHIgBgGQAAgKADgHQAEgIAGgEQAHgFAIgCQAIgDAKAAIAKABIAdAFIgSBkIgdAAIAIgmIgFAAIgGgBQgBAIgHAOQgGAJgNALgAgCgdQgEAFAAAGQAAAIAFAEQADADAIAAIAEAAIAFgeIgLgBQgIAAgCAFg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-5,-5.5,10.1,11.1);


(lib.ь = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgaAzIgRgEIARhjIAcAAIgGAsIAIgDQAFgCAHAAQAMAAAIAIQAIAFAAAPQAAAIgCAGQgCAHgHAFQgFAFgLADQgKAEgPAAgAgHAJIgEAYIADABIADAAQAJAAAEgEQAGgEABgKQAAgFgDgDQgCgCgFAAQgFAAgHADg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-4.4,-5.3,8.9,10.6);


(lib.у = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgvBJQgKgEgCgCIAIgSIAIAEQAFACAHAAQAJAAAFgEQAEgDAFgKIAEgKIgDAAQgJAAgEgCQgFgBgEgEQgDgFgCgFQgBgGAAgFIgChHIAdgDIABBKQAAAGACACQACACADAAIABAAIAghUIAbAFIgrBuQgEAKgFAHQgFAHgEADQgGAEgHACIgOABQgKAAgJgCg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-6,-7.5,12.1,15.2);


(lib.т = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAgA1IANhJQAAgEgBgCQgCgDgGAAQgFAAgEAFQgEAEgDAKIgMA/IgbAAIAMhEIAAgFQAAgFgBgCQgCgCgFAAQgGAAgFAFQgEAFgCAJIgMA/IgdAAIAOhOIgFgRIAXgKIAIAOQAGgIAHgCQAGgEALAAQAEAAAHAEQAGADAFAHQAGgGAIgEQAHgEAKAAQAEAAAIACQAEACADADQADAEABAEQABAFAAAFIAAAIIgCAJIgKA/g");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-7.5,-5.4,15,10.8);


(lib.с = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgXA0QgIgDgEgFQgFgGgCgIQgCgGAAgKQAAgOAEgKQADgMAJgLQAGgIANgHQAKgGAOAAQAJAAAIADQAGACAHAEIgKASQgGgEgEgBIgKgBQgHABgHAEQgDAFgEAGQgEAHgCAIIgCAMQAAAYAPAAIALgCIAMgEIAFASIgRAHQgHACgKAAQgKAAgIgDg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-4.5,-5.5,9.1,11.1);


(lib.р = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ag2BLIAWh5IgGgRIAZgLIAHAOQAGgGAFgEQAIgDAJAAQAPAAAJAKQAJAKAAASQAAASgEAMQgEALgIAKQgJAKgLAEQgMAGgMgBIgNgBIgHApgAAAgtQgDAFgDAJIgIAsIAIABQAFAAAFgEQAGgDAEgHQAFgEADgKQADgJAAgLQAAgJgEgDQgDgFgGAAQgHABgFAFg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-5.6,-7.6,11.1,15.2);


(lib.п = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAIA1IAMhDIABgGQAAgFgCgCQgCgDgGAAQgHAAgEAFQgGAGgDALIgLA9IgeAAIAPhPIgGgQIAZgKIAIAOQAFgGAGgEQAHgEAKAAQARAAAHAIQAGAIABAOIAAAIIgNBDg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-5.1,-5.3,10.2,10.8);


(lib.о = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgaA0QgGgDgHgGQgEgFgDgJQgCgHAAgIQAAgQAFgNQAGgOAHgHQAIgJAKgFQALgEAIAAQALAAAJAEQAJAEAEAFQAFAGACAJQACAGAAAJQAAAQgEAMQgGANgHAIQgHAIgMAFQgLAEgJAAQgMAAgHgDgAgEgbQgEADgEAIQgDAGgCAJIgBANQAAAKADAGQAEAFAGABQAFAAAFgFQAEgDAEgIQADgGACgJQABgGAAgJQAAgKgDgFQgEgFgGAAQgGAAgEAFg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-5,-5.5,10,11.1);


(lib.н = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AADA0IAIgsIgZAAIgHAsIgeAAIAThnIAdAAIgHAoIAZAAIAHgoIAeAAIgTBng");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-5.2,-5.2,10.4,10.5);


(lib.м = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAQA0IALg8IgPAXQgEAHgEACQgEACgEAAQgFAAgEgDQgEgCgBgIIgGgVIgKA8IgbAAIAShnIAhAAIAJAvIABADIAAABIABgBIAcgyIAhAAIgSBng");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-6.2,-5.2,12.5,10.5);


(lib.л = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ag1AqQAJgIAFgHIAGgPIAShBIBFAAIgTBoIgdAAIAOhSIgPAAIgLAvQgCAKgGAJQgHAKgLAJg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-5.4,-5.4,10.9,10.8);


(lib.к = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgEAJIgJAAIgHArIgeAAIAThnIAdAAIgHApIAEAAIAEgBIABgDIAVgfIAHgEIAIgCIAKgBIAFASQgHAAgCACIgGAGIgPAVIgDAEIAUAwIgaAGg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-5.1,-5.3,10.2,10.8);


(lib.и = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAKAnQgGAHgEAEQgHADgLABQgKgBgFgBQgFgDgEgEQgDgCgCgHQgCgFAAgFIAAgJIAOhGIAdAAIgMBAIgBALQAAAFACACQACADAHAAQAHgBACgEQAEgDADgJIAMhEIAeAAIgPBQIAJAQIgYALg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-5,-5.4,10.1,10.8);


(lib.з = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgaAzQgKgEgIgGIANgSIANAHQAGADAJABQAGgBAEgDQAEgDAAgHQAAgFgDgDQgDgDgFAAIgTAAIADgSIAQAAQAJgBADgDQAEgEAAgFQAAgKgLAAQgFAAgFACIgOAGIgIgSIAIgEIAKgEIAJgDQAGgBAHAAQARAAAHAIQAIAHAAAMIgBAJIgFAHIgGAFIgHAGIAFAAIAFAFIADAFIABAJQAAAJgDAGQgDAGgGAFQgGAFgIADQgHACgKAAQgOAAgJgEg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-4.6,-5.5,9.1,11.1);


(lib.З1 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgWBJIgNgDIgLgGIgJgHIAOgTQAIAGAJADQAIAEAKAAQAKAAAGgFQAIgFgBgMQABgLgHgEQgGgEgIAAIgXAAIAEgVIAWAAQAFAAAHgCQAGgDACgDQADgDACgEIABgIQgBgIgEgEQgEgEgIAAQgHAAgIACIgRAHIgJgTIAXgKQALgEAPAAQAKAAAIADQAGADAGAFQAEAEADAHQACAHAAAGQAAANgFAJQgGAJgNAIQAHABAGAIQAEAIAAALQAAAMgEAHQgDAJgHAGQgHAGgLAEQgKADgMAAQgJAAgIgCg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-5.7,-7.5,11.4,15.1);


(lib.е = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgZA0QgHgEgEgFQgFgGgBgHQgCgHAAgIQAAgNAEgLQADgMAIgLQAIgKALgFQAKgHANAAQAIAAAHACQAGACAEAEQAEAFABAEQACAEAAAFQAAALgFAIQgGAIgHACQgIAGgMACQgLADgLgBIAAALIADAFIAFAFQADABAEAAIALgCIANgFIAGATIgRAHQgJADgKAAQgLAAgIgDgAgDgaQgGAJgEANIANgDQAGgBAEgDQADgDACgDQACgEAAgEQAAgDgDgDQgCgCgDAAQgIAAgEAHg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-4.5,-5.5,9.1,11.1);


(lib.д = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgbBHQgHgCgGgHQgFgGgCgHQgCgGAAgJQAAgKADgMQADgKAGgGQAGgIAJgGQAJgEAMAAQAHAAAGAEQAHAEAEAHIAAgIQAAgVgFgIQgGgIgKAAIgKABIgLADIgFgTIARgFIANgCQANAAAIAFQAJAFAEAIQAFAHADALQACAKAAANIgBAQIgDAUQgCAKgEAKQgFALgGAGQgHAIgJAEQgKAFgLAAQgMAAgHgEgAgHABQgEACgDAGIgEAMIgBAMQAAAKADAFQAEAFAHAAQAFAAAEgDQAEgDACgFQADgHABgFIABgMQAAgTgOAAQgFAAgDACg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-5,-7.5,10.1,15.1);


(lib.г = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgVA1QgHgEgDgEQgDgDgCgFIgBgKQAAgHACgEIAGgJIAKgHIATgKIAIgJQACgCAAgEQAAgIgIAAQgCAAgGACIgPAIIgKgRIAVgLIAKgCIAIgBIALABQAHACADACQAEAEADAEQACAFAAAIQAAAGgBAFIgFAJIgJAIIgZAPIgFAFQgCADABADQAAAEABACQADACADAAQAFAAAGgDIANgFIAIASQgKAFgJADQgJADgIAAQgIAAgIgCg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-3.9,-5.5,7.8,11.1);


(lib.в = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AghAsQgKgKAAgVQAAgNADgJQAEgMAHgKQAHgLALgFQALgHALAAQAPAAAJAHQAJAFAAANQAAAJgGAIQgGAGgKAFIAHABIAGADQACADACAEQABAEAAAEQAAALgDAGQgEAHgGAEQgHAFgIACQgIACgHAAQgVAAgJgLgAgHAJIgIACIAAAJQAAAEACAEQABADAEADQACACAEgBQAEAAAFgDQAFgEAAgJQAAgGgEgCQgEgCgEgBgAAAggQgDACgDAEIgFAKQgDAFAAAGQAKgBAEgCQAFgCAEgEQAEgCABgEQACgDAAgEQAAgFgDgBQgCgBgDgBQgEABgEACg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-4.5,-5.5,9,11.1);


(lib.а = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AALArQgHAGgEADQgHADgKAAQgQAAgIgKQgIgKAAgTQAAgPAFgLQAFgPAIgIQAJgJAMgHQALgFAPAAQAJAAALACIAOAEIgOBNIAJAPIgXALgAAAgdQgEADgFAIQgFAGgCAKQgDAHABAKQAAAIACAFQADAGAHAAQAGgBACgDQAFgEABgJIAKgzIgCAAIgCAAQgJAAgFAFg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-5,-5.5,10.1,11.1);


(lib.wheelMc = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.wheel();
	this.instance.setTransform(-20,-20);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-20,-20,40,40);


(lib.urText = function() {
	this.initialize();

	// Print
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAeEcIgLgCIACgNIAUADQAGAAAFgDQAFgDACgHIACgKIgHAAQgGAAgFgBQgDgBgEgEQgDgCgCgGIgEgKIgPg+IAPgDIARBEIADAEQACADADAAIAGACIAHgBIAThMIAPADIgZBhQgCAHgDAFQgDAFgFACQgFAEgEABIgLABgAIVD5QgFgBgFgFQgEgDgDgFQgCgEAAgIQAAgGACgGQADgGAFgDQADgDAHgCQAGgBAHgBIAXAAIAAgDQAAgMgEgEQgFgEgJAAIgNABIgNAEIgFgMQAIgDAGgBQAHgCALAAQALAAAGACQAGADAEAFQADAEACAGIABA0IAHAKIgKAIIgIgJIgGAEIgHADIgIACIgJABIgMgBgAIXDUQgFADAAAHQAAAFABADQACADACABIAGADIAHAAQAHAAAGgDIAKgFIAAgVIgYAAQgHAAgFAEgAGzD3QgGgCgEgFQgDgEgCgGQgBgHAAgGIAAg3IAPAAIAAA2QAAALAFAFQAFAEAJABQAHAAAHgDIAKgFIAAhDIAQAAIAABFIAHAKIgLAIIgIgIQgGAEgIADQgJACgHAAQgKAAgGgDgAEnD5QgEgBgGgFQgDgBgEgHQgDgFAAgHQAAgHADgFQADgGAFgDQAEgDAGgCIAMgCIAYAAIAAgDQAAgLgEgFQgFgEgJAAIgNABIgOAEIgEgMQAIgDAGgBQAHgCALAAQAKAAAHACQAGADAEAFQAEAEABAGQABAIAAAHIAAAlIAHAKIgKAIIgJgJIgFAEIgHADIgIACIgJABQgHAAgFgBgAEpDUQgFADAAAHQAAAFABADQACADACABIAGADIAHAAQAHAAAGgDIAKgFIAAgVIgYAAQgHAAgFAEgACED3QgJgEgEgGQgEgGgDgJQgCgHAAgLQAAgJACgIQAEgKAEgFQAFgGAIgEQAIgDALAAQAMAAAHADQAIAEAFAGQAEAFAEAKQACAIAAAJQAAAJgCAJQgCAIgGAHQgEAGgJAEQgJADgKAAQgKAAgKgDgACEC0QgGAIAAAQQAAARAHAIQAHAIAMAAQAMAAAHgIQAHgJAAgQQAAgQgHgIQgGgIgNAAQgNAAgHAIgAg7D3QgJgEgEgGQgGgHgCgIQgCgHAAgLQAAgJADgIQADgKAFgFQAEgGAJgEQAHgDALAAQAMAAAHADQAIAEAFAGQAFAGADAJQAAAHAAAKQAAALAAAHQgCAIgFAHQgFAGgIAEQgKADgKAAQgKAAgJgDgAg7C0QgHAIAAAQQAAAQAHAJQAHAIAMAAQANAAAHgIQAGgJAAgQQAAgQgGgIQgHgIgNAAQgNAAgGAIgAj8D4QgGgBgFgEQgHAEgFABQgIACgFAAQgFAAgHgCQgFgCgDgDQgEgDgBgFQgCgCgBgHIgGg+IAPgCIAHA+IACAHQACADACAAIAFADIAEAAIAIgBQADgBADgDIAAhGIAPAAIAABGIAHAEIAHABIAFAAIAEgDQACAAACgDQACgBABgGIAGg+IAQACIgHA+QgBAHgCACQgBAGgEACQgDADgFACQgGACgGAAQgFAAgIgCgAmCD4IgMgFQgFAEgGABQgIACgFAAQgFAAgHgCQgEgBgFgEIgFgIIgCgJIgHg+IAQgCIAHA+QAAAEACADQACADACAAIAEADIAFAAIAHgBIAHgEIAAhGIAPAAIAABGQAEADADABIAHABIAEAAIAFgDQACAAACgDIACgHIAHg+IAPACIgGA+IgDAJQgBAFgEADQgFAEgDABQgHACgFAAQgFAAgIgCgAoID4QgFgBgHgEQgGAEgFABQgIACgFAAQgGAAgGgCQgFgCgEgDQgDgDgCgFIgCgJIgHg+IAQgCIAGA+IACAHIAEADIAFADIAFAAIAHgBQADgBAEgDIAAhGIAPAAIAABGIAGAEIAIABIAEAAIAFgDQACAAACgDQABgBABgGIAHg+IAPACIgHA+QAAAFgCAEQgCAGgDACQgEADgEACQgHACgFAAQgFAAgIgCgAF4D3QgCgEAAgFQAAgEACgEQADgDAGgBQAGABACADQADADAAAFQAAAFgDAEQgCADgGgBQgGABgDgDgAi7D3QgDgEAAgFQAAgEADgEQACgDAGgBQAGABADADQACAEAAAEQAAAFgCAEQgDADgGgBQgGABgCgDgADpD4QgFgCgDgDQgDgCgDgGQgCgEAAgJIAAgvIgMAAIAAgNIAMAAIAAgZIAQAAIAAAZIAcAAIAAANIgcAAIAAAsQAAAKADADQAEAEAHABIAQgDIADAMIgWADgAh7D4QgFgCgEgDQgCgCgDgGQgCgEAAgJIAAgvIgMAAIAAgNIAMAAIAAgZIAPAAIAAAZIAcAAIAAANIgcAAIAAAsQAAAKAEADQAEAEAHABIAQgDIADAMIgWADQgGAAgFgBgAFDBQIAAhoIgFgOIANgHIAGAJIAMgFQAIgCAHgBQATABAJAMQAKAKAAAVQAAALgCAIQgEAJgEAGQgGAFgIAEQgKAEgJAAIgUgDIAAAkgAFegcIgLAFIAAA1IAJADIAMABIAKgCQAFgDADgDQAEgEACgHQACgGAAgJQAAgFgCgHQgBgGgEgEQgDgEgEgCQgEgCgGAAQgFAAgHACgAKjAtQgFgBgFgDQgDgDgEgFQgCgHAAgFQAAgIADgGQADgFAEgCQAGgDAFgBQAGgCAGAAIAXAAIAAgFQAAgKgEgGQgFgDgKAAIgMABIgOADIgEgLQAHgDAHgCQAHgCALAAQAJABAIACQAFACAFAEQAEAFAAAGQACAGAAAIIAAAlIAHALIgLAIIgIgJIgMAHQgHADgKAAQgGAAgGgCgAKlAIQgFAEAAAHQAAAFACACQABAEADABIAFADIAHAAQAHAAAGgCIAJgHIAAgUIgWAAQgHgBgGAEgAG2AtQgFgBgFgDQgEgEgDgEQgCgHAAgFQAAgIADgGQACgFAFgCIALgEQAGgCAGAAIAXAAIAAgFQAAgLgFgFQgEgDgKAAIgMABIgOADIgEgLQAHgDAHgCQAGgCAMAAQAJABAIACQAFACAFAEQADAFABAGQACAGAAAIIAAAlIAHALIgLAIIgIgJIgMAHQgHADgKAAIgMgCgAG4AIQgFAEAAAHQAAAFABACQACADACACIAGADIAHAAQAHAAAFgCIAKgHIAAgUIgWAAQgHgBgGAEgAgQAtQgEgBgGgDQgDgDgDgFQgDgFAAgHQAAgJADgFQADgFAEgCQAGgDAFgBQAGgCAGAAIAVAAIAAgFQAAgMgEgEQgFgDgKAAIgKABIgOADIgEgLIAOgFQAHgCAJAAQAKABAHACQAGACAEAEQADAFACAGIABAOIAAAlIAHALIgLAIIgIgJIgMAHQgHADgIAAQgGAAgGgCgAgOAIQgFAEAAAHQAAAFACACQABADADACIAFADIAHAAQAFAAAGgCIAJgHIAAgUIgUAAQgHgBgGAEgAi8ArQgIgDgFgGQgEgGgDgKQgCgHAAgLQAAgGACgKQAEgIAEgGQAGgGAHgEQAKgDAJgBQAKABAJADQAHADAGAHQAEAGAEAIQACAKAAAGQAAAKgCAIQgCAJgGAHQgGAGgHADQgJAEgKAAQgLAAgJgEgAi8gWQgGAIAAAOQAAASAHAHQAHAJAMAAQANAAAGgJQAHgIAAgRQAAgOgHgIQgHgJgMABQgNgBgHAJgAmDArQgHgDgGgGQgFgJgCgHQgDgIAAgKQAAgHADgJQADgIAFgGQAFgHAIgDQAJgDAKgBQAJABAKADQAHAEAGAGQAFAGACAIQADAKAAAGQAAAKgDAIQgCAJgFAHQgFAGgIADQgJAEgKAAQgLAAgJgEgAmDgWQgHAJAAANQAAARAHAIQAHAJANAAQANAAAGgJQAHgIAAgRQAAgNgHgJQgGgJgNABQgNgBgHAJgAEIAGIgLAAIAAAmIgPAAIAAhVIAPAAIAAAjIAIAAIAEgBIADgDIAPgXQACgDAEgDQAEgDAFAAIADAAIAFACIgCAMIgBAAIgCAAIgEABIgEADIgOAXIgCABIAfAjIgLAKgACNArIACgNIALACIAGAAIAGgCIAEgFIAEgHIABgDQgJAAgGgEQgHgEgDgIIgZhHIAPgGIAYBFQACAIAEABQAEABAGAAIAbhPIAQAFIghBaQgDAKgDAEIgHAJIgKAEIgNABgAJsAsIAAgnIgrAAIAAAnIgPAAIAAhVIAPAAIAAAjIArAAIAAgjIAPAAIAABVgAIJAsIAAhIIgLAAIAAgNIAaAAIAABVgAhYAsIAAhIIgfAAIAAgNIBNAAIAAANIgfAAIAABIgAj2AsIAAg2IgrApIAAANIgPAAIAAhVIAPAAIAAA3IArgqIAAgNIAPAAIAABVgAnHAsIAAhrIgnAAIAAgNIBeAAIAAANIgnAAIAABrgApvAsIAAh4IAQAAIAAB4gAqbAsIAAh4IAQAAIAAB4gArHAsIAAhrIg8AAIAABrIgRAAIAAh4IBeAAIAAB4gAA+AAIAAgPIA1AAIAAAPgAMJgcIAAgwIAPAAIAAAwgALvgcIAAgwIAOAAIAAAwgAoKgcIAAgwIAPAAIAAAwgAokgcIAAgwIAOAAIAAAwgAkfg9QgJgFgCgKIAMgFQADAGAEAEQAFAFAIAAQAIAAAEgFQAEgEADgGIAMAFQAAAEgEAFQgCAEgFACQgDAEgGABIgLACQgMAAgJgHgAIYg8QgDgDAAgEQAAgFADgDQACgEAGAAQAGAAACAEQACACAAAGQAAAFgCACQgCADgGABQgFgBgDgDgAHyg8QgCgDAAgEQAAgGACgCQACgEAGAAQAGAAACAEQADADAAAFQAAAEgDADQgCADgGABQgGgBgCgDgAOJh4IAAhrIgGgOIAOgGIAFAJIANgGQAHgCAIAAQASAAAKALQAKALAAAXQAAAMgDAHQgDAJgFAFQgFAGgJAFQgJADgKAAIgUgDIAAAlgAOjjnIgLAFIAAA3IAJADIAMABIAKgCQAGgDACgDQAEgDACgIQADgGAAgIQAAgIgCgIQgBgFgEgFQgEgDgEgCQgEgCgFAAQgIAAgFACgAECh4IAAhrIgFgOIANgGIAGAJIAMgGQAIgCAHAAQATAAAJALQAKALAAAXQAAAMgCAHQgEAJgEAFQgGAGgIAFQgKADgJAAIgUgDIAAAlgAEdjnIgLAFIAAA3IAJADIAMABIAJgCQAFgCAEgEQAEgDACgIQACgFAAgJQAAgJgCgHQgBgFgEgFQgDgDgEgCQgEgCgGAAQgIAAgEACgAslh4IAAgiQgMgBgKgEQgJgEgGgGQgFgEgDgJQgDgKAAgHQAAgKADgIQADgIAGgGQAGgFAJgEQAJgDAMgBIAAgjIAPAAIAAAjQAMABAJADQAJAEAGAGQAFAGADAHQADAJAAAJQAAAHgDAJQgDAIgFAGQgFAFgJAEQgLAFgLABIAAAigAsWioQAQgBAIgIQAHgIAAgOQAAgdgfgEgAs9jeQgIAHAAAQQAAAOAIAIQAHAIARABIAAhAQgQABgIAJgAgliJIAAgUIg+AAIAAATIgPAAIAAghIAJAAIAHgLQAEgHABgHIACgJIACgnIA4AAIAABJIAKAAIAAAigAhOjAIgFAMIgFAJIAnAAIAAg8IgZAAQAAAVgEASgApgiJIAAgUIhFAAIAAhXIAPAAIAABJIAqAAIAAhJIAQAAIAABJIALAAIAAAigAM2ieQgJgEgEgGQgFgHgCgHQgCgIAAgKQAAgMACgGQACgJAGgGQAFgGAIgEQAKgEAJABQAJgBAKAEQAIAEAFAGQAFAGACAJQADAGAAAMQAAAKgCAIQgDAIgFAGQgFAGgIAEQgIAEgLAAQgMAAgIgEgAM2jhQgGAIAAARQAAAQAGAIQAHAJANAAQANAAAGgJQAHgIAAgQQAAgRgHgIQgHgJgMAAQgNAAgHAJgAKHidQgHgDgGgFQgFgHgCgGQgCgIgBgHIgSAAIAAAkIgPAAIAAhXIAPAAIAAAlIASAAQABgJADgHQADgHAEgFQAHgGAGgDQAHgCAKAAQAKgBAIAEQAIAEAFAGQAFAGACAJQACAIAAAKQAAAIgCAKQgCAGgFAIQgFAHgHADQgJAEgKAAQgLAAgHgDgAKGjhQgGAIAAARQAAAQAGAIQAGAJANAAQAMAAAGgJQAGgIAAgQQAAgRgGgIQgGgJgMAAQgNAAgGAJgAHaieQgJgEgEgHQgFgHgCgKQgCgJAAgNQAAgLACgKQABgKAFgIQADgHAHgHQAIgFAJgDIASgEIAGgEIAEgHIANAEIgBAHIgCAEIgDAEIgEADIgEABIgUAGIgLADIgHAHQgDAEgCAEIgCALQAEgEAJgFQAJgDAIAAQALAAAGADQAIAEAEAFQAEAFACAGQACAHAAAJQAAAKgCAIQgCAHgGAHQgFAFgIAFQgJADgKAAQgMAAgIgEgAHojgIgIADIgGAEIgFAFIgBAEIABARIAEAMQAEAGAEACQAGAEAHAAQANAAAHgIQAGgJAAgOQAAgbgYAAgABsidQgJgFgFgFQgFgGgCgIQgCgIAAgKQAAgMACgHQADgHAGgIQAGgHAIgDQAJgEAKABQALAAAGACIANADIgFANIgNgEIgMgBQgHAAgFACQgGADgDAEQgEAFgBAGQgCAFAAAJQAAAPAHAJQAHAHANAAIAOgBQAGgBAHgCIAFALQgGADgIACIgSACQgLAAgJgDgAu4igQgLgFgHgIQgHgKgDgLQgDgLAAgNQAAgMADgMQAEgMAHgIQAGgJALgFQALgGAPABQAOgBAMAGQALAFAGAJQAGAHAEANQADAMAAAMQAAANgDALQgDALgHAKQgHAIgLAFQgMAGgNAAQgPAAgLgGgAuwkIQgHAFgFAGQgFAGgCAKQgDAJAAAKQAAAJADALQACAIAFAIQAFAGAHAEQAHAEALAAQAKAAAHgEQAHgEAFgGQAFgIACgIQADgIAAgMQAAgMgDgHQgCgKgFgGQgFgHgHgEQgHgEgKAAQgLAAgHAEgALqidIAAhKIgeAAIAAgNIBMAAIAAANIgeAAIAABKgAGgidIAAg5IgqAsIAAANIgQAAIAAhXIAQAAIAAA4IAqgsIAAgMIAQAAIAABXgADFidIAAhKIgeAAIAAgNIBMAAIAAANIgeAAIAABKgAAwidIAAg5IgqAsIAAANIgOAAIAAhXIAOAAIAAA4IAqgsIAAgMIAQAAIAABXgAi0idIAAg5IgqAsIAAANIgQAAIAAhXIAQAAIAAA4IAqgsIAAgMIAQAAIAABXgAkWidIAAg5IgrAsIAAANIgPAAIAAhXIAPAAIAAA4IArgsIAAgMIAPAAIAABXgAl5idIAAgnIgqAAIAAAnIgQAAIAAhXIAQAAIAAAjIAqAAIAAgjIAQAAIAABXgAnbidIAAg5IgrAsIAAANIgPAAIAAhXIAPAAIAAA4IArgsIAAgMIAPAAIAABXgAo+idIAAhLIgKAAIAAgMIAZAAIAABXgArOidIAAhLIgKAAIAAgMIAZAAIAABXgAIqjnIAAgwIAOAAIAAAwgAjckHQgJgGgDgLIANgEQADAGAEAEQAEAEAIAAQAJAAAEgEQAEgEADgGIAMAEQAAAFgEAFIgHAHQgEADgFABQgHACgFAAQgLAAgJgGgAoEkHQgJgHgCgKIANgEQABAGAFAEQAEAEAJAAQAIAAAEgEQAFgEACgGIANAEQgCAGgDAEQgBADgGAEQgEADgFABIgLACQgLAAgKgGgAo/kGQgDgCAAgGQAAgEADgDQADgDAFAAQAGAAACADQADADAAAEQAAAFgDADQgCADgGAAQgFAAgDgDgArPkGQgDgDAAgFQAAgEADgDQACgDAGAAQAFAAADADQACAEAAADQAAAFgCADQgDADgFAAQgGAAgCgDg");
	this.shape.setTransform(0,9.6);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-98.4,-18.9,196.9,57.1);


(lib.t7 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E11A2C").s().p("AiDAeQgDgIgDgDQgEgCgIAAIgGAAIgNBFIglAAIAeisIA3AAQANAAAIADQAKABAHAGQAIAFADAIQAEAIAAAMQAAAWgLAMQgLAKgSAGQAFADAEAJIAYA/IgjAIgAiWgJIANAAQAIAAAFgCQAGgCAEgEQAFgEACgFQADgHgBgGQAAgLgFgEQgGgFgKAAIgQAAgAncBUQgKgGgIgIQgHgLgCgLQgDgMAAgOQAAgXAHgXQAIgWAMgNQALgPARgHQAQgIATAAQAPAAAMAEQAMAEAKAIIgPAYQgLgGgFgBQgIgEgKAAQgLAAgKAHQgIAFgHAMQgGAKgFAPQgEAOAAAQQABAIABAIQABAIAEAFQADAFAFADQAGAEAHAAQALAAAIgDIAVgJIALAZQgOAIgOAFQgOAEgRAAQgQAAgNgGgAFjBTIA+iPIAGgMQADgFAGgEQAGgFAFgBQAGgCAJAAQAQAAAHAHQAIAGACASIAQCOIglAFIgEgwIg3AAIgVAwgAHBg0IgEAIIgYA5IArAAIgGg5IgBgIQgBAAAAAAQgBgBAAAAQgBAAAAAAQgBAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBABQAAAAAAAAgAgTBUQgNgFgGgIQgIgJgEgNQgEgNAAgOQAAgWAHgTQAFgVAMgPQAMgRAQgIQAOgJAUAAQAQAAANAFQALAEAIAKQAKAKADALQAEANAAAOQAAAWgGAVQgGAVgMAPQgLAPgRAJQgRAIgUAAQgQABgLgGgAAKg1QgHAGgFANQgHAOgCANQgEAOAAARQABARAGAKQAGAKALAAQALAAAKgHQAKgIAFgLQAHgNACgPQAEgNAAgRQAAgSgGgKQgIgKgNAAQgLABgKAHgAlNBUQgNgFgGgIQgJgKgDgMQgDgLgBgQQAAgWAHgTQAFgWANgOQAKgQARgJQAQgJAUAAQARAAAMAFQALAEAJAKQAIAJAEAMQAEALAAAQQAAAWgGAVQgGAVgMAPQgLAPgRAJQgRAIgUAAQgRABgMgGgAktg1QgJAHgGAMQgGAMgDAPQgEANAAASQAAARAHAKQAGAKANAAQALAAAKgHQAKgHAFgMQAGgMAEgQQADgOAAgQQAAgSgGgKQgIgKgNAAQgLABgJAHgADtBWIAfisIAlAAIgZCOIBKAAIgEAegABsBWIAdisIAmAAIgZCOIBLAAIgGAeg");
	this.shape.setTransform(0,14.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("ACcBUIA/iQIAHgMQADgGAFgDQAFgEAGgCQAGgCAJAAQAPAAAIAHQAIAHABARIARCPIglAEIgEgwIg4AAIgVAxgAD7gzIgEAHIgZA5IArAAIgFg5QAAgFgCgCQAAgBAAAAQgBAAAAgBQgBAAAAAAQgBAAgBAAQAAAAgBAAQAAAAgBAAQAAABgBAAQAAAAAAABgAhpBVQgMgGgHgIQgHgJgEgNQgFgNAAgOQABgVAGgUQAGgVAMgPQAMgQAQgJQAPgJAVAAQAQAAAMAFQALAFAJAJQAHALAEALQADANAAAOQABAVgHAVQgFAXgLANQgKAPgSAJQgQAJgVAAQgRAAgMgFgAhJg1QgJAHgFAMQgGAMgEAQQgDAOAAAQQAAARAGAKQAHAKANAAQALAAAKgHQAJgIAGgLQAGgMADgQQADgMABgSQgBgRgGgKQgHgKgNAAQgMAAgJAHgAAWBWIAdirIA6AAQAKAAALACQAKADAGAFQAHAEAEAJQAEAHAAAKQAAAOgHALQgJAMgLAGQAKACAGAKQAFAJAAALQAAAOgFALQgFALgKAGQgKAHgNADQgMAEgQAAgABAA7IAYAAQAHAAAFgCQAGgCADgDQAEgDADgGQACgGAAgHQAAgFgCgEIgFgGIgIgDIgJgBIgWAAgABMgPIATAAQAMAAAJgHQAHgGAAgMQAAgJgFgEQgEgFgLAAIgUAAgAjYBWIANhMIg3AAIgMBMIgmAAIAeirIAmAAIgMBEIA2AAIAMhEIAlAAIgdCrg");
	this.shape_1.setTransform(-0.2,-14.4);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-50.7,-23.4,101.5,46.9);


(lib.t3 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AHkAvIgFgBIADgHIADABIAEABIAFgBIACgCIADgDIAFgLIgBAAQgGAAgCgDQgDgEAAgHIgFghIAJgBIAFAmIABADIACABIACAAIAAAAIASgqIAIABIgXA4QgDAHgFAEQgEADgIAAgANTAvIALg9IgDgIIAHgEIAEAIIAGgFQAFgDAEAAQAIAAADAFQAEAFAAAIQABAIgDAGQgDAIgEAEQgDAEgGACQgFADgGAAIgIgBIgEAVgANugSIgEADIgDAEIgCAGIgFAYIADABIAEAAIAIgBIAGgFIAFgKQABgEAAgHIgBgGIgBgDIgDgCIgEAAgADfAvIAKg9IgCgIIAHgEIAEAIQACgDAEgCQAFgDAFAAQAGAAAEAFQAEAFAAAIQAAAIgCAGQgCAGgFAGQgDAEgGACQgGADgFAAIgJgBIgDAVgAD6gSIgEADIgEAEIgBAGIgFAYIADABIAEAAQAEAAADgBIAHgFQACgEACgGQACgEAAgHIgBgGIgBgDIgDgCIgEAAgAlBAvIALg9IgCgIIAHgEIADAIIAHgFQAFgDAEAAQAIAAADAFQAEAEAAAJQAAAIgCAGQgCAIgEAEQgEAEgFACQgHADgFAAIgIgBIgEAVgAklgSIgEADIgEAEIgCAGIgEAYIADABIAEAAIAHgBIAHgFIAFgKQABgEAAgHIAAgGIgCgDIgDgCIgDAAgAuOAvIAEgaQgCADgDABQgDACgEAAQgHAAgEgFQgEgFAAgJQAAgHACgGQACgFAEgGQAEgFAFgCQAGgDAFAAIAHABIAEgUIAIAAIgEAZIAGgEQACgCAFAAQAHAAAEAFQADAFAAAIQAAAIgCAGQgDAIgDADQgEAFgFACQgDADgHAAIgFAAIgDgBIgEAVgAt4gPQgDADgBAGIgFAZIADABIAEABQACAAAFgCIAFgGQAEgEABgFQABgEAAgHIAAgGIgCgDIgDgCIgDAAQgFAAgDADgAuQgSQgDACgDAEIgEAJQgBAEgBAHQAAAHACACQADADAEAAIAEgBIADgCQAAAAABAAQAAgBABAAQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAABAAQAAgBAAgBQAAAAAAgBIAFgcIgCgBIgEAAQgEAAgDABgAAaAlIABgMIgCgCIgCgDIgGAFQgEACgGAAQgFAAgCgBIgCgDIgCgEIgBgFIAAgCIAAgCIAAgDIABgCIAEgdIAIAAIgGAgIAAADIgBACQAAAHAHAAQAGAAAEgEQAEgDACgIIAFgdIAIAAIgHAkIAAAEQAAAAAAABQAAAAAAABQAAAAABAAQAAABAAAAIADABIACAAIgDARgAsaAlIADgMIgDgCIgDgDIgGAFQgDACgGAAIgHgBIgEgDIgDgEIAAgJIAHgiIAIAAIgGAeIAAACIgBADIAAACQAAAHAIAAQAFAAAEgEQAEgCABgJIAFgdIAJAAIgIAoIABADIAGABIgEARgAOqAUIgGAFQgDACgFAAQgHAAgEgFQgEgFAAgIQAAgIACgFQADgHADgEQAEgFAGgDQAGgDAHAAIAIABIAGACIgIAnIAEAHIgHAEgAOigRQgDACgDAEIgEAJQgBADgBAGIABAHIABADIADACIADABIAEgBIAEgCIADgEIACgGIAGgZIgDgBIgEAAQgEAAgEACgAK5AWQgEgFgBgKIACgKIAFgLQACgFAGgDQAFgEAHAAQAGAAAEAEQAEADAAAFIgBAFIgDAEIgDADIgFACQAFAAACACQADACAAAGQAAADgCAEQgCAEgCACQgDACgEABIgIABQgJAAgEgFgAK9AEIAAACIABAGQAAABAAAAQAAABAAAAQABABAAAAQAAABAAAAQABABAAAAQAAABAAAAQABAAAAABQABAAAAAAIAFABIAEAAIAEgCIACgEIABgFIgBgDIgCgDIgCgBIgEAAgALHgSIgEAFIgDAGIgCAGIAKgCQAFgBACgCIADgDIACgEQAAgBAAAAQAAgBAAgBQgBAAAAgBQAAAAgBgBQAAAAgBAAQgBgBAAAAQgBAAAAAAQgBAAAAAAQgEAAgDABgAKKAUIgGAFQgEACgEAAQgHAAgFgFQgEgFAAgIQABgIACgEQACgGAEgGQAEgEAGgDQAGgDAGAAIAJABIAFACIgHAmIAEAHIgHAEgAKCgQQgDABgDAEIgFAJIgBAJIAAAHIACADIADACIADABIAEgBIAEgCIADgEIACgGIAFgZIgCAAIgEgBQgEAAgEADgAJSAYQgCgCAAgFIAAgDIAFgeIgJAAIACgHIAJAAIADgPIAIAAIgDAPIANAAIgBAHIgNAAIgFAaIAAAEQAAABAAABQAAABAAAAQAAABAAAAQAAABABAAQAAAAAAAAQABABAAAAQABAAAAAAQABAAAAAAIAEAAIADgCIACAHIgEABIgHABQgGAAgDgDgAIhAZQgEgBgCgDQgDgDAAgEIgBgHQAAgHACgGQACgGAEgFQADgDAFgDQAFgCAFAAQAGAAACACQAFABABADIADAHIABAHQAAAGgCAHQgDAHgCAEQgEADgFADQgFACgFAAQgEAAgEgCgAIpgQQgDACgCAFIgDAJIgBAIQAAAFADAEQACADAFAAQAEAAADgCQADgDADgEIACgJIABgIQAAgFgCgEQgDgDgFAAQgDAAgEACgAG7AZQgDgBgCgDIgEgHIgBgHQABgHACgGQACgGAEgFQAEgEAEgCQAEgCAGAAQAFAAADACQAEABACADQACADABAEIABAHQAAAHgCAGQgCAGgEAFQgEAEgFACQgDACgHAAQgEAAgEgCgAHEgQQgDADgCAEIgEAJIgBAIQABAFACAEQACADAFAAQAFAAADgCQADgCACgFQADgDAAgGIABgIQAAgGgCgDQgDgDgFAAQgDAAgEACgAE3AUIgHAFQgEACgEAAQgHAAgEgFQgEgEAAgJQAAgJACgEQACgHAEgEQAFgGAFgCQAGgDAHAAIAIABIAFACIgHAnIAEAHIgHAEgAEvgRQgEACgDAEQgDAEgCAFQgBADAAAGIAAAHIADADIACACIADABIAEgBIAEgCIADgEIADgGIAEgZIgCgBIgDAAQgFAAgDACgAA4AZIgGgEIgEgGIgBgHQAAgIACgDQADgHADgFQAEgFAFgDQAEgDAGAAIAHABIAEADIADAEIABAEQAAAFgDADQgBADgDADQgDAAgGACIgJABIgIAAIAAADQAAAHADADQADAEAFAAIAHgBIAFgCIACAGIgHADQgBABgHAAQgFAAgDgCgABCgRIgFAEIgEAGIgCAGIAEABIADAAIAHgBIAEgDIAEgDQABgCAAgEQAAgBAAAAQAAgBgBAAQAAgBAAAAQgBgBAAAAQAAgBgBAAQgBgBAAAAQgBAAAAAAQgBAAgBAAQgDAAgCACgAhcATIgDADIgDADIgEABIgFABQgFAAgCgBIgEgDIgCgEIgBgFIAAgCIAAgCIAAgDIABgCIAFgdIAJAAIgGAgIAAADIgBACQABAHAGAAQAGAAAEgEQAEgDACgIIAFgdIAIAAIgHAnIAEAIIgIAEgAkBAWQgFgFABgKQAAgHABgEQACgGAEgFQADgFAGgDQAFgDAHAAIAIABIAFADIgEAFIgEgBIgFgBQgFAAgEACQgEADgCAEIgDAIIgBAIQAAAIACADQAEADAEAAIAHgBIAFgCIABAGIgFADIgJABQgJAAgFgFgAlgAZIgHgEIgCgGIgBgHQAAgIACgDQABgFADgHIAJgIQAFgDAHAAIAGABIAFADIABAEIABAEQAAAFgBADQgDAEgDACQgCABgGABIgJABIgHAAIAAADQAAAHACADQADAEAGAAIAFgBIAFgCIACAGIgFADIgIABQgGAAgDgCgAlWgRIgFAEIgDAGIgCAGIACABIAEAAIAGgBIAFgDIADgDIABgGQAAgBAAAAQAAgBAAAAQAAgBAAAAQgBgBAAAAQgCgCgDAAQgDAAgCACgAm1ATIgDADIgDADIgFABIgEABIgHgBIgEgDIgDgEIAAgJIAHgiIAIAAIgGAeIAAACIgBADIAAACQAAAHAIAAQAFAAAEgEQAEgCABgJIAFgdIAJAAIgHAnIADAIIgHAEgAoAAZQgEgBgCgDQgCgCgBgFIgBgIIABgIQABgFADgFQAFgFACgBQAFgDAGAAQAFAAAEADQAEACABAEIABgCIAAgBIgBgJQgBgGgBgCQgBgDgEgCQgDgCgFAAIgFAAIgGACIgBgGIAGgCIAHgBQALAAAGAHQAFAIABAPIgCARIgEAKIgEAIIgIAGQgEACgFAAQgFAAgEgCgAn6gMQgDADgCADIgBAGIgBAHIABAFQAAABAAAAQAAABAAABQAAAAAAAAQABABAAAAQAAABABAAQAAABAAAAQABABAAAAQABAAAAAAQABABAEAAQAFAAACgCIAFgGIADgIIABgFQAAgGgDgEQgDgDgGAAQgEAAgDACgApgATIgCADIgDADIgFABIgFABIgGgBIgFgDIgCgEIgBgFIAAgCIABgCIAAgDIAAgCIAGgdIAJAAIgHAgIAAADIAAACQAAAHAHAAQAGAAAEgEQADgDACgIIAFgdIAJAAIgIAnIAEAIIgHAEgArOATIgCADIgEADIgEABIgFABQgEAAgCgBIgFgDIgCgEIAAgFIAAgCIAAgCIAAgDIAAgCIAGgdIAJAAIgGAgIAAADIgBACQAAAHAHAAQAGAAAEgEQAEgDABgIIAGgdIAIAAIgIAnIAEAIIgHAEgAvRAZQgDgBgCgDQgCgDgBgEIgBgIQAAgHACgGQACgGAEgEQAEgFAEgCQAHgCADAAQAFAAADACQADABADAEQACACABAEIABAIQAAAHgCAGQgCAGgEAFQgEAEgFACQgDACgHAAIgIgCgAvIgRQgDADgCAEQgCAEgBAFIgBAJQAAAFACAEQACADAFAAQAFAAADgCQAEgDABgEQACgDABgGIABgIQAAgHgCgDQgDgDgFAAQgDAAgEACgAFfAEIgBAAIAAAAIgQAWIgHgCIARgYIgJgXIAIgCIAIAUIAAABIABABIABgCIAOgUIAHACIgQAXIAKAYIgIACgAgyAGIgBgCIAAAAIgBAAIgBACIgPAUIgHgCIASgYIgKgXIAIgCIAIAUIAAABIABABIABgCIAOgUIAIACIgRAXIAKAYIgIACgAo1AGIgBgCIAAAAIgBAAIgCACIgPAUIgHgCIASgYIgJgXIAIgCIAIAUIAAABIAAABIACgCIAOgUIAHACIgQAXIAKAYIgIACgAM8ACIgHAAIgEAXIgIAAIAJgxIAIAAIgEAVIAFAAQABAAAAAAQABAAAAAAQABgBAAAAQAAAAAAgBIAJgOQADgEADgBIAFgBIACAGIgEABIgDADIgHAMIgCACIAAABIAKAXIgIADgAL5AZIACgHIACABIAHAAIACgCIADgCIAEgIIgFgBIgDgBIgCgEIgCgDIgFgqIAJgCIAEAoIACAEIABACIACAAIACAAIAWguIAJACIgaA1IgFAIIgEAFQgCADgDAAIgGABgAiWACIgHAAIgEAXIgJAAIAJgxIAJAAIgEAVIAFAAQABAAAAAAQABAAAAAAQABgBAAAAQABAAAAgBIAJgOQACgEADgBQACgBAEAAIABAGIgEABIgDADIgHAMIgBACIgCABIAMAXIgIADgAjPAaIgLgCIAJgwIAIAAIgEAXIAGgCIAHgBIAFABQACAAADACIADACIABAGIgBAHIgDAGIgIAEQgFACgIAAgAjIABIgGACIgCAQIAGABIAHgBQADgBACgCIACgEIABgEQAAgEgCgCQgCgCgEAAgAmkAWIAHgHIADgIIAJgfIAeAAIgJAxIgIAAIAHgqIgOAAIgHAZIgEAKQgEAFgDADgAQTAZIAIgrIgHAAIABgGIAPAAIgJAxgAP5AZIAEgYIgWAAIgDAYIgJAAIAJgxIAJAAIgFAVIAWAAIAEgVIAJAAIgKAxgAPCAZIAIgrIgGAAIABgGIAPAAIgJAxgAGVAZIAMg/IgUAAIABgHIAxAAIgBAHIgUAAIgMA/gADJAZIAGgkIgBgFQgBgCgEAAIgEABIgEACIgDAFIgCAEIgFAfIgJAAIAGgcIAAgCIAAgCIAAgDIAAgBIAAgFQgBgBAAAAQgBgBAAAAQgBAAgBAAQAAAAgBAAIgEAAIgEADIgEAEQgCADAAACIgGAfIgIAAIAHgnIgCgIIAHgEIADAIIAHgFIADgCIAFgBQAGAAACADIAEAFIAGgFIAEgCIAFgBIAGABIAEADQAAABAAAAQABABAAAAQAAABAAAAQABABAAAAIAAAFIgGAmgAB6AZIAEgYIgVAAIgFAYIgJAAIAJgxIAJAAIgDAVIAVAAIAEgVIAJAAIgJAxgAqYAZIAFgYIgWAAIgEAYIgJAAIAJgxIAJAAIgEAVIAWAAIADgVIAJAAIgJAxgAsGAZIAIgrIgGAAIABgGIAPAAIgJAxgAtWAZIAIgrIgGAAIABgGIAPAAIgJAxgAwnAZIAMhGIAVAAQAJAAAFAEQAGAEAAAHQAAAGgEAGQgEAEgFADQAFADACADQADAEAAADQAAAEgCAGQgCAFgEADIgJAEIgKABgAwdASIAUgBIAGgDQACgBABgDIABgHIgBgDIgDgEIgFgCIgEAAIgMAAgAwXgOIANAAIAFgBQACAAADgDIADgEIABgGQAAgFgDgCQgDgDgHAAIgKAAgAQdgiIgBgEQAAgDABgDQACgCAEAAQAAAAABAAQAAABABAAQAAAAABAAQAAABAAAAQABABAAAAQAAAAABABQAAAAAAABQAAABAAAAQAAADgDADQAAAAAAABQgBAAAAAAQgBABgBAAQAAAAgBAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQgBgBAAAAgAragjQgEgEgBgEIAGgCIADAEQACACAFAAQADAAAEgCQACgBABgDIAGABQgCAHgFACQgDADgHAAQgGAAgEgDgAr8giIAAgEQAAgEABgCQACgCAEAAQAAAAABAAQAAABABAAQAAAAABAAQAAABAAAAQAAABABAAQAAAAAAABQAAAAAAABQAAABAAAAQAAAEgCACQgBACgEAAQAAAAgBAAQAAAAgBgBQAAAAgBAAQAAgBgBAAgAtLgiQAAgBgBAAQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAgDACgDQADgCADAAQAAAAABAAQAAABABAAQAAAAABAAQAAABAAAAIABAEQAAAEgCACQAAAAAAABQgBAAAAAAQgBABgBAAQAAAAgBAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQgBgBAAAAgAPUgjIgBgEQAAgCABgDQABgBAAAAQABgBAAAAQABAAABAAQAAAAABAAQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABQAAABAAAAQAAADgBADQgBAAgBABQAAAAgBAAQAAABgBAAQAAAAgBAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQgBAAAAgBgAPBgjIgCgEQAAgDACgCQAAgBABAAQAAgBABAAQAAAAABAAQABAAAAAAQABAAABAAQAAAAABAAQAAAAABABQAAAAABAAIABAEQgBAEgBACQgBAAAAABQgBAAAAAAQgBABAAAAQgBAAgBAAQAAAAgBAAQAAAAgBgBQAAAAgBAAQAAAAAAgBg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-106.4,-4.7,212.9,9.6);


(lib.t1_3 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ak4BpIAHgiIhKAAIgGAiIglAAIALg/IAOAAIAJgLIAPggIAbhjIBfAAIgZCOIAPAAIgLA/gAlOgPQgFAPgGASQgGAPgHAJIAuAAIAUhxIgbAAgAE7A5IAIgGIAMgQIAHgMQAEgJACgGIAdhsIBmAAIgeCrIgkAAIAZiPIghAAIgbBeIgGAQIgFAIQgIAOgVAQgAHcA3QAMgHAJgLQAKgJAFgMIAIgRQgJgFgHgKQgFgKgBgPQAAgPAGgMQAFgKAKgIQAIgHANgEQALgDAPAAIA8AAIgfCrIglAAIANhBIgRAAIgGAOQgIAQgLAOQgLAOgUAMgAIhhCQgIAHAAAPQAAAMAFAGQAGAFAMAAIAPAAIAKg0IgSAAQgOAAgIAHgAMKBGQgEgFAAgHQgBgKAHgHQAGgHAIAAQAJAAAFAGQAEAFAAAHQAAALgGAGQgGAGgJAAQgIAAgFgFgAjRBGQgMgGgGgJQgHgIgDgOQgCgKgBgQQAAgaAHgTQAHgVAMgPQANgPAQgHQAQgIATAAQAOAAANAEQANAEAKAIIgQAZQgIgFgIgDQgIgDgKAAQgLAAgJAGQgJAGgHALQgGAKgFAPQgDAOAAARIABAPQACAJADAEQADAFAFAEQAGADAIAAQAJAAAKgDQAFgBAPgIIAKAaQgMAHgPAFQgOAEgQAAQgSAAgLgFgAKbBFQgLgFgIgKQgHgJgDgNQgDgNAAgPQAAgXAHgVQAHgVALgOQAMgNARgIQAQgIATAAQANAAAOAEQANAEAKAIIgQAZQgIgFgIgDQgIgDgKAAQgPAAgNAMQgMANgFAVIA0AAIgEAcIg0AAIABAUQABAIAEAFQACAFAGAEQAGADAHAAIAJAAIAUgHIANgGIAKAaQgOAIgNAEQgOAFgRAAQgSAAgLgGgAAMBFIA/iQIAGgMQAEgFAFgEQAFgFAGgBQAGgCAJAAQAPAAAIAHQAHAGADASIAQCPIglAEIgEgwIg4AAIgVAxgAB5AAIgFg7QgBgEgBgDQAAgBAAAAQgBAAAAgBQgBAAAAAAQgBAAgBAAQAAAAgBAAQgBAAAAAAQgBABAAAAQAAAAAAABIgFAHIgYA7IArAAgAC2BHIAdirIA6AAQAKAAALACQAHACAJAGQAHAFAEAIQAEAIAAAKQAAAMgIAMQgHAMgMAGQAKAFAFAJQAHAHgBALQAAAPgFAKQgHALgIAGQgKAHgNADQgMAEgQAAgADfAsIAZAAIALgCIAKgFQAEgDACgGQACgEABgJQAAgFgCgEQgCgDgEgDIgHgBQgDgBgGAAIgXAAgADsgeIATAAQANAAAIgHQAHgGAAgMQAAgJgFgEQgFgFgLAAIgTAAgAhMBHIAZiOIgtAAIAGgdIB9AAIgFAdIgsAAIgZCOgAoQBHIAeirIBrAAIgFAdIhGAAIgHAnIA1AAIgFAdIg1AAIgIAtIBJAAIgGAdgAqiBHIAdirIA7AAQAMAAAKADQAJACAIAGQAIAGADAIQAEAJAAALQAAAOgFAMQgGAMgHAIQgLAJgNACQgPAFgQAAIgVAAIgLBAgApsgUIASAAQAOAAAJgIQAJgIAAgQQAAgLgFgFQgHgFgKAAIgTAAgArrBHIAaiOIg3AAIgZCOIgmAAIAeirICBAAIgeCrgAMOARIASh1IAoAAIgcB1g");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-84,-10.5,168.1,21.1);


(lib.t1_2 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E11A2C").s().p("AAkBpIAHgiIhHAAIgHAiIgkAAIALg/IAOAAIAJgLIAOggIAHgZIAShKIBgAAIgZCOIAPAAIgLA/gAAPgPQgFAPgHASQgEAPgGAJIArAAIAUhxIgaAAgAIsBGQgLgFgHgJQgIgJgCgMQgEgNAAgPIABgJIgaAAIgNBJIglAAIAdirIAmAAIgMBDIAaAAQAEgNAHgPQAHgNAKgKQAKgJANgGQALgFAQAAQAQAAALAFQALAGAIAIQAIAKADAMQADANAAAOQAAAZgFASQgGAVgLAPQgKAPgQAJQgQAIgUAAQgQAAgMgFgAJKhEQgHAHgGAMQgEAMgDAPQgCANAAARIABAPQAAAGADAGQADAGAEACQAFADAGAAQALAAAIgHQAJgHAFgMQAGgMACgOQACgNAAgTQAAgSgGgJQgEgKgOAAQgLAAgIAHgADUBGQgMgGgGgJQgIgKgCgMQgDgMAAgOQAAgXAHgWQAHgWAMgOQANgPAQgHQAQgIASAAQAOAAANAEQAOAEAKAIIgQAZQgHgFgKgDQgHgDgLAAQgJAAgKAGQgJAFgHAMQgHAKgDAPQgEAQAAAPQAAAIABAHQABAIADAFQADAFAGAEQAGADAIAAQAJAAAKgDQAGgBAOgIIAKAaQgNAHgOAFQgOAEgQAAQgSAAgLgFgApzBJQgKgBgGgDQgJgEgEgDIgLgIIASgXQAJAIALADQALAEAKAAQAOAAAIgGQAJgGAAgOQAAgNgIgFQgJgDgKAAIgcAAIAEgcIAbAAQAKAAAHgCQAGgDADgEQAEgDACgFIABgKQAAgLgGgEQgFgFgIAAQgLAAgKAEQgIACgMAGIgLgXQAKgGARgGQAPgFASAAQANAAAJAEQAIACAHAHQAFAGAEAHQACAJAAAHQAAAQgHALQgHALgPAJQAJAFAFAIQAHAHAAAOQgBANgEAKQgDALgKAHQgJAIgLADQgOAEgQAAQgLAAgJgCgAlBBGQgLgFgIgJQgIgKgDgMQgEgLAAgQQAAgUAGgVQAGgWAMgOQALgQAQgJQARgJATAAQARAAAMAFQANAGAIAIQAIAJAEANQADAKAAARQAAAYgFASQgHAVgLAPQgLAQgRAIQgQAJgWAAQgRAAgMgFgAkghEQgJAHgHAMQgFAMgEAQQgDAOAAAQQAAASAGAJQAHAKANAAQALAAAKgHQAJgHAGgMQAGgMAEgOQACgPAAgRQAAgRgGgKQgHgKgOAAQgLAAgIAHgAFZBHIAZiOIgtAAIAGgdIB/AAIgFAdIguAAIgZCOgABoBHIAfirIAkAAIgdCrgAjABHIAfirIA5AAQAMAAALADQAJACAIAGQAHAGAEAIQADAIAAAMQABAOgFAMQgGAMgIAIQgJAIgOADQgPAFgRAAIgUAAIgLBAgAiKgUIASAAQAPAAAIgIQAKgIgBgQQAAgLgFgFQgGgFgKAAIgUAAgAnhBHIAfirIBkAAIgGAdIg/AAIgYCOg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-66.9,-10.5,133.8,21.1);


(lib.t1_1 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AEaBUIA+iQIAGgMIAJgJQAGgFAFgBQAGgCAKAAQAPAAAHAHQAHAGADASIAQCPIglAEIgEgwIg3AAIgVAxgAGGANIgFg5IgBgHQgBgBAAAAQAAAAgBgBQAAAAgBAAQAAAAgBAAQgBAAAAAAQgBAAgBAAQAAABgBAAQAAAAAAABIgEAHIgYA5IAqAAgAAhBVQgMgFgHgJQgIgJgEgNQgCgNAAgOQAAgUAFgVQAFgVAMgPQAMgQAQgJQAQgJAUAAQAQAAANAFQANAGAHAIQAJALADALQAEANAAAOQAAAWgGAUQgHAXgLANQgLAQgRAIQgQAJgVAAQgRAAgMgFgABAg1QgHAGgHANQgGAOgDAOQgEAOAAAQQABASAGAJQAGAKANAAQALAAAKgHQAKgIAFgLQAHgMACgQQAEgMAAgSQAAgRgGgKQgHgKgOAAQgLAAgKAHgAkOBVQgNgFgHgJQgJgKgDgMQgDgLAAgQQgBgWAHgTQAGgWAMgOQAKgPARgKQAQgJAVAAQAQAAAMAFQAMAFAIAJQAIAJAEANQAEAMABAPQgBAVgGAVQgGAVgMAPQgMARgQAHQgQAJgVAAQgRAAgLgFgAjvg1QgJAHgGAMQgGAMgDAQQgDAOAAAQQAAASAGAJQAGAKANAAQAMAAAJgHQAKgHAFgMQAHgOADgOQADgNAAgRQAAgRgGgKQgHgKgNAAQgMAAgJAHgAC/BWIAaiOIguAAIAGgdICAAAIgFAdIguAAIgaCOgAhsBWIALhDQgFgDgDgFQgDgFgCgHIgWhRIAkgFIASBGIACAGQABABAAAAQAAABABAAQAAAAABABQAAAAABAAQAAAAABAAQAAAAAAgBQABAAAAAAQAAAAAAgBQACAAABgEIAohJIAgAFIgtBSQgDAHgHAGQgEAEgGACIgLBDgAmdBWIAZiOIgtAAIAFgdICAAAIgFAdIguAAIgaCOg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-43.5,-9,87,18.1);


(lib.Symbol1 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AGDA3IAAgSIhZAAIAAhZIANAAIAABPIAcAAIAAhPIANAAIAABPIAcAAIAAhPIAMAAIAABPIAIAAIAAAcgAhAA3IAAgSIg2AAIAAASIgMAAIAAgbIAGAAIAFgHQACgEACgFIADgLIAGg1IAwAAIAABQIAHAAIAAAbgAhoANIgDAIIgDAHIAnAAIAAhGIgZAAgAENAIIgkAAIgKAfIgKgCIAZhNQABgFADgFQADgDAGAAIAGAAIAEACIADAEIACAHIAaBNIgNACgAELAAIgNgnIgBgDIgCgBIgCABIgBADIgMAnIAfAAgAlbAIIgkAAIgKAfIgKgCIAYhNQADgHACgDQADgDAGAAIAGAAIAEACIADAEIAbBUIgMACgAleAAIgMgnIgBgDIgCgBIgCABIgOAqIAfAAgAnNAlIgMgHIAFgIQAGAEAFACQAIACAGAAQAKAAAFgEQAFgGAAgIIgBgHQgBgDgCgCQgDgBgDgBQgEgBgGAAIgOAAIAAgKIANAAQAGABADgCIAGgEIADgFIABgGQAAgIgFgEQgEgDgIAAIgMABIgLAEIgEgHIALgFIASgDQAIAAAFACQAGACACACQAEADABAFQACADAAAGIgBAIIgEAHIgFAEIgFAEQAEAAADADQADABACADQADACABACQABAEAAAFQAAAGgCAFQgBAEgFAEQgEAFgGABQgFACgJAAQgKAAgJgCgABlgDIgMAAIAAAoIgMAAIAAhZIAMAAIAAAnIAIAAQADABACgCQACAAABgFIAPgaQABgDADgCQADgCAFAAIAEAAIADABIgBAIIgCAAIgCAAQAAAAgBAAQAAAAgBAAQAAAAAAAAQgBABAAAAIgDADIgPAcIgBABIAeAuIgMACgAiugDIgJAAIAAAoIgNAAIAAgoIgKAAIgdApIgMgCIAfgtIgBgCIgOgcIgDgEIgDAAIgCAAIgCAAIgBgIIAEgBIAEAAQAFAAACABQADADABADIANAaQACAEACABQABACAEgBIAFAAIAAgnIANAAIAAAnIAFAAQADABACgCQACAAABgFIANgaIAEgFQADgCAFAAIAEAAIAEABIgCAIIgCAAIgBAAIgEABIgCADIgNAaIgBACIgCACIAfAtIgMACgAGgAlIAAhZIA4AAIAAAKIgsAAIAAAcIAhAAIAAAKIghAAIAAAgIAuAAIAAAJgACbAlIAAhZIAoABQAGABAEADQAFAEACAFQACAFAAAIQAAAFgCAFQgCAGgEADQgEAEgFACQgHAAgHABIgQAAIAAAkgACngHIAOAAQAKAAAFgEQAGgFAAgJQAAgFgCgEQgBgEgDgCQgCgBgFgBIgIgBIgOAAgAASAlIAAg9IgoAyIAAALIgNAAIAAhZIANAAIAAA/IAogyIAAgNIAMAAIAABZgAk+AlIAAhZIAdAAQAHAAAFACQAFAAAEADQAEAEADAEQACAFAAAGQAAAFgDAGQgFAGgEABQAIAEAEAFQAEAFAAAIQAAAFgCAFQgDAGgDACIgKAGQgGABgGAAgAkxAcIASAAQAKAAAFgFQAEgEAAgIQAAgFgBgEIgFgCQgCgCgFgBIgYAAgAkxgNIARAAQAEABADgCQADgBACgCQADgCAAgDIABgGQAAgIgFgEQgEgDgKAAIgOAAg");
	this.shape.setTransform(0,0,0.496,0.495);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-23.5,-2.7,47,5.5);


(lib.speed = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.speed1();
	this.instance.setTransform(-120,-109.6,2.4,2.4);

	this.instance_1 = new lib.speed2();
	this.instance_1.setTransform(-120,-109.6,2.4,2.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance_1}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-120,-109.6,240,240);


(lib.pr = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AtvRNMAAAgiZIbfAAMAAAAiZg");
	this.shape.setTransform(88,110.1);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,176,220.3);


(lib.logo3_1 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.logo3();
	this.instance.setTransform(-86,-85.5);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-86,-85.5,172,171);


(lib.logo2 = function() {
	this.initialize();

	// 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E1142D").s().p("AACAVIgCgBIAAgCIgBgEIgBgUIgHAUIgDAGQgDACgDAAQgDAAgCgCQgCgCAAgEIgBgiIAJgBIABAdIAAACIABABIAAgBIABgBIAKgeIAIAAIABAfIABABIABgBIAMgfIAIABIgNAiIgDAGQgDACgEAAg");
	this.shape.setTransform(-38.7,-5.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#E1142D").s().p("AgPAVIAHgpIAYAAIgBAHIgPAAIgCAKIALAAIgBAFIgLAAIgCAMIAQAAIgBAHg");
	this.shape_1.setTransform(-43.3,-5.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#E1142D").s().p("AACAVIgCgBIAAgDIgFgaIgGAeIgIAAIAHgqIAMAAIAFAfIABABIAAgBIAGgfIAIAAIgGAjQAAADgDADQgDACgDAAg");
	this.shape_2.setTransform(-47.1,-5.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#6D6E71").s().p("AAFApIAIgsIgdAhIgCALIgRAAIAOhRIARAAIgIAtIAdggIACgNIARAAIgOBRg");
	this.shape_3.setTransform(70,14.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#6D6E71").s().p("AALAxIADgQIghAAIgCAQIgRAAIAFgeIAGAAIAEgGIAEgGIADgIIANgvIAqAAIgMBDIAHAAIgFAegAgDAHIgGAMIATAAIAKg1IgNAAg");
	this.shape_4.setTransform(62.1,15.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#6D6E71").s().p("AAGApIAFgkIgXAAIgGAkIgSAAIAPhRIARAAIgFAhIAXAAIAFghIARAAIgNBRg");
	this.shape_5.setTransform(55.4,14.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#6D6E71").s().p("AgeApIAOhRIAvAAIgCAOIgfAAIgDATIAXAAIgCAMIgXAAIgEAWIAgAAIgCAOg");
	this.shape_6.setTransform(48.7,14.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#6D6E71").s().p("AgdApIAOhRIAtAAIgDAOIgbAAIgMBDg");
	this.shape_7.setTransform(43,14.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#6D6E71").s().p("AgeApIAOhRIAvAAIgCAOIgfAAIgDATIAXAAIgCAMIgXAAIgEAWIAgAAIgCAOg");
	this.shape_8.setTransform(37,14.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#6D6E71").s().p("AglAhIAIgIIACgDIAGgNIANgyIAuAAIgPBRIgRAAIAMhDIgPAAIgKArIgDAIIgDADQgFAJgIAGg");
	this.shape_9.setTransform(29.8,14.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#6D6E71").s().p("AgfApIAOhRIAZAAIAJABQAFACADACQADADACADQACAEAAAFQAAAGgEAFQgEAGgFADQAFAAADAEQACAFAAAFQAAAHgCAFQgEAGgDACQgGAEgFABQgGACgFAAgAgMAcIAMAAIADgBIAFgCIADgFIABgGIgBgEIgDgDIgDgCIgEAAIgJAAgAgGgGIAHAAQAGAAAEgEQADgDAAgFQAAgEgCgDQgCgCgFAAIgHAAg");
	this.shape_10.setTransform(21,14.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#6D6E71").s().p("AAFA2IAIguIgdAjIgCALIgRAAIAOhRIARAAIgIAtIAdggIACgNIARAAIgOBRgAgDgmQgFgEgCgIIAKgDQAAACACAEQACACAEAAQAEAAACgCQADgCACgEIAKADQgEAKgFADQgFAEgIgBQgHABgDgFg");
	this.shape_11.setTransform(13.9,13);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#6D6E71").s().p("AgiAoIAdhEIADgGIACgEQACgCADgBIAHgBQAHAAAEAEQADADABAIIAIBDIgRACIgCgXIgYAAIgKAYgAAIgYIgCAEIgKAaIATAAIgEgeIgBgBg");
	this.shape_12.setTransform(5.9,14.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#6D6E71").s().p("AggApIAOhRIAZAAIALABIAIAEQAEAEABADQACAEAAAGQAAAGgDAGQgCAFgEADQgEAEgHACQgFACgIAAIgJAAIgFAfgAgGgBIAGAAQAGAAAFgEQAEgEAAgIQAAgGgDgCQgCgCgFAAIgHAAg");
	this.shape_13.setTransform(0.2,14.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#6D6E71").s().p("AALAxIADgQIghAAIgCAQIgRAAIAFgeIAGAAIAEgGIAEgGIADgIIANgvIAqAAIgMBDIAHAAIgFAegAgDAHIgGAMIATAAIAKg1IgNAAg");
	this.shape_14.setTransform(-7.3,15.1);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#6D6E71").s().p("AgQAHIACgNIAgAAIgDANg");
	this.shape_15.setTransform(-12.6,14.9);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#6D6E71").s().p("AgUApIALhDIgUAAIACgOIA6AAIgDAOIgVAAIgKBDg");
	this.shape_16.setTransform(-16.6,14.3);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#6D6E71").s().p("AgRAoQgFgCgDgFQgDgEgBgGQgCgGAAgHQAAgLADgJQAEgLAFgGQAHgIAHgDQAGgEAHAAQAGAAAIACIAKAGIgIAMIgHgEIgJgBQgEAAgEACQgDADgDAFQgDAGgCAHQgBAEAAAJIAAAIIACAGIAEAEQADABADAAIAHgBIAKgEIAFAMQgHAEgGACQgGACgGAAQgIAAgGgDg");
	this.shape_17.setTransform(-23.1,14.3);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#6D6E71").s().p("AgeApIAOhRIAvAAIgCAOIgfAAIgDATIAXAAIgCAMIgXAAIgEAWIAgAAIgCAOg");
	this.shape_18.setTransform(-29.2,14.3);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#6D6E71").s().p("AgUApIAMhDIgVAAIACgOIA6AAIgDAOIgVAAIgKBDg");
	this.shape_19.setTransform(-35,14.3);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#E1142D").s().p("AhJBAQgfAAAJgcQAFgUAMgTQAMgXAMgNQAKgLASgHQARgFAPAAIBcAAIgjAZIgpAAQgSAAgIAHQgKAGgIAQIgUAsIBxAAIgdAcg");
	this.shape_20.setTransform(-26.8,-1.6);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#E1142D").s().p("AADBCIhBgBQgbgEgFgSQgFgSAOgeQAMgaANgNQARgRAYgCIATgBQAYgBAmADQAMACAIAGQATAMgHAaIgJAdIgMAcQgMAWgqADgAgbgZIgNAZQgJAVgBAHQAAAJAMACIAoAAIAEgBQAOAAAFgEIAGgIQARggADgNQAEgLgCgEQgCgDgKgBQgQgCgZACIgFAAQgOABgIAMg");
	this.shape_21.setTransform(-10.4,-1.5);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#E1142D").s().p("AAnBGQgpgmgegvIA5ABQAGgBACgFIAEgLQABgGgBgDQgCgDgGAAIg3gCIgiBkIgxAAIAzh+IBNAAQAeAAAQALQAPAJgBARQgBAngWADIgbAAQAfAfAiAXIAQAKg");
	this.shape_22.setTransform(8.1,-0.8);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#E1142D").s().p("Ag+BAQgKgBgHgEQgcgOAWgyIAEgIQALgWANgMQAQgPAWgBIATgCQAbgBAjAEQAMABAJAGQARANgGAaQgCAJgHATQgGASgGALQgMAWgqACIgQAAIgRABQgYAAgYgCgAAAgnIgFABQgOABgIALIgNAaQgJAUAAAHQgBAKAMABIAoAAIAEAAQAOgBAFgEIAGgIIAOgbQAFgNABgEQAEgLgCgEQgCgEgLgBIgTAAIgVAAg");
	this.shape_23.setTransform(25.5,-1.5);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#E1142D").s().p("ACVBAIAKgmIgMABQglAEgUAGIgXAbIiPAAIAIgWIgVAWIiBAAIAxh9IA3AAQgQANgEANQgPAigHAeQgCAGADABIAKAAIBQAAIAmhhIA1AAQgOALgEAJQgJAZgMAmQgDALACACIAFABIAnAAIA8g7QAYgXAegKQAggKArAFIgYB9gACRgXQgPAJgOAQIAxAAIAKgjQgPABgPAJg");
	this.shape_24.setTransform(55,-1.7);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#E1142D").s().p("AnCBSIk/kDIGPAAIBvjWIBtDWIOXAPIumANIhejKIhgDKIlVAAIERDbIAAENID+iaIDFAGIjFALIkZC+g");
	this.shape_25.setTransform(0,3);

	this.addChild(this.shape_25,this.shape_24,this.shape_23,this.shape_22,this.shape_21,this.shape_20,this.shape_19,this.shape_18,this.shape_17,this.shape_16,this.shape_15,this.shape_14,this.shape_13,this.shape_12,this.shape_11,this.shape_10,this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-77,-36.2,154,78.5);


(lib.log = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.l();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,80,55);


(lib.img2Mc = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.img2();
	this.instance.setTransform(-120,-240,0.8,0.8);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-120,-240,240,480);


(lib.gradient = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.702)","rgba(255,255,255,0)"],[0,0.494,1],-47,0,47,0).s().p("AnVOcIAA83IOrAAIAAc3g");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-47,-92.4,94.1,184.9);


(lib.logo = function() {
	this.initialize();

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E1192C").s().p("AAnBjQgogpAAg6QAAg5AogqQApgpA8gBQA6ABApApQAqAqABA5QgBA6gqApQgpAqg6ABQg7gBgqgqgABTg+QgXAaABAkQgBAkAXAbQAXAaAiABQAggBAXgaQAXgbAAgkQAAgkgXgaQgXgbggABIgBAAQghAAgXAagAoFBjQgpgpAAg6QAAg5ApgqQAqgpA7gBQA6ABAqApQApAqABA5QgBA6gpApQgqAqg6ABQg7gBgqgqgAnYg+QgXAaAAAkQAAAkAXAbQAXAaAhABQAggBAXgaQAXgbAAgkQAAgkgXgaQgXgbggABIgBAAQghAAgWAagALYCGIgXg8IhsAAIgXA8IhHAAIBwkHIBLAAIBtEHgAJnAeIBLAAIglhggAF/CGIAAjXIhWAAIAAgwIDkAAIAAAwIhSAAIAADXgAipCGIAAhlIhpiiIBHAAIBABwIBDhwIBEAAIhpCiIAABlgArLCGIAAjXIhTAAIAAgwIDhAAIAAAwIhTAAIAADXg");
	this.shape.setTransform(-0.8,70.7);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-80.7,56.5,159.9,28.5);


(lib.bg = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("EgSuAllMAAAhLJMAldAAAMAAABLJg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-120,-240.6,240,481.2);


(lib.ALWAYS_mc = function() {
	this.initialize();

	// red
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E0192C").s().p("ADsAXIgEgFIgEgDIgEgCIgEgBIgFAAIAAAoIgWAAIAAhqIAoAAQAJAAAGACQAHABAFAEQAFAEADAGQADAFAAAJQAAAGgCAFIgFAJIgHAFQgEADgFABIAEAEIAFAEIAXAcIgRANgADXgEIAPAAQAIAAAFgEQAFgEAAgIQAAgFgBgDQgCgDgCgCIgGgCIgHAAIgPAAgABiA0IAAhqIBNAAIAAATIg4AAIAAAXIArAAIAAARIgrAAIAAAcIA6AAIAAATgAAeA0IAAhXIgeAAIAAgTIBVAAIAAATIggAAIAABXgAg8A0IAAhXIgfAAIAAgTIBWAAIAAATIggAAIAABXgAizA0IAAhqIBOAAIAAATIg3AAIAAAXIAqAAIAAARIgqAAIAAAcIA5AAIAAATgAkXA0IAAhqIAqAAQAIAAAGACQAIABAFADQAEAEADAFQADAFAAAIQAAAIgEAFQgDAGgGADIAHAEIAGADQACADACAFQABAEAAAFQAAAIgCAGQgDAGgFAEQgFAEgHACQgHACgJAAgAkCAiIAYAAIAGgBQADgBACgCIAEgEQABgDABgDQgBgFgBgCQgCgDgDgCIgGgCIgIgBIgUAAgAkCgKIATAAQAHAAAFgDQAEgDAAgHQAAgHgEgDQgGgCgKAAIgPAAg");
	this.shape.setTransform(31.2,29.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#A6A8A9").s().p("AFWBuIgqAAIgKAhIgVgFIAahWIADgJIAGgHQACgCAGgCQAEgBAHAAIAKABIAIAEQADADABADIAEAJIAaBXIgXAFgAE+AzIgCAEIgLAkIAgAAIgKgkIgDgEIgCgBIgEABgADOCOQgGgCgFgDIgLAFQgFABgHAAQgJAAgFgCQgGgCgFgEQgDgEgCgGIgEgMIgJhPIAWgDIAKBOQABAIACADQAEADAGAAIAFAAIAFgCIAAhYIAXAAIAABYIAEACIAFAAQAGAAADgDQAEgDABgIIAJhOIAWADIgJBPIgDAMQgDAGgEAEQgEAEgFACQgHACgIAAQgHAAgFgBgAGgCNIAAglQgGgCgEgFIgHgMIgVguIAUgIIAXAxIADAEIAEABIAEgBIACgEIAXgxIAUAIIgUAsQgEAIgEAGQgEAFgGACIAAAlgAEYg/IgrAAIgKAhIgVgFIAahWIADgJIAGgHQADgCAFgCQAFgBAGAAIAKABIAIAEQADADABADIAEAJIAbBXIgXAFgAEAh6IgDAEIgKAkIAgAAIgLgkIgCgEIgDgBIgDABgABsgeIgLgDIgKgCIgHgDIAHgTQAJAEAJACIARACQALAAAGgEQAGgEAAgGQAAgEgCgCQgBgDgEgBIgGgDIgKgCIgOgDQgGgCgFgDQgFgEgEgFQgDgGAAgIQAAgHADgGQACgGAFgFQAGgEAIgDQAJgCALAAQAMAAAJACIARAFIgFASIgSgEQgIgCgIAAQgKAAgEADQgGADAAAGIABAFIAFAEIAGACIAJACIAOAEQAHABAGAEQAFAEAEAGQADAFABAJQAAAIgEAHQgDAGgGAFQgGAEgIADQgJACgLAAIgOAAgAg5g/IgqAAIgKAhIgWgFIAahWIAEgJIAFgHQADgCAFgCQAEgBAHAAIAKABIAIAEQADADACADIADAJIAaBXIgWAFgAhRh6IgCAEIgLAkIAgAAIgKgkIgDgEIgDgBIgDABgAjCgfQgGgCgFgDIgKAFQgGABgGAAQgJAAgGgCQgGgCgEgEQgEgEgCgGIgDgMIgJhPIAVgDIAKBOQABAIADADQADADAHAAIAEAAIAGgCIAAhYIAWAAIAABYIAFACIAFAAQAFAAAEgDQADgDABgIIAJhOIAXADIgKBPIgDAMQgCAGgEAEQgEAEgGACQgGACgIAAQgHAAgGgBgAmSg/IgrAAIgKAhIgVgFIAahWIADgJIAGgHQADgCAFgCQAFgBAGAAIAKABIAIAEQADADABADIAEAJIAbBXIgXAFgAmqh6IgDAEIgKAkIAgAAIgLgkIgCgEIgDgBIgDABgAAPggIAAglQgHgCgDgFIgFgMIgVguIAUgIIAUAxIAEAEIADABIAEgBIADgEIAWgxIAUAIIgUAsQgEAIgEAGQgEAFgGACIAAAlgAllggIAAhsIAWAAIAABZIA5AAIAAATg");
	this.shape_1.setTransform(50,20.8);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,99.9,41);


(lib._1 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgsBIIAEgYIAcAAIAOhSQAAgBAAgBQAAgBAAAAQAAgBAAAAQAAAAgBAAIgBABIgUAOIgNgTIAggVIAIgFQAGgDAGAAQAHAAAEAEQAEAFAAAGIAAAGIgTBiIAeAAIgEAYg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-4.6,-7.2,9.2,14.5);


(lib._0 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgeBEQgJgEgEgHQgFgIgBgJQgCgIAAgLQAAgQAEgQQADgQAJgOQAIgOALgIQAMgJAPAAQAMAAAHAEQAHADAGAIQAFAHACAJQACAJAAALQAAAUgEAOQgDAQgIAOQgIAOgMAIQgLAIgPAAQgNAAgIgFgAgCgrQgFAFgFALQgFAOgBAKQgCAJAAAQIAAALIACAJIAEAGQAEADADAAQAGAAAEgGQAGgGADgJQAEgJADgOQACgNAAgPQAAgNgDgIQgDgIgHAAQgHAAgDAHg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-5.2,-7.3,10.5,14.7);


(lib.Symbol = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgQAWIAIgWQgDgBgCgDIgCgGQABgHAEgFQAEgEAGAAQAIAAAEAEQAFAEAAAGIgBAFIgBAFIgTAdg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-1.7,-2.8,3.4,5.6);


(lib.Symbol_1 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgXBFQgDgEAAgGQAAgJAFgFQAEgGAIAAQAIAAABAFQAEAEAAAGQAAAJgEAFQgEAFgIAAQgHAAgEgEgAgTAZIAPhhIAfAAIgXBhg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-2.7,-7.3,5.6,14.8);


(lib.й = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.и();
	this.instance.setTransform(0,2.4);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgXAJQgJgHgDgLIATgHQACAGAEAEQAEAEAGAAQAGAAAEgEQADgCAFgHIASAFQgGANgKAHQgKAHgLAAQgNAAgJgIg");
	this.shape.setTransform(1.1,-6.1);

	this.addChild(this.shape,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-5,-7.8,10.1,15.6);


(lib.wheel_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.wheelMc();

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:1,scaleY:1,rotation:-683.9},9).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-20,-20,40,40);


(lib.t6 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.в();
	this.instance.setTransform(31.5,20.3);

	this.instance_1 = new lib.р();
	this.instance_1.setTransform(13.8,22.2);

	this.instance_2 = new lib.е();
	this.instance_2.setTransform(4,20.3);

	this.instance_3 = new lib.д();
	this.instance_3.setTransform(-28.9,18.3);

	this.instance_4 = new lib.и();
	this.instance_4.setTransform(-17.4,20.4);

	this.instance_5 = new lib.и();
	this.instance_5.setTransform(40.9,0.4);

	this.instance_6 = new lib.о();
	this.instance_6.setTransform(-33.9,0.3);

	this.instance_7 = new lib.у();
	this.instance_7.setTransform(-48.9,2.4);

	this.instance_8 = new lib.ь();
	this.instance_8.setTransform(57.4,-19.7);

	this.instance_9 = new lib.л();
	this.instance_9.setTransform(-7,20.4);

	this.instance_10 = new lib.л();
	this.instance_10.setTransform(46.7,-19.6);

	this.instance_11 = new lib.я();
	this.instance_11.setTransform(15.2,-19.7);

	this.instance_12 = new lib.с();
	this.instance_12.setTransform(6.6,-19.7);

	this.instance_13 = new lib.е();
	this.instance_13.setTransform(84,-19.7);

	this.instance_14 = new lib.е();
	this.instance_14.setTransform(-3.3,-19.7);

	this.instance_15 = new lib.т();
	this.instance_15.setTransform(-17.1,-19.9);

	this.instance_16 = new lib.й();
	this.instance_16.setTransform(18.3,-2);

	this.instance_17 = new lib.й();
	this.instance_17.setTransform(-30.4,-22);

	this.instance_18 = new lib.а();
	this.instance_18.setTransform(-41.9,-19.7);

	this.instance_19 = new lib.н();
	this.instance_19.setTransform(29.4,0.2);

	this.instance_20 = new lib.н();
	this.instance_20.setTransform(-53.3,-19.8);

	this.instance_21 = new lib.з();
	this.instance_21.setTransform(-63.9,-19.7);

	this.instance_22 = new lib.і();
	this.instance_22.setTransform(23.5,18.1);

	this.instance_23 = new lib.і();
	this.instance_23.setTransform(9.7,-1.9);

	this.instance_24 = new lib.і();
	this.instance_24.setTransform(-7.9,-1.9);

	this.instance_25 = new lib.і();
	this.instance_25.setTransform(39,-21.9);

	this.instance_26 = new lib.і();
	this.instance_26.setTransform(-70.7,-21.9);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AixDEIAJgxQgFAFgGACQgGACgGAAQgSAAgHgKQgIgKAAgSQAAgQAFgNQAEgNAHgKQAJgKAKgGQANgFAMAAQAIAAAFADIAIgrIAcAAIgIAzQAEgFAGgDQAGgDAIAAQAQAAAHAKQAIALAAASQAAARgFAMQgEANgHALQgIAIgKAGQgLAFgNAAIgHAAIgHgCIgIAqgAh6BJQgGAGgBAJIgIAsIAEACIAFABQAOAAAIgOQAHgNAAgXQABgIgDgEQgCgFgHAAQgHAAgFAFgAiyBGQgFAEgDAIQgCAEgDALIgCARIABAIIABAHQABACADACQADACACAAQAJAAAEgFQAFgFABgIIAJgxIgGgCIgFAAQgHAAgGAEgABMCwIAEgaIgFgDQgDgCgCgGQgLARgVAAQgJAAgGgCQgGgCgDgEQgDgEgCgFQgBgFgBgGIAOhQIAdAAIgNBMQAAAEACADQACADAHAAQAHAAAEgEQAFgFACgHIAMhGIAeAAIgNBKQgBAHACADQAEAFAEAAIAEABIgGAmgAH6CWIAkgzIgQgvIAagGIANApIACABIACgBIAZgpIAXAGIgeAxIASAxIgbAFIgMgkIgCgEQAAAAAAgBQAAAAgBAAQAAAAAAAAQgBgBAAAAIgCABIgdApgArmgRIAFgdIg8AAIgGAdIgeAAIAJg1IAMAAQAEgFADgEIAGgMIAdhjIBPAAIgVB4IANAAIgKA1gAsBhaQgFAMgGAIIAmAAIARhgIgXAAgAMbg4QgFAGgIAEQgFAEgMAAQgKAAgEgEQgFgEgDgHQgGAHgIAEQgGAEgMAAQgOAAgGgHQgGgGAAgMIABgJIABgIIALhCIAeAAIgNBNIABAGQACADAFAAQAGAAAEgFQAFgFACgKIAMhCIAdAAIgNBNQAAAFACACQACACAFAAQAGAAAEgFQAFgGACgJIALhCIAdAAIgOBRIAIAQIgWALgAFCguQgGgDgGgHQgFgIgCgIIgCgTQAAgNAEgRQAEgPAIgMQAGgLANgLQANgJAQgBIALgCQAFAAADgCQADgCACgCIADgHIASAEQgCAJgCAEQgCAEgDADQgFAHgFACQgHADgIABIgSABQgHACgEAEQgFACgDAHIgGAOQAHgGAHgEQAHgDALAAQAJAAAGADQAHAFAEADQAEAGABAHQACAGAAAIQAAAOgEALQgDAKgIAKQgIAIgKADQgJAFgOAAQgMAAgIgEgAFYh2QgGAFgCAEQgDAHgBAGQgBAGAAAGQAAALAEAFQAEAFAGgBQAGAAAEgDQAFgEACgEQADgGABgFQACgHgBgHQAAgJgCgGQgEgFgHgBQgGAAgEADg");
	this.shape.setTransform(-5.1,-9.8);

	this.addChild(this.shape,this.instance_26,this.instance_25,this.instance_24,this.instance_23,this.instance_22,this.instance_21,this.instance_20,this.instance_19,this.instance_18,this.instance_17,this.instance_16,this.instance_15,this.instance_14,this.instance_13,this.instance_12,this.instance_11,this.instance_10,this.instance_9,this.instance_8,this.instance_7,this.instance_6,this.instance_5,this.instance_4,this.instance_3,this.instance_2,this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-88.6,-29.8,177.2,59.6);


(lib.t5 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.Symbol_1();
	this.instance.setTransform(28.7,18.2);

	this.instance_1 = new lib.з();
	this.instance_1.setTransform(-4.3,20);

	this.instance_2 = new lib.а();
	this.instance_2.setTransform(-14,20);

	this.instance_3 = new lib.и();
	this.instance_3.setTransform(71.3,0.1);

	this.instance_4 = new lib.д();
	this.instance_4.setTransform(59.8,-1.9);

	this.instance_5 = new lib.н();
	this.instance_5.setTransform(48.6,0);

	this.instance_6 = new lib.г();
	this.instance_6.setTransform(28.9,0);

	this.instance_7 = new lib.е();
	this.instance_7.setTransform(38.3,0);

	this.instance_8 = new lib.е();
	this.instance_8.setTransform(19.8,0);

	this.instance_9 = new lib.л();
	this.instance_9.setTransform(8.8,0.1);

	this.instance_10 = new lib.в();
	this.instance_10.setTransform(-4.7,0);

	this.instance_11 = new lib.і();
	this.instance_11.setTransform(-12.7,-2.2);

	this.instance_12 = new lib.р();
	this.instance_12.setTransform(-26,22);

	this.instance_13 = new lib.р();
	this.instance_13.setTransform(-43.8,2);

	this.instance_14 = new lib._0();
	this.instance_14.setTransform(-58.5,-1.8);

	this.instance_15 = new lib.м();
	this.instance_15.setTransform(18.6,20);

	this.instance_16 = new lib.о();
	this.instance_16.setTransform(6.3,20);

	this.instance_17 = new lib.о();
	this.instance_17.setTransform(-31.9,0);

	this.instance_18 = new lib.о();
	this.instance_18.setTransform(46.1,-20);

	this.instance_19 = new lib.м();
	this.instance_19.setTransform(33.9,-20);

	this.instance_20 = new lib.є();
	this.instance_20.setTransform(23.1,-20);

	this.instance_21 = new lib.у();
	this.instance_21.setTransform(12,-17.8);

	this.instance_22 = new lib.к();
	this.instance_22.setTransform(-20.7,0);

	this.instance_23 = new lib.к();
	this.instance_23.setTransform(2.4,-20);

	this.instance_24 = new lib.т();
	this.instance_24.setTransform(-11.6,-20.2);

	this.instance_25 = new lib.я();
	this.instance_25.setTransform(-24.9,-20);

	this.instance_26 = new lib.в();
	this.instance_26.setTransform(-34.7,-20);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AikCpQgMgEgIgHIALgTQAJAGAIADQAJAEAJAAQAGAAAFgDQAFgBADgEQADgEACgFQABgFAAgGQAAgKgFgEQgEgFgIAAQgGAAgGACQgEABgIAFIgNgKIAThKIBLAAIgFAZIg0AAIgJAiIAJgDIALgBQAGAAAIACQAHADAFAEQAFAFADAGQADAIAAAJQAAAMgEAJQgDAKgHAHQgHAIgKADQgLAEgNAAQgPAAgMgFgABegbQgKgFgFgIQgFgHgDgLQgCgLAAgKQAAgWAGgSQAGgRAKgMQAKgMAOgHQANgGAQAAQAMAAAKADQALADAIAHIgNAUQgGgEgHgCQgIgDgHAAQgIAAgJAFQgHAFgGAJQgGAKgDAMQgDAOAAANQAAAHABAGQABAFADAGQADAFAEACQAEACAHAAQAJAAAHgCIARgIIAJAWQgKAGgNAEQgLADgPAAQgOAAgKgEg");
	this.shape.setTransform(-57.7,-12);

	this.addChild(this.shape,this.instance_26,this.instance_25,this.instance_24,this.instance_23,this.instance_22,this.instance_21,this.instance_20,this.instance_19,this.instance_18,this.instance_17,this.instance_16,this.instance_15,this.instance_14,this.instance_13,this.instance_12,this.instance_11,this.instance_10,this.instance_9,this.instance_8,this.instance_7,this.instance_6,this.instance_5,this.instance_4,this.instance_3,this.instance_2,this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-76.3,-29.5,152.6,59.1);


(lib.t4 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.в();
	this.instance.setTransform(-4,-0.1);

	this.instance_1 = new lib._1();
	this.instance_1.setTransform(-31.1,-2.1);

	this.instance_2 = new lib._1();
	this.instance_2.setTransform(-18.1,17.9);

	this.instance_3 = new lib._0();
	this.instance_3.setTransform(-29.6,18);

	this.instance_4 = new lib.у();
	this.instance_4.setTransform(41.6,22);

	this.instance_5 = new lib.к();
	this.instance_5.setTransform(32,19.9);

	this.instance_6 = new lib.о();
	this.instance_6.setTransform(20.8,19.9);

	this.instance_7 = new lib.о();
	this.instance_7.setTransform(-45.9,-0.1);

	this.instance_8 = new lib.д();
	this.instance_8.setTransform(-57.2,-2);

	this.instance_9 = new lib.я();
	this.instance_9.setTransform(57.3,-0.1);

	this.instance_10 = new lib.я();
	this.instance_10.setTransform(48.9,-20.1);

	this.instance_11 = new lib.н();
	this.instance_11.setTransform(47,-0.1);

	this.instance_12 = new lib.н();
	this.instance_12.setTransform(38.6,-20.1);

	this.instance_13 = new lib.п();
	this.instance_13.setTransform(26.9,-20.3);

	this.instance_14 = new lib.р();
	this.instance_14.setTransform(8.8,21.9);

	this.instance_15 = new lib.р();
	this.instance_15.setTransform(16,1.9);

	this.instance_16 = new lib.р();
	this.instance_16.setTransform(15.1,-18.1);

	this.instance_17 = new lib.е();
	this.instance_17.setTransform(27.5,-0.1);

	this.instance_18 = new lib.е();
	this.instance_18.setTransform(6.1,-0.1);

	this.instance_19 = new lib.е();
	this.instance_19.setTransform(5.3,-20.1);

	this.instance_20 = new lib.с();
	this.instance_20.setTransform(-3.9,-20.1);

	this.instance_21 = new lib._1();
	this.instance_21.setTransform(-30.9,-22.1);

	this.instance_22 = new lib.З1();
	this.instance_22.setTransform(-46,-22);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACMEDQgLgOAAgVIACgYIAGgWIAKgVQAFgIAJgIQAJgIAJgEQAIgDANAAQANAAAIADQAKAEAFADIgMATQgHgEgGgCIgMgCQgKAAgJAJQgKAKgFASIAFgCIANgDIAGAAQAIgBAIAEQAIADADAFQAFAFACAHQACAGAAAIQAAANgEALQgEAKgHAHQgIAIgJADQgKAEgKAAQgWAAgLgNgACrDIIgJAEIgDAWQAAALADAHQADAGAJABQAKAAAFgIQAGgIAAgRQAAgKgEgEQgDgGgHABgAjXEOQgFgBgEgBIgHgEQgCgCgBgDIgBgGQAAgGACgEQABgEAHgHIA2gwIAHgIIAEgHIABgJQAAgGgDgDQgDgEgHAAIgKACIgJAEIgQAJIgMgSIAKgHIAMgFIAOgFQAIgCAIABQALgBAGADQAGACAHAFQAFAEACAGQACAFAAAJQAAAIgCAGIgHANIgJAKIg2AvIgBABQAAAAAAAAQABABAAAAQAAAAAAAAQABAAAAAAIBAAAIgFAZgAAGA/QgKgKAAgRQAAgIADgEQABgHADgFIAJgKIAKgGQgGgFgDgGQgEgGAAgLQAAgHADgIQAEgJAGgEQAFgFAKgFQAJgCAMAAQALAAAGACQAHACAGAFQAFAEADAHQADAFAAAHQAAANgHAJQgHAKgLAFQALAGAFAHQAFAJAAAKQAAAKgEAHQgEAJgHAFQgIAGgJAEQgKADgNAAQgXAAgLgKgAAbATQgEAGAAAJQAAAKAFADQAFAGAJAAQAKAAAFgHQAGgFAAgLQAAgIgGgFQgFgFgLgFQgJAFgFAHgAArgvQgEAFAAAIIABAHIAEAGIAFAFIAGADQAGgDAGgIQAFgGAAgIQAAgGgEgFQgFgDgHAAQgIAAgFAFgAACiBIBChwIABgDQAAgBAAAAQAAgBAAAAQgBAAAAAAQgBgBgBAAIg9AAIAFgYIBRAAQAJAAAEADQADAEAAAFQAAAEgCAFIhGB5g");
	this.shape.setTransform(-23.7,-1.9);

	this.addChild(this.shape,this.instance_22,this.instance_21,this.instance_20,this.instance_19,this.instance_18,this.instance_17,this.instance_16,this.instance_15,this.instance_14,this.instance_13,this.instance_12,this.instance_11,this.instance_10,this.instance_9,this.instance_8,this.instance_7,this.instance_6,this.instance_5,this.instance_4,this.instance_3,this.instance_2,this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-62.2,-29.6,124.5,59.2);


(lib.t2 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.Symbol_1();
	this.instance.setTransform(58.6,18.4);

	this.instance_1 = new lib.в();
	this.instance_1.setTransform(50.1,20.3);

	this.instance_2 = new lib.й();
	this.instance_2.setTransform(39.4,18);

	this.instance_3 = new lib.а();
	this.instance_3.setTransform(28,20.3);

	this.instance_4 = new lib.З1();
	this.instance_4.setTransform(-47.1,-21.7);

	this.instance_5 = new lib.р();
	this.instance_5.setTransform(15.9,22.2);

	this.instance_6 = new lib.д();
	this.instance_6.setTransform(5.1,18.3);

	this.instance_7 = new lib.т();
	this.instance_7.setTransform(-18,20.1);

	this.instance_8 = new lib.с();
	this.instance_8.setTransform(-29.9,20.3);

	this.instance_9 = new lib.е();
	this.instance_9.setTransform(-39.8,20.3);

	this.instance_10 = new lib.т();
	this.instance_10.setTransform(-53.5,20.1);

	this.instance_11 = new lib.й();
	this.instance_11.setTransform(60.4,-2);

	this.instance_12 = new lib.и();
	this.instance_12.setTransform(49.1,0.4);

	this.instance_13 = new lib.н();
	this.instance_13.setTransform(37.6,0.2);

	this.instance_14 = new lib.р();
	this.instance_14.setTransform(25.7,2.2);

	this.instance_15 = new lib.є();
	this.instance_15.setTransform(16.4,0.3);

	this.instance_16 = new lib.Symbol();
	this.instance_16.setTransform(9.9,-6.4);

	this.instance_17 = new lib.м();
	this.instance_17.setTransform(-0.1,0.2);

	this.instance_18 = new lib.е();
	this.instance_18.setTransform(-11.4,0.3);

	this.instance_19 = new lib.р();
	this.instance_19.setTransform(-22.9,2.2);

	this.instance_20 = new lib.п();
	this.instance_20.setTransform(-34.1,0.1);

	this.instance_21 = new lib.а();
	this.instance_21.setTransform(-48.8,0.3);

	this.instance_22 = new lib.н();
	this.instance_22.setTransform(-60.2,0.2);

	this.instance_23 = new lib.е();
	this.instance_23.setTransform(47.3,-19.7);

	this.instance_24 = new lib.т();
	this.instance_24.setTransform(33.6,-19.9);

	this.instance_25 = new lib.й();
	this.instance_25.setTransform(20.2,-22);

	this.instance_26 = new lib.а();
	this.instance_26.setTransform(8.7,-19.7);

	this.instance_27 = new lib.т();
	this.instance_27.setTransform(-5.5,-19.9);

	this.instance_28 = new lib.і();
	this.instance_28.setTransform(-16.1,-21.9);

	this.instance_29 = new lib.в();
	this.instance_29.setTransform(-24.5,-19.7);

	this.instance_30 = new lib.а();
	this.instance_30.setTransform(-35.4,-19.7);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgfALIAEgVIA7AAIgEAVg");
	this.shape.setTransform(-5.1,19.3);

	this.addChild(this.shape,this.instance_30,this.instance_29,this.instance_28,this.instance_27,this.instance_26,this.instance_25,this.instance_24,this.instance_23,this.instance_22,this.instance_21,this.instance_20,this.instance_19,this.instance_18,this.instance_17,this.instance_16,this.instance_15,this.instance_14,this.instance_13,this.instance_12,this.instance_11,this.instance_10,this.instance_9,this.instance_8,this.instance_7,this.instance_6,this.instance_5,this.instance_4,this.instance_3,this.instance_2,this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-65.4,-29.8,130.9,59.6);


(lib.logo_ = function() {
	this.initialize();

	// ЗАВЖДИ КРАЩЕ
	this.instance = new lib.log();
	this.instance.setTransform(0.5,42.5,1,1,0,0,0,40,27.5);

	// ALWAYS A BETTER WAY
	this.instance_1 = new lib.ALWAYS_mc("synched",0);
	this.instance_1.setTransform(-0.4,187.3,1,1,0,0,0,49.8,21.3);

	// logo
	this.instance_2 = new lib.logo();
	this.instance_2.setTransform(0.5,42,0.582,0.581);

	// Layer 2
	this.instance_3 = new lib.pr();
	this.instance_3.setTransform(0,106.5,0.693,0.967,0,0,0,88,110.1);

	// Layer 5
	this.instance_4 = new lib.pr();
	this.instance_4.setTransform(1.8,108.2,0.693,0.967,0,0,0,88,110.1);
	this.instance_4.alpha = 0.398;
	this.instance_4.filters = [new cjs.ColorFilter(0, 0, 0, 1, 0, 0, 0, 0), new cjs.BlurFilter(2, 2, 1)];
	this.instance_4.cache(-2,-2,180,224);

	this.addChild(this.instance_4,this.instance_3,this.instance_2,this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-61,0,127.8,218.8);


(lib.img2_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// wheels
	this.instance = new lib.wheel_1();
	this.instance.setTransform(100,28,0.271,0.66,-1.7);
	this.instance.alpha = 0.5;

	this.instance_1 = new lib.wheel_1();
	this.instance_1.setTransform(25.7,39.4,0.5,1);
	this.instance_1.alpha = 0.5;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(31));

	// speed
	this.instance_2 = new lib.speed();
	this.instance_2.setTransform(0,109.8);
	this.instance_2.alpha = 0.602;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(31));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("Ayur7MAldAAAIAAUjIlTAPI4HCEIoDBCg");
	mask.setTransform(0,-98.5);

	// Layer 4
	this.instance_3 = new lib.img2Mc();
	this.instance_3.setTransform(0,13);

	this.instance_3.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({alpha:0},15).to({alpha:1},15).wait(1));

	// Layer 1
	this.instance_4 = new lib.img2Mc();

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(31));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-120,-240,240,480.2);


(lib.img1_1 = function() {
	this.initialize();

	// Layer 3 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AvJLGIAA2LIeTAAIAAWLg");
	mask.setTransform(-375.1,9.1);

	// Layer 2
	this.instance = new lib.img2Mc();
	this.instance.setTransform(-374.1,0,0.82,0.82);

	this.instance.mask = mask;

	// Layer 1
	this.instance_1 = new lib.img1();
	this.instance_1.setTransform(-489.5,-270.7,0.8,0.8);

	this.addChild(this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-489.5,-270.7,979,541.5);


(lib.banner = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// urText
	this.instance = new lib.urText();
	this.instance.setTransform(0,181.6,1,1.001);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(524).to({_off:false},0).to({alpha:1},10).wait(40).to({alpha:0},10).to({_off:true},1).wait(5));

	// logoTxt
	this.instance_1 = new lib.Symbol1();
	this.instance_1.setTransform(86.2,-162.3,0.837,0.837);
	this.instance_1.shadow = new cjs.Shadow("#000000",0,0,5);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(509).to({scaleX:3.94,scaleY:3.95,x:0.2,y:126.3},15).wait(50).to({scaleX:0.84,scaleY:0.84,x:86.2,y:-162.3},15).wait(1));

	// logoZnack
	this.instance_2 = new lib.logo_("synched",0);
	this.instance_2.setTransform(106.7,-240,0.343,0.343,0,0,0,60.6,0);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(509).to({startPosition:0},0).to({regX:61,scaleX:1.62,scaleY:1.62,x:97.2,y:-239.8},15).wait(50).to({startPosition:0},0).to({regX:60.6,scaleX:0.34,scaleY:0.34,x:106.7,y:-240},15).wait(1));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_459 = new cjs.Graphics().p("ApfJfQj8j8AAljQAAljD8j8QD9j8FiAAQFjAAD8D8QD9D8AAFjQAAFjj9D8Qj8D8ljAAQliAAj9j8g");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(459).to({graphics:mask_graphics_459,x:0,y:6}).wait(31).to({graphics:null,x:0,y:0}).wait(100));

	// gradient
	this.instance_3 = new lib.gradient();
	this.instance_3.setTransform(-117.6,-91.6,1.391,2.087,45);
	this.instance_3.alpha = 0.91;
	this.instance_3.compositeOperation = "lighter";
	this.instance_3._off = true;

	this.instance_3.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(459).to({_off:false},0).to({x:143.6,y:87.6},30).to({_off:true},1).wait(100));

	// logo3
	this.instance_4 = new lib.logo3_1();
	this.instance_4.setTransform(0,5.5,0.01,0.01);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(439).to({_off:false},0).to({scaleX:1,scaleY:1},10,cjs.Ease.get(1)).wait(50).to({alpha:0},10).to({_off:true},1).wait(80));

	// t6
	this.instance_5 = new lib.t6();
	this.instance_5.setTransform(-232.9,148.6,1.2,1.2);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(389).to({_off:false},0).to({x:0},10,cjs.Ease.get(1)).wait(30).to({alpha:0},10).to({_off:true},1).wait(150));

	// t5
	this.instance_6 = new lib.t5();
	this.instance_6.setTransform(-232.9,148.4,1.2,1.2);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(339).to({_off:false},0).to({x:0},10,cjs.Ease.get(1)).wait(30).to({alpha:0},10).to({_off:true},1).wait(200));

	// t4
	this.instance_7 = new lib.t4();
	this.instance_7.setTransform(-232.9,148.3,1.2,1.2);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(289).to({_off:false},0).to({x:0},10,cjs.Ease.get(1)).wait(30).to({alpha:0},10).to({_off:true},1).wait(250));

	// t2
	this.instance_8 = new lib.t2();
	this.instance_8.setTransform(-206.9,148.6,1.2,1.2);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(239).to({_off:false},0).to({x:0},10,cjs.Ease.get(1)).wait(30).to({alpha:0},10).to({_off:true},1).wait(300));

	// t3
	this.instance_9 = new lib.t3();
	this.instance_9.setTransform(0,222);
	this.instance_9.alpha = 0;
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(239).to({_off:false},0).to({alpha:1},10).wait(180).to({alpha:0},10).to({_off:true},1).wait(150));

	// logo2
	this.instance_10 = new lib.logo2();
	this.instance_10.setTransform(-200,-155.4);
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(229).to({_off:false},0).to({x:-30.2},10,cjs.Ease.get(1)).wait(190).to({alpha:0},10).to({_off:true},1).wait(150));

	// img2
	this.instance_11 = new lib.img2_1();
	this.instance_11.alpha = 0;
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(219).to({_off:false},0).to({alpha:1},10).wait(200).to({alpha:0},10).to({_off:true},1).wait(150));

	// t7
	this.instance_12 = new lib.t7();
	this.instance_12.setTransform(-208.8,168.7,1.2,1.2);
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(174).to({_off:false},0).to({x:0},8,cjs.Ease.get(1)).wait(27).to({alpha:0},10).to({_off:true},1).wait(370));

	// img1
	this.instance_13 = new lib.img1_1();
	this.instance_13.setTransform(-369.5,0);
	this.instance_13.alpha = 0;
	this.instance_13._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(54).to({_off:false},0).to({x:-282.9,alpha:1},15).to({x:369.5},113).wait(27).to({scaleX:1.22,scaleY:1.22,x:457.1},10).to({_off:true},11).wait(360));

	// t1_3
	this.instance_14 = new lib.t1_3();
	this.instance_14.setTransform(-207.9,35.8);
	this.instance_14._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(20).to({_off:false},0).to({x:0},10,cjs.Ease.get(1)).wait(24).to({alpha:0},10).to({_off:true},1).wait(525));

	// t1_2
	this.instance_15 = new lib.t1_2();
	this.instance_15.setTransform(-209,7);
	this.instance_15._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_15).wait(10).to({_off:false},0).to({x:-1},10,cjs.Ease.get(1)).wait(34).to({alpha:0},10).to({_off:true},1).wait(525));

	// t1_1
	this.instance_16 = new lib.t1_1();
	this.instance_16.setTransform(-208,-23.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_16).to({x:-0.1},10,cjs.Ease.get(1)).wait(44).to({alpha:0},10).to({_off:true},1).wait(525));

	// bg
	this.instance_17 = new lib.bg();

	this.timeline.addTween(cjs.Tween.get(this.instance_17).wait(590));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-251.5,-240.6,371.6,481.2);


// stage content:
(lib._300x600 = function() {
	this.initialize();

	// cover
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#666666").ss(2,1,1).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape.setTransform(150,300);

	// banner
	this.instance = new lib.banner();
	this.instance.setTransform(150,300,1.25,1.25);

	this.addChild(this.instance,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-14.4,299,465.4,602);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;