(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.img1 = function() {
	this.initialize(img.img1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.img2 = function() {
	this.initialize(img.img2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.img3 = function() {
	this.initialize(img.img3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.img4 = function() {
	this.initialize(img.img4);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.img5 = function() {
	this.initialize(img.img5);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.urText = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ADcAaIgBgCIgBguQAAgBABgBQAAAAAAgBQABAAAAAAQABAAABAAIAPgBQAIAAAFAEQAGAFAAAHQAAAHgFAFQgFAFgIAAIgMAAIAAARQAAABAAABQAAAAAAABQgBAAAAAAQgBABgBAAIgDgCgADiACIAKgBQAGAAADgCQAEgDAAgGQAAgEgEgEQgDgCgGAAIgKAAgACfAZIAAgCIATgtQABgEAEgBQADABACAEIAUAtIAAABQAAABAAABQAAAAAAAAQgBABAAAAQgBAAgBAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBgBgBIgEgKIgbAAIgEALQAAABAAAAQgBABAAAAQgBAAAAAAQgBABgBAAQAAAAgBgBQgBAAAAAAQgBAAAAgBQAAAAAAgBgACsAIIAWAAIgLgbgABGAaIgBgCIgBguIABgDIADgBQABAAABAAQAAAAABABQAAAAABABQAAAAAAABIAAAUIAagWIADgCIACABIABADQAAAAAAAAQAAABAAAAQAAAAAAAAQgBABAAAAIgYAUIAbAXIABACQABABgBABQAAAAAAAAQgBABAAAAQgBAAgBAAIgEgCIgcgXIABAWQAAAEgEAAIgDgCgAgTAZIABgCIASgtQABgEADgBQAEABABAEIAUAtIABABQAAABAAABQAAAAgBAAQAAABgBAAQgBAAgBAAQAAAAgBAAQAAAAgBgBQAAAAAAAAQgBgBAAgBIgFgKIgaAAIgEALQAAABAAAAQAAABgBAAQAAAAgBAAQAAABgBAAQgBAAAAgBQgBAAAAAAQgBAAAAgBQAAAAgBgBgAgFAIIAVAAIgMgbgAg+AaIgBgCIgBguQAAgBABgBQAAAAAAgBQABAAAAAAQABAAABAAIAOgBQAJAAAFAEQAGAFAAAHQAAAHgFAFQgFAFgIAAIgMAAIAAARQAAABAAABQAAAAAAABQgBAAAAAAQgBABgBAAIgDgCgAg4ACIAKgBQAGAAADgCQAEgDgBgGQAAgEgDgEQgDgCgGAAIgLAAgAhfAaIgBgCIgBgsIgLAAIgCgBIgBgBIABgDIACAAIAegBQABAAABAAQAAAAABAAQAAABAAAAQAAABAAABQAAAAAAABQAAAAAAABQgBAAAAAAQgBAAgBAAIgLABIAAAsIgBACIgCACIgDgCgAjTAaIgCgCIAAguIABgDIACgBQABAAABAAQABAAAAABQABAAAAABQAAAAAAABIAAAUIAagWIADgCIADABIAAADQAAAAAAAAQAAABAAAAQAAAAAAAAQgBABAAAAIgYAUIAbAXQABAAAAAAQAAAAABABQAAAAAAABQAAAAAAAAQAAABAAABQAAAAgBAAQAAABgBAAQgBAAgBAAIgEgCIgcgXIABAWQAAABAAABQAAAAgBABQAAAAgBAAQgBABgBAAIgCgCgAidATQgGgHgBgLQAAgLAHgIQAHgIAMgBQAKABAGAEQAAABABAAQAAABAAAAQABAAAAABQAAAAAAAAIgBADIgDABIgCgCIgDgCQgEgBgFgBQgJABgFAHQgEAGAAAIQAAAIAFAFQAFAIAIAAQAGgBAFgCIACgCIAEgBQABAAAAABQABAAAAAAQAAABAAAAQAAABAAABIgBACQgCADgGABIgJABIgBAAQgLAAgIgIgAB5AXIgBgtIABgCIACgBIAWgBQABAAABAAQABAAAAABQABAAAAABQAAAAAAABQAAABAAAAQAAABgBAAQAAABgBAAQgBAAgBAAIgSAAIABAQIARAAQABABABAAQAAAAABAAQAAAAAAABQAAAAAAABQAAABAAAAQAAAAAAAAQgBABAAAAQgBAAgBAAIgRABIAAATIASAAQABAAABAAQAAAAABAAQAAABAAAAQAAABAAAAQAAABAAABQAAAAAAABQgBAAAAAAQgBAAgBAAIgWABQAAAAgBAAQgBAAAAgBQgBAAAAgBQAAgBAAgBgAj/AXIAAgtIAAgCIADgBIAWgBQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABQAAABAAAAQAAABAAAAQgBABAAAAQgBAAgBAAIgSAAIAAAQIARAAQABABABAAQAAAAABAAQAAAAABABQAAAAAAABQAAABAAAAQAAAAgBAAQAAABgBAAQgBAAgBAAIgRABIABATIASAAQABAAAAAAQABAAAAAAQABABAAAAQAAABAAAAQAAABAAABQAAAAgBABQAAAAgBAAQgBAAgBAAIgVABQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBgBAAgBg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.urText, new cjs.Rectangle(-25.6,-2.7,51.2,5.5), null);


(lib.t4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ag4BCQgVAAAAgVIAAhZQAAgVAPAAQAPAAAAAVIAABVIAjAAIAAhVQAAgKACgEQADgHAHAAQAJAAACAHQACAEAAAKIAABVIAjAAIAAhVQAAgVAPAAQAPAAAAAVIAABZQAAAVgVAAg");
	this.shape.setTransform(107,11.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAbAuIAAg8Ig1BHQgHAKgKAAQgNAAAAgSIAAheQAAgVAOAAQAPAAAAAVIAAA8IA3hIQAGgJAJAAQAOAAAAAUIAABcQAAAVgPAAQgPAAAAgVg");
	this.shape_1.setTransform(91,11.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgaBBQgMAAgFgEQgEgEAAgMIAAhYQAAgMAEgFQAFgFAMAAIAtAAQAWAAAAAOQAAAOgWAAIgkAAIAAAOIATAAQAVAAANAMQAMALAAAVQAAAVgNAMQgNALgWAAgAgRAmIANAAQATAAABgRQgBgSgTAAIgNAAg");
	this.shape_2.setTransform(78.7,11.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgOAyQgNgPgCgYIgUAAIAAAjQAAAVgOAAQgPAAAAgVIAAhbQAAgVAPAAQAOAAAAAVIAAAfIAVAAQACgYANgNQANgPAYAAQAcAAAOAVQANARAAAcQAAAwghAPQgKAEgMAAQgYAAgOgRgAAJggQgFAGgDAMIAAAOQAAAQAEALQAGAOANAAQANAAAHgOQAEgLAAgQQAAgUgHgLQgGgKgLAAQgKAAgFAJg");
	this.shape_3.setTransform(64.2,11.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAgA8QgDgEAAgKIAAhWIgfAAQgGAAAAAIIAABIQAAAbgbAAQgXAAAAgOQAAgIAEgDQACgCAIAAQAFAAACgCQACgBAAgHIAAg+QAAgSAHgJQAHgHATAAIAuAAQAPAAAAAVIAABbQAAAVgPAAQgJAAgDgHg");
	this.shape_4.setTransform(47.8,11.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgtAwQgRgTAAgdQAAgcARgTQAQgTAdAAQAdAAARATQARATAAAcQAAAdgRATQgRATgdAAQgdAAgQgTgAgXgaQgHAKAAARQAAAPAHALQAIAMAPAAQAQABAIgMQAHgMAAgPQAAgQgHgLQgIgNgQAAQgPAAgIANg");
	this.shape_5.setTransform(27.9,11.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AglAtIAAhZQAAgMAFgFQAEgEAMAAIAhAAQAVAAAAAOQAAANgVAAIgYAAIAABTQAAAVgPAAQgPAAAAgVg");
	this.shape_6.setTransform(17.9,12);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AguAwQgQgTAAgdQAAgcAQgTQARgTAdAAQAeAAAQATQARASAAAdQAAAdgRATQgSATgcAAQgcAAgSgTgAgXgaQgHAKAAARQAAAQAHAKQAIAMAPAAQAPABAJgMQAHgMAAgPQAAgRgHgKQgIgNgQAAQgPAAgIANg");
	this.shape_7.setTransform(6,11.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAWA5IgmguIgFAEIAAAfQAAAVgPAAQgPAAAAgVIAAhbQAAgVAPAAQAPAAAAAVIAAAdIAlgoQAKgKAGAAQAGAAAEAEQAFAEAAAGQAAAEgFAFIglAlIAoAsQAHAJAAAGQAAAFgEAFQgFAEgFAAQgHAAgJgKg");
	this.shape_8.setTransform(-5.7,11.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgQAaQgEgEgBgFQABgDADgGIAOgZQAFgLAHAAQAFAAAEAEQADADAAAFQAAAEgCAFIgPAaQgFAKgHAAQgFAAgDgDg");
	this.shape_9.setTransform(-21.3,18.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAaA4IgaglIgaAlQgIALgIAAQgEAAgFgEQgEgEAAgFQAAgHAHgIIAfgqIgYgjQgGgKAAgEQAAgHAEgDQADgEAHAAQAIAAAHAMIASAbIATgcQAIgLAIAAQAGAAADAEQAEADAAAGQAAAFgHAKIgYAjIAgAqQAHAKAAAGQAAAFgEAEQgEADgGAAQgIAAgIgLg");
	this.shape_10.setTransform(-28.3,11.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAbAuIAAg8Ig1BHQgHAKgKAAQgNAAAAgSIAAheQAAgVAOAAQAPAAAAAVIAAA8IA3hIQAGgJAJAAQAOAAAAAUIAABcQAAAVgPAAQgPAAAAgVg");
	this.shape_11.setTransform(-40.8,11.9);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgOAtIAAhTIgUAAQgMgDAAgKQAAgOAVAAIAzAAQAVAAAAAOQAAAKgMADIgUAAIAABTQAAAVgPAAQgOAAAAgVg");
	this.shape_12.setTransform(-52.4,12);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgtAwQgRgTAAgdQAAgcARgTQARgTAcAAQAdAAARATQARATAAAcQAAAdgRATQgRATgdAAQgcAAgRgTgAgXgaQgHALAAAQQAAAPAHALQAIAMAPAAQAQABAIgMQAHgMAAgPQAAgQgHgLQgIgNgQAAQgPAAgIANg");
	this.shape_13.setTransform(-70.2,11.9);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgvAtIAAhZQAAgMAFgFQAEgEAMAAIAaAAQAWAAAMALQAOAMAAAVQAAAVgNALQgMAMgVAAIgTAAIAAAWQAAAVgPAAQgPAAAAgVgAgRgDIANAAQAUAAgBgSQABgRgUAAIgNAAg");
	this.shape_14.setTransform(-82.4,12);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAcAtIAAhUIg2AAIAABUQAAAVgPAAQgPAAAAgVIAAhZQAAgVAUAAIBJAAQAUAAAAAVIAABZQAAAVgPAAQgOAAAAgVg");
	this.shape_15.setTransform(-95.4,12);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAbA1IgEgPIguAAIgFAQQgEANgLAAQgFAAgFgEQgEgEAAgGQAAgEACgEIAihcQAHgTAOAAQARAAAGARIAhBdIACAKQAAAGgFADQgEAEgGAAQgLAAgFgOgAAPALIgPgtIAAAAIgOAtIAdAAg");
	this.shape_16.setTransform(86.2,-10.6);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgOAtIAAhTIgUAAQgMgDAAgKQAAgOAVAAIAzAAQAVAAAAAOQAAAKgMADIgUAAIAABTQAAAVgPAAQgOAAAAgVg");
	this.shape_17.setTransform(76.8,-10.5);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgtAwQgRgTAAgdQAAgcARgTQARgTAcAAQAeAAAQATQARATAAAcQAAAdgRATQgRATgdAAQgcAAgRgTgAgXgaQgHALAAAQQAAAPAHALQAIAMAPAAQAQABAIgMQAHgMAAgPQAAgRgHgKQgIgNgQAAQgPAAgIANg");
	this.shape_18.setTransform(65.7,-10.6);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgaBCQgMgBgEgEQgFgEAAgMIAAhYQAAgMAFgFQAEgFAMAAIAtAAQAWAAAAAPQAAANgWAAIgkAAIAAAOIATAAQAVAAANAMQAMALAAAVQAAAVgOAMQgMALgWABgAgRAmIANAAQATAAAAgRQAAgSgTAAIgNAAg");
	this.shape_19.setTransform(53.5,-10.6);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgvAtIAAhZQAAgMAFgFQAEgEAMAAIAaAAQAWAAANALQANAMAAAVQAAAVgMALQgNAMgVAAIgTAAIAAAWQAAAVgPAAQgPAAAAgVgAgRgDIANAAQATAAABgSQgBgRgTAAIgNAAg");
	this.shape_20.setTransform(42.1,-10.5);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgYBBIACgJIAIgUIglhbQgBgEAAgEQAAgIAEgDQAEgFAGAAQAIABAGANIAYA/IABAAIAYg+QACgHADgDQAEgEAFgBQAOABAAAOQAAADgCAHIgwB5QgCAGgCADQgDADgGABQgOgBAAgOg");
	this.shape_21.setTransform(30.8,-9.4);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgOAtIAAhTIgUAAQgMgDAAgKQAAgOAVAAIAzAAQAVAAAAAOQAAAKgMADIgUAAIAABTQAAAVgPAAQgOAAAAgVg");
	this.shape_22.setTransform(20.8,-10.5);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AAbA1IgEgPIguAAIgFAQQgFANgKAAQgGAAgEgEQgEgEAAgGQAAgEACgEIAihcQAHgTAOAAQAQAAAHARIAgBdQADAHAAADQAAAGgFADQgEAEgGAAQgMAAgEgOgAAPALIgPgtIAAAAIgPAtIAeAAg");
	this.shape_23.setTransform(4.1,-10.6);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("Ag4BCQgVAAAAgVIAAhZQAAgVAPAAQAPAAAAAVIAABVIAjAAIAAhVQAAgKACgEQADgHAHAAQAJAAACAHQACAGAAAIIAABVIAjAAIAAhVQAAgVAPAAQAPAAAAAVIAABZQAAAVgVAAg");
	this.shape_24.setTransform(-10.9,-10.7);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgOAuIAAhbQAAgVAOAAQAPAAAAAVIAABbQAAAVgPAAQgOAAAAgVg");
	this.shape_25.setTransform(-22.8,-10.6);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AAbAuIAAgiIg2AAIAAAiQAAAVgPAAQgOAAAAgVIAAhbQAAgVAOAAQAPAAAAAVIAAAfIA2AAIAAgfQAAgVAPAAQAPAAAAAVIAABbQAAAVgPAAQgPAAAAgVg");
	this.shape_26.setTransform(-32.6,-10.6);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AA3A5IgngvIgCACIAAAiQAAAVgOAAQgNAAAAgVIAAgiIgCgCIgnAvQgJAKgHAAQgGAAgEgEQgEgEAAgFQAAgHAHgJIAogsIglglQgFgFAAgEQAAgFAFgFQAEgEAGAAQAGAAALAKIAiAjIAAgYQAAgVANAAQAIAAAEAGQACAEAAALIAAAYIAigjQALgKAGAAQAGAAAEAEQAFAEAAAGQAAAEgFAFIglAlIAoAsQAHAJAAAHQAAAFgEAEQgFAEgFAAQgHAAgJgKg");
	this.shape_27.setTransform(-48.2,-10.6);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgOAuIAAhbQAAgVAOAAQAPAAAAAVIAABbQAAAVgPAAQgOAAAAgVg");
	this.shape_28.setTransform(-59.6,-10.6);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AAcAuIAAgiIg2AAIAAAiQAAAVgPAAQgPAAAAgVIAAhbQAAgVAPAAQAPAAAAAVIAAAfIA2AAIAAgfQAAgVAPAAQAOAAAAAVIAABbQAAAVgOAAQgPAAAAgVg");
	this.shape_29.setTransform(-69.4,-10.6);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AAbBBIAAg8Ig1BHQgHAKgKAAQgNAAgBgSIAAheQABgVAPAAQAOAAAAAVIAAA9IA2hIQAIgKAIAAQAOAAABAUIAABcQgBAVgPAAQgPAAAAgVgAgVg8QgIgHAAgIQgBgKAKAAQAGAAADAGQAEAGAHAAQAIAAAEgGQADgGAGAAQAJAAABAKQAAAKgLAHQgKAFgKAAQgLAAgKgHg");
	this.shape_30.setTransform(-83.4,-12.5);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AAbA1IgFgPIgtAAIgFAQQgFANgKAAQgGAAgEgEQgEgDAAgHQAAgEACgEIAihcQAHgTAPAAQAQAAAGARIAhBdQACAGAAAEQAAAFgEAEQgFAEgGAAQgLAAgFgOgAAOALIgOgtIAAAAIgOAtIAcAAg");
	this.shape_31.setTransform(-96.2,-10.6);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AAbAuIAAgiIg2AAIAAAiQAAAVgPAAQgOAAAAgVIAAhbQAAgVAOAAQAPAAAAAVIAAAfIA2AAIAAgfQAAgVAPAAQAPAAAAAVIAABbQAAAVgPAAQgPAAAAgVg");
	this.shape_32.setTransform(-109.1,-10.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.t4, new cjs.Rectangle(-114.8,-21.1,229.6,42.3), null);


(lib.t3_mc = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AD2EYQAAgGACgIIAOgiIg8iTQgCgHAAgHQAAgLAGgGQAGgHALAAQANAAAJAVIApBmIABAAIAmhlQAEgKAEgFQAGgHAKAAQAWAAAAAWQAAAJgDAIIhNDFQgEAJgFAGQgFAEgKAAQgVABAAgXgACWD3Ig/hKIgJAHIAAAxQAAAjgYAAQgYAAAAgjIAAiTQAAgjAYABQAYgBAAAjIAAAuIA+g/QAQgSAKABQAKAAAGAGQAIAHAAAJQAAAGgHAJIg9A8IBABJQANANAAAKQAAAIgHAHQgHAIgJAAQgMgBgOgQgAloDoQgbgcAAgwQAAgwAbgeQAcgeAuAAQAvAAAcAeQAaAeAAAwQAAAvgaAeQgcAegvABQguAAgcgggAlFBwQgLARAAAcQAAAaAMARQANATAZAAQAZAAAOgTQALgSAAgZQAAgcgLgRQgNgUgaAAQgZAAgOAUgAh6EFQgSAAgHgGQgHgHAAgSIAAiSQAAgTAHgHQAHgIATAAIAnAAQAdAAAUAMQAYAOAAAbQAAAigZAMIAAABQATAGAIALQAHALAAATQAAAggVASQgUAOghAAgAhqDcIAYAAQAPAAAHgFQAKgEAAgPQAAgRgJgFQgHgEgRAAIgXAAgAhqCEIAUAAQAPABAFgEQAIgEAAgNQAAgVgcAAIgUAAgAp7EFQghAAAAgiIAAiRQAAgjAYABQAYgBAAAjIAACLIA4AAIAAiLQAAgRADgHQAFgLANABQAOgBAEALQAEAHAAARIAACLIA4AAIAAiLQAAgjAYABQAYgBAAAjIAACRQAAAighAAgAlAhwQgbgeAAgwQAAgwAcgfQAdggAvAAQARAAAPAEQATAGAIAKQAEAHAAAGQAAAIgGAHQgGAGgIAAQgIAAgLgEQgKgEgOAAQgbAAgNAUQgMATAAAbQAAAcANAQQAPATAaAAQAMAAANgFQAPgFAEgBQAIABAGAGQAGAHAAAIQAAAHgFAGQgQAWguABQgvgBgdgggAI5h1IAAiGQgZAAgHgCQgTgEAAgRQAAgWAiAAIBTAAQAiAAAAAWQAAARgTAEQgGACgaAAIAACGQAAAjgYgBQgZABAAgjgAHYhkIg/hJIgJAHIAAAxQAAAjgYgBQgYABAAgjIAAiUQAAgiAYAAQAYAAAAAiIAAAuIA+g/QAQgQAKgBQAKABAHAGQAHAHAAAJQAAAHgHAHIg9A9IBBBIQAMAOAAAKQAAAJgHAGQgHAIgJgBQgLABgPgSgAEahpIgIgZIhKAAIgJAbQgHAUgQAAQgKAAgHgGQgGgGAAgKQAAgIACgGIA3iUQAMggAZAAQAaAAAKAcIA1CXQADAJAAAHQAAAKgHAGQgGAFgKAAQgTAAgHgWgAEFitIgXhKIAAAAIgYBKIAvAAgAgCh1IAAiRQAAgTAHgIQAHgHATAAIArAAQAjAAAUASQAWATAAAiQAAAjgUASQgTAUgigBIghAAIAAAkQAAAjgYgBQgXABAAgjgAAtjEIAVAAQAhAAAAgdQAAgbghAAIgVAAgAh4h1IAAiGQgaAAgGgCQgUgEAAgRQAAgWAiAAIBUAAQAiAAAAAWQAAARgTAEQgHACgaAAIAACGQAAAjgYgBQgYABAAgjgAmMhkIg/hJIgJAHIAAAxQAAAjgYgBQgYABAAgjIAAiUQAAgiAYAAQAYAAAAAiIAAAuIA+g/QAQgQAKgBQAKABAHAGQAHAHAAAJQAAAHgHAHIg9A9IBBBIQAMAOAAAKQAAAJgHAGQgHAIgJgBQgLABgPgSgAp8hVQgSAAgHgGQgHgHAAgRIAAiTQAAgTAHgIQAHgHATAAIA2AAQAiAAAAAWQAAAXgiAAIgnAAIAAAmIAiAAQAigBAAAWQAAAXgiAAIgiAAIAAAoIApAAQAiAAAAAWQAAAWgiAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t3_mc, new cjs.Rectangle(-66.9,-30.2,133.9,60.5), null);


(lib.t2_mc = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AM+GlIAAiHQgaAAgGgBQgUgEAAgRQAAgWAjgBIBTAAQAiABAAAWQAAARgTAEQgGABgbAAIAACHQAAAigYAAQgYAAAAgigALIGlIAAg2IhYAAIAAA2QAAAigZAAQgYAAAAgiIAAiUQAAgiAYAAQAZAAAAAiIAAAyIBYAAIAAgyQAAgiAYAAQAYAAAAAiIAACUQAAAigYAAQgYAAAAgigAHmGlIAAiUQAAgiAYAAQAYAAAAAiIAACUQAAAigYAAQgYAAAAgigAEXGoQgageAAgvQAAgvAageQAcgfAvAAQAuAAAcAfQAbAdAAAwQAAAvgbAfQgcAeguAAQgvAAgcgfgAE6EvQgKARgBAcQAAAaAMARQANAUAagBQAYABAOgUQALgRAAgaQAAgcgLgRQgNgUgZAAQgaAAgOAUgACuGlIAAiJIhYAAIAACJQAAAigZAAQgXAAAAgiIAAiSQAAghAggBIB3AAQAhABAAAhIAACSQAAAigYAAQgYAAAAgigAinGoQgbgeAAgvQAAgvAbgeQAbgfAvAAQAwAAAaAfQAaAcAAAxQAAAwgaAeQgcAeguAAQgvAAgbgfgAiDEvQgMARAAAcQAAAaAMARQANAUAZgBQAZABANgUQANgRAAgaQAAgbgMgSQgOgUgZAAQgZAAgNAUgAluGlIAAiSQAAgSAGgIQAIgIASAAIAsAAQAjAAAUASQAXAUAAAiQgBAigTATQgUATgiAAIghAAIAAAkQAAAigYAAQgXAAAAgigAk/FVIAVAAQAiAAgBgcQABgbgiAAIgVAAgAmyG2IhAhJIgIAHIAAAxQAAAigYAAQgYAAAAgiIAAiUQAAgiAYAAQAYAAAAAiIAAAuIA9g/QARgRAKAAQAKAAAGAHQAIAGAAAKQgBAGgGAIIg9A9IBABIQANANAAALQgBAIgGAHQgIAHgIAAQgMAAgOgRgAqDGlIAAiUQAAgiAYAAQAXAAAAAiIAACUQAAAigXAAQgYAAAAgigArHG9QgEgGgCgPIgShzIgBAAIgbBrQgEAPgGAIQgIAKgPAAQgPAAgIgKQgEgGgGgRIgbhrIgBAAIgSB0QgCAPgEAFQgGAKgNAAQgVAAgBgXIAaigQACgPAKgJQAKgJAPAAQANAAAJAIQAIAHAFANIAcB3IAAAAIAch3QAEgNAIgHQAKgIANAAQAPAAAKAJQAKAKACAOIAaCgQAAAXgXAAQgMAAgGgKgAIJDWQgHgGAAgNQAAgMAHgIQAJgIAMAAQAMAAAIAIQAIAIAAAMQAAANgIAGQgIAJgMgBQgMABgJgJgAHGDWQgJgGAAgNQAAgMAJgIQAHgIANAAQAMAAAGAIQAJAIAAAMQAAANgJAGQgGAJgMgBQgNABgHgJgAoGBPQgbgeAAgwQAAgvAcgfQAeghAuAAQARAAAPAFQASAFAJALQAEAGAAAHQAAAIgGAHQgGAGgJAAQgHAAgLgEQgKgFgOAAQgaABgOAUQgMASAAAbQAAAaANASQAPATAaAAQAMgBANgFQAQgFAEAAQAHAAAGAGQAGAIAAAHQAAAIgFAFQgPAXgvAAQgvAAgdgggAJHBKIAAg0Ig4BHQgNAPgNAAQgJAAgHgGQgHgGABgJQAAgMANgQIAmgqQgXgEgOgOQgNgOAAgYQAAgdAUgSQAVgSAoAAIAlAAQASAAAIAHQAHAIAAATIAACQQAAAigYAAQgYAAAAgigAISgjQAAAaAfAAIAWAAIAAgzIgXAAQgeAAAAAZgAGHBKIAAg2IhZAAIAAA2QAAAigYAAQgYAAAAgiIAAiTQAAgiAYAAQAYAAAAAiIAAAyIBZAAIAAgyQAAgiAYAAQAXAAAAAiIAACTQAAAigXAAQgYAAAAgigACmBKIAAg2IhZAAIAAA2QAAAigYAAQgYAAAAgiIAAiTQAAgiAYAAQAYAAAAAiIAAAyIBZAAIAAgyQAAgiAYAAQAXAAAAAiIAACTQAAAigXAAQgYAAAAgigAjTBKIAAg2IhZAAIAAA2QAAAigYAAQgXAAAAgiIAAiTQAAgiAXAAQAYAAAAAiIAAAyIBZAAIAAgyQAAgiAYAAQAYAAAAAiIAACTQAAAigYAAQgYAAAAgigApvBKIAAhgIhXByQgMAQgQAAQgVAAAAgdIAAiYQAAgiAYAAQAYAAAAAiIAABiIBYh1QANgPANAAQAWAAABAgIAACVQAAAigYAAQgZAAAAgigAttBKIAAiFQgagBgHgBQgTgEAAgRQAAgXAiABIBTAAQAjgBgBAXQABARgUAEQgGABgaABIAACFQAAAigYAAQgZAAABgigAhaBpQgSAAgHgFQgIgHABgSIAAiRQgBgTAIgIQAHgHATAAIA2AAQAigBAAAXQAAAWgiABIgoAAIAAAlIAjAAQAhAAABAWQgBAVghAAIgjAAIAAAoIAqAAQAhAAAAAXQAAAVghAAgAiykQIAAg2IhYAAIAAA2QAAAigZAAQgYAAAAgiIAAiUQAAgiAYAAQAZAAAAAiIAAAyIBYAAIAAgyQAAgiAYAAQAYAAAAAiIAACUQAAAigYAAQgYAAAAgigAmBj/Ig+hKIgEACIAAA3QAAAigWAAQgWAAgBgiIAAg3IgDgDIg/BLQgOARgMAAQgIAAgHgHQgHgGAAgJQAAgKAMgOIA/hKIg7g7QgHgIAAgHQAAgIAHgHQAHgHAJAAQALAAAQARIA3A5IAAgoQABgiAWAAQAOAAAFALQADAHAAAQIAAAnIA3g4QARgRAKAAQAKAAAGAHQAIAHAAAIQAAAHgHAIIg7A7IA/BKQAMAOAAAKQAAAIgHAHQgHAHgIAAQgMAAgPgRgAqpkQIAAiUQAAgiAYAAQAYAAAAAiIAACUQAAAigYAAQgYAAAAgigAsCkQIAAg2IhZAAIAAA2QAAAigYAAQgYAAAAgiIAAiUQAAgiAYAAQAYAAAAAiIAAAyIBZAAIAAgyQAAgiAXAAQAYAAAAAiIAACUQAAAigYAAQgXAAAAgigAg5jwQgSgBgIgGQgGgHgBgRIAAiTQABgSAGgIQAIgIASAAIA3AAQAhABAAAWQAAAXghgBIgnAAIAAAmIAiAAQAgAAAAAWQAAAWggAAIgiAAIAAApIAoAAQAiAAgBAVQABAXgiAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t2_mc, new cjs.Rectangle(-93,-45.5,186,91), null);


(lib.t1_mc = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AqdHUQgGgGAAgJIAAgTIiBAAQghAAAAgiIAAiSQAAgiAYAAQAYAAAAAiIAACMIBUAAIAAiMQAAgiAYAAQAYAAAAAiIAACMQAZAAAAAUIAAAnQAAAVgVAAQgKAAgGgGgAMkGSIAAhhIhXBzQgMAQgQAAQgWAAAAgcIAAiaQAAgiAYAAQAYAAAAAiIAABjIBZh1QAMgQAOAAQAWAAAAAgIAACWQAAAigYAAQgYAAAAgigAH+GuQgbgJAAgUQAAgTAUAAQAHAAAJAEIAQAGQAHABANAAQAgAAAAgYQAAgLgHgHQgGgGgLgCIgTAAQgeAAAAgUQAAgJAJgGQAFgEALgBIASAAQALAAAHgEQAJgGAAgKQAAgXgdAAQgIAAgPAEQgPAEgGAAQgUAAAAgSQAAgGAFgGQASgSArAAQBLAAAAA6QAAAfgdAMIAAABQAiANAAAjQAABChTAAQgaAAgSgGgAEjGVQgbgdAAgwQAAguAbgfQAcgfAuAAQAwAAAbAfQAaAdAAAwQAAAwgaAeQgcAegvAAQguAAgcgfgAFGEdQgLARAAAbQAAAaAMARQANAUAZAAQAZAAAOgUQAMgRAAgaQAAgbgMgRQgNgVgaAAQgZAAgOAVgAC+GqQgEgHAAgRIAAiLIgzAAQgLAAAAANIAAB1QAAArgqAAQgnAAAAgWQAAgNAIgFQAEgCALgBQAKAAADgDQADgDAAgJIAAhmQAAgfALgNQALgMAfAAIBLAAQAYAAAAAiIAACUQAAAigYAAQgPAAgFgKgAiAGaQgWgZgDgoIgeAAIAAA5QAAAigYAAQgYAAAAgiIAAiUQAAgiAYAAQAYAAAAAiIAAAzIAfAAQAFgmAVgXQAXgYAlAAQAuAAAVAhQAVAdAAAuQAABOg0AXQgQAHgUAAQgnAAgXgagAhbETQgIALgDASQgBALAAANQAAAYAHATQAJAYAWAAQAVAAAKgYQAHgTAAgYQAAghgLgRQgLgRgQAAQgQAAgKAOgAk8GqQgEgIAAgQIAAiLIgzAAQgLAAAAANIAAB1QAAArgqAAQgnAAAAgWQAAgNAIgFQAEgCALgBQAKAAADgDQADgDAAgJIAAhmQAAgfALgNQALgMAfAAIBLAAQAYAAAAAiIAACUQAAAigYAAQgOAAgGgKgAo/GyQgSAAgHgGQgHgHAAgSIAAiSQAAgTAHgIQAHgHATAAIA2AAQAiAAAAAWQAAAXgiAAIgnAAIAAAlIAhAAQAjAAAAAWQAAAWgjAAIghAAIAAApIAoAAQAiAAAAAWQAAAWgiAAgAmXB5QgGgGAAgJIAAgTIh6AAIAAATQAAAJgGAGQgGAGgKAAQgKAAgGgGQgFgGAAgJIAAgnQAAgUATAAQAFAAADgJQADgJAAgWIAAhNQAAgZAOgOQAOgOAZAAIBJAAQAQAAAGAKQAFAHAAARIAACIQAZAAAAAUIAAAnQAAAVgVAAQgKAAgGgGgAn5hFIAABMQAAAWgGASIBEAAIAAiAIgzAAQgLAAAAAMgAIwA3IAAiTQAAgiAYAAQAYAAAAAiIAACTQAAAigYAAQgYAAAAgigAFhA6QgagdAAgvQAAguAagfQAcgfAvAAQAvAAAbAfQAbAdAAAwQAAAvgbAeQgcAeguAAQgvAAgcgfgAGFg9QgLARAAAbQAAAZAMARQANAUAZAAQAZAAANgUQAMgQAAgaQAAgbgLgRQgOgVgZAAQgaAAgNAVgAD4A3IAAg2IhYAAIAAA2QAAAigYAAQgYAAAAgiIAAiTQAAgiAYAAQAYAAAAAiIAAAyIBYAAIAAgyQAAgiAYAAQAYAAAAAiIAACTQAAAigYAAQgYAAAAgigAhGA3IAAiQQAAgTAHgIQAIgHASAAIArAAQAjAAAUASQAWATAAAiQAAAjgUARQgTATgiAAIggAAIAAAkQAAAigYAAQgYAAAAgigAgWgXIAVAAQAgAAAAgdQAAgbggAAIgVAAgAifA3IAAiTQAAgiAYAAQAYAAAAAiIAACTQAAAigYAAQgYAAAAgigAqMA3IAAiTQAAgiAYAAQAYAAAAAiIAACTQAAAigYAAQgYAAAAgigAk2BXQgTAAgHgIQgHgIAAgSIAAiOQAAgTAHgIQAHgHATAAIBLAAQAiAAAAAWQAAAXgiAAIg8AAIAAAWIAgAAQAiAAAUATQATATAAAhQAAAigVAUQgVASgjAAgAknArIAUAAQAhAAAAgcQAAgbghAAIgUAAgAsmBXQgSAAgIgGQgHgHAAgSIAAiRQAAgTAHgIQAIgHATAAIAnAAQAdAAATAMQAZAOAAAaQAAAjgZAMIAAABQATAGAHALQAJAKAAATQAAAggXARQgUAPghAAgAsXAuIAYAAQAQAAAHgFQAKgFAAgOQAAgRgKgFQgHgDgRAAIgXAAgAsXgpIAVAAQAPAAAFgDQAIgFAAgNQAAgUgcAAIgVAAgAJSiWQgHgHAAgMQAAgNAHgIQAJgHAMAAQAMAAAIAHQAIAIAAANQAAAMgIAHQgIAIgMAAQgMAAgJgIgAIOiWQgHgHAAgMQAAgNAHgIQAJgHAMAAQAMAAAHAHQAIAIAAANQAAAMgIAHQgHAIgMAAQgMAAgJgIgADykjIAAhhIhXBzQgMAQgQAAQgWAAAAgcIAAiaQAAgiAYAAQAYAAAAAiIAABjIBZh1QALgQAOAAQAXAAAAAgIAACWQAAAigYAAQgYAAAAgigAhMkjIAAiRQAAgUAHgHQAHgHATAAIArAAQAiAAAVASQAVATAAAiQAAAjgTASQgUATgiAAIgfAAIAAAkQAAAigYAAQgYAAAAgigAgclyIAUAAQAgAAAAgdQAAgbggAAIgUAAgAiTkYIgIgYIhKAAIgJAaQgGAVgRAAQgKAAgGgGQgHgGAAgKQAAgIACgGIA3iVQAMgfAZAAQAaAAAKAcIA1CXQADAJAAAGQAAALgHAFQgGAGgKAAQgSAAgIgXgAjXlbIAvAAIgXhKIAAAAgAr2kcIAAgXIg/AAQgNAAgIgGQgJgHAAgNQAAgQAPgYIAxhNQAOgXAWAAQAUAAAJAPQAIAOAAATIAABOQAXAAAAAUQAAAUgXAAIAAAZQAAAZgXAAQgVAAAAgbgAsolbIAyAAIAAhRgAoMkDQghAAAAgiIAAiSQAAgiAYAAQAYAAAAAiIAACMIA5AAIAAiMQAAgPADgIQAFgLANAAQANAAAFALQADAIAAAPIAACMIA4AAIAAiMQAAgiAYAAQAYAAAAAiIAACSQAAAiggAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1_mc, new cjs.Rectangle(-85.2,-47.4,170.4,94.9), null);


(lib.logo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ABRDrQgGgHAAgKQAAgKAGgHQAHgHAKAAQAGAAAEACQAEABAEAEIgCADQgEgEgDgBQgEgCgFAAQgIAAgGAGQgGAGAAAJQAAAJAGAGQAGAGAIAAQAFAAAEgCQADgCAEgEIACADQgEAEgEACQgEACgGAAQgKAAgHgHgAEyDxIAAgvIAhAAIAAAEIgdAAIAAASIAaAAIAAADIgaAAIAAATIAeAAIAAADgAEJDxIgPgTIgPAAIAAATIgDAAIAAgvIATAAQAEAAAEACQADABACACIADAEIABAFQAAAFgEAEQgEADgGABIAQAUgADrDbIAQAAQAGAAADgDQAEgDAAgFQAAgFgDgDQgEgCgGAAIgQAAgAC/DxIgGgNIgbAAIgGANIgEAAIAWgvIADAAIAWAvgACfDhIAZAAIgMgbgAgJDxIgGgNIgbAAIgGANIgEAAIAWgvIADAAIAWAvgAgpDhIAZAAIgNgbgAhZDxIgPgTIgPAAIAAATIgEAAIAAgvIAUAAQAEAAAEACIAFADIADAEIABAFQAAAFgEAEQgEADgGABIAPAUgAh3DbIAPAAQAGAAAEgDQAEgDAAgFQAAgFgDgDQgEgCgGAAIgQAAgAizDxIAAgrIgRAAIAAgEIAkAAIAAAEIgQAAIAAArgAjpDxIgRgWIgRAWIgEAAIATgYIgSgXIAEAAIAQAVIAQgVIAEAAIgSAXIATAYgAlSDxIAAgvIAhAAIAAAEIgeAAIAAASIAbAAIAAADIgbAAIAAATIAeAAIAAADgACBBTQgZgBgIgCIABhOIgBgjIAAghIAdgBIAlgBQAoAAAVASQAWATAAAmQAAAogVATQgVASgqAAIgggBgACTAzIAGABIAJAAQAPAAAHgKQAIgKAAgZQAAgXgIgKQgIgKgPAAIgOAAIAABXgAgxAFIABAHQACAKAAALIAAAyIgxABIABhSIAAgfIAAgZIABgHQABgCAEgCQAHgDAXAAIAHABQADACADAEIA7BQIgDgOIgBgPIAAgYIAAgUIABgHQABgCADgCQAHgDAUAAQAJAAAEACQAEACAAAHIgBAhIAAAiIAABJIgxABgAmmACIgBgtIAAgXIAagBIAlgBQAiAAATANQAUAOAAAbQAAAYgTAOQgRAMgfAAIgJgBIgJgBIAAAxIg0ABIAChSgAl0gkIAAATIAAAVIAEABIAGAAQAKAAAFgFQAIgEAAgMQAAgLgIgFQgGgFgKAAIgJABgAF0BUIgLgjIgvAAIgKAjIgkAAIgGgBIgDgDQgDgCAAgDQgBgEACgGIArh3QACgFACgCQACgDAGgBQAJgDAiAAQAMAAAFADQAGACADAIIArB4QACAGgBAEQgBADgCACIgEADIgHABIgOAAIgZAAgAFBASIAiAAIgRg8gAiqBUIgLgjIgwAAIgKAjIgjAAIgGgBIgDgDQgDgCgBgDQAAgEACgGIArh3QABgFACgCQADgDAFgBQAKgDAiAAQALAAAGADQAGACACAIIArB4QACAGAAAEQgBADgDACIgDADIgHABIgOAAIgZAAgAjPgfIgOAxIAhAAIgRg8gACOhXIgfiHQgBgGAAgCQAAgEADgCQADgCAHgBIAVgBQAMAAAEADIADAEIACAHIAQBwIARhwQABgEACgDQADgCAFgCQAJgDAYAAQAPAAAFACQAAAAABAAQAAABABAAQAAAAAAABQABAAAAABIACAFIARB0IAShsQABgHABgDQACgDAEgCQADgCAIAAIAWgBQAHAAACAEQACADgCAIIgiCJIgaABQgeABgPgBIgShxIgQBwIgdABIgaABIgQgBgAgmhnQgVgTAAgpQAAgqAVgTQATgRAnAAQAoAAATARQAUATAAAqQAAApgUATQgTARgoAAQgnAAgTgRgAAAjHQgGALAAAZQAAAZAGAKQAGAKAOAAQAOAAAGgKQAHgKAAgZQAAgagHgKQgGgKgOAAQgOAAgGAKgAjEimIACAHQACAKAAALIAAAyIgxABIABhSIAAggIAAgZIABgHQABgDAEgBQAHgDAXAAIAHABQADACADAEIA8BRIgDgOIgBgQIAAgYIgBgUQAAgFACgCQABgDADgBQAHgDAUAAQAJAAAEACQAEACAAAGIgBAiIAAAjIAABJIgxABgAlvhbQgNgDgGgFQgEgDAAgEQAAgGAHgNQAcAHARAAQAIAAAFgDQAEgCAAgFQAAgHgLgHIgKgGIgNgHQgPgIgIgJQgKgMAAgPQAAgVARgLQARgKAcAAQARAAAPADQANADAFAEQADADgBAFQAAAGgHAMIgSgDIgVgBQgIAAgEACQgEADAAAFQAAAGALAGIALAGIAMAHQAPAJAIAJQAKAMAAAQQAAAVgPAKQgQAKggAAQgUAAgPgEg");
	this.shape.setTransform(0.1,-1.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Слой_3
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AnAA4QgKAAgKgEQgJgEgHgHQgHgHgEgJQgEgKAAgKIAAgJQAAgKAEgKQAEgJAHgHQAHgHAJgEQAKgEAKAAIOBAAQAKAAAKAEQAJAEAHAHQAHAHAEAJQAEAKAAAKIAAAJQAAAKgEAKQgEAJgHAHQgHAHgJAEQgKAEgKAAg");
	this.shape_1.setTransform(0,20.2);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.logo, new cjs.Rectangle(-50,-25.8,100,51.6), null);


(lib.img5_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.img4();
	this.instance.parent = this;
	this.instance.setTransform(-150,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.img5_1, new cjs.Rectangle(-150,-300,300,600), null);


(lib.img4_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.img5();
	this.instance.parent = this;
	this.instance.setTransform(-150,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.img4_1, new cjs.Rectangle(-150,-300,300,600), null);


(lib.img3_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.img3();
	this.instance.parent = this;
	this.instance.setTransform(-150,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.img3_1, new cjs.Rectangle(-150,-300,300,600), null);


(lib.img2_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.img2();
	this.instance.parent = this;
	this.instance.setTransform(-150,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.img2_1, new cjs.Rectangle(-150,-300,300,600), null);


(lib.img1_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.img1();
	this.instance.parent = this;
	this.instance.setTransform(-150,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.img1_1, new cjs.Rectangle(-150,-300,300,600), null);


(lib.bg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("A3bTiMAAAgnDMAu3AAAMAAAAnDg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.bg, new cjs.Rectangle(-150,-125,300,250), null);


(lib.t3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AD2EYQAAgGACgIIAOgiIg8iTQgCgHAAgHQAAgLAGgGQAGgHALAAQANAAAJAVIApBmIABAAIAmhlQAEgKAEgFQAGgHAKAAQAWAAAAAWQAAAJgDAIIhNDFQgEAJgFAGQgFAEgKAAQgVABAAgXgACWD3Ig/hKIgJAHIAAAxQAAAjgYAAQgYAAAAgjIAAiTQAAgjAYABQAYgBAAAjIAAAuIA+g/QAQgSAKABQAKAAAGAGQAIAHAAAJQAAAGgHAJIg9A8IBABJQANANAAAKQAAAIgHAHQgHAIgJAAQgMgBgOgQgAloDoQgbgcAAgwQAAgwAbgeQAcgeAuAAQAvAAAcAeQAaAeAAAwQAAAvgaAeQgcAegvABQguAAgcgggAlFBwQgLARAAAcQAAAaAMARQANATAZAAQAZAAAOgTQALgSAAgZQAAgcgLgRQgNgUgaAAQgZAAgOAUgAh6EFQgSAAgHgGQgHgHAAgSIAAiSQAAgTAHgHQAHgIATAAIAnAAQAdAAAUAMQAYAOAAAbQAAAigZAMIAAABQATAGAIALQAHALAAATQAAAggVASQgUAOghAAgAhqDcIAYAAQAPAAAHgFQAKgEAAgPQAAgRgJgFQgHgEgRAAIgXAAgAhqCEIAUAAQAPABAFgEQAIgEAAgNQAAgVgcAAIgUAAgAp7EFQghAAAAgiIAAiRQAAgjAYABQAYgBAAAjIAACLIA4AAIAAiLQAAgRADgHQAFgLANABQAOgBAEALQAEAHAAARIAACLIA4AAIAAiLQAAgjAYABQAYgBAAAjIAACRQAAAighAAgAlAhwQgbgeAAgwQAAgwAcgfQAdggAvAAQARAAAPAEQATAGAIAKQAEAHAAAGQAAAIgGAHQgGAGgIAAQgIAAgLgEQgKgEgOAAQgbAAgNAUQgMATAAAbQAAAcANAQQAPATAaAAQAMAAANgFQAPgFAEgBQAIABAGAGQAGAHAAAIQAAAHgFAGQgQAWguABQgvgBgdgggAI5h1IAAiGQgZAAgHgCQgTgEAAgRQAAgWAiAAIBTAAQAiAAAAAWQAAARgTAEQgGACgaAAIAACGQAAAjgYgBQgZABAAgjgAHYhkIg/hJIgJAHIAAAxQAAAjgYgBQgYABAAgjIAAiUQAAgiAYAAQAYAAAAAiIAAAuIA+g/QAQgQAKgBQAKABAHAGQAHAHAAAJQAAAHgHAHIg9A9IBBBIQAMAOAAAKQAAAJgHAGQgHAIgJgBQgLABgPgSgAEahpIgIgZIhKAAIgJAbQgHAUgQAAQgKAAgHgGQgGgGAAgKQAAgIACgGIA3iUQAMggAZAAQAaAAAKAcIA1CXQADAJAAAHQAAAKgHAGQgGAFgKAAQgTAAgHgWgAEFitIgXhKIAAAAIgYBKIAvAAgAgCh1IAAiRQAAgTAHgIQAHgHATAAIArAAQAjAAAUASQAWATAAAiQAAAjgUASQgTAUgigBIghAAIAAAkQAAAjgYgBQgXABAAgjgAAtjEIAVAAQAhAAAAgdQAAgbghAAIgVAAgAh4h1IAAiGQgaAAgGgCQgUgEAAgRQAAgWAiAAIBUAAQAiAAAAAWQAAARgTAEQgHACgaAAIAACGQAAAjgYgBQgYABAAgjgAmMhkIg/hJIgJAHIAAAxQAAAjgYgBQgYABAAgjIAAiUQAAgiAYAAQAYAAAAAiIAAAuIA+g/QAQgQAKgBQAKABAHAGQAHAHAAAJQAAAHgHAHIg9A9IBBBIQAMAOAAAKQAAAJgHAGQgHAIgJgBQgLABgPgSgAp8hVQgSAAgHgGQgHgHAAgRIAAiTQAAgTAHgIQAHgHATAAIA2AAQAiAAAAAWQAAAXgiAAIgnAAIAAAmIAiAAQAigBAAAWQAAAXgiAAIgiAAIAAAoIApAAQAiAAAAAWQAAAWgiAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Слой_1
	this.instance = new lib.t3_mc();
	this.instance.parent = this;
	this.instance.setTransform(0.8,1.2);
	this.instance.filters = [new cjs.BlurFilter(4, 4, 1)];
	this.instance.cache(-69,-32,138,65);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.t3, new cjs.Rectangle(-68.1,-31,141,68), null);


(lib.t2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AM+GlIAAiHQgaAAgGgBQgUgEAAgRQAAgWAjgBIBTAAQAiABAAAWQAAARgTAEQgGABgbAAIAACHQAAAigYAAQgYAAAAgigALIGlIAAg2IhYAAIAAA2QAAAigZAAQgYAAAAgiIAAiUQAAgiAYAAQAZAAAAAiIAAAyIBYAAIAAgyQAAgiAYAAQAYAAAAAiIAACUQAAAigYAAQgYAAAAgigAHmGlIAAiUQAAgiAYAAQAYAAAAAiIAACUQAAAigYAAQgYAAAAgigAEXGoQgageAAgvQAAgvAageQAcgfAvAAQAuAAAcAfQAbAdAAAwQAAAvgbAfQgcAeguAAQgvAAgcgfgAE6EvQgKARgBAcQAAAaAMARQANAUAagBQAYABAOgUQALgRAAgaQAAgcgLgRQgNgUgZAAQgaAAgOAUgACuGlIAAiJIhYAAIAACJQAAAigZAAQgXAAAAgiIAAiSQAAghAggBIB3AAQAhABAAAhIAACSQAAAigYAAQgYAAAAgigAinGoQgbgeAAgvQAAgvAbgeQAbgfAvAAQAwAAAaAfQAaAcAAAxQAAAwgaAeQgcAeguAAQgvAAgbgfgAiDEvQgMARAAAcQAAAaAMARQANAUAZgBQAZABANgUQANgRAAgaQAAgbgMgSQgOgUgZAAQgZAAgNAUgAluGlIAAiSQAAgSAGgIQAIgIASAAIAsAAQAjAAAUASQAXAUAAAiQgBAigTATQgUATgiAAIghAAIAAAkQAAAigYAAQgXAAAAgigAk/FVIAVAAQAiAAgBgcQABgbgiAAIgVAAgAmyG2IhAhJIgIAHIAAAxQAAAigYAAQgYAAAAgiIAAiUQAAgiAYAAQAYAAAAAiIAAAuIA9g/QARgRAKAAQAKAAAGAHQAIAGAAAKQgBAGgGAIIg9A9IBABIQANANAAALQgBAIgGAHQgIAHgIAAQgMAAgOgRgAqDGlIAAiUQAAgiAYAAQAXAAAAAiIAACUQAAAigXAAQgYAAAAgigArHG9QgEgGgCgPIgShzIgBAAIgbBrQgEAPgGAIQgIAKgPAAQgPAAgIgKQgEgGgGgRIgbhrIgBAAIgSB0QgCAPgEAFQgGAKgNAAQgVAAgBgXIAaigQACgPAKgJQAKgJAPAAQANAAAJAIQAIAHAFANIAcB3IAAAAIAch3QAEgNAIgHQAKgIANAAQAPAAAKAJQAKAKACAOIAaCgQAAAXgXAAQgMAAgGgKgAIJDWQgHgGAAgNQAAgMAHgIQAJgIAMAAQAMAAAIAIQAIAIAAAMQAAANgIAGQgIAJgMgBQgMABgJgJgAHGDWQgJgGAAgNQAAgMAJgIQAHgIANAAQAMAAAGAIQAJAIAAAMQAAANgJAGQgGAJgMgBQgNABgHgJgAoGBPQgbgeAAgwQAAgvAcgfQAeghAuAAQARAAAPAFQASAFAJALQAEAGAAAHQAAAIgGAHQgGAGgJAAQgHAAgLgEQgKgFgOAAQgaABgOAUQgMASAAAbQAAAaANASQAPATAaAAQAMgBANgFQAQgFAEAAQAHAAAGAGQAGAIAAAHQAAAIgFAFQgPAXgvAAQgvAAgdgggAJHBKIAAg0Ig4BHQgNAPgNAAQgJAAgHgGQgHgGABgJQAAgMANgQIAmgqQgXgEgOgOQgNgOAAgYQAAgdAUgSQAVgSAoAAIAlAAQASAAAIAHQAHAIAAATIAACQQAAAigYAAQgYAAAAgigAISgjQAAAaAfAAIAWAAIAAgzIgXAAQgeAAAAAZgAGHBKIAAg2IhZAAIAAA2QAAAigYAAQgYAAAAgiIAAiTQAAgiAYAAQAYAAAAAiIAAAyIBZAAIAAgyQAAgiAYAAQAXAAAAAiIAACTQAAAigXAAQgYAAAAgigACmBKIAAg2IhZAAIAAA2QAAAigYAAQgYAAAAgiIAAiTQAAgiAYAAQAYAAAAAiIAAAyIBZAAIAAgyQAAgiAYAAQAXAAAAAiIAACTQAAAigXAAQgYAAAAgigAjTBKIAAg2IhZAAIAAA2QAAAigYAAQgXAAAAgiIAAiTQAAgiAXAAQAYAAAAAiIAAAyIBZAAIAAgyQAAgiAYAAQAYAAAAAiIAACTQAAAigYAAQgYAAAAgigApvBKIAAhgIhXByQgMAQgQAAQgVAAAAgdIAAiYQAAgiAYAAQAYAAAAAiIAABiIBYh1QANgPANAAQAWAAABAgIAACVQAAAigYAAQgZAAAAgigAttBKIAAiFQgagBgHgBQgTgEAAgRQAAgXAiABIBTAAQAjgBgBAXQABARgUAEQgGABgaABIAACFQAAAigYAAQgZAAABgigAhaBpQgSAAgHgFQgIgHABgSIAAiRQgBgTAIgIQAHgHATAAIA2AAQAigBAAAXQAAAWgiABIgoAAIAAAlIAjAAQAhAAABAWQgBAVghAAIgjAAIAAAoIAqAAQAhAAAAAXQAAAVghAAgAiykQIAAg2IhYAAIAAA2QAAAigZAAQgYAAAAgiIAAiUQAAgiAYAAQAZAAAAAiIAAAyIBYAAIAAgyQAAgiAYAAQAYAAAAAiIAACUQAAAigYAAQgYAAAAgigAmBj/Ig+hKIgEACIAAA3QAAAigWAAQgWAAgBgiIAAg3IgDgDIg/BLQgOARgMAAQgIAAgHgHQgHgGAAgJQAAgKAMgOIA/hKIg7g7QgHgIAAgHQAAgIAHgHQAHgHAJAAQALAAAQARIA3A5IAAgoQABgiAWAAQAOAAAFALQADAHAAAQIAAAnIA3g4QARgRAKAAQAKAAAGAHQAIAHAAAIQAAAHgHAIIg7A7IA/BKQAMAOAAAKQAAAIgHAHQgHAHgIAAQgMAAgPgRgAqpkQIAAiUQAAgiAYAAQAYAAAAAiIAACUQAAAigYAAQgYAAAAgigAsCkQIAAg2IhZAAIAAA2QAAAigYAAQgYAAAAgiIAAiUQAAgiAYAAQAYAAAAAiIAAAyIBZAAIAAgyQAAgiAXAAQAYAAAAAiIAACUQAAAigYAAQgXAAAAgigAg5jwQgSgBgIgGQgGgHgBgRIAAiTQABgSAGgIQAIgIASAAIA3AAQAhABAAAWQAAAXghgBIgnAAIAAAmIAiAAQAgAAAAAWQAAAWggAAIgiAAIAAApIAoAAQAiAAgBAVQABAXgiAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Слой_1
	this.instance = new lib.t2_mc();
	this.instance.parent = this;
	this.instance.setTransform(0.8,1.2);
	this.instance.filters = [new cjs.BlurFilter(4, 4, 1)];
	this.instance.cache(-95,-47,190,95);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.t2, new cjs.Rectangle(-94.2,-46.3,193,98), null);


(lib.t1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AqdHUQgGgGAAgJIAAgTIiBAAQghAAAAgiIAAiSQAAgiAYAAQAYAAAAAiIAACMIBUAAIAAiMQAAgiAYAAQAYAAAAAiIAACMQAZAAAAAUIAAAnQAAAVgVAAQgKAAgGgGgAMkGSIAAhhIhXBzQgMAQgQAAQgWAAAAgcIAAiaQAAgiAYAAQAYAAAAAiIAABjIBZh1QAMgQAOAAQAWAAAAAgIAACWQAAAigYAAQgYAAAAgigAH+GuQgbgJAAgUQAAgTAUAAQAHAAAJAEIAQAGQAHABANAAQAgAAAAgYQAAgLgHgHQgGgGgLgCIgTAAQgeAAAAgUQAAgJAJgGQAFgEALgBIASAAQALAAAHgEQAJgGAAgKQAAgXgdAAQgIAAgPAEQgPAEgGAAQgUAAAAgSQAAgGAFgGQASgSArAAQBLAAAAA6QAAAfgdAMIAAABQAiANAAAjQAABChTAAQgaAAgSgGgAEjGVQgbgdAAgwQAAguAbgfQAcgfAuAAQAwAAAbAfQAaAdAAAwQAAAwgaAeQgcAegvAAQguAAgcgfgAFGEdQgLARAAAbQAAAaAMARQANAUAZAAQAZAAAOgUQAMgRAAgaQAAgbgMgRQgNgVgaAAQgZAAgOAVgAC+GqQgEgHAAgRIAAiLIgzAAQgLAAAAANIAAB1QAAArgqAAQgnAAAAgWQAAgNAIgFQAEgCALgBQAKAAADgDQADgDAAgJIAAhmQAAgfALgNQALgMAfAAIBLAAQAYAAAAAiIAACUQAAAigYAAQgPAAgFgKgAiAGaQgWgZgDgoIgeAAIAAA5QAAAigYAAQgYAAAAgiIAAiUQAAgiAYAAQAYAAAAAiIAAAzIAfAAQAFgmAVgXQAXgYAlAAQAuAAAVAhQAVAdAAAuQAABOg0AXQgQAHgUAAQgnAAgXgagAhbETQgIALgDASQgBALAAANQAAAYAHATQAJAYAWAAQAVAAAKgYQAHgTAAgYQAAghgLgRQgLgRgQAAQgQAAgKAOgAk8GqQgEgIAAgQIAAiLIgzAAQgLAAAAANIAAB1QAAArgqAAQgnAAAAgWQAAgNAIgFQAEgCALgBQAKAAADgDQADgDAAgJIAAhmQAAgfALgNQALgMAfAAIBLAAQAYAAAAAiIAACUQAAAigYAAQgOAAgGgKgAo/GyQgSAAgHgGQgHgHAAgSIAAiSQAAgTAHgIQAHgHATAAIA2AAQAiAAAAAWQAAAXgiAAIgnAAIAAAlIAhAAQAjAAAAAWQAAAWgjAAIghAAIAAApIAoAAQAiAAAAAWQAAAWgiAAgAmXB5QgGgGAAgJIAAgTIh6AAIAAATQAAAJgGAGQgGAGgKAAQgKAAgGgGQgFgGAAgJIAAgnQAAgUATAAQAFAAADgJQADgJAAgWIAAhNQAAgZAOgOQAOgOAZAAIBJAAQAQAAAGAKQAFAHAAARIAACIQAZAAAAAUIAAAnQAAAVgVAAQgKAAgGgGgAn5hFIAABMQAAAWgGASIBEAAIAAiAIgzAAQgLAAAAAMgAIwA3IAAiTQAAgiAYAAQAYAAAAAiIAACTQAAAigYAAQgYAAAAgigAFhA6QgagdAAgvQAAguAagfQAcgfAvAAQAvAAAbAfQAbAdAAAwQAAAvgbAeQgcAeguAAQgvAAgcgfgAGFg9QgLARAAAbQAAAZAMARQANAUAZAAQAZAAANgUQAMgQAAgaQAAgbgLgRQgOgVgZAAQgaAAgNAVgAD4A3IAAg2IhYAAIAAA2QAAAigYAAQgYAAAAgiIAAiTQAAgiAYAAQAYAAAAAiIAAAyIBYAAIAAgyQAAgiAYAAQAYAAAAAiIAACTQAAAigYAAQgYAAAAgigAhGA3IAAiQQAAgTAHgIQAIgHASAAIArAAQAjAAAUASQAWATAAAiQAAAjgUARQgTATgiAAIggAAIAAAkQAAAigYAAQgYAAAAgigAgWgXIAVAAQAgAAAAgdQAAgbggAAIgVAAgAifA3IAAiTQAAgiAYAAQAYAAAAAiIAACTQAAAigYAAQgYAAAAgigAqMA3IAAiTQAAgiAYAAQAYAAAAAiIAACTQAAAigYAAQgYAAAAgigAk2BXQgTAAgHgIQgHgIAAgSIAAiOQAAgTAHgIQAHgHATAAIBLAAQAiAAAAAWQAAAXgiAAIg8AAIAAAWIAgAAQAiAAAUATQATATAAAhQAAAigVAUQgVASgjAAgAknArIAUAAQAhAAAAgcQAAgbghAAIgUAAgAsmBXQgSAAgIgGQgHgHAAgSIAAiRQAAgTAHgIQAIgHATAAIAnAAQAdAAATAMQAZAOAAAaQAAAjgZAMIAAABQATAGAHALQAJAKAAATQAAAggXARQgUAPghAAgAsXAuIAYAAQAQAAAHgFQAKgFAAgOQAAgRgKgFQgHgDgRAAIgXAAgAsXgpIAVAAQAPAAAFgDQAIgFAAgNQAAgUgcAAIgVAAgAJSiWQgHgHAAgMQAAgNAHgIQAJgHAMAAQAMAAAIAHQAIAIAAANQAAAMgIAHQgIAIgMAAQgMAAgJgIgAIOiWQgHgHAAgMQAAgNAHgIQAJgHAMAAQAMAAAHAHQAIAIAAANQAAAMgIAHQgHAIgMAAQgMAAgJgIgADykjIAAhhIhXBzQgMAQgQAAQgWAAAAgcIAAiaQAAgiAYAAQAYAAAAAiIAABjIBZh1QALgQAOAAQAXAAAAAgIAACWQAAAigYAAQgYAAAAgigAhMkjIAAiRQAAgUAHgHQAHgHATAAIArAAQAiAAAVASQAVATAAAiQAAAjgTASQgUATgiAAIgfAAIAAAkQAAAigYAAQgYAAAAgigAgclyIAUAAQAgAAAAgdQAAgbggAAIgUAAgAiTkYIgIgYIhKAAIgJAaQgGAVgRAAQgKAAgGgGQgHgGAAgKQAAgIACgGIA3iVQAMgfAZAAQAaAAAKAcIA1CXQADAJAAAGQAAALgHAFQgGAGgKAAQgSAAgIgXgAjXlbIAvAAIgXhKIAAAAgAr2kcIAAgXIg/AAQgNAAgIgGQgJgHAAgNQAAgQAPgYIAxhNQAOgXAWAAQAUAAAJAPQAIAOAAATIAABOQAXAAAAAUQAAAUgXAAIAAAZQAAAZgXAAQgVAAAAgbgAsolbIAyAAIAAhRgAoMkDQghAAAAgiIAAiSQAAgiAYAAQAYAAAAAiIAACMIA5AAIAAiMQAAgPADgIQAFgLANAAQANAAAFALQADAIAAAPIAACMIA4AAIAAiMQAAgiAYAAQAYAAAAAiIAACSQAAAiggAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Слой_1
	this.instance = new lib.t1_mc();
	this.instance.parent = this;
	this.instance.setTransform(0.8,1.2);
	this.instance.filters = [new cjs.BlurFilter(4, 4, 1)];
	this.instance.cache(-87,-49,174,99);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1, new cjs.Rectangle(-86.4,-48.2,177,102), null);


(lib.banner = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// t4
	this.instance = new lib.t4();
	this.instance.parent = this;
	this.instance.setTransform(0,-207.2,1.22,1.22,0,0,0,0,-0.1);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(205).to({_off:false},0).to({alpha:1},10).wait(30).to({alpha:0},15).wait(1));

	// img5
	this.instance_1 = new lib.img5_1();
	this.instance_1.parent = this;
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(190).to({_off:false},0).to({alpha:1},15).wait(40).to({alpha:0},15).wait(1));

	// urText
	this.instance_2 = new lib.urText();
	this.instance_2.parent = this;
	this.instance_2.setTransform(-114.1,285);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(261));

	// logo
	this.instance_3 = new lib.logo();
	this.instance_3.parent = this;
	this.instance_3.setTransform(-83.2,-253.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(261));

	// img4
	this.instance_4 = new lib.img4_1();
	this.instance_4.parent = this;
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(150).to({_off:false},0).to({alpha:1},15).to({_off:true},40).wait(56));

	// t3
	this.instance_5 = new lib.t3();
	this.instance_5.parent = this;
	this.instance_5.setTransform(-47.9,138.9,1.26,1.26,0,0,0,-0.1,0.1);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(110).to({_off:false},0).to({alpha:1},10).to({_off:true},45).wait(96));

	// img3
	this.instance_6 = new lib.img3_1();
	this.instance_6.parent = this;
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(95).to({_off:false},0).to({alpha:1},15).to({_off:true},55).wait(96));

	// t2
	this.instance_7 = new lib.t2();
	this.instance_7.parent = this;
	this.instance_7.setTransform(-14.9,138.8,1.26,1.26);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(55).to({_off:false},0).to({alpha:1},10).to({_off:true},45).wait(151));

	// img2
	this.instance_8 = new lib.img2_1();
	this.instance_8.parent = this;
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(40).to({_off:false},0).to({alpha:1},15).to({_off:true},55).wait(151));

	// t1
	this.instance_9 = new lib.t1();
	this.instance_9.parent = this;
	this.instance_9.setTransform(-24.9,138.9,1.26,1.26,0,0,0,-0.1,0.1);
	this.instance_9.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).to({alpha:1},10).to({_off:true},45).wait(206));

	// img1
	this.instance_10 = new lib.img1_1();
	this.instance_10.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(261));

	// bg
	this.instance_11 = new lib.bg();
	this.instance_11.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(261));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,-300,300,600);


// stage content:
(lib._300x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// cover
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#666666").ss(2,1,1).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// banner
	this.instance = new lib.banner();
	this.instance.parent = this;
	this.instance.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(149,299,302,602);
// library properties:
lib.properties = {
	id: 'FC03ADEE38A14996869D61267283DB6F',
	width: 300,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/img1.jpg", id:"img1"},
		{src:"images/img2.jpg", id:"img2"},
		{src:"images/img3.jpg", id:"img3"},
		{src:"images/img4.jpg", id:"img4"},
		{src:"images/img5.jpg", id:"img5"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['FC03ADEE38A14996869D61267283DB6F'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;