(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.t3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AjmB4IAAgXQgGAAgFgCQgGgCgDgDQgEgEgCgFQgCgFAAgHQAAgKAEgHQAFgGAGgDIANgCIAAgWIAIAAIAAAWQAKAAAGAFQAHADADAHQACAGAAAGQAAALgFAHQgEAHgHACQgGACgGAAIAAAXgAjeBbQAHgBAEgDQAFgDACgFQACgFAAgFQAAgHgDgFQgEgFgEgCIgJgBgAjxA0QgFADgCAEQgCAEAAAGQAAAFACAEQABAEADADIAGADIAIADIAAgqQgGAAgFADgAEwBiIgEgHIAGgJIAFgFIADgCIAKAEQAGgDAIgMQAGgIABgIIAAgGIgIgFIABgIIAEgIIACgDIADAAIAHABIAIADIABAMQgCARgNAUQgJARgQAKQgHAGgGABIgGgHgAipBgQgFgCgDgFQgDgEgCgFIgCgLQABgJADgHQADgHAGgEQAGgCAHAAQAIAAAGAEQAGAFACAIQACAGABAGQAAAJgEAIQgEAHgGADQgFADgGAAQgHAAgEgDgAioAzQgFAEgBAFIgBAJQAAAGACAHQADAFAEACQADADAFAAQAFAAAEgEQAEgEABgGIACgJQAAgGgDgGQgCgFgDgDQgFgCgDAAQgHAAgDAEgAk1BcQgGgJgBgOQAAgKAEgHQADgHAHgDQAFgCAFAAQAJAAAGAEQAFAEACAIQACAGAAAGIgnAAQAAAMAFAGQAEAFAJABQAFAAAEgCIAHgEIADAHQgDADgFABQgGACgFAAQgMAAgIgHgAktAyQgEAEgBAHIAdAAQgBgFgCgDQgDgDgDgCIgGgBQgEAAgFADgAmoBcQgIgJAAgOQAAgKAEgHQAEgHAGgDQAFgCAFAAQAJAAAGAEQAFAEADAIQACAGAAAGIgoAAQAAAMAFAGQAFAFAIABQAGAAADgCIAIgEIACAHQgDADgFABQgGACgFAAQgMAAgHgHgAmhAyQgDAEgCAHIAdAAQAAgFgDgDQgCgDgDgCIgHgBQgFAAgEADgAodBiIgFgEIgFgFQgBgDgBgEQAAgJAHgFQAFgFAIgBIANgBIAAgBQAAgHgDgDQgDgDgFAAIgHABQgFACgDADIgDgHIAHgFQAFgBAHAAQAJAAAFAEQAFAFAAALIAAAlIgIAAIAAgEQgDADgEABQgEACgEAAIgHgBgAoVBFQgGACgCADQgCADgBAFQAAADACADIAFADIAEABQAEAAADgCIAGgEIAAgSIgNABgACPBhIAAgNIACgGIADgEIAEgFIAQgNIAFgEIACgDIABgDIABgEQAAgFgDgDQgDgDgFAAIgHABIgEADIgEAEIgDABIgHgLIADgDIAFgDIAJgEQAEgCAGAAQAFAAAFACIAIAFQADAEACADQACAEAAAGQAAAIgDAFQgDAFgGAFIgUAPIgCADIgBACIAkAAIAAANgABPBhIAAgNIABgGIAEgEIAEgFIAQgNIAFgEIADgDIABgDIAAgEQAAgFgDgDQgDgDgFAAIgHABIgEADIgEAEIgCABIgIgLIADgDIAGgDIAIgEQAEgCAGAAQAFAAAFACIAIAFQAEADABAEQACAFAAAFQAAAIgDAFQgDAFgGAFIgUAPIgCADIgBACIAkAAIAAANgAAPBhIAAgJIAAgEIABgGIAEgEIAEgFIAQgNIAFgEIADgDIABgDIAAgEQAAgFgDgDQgDgDgFAAIgHABIgFADIgDAEIgCABIgHgLIACgDIAGgDIAIgEQAEgCAGAAQAFAAAFACQAFACADADQAEADABAEQACAEAAAGQAAAIgDAFQgCAFgIAFIgQANIgDACIgCADIAAACIAjAAIAAANgAhVBhIAAgZIgbAAIAAAZIgJAAIAAg4IAJAAIAAAYIAbAAIAAgYIAJAAIAAA4gAlRBhIAAgwIgUAAIAAADIAAASIgCANQgCAHgDAEQgEAEgHgBIgEAAIAAgHIADAAIAEgBIADgDIACgEIABgNIABgUIAAgIIAlAAIAAA4gAnPBhIAAgwIgSAAIAAgIIAsAAIAAAIIgRAAIAAAwgApHBhIAAgwIgRAAIAAgIIArAAIAAAIIgRAAIAAAwgAD4BZIAAgQIgJAAIAAAQIgOAAIAAgQIgQAAIAAgOIAQAAIAAgLIgQAAIAAgOIAQAAIAAgPIAOAAIAAAPIAJAAIAAgPIAOAAIAAAPIAPAAIAAAOIgPAAIAAALIAPAAIAAAOIgPAAIAAAQgADvA7IAJAAIAAgLIgJAAgAgaA6IAAgNIgLAHIgFgKIAMgIIgMgIIAGgKIAKAHIAAgLIAMAAIAAALIAKgHIAGAKIgMAIIAMAIIgGAKIgKgHIAAANgAIkgXQAJAAAEgCQAFgDACgDIADgFIgVg6IAJAAIARAwIAJgWIAHgaIAJAAQgFAVgFANIgJAVIgFAJQgBAEgFAEQgEADgEACQgFABgJABgAGQgPIAAhPIAIAAIABADQACgDAFgBIAIgBQAIAAAFAFQAGAFACAHIABAMQAAAKgEAIQgFAHgGACQgGADgGAAQgHAAgDgCIAAAYgAGfhXIgGAEIAAAkIADACIAGABQAFAAAFgEQAFgDACgFQACgGAAgFQAAgGgCgFQgBgGgFgCQgDgDgFAAQgDAAgDACgAkJgPIAAhPIAIAAIABADIAHgEIAIgBQAJAAAEAFQAGAFACAHIABAMQAAAKgEAIQgFAHgGACQgGADgGAAQgGAAgEgCIAAAYgAj6hXQgEABgCADIAAAkIADACIAGABQAGAAAEgEQAFgDADgFQABgFAAgGQAAgHgBgEQgCgGgEgCQgEgDgEAAQgEAAgDACgAnNgPIAAhPIAIAAIAAADIAIgEIAIgBQAIAAAGAFQAFAFABAHIACAMQAAAKgEAIQgFAHgGACQgGADgGAAQgGAAgFgCIAAAYgAm+hXIgHAEIAAAkIAEACIAFABQAHAAAEgEQAGgDABgFQACgGAAgFQAAgGgCgFQgCgGgDgCQgEgDgEAAQgEAAgDACgAFjgmIgHgDIgDgGQgCgDAAgFQAAgHAGgFQAGgFAIgCIAMgBIAAgBQAAgHgCgDQgDgDgFAAQgEAAgEACIgIAEIgDgHIAIgEQAFgCAGAAQAJAAAGAEQAEAGAAALIAAAlIgIAAIAAgFQgCADgEACIgIABIgHgBgAFrhCQgGABgCAEQgDADAAADQAAAEACADQACADACAAIAFABQADAAAEgCIAFgEIAAgRQgHgBgFACgADPglIgVg/IgCA+IgJAAIAEhQIALAAIAVBCIAUhCIALAAIAEBQIgJAAIgDg+IgVA/gABnglIgHgCIgFgCIgFgEIAFgIIAJAGQAFACAGAAQAFAAAEgCQAEgCABgCIACgHQgBgGgEgEQgDgDgKgEIgMgGQgFgDgCgEQgCgFAAgEQAAgIAFgFQAEgGAFgBQAGgCAEAAQAIAAAGADQAGADAFAFIgFAGQgJgJgLAAQgGABgEADQgFADAAAFQAAAGAEACQACADAEACIAIADQAJAEAEADQAFADABAEQADAFAAAFQAAAIgFAGQgFAFgFACIgLABIgIAAgAAUgnQgEgCgDgEQgDgDgCgGIgCgKIgLAAIAAAaIgJAAIAAg4IAJAAIAAAWIALAAQABgHAEgGQADgGAGgDQAFgCAGAAQAGAAAEACQAFACADAFQADAEABAFQACAFAAAGQAAAGgCAFQgBAHgDADQgDAEgFADQgFACgFAAQgGAAgFgCgAAVhVQgDAEgCAFIgBAJIABAJQAAAEADADIAEAFQAEABAEAAQAFAAAEgDQAEgEABgFIABgKQAAgHgCgFQgDgFgDgCQgEgCgDAAQgGAAgEADgAhAgnQgEgDgDgEIgFgKQgCgFABgGQgBgIAEgIQAEgHAFgDQAGgDAHAAQAIAAAGAFQAHAFABAHQACAHAAAFQABAKgEAHQgEAHgFADQgGADgGAAQgGAAgGgCgAg/hVQgEAEgBAFIgBAJQAAAHACAGQADAFAEACQADADAFAAQAFAAAFgEQADgEABgFIACgKQAAgHgDgEQgBgGgFgCQgDgDgEAAQgGAAgFAEgAiqgnQgFgBgDgEQgDgEgDgFQgCgGAAgHQAAgLAEgIQAFgHAFgCQAGgCAEAAQAHAAAEACQAEADACACIAEAEIgHAFIgFgGQgDgDgGAAQgFAAgDAEQgEADgCAFQgBAFAAAFQAAAGABAEIADAHIAGAEQADACAEAAQAFAAAEgCQADgBADgDIADAIQgDACgFACQgGABgFAAQgFAAgEgCgAmOgtQgGgHgBgPQAAgJAEgIQAEgGAGgEQAFgCAFAAQAJAAAGAEQAFAFACAGQACAIAAAGIgnAAQAAALAFAGQAEAGAJAAQAFAAAEgCQAFgBACgDIADAHQgCADgGABQgGACgFAAQgMAAgIgIgAmGhVQgEADgBAIIAdAAQAAgFgDgEQgDgDgDgBIgGgCQgFAAgEAEgAoCgtQgHgHAAgPQAAgJAEgIQADgGAGgEQAFgCAGAAQAIAAAGAEQAFAFADAGQACAHAAAHIgoAAQAAALAFAGQAFAGAIAAQAGAAAEgCQAEgBADgDIADAHQgDADgGABQgFACgGAAQgMAAgHgIgAn7hVQgDADgCAIIAdAAQAAgFgDgEQgCgDgDgBIgGgCQgGAAgEAEgAIZgmIgRgaIgIAAIAAAaIgJAAIAAg4IAJAAIAAAWIAGAAQAEABAEgMIAFgIQACgDADAAIAFAAIAFAAIAAAHIgDAAIgFABQgCABgCAGQgFAJgCACIAVAegAHVgmIAAgxIgRAAIAAgHIArAAIAAAHIgRAAIAAAxgAFIgmIgRgaIgJAAIAAAaIgJAAIAAg4IAJAAIAAAWIAHAAQADABAFgMQABgEADgEQADgDACAAIAFAAIAGAAIAAAHIgEAAIgFABIgEAHQgEAIgCADIAUAegACWgmIAAhQIAIAAIAABQgAiCgmIAAg4IAYAAQAIAAAEADQAFAEgBAGQAAAGgCADQgDAEgDABIAGACQACABACAEIABAGQAAAIgFAEQgFAEgHAAgAh5guIAQAAIAFgBQABAAAAAAQAAAAABgBQAAAAAAAAQABgBAAAAIABgGQAAgDgDgCQgCgDgFAAIgPAAgAh5hGIAOAAQAEAAADgDQACgDAAgDQAAgIgIAAIgPAAgAkigmIAAg4IAJAAIAAA4gAlZgmIAAg4IAYAAQAIAAAEADQAFAEAAAGQAAAGgDADQgCAEgEABIAGACQADABABAEQABADAAADQAAAHgFAFQgEAEgIAAgAlQguIAQAAIAFgBQABAAAAAAQABAAAAgBQABAAAAAAQAAgBABAAIABgGQgBgDgCgCQgDgDgEAAIgQAAgAlQhGIAOAAQAFAAACgDQACgCAAgEQAAgIgIAAIgPAAgAohgmIAAhHIglAAIAABHIgJAAIAAhQIA3AAIAABQgAEBhBIAAgIIAYAAIAAAIgAkhhqQAAgBgBAAQAAgBAAAAQgBgBAAAAQAAgBAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBQABgBAAAAQAAAAABgBQAAAAABAAQAAAAABAAQAAgBABAAQABAAAAABQABAAAAAAQABAAAAAAQABABAAAAQAAAAABABQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAABQAAAAAAABQAAAAAAABQgBAAAAABQAAAAgBAAQAAABgBAAQgBAAAAAAQgBABAAAAQgBAAAAgBQgBAAAAAAQgBAAAAgBQgBAAAAAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t3, new cjs.Rectangle(-60.1,-12,120.3,24), null);


(lib.t2_2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AlmBKIAJAAIAKgDIAKgDQAEgCADgFIABgCIACgCIgrhqIAdAAIAdBRIAHgSIAGgTIAGgWIAFgWIAbAAQgIAegJAcQgJAagKASIgIARQgFAHgHAHQgHAGgLAEQgLAEgRAAgADVBPIAAgWIhAAAIAAAWIgbAAIAAguIALAAQAKgNAFgRQAFgSAAgVIAAgNIBMAAIAABSIALAAIAAAugACtAIQgEAPgHALIApAAIAAg7IgZAAQgBASgEAPgAIzA3QgLgFgJgKQgJgKgEgOQgFgOAAgRQAAgTAFgPQAFgPAIgJQAJgJALgFQALgFAMAAQATAAAMAHQAMAIAHAKIgUASIgEgGIgGgFQgEgDgEgCQgFgBgGAAQgHAAgGADQgGADgEAGQgFAGgDAKQgDAKAAANQAAAMADAIQADAJAFAHQAFAGAHADQAGAEAJgBIAOgBIAGgBIAAgbIgWAAIAAgYIAxAAIAABGIgGACIgKAEIgOACIgTABQgOAAgMgEgAEaA2QgKgFgGgIQgGgHgEgLQgDgJAAgLQAAgJADgKQAEgKAGgHQAGgJAKgEQAJgFANAAQANAAAJAFQAJAEAHAJQAGAHADAKQADAKAAAJQAAAKgDAKQgDALgGAHQgHAIgJAFQgJAEgNAAQgNAAgJgEgAElgZQgEACgDAEQgDAEgCAGQgBAGAAAGQAAAHABAFIAFALQADAEAEADQAFACAGAAQAGAAAEgCQAFgDACgEQAEgFABgGQACgFAAgHQAAgFgCgHQgBgFgEgFQgCgEgFgCQgEgDgGAAQgGAAgFADgAheA4QgKgEgGgGQgHgIgEgJQgEgLAAgOQAAgOAEgKQAEgKAHgHQAGgHAJgEQAJgDAKAAQAJAAAHACQAHADAFAEIAIAIIAFAIIgUANQgDgFgFgFQgFgFgIAAQgJAAgGAHQgHAJAAAPQAAAPAHAJQAGAJANgBQAFAAAFgBIAJgDIAFgDIAEgDIAIAXIgFACIgIAEIgMAEIgPAAQgJABgJgDgAoYA2QgJgFgGgIQgGgHgEgLQgDgJAAgLQAAgJADgKQAEgKAGgHQAGgJAJgEQAKgFANAAQANAAAJAFQAJAEAHAJQAGAHADAKQADALAAAIQAAAKgDAKQgDALgGAHQgHAIgJAFQgJAEgNAAQgNAAgKgEgAoMgZQgEACgDAEQgDAEgCAGQgBAGAAAGQAAAHABAFIAFALQADAEAEADQAFACAGAAQAGAAAEgCQAEgDADgEQAEgFABgGQACgEAAgIQAAgGgCgGQgBgFgEgFQgDgEgEgCQgEgDgGAAQgGAAgFADgAHVA5IAAgdIg8AAIAAgWIBBheIAXAAIAABbIAOAAIAAAZIgOAAIAAAdgAG3ADIAeAAIAAgugAAmA5IAAgkIgUAAQgDANgDAHQgEAHgEADQgEAEgDABIgJABIgOAAIAAgXIAGAAIAFgBIADgCIACgFIADgJQgLgGgEgHQgEgIAAgJQAAgRAKgJQALgKASAAIA0AAIAABqgAADgXQgDAEAAAGQAAANAQAAIAWAAIAAgcIgWAAQgJAAgEAFgAitA5IAAg5IgoAoIAAARIgbAAIAAhqIAbAAIAAA5IAognIAAgSIAbAAIAABqgAmmA5IAAhSIggAAIAAgYIBbAAIAAAYIggAAIAABSgAp9A5IAAiRIBZAAIAAAaIg9AAIAAB3gAjRhAQgIgDgFgEQgGgFgDgHQgDgGAAgIIAZAAQACAIAFADQAFAEAFAAQAEAAAFgEQAFgDACgIIAZAAQAAAJgDAGQgEAHgGAFQgGAEgHACQgIACgHABQgJAAgIgDg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t2_2, new cjs.Rectangle(-63.8,-9.8,127.6,19.6), null);


(lib.t2_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AnCBKIAJgBIALgBIAJgEQAEgCADgEIACgCIABgDIgrhpIAcAAIAeBQIAGgSIAHgTIAGgWIAFgVIAbAAQgIAfgKAaQgJAagJATIgJAQQgDAIgIAGQgHAGgLAEQgLAEgRAAgAOgA2QgFgFAAgGQAAgGAFgFQADgFAIAAQAHAAAEAFQAEAFAAAGQAAAGgEAFQgEAFgHAAQgIAAgDgFgANWA3QgJgDgGgHQgHgGgFgLQgDgKgBgOQABgNADgLQAFgKAGgHQAHgHAIgEQAJgDAKAAQAJAAAHACIAMAGQAFAEADAFIAFAIIgTANIgJgKQgFgFgIAAQgIAAgFAFQgHAGgBAMIApAAIAAAUIgpAAQAFAUAUAAQAGAAAFgBIAIgDIAGgDIADgDIAIAWIgFADIgIAEIgMADQgGACgJAAQgJAAgJgEgALjA4QgHgCgFgEQgEgEgEgHQgDgGAAgIQAAgIADgGQADgGAGgEQAFgDAHgDQAIgDAGgBIAMgBIALgBIAAgCQgBgJgEgDQgFgEgHAAIgJABIgIADIgGADIgEADIgJgTIAGgEIAJgEIALgEIAOgBQAIAAAIACQAHADAGAFQAEAEADAIQAEAIAAAKIAABDIgaAAIAAgIQgEAFgHADQgHADgIAAQgIAAgFgDgAMAAHIgJACQgJACgEAEQgDAEAAAFQAAAGAEADQAEADAHAAQAFAAAFgCQAFgCAEgEIAAgVIgJAAgAheA3QgJgDgHgHQgHgHgEgKQgEgKAAgOQAAgNAEgLQAEgKAGgHQAHgHAJgEQAJgDAKAAQAJAAAHACIALAGQAFAEAEAFIAFAIIgVANIgIgKQgFgFgHAAQgIAAgGAFQgGAGgBAMIAoAAIAAAUIgoAAQAFAUATAAQAHAAAEgBIAIgDIAGgDIADgDIAIAWIgEADIgIAEQgFACgHABQgGACgJAAQgKAAgIgEgAoYA2QgKgFgGgIQgHgJgDgLQgCgMAAgNQAAgNACgNQADgNAGgMQAFgKALgIQAJgHAOgCIAJAAQAFgBADgCQACgCACgHIAVAEQgBAIgCAGQgCAFgEADQgDAEgGABIgKADIgLAAQgLACgFAGQgHAHgCAOQADgFAIgEQAIgDAJAAQAMAAAJAFQAIAEAGAIQAGAHACAJQACAIAAAIQAAALgDAKQgFAKgGAHQgHAHgJAEQgKAEgLAAQgMAAgKgFgAoUgMQgFAIAAALQAAAMAFAIQAHAIALAAQANAAAFgIQAHgIgBgMQABgLgHgIQgFgIgNAAQgLAAgHAIgAsEA4QgGgCgGgEQgEgEgDgHQgDgGAAgIQAAgIADgGQADgGAFgEQAFgDAIgDQAHgDAGgBIANgBIAKgBIAAgCQgBgJgEgDQgFgEgHAAIgJABIgIADIgGADIgEADIgJgTIAGgEIAJgEIAMgEIANgBQAIAAAIACQAHADAGAFQAFAFADAHQADAIAAAKIAABDIgZAAIgBgIQgEAFgHADQgHADgIAAQgHAAgGgDgArnAHIgJACQgJACgDAEQgDAEgBAFQABAGADADQAEADAHAAQAGAAAFgCQAEgCAEgEIAAgVIgJAAgAt7A5IgehXIgEBWIgcAAIAHiRIAdAAIAjBnIAghnIAdAAIAHCRIgbAAIgFhVIgaBWgAKlA4IgagpIgNAAIAAApIgbAAIAAhoIAbAAIAAAoIAGAAQAEAAACgDIAEgGIAEgIIACgGQAEgJAGgEQAFgEAKAAIAQAAIAAAWIgHAAQgGAAgCADIgFAHQgFAMgEAEIAlA4gAIsA4IABg4IgoAnIAAARIgbAAIAAhoIAbAAIgBA4IAognIAAgRIAbAAIAABogAGzA4IAAhSIgbAAIAAAMIgBAYIgCASQgDAMgJAIQgHAIgQAAIgLAAIAAgXIAGAAQAEAAAEgCQAEgCACgHQACgIAAggIAAgeIBRAAIAABogAFDA4IgZgpIgOAAIAAApIgbAAIAAhoIAbAAIAAAoIAHAAQADAAACgDIAFgGIADgIIACgGQAFgJAFgEQAGgEAJAAIARAAIAAAWIgIAAQgFAAgDADQgDACgBAFQgFAMgEAEIAlA4gADLA4IAAg4IgoAnIAAARIgbAAIAAhoIAbAAIAAA4IAognIAAgRIAbAAIAABogAAVA4IAAhoIA3AAQAQAAAJAHQAJAIAAAMQAAAQgLAFQAIAEAEAFQAEAGAAAJQAAAKgEAGQgDAFgGAEQgGAEgGACIgNABgAAvAjIAcAAQAGAAADgDQADgDAAgFQAAgLgMAAIgcAAgAAvgGIAYAAQAIAAABgEQADgEAAgEQAAgDgDgDQgBgDgIAAIgYAAgAitA4IAAgqIgmAAIAAAqIgcAAIAAhoIAcAAIAAAoIAmAAIAAgoIAbAAIAABogAk5A4IAAhSIggAAIAAgWIBbAAIAAAWIgfAAIAABSgApmA4IAAg4IgnAnIAAARIgbAAIAAhoIAbAAIgBA4IAognIAAgRIAbAAIAABogAqKhAQgHgCgGgFQgFgFgDgGQgDgHgBgIIAaAAQACAHAEAEQAFAEAFAAQAFAAAFgEQAFgEACgHIAZAAQAAAJgEAHQgDAGgHAFQgFAEgIACQgHADgIAAQgJAAgIgDg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t2_1, new cjs.Rectangle(-95.4,-9.8,190.8,19.6), null);


(lib.t1_2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ABbA0IAGAAIAIgCIAHgCQADgBACgEIACgBIABgCIghhNIAWAAIAWA7IAFgOIAJgeIADgPIAUAAQgGAWgHATQgHAUgGAOIgGALQgDAGgGAFQgGAEgIADQgHADgNAAgAC8AlQgDgDgBgGQABgFADgEQADgEAGAAQAFAAAEAEQADAEABAFQgBAGgDADQgEAEgFAAQgGAAgDgEgAAcAmQgGgDgFgGQgEgGgCgIQgCgGAAgIQAAgIACgGQACgIAFgGQAEgFAIgEQAGgDAKAAQAGAAAGACIAAgeIAUAAIAABrIgSAAIgBgHQgCADgFADQgEACgHAAQgHAAgGgDgAAngVQgDACgDAEQgDADAAAFIgBAHIABAJIACAIIAGAFQADACAFAAQADAAAEgCQAEgCABgDIAAglQgFgDgFABQgFAAgEABgAgzAoQgEgCgEgEIgGgHQgCgEAAgHQAAgFACgFQADgEADgCIAJgFIAKgDIAJgBIAIgBIAAgBQAAgHgEgCQgDgDgGAAIgGABIgGACIgEACIgDADIgGgPIADgCIAHgEIAJgCIAKgBIALABQAGACADAEQAEAEADAFQABAGAAAHIAAAyIgSAAIAAgHQgEAEgFACQgEACgGAAQgFAAgFgBgAgeAEIgHAAQgFACgEADQgCAEAAADQAAAEADACQADADAFgBIAHgBQAEgCADgCIAAgQgAh6AnQgHgDgGgFQgEgEgDgIQgEgIAAgKQABgJACgHQADgIAFgGQAEgEAIgEQAGgCAHAAQAHAAAHACQAHADAEAFQAEAFADAIQACAIAAAKIAAADIgyAAQABALAFAEQAGAEAJAAIAHgBIAGgBIAFgCIADgDIAGAQIgEACIgGADIgJACIgLABQgIAAgGgCgAh4gUQgEAFgCAIIAfAAQgBgFgBgCIgEgGIgEgCIgFgBQgFAAgFADgAirAoIgLgiIgCgDIgDgDIgGAAIgQAAIAAAoIgUAAIAAhrIAlAAIANABQAGACAGAEQAFADAEAHQACAFAAAKQAAAIgDAHQgEAHgIAEQAFADACADQADADADAKIAIAegAjRgTIAPAAQASAAAAgOQAAgHgEgFQgEgDgKAAIgPAAgAC7AFIAAgGIABgGIADgGIAEgGIAFgEIAGgIQAEgEAAgGQAAgFgEgDQgDgDgGAAQgEAAgFADQgFADgGAHIgLgMIAGgHIAHgGIAJgDQAFgCAGAAQAIAAAFACQAGACAEAEQAEADACAGQACAEAAAHQAAAEgBAEQgBAFgCACIgFAGIgEAGIgHAIQgDAEgBAEIAAADg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1_2, new cjs.Rectangle(-23,-7,46,14), null);


(lib.t1_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AFnArIgGgDIABgGIAHADIAHABQAIAAADgEQADgDAAgHIAAgEQgCACgEABIgFABQgGABgDgCQgEgCgDgEQgCgDgBgEQgCgFAAgFIACgJQABgEADgDQADgDAEgDQAFgCAFAAIAJABIAIACIAAAtQAAAHgEAEQgDAFgEACQgGACgFAAIgJgBgAFsgOQgEADgCAFIgBAGQAAAGACAFQADAFADABIAHACIAFgCQADgBACgDIAAgdQgDgCgGAAQgGABgDADgAGRAYQAAAAAAgBQAAgBgBAAQAAgBAAAAQAAgBAAAAIABgFQABAAAAAAQABAAAAgBQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABABAAAAQABAAAAAAQAAABABAAQAAABAAAAQAAABAAAAQAAABAAABQAAAAAAABQAAAAAAABQAAAAAAABQgBABAAAAIgEABIgEgBgAD/AXQgDgDAAgGIAAgeIgIAAIAAgGIAIAAIAAgOIAHAAIAAAOIAMAAIAAAGIgMAAIAAAdQAAAEABABIAEABQADAAAEgDIACAGIgFACIgFABQgGAAgCgCgADCAYIgHgFIgEgHQgCgFAAgGQAAgJADgGQAFgGAFgCQAEgCAEAAQAFAAAEACIAFAEIADAEIgGAEIgEgFQgDgCgEgBQgFAAgDADQgDADgBAFIgCAHIACAIQABAEACACIAEAEIAGABQAEAAAEgCIAFgDIACAHIgHADIgIABIgJgBgABnATQgHgGAAgNQAAgIAEgFQADgGAEgDQAFgCAEAAQAHAAAGAEQAEAEACAFIACALIgiAAQAAAJAEAFQAFAFAHAAQAEAAAEgCIAGgDIABAGIgGAEIgJABQgLAAgFgGgABtgPQgDADgCAHIAZAAQgBgFgBgDQgDgCgDgBIgFgCQgEAAgDADgAAvAYIgGgCIgDgCIACgGIAGADQADACAFAAQAFAAACgCQACgCAAgDQAAgFgMgFQgGgCgEgDQgCgCAAgGQAAgFAEgEQAEgEAGAAQAGAAAEACIAGADIgDAGIgGgDIgGgCQgEABgCACQgBAAAAABQAAAAgBABQAAAAAAABQAAAAAAABQAAAFALADQAGACAEADQADADAAAGQAAAFgCAEQgDADgEABIgHABIgHgBgAgrATQgGgGAAgNQAAgIADgFQADgGAFgDQAFgCAEAAQAIAAAEAEQAFAEABAFQACAHAAAEIggAAQgBAJAEAFQAFAFAGAAIAIgCIAGgDIACAGQgBACgGACIgJABQgKAAgGgGgAglgPQgDADgBAHIAYAAQAAgFgCgDQgCgCgDgBIgFgCQgEAAgEADgAh6AVQgFgFAAgKIAAgcIAIAAIAAAdQAAAGACADQADADAGAAIAHgCQAEgBACgCIAAgkIAHAAIAAAuIgGAAIgBgDIgHADIgIABQgIAAgEgEgAiXAXQgEgDAAgGIAAgeIgHAAIAAgGIAHAAIAAgOIAIAAIAAAOIAMAAIAAAGIgMAAIAAAdQAAAEABABIAEABQADAAADgDIACAGIgEACIgGABQgFAAgCgCgAjNAVQgEgFAAgKIAAgcIAHAAIAAAdQABAGACADQADADAFAAIAHgCQAEgBACgCIAAgkIAHAAIAAAuIgGAAIgBgDIgGADIgIABQgJAAgEgEgAksATQgGgGAAgNQAAgIADgFQADgGAFgDQAFgCAEAAQAHAAAFAEQAFAEACAFIABALIghAAQAAAJAEAFQAEAFAIAAQADAAAEgCIAGgDIACAGIgGAEIgKABQgKAAgGgGgAklgPQgEADgBAHIAYAAQgBgFgBgDQgCgCgDgBIgFgCQgEAAgDADgAFMAYIAAgdQAAgFgDgEQgCgEgGAAIgHACIgGADIAAAlIgHAAIAAguIAHAAIAAADIAGgDIAIgCQAJAAAFAFQADAEAAALIAAAcgAEYAYIAAguIAHAAIAAAugADlAYIAAguIAHAAIAAAugACqAYIgLgSIgLASIgJAAIAQgYIgPgWIAIAAIALAQIAKgQIAIAAIgOAWIAPAYgAAUAYIAAguIAHAAIAAAugAhLAYIAAguIAHAAIABAEIAFgEQADgCADAAIAFABIgBAHIgEAAIgGABIgFAEIAAAjgAjrAYIAAgoIgGAAIAAgGIAGAAIAAgEQAAgGADgFQACgEADgBIAHgBIAIACIgBAGIgEgCIgDAAQgEAAgCAEIgBAHIAAAEIAKAAIAAAGIgKAAIAAAogAlFAYIAAgcQAAgIgCgCQgDgDgFgBIgHACIgGADIAAAlIgHAAIAAhBIAHAAIAAAWIAGgDQAEgCAEAAQAJAAAFAFQADAFAAAKIAAAcgAmGAYIAAg7IgTAAIAAgGIAuAAIAAAGIgTAAIAAA7gAEZggQgBgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAABgBQAAAAAAAAQABAAAAgBQABAAAAAAQABAAAAAAQABAAAAAAQAAAAABAAQAAABABAAQAAAAAAAAQABABAAAAQAAAAABABQAAAAAAABQAAAAAAABQAAABAAAAQAAABAAAAQgBABAAAAQAAAAgBABQAAAAAAAAQgBAAAAABQgBAAAAAAQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAgBgBAAQAAAAAAAAgADlggQgBgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAABgBQAAAAAAAAQABAAAAgBQABAAAAAAQABAAAAAAQABAAAAAAQAAAAABAAQAAABABAAQAAAAABAAQAAABAAAAQAAAAABABQAAAAAAABQAAAAAAABQAAABAAAAQAAABAAAAQgBABAAAAQAAAAAAABQgBAAAAAAQgBAAAAABQgBAAAAAAQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAgBgBAAQAAAAAAAAgAAUggQAAgBgBAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAgBAAAAQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAABgBQAAAAABAAQAAAAAAAAQABAAAAAAQABAAAAAAQABABAAAAQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABQABAAAAABQAAABgBAAQAAABAAAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAAAAAQgBAAAAAAQgBgBAAAAQgBAAAAAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1_1, new cjs.Rectangle(-41,-4.4,82.1,8.8), null);


(lib.logoZnak = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#EF4329").s().p("AjPE/QhihjgBiXQgBhjAyhiQAuhbBLg/QBGg6BagiQBagjBXAAQAcAAAMAEQhNAQg0A/Qg2BBABBPIABAJQB9AeA+BMQA8BGAABtQABByhQBYQhXBfiGABIgCAAQh4AAhchbg");
	this.shape.setTransform(-0.1,-2.4,0.24,0.24);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AmJGKQikijAAjnQAAjmCkijQCjikDmAAQDnAACjCkQCkCjAADmQAADnikCjQijCkjnAAQjmAAijikg");
	this.shape_1.setTransform(0,0,0.24,0.24);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.logoZnak, new cjs.Rectangle(-13.4,-13.4,26.8,26.8), null);


(lib.logoTxt = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AD4AzQgHgDgFgFQgFgEgDgIQgDgHAAgKQAAgJADgGQADgIAFgEQAEgFAGgDQAHgDAHABQAHgBAGADQAGACAEAFQAEAFADAHQADAHAAALIAAADIgwAAQAAAKAFADQAFAFAJAAIAHgBIAGgCIAFgCIACgCIAGAQIgEACIgGACIgIACIgLABQgHAAgGgCgAD6gEQgEADgBAGIAcAAIgBgGIgEgEIgEgCIgEgCQgFABgFAEgABVAxQgHgDgEgGQgFgFgCgHQgCgGAAgIQAAgHACgHQACgGAFgGQAEgFAHgDQAHgEAIABQAJgBAHAEQAGADAFAFQAEAGADAGQACAGAAAIQAAAIgCAGQgDAIgEAEQgEAGgHADQgHAEgJAAQgIAAgHgEgABdgGQgDACgCADIgDAGIgBAJIABAJIADAHIAFAFQADACAEAAQAEAAADgCQAEgCACgDIADgHIABgJIgBgJIgDgGQgCgDgEgCQgCgBgFAAQgEAAgDABgAgmAzIgIgEIgGgHQgCgEAAgGQAAgGADgEQACgEADgDIAJgFIAKgDIAIgBIAHAAIAAgCQAAgFgDgCQgDgDgGAAIgGABIgFACIgEACIgDACIgGgNIAEgDIAGgDIAIgCIAKgBIALABQAFACAEADQACAEACAFQACAFAAAHIAAAvIgQAAIgBgFQgDADgFACQgFACgFAAIgJgCgAgYASQgGACgDADQgCACAAAEQAAADADADQADACAEAAIAIgCQADgBACgDIAAgPgAhyAyQgGgEgEgFQgEgFgCgHQgCgHAAgIQAAgHACgHQADgGAEgGQAEgFAHgDQAHgEAIABQAGAAAHABIAAgcIATAAIAABlIgSAAIAAgFQgDACgEADQgFACgFAAQgIAAgGgDgAhngFQgDABgDADIgDAGIgBAJIABAJIADAHIAFAFQADACAEAAQAEAAAEgCQADgCACgCIAAgkQgGgCgEAAQgFAAgEACgAjAAxQgHgDgEgGQgFgEgCgIQgCgGAAgIQAAgHACgHQACgHAFgFQAEgFAHgDQAHgEAIABQAJgBAHAEQAGADAFAFQAEAFACAHQADAHAAAHQAAAIgDAGQgCAIgEAEQgFAGgGADQgHAEgJAAQgIAAgHgEgAi4gGIgFAFIgEAGIgBAJIABAJIAEAHIAFAFQADACAEAAQAEAAADgCIAGgFIADgHIABgJIgBgJIgDgGIgGgFQgDgBgEAAQgEAAgDABgADDAzIAAgqQAAgJgEgDQgDgFgGABQgFAAgEACIgGAFIAAAzIgTAAIAAhJIARAAIABAGQAFgDAFgDQAGgBAFAAQAGAAAFABQAFACAEAEQADADACAHQACAGAAAHIAAAsgAAaAzIAAg5IgKAAIAAgQIAKAAIAAgDQAAgIACgFQACgFADgDQADgDAFgBQAEgCAGAAIALABIAFACIgCAQIgDgBIgIgCQgEAAgCADQgDACAAAGIAAADIAQAAIAAAQIgQAAIAAA5gAkFAzIgfhJIAUAAIAUAwIATgwIATAAIgeBJg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.logoTxt, new cjs.Rectangle(-29.3,-5.3,58.6,10.6), null);


(lib.bg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// back
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#872213","#972716","#C23420","#EF4329","#ED4732"],[0,0.118,0.349,0.569,1],-110.8,226,139.1,-283.3).s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.bg, new cjs.Rectangle(-150,-300,300,600), null);


(lib.banner = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_89 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(89).call(this.frame_89).wait(1));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_14 = new cjs.Graphics().p("AoqVvIAAkUILVAAIAAEUg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(14).to({graphics:mask_graphics_14,x:-55.5,y:139.1}).wait(76));

	// logoTxt
	this.instance = new lib.logoTxt();
	this.instance.parent = this;
	this.instance.setTransform(-140.2,264);
	this.instance._off = true;

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(14).to({_off:false},0).to({x:-77.7},10,cjs.Ease.get(1)).wait(66));

	// logoZnak
	this.instance_1 = new lib.logoZnak();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-123.6,264,0.02,0.02);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(4).to({_off:false},0).to({scaleX:1.2,scaleY:1.2},5,cjs.Ease.get(1)).to({scaleX:1,scaleY:1},5,cjs.Ease.get(-1)).wait(76));

	// t3
	this.instance_2 = new lib.t3();
	this.instance_2.parent = this;
	this.instance_2.setTransform(-67.2,16.8,1.17,1.17);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(79).to({_off:false},0).to({alpha:1},10).wait(1));

	// t1_2
	this.instance_3 = new lib.t1_2();
	this.instance_3.parent = this;
	this.instance_3.setTransform(-21.7,236);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(59).to({_off:false},0).to({x:-111.7,alpha:1},10,cjs.Ease.get(1)).wait(21));

	// t1_1
	this.instance_4 = new lib.t1_1();
	this.instance_4.parent = this;
	this.instance_4.setTransform(-4.7,220.1);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(49).to({_off:false},0).to({x:-94.7,alpha:1},10,cjs.Ease.get(1)).wait(31));

	// t2_2
	this.instance_5 = new lib.t2_2();
	this.instance_5.parent = this;
	this.instance_5.setTransform(-306.9,-19.9,1.17,1.17,0,0,0,-0.1,0);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(59).to({_off:false},0).to({x:-61.2},10,cjs.Ease.get(1)).wait(21));

	// t2_1
	this.instance_6 = new lib.t2_1();
	this.instance_6.parent = this;
	this.instance_6.setTransform(-270.2,-44.8,1.17,1.17,0,0,0,0,-0.1);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(49).to({_off:false},0).to({x:-24.5},10,cjs.Ease.get(1)).wait(31));

	// Слой 15
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(4,1,1).p("AAMgZQgMAZgLAZ");
	this.shape.setTransform(-69.2,-69.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#FFFFFF").ss(4,1,1).p("ABhiiQhzCYhOCu");
	this.shape_1.setTransform(-60.7,-83.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#FFFFFF").ss(4,1,1).p("ADqkwQk3EFicFc");
	this.shape_2.setTransform(-47,-97.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#FFFFFF").ss(4,1,1).p("AGQmhQhqA5hlBJQmWEgi6Gh");
	this.shape_3.setTransform(-30.4,-108.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#FFFFFF").ss(4,1,1).p("AJKnuQhCAVhBAYIhPAgQgqAQhDAhQiGBDh/BbQmVEgi6Gh");
	this.shape_4.setTransform(-11.8,-116.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f().s("#FFFFFF").ss(4,1,1).p("AMMoVQiQAMioAtQhpAbhmAnIhPAgQgqAQhDAhQiFBDh/BbQmXEgi5Gh");
	this.shape_5.setTransform(7.6,-120.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#FFFFFF").ss(4,1,1).p("AMwnoQAvgSAygNQj0gulPBaQhpAchlAmIhQAgQgqAQhBAiQiHBDh+BaQmXEhi5Gg");
	this.shape_6.setTransform(20.9,-120.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f().s("#FFFFFF").ss(4,1,1).p("AHhkQQASgUAUgSQCciRDuhAQj0gulPBaQhpAchlAmIhQAgQgqAQhBAiQiHBDh+BaQmXEhi5Gg");
	this.shape_7.setTransform(20.9,-120.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f().s("#FFFFFF").ss(4,1,1).p("AEdBpQAPhIAchCQBCihB9h0QCciRDuhAQj0gulPBaQhpAchlAmIhQAgQgqAQhBAiQiHBDh+BaQmXEhi5Gg");
	this.shape_8.setTransform(20.9,-120.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f().s("#FFFFFF").ss(4,1,1).p("AG/FlQhXgehggRQgDgoAHg/QANh+AvhyQBCihB9h0QCciRDuhAQj0gulPBaQhpAchlAmIhQAgQgqAQhBAiQiHBDh+BaQmXEhi5Gg");
	this.shape_9.setTransform(20.9,-120.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f().s("#FFFFFF").ss(4,1,1).p("AMEIQQhDg0hOgqQilhZjGgjQgDgoAHg/QANh+AvhyQBCihB9h0QCciRDuhAQj0gulPBaQhpAchlAmIhQAgQgqAQhBAiQiHBDh+BaQmXEhi5Gg");
	this.shape_10.setTransform(20.9,-120.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f().s("#FFFFFF").ss(4,1,1).p("APPK0Qg1hohNhZQh1iFijhYQikhZjGgjQgDgoAHg/QAMh9AwhzQBCihB8h0QCciRDvhAQj1gulOBaQhpAchmAmIhOAgQgqAQhDAiQiGBDh/BaQmWEii6Gf");
	this.shape_11.setTransform(27.1,-104.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f().s("#FFFFFF").ss(4,1,1).p("AQFN6QgLiVgwiHQg9iqh2iIQh1iFijhYQikhYjGgjQgEgoAIg/QAMh+AwhzQBCihB8h0QCciRDvhAQj1gulOBaQhpAchmAmIhPAgQgqAQhCAiQiHBDh+BaQmXEii5Gf");
	this.shape_12.setTransform(32.5,-84.8);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f().s("#FFFFFF").ss(4,1,1).p("APeQ1QAoiIAAiRQABjIg/iwQg9irh2iHQh1iFijhYQikhZjGgiQgDgoAHhAQAMh+AwhzQBCihB8hzQCciRDvhBQj1gtlOBaQhpAbhmAnIhOAgQgqAQhDAhQiGBDh/BbQmWEhi6Gh");
	this.shape_13.setTransform(32.7,-66.2);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f().s("#FFFFFF").ss(4,1,1).p("AM9TaQBFheAuhsQBVjDABjWQABjIg/iwQg9irh2iGQh1iGijhYQikhZjGgiQgDgoAHhAQAMh+AwhzQBCihB8hzQCciRDvhBQj1gtlOBaQhpAbhmAnIhOAgQgqAQhDAhQiGBDh/BbQmWEhi6Gh");
	this.shape_14.setTransform(32.7,-49.7);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f().s("#FFFFFF").ss(4,1,1).p("AICVqQAGgEAGgEQBmg/BXhVQCTiSBSi8QBVjDABjWQABjIg/iwQg9iqh2iHQh1iGijhYQikhZjGgiQgDgoAHhAQAMh+AwhzQBCihB8hzQCciRDvhBQj1gtlOBaQhpAbhmAnIhOAgQgqAQhDAhQiGBDh/BbQmWEhi6Gh");
	this.shape_15.setTransform(32.7,-35.3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f().s("#FFFFFF").ss(4,1,1).p("ACHWwQB6gVB0gwQDAhRCWiRQCTiSBSi9QBVjDABjVQABjJg/iwQg9iph2iIQh1iFijhYQikhZjGgjQgDgoAHg/QAMh+AwhzQBCihB8h0QCciRDvhAQj1gulOBaQhpAchmAmIhOAgQgqAQhDAiQiGBDh/BaQmWEii6Gg");
	this.shape_16.setTransform(32.7,-28.3);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f().s("#FFFFFF").ss(4,1,1).p("AkJWgQBtAXBxAAQDaAADGhTQDAhRCWiRQCTiSBSi9QBVjDABjVQABjJg/iwQg9iph2iIQh1iFijhYQikhZjGgjQgDgoAHg/QAMh+AwhzQBCihB8h0QCciRDvhAQj1gulOBaQhpAchmAmIhOAgQgqAQhDAiQiGBDh/BaQmWEii6Gg");
	this.shape_17.setTransform(32.7,-27.6);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f().s("#FFFFFF").ss(4,1,1).p("ApuUMQBoBDBzApQCuA/C6AAQDaAADGhTQDAhRCWiRQCTiSBSi9QBVjDABjVQABjJg/iwQg9iph2iIQh1iFijhYQikhZjGgjQgDgoAHg/QAMh+AwhzQBCihB8h0QCciRDvhAQj1gulOBaQhpAchmAmIhOAgQgqAQhDAiQiGBDh/BaQmWEii6Gg");
	this.shape_18.setTransform(32.7,-27.6);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f().s("#FFFFFF").ss(4,1,1).p("AufPvQBeB8B5BgQCOBxCnA8QCuA/C6AAQDaAADGhTQDAhRCWiRQCTiSBSi9QBVjDABjVQABjJg/iwQg9iph2iIQh1iFijhYQikhZjGgjQgDgoAHg/QAMh+AwhzQBCihB8h0QCciRDvhAQj1gulOBaQhpAchmAmIhOAgQgqAQhDAiQiGBDh/BaQmWEii6Gg");
	this.shape_19.setTransform(32.7,-27.6);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f().s("#FFFFFF").ss(4,1,1).p("AwuKMQA2CqBmCTQBnCUCLBuQCOBxCnA8QCuA/C6AAQDaAADGhTQDAhRCWiRQCTiSBSi9QBVjDABjVQABjJg/iwQg9iph2iIQh1iFijhYQikhZjGgjQgDgoAHg/QAMh+AwhzQBCihB8h0QCciRDvhAQj1gulOBaQhpAchmAmIhOAgQgqAQhDAiQiGBDh/BaQmWEii6Gg");
	this.shape_20.setTransform(28.7,-27.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape}]},24).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_15}]},1).to({state:[{t:this.shape_16}]},1).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_18}]},1).to({state:[{t:this.shape_19}]},1).to({state:[{t:this.shape_20}]},1).wait(46));

	// bg
	this.instance_7 = new lib.bg();
	this.instance_7.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(90));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,-300,300,600);


// stage content:
(lib._300x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// cover
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#666666").ss(2,2,0,3).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// banner
	this.instance = new lib.banner();
	this.instance.parent = this;
	this.instance.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(149,299,302,602);
// library properties:
lib.properties = {
	id: '269F2CF89B324EF0A921B432E71E763A',
	width: 300,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['269F2CF89B324EF0A921B432E71E763A'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;