(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.bgImg1 = function() {
	this.initialize(img.bgImg1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,541);


(lib.bgImg2 = function() {
	this.initialize(img.bgImg2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,541);


(lib.bgImg3 = function() {
	this.initialize(img.bgImg3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,541);


(lib.drops1 = function() {
	this.initialize(img.drops1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,541);


(lib.drops2 = function() {
	this.initialize(img.drops2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,541);


(lib.prod = function() {
	this.initialize(img.prod);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,247,300);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.urText = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgdAqIAAgFQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAABAAIAHAAIAHgBIADgEIAHgRIgBAAQgDABgCgCIgDgGIgTgvIAAgBQAAgBAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIAIAAQAAAAAAAAQABAAAAAAQAAABAAAAQABAAAAABIARAsIABABIAAABIABAAIASguIACgCIAIAAQAAAAABAAQAAAAAAAAQAAABABAAQAAAAAAABIgbBFQgEAKgFAEQgGAEgIAAQgKAAAAgDg");
	this.shape.setTransform(127.7,-0.7,0.749,0.749);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgZAtIgBgBIgBgCIAAhSIABgCQABgBAIAAIANgBQAgAAAAAaIAAACQAAAaggAAIgMgBIAAAhIgBACIgBABgAgQAAIAMABQALgBAFgDQAFgEAAgJIAAgCQAAgIgFgFQgFgDgLAAIgMAAg");
	this.shape_1.setTransform(122.2,-0.8,0.749,0.749);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgXAjQgIgJAAgSIAAgPQAAgTAIgJQAJgKAOAAQAQAAAIAKQAIAKAAASIAAAPQAAASgIAJQgJALgPgBQgOABgJgLgAgVgHIAAAPQAAAbAVAAQAWAAAAgbIAAgPQAAgbgWgBQgVABAAAbg");
	this.shape_2.setTransform(116.2,-0.7,0.749,0.749);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgUAtQgHgBAAgCIgBgCIAAhSQAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIAtAAIACABIAAABIAAAFIAAACIgCABIgkAAIAAAcIAMgBQAiAAAAAZIAAACQAAAZgiAAgAgRACIAAAhIAMABQANgBAFgEQAFgDAAgIIAAgDQAAgJgFgDQgGgEgMAAg");
	this.shape_3.setTransform(110.4,-0.7,0.749,0.749);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAaAtIgCgBIgIgdIgfAAIgIAcIAAABIgCABIgHAAQAAAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAgBIAAgBIAXhNQADgJAIAAQAKAAACAJIAXBNIAAABQAAABgBAAQAAAAAAABQAAAAgBAAQAAAAAAAAgAANAGIgLgnIgBAAIAAgBIgBAAIgBABIgMAnIAaAAg");
	this.shape_4.setTransform(104.4,-0.8,0.749,0.749);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAXAtIgCgBIgBgCIAAgoIgnAAIAAAoIgCACIgBABIgGAAIgCgBIgBgCIAAhUIABgBIACgBIAGAAIABABIACABIAAAjIAnAAIAAgjIABgBIACgBIAGAAIACABIAAABIAABUIAAACIgCABg");
	this.shape_5.setTransform(98.3,-0.7,0.749,0.749);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgXAjQgIgJAAgSIAAgPQgBgTAKgJQAHgKAPAAQAQAAAIAKQAIAJAAATIAAAPQAAATgIAIQgJALgPgBQgOABgJgLgAgVgHIAAAPQAAAbAVAAQAVAAABgbIAAgPQgBgbgVgBQgVABAAAbg");
	this.shape_6.setTransform(89.5,-0.7,0.749,0.749);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgVAtIgCgBIgBgCIAAhAQAAgLAGgGQAHgFALAAIAZABIAAACIAAAFQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAAAAAIgYAAQgGAAgEACQgDABAAAJIAABAIgBACIgCABg");
	this.shape_7.setTransform(84.8,-0.8,0.749,0.749);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgXAjQgJgJABgSIAAgPQAAgTAJgJQAIgKAOAAQAPAAAKAKQAHAJABATIAAAPQgBATgHAIQgKALgPgBQgOABgJgLgAgUgHIAAAPQgBAbAVAAQAVAAABgbIAAgPQgBgbgVgBQgVABABAbg");
	this.shape_8.setTransform(78.9,-0.7,0.749,0.749);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgUAtQgGgBgCgBIgBgDIAAhPIABgDIACgBIAVgCQAiAAAAAYIAAACQAAAHgEAEQgDAFgGADQAGABAEAFQADAGABAGIAAACQAAAagjgBgAgSAjIANABQANAAAFgEQAGgEAAgIIAAgCQAAgQgSAAIgTAAgAgSgFIATAAQARAAAAgOIAAgCQAAgHgFgEQgFgDgNAAIgNAAg");
	this.shape_9.setTransform(73.1,-0.7,0.749,0.749);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgXAjQgJgJAAgSIAAgPQAAgTAJgJQAJgKAOAAQAQAAAIAKQAJAKAAASIAAAPQAAASgJAJQgIALgQgBQgPABgIgLgAgUgHIAAAPQAAAbAUAAQAVAAAAgbIAAgPQAAgbgVgBQgUABAAAbg");
	this.shape_10.setTransform(67,-0.7,0.749,0.749);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgCAtIgCgBIAAgCIAAhNIgYAAQAAAAgBAAQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAgGIABgBIABgBIA5AAQABAAAAABQAAAAABAAQAAAAAAABQAAAAAAAAIAAAGQAAAAAAABQAAAAAAAAQgBAAAAAAQAAAAgBAAIgXAAIAABNIgBACIgCABg");
	this.shape_11.setTransform(61.8,-0.7,0.749,0.749);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgZAtIgCgBIAAgCIAAhSIABgCQABgBAIAAIANgBQAgAAAAAaIAAACQAAAaggAAIgMgBIAAAhIgBACIgCABgAgQAAIAMABQAKgBAGgDQAFgEAAgJIAAgCQAAgJgFgEQgFgDgLAAIgMAAg");
	this.shape_12.setTransform(56.4,-0.8,0.749,0.749);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAaAtIgCgBIgIgdIgfAAIgHAcIgBABIgCABIgHAAQAAAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAgBIAAgBIAXhNQADgJAIAAQAKAAACAJIAXBNIAAABQAAABgBAAQAAAAAAABQAAAAgBAAQAAAAAAAAgAANAGIgLgnIAAAAIgBgBIgBAAIgBABIgMAnIAaAAg");
	this.shape_13.setTransform(50.5,-0.8,0.749,0.749);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgCAtIgCgBIAAgCIAAhNIgYAAQAAAAgBAAQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAgGIAAgBIACgBIA5AAQAAAAABABQAAAAABAAQAAAAAAABQAAAAAAAAIAAAGQAAAAAAABQAAAAAAAAQgBAAAAAAQgBAAAAAAIgYAAIAABNIAAACIgCABg");
	this.shape_14.setTransform(45.8,-0.7,0.749,0.749);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgSAkQgIgJAAgSIAAgRQAAgTAIgIQAJgKAOAAIANABIAIACIAAABIAAAGQAAAAAAABQAAAAAAAAQAAAAAAAAQgBAAAAAAIgUgBQgUAAAAAbIAAARQAAANAFAGQAFAIAKgBIAUAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAAAIAAAGIgBACIgVABQgOAAgJgJg");
	this.shape_15.setTransform(40.6,-0.7,0.749,0.749);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgDAtIgBgBIgBgCIAAhUQAAAAABAAQAAgBAAAAQAAAAABAAQAAgBAAAAIAGAAQABAAAAABQABAAAAAAQAAAAAAABQAAAAAAAAIAABUIgBACIgBABg");
	this.shape_16.setTransform(34.2,-0.7,0.749,0.749);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAZAtQAAAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAgBIgVhLQAAgBAAAAQAAgBgBAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQgBAAAAAAQAAAAAAABQAAAAAAABIgVBLQAAABgBAAQAAAAAAABQAAAAgBAAQAAAAgBAAIgHAAQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAAAAAgBIAAgBIAXhNQACgJAJAAQAJAAADAJIAWBNIABABQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_17.setTransform(29.9,-0.8,0.749,0.749);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgUAtQgHgBAAgBQgBAAAAAAQAAgBAAAAQAAAAAAgBQAAAAAAgBIAAhPIAAgDIACgBIAIgBIANgBQAiAAAAAYIAAACQAAAGgDAFQgEAGgGACQAGABAEAFQADAFAAAHIAAACQAAAagigBgAgRAjIAMABQANAAAFgEQAFgEAAgIIAAgCQAAgQgSAAIgRAAgAgRgFIARAAQASAAAAgOIAAgCQAAgIgFgDQgFgDgNAAIgMAAg");
	this.shape_18.setTransform(24.2,-0.7,0.749,0.749);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgCAtIgCgBIgBgCIAAhUQAAAAABAAQAAgBAAAAQAAAAABAAQAAgBABAAIAFAAQABAAAAABQABAAAAAAQAAAAAAABQABAAAAAAIAABUIgBACIgCABg");
	this.shape_19.setTransform(19.9,-0.7,0.749,0.749);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AAXAtIgCgBIAAgCIAAhGIgCgFQAAAAAAAAQAAAAgBgBQAAAAgBAAQgBAAgBAAIgdAAQgBAAgBAAQgBAAAAAAQgBABAAAAQgBAAAAAAIgBAFIAABGIAAACIgCABIgGAAIgCgBIAAgCIAAhGQgBgPARgBIAdAAQARABAAAPIAABGIgBACIgCABg");
	this.shape_20.setTransform(15.4,-0.7,0.749,0.749);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgdAqIAAgFQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAABAAIAIAAIAGgBIAEgEIAGgRIAAAAQgEABgCgCQgCgBgBgFIgTgwQAAgBAAAAQABAAAAgBQAAAAAAAAQABAAAAAAIAIAAQAAAAAAAAQABAAAAAAQAAABAAAAQABAAAAABIARAsIABABIAAABIABAAIASguIACgCIAIAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAAABIgbBEQgEAKgFAEQgFAEgIAAQgLAAAAgDg");
	this.shape_21.setTransform(9.5,-0.7,0.749,0.749);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AASAtIgCgBIghgqIAAAoIgBACIgBABIgHAAIgCgBIAAgCIAAhUIAAgBIACgBIAGAAIACABIABABIAAAoIAhgpIADgBIAIAAQABAAAAABQAAAAABAAQAAAAAAAAQAAAAAAAAIAAACIgkApIAkAqIAAACQAAAAAAAAQAAAAAAAAQAAAAgBAAQAAAAAAABg");
	this.shape_22.setTransform(4,-0.7,0.749,0.749);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgDAtIgBgBIgBgCIAAhUQAAAAABAAQAAgBAAAAQAAAAABAAQAAgBAAAAIAGAAQABAAAAABQABAAAAAAQAAAAAAABQAAAAAAAAIAABUIAAACIgCABg");
	this.shape_23.setTransform(-2.8,-0.7,0.749,0.749);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgRAsIgIgBIAAgCIAAgFQAAAAAAAAQAAgBAAAAQAAAAABAAQAAAAABAAIAUABQAJAAAFgDQAEgFAAgJIAAgCQAAgGgEgEQgEgFgGAAIgVAAQAAAAgBAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAgDQAAgBAAAAQAAAAAAAAQABgBAAAAQABAAAAAAIAVAAQAHAAADgEQAEgEAAgGIAAgCQAAgIgEgDQgFgDgJgBIgUACQgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAgEIABgCIAIgCIANgBQAPAAAHAHQAHAFAAAMIAAACQAAAMgLAHQALAEAAANIAAACQAAAOgIAFQgIAIgNgBIgOgBg");
	this.shape_24.setTransform(-6.9,-0.7,0.749,0.749);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AAaAtIgCgBIgIgdIgfAAIgIAcIgBABIgBABIgHAAQAAAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAgBIAAgBIAWhNQAEgJAIAAQAKAAACAJIAXBNIAAABQAAABgBAAQAAAAAAABQAAAAgBAAQAAAAgBAAgAANAGIgLgnIAAAAIgBgBIgBAAIgBABIgMAnIAaAAg");
	this.shape_25.setTransform(-12.6,-0.8,0.749,0.749);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgZAtIgBgBIgBgCIAAhSIABgCQABgBAIAAIANgBQAgAAAAAaIAAACQAAAaggAAIgMgBIAAAhIgBACIgBABgAgQAAIAMABQALgBAFgDQAGgEAAgJIAAgCQAAgIgGgFQgFgDgLAAIgMAAg");
	this.shape_26.setTransform(-17.4,-0.8,0.749,0.749);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgcAqIAAgFQAAgBAAAAQAAAAAAgBQAAAAABAAQAAAAABAAIAHAAIAHgBIADgEIAHgRIAAAAQgEABgCgCIgDgGIgSgvIAAgBQAAgBAAAAQAAAAAAgBQAAAAAAAAQABAAAAAAIAIAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIARAsIABABIABABIABAAIASguQAAgBABAAQAAAAAAgBQAAAAABAAQAAAAABAAIAGAAQABAAAAAAQABAAAAAAQAAABAAAAQABAAAAABIAAABIgbBEQgEAKgFAEQgFAEgJAAQgKAAABgDg");
	this.shape_27.setTransform(-25.4,-0.7,0.749,0.749);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgQAtIgHgCQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAAAIAAgGQAAAAAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIAVAAQAIAAAEgDQAEgDABgIQgBgEgCgDQgCgDgKgFIgLgHQgJgGgEgEQgDgGAAgHQAAgUAbgBIAOABIAJABQAAAAAAABQAAAAAAAAQAAAAAAAAQABABAAAAIAAAFQAAAAgBABQAAAAAAABQAAAAgBAAQAAAAAAAAIgWgBQgJABgDACQgEADAAAFQAAAFADADIAUAOQAKAFAFAGQAEAFAAAHQAAAIgDAGQgDAEgHAEQgGACgJAAg");
	this.shape_28.setTransform(-33.3,-0.7,0.749,0.749);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgXAjQgJgJAAgSIAAgPQABgTAIgJQAIgKAPAAQAQAAAIAKQAJAKAAASIAAAPQAAASgJAJQgIALgQgBQgPABgIgLgAgUgHIAAAPQAAAbAUAAQAVAAAAgbIAAgPQAAgbgVgBQgUABAAAbg");
	this.shape_29.setTransform(-38.7,-0.7,0.749,0.749);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgBA0QgDgEAAgIIAAgFQgOgCgGgKQgIgIABgRIAAgPQAAgTAIgJQAJgKAOAAQAQAAAIAKQAIAKABASIAAAPQAAAQgIAKQgGAJgOACIAAAFQAAAEABACQABABAGAAIAHAAQABAAAAAAQABAAAAAAQAAABAAAAQABAAAAABIAAAEQAAADgKAAQgLAAgDgEgAgVgRIAAAPQAAAbAVAAQAVAAABgbIAAgPQgBgcgVAAQgVAAAAAcg");
	this.shape_30.setTransform(-44.9,0,0.749,0.749);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgCAtIgCgBIgBgCIAAhUQAAAAABAAQAAgBAAAAQAAAAABAAQAAgBABAAIAFAAQABAAAAABQABAAAAAAQAAAAAAABQAAAAAAAAIAABUIAAACIgCABg");
	this.shape_31.setTransform(-49.3,-0.7,0.749,0.749);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AAZAtIgBgBIgCgEIgGgZIgfAAIgHAcIgBABIgBABIgIAAQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAAAAAgBIAAgBIAXhNQACgJAJAAQAJAAADAJIAWBNIABABQAAABAAAAQgBAAAAABQAAAAAAAAQgBAAAAAAgAANAGIgLgnIAAAAIgBgBIgBAAIAAAAIgBABIgLAnIAZAAg");
	this.shape_32.setTransform(-56,-0.8,0.749,0.749);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgRAsIgIgBIAAgCIAAgFQAAAAAAAAQAAgBAAAAQABAAAAAAQABAAAAAAIAUABQAJAAAFgDQAEgFAAgJIAAgCQAAgGgEgEQgDgFgHAAIgVAAQAAAAgBAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAgDQAAgBAAAAQAAAAAAAAQABgBAAAAQABAAAAAAIAVAAQAHAAAEgEQADgFAAgFIAAgCQAAgIgEgDQgFgDgJgBIgUACQgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAgEIABgCIAIgCIANgBQAPAAAHAHQAHAFAAAMIAAACQAAAMgLAHQALAEAAANIAAACQAAAOgIAFQgIAIgNgBIgOgBg");
	this.shape_33.setTransform(-61.3,-0.7,0.749,0.749);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AAZAtIgBgBIgCgEIgGgZIgfAAIgHAcIgBABIgBABIgIAAQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAAAAAgBIAAgBIAXhNQACgJAJAAQAJAAADAJIAWBNIABABQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAgAANAGIgLgnIAAAAIgBgBIgBAAIAAAAIgBABIgLAnIAZAAg");
	this.shape_34.setTransform(-69.4,-0.8,0.749,0.749);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AAXAtIgCgBIAAgCIAAgoIgoAAIAAAoIgBACIgCABIgGAAIgCgBIgBgCIAAhUIABgBIACgBIAGAAIACABIABABIAAAjIAoAAIAAgjIAAgBIACgBIAGAAIACABIAAABIAABUIAAACIgCABg");
	this.shape_35.setTransform(-75.5,-0.7,0.749,0.749);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AAZAtIgBgBIgCgEIgGgZIgfAAIgHAcIgBABIgBABIgIAAQAAAAgBAAQAAAAAAAAQAAgBgBAAQAAAAAAgBIAAgBIAXhNQACgJAJAAQAJAAADAJIAWBNIABABQAAABAAAAQgBAAAAABQAAAAAAAAQgBAAAAAAgAANAGIgLgnIAAAAIgBgBIgBAAIAAAAIgBABIgLAnIAZAAg");
	this.shape_36.setTransform(-81.7,-0.8,0.749,0.749);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgRAsIgIgBIAAgCIAAgFQAAAAAAAAQAAgBAAAAQABAAAAAAQABAAAAAAIAUABQAJAAAFgDQAEgFAAgJIAAgCQAAgGgEgEQgEgFgGAAIgVAAQAAAAgBAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAgDQAAgBAAAAQAAAAAAAAQABgBAAAAQABAAAAAAIAVAAQAHAAADgEQAEgEAAgGIAAgCQAAgIgEgDQgFgDgJgBIgUACQgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAgEIABgCIAIgCIANgBQAPAAAHAHQAHAFAAAMIAAACQAAAMgLAHQALAEAAANIAAACQAAAOgIAFQgIAIgNgBIgOgBg");
	this.shape_37.setTransform(-86.9,-0.7,0.749,0.749);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AAZAtIgBgBIgJgdIgdAAIgIAcIgBABIgBABIgHAAQgBAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAgBIAAgBIAVhNQADgJAJAAQAKAAACAJIAWBNIAAABQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAgBAAgAANAGIgLgnIAAAAIgBgBIgBAAIgBABIgMAnIAaAAg");
	this.shape_38.setTransform(-92.6,-0.8,0.749,0.749);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AASAtIgCgBIghgqIAAAoIgBACIgBABIgHAAIgBgBIgBgCIAAhUIABgBIABgBIAHAAIABABIABABIAAAoIAigpIACgBIAJAAQAAAAAAABQABAAAAAAQAAAAAAAAQAAAAAAAAIAAACIgjApIAjAqIAAACQAAAAAAAAQAAAAAAAAQAAAAgBAAQAAAAAAABg");
	this.shape_39.setTransform(-98.3,-0.7,0.749,0.749);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AgTAtQgIgBAAgBIgBgDIAAhPIAAgDIACgBIAVgCQAiAAAAAYIAAACQAAAGgDAFQgEAGgGACQAHABADAFQADAGAAAGIAAACQAAAagigBgAgRAjIAMABQANAAAFgEQAGgEAAgIIAAgCQAAgQgTAAIgRAAgAgRgFIARAAQASAAAAgOIAAgCQAAgHgFgEQgFgDgNAAIgMAAg");
	this.shape_40.setTransform(-104,-0.7,0.749,0.749);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AAaAtIgCgBIgIgdIgeAAIgIAcIgBABIgBABIgHAAQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAgBIABgBIAWhNQADgJAIAAQAKAAACAJIAXBNIAAABQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAgAANAGIgLgnIAAAAIgBgBIgBAAIgBABIgLAnIAZAAg");
	this.shape_41.setTransform(-112.5,-0.8,0.749,0.749);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("AAXAtIgCgBIgBgCIAAgoIgnAAIAAAoIgBACIgCABIgGAAIgCgBIgBgCIAAhUIABgBIACgBIAGAAIACABIABABIAAAjIAnAAIAAgjIABgBIACgBIAGAAIABABIABABIAABUIgBACIgBABg");
	this.shape_42.setTransform(-118.6,-0.7,0.749,0.749);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("AgCAtIgCgBIAAgCIAAhUQAAAAAAAAQAAgBAAAAQAAAAABAAQAAgBABAAIAFAAQABAAAAABQABAAAAAAQAAAAAAABQABAAAAAAIAABUIgBACIgCABg");
	this.shape_43.setTransform(-123.1,-0.7,0.749,0.749);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FFFFFF").s().p("AAbA0IgCgBIAAgCIAAgMIgrAAQgQAAgBgPIAAhHIABgBIACgBIAGAAIACABIAAABIAABHIABAEQABABAAAAQABAAAAAAQABABAAAAQABAAABAAIAdAAQABAAABAAQABAAAAgBQABAAAAAAQAAAAABgBQAAAAAAAAQAAAAAAgBQAAAAAAgBQABgBAAgBIAAhHIABgBIABgBIAGAAIACABIAAABIAABHIAAAGIAGAAQABAAAAAAQABAAAAAAQAAABAAAAQABAAAAABIAAATIgBACIgCABg");
	this.shape_44.setTransform(-127.3,-0.2,0.749,0.749);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.urText, new cjs.Rectangle(-130,-4.1,260,8.4), null);


(lib.t2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AguBmQgPgCgCgDQgCgDgBgEIAAi0QABgDABgCIAEgEIARgCIAegBQBOABAAA0IAAAEQAAAPgHALQgIAMgOAEQAOAFAJAMQAIAMAAAPIAAAEQgBA5hOABgAgoBQIAcABQAcABANgJQAMgJAAgTIAAgEQABgjgpAAIgpAAgAgohQIAABDIApAAQAoAAAAggIAAgEQAAgRgMgHQgMgIgeAAg");
	this.shape.setTransform(100.4,13.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgGBlQgBAAAAAAQgBAAAAgBQgBAAAAAAQgBAAAAgBQAAAAgBgBQAAAAAAAAQAAgBAAgBQgBAAAAgBIAAi9QAAgGAGAAIANAAQAGAAAAAGIAAC9QAAABgBAAQAAABAAABQAAAAAAAAQgBABAAAAQAAABgBAAQAAAAgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_1.setTransform(87.4,13.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AA0BlQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAAAgBgBQAAAAAAgBQgBAAAAAAQAAgBAAgBQAAAAAAgBIAAhaIhcAAIAABaQAAABAAAAQAAABgBAAQAAABAAAAQgBABAAAAQgBABAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAIgOAAQAAAAgBAAQAAAAgBgBQAAAAgBAAQAAAAgBgBQAAAAAAgBQgBAAAAAAQAAgBAAgBQAAAAAAgBIAAi9QAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAAAgBQABAAAAAAQABAAAAgBQABAAAAAAIAOAAQABAAAAAAQABABAAAAQABAAAAAAQAAABABAAIACAEIAABOIBcAAIAAhOQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAAAgBQAAAAABAAQAAAAABgBQAAAAABAAIAOAAQAAAAABAAQAAABABAAQABAAAAAAQAAABABAAQAAABAAAAQABAAAAABQAAAAAAABQAAAAAAABIAAC9QAAABAAAAQAAABAAABQAAAAgBAAQAAABAAAAQgBABAAAAQAAAAgBAAQgBABAAAAQgBAAAAAAg");
	this.shape_2.setTransform(73.8,13.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("ABCB2QAAAAAAAAQgBAAAAgBQgBAAAAAAQgBAAAAgBQAAAAgBgBQAAAAAAAAQAAgBAAgBQAAAAAAgBIAAgbIh7AAIAAAbQAAABAAAAQAAABAAABQAAAAAAAAQgBABAAAAQAAABgBAAQAAAAgBAAQAAABgBAAQAAAAAAAAIgQAAQAAAAAAAAQgBAAAAgBQgBAAAAAAQgBAAAAgBQAAAAgBgBQAAAAAAAAQAAgBAAgBQgBAAAAgBIAAgsQABgFAEAAIAJAAIAuifQAFgVAVAAQAWAAAGAUIAtCgIAIAAQAFAAABAFIAAAsQAAABgBAAQAAABAAABQAAAAAAAAQgBABAAAAQAAABgBAAQAAAAgBAAQAAABgBAAQAAAAgBAAgAAwA/IgqiaQgBgEgFAAQgCAAgCAEIgqCaIBeAAg");
	this.shape_3.setTransform(54.6,14.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AA3BlQgBAAgBAAQgBAAAAgBQgBAAAAAAQgBgBAAAAIgyhRIgzBSIgEABIgPAAQgFAAAAgEIABgDIA8hfIg8hcIAAgDQAAgEAEAAIASAAIACABIAzBPIAvhOIACgBIADgBIAQAAQAEAAAAAFIAAACIg7BdIA9BeQAAAAAAABQABAAAAAAQAAAAAAABQAAAAAAABQAAAEgEAAg");
	this.shape_4.setTransform(28.5,13.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AA0BlQAAAAgBAAQAAAAgBgBQAAAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAAAQgBgBAAAAQAAgBAAAAIAAieIgBAAIhTCeQgCAFgHAAIgQAAQgEAAgCgDQgCgCAAgDIAAi7QAAgGAFAAIAOAAQAAAAABAAQAAABABAAQAAAAAAAAQABABAAAAQABABAAAAQAAAAAAABQABAAAAABQAAAAAAABIAACdIAAABIBTieQACgDACgBQACgCAFAAIAPAAQADAAADADQACACAAADIAAC9QAAAEgFAAg");
	this.shape_5.setTransform(9.7,13.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ag6BmQAAAAgBgBQAAAAgBAAQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAgBIAAi8QAAgDACgCQADgCASgBIAdAAQBLAAAAA6IAAAEQAAA7hLABIgbgCIAABMQAAABAAAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAAAAAQgBAAAAAAQgBABAAAAgAgmhPIAABPIAbAAQAaAAAMgIQAMgIAAgWIAAgEQAAgUgMgJQgMgJgaAAQgOAAgNABg");
	this.shape_6.setTransform(-7.7,13);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhCBgIAAgNQAAgEAGAAIARABQAJAAAFgDQAGgDACgGQAFgJAKgcIgBAAQgHAAgGgEQgDgEgDgIIgqhtIAAgDQAAgEAEAAIAQAAQAEAAACAEIAmBlQAAABAAAAQABABAAAAQAAABAAAAQABABAAAAIADABIABAAIAphqQACgEADAAIARAAQAFAAgBAEIAAADIg8CaQgKAagLAIQgLAIgUAAQgXAAAAgGg");
	this.shape_7.setTransform(-24.6,13.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AA/BlIgDgCQgBAAAAgBQAAAAgBAAQAAgBAAgBQAAAAAAgBIAAigIgBAAIgpBTIgDADIgHABIgMAAQgEAAgCgBQgDgCgDgEIgnhQIAAABIAACfQAAABgBAAQAAABAAABQAAAAAAAAQgBABAAAAQAAABgBAAQAAAAgBAAQAAABgBAAQAAAAgBAAIgNAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQgBAAAAgBQAAAAgBgBQAAAAAAAAQAAgBAAgBQAAAAgBgBIAAi7QABgDACgCQADgDADAAIARAAQAHAAACAFIAtBdQAAABAAAAQABABAAAAQABAAAAAAQAAAAAAAAQABAAAAAAQAAAAABAAQAAAAAAgBQABAAAAgBIAthdQACgFAGAAIASAAQADAAADADQACACAAADIAAC7QAAABAAAAQAAABAAAAQAAABgBAAQAAABgBAAQAAABAAAAQgBAAAAAAQgBABAAAAQgBAAAAAAg");
	this.shape_8.setTransform(-43.9,13.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AA2BlQAAAAgBAAQgBAAAAgBQgBAAAAAAQgBgBAAAAIgyhRIgzBSIgEABIgQAAQgEAAAAgEIABgDIA9hfIg9hcIAAgDQAAgEAEAAIARAAIAEABIAxBPIAwhOIACgBIADgBIAQAAQAEAAAAAFIgBACIg6BdIA9BeIABADQAAAEgFAAg");
	this.shape_9.setTransform(-63.6,13.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ag1BQQgUgVABgqIAAgiQAAgqATgWQAUgUAhgBQAjAAAUAWQASAWAAApIAAAiQAAAqgSAVQgUAXgjAAQgiAAgTgXgAgvgRIAAAiQAAA/AvAAQAwAAAAg/IAAgiQAAg+gwgBQgvABAAA+g");
	this.shape_10.setTransform(-81,13.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AA0BlQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAAAgBgBQAAAAAAgBQgBAAAAAAQAAgBAAgBQAAAAAAgBIAAihQAAgGgDgDQgBgCgJAAIhDAAQgIAAgCACQgCACAAAHIAAChQAAABAAAAQAAABgBABQAAAAAAAAQgBABAAAAQgBABAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAIgOAAIgEgCQAAAAAAgBQgBAAAAAAQAAgBAAgBQAAAAAAgBIAAihQAAgiAlAAIBDAAQAlAAAAAiIAAChQAAABAAAAQAAABAAABQAAAAgBAAQAAABAAAAQgBABAAAAQAAAAgBAAQgBABAAAAQgBAAAAAAg");
	this.shape_11.setTransform(-99.9,13.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgtBgQgOgNAAgcIAAhtQAAgcAPgNQAPgNAeAAIAdAAIAUABQAIAAABABQAAAAAAAAQAAAAABABQAAAAAAAAQAAAAAAABIAAACIAAAOQAAABAAABQAAAAgBABQAAAAAAABQgBAAgBAAIg4AAQgRAAgJAEQgIAGAAAUIAAAoIBYAAQAAAAABAAQABAAAAAAQABAAAAABQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABQAAABAAAAIAAAKQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAQgBABAAAAQgBAAAAABQgBAAAAAAQgBAAAAAAIhYAAIAAAwQAAARAHAHQAHAGAUAAIA4AAQABAAABAAQAAABAAAAQABABAAAAQAAABAAABIAAAPIgBADQgBABgRABIgoAAQgeAAgQgNg");
	this.shape_12.setTransform(100.2,-15.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AhIBrQgoAAAAgkIAAirQAAgBABAAQAAgBAAAAQAAgBABAAQAAgBAAAAQABgBAAAAQABgBAAAAQABAAAAAAQABAAABAAIAOAAQABAAAAAAQABAAAAAAQABAAAAABQABAAAAABQABAAAAABQAAAAABABQAAAAAAABQAAAAAAABIAACrQAAAIACACQACADAJAAIA8AAIAAi4QAAgBAAAAQAAgBAAAAQABgBAAAAQAAgBAAAAQABgBAAAAQABgBAAAAQABAAAAAAQABAAABAAIAOAAQAAAAABAAQAAAAABAAQAAAAABABQAAAAAAABQABAAAAABQAAAAABABQAAAAAAABQAAAAAAABIAAC4IA8AAQAIAAADgDQACgCAAgIIAAirQAAgBAAAAQAAgBABAAQAAgBAAAAQABgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAQAAAAABAAIAPAAQAAAAABAAQAAAAABAAQAAAAABABQAAAAABABQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAABIAACrQAAAkgnAAg");
	this.shape_13.setTransform(77.7,-15.5);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AA3BrQgBAAAAAAQAAAAgBAAQAAgBgBAAQAAAAgBgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQgBAAAAgBIAAhfIhiAAIAABfQAAABAAAAQAAABAAAAQAAABAAAAQgBABAAAAQgBABAAAAQgBAAAAABQgBAAAAAAQgBAAgBAAIgOAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQgBAAAAgBQAAAAgBgBQAAAAAAgBQgBAAAAgBQAAAAAAgBIAAjJQAAgBAAAAQAAgBABAAQAAgBAAAAQABgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAQAAAAABAAIAOAAQABAAABAAQAAAAABAAQAAAAABABQAAAAABABQAAAAABABQAAAAAAABQAAAAAAABQAAAAAAABIAABTIBiAAIAAhTQAAgBABAAQAAgBAAAAQAAgBAAAAQABgBAAAAQABgBAAAAQABgBAAAAQABAAAAAAQAAAAABAAIAPAAQABAAAAAAQABAAAAAAQABAAAAABQABAAAAABQAAAAABABQAAAAAAABQABAAAAABQAAAAAAABIAADJQAAABAAAAQAAABgBAAQAAABAAAAQgBABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAQAAAAgBAAg");
	this.shape_14.setTransform(53.6,-15.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgtBgQgOgNAAgcIAAhtQAAgcAPgNQAQgNAdAAIAdAAIAUABQAIAAABABQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIABACIAAAOQAAABgBABQAAAAAAABQgBAAAAABQgBAAAAAAIg5AAQgRAAgJAEQgIAFAAAVIAAAoIBYAAQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABQAAABABAAIAAAKQgBABAAAAQAAABAAAAQAAABAAAAQgBABAAAAQgBABAAAAQgBAAAAABQgBAAAAAAQAAAAgBAAIhYAAIAAAwQAAASAGAGQAIAGAUAAIA5AAQAAAAABAAQAAABABAAQAAABAAAAQABABAAABIAAAPQgBAAAAABQAAAAAAABQAAAAAAAAQgBABAAAAQgBABgRABIgoAAQgeAAgQgNg");
	this.shape_15.setTransform(35.4,-15.5);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("ABEBrQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAAAgBgBQAAAAAAgBQAAAAgBgBQAAAAAAgBQAAAAAAgBIAAiqIAAgBIgtBZIgDADQgDACgEAAIgNAAQgFAAgDgCIgFgGIgqhWIAAABIAACqQAAABAAAAQAAABAAAAQgBABAAAAQAAABgBAAQAAABgBAAQAAAAgBABQAAAAgBAAQAAAAgBAAIgOAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQgBAAAAgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQgBAAAAgBIAAjHQAAgDADgDQACgCADAAIATAAQAHAAACAFIAxBjQAAABAAAAQABABAAAAQABAAAAAAQAAAAAAAAQABAAAAAAQAAAAABAAQAAAAABgBQAAAAAAgBIAwhjQACgFAIAAIASAAQAEAAACACQACAEABACIAADHQAAABgBAAQAAABAAAAQAAABAAAAQgBABAAAAQgBABAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAg");
	this.shape_16.setTransform(15.4,-15.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAhBfQgKgLAAgXIAAgaQAAgXAKgLQAKgLATAAQASAAAKAKQAKANAAAWIAAAaQAAAWgKAMQgKAMgSAAQgTAAgKgMgAApAjIAAAaQAAAeAVAAQAUAAAAgeIAAgaQAAgegUAAQgVAAAAAegAhEBqQAAAAgBAAQAAAAgBAAQAAgBAAAAQAAgBAAAAIABgDIB1jIQADgFAEAAIAOAAQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIgBADIh1DIQgEAFgDAAgAhZAAQgKgLAAgXIAAgaQAAgYAKgKQAKgMASAAQAmAAAAAuIAAAaQAAAXgJALQgKALgTAAQgSAAgKgLgAhRg8IAAAaQAAAdAUABQAVgBAAgdIAAgaQAAgegVAAQgUAAAAAeg");
	this.shape_17.setTransform(-15.3,-15.2);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgqBoIgSgEQgDgBAAgEIAAgKQAAgEAFgBIABAAQAYAFAaAAQAtAAAAgtIAAgEQAAgVgOgJQgOgHgeAAIgiAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAgBgBIgBgDIAIhgIACgBIAEgCIBgAAQAGAAAAAFIAAANQAAAEgGAAIhQAAIgFA9IAOAAQAsAAAUAOQAUANAAAfIAAAEQAAAggTAQQgTASghAAQgSAAgRgCg");
	this.shape_18.setTransform(-35.8,-15.1);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgnBpIgRgEQgDgCAAgDIAAgKQAAgFAFAAIARADQAMACAVAAQAWAAANgMQAMgLAAgoIAAgDQgXAFgTAAQghAAgSgOQgSgPAAgdIAAgCQAAghASgTQASgTAgAAQAiAAARAVQASAUAAAnIAAAxQAAAqgSAVQgSAVglAAQgTAAgQgCgAgghJQgKANAAAZIAAACQAAAWAMAIQANAIARAAQAXAAAUgFIABgcQAAgdgKgOQgKgOgYAAQgVAAgLAMg");
	this.shape_19.setTransform(-53.9,-15.2);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AA8BqIgDgBQgCgCgCgJIgQg6IhJAAIgSBCIgCADIgDABIgRAAQgEAAAAgEIAAgDIA0i2QAGgWAWAAQAXAAAGAWIA0C2IAAADQAAAEgEAAgAAfAPIgaheIgBgCIgBgBIgDAAIgCAAIgBACIgbBfIA9AAg");
	this.shape_20.setTransform(-79.6,-15.3);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AA2BpQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBgBAAQAAAAgBgBQAAAAAAgBQAAAAgBgBQAAAAAAgBIAAheIhgAAIAABeQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAQgBAAAAABQgBAAAAAAQgBABAAAAQgBAAAAAAIgPAAQAAAAgBAAQAAAAgBgBQAAAAgBAAQAAgBgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBIAAjGIABgDQABgBAAAAQABAAAAgBQABAAAAAAQABAAAAAAIAPAAQAAAAABAAQAAAAABAAQAAABABAAQAAAAABABIABADIAABSIBgAAIAAhSQAAAAAAgBQABAAAAgBQAAAAAAgBQABAAAAAAQABgBAAAAQAAAAABgBQAAAAABAAQAAAAABAAIAOAAQABAAAAAAQABAAAAAAQABABAAAAQABAAAAABQABAAAAAAQABABAAAAQAAABAAAAQAAABAAAAIAADGQAAABAAAAQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBABQAAAAgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_21.setTransform(-98.9,-15.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.t2, new cjs.Rectangle(-107,-26.4,214.1,52.8), null);


(lib.t1_2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAZAvIgCgBIgBgCIAAgqIgrAAIAAAqIgBACIgCABIgGAAIgCgBIgBgCIAAhXIABgCIACgBIAGAAIACABIABACIAAAkIArAAIAAgkIABgCIACgBIAGAAIACABIABACIAABXIgBACIgCABg");
	this.shape.setTransform(52.9,17.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgbAvIgCAAIAAgCIAAhXIABgDQABgBAIAAIAOAAQAjAAAAAbIAAACQAAAbgjAAIgNgBIAAAkIAAACIgCAAgAgSgkIAAAkIANAAQAMAAAGgDQAGgEAAgKIAAgCQAAgJgGgEQgFgFgNAAg");
	this.shape_1.setTransform(44.3,17.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgXAvIgCAAIgBgCIAAhEQAAgMAHgGQAHgFANAAIANAAQAMAAABABIAAABIAAAGQAAABAAAAQAAAAAAABQgBAAAAAAQAAAAAAAAIgZAAQgIAAgEACQgDACAAAJIAABEIgBACIgBAAg");
	this.shape_2.setTransform(36.4,17.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgxB+QgQgCgFgCQgEgCAAgDIAAgOQAAgFAIAAIAUADQAPACAaAAQAcAAAPgOQAPgOABgvIAAgFQghAIgUgBQgpAAgWgSQgWgRAAgjIAAgCQAAgqAWgWQAWgWAoAAQAqAAAVAYQAWAZAAAwIAAA7QAAAzgWAZQgWAZguAAQgZAAgTgDgAgohYQgMAPAAAfIAAACQAAAZAOALQAQAKAXAAQAXABAdgHIABgiQAAgjgNgRQgMgRgcAAQgbAAgOAPg");
	this.shape_3.setTransform(20.1,9.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhHB/QgGAAAAgGIAAgPQAAgGAGAAIA4AAIAAjBIg5AXIgCAAQgBAAgBAAQAAgBgBAAQAAgBAAAAQAAgBAAgBIAAgRIAAgDIA7gbIAOgFIANAAQABAAAAAAQABAAAAABQABAAAAAAQABABABAAQAAABAAAAQABABAAAAQAAABAAABQAAAAAAABIAADbIA4AAQAIAAgBAGIAAAPQABAGgIAAg");
	this.shape_4.setTransform(-2.7,9.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("Ag0B+QgTgDgDgCQgDgCAAgEIAAgNQAAgEAFAAIACAAQAcAEAgAAQA4AAAAg2IAAgEQAAgZgQgLQgQgJgoAAIgpAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAgBgBQAAAAAAgBQAAgBAAAAIAAAAIAKh0IACgCQABgBAAAAQABAAAAgBQABAAABAAQAAAAABAAIB3AAQAHAAAAAGIAAAPQAAAGgHAAIhjAAIgGBJIAQAAQA3AAAZASQAYAPAAAmIAAAEQAAAngXAUQgXAVgqAAQgVAAgVgCg");
	this.shape_5.setTransform(-25.3,9.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AhGB/QgIAAABgGIAAgPQgBgGAIAAIA3AAIAAjBIg5AXIgCAAQgBAAgBAAQAAgBgBAAQAAgBAAAAQAAgBAAgBIAAgRIAAgDIA7gbIAOgFIANAAQABAAAAAAQABAAAAABQABAAAAAAQABABAAAAQABABAAAAQABABAAAAQAAABAAABQAAAAAAABIAADbIA4AAQAIAAgBAGIAAAPQABAGgIAAg");
	this.shape_6.setTransform(-48.4,9.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhoBXQgDgIAGgEIASgKIAegUQAPgLAJgNQAEgHABgEQgIgDgLgGQgXgLgRgRQgUgVgOgLQgQgLgQgEQgUgGAuACQAtACAbAJQAYAIAPAHIARAJQAIADAIgPIALgWQAEgJAEgDQAHgFANAAQAKAAAJAGQAJAGAEAAIAtACQANAAAEACQABAAAAABQABAAAAAAQAAAAAAABQAAAAAAAAQgxgBgKADQgIADgEADQgFAEgFAKQgDAFgEAVQgEAUgHAKQgJAOgXAPQgTAMgXAKQgcAMg3AeIgEgIg");
	this.shape_7.setTransform(-68.2,-13.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1_2, new cjs.Rectangle(-83.8,-22.7,140.1,45.4), null);


(lib.t1_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ag9BrQgqAAgSgVQgQgSAAgqIAAgzQAAgqAQgTQASgTAqgBIB7AAQAqABASATQAQATAAAqIAAAzQAAAqgQASQgSAVgqAAgAhdhEQgPALAAAaIAAA/QAAAtAzAAIBzAAQAYAAAMgJQAPgKAAgaIAAg/QAAgagPgLQgMgJgYAAIhzAAQgYAAgMAJg");
	this.shape.setTransform(91.8,-11.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgvBrQgnAAgSgSQgQgSAAgmIAAhBQAAgmAQgRQASgTAnAAIBoAAQBAAAAAA0IAAAFQAAAGgEAEQgFADgGABQgPAAAAgOIAAgCQgBgQgLgFQgIgFgXAAIhbAAQgwAAAAAsIAABEQAAAsAwAAIBbAAQAWAAAJgFQALgGABgQIAAgCQAAgNAPAAQAPAAAAAMIAAAHQAAAyhAABg");
	this.shape_1.setTransform(60.1,-11.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgwBrQgnAAgRgSQgQgSAAgmIAAhBQAAgmAQgRQARgTAnAAIBpAAQBAAAAAA0IAAAFQAAAGgFAEQgEADgGABQgOAAAAgOIAAgCQgCgQgLgFQgJgFgVAAIhcAAQgxAAAAAsIAABEQAAAsAxAAIBcAAQAVAAAJgFQALgGACgQIAAgCQAAgNAOAAQAGAAAEADQAFAEAAAFIAAAHQAAAyhAABg");
	this.shape_2.setTransform(30.3,-11.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("ABfBkIgVgpIiTAAIgVApQgFAGgGAAQgFAAgDgCQgFgDgDgFIAAgEIABgGIBli2QAFgJAOAAQAOAAAGAJIBlC2QABACAAAEIAAAEQgDAFgFADQgDACgFAAQgGAAgFgGgAA6AeIg6hnIg5BnIBzAAg");
	this.shape_3.setTransform(1,-11.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhnBrQgHAAgEgEQgEgEAAgGIAAi5QAAgGAEgEQAEgEAHAAICaAAQAZABANAHIAFADQAPAMAAAiQAAApgXADQAWABAHAPQAEAKAAAiQAAARgEAJQgDAJgIAGIgGADQgMAIgaAAgAhZBPICPAAQATAAAHgFQALgHgBgSIAAgLQAAgdgiAAIiRAAgAhZgQICHAAQAjAAAAgdIAAgFQAAgRgKgHQgIgFgTAAIiFAAg");
	this.shape_4.setTransform(-28.4,-11.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("Ag8BrQgrAAgSgVQgQgSgBgqIAAgzQABgpAQgUQASgTArgBIB6AAQAqABASATQARATAAAqIAAAzQAAAqgRASQgSAVgqAAgAhdhEQgOALAAAaIAAA/QAAAaAOAKQAMAJAYAAIBzAAQAYAAAMgJQAPgKAAgaIAAg/QAAgagPgLQgMgJgYAAIhzAAQgYAAgMAJg");
	this.shape_5.setTransform(-60.9,-11.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgJBmQgFgDAAgHIAAinIhgAAQgFAAgEgEQgDgEgBgHQAAgHAEgFQAEgEAGAAIDbAAQAGAAAEAEQADAFAAAHQAAAPgMAAIhgAAIAACoQAAAGgEAEQgFAEgFAAQgHAAgDgFg");
	this.shape_6.setTransform(-93.2,-11.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAcAtIgBgBIgBgCIAAhHIAAAAIAAAAIgSAkQAAABgBAAQAAAAAAABQAAAAgBAAQAAAAAAAAIgDABIgFAAIgDgBIgCgDIgRgjIgBAAIAABHIgBACIgBABIgGAAIgCgBIgBgCIAAhSIABgDIADgBIAIAAQABAAAAAAQABAAABABQAAAAAAAAQABAAAAABIAUApIAAABIACgBIAUgpQAAgBAAAAQAAAAABAAQAAgBABAAQABAAAAAAIAIAAIADABIABADIAABSIgBACIgCABg");
	this.shape_7.setTransform(47.8,17.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAAAuQgMAAgGgGQgGgFAAgMIAAgtQAAgMAGgFQAHgGALAAIANAAQALAAABABIAAACIAAAGQAAAAAAAAQAAABAAAAQAAAAgBAAQAAAAAAAAIgXAAQgIAAgDACQgDACAAAJIAAARIAkAAIACAAIAAACIAAAEIAAABIgCABIgkAAIAAAUQAAAIADACQACADAJAAIAXAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAIAAAHIAAABQgBABgHAAg");
	this.shape_8.setTransform(39.4,17.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgCAtIgCgBIAAgCIAAhNIgYAAQgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAgFIAAgCIACAAIA5AAQABAAAAAAQABAAAAABQAAAAAAAAQABAAAAABIAAAFQAAABgBAAQAAABAAAAQAAAAgBAAQAAAAgBAAIgXAAIAABNIgBACIgBABg");
	this.shape_9.setTransform(32.3,17.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgQAtIgHgBIgBgCIAAgFQAAAAAAgBQAAAAAAAAQABAAAAgBQABAAAAAAIAUABQAJAAAEgDQAFgEAAgHQAAgFgDgDIgMgJIgMgGQgGgFgFgFQgEgGAAgGQAAgWAcAAIANABIAJABQAAAAAAAAQAAAAABABQAAAAAAAAQAAAAAAABIAAAFQAAAAAAABQAAAAgBAAQAAAAAAABQgBAAAAAAIgVgBQgIAAgFADQgEADAAAGQAAAEADADIAJAHIALAHQAMAGADAFQAEAFAAAIQAAAIgDAFQgDAFgHADQgIADgIAAg");
	this.shape_10.setTransform(24.8,17.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgDAtIgBgBIAAgCIAAgiQgEgCgEgGIgSgpIAAgBQAAgBAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIAHAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIARAnQAAABABAAQAAABABAAQAAABAAAAQAAAAAAAAQAAAAABAAQAAAAAAgBQAAAAABgBQAAAAABgBIARgnIACgCIAHAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAAABIgTApQgDAGgEACIAAAiIgBACIgBABg");
	this.shape_11.setTransform(17.8,17.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgQAtIgHgBIgBgCIAAgFQAAAAAAgBQAAAAAAAAQABAAAAgBQAAAAABAAIAUABQAJAAAEgDQAFgEAAgHQAAgFgDgDIgMgJIgMgGQgIgFgEgFQgDgFAAgHQAAgWAcAAIANABIAJABQAAAAAAAAQAAAAAAABQABAAAAAAQAAAAAAABIAAAFQAAAAAAABQgBAAAAAAQAAAAAAABQgBAAAAAAIgVgBQgJAAgEADQgEADAAAGQAAAEADADIAJAHIALAHQALAGAEAFQAEAFAAAIQAAAIgDAFQgDAFgHADQgIADgIAAg");
	this.shape_12.setTransform(10.3,17.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgTAkQgJgJAAgTIAAgPQAAgTAJgJQAJgKANAAIARABIAIABIABACIAAAGQAAAAAAAAQAAAAgBAAQAAABAAAAQgBAAAAAAIgYgBQgUAAAAAcIAAAPQAAAPAGAGQAFAHAIAAIAQgBIAAgiQAAgBAAAAQAAAAAAAAQABAAAAgBQAAAAABAAIAGAAIACABIABABIAAAoIgBADIgJABIgRABQgMAAgJgKg");
	this.shape_13.setTransform(-1.1,17.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AAUAtQAAAAgBAAQAAAAgBAAQAAgBAAAAQgBAAAAgBIgkhGIgBgBIAABGIgBACIgCABIgFAAQgBAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAgBIAAhUIABgCIADgBIAGAAIAEAAIABACIAlBHIAAhHIAAgCIACAAIAGAAQABAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAABTIgBADIgCABg");
	this.shape_14.setTransform(-9.4,17.7);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgCAtIgCgBIAAgCIAAhUQAAgBAAAAQAAAAAAAAQAAgBABAAQAAAAABAAIAGAAQAAAAAAAAQABAAAAABQAAAAAAAAQABAAAAABIAABUIgBACIgBABg");
	this.shape_15.setTransform(-15.7,17.7);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgDAtIgBgBIgBgCIAAhNIgXAAQgBAAAAAAQgBAAAAAAQAAAAAAgBQgBAAAAgBIAAgFIABgCIACAAIA5AAQABAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAFQAAABAAAAQAAABAAAAQAAAAgBAAQAAAAgBAAIgYAAIAABNIgBACQAAAAAAAAQAAABAAAAQAAAAAAAAQgBAAAAAAg");
	this.shape_16.setTransform(-21.1,17.7);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAZAuIgBgBIgCgFIgHgYIgdAAIgIAcIgBABIgBABIgHAAQgBAAgBgBQAAAAAAAAQgBAAAAgBQAAAAAAAAIABgBIAVhOQADgKAJABQAKgBADAKIAVBOIABABQAAAAAAAAQAAABAAAAQgBAAAAAAQAAABgBAAgAANAGIgLgnIAAgBIgCgBIgBABIgLAoIAZAAg");
	this.shape_17.setTransform(-27.7,17.7);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAAAuQgMAAgGgGQgGgFAAgMIAAgtQAAgMAGgFQAHgGALAAIANAAQALAAABABIAAACIAAAGQAAAAAAAAQAAABAAAAQAAAAgBAAQAAAAAAAAIgXAAQgIAAgDACQgDACAAAJIAAARIAkAAIACAAIAAACIAAAEIAAABIgCABIgkAAIAAAUQAAAIADACQACADAJAAIAXAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAIAAAHIAAABQgBABgHAAg");
	this.shape_18.setTransform(-35.3,17.7);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AAXAtIgCgBIAAgCIAAgoIgpAAIAAAoIAAACIgCABIgGAAIgCgBIgBgCIAAhUIABgCIACAAIAGAAIACAAIAAACIAAAkIApAAIAAgkIAAgCIACAAIAGAAIACAAIABACIAABUIgBACIgCABg");
	this.shape_19.setTransform(-43.5,17.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1_1, new cjs.Rectangle(-105.5,-22.2,211.2,44.5), null);


(lib.prod_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.prod();
	this.instance.parent = this;
	this.instance.setTransform(-124,-150);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.prod_1, new cjs.Rectangle(-124,-150,247,300), null);


(lib.gradient1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#0A7BD7","#68D2AE"],[0,1],0,49.7,0,-49.6).s().p("A29HqIAAvTMAt7AAAIAAPTg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.gradient1, new cjs.Rectangle(-147,-49,294.1,98), null);


(lib.drops2_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.drops2();
	this.instance.parent = this;
	this.instance.setTransform(-150,-271);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.drops2_1, new cjs.Rectangle(-150,-271,300,541), null);


(lib.drops1_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.drops1();
	this.instance.parent = this;
	this.instance.setTransform(-150,-271);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.drops1_1, new cjs.Rectangle(-150,-271,300,541), null);


(lib.cover = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("A3bEiIAApDMAu3AAAIAAJDg");
	this.shape.setTransform(0,321);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("EgAiAu4MAAAhdvIBFAAMAAABdvg");
	this.shape_1.setTransform(146.5,50);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("EgAiAu4MAAAhdvIBFAAMAAABdvg");
	this.shape_2.setTransform(-146.5,50);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("A3bAjIAAhFMAu3AAAIAABFg");
	this.shape_3.setTransform(0,-246.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.cover, new cjs.Rectangle(-150,-250,300,600), null);


(lib.bgImg3_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.bgImg3();
	this.instance.parent = this;
	this.instance.setTransform(-150,-271);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bgImg3_1, new cjs.Rectangle(-150,-271,300,541), null);


(lib.bgImg2_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.bgImg2();
	this.instance.parent = this;
	this.instance.setTransform(-150,-270);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bgImg2_1, new cjs.Rectangle(-150,-270,300,541), null);


(lib.bgImg1_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.bgImg1();
	this.instance.parent = this;
	this.instance.setTransform(-150,-271);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bgImg1_1, new cjs.Rectangle(-150,-271,300,541), null);


(lib.bg2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#0A7BD7","#68D2AE"],[0,1],0,298.8,0,-298.7).s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.bg2, new cjs.Rectangle(-150,-300,300,600), null);


(lib.bg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.bg, new cjs.Rectangle(-150,-300,300,600), null);


(lib.logos = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AIsCLIgsgrIiRAAQgjAAgXgFQgdgHgRgQQgXgXAAgrIAAh9QAAgIAFgFQAGgFAJAAIChAAQAiAAAXAFQAdAHARAQQAYAWAAAsIAAB7IAkAkQAFAGAAAHQAAAHgHAGQgGAHgHAAIgBAAQgHAAgFgGgAEZACQAAAeAPAOIADADQAPAMAgABIChAAIAAhtQgBgfgOgOIgDgCQgQgMgfgBIihAAgAylByQgEgLAHgEIAXgOIAlgYQATgOALgQQAFgJABgFQgKgEgOgHQgcgPgVgVQgZgagSgNQgUgPgUgFQgZgHA5ADQA5ADAiALQAeAJASAJIAXAMQAKADAKgSQAGgKAHgSQAGgLAFgEQAJgHAPAAQANAAALAIQAMAIAEAAIA5ACQAQAAAFADQABAAAAABQABAAAAAAQAAABAAAAQAAAAAAABQg8gCgNAEQgKADgFAEQgGAFgGAMQgEAHgFAbQgFAZgJAMQgMARgcATQgYAQgeAMQgjAOhEAnIgFgKgACMBYQgFgFAAgJIAAjFQAAgKAFgFQAFgFAJAAQAJAAAGAFQAFAFAAAKIAADFQAAAJgFAFQgGAFgJAAQgJAAgFgFgALeBdQg6AAgdgQQgogWAAg3IAAgyQAAg4AogWQAdgQA6AAIA2AAQA6AAAdAQQAoAWAAA4IAAAyQAAA3goAWQgdAQg6AAgAKchjQgVAPAAAkIAAAuQAAAjAVAOQARAMAlAAIBOAAQAlAAARgMQAVgOAAgjIAAguQAAgkgVgPQgRgLglAAIhOAAQglAAgRALgAQhBbQgugBgUgNQgQgKgDgTIAAgDQAAgHAFgFQAFgEAJAAQAIAAAFAEQAFADACAFIABADQAFAIALADQAJADASAAIBWABQAxAAANgHQAMgHAAgVIAAgCQAAgRgHgFQgLgJggAAIh1AAQgnAAgSgOQgRgPAAggIAAgOQAAgdAWgNQAagQBDAAIA6AAQA0AAAYANQASAKADAVIAAADQAAAHgFAFQgFAEgJAAQgIAAgFgEQgFgDgCgFIgBgDQgGgKgPgDQgKgCgcAAIhCAAQgoAAgNAGQgMAFAAATIAAAJQAAAPAIAGQAKAHAbAAIBkAAQAxAAATAKQAcAPAAApIAAABQAAAsglAOQgVAIgvAAg");

	// grad1
	this.instance = new lib.gradient1();
	this.instance.parent = this;
	this.instance.setTransform(-3.5,0,1.02,0.296,0,0,0,-0.1,-0.1);

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.logos, new cjs.Rectangle(-125.4,-14.4,251,29), null);


(lib.banner = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// logos
	this.logos = new lib.logos();
	this.logos.name = "logos";
	this.logos.parent = this;
	this.logos.setTransform(4.4,270.5);

	this.timeline.addTween(cjs.Tween.get(this.logos).wait(203));

	// cover
	this.instance = new lib.cover();
	this.instance.parent = this;
	this.instance.setTransform(0,-50);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(203));

	// t1_1
	this.instance_1 = new lib.t1_1();
	this.instance_1.parent = this;
	this.instance_1.setTransform(0,-214);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(46).to({_off:false},0).to({alpha:1},15).to({_off:true},66).wait(76));

	// bg
	this.instance_2 = new lib.bg2();
	this.instance_2.parent = this;
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.instance_3 = new lib.bg();
	this.instance_3.parent = this;
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(46).to({_off:false},0).to({alpha:1},15).to({_off:true},1).wait(141));
	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(117).to({_off:false},0).to({alpha:0.898},9).to({_off:true},1).wait(76));

	// bg
	this.instance_4 = new lib.bgImg3_1();
	this.instance_4.parent = this;
	this.instance_4.setTransform(0,-29);
	this.instance_4.alpha = 0.262;
	this.instance_4._off = true;

	this.instance_5 = new lib.bg();
	this.instance_5.parent = this;
	this.instance_5.compositeOperation = "lighter";
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(31).to({_off:false},0).to({alpha:1},15).to({_off:true},15).wait(142));
	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(127).to({_off:false},0).to({alpha:0},10).wait(45).to({alpha:1},10).to({alpha:0},10).wait(1));

	// t2
	this.instance_6 = new lib.t2();
	this.instance_6.parent = this;
	this.instance_6.setTransform(0,-222,0.02,0.02,0,0,0,0,-2.5);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(139).to({_off:false},0).to({regY:0,scaleX:1,scaleY:1},10,cjs.Ease.get(1)).to({_off:true},43).wait(11));

	// bgImg2
	this.instance_7 = new lib.bgImg2_1();
	this.instance_7.parent = this;
	this.instance_7.setTransform(0,-29);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(127).to({_off:false},0).to({_off:true},65).wait(11));

	// urText
	this.instance_8 = new lib.urText();
	this.instance_8.parent = this;
	this.instance_8.setTransform(0,231.9,1,0.999);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(61).to({_off:false},0).to({alpha:1},10).to({_off:true},56).wait(76));

	// t1_2
	this.instance_9 = new lib.t1_2();
	this.instance_9.parent = this;
	this.instance_9.setTransform(62.1,-80,0.02,0.02,0,0,0,2.5,-2.5);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(71).to({_off:false},0).to({regX:0,regY:0,scaleX:1,scaleY:1},10,cjs.Ease.get(1)).wait(8).to({scaleX:1.2,scaleY:1.2,y:-79.9},5).wait(10).to({scaleX:1,scaleY:1,y:-80},5).to({_off:true},18).wait(76));

	// prod
	this.instance_10 = new lib.prod_1();
	this.instance_10.parent = this;
	this.instance_10.setTransform(97,20,0.7,0.7,0,0,0,0.1,0.1);
	this.instance_10.alpha = 0;
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(61).to({_off:false},0).to({regX:0,regY:0,scaleX:1,scaleY:1,x:3,alpha:1},10,cjs.Ease.get(1)).to({_off:true},56).wait(76));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_14 = new cjs.Graphics().p("AFwcSMgY+g4GIFOiVMAY+A4GQgBENh3AAQhRAAiFh4g");
	var mask_graphics_15 = new cjs.Graphics().p("AF7cSMgY+g4GIFOiVMAY+A4GQAAENh4AAQhQAAiGh4g");
	var mask_graphics_16 = new cjs.Graphics().p("AGGcSMgY+g4GIFOiVMAY+A4GQAAENh4AAQhQAAiGh4g");
	var mask_graphics_17 = new cjs.Graphics().p("AGRcSMgY+g4GIFOiVMAY+A4GQAAENh4AAQhQAAiGh4g");
	var mask_graphics_18 = new cjs.Graphics().p("AGccSMgY+g4GIFOiVMAY+A4GQAAENh4AAQhQAAiGh4g");
	var mask_graphics_19 = new cjs.Graphics().p("AGocSMgY+g4GIFNiVMAY+A4GQAAENh4AAQhQAAiFh4g");
	var mask_graphics_20 = new cjs.Graphics().p("AGzcSMgY+g4GIFOiVMAY9A4GQAAENh4AAQhQAAiFh4g");
	var mask_graphics_21 = new cjs.Graphics().p("AG+cSMgY+g4GIFOiVMAY+A4GQgBENh3AAQhRAAiFh4g");
	var mask_graphics_22 = new cjs.Graphics().p("AHJcSMgY+g4GIFOiVMAY+A4GQAAENh4AAQhQAAiGh4g");
	var mask_graphics_23 = new cjs.Graphics().p("AHUcSMgY+g4GIFOiVMAY+A4GQAAENh4AAQhQAAiGh4g");
	var mask_graphics_24 = new cjs.Graphics().p("AHfcSMgY+g4GIFOiVMAY+A4GQAAENh4AAQhQAAiGh4g");
	var mask_graphics_25 = new cjs.Graphics().p("AHqcSMgY+g4GIFOiVMAY+A4GQAAENh4AAQhQAAiGh4g");
	var mask_graphics_26 = new cjs.Graphics().p("AH1cSMgY9g4GIFNiVMAY+A4GQAAENh4AAQhQAAiGh4g");
	var mask_graphics_27 = new cjs.Graphics().p("AIBcSMgY+g4GIFNiVMAY+A4GQAAENh4AAQhQAAiFh4g");
	var mask_graphics_28 = new cjs.Graphics().p("AIMcSMgY+g4GIFOiVMAY9A4GQAAENh4AAQhQAAiFh4g");
	var mask_graphics_29 = new cjs.Graphics().p("AIXcSMgY+g4GIFOiVMAY+A4GQgBENh3AAQhRAAiFh4g");
	var mask_graphics_30 = new cjs.Graphics().p("AIicSMgY+g4GIFOiVMAY+A4GQAAENh4AAQhQAAiGh4g");
	var mask_graphics_31 = new cjs.Graphics().p("AItcSMgY+g4GIFOiVMAY+A4GQAAENh4AAQhQAAiGh4g");
	var mask_graphics_32 = new cjs.Graphics().p("AI4cSMgY+g4GIFOiVMAY+A4GQAAENh4AAQhQAAiGh4g");
	var mask_graphics_33 = new cjs.Graphics().p("AJDcSMgY+g4GIFOiVMAY+A4GQAAENh4AAQhQAAiGh4g");
	var mask_graphics_34 = new cjs.Graphics().p("AJOcSMgY9g4GIFNiVMAY+A4GQAAENh4AAQhQAAiGh4g");
	var mask_graphics_35 = new cjs.Graphics().p("AJacSMgY+g4GIFNiVMAY+A4GQAAENh4AAQhQAAiFh4g");
	var mask_graphics_36 = new cjs.Graphics().p("AJlcSMgY+g4GIFOiVMAY+A4GQgBENh4AAQhQAAiFh4g");
	var mask_graphics_37 = new cjs.Graphics().p("AJwcSMgY+g4GIFOiVMAY+A4GQgBENh3AAQhRAAiFh4g");
	var mask_graphics_38 = new cjs.Graphics().p("AJ5cSMgY+g4GIFNiVMAY+A4GQAAENh4AAQhQAAiFh4g");
	var mask_graphics_39 = new cjs.Graphics().p("AJ5cSMgY+g4GIFNiVMAY+A4GQAAENh4AAQhQAAiFh4g");
	var mask_graphics_40 = new cjs.Graphics().p("AJ5cSMgY+g4GIFNiVMAY+A4GQAAENh4AAQhQAAiFh4g");
	var mask_graphics_41 = new cjs.Graphics().p("AJ5cSMgY+g4GIFNiVMAY+A4GQAAENh4AAQhQAAiFh4g");
	var mask_graphics_42 = new cjs.Graphics().p("AJ5cSMgY+g4GIFNiVMAY+A4GQAAENh4AAQhQAAiFh4g");
	var mask_graphics_43 = new cjs.Graphics().p("AJ5cSMgY+g4GIFNiVMAY+A4GQAAENh4AAQhQAAiFh4g");
	var mask_graphics_44 = new cjs.Graphics().p("AJ5cSMgY+g4GIFNiVMAY+A4GQAAENh4AAQhQAAiFh4g");
	var mask_graphics_45 = new cjs.Graphics().p("AJ5cSMgY+g4GIFNiVMAY+A4GQAAENh4AAQhQAAiFh4g");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(14).to({graphics:mask_graphics_14,x:-123.1,y:-174.4}).wait(1).to({graphics:mask_graphics_15,x:-122,y:-168.9}).wait(1).to({graphics:mask_graphics_16,x:-120.9,y:-163.4}).wait(1).to({graphics:mask_graphics_17,x:-119.8,y:-157.9}).wait(1).to({graphics:mask_graphics_18,x:-118.7,y:-152.4}).wait(1).to({graphics:mask_graphics_19,x:-117.5,y:-146.9}).wait(1).to({graphics:mask_graphics_20,x:-116.4,y:-141.5}).wait(1).to({graphics:mask_graphics_21,x:-115.3,y:-136}).wait(1).to({graphics:mask_graphics_22,x:-114.2,y:-130.5}).wait(1).to({graphics:mask_graphics_23,x:-113.1,y:-125}).wait(1).to({graphics:mask_graphics_24,x:-112,y:-119.5}).wait(1).to({graphics:mask_graphics_25,x:-110.9,y:-114}).wait(1).to({graphics:mask_graphics_26,x:-109.7,y:-108.6}).wait(1).to({graphics:mask_graphics_27,x:-108.6,y:-103.1}).wait(1).to({graphics:mask_graphics_28,x:-107.5,y:-97.6}).wait(1).to({graphics:mask_graphics_29,x:-106.4,y:-92.1}).wait(1).to({graphics:mask_graphics_30,x:-105.3,y:-86.6}).wait(1).to({graphics:mask_graphics_31,x:-104.2,y:-81.1}).wait(1).to({graphics:mask_graphics_32,x:-103.1,y:-75.6}).wait(1).to({graphics:mask_graphics_33,x:-102,y:-70.2}).wait(1).to({graphics:mask_graphics_34,x:-100.8,y:-64.7}).wait(1).to({graphics:mask_graphics_35,x:-99.7,y:-59.2}).wait(1).to({graphics:mask_graphics_36,x:-98.6,y:-53.7}).wait(1).to({graphics:mask_graphics_37,x:-97.5,y:-48.2}).wait(1).to({graphics:mask_graphics_38,x:-96.1,y:-42.7}).wait(1).to({graphics:mask_graphics_39,x:-93.9,y:-37.3}).wait(1).to({graphics:mask_graphics_40,x:-91.7,y:-31.8}).wait(1).to({graphics:mask_graphics_41,x:-89.5,y:-26.3}).wait(1).to({graphics:mask_graphics_42,x:-87.2,y:-20.8}).wait(1).to({graphics:mask_graphics_43,x:-85,y:-15.3}).wait(1).to({graphics:mask_graphics_44,x:-82.8,y:-9.8}).wait(1).to({graphics:mask_graphics_45,x:-80.6,y:-4.4}).wait(1).to({graphics:null,x:0,y:0}).wait(157));

	// drops
	this.instance_11 = new lib.drops2_1();
	this.instance_11.parent = this;
	this.instance_11.setTransform(0,-29);
	this.instance_11._off = true;

	var maskedShapeInstanceList = [this.instance_11];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(14).to({_off:false},0).to({_off:true},32).wait(157));

	// mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	var mask_1_graphics_9 = new cjs.Graphics().p("AHmcAMgaug3SIFJifMAauA3SQAIERh7AAQhQAAiGhyg");
	var mask_1_graphics_10 = new cjs.Graphics().p("AHrcAMgaug3SIFKifMAatA3SQAIERh7AAQhQAAiGhyg");
	var mask_1_graphics_11 = new cjs.Graphics().p("AHwcAMgatg3SIFJifMAatA3SQAIERh7AAQhQAAiGhyg");
	var mask_1_graphics_12 = new cjs.Graphics().p("AH1cAMgatg3SIFJifMAatA3SQAIERh7AAQhPAAiHhyg");
	var mask_1_graphics_13 = new cjs.Graphics().p("AH6cAMgatg3SIFJifMAatA3SQAJERh8AAQhPAAiHhyg");
	var mask_1_graphics_14 = new cjs.Graphics().p("AH/cAMgatg3SIFJifMAatA3SQAJERh8AAQhPAAiHhyg");
	var mask_1_graphics_15 = new cjs.Graphics().p("AIFcAMgaug3SIFJifMAauA3SQAIERh7AAQhQAAiGhyg");
	var mask_1_graphics_16 = new cjs.Graphics().p("AIKcAMgaug3SIFJifMAauA3SQAIERh7AAQhQAAiGhyg");
	var mask_1_graphics_17 = new cjs.Graphics().p("AIPcAMgaug3SIFJifMAauA3SQAIERh7AAQhQAAiGhyg");
	var mask_1_graphics_18 = new cjs.Graphics().p("AIUcAMgatg3SIFJifMAatA3SQAIERh7AAQhQAAiGhyg");
	var mask_1_graphics_19 = new cjs.Graphics().p("AIZcAMgatg3SIFJifMAatA3SQAIERh7AAQhPAAiHhyg");
	var mask_1_graphics_20 = new cjs.Graphics().p("AIecAMgatg3SIFJifMAatA3SQAJERh8AAQhPAAiHhyg");
	var mask_1_graphics_21 = new cjs.Graphics().p("AIjcAMgatg3SIFJifMAatA3SQAJERh8AAQhPAAiHhyg");
	var mask_1_graphics_22 = new cjs.Graphics().p("AIpcAMgaug3SIFJifMAauA3SQAIERh7AAQhQAAiGhyg");
	var mask_1_graphics_23 = new cjs.Graphics().p("AIucAMgaug3SIFJifMAauA3SQAIERh7AAQhQAAiGhyg");
	var mask_1_graphics_24 = new cjs.Graphics().p("AIzcAMgaug3SIFJifMAauA3SQAIERh7AAQhQAAiGhyg");
	var mask_1_graphics_25 = new cjs.Graphics().p("AI4cAMgatg3SIFJifMAatA3SQAIERh7AAQhQAAiGhyg");
	var mask_1_graphics_26 = new cjs.Graphics().p("AI9cAMgatg3SIFJifMAatA3SQAIERh7AAQhQAAiGhyg");
	var mask_1_graphics_27 = new cjs.Graphics().p("AJCcAMgatg3SIFJifMAatA3SQAJERh8AAQhPAAiHhyg");
	var mask_1_graphics_28 = new cjs.Graphics().p("AJHcAMgatg3SIFJifMAatA3SQAJERh8AAQhPAAiHhyg");
	var mask_1_graphics_29 = new cjs.Graphics().p("AJNcAMgaug3SIFJifMAauA3SQAIERh8AAQhPAAiGhyg");
	var mask_1_graphics_30 = new cjs.Graphics().p("AJScAMgaug3SIFJifMAauA3SQAIERh7AAQhQAAiGhyg");
	var mask_1_graphics_31 = new cjs.Graphics().p("AJXcAMgaug3SIFJifMAauA3SQAIERh7AAQhQAAiGhyg");
	var mask_1_graphics_32 = new cjs.Graphics().p("AJccAMgatg3SIFJifMAatA3SQAIERh7AAQhQAAiGhyg");
	var mask_1_graphics_33 = new cjs.Graphics().p("AJhcAMgatg3SIFJifMAatA3SQAIERh7AAQhQAAiGhyg");
	var mask_1_graphics_34 = new cjs.Graphics().p("AJmcAMgatg3SIFJifMAatA3SQAJERh8AAQhPAAiHhyg");
	var mask_1_graphics_35 = new cjs.Graphics().p("AJrcAMgatg3SIFJifMAatA3SQAJERh8AAQhPAAiHhyg");
	var mask_1_graphics_36 = new cjs.Graphics().p("AJwcAMgatg3SIFJifMAauA3SQAIERh8AAQhPAAiHhyg");
	var mask_1_graphics_37 = new cjs.Graphics().p("AJ2cAMgaug3SIFJifMAauA3SQAIERh7AAQhQAAiGhyg");
	var mask_1_graphics_38 = new cjs.Graphics().p("AJ7cAMgaug3SIFJifMAauA3SQAIERh7AAQhQAAiGhyg");
	var mask_1_graphics_39 = new cjs.Graphics().p("AKAcAMgatg3SIFJifMAatA3SQAIERh7AAQhQAAiGhyg");
	var mask_1_graphics_40 = new cjs.Graphics().p("AKFcAMgatg3SIFJifMAatA3SQAIERh7AAQhQAAiGhyg");
	var mask_1_graphics_41 = new cjs.Graphics().p("AKKcAMgatg3SIFJifMAatA3SQAJERh8AAQhPAAiHhyg");
	var mask_1_graphics_42 = new cjs.Graphics().p("AKPcAMgatg3SIFJifMAatA3SQAJERh8AAQhPAAiHhyg");
	var mask_1_graphics_43 = new cjs.Graphics().p("AKUcAMgatg3SIFJifMAatA3SQAJERh8AAQhPAAiHhyg");
	var mask_1_graphics_44 = new cjs.Graphics().p("AKacAMgaug3SIFJifMAauA3SQAIERh7AAQhQAAiGhyg");
	var mask_1_graphics_45 = new cjs.Graphics().p("AKfcAMgaug3SIFJifMAauA3SQAIERh7AAQhQAAiGhyg");

	this.timeline.addTween(cjs.Tween.get(mask_1).to({graphics:null,x:0,y:0}).wait(9).to({graphics:mask_1_graphics_9,x:-122.5,y:-63.6}).wait(1).to({graphics:mask_1_graphics_10,x:-122,y:-60.6}).wait(1).to({graphics:mask_1_graphics_11,x:-121.4,y:-57.6}).wait(1).to({graphics:mask_1_graphics_12,x:-120.9,y:-54.6}).wait(1).to({graphics:mask_1_graphics_13,x:-120.4,y:-51.6}).wait(1).to({graphics:mask_1_graphics_14,x:-119.9,y:-48.6}).wait(1).to({graphics:mask_1_graphics_15,x:-119.4,y:-45.6}).wait(1).to({graphics:mask_1_graphics_16,x:-118.9,y:-42.6}).wait(1).to({graphics:mask_1_graphics_17,x:-118.4,y:-39.6}).wait(1).to({graphics:mask_1_graphics_18,x:-117.8,y:-36.6}).wait(1).to({graphics:mask_1_graphics_19,x:-117.3,y:-33.6}).wait(1).to({graphics:mask_1_graphics_20,x:-116.8,y:-30.6}).wait(1).to({graphics:mask_1_graphics_21,x:-116.3,y:-27.6}).wait(1).to({graphics:mask_1_graphics_22,x:-115.8,y:-24.6}).wait(1).to({graphics:mask_1_graphics_23,x:-115.3,y:-21.6}).wait(1).to({graphics:mask_1_graphics_24,x:-114.8,y:-18.6}).wait(1).to({graphics:mask_1_graphics_25,x:-114.2,y:-15.6}).wait(1).to({graphics:mask_1_graphics_26,x:-113.7,y:-12.6}).wait(1).to({graphics:mask_1_graphics_27,x:-113.2,y:-9.6}).wait(1).to({graphics:mask_1_graphics_28,x:-112.7,y:-6.6}).wait(1).to({graphics:mask_1_graphics_29,x:-112.2,y:-3.6}).wait(1).to({graphics:mask_1_graphics_30,x:-111.7,y:-0.6}).wait(1).to({graphics:mask_1_graphics_31,x:-111.2,y:2.4}).wait(1).to({graphics:mask_1_graphics_32,x:-110.6,y:5.4}).wait(1).to({graphics:mask_1_graphics_33,x:-110.1,y:8.4}).wait(1).to({graphics:mask_1_graphics_34,x:-109.6,y:11.4}).wait(1).to({graphics:mask_1_graphics_35,x:-109.1,y:14.4}).wait(1).to({graphics:mask_1_graphics_36,x:-108.6,y:17.4}).wait(1).to({graphics:mask_1_graphics_37,x:-108.1,y:20.4}).wait(1).to({graphics:mask_1_graphics_38,x:-107.6,y:23.4}).wait(1).to({graphics:mask_1_graphics_39,x:-107,y:26.4}).wait(1).to({graphics:mask_1_graphics_40,x:-106.5,y:29.4}).wait(1).to({graphics:mask_1_graphics_41,x:-106,y:32.4}).wait(1).to({graphics:mask_1_graphics_42,x:-105.5,y:35.4}).wait(1).to({graphics:mask_1_graphics_43,x:-105,y:38.4}).wait(1).to({graphics:mask_1_graphics_44,x:-104.5,y:41.4}).wait(1).to({graphics:mask_1_graphics_45,x:-104,y:44.4}).wait(1).to({graphics:null,x:0,y:0}).wait(157));

	// drops
	this.instance_12 = new lib.drops2_1();
	this.instance_12.parent = this;
	this.instance_12.setTransform(0,-29);
	this.instance_12._off = true;

	var maskedShapeInstanceList = [this.instance_12];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(9).to({_off:false},0).to({_off:true},37).wait(157));

	// mask (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	var mask_2_graphics_4 = new cjs.Graphics().p("AmvbLMAP5g7UIMYDVMgP5A7UQi4BqibAAQkNAAi4k/g");
	var mask_2_graphics_5 = new cjs.Graphics().p("Am5bKMAP/g7SIMYDWMgQBA7SQi3BpibAAQkNAAi3k/g");
	var mask_2_graphics_6 = new cjs.Graphics().p("AnEbJMAQGg7RIMXDXMgQHA7RQi3BpiaAAQkOAAi3lAg");
	var mask_2_graphics_7 = new cjs.Graphics().p("AnPbIMAQNg7PIMXDYMgQOA7PQi2BoiaAAQkPAAi3lAg");
	var mask_2_graphics_8 = new cjs.Graphics().p("AnZbGMAQTg7NIMXDaMgQVA7NQi2BoiZAAQkQAAi2lCg");
	var mask_2_graphics_9 = new cjs.Graphics().p("AnkbFMAQag7LIMWDbMgQbA7LQi2BniZAAQkQAAi2lCg");
	var mask_2_graphics_10 = new cjs.Graphics().p("AnvbDMAQhg7IIMWDcMgQiA7JQi2BmiYAAQkRAAi2lDg");
	var mask_2_graphics_11 = new cjs.Graphics().p("An5bCMAQng7HIMWDeMgQpA7HQi2BmiYAAQkRAAi1lEg");
	var mask_2_graphics_12 = new cjs.Graphics().p("AoEbBMAQvg7FIMVDfMgQwA7FQi1BliYAAQkRAAi2lEg");
	var mask_2_graphics_13 = new cjs.Graphics().p("AoPa/MAQ2g7DIMUDhMgQ2A7DQi1BliXAAQkSAAi2lGg");
	var mask_2_graphics_14 = new cjs.Graphics().p("AoZa+MAQ8g7BIMUDiMgQ9A7BQi1BkiXAAQkSAAi1lGg");
	var mask_2_graphics_15 = new cjs.Graphics().p("Aoka9MARDg7AIMUDkMgREA6/Qi1BkiWAAQkTAAi1lHg");
	var mask_2_graphics_16 = new cjs.Graphics().p("Aova7MARKg69IMTDlMgRKA69Qi0BjiXAAQkTAAi1lIg");
	var mask_2_graphics_17 = new cjs.Graphics().p("Ao5a6MARQg68IMTDnMgRRA67Qi0BjiWAAQkUAAi0lJg");
	var mask_2_graphics_18 = new cjs.Graphics().p("ApEa4MARXg65IMTDoMgRYA65Qi0BiiVAAQkVAAi0lKg");
	var mask_2_graphics_19 = new cjs.Graphics().p("ApPa3MAReg63IMSDpMgRfA63QizBhiVAAQkVAAi0lKg");
	var mask_2_graphics_20 = new cjs.Graphics().p("ApZa2MARkg62IMSDrMgRmA61QiyBhiVAAQkWAAizlLg");
	var mask_2_graphics_21 = new cjs.Graphics().p("Apka0MARsg6zIMRDsMgRtA6zQixBgiWAAQkWAAizlMg");
	var mask_2_graphics_22 = new cjs.Graphics().p("ApvazMARzg6yIMRDuMgR0A6xQixBgiVAAQkXAAizlNg");
	var mask_2_graphics_23 = new cjs.Graphics().p("Ap5axMAR5g6vIMQDvMgR6A6vQiwBfiVAAQkYAAiylOg");
	var mask_2_graphics_24 = new cjs.Graphics().p("AqEawMASAg6tIMQDwMgSBA6tQiwBeiVAAQkYAAiylOg");
	var mask_2_graphics_25 = new cjs.Graphics().p("AqOauMASGg6rIMQDyMgSIA6rQiwBeiUAAQkZAAixlQg");
	var mask_2_graphics_26 = new cjs.Graphics().p("AqZatMASNg6pIMPDzMgSOA6pQiwBdiUAAQkZAAixlQg");
	var mask_2_graphics_27 = new cjs.Graphics().p("AqkasMASUg6nIMPD0MgSVA6nQivBciUAAQkaAAixlQg");
	var mask_2_graphics_28 = new cjs.Graphics().p("AquaqMASag6lIMPD2MgScA6lQivBciTAAQkbAAiwlSg");
	var mask_2_graphics_29 = new cjs.Graphics().p("Aq5apMASig6jIMND3MgSiA6jQivBbiTAAQkbAAiwlSg");
	var mask_2_graphics_30 = new cjs.Graphics().p("ArDanMASog6gIMND4MgSpA6hQiuBaiTAAQkcABivlUg");
	var mask_2_graphics_31 = new cjs.Graphics().p("ArOamMASvg6fIMND6MgSwA6fQiuBaiSAAQkdAAivlUg");
	var mask_2_graphics_32 = new cjs.Graphics().p("ArZakMAS2g6cIMMD7MgS2A6dQiuBZiSAAQkdAAivlVg");
	var mask_2_graphics_33 = new cjs.Graphics().p("ArjajMAS8g6bIMMD+MgS9A6aQitBYiSABQkeAAiulWg");
	var mask_2_graphics_34 = new cjs.Graphics().p("AruahMATDg6YIMMD/MgTEA6YQitBYiRAAQkeAAivlXg");
	var mask_2_graphics_35 = new cjs.Graphics().p("Ar4agMATJg6WIMLEAMgTKA6WQitBXiRAAQkeAAiulXg");
	var mask_2_graphics_36 = new cjs.Graphics().p("AsDaeMATQg6TIMLEBMgTRA6TQisBXiRAAQkfAAiulYg");
	var mask_2_graphics_37 = new cjs.Graphics().p("AsNadMATXg6SIMKEDMgTXA6RQitBXiQAAQkgAAitlZg");
	var mask_2_graphics_38 = new cjs.Graphics().p("AsYabMATeg6PIMJEEMgTdA6PQitBWiQAAQkgAAitlag");
	var mask_2_graphics_39 = new cjs.Graphics().p("AsiaaMATkg6NIMJEFMgTkA6NQisBViQAAQkhAAislag");
	var mask_2_graphics_40 = new cjs.Graphics().p("AstaYMATrg6LIMJEHMgTrA6LQisBViPAAQkiAAislcg");
	var mask_2_graphics_41 = new cjs.Graphics().p("As4aWMATyg6IIMIEIMgTxA6JQisBUiOAAQkjAAisldg");
	var mask_2_graphics_42 = new cjs.Graphics().p("AtCaVMAT4g6GIMIEJMgT4A6HQirBTiPAAQkjAAirldg");
	var mask_2_graphics_43 = new cjs.Graphics().p("AtNaTMAT/g6DIMIELMgT/A6DQirBTiOAAQkkAAirleg");
	var mask_2_graphics_44 = new cjs.Graphics().p("AtXaSMAUFg6CIMHENMgUFA6BQirBTiNAAQklAAiqlfg");
	var mask_2_graphics_45 = new cjs.Graphics().p("AthaQMAUMg5/IMGEOMgUMA5/QiqBSiNAAQklAAiqlgg");

	this.timeline.addTween(cjs.Tween.get(mask_2).to({graphics:null,x:0,y:0}).wait(4).to({graphics:mask_2_graphics_4,x:137.8,y:-140.6}).wait(1).to({graphics:mask_2_graphics_5,x:137.4,y:-135.8}).wait(1).to({graphics:mask_2_graphics_6,x:136.9,y:-131.1}).wait(1).to({graphics:mask_2_graphics_7,x:136.5,y:-126.4}).wait(1).to({graphics:mask_2_graphics_8,x:136.1,y:-121.7}).wait(1).to({graphics:mask_2_graphics_9,x:135.6,y:-117}).wait(1).to({graphics:mask_2_graphics_10,x:135.2,y:-112.3}).wait(1).to({graphics:mask_2_graphics_11,x:134.8,y:-107.6}).wait(1).to({graphics:mask_2_graphics_12,x:134.4,y:-102.9}).wait(1).to({graphics:mask_2_graphics_13,x:133.9,y:-98.2}).wait(1).to({graphics:mask_2_graphics_14,x:133.5,y:-93.5}).wait(1).to({graphics:mask_2_graphics_15,x:133.1,y:-88.8}).wait(1).to({graphics:mask_2_graphics_16,x:132.6,y:-84.1}).wait(1).to({graphics:mask_2_graphics_17,x:132.2,y:-79.4}).wait(1).to({graphics:mask_2_graphics_18,x:131.8,y:-74.7}).wait(1).to({graphics:mask_2_graphics_19,x:131.3,y:-69.9}).wait(1).to({graphics:mask_2_graphics_20,x:130.9,y:-65.2}).wait(1).to({graphics:mask_2_graphics_21,x:130.5,y:-60.5}).wait(1).to({graphics:mask_2_graphics_22,x:130.1,y:-55.8}).wait(1).to({graphics:mask_2_graphics_23,x:129.6,y:-51.1}).wait(1).to({graphics:mask_2_graphics_24,x:129.2,y:-46.4}).wait(1).to({graphics:mask_2_graphics_25,x:128.8,y:-41.7}).wait(1).to({graphics:mask_2_graphics_26,x:128.3,y:-37}).wait(1).to({graphics:mask_2_graphics_27,x:127.9,y:-32.3}).wait(1).to({graphics:mask_2_graphics_28,x:127.5,y:-27.6}).wait(1).to({graphics:mask_2_graphics_29,x:127,y:-22.9}).wait(1).to({graphics:mask_2_graphics_30,x:126.6,y:-18.1}).wait(1).to({graphics:mask_2_graphics_31,x:126.2,y:-13.4}).wait(1).to({graphics:mask_2_graphics_32,x:125.7,y:-8.7}).wait(1).to({graphics:mask_2_graphics_33,x:125.3,y:-4}).wait(1).to({graphics:mask_2_graphics_34,x:124.9,y:0.7}).wait(1).to({graphics:mask_2_graphics_35,x:124.4,y:5.4}).wait(1).to({graphics:mask_2_graphics_36,x:124,y:10.1}).wait(1).to({graphics:mask_2_graphics_37,x:123.6,y:14.8}).wait(1).to({graphics:mask_2_graphics_38,x:123.1,y:19.5}).wait(1).to({graphics:mask_2_graphics_39,x:122.7,y:24.2}).wait(1).to({graphics:mask_2_graphics_40,x:122.3,y:28.9}).wait(1).to({graphics:mask_2_graphics_41,x:121.8,y:33.7}).wait(1).to({graphics:mask_2_graphics_42,x:121.4,y:38.4}).wait(1).to({graphics:mask_2_graphics_43,x:121,y:43.1}).wait(1).to({graphics:mask_2_graphics_44,x:120.5,y:47.8}).wait(1).to({graphics:mask_2_graphics_45,x:120.1,y:52.5}).wait(1).to({graphics:null,x:0,y:0}).wait(157));

	// drops
	this.instance_13 = new lib.drops1_1();
	this.instance_13.parent = this;
	this.instance_13.setTransform(0,-29);
	this.instance_13._off = true;

	var maskedShapeInstanceList = [this.instance_13];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(4).to({_off:false},0).to({_off:true},42).wait(157));

	// mask (mask)
	var mask_3 = new cjs.Shape();
	mask_3._off = true;
	var mask_3_graphics_4 = new cjs.Graphics().p("EgnPgNFIHnqTMAxZAkeQBWI9o9BWg");
	var mask_3_graphics_5 = new cjs.Graphics().p("EgmxgNKIHpqSMAxRAknQBUI+o9BUg");
	var mask_3_graphics_6 = new cjs.Graphics().p("EgmTgNQIHrqRMAxJAkyQBSI+o9BTg");
	var mask_3_graphics_7 = new cjs.Graphics().p("Egl2gNWIHuqPMAxBAk8QBRI+o+BRg");
	var mask_3_graphics_8 = new cjs.Graphics().p("EglYgNcIHvqNMAw6AlGQBPI+o+BPg");
	var mask_3_graphics_9 = new cjs.Graphics().p("Egk6gNhIHxqMMAwyAlPQBNI/o+BNg");
	var mask_3_graphics_10 = new cjs.Graphics().p("EgkcgNnIHzqKMAwqAlZQBLI+o+BMg");
	var mask_3_graphics_11 = new cjs.Graphics().p("Egj+gNtIH1qIMAwiAljQBJI+o/BKg");
	var mask_3_graphics_12 = new cjs.Graphics().p("EgjhgNzIH4qGMAwaAltQBHI+o/BIg");
	var mask_3_graphics_13 = new cjs.Graphics().p("EgjDgN4IH6qFMAwSAl2QBFI/o/BGg");
	var mask_3_graphics_14 = new cjs.Graphics().p("EgilgN+IH8qDMAwJAmAQBEI/o/BEg");
	var mask_3_graphics_15 = new cjs.Graphics().p("EgiHgOEIH+qBMAwBAmKQBCI/o/BCg");
	var mask_3_graphics_16 = new cjs.Graphics().p("EghpgOJIH/qAMAv6AmTQA/JAo/BAg");
	var mask_3_graphics_17 = new cjs.Graphics().p("EghLgOPIIBp+MAvxAmdQA+I/o/A/g");
	var mask_3_graphics_18 = new cjs.Graphics().p("EggtgOVIIDp8MAvpAmnQA8I/o/A9g");
	var mask_3_graphics_19 = new cjs.Graphics().p("EggPgOaIIFp7MAvhAmwQA6JApAA7g");
	var mask_3_graphics_20 = new cjs.Graphics().p("A/yugIIIp5MAvYAm6QA4JAo/A5g");
	var mask_3_graphics_21 = new cjs.Graphics().p("A/IveIIepmMAt/AojQAkJCpCAkg");
	var mask_3_graphics_22 = new cjs.Graphics().p("A+cwbIIzpTMAshAqKQAQJCpDARg");
	var mask_3_graphics_23 = new cjs.Graphics().p("ANRaWMgrBgrtIJIo+MArAArtQgFI+o6AAIgIAAg");
	var mask_3_graphics_24 = new cjs.Graphics().p("AMaa7MgpcgtNIJbopMApcAtNQgYIqoVAAIgugBg");
	var mask_3_graphics_25 = new cjs.Graphics().p("ALhbdMgn0gupIJuoTMAn1AuoQgrIXnzAAQgnAAgqgDg");
	var mask_3_graphics_26 = new cjs.Graphics().p("AKmb8MgmKgwBIKBn9MAmKAwBQg8IEnVAAQg2AAg6gHg");
	var mask_3_graphics_27 = new cjs.Graphics().p("AJocZMgkbgxWIKTnmMAkbAxVQhLHym7AAQhCAAhLgLg");
	var mask_3_graphics_28 = new cjs.Graphics().p("AIpczMgiqgymIKjnPMAirAymQhaHfmjAAQhOAAhZgQg");
	var mask_3_graphics_29 = new cjs.Graphics().p("AHodKMgg3gzzIK0m3MAg3AzzQhoHOmNAAQhYAAhngXg");
	var mask_3_graphics_30 = new cjs.Graphics().p("AGldeMgfAg07ILCmeMAfBA07Qh0G8l5AAQhiAAh0geg");
	var mask_3_graphics_31 = new cjs.Graphics().p("AFhdwMgdIg2AILRmFMAdIA2AQiAGrlnAAQhrAAh/gmg");
	var mask_3_graphics_32 = new cjs.Graphics().p("AEbd/MgbNg3AILflrMAbMA2/QiLGalWAAQhzAAiKgug");
	var mask_3_graphics_33 = new cjs.Graphics().p("ADTeLMgZPg37ILrlSMAZPA37QiVGKlGAAQh7AAiVg4g");
	var mask_3_graphics_34 = new cjs.Graphics().p("ACLeUMgXQg4yIL2k3MAXQA4yQieF5k4AAQiDAAidhCg");
	var mask_3_graphics_35 = new cjs.Graphics().p("ABBeaMgVOg5kIMAkcMAVPA5lQimFokrAAQiKAAimhNg");
	var mask_3_graphics_36 = new cjs.Graphics().p("AgJeeMgTMg6SIMKkBMATMA6TQiuFYkfAAQiQAAithYg");
	var mask_3_graphics_37 = new cjs.Graphics().p("AhUefMgRIg68IMTjkMARHA68Qi1FHkTAAQiXAAizhjg");
	var mask_3_graphics_38 = new cjs.Graphics().p("AiheeMgPCg7hIMbjJMAPBA7hQi6E4kJAAQieAAi5hvg");
	var mask_3_graphics_39 = new cjs.Graphics().p("AjueZMgM7g8AIMiitMAM5A8BQi/Eoj/AAQijAAi/h8g");
	var mask_3_graphics_40 = new cjs.Graphics().p("Ak8eSMgKyg8bIMniQMAKxA8bQjDEYj1AAQiqAAjEiIg");
	var mask_3_graphics_41 = new cjs.Graphics().p("AmKeJMgIpg8yIMrh0MAIpA8yQjHEJjrAAQiyAAjHiVg");
	var mask_3_graphics_42 = new cjs.Graphics().p("AnYd8MgGgg9DIMwhXMAGeA9DQjJD6jjAAQi4AAjKijg");
	var mask_3_graphics_43 = new cjs.Graphics().p("AomdtMgEWg9QIMyg5MAEVA9PQjMDqjbAAQi/AAjLiwg");
	var mask_3_graphics_44 = new cjs.Graphics().p("Ap1dbMgCLg9XIMzgdMACLA9XQjMDcjUAAQjGAAjNi/g");
	var mask_3_graphics_45 = new cjs.Graphics().p("ArCdHMAAAg9aIMzAAMAAAA9aQjMDNjNAAQjNAAjNjNg");

	this.timeline.addTween(cjs.Tween.get(mask_3).to({graphics:null,x:0,y:0}).wait(4).to({graphics:mask_3_graphics_4,x:-251.2,y:-136}).wait(1).to({graphics:mask_3_graphics_5,x:-248.2,y:-133.1}).wait(1).to({graphics:mask_3_graphics_6,x:-245.2,y:-130.1}).wait(1).to({graphics:mask_3_graphics_7,x:-242.3,y:-127.2}).wait(1).to({graphics:mask_3_graphics_8,x:-239.3,y:-124.3}).wait(1).to({graphics:mask_3_graphics_9,x:-236.3,y:-121.3}).wait(1).to({graphics:mask_3_graphics_10,x:-233.3,y:-118.4}).wait(1).to({graphics:mask_3_graphics_11,x:-230.3,y:-115.5}).wait(1).to({graphics:mask_3_graphics_12,x:-227.4,y:-112.5}).wait(1).to({graphics:mask_3_graphics_13,x:-224.4,y:-109.6}).wait(1).to({graphics:mask_3_graphics_14,x:-221.4,y:-106.7}).wait(1).to({graphics:mask_3_graphics_15,x:-218.4,y:-103.8}).wait(1).to({graphics:mask_3_graphics_16,x:-215.4,y:-100.8}).wait(1).to({graphics:mask_3_graphics_17,x:-212.4,y:-97.9}).wait(1).to({graphics:mask_3_graphics_18,x:-209.4,y:-95}).wait(1).to({graphics:mask_3_graphics_19,x:-206.4,y:-92}).wait(1).to({graphics:mask_3_graphics_20,x:-203.5,y:-89.1}).wait(1).to({graphics:mask_3_graphics_21,x:-199.3,y:-84.4}).wait(1).to({graphics:mask_3_graphics_22,x:-194.9,y:-79.7}).wait(1).to({graphics:mask_3_graphics_23,x:-190.5,y:-74.9}).wait(1).to({graphics:mask_3_graphics_24,x:-185.9,y:-70.1}).wait(1).to({graphics:mask_3_graphics_25,x:-181.2,y:-65.3}).wait(1).to({graphics:mask_3_graphics_26,x:-176.5,y:-60.4}).wait(1).to({graphics:mask_3_graphics_27,x:-171.6,y:-55.4}).wait(1).to({graphics:mask_3_graphics_28,x:-166.6,y:-50.3}).wait(1).to({graphics:mask_3_graphics_29,x:-161.6,y:-45.2}).wait(1).to({graphics:mask_3_graphics_30,x:-156.4,y:-40.1}).wait(1).to({graphics:mask_3_graphics_31,x:-151.2,y:-34.9}).wait(1).to({graphics:mask_3_graphics_32,x:-145.9,y:-29.6}).wait(1).to({graphics:mask_3_graphics_33,x:-140.5,y:-24.3}).wait(1).to({graphics:mask_3_graphics_34,x:-135,y:-19}).wait(1).to({graphics:mask_3_graphics_35,x:-129.4,y:-13.6}).wait(1).to({graphics:mask_3_graphics_36,x:-123.8,y:-8.2}).wait(1).to({graphics:mask_3_graphics_37,x:-118.1,y:-2.7}).wait(1).to({graphics:mask_3_graphics_38,x:-112.4,y:2.8}).wait(1).to({graphics:mask_3_graphics_39,x:-106.6,y:8.3}).wait(1).to({graphics:mask_3_graphics_40,x:-100.7,y:13.8}).wait(1).to({graphics:mask_3_graphics_41,x:-94.8,y:19.4}).wait(1).to({graphics:mask_3_graphics_42,x:-88.9,y:25}).wait(1).to({graphics:mask_3_graphics_43,x:-82.9,y:30.7}).wait(1).to({graphics:mask_3_graphics_44,x:-76.9,y:36.3}).wait(1).to({graphics:mask_3_graphics_45,x:-70.7,y:42}).wait(1).to({graphics:null,x:0,y:0}).wait(157));

	// drops
	this.instance_14 = new lib.drops1_1();
	this.instance_14.parent = this;
	this.instance_14.setTransform(0,-29);
	this.instance_14._off = true;

	var maskedShapeInstanceList = [this.instance_14];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_3;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(4).to({_off:false},0).to({_off:true},42).wait(157));

	// mask (mask)
	var mask_4 = new cjs.Shape();
	mask_4._off = true;
	var mask_4_graphics_4 = new cjs.Graphics().p("AjlKtMgFlg9KIMwhKMAFlA9JQjLDzjgAAQi6AAjLiog");
	var mask_4_graphics_5 = new cjs.Graphics().p("AjpLeMgFdg9LIMwhIMAFdA9KQjLDyjgAAQi7AAjKipg");
	var mask_4_graphics_6 = new cjs.Graphics().p("AjuMPMgFTg9LIMwhHMAFTA9LQjKDxjgAAQi7AAjLiqg");
	var mask_4_graphics_7 = new cjs.Graphics().p("AjyNAMgFLg9MIMwhFMAFLA9MQjLDwjfAAQi7AAjLirg");
	var mask_4_graphics_8 = new cjs.Graphics().p("Aj2NxMgFDg9NIMwhDMAFDA9NQjLDvjfAAQi8AAjKisg");
	var mask_4_graphics_9 = new cjs.Graphics().p("Aj7OiMgE6g9NIMxhCMAE6A9OQjMDujeAAQi8AAjLitg");
	var mask_4_graphics_10 = new cjs.Graphics().p("Aj/PTMgExg9OIMwhAMAExA9PQjLDtjeAAQi8AAjLiug");
	var mask_4_graphics_11 = new cjs.Graphics().p("AkEQEMgEog9PIMxg9MAEoA9OQjLDtjdAAQi+AAjLivg");
	var mask_4_graphics_12 = new cjs.Graphics().p("AkIQ1MgEgg9PIMxg8MAEgA9PQjMDsjcAAQi+AAjLiwg");
	var mask_4_graphics_13 = new cjs.Graphics().p("AkNRmMgEWg9QIMxg6MAEWA9QQjLDqjcAAQi+AAjMiwg");
	var mask_4_graphics_14 = new cjs.Graphics().p("AkRSXMgEOg9RIMxg4MAEOA9RQjLDpjcAAQi+AAjMixg");
	var mask_4_graphics_15 = new cjs.Graphics().p("AkVTIMgEGg9RIMxg3MAEGA9SQjMDojbAAQi/AAjLiyg");
	var mask_4_graphics_16 = new cjs.Graphics().p("AkaT5MgD9g9SIMyg1MAD9A9SQjMDojbAAQi/AAjMizg");
	var mask_4_graphics_17 = new cjs.Graphics().p("AkeUqMgD0g9SIMxgzMAD0A9SQjMDnjaAAQi/AAjMi0g");
	var mask_4_graphics_18 = new cjs.Graphics().p("AkjVbMgDrg9TIMygxMADrA9TQjMDljaABQjAAAjMi1g");
	var mask_4_graphics_19 = new cjs.Graphics().p("AknWMMgDjg9UIMygvMADjA9UQjMDkjaAAQjAAAjMi1g");
	var mask_4_graphics_20 = new cjs.Graphics().p("AkrW9MgDag9UIMxguMADaA9UQjMDkjYAAQjBAAjMi2g");
	var mask_4_graphics_21 = new cjs.Graphics().p("AkwXuMgDRg9VIMygsMADRA9VQjMDjjYAAQjCAAjMi3g");
	var mask_4_graphics_22 = new cjs.Graphics().p("Ak0YeMgDJg9UIMygqMADJA9VQjNDijXAAQjCAAjMi5g");
	var mask_4_graphics_23 = new cjs.Graphics().p("Ak5ZPMgC/g9VIMygoMAC/A9VQjMDhjXAAQjCAAjNi5g");
	var mask_4_graphics_24 = new cjs.Graphics().p("Ak9aAMgC3g9WIMygmMAC3A9WQjMDgjXAAQjDAAjMi6g");
	var mask_4_graphics_25 = new cjs.Graphics().p("AlBaxMgCvg9WIMyglMACvA9XQjNDfjWAAQjDAAjMi7g");
	var mask_4_graphics_26 = new cjs.Graphics().p("AlGbiMgClg9XIMygiMAClA9WQjMDejWAAQjDAAjNi7g");
	var mask_4_graphics_27 = new cjs.Graphics().p("AlKcSMgCdg9WIMyghMACdA9XQjMDdjWAAQjEAAjMi9g");
	var mask_4_graphics_28 = new cjs.Graphics().p("AlPdDMgCUg9XIMzgfMACUA9XQjNDdjVAAQjEAAjNi+g");
	var mask_4_graphics_29 = new cjs.Graphics().p("AlTdcMgCLg9YIMygdMACLA9YQjMDbjVAAQjEAAjNi+g");
	var mask_4_graphics_30 = new cjs.Graphics().p("AlXdaMgCDg9XIMygcMACDA9YQjNDbjTAAQjGAAjMjAg");
	var mask_4_graphics_31 = new cjs.Graphics().p("AlcdZMgB6g9YIMzgZMAB6A9YQjNDZjTAAQjGAAjNjAg");
	var mask_4_graphics_32 = new cjs.Graphics().p("AlgdYMgByg9YIMzgYMAByA9YQjNDZjTAAQjGAAjNjBg");
	var mask_4_graphics_33 = new cjs.Graphics().p("AlldXMgBog9ZIMzgWMABoA9ZQjNDYjSAAQjHAAjNjCg");
	var mask_4_graphics_34 = new cjs.Graphics().p("AlpdWMgBgg9ZIMzgUMABgA9ZQjNDWjSAAQjHAAjNjCg");
	var mask_4_graphics_35 = new cjs.Graphics().p("AltdUMgBYg9ZIMzgSMABYA9ZQjNDWjSAAQjHAAjNjEg");
	var mask_4_graphics_36 = new cjs.Graphics().p("AlydTMgBOg9ZIMzgRMABOA9aQjNDVjRAAQjIAAjNjFg");
	var mask_4_graphics_37 = new cjs.Graphics().p("Al2dSMgBGg9aIMzgOMABGA9ZQjNDUjRAAQjIAAjNjFg");
	var mask_4_graphics_38 = new cjs.Graphics().p("Al6dQMgA9g9ZIMygNMAA9A9aQjMDTjRAAQjJAAjMjHg");
	var mask_4_graphics_39 = new cjs.Graphics().p("Al/dPMgA0g9aIMzgKMAA0A9ZQjNDSjQAAQjJAAjNjHg");
	var mask_4_graphics_40 = new cjs.Graphics().p("AmDdOMgAsg9aIMzgJMAAsA9aQjNDRjPAAQjKAAjNjIg");
	var mask_4_graphics_41 = new cjs.Graphics().p("AmIdMMgAig9ZIMzgIMAAiA9aQjNDRjOAAQjLAAjNjKg");
	var mask_4_graphics_42 = new cjs.Graphics().p("AmMdLMgAag9aIMzgFMAAaA9aQjNDPjOAAQjLAAjNjKg");
	var mask_4_graphics_43 = new cjs.Graphics().p("AmQdKMgASg9aIMzgEMAASA9aQjNDPjOAAQjLAAjNjLg");
	var mask_4_graphics_44 = new cjs.Graphics().p("AmVdIMgAIg9aIMzgBMAAIA9aQjNDNjNAAQjMAAjNjMg");
	var mask_4_graphics_45 = new cjs.Graphics().p("AmZdHMAAAg9aIMzAAMAAAA9aQjNDNjNAAQjMAAjNjNg");

	this.timeline.addTween(cjs.Tween.get(mask_4).to({graphics:null,x:0,y:0}).wait(4).to({graphics:mask_4_graphics_4,x:-43.9,y:-330.4}).wait(1).to({graphics:mask_4_graphics_5,x:-42.7,y:-325.4}).wait(1).to({graphics:mask_4_graphics_6,x:-41.5,y:-320.4}).wait(1).to({graphics:mask_4_graphics_7,x:-40.3,y:-315.4}).wait(1).to({graphics:mask_4_graphics_8,x:-39.1,y:-310.4}).wait(1).to({graphics:mask_4_graphics_9,x:-37.8,y:-305.4}).wait(1).to({graphics:mask_4_graphics_10,x:-36.6,y:-300.4}).wait(1).to({graphics:mask_4_graphics_11,x:-35.4,y:-295.3}).wait(1).to({graphics:mask_4_graphics_12,x:-34.2,y:-290.3}).wait(1).to({graphics:mask_4_graphics_13,x:-33,y:-285.3}).wait(1).to({graphics:mask_4_graphics_14,x:-31.7,y:-280.3}).wait(1).to({graphics:mask_4_graphics_15,x:-30.5,y:-275.3}).wait(1).to({graphics:mask_4_graphics_16,x:-29.3,y:-270.3}).wait(1).to({graphics:mask_4_graphics_17,x:-28.1,y:-265.2}).wait(1).to({graphics:mask_4_graphics_18,x:-26.9,y:-260.2}).wait(1).to({graphics:mask_4_graphics_19,x:-25.6,y:-255.2}).wait(1).to({graphics:mask_4_graphics_20,x:-24.4,y:-250.2}).wait(1).to({graphics:mask_4_graphics_21,x:-23.2,y:-245.2}).wait(1).to({graphics:mask_4_graphics_22,x:-22,y:-240.1}).wait(1).to({graphics:mask_4_graphics_23,x:-20.8,y:-235.1}).wait(1).to({graphics:mask_4_graphics_24,x:-19.6,y:-230.1}).wait(1).to({graphics:mask_4_graphics_25,x:-18.3,y:-225.1}).wait(1).to({graphics:mask_4_graphics_26,x:-17.1,y:-220}).wait(1).to({graphics:mask_4_graphics_27,x:-15.9,y:-215}).wait(1).to({graphics:mask_4_graphics_28,x:-14.7,y:-210}).wait(1).to({graphics:mask_4_graphics_29,x:-13.5,y:-202.5}).wait(1).to({graphics:mask_4_graphics_30,x:-12.2,y:-192.5}).wait(1).to({graphics:mask_4_graphics_31,x:-11,y:-182.5}).wait(1).to({graphics:mask_4_graphics_32,x:-9.8,y:-172.5}).wait(1).to({graphics:mask_4_graphics_33,x:-8.6,y:-162.5}).wait(1).to({graphics:mask_4_graphics_34,x:-7.4,y:-152.4}).wait(1).to({graphics:mask_4_graphics_35,x:-6.1,y:-142.4}).wait(1).to({graphics:mask_4_graphics_36,x:-4.9,y:-132.4}).wait(1).to({graphics:mask_4_graphics_37,x:-3.7,y:-122.4}).wait(1).to({graphics:mask_4_graphics_38,x:-2.5,y:-112.4}).wait(1).to({graphics:mask_4_graphics_39,x:-1.3,y:-102.3}).wait(1).to({graphics:mask_4_graphics_40,x:0,y:-92.3}).wait(1).to({graphics:mask_4_graphics_41,x:1.2,y:-82.3}).wait(1).to({graphics:mask_4_graphics_42,x:2.4,y:-72.3}).wait(1).to({graphics:mask_4_graphics_43,x:3.6,y:-62.3}).wait(1).to({graphics:mask_4_graphics_44,x:4.8,y:-52.2}).wait(1).to({graphics:mask_4_graphics_45,x:6.1,y:-42.2}).wait(1).to({graphics:null,x:0,y:0}).wait(157));

	// drops
	this.instance_15 = new lib.drops1_1();
	this.instance_15.parent = this;
	this.instance_15.setTransform(0,-29);
	this.instance_15._off = true;

	var maskedShapeInstanceList = [this.instance_15];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_4;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_15).wait(4).to({_off:false},0).to({_off:true},42).wait(157));

	// bgImg1
	this.instance_16 = new lib.bgImg1_1();
	this.instance_16.parent = this;
	this.instance_16.setTransform(0,-29);

	this.instance_17 = new lib.bg2();
	this.instance_17.parent = this;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_16}]}).to({state:[{t:this.instance_17}]},46).to({state:[{t:this.instance_16}]},146).wait(11));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,-300,300.9,600);


// stage content:
(lib._300x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// cover
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#666666").ss(2,1,1).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// banner
	this.instance = new lib.banner();
	this.instance.parent = this;
	this.instance.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(149,299,302,602);
// library properties:
lib.properties = {
	id: '892A42370B514A63B70592071675BDC6',
	width: 300,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/bgImg1.jpg", id:"bgImg1"},
		{src:"images/bgImg2.jpg", id:"bgImg2"},
		{src:"images/bgImg3.jpg", id:"bgImg3"},
		{src:"images/drops1.png", id:"drops1"},
		{src:"images/drops2.png", id:"drops2"},
		{src:"images/prod.png", id:"prod"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['892A42370B514A63B70592071675BDC6'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;