(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 300,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	manifest: [
		{src:"images/imgpngcopy.png", id:"imgpngcopy"},
		{src:"images/site.png", id:"site"},
		{src:"images/t1.png", id:"t1"},
		{src:"images/t2.png", id:"t2"},
		{src:"images/t3.png", id:"t3"},
		{src:"images/t4.png", id:"t4"}
	]
};



// symbols:



(lib.imgpngcopy = function() {
	this.initialize(img.imgpngcopy);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,243,130);


(lib.site = function() {
	this.initialize(img.site);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,181,16);


(lib.t1 = function() {
	this.initialize(img.t1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,303,90);


(lib.t2 = function() {
	this.initialize(img.t2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,315,96);


(lib.t3 = function() {
	this.initialize(img.t3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,178,102);


(lib.t4 = function() {
	this.initialize(img.t4);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,261,124);


(lib.t4_1 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.t4();
	this.instance.setTransform(-186,-88.3,1.425,1.425);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-186,-88.3,372,176.8);


(lib.t3_1 = function() {
	this.initialize();

	// Layer 3
	this.instance = new lib.t3();
	this.instance.setTransform(-112.2,-72.8,1.428,1.428);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-112.2,-72.8,254.2,145.6);


(lib.t2_1 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.t2();
	this.instance.setTransform(-157.5,-48);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-157.5,-48,315,96);


(lib.t1_Bg = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#C40B33").s().p("AqMUnInzJlIh5quIsZOSIAhweIzzHgIPI0aIvIhEINCmAIq8zsIV4IqIkeu6IKnGyIkfwxIRuQdIgbreIGDKbIIGx0IAATzILkowIARHvIJOq3IjISiIQxntIm4MZIN2CnIypG4IXCJcI1lAUIPBNJI6KqpIMgV/I1PyWIBwNPIpKpeIneVxgAkYeUIFyw5IGHGUIhnr+INyL5IoBuFIRRHBInImPIOfgOIwXmsIPjlvIm/hVIEXn1ItfGMICNtKInGIYIgVp0IrxI6IAArtIkoKQIi0k1IAQGfIvTuNIDwODIqTmkID6NAIzvnzIIVO/IlECTIIrAnIsLQdIOPlZIgZMXIK8snIB1KeIHXpCg");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FEF152").s().p("AqMUnInzJlIh5quIsZOSIAhweIzzHgIPI0aIvIhEINCmAIq8zsIV4IqIkeu6IKnGyIkfwxIRuQdIgbreIGDKbIIGx0IAATzILkowIARHvIJOq3IjISiIQxntIm4MZIN2CnIypG4IXCJcI1lAUIPBNJI6KqpIMgV/I1PyWIBwNPIpKpeIneVxg");

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-330,-262.6,660,525.3);


(lib.t1_1 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.t1();
	this.instance.setTransform(-151.5,-45);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-151.5,-45,303,90);


(lib.site_1 = function() {
	this.initialize();

	// Layer 3
	this.instance = new lib.site();
	this.instance.setTransform(-113.1,-10,1.25,1.25);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-113.1,-10,226.3,20);


(lib.price = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#C40A32").s().p("Ai5FEQgLgEgHgGQgDgEgBgFQgDgeAAhcQgLgLgCgLQgBgJADgCQAkgYAqgGIATgDQAOgCAEABQAGAAADACQAEACAAAHQADAegKABIguAGQgFABgUAHIACAAQAJAAADAHQABAEAAAMIgBAuQAAAeACAjQACAVgIABIgDAAQgKAAgLgEgAgwE1QgOgEgGgGQgDgDgBgGQgEggAAgpQAAgiACgQQgJgLgGgLQgEgIAEgDQAIgIARgJQAZgMAXgDQAEgBAYAGQAbAFAGADQADACAGAMQAHAOABAJQADAbgLAXQgMAZgZAKQgPAFgGgCQgEgBgHgHIgDgDQAAAgAEAsQAAAGgGAAIgJABQgJAAgKgDgAgMCVQgIAAgJAFIABAAQALAEAAALIgBAmQANgDAHgLQAKgLgBgOQgBgJgHgGQgDgEgIAAIgEAAgAB2EjQgQgEgGgGQgDgDgBgGQgDgYAAgoQgNgQgBgIQgBgEAEgBIALgBQAAhCADgSQABgGAFAAQAIgBAPABQAQAAAGACQAHACAAAGQgCAeAAApIAigGQABhDACgMQAAgGAGgBQAIgBAPABQAQABAGABQAHACAAAGQgCAiAAAwQAAA/AFAsQABAHgHAAQgOACgQgEQgPgEgGgGQgDgEgBgGQgCgTgBgiIgiAHQACAqADAeQABAGgHABIgIAAQgKAAgLgDgAizgCQgHgEgBgNQgEgkAChbQgugPgFgHQgFgHAAgEQgBgHAKgGQASgNARgnQAKgYAFgTQADgJAJgBQAOgCARACQAUACAMAGQAQAIAAAJQgDAvgBBNQgBBaACBJQABALgLAAIgCABQgXAAgugdgAAuAJQhJgPgVgZQgJgLABgVQADg2AxgoIAAgBQgcgNgLgJQgOgLgBgOQgDg0AjgiQAagbAqgJQAPgBANADQBEAQASAVQAJALgBAWQgCAmgtAuQAjALARAMQATAOAAASQACA1gnAmQgiAegrAGIgKAAQgJAAgJgCgAAihqQgHALABAGQAAAHALADQAKADAIgCQASgEAEgCQAIgFgCgLQgBgGgNgKQgMgKgEgBIgCAAQgLAIgIANgAAxjvQgXAGADAUQACAGAIACIALACIABABQASgPgCgOQgBgIgKAAIgHAAg");
	this.shape.setTransform(1.6,6.4);

	// Layer 3
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FEF152").s().p("AhHF/IklDmIACmHImgDTIFvlFInKkXIH6AFIhRkmIDMBsIgJmeIECFwIDSjzIgtE0IHSh7Il4FeIJeBsIo2BVIFBFjIlMiUIhjHZg");
	this.shape_1.setTransform(4.5,5.3);

	// Layer 2
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#C40931").s().p("Ag9HqIlZEQIABmjIphEdIIDnzIqAmAILJAgIhklmIDyCAIgLnqIFOG/IE3lyIhGHGIK8jCIojHVILDCWIqmCFIF0GzInUi1IhxIggAC6JkIBTmSIB3A1IjAjUIEigsIlUg8IEVkDIkxBRIAbi2Ih1CGIi0kCIAHE1IiohZIA/DmIlhgEIFJDJIgsAnIAwgZIgBFqIDvi9g");
	this.shape_2.setTransform(2,4.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FEF152").s().p("AAZEEIjtC9IABlqIgwAYIAsgnIlJjIIFhAEIg/jmICoBZIgHk1IC0ECIB1iGIgbC2IExhRIkVEDIFUA+IkiAqIDADUIh3g1IhUGSg");
	this.shape_3.setTransform(-3.9,7.9);

	this.addChild(this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-112,-90.3,228.1,189);


(lib.pacMancopy = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FEF152").s().p("AAAAoIgnApIgpgpIApgoIgpgnIApgpIAnApIAogpIApApIgpAnIApAoIgpApg");
	this.shape.setTransform(-5.7,-61.1,3.07,3.07);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(9));

	// Layer 8
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#000000").ss(2.8,1,1).p("APOseQifh1jCg/QjHhBjZAAQnuAAlfEyQleEzAAGuQAAGxFeExQFfEyHuAAQDdAADOhEQDGhCChh7Ispsgg");
	this.shape_1.setTransform(5.5,-5.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AqALiQlekxAAmxQAAmuFekzQFfkxHuAAQDZAADHBAQDCA/CfB1IsYMQIMpMhQihB7jGBCQjOBEjdAAQnuAAlfkyg");
	this.shape_2.setTransform(5.5,-5.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#000000").ss(2.8,1,1).p("AwzAAQAAmuFekzQFfkyHvAAQDYAADIBBQDBA/CgB1QBDAkBIBPQAVAhANAmIvFJaIPSJlQgXAjAAAQQhIBVhKAwQiiB7jGBCQjNBEjdAAQnvAAlfkyQlekxAAmxg");
	this.shape_3.setTransform(14,-5.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("ArVLiQlekxAAmxQAAmuFekzQFfkxHvAAQDYAADHBAQDCA/CfB1QBEAkBIBQQAVAgANAmIvGJZIPTJmQgXAiAAAQQhIBWhLAwQihB7jGBCQjOBEjcAAQnvAAlfkyg");
	this.shape_4.setTransform(14,-5.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f().s("#000000").ss(2.8,1,1).p("Ax/AAQAAmuFfkzQFfkyHuAAQDZAADHBBQDCA/CfB1QBlA2BqB9QBQBfAsB0IxjGPIRqGXQgeBehFBWQhuCIhwBJQihB7jGBCQjOBEjdAAQnuAAlfkyQlfkxAAmxg");
	this.shape_5.setTransform(21.6,-5.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AshLiQlekxAAmxQAAmuFekzQFgkxHuAAQDYAADIBAQDCA/CfB1QBlA2BqB9QBQBfAsB0IxjGPIRpGXQgdBehFBWQhuCIhwBJQihB7jGBCQjOBEjdAAQnuAAlgkyg");
	this.shape_6.setTransform(21.6,-5.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f().s("#000000").ss(2.8,1,1).p("AyjAAQAAmuFekzQFfkyHuAAQDZAADHBBQDCA/CfB1QBlA2BqB9QClDCAkENIyuCQISxCQQgGDvimDPQhuCIhwBJQihB7jGBCQjOBEjdAAQnuAAlfkyQlekxAAmxg");
	this.shape_7.setTransform(25.2,-5.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AtFLiQlekxAAmxQAAmuFekzQFfkxHuAAQDZAADHBAQDCA/CfB1QBlA2BqB9QClDDAkEMIyuCQISxCQQgGDvimDPQhuCIhwBJQihB7jGBCQjOBEjdAAQnuAAlfkyg");
	this.shape_8.setTransform(25.2,-5.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f().s("#000000").ss(2.8,1,1).p("APFprQhqh9hkg2Qigh1jBg/QjIhBjWAAQnwAAlgEyQleEzAAGuQAAGxFeExQFgEyHwAAQDbAADNhEQDGhCCih7QBwhJBuiIQDWkMgFk2IzWgNITUgQQghlajPj0g");
	this.shape_9.setTransform(27.1,-5.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AtYLiQlekxAAmxQAAmuFekzQFgkxHwAAQDWAADIBAQDBA/CgB1QBkA2BqB9QDPD0AhFZIzUAQITWAOQAFE2jWEMQhuCIhwBJQiiB7jGBCQjNBEjbAAQnwAAlgkyg");
	this.shape_10.setTransform(27.1,-5.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f().s("#000000").ss(2.8,1,1).p("AyaAAQAAmuFekzQFfkyHvAAQDYAADIBBQDBA/CgB1QBkA2BqB9QCQCpAmDnIyaDQISeDSQgLDKiOCxQhuCIhwBJQiiB7jGBCQjNBEjdAAQnvAAlfkyQlekxAAmxg");
	this.shape_11.setTransform(24.3,-5.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("As8LiQlekxAAmxQAAmuFekzQFfkxHvAAQDYAADHBAQDCA/CfB1QBlA2BqB9QCQCqAmDmIybDPISfDTQgLDKiOCxQhuCIhxBJQihB7jGBCQjOBEjcAAQnvAAlfkyg");
	this.shape_12.setTransform(24.3,-5.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f().s("#000000").ss(2.8,1,1).p("AyIAAQAAmuFekzQFgkyHuAAQDYAADIBBQDBA/CgB1QBkA2BqB9QBmB4ApCaIx1FPIR8FWQgYCBhdB1QhuCIhwBJQiiB7jGBCQjNBEjdAAQnuAAlgkyQlekxAAmxg");
	this.shape_13.setTransform(22.5,-5.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AsqLiQlekxAAmxQAAmuFekzQFgkxHuAAQDYAADIBAQDBA/CgB1QBkA2BqB9QBmB4ApCaIx1FPIR8FWQgYCBhdB1QhuCIhwBJQiiB7jGBCQjNBEjdAAQnuAAlgkyg");
	this.shape_14.setTransform(22.5,-5.6);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f().s("#000000").ss(2.8,1,1).p("AxJAAQAAmuFekzQFgkyHuAAQDYAADIBBQDBA/CgB1QBOArBTBdQAiAuAYAzIvzIrIP+I3QgbAqgPAdQhVBnhWA4QiiB7jGBCQjNBEjdAAQnuAAlgkyQlekxAAmxg");
	this.shape_15.setTransform(16.2,-5.6);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("ArrLiQlekxAAmxQAAmuFekzQFfkxHvAAQDYAADHBAQDCA/CfB1QBPArBTBdQAiAuAYAzIv0IrIP/I3QgbAqgPAdQhVBnhXA4QihB7jGBCQjOBEjcAAQnvAAlfkyg");
	this.shape_16.setTransform(16.2,-5.6);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f().s("#000000").ss(2.8,1,1).p("AvxAAQAAmuFekzQFgkyHuAAQDZAADHBBQDCA/CfB1QAPAImSGFQjJDDjMDBINOLyQgHAMgFAIQgLARgOAJQihB7jGBCQjOBEjdAAQnuAAlgkyQlekxAAmxg");
	this.shape_17.setTransform(7.4,-5.6);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AqTLiQlekxAAmxQAAmuFekzQFgkxHuAAQDYAADIBAQDCA/CfB1QAPAImSGFQjJDDjMDBINOLyIgMAUQgLARgOAJQihB7jGBCQjOBEjdAAQnuAAlgkyg");
	this.shape_18.setTransform(7.4,-5.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1}]}).to({state:[{t:this.shape_4},{t:this.shape_3}]},1).to({state:[{t:this.shape_6},{t:this.shape_5}]},1).to({state:[{t:this.shape_8},{t:this.shape_7}]},1).to({state:[{t:this.shape_10},{t:this.shape_9}]},1).to({state:[{t:this.shape_12},{t:this.shape_11}]},1).to({state:[{t:this.shape_14},{t:this.shape_13}]},1).to({state:[{t:this.shape_16},{t:this.shape_15}]},1).to({state:[{t:this.shape_18},{t:this.shape_17}]},1).wait(1));

	// Layer 4
	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#231F20").s().p("AjQDwQhxhkgBiMQABiLBxhkQBzhjCgAAQBFAABCAUQA/AVA0AmIkAD/IEFEEQg0AohBAWQhDAWhHgBQigAAhzhjg");
	this.shape_19.setTransform(-5.6,5.6,3.07,3.07);

	this.timeline.addTween(cjs.Tween.get(this.shape_19).wait(9));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-104.7,-111.4,210.9,221.4);


(lib.logoBg = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FCFCFC").s().p("ArXPmIAH/KIWnCeIkRcsg");
	this.shape.setTransform(-1.6,-7.9);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-74.4,-107.7,145.6,199.6);


(lib._img = function() {
	this.initialize();

	// Layer 2
	this.instance = new lib.imgpngcopy();
	this.instance.setTransform(-180,-102,1.585,1.585);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-180,-102,385.1,206);


(lib.ClipGroup = function() {
	this.initialize();

	// Layer 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AoiNJIAA6RIRFAAIAAaRg");
	mask.setTransform(54.7,84.2);

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AAEAGIAAgIIgDAIIgBAAIgDgIIAAAIIgCAAIAAgLIADAAIACAHIADgHIADAAIAAALg");
	this.shape.setTransform(69.8,90.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AAAAGIAAgIIgEAAIAAgDIAJAAIAAADIgEAAIAAAIg");
	this.shape_1.setTransform(68.4,90.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhLCSQAAgHgGgVQgJgdgNgXIAAABIAlAdQAOAJATAJQAEABAHgCQAHgCAEgGIAAABIAAgEQgDgIgsgpIgDgFQAAAAAAAAQAAgBABAAQAAAAABAAQABgBAAAAIAZAAQAWAAgDgVIgEgiQgBgOgMgBQgRgDgeAKQAAAAgBAAQgBAAAAAAQgBAAAAAAQAAAAAAAAQgBAAAAgBQAAAAAAgBQABAAAAgBQAAAAABgBQAhgWAZgdQAggoAMgkQABgBAAgBQABAAAAAAQABgBABABQAAAAABAAQADABAEAHQAGAJADANQAEAcAAAOQACAigJAvQgGArgLAcQgBAEACACQAAAAABAAQAAAAABAAQAAAAABgBQABAAABgBQANgSARhBQALgsAEgvQAIAiAHAeIAAAFQACANAJBVIAEA9QhiAJhFAKIgEAAIgCAAQgGAAAAgFgAgSBBIACAAIAAgNIgEAAIgDAJIgDgJIgEAAIAAANIADAAIAAgLIADALIACAAIAEgLgAgrA2IAEAAIAAALIADAAIAAgLIAEAAIAAgCIgLAAg");
	this.shape_2.setTransform(72.3,84.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFF1E4").s().p("AgLDLIgJgGIgBgBIgDgOQgCgHgFgJIgMgUIgCgLIgBgQIAAgHIAAgEIAAgCQgBAAgBAAQAAAAgBABQgBAAAAAAQAAAAgBABIgEAFIAAADQAAAGgDAFQgCAEgDAAQgFgBgBgHQAAgGgCgDQgBgBAAAAQgBgBAAAAQgBAAAAAAQgBAAgBAAIgHACQgIACgJAAIgGABIAAgBQgCgHgGgCQgMgCgEgCQgDgDACgCQAIgHAEgCQAPgFAEAAQAhABAVgHQANgEASgJQAGgDADABQAKAEADAFIACANQACANADAGQACAIAFgEQAEgDACgGQACgJAAgMQAAgPAFgGQAHgHAEgQQADgKgDgVIAAADQAIgGABgGQACgLgFgJQgFgIgMgIQgOgJgMgNIgKgKIgNgJQgNgGgNABQgIABgCACQgEACgDAEQgDACAEAHIADAJQAEAJgFAFQgHAHgKAGQgRALgNgBQgNAAgLgFIgDgEIgHgQIgCgJQgBgHAAgFIAEgWQABgFgBgIIgBgOIgBgqIAHgCQAFgBAGACQAGADABAEQAJAXALAFQADACAGgGIAEgFQACgEgBgBIgGgJQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBABAAIADAAQAUAJAUgBQAJAAARgFIAPgGQAGAAADAEIAEAGIABABIAAAAIAAABIABAAIAAAAIgDABQgBAAAAAAQgBAAAAAAQAAAAAAABQgBAAAAABQgCACADADQAEAGAAAEQAAAHgCADQgBAFgEAFIgFAIIAAACIAAACIABABIABABIAAAAIABABIAEADQAAAAABAAQAAAAAAAAQABAAAAAAQABAAAAAAQAEAAAKgEIABgBQAPgJAJgTQAGgMADgsQAAgIAFgEQAQgMAFgBQAEgBADAGQACAGAHAoQABAHAEgDQAFgDAEgHQACgEgBgEQgBgFgCgCQgIgJACgFQAFgMALACQAMACACAbQACAjgTAzQgFAOgDANIgDAQQAAAFgDABQgBAAgBAAQAAAAgBAAQAAAAgBgBQAAAAAAAAIgEgHQAAgBgBAAQAAAAAAAAQAAAAgBAAQAAAAAAABQgCABAAAEQgCAIgHALQgBACAAAIQAEAcgBAcQgCA6gcAmQgdAmgeASQgCADgEAAIgGgBg");
	this.shape_3.setTransform(64.4,56.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFF1E4").s().p("AANA4IgNgTIgEgGIgDgGIgBgGQgJgBgHgCIgCgBQgKgFgFgDQgNgHgJgQQgCgEAEgEIAIgFQADgCAFADQAMAHADAAQAEgBACgDIALgOQALgJANgBIAXABQAOAAAJgGQAFgEACACQACACgEAEIgBACIgBAAIgBADQgEAEgEACIgJAEQgFACAAAFIADAJQAAAFgFAKQgFAGgIAFIgHADIgBADIAAABIAAABIAAABIABADQACAFAIgCIAQgEQAKgDADgDIAEgDIgEAEIgCACIAAABIgEAHQgEAHgBALQgBAEgGADQgDABgLAIIgEABQgBAAgBAAQAAgBgBAAQAAAAgBAAQAAgBgBAAg");
	this.shape_4.setTransform(38.9,48.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFF1E4").s().p("Ag8B/QgMgHgLgFQgVgJgbABQgkACgXACQACgRgCgaQAIhPAQgiQALgXAEgEIAAgCIAAgEIAUgEQAdgFAaAIQAPAFACgDQAEgCALgNIABgCIABAAIAAgDIgBgCQAPgNAGgEQAQgMAKABQAXABAZAGQAkAIAUAOQAgAVALAbIgCAAIAAABIAAAAIgBABIAAABIABACIAHAnIABAKQADALALANQANAQADAMIAEATIAAACQAAABAAAAQgBAAAAABQgBAAAAAAQgBAAgBAAQgdgBgKAAQgJAAgjAEQgoAFgRADQghAHgPASIgJAHIgKgBQgNgBgKAFQgHADgFAAIgFgBg");
	this.shape_5.setTransform(54.2,25.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgBBJIggiNIAggEIAjCRg");
	this.shape_6.setTransform(89.8,106.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgDBEIgaiDIAdgEIAeCHg");
	this.shape_7.setTransform(82.4,106.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgJBAIAAgGIgPhzIAAgBIAbgFIAXB/g");
	this.shape_8.setTransform(75,107);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgyhSIAAgCQAAgGAJABIBcAHIgYCsg");
	this.shape_9.setTransform(94.6,85);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgZBqIgXiuIBCgiQAHgDAJAAIAHAAIAIACQgJAOgSBUQgHAVgPBag");
	this.shape_10.setTransform(16.5,102.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgKAEIAAgFQAAgBAAAAQAAgBAAAAQAAAAABAAQAAgBABAAIAQgCQABAAAAABQABAAAAAAQABABAAAAQAAABAAAAIAAAFQAAABAAAAQAAABAAAAQgBABgBAAQAAAAgBAAIgOABIgBABQgBAAAAgBQgBAAAAAAQAAAAAAgBQgBAAAAgBg");
	this.shape_11.setTransform(70.1,35.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgJAGIgBgGQgBgBAAAAQAAgBABAAQAAgBAAAAQABAAAAAAIAQgDQABAAAAAAQABAAAAAAQAAABABAAQAAABAAABIACAFQAAAAgBABQAAABAAAAQAAAAgBABQAAAAAAAAIgNACIgDAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAgBAAAAg");
	this.shape_12.setTransform(29,40.9);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("ADhCFQgSgmghgyQAAAAgBgBQAAAAgBAAQAAgBAAAAQgBAAAAAAQgLgbgggTQgUgOgkgIQgZgGgXgBQgMgBgOAMQgGAEgPANIgDgDQgNgJgQgHQghgPghgBQgggBgiAJIglANIgEABIgDgBQgBAAAAgBQgBAAAAgBQAAAAAAgBQAAAAABgBQAEgGAHgHQAfgcAVgJIAJgEQADgCAAgEQAAgEgGAAIgPACQgBAAgBAAQgBAAAAAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQgBgBAAAAQAAgBABgBQAAAAABgBQAFgGAMgHQAPgIAZgIQAWgIAPgDQAagGAQgBIAgABQAiABAkAMQAnALAfAUQApAfAXAiQAkAzAHBPQACAPgCALQgBAEgCACIgCABQgBAAAAAAQAAgBgBAAQAAgBgBAAQAAgBAAgBg");
	this.shape_13.setTransform(52.2,16.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgsAFQgBAAAAgBQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAgBQABAAAAAAQABgBAAAAQABAAABAAIAWgEQAUgEAigCIAJAAIADABQABAAAAABQAAAAAAABQgBAAAAABQgBAAgBABQgPAFgQADIglAIQgLAAgJgGg");
	this.shape_14.setTransform(55.6,62.6);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AhvAjQgCgDAFgDQAIgDAJgIQALgRAGgCQADgDAHgBQAJgCAHAEQARAGAagDQAKAAAGgNQACgEAKgFQAJgDANgOQAEgDAHAEQAGAEAHAHIANAOQAJAMAQABQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABABIABADQAAADgFADQgGAFgQAAQhpADg7AUQgKADgHAAQgKAAgFgGg");
	this.shape_15.setTransform(55.2,56.9);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgQAVIAFgIQADgDADgHQABgDAAgFQAAgEgEgGQgCgDABgCQABAAAAgBQAAAAAAAAQABgBAAAAQAAAAABAAIAEgBIAIAAIAHABQAEABAAAFQgBARgQANIAAABIAAgBQgDAEgGACIgGADIAAAAg");
	this.shape_16.setTransform(66.6,44.4);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAQBWIgLgIQgcgUgNgQQgNgQgCgQQgBgKAEgYQAEgUgIgXQAAgBAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAAAQABAAAAAAQABAAABAAQAAAAABAAQACACALAMQAFAGABgIQAAgJgCgKIAGgBQAIAAAIgCIAIgCQAAAAAAAAQAAAAABAAQAAABABAAQAAAAAAABQACADABAGQAAAHAFABQAEAAACgEQADgFAAgGIAAgDIAEgFQAAAAABgBQAAAAABAAQAAAAABAAQABgBAAAAIABACIgBAEIAAAHIABAQIADALIALAUQAFAJACAHIAEANQgBAAAAAAQAAAAgBAAQAAAAAAAAQgBAAAAAAIgBAEIADALQADALgLASQgQAbACAPQAAABAAAAQAAABAAAAQAAAAgBABQAAAAAAAAIgDABQgEAAgGgEg");
	this.shape_17.setTransform(56.8,76.3);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgZAbIAHgEQAIgEAFgJQAEgIAAgFIgCgIQgBgFAEgDIAIgEQAFgCADgEQgBAEADAEIAHAHIACABIAAACQAAALgKAKQgFAGgNAHQgFADgJACIgKABIgBABg");
	this.shape_18.setTransform(43.2,47.2);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AAHAZQgDgCgEgLQgIgMgFgLQgBgHADgCIAJgEQAEgDABAIQACARAHAQIACAGQABAEgDABIgCABIgDgBg");
	this.shape_19.setTransform(26.7,45.4);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgnB3QgGgNgEgZQgEgdABgiQACgVgLgOQgLgOgBgDQgDgFAGgEQACgCAHABQAWgGARgOIAYgWQASgPAJgFQAOgIAGgBQAJgEAMgBQABgBABAAQAAAAABABQAAAAABAAQAAAAABABQAAAAAAAAQAAABAAAAQAAABgBABQAAAAgBABQgJAFgHAGQgPALgNATQgHAMgFALIgGAQQgDAFgDAEIgGAIQgJAJgDAKQgLA0AFAuIABAKQAAAFgEACIgJAFIgDABQgDAAgCgDg");
	this.shape_20.setTransform(28.2,28.6);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgKASIAAgCQAJgOACgPQADgIABAHQAFAOABAJIAAAEQAAAAAAABQgBAAAAABQgBAAAAAAQgBABgBAAIgPADIgCgBg");
	this.shape_21.setTransform(58.5,98.9);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AhXByIgGgWQgDgKgCgoQgEguADgeIATAlQAFAJAOATIAYAaIAFAGIAYAVIAGAEIAEADQAKABAHgEQAFgCACgEQACgCgBgFIAAABQABgFgEgEQgPgPgTgeQgQgWgOghQgLgZgEgTQgFgPAAgaQAJAIAQALIAaATIAZAPQgFADgCADIgJADQgJAGABAOIAEAXQAEANABAGQAGAMAKABQAHABASgDIAbgGIgMAYIgEARQAAAGAEgFQALgUARgUIAGgHIAKgCQABAAgHAJIgLAcQgLAcgIAOIgFAMIiAAXIgHABQgIAAgEgFg");
	this.shape_22.setTransform(44.2,92.2);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AlsI2IAFgcQAEgYAThDIAThFQABgGAAgGQgCgGgEgBIgagGIgHAAQgJAAgHADIhEAiIgEgaQAvgdA3gYQAcgNAWgIQAFgCACgDIAGgIQAHgIAIgFIAdgPQAHgDADgNQANg2AFgLQACgFgBgDIgJgMQgVgagLgjQgDgJgGgEIgQgJQgVgNAAgeQABgSgKgHQgJgIgWgeQgMgRgLggQgEgJAAgOQAAgOADgHQADgGgGgFQgUgPgGgMQgGgLAGgMQADgEAFgdQAGgkgLgWQgCgGgKgLQgIgMgEgHQgDgJABgJQABgHAEgDQAMgHAFgFQAQgMAQgWQAMgRAFgLQAFgJgCgJQAAgGgCgDQgDgIAAgGQAAgDAEgEIAIgDIAXgJQAXgIAOgHIAmgWIAigQIAcgKQAVgJAVgDQAWgEAVgCQAVAAAZACQAjADAeAMQAeAKAdAPIAcASQAgAYATAYQAlAwAOBAQACALAIAFQAEACABAFQAFAQgCAbQgDATgFAQQgFAOAKAJQAUASgCArQgBATgHAeQgHAZgIAVQgHAQAAAQIABAXQACAKgPAIQgIADABALQAAAcgFAhQgCAIADACIAJAIQAIAHAFAGQAMAOAFACIApANQAcAJAMAGIAGAFQADADAEAAIBwALIABAAIgEAWIhdgGQgKgCAAAHIABACIBOCtIgIA/IgQglQhMjFgIgRQgDgFgIgEQgHgDgHgBQgJgBADAJIATA9QAJAfAMAyQALAxADAZQACAIACACQADACAFAAIAHABQAKAAAJACQABAAABAAQAAABABAAQAAABAAAAQAAABAAABQgCACgGAAQgHAAgTADIirAXQhPALhPARQhJAQgvAPQhAATg+AZQgMAEgEgIQgCgDgBgOQgDg2AGhDQAGg+AHgmQAAgBAAgBQAAAAAAgBQAAAAAAgBQgBAAAAAAIgCABIgFACQgFACgCAHQgDAFgEAOIgRBNQgMA8gEAVIgKBNgAjIElIgJAFQgCACgDAUQgCAeAEAwQACAoADAKIAGAWQAFAHAOgDICBgXIAEgBIACAAIAAAAIAKgCIABAAIAAAAIABgBIABAAIAAAAIACgBIABgBIAAAAIABgBIAAAAIACgCIAAgBIABgBIAAAAIABgBIAAgBIABgBIAAgBIABgBIABgBIABgCIAAAAIAAgBIACgEIABgDIAFgJQARgtADgVQADgMgHAEIgCABIAAAAIAAABIgBAAIgDADIgRAPIAAABIgGAGQgSAUgKAUQgBABAAAAQgBABAAAAQgBAAAAAAQAAAAAAAAIgBgDIAEgRQAEgJANgXIABgDQAAgBABgBQAAAAAAgBQAAAAgBgBQAAAAAAAAIgEAAIgYAEQgVAEgJgHQgDgDgBgGIgBgOIgEgdIAAgDIABgDQACgCAFgDIADgCQAIgDALgCIAMgCQAGgBgFgFIgSgIQgfgOgbgTQgRgMgIgIQgCgDgCABQgDABgDAHIgBADIAAABIAAACIAAACIAAAFIgBADIAAABQAAAZAEAQQAFASAKAaQAOAjAQAWQAWAeAOAPQAFAEgBAEIAAABIgBABIAAAAIgBAAIgBABIgCAAIgBgBIAAAAIgBgBQgPgKgggkQgOgPgUgmIgUgmQgBgBAAAAQgBAAAAgBQgBAAAAAAQgBAAgBAAIgCAAgAAeGXQgFARgJAOIAAACIACABIARgDQABAAABgBQAAAAABAAQAAgBABAAQAAgBAAAAIAAgEQgBgJgFgQQAAgBAAgBQAAAAAAgBQAAAAgBAAQAAAAAAAAQAAAAgBAAQAAAAAAABQgBAAAAABQAAABAAABgAA3FMQAAAAgBABQAAAAAAABQAAAAAAABQABAAAAABIAGAKQANAXAJAdQAGAVAAAHQAAAGAIgBIAEAAQBLgKBrgKIAMgCIABgBIAAAAIADgCIAAAAIAAgBIABgEIAAgDIgEgUIAAgBIgJg8IgCgHIAAgCIgJgzIAAgBIgOhCQgFgVgKgDIgCgBIgCAAIgBABIAAAAIAAAAIgBABIAAAAIAAABIgBADIAAALQgEAvgLAsQgRBDgNASQgBAAgBABQgBABAAAAQgBAAAAAAQgBAAAAAAQgCgCABgEQAMghAFgnQAJgwgCgiQAAgOgEgcQgEgWgMgIQgBAAAAgBQgBAAgBAAQAAABgBAAQAAABgBABQgMAkgiAoQgZAdghAWQgBABAAAAQAAABgBAAQAAABAAAAQAAAAABABQAAAAAAAAQABAAAAAAQABAAAAAAQABAAABAAQAdgKARADQAMABABAOIAEAkQADAVgWAAIgZAAQAAAAgBAAQgBABAAAAQgBAAAAAAQAAABAAAAIADAFQAsApADAIIAAAEIgDAAIgDgBIgOgLQgvgigbgIIgBgBIgDABgAgoB7QAAAAAAABQgBAAAAABQAAAAABABQAAAAAAABQAIAXgEAUQgFAZACALQABAQANAQQAOAQAbAUIAMAIQAIAFAFgCQAAgBAAAAQAAAAAAAAQAAgBAAAAQAAgBAAAAQgBgPAQgbQALgSgDgLIgDgLIAAgEQABgBAAAAQABgBAAAAQABAAAAABQABAAABABIAJAGQAHADAGgFQAegSAdgmQAcgmACg6QACgcgFgcQAAgIABgCQAHgLACgIQAAgEACgBQAAgBABAAQAAAAAAAAQABAAAAAAQAAAAAAABIAEAHQAAAAABAAQAAAAAAABQABAAABAAQAAAAABAAQADgBABgFIADgQQACgNAGgOQASgzgCgjQgCgbgMgCQgKgCgGAMQgBAFAHAJQADACAAAFQABAEgCAEQgEAHgFADQgEADgBgHQgGgogDgGQgCgGgFABQgEABgQAMQgGAEABAIQgEAsgFAMQgKATgPAJIgBABIgCAAIgBgBIgBAAIgBgBIgDgHIAAgCIABgBIABgBQAQgNABgUQAAgEgEgBIgHgBIgKAAIgBAAIAAAAIgBgBIAAAAIgBgBIAAAAIgEgGQgDgEgGAAIgRAGQgRAFgJAAQgTABgVgJIgDAAQgBAAAAABQAAAAgBABQAAAAAAABQAAAAABABIAFAJQACADgGAHQgFAGgDgCQgLgFgJgXQgBgEgFgDQgHgCgFABIgGACIgEABIAAAAIgCABIgCACIAAAAIgBABQgDADgCAHQgDAIABAHIADAdQAAAGgDAUQgDAQACAFIABACIAAABIABACIAAABIACADIABABIACACIABABIADADIABABIADADIABAAIAFADIAAABIAFACIABAAQALAFANAAQANABAPgLQAKgGAIgHQAEgFgDgJIgEgJIAAgBIABgBIAAgBIABgBIAAAAIABAAIAAAAIABgBIAEAAQASACAQAQIAOAOQAIAJAHAFQAHAEAHADIAIADQAEADACACQADAFABAKQAEAWgDALQgEAQgGAHQgFAGgBAPQAAAMgCAJQgCAGgEADQgFAEgCgIQgDgGgCgNIgCgNQgDgFgMgEQgDgBgGADQgSAJgMAEQgWAGgeAAQgFAAgOAFQgFACgIAHQgBACACADQAEACAMACQAGACACAHQADALgBAJQgBAIgEgGQgLgMgDgCIgCgBIgCABgAijAeIgKAEQgGAEgEANQgEAOAGAOQAVA1AjAZQAaASATgDQALgDgGgLIgSgqQgDgEgDABQAAAAgBABQAAAAgBAAQAAABAAAAQAAABAAAAIgFAOQgCAKgIgJQgNgOgMgmQgJgcgCgNQAAgGgFgBIgEgBIgCAAgAAhAwQghACgVAEIgWAFQgGABAEAEQAKAGAKAAIAmgHQAPgDAPgIQABgBABAAQAAgBABAAQAAgBAAAAQAAgBgBAAIgDgBgAhFgCQgHABgDABQgGAEgKAQQgKAIgHAEQgGADACADQAJALAYgJQA6gTBpgDQARgBAGgEQAEgDAAgEIgBgDQAAAAgBgBQAAAAgBAAQgBgBAAAAQgBAAAAAAQgQgBgJgKIgNgPQgGgHgHgEQgHgEgEAEIgIAIQgIAHgGACQgKAFgCADQgGAMgKABQgaAEgRgHQgEgCgFAAIgHABgAjag0QgCABACAEIACAFIABACIACAEIAJAMIAMAMIAAAAIAFAFIAEACIAAABIACABIABABIAFABIAGAAIACgBIAAAAIAFgCIADgCIABAAIADgDIAGgGIABAAIAFgFQALgHADgBQAGgEABgEQABgLADgHIAFgGIAAgBIACgCIALgLQASgUgBgTQAAgBAAgBQAAAAAAgBQAAAAAAgBQAAAAAAAAQgBgBAAAAQAAAAAAAAQgBAAAAAAQAAABAAAAIgHAHIgCABIAAAAIgCABIgCgBIgHgHQgDgEABgEIACgCIABAAIABgDQADgEgBgBQgDgCgFADQgIAGgOAAIgXAAQgQAAgLAKIgKANQgCAEgFAAQgFAAgJgGQgFgEgDADIgIAFQgFADADAEQAJAQAMAJQAFAEALAEIADACIAAABIAAABIABAAIAAACIgBABIAAACIAAAAIAAABIAAACQgDAGgGgCIgKgDIgGgDIgCgBIgBABgAhcg6QgDAFAAAHQAAAJAGAGQAFAGAGAAQAEAAABgDQAAgFgDgEQgGgJAFgNQAAgDgFgBIgCAAQgFAAgDAFgAkkiJIgIAEQgEACACAHQAEANAIANQAHAKACACQADACADgCQACgBAAgEIgCgGQgIgSgCgRQAAgGgEAAIgDABgAibipQgFABgKAFQgIAFgGAFIgKAIIgLAHQgCADACACIAFABQAGAAAJgFQARgLAIgEQAJgDAPAAQAFABgCgEQAAgDgEgDQgGgFgJAAIgDAAgAjNinIgVAGQgGACgEAGQgEAFAAAEQgBAGAFACQAEACAFgEIAbgWQACgCgBgDQgBgCgDAAIgCAAgAkTihQgBAAAAABQAAAAAAAAQgBABAAAAQAAABAAAAIACAJQAAACAGgBIAPgCQAAgBAAAAQABAAAAgBQAAAAAAgBQAAAAAAgBIgBgHQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAAAgBAAgAlYlEQgGAEADAFQADAGAJAMQALAOgCAXQgBAhAEAdQADAaAHAMQACAFAFgCIAKgFQAEgCAAgGIgBgKQgFguAKg0QADgLAKgJIAHgIQAEgEACgGIAHgPQAEgMAIgLQANgTAOgMQAIgGAIgEQABgBABgBQAAgBABAAQAAgBAAAAQAAgBgBAAQAAAAAAgBQgBAAAAAAQgBAAgBAAQAAAAgBAAQgNACgJADQgFACgOAIQgJAFgSAPIgaAVQgSAOgVAGIgEAAQgEAAgBABgABNivQAIAFAKADQAHAEAFgDQABgBABAAQAAgBABAAQAAgBAAAAQgBgBAAAAIgFgCQgIgDgNgLQgLgIgKABIgIABQgHADgLALQAAABAAAAQAAAAAAABQAAAAAAABQAAAAAAABQAAAAABAAQAAABABAAQAAAAABAAQABAAABAAIANgFIAJgBQAHAAAHAEgAhijAQALAFAMAHQAIADAJgFQALgFAMABIAKABQAFgCAEgFQAQgSAhgHQAQgDAogFQAkgEAIAAQALAAAcABQABAAABAAQABAAAAAAQABgBAAAAQAAAAAAgBIAAgCIgEgTQgDgMgNgQQgLgNgDgLIgBgMIgHgnIgBgCIAAgBIABgBIAAAAIAAgBIACAAQAAAAABAAQAAAAABAAQAAAAABABQAAAAABABQAgAyASAmQACAFADgCQACgCABgEQACgLgCgPQgHhPgjg1QgYgigpgfQgegUgngMQgjgLgkgBIgggBQgQABgZAGQgQADgWAIQgZAIgPAIQgNAIgEAFQAAAAgBABQAAABAAAAQAAABAAAAQAAABAAAAQABAAAAABQABAAAAAAQABAAAAAAQABAAABAAIAPgCQAGAAAAAEQAAAEgDACIgIAEQgWAJgfAcQgHAHgEAGQAAABAAAAQAAAAAAABQAAAAAAABQAAAAABABIADABIAEgBIAlgNQAjgJAgABQAgABAhAPQAQAHANAJIAEADIAAACIAAADIAAAAIgBACQgMANgEACQgCADgPgFQgagIgcAFIgVAEIAAAAIgEABIgBAAIgEACIgBAAIgEACIgBABIgDABIgGAEIgIAIIgBACIgEAFQgVAfgHAnQgCAMgCAiIgBAKQgBAHgCACIgKAJQgCACgBAGIACAPQABAGAHAAIAGgCIAHgBIADgBIAKgCIADAAIAHgBQAXgDAlgCIAFgBQAZAAASAJgABXjNQAAAAgBAAQAAABAAAAQgBAAAAABQAAAAAAABQgBAAAAAAQAAABAAAAQAAAAABABQAAAAABAAQAEABAJAHQAKAHAHABIAEAAQABgBACgEQADgIgKgGQgFgDgKAAIgOABgACGjVQgBAAAAAAQgBAAAAABQAAAAAAAAQAAABAAABIAAAHQAAAAABABQAAABAAAAQABAAABAAQABAAABAAIAPgBQABAAABgBQAAAAABAAQAAgBAAAAQABgBAAAAIgBgHQAAgBAAAAQAAgBgBAAQAAgBAAAAQgBAAgBAAg");
	this.shape_23.setTransform(55.7,56.7);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#F5D4BA").s().p("AgkBpQARhaAHgVQAQhUAJgOIASAEQAEABACAGQABAGgCAGIgTBFQgRBBgEAYIgFAcg");
	this.shape_24.setTransform(20.1,102.8);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#F5D4BA").s().p("AAmBMIgFgDIgGgEIgZgVIgagfQgOgSgFgJIgUgmQACgUADgCIAIgFQAFgBACADIAUAmQAVAlALAOQAhAlAOAJIACABIAAAAIABABIACAAIABgBIABAAIAAAAIAAgBIAAgBQABAEgBADQgCADgFADQgGACgGAAIgGAAg");
	this.shape_25.setTransform(40.6,93.7);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#F5D4BA").s().p("AgGAYIgZgTQgQgJgJgIIAAgBIAAgDIAAgFIABgCIAAgCIAAgBIABgDQADgHACgBQACgBADADQAIAIARAMQAZARAfAOIASAIQAFAFgGABIgMACQgLACgIADIgDACg");
	this.shape_26.setTransform(43.9,81.7);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#F5D4BA").s().p("AgPAoQgJgBgGgMQgEgGgDgPIgFgWQgBgOALgGIAKgDIgBADIAAADIAEAdIABAMQABAHADACQAJAHASgEIAZgEIAEAAQAAAAABAAQAAABAAAAQAAABAAABQgBAAAAABIgCACIgEAJIgcAGQgLADgIAAIgEAAg");
	this.shape_27.setTransform(47.6,90.2);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#F5D4BA").s().p("AAbAeQgTgIgMgJIgkgcIgBAAIgGgKQAAgBgBAAQAAgBAAAAQAAgBAAAAQABgBAAAAQABgBAAAAQABAAAAAAQABAAAAAAQABAAABAAQAbAJAsAfIAOALIACABIAAAAIAEAAQgEAFgHADIgHABIgEgBg");
	this.shape_28.setTransform(66,93);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#F5D4BA").s().p("AgYAqQAIgOALgcIAJgaQAHgJgBAAIgKADIAAgBIARgPIAEgDIAAAAIACgBIAAAAIACgBQAHgEgCAMQgEAVgTArIgHAQIAAABIAAAAIAAACIgBABIAAABIgBABIgBABIAAABIgBABIAAAAIgBABIAAABIgCACIAAAAIgBABIAAAAIgBABIgBABIgBAAIAAAAIgBABIgBAAIgBAAIgJACIgCAAIgBAAIgDABIAFgNg");
	this.shape_29.setTransform(53.3,96.3);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#F5D4BA").s().p("AANBCIgFgDIAAAAIgFgDIgBgBIgCgDIAAAAIgDgEIgBAAIgCgDIgBgBIgCgDIAAAAIgBgDIgBAAIgBgDQgBgFACgQQAEgSAAgGIgDgdQgBgGADgIQACgHACgDIABgCIABAAIACgBIAAgBIAAgBIADgBIABAqIABAOQABAJgBADIgEAWQAAAEABAIIACAIIAFAKIACAHIADAEg");
	this.shape_30.setTransform(50.2,46.9);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#F5D4BA").s().p("AgEAIIgDgDIgBgBIgBAAIAAgBIgBAAIAAgBIAAgCIAGgBQAEgDAEgDIAAAAIgBACIAAACIADAEIABABIABAAIABABIACAAQgKAFgBAAg");
	this.shape_31.setTransform(66.1,46.7);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#F5D4BA").s().p("AAGAdIgFgBIgBgBIgBgBIAAAAIgDgDIgMgKIgFgGIgJgLIgCgEIgBgBIgDgGQgBgDACgCQAAAAAAAAQAAAAABAAQAAAAABAAQAAAAABAAIAGADIAKAEQAHABABgGIAAgBIABgBIAAgBIAAgBIABgBIAAgCIgBgBIAAgBIAAAAIgBgBQAGACAHABIACAGIADAGIADAGIAQARQADADAGgCIgGAEIgBABIgIAIIgBABIgDACIgFACIgBAAIgBAAg");
	this.shape_32.setTransform(37.4,53.4);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#F5D4BA").s().p("AgfAcIgCgDIAAgBIAAgBIABgBIABAAIAKgCQAJgCAFgCQANgIAFgGQAJgJABgLIAAgDIABAAIABAAIACgCIAGgGQABgBAAAAQAAAAAAAAQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQABATgSATIgMAJQgCADgIADIgRAEIgDAAQgFAAgBgDg");
	this.shape_33.setTransform(43.8,47.9);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#F5D4BA").s().p("AAvAqQgBgMgDgEQgCgDgFgDIgIgDQgGgCgHgFQgHgEgIgIIgMgOQgQgPgSgCIgEAAIgBAAIgBAAIAAABIgBAAIgBABIAAABIAAAAIAAACQgEgHADgDIAHgFQACgCAIgBQANgCANAHIAMAIIALALQAMAMAOAJQAMAGAFAIQAFAKgCAKQgBAIgIAHg");
	this.shape_34.setTransform(64.1,52.4);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#F5D4BA").s().p("AgoBeIgCgQQABgFACgDIAKgIQACgDABgGIABgKQACgjACgJQAHgoATgfIAEgFIABgBIAIgIIAGgEIADgCIABgBIAEgBIABgBIAEgBIABgBIAEgBIAAAAIABAFIgBACQgEADgLAYQgQAhgIBQQACAZgCASIgBAAIgFACIgDAAIgKACIgGABIgKACIgCAAQgFAAgBgFg");
	this.shape_35.setTransform(34.7,27.7);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#F5D4BA").s().p("AgCA9QgJhUgDgNIAAgGQgGgdgIgjIAAgLIABgCIAAgBIAAAAIABgBIAAgBIAAAAIABAAIABAAIABAAIABAAQALAGAFATIAMBBIAAACIAJAxIAAACIALBDIAAABIADATIAAAGIAAABIgBABIAAABIgCACIAAAAIgBAAIgHACIgSACg");
	this.shape_36.setTransform(82.7,85.6);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#F5D4BA").s().p("AADA3QgggYgWgzQgGgOAEgPQAEgNAHgDIAJgEQADgBADABQAFACAAAGQACANAJAcQALAkAMANQAIAJADgJIAEgOQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAABAAQADgCACAFIASApQAHAMgLACIgGABQgSAAgWgQg");
	this.shape_37.setTransform(42.6,66.8);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#F5D4BA").s().p("AAMALQgFgBgKgHQgJgFgFgBQAAgBgBAAQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAAAABgBQAAAAAAgBQABAAAAAAQABAAAAAAQATgDAIAFQAJAGgCAGQgCAEgBABIgEAAg");
	this.shape_38.setTransform(66.1,37);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#F5D4BA").s().p("AAVALQgKgEgIgFQgHgDgNABIgOAFQAAAAgBAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAAAgBQgBAAAAgBQAAAAABgBQAAAAAAgBQALgJAHgDIAIgBQAJgBAJAIQANAJAJADIAFACQAAABABAAQAAABAAAAQgBABAAAAQgBABgBAAIgEACQgEAAgFgDg");
	this.shape_39.setTransform(63,38.7);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#F5D4BA").s().p("AgDANQgGgGAAgHQgBgHADgFQAEgGAEABQAGABgBADQgEAMAGAIQADAEAAAFQgBACgEAAIgBAAQgFAAgDgFg");
	this.shape_40.setTransform(47.1,52.1);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#F5D4BA").s().p("AgiARQgDgCADgDIAVgNQAFgFAIgFQAJgFAEgBQAMgBAHAGQAEADAAADQABADgEAAQgPAAgJADQgLAEgNAJQgIAFgGAAIgCAAIgDgBg");
	this.shape_41.setTransform(38.6,41.5);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#F5D4BA").s().p("AgQAOQgEgBABgGQAAgEAEgDQAEgHAGgCIATgFQAFgBABADQABACgDADIgZAUQgDACgDAAIgDgBg");
	this.shape_42.setTransform(33.6,41.4);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#C40C32").s().p("AgDBHIgeiIIAkgFIAfCNg");
	this.shape_43.setTransform(86,106.3);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#C40C32").s().p("AgKBCIgWh+IAmgFIAbCDg");
	this.shape_44.setTransform(78.7,106.7);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#C40C32").s().p("AjzCEIAKhNQADgVANg6IARhNQAEgOACgFQADgHAEgCIAGgCIACgBQAAAAAAABQABAAAAAAQAAABAAAAQAAABAAABQgHAmgGA+QgHBGAEAxQABAOACADQAEAIALgEQA6gXBFgWQAwgOBIgQQBRgRBMgLIAAABIAPB1IABAGg");
	this.shape_45.setTransform(49.5,100.1);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#C40C32").s().p("AAgDFIgiiTQARgDAGAAQAGAAACgCQAAgBAAAAQAAgBAAAAQAAgBgBAAQgBgBgBAAQgJgCgKAAIgHgBQgEAAgCgCQgCgCgBgIQgEgZgLgvQgLgygKgfIgSg9QgDgJAIABQAHABAHADQAIAEADAFQAIARBLDDIAPAlIgTCDg");
	this.shape_46.setTransform(89.9,93.7);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#C40C32").s().p("AiumsIEtAAIg0AJIgXAJIgHADQgFAEAAADQAAAGADAIQACADABAGQABAJgFAJQgFALgMARQgQAWgNAMQgGAFgLAHQgEADgCAHQgBAJAEAJQADAHAJAMQAJALACAGQAJAWgGAkQgDAdgCAEQgHANAGAKQAFAMATAPQAHAFgEAGQgDAHAAAOQAAAOAEAJQAMAeAMARQAVAeAJAIQAKAJgBASQAAAeAVANIAQAJQAGAEADAJQALAjAWAaIAIAMQACADgCAFQgGALgMA2QgEANgHADIgcAPQgIAFgHAIIgHAIQgCADgFACQgWAIgbANQg1AYgvAdg");
	this.shape_47.setTransform(17.5,50.2);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#C40C32").s().p("ABvFOIhvgLQgCAAgDgDIgHgFQgMgGgbgJIgqgNQgEgCgNgOQgFgGgHgHIgJgIQgDgCACgIQAEghAAgcQAAgLAHgDQAPgIgBgMIgCgXQABgQAGgQQAIgUAIgaQAHgeABgRQACgrgUgSQgKgJAEgOQAFgQADgTQADgbgFgQQgCgFgEgCQgCAAgCgEQgFgFgBgHQgOhAglgwIgpggIGagBIheKbg");
	this.shape_48.setTransform(88.8,41);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#C40C32").s().p("AgHANQgDgCgCgEQgDgEAAgDIADgGIAFgGQAEgCADAAQAEAAAEACQADACACAEQACAEABACQgBAEgCADQgCAEgDACQgEACgEAAQgDAAgEgCgAgIgIQgDAEAAAEQAAAFADAEQAEADAEAAQAFAAADgDQAEgEAAgFQAAgEgEgEQgDgDgFAAQgEAAgEADgAACAIIgCgGIgBgBIAAAAIAAAHIgFAAIAAgPIAGAAQABAAABAAQAAAAABAAQAAABABAAQAAAAABAAQAAABAAAAQAAAAABABQAAAAAAABQAAAAAAABIgBACIgEABIACAAIAEAHgAgBAAIABAAIABAAIAAgCIAAgBIgBgBIgBAAg");
	this.shape_49.setTransform(96,124.7);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#C40C32").s().p("AAABNQgagsgOgUQgHAcgCAUQgCAgAMABIgEAQQhWABglgBIACgQQAHAAAGgCQALgCAIgZQAEgTANhLQAGgfAAgNQABgUgOgCIADgPIB3AAIAAABIgBANQgPADgIAeQgFARgHAjQA9gpAigiQAJgKgWAAIADgOIB2AAIgCAPQgSADgTAPIggAbIg1AqIAaAoQASAcAKAOQAQAUARAAQAAAIgDAIQgMABgNAAIgfAAIgBAAQgsAAgagig");
	this.shape_50.setTransform(32,134.4);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#C40C32").s().p("AgMByQg0gFgegZQgjgdAFgyQAEgwAxgiQAsgeA6gFQAVgCAdACQAaABATAGIgOA4QgHgBgJgGIgPgJQgmgQgqAUQgqAUgCAlIAAANQAJA1BAAIIASAAQAYgDAagIIgMAwQgVAEgiADIgYAAIgTAAg");
	this.shape_51.setTransform(80.4,134.5);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#C40C32").s().p("AhxBtIAMhHIAPhKIAGgnQACgTgLgBIADgOICUAAIAkAAQANAAADABIgFAVIgJAmQgGAAgGgHQgFgHgGAAQgNgBgZAAIgnABQgDAPgEAcIBMAAQgBAKgEAOIgGAaQgKgGgNgBQgZgCgaAAQgHAdABAQQAAAbAQADIgEAOQhWAAgRgBg");
	this.shape_52.setTransform(59.3,134.3);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#000000").s().p("AAAAJIgBgCIAAgMIgEAAIgCgBIAAgCIAAgBIACAAIALAAIACAAIAAABIAAACIgCABIgEAAIAAAMIgBACIgBABIAAgBg");
	this.shape_53.setTransform(92.7,148.4);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#000000").s().p("AAiBOQgEgEAAgJIAAgDQgFAHgHAFQgGAEgHACQgFACgIAAQgLAAgJgEQgJgFgGgIQgHgIgEgMQgDgLAAgNQAAgbAOgPQANgQAXAAQAKAAAJAFQAKAEAIAJIAAgsQAAgJADgEQAEgFAHAAQAHAAADAEQAEAEAAAJIAACBQAAAIgEAFQgEAEgGAAQgGAAgEgEgAgNgKQgHAFgDAGQgEAKAAALQAAALAEAJQAEAJAGAEQAHAEAGAAQAIAAAGgEQAGgDAEgJQAEgIAAgNQAAgNgEgIQgDgFgHgGQgHgFgHAAQgHAAgGAFg");
	this.shape_54.setTransform(84.7,155.6);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#000000").s().p("AgXA4QgLgEgIgJQgIgIgEgLQgEgKAAgOQAAgNAEgKQAEgLAIgJQAIgHALgFQAMgEALAAQANAAALAEQALAFAIAIQAHAIAFALQAEAMAAALQAAAMgEAMQgFALgHAIQgIAIgLAFQgKAEgOAAQgLAAgMgEgAgOggQgHAEgDAJQgEAKAAAJQAAAJADALQAEAJAHAEQAHAFAHAAQAMAAAJgKQAIgKAAgSQAAgRgIgKQgJgKgMAAQgHAAgHAFg");
	this.shape_55.setTransform(72.1,157.8);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#000000").s().p("AgXA4QgLgEgIgJQgIgIgEgLQgEgKAAgOQAAgNAEgKQAEgLAIgJQAHgHAMgFQAMgEALAAQANAAALAEQALAFAIAIQAHAIAFALQAEAMAAALQAAAMgEAMQgFALgHAIQgIAJgLAEQgKAEgOAAQgLAAgMgEgAgOggQgHAEgDAJQgEAKAAAJQAAAJADALQAEAJAHAEQAHAFAHAAQAMAAAJgKQAIgKAAgSQAAgRgIgKQgJgKgMAAQgHAAgHAFg");
	this.shape_56.setTransform(59.4,157.8);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#000000").s().p("AgcBOQgMgFgGgGQgHgHAAgHQAAgGAEgDQADgEAGAAQAHAAAEAGIAFAGIAGAFIAHADIAKABQAKAAAGgDQAHgDACgGQADgGAAgGIABgVQgIAKgIAEQgIAFgLAAQgPAAgLgIQgMgHgGgOQgGgMAAgSQAAgNAEgLQADgKAHgIQAHgHAJgEQAJgEAKAAQAKAAAKAFQAJAFAJAKIAAgEQAAgHAEgFQAEgEAFAAQAJAAADAFQADAGAAALIAABUQAAAQgEAKQgDALgHAGQgGAHgMAEQgKADgQAAQgQAAgMgEgAgTgxQgIAKAAARQAAATAIAHQAIAJALAAQAHAAAHgEQAHgEADgGQAFgIAAgLQAAgSgIgLQgIgKgNAAQgLAAgIAKg");
	this.shape_57.setTransform(46.6,160);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#C40C32").s().p("AgXA4QgJgDgKgKQgHgIgFgLQgEgMAAgMQAAgKAEgNQAFgLAHgJQAIgHALgFQAMgEALAAQANAAALAEQAMAFAHAIQAIAIAEALQAEAKAAANQAAAOgEAKQgEALgIAIQgHAIgMAFQgKAEgOAAQgMAAgLgEgAgOggQgGAEgEAJQgEAIAAALQAAALAEAJQADAJAHAEQAHAFAHAAQANAAAIgKQAIgLAAgRQAAgQgIgLQgIgKgNAAQgHAAgHAFg");
	this.shape_58.setTransform(33.9,157.8);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#C40C32").s().p("AgbA4QgMgGgFgHQgGgHABgIQgBgFAEgDQAEgEAFAAQAFAAACACIAFAHQAFAIAGAEQAHAEAIAAQAJAAAGgEQAFgEABgGQAAgIgHgDQgGgDgLgEQgMgDgNgEQgJgDgHgHQgFgHAAgKQgBgIAGgIQAEgIAMgGQAKgEAPAAQALAAAIADQAJACAGAEQAGAEAEAFQADAEAAAGQAAAEgDAEQgEADgGAAQgEAAgEgCIgIgIIgIgIQgEgCgGAAQgIAAgGADQgEADAAAGQAAAFADADQAGADAFABIAQAFQAMADALAGQAIACAFAGQAEAIABAHQAAAMgHAJQgFAJgMAFQgMAEgPAAQgPAAgMgEg");
	this.shape_59.setTransform(21.9,157.8);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#000000").s().p("AAHAJIgBgBIAAgMIgEAMIgBABIgBABIAAAAIgBgBIAAgBIAAgCIgDgKIAAAMIgBABIgCABIgBgBIgBgBIAAgPIABgCIACAAIADAAIABABIACALIADgJIABgDIADAAIACAAIAAACIAAAPIAAABIgCABg");
	this.shape_60.setTransform(94.7,148.4);

	this.shape.mask = this.shape_1.mask = this.shape_2.mask = this.shape_3.mask = this.shape_4.mask = this.shape_5.mask = this.shape_6.mask = this.shape_7.mask = this.shape_8.mask = this.shape_9.mask = this.shape_10.mask = this.shape_11.mask = this.shape_12.mask = this.shape_13.mask = this.shape_14.mask = this.shape_15.mask = this.shape_16.mask = this.shape_17.mask = this.shape_18.mask = this.shape_19.mask = this.shape_20.mask = this.shape_21.mask = this.shape_22.mask = this.shape_23.mask = this.shape_24.mask = this.shape_25.mask = this.shape_26.mask = this.shape_27.mask = this.shape_28.mask = this.shape_29.mask = this.shape_30.mask = this.shape_31.mask = this.shape_32.mask = this.shape_33.mask = this.shape_34.mask = this.shape_35.mask = this.shape_36.mask = this.shape_37.mask = this.shape_38.mask = this.shape_39.mask = this.shape_40.mask = this.shape_41.mask = this.shape_42.mask = this.shape_43.mask = this.shape_44.mask = this.shape_45.mask = this.shape_46.mask = this.shape_47.mask = this.shape_48.mask = this.shape_49.mask = this.shape_50.mask = this.shape_51.mask = this.shape_52.mask = this.shape_53.mask = this.shape_54.mask = this.shape_55.mask = this.shape_56.mask = this.shape_57.mask = this.shape_58.mask = this.shape_59.mask = this.shape_60.mask = mask;

	this.addChild(this.shape_60,this.shape_59,this.shape_58,this.shape_57,this.shape_56,this.shape_55,this.shape_54,this.shape_53,this.shape_52,this.shape_51,this.shape_50,this.shape_49,this.shape_48,this.shape_47,this.shape_46,this.shape_45,this.shape_44,this.shape_43,this.shape_42,this.shape_41,this.shape_40,this.shape_39,this.shape_38,this.shape_37,this.shape_36,this.shape_35,this.shape_34,this.shape_33,this.shape_32,this.shape_31,this.shape_30,this.shape_29,this.shape_28,this.shape_27,this.shape_26,this.shape_25,this.shape_24,this.shape_23,this.shape_22,this.shape_21,this.shape_20,this.shape_19,this.shape_18,this.shape_17,this.shape_16,this.shape_15,this.shape_14,this.shape_13,this.shape_12,this.shape_11,this.shape_10,this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0.1,109.4,168.3);


(lib.logo1 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.ClipGroup();
	this.instance.setTransform(0,0.1,1,1,0,0,0,54.7,84.2);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FCFCFC").s().p("Am1OWIkR8rIWNAAIkRcrg");

	this.addChild(this.shape,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-71.1,-91.8,142.4,183.7);


(lib.logo = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.logo1();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-71.1,-91.8,142.4,183.7);


(lib.bulki = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib._img();
	this.instance.setTransform(220.5,0,0.16,0.16,0,0,0,12.5,1);

	this.instance_1 = new lib._img();
	this.instance_1.setTransform(147,0,0.16,0.16,0,0,0,12.5,1);

	this.instance_2 = new lib._img();
	this.instance_2.setTransform(73.5,0,0.16,0.16,0,0,0,12.5,1);

	this.instance_3 = new lib._img();
	this.instance_3.setTransform(0,0,0.16,0.16,0,0,0,12.5,1);

	this.instance_4 = new lib._img();
	this.instance_4.setTransform(-73.5,0,0.16,0.16,0,0,0,12.5,1);

	this.instance_5 = new lib._img();
	this.instance_5.setTransform(-147,0,0.16,0.16,0,0,0,12.5,1);

	this.instance_6 = new lib._img();
	this.instance_6.setTransform(-220.5,0,0.16,0.16,0,0,0,12.5,1);

	this.addChild(this.instance_6,this.instance_5,this.instance_4,this.instance_3,this.instance_2,this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-251.3,-16.4,502.6,33);


(lib.banner = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.site_1();
	this.instance.setTransform(0.1,3.1,0.016,0.016);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(334).to({_off:false},0).wait(1).to({scaleX:0.03,scaleY:0.03,y:4.8},0).wait(1).to({scaleX:0.09,scaleY:0.09,y:10.3},0).wait(1).to({scaleX:0.18,scaleY:0.18,y:19.2},0).wait(1).to({scaleX:0.29,scaleY:0.29,y:30.9},0).wait(1).to({scaleX:0.42,scaleY:0.42,y:44},0).wait(1).to({scaleX:0.55,scaleY:0.55,y:57},0).wait(1).to({scaleX:0.67,scaleY:0.67,y:68.3},0).wait(1).to({scaleX:0.75,scaleY:0.75,y:76.7},0).wait(1).to({scaleX:0.8,scaleY:0.8,y:81.8},0).wait(1).to({scaleX:0.82,scaleY:0.82,y:83.5},0).wait(25).to({scaleX:0.8,scaleY:0.8,y:82},0).wait(1).to({scaleX:0.76,scaleY:0.76,y:77.7},0).wait(1).to({scaleX:0.69,scaleY:0.69,y:70.4},0).wait(1).to({scaleX:0.59,scaleY:0.59,y:60.4},0).wait(1).to({scaleX:0.47,scaleY:0.47,y:48.6},0).wait(1).to({scaleX:0.35,scaleY:0.35,y:36.2},0).wait(1).to({scaleX:0.23,scaleY:0.23,y:24.7},0).wait(1).to({scaleX:0.14,scaleY:0.14,y:15.3},0).wait(1).to({scaleX:0.07,scaleY:0.07,y:8.4},0).wait(1).to({scaleX:0.03,scaleY:0.03,y:4.3},0).wait(1).to({scaleX:0.02,scaleY:0.02,y:3.1},0).wait(1));

	// logo
	this.instance_1 = new lib.logo();
	this.instance_1.setTransform(-99.8,235.9,0.697,0.697);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({alpha:1},9).wait(314).to({alpha:0},10).wait(1).to({scaleX:0.02,scaleY:0.02,x:-1.4,y:1.1,alpha:1},0).wait(1).to({scaleX:0.03,scaleY:0.03,y:0.8},0).wait(1).to({scaleX:0.09,scaleY:0.09,x:-1.3,y:-0.2},0).wait(1).to({scaleX:0.18,scaleY:0.18,x:-1.1,y:-1.8},0).wait(1).to({scaleX:0.29,scaleY:0.29,x:-0.9,y:-3.9},0).wait(1).to({scaleX:0.42,scaleY:0.42,x:-0.7,y:-6.3},0).wait(1).to({scaleX:0.55,scaleY:0.55,x:-0.4,y:-8.6},0).wait(1).to({scaleX:0.67,scaleY:0.67,x:-0.2,y:-10.7},0).wait(1).to({scaleX:0.75,scaleY:0.75,x:-0.1,y:-12.2},0).wait(1).to({scaleX:0.8,scaleY:0.8,x:0,y:-13.1},0).wait(1).to({scaleX:0.82,scaleY:0.82,x:0.1,y:-13.4},0).wait(25).to({scaleX:0.8,scaleY:0.8,y:-13.1},0).wait(1).to({scaleX:0.76,scaleY:0.76,y:-12.4},0).wait(1).to({scaleX:0.69,scaleY:0.69,y:-11},0).wait(1).to({scaleX:0.59,scaleY:0.59,y:-9.2},0).wait(1).to({scaleX:0.47,scaleY:0.47,y:-7.1},0).wait(1).to({scaleX:0.35,scaleY:0.35,y:-4.9},0).wait(1).to({scaleX:0.23,scaleY:0.23,y:-2.8},0).wait(1).to({scaleX:0.14,scaleY:0.14,y:-1.1},0).wait(1).to({scaleX:0.07,scaleY:0.07,y:0.1},0).wait(1).to({scaleX:0.03,scaleY:0.03,y:0.9},0).wait(1).to({scaleX:0.02,scaleY:0.02,y:1.1},0).wait(1));

	// logoBg
	this.instance_2 = new lib.logoBg();
	this.instance_2.setTransform(-99.8,235.9,0.697,0.697);
	this.instance_2.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({alpha:1},9).wait(314).to({alpha:0},10).to({_off:true},1).wait(46));

	// Layer 4
	this.instance_3 = new lib.t4_1();
	this.instance_3.setTransform(-0.3,1.6,0.014,0.014);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(288).to({_off:false},0).wait(1).to({scaleX:0.03,scaleY:0.03},0).wait(1).to({scaleX:0.07,scaleY:0.07},0).wait(1).to({scaleX:0.15,scaleY:0.15},0).wait(1).to({scaleX:0.25,scaleY:0.25},0).wait(1).to({scaleX:0.36,scaleY:0.36},0).wait(1).to({scaleX:0.47,scaleY:0.47},0).wait(1).to({scaleX:0.57,scaleY:0.57},0).wait(1).to({scaleX:0.64,scaleY:0.64},0).wait(1).to({scaleX:0.69,scaleY:0.69},0).wait(1).to({scaleX:0.7,scaleY:0.7},0).wait(26).to({scaleX:0.69,scaleY:0.69},0).wait(1).to({scaleX:0.64,scaleY:0.64},0).wait(1).to({scaleX:0.56,scaleY:0.56},0).wait(1).to({scaleX:0.47,scaleY:0.47},0).wait(1).to({scaleX:0.35,scaleY:0.35},0).wait(1).to({scaleX:0.24,scaleY:0.24},0).wait(1).to({scaleX:0.14,scaleY:0.14},0).wait(1).to({scaleX:0.07,scaleY:0.07},0).wait(1).to({scaleX:0.03,scaleY:0.03},0).wait(1).to({scaleX:0.01,scaleY:0.01},0).to({_off:true},1).wait(46));

	// price
	this.instance_4 = new lib.price();
	this.instance_4.setTransform(69.8,32,0.011,0.011);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(119).to({_off:false},0).wait(1).to({regX:2,regY:4.2,scaleX:0.02,scaleY:0.02,x:69.9,y:32.1},0).wait(1).to({scaleX:0.06,scaleY:0.06,y:32.3},0).wait(1).to({scaleX:0.12,scaleY:0.12,x:70.1,y:32.5},0).wait(1).to({scaleX:0.2,scaleY:0.2,x:70.2,y:32.9},0).wait(1).to({scaleX:0.29,scaleY:0.29,x:70.4,y:33.2},0).wait(1).to({scaleX:0.38,scaleY:0.38,x:70.6,y:33.6},0).wait(1).to({scaleX:0.46,scaleY:0.46,x:70.7,y:34},0).wait(1).to({scaleX:0.52,scaleY:0.52,x:70.9,y:34.2},0).wait(1).to({scaleX:0.56,scaleY:0.56,y:34.4},0).wait(1).to({regX:0,regY:0,scaleX:0.57,scaleY:0.57,x:69.8,y:32},0).wait(15).to({scaleX:0.68,scaleY:0.68},5).wait(5).to({scaleX:0.57,scaleY:0.57},5).wait(10).to({scaleX:0.68,scaleY:0.68},5).wait(5).to({scaleX:0.57,scaleY:0.57},5).wait(34).to({alpha:0},10).to({_off:true},1).wait(151));

	// t3
	this.instance_5 = new lib.t3_1();
	this.instance_5.setTransform(-134.1,-318.2,0.166,0.166,0,0,0,-42.9,-68.9);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(109).to({_off:false},0).wait(1).to({regX:14.8,regY:0,scaleX:0.18,scaleY:0.18,x:-123.9,y:-306},0).wait(1).to({scaleX:0.21,scaleY:0.21,x:-122,y:-303.7},0).wait(1).to({scaleX:0.27,scaleY:0.27,x:-118.6,y:-299.7},0).wait(1).to({scaleX:0.35,scaleY:0.35,x:-114.1,y:-294.3},0).wait(1).to({scaleX:0.44,scaleY:0.44,x:-108.9,y:-288.1},0).wait(1).to({scaleX:0.53,scaleY:0.53,x:-103.7,y:-282},0).wait(1).to({scaleX:0.6,scaleY:0.6,x:-99.4,y:-276.7},0).wait(1).to({scaleX:0.66,scaleY:0.66,x:-96.1,y:-272.9},0).wait(1).to({scaleX:0.69,scaleY:0.69,x:-94.3,y:-270.7},0).wait(1).to({regX:-43,regY:-69,scaleX:0.7,scaleY:0.7,x:-134.1,y:-318.2},0).wait(25).to({scaleX:0.77,scaleY:0.77,x:-132.5,y:-320.6},5).wait(5).to({scaleX:0.7,scaleY:0.7,x:-134.1,y:-318.2},5).wait(10).to({scaleX:0.77,scaleY:0.77,x:-132.5,y:-320.6},5).wait(5).to({scaleX:0.7,scaleY:0.7,x:-134.1,y:-318.2},5).wait(94).to({regX:14.8,regY:0,scaleX:0.69,scaleY:0.69,x:-94.3,y:-270.7},0).wait(1).to({scaleX:0.66,scaleY:0.66,x:-96.2,y:-273},0).wait(1).to({scaleX:0.6,scaleY:0.6,x:-99.5,y:-277},0).wait(1).to({scaleX:0.52,scaleY:0.52,x:-104,y:-282.2},0).wait(1).to({scaleX:0.43,scaleY:0.43,x:-109,y:-288.3},0).wait(1).to({scaleX:0.35,scaleY:0.35,x:-114.1,y:-294.4},0).wait(1).to({scaleX:0.27,scaleY:0.27,x:-118.6,y:-299.7},0).wait(1).to({scaleX:0.21,scaleY:0.21,x:-122,y:-303.7},0).wait(1).to({scaleX:0.18,scaleY:0.18,x:-124,y:-306.2},0).wait(1).to({regX:-42.9,regY:-69.3,scaleX:0.16,scaleY:0.16,x:-134.1,y:-318.2},0).to({_off:true},1).wait(92));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_149 = new cjs.Graphics().p("A2CO6IAAyXQAXAlAgAhQBjBjCLAAQCMAABihjQBkhjgBiLQABiMhkhjQhihiiMAAQiLAAhjBiQggAhgXAlIAAmLMAsFAAAIAAdzg");
	var mask_graphics_154 = new cjs.Graphics().p("A3HOhIAA9BMAuPAAAIAAdBgAu/D9QhiBiAACMQAACMBiBiQBjBjCMAAQCLAABjhjQBjhiAAiMQAAiMhjhiQhjhjiLAAQiMAAhjBjgAy7oIQhiBjAACLQAACMBiBiQBjBhCMAAQCLAABjhhQBjhiAAiMQAAiLhjhjQhjhjiLAAQiMAAhjBjg");
	var mask_graphics_159 = new cjs.Graphics().p("A08NzIAAlhIEwAAQAUBaBGBGQBjBjCLAAQCMAABjhjQBihjAAiMQAAiLhihjQghghgmgWQAMgrAAgwQAAiJhjhjIgVgUQAZg9AAhHQAAiMhihjQhjhiiMAAQiLAAhjBiQhjBjAACMQAAAiAGAgIgxAAIAAp2MAp5AAAIAAbog");
	var mask_graphics_164 = new cjs.Graphics().p("AhbLwQBegSBKhKQBjhjAAiLQAAiMhjhjQhhhiiLAAQh6AAhbBLQgNhxhUhSIgWgUQAag9AAhHQAAiMhjhjQhihiiMAAQiMAAhiBiQhiBigBCJIglAAIAAOvIlOAAIAA3fMAvNAAAIAAXfg");
	var mask_graphics_169 = new cjs.Graphics().p("AjUJxIAAgGQBjgSBLhLQBhhjAAiLQAAiDhUheQBUhdAAiBQAAiMhhhjQhihiiMAAQiLAAhjBiQgsArgYAzIABgRQAAiMhjhjQhjhiiLAAQiMAAhjBiQgQAQgOASIj1AAIAAlnMAsxAAAIAAXmg");
	var mask_graphics_174 = new cjs.Graphics().p("AnzIrQARgNAQgQQBjhjAAiLQAAiChWhfQBWhcAAiDQAAiLhjhjQgogogwgYQALgpAAgtQAAiMhjhjQhghfiGgDIeTAAIAAWggAwqt1ICxAAQhjAChOA1g");
	var mask_graphics_179 = new cjs.Graphics().p("AnPIqIAAhaQAwhNABhgQAdAEAeAAQCMAABjhjQBihiAAiKQAAiLhihjQhjhjiMAAQhBAAg4AWQgRgWgUgVQgpgogvgYQAKgpAAgtQAAiMhjhjQhfhfiGgDIdhAAIAAWfgAvJt1IAhAAIghACg");
	var mask_graphics_183 = new cjs.Graphics().p("AibJeQBggTBIhKQBjhiAAiMQAAiLhjhjQgegggkgUIABgZQAAiLhjhjQhjhjiLAAQhCAAg4AWQgQgWgVgVQgogogwgYQALgpAAgtQAAiMhjhjQhghfiGgDIfAAAIAAXTgAwFt1IA5AAIgGAAQgaABgZAFg");
	var mask_graphics_189 = new cjs.Graphics().p("AhkJYQBQgXA+hAQBihiAAiMQAAiLhihjQgggggjgUIABgZQAAiLhjhjQhVhVhygMQAbg+AAhJQABiMhkhjQhihiiLAAQg+AAg1ASQhNg1higDId1AAIAAXNgAvct1IAtAAQgXAAgWAEg");
	var mask_graphics_194 = new cjs.Graphics().p("AhOJRQBFgYA2g4QBihiAAiMQAAiMhihiQgggggjgTIABgaQABhRgihDQBKgYA8g8QBjhjAAiLQAAiMhjhjQhhhiiLAAQiKAAhjBgQhhhgiKAAQg+AAg1ASQhNg1hhgDIdIAAIAAXGgAuyt1IADAAIgDAAg");
	var mask_graphics_199 = new cjs.Graphics().p("AEtJeIAAhtQB2gKBXhXQBjhjAAiLQAAiMhjhhQhjhiiLAAQiMAAhjBiQgwAygYA7QgfgegigTIAAgZQAAhRghhDQBMgYA8g8QBhhjAAiLQAAiMhhhjQhihiiMAAQiKAAhiBgQhjhgiJAAQg+AAg1ASQhNg1higDIfbAAIAAXTg");
	var mask_graphics_204 = new cjs.Graphics().p("AK4JYIAAhnQB3gKBWhXQBjhjAAiLQAAiMhjhhQgSgSgVgPQASg1AAg8QAAiLhjhjQhihjiMAAQgeAAgcAFQgNhwhThUQhjhiiLAAQiKAAhhBgQhihgiKAAQg9AAg1ASQhNg1higDIe7AAIAAXNgA1Zt1ILiAAQiGADhgBfQhEBFgVBYQg/gchMAAQiLAAhjBiQgYAYgSAag");
	var mask_graphics_209 = new cjs.Graphics().p("AF4E8QAkhGAAhUQAAiMhjhhQgSgSgVgPQASg1AAg8QAAgygNgtQBdhhAAiHQAAiMhjhjQhfhfiGgDIKjAAIAASxgAjnsKIAAhrIECAAQiFADhfBfIgRATIgNgKg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(149).to({graphics:mask_graphics_149,x:16,y:-81.9}).wait(5).to({graphics:mask_graphics_154,x:1.5,y:-92.6}).wait(5).to({graphics:mask_graphics_159,x:0.2,y:-88.7}).wait(5).to({graphics:mask_graphics_164,x:-15.5,y:-102.1}).wait(5).to({graphics:mask_graphics_169,x:-3.9,y:-88.7}).wait(5).to({graphics:mask_graphics_174,x:38.9,y:-88.7}).wait(5).to({graphics:mask_graphics_179,x:43.7,y:-88.7}).wait(4).to({graphics:mask_graphics_183,x:47.1,y:-88.7}).wait(6).to({graphics:mask_graphics_189,x:44.3,y:-88.7}).wait(5).to({graphics:mask_graphics_194,x:44,y:-88.7}).wait(5).to({graphics:mask_graphics_199,x:52.7,y:-88.7}).wait(5).to({graphics:mask_graphics_204,x:13.1,y:-88.7}).wait(5).to({graphics:mask_graphics_209,x:71.9,y:-88.7}).wait(5).to({graphics:null,x:0,y:0}).wait(166));

	// img
	this.instance_6 = new lib._img();
	this.instance_6.setTransform(15.8,-101.7,0.013,0.013);
	this.instance_6._off = true;

	this.instance_6.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(99).to({_off:false},0).wait(1).to({regX:12.5,regY:1,scaleX:0.03,scaleY:0.03,x:15.5,y:-101.3},0).wait(1).to({scaleX:0.07,scaleY:0.07,x:14.4,y:-100.4},0).wait(1).to({scaleX:0.14,scaleY:0.14,x:12.4,y:-98.7},0).wait(1).to({scaleX:0.23,scaleY:0.23,x:9.8,y:-96.5},0).wait(1).to({scaleX:0.33,scaleY:0.33,x:6.9,y:-94},0).wait(1).to({scaleX:0.43,scaleY:0.43,x:4.1,y:-91.5},0).wait(1).to({scaleX:0.52,scaleY:0.52,x:1.6,y:-89.5},0).wait(1).to({scaleX:0.58,scaleY:0.58,x:-0.2,y:-87.9},0).wait(1).to({scaleX:0.62,scaleY:0.62,x:-1.3,y:-87},0).wait(1).to({regX:0,regY:0,scaleX:0.63,scaleY:0.63,x:-9.5,y:-87.3},0).to({_off:true},105).wait(14).to({_off:false,scaleX:0.01,scaleY:0.01,x:-0.2,y:-41.6},0).wait(1).to({regX:12.5,regY:1,scaleX:0.03,scaleY:0.03,x:0,y:-41.5},0).wait(1).to({scaleX:0.07,scaleY:0.07,y:-41.6},0).wait(1).to({scaleX:0.14,scaleY:0.14,y:-41.5},0).wait(1).to({scaleX:0.23,scaleY:0.23},0).wait(1).to({scaleX:0.33,scaleY:0.33},0).wait(1).to({scaleX:0.43,scaleY:0.43},0).wait(1).to({scaleX:0.52,scaleY:0.52,y:-41.6},0).wait(1).to({scaleX:0.58,scaleY:0.58,y:-41.5},0).wait(1).to({scaleX:0.62,scaleY:0.62,y:-41.6},0).wait(1).to({regX:0,regY:0,scaleX:0.63,scaleY:0.63,x:-7.9,y:-42.2},0).wait(40).to({regX:12.5,regY:1,scaleX:0.62,scaleY:0.62,x:0,y:-41.6},0).wait(1).to({scaleX:0.57,scaleY:0.57},0).wait(1).to({scaleX:0.51,scaleY:0.51},0).wait(1).to({scaleX:0.42,scaleY:0.42},0).wait(1).to({scaleX:0.32,scaleY:0.32},0).wait(1).to({scaleX:0.22,scaleY:0.22},0).wait(1).to({scaleX:0.14,scaleY:0.14,y:-41.5},0).wait(1).to({scaleX:0.07,scaleY:0.07,y:-41.6},0).wait(1).to({scaleX:0.03,scaleY:0.03,y:-41.5},0).wait(1).to({regX:0,regY:0,scaleX:0.01,scaleY:0.01,x:-0.2,y:-41.6},0).to({_off:true},1).wait(92));

	// Layer 9
	this.instance_7 = new lib.pacMancopy("synched",0);
	this.instance_7.setTransform(-232.3,127.2,0.112,0.112,0,0,0,0.5,-0.9);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(99).to({_off:false},0).to({x:-196.8,alpha:1,startPosition:1},10).to({x:189.6,startPosition:2},109).to({x:225,alpha:0,startPosition:8},10).to({_off:true},1).wait(151));

	// Layer 5 (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	var mask_1_graphics_99 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_100 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_101 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_102 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_103 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_104 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_105 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_106 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_107 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_108 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_109 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_110 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_111 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_112 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_113 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_114 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_115 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_116 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_117 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_118 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_119 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_120 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_121 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_122 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_123 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_124 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_125 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_126 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_127 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_128 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_129 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_130 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_131 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_132 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_133 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_134 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_135 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_136 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_137 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_138 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_139 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_140 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_141 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_142 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_143 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_144 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_145 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_146 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_147 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_148 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_149 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_150 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_151 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_152 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_153 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_154 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_155 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_156 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_157 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_158 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_159 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_160 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_161 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_162 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_163 = new cjs.Graphics().p("EghjAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_164 = new cjs.Graphics().p("EghbAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQgBgbgLgWQgOgcgegSQgHgFgNgFQgVgHgbgHQAaABAQgBQAOAAgBgCIgHgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_165 = new cjs.Graphics().p("EghJAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcgBggQAAgbgLgWQgOgcgegSQgHgFgOgFQgUgHgcgHQAbABAQgBQAOAAgBgCIgHgKIgKgLMBD5gAXIAAE5MhD5AAXQAHgHgBgQg");
	var mask_1_graphics_166 = new cjs.Graphics().p("Egg3AK5IgDgQQgDgKgGgNQAugRAYggQAWgcgBggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgHgKIgLgLMBD5gAXIAAE5MhD5AAXQAIgHgBgQg");
	var mask_1_graphics_167 = new cjs.Graphics().p("EggmAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgHgKIgLgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_168 = new cjs.Graphics().p("EggUAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQgBgbgLgWQgOgcgegSQgHgFgNgFQgUgHgcgHQAaABAQgBQAOAAAAgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_169 = new cjs.Graphics().p("EggCAK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQgBgbgLgWQgOgcgegSQgHgFgOgFQgUgHgcgHQAbABAQgBQAOAAgBgCIgHgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_170 = new cjs.Graphics().p("A/wK5IgDgQQgDgKgGgNQAugRAZggQAVgcgBggQAAgbgLgWQgOgcgegSQgIgFgNgFQgUgHgcgHQAbABAQgBQAOAAgBgCIgHgKIgKgLMBD5gAXIAAE5MhD5AAXQAHgHgBgQg");
	var mask_1_graphics_171 = new cjs.Graphics().p("A/eK5IgDgQQgDgKgGgNQAugRAYggQAWgcgBggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgHgKIgLgLMBD5gAXIAAE5MhD5AAXQAIgHgBgQg");
	var mask_1_graphics_172 = new cjs.Graphics().p("A/NK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQgBgbgKgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABAQgBQAOAAAAgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_173 = new cjs.Graphics().p("A+7K5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQgBgbgLgWQgOgcgegSQgHgFgOgFQgUgHgbgHQAaABAQgBQAOAAgBgCIgHgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_174 = new cjs.Graphics().p("A+pK5IgDgQQgDgKgGgNQAvgRAYggQAVgcgBggQAAgbgLgWQgOgcgegSQgIgFgNgFQgUgHgcgHQAbABAQgBQAOAAgBgCIgHgKIgKgLMBD5gAXIAAE5MhD5AAXQAHgHgBgQg");
	var mask_1_graphics_175 = new cjs.Graphics().p("A+XK5IgDgQQgDgKgGgNQAugRAYggQAWgcgBggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgHgKIgLgLMBD5gAXIAAE5MhD5AAXQAIgHgBgQg");
	var mask_1_graphics_176 = new cjs.Graphics().p("A+GK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABAQgBQAPAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_177 = new cjs.Graphics().p("A90K5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQgBgbgLgWQgOgcgegSQgHgFgNgFQgVgHgbgHQAaABAQgBQAOAAgBgCIgHgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_178 = new cjs.Graphics().p("A9iK5IgDgQQgDgKgGgNQAvgRAYggQAVgcgBggQAAgbgLgWQgOgcgegSQgIgFgNgFQgUgHgcgHQAbABAQgBQAOAAgBgCIgHgKIgKgLMBD5gAXIAAE5MhD5AAXQAHgHgBgQg");
	var mask_1_graphics_179 = new cjs.Graphics().p("A9QK5IgDgQQgDgKgGgNQAugRAYggQAWgcgBggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgHgKIgLgLMBD5gAXIAAE5MhD5AAXQAIgHgBgQg");
	var mask_1_graphics_180 = new cjs.Graphics().p("A8/K5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgHgKIgLgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_181 = new cjs.Graphics().p("A8tK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQgBgbgLgWQgOgcgegSQgHgFgNgFQgUgHgcgHQAaABAQgBQAOAAAAgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_182 = new cjs.Graphics().p("A8bK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQgBgbgLgWQgOgcgegSQgHgFgOgFQgUgHgcgHQAbABAQgBQAOAAgBgCIgHgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_183 = new cjs.Graphics().p("A8JK5IgDgQQgDgKgGgNQAugRAZggQAVgcgBggQAAgbgLgWQgOgcgegSQgIgFgNgFQgUgHgcgHQAbABAQgBQAOAAgBgCIgHgKIgKgLMBD5gAXIAAE5MhD5AAXQAHgHgBgQg");
	var mask_1_graphics_184 = new cjs.Graphics().p("A73K5IgDgQQgDgKgGgNQAugRAYggQAWgcgBggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgHgKIgLgLMBD5gAXIAAE5MhD5AAXQAIgHgBgQg");
	var mask_1_graphics_185 = new cjs.Graphics().p("A7mK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQgBgbgKgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABAQgBQAOAAAAgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_186 = new cjs.Graphics().p("A7UK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQgBgbgLgWQgOgcgegSQgHgFgOgFQgUgHgbgHQAaABAQgBQAOAAgBgCIgHgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_187 = new cjs.Graphics().p("A7CK5IgDgQQgDgKgGgNQAvgRAYggQAVgcgBggQAAgbgLgWQgOgcgegSQgIgFgNgFQgUgHgcgHQAbABAQgBQAOAAgBgCIgHgKIgKgLMBD5gAXIAAE5MhD5AAXQAHgHgBgQg");
	var mask_1_graphics_188 = new cjs.Graphics().p("A6wK5IgDgQQgDgKgGgNQAugRAYggQAWgcgBggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgHgKIgLgLMBD5gAXIAAE5MhD5AAXQAIgHgBgQg");
	var mask_1_graphics_189 = new cjs.Graphics().p("A6fK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABAQgBQAPAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_190 = new cjs.Graphics().p("A6NK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQgBgbgLgWQgOgcgegSQgHgFgNgFQgVgHgbgHQAaABAQgBQAOAAgBgCIgHgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_191 = new cjs.Graphics().p("A57K5IgDgQQgDgKgGgNQAvgRAYggQAVgcgBggQAAgbgLgWQgOgcgegSQgHgFgOgFQgUgHgcgHQAbABAQgBQAOAAgBgCIgHgKIgKgLMBD5gAXIAAE5MhD5AAXQAHgHgBgQg");
	var mask_1_graphics_192 = new cjs.Graphics().p("A5pK5IgDgQQgDgKgGgNQAugRAYggQAWgcgBggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgHgKIgLgLMBD5gAXIAAE5MhD5AAXQAIgHgBgQg");
	var mask_1_graphics_193 = new cjs.Graphics().p("A5YK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgHgKIgLgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_194 = new cjs.Graphics().p("A5GK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQgBgbgLgWQgOgcgegSQgHgFgNgFQgUgHgcgHQAaABAQgBQAOAAAAgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_195 = new cjs.Graphics().p("A40K5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQgBgbgLgWQgOgcgegSQgHgFgOgFQgUgHgcgHQAbABAQgBQAOAAgBgCIgHgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_196 = new cjs.Graphics().p("A4iK5IgDgQQgDgKgGgNQAugRAZggQAVgcgBggQAAgbgLgWQgOgcgegSQgIgFgNgFQgUgHgcgHQAbABAQgBQAOAAgBgCIgHgKIgKgLMBD5gAXIAAE5MhD5AAXQAHgHgBgQg");
	var mask_1_graphics_197 = new cjs.Graphics().p("A4QK5IgDgQQgDgKgGgNQAugRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgHgKIgLgLMBD5gAXIAAE5MhD5AAXQAIgHgBgQg");
	var mask_1_graphics_198 = new cjs.Graphics().p("A3/K5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQgBgbgKgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABAQgBQAOAAAAgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_199 = new cjs.Graphics().p("A3tK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQgBgbgLgWQgOgcgegSQgHgFgOgFQgUgHgbgHQAaABAQgBQAOAAgBgCIgHgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_200 = new cjs.Graphics().p("A3bK5IgDgQQgDgKgGgNQAvgRAYggQAVgcgBggQAAgbgLgWQgOgcgegSQgIgFgNgFQgUgHgcgHQAbABAQgBQAOAAgBgCIgHgKIgKgLMBD5gAXIAAE5MhD5AAXQAHgHgBgQg");
	var mask_1_graphics_201 = new cjs.Graphics().p("A3JK5IgDgQQgDgKgGgNQAugRAYggQAWgcgBggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgHgKIgLgLMBD5gAXIAAE5MhD5AAXQAIgHgBgQg");
	var mask_1_graphics_202 = new cjs.Graphics().p("A24K5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABAQgBQAPAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_203 = new cjs.Graphics().p("A2mK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQgBgbgLgWQgOgcgegSQgHgFgNgFQgVgHgbgHQAaABAQgBQAOAAgBgCIgHgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_204 = new cjs.Graphics().p("A2UK5IgDgQQgDgKgGgNQAvgRAYggQAVgcgBggQAAgbgLgWQgOgcgegSQgIgFgNgFQgUgHgcgHQAbABAQgBQAOAAgBgCIgHgKIgKgLMBD5gAXIAAE5MhD5AAXQAHgHgBgQg");
	var mask_1_graphics_205 = new cjs.Graphics().p("A2CK5IgDgQQgDgKgGgNQAugRAYggQAWgcgBggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgHgKIgLgLMBD5gAXIAAE5MhD5AAXQAIgHgBgQg");
	var mask_1_graphics_206 = new cjs.Graphics().p("A1xK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgHgKIgLgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_207 = new cjs.Graphics().p("A1fK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQgBgbgLgWQgOgcgegSQgHgFgNgFQgUgHgcgHQAaABAQgBQAOAAAAgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_208 = new cjs.Graphics().p("A1NK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQgBgbgLgWQgOgcgegSQgHgFgOgFQgUgHgcgHQAbABAQgBQAOAAgBgCIgHgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_209 = new cjs.Graphics().p("A07K5IgDgQQgDgKgGgNQAugRAZggQAVgcgBggQAAgbgLgWQgOgcgegSQgIgFgNgFQgUgHgcgHQAbABAQgBQAOAAgBgCIgHgKIgKgLMBD4gAXIAAE5MhD4AAXQAHgHgBgQg");
	var mask_1_graphics_210 = new cjs.Graphics().p("A0pK5IgDgQQgDgKgGgNQAugRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgHgKIgLgLMBD5gAXIAAE5MhD5AAXQAIgHgBgQg");
	var mask_1_graphics_211 = new cjs.Graphics().p("A0YK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQgBgbgLgWQgNgcgfgSQgHgFgNgFQgUgHgcgHQAaABAQgBQAOAAAAgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_212 = new cjs.Graphics().p("A0GK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQgBgbgLgWQgOgcgegSQgHgFgOgFQgUgHgbgHQAaABAQgBQAOAAgBgCIgHgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_213 = new cjs.Graphics().p("Az0K5IgDgQQgDgKgGgNQAugRAZggQAVgcgBggQAAgbgLgWQgOgcgegSQgIgFgNgFQgUgHgcgHQAbABAQgBQAOAAgBgCIgHgKIgKgLMBD5gAXIAAE5MhD5AAXQAHgHgBgQg");
	var mask_1_graphics_214 = new cjs.Graphics().p("AziK5IgDgQQgDgKgGgNQAugRAYggQAWgcgBggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgHgKIgLgLMBD5gAXIAAE5MhD5AAXQAIgHgBgQg");
	var mask_1_graphics_215 = new cjs.Graphics().p("AzRK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABAQgBQAPAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_216 = new cjs.Graphics().p("Ay/K5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQgBgbgLgWQgOgcgegSQgHgFgNgFQgVgHgbgHQAaABAQgBQAOAAgBgCIgHgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_217 = new cjs.Graphics().p("AytK5IgDgQQgDgKgGgNQAvgRAYggQAVgcgBggQAAgbgLgWQgOgcgegSQgIgFgNgFQgUgHgcgHQAbABAQgBQAOAAgBgCIgHgKIgKgLMBD5gAXIAAE5MhD5AAXQAHgHgBgQg");
	var mask_1_graphics_218 = new cjs.Graphics().p("AybK5IgDgQQgDgKgGgNQAugRAYggQAWgcgBggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgHgKIgLgLMBD5gAXIAAE5MhD5AAXQAIgHgBgQg");
	var mask_1_graphics_219 = new cjs.Graphics().p("AyKK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgHgKIgLgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_220 = new cjs.Graphics().p("Ax4K5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQgBgbgLgWQgOgcgegSQgHgFgNgFQgUgHgcgHQAaABAQgBQAOAAAAgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_221 = new cjs.Graphics().p("AxmK5IgDgQQgDgKgGgNQAvgRAYggQAVgcgBggQAAgbgLgWQgOgcgegSQgHgFgOgFQgUgHgcgHQAbABAQgBQAOAAgBgCIgHgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_222 = new cjs.Graphics().p("AxUK5IgDgQQgDgKgGgNQAugRAZggQAVgcgBggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAbABAQgBQAOAAgBgCIgHgKIgKgLMBD4gAXIAAE5MhD4AAXQAHgHgBgQg");
	var mask_1_graphics_223 = new cjs.Graphics().p("AxCK5IgDgQQgDgKgGgNQAugRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgHgKIgLgLMBD5gAXIAAE5MhD5AAXQAIgHgBgQg");
	var mask_1_graphics_224 = new cjs.Graphics().p("AwxK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQgBgbgLgWQgNgcgfgSQgHgFgNgFQgUgHgcgHQAaABAQgBQAOAAAAgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_225 = new cjs.Graphics().p("AwfK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQgBgbgLgWQgOgcgegSQgHgFgOgFQgUgHgcgHQAbABAQgBQAOAAgBgCIgHgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");
	var mask_1_graphics_226 = new cjs.Graphics().p("AwNK5IgDgQQgDgKgGgNQAugRAZggQAVgcgBggQAAgbgLgWQgOgcgegSQgIgFgNgFQgUgHgcgHQAbABAQgBQAOAAgBgCIgHgKIgKgLMBD5gAXIAAE5MhD5AAXQAHgHgBgQg");
	var mask_1_graphics_227 = new cjs.Graphics().p("Av7K5IgDgQQgDgKgGgNQAugRAYggQAWgcgBggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABARgBQAOAAgBgCIgHgKIgLgLMBD5gAXIAAE5MhD5AAXQAIgHgBgQg");
	var mask_1_graphics_228 = new cjs.Graphics().p("AvqK5IgDgQQgDgKgGgNQAvgRAYggQAVgcAAggQAAgbgLgWQgOgcgfgSQgHgFgNgFQgUgHgcgHQAaABAQgBQAPAAgBgCIgIgKIgKgLMBD5gAXIAAE5MhD5AAXQAIgHgCgQg");

	this.timeline.addTween(cjs.Tween.get(mask_1).to({graphics:null,x:0,y:0}).wait(99).to({graphics:mask_1_graphics_99,x:-10.2,y:72}).wait(1).to({graphics:mask_1_graphics_100,x:-6.6,y:72}).wait(1).to({graphics:mask_1_graphics_101,x:-3.1,y:72}).wait(1).to({graphics:mask_1_graphics_102,x:0.5,y:72}).wait(1).to({graphics:mask_1_graphics_103,x:4,y:72}).wait(1).to({graphics:mask_1_graphics_104,x:7.6,y:72}).wait(1).to({graphics:mask_1_graphics_105,x:11.1,y:72}).wait(1).to({graphics:mask_1_graphics_106,x:14.7,y:72}).wait(1).to({graphics:mask_1_graphics_107,x:18.2,y:72}).wait(1).to({graphics:mask_1_graphics_108,x:21.8,y:72}).wait(1).to({graphics:mask_1_graphics_109,x:25.4,y:72}).wait(1).to({graphics:mask_1_graphics_110,x:28.9,y:72}).wait(1).to({graphics:mask_1_graphics_111,x:32.5,y:72}).wait(1).to({graphics:mask_1_graphics_112,x:36,y:72}).wait(1).to({graphics:mask_1_graphics_113,x:39.6,y:72}).wait(1).to({graphics:mask_1_graphics_114,x:43.1,y:72}).wait(1).to({graphics:mask_1_graphics_115,x:46.7,y:72}).wait(1).to({graphics:mask_1_graphics_116,x:50.2,y:72}).wait(1).to({graphics:mask_1_graphics_117,x:53.8,y:72}).wait(1).to({graphics:mask_1_graphics_118,x:57.3,y:72}).wait(1).to({graphics:mask_1_graphics_119,x:60.9,y:72}).wait(1).to({graphics:mask_1_graphics_120,x:64.4,y:72}).wait(1).to({graphics:mask_1_graphics_121,x:68,y:72}).wait(1).to({graphics:mask_1_graphics_122,x:71.6,y:72}).wait(1).to({graphics:mask_1_graphics_123,x:75.1,y:72}).wait(1).to({graphics:mask_1_graphics_124,x:78.7,y:72}).wait(1).to({graphics:mask_1_graphics_125,x:82.2,y:72}).wait(1).to({graphics:mask_1_graphics_126,x:85.8,y:72}).wait(1).to({graphics:mask_1_graphics_127,x:89.3,y:72}).wait(1).to({graphics:mask_1_graphics_128,x:92.9,y:72}).wait(1).to({graphics:mask_1_graphics_129,x:96.4,y:72}).wait(1).to({graphics:mask_1_graphics_130,x:100,y:72}).wait(1).to({graphics:mask_1_graphics_131,x:103.5,y:72}).wait(1).to({graphics:mask_1_graphics_132,x:107.1,y:72}).wait(1).to({graphics:mask_1_graphics_133,x:110.6,y:72}).wait(1).to({graphics:mask_1_graphics_134,x:114.2,y:72}).wait(1).to({graphics:mask_1_graphics_135,x:117.8,y:72}).wait(1).to({graphics:mask_1_graphics_136,x:121.3,y:72}).wait(1).to({graphics:mask_1_graphics_137,x:124.9,y:72}).wait(1).to({graphics:mask_1_graphics_138,x:128.4,y:72}).wait(1).to({graphics:mask_1_graphics_139,x:132,y:72}).wait(1).to({graphics:mask_1_graphics_140,x:135.5,y:72}).wait(1).to({graphics:mask_1_graphics_141,x:139.1,y:72}).wait(1).to({graphics:mask_1_graphics_142,x:142.6,y:72}).wait(1).to({graphics:mask_1_graphics_143,x:146.2,y:72}).wait(1).to({graphics:mask_1_graphics_144,x:149.7,y:72}).wait(1).to({graphics:mask_1_graphics_145,x:153.3,y:72}).wait(1).to({graphics:mask_1_graphics_146,x:156.8,y:72}).wait(1).to({graphics:mask_1_graphics_147,x:160.4,y:72}).wait(1).to({graphics:mask_1_graphics_148,x:164,y:72}).wait(1).to({graphics:mask_1_graphics_149,x:167.5,y:72}).wait(1).to({graphics:mask_1_graphics_150,x:171.1,y:72}).wait(1).to({graphics:mask_1_graphics_151,x:174.6,y:72}).wait(1).to({graphics:mask_1_graphics_152,x:178.2,y:72}).wait(1).to({graphics:mask_1_graphics_153,x:181.7,y:72}).wait(1).to({graphics:mask_1_graphics_154,x:185.3,y:72}).wait(1).to({graphics:mask_1_graphics_155,x:188.8,y:72}).wait(1).to({graphics:mask_1_graphics_156,x:192.4,y:72}).wait(1).to({graphics:mask_1_graphics_157,x:195.9,y:72}).wait(1).to({graphics:mask_1_graphics_158,x:199.5,y:72}).wait(1).to({graphics:mask_1_graphics_159,x:203,y:72}).wait(1).to({graphics:mask_1_graphics_160,x:206.6,y:72}).wait(1).to({graphics:mask_1_graphics_161,x:210.2,y:72}).wait(1).to({graphics:mask_1_graphics_162,x:213.7,y:72}).wait(1).to({graphics:mask_1_graphics_163,x:217.3,y:72}).wait(1).to({graphics:mask_1_graphics_164,x:220,y:72}).wait(1).to({graphics:mask_1_graphics_165,x:221.8,y:72}).wait(1).to({graphics:mask_1_graphics_166,x:223.6,y:72}).wait(1).to({graphics:mask_1_graphics_167,x:225.4,y:72}).wait(1).to({graphics:mask_1_graphics_168,x:227.1,y:72}).wait(1).to({graphics:mask_1_graphics_169,x:228.9,y:72}).wait(1).to({graphics:mask_1_graphics_170,x:230.7,y:72}).wait(1).to({graphics:mask_1_graphics_171,x:232.5,y:72}).wait(1).to({graphics:mask_1_graphics_172,x:234.3,y:72}).wait(1).to({graphics:mask_1_graphics_173,x:236,y:72}).wait(1).to({graphics:mask_1_graphics_174,x:237.8,y:72}).wait(1).to({graphics:mask_1_graphics_175,x:239.6,y:72}).wait(1).to({graphics:mask_1_graphics_176,x:241.4,y:72}).wait(1).to({graphics:mask_1_graphics_177,x:243.1,y:72}).wait(1).to({graphics:mask_1_graphics_178,x:244.9,y:72}).wait(1).to({graphics:mask_1_graphics_179,x:246.7,y:72}).wait(1).to({graphics:mask_1_graphics_180,x:248.5,y:72}).wait(1).to({graphics:mask_1_graphics_181,x:250.2,y:72}).wait(1).to({graphics:mask_1_graphics_182,x:252,y:72}).wait(1).to({graphics:mask_1_graphics_183,x:253.8,y:72}).wait(1).to({graphics:mask_1_graphics_184,x:255.6,y:72}).wait(1).to({graphics:mask_1_graphics_185,x:257.4,y:72}).wait(1).to({graphics:mask_1_graphics_186,x:259.1,y:72}).wait(1).to({graphics:mask_1_graphics_187,x:260.9,y:72}).wait(1).to({graphics:mask_1_graphics_188,x:262.7,y:72}).wait(1).to({graphics:mask_1_graphics_189,x:264.5,y:72}).wait(1).to({graphics:mask_1_graphics_190,x:266.2,y:72}).wait(1).to({graphics:mask_1_graphics_191,x:268,y:72}).wait(1).to({graphics:mask_1_graphics_192,x:269.8,y:72}).wait(1).to({graphics:mask_1_graphics_193,x:271.6,y:72}).wait(1).to({graphics:mask_1_graphics_194,x:273.3,y:72}).wait(1).to({graphics:mask_1_graphics_195,x:275.1,y:72}).wait(1).to({graphics:mask_1_graphics_196,x:276.9,y:72}).wait(1).to({graphics:mask_1_graphics_197,x:278.7,y:72}).wait(1).to({graphics:mask_1_graphics_198,x:280.5,y:72}).wait(1).to({graphics:mask_1_graphics_199,x:282.2,y:72}).wait(1).to({graphics:mask_1_graphics_200,x:284,y:72}).wait(1).to({graphics:mask_1_graphics_201,x:285.8,y:72}).wait(1).to({graphics:mask_1_graphics_202,x:287.6,y:72}).wait(1).to({graphics:mask_1_graphics_203,x:289.3,y:72}).wait(1).to({graphics:mask_1_graphics_204,x:291.1,y:72}).wait(1).to({graphics:mask_1_graphics_205,x:292.9,y:72}).wait(1).to({graphics:mask_1_graphics_206,x:294.7,y:72}).wait(1).to({graphics:mask_1_graphics_207,x:296.4,y:72}).wait(1).to({graphics:mask_1_graphics_208,x:298.2,y:72}).wait(1).to({graphics:mask_1_graphics_209,x:300,y:72}).wait(1).to({graphics:mask_1_graphics_210,x:301.8,y:72}).wait(1).to({graphics:mask_1_graphics_211,x:303.6,y:72}).wait(1).to({graphics:mask_1_graphics_212,x:305.3,y:72}).wait(1).to({graphics:mask_1_graphics_213,x:307.1,y:72}).wait(1).to({graphics:mask_1_graphics_214,x:308.9,y:72}).wait(1).to({graphics:mask_1_graphics_215,x:310.7,y:72}).wait(1).to({graphics:mask_1_graphics_216,x:312.4,y:72}).wait(1).to({graphics:mask_1_graphics_217,x:314.2,y:72}).wait(1).to({graphics:mask_1_graphics_218,x:316,y:72}).wait(1).to({graphics:mask_1_graphics_219,x:317.8,y:72}).wait(1).to({graphics:mask_1_graphics_220,x:319.5,y:72}).wait(1).to({graphics:mask_1_graphics_221,x:321.3,y:72}).wait(1).to({graphics:mask_1_graphics_222,x:323.1,y:72}).wait(1).to({graphics:mask_1_graphics_223,x:324.9,y:72}).wait(1).to({graphics:mask_1_graphics_224,x:326.7,y:72}).wait(1).to({graphics:mask_1_graphics_225,x:328.4,y:72}).wait(1).to({graphics:mask_1_graphics_226,x:330.2,y:72}).wait(1).to({graphics:mask_1_graphics_227,x:332,y:72}).wait(1).to({graphics:mask_1_graphics_228,x:333.8,y:72}).wait(1).to({graphics:null,x:0,y:0}).wait(151));

	// Layer 11
	this.instance_8 = new lib.bulki();
	this.instance_8.setTransform(0.3,128,0.7,0.7);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.instance_8.mask = mask_1;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(99).to({_off:false},0).to({alpha:1},10).to({_off:true},120).wait(151));

	// t2
	this.instance_9 = new lib.t2_1();
	this.instance_9.setTransform(0,0,0.012,0.012);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(54).to({_off:false},0).wait(1).to({scaleX:0.03,scaleY:0.03},0).wait(1).to({scaleX:0.09,scaleY:0.09},0).wait(1).to({scaleX:0.18,scaleY:0.18},0).wait(1).to({scaleX:0.3,scaleY:0.3},0).wait(1).to({scaleX:0.44,scaleY:0.44},0).wait(1).to({scaleX:0.59,scaleY:0.59},0).wait(1).to({scaleX:0.71,scaleY:0.71},0).wait(1).to({scaleX:0.8,scaleY:0.8},0).wait(1).to({scaleX:0.85,scaleY:0.85},0).wait(1).to({scaleX:0.87,scaleY:0.87},0).wait(26).to({scaleX:0.85,scaleY:0.85},0).wait(1).to({scaleX:0.8,scaleY:0.8},0).wait(1).to({scaleX:0.7,scaleY:0.7},0).wait(1).to({scaleX:0.58,scaleY:0.58},0).wait(1).to({scaleX:0.43,scaleY:0.43},0).wait(1).to({scaleX:0.29,scaleY:0.29},0).wait(1).to({scaleX:0.17,scaleY:0.17},0).wait(1).to({scaleX:0.08,scaleY:0.08},0).wait(1).to({scaleX:0.03,scaleY:0.03},0).wait(1).to({scaleX:0.01,scaleY:0.01},0).to({_off:true},1).wait(280));

	// t_Bg
	this.instance_10 = new lib.t1_Bg();
	this.instance_10.setTransform(0,0,0.011,0.006);
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(54).to({_off:false},0).wait(1).to({scaleX:0.02,scaleY:0.01},0).wait(1).to({scaleX:0.06,scaleY:0.03},0).wait(1).to({scaleX:0.11,scaleY:0.07},0).wait(1).to({scaleX:0.19,scaleY:0.11},0).wait(1).to({scaleX:0.27,scaleY:0.16},0).wait(1).to({scaleX:0.36,scaleY:0.22},0).wait(1).to({scaleX:0.43,scaleY:0.26},0).wait(1).to({scaleX:0.49,scaleY:0.3},0).wait(1).to({scaleX:0.52,scaleY:0.32},0).wait(1).to({scaleX:0.53,scaleY:0.32},0).wait(26).to({scaleX:0.52,scaleY:0.32},0).wait(1).to({scaleX:0.49,scaleY:0.3},0).wait(1).to({scaleX:0.43,scaleY:0.26},0).wait(1).to({scaleX:0.35,scaleY:0.21},0).wait(1).to({scaleX:0.26,scaleY:0.16},0).wait(1).to({scaleX:0.18,scaleY:0.11},0).wait(1).to({scaleX:0.1,scaleY:0.06},0).wait(1).to({scaleX:0.05,scaleY:0.03},0).wait(1).to({scaleX:0.02,scaleY:0.01},0).wait(1).to({scaleX:0.01,scaleY:0.01},0).to({_off:true},1).wait(280));

	// t1
	this.instance_11 = new lib.t1_1();
	this.instance_11.setTransform(0,0,0.013,0.013);
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(9).to({_off:false},0).wait(1).to({scaleX:0.03,scaleY:0.03},0).wait(1).to({scaleX:0.09,scaleY:0.09},0).wait(1).to({scaleX:0.19,scaleY:0.19},0).wait(1).to({scaleX:0.32,scaleY:0.32},0).wait(1).to({scaleX:0.47,scaleY:0.47},0).wait(1).to({scaleX:0.63,scaleY:0.63},0).wait(1).to({scaleX:0.76,scaleY:0.76},0).wait(1).to({scaleX:0.87,scaleY:0.87},0).wait(1).to({scaleX:0.93,scaleY:0.93},0).wait(1).to({scaleX:0.95,scaleY:0.95},0).wait(26).to({scaleX:0.93,scaleY:0.93},0).wait(1).to({scaleX:0.86,scaleY:0.86},0).wait(1).to({scaleX:0.76,scaleY:0.76},0).wait(1).to({scaleX:0.62,scaleY:0.62},0).wait(1).to({scaleX:0.47,scaleY:0.47},0).wait(1).to({scaleX:0.32,scaleY:0.32},0).wait(1).to({scaleX:0.19,scaleY:0.19},0).wait(1).to({scaleX:0.09,scaleY:0.09},0).wait(1).to({scaleX:0.03,scaleY:0.03},0).wait(1).to({scaleX:0.01,scaleY:0.01},0).to({_off:true},1).wait(325));

	// t_Bg
	this.instance_12 = new lib.t1_Bg();
	this.instance_12.setTransform(0,0,0.009,0.009);
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(9).to({_off:false},0).wait(1).to({scaleX:0.02,scaleY:0.02},0).wait(1).to({scaleX:0.05,scaleY:0.05},0).wait(1).to({scaleX:0.09,scaleY:0.09},0).wait(1).to({scaleX:0.15,scaleY:0.15},0).wait(1).to({scaleX:0.22,scaleY:0.22},0).wait(1).to({scaleX:0.29,scaleY:0.29},0).wait(1).to({scaleX:0.35,scaleY:0.35},0).wait(1).to({scaleX:0.4,scaleY:0.4},0).wait(1).to({scaleX:0.43,scaleY:0.43},0).wait(1).to({scaleX:0.44,scaleY:0.44},0).wait(26).to({scaleX:0.43,scaleY:0.43},0).wait(1).to({scaleX:0.4,scaleY:0.4},0).wait(1).to({scaleX:0.35,scaleY:0.35},0).wait(1).to({scaleX:0.29,scaleY:0.29},0).wait(1).to({scaleX:0.22,scaleY:0.22},0).wait(1).to({scaleX:0.15,scaleY:0.15},0).wait(1).to({scaleX:0.09,scaleY:0.09},0).wait(1).to({scaleX:0.05,scaleY:0.05},0).wait(1).to({scaleX:0.02,scaleY:0.02},0).wait(1).to({scaleX:0.01,scaleY:0.01},0).to({_off:true},1).wait(325));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-151.6,-300,301.7,600);


// stage content:



(lib._300x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#999999").ss(1,1,1).p("EgXWguyMAutAAAMAAABdlMgutAAAg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(380));

	// Layer 1
	this.instance = new lib.banner();
	this.instance.setTransform(150,299,1,1,0,0,0,0,-1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(380));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(148.4,299.5,302.2,601);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;