(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.dev = function() {
	this.initialize(img.dev);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,242,382);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.urText = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AmpEhIgEgCIACgIIAGABIAEgBQABAAAAAAQAAgBABAAQAAAAABgBQAAAAAAgBIAGgMIgUgyIAKAAIAPAnIAPgnIAKAAIgWA3QgDAIgDAEQgDAEgDACQgDACgGAAgACdEfIAAhJIAJAAIAAAIQADgEAFgDQADgCAGAAQAHAAAEAEQAGAEADAFQADAGAAAHQAAAIgDAFQgDAFgGAFQgEADgHAAQgGAAgDgCQgFgCgDgFIAAAfgACuDgQgDACgDAEQgCAEAAAFQAAAFACAEQADAEADACQACACAFAAQAEAAAEgCQADgCACgEQACgEAAgFQAAgFgCgEQgCgEgDgCQgEgCgEAAQgEAAgDACgAhwEfIAAhJIAJAAIAAAIQADgEAFgDQADgCAGAAQAHAAAEAEQAGAEADAFQADAGAAAHQAAAIgDAFQgDAFgGAFQgEADgHAAQgGAAgDgCQgFgCgDgFIAAAfgAhfDgQgDACgDAEQgCAEAAAFQAAAFACAEQADAEADACQACACAFAAQAEAAAEgCQADgCACgEQACgEAAgFQAAgFgCgEQgCgEgDgCQgEgCgEAAQgEAAgDACgArfEWIAAgOIg3AAIAAhIIAKAAIAAA+IAjAAIAAg+IAKAAIAAA+IAKAAIAAAYgAE/EUIAAgMIgqAAIAAgyIAJAAIAAApIAYAAIAAgpIAKAAIAAApIAIAAIAAAVgAMUEIIgCgCIgBgEIABgDIACgCIADgCIAEACIACACIAAADIAAAEIgCACIgEABIgDgBgAJeEGQgGgFgDgFQgDgFAAgIQAAgHADgGQADgFAGgEQAFgEAGAAQAGAAADACQAFADADAEIAAgIIAJAAIAAAyIgJAAIAAgIQgDAEgFADQgDACgGAAQgGAAgFgDgAJjDgQgDACgCAEQgCAFAAAEQAAAEACAFQACAEADACQADACAFAAQAFAAACgCQAEgCACgEQACgEAAgFQAAgFgCgEQgCgEgEgCQgDgCgEAAQgEAAgEACgAIsEGQgGgFgDgFQgDgGAAgHQAAgHADgGQADgGAGgDQAFgDAJgBQAFABAGACQAGACADAFIgGAGIgGgFQgEgBgEgBQgFAAgEACQgDADgDADQgCAEAAAFQAAAFACAEQACAEAEACQAEACAFAAQAEgBAEgBQADgCADgDIAGAGQgDAFgGACQgEACgHABQgIAAgGgDgAHbEGQgFgFgDgFQgDgFAAgIQAAgHADgGQADgFAFgEQAGgEAGAAQAGAAAEACQAEADACAEIAAgIIAKAAIAAAyIgKAAIAAgIQgCAEgEADQgEACgGAAQgGAAgGgDgAHhDgQgEACgCAEQgCAFAAAEQAAAEACAFQACAEAEACQAEACAEAAQAFAAADgCQAEgCABgEQACgEAAgFQAAgFgCgEQgBgEgEgCQgEgCgEAAQgEAAgEACgADiEGQgHgFgCgFQgDgFAAgIQAAgHADgGQACgFAHgEQAFgEAGAAQAGAAAEACQAFADACAEIAAgIIAJAAIAAAyIgJAAIAAgIQgCAEgFADQgEACgGAAQgGAAgFgDgADnDgQgEACgBAEQgDAFAAAEQAAAEADAFQABAEAEACQADACAFAAQAFAAADgCQADgCACgEQACgEAAgFQAAgFgCgEQgCgEgDgCQgEgCgEAAQgEAAgEACgABCEGQgGgFgDgFQgDgGAAgHQAAgHADgGQAEgGAFgDQAFgDAIgBQAGABAHACQAFACADAFIgGAGIgHgFQgDgBgFgBQgFAAgDACQgDADgCADQgCAEAAAFQAAAFACAEQACAEADACQADACAFAAQAFgBADgBQAEgCADgDIAGAGQgDAFgFACQgFACgIABQgHAAgGgDgAAQEGQgGgFgDgFQgDgGAAgHQAAgHADgGQADgGAGgDQAFgDAJgBQAHABAEACQAGACADAEIgGAGIgGgFQgDgBgFgBQgEAAgEACQgEACgCADIgCAIIAYAAIAAAGIgYAAQAAAGAFAFQAEADAHAAQAFAAADgBIAGgFIAGAGQgEAFgFACQgEACgHAAQgIAAgGgDgAgrEGQgGgFgDgFQgDgFAAgIQAAgHADgGQADgFAGgEQAGgEAGAAQAIAAAEAEQAFACAEAGQAEAGAAAHIgBADIgnAAQABAFADADQAAADAFADIAIABQAFAAADgBIAIgFIAEAGQgCAFgHACQgEACgIAAQgHAAgGgDgAgQDrQgBgGgEgEQgFgDgFgBQgFABgEADQgEAEgCAGIAeAAIAAAAgAklEGQgFgFgEgFQgDgFAAgIQAAgHADgGQAEgGAFgDQAGgDAHgBQAIABAFADQAGADADAGQADAGAAAHQAAAIgDAFQgDAFgGAFQgFADgIAAQgHAAgGgDgAkgDgQgDADgCADQgCAEAAAFQAAAFACAEIAFAGQADACAFAAQAEAAAEgCQAFgDABgDQACgEAAgFQAAgFgCgEQgCgDgEgDQgEgCgEAAQgFAAgDACgAntEGQgHgFgCgFQgDgFAAgIQAAgHADgGQACgFAHgEQAFgEAGAAQAGAAAEACQAFADACAEIAAgIIAJAAIAAAyIgJAAIAAgIQgCAEgFADQgEACgGAAQgGAAgFgDgAnoDgQgEACgBAEQgDAFAAAEQAAAEADAFQABAEAEACQADACAFAAQAFAAADgCQADgCACgEQACgEAAgFQAAgFgCgEQgCgEgDgCQgEgCgEAAQgEAAgEACgAokEHQgFgDgDgEIAFgGQADAEAEABQAEACAEAAQAGAAADgCQADgCAAgEQAAgHgKAAIgKAAIAAgGIAIAAQAGAAACgDQACgBAAgDQAAgDgCgDQgDgBgEgBQgJABgGAFIgFgGQADgDAGgDQAEgCAHAAQAJABAFADQAEAEAAAGQAAAEgBADQgCADgEACQAEAAADADQACADAAAEQABAGgDACQgDAEgFACQgEABgHABQgIAAgEgCgAL/EIIAAgxIAKAAIAAAxgALaEIIAAgpIgRAAIAAgIIArAAIAAAIIgRAAIAAApgAKzEIIAAgkIgaAkIgIAAIAAgyIAJAAIAAAkIAZgkIAJAAIAAAygAG4EIIAAgWIgXAAIAAAWIgKAAIAAgyIAKAAIAAAUIAXAAIAAgUIALAAIAAAygAFvEIIAAgyIAJAAIAAAygAFREIIAAgxIAJAAIAAAxgAB4EIIAAgpIgRAAIAAgIIArAAIAAAIIgRAAIAAApgAieEIIAAgkIgaAkIgIAAIAAgyIAJAAIAAAkIAagkIAJAAIAAAygAjyEIIAAgyIAWAAQAIAAAFAEQAEAEABAGQgBADgBADQgCADgDABQAEACADACQACAEAAAEQAAAEgCADQgCADgEACQgDACgHAAgAjoEAIAMAAQAFAAADgBQADgDgBgDQABgHgLAAIgMAAgAjoDsIAKAAQAGAAACgDQACgBABgDQAAgHgLAAIgKAAgAlFEIIAAgjIgQAVIgGAAIgQgVIAAAjIgJAAIAAgyIAJAAIATAaIATgaIAJAAIAAAygApWEIIAAgkIgaAkIgIAAIAAgyIAJAAIAAAkIAZgkIAJAAIAAAygAqTEIIAAgWIgXAAIAAAWIgKAAIAAgyIAKAAIAAAUIAXAAIAAgUIAKAAIAAAygArIEIIAAgxIAJAAIAAAxgAKeDMQgCgBgDgDQgCgEgBgFIAIAAQABAEABACQACACAFAAQAEAAACgCQACgCABgEIAIAAIgDAJIgGAEIgIACQgEAAgFgCgAMBDLIgCgCIgBgEIABgDIACgCIADAAIADAAIACACIABADIgBAEIgCACIgDAAgAF4DKQAAgBgBAAQAAgBAAAAQgBgBAAAAQAAgBAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBQABAAAAAAQAAgBABAAQAAAAABgBQAAAAABAAQAAAAABAAQABAAAAAAQABAAAAAAQABABAAAAQABAAAAABQAAAAABAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAABQAAAAAAABQAAAAAAABQgBAAAAABQAAAAgBAAQAAABgBAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAAAgBgBQAAAAgBAAgAFnDKQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAgBAAgBQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAAAAAIAFgCQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAABQABAAAAAAQAAABABAAQAAABAAAAQAAABAAAAQAAABAAABQAAAAAAABQgBAAAAABQAAAAgBABQAAAAgBAAQAAABgBAAQAAAAgBAAQAAAAAAAAIgFgBgAFSDLIgBgCIgBgEIABgDIABgCIAEAAIADAAIACACIABADIgBAEIgCACIgDAAgArHDLIgCgCIgBgEIABgDIACgCIAEAAIADAAIACACIABADIgBAEIgCACIgDAAgAl+CnIAAhJIAJAAIAAAIQADgFAFgCQADgBAGAAQAHAAAEACQAGAFADAFQADAGAAAHQAAAIgDAFQgDAFgGAEQgEADgHABQgGgBgDgCQgFgCgDgEIAAAfgAltBoQgDACgDAFQgCADAAAFQAAAGACADQADAEADACQACACAFAAQAEAAAEgCQADgDACgDQACgDAAgGQAAgEgCgEQgCgFgDgCQgEgCgEAAQgEAAgDACgArsCcIAAgNIgoAAIAAANIgIAAIAAgVIAFAAQACgCABgFQABgEAAgJIABgVIAnAAIAAApIAHAAIAAAVgAsKCAIgDAHIAYAAIAAggIgUAAgALNCPIgCgCIAAgDIAAgDIACgDIAEgBIADABIACADIABADIgBADIgCACIgDACIgEgCgAF0CQIABgIIADAAQABAAAAAAQABAAAAAAQABgBAAAAQABAAAAgBQABgBABgDIABgkIAnAAIAAAxIgJAAIAAgoIgVAAIAAARQAAAJgBAFQgCAGgEACQgCADgGAAgAFGCNQgGgEgDgFQgDgFAAgIQAAgHADgGQAEgGAFgDQAGgDAHAAQAIAAAFADQAGADADAGQADAGABAHQgBAIgDAFQgDAFgGAEQgFADgIABQgHgBgGgDgAFLBoQgDADgCAEQgCADgBAFQABAGACADIAFAFQADACAFABQAEgBAEgCQAFgCABgDQACgEAAgFQAAgEgCgEQgCgEgEgDQgEgBgEAAQgFAAgDABgACcCNQgFgEgEgFQgDgFAAgIQAAgHADgGQAEgGAFgDQAGgDAHAAQAIAAAFADQAGADADAGQADAGAAAHQAAAIgDAFQgDAFgGAEQgFADgIABQgHgBgGgDgAChBoQgDADgCAEQgCADAAAFQAAAGACADIAFAFQADACAFABQAEgBAEgCQAFgCABgDQACgEAAgFQAAgEgCgEQgCgEgEgDQgEgBgEAAQgFAAgDABgAiaCNQgFgEgDgFQgDgFAAgIQAAgHADgGQADgFAFgFQAGgCAGAAQAGAAAEABQAEADACAEIAAgIIAKAAIAAAxIgKAAIAAgHQgCAEgEACQgEACgGABQgGgBgGgDgAiUBoQgEACgCAFQgCAEAAAEQAAAEACAFQACADAEADQAEACAEAAQAFAAADgCQAEgDABgDQACgDAAgGQAAgFgCgDQgBgFgEgCQgEgCgEAAQgEAAgEACgAj9CNQgGgEgDgFQgDgGAAgHQAAgHADgGQADgHAGgCQAFgDAJAAQAFgBAGADQAGADADAEIgGAGIgGgFQgEgCgEABQgFAAgEABQgEADgCAEQgCADAAAFQAAAFACAEQACADAEACQAEACAFABQAEAAAEgCQADgBADgEIAGAGQgDAEgGADQgEADgHAAQgIgBgGgDgAmxCNQgGgEgDgFQgDgFAAgIQAAgHADgGQAEgGAFgDQAGgDAHAAQAIAAAFADQAGADADAGQAEAGAAAHQAAAIgEAFQgDAFgGAEQgFADgIABQgHgBgGgDgAmsBoQgEADgCAEQgCADAAAFQAAAGACADIAGAFQAEACAEABQAFgBADgCQAEgCABgDQADgEAAgFQAAgEgDgEQgBgEgEgDQgDgBgFAAQgEAAgEABgArhCQIACgIIACAAQABAAAAAAQABAAAAAAQABgBAAAAQABAAAAgBQABgBABgDIACgkIAmAAIAAAxIgJAAIAAgoIgUAAIgBARQAAAJgBAFQgCAGgDACQgDADgGAAgAKzCPIAAgjIgaAjIgIAAIAAgxIAJAAIAAAlIAZglIAJAAIAAAxgAJ6CPIAAgiIgQAVIgGAAIgQgVIAAAiIgJAAIAAgxIAJAAIATAaIATgaIAJAAIAAAxgAI3CPIAAgwIAKAAIAAAwgAIdCPIAAgVIgYAAIAAAVIgKAAIAAgxIAKAAIAAAUIAYAAIAAgUIAKAAIAAAxgAHWCPIAAgoIgRAAIAAgIIArAAIAAAIIgRAAIAAAogAG1CPIAAgwIAJAAIAAAwgAEjCPIAAgVIgZAAIAAAVIgJAAIAAgxIAJAAIAAAUIAZAAIAAgUIAKAAIAAAxgADPCPIAAgxIAWAAQAIABAFADQAEAEABAFQgBAEgBADQgCADgDABQAEABADADQACAEAAAEQAAAFgCACQgCADgEABQgDACgHAAgADYCJIANAAQAFAAADgDQADgCgBgDQABgHgLAAIgNAAgADYBzIALAAQAGAAACgCQACgBABgDQAAgHgLAAIgLAAgAB5CPIAAgoIgZAAIAAAoIgJAAIAAgwIAsAAIAAAwgAAvCPIAAgTIgLAAIgMATIgKAAIAMgTQgFgCgDgDQgDgDAAgGQAAgHAFgFQAGgEAIAAIAXAAIAAAxgAAbBoQgCADgBADQABAEACABQAEADAEAAIAMAAIAAgQIgMAAQgGAAgCACgAgJCPIAAgVIgXAAIAAAVIgKAAIAAgxIAKAAIAAAUIAXAAIAAgUIAKAAIAAAxgAhECPIAAgVIgZAAIAAAVIgJAAIAAgxIAJAAIAAAUIAZAAIAAgUIAKAAIAAAxgAjICPIAAgoIgRAAIAAgIIAsAAIAAAIIgRAAIAAAogAkgCPIAAgjIgZAjIgJAAIAAgxIAJAAIAAAlIAZglIAJAAIAAAxgAnLCPIgNgTIgBgCIgCAAIgHAAIAAAVIgKAAIAAgxIAKAAIAAAUIAIAAIACgBIANgTIAMAAIgSAYIASAZgAoGCPIAAgjIgaAjIgIAAIAAgxIAJAAIAAAlIAaglIAJAAIAAAxgApaCPIAAgxIAWAAQAIABAFADQAEAEABAFQgBAEgBADQgCADgDABQAEABADADQACAEAAAEQAAAFgCACQgCADgEABQgDACgHAAgApQCJIAMAAQAFAAADgDQADgCgBgDQABgHgLAAIgMAAgApQBzIAKAAQAGAAACgCQACgBABgDQAAgHgLAAIgKAAgAqCCPIAAgTIgLAAIgLATIgLAAIANgTQgGgCgDgDQgDgDAAgGQAAgHAFgFQAFgEAJAAIAWAAIAAAxgAqWBoQgCADAAADQAAAEACABQAEADAEAAIAMAAIAAgQIgMAAQgFAAgDACgAI5BTIgDgDIgBgDIABgCIADgDIADgBIADABIACADIABACIgBADIgCADIgDABgAG2BTIgCgDIAAgDIAAgCIACgDIAEgBIADABIACADIABACIgBADIgCADIgDABgArVAkIAAgNIhDAAIAAgvIAJAAIAAAnIAUAAIAAgnIAKAAIAAAnIATAAIAAgnIAKAAIAAAnIAIAAIAAAVgAJoAWQgFgEgEgGQgDgFAAgHQAAgIADgFQADgGAGgDQAGgDAGAAQAHAAAGADQAEACAFAGQADAGAAAGIgBAEIgmAAQAAADACAFQACACAEACIAIACQAFAAADgCIAHgDIAGAFQgDAFgGACQgFABgIAAQgHAAgGgCgAKDgEQgCgGgDgEQgEgEgGAAQgFAAgFAEQgDAEgBAGIAdAAIAAAAgAF/AYIABgJIAEAAQADAAABgBIACgIIADg1IAxAAIAABGIgKAAIAAg9IgeAAIAAAdIgDAUQgBAGgDAFQgEACgHAAgAFbAXIgBgBIgBgEIABgDIABgCIAEgBIAEABIABACIABADIgBAEIgBABIgEABIgEgBgADOAWQgGgEgDgGQgDgGAAgGQAAgHADgGQADgGAGgDQAFgDAJAAQAFAAAGACQAGADADAEIgGAGIgGgFQgEgBgEAAQgFAAgEACQgDABgDAEQgCAEAAAFQAAAEACADQACAFAEACQAEABAFAAQAEABAEgCQADgCADgDIAGAGQgDAEgGADQgEADgHgBQgIAAgGgCgAAGAWQgGgEgCgGQgDgFAAgHQAAgIADgFQACgGAGgDQAFgDAIAAQAHAAAFADQAEACAFAGQACAGAAAGIAAAEIgmAAQAAADACAFQABACAFACIAIACQAFAAAEgCIAGgDIAFAFQgDAFgGACQgEABgHAAQgIAAgGgCgAAhgEQgCgGgDgEQgEgEgFAAQgFAAgGAEQgEAEAAAGIAdAAIAAAAgAhDAYIABgJIADABQABAAAAAAQABAAAAAAQABgBAAAAQABAAAAgBQABgBABgDIABgiIAoAAIAAAvIgKAAIAAgnIgVAAIAAAQQAAAJgCAFQgBAGgDACQgDADgGgBgAhxAWQgGgEgDgGQgDgFAAgHQAAgIADgFQADgGAGgDQAFgDAGAAQAGAAADACQAFACADAEIAAgHIAJAAIAAAvIgJAAIAAgHQgDAEgFADQgDABgGAAQgGAAgFgCgAhsgOQgDABgCAEIgCAJQAAADACAFQACADADADQADACAFAAQAFAAACgCQAEgDACgDQACgEAAgEQAAgFgCgEQgCgEgEgBQgDgDgEAAQgEAAgEADgAioAXQgFgDgDgEIAFgFQADADADABQAFACAEAAQAFAAAEgDQADgBAAgEQAAgHgKAAIgKAAIAAgGIAIAAQAGAAACgBQACgCAAgEQABgDgDgCQgDgCgFAAQgIAAgFAGIgGgGQADgDAGgCQAEgCAHAAQAJAAAFADQAFAEgBAGQABAEgCADQgCADgEABQAEABADADQACACAAAFQAAAEgCADQgDAEgFACQgEACgHgBQgHAAgFgBgAjpAWQgGgEgDgGQgDgGAAgGQAAgHADgGQAEgGAFgDQAFgDAJAAQAHAAAEACQAHADACAEIgFAFIgHgFQgEgCgEAAQgFABgDACQgEABgBADQgDADgBAEIAZAAIAAAHIgZAAQABAGAFAEQAEADAHAAQAEAAAEgBQAEgCADgDIAFAGQgDAEgGADQgEABgHAAQgIAAgGgCgAklAWQgGgEgDgGQgDgFAAgHQAAgIADgFQADgGAGgDQAFgDAGAAQAGAAADACQAFACADAEIAAgHIAJAAIAAAvIgJAAIAAgHQgDAEgFADQgDABgGAAQgGAAgFgCgAkggOQgDABgCAEIgCAJQAAADACAFQACADADADQADACAFAAQAFAAACgCQAEgDACgDQACgEAAgEQAAgFgCgEQgCgEgEgBQgDgDgEAAQgEAAgEADgAndAYIACgJIACABQABAAAAAAQABAAAAAAQABgBAAAAQABAAAAgBQACgBAAgDIACgiIAmAAIAAAvIgJAAIAAgnIgUAAIgBAQQAAAJgCAFQgBAGgDACQgDADgGgBgAq/AWQgGgEgDgGQgDgFAAgHQAAgHADgGQAEgGAFgDQAGgDAHAAQAIAAAFADQAGADADAGQAEAFAAAIQAAAHgEAFQgDAGgGAEQgFACgIAAQgHAAgGgCgAq6gOQgEACgCADQgCAEAAAFQAAAEACAEIAGAGQAEABAEAAQAFAAADgBQAEgDABgDQADgEAAgEQAAgEgDgFQgBgDgEgCQgDgCgFAAQgEAAgEACgAIPAXIAAgvIAJAAIAAAnIAUAAIAAgnIAJAAIAAAnIAUAAIAAgnIAKAAIAAAvgAH1AXIAAgiIgaAiIgIAAIAAgvIAJAAIAAAjIAZgjIAJAAIAAAvgAEpAXIAAgvIAKAAIAAARIAKAAQAJAAAGAEQAFADAAAHQAAAJgFAEQgGADgJAAgAEzAQIAKAAQAKAAABgJQgBgDgCgCQgEgCgEAAIgKAAgAEDAXIAAgnIgRAAIAAgIIAsAAIAAAIIgRAAIAAAngACxAXIAAgvIAJAAIAAAvgACWAXIAAgVIgXAAIAAAVIgKAAIAAgvIAKAAIAAATIAXAAIAAgTIAKAAIAAAvgABlAXIgNgTIgBgBIgFAAIAAAUIgKAAIAAgUIgFAAIgCABIgMATIgLAAIAQgZIgQgWIALAAIAMARIACACIABAAIAEAAIAAgTIAKAAIAAATIAEAAIABAAIAOgTIAKAAIgQAWIARAZgAk/AXIgMgTIgCgBIgKAAIAAAUIgJAAIAAgvIAJAAIAAATIAIAAIACAAIAOgTIALAAIgRAWIARAZgAl6AXIAAgiIgZAiIgJAAIAAgvIAJAAIAAAjIAZgjIAJAAIAAAvgAnpAXIgMgTIgCgBIgKAAIAAAUIgJAAIAAgvIAJAAIAAATIAIAAIADAAIANgTIALAAIgRAWIARAZgAokAXIAAgiIgZAiIgJAAIAAgvIAJAAIAAAjIAagjIAJAAIAAAvgAp4AXIAAgvIAWAAQAIgBAFAEQAFAEAAAFQAAAEgCADQgCAEgDAAQAEABADADQACADAAAEQAAAEgCADQgCADgEACQgEABgFAAgApvAQIAOAAQAEAAADgCQACgCABgDQgBgHgJAAIgOAAgApvgEIALAAQAFAAADgBQADgCAAgEQAAgGgLAAIgLAAgACygkIgCgDIgBgCIABgEIACgCIAEgBIADABIACACIABAEIgBACIgCADIgDAAgAqWhIIAAhJIAKAAIAAAIQACgEAFgDQADgCAGAAQAHAAAEAEQAGAEADAFQADAGAAAHQAAAIgDAFQgDAFgGAFQgEADgHAAQgGAAgDgCQgFgCgCgFIAAAfgAqFiHQgEACgCAEQgCAEAAAFQAAAFACAEQACAEAEACQAEACADAAIAIgCQADgCACgEQACgEAAgFIgCgJQgCgEgDgCQgEgCgEAAQgEAAgDACgAGmhRIAGgHQACgEAAgDIgEgCQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAgBAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAgBABAAQAAAAAAgBQABAAAAAAQABAAABAAQAAgBABAAQADABACACQACACAAAEQAAAHgDAFQgDAFgHAFgADOhiQgFgDgEgGQgDgFAAgIQAAgHADgGQAEgGAFgDQAGgDAHgBQAIABAFADQAGADADAGQAEAGAAAHQAAAIgEAFQgDAGgGADQgFADgIABQgHgBgGgDgADTiHQgEADgCADQgCAEAAAFQAAAFACAEIAGAGQAEACAEAAQAFAAADgCQAFgDAAgDQADgEAAgFQAAgFgDgEQgBgDgEgDQgDgCgFAAQgEAAgEACgAjLhhQgGgFgDgFQgDgGAAgHQAAgHADgGQAEgGAFgDQAFgDAIgBQAGABAHACQAFACADAFIgGAGIgHgFQgDgBgFgBQgFAAgDACQgDADgCADQgCAEAAAFQAAAFACADQACAFADACQADACAFAAQAFgBADgBQAEgCADgDIAGAGQgDAFgFACQgFACgIABQgHAAgGgDgAm1hfIABgIIADAAQABAAAAAAQABAAAAAAQABgBAAAAQABAAAAAAQABgBABgFIABgjIAnAAIAAAyIgJAAIAAgpIgVAAIAAARQAAAJgBAFQgCAGgDACQgDACgGABgAnjhiQgFgDgEgGQgDgFAAgIQAAgHADgGQAEgGAFgDQAGgDAHgBQAIABAFADQAGADADAGQADAGAAAHQAAAIgDAFQgDAGgGADQgFADgIABQgHgBgGgDgAneiHQgDADgCADQgCAEgBAFQABAFACAEIAFAGQADACAFAAQAEAAAEgCQAFgDABgDQACgEAAgFQAAgFgCgEQgCgDgEgDQgEgCgEAAQgFAAgDACgAoahgQgFgDgDgEIAFgGQADAEADABQAFACAEAAQAGAAADgCQADgCAAgEQAAgHgKAAIgKAAIAAgGIAIAAQAGAAACgDQACgBAAgDQABgDgDgDQgDgBgFgBQgIABgGAFIgFgGQADgDAGgDQAEgCAHAAQAJABAFADQAEAEAAAHQABADgCADQgCADgEABQAEABADADQACADAAAEQAAAGgCACQgDAEgFACQgEABgHABQgIAAgEgCgApRhiQgFgDgEgGQgDgFAAgIQAAgHADgGQAEgGAFgDQAFgDAIgBQAIABAFADQAGADADAGQADAGABAHQgBAIgDAFQgDAGgGADQgFADgIABQgIgBgFgDgApMiHQgDADgDADQgCAEAAAFQAAAFACAEIAGAGQAEACAEAAQAFAAADgCQAFgDAAgDQADgEAAgFQAAgFgDgEQgBgDgEgDQgDgCgFAAQgEAAgEACgArJhhQgGgFgDgFQgDgFAAgIQAAgHADgGQADgFAGgEQAFgEAIAAQAHAAAFAEQAEACAFAGQACAGAAAHIAAADIgmAAQAAAFACADQABADAFADIAIABQAFAAAEgBIAGgFIAFAGQgDAFgGACQgEACgHAAQgIAAgGgDgAquh8QgCgGgDgEQgEgDgFgBQgGABgFADQgDAEgBAGIAdAAIAAAAgAGQhfIAAgWIgYAAIAAAWIgJAAIAAgxIAJAAIAAATIAYAAIAAgTIAKAAIAAAxgAFVhfIAAgkIgZAkIgJAAIAAgxIAJAAIAAAjIAZgjIAJAAIAAAxgAENhfIAAgpIgQAAIAAgJIArAAIAAAJIgRAAIAAApgAC1hfIgOgUIgBgCIgJAAIAAAWIgKAAIAAgxIAKAAIAAATIAIAAIABgBIABgBIAOgRIAKAAIgRAXIASAagAB/hfIAAgxIAKAAIAAAxgABlhfIAAgWIgYAAIAAAWIgKAAIAAgxIAKAAIAAATIAYAAIAAgTIAKAAIAAAxgAgChfIAAgyIAIAAIAAASIALAAQAKAAAFAEQAFADAAAIQAAAJgFADQgFAFgKAAgAAGhnIAKAAQAMAAAAgJQAAgDgDgDQgEgCgFAAIgKAAgAgohfIAAgpIgRAAIAAgJIAsAAIAAAJIgRAAIAAApgAhOhfIAAgkIgZAkIgJAAIAAgxIAJAAIAAAjIAagjIAJAAIAAAxgAiVhfIAAgpIgRAAIAAgJIArAAIAAAJIgRAAIAAApgAjohfIAAgxIAKAAIAAAxgAj/hfIAAgjIgQAVIgGAAIgQgVIAAAjIgJAAIAAgxIAJAAIATAZIATgZIAJAAIAAAxgAl0hfIAAgyIAJAAIAAASIALAAQAJAAAGAEQAFADAAAIQAAAJgFADQgGAFgJAAgAlrhnIAKAAQALAAAAgJQAAgDgCgDQgEgCgFAAIgKAAgArohfIgFgPIggAAIgGAPIgJAAIAbhIIAIAAIAcBIgArwh2IgOgiIgMAiIAaAAgACBicIgCgCIgCgEIACgDIACgCIADAAIADAAIACACIABADIgBAEIgCACIgDAAgAjmicIgCgCIgCgEIACgDIACgCIACAAIAEAAIACACIABADIgBAEIgCACIgEAAgAipjAIACgIIAFABQABAAABAAQABAAAAAAQABAAAAgBQABAAAAAAQAAAAABAAQAAgBABAAQAAAAABgBQAAAAAAgBIAGgNIgUgwIAKAAIAPAlIAPglIAKAAIgWA2QgDAIgDADQgDAFgEACQgEACgEAAgAAbjAIAAhJIAKAAIAAAIQADgFADgCQAEgBAGAAQAGAAAGACQAFAFADAFQADAGAAAHQAAAIgDAFQgDAFgFAEQgGADgGABQgGgBgEgCQgDgCgDgEIAAAfgAArj/QgDACgCAEQgCAEAAAFQAAAGACADQACAEADACQAEACAEAAIAIgCQAEgDACgDQABgDAAgGIgBgJQgDgEgDgCQgEgCgEAAQgEAAgEACgAF5jYIgCgCIgBgDIABgDIACgDIAEgBIADABIACADIACADIgCADIgCACIgDACIgEgCgACXjZQgFgCgEgDIAGgHQACADAFACQAFACADAAQAGAAADgDQADgBAAgEQAAgHgKAAIgKAAIAAgHIAIAAQAFAAACgCQAEgBAAgDQgBgDgCgDQgDgCgEABQgJgBgGAGIgFgFQADgEAFgDQAFgBAHAAQAJAAAFADQAEAEABAGQAAAEgCADQgCADgEACQAEAAAEADQABADAAAFQAAAFgCADQgDADgEACQgFACgHAAQgHgBgFgCgAhnjaQgGgEgDgFQgDgGAAgHQAAgHADgGQAEgHAFgCQAFgDAIAAQAGgBAHADQAFADADAEIgGAGIgHgFQgDgCgFABQgFAAgDABQgDADgCAEQgCADAAAFQAAAFACAEQACADADACQADACAFABQAFAAADgCQAEgBADgEIAGAGQgDAEgFADQgFADgIAAQgHgBgGgDgAjfjaQgGgEgDgFQgDgGAAgHQAAgHADgGQADgHAGgCQAGgDAIAAQAHgBAEADQAGADADADIgFAGIgHgFQgEgCgEABIgIABIgFAFIgEAHIAYAAIAAAHIgYAAQABAHAFADQAEAFAHAAQAEAAAEgCQAEgBADgEIAFAGQgDAEgGACQgEACgHABQgIgBgGgDgAkbjaQgGgEgDgFQgDgFAAgIQAAgHADgGQADgFAGgFQAFgCAGAAQAGAAADABQAGADABAEIAAgIIAKAAIAAAxIgKAAIAAgHQgBAEgGACQgDACgGABQgGgBgFgDgAkWj/QgDACgCAEIgCAJQAAAEACAFQACADADADIAIACQADAAAEgCQAFgDABgDQACgDAAgGQAAgFgCgEQgBgEgFgCQgDgCgEAAQgEAAgEACgAmIjaQgFgCgEgGQgEgFAAgGIgHAAIAAAVIgKAAIAAgwIAKAAIAAATIAHAAQADgIACgDQACgDAGgEQAGgDAFABQAIAAAGADQAFADADAGQADAGAAAHQAAAIgDAFQgDAGgFADQgGAEgIAAQgGgBgFgDgAmEj/QgDAEgCADQgCADAAAFQAAAGACADQABACAEADQADACAEABQAFgBADgCQADgCADgDQABgEAAgFQAAgEgBgEQgDgFgDgCQgDgBgFAAQgEAAgDABgAnnjXIABgIIADAAQABAAAAAAQABAAAAAAQABgBAAAAQABAAAAgBQACgBAAgDIACgkIAnAAIAAAxIgKAAIAAgoIgUAAIgBARQAAAJgCAFQgBAGgDACQgDADgGAAgArJjaQgGgEgDgFQgDgFAAgIQAAgHADgGQADgFAGgFQAFgCAIAAQAHAAAFACQAEADAFAGQACAGAAAHIAAADIgmAAQAAAFACAEQABACAFACIAIACQAFAAAEgCIAGgEIAFAHQgDADgGACQgEACgHABQgIgBgGgDgAquj0QgCgHgDgDQgEgEgFABQgGgBgFAEQgDADgBAHIAdAAIAAAAgAFHjYIAAgxIAVAAQAJABAFADQAFAEgBAFQABAEgCADQgDADgCABQAEABACADQADAEAAAEQAAAFgCACQgCADgEABQgDACgGAAgAFQjeIANAAQAFAAADgDQACgCAAgDQAAgHgKAAIgNAAgAFQj0IALAAQAFAAADgCQADgBgBgDQAAgHgKAAIgLAAgAEzjYIAAgwIAKAAIAAAwgAEjjYIgOgTIgBgCIgKAAIAAAVIgJAAIAAgwIAJAAIAAATIAIAAIACgBIABgBIAOgRIAKAAIgRAXIARAZgADnjYIAAgjIgaAjIgIAAIAAgwIAJAAIAAAjIAZgjIAJAAIAAAwgAB5jYIAAgjIgaAjIgIAAIAAgwIAJAAIAAAjIAZgjIAKAAIAAAwgAgJjYIgNgSIgOASIgLAAIASgYIgSgYIALAAIAOARIANgRIALAAIgSAYIASAYgAg+jYIAAgwIAKAAIAAAwgAk4jYIAAgUQgHADgHABQgDgBgHgCQgDgCgDgDQgCgGgBgEIAAgOIAKAAIAAANQABAFACACQACACAGABQAIAAAEgDIAAgUIAKAAIAAAwgAnzjYIgMgTIgCgCIgKAAIAAAVIgJAAIAAgwIAJAAIAAATIAIAAIACgBIAOgSIALAAIgRAXIARAZgAoujYIAAgjIgZAjIgJAAIAAgwIAJAAIAAAjIAZgjIAJAAIAAAwgAqCjYIAAgxIAVAAQAJABAFADQAFAEgBAFQAAAEgBADQgDADgCABQAEABACADQADAEAAAEQAAAFgCACQgCADgEABQgEACgFAAgAp5jeIAOAAQAEAAADgDQADgCAAgDQgBgHgJAAIgOAAgAp5j0IALAAQAFAAADgCQACgBAAgDQABgHgLAAIgLAAgArnjYIAAggIglAAIAAAgIgKAAIAAhHIAKAAIAAAeIAlAAIAAgeIAKAAIAABHgAE1kUIgCgDIgCgDIACgCIACgDIADgBIADABIACADIABACIgBADIgCADIgDABgAg8kUIgDgDIgBgDIABgCIADgDIACgBIAEABIACADIABACIgBADIgCADIgEABg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.urText, new cjs.Rectangle(-79.7,-28.8,159.5,57.7), null);


(lib.t2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AjVBoQgUgHgOgNIAVggQALAJAPAHQAPAGAOAAQASAAAJgIQAKgIgBgOQABgMgJgIQgIgGgPAAIgdAAIAAgiIAVAAQAQAAAKgHQAIgHAAgMQAAgNgJgIQgJgGgQAAQgNAAgMAEQgMAFgNAJIgTggQANgMAUgGQASgHAUAAQAXABAQAGQARAHAIAOQAKANAAATQAAAPgGAMQgHANgLAHQAOAHAIAMQAIANAAASQAAATgKAPQgKAOgRAHQgRAHgWABQgXgBgWgHgACWBrIAuhFQgEABgIABQgTAAgRgKQgRgIgKgSQgKgOAAgWQAAgVAKgRQALgSASgKQARgKAYAAQAWABASAIQAUALAIAQQALARAAAVQAAAQgFAPQgFAOgNAUIg0BMgACrhBQgIAFgFAJQgFAJgBAKQABAKAFAJQAFAJAIAEQAJAFALgBQAKABAJgFQAHgEAGgJQAFgKAAgJQAAgMgFgHQgFgKgIgEQgJgFgKAAQgLAAgJAFgAgdBrIAthFQgEABgIABQgSAAgSgKQgRgJgJgRQgLgPABgVQAAgVAKgRQAKgSATgKQARgKAXAAQAWABASAIQATALAJAQQAKAPAAAXQAAARgEAOQgFAOgNAUIg0BMgAgIhBQgJAFgFAJQgEAIgBALQABALAEAIQAFAJAJAEQAIAFAKgBQALABAJgFQAHgEAFgJQAGgIAAgLQgBgLgEgIQgFgKgIgEQgJgFgLAAQgKAAgIAFgAk/BrIAAipIg5AZIAAgmIBBgcIAiAAIAADSgAFDAHQgGgBgEgEQgEgDgDgGQgCgGgBgHQABgGACgGIgHAAIAAgNIASAAIAFgFIAHgFIgeAAIAAgNIAwAAQADgCADgEQACgDAAgFQAAgGgFgEQgFgDgJAAIgGAAIgHACIgHAEIgHAGIAAgUQAMgIAOAAQAJAAAFACQAGABAGAFQAFAEACAFQADAGAAAHIgBAHIgDAGIAKAAIAAANIgXAAIgPAKIAmAAIAAANIg0AAIgEAGQgBADAAADIAAAGIAEAEQADAEADAAQAEABAFABIAHgBIAJgEIAIgEIAHgHIAAAUQgJAFgGACQgJADgJAAQgHAAgHgDg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t2, new cjs.Rectangle(-37.7,-11.1,75.4,22.3), null);


(lib.t1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#35303E").s().p("AloDiIAAiXIAUAAIAAAPQAGgJAJgEQAJgFALABQAOgBAKAHQAKAGAHANQAGAMAAAPQAAAQgGAMQgHAMgKAHQgLAGgNAAQgLABgJgFQgJgEgGgJIAABBgAlFBfQgIAFgDAHQgEAIAAAKQAAAMAEAGQADAIAIAFQAHAFAJgBQAJABAHgFQAIgFADgIQAEgHAAgLQAAgJgEgJQgDgHgIgFQgHgFgJABQgJgBgHAFgACnCsQgMgHgHgNQgHgMAAgPQAAgOAGgNQAHgLAMgIQALgGASAAQAOgBAKAFQAMAFAGAJIgMAMQgEgGgJgEQgHgEgKAAQgHAAgJAEQgHADgFAHQgFAGgBAJIAyAAIAAAOIgyAAQACAOAJAIQAIAHAPAAQAJAAAIgDQAIgDAFgHIAMAMQgGAJgLAFQgLAEgOAAQgQAAgMgGgAjbCsQgLgIgGgLQgGgLAAgRQAAgPAGgMQAGgMALgHQALgHAOABQALgBAIAFQAJAEAGAJIAAgPIAUAAIAABlIgUAAIAAgPQgGAJgJAEQgIAFgLgBQgNAAgMgGgAjPBfQgGAEgFAIQgEAJAAAJQAAALAEAHQAEAJAHAEQAHAFAJgBQAJABAIgFQAHgFAEgIQAEgHAAgLQAAgJgEgJQgEgHgHgFQgIgFgJABQgJgBgHAFgAnRCsQgKgHgHgMQgGgMAAgQQAAgPAGgMQAHgNAKgGQALgHAOABQAKgBAJAFQAIAEAHAJIAAgPIAUAAIAABlIgUAAIAAgPQgHAJgIAEQgJAFgKgBQgNAAgMgGgAnFBfQgIAFgDAHQgEAJAAAJQAAALAEAHQADAIAIAFQAHAFAJgBQAKABAGgFQAHgEAFgJQAEgHAAgLQAAgJgEgJQgFgIgHgEQgGgFgKABQgJgBgHAFgArBCuQgLgEgGgJIALgMQAFAGAIAEQAJADAJAAQAMAAAHgEQAGgFAAgHQAAgOgVAAIgVAAIAAgOIARAAQAKAAAGgEQAGgEAAgHQAAgGgGgEQgFgFgKAAQgSAAgLANIgLgNQAGgHALgEQAKgEAOAAQATgBAKAIQAKAHAAAOQAAAIgEAFQgEAIgHABQAJADAFAGQAFAHAAAJQAAAJgFAHQgFAHgLAEQgKADgOAAQgNABgMgFgAE9CsQgLgFgHgLQgGgLgCgOIgQAAIAAAtIgUAAIAAhlIAUAAIAAAoIARAAQACgMAHgKQAHgKAKgGQAKgEAOAAQAPgBALAHQAMAIAGALQAGAMAAAPQAAAQgGALQgGAMgMAHQgLAHgPAAQgOAAgLgGgAFGBfQgHAEgEAIQgEAIAAAKQAAAMAEAGQAEAIAHAFQAHADAJAAQAIAAAHgDQAHgFAEgIQAEgIAAgKQAAgJgEgJQgEgIgHgEQgHgEgIAAQgJAAgHAEgABlCwIAAhlIAUAAIAABlgAAbCwIAAhUIgiAAIAAgRIBZAAIAAARIgjAAIAABUgAgrCwIAAgtIgyAAIAAAtIgUAAIAAhlIAUAAIAAAoIAyAAIAAgoIAUAAIAABlgAo3CwIAAhlIBHAAIAAARIgzAAIAABUgABpAyIgFgEQgCgDAAgDQAAgEACgDIAFgFQADgCADAAQAEAAADACIAFAFQABADAAAEQAAADgBADIgFAEQgDACgEAAQgDAAgDgCgAlugUIgIgCIADgRIANABQAGAAADgCQADgBAFgFIAHgNIAEgNIgqhlIAVAAIAfBPIAfhPIAVAAIguBxQgHAPgFAJQgGAJgHAEQgIADgKAAIgJAAgApNgUIgIgCIADgRIAMABQAHAAADgCQADgBAFgFQAEgGACgHIAFgNIgqhlIAVAAIAfBPIAfhPIAVAAIguBxQgHAPgFAJQgHAKgGADQgIADgKAAIgJAAgABQgWIAAgwQgPgBgNgGQgNgHgHgMQgGgLAAgPQAAgPAGgMQAHgMANgGQAMgIAQAAIAAgyIAUAAIAAAyQAQAAAMAIQAMAGAHAMQAHAMAAAPQAAAOgHAMQgHAMgMAHQgMAGgQABIAAAwgABkhYQAKAAAHgFQAIgFAFgHQAEgIAAgJQAAgKgEgIQgFgIgIgEQgHgEgKgBgAA+iYQgIAFgEAHQgEAIAAAKQAAAJAEAIQAEAHAIAFQAIAFAKAAIAAhFQgLABgHAEgAE4guIAAgaIhYAAIAAhlIAUAAIAABUIAyAAIAAhUIAUAAIAABUIAPAAIAAArgAKDhMQgLgHgHgMQgHgNAAgOQAAgPAHgMQAHgNALgGQALgIAQABQARgBALAIQALAGAHANQAHAMAAAPQAAAOgHANQgHAMgLAHQgNAGgPABQgOgBgNgGgAKOiZQgHAFgFAIQgEAHAAALQAAALAEAHQAFAHAHAEQAHAFAJAAQAKAAAHgFQAHgDAFgIQAEgIAAgKQAAgKgEgIQgFgIgHgFQgHgEgKAAQgJAAgHAEgAhHhMQgMgHgHgMQgHgNAAgOQAAgPAHgMQAHgNAMgGQALgIAQABQAQgBALAIQAMAGAGANQAHAMAAAPQAAAOgHANQgGAMgMAHQgMAGgPABQgOgBgNgGgAg8iZQgIAFgEAIQgEAIAAAKQAAAKAEAIQAEAIAIADQAHAFAJAAQAJAAAIgFQAHgEAEgHQAEgHAAgLQAAgLgEgHQgEgIgHgFQgIgEgJAAQgJAAgHAEgAJDhIIAAgtIgyAAIAAAtIgUAAIAAhlIAUAAIAAAoIAyAAIAAgoIAUAAIAABlgAHQhIIAAhKIg0BKIgTAAIAAhlIATAAIAABJIA1hJIATAAIAABlgAFchIIAAhlIAUAAIAABlgACyhIIAAhlIAUAAIAABlgAi1hIIAAhKIg1BKIgSAAIAAhlIATAAIAABJIA1hJIASAAIAABlgAmVhIIAAhUIgyAAIAABUIgUAAIAAhlIBaAAIAABlgApqhIIgshAIgDgDIgFAAIgTAAIAABDIgUAAIAAiUIAUAAIAAA+IAUAAIAEAAIADgEIApg6IAXAAIgxBIIA0BMgAGmjCQgHgDgFgIQgFgHgBgJIAQAAQABAHAFAEQAEAEAJABQAJgBAEgEQAFgEABgHIAQAAQgBAKgFAGQgFAHgHAEQgHAEgKgBQgKABgHgEgAjfjCQgIgEgEgHQgFgGgBgKIAQAAQABAHAFAEQAEAEAJABQAIgBAFgEQAFgEABgHIAQAAQgCAKgEAGQgEAHgJAEQgHAEgJgBQgKABgHgEgAFfjGQgDgBgCgDIgCgHIACgGQACgDADgCQACgBAEAAQAEAAADABQADADACACQABADAAADQAAAEgBADQgCADgDABIgHADIgGgDgAC2jGQgDgBgCgDQgCgCAAgFQAAgEACgCQACgDADgCQACgBAEAAQAEAAADABQADACABADQACACAAAEQAAAFgCACQgBADgDABIgHADIgGgDg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1, new cjs.Rectangle(-72.3,-22.6,144.6,45.2), null);


(lib.r_part = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#35303E").s().p("AhijHQBSAAA5A7QA6A6AABSQAABTg6A6Qg5A7hSAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.r_part, new cjs.Rectangle(-9.9,-20,19.9,40), null);


(lib.l_part = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#35303E").s().p("AgoCNQg7g6AAhTQAAhSA7g6QA5g7BTAAIAAGPQhTAAg5g7g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.l_part, new cjs.Rectangle(-9.9,-20,19.9,40), null);


(lib.iqos_logo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhxGrIgegeIgEgCIgDgBIiGAAQgqAAgYgVQgXgSAAgeIAAhyQABgFADgDQAEgEAFAAICZAAQApAAAZAUQAWATAAAeIAAA1QAAAGgDADQgEADgEABIgFAAQgFgBgEgDQgDgDAAgGIAAg1QAAgIgDgGQgEgHgFgGQgIgGgNgEQgLgDgQAAIiFAAIgDABIgBADIAABdQAAAIAEAHQACAHAHAFQAHAHANADQAMADAPAAICOAAIAHABIAGAFIAkAkQADADAAAFQAAAFgDAEIgDADQgEADgEAAQgHAAgCgDgAEcGKQgOAAgNgFQgNgGgJgJIgHgGQgDgDgBgGQABgFADgDIADgEQADgDAFAAQAFAAAEADIAHAHQAGAFAHADQAHADAJAAIBgAAQAOABAKgDQAKgDAGgEIAFgHQACgEAAgHQAAgHgCgDQgCgEgDgEQgGgEgKgDQgKgCgOAAIhRAAQglAAgVgQQgRgOAAgXIAAgGQAAgYARgOQAVgPAlAAIBZAAQANAAAMAFQAMAEAKAJIAIAIQAEADAAAFQAAAFgCAEIgDADQgEAEgFAAQgFABgEgEIgIgHQgFgFgJgEQgHgCgHAAIhZAAQgNAAgLACQgKADgGAFQgDACgCAEQgBAEAAAHQAAAHABAEQACAEADADQAGAFAKACQALACANABIBRAAQAmgBATAQQASANAAAYIAAAGQAAAYgSAOQgTAPgmAAgAARGKQgoAAgZgVQgWgSAAgeIAAg5QAAgeAWgTQAZgUAoAAIBOAAQApAAAYAUQAWATABAeIAAA5QgBAegWASQgYAVgpAAgAgJDnQgMAEgJAGQgFAGgDAHQgEAGABAIIAAA5QgBAIAEAHQADAHAFAFQAJAHAMADQALADAPAAIBOAAQAPAAAMgDQAMgDAHgHQAHgFADgHQAEgHAAgIIAAg5QAAgJgEgFQgDgHgHgGQgHgGgMgEQgMgDgPAAIhOAAQgPAAgLADgAm6GKQgEAAgFgDQgDgEAAgFIAAirQAAgFADgDQAFgEAEAAIAEAAQAGAAADAEQAEAEAAAEIAACrQAAAFgEAEQgDADgGAAgAhtAxQgpABghgVQgggTgTggQgSgggBgmQgBgmAUgkIBvi/QAUgiAigTQAhgTAkAAQAmAAAgATQAiATAUAiIBvC/QAUAkgBAmQgBAmgSAgQgTAgggATQgiAVgogBgAhJlLQghAOgaAaQgaAbgOAhQgPAkAAAmQAAAnAPAiQAOAhAaAcQAaAZAhANQAkAQAlAAQAmAAAkgQQAhgNAagZQAagcAOghQAPgiAAgnQAAgmgPgkQgOghgagbQgagaghgOQgkgPgmAAQglAAgkAPg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.iqos_logo, new cjs.Rectangle(-45.5,-43,91,86), null);


(lib.ic = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFDFB").ss(1.5,1,0,4).p("AAhAFQgYgKgaACQgIAAgHAC");
	this.shape.setTransform(1,-9.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#FFFDFB").ss(1.5,1,0,4).p("AA8gJQgYgLgaACQgnADgaAeQgCACgCAD");
	this.shape_1.setTransform(-1.8,-7.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#FFFDFB").ss(1.5,1,0,4).p("ABGgqQgYgLgbACQgnADgaAfQgaAdADAp");
	this.shape_2.setTransform(-2.7,-4.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#FFFDFB").ss(1.5,1,0,4).p("ABGhIQgYgLgbACQgnAEgaAeQgaAfADAoQADAiAXAY");
	this.shape_3.setTransform(-2.7,-1.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#FFFDFB").ss(1.5,1,0,4).p("ABGhXQgYgLgbACQgnAEgaAeQgaAfADAoQAEAoAfAaQAWASAZAE");
	this.shape_4.setTransform(-2.7,-0.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f().s("#FFFDFB").ss(1.5,1,0,4).p("ABGhXQgYgLgbACQgnADgaAfQgaAfADAnQAEAoAfAbQAfAaAngEQASgBAQgI");
	this.shape_5.setTransform(-2.7,0);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#FFFDFB").ss(1.5,1,0,4).p("AAwhXQgYgLgaACQgoADgaAfQgaAfADAnQAEAoAfAbQAfAaAngEQAogDAagfQAHgIAFgJ");
	this.shape_6.setTransform(-0.5,0);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f().s("#FFFDFB").ss(1.5,1,0,4).p("AAqhXQgYgLgZACQgoADgaAfQgbAfAEAnQADAoAfAbQAfAaAngEQAogDAbgfQAagfgEgn");

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f().s("#FFFDFB").ss(1.5,1,1).p("AgQgRIAhAj");
	this.shape_8.setTransform(-3,0.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f().s("#FFFDFB").ss(1.5,1,1).p("AgggUIAmApIAbgb");
	this.shape_9.setTransform(-1.4,1.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f().s("#FFFDFB").ss(1.5,1,1).p("Ag1gFIAnApIBEhH");
	this.shape_10.setTransform(0.7,-0.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f().s("#FFFDFB").ss(1.5,1,1).p("AhFAKIAoAqIBjhn");
	this.shape_11.setTransform(2.3,-1.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_7},{t:this.shape_8}]},1).to({state:[{t:this.shape_7},{t:this.shape_9}]},1).to({state:[{t:this.shape_7},{t:this.shape_10}]},1).to({state:[{t:this.shape_7},{t:this.shape_11}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.dev_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(67,119,134,0.6)").s().p("AgvAWQgEgKAIgHQAEgEAGgBQALgGAEAAQALABADAJQADAJgHAIQgCACgLAFIgMAEIgBAAQgJAAgEgKgAAFAEQgEgEAAgHQABgKAOgIQAHgEAHgBQAJgCAFAFQAFAEAAAGQABAGgEAFQgCADgFACIgIADQgLAGgDAAIgCAAQgFAAgFgEg");
	this.shape.setTransform(-38.7,-51.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(67,119,134,0.6)").s().p("AgTAPQgFgEABgHQAAgJAPgIQAGgEAHgCQAIgBAGAEQAEAEABAGQABAGgEAEQgDADgEACIgJAEQgJAGgEABIgBAAQgFAAgFgFg");
	this.shape_1.setTransform(-36.1,-52.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},1).to({state:[]},9).wait(1));

	// Слой_1
	this.instance = new lib.dev();
	this.instance.parent = this;
	this.instance.setTransform(-121,-191);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(11));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-121,-191,242,382);


(lib.btn_txt = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AA3A2QgJgHgFgIQgEgJAAgMQAAgMAEgIQAFgJAJgGQAJgFAKgBQAGABAJADQAGADAFAIIAAgNIAQAAIAABNIgQAAIAAgLQgEAHgHADQgHAEgIAAQgLAAgIgFgABAgFQgFAEgEAEQgDAHAAAIQAAAHADAHQAEAGAFADQAGAEAGAAQAIAAAFgEQAFgDAEgGQADgHAAgHQAAgIgDgHQgEgEgFgEQgFgDgIAAQgGAAgGADgAgWA2QgKgHgFgJQgFgIAAgMQAAgLAFgJQAFgJAJgFQAKgHAMAAQAJAAAJAFQAJAEAFAHIgJAIQgEgDgHgEQgGgCgGAAQgHAAgGADQgGAEgDAEQgDAHAAAIQAAAIADAFQACAHAHADQAGADAHABQAHAAAFgEQAGgCAFgFIAJAKQgFAHgJAEQgJAEgJAAQgNAAgIgFgAihA2QgJgGgFgJQgFgJAAgMQAAgMAFgIQAFgKAJgFQAJgFAJgBQAIABAHADQAHADAFAIIAAgNIAPAAIAABNIgPAAIAAgLQgEAHgIADQgGAEgJAAQgLAAgHgFgAiYgFQgGAEgDAEQgDAHAAAIQAAAHADAHQADAFAGAEQAFAEAHAAQAIAAAEgEQAGgEADgFQAEgHAAgHQAAgIgEgHQgDgEgGgEQgEgDgIAAQgHAAgFADgAD5A4IAAg/IgbAAIAAgOIBGAAIAAAOIgbAAIAAA/gADDA4IAAg4IgpA4IgOAAIAAhNIAPAAIAAA5IApg5IANAAIAABNgAjYA4IAAgzIg7AAIAAAzIgQAAIAAhxIAQAAIAAAxIA7AAIAAgxIAQAAIAABxgACigkQgGgEgDgFQgDgFgCgIIAMAAQABAGAEADQAEAEAGAAQAHAAADgEQAEgDABgGIAMAAQgBAGgDAHQgEAFgGAEQgGACgHAAQgGAAgHgCg");
	this.shape.setTransform(0,-1.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.btn_txt, new cjs.Rectangle(-29.2,-7.4,58.4,11.8), null);


(lib.btn_round = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#35303E").s().p("AiMCNQg7g6AAhTQAAhSA7g6QA6g7BSAAQBTAAA6A7QA7A6AABSQAABTg7A6Qg6A7hTAAQhSAAg6g7g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.btn_round, new cjs.Rectangle(-20,-20,40,40), null);


(lib.btn_bg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#35303E").s().p("AlYDIQhSAAg6g6Qg7g5AAhTIAAgCQAAhSA7g6QA6g7BSAAIKxAAQBTAAA6A7QA6A6AABSIAAACQAABSg6A6Qg6A6hTAAg");
	this.shape.setTransform(-0.3,0);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.btn_bg, new cjs.Rectangle(-54.7,-20,108.8,40), null);


(lib.bg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00D1D2").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.bg, new cjs.Rectangle(-150,-300,300,600), null);


(lib.btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_4
	this.instance = new lib.btn_txt();
	this.instance.parent = this;
	this.instance.setTransform(0,8.9);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(12).to({_off:false},0).to({y:0.7,alpha:1},8).wait(1));

	// r_part
	this.instance_1 = new lib.r_part();
	this.instance_1.parent = this;
	this.instance_1.setTransform(10.1,0);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(9).to({_off:false},0).to({x:44.2},8,cjs.Ease.get(1)).to({_off:true},1).wait(3));

	// l_part
	this.instance_2 = new lib.l_part();
	this.instance_2.parent = this;
	this.instance_2.setTransform(-10,0);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(9).to({_off:false},0).to({x:-44.8},8,cjs.Ease.get(1)).to({_off:true},1).wait(3));

	// Слой_5
	this.instance_3 = new lib.btn_bg();
	this.instance_3.parent = this;
	this.instance_3.setTransform(0,0,0.01,1);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(9).to({_off:false},0).to({scaleX:1},8,cjs.Ease.get(1)).wait(4));

	// Слой_1
	this.instance_4 = new lib.btn_round();
	this.instance_4.parent = this;
	this.instance_4.setTransform(0,0,0.012,0.012);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({scaleX:1.2,scaleY:1.2},5,cjs.Ease.get(1)).to({scaleX:1,scaleY:1},4,cjs.Ease.quadInOut).to({_off:true},9).wait(3));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-0.2,-0.2,0.5,0.5);


(lib.banner_g = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_89 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(89).call(this.frame_89).wait(1));

	// btn
	this.instance = new lib.btn("synched",0,false);
	this.instance.parent = this;
	this.instance.setTransform(71.9,-160.5,0.9,0.9,0,0,0,-0.6,0.6);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(35).to({_off:false},0).wait(55));

	// t2
	this.instance_1 = new lib.t2();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-7.7,-161,1.604,1.604,0,0,0,-0.3,-0.4);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(25).to({_off:false},0).to({regX:-0.2,x:-55.7,alpha:1},10,cjs.Ease.cubicOut).wait(55));

	// ic
	this.instance_2 = new lib.ic("synched",0,false);
	this.instance_2.parent = this;
	this.instance_2.setTransform(49.8,-222.6,1.066,1.066,0,0,0,-0.1,-0.7);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(25).to({_off:false},0).wait(65));

	// t1
	this.instance_3 = new lib.t1();
	this.instance_3.parent = this;
	this.instance_3.setTransform(15.6,-235.2,1.3,1.3,0,0,0,-0.1,-0.1);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(15).to({_off:false},0).to({x:-23.4,alpha:1},10,cjs.Ease.cubicOut).wait(65));

	// urText
	this.instance_4 = new lib.urText();
	this.instance_4.parent = this;
	this.instance_4.setTransform(-48.9,247.1,1,1,0,0,0,-0.1,0.2);
	this.instance_4.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({alpha:1},15).wait(75));

	// logo
	this.instance_5 = new lib.iqos_logo();
	this.instance_5.parent = this;
	this.instance_5.setTransform(91.9,246.9,0.669,0.669,0,0,0,0.6,1.2);
	this.instance_5.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).to({alpha:1},15).wait(75));

	// dev
	this.instance_6 = new lib.dev_1("single",0);
	this.instance_6.parent = this;
	this.instance_6.setTransform(234.4,109.5,1,1,0,0,0,0.5,0.5);
	this.instance_6.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).to({x:1,alpha:1},15,cjs.Ease.cubicOut).wait(44).to({x:0.5,mode:"synched",loop:false},0).wait(31));

	// bg
	this.instance_7 = new lib.bg();
	this.instance_7.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(90));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,-300,504.9,600.1);


// stage content:
(lib._300x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// cover
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#666666").ss(2,2,0,3).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// banner
	this.instance = new lib.banner_g();
	this.instance.parent = this;
	this.instance.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(149,299,505.9,602);
// library properties:
lib.properties = {
	id: '0A6E3F5DF6B342F4AF907DBE848CDF8D',
	width: 300,
	height: 600,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/dev.png", id:"dev"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['0A6E3F5DF6B342F4AF907DBE848CDF8D'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;