(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.dev_1 = function() {
	this.initialize(img.dev_1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,142,144);


(lib.dev_2 = function() {
	this.initialize(img.dev_2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,208,304);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.urText = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#1B1C1F").s().p("AriBhIAAhFIAHAAIAAAKQAHgKAMAAQAMAAAGAHQAIAHAAALQAAAMgIAHQgGAHgMAAQgMAAgHgKIAAAcgArVAnQgFAGgBAIQABAJAFAFQAFAGAIAAQAIAAAGgGQAFgFAAgJQAAgIgFgGQgGgFgIAAQgIAAgFAFgAx5BhIAAhFIAHAAIAAAKQAFgKAOAAQALAAAHAHQAHAHAAALQAAAMgHAHQgHAHgLAAQgNAAgGgKIAAAcgAxtAnQgFAGAAAIQAAAJAFAFQAFAGAIAAQAJAAAFgGQAFgFAAgJQAAgIgFgGQgFgFgJAAQgIAAgFAFgAFBBbIAAgNIgtAAIAAANIgGAAIAAgTIADAAQAFAAACgJQABgFACgNIAAgRIAlAAIAAAsIAIAAIAAATgAEhAtQgCAXgFAEIAfAAIAAgmIgYAAgAzIBbIAAgNIguAAIAAANIgFAAIAAgTIACAAQAJAAAAgbIABgRIAlAAIAAAsIAIAAIAAATgAzpAtQgBAXgGAEIAfAAIAAgmIgXAAgAMUBOIABgGIACABQAJAAABgbIABgSIAlAAIAAAyIgHAAIAAgsIgYAAIgBAMQgBAhgNAAgAFKBOIABgGIADABQAFAAACgJIADgSIAAgSIAlAAIAAAyIgHAAIAAgsIgYAAIgBAMQgBAQgCAIQgDAJgHAAgAgEBOIAAgGIADABQAHAAABgbIABgSIAmAAIAAAyIgHAAIAAgsIgZAAIAAAMQgBAhgNAAgAUhBKQABgGAEAAQAGAAAAAGQAAAFgGAAQgEAAgBgFgATtBGQgHgJAAgPQAAgfAagGIAWgFIABAGIgVAFQgVAFAAAWQAGgNAPAAQALAAAGAHQAHAHAAALQgBALgGAHQgHAHgLAAQgNAAgHgJgATzAoQgFAGAAAIQAAAIAFAGQAGAFAIAAQAHAAAGgFQAFgFAAgJQAAgIgFgGQgFgFgIAAQgJAAgFAFgASaBIQgIgIABgLQgBgLAIgHQAHgHALAAQAOAAAGAKIgFADQgFgHgKAAQgIAAgFAFQgGAFAAAJQAAAJAGAGQAFAFAIAAQAKAAAFgIIAFAEQgGAKgOAAQgLAAgHgHgARdBIQgHgIAAgLQAAgLAHgHQAHgHALAAQALAAAIAHQAGAHAAALQAAAMgGAHQgIAHgLAAQgLAAgHgHgARiAnQgGAFABAJQgBAJAGAFQAFAGAIAAQAIAAAFgGQAFgFABgJQgBgJgFgFQgEgFgJAAQgIAAgFAFgALjBIQgHgIAAgLQAAgLAHgHQAHgHAMAAQAKAAAIAHQAHAHAAALQAAALgHAIQgIAHgKAAQgMAAgHgHgALoAnQgGAFABAJQgBAJAGAFQAFAGAJAAQAHAAAFgGQAGgFAAgJQAAgJgGgFQgFgFgHAAQgJAAgFAFgAIsBIQgHgIAAgLQAAgLAHgHQAIgHAKAAQAMAAAHAHQAHAHAAALQAAAMgHAHQgHAHgMAAQgKAAgIgHgAIxAnQgFAFgBAJQABAJAFAFQAGAGAHAAQAIAAAGgGQAFgFAAgJQAAgJgFgFQgGgFgIAAQgHAAgGAFgABBBOIAAgyIAHAAIAAASIAOAAQAUAAAAAQQAAARgUAAgABIBJIANAAQAOAAAAgLQAAgKgOgBIgNAAgAlxBIQgIgHABgMQAAgLAGgHQAIgHAKAAQALAAAGAHQAIAHgBALIAAACIgqAAQABAIAFAFQAFAFAJAAQALAAAEgHIAFAFQgHAIgNAAQgMAAgHgHgAlOAyQAAgHgFgFQgGgFgHAAQgHAAgFAFQgFAFgBAHIAkAAIAAAAgAntBLQgFgEAAgHQAAgOATAAIAQAAIAAgDQAAgNgOAAQgLAAgFAGIgEgGQAJgGAMAAQAVAAAAATIAAAfIgHAAIAAgHQgGAIgMAAQgIAAgFgEgAnrBAQgBAKANAAQANAAADgLIAAgIIgQAAQgNAAABAJgApkBJIACgFQAIAFAKAAQAGAAAFgCQAFgDgBgFQAAgIgNAAIgJAAIAAgFIAJAAQAMAAAAgIQAAgJgOAAQgIAAgIAEIgCgFQAJgFAKAAQAIAAAGAEQAGAEAAAGQAAAIgKADQALADAAAJQAAAHgGAEQgHAEgJAAQgNAAgHgGgAtrBKQAAgGAGAAQAEAAAAAGQAAAFgEAAQgGAAAAgFgAwwBIQgHgIAAgLQAAgLAHgHQAIgHALAAQALAAAHAHQAHAHAAALQAAALgHAIQgHAHgLAAQgLAAgIgHgAwqAnQgGAFAAAJQAAAJAGAFQAEAGAJAAQAIAAAFgGQAGgFgBgJQABgJgGgFQgFgFgIAAQgJAAgEAFgAyzBIQgIgIAAgLQAAgLAIgHQAGgHAMAAQALAAAHAHQAIAHAAALQAAALgIAIQgHAHgLAAQgMAAgGgHgAyvAnQgFAFAAAJQAAAJAFAFQAGAGAIAAQAIAAAFgGQAFgFABgJQgBgJgFgFQgFgFgIAAQgIAAgGAFgA0tBJIACgFQAIAFAKAAQAHAAAFgCQAEgDAAgFQAAgIgNAAIgJAAIAAgFIAIAAQAMAAAAgIQAAgJgOAAQgIAAgHAEIgDgFQAJgFAKAAQAJAAAFAEQAHAEAAAGQgBAIgJADQALADAAAJQAAAHgHAEQgGAEgKAAQgMAAgIgGgATKBOIAAgyIAHAAIAAAygAQoBOIgQgVIgQAVIgIAAIAUgZIgTgZIAHAAIAQAUIAPgUIAHAAIgTAZIAVAZgAPqBOIAAgyIAGAAIAAAygAPTBOIAAgWIggAAIAAAWIgHAAIAAgyIAHAAIAAAWIAgAAIAAgWIAHAAIAAAygAODBOIAAgsIgTAAIAAgGIAtAAIAAAGIgTAAIAAAsgANbBOIAAgyIAHAAIAAAygALKBOIAAgWIggAAIAAAWIgGAAIAAgyIAGAAIAAAWIAgAAIAAgWIAHAAIAAAygAJnBOIAAgyIAWAAQASAAAAANQABAIgJADQAKACAAALQAAANgUAAgAJuBJIAPAAQANAAABgJQAAgIgNAAIgQAAgAJuAyIAOAAQANAAAAgIQAAgJgNAAIgOAAgAITBOIAAgsIgfAAIAAAsIgHAAIAAgyIAtAAIAAAygAGyBOIAAgQIgSAAIgMAQIgHAAIAMgRQgMgDAAgNQAAgRAVAAIAVAAIAAAygAGUAtQAAAMAOAAIAQAAIAAgXIgQAAQgOAAAAALgADZBOIAAgoIgiAoIgGAAIAAgyIAHAAIAAAoIAigoIAFAAIAAAygACZBOIgTgWIgLAAIAAAWIgHAAIAAgyIAHAAIAAAWIALAAIASgWIAHAAIgUAYIAWAagAgaBOIAAgyIAHAAIAAAygAhDBOIAAgsIgTAAIAAgGIAtAAIAAAGIgTAAIAAAsgAiLBOIAAgoIgiAoIgFAAIAAgyIAGAAIAAAoIAhgoIAHAAIAAAygAjSBOIAAgoIgiAoIgFAAIAAgyIAGAAIAAAoIAigoIAGAAIAAAygAkQBOIAAgWIggAAIAAAWIgGAAIAAgyIAGAAIAAAWIAgAAIAAgWIAHAAIAAAygAmRBOIAAgVQgKAEgHAAQgUAAABgQIAAgRIAGAAIAAAQQAAAMAOAAQAGAAAKgEIAAgYIAHAAIAAAygAoEBOIAAgWIgfAAIAAAWIgHAAIAAgyIAHAAIAAAWIAfAAIAAgWIAHAAIAAAygApyBOIAAgoIgiAoIgHAAIAAgyIAHAAIAAAoIAigoIAGAAIAAAygAr/BOIAAg9IgrAAIAAA9IgGAAIAAhDIA4AAIAABDgAuCBOIAAgQIgSAAIgMAQIgIAAIANgRQgMgDAAgNQAAgRAWAAIAUAAIAAAygAugAtQAAAMAOAAIAQAAIAAgXIgPAAQgPAAAAALgAv1BOIAAgyIAWAAQASAAAAANQABAIgJADQALADAAAKQgBANgTAAgAvuBJIAPAAQANAAABgJQAAgIgNAAIgQAAgAvuAyIAOAAQANAAAAgIQAAgJgNAAIgOAAgAu9AfIAEgOQgDgBgBgEQAAgFAGAAQAEAAAAAFIgBAFIgEAOgAiqAIIAFAAQAAAJAJAAQAJAAAAgJIAGAAQAAANgPAAQgOAAAAgNgATJAMQAAgFAEAAQAFAAABAFQgBAFgFAAQgEAAAAgFgAPoAMQAAgFAFAAQAFAAAAAFQAAAFgFAAQgFAAAAgFgANZAMQAAgFAFAAQAFAAAAAFQAAAFgFAAQgFAAAAgFgAgcAMQABgFAFAAQAEAAAAAFQAAAFgEAAQgFAAgBgFgAJIgKIADgFQADADAGAAQAHAAAEgIIACgFIgXgyIAHAAIAUArIATgrIAGAAIgZA4QgGANgLAAQgHAAgFgEgAL3gGIAAhFIAHAAIAAAKQAGgLANAAQALAAAHAHQAHAIAAALQAAALgHAIQgHAHgLAAQgNAAgGgKIAAAcgAMDhAQgGAFABAJQgBAJAGAFQAFAGAJAAQAHAAAGgGQAFgFABgJQgBgJgFgFQgGgGgHAAQgJAAgFAGgAw8gGIAAhFIAHAAIAAAKQAHgLANAAQAKAAAIAHQAGAIABALQgBALgGAIQgIAHgKAAQgOAAgFgKIAAAcgAwwhAQgFAFAAAJQAAAJAFAFQAGAGAIAAQAIAAAFgGQAFgFABgJQgBgJgFgFQgFgGgIAAQgIAAgGAGgATDgNIAAgMIgtAAIAAAMIgHAAIAAgSIADAAQAIAAABgbIABgRIAlAAIAAAsIAIAAIAAASgAShg6QgBAXgFAEIAfAAIAAgmIgYAAgATMgZIAAgGIACABQAJAAABgbIABgSIAlAAIAAAyIgHAAIAAgsIgYAAIgBAMQgBAhgNAAgAN0geIADgFQAGAFALAAQAQAAAAgKQAAgIgOAAIgJAAIAAgFIAIAAQANAAAAgIQAAgJgOAAQgJAAgHAEIgCgFQAKgFAJAAQAIAAAHAEQAFAEAAAGQAAAIgKADQALADAAAJQABAGgHAFQgGAEgKAAQgLAAgJgGgAKJgfQgIgIAAgLQAAgLAIgIQAGgHAMAAQAOAAAGAKIgFAEQgFgIgKAAQgJAAgFAGQgFAFAAAJQAAAJAFAFQAFAGAJAAQAKAAAFgIIAFAEQgGAKgOAAQgMAAgGgHgAIEggQgHgHgBgLQABgLAHgHQAIgIALAAQANAAAHAIIgDAEQgHgGgKAAQgIAAgGAFQgFAFgBAIIAbAAIAAAFIgbAAQABAIAFAFQAGAEAIAAQAKAAAHgGIADAEQgHAIgNAAQgLAAgIgIgAHFgcQgFgEAAgHQAAgOATAAIAQAAIAAgDQAAgOgOAAQgKAAgHAGIgDgFQAIgHANAAQAUAAAAAUIAAAfIgHAAIAAgIQgEAJgNAAQgIAAgFgEgAHHgnQgBAJANAAQAMAAAEgKIAAgIIgQAAQgNAAABAJgAFRgfQgIgGgBgKIgLAAIAAAWIgHAAIAAgyIAHAAIAAAWIAMAAQABgKAHgHQAHgGAKAAQAKAAAIAHQAGAIABALQgBALgGAHQgIAIgKAAQgLAAgGgHgAFUhAQgEAFAAAJQAAAJAEAFQAGAGAIAAQAHAAAFgGQAGgFAAgJQAAgJgGgFQgFgGgHAAQgIAAgGAGgADwgZIAAgGIADABQAFAAADgJIACgSIABgSIAlAAIAAAyIgHAAIAAgsIgZAAIAAAMQgBAQgCAHQgDAKgIAAgAggggQgHgHgBgLQAAgLAIgHQAGgIAMAAQAKAAAGAHQAHAIAAALIgBACIgoAAQABAIAFAFQAFAFAIAAQAKAAAFgHIADAEQgFAJgNAAQgLAAgIgIgAADg1QgBgHgFgFQgFgFgGAAQgIAAgFAFQgEAFgBAHIAjAAIAAAAgAl3giQgKgKAAgOQAAgPAKgKQAKgJAQAAQAPAAAJAJQAKAKAAAPQAAAOgKAKQgJAKgPAAQgQAAgKgKgAlyhOQgIAIAAAMQAAAMAIAIQAIAHANAAQALAAAJgHQAHgIABgMQgBgMgHgIQgJgIgLAAQgNAAgIAIgAm+ghIACgFQAKAIANAAQASAAAAgMQgBgJgUgFQgVgFAAgNQAAgIAHgFQAGgFAMAAQANAAAIAGIgCAFQgJgFgKAAQgRAAAAAMQgBAIAVAGQAUAFAAANQAAAHgFAFQgHAGgMAAQgRAAgIgJgAtHgcQgFgEAAgHQAAgOATAAIAQAAIAAgDQAAgOgOAAQgJAAgIAGIgDgFQAIgHAMAAQAVAAAAAUIAAAfIgGAAIAAgIQgFAJgNAAQgIAAgFgEgAtGgnQAAAJANAAQAMAAAEgKIAAgIIgPAAQgOAAAAAJgAurgfQgIgIAAgLQAAgLAIgIQAHgHALAAQAOAAAGAKIgFAEQgFgIgKAAQgIAAgFAGQgFAFgBAJQABAJAFAFQAFAGAIAAQAKAAAFgIIAFAEQgGAKgOAAQgLAAgHgHgAx2ggQgIgHABgLQgBgLAIgHQAIgIALAAQAKAAAIAIQAHAHAAALQAAALgHAHQgIAIgKAAQgLAAgIgIgAxxhAQgGAFAAAJQAAAJAGAFQAFAGAJAAQAIAAAEgGQAGgFAAgJQAAgJgGgFQgEgGgIAAQgJAAgFAGgAUygZIAAgQIgSAAIgLAQIgIAAIANgRQgNgDAAgNQABgRAVAAIAVAAIAAAygAUVg6QgBALAPAAIAPAAIAAgWIgOAAQgPAAAAALgARZgZIAAgoIghAoIgGAAIAAgyIAHAAIAAAoIAhgoIAGAAIAAAygAQZgZIgSgWIgLAAIAAAWIgHAAIAAgyIAHAAIAAAWIALAAIASgWIAIAAIgUAYIAVAagAPWgZIAAgoIgiAoIgGAAIAAgyIAHAAIAAAoIAigoIAFAAIAAAygANlgZIAAgoIghAoIgGAAIAAgyIAHAAIAAAoIAhgoIAHAAIAAAygAK5gZIAAgyIAHAAIAAAygAGmgZIAAgVQgIAEgIAAQgUAAAAgRIAAgQIAHAAIAAAQQAAAMAOAAQAHAAAIgEIAAgYIAHAAIAAAygADigZIgTgWIgMAAIAAAWIgHAAIAAgyIAHAAIAAAWIAMAAIARgWIAIAAIgUAYIAVAagACdgZIAAgoIgiAoIgFAAIAAgyIAGAAIAAAoIAigoIAGAAIAAAygAA5gZIAAgyIAWAAQASAAAAANQAAAIgJADQALADAAAKQAAANgUAAgAA/geIAQAAQANAAAAgJQAAgJgMAAIgRAAgAA/g1IAPAAQANAAAAgIQAAgJgNAAIgPAAgAg5gZIAAgWIgfAAIAAAWIgHAAIAAgyIAHAAIAAAWIAfAAIAAgWIAHAAIAAAygAjOgZIAAhDIAcAAQAQAAAJAKQAKAJAAAPQAAAPgKAJQgJAJgQAAgAjHgfIAUAAQANAAAIgHQAIgIAAgMQAAgMgIgIQgIgIgNAAIgUAAgAjtgZIAAhDIAHAAIAABDgAkqgZIAAhDIAHAAIAAA9IAlAAIAAAGgAn3gZIAAhHIAGAAIAABHgAoWgZIAAgyIAHAAIAAAygAo1gZIAAhHIAGAAIAABHgApxgZIAAgQIgRAAIgMAQIgHAAIAMgRQgMgDAAgNQAAgRAVAAIAWAAIAAAygAqOg6QAAALAOAAIAPAAIAAgWIgOAAQgPAAAAALgAqngZIAAgWIggAAIAAAWIgHAAIAAgyIAHAAIAAAWIAgAAIAAgWIAHAAIAAAygArkgZIAAgWIggAAIAAAWIgHAAIAAgyIAHAAIAAAWIAgAAIAAgWIAHAAIAAAygAtxgZIAAgsIgTAAIAAgGIAtAAIAAAGIgUAAIAAAsgAvNgZIAAgoIghAoIgGAAIAAgyIAGAAIAAAoIAigoIAGAAIAAAygAyGgZIgTgWIgMAAIAAAWIgGAAIAAgyIAGAAIAAAWIAMAAIASgWIAHAAIgUAYIAWAagAzLgZIAAgoIgiAoIgFAAIAAgyIAGAAIAAAoIAigoIAGAAIAAAygA04gZIAAhDIAcAAQAXAAAAARQAAAMgLAEQAOADAAANQABASgZAAgA0xgeIAXAAQARAAAAgNQAAgNgRAAIgXAAgA0xg9IAVAAQAQAAAAgNQAAgMgQAAIgVAAgAK4hbQAAgFAEAAQAGAAAAAFQAAAFgGAAQgEAAAAgFgAoXhbQAAgFAEAAQAGAAgBAFQABAFgGAAQgEAAAAgFg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.urText, new cjs.Rectangle(-133.6,-9.7,267.3,19.4), null);


(lib.t1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#191919").s().p("AHaDmQgagZAAgmQAAgmAagaQAbgZAnAAQAoAAAaAZQAaAZAAAnQAAAmgaAZQgaAagoAAQgnAAgbgagAHnBzQgVAUAAAgQAAAfAVAVQAVAVAggBQAgABAUgVQAVgVAAgfQAAgggVgUQgUgVggAAQggAAgVAVgACLDmQgagZAAgmQAAgmAagaQAagZAoAAQAoAAAaAZQAZAZAAAnQAAAmgZAZQgaAagoAAQgoAAgagagACYBzQgVAUAAAgQAAAfAVAVQAVAVAggBQAgABAUgVQAVgVAAgfQAAgggVgUQgUgVggAAQggAAgVAVgAqMDpIAIgNQAWAUAhAAQAWAAAPgKQAQgKAAgRQgBgQgMgIQgLgIgWAAIglAAIAAgPIAkAAQASAAALgIQAKgHAAgOQAAgQgOgJQgNgJgTAAQgbAAgXAOIgGgOQAagQAeAAQAcAAASAMQASAOAAAVQAAAdgdAKQASAEAJALQAKALAAAQQAAAXgVAOQgTANgdABQgmAAgbgXgAFUD/IAAiwIBwAAIAAAQIheAAIABCggAg/D/IAAiwIBHAAQAdAAAPAMQAQALAAAWQAAAdgcALQAlAHAAAkQgBAwg/AAgAgtDvIA6AAQAuAAgBghQABghguAAIg6AAgAgtCeIA0AAQAqAAAAgfQABgQgLgIQgLgJgVAAIg0AAgAiTD+IAAiQIhwCQIgQAAIAAivIASAAIAACRIBviRIARAAIAACvgAlQD+IgUguIhiAAIgUAuIgUAAIBQivIASAAIBQCvgAlrDBIgqhfIgqBfIBUAAgAjoA6QgMgJAAgPIAOAAQAAALAIAFQAHAGAMAAQAMAAAHgGQAIgFAAgLIAOAAQAAAPgMAJQgKAJgTAAQgTAAgKgJgAOphmQgagZAAgnQAAgmAagZQAagZAogBQAnAAAaAaQAaAZAAAmQAAAngaAZQgaAZgnABQgogBgagZgAO1jaQgVAVABAfQgBAfAVAWQAWAUAgAAQAfAAAVgUQAVgWgBgfQABgfgVgVQgVgUgfAAQggAAgWAUgAJZhmQgagZAAgnQAAgmAagZQAbgZAogBQAnAAAaAaQAaAZAAAmQAAAngaAZQgaAZgnABQgogBgbgZgAJnjaQgWAVAAAfQAAAfAWAWQAUAUAhAAQAfAAAVgUQAVgWAAgfQAAgfgVgVQgVgUgfAAQghAAgUAUgAiWhmQgagZAAgnQAAgmAagZQAbgZAngBQAnAAAaAaQAZAZAAAmQAAAngZAZQgaAZgnABQgngBgbgZgAiJjaQgVAVAAAfQAAAfAVAWQAVAUAgAAQAfAAAWgUQAUgWAAgfQAAgfgUgVQgWgUgfAAQggAAgVAUgAnahmQgagZAAgnQAAgmAagZQAagaAnAAQApABAXAZIgMALQgUgUggAAQgfAAgWAUQgUAWAAAeQAAAfAUAWQAWAUAfAAQAgAAAUgVIAMALQgXAbgpAAQgogBgZgZgAqwhmQgagZAAgnQAAgmAagZQAbgZAngBQAoAAAaAaQAaAZAAAmQAAAngaAZQgaAZgoABQgngBgbgZgAqjjaQgUAVgBAfQABAfAUAWQAWAUAfAAQAgAAAVgUQAUgWAAgfQAAgfgUgVQgVgUggAAQgfAAgWAUgAMjhOIAAivIBvAAIAAAQIhdAAIABCfgAIChOIAAhIQgdAMgbgBQgeAAgSgPQgQgOgBgbIAAg6IATAAIAAA3QAAAVANALQAMAMAXgBQAZAAAdgMIAAhWIASAAIAACvgAFQhOIAAivIASAAIAACvgAD7hOIAAhRIhuAAIAABRIgSAAIAAivIASAAIAABOIBuAAIAAhOIASAAIAACvgAkMhOIAAifIg+AAIAAgQICNAAIAAAQIg9AAIAACfgAtxhOIAAivIBCAAQAhAAATAQQATAQAAAcQAAAcgTAQQgTAQghAAIgvAAIAAA3gAteiVIAuAAQAaAAAOgMQAOgLAAgVQAAgVgOgMQgOgLgaAAIguAAgAvFhOIAAifIhuAAIAACfIgSAAIAAivICTAAIAACvg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1, new cjs.Rectangle(-109.4,-25.5,218.8,51.1), null);


(lib.lil_logo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#191919").s().p("AAMHTQgEAAgDgDQgCgDAAgEIAAh1QAAgEACgDQADgDAEAAQAFAAADADQACADAAAEIAABrIBEAAQAEAAADADQACADAAAEQAAAEgCADQgDADgEAAgAkFHKQgNgIgEgNQgCgEACgEQACgEAEgBQAEgCADACQAEACACAEQACAHAIAFQAHAFAKAAQAMAAAIgHQAIgGAAgKQAAgGgDgEQgHgIgSgCQgTgCgLgKQgMgLAAgPQAAgPANgLQAMgKARAAQANAAALAHQALAHAEALQACAEgCADQgCAEgEACQgEABgDgCQgEgCgCgDQgCgGgFgDQgGgDgHAAQgJAAgGAEQgGAFAAAHQAAAHAGAFQAGAFALABQAbADALAOQAIAJABAOQAAASgPAMQgOANgUAAQgQAAgNgJgAC4HSQgEAAgDgDQgDgCAAgFIAAh0QAAgEADgDQADgDAEAAIAcAAQAcAAAUAUQAUAUAAAcQAAAcgUAUQgUAUgcAAgADCG+IASAAQAUAAAOgOQAOgOAAgUQAAgUgOgOQgOgOgUAAIgSAAgACAHPQgDgCAAgFIAAh0QAAgEADgDQADgDAEAAQAEAAADADQADADAAAEIAAB0QAAAFgDACQgDADgEAAQgEAAgDgDgAiLG+QgUgUAAgcQAAgcAUgUQAUgUAcAAQAcAAAUAUQAVAUAAAcQAAAcgUAUQgUAUgdAAQgcAAgUgUgAh9FsQgOAOAAAUQAAAUAOAOQAOAOAUAAQAUAAAOgOQAPgOAAgUQAAgUgOgOQgPgPgUAAQgUAAgOAPgACxDjQgPgPAAgVIAApeQAAgVAPgPQAPgPAVAAQAVAAAOAPQAPAPAAAVIAAJeQAAAVgPAPQgOAPgVAAQgVAAgPgPgAgiDjQgPgPAAgVIAAmUQAAgVAPgPQAOgOAUAAQAVAAAPAOQAPAPAAAVIAAGUQAAAVgPAPQgPAPgVAAQgUAAgOgPgAj3DjQgPgPAAgVIAApeQAAgVAPgPQAPgPAVAAQAVAAAOAPQAPAPAAAVIAAJeQAAAVgPAPQgOAPgVAAQgVAAgPgPgAgmlFQgQgRAAgXQAAgXAQgQQAQgQAWAAQAXAAARAQQAQAQAAAXQAAAXgQARQgRAQgXAAQgWAAgQgQg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.lil_logo, new cjs.Rectangle(-28,-46.6,56,93.4), null);


(lib.iqos_logo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#101113").s().p("Ah5DdIgmgmIh7AAQgeAAgSgEQgZgGgPgOQgUgTAAglIAAhqQAAgGAFgFQAFgEAHAAICJAAQAdAAAUAEQAYAGAPANQAUATAAAlIAABqIAfAfQAEAEgBAGQAAAGgFAGQgGAFgGAAQgGAAgEgEgAljBoQAAAZANAMIACADQANAJAbABICJAAIAAhdQAAgZgNgNIgCgCQgNgKgcgBIiIAAgAnaCxQgFgFAAgHIAAioQAAgIAFgEQAEgFAIAAQAIAAAEAFQAEAEABAIIAACoQgBAHgEAFQgEAEgIAAQgIAAgEgEgAEvC1QgmgCgRgKQgOgJgDgQIAAgDQABgGAFgEQADgEAIAAQAGAAAFADQAEADACAFIAAACQAFAHAIADQAIACAPAAIBKAAQApAAAMgGQAKgFAAgSIAAgCQAAgOgHgGQgIgHgcAAIhjAAQghAAgPgMQgPgMAAgcIAAgLQABgaASgJQAWgOA5AAIAxAAQAtAAAUALQAPAIADARIAAADQgBAGgEAEQgEADgIAAQgGAAgEgDQgFgCgCgFIgBgCQgEgJgNgCQgJgCgYAAIg4AAQgiAAgLAFQgKAEAAAQIAAAIQAAAMAHAFQAIAHAXAAIBVAAQAqAAAQAIQAYANAAAkIAAABQAAAlgfANQgSAHgoAAgAAdC1QgwAAgZgOQgigSAAgwIAAgqQAAgwAigRQAZgOAwAAIAuAAQAyAAAYAOQAhARABAwIAAAqQAAAwgjASQgYAOgxAAgAgaASQgRAMAAAfIAAAnQAAAeARANQAOAKAfAAIBCAAQAfAAAPgKQARgNAAgeIAAgnQAAgfgRgMQgPgKgfAAIhCAAQgfAAgOAKgABEikQgKgKAAgPQAAgPAKgKQALgKAQAAQAKAAAIAEQAIAFAEAIIgKAHQgIgLgMAAQgKAAgGAGQgHAGABAKQgBAKAHAGQAGAGAKAAQAMAAAIgLIAKAHQgEAIgIAEQgJAFgJAAQgQAAgLgKgAgOiiQgJgIABgNIAAgoIANAAIAAApQAAAHAFAEQAEAEAFAAQAIAAADgEQAFgEAAgHIAAgpIAOAAIAAAoQAAANgJAIQgHAIgOAAQgMAAgHgIgAjBikQgLgKABgPQgBgPALgKQALgKAQAAQAPAAALAKQALAKgBAPQABAPgLAKQgLAKgPAAQgQAAgLgKgAi3jNQgFAGgBAKQAAAJAGAHQAHAGAKAAQAJAAAHgGQAFgHAAgJQAAgKgFgGQgHgGgJAAQgKAAgHAGgAl8iaIgogqIAAApIgPAAIAAhFIAGAAIAnApIAAgoIAPAAIAABFgAG6ibIAAgbIgYgpIAQAAIAPAbIAPgbIAQAAIgYApIAAAbgAFhibIAAhEIAYAAQALAAAFAFQAHAGAAAIQAAAHgGAFQANAFAAAMQgBAJgGAFQgGAGgKAAgAFvinIAQAAQAEAAADgCQADgDgBgEQABgEgDgCQgDgCgEAAIgQAAgAFvjEIAJAAQAFAAACgCQACgCAAgDQAAgEgCgCQgCgCgFAAIgJAAgADcibIAAhEIAXAAQAQAAALAJQALAKAAAPQAAAPgLAJQgLAKgQAAgADrioIAIAAQALAAAFgGQAHgGAAgJQAAgKgHgGQgFgGgLAAIgIAAgACUibIAAhEIAuAAIAAANIgfAAIAAANIAXAAIAAAMIgYAAIAAARIAiAAIAAANgAhqibIAAhEIAWAAQARAAALAJQAKAKAAAPQAAAPgKAJQgLAKgRAAgAhcioIAIAAQALAAAGgGQAHgGAAgJQAAgKgHgGQgGgGgLAAIgIAAgAlNibIAAg3IgWAAIAAgNIA6AAIAAANIgWAAIAAA3gAnbibIAAhEIANAAIAABEgAjqicIgSgXIgLAAIAAAXIgNAAIAAhDIAaAAQAKAAAIAGQAGAGAAAKQABAGgEAFQgDAFgGADIAUAagAkHi/IANAAQAEAAADgDQADgDAAgEQAAgFgDgCQgDgDgEAAIgNAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.iqos_logo, new cjs.Rectangle(-48,-22.5,96,45.1), null);


(lib.dev_2_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.dev_2();
	this.instance.parent = this;
	this.instance.setTransform(-104,-152);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.dev_2_1, new cjs.Rectangle(-104,-152,208,304), null);


(lib.dev_1_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.dev_1();
	this.instance.parent = this;
	this.instance.setTransform(-71,-72);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.dev_1_1, new cjs.Rectangle(-71,-72,142,144), null);


(lib.bg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#DBE1E7").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.bg, new cjs.Rectangle(-150,-300,300,600), null);


(lib.banner = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// t1
	this.instance = new lib.t1();
	this.instance.parent = this;
	this.instance.setTransform(0,-108.5);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(59).to({_off:false},0).to({alpha:1},10).wait(49).to({alpha:0},10).to({_off:true},1).wait(15));

	// dev_2
	this.instance_1 = new lib.dev_2_1();
	this.instance_1.parent = this;
	this.instance_1.setTransform(256,69);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(34).to({_off:false},0).to({x:46},15,cjs.Ease.get(1)).wait(69).to({x:256},15,cjs.Ease.get(-1)).to({_off:true},1).wait(10));

	// dev_1
	this.instance_2 = new lib.dev_1_1();
	this.instance_2.parent = this;
	this.instance_2.setTransform(-221,89);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(34).to({_off:false},0).to({x:-61},15,cjs.Ease.get(1)).wait(69).to({x:-221},15,cjs.Ease.get(-1)).to({_off:true},1).wait(10));

	// lil_logo
	this.instance_3 = new lib.lil_logo();
	this.instance_3.parent = this;
	this.instance_3.setTransform(1,-60);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(24).to({y:-212},15,cjs.Ease.quadInOut).wait(89).to({y:-60},15,cjs.Ease.quadInOut).wait(1));

	// iqos_logo
	this.instance_4 = new lib.iqos_logo();
	this.instance_4.parent = this;
	this.instance_4.setTransform(-1,52);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(24).to({y:217},15,cjs.Ease.quadInOut).wait(89).to({y:52},15,cjs.Ease.quadInOut).wait(1));

	// urText
	this.instance_5 = new lib.urText();
	this.instance_5.parent = this;
	this.instance_5.setTransform(0,273.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(144));

	// bg
	this.instance_6 = new lib.bg();
	this.instance_6.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(144));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,-300,300,600);


// stage content:
(lib._300x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// cover
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#666666").ss(2,1,1).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// banner
	this.instance = new lib.banner();
	this.instance.parent = this;
	this.instance.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(149,299,302,602);
// library properties:
lib.properties = {
	id: 'D78E0080C82B4A91A29A8C60B712AE41',
	width: 300,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/dev_1.png", id:"dev_1"},
		{src:"images/dev_2.png", id:"dev_2"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['D78E0080C82B4A91A29A8C60B712AE41'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;